- BUILD.md
A few minor formatting and clarification updates.
> docs:Update Build instructions

- layers/core_validation.cpp
- layers/object_tracker_utils.cpp
> layers: Fix debug-utils race hazards

- BUILD.md
Updated the MacOS section in BUILD.md
> docs: Update MacOS Build Documentation

- tests/vkrenderframework.cpp
- tests/vktestbinding.cpp
- tests/vktestbinding.h
IsEnbledExtension -> IsEnabledExtension
> tests: fix typo in function name

- layers/core_validation.cpp
- scripts/lvl_genvk.py
- tests/_vkvalidatelayerdoc.ps1
Update doc links to new repos.
Change-Id: I9e1764d616596bd7e14ac08ba7dbee72c5265099
> docs: Update links

- layers/core_validation.cpp
- tests/layer_validation_tests.cpp
Address #93
Add validation to vkCmdExecuteCommands s.t. the initial layout of the secondary command buffers is compared against the current layout of the parent command buffer.
Add new valid usage:
UNASSIGNED-vkCmdExecuteCommands-commandBuffer-00001
> Validate initial layout of secondary CBs

- layers/buffer_validation.cpp
- tests/layer_validation_tests.cpp
Addresses #78 
Validate a subset of internally inconsistent image memory barriers in a single barrier/event call. Duplicate image layout transistions for the same image and subresource range will generate errors.  Intersecting subresource ranges are not detected.  Duplicate transitions with oldLayout UNDEFINED are not invalid, and not flagged.
> Detect duplicate layout transitions in barrier

- CMakeLists.txt
- tests/CMakeLists.txt
Allows other repos to use layer validation tests
Change-Id: I24ddff6116b81edf165a49268d3da7e9bf966eab
> tests: Add option to install tests

- .travis.yml
Convert cmake command to use _INSTALL_DIR semantic for VulkanTools
Change-Id: I05a664e3b99ded6305e5325e5857c0b5ac4a9a0c
> build: Update travis VulkanTools cmake options

- CMakeLists.txt
- layers/CMakeLists.txt
It is sometimes useful to generate the layer support files without actually building the layers themselves.
Change-Id: I2fc75afc784376d11b5bc0100ef05a5bb2355b47
> Add option to generate layer files without building layers

- tests/layer_validation_tests.cpp
I was hitting undefined symbol build errors with my current combination of Loader/Header/Layers. Figured this may save someone else same issues.
> tests:Use GPA for GPDF2 function

- layers/core_validation.cpp
- layers/parameter_validation_utils.cpp
- tests/layer_validation_tests.cpp
Update changed and deprecated VUIDs found by vk_validation_stats consistency check.
> Remove/update deprecated VUIDs

- layers/unique_objects.cpp
- scripts/unique_objects_generator.py
Fixes #199 
Add support for debug callbacks in unique_objects layer.
> Tobin unsupported ext test

- scripts/vk_validation_stats.py
Improve the error text filtering to get rid of more &html;escape;&codes;.
Allow the vuid lookup to report implicit checks & line numbers.
> Tweak vk_validation_stats script

- scripts/helper_file_generator.py
While Android O does define AHardwareBuffer, it's still an abstract
object and the definition doesn't help the code here create an
AHardwareBuffer object.
Just keep the placeholder definition as that works fine.
Bug: 219
Change-Id: I9f3b7b3fd4d6fb63d05dceaa2edc283a59a89838
> Always use stand-in type for AHardwareBuffer

- .gitignore
- BUILD.md
- scripts/known_good.json
- scripts/update_deps.py
New Python script to build dependent repos using "known-good" commits.
> build: Add pgm to build dependent repos [skip ci]

- layers/core_validation.cpp
- tests/layer_validation_tests.cpp
Add VUIDs for validating a correct pipeline is bound to the command buffer at Draw/Dispatch submission time.
Applies to but does not fully resolve issue #135 .
> Validate pipeline is bound at Draw/Dispatch time

- layers/buffer_validation.cpp
- layers/core_validation.cpp
- layers/core_validation_types.h
- layers/descriptor_sets.cpp
- layers/descriptor_sets.h
- layers/shader_validation.cpp
- layers/shader_validation.h
- tests/layer_validation_tests.cpp
Existing non-conformant function names in the Core Validation layer were updated to comply with the style guide.
> Core Validation function name cleanup

- layers/core_validation.cpp
More work done towards converting Core Validation functions to a precall/postcall format.
Batch 1 of many.
> Update Core Validation functions to pre/postcall format

- layers/core_validation.cpp
More work done towards converting Core Validation functions to a precall/postcall format.
This PR addresses the rest of the DebugUtils functions and QueuePresentKHR()
Batch 2 of many.
> Update more Core Validation functions to pre/postcall format

- layers/core_validation.cpp
More work done towards converting Core Validation functions to a precall/postcall format.
This PR addresses functions with the word "Reset" in their name.
Batch 3 of many.
> Update even more Core Validation functions to pre/postcall format

- layers/core_validation.cpp
Unused variable warning introduced during core_validation precall/postcall function format conversion.
Changes made to CmdEndRenderPass and associated PreCall and PostCall
functions.
Change-Id: Ia1e632b134cdea62bd8d83239cd74ed1550538a4
> Bug fix for unused variable warning in core_validation

- .appveyor.yml
- scripts/update_deps.py
Also fix case sensitivity in update_deps.py
Change-Id: I0c2af8bf616a959d165594a652f7046903186e65
> build: Use update_deps.py in appveyor

- build-android/known_good.json
- layers/linux/VkLayer_core_validation.json
- layers/linux/VkLayer_object_tracker.json
- layers/linux/VkLayer_parameter_validation.json
- layers/linux/VkLayer_standard_validation.json
- layers/linux/VkLayer_threading.json
- layers/linux/VkLayer_unique_objects.json
- layers/macos/VkLayer_core_validation.json
- layers/macos/VkLayer_object_tracker.json
- layers/macos/VkLayer_parameter_validation.json
- layers/macos/VkLayer_standard_validation.json
- layers/macos/VkLayer_threading.json
- layers/macos/VkLayer_unique_objects.json
- layers/windows/VkLayer_core_validation.json
- layers/windows/VkLayer_object_tracker.json
- layers/windows/VkLayer_parameter_validation.json
- layers/windows/VkLayer_standard_validation.json
- layers/windows/VkLayer_threading.json
- layers/windows/VkLayer_unique_objects.json
- scripts/known_good.json
- scripts/parameter_validation_generator.py
- tests/layers/linux/VkLayer_device_profile_api.json
- tests/layers/windows/VkLayer_device_profile_api.json
Change-Id: Idcce85e420ce27eb2ab5040455096d338701a2ad
> Update known-good for 1.1.81 headers

- layers/shader_validation.cpp
> Fix various gaps in OpRuntimeArray support in SC

- layers/shader_validation.cpp
- tests/layer_validation_tests.cpp
Improve PointSize check to look specifically for a write to the PointSize variable by the appropriate shader stage.
> Improve PointSize shader-pipeline validation

- scripts/known_good.json
- scripts/update_deps.py
Updated update_deps.py with the following elements:
'build_platforms': Specifies what platforms a repo should be built on.
'custom_build': A list of build instructions to use instead of the
default CMake build sequence.
Added MoltenVK to known_good.json to build only on
MacOS.
> build: Add MoltenVK to known_good

- layers/CMakeLists.txt
This PR fixes the library_path entry of the installed layer json files by removing the "./" before installing to system directories.
> Update CMakeLists.txt to specify correct library path for installed layer json files

- layers/unique_objects.cpp
- scripts/unique_objects_generator.py
Adds CreateRenderPass2KHR to unique objects, mimicking the CreateRenderPass code
> layers: Add CreateRenderPass2KHR to unique objects

- build-android/known_good.json
- scripts/known_good.json
Update VVL known good for 1.1.84 header update.
> build: Update known-good for 1.1.84 Headers

- layers/core_validation.cpp
- tests/layer_validation_tests.cpp
Remove validation of feature bits at vkCreateDevice() time. The device is required to return a VK_ERROR_FEATURE_NOT_PRESENT result in this case, so the validation layer was adding no additional information. Also removed a related error that should instead be a warning in the assistant layer.
Resolves #335.
> Remove feature bit checks at CreateDevice() time

- layers/CMakeLists.txt
Run cmake-format on master branch before applying next set of changes.
No function changes to the CMake code.
Change-Id: I288e1cb1f03a3852fb6ea7c51dcb1f35b02c9d7f
> build: Rerun cmake-format

- layers/core_validation.cpp
Removed tested conditions not required by the current Vulkan spec that
were being tracked and reported.
Fixes #269
> Remove over validation of vkGetQueryPoolResults

- layers/buffer_validation.cpp
Get this commit out of my working branch.
> Clean up some long-expired comments

- layers/core_validation.cpp
- layers/shader_validation.cpp
FindEntrypoint was assuming SPIR-V ExecutionModel values and Vulkan shader stage bits line up, but they no longer do. Add translation from one namespace to the other.
Add missing handling of acceleration structure OpType/descriptorType.
Fix some remaining places that still treated VK_PIPELINE_BIND_POINT as contiguous enums.
> Fix some raytracing (and mesh) issues.

- layers/buffer_validation.cpp
- layers/vk_format_utils.cpp
- layers/vk_format_utils.h
- tests/layer_validation_tests.cpp
> layers: Handle multiplanar format size compares

- layers/vk_layer_logging.h
The code could generate invalid message types and severities under
certain conditions.  It was getting confused when content was
coming from a Debug Report callback versus a Debug Utils messenger.
The issues discovered by @mark_lunarg should now be resolved.
Change-Id: I99f1a78cc4002c09e22cf6294b81c47967c2a70e
> layers: Fix debug messenger/callback deletion

- .appveyor.yml
- .travis.yml
- BUILD.md
Specify a known good gtest version for CI
> tests: Specify gtest version

- layers/shader_validation.cpp
Previously we only cared about whether the NonWritable decoration was
applied to an entire descriptor-backed OpVariable. This is problematic
for real-world shaders, because glslang emits per-member decorations
instead in all cases.
Adjust the logic to consider per-member decorations in these cases.
Fixes #73.
> Consider member-level nonwritable decorations

- layers/core_validation.cpp
> layers: Ignore MS state if rasterization is disabled

- layers/buffer_validation.cpp
- tests/layer_validation_tests.cpp
Specifying ASPECT_COLOR is the same as specifying all of the
individual planes  Addresses #344
> layers: Fix multiplane layout tracking

- scripts/known_good.json
Removed MoltenVK from known_good.json as it is
needed only for running tests.
> build: Remove MoltenVK from known_good.json

- layers/object_tracker_utils.cpp
- layers/unique_objects.cpp
- layers/unique_objects.h
Derived largely from Gary Sweet's PR #378.  Addresses issue #377.
> layers: Fix unique object tracking for VkDisplayKHR

- layers/core_validation.cpp
- layers/core_validation_types.h
- layers/shader_validation.cpp
Includes fix for #415 and #418.
> Added support for Transform Feedback capabilities.

- layers/core_validation.cpp
- tests/layer_validation_tests.cpp
- Fix #386 which was causing an erroneous validation warning, details in the issue
- Add positive validation test case that was previously triggering the warning
> Fix warning when no metadata is bound to sparse image that requires it

- layers/parameter_validation_utils.cpp
- tests/layer_validation_tests.cpp
> Add missing VUID-vkCmdDrawMeshTasksIndirectNV-drawCount-02147

- scripts/common_codegen.py
This completes the removal of references to MIR in the V-VL repo
> scripts: Remove last reference to MIR

- layers/core_validation.cpp
This is being misused, validate it!
> Add checks for VK_QUERY_CONTROL_PRECISE_BIT

- tests/layer_validation_tests.cpp
> Add tests for QUERY_CONTROL_PRECISE_BIT validation

- layers/vk_layer_logging.h
The `VkDebugUtilsObjectNameInfoEXT` member of the
`VkDebugUtilsMessengerCallbackDataEXT` struct was turned const in Vulkan
header 1.1.95 and modifications were required for compilation
> tests: Modify `vk_layer_logging.h` for hdr 1.1.95

- tests/layer_validation_tests.cpp
Transform feedback is becoming supported in Vulkan.  Use ImageRect
instead
Change-Id: I22c5d369b649aa9d8cce63db2ff57ec369b31475
> tests: Use bad capability that won't be supported later

- layers/core_validation.cpp
- layers/core_validation_types.h
- layers/shader_validation.cpp
> Validation for VK_KHR_swapchain_mutable_format and VK_KHR_shader_float16_int8

- layers/core_validation.cpp
- tests/layer_validation_tests.cpp
Added support for VK_NV_fragment_coverage_to_color to the validation
layers.
> layers: Added VK_NV_fragment_coverage_to_color

- layers/core_validation.cpp
Fix #45 
Remove the warnings for GetPhysicalDeviceSurfacePresentModesKHR as they
aren't showing invalid usage, and will be added to the assistant layer.
Change-Id: Id4944ad1ef34fce45cbf103056ef19c22e7678fd
> layers: Remove warnings from present mode get call

- scripts/layer_chassis_generator.py
Replaces custom device extension tracking with the provided utility.
> Use extension helper in chassis CreateDevice

- layers/buffer_validation.cpp
- tests/layer_validation_tests.cpp
Addresses #530 by deconstructing ASPECT_COLOR into component planes
> layers: Fix layout tracking of views of multi-plane images

- README.md
Added a note to `README.md` about the new version tagging scheme.
> docs: Add explanation of version tagging scheme

- layers/descriptor_sets.cpp
- layers/shader_validation.cpp
- scripts/known_good.json
- tests/layer_validation_tests.cpp
- tests/vktestframework.cpp
This is WIP because the raytracing fix is in https://github.com/KhronosGroup/SPIRV-Tools/pull/2190, but that needs to get merged and pulled into glslang and then into this PR.
> Fix raytracing and descriptor indexing crashes

- build-android/known_good.json
- scripts/known_good.json
- Pickup newer glslang that is required for SPIR-V support for
gpu validation
- Pickup mock ICD fix needed for gpu validation tests
> build: Update known-good

- scripts/check_code_format.sh
Add check for current copyright date to the check_code_format shell script used by travis CI.
Collects PR filenames containing "Copyright ([C|c]) LunarG, Inc." and looks to see if the current year is also in that string.  Will print a warning for each file that doesn't meet these requirements.
@karl-lunarg pointed out that spirv-tools has a much more robust and aggressive copyright checker, if somebody else wanted to take that on either in addition to or in place of this change.
> Add copyright date check to check_code_format.sh

- layers/core_validation.cpp
- layers/core_validation_types.h
- layers/shader_validation.cpp
- scripts/helper_file_generator.py
- tests/layer_validation_tests.cpp
Supercedes https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/497
> VK_EXT_scalar_block_layout (v2)

- layers/parameter_validation_utils.cpp
- scripts/parameter_validation_generator.py
> Python 2 + compile fixes

- scripts/layer_chassis_generator.py
Validation objects could use the api_version member variable before it was initialized. Moved setting this variable before any first use.
Fixes #580.
> Set chassis validation object api_version variable before CreateInstance() call

- layers/parameter_validation_utils.cpp
- tests/layer_validation_tests.cpp
Added support for VK_NV_viewport_swizzle to the
validation layers.
> layers: Added VK_NV_viewport_swizzle

- layers/core_validation.cpp
- layers/vk_format_utils.cpp
- layers/vk_format_utils.h
Cherry-picked from https://gitlab.khronos.org/vulkan/Vulkan-ValidationLayers/merge_requests/19
> Add VK_KHR_depth_stencil_resolve

- layers/buffer_validation.cpp
- layers/core_validation.cpp
- layers/core_validation_types.h
- layers/parameter_validation_utils.cpp
- layers/stateless_validation.h
- scripts/parameter_validation_generator.py
- tests/layer_validation_tests.cpp
This is ready for review, I just need to split the commits.
> Add support for VK_EXT_buffer_device_address and VK_EXT_memory_priority

- layers/core_validation.cpp
The connection to this source was dropped in the rebase.
> Add in GPU-Validation Config/Settings file setup

- tests/layer_validation_tests.cpp
Add a variant to the multiplane image positive test that does a disjoint memory bind.
Resolves #583.
> Add disjoint image binding to multi-plane positive test

- layers/descriptor_sets.cpp
> layers: validate texel buffer descriptor component type vs shader

- layers/gpu_validation.cpp
> layers:Initialize gpu validation variables

- tests/layer_validation_tests.cpp
Fixed test failures and assertions when the maxPushDescriptors property
was zero on platforms that support the push descriptor extension.
The test logic previously assumed that if the push descriptor extension was enabled, at least one push descriptor would be available.  In testing on a specific platform, this wasn't true.
Additionally skipped test cases with "unexpected" errors with the same issue.
Note: it *is* invalid for maxPushDescriptors to be zero when the extension is supported, but as the platform on which this occurs is common, the CI team preferred the work-around to the false positives.
> tests: Fix test failures on maxPushDescriptors 0

- tests/layer_validation_tests.cpp
Added positive layer test to make sure that the usage of
gl_ViewportMask does not cause any errors.
> tests: Added VK_NV_viewport_array2

- layers/core_validation.cpp
Also cleaned up some leftover comments and dead variables.
Fixes #650.
> Clean up RecordRenderPassDag helper function

- scripts/thread_safety_generator.py
Wrap std::unordered_map in a 'small_unordered_map' class that has inline storage
for the first element of the map. This avoids memory allocation and hashing in the
common case where there is only zero or one entries in the map at a time, which
happens a lot given that entries only stay in the map for the duration of an entry
point.
> perf: Optimize unordered_map usage in thread_safety.h

- layers/buffer_validation.cpp
- layers/buffer_validation.h
- layers/core_validation.cpp
- layers/core_validation_types.h
- layers/descriptor_sets.cpp
- layers/parameter_validation_utils.cpp
- layers/stateless_validation.h
This is worth a few percent performance.
> layers: remove more string construction (perf)

- docs/unique_objects_layer.md
Added Vulkan Logo
Added Creative Commons License to the document (since there was no license)
> docs: Add Vulkan Logo

- layers/gpu_validation.cpp
GCC 4.8 has known regex issues, provide a fallback path for finding #line directives
> GPU: Work around gcc std::regex problems

- scripts/common_codegen.py
Available in Vulkan-Headers since 1.1.102.
> scripts: Add metal platform to platform_dict

- layers/gpu_validation.cpp
> gpu: Fix bug using wrong desc set

- layers/buffer_validation.cpp
- layers/core_validation.cpp
- layers/core_validation.h
- layers/descriptor_sets.cpp
- layers/gpu_validation.cpp
- layers/shader_validation.cpp
Planning to go through all of the validation helper functions starting at the lowest  level and clean things out.  Lemme know if y'all would rather have this done in fewer, bigger commits, or fewer bigger PRs.  There'll be a lot, but they are easy to review.
> Cleaning up layer_data refs, first blob

- layers/buffer_validation.cpp
- layers/core_validation.cpp
- layers/core_validation.h
- layers/descriptor_sets.cpp
- layers/gpu_validation.cpp
- layers/shader_validation.cpp
This is the rest of the basic helpers.  Next will be the validation and state recording routines.
> Clean up more CV helper functions

- tests/layer_validation_tests.cpp
These two tests relied on interactions between separate layers to generate multiple errors. The DebugMarkerNameTest was also using incorrect object types, causing crashes on some drivers.
> Fix DebugMarkerNameTest object_types and remove multi-layer dependency artifacts

- scripts/check_commit_message_format.sh
Added a bit more structure to the current commit checks.
> Update CI commit message check

- layers/core_validation.cpp
- layers/core_validation.h
- layers/core_validation_types.h
- tests/layer_validation_tests.cpp
- tests/vkrenderframework.cpp
- tests/vkrenderframework.h
- tests/vktestframeworkandroid.cpp
- tests/vktestframeworkandroid.h
[Issue #728](https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/728)
> Validate device mask

- tests/layer_validation_tests.cpp
Change-Id: I91c19b54038907eb611ddcc771ebee9fb443108d
> tests: Setup VkPhysicalDeviceGroupProperties.sType

- layers/descriptor_sets.cpp
- tests/layer_validation_tests.cpp
[Issue #812](https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/812)
> layers: Used binding index, instead of global descriptor index

- layers/buffer_validation.cpp
[Issue #826](https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/826)
> layers: Fixed log msg

- layers/core_validation.cpp
- tests/layer_validation_tests.cpp
[Issue #744 ](https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/744)
> Validate topology of VkPipelineInputAssemblyStateCreateInfo

- layers/parameter_validation_utils.cpp
- layers/stateless_validation.h
- scripts/parameter_validation_generator.py
This implements VUID-VkAccelerationStructureCreateInfoNV-compactedSize-02421.
> layers: Check acceleration structure compactedSize

- layers/vk_layer_utils.h
- scripts/layer_chassis_dispatch_generator.py
The handle wrap/unwrap logic for templates was storing non-dispatchable handles in void *, which is non-portable and subject to truncation errors.  
Change storage for all handles to 64 bit, replaced "reinterpret_cast" with size-change-safe, portable cast utilities.
> Avoid void * overflow and portability issues with handle storage on 32bit

- layers/core_validation.cpp
Change-Id: I032749665258141c65b5da7c1e60791883f341f6
> layers: Print topology string to make log msg clear

- layers/buffer_validation.cpp
- layers/core_validation.cpp
- layers/shader_validation.cpp
- layers/vk_layer_utils.h
Two bugfixes discovered during 32-bit type/size safety assessment.
> Type and size-safe bugfixes

- layers/core_validation.cpp
Reviewed here: https://gitlab.khronos.org/vulkan/Vulkan-ValidationLayers/merge_requests/22
> Add VK_KHR_surface_protected_capabilities

- scripts/parameter_validation_generator.py
This implements verifications for VUID-VkAllocationCallbacks-pfnInternalAllocation-00635.
> layers: Check optional allocator pointers

- tests/layer_validation_tests.cpp
Some tests crash in some specific Android devices, like Samsung Mali.
> tests: Fix Android crash

- layers/gpu_validation.cpp
If all descriptor sets are used by the app, gpu-av doesn't modify the pipeline layout, and in this case it should remove the instrumented shaders at pipeline creation
> gpu: Replace shaders if layout unmodified

- build-android/known_good.json
- docs/gpu_validation.md
- layers/core_validation.cpp
- layers/core_validation.h
- layers/descriptor_sets.h
- layers/gpu_validation.cpp
- layers/gpu_validation.h
- tests/layer_validation_tests.cpp
- tests/vkrenderframework.cpp
- tests/vkrenderframework.h
gpu_validation.md still needs to be updated to reflect extended design
> Add gpu assisted validation for descriptor_indexing features

- .appveyor.yml
- BUILD.md
Updated appveyor script and some stuff in the BUILD.md doc.
> Move minimum MSVC version to 2015

- layers/descriptor_sets.cpp
- tests/layer_validation_tests.cpp
@jzulauf-lunarg  I closed the old [PR #869 ](https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/869) and opened this PR because the old one keeps showing `This branch has conflicts that must be resolved` , but doesn't explain where.  I cannot fix it, so I opened new one.
> Use wrong index to get descriptor in update descriptor set

- layers/buffer_validation.cpp
- layers/core_validation_types.h
Added additional tests to layout checks, such that inexact (relaxed)
initial uses of resources don't cause false positives for later exact
uses.
Addresses additional cases for #316
> Further refine relaxed layout matching

- scripts/thread_safety_generator.py
Add nullptr check for thread safety (outer) loop array parameters to
support optional array parameters and increase robustness.
Fixes #842
> Add null checks for thread safety array params

- tests/layer_validation_tests.cpp
Test [PR #883](https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/883)
Creating two samplers and conversions tests VUID-01948.
Descriptors use two different samplers, but two views use the first sampler, so the second view triggers VUID-01948. If it uses a wrong index to get descriptor, it will not trigger VUID-01948.
> tests: Test if descriptor uses a wrong index

- tests/layer_validation_tests.cpp
> tests:Re-enable android for gpu validation test

- layers/core_validation.cpp
- layers/core_validation.h
- layers/core_validation_types.h
Refactored common validation logic for Begin/EndQuery and added valid usages for the query indexed extension.
Fixes #824
> Add QueryIndexedEXT validation

- layers/core_validation.cpp
- layers/core_validation.h
- layers/gpu_validation.cpp
Free old input/output buffers a command buffer reset time
> gpu: Free resources at command buffer reset

- layers/buffer_validation.cpp
- layers/core_validation.cpp
- layers/core_validation_types.h
Change-Id: I27e8f9cc58b9cd492b8ef41120f71407c3d52d5c
> layers: Avoid invalid pNext (VkExternalFormatANDROID)

- layers/parameter_validation_utils.cpp
- layers/stateless_validation.h
- scripts/parameter_validation_generator.py
- tests/layer_validation_tests.cpp
Check valid usage for VUID-VkPipelineCreationFeedbackCreateInfoEXT-*.
This pull request fixes #830
> layers: Validate VK_EXT_pipeline_creation_feedback

- layers/core_validation.cpp
- layers/core_validation.h
- layers/core_validation_types.h
- tests/vklayertests.cpp
- tests/vkpositivelayertests.cpp
Add validations for VK_EXT_host_query_reset VUIDs and tests for them.
> layers: Add VK_EXT_host_query_reset validations

- tests/vklayertests.cpp
Fix for #629 together with a fix for running on the Mesa driver
> tests: Check tiling/format/usage combos

- layers/core_validation.cpp
- layers/core_validation.h
- layers/gpu_validation.cpp
- scripts/layer_chassis_generator.py
Replace instrumented shaders in compute pipelines when descriptor set is unavailable.  Mirrors treatment of graphics pipelines
> gpu: Fix shaders in compute pipelines

- layers/core_validation.cpp
- layers/core_validation.h
- layers/gpu_validation.cpp
- layers/gpu_validation.h
Use the loader supplied method of initializing loader data
> gpu: Use SetDeviceLoaderData on command buffer

- layers/core_validation.cpp
> Validation message rephrasing

- BUILD.md
> docs: Improve instructions for using update_deps

- tests/layers/CMakeLists.txt
> Explicitly specify files and avoid xcopy for device_profile_api.* file copies

- tests/vklayertests_others.cpp
- Remove misleading\obsolete comment
- Use VUID
- Optimize by not creating a device via framework
- some code C++ization
> tests: Rewrite LeakAnObject test

- layers/core_validation.cpp
- layers/core_validation.h
- layers/drawdispatch.cpp
- layers/parameter_validation_utils.cpp
- tests/vklayertests_others.cpp
[issue #857 ](https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/857)
> Validate stride in QueryPool and CmdDraw

- layers/drawdispatch.cpp
- layers/parameter_validation_utils.cpp
Move VUID-02146 from core validation into parameter validation
> layers: Fix test MeshShaderNV

- tests/layer_validation_tests.cpp
- tests/layer_validation_tests.h
- tests/vklayertests_others.cpp
- tests/vktestframeworkandroid.cpp
Change-Id: I6cc0824be3827d79dc2eae5c8917103dc4f98213
> tests: Fix ValidateStride in PixelC

- tests/layer_validation_tests.cpp
- tests/layer_validation_tests.h
- tests/vklayertests_buffer_image_memory_sampler.cpp
- tests/vklayertests_command.cpp
- tests/vklayertests_descriptor_renderpass_framebuffer.cpp
- tests/vklayertests_others.cpp
- tests/vklayertests_pipeline_shader.cpp
- tests/vkpositivelayertests.cpp
- tests/vkrenderframework.cpp
- tests/vkrenderframework.h
Previous [PR #924 ](https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/924), [PR #949 ](https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/949)
I extracted the common code. That is my final version. If you have any idea to make it better, please let me know or write down in [issue #427 ](https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/427)
> Refactor validation layer tests

- .travis.yml
- layers/CMakeLists.txt
Guard LAYER_UTIL_FILES installation with BUILD_LAYER_SUPPORT_FILES.
Fix #233.
Change-Id: Ic6ac477b2f54b66b23639d9ec97f4ce592a84346
> layers: Guard layer utils installation

- layers/core_validation.cpp
- layers/core_validation_error_enums.h
- scripts/helper_file_generator.py
- tests/layer_validation_tests.cpp
- tests/vklayertests_others.cpp
- tests/vkrenderframework.cpp
- tests/vkrenderframework.h
[issue #934 ](https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/934)
> layers: Warning when swapchaincreateinfo-preTransform doesn't match currentTransform

- layers/generated/vk_enum_string_helper.h
- scripts/helper_file_generator.py
Change-Id: I7a10fa215037d8d30969b8bc071573b489d2412f
> scripts: Add include of std string to gen'ed header

- layers/generated/spirv_tools_commit_id.h
- scripts/known_good.json
> scripts: Update glslang commit for 114 SDK

- layers/shader_validation.cpp
- layers/shader_validation.h
This eliminates a number of passes over the shader, and partially
eliminates the need for external flattening of decoration groups.
> Centralize decoration collection

- build-android/cmake/layerlib/CMakeLists.txt
android: Fix typo in CMakeLists.txt in layerlib
> android: Fix typo in CMakeLists.txt in layerlib

- tests/vkpositivelayertests.cpp
Added positive layer test to make sure that the usage of
VK_NV_sample_mask_override_coverage does not cause any
errors.
> test: Added VK_NV_sample_mask_override_coverage

- layers/core_validation.cpp
- tests/vkpositivelayertests.cpp
Fixed [issue #930](https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/930) & [issue #981](https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/981)
Implement vkspec: 
```
pViewportState is a pointer to an instance of the VkPipelineViewportStateCreateInfo structure, and is ignored if the pipeline has rasterization disabled.
pMultisampleState is a pointer to an instance of the VkPipelineMultisampleStateCreateInfo, and is ignored if the pipeline has rasterization disabled.
pDepthStencilState is a pointer to an instance of the VkPipelineDepthStencilStateCreateInfo structure, and is ignored if the pipeline has rasterization disabled.
pColorBlendState is a pointer to an instance of the VkPipelineColorBlendStateCreateInfo structure, and is ignored if the pipeline has …
```
> Ignore some structure when rasterizerDiscardEnable is TRUE

- layers/buffer_validation.cpp
- layers/core_validation.cpp
- layers/vk_format_utils.cpp
- layers/vk_format_utils.h
- tests/layer_validation_tests.cpp
Fix some more issues discovered by warnings in #1106
> Fix some more compiler and static analysis warnings

- layers/vk_layer_logging.h
[issue #1132 ](https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/1132)
Undo [4f56658](https://github.com/KhronosGroup/Vulkan-ValidationLayers/commit/4f56658c556e19cd3724b2ef7d6cdd28d3c15a86)
@kennyalive
> layers: Copy string

- layers/descriptor_sets.cpp
Additionally, if command_buffer_state validation is disabled, skip this tracking entirely.
This makes the logic for descriptor set tracking match what we do for other objects like buffers/images/views/samplers/etc.
In the app I'm testing (with image layout and command buffer state validation enabled) I measured a 10% reduction in core validation time from adding the "if (inserted.second)" filtering, and then another 10% reduction from skipping the tracking entirely.
> layers: If a descriptor set is already tracked, don't insert it again

- layers/core_validation.cpp
- tests/vklayertests_pipeline_shader.cpp
- tests/vkpositivelayertests.cpp
[issue #1129 ](https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/1129)
> Geometry shader that doesn't has PointSize works in VK_PRIMITIVE_TOPOLOGY_POINT_LIST.

- CMakeLists.txt
- layers/CMakeLists.txt
- tests/layers/CMakeLists.txt
> Move generated includes before external includes

- tests/vklayertests_pipeline_shader.cpp
Specialize the correct stage.
Change-Id: I2249d64e6bc2c3fd9dc839d614f4a547573b10cb
> tests: Fix specialization test

- layers/parameter_validation_utils.cpp
- layers/stateless_validation.h
> Track extension Features in stateless

- tests/vkpositivelayertests.cpp
Added positive layer test to make sure that the usage of
VK_NV_geometry_shader_passthrough does not cause any
errors.
> test: Added VK_NV_geometry_shader_passthrough

- layers/buffer_validation.cpp
- layers/core_validation.cpp
- layers/core_validation.h
- tests/vklayertests_buffer_image_memory_sampler.cpp
- tests/vklayertests_descriptor_renderpass_framebuffer.cpp
Previous pull request: #1115
The opened issue: #1097
> Add missing fragmentDensityMap validations

- layers/parameter_validation_utils.cpp
- tests/vklayertests_pipeline_shader.cpp
Added support for VK_NV_fill_rectangle to the validation
layers.
Added test to ensure that wrong usage is detected when the
extension is enabled.
Enhanced existing PSOPolygonModeInvalid to make sure that
using VK_POLYGON_MODE_FILL_RECTANGLE_NV causes an error if
the extension is not enabled.
> layers: Add VK_NV_fill_rectangle

- layers/stateless_validation.h
per resolution in https://github.com/KhronosGroup/Vulkan-Docs/issues/1021
> layers: Re-ban ray tracing stages in render pass

- layers/shader_validation.cpp
- layers/shader_validation.h
> layers: Refactor shader location validation

- layers/best_practices.cpp
- layers/best_practices.h
- layers/best_practices_error_enums.h
- layers/core_validation_error_enums.h
- layers/generated/chassis.cpp
- scripts/layer_chassis_generator.py
- Now using Validation State Tracker. Added a few warnings that were migrated from the Assistant Layer in LunarG/VulkanTools
- Also changes the VUID's on all the log-msg calls
> Best Practices Step 3 -Using ValidationStateTracker

- layers/core_validation.cpp
Now that the PhysicalDeviceSurface... Get warnings have been added to the Best Practices Validation Object, it is now safe to remove these warnings from CoreChecks.
> Remove PhysicalDeviceSurface... Get Warning from CoreChecks

- layers/best_practices.cpp
- layers/best_practices.h
- layers/best_practices_error_enums.h
- layers/core_validation.cpp
Add Buffer/Image Memory Requirements Get Warnings to BestPractices and Remove from CoreChecks
> layers: Move Buffer/Image Memory Requirements Get Warnings

- layers/buffer_validation.cpp
- tests/vklayertests_buffer_image_memory_sampler.cpp
Add 4 or 5 bounds check VUIDs for `vkCmdCopyBuffer `-- 00112 to 00117, along with tests.
Fixes #1214.
> Add Some CmdCopyBuffer Range VU Checks

- layers/best_practices.cpp
- layers/best_practices.h
Fixes issue KhronosGroup/Vulkan-LoaderAndValidationLayers#2535 tracked in #24 stating to "Validate getter's structure count"
> Best-Practices: Structure Count Warning

- build-android/known_good.json
- docs/gpu_validation.md
- layers/buffer_validation.cpp
- layers/core_validation.cpp
- layers/core_validation.h
- layers/core_validation_types.h
- layers/generated/chassis.cpp
- layers/generated/chassis.h
- layers/generated/spirv_tools_commit_id.h
- layers/generated/thread_safety.cpp
- layers/generated/thread_safety.h
- layers/gpu_validation.cpp
- layers/gpu_validation.h
- scripts/known_good.json
- scripts/layer_chassis_generator.py
- scripts/object_tracker_generator.py
- scripts/thread_safety_generator.py
- tests/vklayertests_descriptor_renderpass_framebuffer.cpp
This will need a newer spirv-tools than is known good today, but would like to get through the code review.
> Add GPU assisted validation for VK_EXT_buffer_device_address

- build-android/cmake/layerlib/CMakeLists.txt
- build-android/jni/Android.mk
- layers/best_practices.cpp
- layers/best_practices.h
And fixed some clang compilation errors.
> Add Android support for Best Practices validation

- layers/best_practices.cpp
Change the comparison op to match the error message.
> layers: Update GetPhysicalDeviceSurfaceFormatsKHR check

- layers/buffer_validation.cpp
- layers/core_validation.cpp
- layers/core_validation_types.h
- layers/state_tracker.cpp
- tests/vklayertests_buffer_image_memory_sampler.cpp
> Support VK_NV_dedicated_allocation_image_aliasing

- layers/descriptor_sets.cpp
- tests/vklayertests_descriptor_renderpass_framebuffer.cpp
https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/182
When `dstArrayElement of VkWriteDescriptorSet` is wrong, the validation layer might point to a wrong descriptorset with a wrong offset, like the issue's description. It wants to update input attachment, but the validation layer point to uniform buffer, so it needs to validate the data type.
> layers: Validate Update descriptorset type

- BUILD.md
> Add python3-distuils to required Linux package list

- layers/generated/chassis.cpp
- layers/generated/chassis.h
- layers/generated/layer_chassis_dispatch.cpp
- layers/generated/thread_safety.h
- layers/object_lifetime_validation.h
- layers/stateless_validation.h
- layers/vk_layer_utils.h
- scripts/layer_chassis_dispatch_generator.py
- scripts/layer_chassis_generator.py
- scripts/thread_safety_generator.py
> layers: Switch chassis to read/write locking

- layers/core_validation.cpp
- layers/core_validation_types.h
- layers/descriptor_sets.cpp
- layers/descriptor_sets.h
- layers/state_tracker.cpp
- layers/state_tracker.h
> layers: Fix constness of shared_ptrs

- layers/core_validation.cpp
- layers/state_tracker.cpp
If the only thing that has changed is that a newly bound pipeline uses more bindings
than the last time we validated the set, then only validate those additional bindings.
> layers: Improve large descriptor set validation filtering

- layers/generated/vk_extension_helper.h
- layers/shader_validation.cpp
- scripts/helper_file_generator.py
Reviewed on https://gitlab.khronos.org/vulkan/Vulkan-ValidationLayers/merge_requests/26
Running through CI
> VK_KHR_spirv_1_4 validation

- layers/core_validation.cpp
- layers/core_validation.h
- layers/core_validation_types.h
- layers/descriptor_sets.cpp
- layers/descriptor_sets.h
- layers/state_tracker.cpp
- tests/vklayertests_descriptor_renderpass_framebuffer.cpp
https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/539
> Validate UPDATE_AFTER_BIND of descriptorSet in QueueSumit 

- layers/shader_validation.cpp
- tests/vkpositivelayertests.cpp
Fix #766.
There is a bug in the construction of location_map which led to false
positives when attachment references are marked as unused.
Change-Id: I3e210da10d1d571bd442a3b78aab4f5f6af6ae5c
> layers: Fix attachment unused false positive

- build-android/known_good.json
- layers/generated/spirv_tools_commit_id.h
- scripts/known_good.json
Change-Id: I2b8e3226c82e5f2841cddc00ffda1d122ba1317e
> build: Update known-good commits for SDK 126

- tests/vkpositivelayertests.cpp
Test reserved descriptor set and pipeline recovery code
> Add more gpu-av positive tests

- layers/shader_validation.cpp
- tests/vklayertests_pipeline_shader.cpp
The most recent Vulkan spec update clarifies that the shader input/output limits mean that the total number of components (including builtins) can't be more than the limit, AND that individual variables can't use locations higher than the limit. Core validation previously only checked the former, this commit adds the latter.
> layers: Update ValidateShaderStageInputOutputLimits to new spec rules 

- .appveyor.yml
> Add VUID coverage text file to AppVeyor artifacts

- layers/best_practices.cpp
- layers/buffer_validation.cpp
- layers/core_validation_types.h
See #1365 
Creating separate branch to get CI to pass.
> layers: Add ext mem check for vkGet*MemReqs

- layers/core_validation.cpp
While developing some VK-GL-CTS tests with renderpass2 using a depth/stencil multisample attachment and a VK_ATTACHMENT_UNUSED depth/stencil resolve attachment from a VkSubpassDescriptionDepthStencilResolveKHR structure, the layers were crashing while attempting to use the attachment index (VK_ATTACHMENT_UNUSED) to access the attachment array.
This pull request adds checks so depth/stencil resolve validations will not crash.
> layers: Fix crashes with depth/stencil resolve

- layers/core_validation.cpp
- tests/vklayertests_pipeline_shader.cpp
- tests/vkpositivelayertests.cpp
https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/507
@scyganINTEL
> Add VK_PIPELINE_STAGE_CONDITIONAL_RENDERING_BIT_EXT in supported_pipeline_stages_table

- layers/buffer_validation.cpp
- tests/vklayertests_buffer_image_memory_sampler.cpp
> Add missing CmdFillBuffer size/offset VUIDs

- layers/buffer_validation.cpp
- layers/core_validation.cpp
- layers/descriptor_sets.cpp
- layers/generated/vk_dispatch_table_helper.h
- layers/generated/vk_extension_helper.h
- layers/gpu_validation.cpp
- layers/parameter_validation_utils.cpp
- layers/shader_validation.cpp
- layers/state_tracker.h
- scripts/dispatch_table_helper_generator.py
- scripts/helper_file_generator.py
- tests/vkpositivelayertests.cpp
Addresses #1252
Keep track of how extension was enabled and only return function pointer if appropriate
> Fix GetProcAddrs for promoted extensions

- layers/generated/chassis.cpp
- layers/generated/chassis.h
- layers/generated/layer_chassis_dispatch.cpp
- layers/json/VkLayer_khronos_validation.json.in
- layers/stateless_validation.h
- scripts/dispatch_table_helper_generator.py
- scripts/layer_chassis_dispatch_generator.py
- scripts/layer_chassis_generator.py
- tests/vkpositivelayertests.cpp
Add support to chassis for this extension, handle queries properly.
Fixes #1430.
> Add tooling extension query support to Validation layers

- layers/buffer_validation.cpp
- tests/vklayertests_buffer_image_memory_sampler.cpp
Keeps checks for 00012 and 00005, adding 01394 and nuking the old made-up checks. Tests already existed for 5 and 12, added a new test for 1394.
Fixes #1440.
> Streamline CmdClear layout validation checks 

- layers/buffer_validation.cpp
- tests/vklayertests_command.cpp
Wrote a test to verify support as well
> layers: Added support for VUID 01560

- layers/parameter_validation_utils.cpp
- tests/vklayertests_buffer_image_memory_sampler.cpp
Add checks to implement vu 01646.
Fixes #1476.
> Add some YCBCR sampler conversion validation checks

- layers/CMakeLists.txt
> layers: update minor version for generated linux json files

- layers/shader_validation.cpp
- tests/vkpositivelayertests.cpp
> Fix constant specialization

- layers/buffer_validation.cpp
- layers/core_validation_types.h
- layers/state_tracker.cpp
- tests/vklayertests_buffer_image_memory_sampler.cpp
Adds supports for
- VUID-VkImageCreateInfo-format-02653
- VUID-VkImageCreateInfo-format-02564
- VUID-VkImageCreateInfo-format-02561
- VUID-VkImageCreateInfo-format-02562
- VUID-VkImageCreateInfo-format-02563
> Added more YCbCr validation

- layers/shader_validation.cpp
> layers: Use correct VK version when validating spec consts

- layers/shader_validation.h
Fix #1530.
Initialize has_specialization_constant to false.
Change-Id: I245d2a20612227e772ea3b8a5270c08957d523ae
> layers: Fix unitialized variable.

- layers/range_vector.h
- tests/vkpositivelayertests.cpp
Implements fix and test for range_map erase entry point.
> Bugfix for range_map erase range and regression test

- layers/generated/parameter_validation.cpp
- layers/parameter_validation_utils.cpp
- layers/stateless_validation.h
- scripts/parameter_validation_generator.py
- tests/vklayertests_command.cpp
> layers: Validate unaligned CmdPushDescriptorSet

- layers/generated/parameter_validation.cpp
- layers/parameter_validation_utils.cpp
- layers/stateless_validation.h
- scripts/parameter_validation_generator.py
- tests/vklayertests_buffer_image_memory_sampler.cpp
VUID-VkBufferCopy-size-01988
> The size must be greater than 0
> Added support for VUID-VkBufferCopy-size-01988

- layers/parameter_validation_utils.cpp
- tests/vklayertests_pipeline_shader.cpp
VUID-VkComputePipelineCreateInfo-stage-00701
> The stage member of stage must be VK_SHADER_STAGE_COMPUTE_BIT
> Added support for VUID-VkComputePipelineCreateInfo-stage-00701

- layers/core_validation.cpp
- layers/core_validation_types.h
> Fix false errors if query condition is unknownn

- layers/buffer_validation.cpp
- layers/core_validation_types.h
- layers/state_tracker.cpp
> layers: Fix swapchain CreateInfo flags

- scripts/generate_source.py
Add line-by-line diff when generate_source.py --verify fails.  This will help debug issues where CI fails because of generated source consistency check.
> Add line diff to generate_source.py

- layers/vk_layer_config.cpp
> layers: Fix layer settings file loading using registry

- layers/gpu_validation.cpp
- layers/gpu_validation.h
Part of getting away from the deprecated extension.
> Remove unneeded refs to debug report enums from Gpu Ass Val

- layers/core_validation.cpp
- layers/core_validation.h
- layers/shader_validation.cpp
Plan to add some `VkComputePipelineCreateInfo` VUID support in near future and while scanning current support came across some low hanging fruit to fix first
> layers: Rename ValidateComputePipelineShaderState

- tests/vklayertests_pipeline_shader.cpp
Change-Id: I419c83cbd7d3b4108caddda786b198ec37a3d0a1
> tests: Test array dynamic indexing features

- layers/core_validation.cpp
- tests/vklayertests_buffer_image_memory_sampler.cpp
Adds support for
- VUID-VkMemoryDedicatedAllocateInfo-image-01432
- VUID-VkMemoryDedicatedAllocateInfo-image-01433
- VUID-VkMemoryDedicatedAllocateInfo-image-01434
- VUID-VkMemoryDedicatedAllocateInfo-buffer-01435
- VUID-VkMemoryDedicatedAllocateInfo-buffer-01436
- VUID-VkMemoryDedicatedAllocateInfo-image-01797
> Add VkMemoryDedicatedAllocateInfo Support

- layers/buffer_validation.cpp
- tests/vklayertests_buffer_image_memory_sampler.cpp
Moves a single VUID into the 4 VUIDs that make it up depending on the combination of extensions enabled
> layers: Add VUID for 01759 01760 01761

- LAYER_CONFIGURATION.md
Added some historical context.
Fixes #1560.
> Update layer config and overview doc

- layers/parameter_validation_utils.cpp
- tests/vklayertests_pipeline_shader.cpp
VUID-VkPipelineDynamicStateCreateInfo-pDynamicStates-01442
> Each element of pDynamicStates must be unique
> Add support for VUID 01442

- layers/parameter_validation_utils.cpp
While working with the Graphics Pipeline Parameter Validation realized it is making redundant loops through `pStages`
> Removed redundant looping in graphics pipeline

- layers/core_validation.h
- layers/shader_validation.cpp
- tests/vklayertests_pipeline_shader.cpp
VUID-VkComputePipelineCreateInfo-layout-01687
VUID-VkGraphicsPipelineCreateInfo-layout-01688
> Add support for maxPerStageResources

- BUILD.gn
> build: Add VK_ENABLE_BETA_EXTENSIONS to GN build

- layers/buffer_validation.cpp
- layers/core_validation.cpp
- layers/core_validation_types.h
- layers/state_tracker.cpp
- tests/vklayertests_buffer_image_memory_sampler.cpp
- tests/vkpositivelayertests.cpp
> Fix layout tracking for swapchain images and imageless framebuffers

- layers/parameter_validation_utils.cpp
VUID-VkDescriptorSetLayoutBinding-descriptorType-00282
> layers: Add label for 00282

- layers/core_validation.cpp
VUID-VkBufferMemoryBarrier-buffer-01931
> layers: Add label for 01931

- layers/buffer_validation.cpp
VUID-VkImageCreateInfo-flags-01572
VUID-VkImageCreateInfo-flags-01573
> layers: Add label for 01572 and 01573

- layers/debug_printf.cpp
Fixes intermittent test failure
> Add null terminator to types array in debug printf

- layers/buffer_validation.cpp
- tests/vklayertests_buffer_image_memory_sampler.cpp
Adds:
- VUID-VkImageMemoryBarrier-image-01671
- VUID-VkImageMemoryBarrier-image-01672
- VUID-VkImageMemoryBarrier-image-01673
> Add Disjoint Image Barrier VUID

- tests/vklayertests_buffer_image_memory_sampler.cpp
- tests/vklayertests_descriptor_renderpass_framebuffer.cpp
- tests/vklayertests_others.cpp
- tests/vklayertests_pipeline_shader.cpp
Clean up some unexpected errors and unnecessary test skips
> Miscellaneous test cleanup

- layers/CMakeLists.txt
> layers: Add some headers to cmake

- CONTRIBUTING.md
- docs/creating_tests.md
After having writing many tests over the last few months... here is the "What I wish I knew back then" guide I had some energy to write up
> Add Documentation about writing tests

- layers/core_validation.cpp
- layers/core_validation.h
- layers/core_validation_types.h
- layers/state_tracker.cpp
- layers/state_tracker.h
- tests/vklayertests_others.cpp
New new VUs were added around the reset behavior of performance queries.
This adds new tests for them.
> Update validation for VK_KHR_performance_query

- docs/debug_printf.md
Change-Id: Id0bbe52a3faae21287ca9a82c15e4352d30fd877
> docs: Suggest disabling validation with debug printf

- layers/best_practices_utils.cpp
This caused a null pointer dereference and crash in a user application.
> Avoid VertexInputState Best Practices checks when using active mesh shader stage

- layers/parameter_validation_utils.cpp
- tests/vklayertests_others.cpp
VUID-VkImageCreateInfo-tiling-02261
VUID-VkImageCreateInfo-pNext-02262
I added these as I add an assert in #1685 that relies on this VUID catching it
> Add support for VUID 02261 and 02262

- layers/generated/chassis.cpp
- scripts/layer_chassis_generator.py
discalaimer: I am not sure what exactly the locks are supposed to be for, but they seem to be in all the other commands.
> layers: Add missing instance chassis locks?

- layers/buffer_validation.cpp
- layers/generated/parameter_validation.cpp
- layers/parameter_validation_utils.cpp
- layers/stateless_validation.h
- scripts/parameter_validation_generator.py
- tests/vklayertests_buffer_image_memory_sampler.cpp
- tests/vklayertests_others.cpp
This is WIP until the new VUIDs get assigned in Vulkan-Docs.
> Validate cube image view layerCount

- tests/vkpositivelayertests.cpp
It uses magic number for allocation
and https://github.com/KhronosGroup/Vulkan-Tools/pull/377
broke it.
Plus some other lifetime, robustness, and
code style improvements.
> tests: Fix failing TestAliasedMemoryTracking

- layers/core_validation.cpp
- layers/core_validation.h
> Fix renderpass2 tracking

- layers/core_validation.cpp
This allows this VUID to properly be used for external AHB formats
Also updated the error message to make clear it is using the VkImage's format feature and not the VkImageView's features
cc: @djdeath
> layers: Fix VUID 02023 to use image state format feature

- layers/buffer_validation.cpp
- layers/core_validation.cpp
- layers/core_validation_types.h
- layers/state_tracker.cpp
- layers/state_tracker.h
Fixes 1533266eac486fae0c34bffe4868c4bc91dbe078
> Fix validation of blended attachments on imageless framebuffers

- layers/core_validation_types.h
- layers/state_tracker.cpp
- tests/vkpositivelayertests.cpp
- tests/vkrenderframework.cpp
- tests/vkrenderframework.h
- tests/vktestbinding.cpp
- tests/vktestbinding.h
> Fix wsi format props

- layers/best_practices_utils.cpp
- layers/best_practices_validation.h
Validate attachments for imageless framebuffers in BeginRenderPass
> BP: Fix CreateFramebuffer and validate attachments in BeginRenderPass

- layers/best_practices_utils.cpp
Fixes crash in swapchain.create.image_swapchain_create_info with BP enabled
> Don't validate swapchain memory in BP

- layers/parameter_validation_utils.cpp
- tests/vklayertests_command.cpp
Adds
VUID-vkCmdClearAttachments-rect-02682
VUID-vkCmdClearAttachments-rect-02683
> Add Clear Attachments rect VUIDs

- layers/buffer_validation.cpp
- tests/vklayertests_buffer_image_memory_sampler.cpp
Adds
VUID-VkImageMemoryBarrier-oldLayout-01658
VUID-VkImageMemoryBarrier-oldLayout-01659
> Add ImageMemoryBarrier oldLayout VUIDs

- layers/core_validation.cpp
- tests/vklayertests_imageless_framebuffer.cpp
VUID-VkFramebufferCreateInfo-pAttachments-02634
> Add support for VUID 02634

- layers/stateless_validation.h
- tests/vklayertests_buffer_image_memory_sampler.cpp
- tests/vklayertests_descriptor_renderpass_framebuffer.cpp
VUID-VkAttachmentDescription-format-03280
VUID-VkAttachmentDescription-format-03281
VUID-VkAttachmentDescription-format-03282
VUID-VkAttachmentDescription-format-03283
VUID-VkAttachmentDescription2-format-03294
VUID-VkAttachmentDescription2-format-03295
VUID-VkAttachmentDescription2-format-03296
VUID-VkAttachmentDescription2-format-03297
> Add RenderPass Attachment VUIDs

- layers/core_validation.cpp
- tests/vklayertests_buffer_image_memory_sampler.cpp
VUID-vkCmdBindIndexBuffer-offset-00431
> Add VUID 00431

- layers/core_validation.cpp
- layers/core_validation.h
- layers/parameter_validation_utils.cpp
- tests/vklayertests_others.cpp
VUID-vkCmdEndQuery-query-00810
VUID-VkQueryPoolCreateInfo-queryCount-02763
VUID-vkCmdResetQueryPool-firstQuery-00796
VUID-vkCmdResetQueryPool-firstQuery-00797
VUID-vkCmdCopyQueryPoolResults-firstQuery-00820
VUID-vkCmdCopyQueryPoolResults-firstQuery-00821
VUID-vkGetQueryPoolResults-firstQuery-00813
VUID-vkGetQueryPoolResults-firstQuery-00816
VUID-vkCmdWriteTimestamp-queryPool-01416
> Add Query VUIDs

- layers/buffer_validation.cpp
- tests/vklayertests_buffer_image_memory_sampler.cpp
- tests/vklayertests_command.cpp
This helps address related issue from #473 by adding support for `VUID-vkCmdCopyImage-None-01549`
Working Group discussions show the transitive property can be used for checking compatible single-plane formats. CTS tests are being written for this and if come back that a IHV can't support this property I will come back and make 01549 more strict
> Add support for VUID 01549

- layers/core_validation.cpp
- tests/vklayertests_descriptor_renderpass_framebuffer.cpp
Already tested VUID, just needed label
VUID-VkSubpassDependency2-viewOffset-02530
VUID-VkRenderPassCreateInfo2-attachment-02525
> Label RenderPass2 VUIDs

- layers/core_validation.cpp
- tests/vklayertests_descriptor_renderpass_framebuffer.cpp
VUID-VkSubpassDependency-srcSubpass-02243
VUID-VkSubpassDependency2-srcSubpass-02245
> Add VUID 02243 and 02245

- layers/parameter_validation_utils.cpp
- tests/vklayertests_others.cpp
VUID-VkDeviceCreateInfo-ppEnabledExtensions-02831
VUID-VkDeviceCreateInfo-ppEnabledExtensions-02832
VUID-VkDeviceCreateInfo-ppEnabledExtensions-02833
VUID-VkDeviceCreateInfo-ppEnabledExtensions-02834
VUID-VkDeviceCreateInfo-ppEnabledExtensions-02835
> Added feature12 extension VUID

- layers/core_validation.cpp
cleaning up as I added these VUs
> layers: Fix typo of dose to does

- layers/debug_printf.h
- layers/gpu_validation.h
- tests/vklayertests_gpu.cpp
> Initialize layout handles gpu-av / printf

- layers/core_validation.cpp
- layers/debug_printf.cpp
- layers/gpu_validation.cpp
- layers/state_tracker.cpp
> Avoid state updates if QueueSubmit call does not succeed

- BUILD.md
> Update BUILD.md for the new SPIRV-headers dependencies

- layers/core_validation.cpp
- tests/vklayertests_buffer_image_memory_sampler.cpp
VUID-vkBindImageMemory2-pBindInfos-04006
> Label VUID 04006

- layers/core_validation.cpp
- tests/vklayertests_others.cpp
- tests/vkpositivelayertests.cpp
VUID-vkCmdWriteTimestamp-timestampValidBits-00829
> Add VUID 00829

- layers/core_validation.cpp
- layers/parameter_validation_utils.cpp
- tests/vklayertests_buffer_image_memory_sampler.cpp
VUID-VkSamplerCreateInfo-None-01647
VUID-VkSamplerCreateInfo-compareEnable-01423
> Add VK_EXT_sampler_filter_minmax VUID

- layers/core_validation.cpp
- layers/core_validation.h
- tests/vklayertests_others.cpp
VUID-VkSubmitInfo-pWaitDstStageMask-00078
VUID-vkCmdSetEvent-stageMask-01149
VUID-vkCmdResetEvent-stageMask-01153
> Add HOST_STAGE VUIDs

- layers/core_validation.cpp
- layers/core_validation_types.h
- layers/descriptor_sets.cpp
- layers/parameter_validation_utils.cpp
- layers/state_tracker.cpp
- layers/state_tracker.h
- layers/vk_format_utils.cpp
- layers/vk_format_utils.h
- tests/vklayertests_buffer_image_memory_sampler.cpp
Validation of 04015 for DescriptorClass::PlainSampler coming in a later PR
> Validation for VK_EXT_custom_border_color

- layers/buffer_validation.cpp
- tests/vklayertests_command.cpp
VUID-VkBufferImageCopy-None-01735
VUID-VkBufferImageCopy-None-01736
VUID-VkBufferImageCopy-None-01737
VUID-VkBufferImageCopy-None-01738
VUID-VkBufferImageCopy-None-01739
VUID-VkBufferImageCopy-None-01740
VUID-VkBufferImageCopy-None-01741
> layers: Label YCbCr VUIDs

- layers/parameter_validation_utils.cpp
- layers/stateless_validation.h
- tests/vklayertests_gpu.cpp
> Validate validation features

- layers/parameter_validation_utils.cpp
VUID-VkGraphicsPipelineCreateInfo-flags-00764
> layers: Add VUID 00764

- layers/buffer_validation.cpp
- tests/vklayertests_buffer_image_memory_sampler.cpp
VUID-VkBufferViewCreateInfo-offset-00926
> layers: Add VUID 00926

- layers/buffer_validation.cpp
- tests/vklayertests_buffer_image_memory_sampler.cpp
VUID-VkImageMemoryBarrier-image-01207
> layers: Add VUID 01207

- tests/vklayertests_buffer_image_memory_sampler.cpp
> Remove duplicate feature being set

- layers/parameter_validation_utils.cpp
- tests/vklayertests_others.cpp
VUID-VkPhysicalDeviceVariablePointersFeatures-variablePointers-01431
> Add VUID 01431 in VK_KHR_variable_pointers

- tests/vklayertests_buffer_image_memory_sampler.cpp
Ran into some tests failing on some devices due to this not being wrapped in `FragmentDensityMapEnabled`
> Add samplerAnisotropy check

- layers/core_validation.cpp
VUID-VkBindBufferMemoryInfo-buffer-01593
VUID-VkBindBufferMemoryInfo-buffer-01594
VUID-VkBindBufferMemoryInfo-memoryOffset-01595
VUID-VkBindImageMemoryInfo-image-01609
VUID-VkBindImageMemoryInfo-image-01610
VUID-VkBindImageMemoryInfo-memoryOffset-01611
> Label BindMemory2 VUIDs

- layers/core_validation.cpp
There is not a VUID for this check, so remove it until there is.  MR to add to spec is in progress.
> Removal of check for border color feature

- layers/core_validation.cpp
VUID-VkBindBufferMemoryInfo-memory-01599
VUID-VkBindBufferMemoryInfo-memoryOffset-01600
VUID-VkBindBufferMemoryInfo-size-01601
VUID-VkBindBufferMemoryInfo-memory-01900
Also part to help #1870 by moving the `if (mem_info) {` into single section
> Label BindBufferMemory2 VUIDs

- layers/generated/spirv_tools_commit_id.h
- scripts/known_good.json
Changes:
- Updated known-good file
- Generated new source files using `generate_source.py`
Change-Id: I6be54bac3c08b24d289a947a541cae0ae3a21fdf
> build: Update known-good file for 1.2.141 SDK

- layers/core_validation.cpp
- tests/vklayertests_command.cpp
VUID-vkBeginCommandBuffer-commandBuffer-02840
> Add VUID 02840

- layers/core_validation.cpp
- tests/vklayertests_descriptor_renderpass_framebuffer.cpp
If flags does not include VK_FRAMEBUFFER_CREATE_IMAGELESS_BIT, each element of pAttachments that is a 2D or 2D array image view taken from a 3D image must not be a depth/stencil format.
Passed internal CI.
Fixes #1872.
> Add validation, test for VUID-VkFramebufferCreateInfo-pAttachments-00891

- docs/khronos_validation_layer.md
Trivial bug fix for a broken link. This is my first PR, I tried to follow the convention but I don't exclude that I messed up.
> docs: Fix link to LAYER_CONFIGURATION.md, issue #1902

- layers/buffer_validation.cpp
- tests/vklayertests_command.cpp
Added
VUID-VkImageCopy-srcImage-00139
VUID-VkImageCopy-layerCount-00138
and then regroup logic to group the pre and post maintenance1 extension logic as there was duplicated logic going on
> Label and fix Maintenance1 VUs

- layers/core_validation.cpp
- layers/descriptor_sets.cpp
- layers/state_tracker.cpp
- tests/vklayertests_descriptor_renderpass_framebuffer.cpp
> Allow descriptor validation for push descriptors

- layers/gpu_validation.cpp
Fixes crash in running CTS with GPU-AV enabled
> Record destroy of buffers and devices

- layers/parameter_validation_utils.cpp
- tests/vklayertests_others.cpp
VUID-VkPhysicalDeviceMultiviewFeatures-multiviewGeometryShader-00580
VUID-VkPhysicalDeviceMultiviewFeatures-multiviewTessellationShader-00581
> Add VUID 00580 and 00581

- BUILD.md
- CMakeLists.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/khronosgroup/vulkan-validationlayers/1843)
> Build system fixes

- layers/descriptor_sets.cpp
- tests/vklayertests_descriptor_renderpass_framebuffer.cpp
VUID-VkWriteDescriptorSet-descriptorType-01946
> Add VUID 01946

- layers/core_validation.cpp
- layers/core_validation_types.h
- layers/state_tracker.cpp
- layers/state_tracker.h
- tests/vklayertests_others.cpp
- tests/vktestbinding.cpp
- tests/vktestbinding.h
fixes spurious validation error
VUID-VkAccelerationStructureBuildGeometryInfoKHR-update-03538
> layers:Add missing KHR build info tracker

- layers/core_validation.cpp
- tests/vklayertests_others.cpp
Closes #1927 
Adds VUID-vkCmdCopyQueryPoolResults-queryType-00827
> Add VUID 00827

- BUILD.gn
Also reformats the GN files. Necessary for rolling in new headers in
Chrome/ANGLE.
@courtney-g FYI
> Fix GN header dependencies.

- layers/core_validation.cpp
- tests/vklayertests_others.cpp
Addresses #1935 
Still WIP as test will fail due explanation on not having "valid" external format for AHB
> Remove invalid check for AHB format

- layers/core_validation_types.h
- layers/descriptor_sets.cpp
Indicates if create_infoKHR is valid
> layers: Add is_khr to acceleration_structure_state

- layers/buffer_validation.cpp
- layers/state_tracker.cpp
> layers: Fix DRM format properties accesses

- tests/vklayertests_buffer_image_memory_sampler.cpp
Test has been failing for a while.  Adding drivers with support for custom border color to internal CI
> Fix unexpected custom border color error

- layers/buffer_validation.cpp
From spec
> if any call to vkGetPhysicalDeviceImageFormatProperties2 returns an error then imageCreateImageFormatPropertiesList is defined to be the empty list.
So error can be anything that isn't `VK_SUCCESS`
> layers: Label VUID 02251

- layers/buffer_validation.cpp
- tests/vklayertests_buffer_image_memory_sampler.cpp
VUID-VkImageCreateInfo-extent-02252
VUID-VkImageCreateInfo-extent-02253
VUID-VkImageCreateInfo-extent-02254
> Add maxExtent VUIDs

- layers/buffer_validation.cpp
- layers/parameter_validation_utils.cpp
- tests/vklayertests_buffer_image_memory_sampler.cpp
VUID-VkImageSwapchainCreateInfoKHR-swapchain-00995
> Add VkImageSwapchainCreateInfoKHR VUID

- layers/gpu_validation.cpp
Cover degenerate case where the pipeline layout has been destroyed between pipeline creation and draw
> gpu: Handle destroyed pipeline layout

- layers/core_validation.cpp
- layers/descriptor_sets.cpp
Spec recently updated to add more disqualified formats and to require feature to be enabled
> Add more custom border color checks

- layers/debug_printf.cpp
- layers/gpu_validation.cpp
- layers/shader_validation.cpp
- layers/shader_validation.h
- layers/state_tracker.cpp
> Use helper to pick spirv env

- layers/generated/chassis.h
- scripts/layer_chassis_generator.py
Was replaced with the official VK_VALIDATION_FEATURE_ENABLE_DEBUG_PRINTF_EXT
> Remove leftover enum

- layers/parameter_validation_utils.cpp
- tests/vklayertests_buffer_image_memory_sampler.cpp
VUID-VkImageViewCreateInfo-pNext-01970
VUID-VkSamplerYcbcrConversionCreateInfo-components-02581
VUID-VkSamplerYcbcrConversionCreateInfo-components-02582
VUID-VkSamplerYcbcrConversionCreateInfo-components-02583
VUID-VkSamplerYcbcrConversionCreateInfo-components-02584
VUID-VkSamplerYcbcrConversionCreateInfo-components-02585
> Add YCbCr Swizzle VUIDs

- layers/debug_printf.cpp
- layers/gpu_validation.cpp
Issue reported at Lunar Exchange noting that when instrumentation fails, no reason is reported
> Report errors when shader GPU-AV instrumentation fails

- layers/best_practices_utils.cpp
- layers/best_practices_validation.h
Fixes #2018 
I'll run CTS on this tonight.
> Make copies of createInfos in Best Practices

- layers/subresource_adapter.cpp
- layers/subresource_adapter.h
- tests/vklayertests_buffer_image_memory_sampler.cpp
Image aspect also affect sub extent, not only mip level.
> Some bug fix in sync val

- docs/khronos_validation_layer.md
- Add links to the per feature docs where missing. 
- Add synchronization validation to the list of features
- Add a note to express the performance degradation when using multiple of these features.
> doc: Add links to per-feature docs

- docs/synchronization.md
- docs/synchronization_usage.md
Cleanup the the style of the design doc and add a user document suitable
for SDK documentation.
> Style cleanup design doc/add user doc

- build-android/known_good.json
- docs/gpu_validation.md
- layers/debug_printf.cpp
- layers/debug_printf.h
- layers/gpu_utils.cpp
- layers/gpu_validation.cpp
- layers/gpu_validation.h
- tests/vklayertests_gpu.cpp
It would be nice to get this into next week's SDK
> Add debug printf and GPU-AV to mesh and task shaders

- tests/vklayertests_descriptor_renderpass_framebuffer.cpp
Test was failing on my devsim setup
> tests: Add depth stencil format check

- tests/vklayertests_buffer_image_memory_sampler.cpp
Test was failing on my devsim setup
> tests: Add format check for YCbCr swizzle

- layers/core_validation.cpp
- tests/vklayertests_pipeline_shader.cpp
Adds validation check for VUID-VkGraphicsPipelineCreateInfo-coverageReductionMode-02722
> Add validation support for VK_NV_coverage_reduction_mode

- layers/parameter_validation_utils.cpp
- tests/vklayertests_buffer_image_memory_sampler.cpp
VUID-VkSamplerYcbcrConversionCreateInfo-ycbcrModel-01655
> Add VUID 01655

- layers/buffer_validation.cpp
- tests/vklayertests_buffer_image_memory_sampler.cpp
- tests/vklayertests_command.cpp
VUID-vkCmdClearDepthStencilImage-image-02825
VUID-vkCmdClearDepthStencilImage-image-02826
> Add VUID 02825 and 02826

- layers/core_validation.cpp
- layers/core_validation_types.h
- layers/state_tracker.cpp
- tests/vklayertests_buffer_image_memory_sampler.cpp
- tests/vklayertests_others.cpp
Added state_tracker flag for multi-instance, validation check, and test.  Passes internal CI.
Fixes #294.
> Implement VUID 00683, mapping memory from multi-instance heap

- layers/core_validation.cpp
- tests/vklayertests_others.cpp
> Add check and add test for VUID 00824

- layers/buffer_validation.cpp
- tests/vklayertests_command.cpp
Related to #1996 
VUID-vkCmdClearAttachments-commandBuffer-02504
VUID-vkCmdClearAttachments-commandBuffer-02505
> Add Protected clear attachment

- layers/synchronization_validation.cpp
- tests/vklayertests_buffer_image_memory_sampler.cpp
> Fix wrong SYNC-HAZARD-NONE log

- layers/core_validation.cpp
- layers/state_tracker.cpp
- layers/state_tracker.h
- tests/vklayertests_buffer_image_memory_sampler.cpp
> Add validation for VUID 01429

- layers/core_validation.cpp
- tests/vklayertests_command.cpp
> layers: Fix TransformFeedback size check

- BUILD.md
> Clarify use of BUILD_LAYER_SUPPORT_FILES

- layers/buffer_validation.cpp
- layers/core_validation.h
- layers/core_validation_types.h
- layers/state_tracker.cpp
- tests/vklayertests_command.cpp
Closes: #2113 
It will be a while until the label of the VU comes through, but will re-label when it happens, but for now this should be enough to close the issue
> Add Depth/Stencil BufferImageCopy VU

- layers/core_validation.cpp
Removing redundant VUID in spec and approved in internal meeting so can go ahead and remove this `todo`
> layers: Remove 03269 todo

- layers/core_validation.cpp
- layers/core_validation.h
- layers/core_validation_error_enums.h
reworked function to take VUs and removed TODO while labeling the VUs
VUID-vkQueueSubmit-fence-00064
VUID-vkQueueBindSparse-fence-01114
VUID-vkAcquireNextImageKHR-fence-01287
VUID-vkQueueSubmit-fence-00063
VUID-vkQueueBindSparse-fence-01113
> layers: Label ValidateFenceForSubmit VUs

- layers/core_validation.cpp
- layers/core_validation.h
Added label for `VUID-vkImportFenceFdKHR-fence-01463`
Raised issue in working group about adding the same VU for `VkImportFenceWin32HandleInfoKHR` but for now leaving as the same unassigned VU
> layers: Label import fence VUs

- layers/core_validation.cpp
Realized these just made it in 151 headers, just following through the TODOs I added for unassigned VUs
> layers: Label bind2 protected VUs

- layers/core_validation.cpp
- tests/vklayertests_command.cpp
- tests/vklayertests_others.cpp
Addresses #1996
- VUID-VkProtectedSubmitInfo-protectedSubmit-01816
- VUID-VkProtectedSubmitInfo-protectedSubmit-01817 (which will be relabeled in future header update as noted with spec fix in the works)
- VUID-VkSubmitInfo-pNext-04120
> Add ProtectedSubmitInfo VUs

- layers/buffer_validation.cpp
- layers/core_validation.cpp
- layers/core_validation_types.h
- layers/descriptor_sets.cpp
Change-Id: I2ee9b32e516deeb30642daeebf3ddf9b56a333b4
> layers: Get imageview from imageless framebuffer

- layers/parameter_validation_utils.cpp
VUID-VkImageCreateInfo-tiling-04121
VUID-VkPipelineRasterizationStateCreateInfo-polygonMode-01413
VUID-VkPresentRegionsKHR-swapchainCount-01260
missed `sType-sType`
> Label unassigned VUs

- scripts/vk_validation_stats.py
Closes #2141 
Marked as WIP until https://github.com/KhronosGroup/SPIRV-Tools/pull/3756 is merged
This allows you to go
```
python vk_validation_stats.py validusage.json -spirvtools SPIRV-Tools/
```
> scripts: Add SPIRV-Tools option to stats

- layers/synchronization_validation.cpp
Centralize (DRY) WHOLE_SIZE support and clean up range compute for buffer hazard checks. Fixes #2166, where WHOLE_SIZE computation is missing in some cases.
> syncval: DRY/clean MakeRange computation

- layers/core_validation.cpp
VUID-vkImportFenceWin32HandleKHR-fence-04448
> layers: label VUID 04448

- layers/core_validation.cpp
Can across a WSI error and it was less than informative, so cleaned up some WSI related error messages
> layers: Improve WSI related error messages

- layers/debug_printf.cpp
- layers/debug_printf.h
- layers/gpu_validation.cpp
- layers/gpu_validation.h
Forgot the KHR versions in d13f9b59
> Handle KHR version of CmdDispatchBase

- layers/descriptor_sets.cpp
- tests/vklayertests_buffer_image_memory_sampler.cpp
I recently added to the spec to label
VUID-VkWriteDescriptorSet-descriptorType-04151
VUID-VkWriteDescriptorSet-descriptorType-04152
> layers: label VUID 04151 and 04152

- tests/vklayertests_others.cpp
When running with a 1.0 VK instance with `VK_KHR_depth_stencil_resolve` supported it breaks
> tests: Fix UnsupportedPnextApiVersion on 1.0

- layers/generated/spirv_tools_commit_id.h
- scripts/known_good.json
Change-Id: Ib7bf4495ea52f5b35d84bbb444140d1851200042
> build: Update glslang commit for 154 SDK

- layers/descriptor_sets.cpp
- tests/vklayertests_descriptor_renderpass_framebuffer.cpp
Robustness2 permits samplers with NULL image views.
> Allow for a sampler with a NULL image view

- build-android/known_good.json
> build: Update Android known-good for 1.2.154 SDK

- layers/debug_printf.cpp
- layers/state_tracker.h
> Fix debug printf save and restore of PipelineCreateInfos

- layers/best_practices_utils.cpp
- layers/best_practices_validation.h
- layers/core_validation.cpp
- layers/core_validation.h
- layers/generated/parameter_validation.cpp
- layers/parameter_validation_utils.cpp
- layers/stateless_validation.h
- scripts/parameter_validation_generator.py
Closes #2272
Went through and fixed/added some other 1.2 functions to keep everything consistent
> layers: Add missing 1.2 overload functions

- layers/core_validation.h
- layers/shader_validation.cpp
- tests/vklayertests_pipeline_shader.cpp
From inactive #1950 
I just removed the clip/control part as still need to address @jeffbolznv comments, but the `SampleMask` built in seemed fine and rather get something in then wait until I get around to fix the clip/control part
VUID-VkPipelineShaderStageCreateInfo-maxSampleMaskWords-00711
> Add SampleMask Array Limit VUID

- layers/core_validation.cpp
- layers/core_validation.h
- tests/vklayertests_buffer_image_memory_sampler.cpp
General cleanup on some log messages to add API name to error
Labled `VUID-vkCreateSampler-maxSamplerAllocationCount-04110`
> layers: Add extra api names to errors

- tests/vklayertests_buffer_image_memory_sampler.cpp
Missed running the last commit from #2276 through internal CI. This
should resolve the error.
Change-Id: I084b4b7c5da564ab2fbf98e79d559928d3b525aa
> layers: Fix test error introduced by #2276

- layers/synchronization_validation.h
Change-Id: I6b914e0fd8bd607da47438aeeea06ea824340dc6
> syncval: Add override keyword to ValidationObject method overrides.

- layers/descriptor_sets.cpp
- tests/vklayertests_descriptor_renderpass_framebuffer.cpp
Addresses #2238  Also cleans up StringifySetAndLayout
> Add validation for variable count descriptor arrays

- layers/gpu_utils.cpp
> Report OpLine info from GPU-AV, even if no source

- layers/parameter_validation_utils.cpp
- layers/stateless_validation.h
- tests/vklayertests_command.cpp
Picked off a couple of security vuids and removed some cruft from stateless validation, including some warnings that are out of place.
> Add remaining 02728 Security VUIDs, stateless validation cleanup

- layers/core_validation.cpp
- layers/parameter_validation_utils.cpp
VUID-vkAllocateMemory-maxMemoryAllocationCount-04101
VUID-VkApplicationInfo-apiVersion-04010
> layers: Label 04101 and 04010

- layers/core_validation.cpp
- layers/core_validation.h
- tests/vklayertests_imageless_framebuffer.cpp
VUID-VkFramebufferCreateInfo-flags-04113
VUID-VkRenderPassAttachmentBeginInfo-pAttachments-04114
added function name pass through to `VerifyFramebufferAndRenderPassImageViews()` for message
> Add VUID 04113 and 04114

- layers/core_validation.cpp
Simple labeling of `VUID-VkSubpassDescription2-attachment-04563` from recent header
> layers: Label VU 04563

- layers/core_validation.cpp
- tests/vklayertests_command.cpp
VUID-vkCmdExecuteCommands-pCommandBuffers-00094
> Label 00094 and add test for it

- layers/core_validation.cpp
- tests/vklayertests_buffer_image_memory_sampler.cpp
VUID-VkMappedMemoryRange-size-01389
> Add VUID 01389

- layers/core_validation.h
- layers/drawdispatch.cpp
- layers/parameter_validation_utils.cpp
- layers/stateless_validation.h
- tests/vklayertests_others.cpp
Also change count parameter to drawCount to match the API
> Add VUIDs 02719, 00539, and 00487

- build-android/known_good.json
- layers/generated/spirv_tools_commit_id.h
- scripts/known_good.json
Changes:
- Updated known-good files
- Generated new source files using `generate_source.py`
Passed internal CI
> build: Update known-good files for 1.2.162 SDK

- layers/generated/parameter_validation.cpp
- layers/stateless_validation.h
- scripts/parameter_validation_generator.py
- tests/vklayertests_others.cpp
- tests/vkrenderframework.cpp
- tests/vkrenderframework.h
I randomly came across this a while ago and finally got time to just dig into the XML/Python code.
Added generated logic to expose missing implicit VUs for array length
Added a test to cover the various edge cases missing as well
> Add missing implicit arrayLength VUs

- tests/layer_validation_tests.cpp
I normally have a script to kick off the test on Android that will kill the previous process, but the script was lost and decided to just fix the code itself.
The issue is if you run the test suite twice in a row, the app was never properly destroyed and won't initialize properly the second time
Feel free to [poke Dustin](https://github.com/LunarG/gfxreconstruct/commit/5f596d56f2dad58d7c67e97b6180262b26186d50) if you need more convincing this is the correct change to make :laughing:
> tests: Properly end android APK

- layers/shader_validation.cpp
- tests/vklayertests_pipeline_shader.cpp
Closes #2383 
@Tony-LunarG please verify this fix the CTS issue you had
Was simple fix and added an extra test as well
> layers: Fix OpGroupNonUniformPartitionNV check

- layers/descriptor_sets.cpp
Fix an incorrect runtime type cast.
This is to resolve issue #2391.
> layers: Fix Github issue 2391

- layers/core_validation.cpp
- layers/core_validation.h
- layers/generated/parameter_validation.cpp
- layers/parameter_validation_utils.cpp
- layers/state_tracker.cpp
- layers/state_tracker.h
- layers/stateless_validation.h
- scripts/parameter_validation_generator.py
- tests/vklayertests_others.cpp
- VUID-VkDisplaySurfaceCreateInfoKHR-planeIndex-01252
- VUID-VkDisplaySurfaceCreateInfoKHR-alphaMode-01254
- VUID-VkDisplaySurfaceCreateInfoKHR-alphaMode-01255
- VUID-VkDisplaySurfaceCreateInfoKHR-width-01256
- VUID-VkDisplayModeParametersKHR-width-01990
- VUID-VkDisplayModeParametersKHR-height-01991
- VUID-VkDisplayModeParametersKHR-refreshRate-01992
> Add VK_KHR_display VUs

- layers/stateless_validation.h
Addresses #2398
@mark-lunarg can do this for other files if desired too, I have the script to quickly do it locally
> layers: core alias name in stateless_validation

- layers/parameter_validation_utils.cpp
- layers/state_tracker.cpp
- layers/stateless_validation.h
pInheritanceInfo must be ignored when beginning primary command buffers
> Handle invalid pInheritanceInfo

- docs/best_practices.md
> Update best practices doc for ARM vendor enable

- layers/stateless_validation.h
> layers: Add missing 'override' keyword.

- .github/workflows/ci_build.yml
- scripts/check_code_format.py
Same idea as #2418 but for master and all Travis references removed.
> build: Fix format check on PRs

- layers/descriptor_sets.cpp
- layers/shader_validation.cpp
- tests/vklayertests_pipeline_shader.cpp
Re-upload of #2011 (deferred) 
Pleasant surprise that my original issue was fixed in #2182 and these extra test pass. They test if the descriptor types are `VK_DESCRIPTOR_TYPE_SAMPLED_IMAGE` and `VK_DESCRIPTOR_TYPE_SAMPLER`
> Extra tests for 04553

- layers/parameter_validation_utils.cpp
- tests/vklayertests_buffer_image_memory_sampler.cpp
Waiting on #2459 to merge first
Adds 
- VUID-VkImageCreateInfo-format-04712
- VUID-VkImageCreateInfo-format-04713
> layers: Add VUID 04712 and 04713

- layers/debug_printf.cpp
- layers/debug_printf.h
> Fix Debug Printf in CreateRayTracingPipelinesKHR

- layers/core_validation.cpp
- layers/core_validation_error_enums.h
- layers/parameter_validation_utils.cpp
- tests/vklayertests_command.cpp
- tests/vklayertests_others.cpp
- tests/vklayertests_pipeline_shader.cpp
VUID-VkGraphicsPipelineCreateInfo-stage-00726
VUID-vkQueueSubmit-pSubmits-04626
VUID-vkCmdDrawIndirectByteCountEXT-counterBufferOffset-04568
VUID-VkPipelineShaderStageCreateInfo-pName-00707
VUID-VkPipelineRasterizationStateCreateInfo-polygonMode-01413
> layers: Remove some unassigned labels

- layers/parameter_validation_utils.cpp
- tests/vklayertests_others.cpp
VUID-VkDeviceCreateInfo-ppEnabledExtensions-04476
> Add VUID 04476 for shaderDrawParameters

- layers/core_validation.cpp
`VUID-VkPresentInfoKHR-pImageIndices-01430`/`VUID-VkPresentInfoKHR-pImageIndices-01296` covered more VUs
> layers: Label vkQueuePresentKHR VU

- layers/generated/parameter_validation.cpp
- layers/parameter_validation_utils.cpp
- layers/stateless_validation.h
- scripts/parameter_validation_generator.py
- tests/vklayertests_others.cpp
VUID-vkCreatePrivateDataSlotEXT-privateData-04564
> Add privateData feature VUID

- layers/core_validation.cpp
- layers/core_validation_types.h
- layers/state_tracker.cpp
- tests/vklayertests_imageless_framebuffer.cpp
Fixes from https://github.com/KhronosGroup/Vulkan-Docs/issues/1391
> Add inherited usage edge case

- layers/shader_validation.cpp
- tests/vkpositivelayertests.cpp
> Fix shader validation with fragment shading rate enabled 

- layers/parameter_validation_utils.cpp
- tests/vklayertests_others.cpp
VUID-VkGraphicsPipelineCreateInfo-pDynamicStates-04132
VUID-VkGraphicsPipelineCreateInfo-pDynamicStates-04133
> Add VUID 04132 and 04133

- layers/buffer_validation.cpp
- tests/vklayertests_command.cpp
So this should be adding support for
VUID-vkCmdCopyBufferToImage-commandBuffer-04052
VUID-vkCmdCopyImageToBuffer-commandBuffer-04052
VUID-VkCopyBufferToImageInfo2KHR-commandBuffer-04052
VUID-VkCopyImageToBufferInfo2KHR-commandBuffer-04052
VUID-vkCmdCopyBufferToImage-srcImage-04053
VUID-vkCmdCopyImageToBuffer-srcImage-04053
VUID-VkCopyBufferToImageInfo2KHR-srcImage-04053
VUID-VkCopyImageToBufferInfo2KHR-srcImage-04053
Note the current VUs don't line up but should when
https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/4344
lands
> Add bufferOffset for copy bufferimage

- layers/buffer_validation.cpp
- layers/core_validation.cpp
- layers/core_validation.h
- tests/layer_validation_tests.cpp
- tests/layer_validation_tests.h
- tests/vklayertests_buffer_image_memory_sampler.cpp
- tests/vklayertests_pipeline_shader.cpp
VUID-VkClearDepthStencilValue-depth-02506
VUID-VkGraphicsPipelineCreateInfo-pDynamicStates-02510
VUID-vkCmdSetDepthBounds-minDepthBounds-02508
VUID-vkCmdSetDepthBounds-maxDepthBounds-02509
(and technically)
VUID-VkClearDepthStencilValue-depth-00022
VUID-VkGraphicsPipelineCreateInfo-pDynamicStates-00755
VUID-vkCmdSetDepthBounds-minDepthBounds-00600
VUID-vkCmdSetDepthBounds-maxDepthBounds-00601
> Add VK_EXT_depth_range_unrestricted support

- layers/core_validation.cpp
- tests/vklayertests_imageless_framebuffer.cpp
> Fix framebuffer width/height compares to consider imageview mip level

- layers/core_validation_error_enums.h
- layers/generated/spirv_validation_helper.cpp
- layers/shader_validation.cpp
- scripts/spirv_validation_generator.py
- tests/vklayertests_others.cpp
- tests/vkpositivelayertests.cpp
- tests/vkrenderframework.cpp
- tests/vkrenderframework.h
This is a first pass at handling push constants using the
PhysicalStorageBuffer storage class.
This is for resolving Github issues #2465 and #2467.
> layers: Fix references in push constants

- layers/buffer_validation.cpp
- tests/vklayertests_buffer_image_memory_sampler.cpp
> layers: Improved ValidateImageAspectMask wording

- layers/core_validation_types.h
From https://github.com/KhronosGroup/Vulkan-Docs/issues/1433
Simple fix and only spot I found with similar issue
cc @dgkoch
> layers: Add missing RayTracing KHR alias struct

- layers/parameter_validation_utils.cpp
- tests/vklayertests_pipeline_shader.cpp
VUID-VkGraphicsPipelineCreateInfo-pDynamicStates-03578
> Add VUID 03578

- docs/creating_tests.md
- tests/vklayertests_others.cpp
- tests/vkpositivelayertests.cpp
Added information about new `VK_DEVSIM_MODIFY_EXTENSION_LIST` in devsim
Fixed various tests that were failing for me on devsim/mockicd
> Fix various tests failing on MockICD

- layers/state_tracker.cpp
- layers/state_tracker.h
- layers/subresource_adapter.h
- layers/synchronization_validation.cpp
- layers/synchronization_validation.h
- layers/vk_layer_data.h
Changes to Resource State, Tagging, and operation encapsulation to support Synchronization Phase 2 development.  Represents intermediate state, but merging as the changes are non-disruptive, and to minimize the size of the development branch.
> Sync phase 2 preparatory changes.

- layers/synchronization_validation.cpp
Restore the SimpleBinding() guards for image address access type and
range generator creation.
h/t @karl-lunarg for finding the missing return... good catch.
Fixes #2530
> Guard image access of non-simple bindings

- build-android/known_good.json
- layers/debug_printf.cpp
- layers/debug_printf.h
- layers/generated/spirv_tools_commit_id.h
- layers/gpu_utils.h
- layers/gpu_validation.cpp
- layers/gpu_validation.h
- layers/gpu_vuids.h
- scripts/known_good.json
- tests/vklayertests_gpu.cpp
This needs a new glslang but presenting the code for review
> Use VUIDs for buffer oob GPU-AV errors

- docs/synchronization.md
Change-Id: Ibac3f47e875877f3203b58bd0b1d919d74bde0aa
> syncval: Update documentation for synchronization2

- build-android/known_good.json
- layers/generated/spirv_tools_commit_id.h
- scripts/known_good.json
Update glslang, SPIRV-Headers, SPIRV-Tools, and Vulkan-Tools
known goods to latest tested commits for these projects.
Change-Id: I2be26741fa661600f5aff04838e4bcec77234b51
> build: Update known-good files for 1.2.170 SDK

- layers/core_validation.cpp
> layers: Fix using wrong extent for 03212

- docs/synchronization_usage.md
Add the extension and its relevant commands to the
"Current Feature Set" section.
Change-Id: I21f87345ff43c86857193475b4b52083c968e2d5
> docs: Update synval usage document for synchronization2

- layers/buffer_validation.cpp
- layers/sync_vuid_maps.cpp
- layers/sync_vuid_maps.h
2 hotspots identified by @jzulauf-lunarg 's profiling
> sync2 perf changes (part 1)

- layers/buffer_validation.cpp
- layers/core_error_location.cpp
- layers/core_error_location.h
- layers/core_validation.cpp
- layers/core_validation.h
- layers/sync_vuid_maps.h
- layers/vk_layer_data.h
- layers/vk_layer_logging.h
additional set of performance changes to keep Sync2 performance neutral
> Sync2 performance tuning (part 2)

- CMakeLists.txt
- layers/CMakeLists.txt
- layers/vk_layer_logging.h
Also update the size type for LogObjectList.
> Build fix for older versions of VS

- layers/core_error_location.cpp
Change-Id: I8b24366308c6caddfab35dd986c8ed6ac5bccf8a
> corechecks: Add license header to core_error_location.cpp

- layers/parameter_validation_utils.cpp
Change-Id: Ibee54a6675305b653fa9f5227fe9c7477726ee74
> layers: Correct drm_format_mod_explicit nullptr check

- layers/shader_validation.cpp
cc: @jeffbolznv to make sure I am not missing anything obvious here.
> layers: ValidateCooperativeMatrix only if support

- layers/synchronization_validation.cpp
Initial revision had excess support for multiple barrier sets which the
entry point doesn't support, which is now removed.
Fixes #2560
> syncval: Cleanup vkPipelineBarrier2 validation

- layers/state_tracker.cpp
- tests/vklayertests_others.cpp
Handle null pointer dereferences or out of bounds accesses if
the SemaphoreValues arrays are null or incorrectly sized.
Add a test case that prevents this regression from happening again.
Fixes #2616
> layers: Fix recording of VkTimelineSemaphoreSubmitInfo

- layers/buffer_validation.cpp
- tests/vklayertests_buffer_image_memory_sampler.cpp
> Fix CompatibilityClass edge case

- docs/best_practices.md
- docs/core_checks.md
- docs/debug_printf.md
- docs/gpu_validation.md
- docs/handle_wrapping.md
- docs/images/sync_diagram_source.txt
- docs/khronos_validation_layer.md
- docs/object_lifetimes.md
- docs/stateless_validation.md
- docs/synchronization.md
- docs/synchronization_usage.md
- docs/thread_safety.md
No license will be found in file and will default to repository Apache 2.0 license.
Fixes issue #2652
> docs: Remove Creative Commons License.

- layers/generated/vk_enum_string_helper.h
- layers/stateless_validation.h
- scripts/helper_file_generator.py
- tests/vkpositivelayertests.cpp
Adds support for structures with allowduplicate="true".
Closes #2671.
> Allow duplicate pNext structure types

- tests/vklayertests_buffer_image_memory_sampler.cpp
- tests/vkpositivelayertests.cpp
A couple of changes that fix test problems I found running VLTs on IGFX and RADV.  This is not an exhaustive fix.
> Fix up test issues found running VLTs on IGFX & RADV

- layers/descriptor_sets.cpp
- layers/descriptor_sets.h
- layers/shader_validation.cpp
Fix assert failure and false positives
Add skeleton structs for future VUID validation (coming sort of soon)
> Add compatibility validation for mutable descriptors

- layers/buffer_validation.cpp
- layers/core_validation.cpp
This template method is causing undefined symbols in some MacOS builds.
Change-Id: I2515300f4d53448c2f23cc7c4cfe018128168c82
> corecheck: Explicitly instantiate ComputeBarrierOperationsType()

- layers/buffer_validation.cpp
- layers/parameter_validation_utils.cpp
- tests/vklayertests_buffer_image_memory_sampler.cpp
- VUID-VkImageViewCreateInfo-pNext-01585
- VUID-VkImageViewCreateInfo-pNext-04082
- VUID-VkImageViewCreateInfo-flags-04083
> Add VK_KHR_image_format_list

- tests/CMakeLists.txt
- tests/vkrenderframework.cpp
At the request of our internal CI team
> Add environment variable to print driver info in VLTs

- layers/descriptor_sets.cpp
- tests/vklayertests_descriptor_renderpass_framebuffer.cpp
Added tests to check for consecutive bindings updated via a single `VkWriteDescriptorSet` structure without identical `VkDescriptorBindingFlagBits`
With this, improved the error message to print "what" was not consistent
As for `todo` remove, internal spec fix purposed
> Improve non-consistent descriptor update message

- layers/parameter_validation_utils.cpp
- tests/vklayertests_pipeline_shader.cpp
Adds
- VUID-VkComputePipelineCreateInfo-flags-03364
- VUID-VkComputePipelineCreateInfo-flags-03365
- VUID-VkComputePipelineCreateInfo-flags-03366
- VUID-VkComputePipelineCreateInfo-flags-03367
- VUID-VkComputePipelineCreateInfo-flags-03368
- VUID-VkComputePipelineCreateInfo-flags-03369
- VUID-VkComputePipelineCreateInfo-flags-03576
- VUID-VkComputePipelineCreateInfo-flags-02874
> Add compute pipeline invalid flags

- layers/core_validation.cpp
- layers/core_validation.h
- tests/vklayertests_descriptor_renderpass_framebuffer.cpp
Adds 
- VUID-VkAttachmentReference2-attachment-04754
- VUID-VkAttachmentReference2-attachment-04755
- VUID-VkAttachmentReference2-attachment-04756
- VUID-VkAttachmentReference2-attachment-04757
> Add VkAttachmentReference2 VUs

- layers/core_validation.cpp
- layers/core_validation_types.h
- layers/generated/parameter_validation.cpp
- layers/parameter_validation_utils.cpp
- layers/state_tracker.cpp
- layers/stateless_validation.h
- scripts/parameter_validation_generator.py
- tests/vklayertests_others.cpp
Spec is here: https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_EXT_vertex_input_dynamic_state.html
> Validation for VK_EXT_vertex_input_dynamic_state

- layers/vk_layer_config.cpp
Fixes reading setprop values on Android.
Closes #2733
> layers: Fix reading android settings bug

- layers/drawdispatch.cpp
Add label for `VUID-vkCmdDrawIndirectByteCountEXT-counterBuffer-04567`
> layers: Label vkCmdDrawIndirectByteCountEXT VUID

- layers/range_vector.h
- tests/vkpositivelayertests.cpp
Commit a72a0b1d introduced a bug into splice where it incorrectly splits existing ranges in some cases.
Add 2 unit tests to prevent this from regressing again.
Fixes #2793
> layers: Fix sparse_container::splice()

- docs/debug_printf.md
- layers/debug_printf.cpp
- tests/vklayertests_gpu.cpp
> Add %lu and %lx to debug printf

- layers/gpu_validation.cpp
Replace invalid UTF-8 character with "*".
> layers: Fix invalid UTF-8 character

- layers/best_practices_utils.cpp
> layers: Fix API name

- layers/core_validation.cpp
> layers: Fix one fragment_shading_rate crash

- .github/workflows/build_android.yml
- .github/workflows/build_linux.yml
- .github/workflows/build_linux_gn.yml
- .github/workflows/build_windows.yml
- README.md
Also split up builds into separate config files.
> build: Fix README build badges

- layers/best_practices_utils.cpp
Cannot use baseArrayLayer, the entire 3D subresource is technically
accessed.
Closes #2827.
> practices: Fix crash when rendering to 3D image slices

- layers/state_tracker.cpp
DEVICE_MEMORY_STATE::RemoveParent() has to manage its bound_images
set when an IMAGE_STATE parent is removed. Check the handle type before
doing this, to avoid miscasting a BUFFER_STATE or ray tracing state.
The bound_images tracking scheme needs further cleanup, which will
be done as part of upcoming state tracker refactoring.
Fixes #2825
> layers: Fix Control Flow Integrity in DEVICE_MEMORY_STATE

- layers/drawdispatch.cpp
- tests/vkpositivelayertests.cpp
Mainly creating this PR to test proposed changes to #2605 while including the tests from #2608 and some additional tests 1.2 tests.
> Check drawIndirectCount enabled by feature and extension

- layers/best_practices_error_enums.h
- layers/best_practices_utils.cpp
- layers/core_validation.cpp
- layers/core_validation.h
- layers/core_validation_error_enums.h
- scripts/vk_validation_stats.py
- tests/vklayertests_best_practices.cpp
> layers: Move SwapchainInvalidCount to BP

- tests/vklayertests_pipeline_shader.cpp
From #2835
Mocked issue's shader in a test to make sure the validation is working correctly when a single location has too many components and walking the code it seems it should be correctly validating it
> tests: Add single block max components test

- tests/vklayertests_buffer_image_memory_sampler.cpp
- tests/vklayertests_command.cpp
- tests/vklayertests_descriptor_renderpass_framebuffer.cpp
- tests/vklayertests_gpu.cpp
- tests/vklayertests_others.cpp
- tests/vkpositivelayertests.cpp
- tests/vkrenderframework.cpp
- tests/vkrenderframework.h
- tests/vksyncvaltests.cpp
Fix 6 tests and skip 6 tests running on RADV
> Fix validation layer tests running on RADV

- tests/vkpositivelayertests.cpp
Add a test for image layout transitions of
VK_IMAGE_CREATE_2D_ARRAY_COMPATIBLE_BIT images.
> tests: Add a test for layouts for 2D views of 3D image slices

- layers/debug_printf.cpp
- layers/gpu_validation.cpp
- layers/json/VkLayer_khronos_validation.json.in
Vkconfig uses caps for TRUE or FALSE, so make option compares case insensitive
> gpu: Make option compares case insensitive

- layers/core_validation.cpp
Recently added to spec as noticed they were missing
> layers: Label vkQueueSubmit2KHR VUs

- layers/buffer_validation.cpp
- layers/core_validation.cpp
- layers/core_validation.h
- layers/gpu_validation.cpp
- layers/state_tracker.cpp
- layers/state_tracker.h
- tests/layer_validation_tests.cpp
- tests/vklayertests_others.cpp
> layers: Add VUID 03673

- build-android/known_good.json
- layers/generated/spirv_tools_commit_id.h
- scripts/known_good.json
Change-Id: I86e255ed5a271a33e694a50633918ba8da5712dd
> build: Update SPIR-V and shaderc known_good.json

- layers/shader_module.cpp
- layers/shader_module.h
- layers/shader_validation.cpp
- layers/vk_layer_data.h
- tests/vklayertests_pipeline_shader.cpp
- tests/vkrenderframework.cpp
- tests/vkrenderframework.h
> layers: Add invalid specialization constant size check

- layers/buffer_validation.cpp
- tests/vklayertests_others.cpp
simple labeling followup of https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/2719
> layers: Label VU 04882

- layers/generated/vk_safe_struct.cpp
- scripts/helper_file_generator.py
- tests/vkpositivelayertests.cpp
> Ignore pAttachments of imageless framebuffers

- tests/layer_validation_tests.cpp
- tests/layer_validation_tests.h
- tests/vklayertests_buffer_image_memory_sampler.cpp
- tests/vklayertests_command.cpp
- tests/vklayertests_descriptor_renderpass_framebuffer.cpp
- tests/vklayertests_gpu.cpp
- tests/vklayertests_others.cpp
- tests/vklayertests_pipeline_shader.cpp
- tests/vklayertests_portability_subset.cpp
- tests/vkpositivelayertests.cpp
- tests/vksyncvaltests.cpp
Can now enforce this as the standard for all future GLSL tests
> tests: All GLSL shader use raw strings

- layers/core_validation.h
- layers/drawdispatch.cpp
- layers/state_tracker.cpp
- layers/state_tracker.h
These were found by code inspection of chassis.h.
> layers: Move TraceRays command recording to state tracker

- layers/buffer_validation.cpp
- tests/vklayertests_buffer_image_memory_sampler.cpp
Part of #2945
Labels
- `VUID-VkImageViewCreateInfo-image-04970`
- `VUID-VkImageViewCreateInfo-image-04971` (add some test as well)
Also improved some of the surrounding error messages as well
> layers: Label Maintenance1 ImageView VU

- layers/buffer_validation.cpp
- tests/vklayertests_buffer_image_memory_sampler.cpp
- tests/vklayertests_descriptor_renderpass_framebuffer.cpp
- tests/vkpositivelayertests.cpp
Part of #2945
Adds:
- `VUID-VkImageViewCreateInfo-imageViewType-04973`
- `VUID-VkImageViewCreateInfo-imageViewType-04974`
> Add imageView layerCount check

- tests/vkpositivelayertests.cpp
Some more tests that were failing when running and super old and super new devsim json I have
> tests: Fix devsim tests failing

- layers/buffer_validation.cpp
- layers/core_validation.cpp
- tests/vklayertests_portability_subset.cpp
This is to address https://github.com/KhronosGroup/Vulkan-Portability/issues/27.
> layers: Make swizzle less restrictive

- tests/vklayertests_buffer_image_memory_sampler.cpp
- tests/vklayertests_pipeline_shader.cpp
- tests/vkpositivelayertests.cpp
Also fix one issue identified by clang's ASAN.
> tests: Fix tests running on RADV

- tests/vklayertests_buffer_image_memory_sampler.cpp
- tests/vklayertests_command.cpp
- tests/vklayertests_others.cpp
Ran full tests suite on Pixel device I have and caught some tests failing for various of reasons
> tests: Fix tests ran on Android

- layers/drawdispatch.cpp
> layers: Fix Invalid message

- layers/core_validation.cpp
- tests/vklayertests_command.cpp
Check if the command pool the command buffer was allocated from supports the used pipelineBindPoint
> Adding vuid 00361

- layers/core_validation.cpp
Replace VK_PIPELINE_BIND_POINT_RAY_TRACING_NV with VK_PIPELINE_BIND_POINT_RAY_TRACING_KHR
> Update pipeline bind point NV to KHR

- layers/core_validation.cpp
- tests/vklayertests_command.cpp
If an occlusion query is active the command buffers submitted to vkCmdExecuteCommands must have been recorded with VkCommandBufferInheritanceInfo::occlusionQueryEnabled set to VK_TRUE
> Adding vuid 00102

- layers/core_validation.cpp
- tests/vklayertests_descriptor_renderpass_framebuffer.cpp
The checking for dynamic offsets was crashing if the descriptor's buffer was VK_NULL_HANDLE. Fixes #3014
> corechecks: Fix a crash in PreCallValidateCmdBindDescriptorSets

- tests/vkrenderframework.cpp
- tests/vkrenderframework.h
This reverts commit 3d74d970295f3b61f52d460479d5fa23facd6e5d.
> [WIP] Revert "tests: Fix VkRenderFramework::InitSurface() leaks"

- layers/generated/vk_extension_helper.h
- layers/parameter_validation_utils.cpp
- scripts/helper_file_generator.py
There was a problem when one of the extensions was in ppEnabledExtensionNames and the other was enabled by api level.
> Fix checking extensions in ppEnabledExtensionNames

- layers/shader_module.cpp
Touching other code around Built-ins and realized this was able to be pulled out by itself
Refactored code to use the `std::vector<builtin_set> builtin_decoration_list;` added a while ago to reduce re-looping to find the decorations
> layers: Cleanup CollectBuiltinBlockMembers

- layers/buffer_validation.cpp
- layers/core_validation.cpp
- layers/core_validation.h
> layers: Improve InvalidImageLayout error message

- layers/core_validation.cpp
Add the correct message for vuid-00721
> Update vuid 00721 message

- layers/shader_validation.cpp
The SPIR-V spec states:
> If the Image Dim operand is not SubpassData, the Image Format must
> not be Unknown, unless the StorageImageReadWithoutFormat Capability was
> declared.
This check is missing, causing ANGLE tests to fail.
> layers: Fix ValidateShaderStorageImageFormats: SubpassData

- layers/core_validation.cpp
- tests/vklayertests_others.cpp
If QueueSubmit2KHR is called synchronization2 feature must be enabled
> Adding vuid 03866

- layers/core_validation.cpp
- layers/generated/chassis.cpp
- scripts/layer_chassis_generator.py
> Fix some instances of -Wunused-but-set-variable.

- layers/core_validation.cpp
- tests/vklayertests_others.cpp
If one queue is already waiting on a binary semaphore then another queue cannot wait on the same semaphore
> Adding vuid 00068 and 03871

- layers/parameter_validation_utils.cpp
- layers/stateless_validation.h
- tests/vklayertests_pipeline_shader.cpp
If pNext of ShaderStageCreateInfo includes VkPipelineShaderStageRequiredSubgroupSizeCreateInfoEXT validate shader stage flags
> Adding vuid 02754

- layers/generated/parameter_validation.cpp
- layers/parameter_validation_utils.cpp
- layers/stateless_validation.h
- scripts/parameter_validation_generator.py
- tests/vklayertests_others.cpp
Check if vkGetPHysicalDeviceVideoFormatProperties imageUsage contains one of the needed bits
> Adding vuid 04844

- layers/core_validation.cpp
- layers/state_tracker.cpp
- layers/state_tracker.h
- tests/vklayertests_others.cpp
firstDiscardRectangle + discardRectangleCount must not be greater than maxDiscardRectangles
> Adding vuid 00585

- layers/core_validation.cpp
- layers/core_validation.h
- tests/vklayertests_others.cpp
Check if colorWriteEnable feature is enabled and if attachmentCount matches currently bound pipelines pColorBlendState->attachmentCount
> Adding vuid 04803 04804

- layers/core_validation.cpp
- tests/vklayertests_wsi.cpp
srcRect of DisplayPresentInfoKHR must be a subset of the swapchain image being presented
> Adding vuid 01257

- layers/core_validation.cpp
- tests/vklayertests_others.cpp
If query type is transform feedback stream index must be less than maxTransformFeedbackStreams, otherwise it must be 0
> Adding vuid 02346 02347

- layers/core_validation.cpp
- tests/vklayertests_others.cpp
All offsets in pDiscardRectangles in CmdSetDiscardRectangleExt must be non-negative
> Adding vuid 00587

- layers/parameter_validation_utils.cpp
- tests/vklayertests_others.cpp
VkAccelerationStructureInfoNV type must not be VK_ACCELERATION_STRUCTURE_TYPE_GENERIC_KHR
> Adding vuid 04623

- layers/buffer_validation.cpp
- tests/vklayertests_buffer_image_memory_sampler.cpp
If image was created with VK_IMAGE_CREATE_BLOCK_TEXEL_VIEW_COMPATIBLE_BIT and non-compressed format then viewType must not be 3D
> Adding vuid 04739

- layers/core_validation.cpp
- tests/vklayertests_wsi.cpp
signalSemaphoreCount, waitSemaphoreCount and commandBufferCount must be equal in DeviceGroupSubmitInfo and SubmitInfo
> Adding vuid 00084 00083 00082

- layers/core_validation.cpp
- tests/vklayertests_descriptor_renderpass_framebuffer.cpp
If RenderPassBeginInfo pNext chain contains VkDeviceGroupRenderPassBeginInfo each pDeviceRenderArea must be within the framebuffer bounds
> Adding vuid 02854 02855 02856 02857

- layers/core_validation.cpp
- tests/vklayertests_imageless_framebuffer.cpp
If descriptorType is VK_DESCRIPTOR_TYPE_INLINE_UNIFORM_BLOCK_EXT then dstArrayElement and descriptorCount must both be a multiple of 4
> Adding vuid 02226 02227

- layers/core_validation.h
- layers/core_validation_error_enums.h
- layers/shader_module.cpp
- layers/shader_module.h
- layers/shader_validation.cpp
- tests/vklayertests_pipeline_shader.cpp
- tests/vkpositivelayertests.cpp
First part of #2629
I have the rest of the atomics ready to go, but wanted to test the waters with the first (simplest) check first before adding the rest
> Add VK_KHR_shader_atomic_int64

- layers/shader_validation.cpp
- tests/vklayertests_pipeline_shader.cpp
- tests/vkpositivelayertests.cpp
Another for #2629
Adds `shaderImageInt64Atomics` check for `VK_EXT_shader_image_atomic_int64`
> Add shaderImageInt64Atomics

- layers/core_validation.cpp
- tests/vklayertests_pipeline_shader.cpp
Check that the pipeline being bound was not created with VK_PIPELINE_CREATE_LIBRARY_BIT_KHR
> Adding vuid 03382

- layers/core_validation.cpp
- tests/vklayertests_pipeline_shader.cpp
discardRectangleCount of VkPipelineDiscardRectangleStateCreateInfoEXT must not be greater than maxDiscardRectangles of VkPhysicalDeviceDiscardRectanglePropertiesEXT
> Adding vuid 00582

- layers/core_validation.cpp
- tests/vklayertests_others.cpp
New VUID was added in 1.2.187 headers
> layers: Label VUID 06225

- layers/core_validation.cpp
- layers/parameter_validation_utils.cpp
- tests/vklayertests_pipeline_shader.cpp
Check if attachmentCount of ColorWriteCreateInfo matches ColorBlendState attachmentCount and if colorWriteEnable features is not enabled all elements of pColorWriteEnable are VK_TRUE
> Adding vuid 04801 04802

- layers/buffer_validation.cpp
- tests/vklayertests_command.cpp
If the active render pass in CmdClearAttachments uses multiview,
each element of pRects must have baseArrayLayer 0 and layerCount 1
> Adding vuid 00018

- layers/core_validation.cpp
Improve pipeline error messages
> layers: Label missing pipeline index value

- layers/generated/chassis.cpp
- scripts/layer_chassis_generator.py
- tests/vkpositivelayertests.cpp
- tests/vkrenderframework.cpp
The extension wasn't be reported on Android.  Partially addresses #3072
> Fix validation reporting of validation_features extension

- layers/core_validation.cpp
- layers/state_tracker.cpp
- layers/state_tracker.h
- tests/vklayertests_pipeline_shader.cpp
Check if VkPHysicalDeviceBlendOperationAdvancedPropertiesEXT properties are supported if they are used by a pipeline
> Adding vuid 01424 01425 01426

- layers/core_validation.cpp
- tests/vklayertests_others.cpp
If queryPool was created with type VK_QUERY_TYPE_TRANSFORM_FEEDBACK_STREAM_EXT then transformFeedbackQueries must be supported
> Adding vuid 02328 02341

- layers/core_validation.cpp
- tests/vklayertests_imageless_framebuffer.cpp
Attachment referenced by fragmentDensityMapAttachment in vkCreateFramebuffer must have layerCount equal to 1
> Adding vuid 02744

- tests/vklayertests_others.cpp
Correctly load VK_KHR_get_physical_device_properties2 instance extension
> Fix CmdSetDiscardRectangleEXT tests

- layers/generated/parameter_validation.cpp
- layers/parameter_validation_utils.cpp
- layers/stateless_validation.h
- scripts/parameter_validation_generator.py
- tests/vklayertests_others.cpp
Check if any element on pDiscardRectangles in CmdSetDiscardRectangleEXT causes a signed integer overflow
> Adding vuid 00588 00589, Check for CmdSetDiscardRectangleEXT integer overflow

- layers/json/VkLayer_khronos_validation.json.in
> layers: Fix ARM best practices description

- layers/core_validation_error_enums.h
- layers/shader_module.cpp
- layers/shader_module.h
- layers/shader_validation.cpp
- tests/vklayertests_pipeline_shader.cpp
- tests/vkpositivelayertests.cpp
Closes #1596
Check if shared memory used by compute shader exceeds VkPhysicalDeviceLimits::maxComputeSharedMemorySize
> Fix issue 1596

- layers/state_tracker.cpp
Call the correct version of vkGetImageMemoryRequirements2() depending on if the application is using Vulkan 1.0 and the VK_KHR_get_memory_requirements2 extension or Vulkan 1.1 and higher
This fixes the following test cases on some devices:
VkLayerTest.BindInvalidMemory2Disjoint
VkLayerTest.BindInvalidMemoryNoCheck
> layers: Fix vkCreateImage memory reqs. check for multiplanar

- layers/core_validation.cpp
- tests/vklayertests_others.cpp
The queryType of the queryPool must not be
VK_QUERY_TYPE_ACCELERATION_STRUCTURE_COMPACTED_SIZE_KHR,
VK_QUERY_TYPE_ACCELERATION_STRUCTURE_SERIALIZATION_SIZE_KHR or
VK_QUERY_TYPE_ACCELERATION_STRUCTURE_COMPACTED_SIZE_NV
> Adding vuid 04728 04729, Validate CmdBeginQuery  and CmdBeginQueryIndexed queryPool queryType 

- layers/pipeline_state.cpp
- tests/vkpositivelayertests.cpp
Closes #2753 
Graphics pipeline shader stages must be recorded in order they are executed
> Fix issue 2753

- layers/state_tracker.cpp
Commit 0c09bc913 checked for VK_KHR_get_memory_requirements2 incorrectly. Fix it.
> layers: Fix VUID 01619 regression in CTS

- tests/vklayertests_gpu.cpp
Fixes some problems I noticed working on another problem with this test
> Fix BDA GPU-AV test

- layers/parameter_validation_utils.cpp
- tests/vklayertests_pipeline_shader.cpp
Validate VkComputePipelineCreateInfo basePipelineHandle and basePipelineIndex when flags contain VK_PIPELINE_CREATE_DERIVATIVE_BIT
> Adding vuid 00698 00699 00700

- layers/core_validation.cpp
- layers/core_validation.h
- tests/vklayertests_pipeline_shader.cpp
If VkRenderPassSampleLocationBeginInfoEXT is needed, check if it matches VkPipelineSampleLocationStateCreateInfoEXT
> Adding vuid 01525, Validate VkRenderPassSampleLocationBeginInfoEXT 

- tests/vklayertests_others.cpp
- tests/vklayertests_pipeline_shader.cpp
- tests/vkpositivelayertests.cpp
- tests/vkrenderframework.cpp
- tests/vkrenderframework.h
- tests/vktestframework.cpp
- tests/vktestframework.h
- tests/vktestframeworkandroid.cpp
- tests/vktestframeworkandroid.h
Testing a fix for CI failures seen in #3195.
> tests: Shader tests use Vulkan Version enum

- layers/core_validation.h
- layers/core_validation_error_enums.h
- layers/shader_module.cpp
- layers/shader_module.h
- layers/shader_validation.cpp
- tests/vklayertests_pipeline_shader.cpp
Closes #2304 
Check if specialization for WorkGroupSize is within VkPhysicalDeviceLimits::maxComputeWorkGroupSize
> Fix issue 2304

- build-android/known_good.json
- scripts/known_good.json
Update robin-hood-hashing to 3.11.3
> layers: Update robin-hood-hashing to 3.11.3

- layers/core_validation.cpp
- tests/vkpositivelayertests.cpp
Closes #3237 
Fix validating framebuffers image view layer count
> Fix issue 3237

- layers/best_practices_utils.cpp
- layers/core_validation.cpp
- layers/core_validation.h
- layers/descriptor_sets.cpp
- layers/drawdispatch.cpp
- layers/gpu_utils.h
- layers/pipeline_state.cpp
- layers/pipeline_state.h
- layers/ray_tracing_state.h
- layers/render_pass_state.cpp
- layers/render_pass_state.h
- layers/sampler_state.h
- layers/shader_module.cpp
- layers/shader_module.h
- layers/shader_validation.cpp
- layers/state_tracker.cpp
- layers/state_tracker.h
- layers/synchronization_validation.cpp
More moving  initialization into constructors and making member data const. See individual commit messages for more detail.
> layers: Clean up PIPELINE_STATE and PipelineStageState

- layers/core_validation.cpp
- layers/core_validation.h
- tests/vklayertests_wsi.cpp
> Validate surface is supported on physical device

- layers/shader_validation.cpp
- tests/vklayertests_pipeline_shader.cpp
Addresses #3230
There are already positive tests, so just had to add the negative tests
> Fix AdjustValidatorOptions

- layers/core_validation.cpp
- tests/vkpositivelayertests.cpp
> Fix issue 3251, Fix checking physical device surface support

- layers/shader_module.cpp
- layers/shader_module.h
- layers/shader_validation.cpp
- tests/vklayertests_best_practices.cpp
- tests/vklayertests_pipeline_shader.cpp
- tests/vkpositivelayertests.cpp
> Fix issue 1529, Fix validating shader input and output components

- layers/gpu_validation.cpp
- tests/vklayertests_gpu.cpp
> Fix issue 3257,  GpuAV with unbound descriptor set

- layers/cmd_buffer_state.cpp
- layers/core_validation.cpp
Fix wrong errors and asserts in some VK-GL-CTS tests
> Fix color attachment blend checks

- layers/buffer_validation.cpp
- tests/vklayertests_buffer_image_memory_sampler.cpp
> Fix issue 3266, cubic filter image type check

- layers/core_validation.cpp
- tests/vklayertests_others.cpp
Query in CmdEndQueryIndexedEXT must be less than queryCount the query
pool was created with
> Adding vuid 02343, Validate CmdEndQueryIndexedEXT query slot 

- layers/best_practices_utils.cpp
- layers/best_practices_validation.h
- layers/core_validation.cpp
- layers/core_validation.h
- layers/device_state.h
- layers/generated/best_practices.cpp
- layers/image_state.cpp
- layers/image_state.h
- layers/state_tracker.cpp
- layers/state_tracker.h
- scripts/best_practices_generator.py
Make the map for this state use AccessorTraits.
Add factory method for best practices validation to use.
Remove unused member data, move other stuff to swapchain state.
> layers: Clean up PHYSICAL_DEVICE_STATE

- layers/shader_module.cpp
- layers/shader_validation.cpp
- tests/vkpositivelayertests.cpp
> Fix validating shaders struct interface

- tests/vklayertests_pipeline_shader.cpp
Making sure the features in Vulkan for `VK_KHR_workgroup_memory_explicit_layout` are all covered between the SPIR-V Capability checking and the `--workgroup-scalar-block-layout` flag in `spirv-val`
related #3288
> tests: VK_KHR_workgroup_memory_explicit_layout

- tests/vkrenderframework.cpp
- tests/vkrenderframework.h
Fix an issue when adding instance extensions with dependencies.
> tests: Fix adding instance extensions

- layers/core_validation.cpp
- tests/vklayertests_command.cpp
Transform feedback must not be begun in a render pass with multiview enabled
> Adding vuid 02373, Validate transform feedback with multiview

- layers/core_validation.cpp
- tests/vklayertests_others.cpp
Query must be less than queryCount of queryPool
> Adding vuid 04903, Validate CmdWriteTimestamp2KHR query 

- layers/core_validation.cpp
- tests/vklayertests_pipeline_shader.cpp
Flags used in creating a ray tracing library must also have been set when creating the libararies used in create info
> Add vuid 04718 04719 04720 04721 04722 04723, Validate ray tracing pipeline flags with library 

- layers/core_validation.h
- layers/shader_module.cpp
- layers/shader_module.h
- layers/shader_validation.cpp
- tests/vklayertests_pipeline_shader.cpp
Closes #3290 
Check if TexelGatherOffset is within minTexelGatherOffset and maxTexelGatherOffset limits
> Add vuid 06376-06377, Validate TexelGatherOffset

- layers/core_validation.cpp
- layers/generated/parameter_validation.cpp
- layers/parameter_validation_utils.cpp
- layers/stateless_validation.h
- scripts/parameter_validation_generator.py
- tests/vklayertests_buffer_image_memory_sampler.cpp
Offset must be less than buffer size by 4 bytes and a multiple of 4
> Adding vuid 01983 01984, Validate ConditionalRenderingBeginInfo offset

- tests/vkpositivelayertests.cpp
Make sure nullDescriptor is working for CmdBindVertexBuffers* variants.
closes #2541
> tests: Add nullDescriptor tests

- layers/core_validation.cpp
- tests/vklayertests_pipeline_shader.cpp
Pipeline library must be created with VK_PIPELINE_CREATE_LIBRARY_BIT_KHR bit
> Adding vuid 03381, Validate pipeline library create flags

- tests/vkpositivelayertests.cpp
Add a test for task and mesh shader interface with taskNV, mentioned in #2102
> tests: Add positive test for task and mesh shader

- layers/image_state.cpp
- layers/image_state.h
- layers/state_tracker.cpp
Pre query Image memory requirements.
> layers: Make more IMAGE_STATE  member data be const

- layers/device_memory_state.cpp
- tests/vkpositivelayertests.cpp
> Fix issue 3350, Fix checking if memory is multi instance

- tests/vklayertests_buffer_image_memory_sampler.cpp
deviceCoherentMemory feature is not enabled so VK_MEMORY_PROPERTY_DEVICE_COHERENT_BIT_AMD must not be used
> tests: Fix invalid memory type test

- layers/buffer_validation.cpp
Another small fix towards https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/3225 around where `FormatElementSize` is called in buffer validation
> layers: More depth/stencil element size fixes

- tests/layer_validation_tests.cpp
- tests/vklayertests_buffer_image_memory_sampler.cpp
Test failed on AMD as described in #3362
> Fix multiplane sampler conversion test

- layers/device_memory_state.cpp
- layers/device_memory_state.h
- layers/state_tracker.cpp
Issue pointed out in: https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/3351#discussion_r719376141
> Fix checking if memory is multi instance

- tests/vkpositivelayertests.cpp
vk::CreateSwapchainKHR can return VK_ERROR_OUT_OF_HOST_MEMORY
> tests: Fix swapchain exclusive mode test

- layers/core_validation.h
- layers/device_state.h
- layers/shader_validation.cpp
- layers/state_tracker.cpp
- tests/vklayertests_pipeline_shader.cpp
Check if SubgroupSizeControlFeaturesEXT are enabled when used
> Adding vuid 02784 02785, Validate SubgroupSizeControlFeaturesEXT 

- tests/vklayertests_pipeline_shader.cpp
computeFullSubgroups feature was not enabled when used
> tests: Fix SubgroupSizeControl test

- layers/core_validation.cpp
- layers/vk_loader_platform.h
- tests/test_common.h
Modifications for layers to compile and run on FreeBSD.
Clone of #3380 with code formatting fix.
> layers: Add support for FreeBSD

- layers/descriptor_sets.cpp
- tests/vklayertests_command.cpp
This is a clone of #3352 with build and test fixes included.
> layers: Fix wrong image view type check for cubic filter

- layers/buffer_validation.cpp
- layers/core_validation.h
- layers/core_validation_error_enums.h
- tests/vklayertests_wsi.cpp
> Partial fix for issue 365

- tests/vklayertests_descriptor_renderpass_framebuffer.cpp
- tests/vklayertests_instanceless.cpp
- tests/vklayertests_others.cpp
Only run tests that leak on the mock ICD and fix the rest of the tests with leaks
Addresses #3414
> Fix test leaks

- layers/core_validation.h
- layers/shader_validation.cpp
- tests/vklayertests_pipeline_shader.cpp
Part of #3292 
Transform feedback output stride must be less than maxTransformFeedbackBufferData stride and stream index must be less than maxTransformFeedbackStreams
> Adding vuid 06310 06313, Validate transform feedback stride and stream 

- layers/best_practices_utils.cpp
layers: Fix crash during call ValidateBindBufferMemory
> layers: Fix ValidateBindBufferMemory's crash

- layers/descriptor_sets.cpp
- layers/descriptor_sets.h
Fixes invalid 04611 error in the CTS mutable_descriptor tests
> layers: Fix comparing DescriptorSetLayoutDef

- layers/core_validation.h
- layers/shader_validation.cpp
- tests/vklayertests_pipeline_shader.cpp
> Adding vuid 06265 06266, validate spirv memory scope

- layers/buffer_validation.cpp
- layers/cmd_buffer_state.cpp
- layers/cmd_buffer_state.h
- tests/positive/sync.cpp
> Fix issue 3451, validation of multiple pipeline barriers on same image

- layers/generated/spirv_grammar_helper.cpp
- layers/generated/spirv_grammar_helper.h
- layers/shader_module.cpp
- layers/shader_module.h
- layers/shader_validation.cpp
- scripts/spirv_grammar_generator.py
Made naming more clear adding `Position` in function name
Added another helper function for getting count of image operand parameters
> layers: Rename and add spirv parameter helper

- layers/shader_validation.cpp
- tests/vklayertests_pipeline_shader.cpp
> Add vuid 06312

- layers/descriptor_sets.cpp
- tests/positive/shaderval.cpp
> Fix validating acceleration structure descriptors

- layers/shader_module.cpp
- layers/shader_validation.cpp
- tests/vklayertests_pipeline_shader.cpp
> Add vuid 06308

- layers/buffer_validation.cpp
- layers/cmd_buffer_state.cpp
- layers/cmd_buffer_state.h
- layers/core_validation.cpp
- layers/core_validation.h
- layers/generated/layer_chassis_dispatch.cpp
- layers/object_tracker_utils.cpp
- layers/parameter_validation_utils.cpp
- layers/pipeline_state.cpp
- layers/pipeline_state.h
- layers/render_pass_state.cpp
- layers/render_pass_state.h
- layers/shader_validation.cpp
- layers/state_tracker.cpp
- layers/state_tracker.h
- scripts/layer_chassis_dispatch_generator.py
- tests/vklayertests_command.cpp
WIP - Add VU for VK_KHR_dynamic_rendering extension.
> layers: Add VK_KHR_dynamic_rendering

- layers/buffer_validation.cpp
- layers/cmd_buffer_state.h
- layers/core_validation.cpp
- layers/core_validation.h
- layers/drawdispatch.cpp
- layers/pipeline_state.h
- layers/render_pass_state.cpp
- layers/render_pass_state.h
- layers/shader_validation.cpp
- layers/state_tracker.cpp
- layers/state_tracker.h
- tests/CMakeLists.txt
- tests/positive/dynamic_rendering.cpp
- tests/vkrenderframework.cpp
- tests/vkrenderframework.h
Add additional VUs for the VK_KHR_dynamic_rendering extension.
Small refactors and unit tests as well as addition of  VUIDs for
VkDraw* commands.
> layers: Add VK_KHR_dynamic_rendering VUs - Change Set #2

- layers/shader_validation.cpp
- tests/vklayertests_pipeline_shader.cpp
> Add vuid 06309

- layers/core_validation.h
- layers/shader_validation.cpp
- tests/positive/pipeline.cpp
Closes #3554 by adding a dynamic render path for FS ouput validation
> layers: Dynamic Rendering - Validate FS Outputs

- layers/buffer_validation.cpp
- layers/core_validation.cpp
- layers/render_pass_state.cpp
Bug fixes associated with validating dynamic rendering against Vulkan CTS 1.3.0.
> layers: Dynamic Rendering - Validate against CTS

- layers/descriptor_sets.cpp
> Fix error message for VUID 04553

- layers/parameter_validation_utils.cpp
- tests/vklayertests_pipeline_shader.cpp
Adds VUID-VkPipelineViewportDepthClipControlCreateInfoEXT-negativeOneToOne-06470
> Add VK_EXT_depth_clip_control

- layers/generated/chassis.h
- layers/generated/layer_chassis_dispatch.cpp
- scripts/layer_chassis_dispatch_generator.py
- scripts/layer_chassis_generator.py
Adds tracking of allocations associated with deferred operations with
subsequent deletion once the deferred operations have completed.
Closes KhronosGroup#2767
> scripts: Store and delete mem for deferred ops

- layers/cmd_buffer_state.cpp
- layers/core_validation.cpp
- layers/core_validation.h
- layers/descriptor_sets.cpp
- layers/pipeline_state.cpp
- layers/pipeline_state.h
- layers/sampler_state.h
- layers/shader_module.h
- layers/shader_validation.cpp
- layers/state_tracker.cpp
Restructure samplers_used_by_image and wrote_primitive_shading_rate be const.
> layers: Make more PIPELINE_STATE fields be const

- layers/buffer_validation.cpp
There is a confusion that DRM modifiers are bit fields but they're more like enums.
> layers: Fix assumption on DRM modifiers

- tests/vklayertests_pipeline_shader.cpp
Adds tests for:
VUID-VkPipelineRenderingCreateInfoKHR-pColorAttachmentFormats-06064
VUID-VkPipelineRenderingCreateInfoKHR-depthAttachmentFormat-06065
VUID-VkPipelineRenderingCreateInfoKHR-stencilAttachmentFormat-06164
VUID-VkPipelineRenderingCreateInfoKHR-depthAttachmentFormat-06165
VUID-VkPipelineRenderingCreateInfoKHR-multiview-06066
VUID-VkPipelineRenderingCreateInfoKHR-viewMask-06067
> Add tests for VkPipelineRenderingCreateInfoKHR VUIDs

- layers/core_validation.cpp
- tests/vklayertests_command.cpp
Covers:
VUID-vkCmdExecuteCommands-pNext-06032
VUID-vkCmdExecuteCommands-pNext-06033
VUID-vkCmdExecuteCommands-pNext-06034
VUID-vkCmdExecuteCommands-pNext-06035
VUID-vkCmdExecuteCommands-pNext-06036
VUID-vkCmdExecuteCommands-pNext-06037
> Add validation and tests for 6 vkCmdExecuteCommands-pNext VUIDs

- tests/vklayertests_buffer_image_memory_sampler.cpp
"I was doing something and wanted to multi-task" PR
Wanted to do this for a while, picked a smaller test file, wasn't as bad as I thought it would be
> tests: Convert buffer image tests to LvlInitStruct

- layers/parameter_validation_utils.cpp
- tests/vklayertests_others.cpp
Add check and test for VUID-01840, which validates that the extension AMD_negative_viewport_height is not enabled on api version 1.1 or greater
> Validate that AMD_NEG_VP_HT is not enabled on 1.1+ instances

- layers/queue_state.cpp
- layers/queue_state.h
It turns out the QUEUE_STATE deque does not need to be public, so
all of these classes are fully encapsulated and can manage their
locking.
The tricky part of this change is making sure QUEUE_STATE::Retire()
doesn't get called with a lock held. This would lead to deadlock.
> layers: Make QUEUE_STATE and related classes threadsafe

- layers/buffer_validation.cpp
- tests/positive/dynamic_rendering.cpp
Uses VkRenderingInfoKHR->render_area if dynamic area is active.
Fixes #3614
> layers: Dynamic Rendering render_area fixes

- tests/layer_validation_tests.cpp
- tests/layer_validation_tests.h
- tests/vklayertests_command.cpp
- tests/vklayertests_descriptor_renderpass_framebuffer.cpp
- tests/vklayertests_gpu.cpp
- tests/vklayertests_pipeline_shader.cpp
Add vendor portable checks to pass validation layer tests on more implementations.
> tests: Updated tests to be vendor portable

- layers/state_tracker.cpp
Unless enabled on the VkDevice.
Would that help for #3673 ?
> layers: don't include DRM modifiers in queries

- layers/shader_module.cpp
- tests/vklayertests_buffer_image_memory_sampler.cpp
closes #3623 
I feel the `shader_module_used_operators::update` and other code in `shader_module.cpp` could be slightly improved/refactored yet (probably can make more use of the generated code from SPIR-V spec too!), but for now this should be enough to properly fix the issue
The main issue is due to Combined image samplers looking like
```swift
%load = OpLoad %OpTypeSampledImage %var
%3    = OpImageSampleImplicitLod %1 %load %2
```
but when using a sampler and sample image you get
```swift
%imageLoad   = OpLoad %OpTypeImage %var1
%samplerLoad = OpLoad %OpTypeSampler %var2
%load        = OpSampledImage %OpTypeSampledImage %imageLoad %samplerLoad
%3           = OpImageSampleImplicitLod %1 %load %2
```
> layers: Fix drawtime checks for separate samplers

- tests/positive/command.cpp
Closes #3389 
This issue required a spec fix. Adding a test to make sure it works.
> tests: Validate CmdWriteTimestamp2 stage flags

- layers/buffer_validation.cpp
- layers/core_validation.cpp
- layers/image_state.cpp
- layers/image_state.h
- tests/positive/command.cpp
> Fix issue 3410, Fix CmdClearAttachment layer count

- layers/core_validation.h
- layers/device_state.h
- layers/shader_validation.cpp
- layers/state_tracker.cpp
- tests/vklayertests_pipeline_shader.cpp
> Add vuid 06372-06373, Validate spirv Workgroup initialization

- layers/descriptor_sets.cpp
- tests/vklayertests_descriptor_renderpass_framebuffer.cpp
Fixes issue #3492. Replaced error code for updating descriptor sets while in use.
> Fix issue 3492

- layers/buffer_validation.cpp
- tests/vklayertests_buffer_image_memory_sampler.cpp
Touches test from #2214
Not fixing, but related to #1495 
Adds support for `VUID-VkImageViewCreateInfo-image-01583`
confirmed that "size-compatible" refers to the `FormatElementSize`
(CTS has a test that goes from `VK_FORMAT_BC3_UNORM_BLOCK` to `VK_FORMAT_R32G32B32A32_UINT` which both are a 128-bit format)
> layers: Block Texel View VU 01583

- layers/core_validation.cpp
Addresses #3730
$XDG_CACHE_HOME defines the base directory relative to which user-specific
non-essential data files should be stored. If $XDG_CACHE_HOME is either
not set or empty, a default equal to $HOME/.cache should be used.
> Use a more secure location for shader validation cache

- layers/best_practices_utils.cpp
Flags use of deprecated extensions.
> Handle deprecated extensions in 1.3 in Best Practices

- layers/descriptor_sets.cpp
- tests/vklayertests_pipeline_shader.cpp
Realized the VU talks of how 
> Any VkImageView or **VkBufferView** being read as a storage image or **storage texel buffer** where the image format field of the OpTypeImage is Unknown ...
So added a path in texel buffer descriptors to all check for proper usage of
`VK_FORMAT_FEATURE_2_STORAGE_READ_WITHOUT_FORMAT_BIT` / `VK_FORMAT_FEATURE_2_STORAGE_WRITE_WITHOUT_FORMAT_BIT` 
cc @djdeath
> layers: Add WITHOUT_FORMAT_BIT for storage buffer

- layers/generated/object_tracker.cpp
- scripts/object_tracker_generator.py
> Check count before pointer in Object Tracker

- layers/gpu_validation.cpp
- layers/gpu_validation.h
- tests/vklayertests_gpu.cpp
Handle NULL renderpass special case.
> Fix GPU-AV wrt dynamic rendering

- layers/core_validation.cpp
- tests/positive/dynamic_rendering.cpp
> Skip render pass validation if dynamic rendering is used

- layers/shader_validation.cpp
- tests/vklayertests_pipeline_shader.cpp
> Check attachments vector size before access

- layers/best_practices_utils.cpp
- layers/state_tracker.cpp
- tests/vklayertests_best_practices.cpp
> Create pipeline state even when no render pass is specified

- layers/buffer_validation.cpp
- layers/core_validation.cpp
- tests/vklayertests_others.cpp
Got this crash when I was looking at another issue.
> layers: Check vector size before access

- layers/generated/vk_object_types.h
- scripts/helper_file_generator.py
> layers: Add necessary guards for object types

- layers/core_validation.cpp
> layers: Check if extension is enabled for VUIDs

- layers/generated/parameter_validation.cpp
- layers/parameter_validation_utils.cpp
- layers/stateless_validation.h
- scripts/parameter_validation_generator.py
Spec now lists it as optional and default code gen code is correct
Closes #3763
> Remove special case for planeAspect

- layers/debug_printf.cpp
- layers/debug_printf.h
- layers/gpu_utils.h
- layers/gpu_validation.cpp
- layers/gpu_validation.h
Minor cleanup of these classes to get ready for bigger cleanups and fine--------grained locking
> layers: Clean up GPUAV and DebugPrintf member data (and 1 method)

- layers/core_validation.cpp
- tests/vklayertests_dynamic_rendering.cpp
> layers: Fix rendering attachment access

- layers/core_validation.cpp
- tests/vklayertests_dynamic_rendering.cpp
> Validate RenderingInfo depth and stencil samples

- layers/core_validation.cpp
- tests/vklayertests_dynamic_rendering.cpp
"equal to" was missing in logs
Replaced %u with PRIu32
Added numbers to logs
> layers: Fix vuid 06083 and 06084 log messages

- layers/parameter_validation_utils.cpp
- tests/positive/other.cpp
> Fix issue 3876, Fix checking enabled ray tracing features

- layers/best_practices_error_enums.h
- layers/best_practices_utils.cpp
- layers/core_validation.cpp
- layers/core_validation.h
- layers/vk_layer_utils.h
- tests/vklayertests_best_practices.cpp
> Fix issue 3794,  Warn when transitioning from undefined layout to a read-only layout

- layers/core_validation.cpp
> layers: Fix segfault when checking for dynamic DS attachments

- docs/fine_grained_locking.md
- layers/core_validation.cpp
- layers/core_validation.h
some places were not making use of the `CMD_TYPE` system
> layers: Make use of CMD_TYPE

- layers/state_tracker.cpp
> layers: Use copy of pointer in lambda

- layers/core_validation.cpp
- tests/positive/dynamic_rendering.cpp
hotfix #3805
Silences false errors about null `pColorBlendState` or `pDepthStencilState` when user provides fragment shader but enables rasterizer discard.
Deep inclarity remains about the literal meaning of new specification language, but this code matches what logic the non-dynamic rendering code uses.
> layers: Fix false pipeline errors in dyn. rendering

- layers/buffer_validation.cpp
- tests/vklayertests_buffer_image_memory_sampler.cpp
> Fix checking buffer copy overlaps

- layers/cmd_buffer_state.cpp
- layers/cmd_buffer_state.h
- layers/core_validation.cpp
- layers/core_validation.h
- layers/drawdispatch.cpp
- layers/state_tracker.cpp
- layers/state_tracker.h
- tests/vklayertests_others.cpp
> Add vuid 06667, Validate dynamic color write enable

- layers/synchronization_validation.cpp
- tests/vksyncvaltests.cpp
> Fix issue 3892, Use format usage only if set

- layers/generated/parameter_validation.cpp
- layers/parameter_validation_utils.cpp
- layers/stateless_validation.h
- scripts/parameter_validation_generator.py
- tests/vklayertests_buffer_image_memory_sampler.cpp
VkDeviceImageMemoryRequirements::pNext must not contain VkImageSwapchainCreateInfoKHR
> Add vuid 06416, validate VkDeviceImageMemoryRequirements pNext

- layers/best_practices_utils.cpp
- tests/vklayertests_best_practices.cpp
Closes #2927 
@ncesario-lunarg You already fixed this once, not sure why it's not in the code
> layers: Fix swapchain double buffer performance warning

- GOVERNANCE.md
- docs/fine_grained_locking.md
Doesn't fix https://gitlab.khronos.org/vulkan/Vulkan-SDK-Packaging/-/issues/1002 but was motivated by it
> Update spec links to 1.3 spec

- layers/shader_module.cpp
- tests/positive/pipeline.cpp
> Fix calculating components for matrices

- layers/core_validation.cpp
- tests/vklayertests_others.cpp
> Add vuid 03707, Validate memory in build acceleration structures

- layers/core_validation.cpp
The 1.3.208 Vulkan Spec [added a revision to VK_ANDROID_external_memory_android_hardware_buffer](https://github.com/KhronosGroup/Vulkan-Docs/commit/e88e27f2cda370444f87fc724412a384cb958824) that allows for another usage flag
cc @chrisforbes
> layers: AHB GPU_DATA_BUFFER can use storage

- layers/descriptor_sets.cpp
- tests/vklayertests_descriptor_renderpass_framebuffer.cpp
> Fix validating image view usage in descriptors

- layers/image_state.cpp
- layers/image_state.h
- tests/positive/descriptors.cpp
> Make a safe copy of VkImageViewCreateInfo

- layers/core_validation.cpp
- tests/positive/pipeline.cpp
- tests/vklayertests_pipeline_shader.cpp
> Add vuid 06427, Validate dual source blending output writes

- layers/debug_printf.cpp
- layers/debug_printf.h
- layers/gpu_utils.cpp
- layers/gpu_utils.h
- layers/gpu_validation.cpp
- layers/gpu_validation.h
- layers/state_tracker.cpp
- layers/state_tracker.h
This is a common base class for DebugPrintf and GPUAV.
> layers: Add GpuAssistedBase class

- layers/parameter_validation_utils.cpp
- tests/vklayertests_buffer_image_memory_sampler.cpp
> Add vuid 06726, Validate sampler reduction mode

- layers/synchronization_validation.cpp
> layers: Check if iterator is not empty before increment

- layers/core_validation.cpp
- layers/parameter_validation_utils.cpp
- tests/vklayertests_graphics_library.cpp
- tests/vklayertests_pipeline_shader.cpp
Adds VUIDs:
- 06576
- 06602
- 06603
Also attempts removes duplicate logs of 06574 and 06575, as well as
attempting to clarify the difference between 06574, 06575, and 06576.
> layers: Add more implicit -> explicit VUIDs
