BUILD.md
CMakeLists.txt
tests/CMakeLists.txt

Hopefully addresses three issues found by @danginsburg.  
- If an SDK is installed, setting LOADER_REPO_ROOT is not required.  However, setting it to point to an installed SDK uncovered a cmake deficiency.
- Pointing to a glslang repo caused a host of issues (build dir names, build decorations, etc).  Changed glslang location method to **require** building per the glslang instructions, meaning that  INSTALL_PREFIX is supplied and 'make install' gets run.  GLSLANG_REPO_ROOT will be phased out and the new hotness is "**GLSLANG_INSTALL_DIR**".  Both should work for the time being.
- The LOADER and GLSLSANG variables were not predefined, and so could not be manipulated with ccmake or cmake-gui.  
Updated BUILD.md to reflect changes.
Fixes #113.

Cmake fixes and upgrades for glslang, sdk locations

---

layers/buffer_validation.cpp
layers/buffer_validation.h
layers/core_validation.cpp
layers/core_validation_types.h
layers/hash_vk_types.h
tests/layer_validation_tests.cpp

Added tracking and validation and test of queue family ownership transfer barriers.  Validation will warn on duplicated transfers and error on acquire operations without matching release operations. Fixes #39.
Adds new valid usage placeholders:
- UNASSIGNED-VkImageMemoryBarrier-image-00001 QFO transfer image barrier must not duplicate QFO recorded in command buffer
- UNASSIGNED-VkImageMemoryBarrier-image-00002 QFO transfer image barrier must not duplicate QFO submitted in batch
- UNASSIGNED-VkImageMemoryBarrier-image-00003 QFO transfer image barrier must not duplicate QFO submitted previously
- UNASSIGNED-VkImageMemoryBarrier-image-00004 QFO acquire image barrier must have matching QFO release submitted previously
- UNASSIGNED-VkImageMemoryBarrier-buffer-00001 QFO transfer buffer barrier …

Add queue transfer ownership validation

---

layers/core_validation.cpp

Skip invalid handles during core validation of vkQueueBindSparse.  Addresses [LunarXChange #763](https://vulkan.lunarg.com/issue/view/5ae4620ee46ffe75aa6fff9a)

layers: Avoid SEGV in Sparse binding validation

---

CONTRIBUTING.md

Give a brief overview of GitHub cloud CI testing including links for devsim and device profiles. This gives some starting info to people who hit CI fails with their PR.

docs:Add Cloud CI section to Contributing.md

---

layers/buffer_validation.cpp
layers/core_validation.cpp
layers/shader_validation.cpp
layers/shader_validation.h

Several cases where relevant object information was missing from the log messages used.  This was discovered in issue #94.  These two commits add logic to identify the relavent `VkShaderModule` on failing pipeline attachments, and the `VkImage`  during `VkImageView` creation.

Issue #94: Add missing object information

---

scripts/helper_file_generator.py
scripts/vuid_mapping.py

- Update Vulkan-Headers submodule to 1.1.75
- Update vuid_mapping.py with new structure ids
- Stop helper_file_generator.py from generating bogus VkStructureType
values for VkBase(In|Out)Structure

header: Update to 1.1.75

---

scripts/parse_test_results.py
tests/layer_validation_tests.cpp

Went through and fixed several small bugs in tests that were causing unexpected errors to be printed.
The following test with unexpected errors were fixed:
CreatePipelineLayoutExcessPerStageDescriptors 
IndexBufferBadSizeOffset 
InvalidQueueFamilyIndex 
SetDynViewportParamAmdNegHeightTests 
CopyImageTypeExtentMismatchMaintenance1 
InvalidBarrierQueueFamilyWithMemExt 
DescriptorIndexingUpdateAfterBind 
BufferViewInUseDestroyedSignaled 
CreatePipelineLayoutExcessDescriptorsOverall 
InvalidCmdBufferBufferViewDestroyed 
InvalidBarrierQueueFamily

Cleaned up unexpected errors in various tests

---

layers/core_validation.cpp
layers/object_tracker_utils.cpp
layers/parameter_validation_utils.cpp
layers/threading.cpp
layers/unique_objects.cpp
layers/vk_validation_error_messages.h
scripts/spec.py
tests/layers/device_profile_api.cpp

In order to address compile/runtime issues, the large validation tables
are now generated such that the declaration and implementation are
separate.

layers: Make validation error maps non-static

---

tests/device_profiles/geforce_1080_ti.json
tests/device_profiles/mobile_chip.json
tests/layer_validation_tests.cpp
tests/vktestbinding.cpp

Made fixes to two tests and added a high end device profile to get seven more tests running without being skipped.
The tests now no longer being skipped are:
VkPositiveLayerTest.MultiplaneImageTests
VkPositiveLayerTest.MultiplaneGetImageSubresourceLayout
VkLayerTest.CopyImageSinglePlane422Alignment
VkLayerTest.DescriptorIndexingSetLayout
VkLayerTest.MultiplaneImageLayoutBadAspectFlags
VkLayerTest.CopyImageMultiplaneAspectBits
VkLayerTest.InvalidBarriers

tests: Get seven more tests running without skipping on device profiles

---

layers/VkLayer_core_validation.def
layers/VkLayer_object_tracker.def
layers/VkLayer_parameter_validation.def
layers/VkLayer_threading.def
layers/VkLayer_unique_objects.def
layers/parameter_validation_utils.cpp

On Windows the `vkNegotiateLoaderLayerInterfaceVersion` entry points are not included in the def files. As a result, the loader is unable to find these functions and they never get used. On top of that, the negotiate function in parameter validation has the wrong name and protoype. This change gets the negotiate functions working in the validation layers.

layers: Export negotiate functions on Windows

---

layers/vk_layer_logging.h

Fix the conversion of the DebugReport message types into the
DebugUtils message severity/types.  This was caught by @RCalocaO.
Change-Id: Ib0670e89867b16e8a48f2a2c760c46cc31ee253e

layers: gh146- Fix message type conversion

---

.appveyor.yml
.gitignore
.gitmodules
.travis.yml
BUILD.md
CMakeLists.txt
external/CMakeLists.txt
tests/CMakeLists.txt
tests/test_common.h

Removed this component as a submodule and made it an optional component of the tests portion of the repo.  If googletests is present in the External folder, tests will build (if enabled).  Otherwise, building of tests will be skipped.  This step has no other dependencies.

Remove googletest as a submodule and make it optional

---

.appveyor.yml
.travis.yml

Vulkan-Loader build requirements changed, so update the CI
configs to build it with the new methods.

ci: Update CI for changes to Vulkan-Loader

---

tests/CMakeLists.txt

This is mainly to ensure that in a Visual Studio workflow, running the `vk_layers_validation_tests` project in the IDE triggers the individual layers to build if they're out of date.
(...no *YOU* just spent an hour "debugging" a test failure you'd already fixed because your layers binaries were stale.)

tests: layer tests should depend on layer builds

---

.appveyor.yml
.travis.yml

Removed submodule cruft, removed *_REPO_ROOT references, changed to new install targets for loader, headers, and glslang.

Update appveyor/travis for INSTALL_DIR builds

---

BUILD.md
CMakeLists.txt
tests/CMakeLists.txt

This allowed killing a bunch of cmake crud. Repo root is now gone, and setting VULKAN_HEADERS_INSTALL_DIR, VULKAN_LOADER_INSTALL_DIR, and GLSLANG_INSTALL_DIR can all be done via environment variables.

Remove *_REPO_ROOT, allow env var for glslang

---

layers/unique_objects.cpp
scripts/unique_objects_generator.py

- remove duplicate include
- `currentDisplay` in `vkGetPhysicalDeviceDisplayPlaneProperties` may be `VK_NULL_HANDLE`
- `vkGetDisplayPlaneSupportedDisplays` did not account for `VK_INCOMPLETE`
-  `vkGetDisplayPlaneCapabilitiesKHR` can be handled by generated code

layers: Fix bugs of display queries in unique_objects

---

.appveyor.yml

Build only x64 Release and Win32 Debug to improve
turnaround time.

ci: Reduce AppVeyor jobs to two

---

tests/CMakeLists.txt

Even though INSTALL_DIR was used to indicate the loader libs to link against, due to Windows DLL search order rules there was no telling which, if any, vulkan loader was getting used. Copy the indicated loader binary to the app dir to make sure.
This is a cmake post-build step that runs ONLY on windows.

Copy loader dll to bin dir for LVTs

---

layers/buffer_validation.cpp
layers/buffer_validation.h
layers/core_validation.cpp
layers/core_validation_types.h
layers/vk_layer_utils.h
tests/layer_validation_tests.cpp

Addresses #51  Add additional logic to support search for matching self-dependency when more than one are present in a sub-pass. 
This provides coverage for the case where a matching (superset) mask is in some other self-dependency than the one we were checking.
Additionally (and in separate commit) refactored in to PreCall/PostCall style.
Two notes:
1. The isn't as stringent as it could be.  It could be checking that the union of all the require mask matching was done across all mask type for each barrier.  Currently if the statge mask is satisfied by A and the access mask is satisfied by B, there will be no error directly related will be generated.
2. The VUID's as written don't well match the multiple self-dependenices well, thus there is now more reporting multiple VUID's for a single …

 Update barrier validation for mulitple self-dependencies

---

tests/layer_validation_tests.cpp

Issuing multiple calls to SetDesiredFailureMsg() using the same VUID is now supported.
Resolves #87 (LVL #2639)

Allow duplicate failure messages in layer validation tests

---

tests/layers/device_profile_api.cpp

Layer was using header from the threading layer (!), was mixing layer init methods, and was based on very old patterns. Brought into the 20th century, at least.
First step in the process of removing most of vk_layer_table.*, next up is Object Tracker.

Update device_profile test layer

---

BUILD.md
CMakeLists.txt
external/CMakeLists.txt
tests/CMakeLists.txt

Behavior is largely unchanged except that specifying BUILD_TESTS=ON
with googletest not present no longer quietly skips building the tests.
- Make inclusion of external directory unconditional.  We may someday
put something there is not related to testing.
- Make default for BUILD_TEST dependent on googletest presence.
- Remove if() around entire contents of tests CMake file.
- Add CMake messaging to clarify googletest activity.
- Throw a CMake error if googletest not present and BUILD_TESTS=ON

build: Improve googletest handling

---

layers/object_tracker.h
layers/object_tracker_utils.cpp
scripts/object_tracker_generator.py

OT was using old style dispatch table handling (and for some reason had multiple device dispatch tables!). Updated to be consistent with other validation layers.  
Next up, getting rid of vk_layer_table.*, and then fixing up the dispatch tables to null extension function pointers if they're disabled.

Update object_tracker dispatch table handling

---

build-android/android-generate.sh
build-android/jni/Android.mk

We can't use submodules in the Android NDK build, so these changes are needed to find vulkan headers outside the project.
We also can't build tests without the Vulkan-Tools project, so adding the ability to skip building tests.
I haven't done Windows side yet.  Still need to document changes.

Android external headers

---

cmake/Copyright_cmake.txt

Get latest Kitware copyright notice from
https://gitlab.kitware.com/cmake/cmake/blob/master/Copyright.txt @ d45d5e2

cmake: Add Kitware copyright

---

layers/object_tracker.h
layers/object_tracker_utils.cpp
layers/parameter_validation_utils.cpp
layers/threading.h
layers/unique_objects.cpp
layers/vk_layer_logging.h
tests/layer_validation_tests.cpp

Remove the variant of log_msg that accepts enums for msg_code, and fix up all remaining code that linked to it in threading, object tracker, and unique objects layers.
Removed a chunk of aspectFlag checks from parameter_validation_utils that pre-dated VUID enums and appears obsoleted by current, specific VUIDs. 
This PR will not compile until the changes in PR #208 are merged.

Clean up all remaining enum-based log_msg calls

---

layers/buffer_validation.cpp
layers/core_validation.cpp
layers/core_validation_types.h
tests/layer_validation_tests.cpp

Extends validation coverage of the BufferViewCreateInfo  structure. The following checks are now in place and tested:
* `offset` must be less than the size of `buffer`
* If `range` is not equal to `VK_WHOLE_SIZE`, `range` must be greater than 0
* If `range` is not equal to `VK_WHOLE_SIZE`, `range` must be a multiple of the element size of `format`
* If `range` is not equal to `VK_WHOLE_SIZE`, `range` divided by the element size of `format` must be less than or equal to `VkPhysicalDeviceLimits::maxTexelBufferElements`
* If `range` is not equal to `VK_WHOLE_SIZE`, the sum of `offset` and `range` must be less than or equal to the size of `buffer`
* `buffer` must have been created with a `usage` value containing at least one of `VK_BUFFER_USAGE_UNIFORM_TEXEL_BUFFER_BIT` or …

Additional BufferViewCreateInfo validation

---

layers/object_tracker_utils.cpp
scripts/object_tracker_generator.py

Codegen currently does not handle optional array pointers. This fixes some CTS crashes.

Fix CTS crashes -- do not codegen vkGetDescriptorSetLayoutSupport in Object Tracker

---

.travis.yml
scripts/known_good.json

Using the script causes CI to build the "known-good" versions of the
dependent repositories. This should improve the stability of the
CI testing of Vulkan-ValidationLayers.
If Travis CI is triggered by a cron job, it builds the master branch
of the dependent repositories.
Add Vulkan-Tools to "ci_only" repo list in known-good file since
the CI tests need the mock ICD.

ci: Use update_deps script in Travis-CI

---

layers/core_validation.cpp
layers/object_tracker.h
layers/object_tracker_utils.cpp
layers/parameter_validation_utils.cpp
layers/threading.cpp
layers/threading.h
layers/unique_objects.cpp
layers/unique_objects.h
scripts/dispatch_table_helper_generator.py
scripts/helper_file_generator.py

Per the Vulkan Specification, GetDeviceProcAddr() should behave as follows:
Given this as an API-Name | GDPA should return:
------------ | -----------------------
core device-level Vulkan command |  fp
enabled device extension commands  |  fp
*(any pName not covered above) |  NULL
However, the layers do not check for **enabled** device extension commands and return a valid fp regardless of which extensions were enabled.  This patch is to bring the layers up to spec in this regard.

Fix Layer GetDeviceProcAddr behavior

---

scripts/known_good.json

@karl-lunarg , lemme know if any of these should go back to the 1.1.77 SDK tag.  Also, it'd be best to run this after your CI change goes in.

Update known-good for 1.1.79 header

---

layers/parameter_validation_utils.cpp
layers/vk_layer_logging.h
scripts/dispatch_table_helper_generator.py

This change removes the assumption that `vk_layer.h` will include `vk_layer_dispatch_table.h`, since it will be removed from `vk_layer.h` in the near future. The change to remove the extra include is KhronosGroup/Vulkan-Headers#11.
This PR is needed to ensure that merging the Vulkan-Headers PR doesn't break anything in this repo.

layers: Rework include dependencies

---

layers/CMakeLists.txt

This is required to build LunarG/VulkanTools.

layers: Add layer-utils source to install target

---

.travis.yml
CMakeLists.txt
scripts/helper_file_generator.py

- Although ccache is turned on in the Travis config file, additional
steps are needed to turn it on for CMake-based builds.  Set USE_CCACHE=ON
in the Travis config for this repo to cause CMake to "wrap" (prepend)
compiler invocations with "ccache".
- Turn off ccache linker wrapping in CMake code to enable ccache.
It doesn't work.
- Modify the helper generator script to sort the enums when generating
the enum-to-string functions.  This causes the header file to be generated
with the same content each time the script is run, which greatly improves
ccache effectiveness.  For local ccache-assisted builds of this repo,
the build time can be cut in half.

ci: Turn on ccache for Travis-CI

---

scripts/vk_validation_stats.py

Make the sought-for argument match the help text.
(Look for -text instead of -txt)

scripts: Fix processing of -text arg [skip ci]

---

layers/descriptor_sets.cpp
tests/layer_validation_tests.cpp

Implements validation of effective range when VK_WHOLE_SIZE is used in
vkUpdateDescriptorSets with uniform or storage buffers.

layers: Validation of VK_WHOLE_SIZE in descriptor sets

---

layers/core_validation.cpp

More work done towards converting Core Validation functions to a precall/postcall format. This PR contains changes to the majority of the remaining Core functions.
Batch 4 of not as many as I thought.

Update Core Validation functions to pre/postcall format (large batch)

---

layers/buffer_validation.cpp
layers/core_validation.cpp
layers/core_validation_types.h
layers/shader_validation.cpp

Address the false positives documented here: https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/238
This PR includes some cleanup and reorg but the functional change is in the third commit:
> The shader capabilities table was storing pointers to specific enable booleans, but the table has a static lifetime so only capabilities from the first VkDevice were being captured and used for comparison.  This change goes back to storing pointers-to-member so that the capabilities used for comparison reflect the current device and the lookup table can remain static.

Fix shader capability validation false positives 

---

layers/shader_validation.cpp
scripts/known_good.json

spirv-tools now [supports the Vulkan 1.1 environment qualifier](https://github.com/KhronosGroup/SPIRV-Tools/pull/1629) and that fix was recently incorporated into the glslang [known_good](https://github.com/KhronosGroup/glslang/pull/1453) tag. This seems like an opportune time to start using the 1.1 environment variable in shader validation, and close a few lingering issues.
Fixes #158 
Fixes #101 
Fixes #74 
Note that this PR requires a refresh of the glslang repo (via `update_glslang_sources.py`) to work correctly. Prior to that refresh, validation will fail to detect any illegal SPIRV capabilities within a shader when run in a Vulkan 1.1 environment.

Provide Vulkan_1_1 environment to SPIR-V tools, when appropriate

---

layers/shader_validation.cpp
tests/layer_validation_tests.cpp

We were emitting type trees here, which are ridiculously large for
SSBOs, etc.

Improve error messages for pipeline/descriptor mismatches

---

.travis.yml
scripts/known_good.json
scripts/update_deps.py

The new LunarG-VulkanTools build process results in failure when using VulkanTools tip-of-tree. This commit updates everything necessary for build success.
`update_deps.py` was modified to no longer build LunarG/VulkanTools due to the VulkanTools build now requiring the VVL install directory. The VulkanTools build step is now kicked off in the `.travis.yml` file.

Update LG-VT known-good and build scripts

---

layers/core_validation_error_enums.h
layers/shader_validation.cpp
tests/layer_validation_tests.cpp

Fixes #8.
Added SC validation call to check that PointSize is set in the last geometry shader stage, along with a test.

Validate that PointSize is set in shader when using TOPOLOGY_POINT_LIST

---

layers/core_validation.cpp

Extensions can create fences s.t. validation is not aware of them.
Added logic to handle unknown fences in core validation.
Addresses #268

Eliminate crash for unknown fence

---

scripts/known_good.json

glslang build now supports ccache in CMake via the USE_CCACHE option.
This is necessary to allow ccache to work in CMake-generated makefiles.

build: Activate ccache for glslang in Travis-CI

---

layers/buffer_validation.cpp
layers/core_validation.cpp
tests/layer_validation_tests.cpp

Header updates were made without running `vk_validation_stats.py -c` to check for consistency errors. This commit corrects that oversight with appropriate VUID changes.
Files updated:
layers/buffer_validation.cpp
layers/core_validation.cpp
tests/layer_validation_tests.cpp

Update recently modified VUIDs throughout repo

---

build-android/known_good.json
layers/linux/VkLayer_core_validation.json
layers/linux/VkLayer_object_tracker.json
layers/linux/VkLayer_parameter_validation.json
layers/linux/VkLayer_standard_validation.json
layers/linux/VkLayer_threading.json
layers/linux/VkLayer_unique_objects.json
layers/macos/VkLayer_core_validation.json
layers/macos/VkLayer_object_tracker.json
layers/macos/VkLayer_parameter_validation.json
layers/macos/VkLayer_standard_validation.json
layers/macos/VkLayer_threading.json
layers/macos/VkLayer_unique_objects.json
layers/windows/VkLayer_core_validation.json
layers/windows/VkLayer_object_tracker.json
layers/windows/VkLayer_parameter_validation.json
layers/windows/VkLayer_standard_validation.json
layers/windows/VkLayer_threading.json
layers/windows/VkLayer_unique_objects.json
scripts/known_good.json
scripts/parameter_validation_generator.py
tests/layers/linux/VkLayer_device_profile_api.json
tests/layers/windows/VkLayer_device_profile_api.json

This PR updates the known-good SHAs and changes the `parameter_validation_generator.py` script to exclude disabled enums in `parameter_validation.cpp` which were causing errors after the header update.

Update known-good for 1.1.83 headers

---

layers/shader_validation.cpp
tests/layer_validation_tests.cpp
tests/vktestframework.cpp
tests/vktestframework.h
tests/vktestframeworkandroid.cpp
tests/vktestframeworkandroid.h

Tell the SPIR-V validator to skip block layout checking if the
VK_KHR_relaxed_block_layout extension is enabled.
This prevents validation error messages for shaders with
non-compliant layouts when the extension is enabled.
The VK_KHR_relaxed_block_layout extension was promoted to core
in 1.1, so it is "enabled" for 1.1 and later apps all the time.
Since block layout checking is always relaxed in 1.1 or later,
there is really no way to write a negative test for 1.1 or later.
Therefore there is just a positive test that checks that no error
is generated for a shader with a non-compiliant layout.
Fixes #275

layers: Add check and test for relax block layout

---

tests/vkrenderframework.cpp
tests/vkrenderframework.h

Karl added plumbing for including spirv assembly in tests, added a constructor to use it with the framework.

tests: Add constructor overload for spirv-asm

---

tests/layer_validation_tests.cpp
tests/vkrenderframework.cpp

Fixes #263
VkLayerTest.DSAspectBitsErrors was failing as the depth stencil formats
on certain platforms did not support VK_IMAGE_USAGE_SAMPLED_BIT.
This test is now skipped for these platforms.
Change-Id: I5ac270e976a3e1e2163a6111da6d66c8c7352a89

Disable test when needed format not avail

---

tests/layer_validation_tests.cpp

Modified the ExtensionNotEnabled test to exercise the test case that had
been renderer ineffective by unrelated updates.  Updated test to use the
simplest test case to reproduce.
Had to create a situation where the specific extension *was* enabled, but that prerequisite *other* extensions were not, so the change is a little larger than would be otherwise.
Fixes #262 .

tests: Update missing extension test to reenable

---

layers/CMakeLists.txt

Cmake code which installed the layer json files to the appropriate directory was erroneously removed in a recent change. This commit adds install functionality back again.
When testing this PR please verify the json files are where you expect them to be.

build: Update cmake to install json files

---

layers/core_validation.cpp
layers/descriptor_sets.cpp
layers/descriptor_sets.h
tests/layer_validation_tests.cpp

There was a hole in the DescriptorImageInfo layout checking for the first use of the image subresource in a command buffer.  The layout requirement was not recorded and so validation was not properly done at execution-time.  
Fixes #43.

Track DescriptorImageInfo layouts

---

layers/parameter_validation_utils.cpp

For missing extension dependencies, the current validation layer
support emits error messages like:
Missing required extensions for instance extension VK_EXT_xxx,
VK_KHR_yyy.
With the comma, it's easy to read this as saying that there are
unspecified missing required extensions for both "VK_EXT_xxx" and
"VK_KHR_yyy".
Using a colon instead:
Missing required extensions for instance extension VK_EXT_xxx:
VK_KHR_yyy.
makes it clearer VK_KHR_yyy (plus any other listed extensions that
follow) is a missing required extension for VK_EXT_xxx.

Fix format of required extensions error message.

---

layers/buffer_validation.cpp
layers/core_validation.cpp
layers/core_validation_types.h

A release or acquire from an external queue isn't visible to the current instance's validation so to avoid false warnings we no longer validate QFO transfers involving external queues at barrier record time.
Resolves #290
Partially addresses #307

Ignore external queue family validation/record at barrier record time

---

.cmake-format.py
BUILD.md
CMakeLists.txt
cmake/FindVulkan.cmake
external/CMakeLists.txt
layers/CMakeLists.txt
tests/CMakeLists.txt
tests/layers/CMakeLists.txt

This is the first PR cleaning up CMake files in Khronos repos.  It consists primarily of cleanup, dead code/variable removal, and simplification.
This PR (in its current form of many separate commits) meant to make it easier to review;  it will be squashed to a single commit before pushing to VVL master.

CMake cleanup, part 1

---

layers/core_validation.cpp
layers/descriptor_sets.cpp

Tony's CTS test passes revealed a couple of logic holes -- check if image/sampler descriptors are updated before adding to image layout map, and account for a sparse descriptor set vector.

layers: Fix DescSet Image Layout null deref

---

scripts/parameter_validation_generator.py

Parameter validation was not gathering and processing structure information correctly for one of the 84 Headers extensions

Modify parameter_validation generator to accommodate new extensions

---

layers/core_validation_types.h

The `IsSpecial` function was throwing build warnings, informing us that type qualifiers were being ignored.
This change removes the offending qualifier.

Cleanup VVL build warnings

---

layers/shader_validation.cpp

Take care of false positives related to implicit decls in glsl gl_PerVertex structures.
Fixes #321.

layers: Fix false positive in pointsize write check

---

layers/core_validation.cpp
layers/parameter_validation_utils.cpp
tests/layer_validation_tests.cpp
tests/vkrenderframework.cpp
tests/vkrenderframework.h

The promotion of extensions was being treated inconsistently  by layers, framework, and tests, with the result being inconsistent errors between 1.0 and 1.1 drivers.
This set of changes unties this knot, cleaning up the tests that the fixes would otherwise break.

Clean up for "ExtensionNotEnabled" with prerequisite framework fixes.

---

layers/core_validation.cpp

This doesn't pretend to understand the new bits -- device masks, etc -- but is enough to make validation of ANI2 work as well as ANI does today.

layers: Add basic support for AcquireNextImage2KHR

---

scripts/known_good.json

The wget from glslang master-tot is failing... but we don't really need it....
Since update is already building glsl, have Vulkan-Tools point to the
built copy and not wget it.

scripts: Add glslang to Vulkan-Tools VVL known good dependency list 

---

layers/parameter_validation_utils.cpp
tests/layer_validation_tests.cpp

Added 2D-array-compat flag/3d imagetype check, vuid 950.
Fixes #333.

Check for 3D image with 2D_ARRAY_COMPAT flag

---

layers/core_validation.cpp
tests/layer_validation_tests.cpp

The language of the error message was confusing relative to whether the
second queue handle displayed referred to a signalling or waiting queue.
Rephrased message to clarify that the second queue is the prior
signalling queue.  Updated test to handle changed message text.

layers: Clarify semaphore error message

---

layers/core_validation.cpp
layers/core_validation_types.h

This PR contains relatively more complicated changes and concludes the conversion of Core Validation functions to a precall/postcall format.
Closes #77 - excepting `vkGetDeviceProcAddr` and `vkGetInstanceProcAddr` which contain neither validation nor recording.
Batch 5 of 5

Update Core Validation functions to pre/postcall format 

---

layers/buffer_validation.cpp
layers/buffer_validation.h
layers/core_validation.cpp
layers/core_validation_types.h
tests/layer_validation_tests.cpp

During BeginRenderpass, if a framebuffer contain references to (incorrectly) deleted image view objects, the stale handles could cause a variety of crashes.
Validation error reporting and crash prevention/robustness checks have been added, and a unit test created for the condition (thanks @karl-lunarg for the ULT)
Fixes #329 .

Avoid crashes/report errors for condition where attachment handles have become stale

---

build-android/known_good.json
scripts/known_good.json
tests/CMakeLists.txt
tests/vktestframework.cpp

Fix compilation errors in vk_layer_validation_tests due to uninitialized garbage in glslang's builtin limits. This was caused in part by the structure size mismatching between the glslang library compile and the test framework compile, which is fixed by #defining NV_EXTENSIONS in cmake.
This happens when running a TOT validation layer against a glslang after the Turing extensions were merged yesterday.
I've talked with JohnK about possibly removing the ifdef from the structure definitions, but this gets things working in the meantime.

Fix GLSL compilation errors in vk_layer_validation_tests

---

build-android/jni/Android.mk
build-android/known_good.json
tests/vktestframeworkandroid.cpp

This sprinkles the extension defines around and adds some logging for the future.  Also updates shaderc revision to pull in upstream fixes.  Android tests get back to passing state.

 Fix Android tests

---

layers/core_validation_types.h

Added default constructor for LAST_BOUND_STATE because the default
constructor VS2013 was calling for unordered_map::operator [] was
leaving the structure uninitialized.

layers: Fixed portablity issue in new ext support

---

layers/core_validation.cpp
layers/object_tracker.h
layers/object_tracker_utils.cpp
layers/parameter_validation.h
layers/parameter_validation_utils.cpp
layers/threading.cpp
layers/unique_objects.cpp
scripts/dispatch_table_helper_generator.py
scripts/object_tracker_generator.py
scripts/parameter_validation_generator.py
scripts/threading_generator.py
scripts/unique_objects_generator.py

Change GetDeviceProcAddr policy such that nullptr are returned for any
entry point which has a nullptr in the dispatch table.
Fixes #304

layers: Prevent layer calls with null dispatches.

---

layers/core_validation.cpp

The subpass and barrier layouts were switched round.

Fix image layout error message

---

layers/buffer_validation.cpp

The new layout from KHR_maintenance2 were not allowed in the checks of input attachments, so spurious errors were produced.
Fixes #373.

Fix input attachment layout validation

---

layers/parameter_validation_utils.cpp

The spec was clarified that these formats can be used without the feature being enabled, so remove the checks.
Fixes #336.

Stop requiring texureCompression* features

---

layers/core_validation.cpp

Add locking around Record function for UpdateDescriptorSetWithTemplate
and UpdateDescriptorSetWithTemplateKHR.

layers: Add missing locks for UDSWithTemplate

---

layers/buffer_validation.cpp

When checking buffer bounds in image to buffer copies, the required buffer size must
account for the texel block size for compressed or single plane "_422" image formats.
Change-Id: Id9de7debe9e66cba35e39762a67cfb7e3c35bc07

layers: Handle texel block size for image to buffer copies

---

layers/buffer_validation.cpp
layers/core_validation.cpp
layers/core_validation_types.h
layers/descriptor_sets.cpp
layers/descriptor_sets.h
layers/parameter_validation_utils.cpp
layers/unique_objects.cpp
layers/unique_objects.h

Many of the layers source files fell out of clang-format compliance recently (you know who you are!), which can produce false-positive diffs in following PRs. This commit is whitespace only, bringing the VL layers directory back to clang-format cleanliness.

Whitespace changes - bring layers source back to clang-format cleanliness

---

CMakeLists.txt
external/CMakeLists.txt
layers/CMakeLists.txt
tests/CMakeLists.txt
tests/layers/CMakeLists.txt

This is another PR cleaning up CMake files.  It includes: using modern CMake idioms, removing dead code/variables, simplifying conditions, and some cosmetic/whitespace changes.
This PR, in its current form of many separate commits, meant to make it easier to review.  It will be squashed to a single commit before pushing into master.
The last commit of the series runs the cmake_format tool, so don't worry about ugly code in intermediate commits.
This PR passes LunarG internal CI.

build: More CMake refinements

---

scripts/unique_objects_generator.py

This affects three generated commands in unique_objects_wrapper.h:
- CreateDisplayModeKHR: unwrap display
- RegisterDisplayEventEXT: unwrap display
- CreateRaytracingPipelinesNVX: unwrap pipelineCache
We had an internal report of vkCreateRaytracingPipelinesNVX crashing with validation layers.

Fix unique_objects to unwrap pipelineCache in CreateRaytracingPipelinesNVX

---

scripts/parameter_validation_generator.py

"PCIBus" was confusing the parameter validation build script so a new substitution was added to correct this. I also reordered the list of substitutions so things would be easier to find.

Update parameter validation script for 1.1.89

---

layers/parameter_validation_utils.cpp

Prior to this change, VkPipelineColorBlendStateCreateInfo erroneously
did not specify any acceptable Vulkan structures for its pNext member
Closes #415

layers: Specify VkPipelineColorBlendStateCI pNext

---

scripts/helper_file_generator.py
scripts/parameter_validation_generator.py

The 1.1.90 header introduced the use of "\textrm" in `vk.xml`, requiring
changes to:
- scripts/helper_file_generator.py
- scripts/parameter_validation_generator.py

scripts: Extend scope of LaTeX handling

---

layers/core_validation.cpp
layers/descriptor_sets.cpp
layers/descriptor_sets.h

Further refined the restriction of descriptor set image layout
requirement entries to eliminate false positives for unused bindings
within active descriptor sets.
Integrated image layout requirement setting into "dirty-only" drawstate
update framework to reduce overhead.
Should replace [Narrow down descset image layout checks # 432](https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/432)

Refine descriptor required layout tracking

---

layers/threading.cpp
layers/threading.h
scripts/threading_generator.py

Change the transitivity of usage counters such that only externally
synchronized command buffers mark their command pool as being an active
writer.
Added additional tracking for non-externally sync'd command buffers
s.t. command pool reset and destroy operations detect usage races.
Fixes #376

layers: Kill false thread errors re: command pool

---

layers/core_validation.cpp
layers/object_tracker_utils.cpp

After finding the display routines that needed to handle VK_INCOMPLETE as a return code, I went through the spec to see which other routines needed to handle it and verified that they were.  This fixes the api calls that were not handling it correctly.

layers: Tolerate return code of INCOMPLETE

---

build-android/known_good.json
layers/shader_validation.cpp
scripts/known_good.json

The latest version of glslang uses newly promoted `NVX` extensions (to `NV`) requiring the known-good files and shader validation code to be updated.
Updated:
- `build-android/known_good.json`
- `layers/shader_validation.cpp`
- `scripts/known_good.json`

layers: Bump glslang known-good

---

scripts/dispatch_table_helper_generator.py
scripts/helper_file_generator.py
scripts/loader_extension_generator.py
scripts/lvl_genvk.py
scripts/object_tracker_generator.py
scripts/parameter_validation_generator.py
scripts/parse_test_results.py
scripts/threading_generator.py
scripts/unique_objects_generator.py
scripts/vk_validation_stats.py

This is a trivial change that replaces `==` operator with `is` operator, following PEP 8 guideline:
> Comparisons to singletons like None should always be done with is or is not, never the equality operators.
https://legacy.python.org/dev/peps/pep-0008/#programming-recommendations

Compare to `None` using identity `is` operator

---

build-android/cmake/layerlib/CMakeLists.txt
build-android/jni/Android.mk
layers/core_validation.cpp
layers/shader_validation.h
tests/layer_validation_tests.cpp

Shader_validation did not yet handle group decorations.  Added an optimizer pass to flatten group decorations before doing any layer-side validation.  Used a cut-down version of the failing CTS case for the new validation test. 
Fixes #20.
Added @cnorthrop to vet the untested Android-cmake changes.

Support OpGroupDecorate in Shader Validation

---

layers/core_validation.cpp

This is broken for inline_uniform descriptors and manifested in the CTS tests. The other descriptor types were OK because they only do +=descriptorCount, but it's unclear whether this was by design or by accident so I applied to fix to all types.

Don't count unused descriptors against descriptor limits.

---

scripts/parameter_validation_generator.py

Avoids validating structs that could be uninitialized until filled in by the driver
Address #458
Change removes pNext validation from:
vkEnumeratePhysicalDeviceGroups
vkGetImageMemoryRequirements2
vkGetBufferMemoryRequirements2
vkGetImageSparseMemoryRequirements2
vkGetPhysicalDeviceProperties2
vkGetPhysicalDeviceFormatProperties2
vkGetPhysicalDeviceImageFormatProperties2
vkGetPhysicalDeviceQueueFamilyProperties2
vkGetPhysicalDeviceMemoryProperties2
vkGetPhysicalDeviceSparseImageFormatProperties2
vkGetPhysicalDeviceExternalBufferProperties
vkGetPhysicalDeviceExternalFenceProperties
vkGetPhysicalDeviceExternalSemaphoreProperties
vkGetDescriptorSetLayoutSupport
vkGetPhysicalDeviceProperties2KHR
vkGetPhysicalDeviceFormatProperties2KHR
vkGetPhysicalDeviceImageFormatProperties2KHR …

layers: Dont validate non-const pNexts

---

tests/layer_validation_tests.cpp

Old NV Linux drivers won't tolerate the unexpected errors.
Should supersede #468.

Remove OpGroupDecorate unexpected errors

---

.travis.yml
build-android/jni/Android.mk
build-android/jni/Application.mk

Updates the `travis.yml` and `Android.mk` files to specify building with the current NDK version (r18b) and for platform 26 (Oreo). Required to support the `VK_ANDROID_external_memory_android_hardware_buffer`
extension, which is defined in the NDK only at platform 26 or later.

Update Android NDK and platform versions

---

layers/core_validation.cpp
layers/descriptor_sets.cpp
layers/descriptor_sets.h
tests/layer_validation_tests.cpp

Fixes #395
Reuse the descriptor set template decoder to validate the update using the non-template functionality, with parameterization of the calling function name to disambiguate the validation messages.
One test had to be changed to VUID string avoid expected message
Add tests to spot check the addition of descriptor update validation for templated updates.

Add descriptor validation for UpdateDescriptorSetWithTemplate

---

scripts/update_deps.py

Normalize (all slashes going the same direction) and escape (`\` to `\\`) paths when writing helper.cmake.  CMake was previously interpreting the single `\` characters and whatever followed as invalid escape sequences on Windows. Linux and macOS are unaffected.
helper.cmake before:
```
set(GLSLANG_INSTALL_DIR "C:\Users\mike\Projects\glslang/build/install" CACHE STRING "" FORCE)
set(VULKAN_HEADERS_INSTALL_DIR "C:\Users\mike\Projects\Vulkan-Headers/build/install" CACHE STRING "" FORCE)
set(VULKAN_LOADER_INSTALL_DIR "C:\Users\mike\Projects\Vulkan-Loader/build/install" CACHE STRING "" FORCE)
```
helper.cmake after:
```
set(GLSLANG_INSTALL_DIR "C:\\Users\\mike\\Projects\\glslang\\build\\install" CACHE STRING "" FORCE)
set(VULKAN_HEADERS_INSTALL_DIR …
```

scripts: Fix windows paths in helper.cmake

---

BUILD.md

The name of the cube demo in Vulkan-Tools has changed to vkcube

docs: Change references to cube to vkcube

---

layers/descriptor_sets.cpp
layers/descriptor_sets.h

The descriptor set layout definition dictionary uses the hash and
equality functions to determine uniqueness and equivalence.
Added the new extension data fields to these operations to ensure
correct function w.r.t. descriptor set creation and pipeline layout
compatibility.

Update DescriptorSetLayoutDef hash and equality for new fields

---

scripts/vk_validation_stats.py

Tweak the validation_stats python script to include spec version and creation time when generating the `vk_validation_error_messages.h` header file.

Add spec version comment to error message header

---

layers/core_validation.cpp
layers/object_tracker_utils.cpp
layers/parameter_validation_utils.cpp
layers/threading.cpp
layers/unique_objects.cpp
layers/vk_layer_logging.h
layers/vk_layer_utils.cpp

Layers registered two default callbacks if application registered none, which resulted in duplicate validation messages being output.  Fixed this in the validation layers, as well as a bug in the windows outputdebugstring version of the callback logging function.
@karl-lunarg, once the board is clear, can you check that this resolves your issues?

Prevent duplicate validation messages when using default debug callbacks

---

build-android/AndroidManifest.xml
build-android/jni/Android.mk
layers/android_ndk_types.h
layers/buffer_validation.cpp
layers/buffer_validation.h
layers/core_validation.cpp
layers/core_validation.h
layers/core_validation_types.h
layers/descriptor_sets.cpp

All validation is updated with the revised VUs in spec version 1.1.92. All Gerrit and Travis build issues seem resolved. Ready for review and push.
> WIP - won't compile for Android as-is.  Has replicated NDK typedefs and enums in core_validation_types.h that must be replaced with the appropriate NDK #includes.
> 
> Adds core validation checks for new VUIDs added with the VK_ANDROID_external_memory_android_hardware_buffer extension.
> 
> For review.

VK_ANDROID_external_memory_android_hardware_buffer validation

---

scripts/object_tracker_generator.py
scripts/parameter_validation_generator.py
scripts/unique_objects_generator.py

Current code gen will tolerate the self-referential VkBase* structures in the header, but will crash if they are actually used in any entry point.

Codegen fixes for VkBase(In|Out)Structure

---

layers/buffer_validation.cpp
tests/layer_validation_tests.cpp

* Standardise on "vkCreateImage: " rather than "CreateImage: " or
"vkCreateImage(): ".
* Report one failure if attempting to create an image with an
unsupported format. This is a bit less confusing than printing one
message for each format_limit saying that the max is 0.

Improve error messages for vkCreateImage

---

layers/core_validation.cpp
layers/core_validation_error_enums.h
layers/core_validation_types.h
layers/descriptor_sets.cpp
layers/descriptor_sets.h
tests/layer_validation_tests.cpp

Add validation of CmdPushDescriptorSet(WithTemplate) descriptor state updates, removing the code disabling later use of the recorded data.
Addresses #413 and #428

Add push descriptor validation

---

layers/parameter_validation_utils.cpp

Implement "offset must be multiple of 4" test for vkCmdDispatchIndirect.
VUID-vkCmdDispatchIndirect-offset-00406
Positive test implicit in extant VkLayerTest.InvalidPipeline case.
Fixes #479

Add offset modulo test in DispatchIndirect

---

scripts/dispatch_table_helper_generator.py

The DebugUtils functions are from an Instance extension but are in the device dispatch table. This change prevents their exclusion from having  stub functions generated for them. Previously, the last layer didn't hook this function, and the other layers specifically made this null-check in their intercept routines (which should have been unnecessary, and now will be).
This fixes crashes when running `cube --validate.`
Change-Id: I67d351e13ede9995642a0922b146a02da6c153b2

layers: Add stub functions for DebugUtils functions

---

scripts/layer_chassis_dispatch_generator.py
scripts/layer_chassis_generator.py

Track which descriptor sets are allocated from each pool in the handle wrapping code.  Clean up implicitly freed descriptor sets when a descriptor pool is reset or destroyed.
Fixes #236

Fix memory leak in handle wrapping code

---

layers/vk_layer_logging.h

Set the logical length of the sprintf'd string to match the strlen.
issue reported by @cmayer1

Set string logical length correctly in string_sprintf

---

layers/descriptor_sets.cpp

Fixes #521 
This prevents a false positive reported in #521 when VK_DESCRIPTOR_BINDING_UPDATE_AFTER_BIND_BIT_EXT is enabled.
However, it does not address a number of other validation updates required for VK_DESCRIPTOR_BINDING_UPDATE_AFTER_BIND_BIT_EXT.
I'll file a separate issue to track complete validation for that bit.

layers:Fix descriptor not updated false positive

---

layers/core_validation.cpp
scripts/helper_file_generator.py
scripts/layer_chassis_generator.py

Added support for object naming, queue labeling, and command buffer labeling to the layer chassis.
Also add instance extensions to the list of extensions enabled for GetDeviceProcAddress calls to pick up device APIs that are part of instance extensions.
Fixes #522.
It is likely that to properly test the features of this extension (without overhauling the LVTs) requires a standalone test script, similar to the ones for vulkaninfo or the assistant layer.

Add DebugUtils naming and labeling to chassis

---

layers/descriptor_sets.cpp

We're not validating descriptors with VK_DESCRIPTOR_BINDING_PARTIALLY_BOUND_BIT_EXT or VK_DESCRIPTOR_BINDING_UPDATE_AFTER_BIND_BIT_EXT, we shouldn't be recording their state either.
Fixes #524

layers: Don't record unvalidated descriptors

---

layers/buffer_validation.cpp
layers/vk_format_utils.cpp
layers/vk_format_utils.h
tests/layer_validation_tests.cpp

Add an adjustment to image subresource extent when the aspect selects a compressed plane from a multiplane format.
Fixes #472.

Adjust extents for compressed planes of multiplane images

---

build-android/build_all.sh
build-android/jni/Application.mk
build-android/test_APK.sh
layers/android_ndk_types.h
layers/buffer_validation.cpp
layers/core_validation.cpp
layers/core_validation_types.h
tests/layer_validation_tests.cpp

Adds tests for new AndroidHardwareBuffer extension VUID checks. Includes some minor fixes to the validation code, exposed during creation of the new tests. Updated a previously-missed build script to platform 26.
Apologies on the large diff in layer_validation_tests.cpp: Apparently an bunch of non-clang-formatted changes were sneaked in, and I did a whole-file clang-format at some point that I cannot back out. You can safely ignore any diffs in that file above line 35392 as being not part of this PR.
Also modified the script for testing the Android apk, to be much less verbose on successful runs, and even more verbose on failed runs.

Validation tests for Android Hardware Buffer extension

---

tests/vkrenderframework.cpp
tests/vkrenderframework.h

DeviceCanDraw - Indicates if device is capable of drawing
for use in tests that require shader execution, etc.
CopyOut - Copies RT image to a staging image.
Read - Returns a 16x16 pixel block.
DeviceIsMockICD -  Indicates if device identifies itself as the
Mock ICD according to its device properties.  Can be fooled by DevSim.

tests: Add Framework support for reading RT images

---

scripts/layer_chassis_dispatch_generator.py
tests/layer_validation_tests.cpp

When the handle-wrapping code processed pnext chains, it ignored pnext-only structures that contained no non-dispatchable objects (or that had no sister structures containing NDOs). This change causes **all** structs that can be part of a pNext chain to be wrapped by the dispatcher, which allows data returned from the driver to be passed back up to the caller.
Fixes LunarXchange issue #817.

Preserve pNext chain data in chassis dispatch (unique objects)

---

tests/layer_validation_tests.cpp

PnextOnlyStructWrapping test used a handleType that caused some Android platforms to barf. Changed to a more compatible handle type.

Fix pnext struct handling test Android issue

---

layers/vk_layer_logging.h

If there are more End markers than Begin markers at any time, the vector
that keeps track of the labels will issue a `pop_back()` while being
empty, causing a crash.
This was observed on ANGLE's Vulkan backend executing deqp test
dEQP.GLES2/functional_debug_marker_random.

Fix a crash with unbalanced debug markers

---

scripts/layer_chassis_generator.py

The threading PostCallRecord functions must be called even for non-success return codes.
Fixes #574.
The long-term answer is to pass return codes to the post-call routines and let them sort it out, but that wouldn't make this SDK.

Allow threading to tolerate non-SUCCESS return codes

---

build-android/cmake/layerlib/CMakeLists.txt
build-android/jni/Android.mk
docs/core_validation_layer.md
docs/gpu_validation.md
docs/object_tracker_layer.md
docs/parameter_validation_layer.md
docs/threading_layer.md
docs/unique_objects_layer.md
layers/CMakeLists.txt
layers/core_validation.cpp
layers/core_validation_types.h
layers/gpu_validation.cpp
layers/gpu_validation.h
layers/shader_validation.cpp
layers/shader_validation.h
tests/layer_validation_tests.cpp
tests/vkrenderframework.cpp
tests/vkrenderframework.h
tests/vktestframework.cpp
tests/vktestframework.h
tests/vktestframeworkandroid.cpp
tests/vktestframeworkandroid.h

Add GPU-Assisted support to the core validation layer
Add VLT test for above
Add documentation
Bump glslang version to pickup required SPIRV-Tools dependencies
Please see `docs/gpu_validation.md` for a design document which may be helpful for review.
The original development branch is in karl-lunarg/Vulkan-ValidationLayers branch: karl-gpu which has all the individual commits, but is unlikely to be useful for review.  It will probably be easier to look at the design doc and the code.  The main code file is all brand new anyway.

Add GPU-Assisted Validation Support

---

layers/gpu_validation.cpp

This is a temporary fix to address a missing array stride
decoration in the SPIR-V generated by the instrumentation pass.
This fix should be removed once a spirv-tools version with the fix
is available via known-good.  This fix is designed to coexist with
a fixed spirv-tools, so it does not have to be removed immediately
when using the fixed spirv-tools.

gpu: Add missing stride decoration

---

layers/core_validation.cpp
layers/core_validation_types.h
tests/layer_validation_tests.cpp

Add checks for explicit VUIDs in the extension, and tests to exercise.
Resolves #168

Add VK_EXT_vertex_attribute_divisor validation

---

build-android/cmake/layerlib/CMakeLists.txt
build-android/jni/Android.mk
layers/CMakeLists.txt
layers/buffer_validation.cpp
layers/core_dispatch.cpp
layers/core_validation.cpp
layers/core_validation.h
layers/core_validation_types.h
layers/gpu_validation.cpp
layers/gpu_validation.h

Step 0.0.1 of the CV core-chassis conversion.  Removing the core function definitions out of core_validation.cpp and into core_dispatch.cpp.  This batch contains about 90 APIs moved.

Move core functions out of core_validation.cpp and into core_dispatch.cpp

---

tests/layer_validation_tests.cpp

Tests failing on Pixel2, probably due to issues in gpu validation.
Disabling test on Android until solved.
Change-Id: Ib14363dd7ffccddeffa38cf59ce288b9ba86e218

tests: Temp disable GPU test on Android

---

layers/core_validation.cpp
tests/layer_validation_tests.cpp

There was a check that attachment referenced don't have duplicate attachment IDs. Spec says it's allowed as long as they have identical image layouts. The duplicate reference check was removed, and a check for the image layouts was added. There's also some code cleanup to reuse the same renderpass2 related code repeated in several tests.

Remove duplicate attachment reference checking and add image layout check for duplicate references.

---

layers/gpu_validation.cpp

layers:Initialize gpu validation variables

---

layers/buffer_validation.cpp
layers/buffer_validation.h
layers/core_dispatch.cpp

All pre- and post-record/validate routines will require function signatures that match their parent API call.  This change normalizes all the buffer validation pre & post functions.

Normalize buffer validation pre/post routine call signatures

---

layers/CMakeLists.txt

Core_dispatch.cpp needs it, and unique_objects.cpp no longer exists.

Update 'bigobj' list for VS2013

---

layers/object_tracker_utils.cpp
layers/parameter_validation_utils.cpp
layers/stateless_validation.h
scripts/layer_chassis_generator.py
scripts/object_tracker_generator.py
scripts/thread_safety_generator.py

In several cases, PostCallRecordApi functions need to do different things depending upon the return code. The most flexible way to handle this is to allow each validation object's PCR routines to decide this for themselves.
All PostCallRecord functions returning a VkResult will now have VkResult as an additional, final parameter.

Pass VkResult to PostCallRecordApi* functions

---

layers/core_validation.cpp

This adds a missing check which fixes a crash seen when running apps that use VK_KHR_depth_stencil_resolve extension together with validation layers.

VK_KHR_depth_stencil_resolve validation: Add a missing nullptr check

---

layers/buffer_validation.cpp
layers/core_validation.cpp
layers/vk_format_utils.cpp
layers/vk_format_utils.h
tests/layer_validation_tests.cpp

Clean up partial & missing multi-plane support in vk_format_utils. Rename size functions to distinguish single texel size from format raw element size. Corrects a validation error which was erroneously using element size where texel size was needed.
Fixes #577.

Format utilities for multi-plane

---

scripts/dispatch_table_helper_generator.py

The vk_dispatch_table_helper.h stubs only supported return values
of 'void' or 'VkResult'.  Add support for more.
Change-Id: Ib76d0aa8ebc78e3e17d182f648f5dd1da9039749

layers: Fix GCC 8 warnings from current build

---

layers/buffer_validation.cpp
tests/layer_validation_tests.cpp

In #489 it was pointed out that error messages should be using "vkCmd(): ...", rather than "vkCmd: ...". A quick search shows various places where this is happening, so make them consistent.

layers: Fix other occurrences of vkCmd to vkCmd()

---

layers/core_validation.cpp

In 1.1.97, the following was added to the render pass compatibility rules:
> As an additional special case, if two render passes have a single subpass, they are compatible even if they have different resolve attachment references but satisfy the other compatibility conditions.
To handle this, skip checking compatibility between resolve attachments when `subpassCount == 1`.

Update for render pass resolve attachment compatibility rule change in 1.1.97

---

scripts/vk_validation_stats.py
tests/CMakeLists.txt

In some nested project build configurations, Vulkan-Loader is built at the same time as Vulkan-ValidationLayers, so we should use the built Vulkan::Vulkan target rather than the installed one.
Other fixes are trivial extensions to the same.

Build fixes for nested project builds

---

layers/core_dispatch.cpp

BindBufferMemory2KHR was calling down the layer stack with the non-KHR name causing crashes on a number of implementations.
RP2 entry points were silently falling back to RP1, dropping args in the process.

layers: Fix core_dispatch name mismatches

---

layers/core_dispatch.cpp
layers/core_validation.cpp
layers/core_validation.h

Includes some refactoring of some mixed renderpass recording/validation, and of some goofy create*swapchain support.

Normalize function signatures for vkCreate* pre- and post-calls

---

layers/core_dispatch.cpp
layers/core_validation.cpp
layers/core_validation.h

Includes a surprising amount of lock/unlock cleanup and some new support functions.
- PreCallValidateGetQueryPoolResults
- PreCallValidateGetFenceStatus
- PreCallValidateGetImageMemoryRequirements2
- PreCallValidateGetImageMemoryRequirements2KHR
- PreCallValidateGetSwapchainImagesKHR
- PreCallValidateGetDisplayPlaneSupportedDisplaysKHR
- PreCallValidateGetDisplayPlaneCapabilitiesKHR
- PreCallValidateGetDisplayPlaneCapabilities2KHR
- PreCallValidateGetAndroidHardwareBufferProperties
- PreCallValidateGetMemoryAndroidHardwareBuffer
- PostCallRecordGetFenceStatus
- PostCallRecordGetQueryPoolResults
- PostCallRecordGetDeviceQueue
- PostCallRecordGetBufferMemoryRequirements
- PostCallRecordGetBufferMemoryRequirements2
- PostCallRecordGetBufferMemoryRequirements2KHR
- …

Normalize vkGet* pre/post function call signatures

---

layers/core_dispatch.cpp
layers/core_validation.cpp
layers/core_validation.h

Runs cleanly on internal CI and on Dota2.
- PreCallValidateGetPhysicalDeviceImageFormatProperties2
- PreCallValidateGetPhysicalDeviceImageFormatProperties2KHR
- PreCallValidateGetPhysicalDeviceSurfaceSupportKHR
- PreCallValidateGetPhysicalDeviceSurfaceFormatsKHR
- PreCallValidateGetPhysicalDeviceQueueFamilyProperties
- PreCallValidateGetPhysicalDeviceQueueFamilyProperties2
- PreCallValidateGetPhysicalDeviceQueueFamilyProperties2KHR
- PreCallValidateGetPhysicalDeviceWaylandPresentationSupportKHR
- PreCallValidateGetPhysicalDeviceWin32PresentationSupportKHR
- PreCallValidateGetPhysicalDeviceXcbPresentationSupportKHR
- PreCallValidateGetPhysicalDeviceXlibPresentationSupportKHR
- PostCallRecordGetPhysicalDeviceQueueFamilyProperties
- PostCallRecordGetPhysicalDeviceQueueFamilyProperties2
- …

Normalize vkGetPhysicalDevice* pre/post function signatures 

---

layers/core_dispatch.cpp
layers/core_validation.cpp
layers/core_validation.h

Passes internal CI, passes on Pixel2, and runs cleanly on Dota2.
Includes a change to ValidateCmdDrawType to avoid passing in a previously in/out cb_state parameter.
- PreCallRecordCmdDrawIndirectCountKHR
- PreCallRecordCmdDrawIndexedIndirectCountKHR
- PreCallRecordCmdDrawMeshTasksNV
- PreCallRecordCmdDrawMeshTasksIndirectNV
- PreCallRecordCmdDrawMeshTasksIndirectCountNV
- PostCallRecordCmdDraw
- PostCallRecordCmdDrawIndexed
- PostCallRecordCmdDrawIndexedIndirect
- PostCallRecordCmdDrawIndirect
- PreCallValidateCmdDraw
- PreCallValidateCmdDrawIndexed
- PreCallValidateCmdDrawIndexedIndirect
- PreCallValidateCmdDrawIndexedIndirectCountKHR
- PreCallValidateCmdDrawIndirect
- PreCallValidateCmdDrawIndirectCountKHR
- PreCallValidateCmdDrawMeshTasksNV
- PreCallValidateCmdDrawMeshTasksIndirectNV …

Normalize vkCmdDraw/Dispatch function signatures

---

scripts/layer_chassis_generator.py
scripts/thread_safety_generator.py

The default behavior is to return a lock that has acquired the mutex.
Overrides, such as thread_safety, may take a deferred lock. i.e. It
doesn't acquire the mutex. The goal here is to leverage RAII and SBRM
for lock management.
Change-Id: I274b1e44e62bf143898cca4bee63a6d76effce87

layers: Wrap a unique_lock around chassis mutex

---

layers/buffer_validation.cpp
layers/buffer_validation.h
layers/core_dispatch.cpp
layers/core_validation.cpp
layers/core_validation.h

Also cleaned up some unused parameters, declarations.
Passes on Pixel2, Dota2, and internal CI.
- PreCallValidateCmdSetViewport
- PreCallValidateCmdSetScissor
- PreCallValidateCmdSetExclusiveScissorNV
- PreCallValidateCmdSetViewportShadingRatePaletteNV
- PreCallValidateCmdSetLineWidth
- PreCallValidateCmdSetDepthBias
- PreCallValidateCmdSetBlendConstants
- PreCallValidateCmdSetDepthBounds
- PreCallValidateCmdSetStencilCompareMask
- PreCallValidateCmdSetStencilWriteMask
- PreCallValidateCmdSetStencilReference
- PreCallValidateCmdSetDiscardRectangleEXT
- PreCallValidateCmdSetSampleLocationsEXT
- PreCallRecordCmdSetViewport
- PreCallRecordCmdSetScissor
- PreCallRecordCmdSetExclusiveScissorNV
- PreCallRecordCmdSetViewportShadingRatePaletteNV
- PreCallRecordCmdSetLineWidth
- …

Normalize vkCmdSet*, *Query*, *Event* pre/post function signatures

---

layers/android_ndk_types.h
layers/core_validation.cpp
tests/layer_validation_tests.cpp

The VK_ANDROID_external_memory_android_hardware_buffer references enums in the Android NDK that were added in the platform-28 (Android P) timeframe. This adds compilation guards to avoid missing symbols on Android builds which use older versions of those header files.
Fixes #623

Add guards for missing Android hardware buffer symbols with old NDKs

---

layers/descriptor_sets.cpp
tests/layer_validation_tests.cpp
tests/vkrenderframework.cpp
tests/vkrenderframework.h

Implement check and unit test for VUID-VkWriteDescriptorSet-descriptorType-01403 which requires that descriptor updates for sampled images have specific image layout values.  Note that the language of the spec is being updated to refer to the body text which gives the full set of (extension specific) valid image layout values.
Addtionally
* fixed existing issue in imageLayout tracking in test framework
* refactored/simplified test case which would get the ...-01403 unit test.
Fixes #551

Add VU check for sampled image descriptors

---

CMakeLists.txt
layers/CMakeLists.txt

Disable build of glslang if not building layers or tests.
This is needed so that VulkanTools doesn't need to build glslang.
Change-Id: Ifbed510d689756ed5b36bdf03aa7f31f3914adde

cmake: don't build glslang if not building layers or tests

---

layers/core_dispatch.cpp
layers/core_validation.cpp
layers/core_validation.h

Passes internal CI.
Includes a commit that removes state updates from the vkCmdExecuteCommands validation routine.
- PreCallValidateCmdBindPipeline
- PreCallRecordCmdBindPipeline
- PostCallRecordCmdBindPipeline
- PreCallValidateCmdBindShadingRateImageNV
- PreCallRecordCmdBindShadingRateImageNV
- PreCallValidateCmdBindDescriptorSets
- PreCallRecordCmdBindDescriptorSets
- PreCallValidateCmdBindIndexBuffer
- PreCallRecordCmdBindIndexBuffer
- PreCallValidateCmdBindVertexBuffers
- PreCallRecordCmdBindVertexBuffers
- PreCallValidateCmdBeginRenderPass
- PreCallRecordCmdBeginRenderPass
- PreCallValidateCmdBeginRenderPass2KHR
- PreCallRecordCmdBeginRenderPass2KHR
- PreCallValidateCmdEndRenderPass
- PostCallRecordCmdEndRenderPass
- PreCallValidateCmdEndRenderPass2KHR
- …

Normalize remaining vkCmd* pre/post function signatures

---

layers/buffer_validation.cpp
layers/buffer_validation.h
layers/core_validation.cpp
layers/core_validation_types.h
layers/object_lifetime_validation.h
layers/object_tracker_utils.cpp
layers/parameter_name.h
layers/stateless_validation.h

Change many function parameters from (const)std::string(&) to const char * to reduce
time spent allocating, copying, and deallocating constant string literals into string
objects.
Change ParameterName to hold a const char * and a const size_t * rather than a string
and vector constructed for each parameter validation.
I tested this with a UE4 test app I got from @RCalocaO. Without the validation layers, it is vsynced to 16ms/frame. With the validation layers (before this change) it was around 180ms/frame. After this change (and one other I will push shortly) it is in the 90-100ms range. I also measured around a 33% reduction in validation time running dota2 (cc @danginsburg). Most of the benefit is in parameter_validation, and then smaller improvements in core_validation and …

layers: Reduce time spent constructing strings and vectors

---

layers/core_dispatch.cpp
layers/core_validation.cpp
layers/core_validation.h

Leaving only the stateful or down-chain-modifier APIs, to be handled next.  Passes internal CI and on Pixel 2.0.
- PreCallValidateSetEvent
- PreCallRecordSetEvent
- PreCallValidateImportSemaphoreWin32HandleKHR
- PostCallRecordImportSemaphoreWin32HandleKHR
- PreCallValidateImportSemaphoreFdKHR
- PostCallRecordImportSemaphoreFdKHR
- PreCallValidateImportFenceWin32HandleKHR
- PostCallRecordImportFenceWin32HandleKHR
- PreCallValidateImportFenceFdKHR
- PostCallRecordImportFenceFdKHR
- PreCallValidateAcquireNextImageKHR
- PostCallRecordAcquireNextImageKHR
- PreCallValidateAcquireNextImage2KHR
- PostCallRecordAcquireNextImage2KHR
- PreCallValidateEnumeratePhysicalDevices
- PostCallRecordEnumeratePhysicalDevices
- PreCallRecordEnumeratePhysicalDevices
- …

Normalize last big batch of pre/post function signatures

---

tests/layer_validation_tests.cpp

There were various places where the tests were using features that are
not guaranteed to be supported on implementations. Check features for
query pools and stick to using optimal layout images where possible.

tests: Stop using features that may not be supported

---

layers/buffer_validation.cpp
layers/core_dispatch.cpp
layers/core_validation.cpp
layers/core_validation.h
layers/parameter_validation_utils.cpp
layers/stateless_validation.h
scripts/parameter_validation_generator.py
tests/layer_validation_tests.cpp

As @jeffbolznv pointed out, this layer is almost completely stateless and should not require the standard locking/unlocking around validation calls. 
Parameter validation did contain two bits of state -- one was QueueFamilyIndex range/validity checks which were moved into core validation, and some CreateGraphicsPipeline checks which are dependent on a small bit of renderpass state.  These state updates/checks are now guarded by a local mutex and the base write_lock function has been overridden to avoid taking the validation object lock (like the threading layer). 
Also updated/added QFIndex tests for the new CV checks.
Fixes #643.

Make stateless validation more stateless

---

layers/core_validation.cpp
layers/core_validation_error_enums.h

Refactored dynamic descriptor validation to do *per binding* array lookups instead of *per descriptor* nested map lookups. Locally significant speedup. Small, but measurable overall performance improvement.
Fixes #644

Speed up BindDescriptor validation

---

layers/buffer_validation.cpp
layers/core_validation.cpp

This change adds checks to more spots to see if VkExternalFormatAndroid.externalFormat = 0. If it does equal 0 then the spec states that it should be treated as if the VkExternalFormatANDROID struct was not even present. This was already correctly checked for in ValidateCreateImageANDROID, but this change adds the check to more spots in the layers.

Fixes when VkExternalFormatANDROID.externalFormat = 0

---

layers/core_validation.cpp

When we check to to see if the usages of the VkImage are present on a Android hardwarebuffer, we don't want to check transfer_src and transfer_dst since they have no hardwarebuffer equivalent and are always allowed.

Fix usage check comparing VkImage usage to Android HardwareBuffer

---

layers/core_validation.cpp

The test claims that other usage bits besides the ones list in the Usage Equivalence table are not allowed to be present on the AHardwareBuffer. However in the spec it reads:
"The usage member of AHardwareBuffer_Desc must include bits corresponding to bits included in VkImageCreateInfo::usage and VkImageCreateInfo::flags where such a correspondence exists according to AHardwareBuffer Usage Equivalence. It may also include additional usage bits, including vendor-specific usages."
This suggests that other bits are allowed to be present.

Fix check for compatible AHardwareBuffer usage bits.

---

docs/gpu_validation.md
layers/core_dispatch.cpp
layers/core_validation.cpp
layers/core_validation.h
layers/core_validation_types.h
layers/gpu_validation.cpp
layers/gpu_validation.h

This is in preparation for our next phase of gpu assisted validation.  It also allows reporting of which draw
in the command buffer got which errors.

Make GPU assisted validation per draw

---

build-android/known_good.json
scripts/known_good.json

SPIRV-Tools commit 8d2d66f30c5c25029ac029af2bc9c4aa6979e5bc removed
kInstVertOutVertexId and kInstVertOutInstanceId in favor of index
variants.
Update glslang known-good:
Pick up new spirv-tools instrumentation constant definitions.

build: Update known-good, fix SPIRV-Tools errors

---

layers/gpu_validation.cpp

Now that the glslang / spirv-tools dependencies have been updated, these are no longer necessary

Remove workarounds in gpu assisted validation

---

layers/buffer_validation.cpp

Fixes #685 
Validation test fixed s.t. that resolve attachment is checked for VK_ATTACHMENT_UNUSED before testing layout requirements
The message now correctly states that the RESOLVE attachment (not the color attachment) layout is incorrect.

Fix resolve attach message and val test

---

layers/object_lifetime_validation.h
layers/object_tracker_utils.cpp

Resetting descriptor pools at the end of a frame has some potentially
O(N^2) behavior in the object_tracker layer, where resetting each pool
iterates over ALL allocated sets (across all pools), checking that the
parent matches the pool being reset. This change has each pool track
its children, and Reset only iterates over its children.
This is worth around 5% performance.

layers: in object_tracker, have descriptor_pool track sets it owns

---

layers/core_dispatch.cpp
layers/core_validation.cpp
layers/core_validation.h
layers/gpu_validation.cpp
layers/gpu_validation.h
layers/shader_validation.cpp
layers/shader_validation.h

Reworked the following API pre/post routines to normalize the function calls, along with a single custom additional parameter to preserve state across the API call.  These will get special-cased in the chassis to preserve this method of operation (these special use cases exist either for performance (!) or for GPU validation to modify call parameters.
- bool PreCallValidateCreateGraphicsPipelines
- void PreCallRecordCreateGraphicsPipelines
- void PostCallRecordCreateGraphicsPipelines
- bool PreCallValidateCreateComputePipelines
- void PostCallRecordCreateComputePipelines
- bool PreCallValidateCreatePipelineLayout
- void PreCallRecordCreatePipelineLayout
- void PostCallRecordCreatePipelineLayout
- bool PreCallValidateCreateShaderModule
- void PreCallRecordCreateShaderModule
- void …

Refactor stateful or special-case APIs for future chassis integration

---

layers/buffer_validation.cpp
tests/layer_validation_tests.cpp

Fixes #657 :  Refactored validation of ClearAttachment to improve coverage for secondary command buffers, including those with null framebuffer inheritance. DRY/clean by moving common code to utility adding robust null checks (since nulls are valid in some cases).  Reduced number of lambda functions added to deferred (execute command buffer time) list to one per attachment vs. one per attachment per clear area.
Fixes #678 : Reorder/refactor vkCmdClearAttachments validation s.t. bounds are checked before validation comparison values are looked up.  Added additional bounds checks for renderpass and framebuffer attachment look-ups.

Clean up validation issues with ClearAttachments

---

layers/core_dispatch.cpp
layers/core_validation.cpp
layers/core_validation.h
layers/gpu_validation.cpp
layers/parameter_validation_utils.cpp
layers/stateless_validation.h
layers/vk_layer_logging.h
scripts/layer_chassis_generator.py

Should close some potential holes around calling log_msg from multiple threads.  Added object NAME support to the chassis and to core_dispatch, taking it out of the Pre/Post calls.  
This should simplify the work Locke is beginning as well.

Thread-protect debug report/messenger functions and normalize object label handling

---

layers/core_validation.cpp

With the spate of recent extensions the number of valid bits that `VK_PIPELINE_STAGE_ALL_GRAPHICS_BIT` expands into has changed.  Updated the expansion list from the Vulkan-Docs:chapters/synchronization.txt
list.  Expansion is conditional on enabled extensions.  Bits for non-enabled extensions will not be set during ALL_GRAPHICS_BIT expansion.
Additionally updated stageMask bit to stage ordinal list.
Fixes #695

Update VK_PIPELINE_STAGE_ALL_GRAPHICS_BIT expansion

---

layers/buffer_validation.cpp

Resolve attachment error message was reporting the color attachement
layout instead of the resolve attachment layout in validation error
message involving an incorrect resolve attachment layout.
Corrected log_msg to output the correct attachment layout information.
Fixes #700

Fix resolve attachment layout error message

---

scripts/thread_safety_generator.py
tests/layer_validation_tests.cpp

Threading comes before parameter validation, and passing a null array with a non-zero count crashed the threading layer. Added defensive null checks for bad pointers to get us to parameter-validation, which'll throw useful errors, along with a test to see that the layers survive at least until the error goes out.
Fixes #699.

Add null array protection to the threading layer

---

layers/CMakeLists.txt

A quick Google search showed no downside to doing so, so rather than adding buffer_validation, use it for all files in layers

layers: Compile everything with bigobj

---

layers/core_validation.cpp
scripts/object_tracker_generator.py

The three CreatePipelines APIs are perfectly happy returning less than _count_ number of pipelines objects.  Non-created array members will be set to NULL by the driver, so allow recording of only the created pipeline objects in object_tracker and core_validation.  Fixes crashes in these two CTS tests:
```
dEQP-VK.api.object_management.alloc_callback_fail_multiple.graphics_pipeline
dEQP-VK.api.object_management.alloc_callback_fail_multiple.compute_pipeline
```
Fixes #719.

Fix validation for CreateXxxPipelines partial results

---

scripts/layer_chassis_generator.py
tests/layer_validation_tests.cpp

Layer chassis ignored `DebugUtilsMessenger `callbacks.  Restored this capability for those layers, and added the special-cased `DebugReportCallback `functions to the code-gen'd pile.
Fixes #717.

Fix DebugUtils user debug callbacks

---

layers/core_dispatch.cpp
layers/core_validation.cpp
layers/core_validation.h
tests/layer_validation_tests.cpp

Adds a validation check for `VUID-vkGetDeviceMemoryCommitment-memory-00690` that enforces the `memory must have been created with a memory type that reports VK_MEMORY_PROPERTY_LAZILY_ALLOCATED_BIT` valid usage from the spec. Also adds a negative test for this case.

Add validation for vkGetDeviceMemoryCommitment

---

layers/vk_layer_logging.h
tests/layer_validation_tests.cpp

Spec says a debug label can be changed by calling a debug label API with an old handle and a new name, which was never implemented in the layers logging support.  Also added a test.
Fixes #737.

Add Ability to Change Debug Object Labels

---

docs/core_validation_layer.md
docs/gpu_validation.md
docs/object_tracker_layer.md
docs/parameter_validation_layer.md

As part of sdk rebranding, retain LunarG copyright information in file
internally.
(merged from PR 732-735)

docs: Make copyright internal to file

---

docs/gpu_validation.md
layers/gpu_validation.cpp

The spirv-tools implementation returns only 0 for out of bounds or 1 for descriptor uninitialized

gpu: Fix error codes to match implementation

---

layers/core_validation.cpp
layers/object_tracker_utils.cpp
layers/vk_layer_logging.h
tests/layer_validation_tests.cpp

Added FormatHandle to show handle's name & ID or only ID.
Test the function in core_validation, object_tracker, 
parameter_validation layer.

Add FormatHandle for debug object name

---

scripts/object_tracker_generator.py

OT should not create pipelines if the return code is VK_ERROR_VALIDATION_FAILED_EXT. This fixes scads of unexpected errors in the LVTs.

Avoid ObjectTracker pipeline creation on validation failures

---

layers/gpu_validation.cpp
layers/gpu_validation.h

dEQP-VK.binding_model.descriptorset_random.sets32.runtimesize.
ubolimithigh.sbolimithigh.imglimithigh.iublimithigh.frag.0
and
dEQP-VK.binding_model.descriptorset_random.sets32.runtimesize.
ubolimithigh.sbolimithigh.imglimithigh.iublimithigh.vert.0
both have issues with destroy device happening before the memory
and descriptor set managers go out of scope, causing the validation
code to use an already destroyed device to free the resources
Change-Id: I536b3262f5ddd08fc7aabb6df94b3bb455dc633a

Move gpu assisted validation cleanup out of destructors

---

layers/core_validation_error_enums.h
layers/shader_validation.cpp
tests/layer_validation_tests.cpp

Alpha to coverage uses location 0 alpha component.
* When using alpha to coverage, we should not warn on a "useless" declaration of this output.
* When using alpha to coverage, if location 0 alpha component is _not_ declared, that should be an error.
Fixes #703

Consider alpha to coverage in FS output interface validation

---

tests/layer_validation_tests.cpp

Both tests had been configured for Vulkan 1.0 version but used some non-KHR functions that were not in core until 1.1, so the respective pointer was NULL and used stubs instead, which means than some objects were not properly initialized.
As these are tests for the validation layers themselves, the patch sets the target version to Vulkan 1.1 to fix this.
Fixes segfaults on the following tests on Intel's ANV driver:
```VkPositiveLayerTest.MultiplaneImageTests```
```VkLayerTest.MultiplaneImageSamplerConversionMismatch```

tests: set target API version correctly for some tests

---

layers/buffer_validation.cpp
layers/buffer_validation.h
layers/core_dispatch.cpp
layers/core_validation.cpp
layers/core_validation.h
layers/core_validation_types.h
layers/descriptor_sets.cpp
layers/descriptor_sets.h
layers/gpu_validation.cpp
layers/shader_validation.cpp
layers/shader_validation.h
scripts/layer_chassis_generator.py

Some housekeeping and prep for an upcoming blob of changes for the basic conversion of CV to use the chassis, including handling the weird CV cases that pass state between the pre- and post-calls. That'll be a big fat commit as it is and this should help to reduce the size somewhat.

Prepare for core_validation conversion to layer chassis

---

layers/buffer_validation.cpp
layers/core_validation.cpp
layers/core_validation.h
layers/descriptor_sets.cpp
layers/descriptor_sets.h
layers/gpu_validation.cpp
layers/shader_validation.cpp
scripts/layer_chassis_generator.py

Gets rid of the majority of layer_data cruft in core_validation, and *should* be the last of the big churn-inducing changes.

Remove redundant layer_data refs from core_validation

---

layers/core_validation.cpp

In PreCallValidateCreateGraphicsPipelines, it doesn't create pipeline. 
If we print pipeline in log_msg, it's always 0. It is unhelpful. 
So I use device instead of pipeline. [Issue #527](https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/527)

layers: Show device instead of pipeline

---

tests/layer_validation_tests.cpp

This test now correctly hits the validation errors and exits before doing the recording. Previously, the recording happened regardless, resulting in unexpected errors when the EndQuery calls were executed. Removed them to avoid the additional errors.

Fix layer validation test 'QueryPreciseBit' unexpected errors

---

layers/parameter_validation_utils.cpp
tests/layer_validation_tests.cpp

Set VkPipelineTessellationDomainOriginStateCreateInfo 
in VkPipelineTessellationStateCreateInfo.pNext.
[Issue #747](https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/747)

layers: Set Tessellation CreateInfo pNext

---

build-android/cmake/layerlib/CMakeLists.txt
build-android/jni/Android.mk
layers/CMakeLists.txt
layers/VkLayer_khronos_validation.def
layers/buffer_validation.h
layers/core_validation.cpp
layers/core_validation.h
layers/core_validation_types.h
layers/gpu_validation.cpp
layers/gpu_validation.h
layers/json/VkLayer_khronos_validation.json.in
layers/parameter_validation_utils.cpp
scripts/layer_chassis_dispatch_generator.py
scripts/layer_chassis_generator.py
tests/layer_validation_tests.cpp
tests/vktestframework.cpp
tests/vktestframework.h
tests/vktestframeworkandroid.cpp
tests/vktestframeworkandroid.h

The new and improved `VK_LAYER_KHRONOS_validation`.  
And tests!  Added an argument '`--uberlayer`' to the `layer_validation_tests `so that you can try it yourself.  Should coexist fine with the other layers...
Still some cleanup to do, but much of that will come after the old layers are dropped.

Say 'Hello' to the KHRONOS_validation layer

---

layers/core_validation.cpp
layers/core_validation.h
layers/core_validation_types.h
layers/gpu_validation.cpp
layers/gpu_validation.h

Reduces GPU validation dependencies needed for the core_validation types & structs.

Separate GPUval data from core_validation data

---

tests/layer_validation_tests.cpp
tests/vktestframework.cpp
tests/vktestframework.h
tests/vktestframeworkandroid.cpp
tests/vktestframeworkandroid.h

Switches the layer validation tests to load the Khronos_validation layer by default.  
The option to change this has been renamed to '--uberlayer_disable', which if used will explicitly load the old five individual layers.

tests: Make khronos layer default for LVTs

---

layers/json/VkLayer_standard_validation.json.in

The definition of the meta-layer gets changed to load the khronos validation layer in place of the five legacy layers.
@lenny-lunarg promised this would not affect the loader in any way.

Switch VK_LAYER_LUNARG_standard_validation to load KHRONOS_validation layer

---

layers/vk_layer_config.cpp

This prevented validation output from going to `stdout `when not using a debug callback.

Add default output config entries for khronos layer

---

layers/core_validation.cpp
layers/gpu_validation.cpp
layers/parameter_validation_utils.cpp
scripts/layer_chassis_dispatch_generator.py
scripts/layer_chassis_generator.py

In preparation for gpu assisted validation moving to vma, change dispatch routines to get their own validation object pointer instead of requiring them to be passed as a parameter

layers:Remove dev_data requirement from Dispatch*

---

layers/buffer_validation.cpp
layers/vk_format_utils.cpp
layers/vk_format_utils.h
tests/layer_validation_tests.cpp

Get correct multi-planar size when it runs `vkCmdCopyBufferToImage()`.
[Issue #691](https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/691)

layers: Find multi-planar size

---

layers/vk_layer_logging.h

As subject issue describes, callback was passed a pointer to an out-of-scope local variable.  
Fixes #802.

Fix scoping issue with debug utils/report object names

---

tests/layer_validation_tests.cpp

Android test not run in the VALIDATION_APK will croak on unexpected errors, causing Android failures on rooted devices. Moved these protections out of that scope.
@cnorthrop confirmed that this is all-good on their farm.

Make unexpected errors safe on native Android

---

tests/layer_validation_tests.cpp
tests/vkrenderframework.cpp

Skip the test if the system, like Android, doesn't support Vulkan 1.1+ when it tests invalid device mask.

tests: Device Group requires Vulkan 1.1+

---

docs/gpu_validation.md
layers/core_validation.h
layers/gpu_validation.cpp
layers/gpu_validation.h
layers/vk_mem_alloc.h

In preparation for phase 2 of GPU-AV, replace the block allocator currently used with the more flexible VMA.

Use Vulkan Memory Allocator for GPU-AV

---

CMakeLists.txt

Remove line of code that prevented CMAKE_INSTALL_PREFIX
from being set on MacOS.
Previously, CMAKE_INSTALL_PREFIX would always be
set to CMAKE_BINARY_DIR.

cmake: Fix CMAKE_INSTALL_PREFIX on MacOS

---

tests/layer_validation_tests.cpp
tests/vkrenderframework.cpp
tests/vkrenderframework.h

In not VALIDATION_APK situation, it cannot get Android window
successfully, so it cannot create VkSurface. In this case,
skip VkAcquireNextImageInfoKHR test.
Change-Id: I1d10bd80276716985c21373e9864c242739c2846

tests: Checked VALIDATION_APK for create Android surface

---

layers/core_validation.cpp
layers/core_validation.h
layers/stateless_validation.h
scripts/layer_chassis_generator.py

Added a disable for query validation. To disable, set this in your vk_layer_settings.txt file:
`khronos.validation.disables = VALIDATION_CHECK_DISABLE_QUERY_VALIDATION`
-or- 
set the `VK_LAYER_DISABLES ` environment variable to `VALIDATION_CHECK_DISABLE_QUERY_VALIDATION`
Fixes #4.  Or, at least works around it.
The `VK_EXT_validation_features `extension will be modified to include a flag for this disable.

Add disable for Query validation

---

layers/CMakeLists.txt
layers/libVkLayer_core_validation.map
layers/libVkLayer_khronos_validation.map
layers/libVkLayer_object_lifetimes.map
layers/libVkLayer_stateless_validation.map
layers/libVkLayer_thread_safety.map
layers/libVkLayer_unique_objects.map
tests/layers/CMakeLists.txt
tests/layers/libVkLayer_device_profile_api.map

Added `.map` files to control which symbols should export or hide in Linux. The feature is the same with `.def` files in Visual Studio.
So, maybe we don't need `#define VK_LAYER_EXPORT __attribute__((visibility("default")))` any longer.

Added Linux export symbol

---

layers/buffer_validation.cpp
layers/buffer_validation.h
layers/core_validation.cpp
layers/core_validation.h
layers/core_validation_types.h
layers/descriptor_sets.cpp
layers/sparse_containers.h
tests/layer_validation_tests.cpp

Based on profiling, the map used for tracking image layout state within command buffers was a hot spot.  A new two level (image, then subresource) map is construct where the second level is a specialized, adaptive sparse_vector that can function as a map for sparse usage, and as a vector for dense usage.  In testing, this yielded performance improvement.
Layout tracking was also changed semantically, such that only operations that *change* layout alter the current layout state.  This may cause additional layout incompatibility messages, as subsequent incorrect uses will not be (incorrectly) masked by a previous incorrect use.
Based on user feedback, record time reporting of layout incompatibility is preserved.
Plus low hanging fruit... making bindable resource tracking lazy. Change the …

Image Layout tracking refactor for performance & low hanging fruit perf changes for object binding

---

layers/CMakeLists.txt

Both VkLayer_thread_safety and VkLayer_khronos_validation depend
on the generation of parameter_validation.cpp and parameter_validation.h.
In a parallel build, it's possible for one thread to create these files and
attempt to compile them, while another thread erases and attempts to recreate
them, leading to bizarre compile errors.
This fixes the issue by adding a dependency between VkLayer_khronos_validation
and VkLayer_thread_safety.

layers: Fix build race condition

---

layers/descriptor_sets.cpp
tests/layer_validation_tests.cpp

[issue #50 ](https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/50)
That validate image at descriptor sets update and draw time 
and texel buffer view & buffer at descriptor sets update 
had been added. 
I only added validate texel buffer view & buffer at draw time.

Validate texel buffer view & buffer at draw time

---

layers/descriptor_sets.cpp
tests/layer_validation_tests.cpp

[Issue #726 ](https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/726)
> Based on this text the primary check that we'd like added is to verify at draw time that, if any samplers in the descriptor set contain a YCBCR conversion, then those samplers MUST also exists as immutable samplers in the currently bound pipeline.
The above validation might not work.
Because if it wants to update and bind a descriptor set that contain a YCBCR conversion, it has to pass VUID-VkWriteDescriptorSet-descriptorType-01947 & 01948.
But in the case, the error that a sampler in the descriptor set contain a YCBCR conversion, but it is not an immutable sampler at draw time will not happen.

Validate YCrCb conversion

---

layers/core_validation.cpp
layers/core_validation_types.h
tests/layer_validation_tests.cpp

This implements the correct VUIDs for vkCmdBindPipeline to ensure that the correct pipeline is used with the correct binding points.

core_validation: Implement some missing vkCmdBindPipeline VUIDs

---

layers/drawdispatch.cpp
tests/layer_validation_tests.cpp

Fixes #450. Blocked on #848 being merged.

layers: Check indirect buffer usage

---

.travis.yml

Seems like only DevSim is needed, so the only necessary target should be 'layersvt'.  Skip building VLF, VKTRACE, and related items.

Skip building most of VulkanTools for Travis VVL builds

---

layers/buffer_validation.cpp
layers/core_validation.cpp
layers/core_validation.h
layers/core_validation_types.h
layers/descriptor_sets.cpp
layers/vk_layer_logging.h
scripts/layer_chassis_generator.py
tests/layer_validation_tests.cpp
tests/vktestbinding.h

For descriptor accessed images, implement additional logic supporting
depth only and stencil relaxed layout matching rules.
As the relaxed rules are for the descriptor access cases only, the matching rules are only changed on those paths only. 
Also enabled and fixes crashes in DebugUtils -- with test.
Fixes #316

Add relaxed image layout matching rules

---

layers/parameter_validation_utils.cpp

Dumping wrong value in error message.
Fixes #870.

Fix cut-paste error in parameter validation VertexAttrDescCount logmsg

---

tests/layer_validation_tests.cpp

Test requiring DebugUtils support was failing on some platforms. Revert
the requirement to investigate why layers aren't reporting that support
on all platforms.
Additionally fix the incorrect usage of GetDeviceProcAddr for GetInstanceProcAddr

layers: Revert assertion for/ fix get proc addr DebugUtils support

---

layers/vk_mem_alloc.h

Kudos to Tor Colvin for finding the root cause.
There is a build error on CentOS6 because CentOS6 comes with glibc is 2.12.
As seen on the "Versions" section of the aligned_alloc() manpage: https://linux.die.net/man/3/aligned_alloc, "The function aligned_alloc() was added to glibc in version 2.16. ".
This patch reuses the implementation for Apple and Android (using posix_memalign()) when it is detected that glibc<2.16. For the use of __GLIBC_PREREQ(major,minor) in the patch, this macro is defined since 1999-06-18: https://github.molgen.mpg.de/git-mirror/glibc/blob/master/ChangeLog.10
This was discovered while trying to build the 1.1.106 Vulkan SDK on CentOS6.
Note that this has nothing to do with the gcc/g++ version but only with the glibc version: on CentOS6, I used gcc 6.4.0 and …

aligned_alloc() is only defined for glibc>=2.16

---

layers/gpu_validation.cpp
layers/gpu_validation.h

If we abort gpu-av in CreateDevice because of Vulkan < 1.1 (or any other reason), don't try to cleanup vma or the descriptor set manager in DestroyDevice

Be more careful cleaning up gpu-av resources

---

layers/parameter_validation_utils.cpp
layers/stateless_validation.h
scripts/helper_file_generator.py
scripts/parameter_validation_generator.py
tests/layer_validation_tests.cpp

[issue #855 ](https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/855)
@ShabbyX 
The PR also replaces the whole `GenericHeader` into `VkBaseOutStructure`.

Validate using VkPhysicalDeviceFeatures2 & VkPhysicalDeviceVertexAttributeDivisorFeaturesEXT without enabling the extensions.

---

layers/core_validation.cpp
layers/object_lifetime_validation.h
layers/object_tracker_utils.cpp
layers/shader_validation.h

Old '`INFORMATION`' log messages halved ObjectTracker speed in Dota2.
SPIR-V validator runs _by default_ when SPIR_V optimizer runs.  Since shaders have previously run through the validator, disabling validation during optimizer cut a boatload of time from all `CreateShaderModule `calls.

Improve ObjTracker and CoreValidation Performance

---

tests/layer_validation_tests.cpp

[LunarHub-Doc issue #212 ](https://github.com/LunarG/LunarHub-Doc/issues/212)
Two tests fail in Intel GPU.
**VkLayerTest.CreateImageYcbcrArrayLayers**
```
C:\Users\Locke\Works\Vulkan-ValidationLayers\tests\layer_validation_tests.cpp(38539): error: Expected equality of these values:
VK_SUCCESS
Which is: 0
GPDIFPHelper(gpu(), &image_create_info, &img_limits)
Which is: -11
UNKNOWN_RESULT
```
Check if it supports multiplane image 
**VkPositiveLayerTest.PushDescriptorNullDstSetTest**
```
unknown file: error: SEH exception with code 0xc0000005 thrown in the test body.
VUID-vkDestroyDevice-device-00378(ERROR / SPEC): msgNum: 0 - OBJ ERROR : For device 0x22f6408f5b8, DeviceMemory object 0x6 has not been destroyed. The Vulkan spec states: All child objects created on device must have been …
```

tests: Fix Intel GPU fail

---

layers/buffer_validation.cpp
layers/core_validation.cpp
layers/core_validation.h
layers/descriptor_sets.cpp
layers/gpu_validation.cpp
layers/shader_validation.cpp

Most of these were added to hide layer_data internals from descriptor sets and buffer validation, but all data now exists in the same object so these functions are no longer necessary.  Plus it's less noisy.
Also, a first step toward making the CV object maps private.

Get rid of some old accessor functions

---

layers/descriptor_sets.cpp

The original fix for this was commit b8fd9cc, which was reverted by
mistake in commit f45e45f.
This brings back the fix again.

layers: Use right index to get right descriptor

---

layers/core_validation.h
layers/drawdispatch.cpp
layers/shader_validation.cpp
tests/layer_validation_tests.cpp

[Issue #698](https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/698)
Validate `maxComputeWorkGroupSize` in `vkCreateComputePipelines()` and `maxComputeWorkGroupInvocations` in `vkCmdDispatc()`

Validate maxComputeWorkGroupSize & maxComputeWorkGroupInvocations of Compute shader

---

layers/buffer_validation.cpp
layers/core_validation.cpp
layers/core_validation.h
tests/layer_validation_tests.cpp

Those tests require `Android Q`.
I resolved most problems about AHB tests, besides a test, `AndroidHardwareBufferMemoryAllocation`.
The test needs to `AHardwareBuffer_allocate()` for usage `AHARDWAREBUFFER_USAGE_GPU_MIPMAP_COMPLETE`.
I cannot allocate it successfully. It fails and returns `-12`. It means `NO_MEMORY`.

Fix Android Hardware Buffer tests fail

---

layers/buffer_validation.cpp
layers/buffer_validation.h
layers/core_validation.cpp
layers/core_validation.h
layers/core_validation_types.h
layers/descriptor_sets.cpp
layers/descriptor_sets.h
layers/drawdispatch.cpp
layers/gpu_validation.cpp
layers/shader_validation.cpp
layers/shader_validation.h

Finally got rid of all the old 'node' names for the maps and accessor functions in preparation for moving more of the maps to use unique_ptrs.

CoreChecks object map name normalization

---

layers/gpu_validation.cpp

Old GPUVAL config file settings were overwritten by the default instance settings. Copied instance settings to device in this case.  This'll allow enabling GpuVal using the original config settings.

Make settings consistent using old configs

---

build-android/test_APK.sh

The test_APK script has always defaulted to whatever
primary ABI was in use by the device.  This means no
coverage for 32-bit Android.  We've been covering that
with 32-bit native executable internally, but we need
to support it externally as well.

Android: Specify ABI in test_APK

---

layers/core_validation.cpp
layers/core_validation.h

Replacing numerous cut/paste versions of the extension properties fetch
with a templated utility function.
Was adding the N+1th copy, and it crossed my copy paste threshold.

layers: Refactor CreateDevice physical props fetch

---

layers/buffer_validation.cpp
layers/core_validation_types.h

Add initial image layout state tracking to path it was missing.
Resolves CTS assert.  Refactor initial layout state setup to utility
function.

Fixes CTS assert/ game crash -- Add missing initial image layout state tracking

---

layers/vk_layer_logging.h

layers: Fix vk_layer_logging.h warning with GCC 9

---

layers/descriptor_sets.cpp

Sometimes, `pNext`'s pointer is invalid. If it tries to get the struct of a `pNext`, it will crash. So I check `samplerConversion`, instead of `pNext`.
[issue #905 ](https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/905)

layers: Avoid crash when pNext is invalid in update combined image of descriptor set

---

scripts/helper_file_generator.py
scripts/layer_chassis_dispatch_generator.py
scripts/layer_chassis_generator.py
scripts/object_tracker_generator.py
scripts/parameter_validation_generator.py
scripts/thread_safety_generator.py

The 'is' operator is not meant to be used for comparisons. It currently working is an implementation detail of CPython.
CPython 3.8 has added a SyntaxWarning for this.

Fix use of 'is' operator for comparison

---

layers/buffer_validation.cpp
layers/vk_format_utils.h

The plane index was being confused with the aspect mask which meant that
the check was failing incorrectly.

layers: Fix plane compatibility validation

---

layers/core_validation.cpp

For GPU-AV purposes, ignore GetPhysicalDeviceProperties calls if maxBoundDescriptorSets == 0

gpu: Ignore if maxBoundDescriptorSets == 0

---

layers/vk_format_utils.cpp
tests/vklayertests.cpp

Addresses #850 - callers check for >= VK_MULTIPLANE_FORMAT_MAX_PLANES and will treat as an error

layers: Return error if >1 plane in mask

---

BUILD.gn
build-gn/secondary/build_overrides/vulkan_validation_layers.gni

The chromium build has multiple dependencies that reference the glslang
and spirv-tools dir. Adding "vvl_" prefix to these dirs here to avoid
name collisions.

build:Modify spirv/glslang dir variable names

---

layers/shader_validation.cpp

Do not require shaderStorageImageExtendedFormats Vulkan
feature when declaring the StorageImageExtendedFormats
OpCapability in SPIR-V shader. Validation now only requires
that the VK_FORMAT_FEATURE_STORAGE_IMAGE_BIT is found in
image view's format features when usage contains
VK_IMAGE_USAGE_STORAGE_BIT in image view creation.
Fixes #925

layers: Fix incorrect feature requirement

---

layers/core_validation.h
layers/shader_validation.cpp
tests/vklayertests.cpp

Fixes #820.
Check for outermost array that shouldn't be counted for certain shader stages, for non-patch attributes. Implement maxGeometryTotalOutputComponents device limit check, and some related verticesout/invocations limits.
Update the tests to each run two iterations, one that is just under the limit and one that is just over the limit. Add a variant that tests OutputVertices/Invocations.

Improve component counting in ValidateShaderStageInputOutputLimits

---

scripts/layer_chassis_dispatch_generator.py
scripts/layer_chassis_generator.py

Was confusingly sharing name with corechecks.

Rename chassis dispatcher descriptor set template map

---

tests/CMakeLists.txt

The gtest project exports its include directories as
"INTERFACE SYSTEM" which means when including the gtest target
in another target, it is unnecessary to explictly list the
gtest include directories in the target's include directory
search path.  The target in this case is the validation layer tests (VLT).
Further, it is somewhat misleading to add the gtest include dir in the
search path on Linux-like systems because gtest exports the include
dir as "SYSTEM" which means it is moved from the location specified in the
CMake code to the end of the search path, along with other system includes.
So placing it in the include path in the CMake code gives the misleading
impression of its position in the final include search path.
Motivated by …

build: Remove unneeded gtest include dir from VLT

---

tests/layer_validation_tests.cpp
tests/layer_validation_tests.h
tests/vkrenderframework.cpp
tests/vkrenderframework.h
tests/vktestframework.h

https://github.com/google/googletest/blob/master/googletest/docs/faq.md#should-i-use-the-constructordestructor-of-the-test-fixture-or-setupteardown
This cleans up bit of confusion of Constructor vs SetUp(). Only one of those should be used for clarity. This PR chooses Constructor per above.
Not sure what the deal with the middleman classes are. Their division of labour seem blurry. So I at least made the `VkRenderFramework` and `VkTestFramework` abstract, to make sure they are not used outside `VkLayerTest`.

tests: Remove SetUp()\TearDown() functions

---

layers/core_validation.cpp
layers/descriptor_sets.cpp
layers/descriptor_sets.h

In order to make state tracking reusable in various ValidationObject subclasses, the objects that track state must be distinct from the CoreChecks validation functionality.
This is the first piece of that refactor.  Note that for functions that I moved to the end of file, the move is a separate change.  Later refactors I left in situ, but will move as a separate PR to improve reviewability.

Refactor first tranche of validation functions out of DescriptorSet* classes.

---

scripts/layer_chassis_generator.py

This fixes a bug where the layer chassis did not call down properly in `vkEnumerateDeviceExtensionProperties` if `pLayerName` was null. This prevented other layers from ever seeing the call.
This bug wasn't causing problems in the past (though it was technically still bugged), but it will start causing problems once KhronosGroup/Vulkan-Loader#194 is merged.

chassis: Fix calldown logic in device extensions

---

scripts/layer_chassis_generator.py
tests/vkpositivelayertests.cpp

Disabling the CoreChecks validation object in the Khronos layer caused crashes due to uninitialized CreatePipelines data.  Initialized data and added positive test.  
Fixes #964.

Allow disabling of CoreChecks in Khronos layer

---

scripts/vk_validation_stats.py

`vk_validation_stats.py` could not handle the case when a validation
helper function's first parameter is a VUID string.

scripts: Modify val stats script for helper fxns

---

layers/core_validation.cpp
layers/core_validation.h

In order to allow reuse of the CoreCheck handle-to-data maps, separate out state into it's own object.
Convert all the extant *_STATE accessors using unique_ptr to a common declaration and accessor framework.  Add support for const accessors, leaving existing accessors in place for backward compatibility.

Refactor handle maps into separate object/Begin standardizing state declarations/get

---

layers/core_validation.cpp
layers/descriptor_sets.cpp
layers/descriptor_sets.h

Make ValidateDrawState a stand-alone function.  Part of refactor spliting state tracking from validation functionality.
A much smaller change from the last Descriptor Set PR... one function plus a little cleanup.

Remove ValidateDrawstate from DescriptorSet

---

layers/core_validation.cpp
layers/core_validation.h
tests/vklayertests_others.cpp

Fixes #255.  This warning was invalid, confusing, and as part of the move to separate warnings from valid usage, being removed from CoreChecks.

Remove unsubmitted fence warning

---

layers/buffer_validation.cpp
tests/vklayertests_buffer_image_memory_sampler.cpp

Added check for `VUID-VkImageCreateInfo-imageType-00954`, width==height and arrayLayers >= 6, along with tests.
Fixes #410.

Add VU checks for CUBE_COMPATIBLE image sizes

---

.appveyor.yml
.travis.yml

Add the ability to specify a specific version of CMake to be used
for CI builds.  Currently, use CMake 3.10.2 for all CI builds.
Also, removed Karl from the Travis distribution list, at his request.

cmake: Always use a known CMake version for CI

---

layers/core_validation.cpp
layers/core_validation.h
tests/vkpositivelayertests.cpp

despite the strict VU wording, the counts can be infered:
> Implementations **must** support at least one queue family.
> Each queue family **must** support at least one queue.

layers: Allow using 0th Queue Family and 1 queue

---

layers/descriptor_sets.cpp

The term "updated" on its own implies a previous write/copy action so
clarifying to indicate that descriptor has NEVER been updated by a call
to vkUpdateDescriptorSets() or similar calls.
For brevity and forward compatibility I went with "similar calls"
rather than listing every variant of descriptor update function.

layers:Clarify descriptor update error message

---

scripts/layer_chassis_generator.py

The layer chassis currently doesn't report device extensions that are defined in the layer properly. This change reports those extensions in the same way that instance extensions are supported.
Without this fix, two tests (`VkLayerTest.DebugMarkerNameTest` and `VkLayerTest.ValidationCacheTestBadMerge`) will fail when updating to the latest loader.

Make layer chassis properly report device extensions

---

layers/buffer_validation.cpp
layers/core_validation.cpp
layers/descriptor_sets.cpp
layers/object_tracker_utils.cpp
layers/shader_validation.cpp
layers/vk_layer_logging.h
scripts/helper_file_generator.py
tests/vklayertests_buffer_image_memory_sampler.cpp
tests/vklayertests_command.cpp
tests/vklayertests_descriptor_renderpass_framebuffer.cpp
tests/vklayertests_others.cpp
tests/vklayertests_pipeline_shader.cpp

[issue #983](https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/983)
Changed FormatHandle from `0x%l016llx [definedName]` into `handleTypeName 0x%l016llx [definedName]`.
And modified log_msg if it has duplicate handle type name and expected error in test if it uses old handle type name.

Add handle type name in FormatHandle

---

layers/core_validation.cpp
layers/core_validation.h
layers/descriptor_sets.cpp
layers/descriptor_sets.h

Complete the migration of validation functions out of DescriptorSet.*.
Refactor standalone functions to CoreChecks methods, remove CoreChecks
dependency from Descriptor set classes.  Eliminate redundant warning.

Finish Migration of DescriptorSet* validation to CoreChecks

---

layers/core_validation_error_enums.h
layers/descriptor_sets.cpp
tests/vklayertests_descriptor_renderpass_framebuffer.cpp

A couple of the error messages were printing decimal numbers disguised as hex ones, and an object-lifetime VUID was being used for a bunch of generic ImageView errors.  
Fixes #622.

Update some iffy descriptor_sets.cpp VUIDs, messages

---

layers/buffer_validation.cpp
layers/core_validation.cpp
layers/core_validation.h
layers/core_validation_types.h
tests/layer_validation_tests.cpp
tests/layer_validation_tests.h
tests/vklayertests_buffer_image_memory_sampler.cpp
tests/vklayertests_command.cpp
tests/vklayertests_descriptor_renderpass_framebuffer.cpp
tests/vklayertests_others.cpp
tests/vkpositivelayertests.cpp
tests/vkrenderframework.cpp
tests/vkrenderframework.h

[issue #749 ](https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/749)
`Image_state` records if the image is created from a swapchain and bind with a swapchain.
And add checking swapchain when it validates if image binds memory.

Fix vkBindImageMemory doesn't check swapchain

---

layers/buffer_validation.cpp
tests/vklayertests_buffer_image_memory_sampler.cpp
tests/vkpositivelayertests.cpp
tests/vkrenderframework.cpp
tests/vkrenderframework.h

Fixed [issue #750 ](https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/750)
The first five commits are from [PR #994 ](https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/994). After it merges, I will remove those commits in this PR.
The last three commits are new. Fixed when it checks if image's layout is correct, it doesn't check swapchain's image's layout.

Fix it doesn't check swapchain's image layout

---

tests/vkpositivelayertests.cpp

CoreChecks saves imageLayout in map. (`CoreChecks::SetLayout)` 
But the index of data in map doesn't follow when it adds, so when it runs the whole ImageLayoutMap in `CoreChecks::ValidateCmdBufImageLayouts`. The data order might be different with the command order.
For example: in `VkPositiveLayerTest.TransferImageToSwapchainDeviceGroup`, it adds command `vkCmdPipelineBarrier`, and then add `vkCmdCopyImage`. 
But sometimes, in `CoreChecks::ValidateCmdBufImageLayouts`, it runs `vkCmdCopyImage` first, and then runs `vkCmdPipelineBarrier`.
In this case, I run only one command in one queue in this test.

ImageLayoutMap might have order issue in CoreChecks::ValidateCmdBufImageLayouts.

---

layers/core_validation.cpp

Validation snapshotted surfaceCaps at the time the app queried them, but this led to bad validation messages when resizing display surfaces.  Validation now queries latest caps at CreateSwapchain-time to narrow the race condition defined by the API.  See the issue for more details.
Also changed the two remaining UNCALLED checks from ERROR to WARNING.
Fixes #624.

Use fresh surface capabilities when validating swapchain creation

---

layers/core_validation.cpp
tests/vklayertests_pipeline_shader.cpp

The layers were making an incorrect/illegal downchain call when the instance api version was less than the device api version.  An updated driver on one platform exposed this by causing a crash inside the loader.
To tests were also shown not to be robust to valid platform differences.  In one case, further work is needed inside the layers relocate validation eariler s.t. our testing doesn't drive invalid content that can't be caught before the driver could take exception to it. (Will open an issue to track.)

Fix one layer and two test issues found in testing vs. updated drivers

---

layers/parameter_validation_utils.cpp
layers/stateless_validation.h
scripts/parameter_validation_generator.py
tests/layer_validation_tests.cpp
tests/vklayertests_command.cpp
tests/vklayertests_pipeline_shader.cpp
tests/vkpositivelayertests.cpp

The layerCount member of each pRects member must be greater than zero. This broke half-a-dozen tests.  Also added a new test  specifically for this VU.
Fixes #627.

Add CmdClearAttachments Check for VUID 01394

---

tests/vklayertests_buffer_image_memory_sampler.cpp
tests/vkpositivelayertests.cpp

Android doesn't support bindimagememory2 with swapchain
Change-Id: I0fe192665b14cb8fbab00bf0e6a8d88f5378302e

tests: Skip Android test

---

layers/core_validation_types.h

When image layout state data was propagated to secondary command buffers, the initial layout state map was not updated, resulting in stale data which led to segmentation faults.
Fixes #1011.

Update secondary command buffer's initial layout map

---

build-android/known_good.json

These were ancient, and updates were needed for new extensions -- this has been blocking PR #921.
Hopefully, @cnorthrop or @tobine can run it through the Google test farm.

Update spirvtools/headers known good for Android

---

layers/vk_layer_logging.h
layers/vk_layer_utils.cpp

DebugReport has this ability, added it to DebugUtils. 
Fixes #897.

Support breakpoint debug actions for DebugUtils extension

---

layers/buffer_validation.cpp
layers/core_validation.cpp
layers/core_validation.h
layers/core_validation_types.h
layers/descriptor_sets.cpp
layers/descriptor_sets.h
layers/shader_validation.cpp

Refactors ValidationStateTracker to be base class of CoreChecks
Implements split of Device, Image, Buffer, *View, and DescriptorSet related functions as both example and first tranche of implementation.

Initial refactor of record logic to ValidationStateTrack (aka VST)

---

tests/vklayertests_pipeline_shader.cpp

Test was checking for required feature enable without first seeing if
extension that supports feature was supported.
Add extension supported check and else skip logic to test.  This is a workaround to avoid a driver specific CreateShaderModule failure because an unsupported feature is required by the passed shader source.  The driver fails the CSM call, and the test framework asserts success. 
This is another example of #1022 where a driver is detecting and failing a create based on unsupported extensions/features/capabilities, but validation isn't checking at CreateShaderModule time.
@mikes-lunarg  -- Also it feels likes there's a missing class of VU's. There are features or capabilities that require extensions, but I don't see VU that states that an feature that is added as part of an …

Check extension support before feature test

---

scripts/parameter_validation_generator.py

Doing so will help to guard the manual checks from nullptr accesses, as the code-generated implicit VU checks do this automatically.
Fixes #1039.

Move stateless validation manual checks AFTER implicit VU checks

---

scripts/object_tracker_generator.py

About 45 of the implicit VU checks for optional parameter arrays require that in addition to the count being non-zero, that the array pointer must also be non-null. Added the appropriate null checks to object lifetimes codegen.
Fixes #1042.
Codegen was:
```
bool ObjectLifetimes::PreCallValidateCmdBindTransformFeedbackBuffersEXT(...) {
bool skip = false;
skip |= ValidateObject(...);
for (uint32_t index0 = 0; index0 < bindingCount; ++index0) {
skip |= ValidateObject(commandBuffer, pBuffers[index0], kVulkanObjectTypeBuffer, ...);
}
return skip;
}
```
Codegen now: 
```
bool ObjectLifetimes::PreCallValidateCmdBindTransformFeedbackBuffersEXT(...) {
bool skip = false;
skip |= ValidateObject(...);
if (pBuffers) {
for (uint32_t index0 = 0; index0 < bindingCount; ++index0) {
skip |= …
```

Add object-lifetimes null-array protection for counted arrays

---

tests/CMakeLists.txt

Causes validation layers to get rebuilt if layer source is modified but only the layer validation tests target is built. 
Makes sense to me that LVTs go hand-in-hand with a new validation layer -- AFAICT we don't build standalone LVTs in any peer repository.
Fixes #1045.

Make khronos validation layer a dependency for the layer validation tests

---

layers/buffer_validation.cpp
layers/core_validation.cpp
layers/core_validation.h
layers/core_validation_types.h
layers/shader_validation.cpp
layers/shader_validation.h

In this change we split CoreChecks validation and ValidationStateTracker state tracking for:
- Pipeline create/destroy
- Light refactor of shader module state
- Fix of RayTracing pipeline @jeffbolznv (Specifically "layers: Add stageCount to raytrace pipe validation")
- Constness cleanup to make sure nothing sneaky is happening in CoreChecks validation code
- First group of Clear/copy/blit commands
- includes const cleanup of Corechecks Validate call tree

Second batch of VST refactors.

---

docs/gpu_validation.md
tests/vklayertests_descriptor_renderpass_framebuffer.cpp

The new tests are failing on Shield TV, but passing everywhere else.  @cnorthrop could you put this through your farm and maybe we could discern a trend based on what passes and doesn't?

Add gpu assisted validation tests for buffer descriptors

---

layers/buffer_validation.cpp
layers/core_validation.cpp
layers/core_validation.h

Trying to keep the batches bite-sized.  The following entrypoints are now split and should be const clean in the Validate call trees.
```
AllocateMemory
CmdCopyBuffer
CmdCopyBufferToImage
CmdCopyImageToBuffer
CmdFillBuffer
CmdSetBlendConstants
CmdSetDepthBias
CmdSetDepthBounds
CmdSetExclusiveScissorNV
CmdSetLineWidth
CmdSetScissor
CmdSetStencilCompareMask
CmdSetStencilReference
CmdSetStencilWriteMask
CmdSetViewport
CmdSetViewportShadingRatePaletteNV
CmdUpdateBuffer
EnumeratePhysicalDeviceGroups
EnumeratePhysicalDeviceGroupsKHR
FreeMemory
```

Third Tranche (t2) of ValidationStateTracker (VST) state/validation refactor.

---

tests/layer_validation_tests.cpp

In Android native tests, it cannot create surface, so check VALIDATION_APK to skip the related tests.

Check VALIDATION_APK when add surface extension

---

layers/core_validation.cpp
layers/core_validation.h
layers/core_validation_types.h

Refactor with const clean and state/validation split:
CmdBindPipeline
CreatePipelineLayout
DestroyPipelineLayout
CmdBindDescriptorSets
BeginCommandBuffer
EndCommandBuffer
ResetCommandBuffer
ResetCommandPool
FreeCommandBuffers

Fourth tranche (t3) of ValidationStateTracker state/validation refactor

---

layers/core_validation.cpp
layers/core_validation.h
layers/core_validation_types.h
layers/drawdispatch.cpp
tests/vklayertests_buffer_image_memory_sampler.cpp

These had been special-cased since the early days of the DrawState layer for no good reason. Normalized the tracking for in-flight command buffers and fixed up some names.
Fixes #29.

Remove special cases for in-use tracking of vertex/index buffers

---

build-android/known_good.json
docs/gpu_validation.md
layers/core_validation.cpp
layers/core_validation.h
layers/core_validation_types.h
layers/drawdispatch.cpp
layers/generated/chassis.cpp
layers/generated/chassis.h
layers/generated/spirv_tools_commit_id.h
layers/gpu_validation.cpp
layers/gpu_validation.h
scripts/known_good.json
scripts/layer_chassis_generator.py
tests/vklayertests_descriptor_renderpass_framebuffer.cpp
tests/vkrenderframework.cpp
tests/vkrenderframework.h
tests/vktestbinding.cpp
tests/vktestbinding.h

Updates gpu validation to support descriptor indexing shader checks for
ray tracing ray generation, intersection, any hit, closest hit, miss, and callable shaders.
Note this PR depends on https://github.com/KhronosGroup/SPIRV-Tools/pull/2733 - just want to start review process to get feedback.

Add ray tracing shader descriptor indexing validation

---

BUILD.gn

Windows GN build for ANGLE is strict about every include file being
explicitly called out for each layer. Adding additional source files
to meet this requirement.

build:Add explicit includes to BUILD.gn

---

BUILD.gn

The individual layers include shader_validation in their dependency
chain which includes <SPIRV/spirv.hpp>. Adding appropriate glslang dep
to fix strict build.
This is a follow-on to #1068.

build:Add missing dependency to BUILD.gn

---

layers/buffer_validation.cpp
layers/buffer_validation.h
layers/core_validation.cpp
layers/core_validation.h
layers/core_validation_types.h
layers/descriptor_sets.cpp
layers/descriptor_sets.h
layers/drawdispatch.cpp

The next group of ValidationStateTracker refactors and const cleanups of `CoreChecks::.*Validate.*` paths for draw/dispatch/queue submit

VST refactor next batch (t4) Draw/Dispatch/QueueSubmit

---

layers/buffer_validation.cpp
layers/core_validation.cpp
layers/core_validation.h
layers/core_validation_error_enums.h

Memory bind and some simple refactors.  @jmacnak-nv  -- I did some refactors of your code that CI fine here, but would appreciate your double check that I haven't broken anything.
Of note in the bind code is that we don't *reactively* get requirements if they are missing at validation time (as it would make validation operations non-const), but *proactively* at create time, which we used if none are queried.
Also, the last change collects miscellaneous VST refactors with minimal complexity

VST Refactor 6th (t5) batch

---

layers/generated/spirv_tools_commit_id.h
scripts/external_revision_generator.py
scripts/generate_source.py
scripts/vk_validation_stats.py

- Make spirv_tools_commit_id.h depend only on glslang revision from known_good.json instead of hash of entire file
- Make vk_validation_stats.py quiet instead of squashing stdout for all code generators
- Merge generate_source.py tweaks from Vulkan-Tools code review back to VVL

Misc codegen cleanup

---

layers/buffer_validation.cpp
layers/parameter_validation_utils.cpp
layers/stateless_validation.h

Fixed [issue #979 ](https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/979)
@tobine 
I pulled a similar request, [PR #1088 ](https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/1088). But this PR removes test code, only leaves the warning message. 
I cannot force the driver returns `VK_SUBOPTIMAL_KHR`, so please test it in your system to ensure if it is good. Thank you.

layers: Warning VK_SUBOPTIMAL_KHR

---

layers/generated/chassis.cpp
scripts/layer_chassis_generator.py

When creating an instance or device with an extension that is not supported by the validation layers, the layers emit an error indicating that using the extension "may adversely affect validation results and/or produce undefined behavior". In VK-GL-CTS there are a few tests that make that error appear when enabling the validation layers. Sometimes, without any further problems, but the validation error makes these tests fail because validation errors are considered a test failure cause.
The error text itself sounds like a warning. After all, enabling an unsupported extension *may* adversely affect validation results but it may not, depending on what the application is doing, and enabling the extension is not a problem by itself. Taking into account all of this, I believe this error should …

Turn unsupported extensions error into warning

---

layers/buffer_validation.cpp
layers/core_validation.cpp
layers/core_validation.h

VST split and const clean
CreateAccelerationStructureNV
DestroyAccelerationStructureNV
DestroySurfaceKHR
CreateSharedSwapchainsKHR
CreateSwapchainKHR
DestroySwapchainKHR
CreateRenderPass
CreateRenderPass2KHR
DestroyRenderPass
GetMemoryAndroidHardwareBufferANDROID
CreateAndroidSurfaceKHR
CreateIOSSurfaceMVK
CreateMacOSSurfaceMVK
CreateWaylandSurfaceKHR
CreateXcbSurfaceKHR
CreateXlibSurfaceKHR
CreateEvent
DestroyEvent
CreateFence
DestroyFence
CreateQueryPool
DestroyQueryPool
CreateSamplerYcbcrConversion
DestroySamplerYcbcrConversion
CreateSamplerYcbcrConversionKHR
DestroySamplerYcbcrConversionKHR
CreateSemaphore
DestroySemaphore
GetPhysicalDeviceDisplayPlanePropertiesKHR
GetPhysicalDeviceDisplayPlaneProperties2KHR
GetPhysicalDeviceQueueFamilyProperties …

VST refactor seventh tranche (t6)

---

build-android/test_APK.sh

We want to be able to archive the artifact files from an
Android run for later review on an arbitrary system.
But the filenames generated included ":" characters, which
are not legal in Windows systems.
This changes the generated filenames so they are legal for
all in-use OSes.

Android: rename artifact files

---

layers/core_validation.cpp

Without this, I was seeing cases during device destroy where freeing descriptor
sets would crash trying to access command buffers that had already been freed.
There's an app bug here where the app isn't freeing all its objects before destroying
the device, but still nicer not to crash.

layers: Reset command buffers in PreCallRecordDestroyDevice

---

layers/descriptor_sets.cpp

This reduces core validation time by around 25% when both disables are on, in the test app I'm using.

layers: Skip descriptor set UpdateDrawState if image layout and command buffer state validation are disabled

---

layers/parameter_validation_utils.cpp
layers/stateless_validation.h

Issue called out a missing implicit flags check in CGPL's parameter validation.  Turns out, stateless validation source for `CreateGraphicsPipelines` is manually generated, and was missing about 15 implict validation checks tagged `noautovalidity` in the XML.  Hacked the codegen to produce these checks and copied them into the manual routine, along with the extra conditionals that caused them to be tagged `noautovalidity` in the first place.
Fixes #1100.

Add CreateGraphicsPipelines Implict VU Checks

---

layers/stateless_validation.h

Allow raytracing stages, `VK_PIPELINE_STAGE_FRAGMENT_DENSITY_PROCESS_BIT_EXT` and `VK_PIPELINE_STAGE_COMMAND_PROCESS_BIT_NVX` in render pass.

layers: Allow more stages in render pass

---

layers/descriptor_sets.cpp
tests/vkpositivelayertests.cpp

[issue #385 ](https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/385)
The issue happens that is because of shader code: binding #0 includes image and sampler.
```
OpDecorate %InputData DescriptorSet 0
OpDecorate %InputData Binding 0
OpDecorate %SamplerData DescriptorSet 0
OpDecorate %SamplerData Binding 0
```
But this shader only uses sampler, not image, so in shader validation, it doesn't have image information.
`%call_smp = OpLoad %Sampler %SamplerData`
It causes shader validation's image format is 0 and mismatches descriptor's image format.
@gnl21

Check sampler type when shader code uses sampler and descriptor type is COMBINED_IMAGE_SAMPLER. 

---

layers/buffer_validation.cpp
layers/core_validation.cpp
layers/core_validation.h

Eight batch of the split between CoreChecks (Core Validation) and ValidationStateTracker covering:
CmdBeginDebugUtilsLabelEXT
CmdBeginQuery
CmdBeginQuery
CmdBeginQueryIndexedEXT
CmdBeginQueryIndexedEXT
CmdBeginRenderPass
CmdBeginRenderPass2KHR
CmdBindIndexBuffer
CmdBindShadingRateImageNV
CmdBindVertexBuffers
CmdBuildAccelerationStructureNV
CmdCopyAccelerationStructureNV
CmdCopyQueryPoolResults
CmdCopyQueryPoolResults
CmdEndDebugUtilsLabelEXT
CmdEndQuery
CmdEndQueryIndexedEXT
CmdEndRenderPass
CmdEndRenderPass2KHR
CmdInsertDebugUtilsLabelEXT
CmdNextSubpass
CmdNextSubpass2KHR
CmdResetQueryPool
ResetQueryPoolEXT

Validation State Tracker (VST) refactor 8th tranche (t7)

---

layers/generated/vk_safe_struct.cpp
layers/generated/vk_safe_struct.h
scripts/helper_file_generator.py

Safe structs weren't so safe.  Strings were not previously copied which could cause crashes if the application reclaimed those resources.  Extended deep copying coverage to all strings in Vulkan structs.
Also default-initialized all pointers.

Deep copy strings in safe_structs

---

layers/generated/parameter_validation.cpp
layers/parameter_validation_utils.cpp
layers/stateless_validation.h
scripts/parameter_validation_generator.py
tests/vklayertests_buffer_image_memory_sampler.cpp

- use proper VUID
- eliminate dependency on std::bitset
- do not use raw bool parameters
- make single bit, and unknown bit checks independent
- merge single bit and Flags generation script

layers: Rewrite flag validation 

---

layers/generated/parameter_validation.cpp
scripts/parameter_validation_generator.py
tests/vklayertests_command.cpp
tests/vklayertests_others.cpp

fix #1104 
Alternatively manual checks would have to be made robust against the scripted errors, or the test framework be made somehow to tolerate crashes.

Skip manual checks if scripted validation fails 

---

CONTRIBUTING.md
scripts/check_commit_message_format.sh

Any limit I could find on GitHub is 72. 64 for blame page.
The 50 limit arguments always seem to link back to some obsolete article on some personal blog, which actually says:
> shoot **for about** 50 characters (though this **isn’t a hard maximum**)
Not that it matters that much, as we are all obviously ignoring the rule anyway:
Ye without sin, throw the first stone!

ci: Relax summary limit to 64 from 54

---

layers/shader_validation.cpp

Vulkan header version 1.1.116 changd the declaration of
VkPhysicalDeviceFloatControlsPropertiesKHR to use enums instead of
booleans for denorm and rounding mode independence.  The validation
layers were subsequently updated to throw correct errors.  However the
changes were not as granular as they could be.  This commit makes things
a bit finer-grained.

Improve shader validation of denorm and rounding mode independence

---

layers/core_validation.cpp
layers/core_validation.h
tests/vkpositivelayertests.cpp

[issue #948 ](https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/948)
vkspec: `If two subpasses use the same attachment in different layouts, and both layouts are read-only, no subpass dependency needs to be specified between those subpasses.`
But even in same layouts, they should be treated in the same way, thus `if two subpasses are the same attachment, and their layouts are read-only, they don't need dependency, whatever they are in the same or different layouts.`
@liufachen

If layouts are read-only in subpasses, it doesn't need dependencies.

---

layers/best_practices.cpp
layers/best_practices.h

Most code is migrated from VulkanTools Assistant Layer.
A few minor changes were made:
- reword some of the Warning Messages
- Use log_msg instead of Warning() wrapper function
There are a few comments marked as TODO. Will be updated in upcoming Best Practices PR

Best Practices Validation Object Step 2

---

.appveyor.yml

Related to #1134. This does not however switch the build type, so Release builds have no symbol information yet, but it shows that AppVeyor will do this for open source accounts.
Tested in a fork using my personal AppVeyor account. Sample link showing artifacts for download: https://ci.appveyor.com/project/NunoSubtil/vulkan-validationlayers/builds/26758820/job/gv1udp0dyhk30i45/artifacts

appveyor: Capture layer binaries as artifacts

---

tests/vklayertests_descriptor_renderpass_framebuffer.cpp

Addresses usage concerns reported in https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/1162.
Tested on laptop with GTX1060 and Nvidia's 436.02 game ready driver.

Fix shader group types for RT OOB test

---

layers/generated/vk_safe_struct.cpp
scripts/helper_file_generator.py

otherwise they are not set to `nullptr` in default constructor, but still destroyed in destructor.

layers: Initialize safe_struct pointers

---

layers/core_validation.cpp
layers/generated/object_tracker.cpp
layers/object_lifetime_validation.h
layers/object_tracker_utils.cpp
layers/vk_layer_utils.h
scripts/object_tracker_generator.py
tests/vklayertests_others.cpp

Use vl_concurrent_unordered_map for the object_maps, and remove most use of
the single object_lifetime_mutex. object_lifetime_mutex is still used in a few
cases like to protect access through ObjTrackState::child_objects.
Use shared_ptr for the pointers to ObjTrackState in case of application bugs
like destroying the same object twice, which could otherwise crash when accessing
and freeing that pointer.
I'm seeing around a 15-20% full frame speedup with only the object lifetimes layer enabled in my test app. That's probably a reduction of about half of the time spend in the layers themselves, but it's hard to measure this exactly. Qualitatively, the lock contention is significantly reduced.

Use vl_concurrent_unordered_map in ObjectLifetimes

---

layers/core_validation.cpp
layers/core_validation_types.h
layers/generated/layer_chassis_dispatch.cpp
layers/gpu_validation.cpp
layers/object_lifetime_validation.h
layers/vk_layer_utils.h
layers/vk_mem_alloc.h
scripts/layer_chassis_dispatch_generator.py

ANGLE uses an older Windows SDK than what you get by default with newer VS versions. This leads to some picky build errors. Putting these out there for consideration. The first 2 CLs seem pretty harmless. Probably a better way to do the last one (std::min vs Win min), so open for suggestions. Tried explicitly including <algorithm> and still getting ambiguous function error and this fixes it, at least.

Tobin angle build fixes

---

layers/buffer_validation.cpp
layers/core_validation.cpp
layers/core_validation.h
layers/core_validation_types.h
tests/vklayertests_command.cpp

Validation and State tracking segregation and validation const cleaness implementations for:
EnumeratePhysicalDevices
GetAccelerationStructureMemoryRequirementsNV
GetBufferMemoryRequirements
GetBufferMemoryRequirements2
GetBufferMemoryRequirements2KHR
GetDeviceQueue
GetDeviceQueue2
GetImageMemoryRequirements
GetImageMemoryRequirements2
GetImageMemoryRequirements2KHR
GetImageSparseMemoryRequirements
GetImageSparseMemoryRequirements2
GetImageSparseMemoryRequirements2KHR
Segregate state tracking and validation, including const clean up of
validation, which in turn required a disentangle of three commingled
VUID tests.
CmdExecuteCommands

Validation / State tracking refactor, batch 9 (t8)

---

docs/gpu_validation.md
layers/gpu_validation.cpp
tests/vkpositivelayertests.cpp

The shader instrumentation is not designed to know if part of a block is accessed or not, so when applied to an inline uniform block, it can return false positives, as it would running the included test.
Warn when appropriate and never generate an error for VK_DESCRIPTOR_TYPE_INLINE_UNIFORM_BLOCK_EXT descriptors

Don't report GPU-AV errors from inline uniform blocks

---

layers/vk_layer_utils.h

Only add lock struct padding if lock is less than 64-bytes.
On Windows x64 std::mutex may be 80 bytes so each lock takes more
than a single 64-byte cache line and no padding needed.

layers:Fix struct padding

---

layers/core_validation.cpp
layers/core_validation.h
layers/descriptor_sets.cpp
layers/generated/chassis.cpp
layers/generated/chassis.h
scripts/layer_chassis_generator.py

There were issues when using the Validation State Tracker for multiple Validation objects (Core and Best Practices). This resolves some, but not necessarily all of those issues. There will be a future PR for the rest of the problems.

layers: Fixes when using ValidationStateTracker for Best Practices

---

layers/core_validation.cpp
layers/core_validation.h
layers/gpu_validation.cpp

The shader instrumentation uses fragmentStoresAndAtomics and vertexPipelineStoresAndAtomics so don't instrument shaders if those features are missing

gpu: Stop validation if features missing

---

layers/buffer_validation.cpp
layers/core_validation.cpp
layers/core_validation.h
layers/core_validation_types.h
layers/descriptor_sets.cpp

State/Validation test split for: 
GetFenceFdKHR
GetFenceStatus
GetFenceWin32HandleKHR
DeviceWaitIdle
QueueWaitIdle
WaitForFences
CmdSetDeviceMask
CmdSetDeviceMaskKHR
CmdWriteTimestamp
CmdPushConstants
CmdPushDescriptorSetKHR
CmdPushDescriptorSetWithTemplateKHR
SetEvent
CmdResetEvent
CmdSetEvent
CmdWaitEvents

VST refactor 10 batch (t9) valstate split

---

.clang-format
CONTRIBUTING.md
layers/best_practices.h
layers/core_validation.cpp
layers/core_validation.h
layers/core_validation_types.h
layers/descriptor_sets.h
layers/generated/.clang-format
layers/gpu_validation.h
layers/hash_util.h
layers/object_lifetime_validation.h
layers/parameter_name.h
layers/shader_validation.h
layers/sparse_containers.h
layers/stateless_validation.h
layers/vk_layer_config.cpp
layers/vk_layer_data.h
layers/vk_layer_utils.cpp
layers/vk_layer_utils.h
tests/layer_validation_tests.h
tests/test_environment.h
tests/vkrenderframework.h
tests/vktestbinding.h
tests/vktestframework.h
tests/vktestframeworkandroid.h

- make access modifiers indented by 2 spaces
(originally 1 space, so preserves being a half indent; accidentally 3 spaces in this repo)
- document we use `*.cpp` instead of Google's `*.cc`

repo: Update code style

---

layers/generated/object_tracker.cpp
layers/object_lifetime_validation.h
layers/object_tracker_utils.cpp
scripts/common_codegen.py
scripts/object_tracker_generator.py

No distinction existed between objects having instance or device parent types, necessary for properly reporting the correct VUID. These are now checked and reported separately, at the appropriate time.
Fixes #658.

Fix-up Instance/Device 'undestroyed object' Reporting in ObjectTracker

---

layers/core_validation.cpp
layers/core_validation.h
layers/core_validation_types.h

Final tranche of the initial ValidationStateTracker refactor.  Follow on PR's will segregate VST and CoreCheck content.
QueueBindSparse
QueuePresentKHR
RecordResetFences
GetSemaphoreFdKHR
GetSemaphoreWin32HandleKHR
ImportFenceFdKHR
ImportFenceWin32HandleKHR
ImportSemaphoreFdKHR
ImportSemaphoreWin32HandleKHR
MapMemory
UnmapMemory
FlushMappedMemoryRanges
InvalidateMappedMemoryRanges

Final tranche VST refactor -- Validation and state tracking split

---

layers/core_validation.cpp
layers/core_validation.h

Now that the structure count warnings are in BestPractices, they can be removed from Core

layers: Remove Count Warnings from Core

---

layers/core_validation.cpp
layers/core_validation.h

Fix out of range access regression from VST refactor in EventStageMask
validation.
The update of the events array is now split between the StateTracker and the CoreChecks, this change addresses a regression from that splite

Fix out of range access for EventStageMask

---

layers/buffer_validation.cpp
layers/core_validation.cpp
layers/core_validation.h
layers/core_validation_error_enums.h
layers/core_validation_types.h
tests/vklayertests_others.cpp
tests/vkpositivelayertests.cpp
tests/vkrenderframework.cpp

Fixed [issue #750](https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/750) & [issue #1020](https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/1020)
This PR implements vkspec `If two aliases are both images that were created with identical creation parameters, both were created with the VK_IMAGE_CREATE_ALIAS_BIT flag set, and both are bound identically to memory except for VkBindImageMemoryDeviceGroupInfo::pDeviceIndices and VkBindImageMemoryDeviceGroupInfo::pSplitInstanceBindRegions, then they interpret the contents of the memory in consistent ways, and data written to one alias can be read by the other alias.`
For `data written to one alias can be read by the other alias`, this PR only does setting layout. When one image sets layout, it will set it to the whole …

Implement some VK_IMAGE_CREATE_ALIAS_BIT features

---

layers/generated/thread_safety.h
scripts/thread_safety_generator.py

Conditional compilation defs for include was different than that of implementation, causing compilation failures on some supported versions of Visual Studio.
Fixes #1236.
We also reproduced this on a VS2017 version 15.1 installation.

Fix shared_mutex supportd version compilation errors

---

layers/core_validation.cpp
layers/parameter_validation_utils.cpp
tests/vktestframework.cpp

This fixes the following build error with `gcc-5.3.0` on `Slackware-14.2`.
```
Vulkan-ValidationLayers-sdk-1.1.114.0/layers/parameter_validation_utils.cpp: In lambda function:
Vulkan-ValidationLayers-sdk-1.1.114.0/layers/parameter_validation_utils.cpp:659:13: error: '__builtin_isnan' is not a member of 'std'
if (std::isnan(v1_f)) return false;
^
Vulkan-ValidationLayers-sdk-1.1.114.0/layers/parameter_validation_utils.cpp:659:13: note: suggested alternative:
<built-in>: note:   '__builtin_isnan'
layers/CMakeFiles/VkLayer_stateless_validation.dir/build.make:134: recipe for target 'layers/CMakeFiles/VkLayer_stateless_validation.dir/parameter_validation_utils.cpp.o' failed
make[2]: *** [layers/CMakeFiles/VkLayer_stateless_validation.dir/parameter_validation_utils.cpp.o] Error 1 …
```

Fix build with gcc5.

---

layers/generated/thread_safety.h
scripts/thread_safety_generator.py

MacOS compiler was unable to cast a type of
std::atomic<_opaque_pthread_t *> to uint64_t.

layers: Fix bad cast in thread_safety.h

---

layers/gpu_validation.cpp

Have to handle both no DS bound and bound DS with no bindings
Change-Id: Ie2b34b990583bd6f877fe782b5e2c129c993c0d5

Fix problem with unbound descriptor sets

---

layers/generated/thread_safety.cpp
layers/generated/thread_safety.h
scripts/thread_safety_generator.py

The CreatePipelines APIs **CAN** return valid results even with non-success return codes, but this caused crashes in the threading layer.  
Reproduce with CTS test case 
`dEQP-VK.api.object_management.alloc_callback_fail_multiple.graphics_pipeline`
Fixes #1254.

Make threading respect CreatePipelines partial results

---

tests/vklayertests_pipeline_shader.cpp
tests/vkrenderframework.cpp

Was defaulted to Error, for some reason, allowing false negatives.

Fix ErrorMonitor default flag mask

---

layers/generated/object_tracker.cpp
layers/generated/parameter_validation.cpp
layers/generated/vk_object_types.h
layers/object_lifetime_validation.h
layers/object_tracker_utils.cpp
layers/parameter_validation_utils.cpp
layers/stateless_validation.h
scripts/helper_file_generator.py
scripts/object_tracker_generator.py
scripts/parameter_validation_generator.py
tests/vklayertests_others.cpp

A couple of the DebugUtils APIs specify objects by using a `uint64_t/VkObjectType` pair to describe Vulkan objects. These needed a bit more plumbing to get validated correctly in ObjectTracker.
Also:
- picked up a couple of easy related stateless VUs
- added tests
- Removed a bunch of dipsatchable-object plumbing left over from the layer_data_map days
Fixes #590.

Add validation checks for Debug Utils anonymous objects

---

layers/generated/thread_safety.cpp
scripts/thread_safety_generator.py

Fixes crash in dEQP-VK.api.object_management.multithreaded_per_thread_resources.descriptor_pool

Fix thread_safety map accesses

---

layers/best_practices.cpp

Best Practices validation object failed to call the base class for the CreatePipelines APIs, causing crashes.
This subsumes PR #1263.

bestprac: Fixed pipeline creation state issue

---

layers/best_practices.cpp
layers/state_tracker.cpp
layers/state_tracker.h

- Add state tracking for `vkGetPhysicalDeviceFeatures*()` variants
- Test correct state in `vkCreateDevice()` best-practices check
Fixes #1272

Fix incorrect test in vkCreateDevice() best practices

---

layers/buffer_validation.cpp
layers/core_validation.cpp
layers/core_validation.h
tests/vklayertests_buffer_image_memory_sampler.cpp

This had a few issues, including using the wrong version of GetPhysicalDeviceImageFormatProperties call (need to use the '2' version if DRM is active) and not allowing the new VK_IMAGE_ASPECT flags.
Straightened out these checks, fixed some incorrect VUIDs, and removed some dead code as well.
Note that no tests have been added as we don't have any hardware that uses this extension.  Hoping @djdeath and @szihs can verify the changes for their issues.
Fixes #456.
Fixes #796.

Clean up some issues related to the drm_format_modifier extension

---

layers/generated/layer_chassis_dispatch.cpp
scripts/layer_chassis_dispatch_generator.py
tests/vklayertests_pipeline_shader.cpp

This extension returns data from the driver to the application.  However, when handle-wrapping is enabled, the driver data is located within the copy of the pNext chain and was discarded.  This fix copies the data back into the original pNext chain for the three CreatePipeline variants.
Also moved the raytracingNV variant to a manual dispatcher to handle the partial fulfillment of the create request.
Fixes #1295.

Send driver data back to app when wrapping handles (PipelineCreationFeedback Extension)

---

layers/shader_validation.cpp

Previously properties were only checked if capabilities didn't depend on
extensions, but there were some that required both. Do the checks
unconditionally.

layers: Always check capability properties

---

layers/core_validation_types.h
layers/shader_validation.cpp
layers/state_tracker.cpp
layers/state_tracker.h

These properties were being treated as features, meaning that the
validation layer incorrectly expected them to be enabled.

layers: Fix float_controls properties

---

layers/buffer_validation.cpp
tests/vklayertests_command.cpp

https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/403
vkspec: `“_422” image formats that are not multi-planar are treated as having a 2×1 compressed texel block for the purposes of these rules.`

Check for single-plane _422 formats as compressed

---

layers/core_validation.cpp
layers/state_tracker.cpp

I was using this for an app that generates query-related errors, and
when I had the disable turned on I just got different errors because
some query validation was still enabled.

layers: Add more disabled.query_validation checks

---

layers/buffer_validation.cpp
layers/core_validation.cpp
layers/core_validation.h
layers/core_validation_types.h
layers/descriptor_sets.cpp
layers/descriptor_sets.h
layers/generated/chassis.h
layers/gpu_validation.cpp
layers/gpu_validation.h
layers/shader_validation.cpp
layers/shader_validation.h
layers/state_tracker.cpp
layers/state_tracker.h
scripts/layer_chassis_generator.py
tests/vklayertests_descriptor_renderpass_framebuffer.cpp

Allocate the *_STATE objects as shared_ptrs, so other objects can keep references to them even if the API-level object gets destroyed. Take advantage of this in descriptor set validation to only do the hash table lookup at Update time, not at Draw time when the descriptor set is validated. This can be a significant speedup for large descriptor sets that are used much more frequently than they're updated.
These changes made my test app 10% faster with just image_layout validation disabled, and 
25% faster with image layout and command_buffer_state validation disabled.
Related to #1001.

Use shared_ptrs to reduce hash table lookups in descriptor validation

---

layers/generated/layer_chassis_dispatch.cpp
scripts/layer_chassis_dispatch_generator.py

Pipeline feedback copy only correctly copied first createInfo's data.
Fixes #1305.

Allow for multiple createinfos in dispatcher pipeline feedback copy

---

layers/core_validation.cpp
layers/core_validation_types.h
layers/descriptor_sets.h
layers/state_tracker.cpp

Precompute vertex attribute alignment requirement.
Calculate this at pipeline creation time, rather than per-draw.
Avoids frequent hash table lookups of the VK_FORMAT enums.
Remove unused cb_vertex_buffer_binding_info.
Bonus: Make DescriptorSet::GetLayout return const reference

Precompute vertex attribute alignment requirement

---

layers/core_validation_types.h
layers/vk_layer_data.h

Refactor small_unordered_map to a base class that can be shared
between small_unordered_map and small_unordered_set.
Change BINDABLE::bound_memory_set_ to a small_unordered_set<...,1>
since non-sparse resources only get a single allocation bound.

layers: Add small_unordered_set 

---

layers/core_validation.cpp
layers/core_validation_types.h
layers/state_tracker.cpp
tests/vklayertests_descriptor_renderpass_framebuffer.cpp
tests/vklayertests_pipeline_shader.cpp

Add support for 11 similar VU that require that bound descriptor sets must be bound with a pipeline layout compatible with the pipeline layout of the pipeline object being used for a draw/dispatch/mesh call.
Update/add test to reflect the additional error messages from the new VU check.
Fixes #1286

Add "compat for N" between the Bind pipeline layout and the Shader pipeline pipeline layout

---

layers/core_validation.cpp
layers/core_validation.h
tests/vklayertests_others.cpp

Partial fix for #1179  (the part I can reproduce).
Correct and clean up deferred (submit time) validation messages for `vkCmdWriteTimestamp`. Clarify function names and add informative comment.
Ensure that the setup precondition for the timestamp reset test is expecting success.

cleanup vkCmdWriteTimestamp messages to report correct entrypoint

---

layers/core_validation.cpp
layers/state_tracker.cpp
layers/state_tracker.h

Two changes: 
1 Refactor PostCallRecordGetSwapchainImagesKHR s.t. the common state tracking is in the ValidationStateTracker.
2 Move VST function into state_tracker.cpp  
Fixes #1312 , which broke BestPractices, but all VST derived classes (except CoreChecks) would find the same issue.

Move swapchain image state setup to ValidationStateTracker 

---

BUILD.gn

On the x11 platform define VK_USE_PLATFORM_XLIB_KHR. This is needed
to enable layer code so that surface pointer is correctly recorded.

build:Add VK_USE_PLATFORM_XLIB_KHR for x11

---

layers/core_validation.cpp
layers/core_validation.h
layers/drawdispatch.cpp
tests/vklayertests_descriptor_renderpass_framebuffer.cpp

This "fixes" an internally reported issue. The application fails to bind one of the highest numbered descriptor sets. This crashes in ValidationStateTracker::UpdateDrawState (accessing state.per_set[setIndex]), and wasn't reporting an error before it crashes. After this change it correctly reports the missing descriptor set. It _still_ crashes, but I think it's considered OK for the layers to crash as long as they've reported an error related to the crash first.

layers: Add PreCallValidateCmdTraceRaysNV

---

build-android/test_APK.sh

In the *.logcat.text file created during test execution,
only lines with "Vulkan-ValidationLayers" were included.
There are some errors (e.g. from the shaderc compiler)
that affect tests but weren't included in logcat.
So now include unfiltered logcat messages.

tests: Don't filter logcat messages

---

layers/generated/spirv_tools_commit_id.h
layers/shader_validation.cpp
layers/shader_validation.h
scripts/known_good.json
tests/vklayertests_pipeline_shader.cpp

Second try. The spirv optimizer has been fixed to address issues in previous attempt and I've added a message consumer which should log when unrecognized extended types fail during specialization.

layers: Validate specialization constants

---

layers/best_practices.cpp
layers/best_practices.h

Now #include "state_tracker.h" instead of "core_validation.h" since the stateTracker now moved to it's own file.
num_mem_objects in BP was never initialized which caused a performance warning to be thrown saying there were too many memory objects. Now initialize num_mem_objects to 0.

Fix Issues in BP after StateTracker moved to its own file

---

tests/vklayertests_pipeline_shader.cpp
tests/vktestframeworkandroid.cpp

ShaderC does validation that will cause one of the tests to fail on some systems supporting non-zero limits for MaxGeometryInputComp/MaxGeometryOutputComp.  Disallowed this test from running on Android platforms.  
Also fixed an issue with the shaderC error output, which was being excluded from CI output due to an invalid filter key.
Fixes #1313.

Remove Geometry inp/outp components test from Android runs, fix shaderc error output

---

build-android/test_APK.sh

Testing has observed occasional spurious test failures that
may be due to a race condition (if the device takes too long to
wake up, it may miss the HOME keycode or process it in the
wrong state).
These changes include a tentative fix for the above, and also
include changes that allow triage of a timeout failure.
(Currently, on a timeout failure, "adb" gets an error
"failed to stat remote object" when trying to pull the
executioin output, which causes the test script to exit
before logcat text can be collected.)
test_APK.sh:
- add "sleep 2" after every keyevent, to ensure that a keyevent is
processed before the next keyevent is sent (and to better simulate
human usage)
- don't wake up the device until after you have the device lock
- don't exit early on error - this exit prevents us from …

Android: Make tests more reliable

---

tests/vklayertests_pipeline_shader.cpp
tests/vkrenderframework.cpp
tests/vktestframework.cpp
tests/vktestframework.h
tests/vktestframeworkandroid.cpp
tests/vktestframeworkandroid.h

The test framework commonly converts glsl to spirv when creating  `VkShaderObj `objects. Glslang validates GL limits (see the list below) using internal, default limits.  The desktop interface to glslang passes in another set of default values.  However, neither the default glslang values nor the version created by the test framework use the actual hardware values for common items.  This PR passes in the current `PhysicalDeviceLimits `values so that glslang's validation will not generate inappropriate limits violation errors.
Also restored the `ExceedMaxGeometryInputOutputComponents `test for Android, since it will no longer generate invalid limits violations.
**Vulkan PDev limits which overlap with glslang's default OpenGL limits**:
- maxClipDistances;
- maxComputeWorkGroupCountX;
- …

Use hardware limits where appropriate for glsl-to-spirv generation

---

layers/core_validation.cpp
layers/core_validation_types.h
layers/state_tracker.cpp
tests/vkpositivelayertests.cpp

https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/1337
In previous version, SWAPCHAIN_NODE has a single bound_images, so when the images of Swapchain are plural, and some regular images bind to a image of Swapchain, and all of bound_images store in the same place, it causes this issues.
Also, when images of SWAPCHAIN store in the same bound_images, it also causes those images of Swapchain thought they were alias images.
So,  in SWAPCHAIN_NODE, each image should have an individual bound_images.

Fix Swapchain images layout issue.

---

layers/generated/lvt_function_pointers.cpp
scripts/lvt_file_generator.py

Layer validation tests weren't running on macOS because of platform specific loader filename.

tests: Add macOS loader filename

---

layers/shader_validation.cpp
tests/layer_validation_tests.cpp
tests/vklayertests_pipeline_shader.cpp

Which would have surfaced the usage issues in https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/1162.

Add validation of ray tracing shader groups

---

layers/core_validation.cpp
tests/vklayertests_command.cpp

An oldie -- `VUID-VkSubmitInfo-pCommandBuffers-00075`.  Also added a test, and moved some other primary/secondary checks into an else clause, since they make little sense in this case and led to more confusion than clarity.
Fixes #1366.

Add VUID check for submitting secondary CB as primary

---

layers/core_validation.cpp
layers/core_validation.h
tests/vkpositivelayertests.cpp

Local per-CB query-state data went out of scope during QueueSubmit-time validation.  Moved state data up to the submit-level and added a positive test.
Fixes #1364.

Fix Query validation when used across multiple command buffers

---

layers/best_practices.cpp
layers/best_practices.h
layers/buffer_validation.cpp
tests/CMakeLists.txt
tests/vklayertests_best_practices.cpp
tests/vklayertests_pipeline_shader.cpp

Resolves #1307 tracked in #24 which moves a performance warning to BP.
I also needed to  set up BP test file for all future BP tests. Migrated one test over to BP which is related to the warning in #1307

Move CmdAttachment Perf Warning to BP and Setup BP Tests

---

layers/core_validation.cpp
tests/vklayertests_buffer_image_memory_sampler.cpp

VUID changes were missing in the 1.1.128 known-good update
Updated:
- `layers/core_validation.cpp`
- `tests/vklayertests_buffer_image_memory_sampler.cpp`
Change-Id: Ic95e44d7e3044779886cd3354fc0e39d93335a6d

build: Update VUIDs for 1.1.128 header

---

tests/layer_validation_tests.h
tests/vklayertests_best_practices.cpp

Includes a BestPractices Tests class and and initBestPracticesFramework to easily enable the BP layer for testing

Add Subclass for BestPractices Tests

---

layers/core_validation.cpp
tests/vklayertests_others.cpp

Would have caught the recent AMD CI failures beforehand.

Add VUID for CmdBeginQuery called on a TIMESTAMP querypool

---

tests/vklayertests_others.cpp

- remove redundant\duplicate skip message
- fix Mock workaround so it does not depend on swapchain image count to always be 2

tests: Minor fixes to SwapchainAcquireTooManyImages

---

layers/vk_layer_config.cpp

vk_layer_settings.txt was not properly parsed because the '=' character was being read as part of the option value. This change makes sure '=' is present in the line being parsed and excludes the character from the option value.

layers: Fix broken config file parsing

---

layers/core_validation.cpp
layers/core_validation_error_enums.h

I got an internal question about this "error" (it's actually "information"), and I noticed it has already been copied to best_practices but not removed from core_validation.

layers: Remove MemTrack-FreedMemRef that has moved to best_practices

---

layers/core_validation.cpp
layers/core_validation.h
layers/core_validation_types.h
layers/state_tracker.cpp
layers/state_tracker.h
tests/vklayertests_others.cpp

These two commits add initial validation support for VK_KHR_timeline_semaphore, including tests for some of them.
These validations do not cover yet the timeline semaphore state tracking, which is something I'm working on currently, but it is not ready.

Add VK_KHR_timeline_semaphore validation

---

layers/best_practices.cpp
layers/best_practices.h
layers/core_validation.cpp
layers/state_tracker.cpp
layers/state_tracker.h

Remove CALLSTATE usages everywhere except in Best Practices and State Tracker. This will enable me to move the CALLSTATE tracking fully into BP layer in a future PR.
Also migrated one warning from Core to BP.

Remove CALLSTATE everywhere except BP

---

layers/generated/vk_extension_helper.h
scripts/helper_file_generator.py

`vk_extension_helper.h` needs `cassert` to compile and it is annoying to have to include it manually before including the file.

include cassert in vk_extension_helper.h

---

layers/state_tracker.cpp
tests/vklayertests_imageless_framebuffer.cpp

In a handful of statetracker locations, framebuffer attachments were being used even though they must be ignored when the `VK_FRAMEBUFFER_CREATE_IMAGELESS_BIT_KHR `bit was set.  Guarded these references and added a positive test.
Fixes #1256.

Fix bad pAttachments derefs when using Imageless Framebuffer extension

---

layers/state_tracker.cpp

This was creating twice the expected number of push constant ranges.
Change-Id: I539dfa6c957a004e6d5f9e500b0747fc66015b8e

Remove default initialized push constant ranges

---

layers/shader_validation.cpp
tests/vklayertests_pipeline_shader.cpp
tests/vkpositivelayertests.cpp

Fix 1367.
Remove the false positive generated by only checking the first range-matching entry of push constant ranges. It is valid as long as one push constant range matches the range and stage.
Change-Id: Ide24b48f08b7d1aa73f0dacb954ecbc584f410f3

Fix overlapping push constant ranges

---

layers/core_validation.cpp
layers/descriptor_sets.cpp
layers/descriptor_sets.h
layers/state_tracker.cpp
layers/state_tracker.h

Simplify the handling of shared pointers from const StateTracker by allowing for an const cast "Get" in the contexts that require it.
Fixes #1395

Improve const shared pointer handling

---

layers/generated/object_tracker.cpp
layers/object_tracker_utils.cpp
scripts/object_tracker_generator.py
tests/vklayertests_descriptor_renderpass_framebuffer.cpp

A couple of parameters must only be checked if specific templateType flags are set.  Added a couple of new VUs and new test cases.
Fixes #1431.

Fixed overly aggressive object lifetimes DescriptorUpdateTemplate validation

---

layers/generated/parameter_validation.cpp
layers/parameter_validation_utils.cpp
layers/stateless_validation.h
scripts/parameter_validation_generator.py
tests/vklayertests_command.cpp

Added a check to stateless validation, and a test.
Fixes #1446.

Check vertexStride parameter in CmdDrawIndirectByteCount API

---

layers/best_practices.cpp
layers/best_practices.h
layers/best_practices_error_enums.h
layers/core_validation.cpp
layers/core_validation.h
layers/core_validation_error_enums.h
layers/drawdispatch.cpp
tests/vklayertests_best_practices.cpp
tests/vklayertests_pipeline_shader.cpp

Google folks were getting a Perf Warning from the Khronos layer (`UNASSIGNED-CoreValidation-DrawState-VtxIndexOutOfBounds`).  Moved this logic to Best Practices and created a new BP VUID there.  
This VUID was also legitimately used in another corechecks location, but had long since been superseded by a family of real VUIDS (`VUID-[APINAME]-None-02720`), which are now plumbed through to the reporting function and report correctly.

Fix up some really old Vertex buffer validation

---

layers/buffer_validation.cpp
layers/core_validation.h

Ensure that initial layout validation is still correct on release
barriers by recording the initial layout usage, while leaving current
layout alone (as it did before to avoid double recording).
Fixes #1437

Record initial layout on release barriers

---

layers/generated/vk_dispatch_table_helper.h
scripts/dispatch_table_helper_generator.py

Device extension functions were previously treated this way, and now instance extension functions are also provided with stubs to prevent walking off the end of a layer call-chain.  This addresses the open Android issues.
Fixes #1336.

Chassis: Added stub functions for instance extension functions

---

layers/core_validation.h
layers/descriptor_sets.cpp
tests/vklayertests_descriptor_renderpass_framebuffer.cpp

In `vkUpdateDescriptorSets `there's valid usage requiring that you cannot write or copy to a standalone sampler binding that was allocated as immutable in the layout.  Added these two VUIDs as well as tests for them.
Fixes #1419.

Add validation for writing/copying to immutable sampler bindings

---

layers/generated/parameter_validation.cpp
layers/generated/parameter_validation.h
layers/parameter_validation_utils.cpp
layers/stateless_validation.h
scripts/parameter_validation_generator.py
tests/vklayertests_buffer_image_memory_sampler.cpp
tests/vklayertests_command.cpp

Didn't see a case of adding both KHR and promoted function to manual
generation list, but assume need to list both and just have point
to same function in parameter_validation.cpp

layers: Added support for VUID 01648

---

layers/core_validation.cpp
tests/vklayertests_buffer_image_memory_sampler.cpp

VUID 01589
> If image was created with a multi-planar format and the VK_IMAGE_CREATE_DISJOINT_BIT flag, there must be a VkImagePlaneMemoryRequirementsInfo included in the pNext chain of the VkImageMemoryRequirementsInfo2 structure
VUID 01590
> If image was not created with the VK_IMAGE_CREATE_DISJOINT_BIT flag, there must not be a VkImagePlaneMemoryRequirementsInfo included in the pNext chain of the VkImageMemoryRequirementsInfo2 structure

Added support for VUID 01589/01590

---

tests/vklayertests_buffer_image_memory_sampler.cpp

This was my mistake from a previous PR, didn't catch before

tests: Fixed checking format against VK_IMAGE_USAGE

---

layers/generated/chassis.h
layers/vk_layer_logging.h
scripts/layer_chassis_generator.py
tests/vkrenderframework.cpp
tests/vkrenderframework.h

Add local logging functions to the base validation object.  
```
LogError(VkHandle, VUID, FormatString, ...)
LogWarning(VkHandle, VUID, FormatString, ...)
LogPerformanceWarning(VkHandle, VUID, FormatString, ...)
LogInformation(VkHandle, VUID, FormatString, ...)
```
This eliminates the need to supply `DebugReportData *`, `DebugReportFlagsBitEXT` enum, and `DebugReportObjectType` for each logging call.  
Follow-on PRs will replace log_msg() calls in the Khronos layer with these new functions.  This will in turn reduce dependencies tying the the log_msg() and layer validation tests ErrorMonitor() to the deprecated DebugReport extension.
Here are a couple of examples illustrating the simplifications:
```
@@ -1788,17 +1781,15 @@ bool CoreChecks::ValidateUpdateDescriptorSets(uint32_t …
```

Simplify Error Logging in Validation Layers

---

layers/descriptor_sets.cpp
layers/descriptor_sets.h

Replace new/free per descriptor with a new/free for a backing store for
all descriptors in a given descriptor set.  Performance optimization.

Optimize descriptor allocation

---

layers/core_validation.cpp
tests/vklayertests_buffer_image_memory_sampler.cpp

VUID-VkBindImagePlaneMemoryInfo-planeAspect-02283
> If the image’s tiling is VK_IMAGE_TILING_LINEAR or VK_IMAGE_TILING_OPTIMAL, then planeAspect must be a single valid format plane for the image. (That is, planeAspect must be VK_IMAGE_ASPECT_PLANE_0_BIT or VK_IMAGE_ASPECT_PLANE_1_BIT for “_2PLANE” formats and planeAspect must be VK_IMAGE_ASPECT_PLANE_0_BIT, VK_IMAGE_ASPECT_PLANE_1_BIT, or VK_IMAGE_ASPECT_PLANE_2_BIT for “_3PLANE” formats.)

Added support for VUID 02283

---

layers/range_vector.h

Fixes assert in range vector code from running
api.image_clearing.core.clear_depth_stencil_image.multiple_layers.d24_unorm_s8_uint_separate_layouts_depth

Fix call to overwrite_range

---

layers/CMakeLists.txt
layers/buffer_validation.cpp
layers/core_validation.cpp
layers/descriptor_sets.cpp
layers/drawdispatch.cpp
layers/generated/chassis.h
layers/gpu_validation.cpp
layers/hash_util.h
layers/parameter_validation_utils.cpp
layers/shader_validation.cpp
layers/sparse_containers.h
layers/state_tracker.cpp
layers/vk_layer_config.cpp
layers/vk_loader_platform.h
scripts/layer_chassis_generator.py
tests/CMakeLists.txt
tests/layer_validation_tests.h
tests/test_common.h

Not having NOMINMAX defined in every file was causing build issues in Chromium.  As @jzulauf-lunarg suggested, this change moves that definition into the CMake file, making local definitions unnecessary.  Passes internal CI cleanly.
Fixes #1501.

Move NOMINMAX definition from sources to CMake file

---

BUILD.gn

NOMINMAX define was previously added to Win CMake build, this adds it to ninja build.

build: Add NOMINMAX to Win ninja build

---

layers/buffer_validation.cpp
layers/core_validation_types.h

Fixes crash in
dEQP-VK.image.mutable.2d.r32g32b32a32_sfloat_r32g32b32a32_uint_clear_load_format_list
and others

Use safe_VkImageCreateInfos in core validation

---

BUILD.gn

layers/state_tracker.h is listed in both core_validation_sources and
chassis_sources and these two lists are then concatenated. This leads
to duplicate entries which then causes errors when loading gn generated
projects into Visual Studio. The error message is:
Cannot load project with duplicated project items:
... vulkan-validation-layers/src/layers/state_tracker.h is included
as 'None' and as 'None' item types.
This was found while investigating crbug.com/1048779.
layers/core_validation.h is also duplicated and is also fixed by this.
This fixes issue 1526.

Fix duplicate header file entries

---

layers/descriptor_sets.cpp

VU01564 should only be issued if VkDescriptorImageInfo::sampler is used.
VkDescriptorImageInfo::sampler is unused if the binding uses an immutable sampler.
Fixes #1523

layers: Don't issue VU01564 for immutable samplers

---

layers/descriptor_sets.cpp
layers/descriptor_sets.h
tests/vklayertests_descriptor_renderpass_framebuffer.cpp

VUID-VkWriteDescriptorSet-descriptorCount-00317
> All consecutive bindings updated via a single VkWriteDescriptorSet structure, except those with a descriptorCount of zero, must have identical descriptorType and stageFlags.
VUID-VkWriteDescriptorSet-descriptorCount-00318
> All consecutive bindings updated via a single VkWriteDescriptorSet structure, except those with a descriptorCount of zero, must all either use immutable samplers or must all not use immutable samplers
---
Needed to remove 00321 tests duplicates that were testing what
00317 and 00318 should have been testing instead. There is still
00321 tests left.

Added support for 00317 and 00318

---

layers/generated/parameter_validation.cpp
layers/parameter_validation_utils.cpp
layers/stateless_validation.h
scripts/parameter_validation_generator.py
tests/vklayertests_others.cpp

VUID-VkImportSemaphoreFdInfoKHR-handleType-01143
> handleType must be a value included in the Handle Types Supported by VkImportSemaphoreFdInfoKHR table.

Added support for VUID 01143

---

layers/parameter_validation_utils.cpp
tests/vklayertests_buffer_image_memory_sampler.cpp

VUID-VkSamplerCreateInfo-maxLod-01973
> maxLod must be greater than or equal to minLod
VUID-VkSamplerCreateInfo-mipLodBias-01069
> The absolute value of mipLodBias must be less than or equal to VkPhysicalDeviceLimits::maxSamplerLodBias

Added support for 01973 and 01069

---

layers/core_validation.cpp
tests/vklayertests_descriptor_renderpass_framebuffer.cpp

VUID-vkCmdBindDescriptorSets-firstSet-00360
> The sum of firstSet and descriptorSetCount must be less than or equal to VkPipelineLayoutCreateInfo::setLayoutCount provided when layout was created

Added support for VUID-vkCmdBindDescriptorSets-firstSet-00360

---

layers/buffer_validation.cpp
layers/vk_format_utils.cpp
tests/vklayertests_buffer_image_memory_sampler.cpp

Validation checks for `VUID-vkCmdBlitImage-srcImage-01561` and `VUID-vkCmdBlitImage-dstImage-01562`, including tests.  
Fixes #1488.

Add CmdBlitImage YCBCR format VUIDs

---

layers/shader_validation.cpp
tests/vklayertests_pipeline_shader.cpp
tests/vkpositivelayertests.cpp

I needed to update to the latest headers to get the extension in the auto-generated availability flags. I did my best to model what previous updates had done but I may have messed up (previous updates seemed to update the VulkanTools commit pointer but I couldn't figure out why or if it was a coincidence). I can either try and fix it, or else we can defer this PR until the update is done properly and I can rebase my PR to drop that commit.
I also added a couple of tests to make sure the validation worked in both directions (detecting problems and not complaining when it's fine), although they're fairly trivial.

Add validation support for VK_KHR_shader_non_semantic_info

---

layers/generated/thread_safety.cpp
layers/generated/thread_safety.h
scripts/thread_safety_generator.py
tests/vklayertests_others.cpp

Threading object would generate errors, but with no mention of the API which caused the problem.  Modified the codegen to include the api name as part of the validation error messages.
Fixes #259.

Plumb thread safety API names through to error messages

---

layers/buffer_validation.cpp
layers/parameter_validation_utils.cpp

The framework automatically marks promoted extensions as enabled, so no need to check for VK_API_VERSION explicitly. This was causing confusion in external PRs. @sfricke-samsung, if you know of any instances that were missed, please chime in.
Fixes #1553.

Remove redundant API version checks

---

layers/generated/thread_safety.cpp
layers/generated/thread_safety.h
scripts/thread_safety_generator.py
tests/vkpositivelayertests.cpp

These objects can be created through the `GetPhysicalDeviceDisplayProperties `APIs, so needed to special-case these for this validation object as pointed out by **amshafer** in the original issue.  Added a positive test as well.  
Fixes #1569.

Fix use of VkDisplayKHR objects in thread safety validation

---

layers/best_practices.cpp
layers/best_practices.h
layers/best_practices_error_enums.h
tests/vklayertests_best_practices.cpp

Added checks for:
- Command pool creation with the RESET_COMMAND_BUFFER bit
- Simultaneous use of command buffers
This corresponds to checks 1-2 from [PerfDoc](https://github.com/ARM-software/perfdoc).

Best Practices: Add checks for command buffer handling

---

layers/generated/thread_safety.h
scripts/thread_safety_generator.py

Thread checker used obsolete debug-report enums for object identifiers -- updated to use VulkanObjectTypes instead.  This gives additional information for Vulkan objects defined after the debug report extension was released.

threading: Remove use of debug report defs

---

layers/best_practices.cpp
layers/best_practices.h
layers/best_practices_error_enums.h
tests/vklayertests_best_practices.cpp

Added checks for:
- Store ops for potentially transient images
- Framebuffer attachments that should/should not be transient
- Clearing attachments after load
- Many instanced vertex buffers in a pipeline
This corresponds to checks 8, 10-11, 14 and 32 from [PerfDoc](https://github.com/ARM-software/perfdoc).

Best Practices: Added checks for attachments and vertex buffers

---

layers/descriptor_sets.cpp
tests/vklayertests_descriptor_renderpass_framebuffer.cpp

Removes `UNASSIGNED-CoreValidation-DrawState-InvalidImageView` with the actual VUID from spec

layers: Label VUID 00337, 00338, 00339

---

layers/buffer_validation.cpp
tests/vklayertests_buffer_image_memory_sampler.cpp

VUID-vkCmdClearColorImage-image-01545
> image must not use a format listed in Formats requiring sampler Y′CBCR conversion for VK_IMAGE_ASPECT_COLOR_BIT image views

Add support for 01545

---

layers/core_validation.cpp
tests/vklayertests_buffer_image_memory_sampler.cpp

VUID-VkImageMemoryRequirementsInfo2-image-02280
> If image was created with a single-plane format and with any tiling other than VK_IMAGE_TILING_DRM_FORMAT_MODIFIER_EXT, then there must not be a VkImagePlaneMemoryRequirementsInfo included in the pNext chain of the VkImageMemoryRequirementsInfo2 structure
VUID-VkImagePlaneMemoryRequirementsInfo-planeAspect-02281
> If the image’s tiling is VK_IMAGE_TILING_LINEAR or VK_IMAGE_TILING_OPTIMAL, then planeAspect must be a single valid format plane for the image. (That is, for a two-plane image planeAspect must be VK_IMAGE_ASPECT_PLANE_0_BIT or VK_IMAGE_ASPECT_PLANE_1_BIT, and for a three-plane image planeAspect must be VK_IMAGE_ASPECT_PLANE_0_BIT, VK_IMAGE_ASPECT_PLANE_1_BIT or VK_IMAGE_ASPECT_PLANE_2_BIT).

Add support for 02280 and 02281

---

layers/generated/parameter_validation.cpp
layers/parameter_validation_utils.cpp
layers/stateless_validation.h
scripts/parameter_validation_generator.py
tests/vklayertests_buffer_image_memory_sampler.cpp
tests/vklayertests_others.cpp

Required change to Vulkan header 1.2.133
The logic for this was already there, just didn't have the correct VUID tagged to it.
For the test, I found it would add more coverage to replace querying a vendor extension with a Vulkan 1.1 requirement.

Add support for sType-unique and most pNext-pNext

---

layers/generated/chassis.h
layers/vk_layer_config.h
layers/vk_layer_logging.h
layers/vk_layer_utils.cpp
scripts/layer_chassis_generator.py
tests/layer_validation_tests.cpp
tests/layer_validation_tests.h
tests/test_common.h
tests/vklayertests_best_practices.cpp
tests/vklayertests_buffer_image_memory_sampler.cpp
tests/vklayertests_command.cpp
tests/vklayertests_descriptor_renderpass_framebuffer.cpp
tests/vklayertests_imageless_framebuffer.cpp
tests/vklayertests_others.cpp
tests/vklayertests_pipeline_shader.cpp
tests/vkpositivelayertests.cpp
tests/vkrenderframework.cpp
tests/vkrenderframework.h

Lots of the validation/test code was built around stuff defined in the debug report extension, which was deprecated long ago.  This PR removes most of those dependencies, and paves the way for tests to be converted to use the debug utils extension for callbacks.
I'll handle rebasing for in-flight PRs, just lemme know.

Remove repo dependencies on deprecated VK_DEBUG_REPORT extension

---

layers/best_practices_error_enums.h
layers/vk_layer_logging.h
tests/layer_validation_tests.cpp
tests/layer_validation_tests.h
tests/vklayertests_best_practices.cpp
tests/vklayertests_buffer_image_memory_sampler.cpp
tests/vklayertests_command.cpp
tests/vklayertests_descriptor_renderpass_framebuffer.cpp
tests/vklayertests_imageless_framebuffer.cpp
tests/vklayertests_others.cpp
tests/vklayertests_pipeline_shader.cpp
tests/vkpositivelayertests.cpp
tests/vkrenderframework.cpp
tests/vkrenderframework.h

Debug Report is deprecated.  This PR changes the test harness to use the DebugUtils extension.
Also fixes some tests and framework issues found during the refactor.

Move Layer Validation Tests to use DebugUtils extension

---

layers/buffer_validation.cpp
tests/vklayertests_command.cpp

This partly was to address #1499 but still currently working with Working Group to decide on how to handle the VUID 00122/00123
This PR does 3 things
- Adds support for `VUID-vkCmdCopyImage-srcImage-01548`
- Fixes bug that `VUID-vkCmdCopyImage-srcImage-00135` wasn't checking for non-multi-planar formats as mentioned in spec (looks like it was written pre-YCbCr support so makes sense)
- Adds a series of tests to check current coverage of YCbCr VkCmdCopyImage for future fixes to the VUID related to them

Clean up YCbCr support in VkCmdCopyImage

---

layers/core_validation.cpp
tests/vklayertests_others.cpp

We recently changed some alignment/padding reported by our driver, and it causes some validation tests to fail. I found the failures are due to using the wrong size for the buffers.

Fix RayTracing VUIDs to use buffer->createInfo.size

---

scripts/common_codegen.py
scripts/object_tracker_generator.py
scripts/thread_safety_generator.py

Aliased handle types are still handle types and belong in this
dictionary. Add another dictionary to tell whether a type is an
alias, and use that to skip some redundant codegen for aliases.
There should be no effect on the generated files with the current XML.

scripts: Add aliased types to handle_types

---

layers/shader_validation.cpp

"range-loop-constructs" is a new warning added to catch this bad code
pattern. Because the warning might be unavailable on older Clang or GCC
we don't try to enable it anywhere for now. If it pops up again we can
look at disabling it in the GN build or adding it to the default set
of enabled warnings.
@mikes-lunarg @mark-lunarg  PTAL

Fix Chromium warning about copying iterators.

---

layers/parameter_validation_utils.cpp
tests/vklayertests_buffer_image_memory_sampler.cpp

VUID-VkImageCreateInfo-usage-00968
> If the multisampled storage images feature is not enabled, and usage contains VK_IMAGE_USAGE_STORAGE_BIT, samples must be VK_SAMPLE_COUNT_1_BIT

Add support for VUID 00968

---

layers/core_validation.cpp
tests/vklayertests_buffer_image_memory_sampler.cpp

VUID-VkBufferMemoryBarrier-size-01188
> If size is not equal to VK_WHOLE_SIZE, size must be greater than 0

Add support for VUID 01188

---

layers/parameter_validation_utils.cpp
tests/vklayertests_descriptor_renderpass_framebuffer.cpp

VUID-VkDescriptorSetLayoutBinding-descriptorType-01510
>  If descriptorType is VK_DESCRIPTOR_TYPE_INPUT_ATTACHMENT and descriptorCount is not 0, then stageFlags must be 0 or VK_SHADER_STAGE_FRAGMENT_BIT

Add support for VUID 01510

---

layers/core_validation.cpp
tests/vklayertests_descriptor_renderpass_framebuffer.cpp

VUID-VkSubpassDescription2-attachment-02801
> If the attachment member of any element of pInputAttachments is not VK_ATTACHMENT_UNUSED, then the aspectMask member must not include VK_IMAGE_ASPECT_METADATA_BIT

Add support for VUID 02801

---

layers/buffer_validation.cpp
tests/vklayertests_others.cpp

VUID-VkImageViewCreateInfo-image-01762
Note: There were 2 tests for `VUID-VkImageViewCreateInfo-image-01019` and only 1 was changed so now both VUID are covered in tests

Add support for VUID 01762

---

layers/core_validation.cpp
layers/core_validation.h
layers/core_validation_types.h
layers/state_tracker.cpp
tests/vklayertests_others.cpp

This PR add more timeline semaphores VUIDs validation, as well as new tests for some of them.
Specifically, it tries to track correctly the status of the semaphores.

More Timeline Semaphore validation

---

.travis.yml

GN builds could fail, but these were 'allowed' and would not fail a travis build. Made them hard failures.

Make GN build problems hard failures for Travis CI

---

layers/core_validation.cpp
tests/layer_validation_tests.cpp
tests/layer_validation_tests.h
tests/vklayertests_descriptor_renderpass_framebuffer.cpp
tests/vklayertests_pipeline_shader.cpp

This adds support for various VUID tied to an `ifdef` around the Descriptor Indexing extension
VUID-VkPipelineLayoutCreateInfo-descriptorType-03016
VUID-VkPipelineLayoutCreateInfo-descriptorType-03017
VUID-VkPipelineLayoutCreateInfo-descriptorType-03018
VUID-VkPipelineLayoutCreateInfo-descriptorType-03019
VUID-VkPipelineLayoutCreateInfo-descriptorType-03020
VUID-VkPipelineLayoutCreateInfo-descriptorType-03021
VUID-VkPipelineLayoutCreateInfo-descriptorType-02212
VUID-VkPipelineLayoutCreateInfo-descriptorType-03028
VUID-VkPipelineLayoutCreateInfo-descriptorType-03029
VUID-VkPipelineLayoutCreateInfo-descriptorType-03028
VUID-VkPipelineLayoutCreateInfo-descriptorType-03030
VUID-VkPipelineLayoutCreateInfo-descriptorType-03031
VUID-VkPipelineLayoutCreateInfo-descriptorType-03032 …

Add support for Descriptor Indexing Duplicate VUID

---

layers/descriptor_sets.cpp
tests/vklayertests_descriptor_renderpass_framebuffer.cpp

#1544 didn't correctly handle descriptor bindings with descriptorCount>1. Fix that, and expand the tests.
@sfricke-samsung, FYI

layers: Fix consecutive binding validation

---

CMakeLists.txt

Clang was already set to fail on warnings, but only did so for Ubuntu 16.04 LTS default clang versions (3.8.0 ?) or earlier.  Updated version to 6.0.0, the default version in Ubuntu 18.04 LTS.

Enable Warnings-As-Errors for Clang compiler on Travis CI builds

---

build-android/jni/Android.mk
tests/layer_validation_tests.cpp

These were left over from the Pleistocene and were unused.  Removes an unnecessary inter-repository dependency.

tests: Remove unused refs to Vulkan-Tools vulkan_wrapper.*

---

layers/core_validation.cpp
layers/core_validation.h
layers/drawdispatch.cpp

Instead of passing strings into a function, moved to a LUT instead.
This is needed to in order to expand more drawdispatch VUID to be added
Issue #135

layers: Refactor DrawDispatch VUID strings

---

layers/buffer_validation.cpp
layers/stateless_validation.h
tests/vklayertests_descriptor_renderpass_framebuffer.cpp

Main issue is there are 3 sets of VUID for checking if LOAD_OP_CLEAR
- renderpass2
- renderpass with Maintenance2
- renderpass with no extension
Tests need to updated otherwise will fail CI with changes
Adds
VUID-VkRenderPassCreateInfo-pAttachments-02511
VUID-VkRenderPassCreateInfo-pAttachments-02513

layers: Fix renderpass2 VUID

---

layers/generated/vk_safe_struct.cpp
layers/generated/vk_safe_struct.h
scripts/helper_file_generator.py

Without this, the type sizes won't match and the code to copy arrays is broken.
Fixes #1647.

scripts: Make safe structs 'union' or 'struct' to match the Vulkan headers

---

layers/state_tracker.cpp
tests/vkpositivelayertests.cpp

I was running a test using sparse memory, and some memory that was previously bound to the sparse image was freed, then the image was used again. This caused this assert in ValidationStateTracker::GetStateStructPtrFromObject to fire, and then crash:
```
assert(object_struct.node == GetStateStructPtrFromObject(other));
```
I didn't see any code to ever actually erase elements from sparse_bindings, but the hook was there (UpdateBoundMemorySet) to recompute the bound_memory_set when freeing memory.

layers: Make FreeMemory remove memory from sparse_bindings

---

.travis.yml
scripts/known_good.json

These repos are unneeded for validation layers and are solely used for Travis CI.  Removed them from known good and updated` .travis.yml` to clone those repos and build using the VVL-specified sub-components.
TOT should be fine for the `MockICD `and `device_simulation` layers, more so since they're built using VVL-specified headers.  If there is an issue, it can be fixed in the source repos and pushed there _requiring no update_ of `known_good.json` files.
This should simplify Vulkan header updates for the VVL repo.

Remove VulkanTools, Vulkan-Tools from VVL Known-Good

---

layers/state_tracker.cpp

This CL adds an extra set of braces around the array initializer. This
works around a warning being received from Clang5 for -Wmissing-braces
which turnes into an error due to the -Werror being enabled.

Add braces around array initializer.

---

layers/buffer_validation.cpp
layers/core_validation.cpp
layers/core_validation_types.h
layers/state_tracker.cpp
tests/vklayertests_buffer_image_memory_sampler.cpp

These structures don't alias and have slightly different meaning. Split them
so VUID-vkBindBufferMemory-bufferDeviceAddress-03339 only applies to KHR/core.
Fixes #1661

layers: Split EXT buffer_device_address features from KHR

---

tests/vklayertests_buffer_image_memory_sampler.cpp
tests/vklayertests_descriptor_renderpass_framebuffer.cpp
tests/vklayertests_others.cpp
tests/vkpositivelayertests.cpp

This CL adds the explicit {}'s around std::array initializers to work
around a compiler warning (which turns to error).

[layers] Add braces around std::array initializers

---

layers/generated/vk_enum_string_helper.h
scripts/helper_file_generator.py
tests/test_common.h

Fixes warning seen downstream in https://github.com/godotengine/godot when building with Clang on Windows: https://github.com/godotengine/godot/pull/37492#issuecomment-607271991
```
thirdparty\\vulkan\\vk_enum_string_helper.h:35:9: error: unknown pragma ignored [-Werror,-Wunknown-pragmas]
#pragma warning( disable : 4065 )
```
I reviewed other uses of `disable :` to ensure that they checked `_MSC_VER` and not `_WIN32`.

build: Don't set MSVC pragma for Win32 GCC/Clang

---

build-gn/generate_vulkan_layers_json.py

Bring over commit: https://github.com/KhronosGroup/Vulkan-Tools/commit/94ed4c384c3425963b459a735045706e5f83f01b to keep the build-gn/generate*.py scripts identical across repos.
See the Vulkan-Tools commit for rationale of the change.
Change-Id: I8b132147d9ffff13fbfbbcc644e26ae0c23a50e8

build-gn: Keep generate*.py identical across repos

---

layers/best_practices_validation.h
layers/command_counter.h
layers/core_validation.cpp
layers/core_validation.h
layers/debug_printf.h
layers/generated/chassis.cpp
layers/generated/chassis.h
layers/generated/thread_safety.h
layers/gpu_validation.h
layers/object_lifetime_validation.h
layers/state_tracker.cpp
layers/state_tracker.h
layers/stateless_validation.h
scripts/layer_chassis_generator.py
scripts/thread_safety_generator.py

Moved much of the per-validation-object setup into constructors/init functions.

Clean up create-instance/device validation object setup and initialization

---

tests/vkrenderframework.cpp
tests/vkrenderframework.h
tests/vktestbinding.cpp
tests/vktestbinding.h

- remove parameters the class already knows
- use pre-existing code for extension enumeration
- simplify it so it does not require `layer` parameter (enumerate extensions for all enabled layers)
- update enumeration code to be robust

tests: Refactor DeviceExtensionSupported

---

layers/core_validation.cpp
tests/layer_validation_tests.cpp
tests/layer_validation_tests.h
tests/vklayertests_buffer_image_memory_sampler.cpp
tests/vklayertests_descriptor_renderpass_framebuffer.cpp
tests/vklayertests_others.cpp
tests/vkpositivelayertests.cpp

Fix errors that were happening when errorMonitor was not running and were being ignored

Fix extraneous test errors

---

tests/layer_validation_tests.cpp
tests/layer_validation_tests.h
tests/layers/device_profile_api.cpp
tests/layers/vk_lunarg_device_profile_api_layer.h

This is added for future YCbCr tests I wrote that are waiting for other PR to get merged in first (in VVL and Spec). Those tests need to call `vkGetPhysicalDeviceFormatProperties2` and realized I wasn't able to use the device profile api layer with current lack of support.
Until then, broke this logic out into own commit as it will be needed

Add PhysicalDeviceFormatProperties2 for Device Profile API

---

layers/image_layout_map.cpp
layers/parameter_validation_utils.cpp
layers/range_vector.h
layers/subresource_adapter.h

Small cleanup pass to eliminate warnings [-Wdeprecated-copy](https://gcc.gnu.org/onlinedocs/gcc-9.1.0/gcc/C_002b_002b-Dialect-Options.html#index-Wdeprecated-copy) and [-Wignored-qualifiers](https://gcc.gnu.org/onlinedocs/gcc-9.1.0/gcc/Warning-Options.html#index-Wignored-qualifiers) with recent versions of GCC.
-Wdeprecated-copy is particularly noisy and makes it difficult sort through other compiler output.

Fix some noisy warnings when compiling with GCC 9.1

---

layers/state_tracker.cpp

Fixes an exception running dEQP-VK.synchronization.timeline_semaphore.device_host.write_copy_buffer_read_copy_buffer.buffer_16384
with layers built with VS2015

Don't remove container contents during iteration

---

layers/best_practices_utils.cpp
layers/core_validation.cpp
layers/core_validation.h
layers/core_validation_types.h
layers/state_tracker.cpp
layers/state_tracker.h
tests/vklayertests_buffer_image_memory_sampler.cpp

This adds
VUID-VkBindImageMemoryInfo-pNext-01619
VUID-VkBindImageMemoryInfo-pNext-01620
VUID-VkBindImageMemoryInfo-pNext-01621
Which already were checked for non-disjoint VUID, this adds support for disjoint VUID.
This required some additional state tracking logic to be added as well as removing unused arguments getting passed around
Also adds
VUID-VkBindImageMemoryInfo-pNext-01615
VUID-VkBindImageMemoryInfo-pNext-01616
VUID-VkBindImageMemoryInfo-pNext-01617
Which is just the `device_extensions.vk_khr_sampler_ycbcr_conversion` addition of 3 other VUID

Add disjoint bindImageMemory VUID

---

build-android/jni/Android.mk
layers/vk_layer_logging.h
tests/CMakeLists.txt
tests/layer_validation_tests.cpp
tests/layer_validation_tests.h
tests/vklayertests_buffer_image_memory_sampler.cpp
tests/vklayertests_instanceless.cpp
tests/vklayertests_others.cpp
tests/vkpositivelayertests.cpp
tests/vkrenderframework.cpp
tests/vkrenderframework.h
tests/vktestbinding.cpp

Add tests for `vkCreateInstance` and `vkDestroyInstance`.
Unfortunatelly requires some considerable framework work; I want to be able to directly call `vkCreateInstance` to maximize the amount of tests I can do without worrying about the framework internals.
There are some problems discovered during this (those tests are not part of this PR, and there is a workaround that has to be on all the tests). There are probably some problems with Loader, Layer, or MockICD, where those are buggy or not as robust as they could be. Directory to emergent Issues or fixes:
- #1677 (demonstrated by #1676) -- creating two instances without destroy in between crashes subsequent destroy. This necessitates the workarounds in this PR.
- fixed by https://github.com/KhronosGroup/Vulkan-Tools/pull/365 and …

tests: Add instance creation\destruction tests

---

tests/vkpositivelayertests.cpp

This code crashes, but looks like it should work.
It crashes specifically when used with MockICD, and the enabled layers are the ValidationLayer+DeviceProfileLayer.

tests: Add multiple instance creation test

---

layers/buffer_validation.cpp
layers/core_validation.cpp
layers/core_validation_types.h
layers/descriptor_sets.cpp
layers/descriptor_sets.h
layers/vk_layer_logging.h

Dozens of these error messages were not using `FormatHandle()`, resulting in object names and types missing from error messages.
Fixes #1695.

Fix descriptor_sets.cpp error messages for proper object handing

---

layers/buffer_validation.cpp
layers/core_validation.cpp
layers/core_validation.h
layers/core_validation_error_enums.h
layers/core_validation_types.h
layers/state_tracker.cpp
tests/vklayertests_buffer_image_memory_sampler.cpp
tests/vklayertests_others.cpp

So this fixes up a few issues with external AHB tracking
The big change is instead of tracking "imported ahb" I am tracking "external ahb" which can be imported or exported as there is no way to know if it will be imported or exported upon creating an image/buffer
This makes fixes to upcoming spec fixes that alter the use of dedicated memory VU if its an external AHB
Lastly made changes to the fact you can't call vkGet*MemoryRequirements for an external AHB until the memory is bound
More changes to come in future, this is just to clean things up a little first

Fix general external AHB tracking

---

layers/core_validation.cpp
layers/core_validation.h
layers/state_tracker.cpp
layers/state_tracker.h

Add the missing validation and record entry points for vkWaitSemaphores
and vkWaitSemaphoresKHR.
Fixes #1502

Add missing WaitSemaphores (KHR/not) entry

---

tests/vklayertests_others.cpp
tests/vkpositivelayertests.cpp

Remove mock workarounds for vkAcquireNextImageKHR
that now correctly returns index value

tests: Remove mock workarounds for vkAcquire

---

scripts/vk_validation_stats.py

Removed KHR alias logic, it was not updated and unnecessary -- validation always uses unaliased names.
Also cleaned up special cases in the consistency checks (comes up clean now) and added counting of a bunch of code-generated implicit VUIDs.

Validation-stats cleanup, remove dead code

---

layers/core_validation.cpp
layers/core_validation.h
tests/vklayertests_pipeline_shader.cpp

We got this bug report from the Angle team at Google : https://gitlab.freedesktop.org/mesa/mesa/-/issues/2743
After checking the spec I realized this should have been reported as an error in the validation layer but we're missing this VU.

Validate blending on color attachment without blending support VU 02023

---

layers/core_validation.cpp
layers/generated/chassis.cpp
layers/object_lifetime_validation.h
layers/object_tracker_utils.cpp
layers/parameter_validation_utils.cpp
scripts/layer_chassis_generator.py
tests/layer_validation_tests.h
tests/vklayertests_best_practices.cpp
tests/vklayertests_command.cpp

Add missing skip handling of debug callback for `vkCreateInstance`.
Should fix #1713 and remove necessity for the workarounds in #810.

layers: Add missing skip handling to commands

---

layers/buffer_validation.cpp
layers/core_validation.cpp
layers/core_validation.h
layers/core_validation_types.h
layers/state_tracker.cpp
layers/state_tracker.h

This resolves #1636 
This is to add structural support only as future PR can add new VU's and tests
The state_tracking here adds tracking of format feature at an Image and ImageView level. This is determined by the area of the spec that describes the edge cases for drm formats and AHB formats.
There is also a slight change to how the AHB is being tracked for external formats in order to add support

Add full Format Feature tracking support

---

layers/core_validation.cpp

The way this check is written implies a false positive unless *both*
pSemaphore->signaled and SemaphoreWasSignaled() are true. But based on
the rest of the code, the intent here is clearly to assume a semaphore
is signalled if *either* of the two return true.
Fixes #1712.

layers: fix logic error in semaphore validation

---

layers/buffer_validation.cpp
layers/core_validation_error_enums.h
tests/layer_validation_tests.cpp
tests/vklayertests_buffer_image_memory_sampler.cpp
tests/vklayertests_others.cpp

Many small fixes for various tests ran on Android (cc #1726)
- Add `kVUID_Core_Image_FormatNotSupported` as some Android devices didn't support combination of create image features. Also made message more clear what is wrong
- Checked if `CreateGraphicsPipeline` was successful as some devices have compilers that fail to compiler the pipeline and will lead to the layers crashing when trying to reference a `PIPELINE_STATE` that doesn't exists
- Some Android device don't support multiple viewports so firstScissor must be 0 (VUID-vkCmdSetScissor-firstScissor-00593). These test were triggering two VUs while test only expected one
- Check for support before calling to `vkGetPhysicalDeviceProperties2` which otherwise crashed a device

Fixes crashing some Android devices

---

layers/state_tracker.cpp
layers/state_tracker.h
tests/vklayertests_buffer_image_memory_sampler.cpp

When I made #1644 I realized that when the image (and buffer) is created the layers check the memory requirements as it is not invalid to not do so from the app side (the Best Practice will yell though)
Its seems error prone to have it being tracked in two spots, so I wrote the TODO I am removing here. I wrote a test to validate the layers throw the same error regardless of the memory requirements being checked or not prior

Remove redundant checking of memory requirements

---

layers/core_validation.cpp

The new check from #1693 will crash if there are more blend attachments than subpass color attachments. This means VUID-VkGraphicsPipelineCreateInfo-attachmentCount-00746 has already been violated, but it's still nice not to crash in this case.

layers: Fix crash when there are more blend attachments than subpass color attachments

---

layers/buffer_validation.cpp
tests/vklayertests_buffer_image_memory_sampler.cpp

VUID-VkImageCreateInfo-imageCreateFormatFeatures-02260
> If format is a multi-planar format, and if imageCreateFormatFeatures (as defined in Image Creation Limits) does not contain VK_FORMAT_FEATURE_DISJOINT_BIT, then flags must not contain VK_IMAGE_CREATE_DISJOINT_BIT

Add support for VUID 02260

---

layers/best_practices_utils.cpp
layers/best_practices_validation.h

Should fix [this issue](https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/1739).
Additionally, leaving `instance_api_version` as zero by default should be sufficient, as checks are looking for `instance_api_version > [target_version]`.

Best Practices - fix null pointer issue in PreCallRecordCreateInstance

---

tests/vklayertests_instanceless.cpp

attempt trois
Should hopefully work now with `vkCreateInstance` being skipped via #1717.
cc @sfricke-samsung @mark-lunarg

tests: Remove mock workarounds in instanceless

---

layers/generated/thread_safety.h
scripts/thread_safety_generator.py
tests/vkpositivelayertests.cpp

Do not reset counter on `vkGetDeviceQueue`.
When `vkGetDeviceQueue` gets called it calls `CreateObject`, which rewrites the counter. But if `vkGetDeviceQueue` was already called before and same `VkQueue` was already received, the access counters get reset to `0`. If some parallel command is using this `VkQueue` and finishes, then it decrements the access count to `-1`, which upon next access causes a threading validation error (because `accesscount != 0`).
https://stackoverflow.com/questions/61310092/vulkan-theaded-application-get-error-message-on-queue-submissions-under-mutex
https://github.com/KhronosGroup/Vulkan-Docs/issues/1254

layers: Do not reset counter on vkGetDeviceQueue

---

layers/buffer_validation.cpp
layers/parameter_validation_utils.cpp
tests/vklayertests_buffer_image_memory_sampler.cpp

This is failing on devices that don't support the `imageCubeArray` feature

Fix cubearray test from failing on device not supporting feature

---

layers/gpu_validation.cpp
layers/gpu_validation.h

I missed this in the 1.2 promotion update

Fix GPU-AV for promoted buffer device address

---

layers/core_validation.cpp
layers/core_validation.h
layers/state_tracker.cpp
layers/state_tracker.h
tests/vklayertests_buffer_image_memory_sampler.cpp

Adds support for 
- VUID-VkSamplerYcbcrConversionCreateInfo-format-01650
- VUID-VkSamplerYcbcrConversionCreateInfo-xChromaOffset-01651
- VUID-VkSamplerYcbcrConversionCreateInfo-xChromaOffset-01652
- VUID-VkSamplerYcbcrConversionCreateInfo-forceExplicitReconstruction-01656 (might be longest VUID name out there 🤣)
- VUID-VkSamplerYcbcrConversionCreateInfo-chromaFilter-01657
- VUID-VkSamplerCreateInfo-minFilter-01645
Adds state tracking for `VkSamplerYcbcrConversions` for use in checking `VUID-VkSamplerCreateInfo-minFilter-01645`
The `GetPotentialFormatFeatures` function will also be reused for future Render Pass VUID that also check for the same style Format Feature VUIDs

Add Sampler YCbCr Conversion Format Feature VUIDs

---

scripts/object_tracker_generator.py

Fix for incoming header breakage.
Array types may get multiple optional values from vk.xml, one for each level of pointer indirection.  Update object_tracker_generator.py to choose the correct optional value for handles inside arrays.

scripts: Object tracker optional handling

---

tests/vklayertests_best_practices.cpp
tests/vkrenderframework.cpp
tests/vkrenderframework.h

Add correctly scoped storage for previously function scoped stack
storage in the renderpass and framebuffer create info.  The renderpass ci was pointer to stale pointers (stack std::vector data)
Also, changed the initial layout away from UNDEFINED for loadOpLoad targets, as that doesn't make *any* sense given that an transition away from UNDEFINED results in undefined contents that wouldn't make sense to *load*.

Add persitant storage for renderpass/framebuffer, and sanify initial layout

---

layers/buffer_validation.cpp

Needs to consider imageless framebuffers.
Fixes #1780

Fix ValidateClearAttachmentExtent

---

layers/best_practices_utils.cpp
layers/buffer_validation.cpp
layers/core_validation.cpp
layers/core_validation.h
layers/core_validation_types.h
layers/state_tracker.cpp
tests/layer_validation_tests.cpp
tests/layer_validation_tests.h
tests/vklayertests_buffer_image_memory_sampler.cpp

3 Things happening here 
1. Add `VUID-vkBindImageMemory2-pBindInfos-02858` support
2. Moved disjoint status to IMAGE_STATE as it is now referenced a lot more and much easier to use then have to compare the flag every time
3. Add support for upcoming spec 139 VUID I just labeled as `UNASSIGNED-vkBindImageMemory2-duplicate` for now which says the pBindInfos must not refer to the same image subresource more than once. If we want to wait until the 139 headers get merged thats fine, otherwise I will update the VUID when it comes out in another pull request
Note: for the  `UNASSIGNED-vkBindImageMemory2-duplicate` I moved redid the ValidateBindImage call the consume the array count... it might be a little awful to review fyi

Add support for vkBindImageMemory2 VUID

---

tests/layer_validation_tests.cpp
tests/vklayertests_best_practices.cpp
tests/vklayertests_buffer_image_memory_sampler.cpp
tests/vklayertests_command.cpp
tests/vklayertests_descriptor_renderpass_framebuffer.cpp
tests/vklayertests_gpu.cpp
tests/vklayertests_others.cpp
tests/vklayertests_pipeline_shader.cpp
tests/vkpositivelayertests.cpp
tests/vkrenderframework.cpp
tests/vkrenderframework.h

Instead of using the blacklist in LunarG CI scripts, move the decision on whether to 
run a test on a particular device into the test itself.

Move device checking from blacklist to the test itself

---

layers/best_practices_utils.cpp
tests/vklayertests_best_practices.cpp

If you get a TIMEOUT, SUBOPTIMAL, or other 'success' code that's not VK_SUCCESS, an INFORMATION-level message will be output instead of a WARNING-level one.
Added tests for Error code and non-success success code.
Fixes #1788.

Fix error text and change non-VK_SUCCESS success code warning to infos

---

tests/layer_validation_tests.cpp
tests/vklayertests_buffer_image_memory_sampler.cpp
tests/vklayertests_descriptor_renderpass_framebuffer.cpp
tests/vklayertests_gpu.cpp
tests/vklayertests_others.cpp

Some tests were using the instance's api_version field which is really the loader version.  Use physical device properties to determine available api version.

Make all tests use the same api version check

---

layers/core_validation.cpp
layers/core_validation.h
layers/parameter_validation_utils.cpp
layers/state_tracker.cpp
layers/state_tracker.h
tests/vklayertests_others.cpp

Adds support for
- VUID-vkGetDeviceQueue-flags-01841
- VUID-VkDeviceQueueCreateInfo-flags-02861
Labeled from unassigned
- VUID-VkDeviceCreateInfo-pNext-00373
Tests using `vkGetDeviceQueue` need Vulkan Loader fix here:
https://github.com/KhronosGroup/Vulkan-Loader/pull/385

Add GetDeviceQueue VUIDs

---

tests/vklayertests_gpu.cpp

For some reason the api version check is still letting the OOBGraphicsShaders test run on NP.
Blacklist the test until we get a chance to investigate

Blacklist Nexus Player in OOBGraphicsShaders

---

layers/generated/vk_safe_struct.cpp
scripts/helper_file_generator.py
tests/vkpositivelayertests.cpp

SafeStructs was copying these regardless, and if these fields were uninitialized the layers could crash.
Fixes #1716.

Ignore queueFamilyCount and pQueueFamilyIndices when sharing mode is EXCLUSIVE

---

tests/vklayertests_gpu.cpp

A recent api check has caused gpu tests to be unnecessarily skipped

Set 1.1 target api for gpu tests

---

layers/buffer_validation.cpp

We can't see layout transfers that occur on a resource while it is owned
by a different instance, so don't validate the initial layout in this
case.
Bug: 1438

Don't validate initial layout on external resource acquire

---

layers/core_validation.cpp
layers/core_validation.h
layers/core_validation_types.h
layers/drawdispatch.cpp
layers/parameter_validation_utils.cpp
layers/state_tracker.cpp
layers/state_tracker.h
layers/vk_layer_utils.h
tests/vklayertests_descriptor_renderpass_framebuffer.cpp

VUID-VkImageCreateInfo-flags-01533
VUID-VkGraphicsPipelineCreateInfo-pDynamicStates-01521
VUID-VkGraphicsPipelineCreateInfo-pDynamicStates-01522
VUID-VkGraphicsPipelineCreateInfo-pDynamicStates-01523
VUID-VkSampleLocationsInfoEXT-sampleLocationsPerPixel-01526 
VUID-VkSampleLocationsInfoEXT-sampleLocationsCount-01527
VUID-vkCmdSetSampleLocationsEXT-sampleLocationsPerPixel-01529
VUID-vkCmdDraw-sampleLocationsEnable-02689

Add VK_EXT_sample_locations VUIDs

---

CMakeLists.txt
build-android/jni/Android.mk
layers/CMakeLists.txt
layers/gpu_utils.cpp
layers/shader_validation.cpp
layers/shader_validation.h
scripts/known_good.json
tests/CMakeLists.txt

Was using a deprecated copy from deep inside the glslang build tree.  With this change, we now install and use a selectable version from known-good.  We have been unequivocally assured from the glslang folks that using TOT will always work for this specific header (spirv.hpp).  Passed internal CI.
Pinging @dj2.
Fixes #1768.

Install SPIRV-Headers for validation layers build

---

layers/core_validation.h
layers/drawdispatch.cpp
layers/generated/parameter_validation.cpp
layers/parameter_validation_utils.cpp
layers/state_tracker.cpp
layers/stateless_validation.h
scripts/parameter_validation_generator.py
tests/vklayertests_command.cpp
tests/vklayertests_pipeline_shader.cpp

- first commit moves out some VUID to stateless parameter validation
- then add VUID-vkCmdDrawIndirectCount-None-02836

Add drawIndirectCount VUIDs

---

layers/buffer_validation.cpp

Fixes crash running dEQP-VK.device_group.sfr with validation

Don't validate QueueFamilyIndices if sharingMode != CONCURRENT

---

layers/core_validation.cpp
layers/core_validation.h
layers/descriptor_sets.cpp

Not every error found in ValidateDescriptorSetBindingData is DescriptorSetNotUpdated.  This is a start at rectifying that by moving the LogErrors into ValidateDescriptorSetBindingData instead of just one in ValidateCmdBufDrawState. Next could be to use better vuid descriptors and / or not aborting on the first error.

Move logging into ValidateDescriptorSetBindingData

---

layers/parameter_validation_utils.cpp
tests/vklayertests_buffer_image_memory_sampler.cpp

Missing test case resulted in crash, added and fixed.
Fixes #1827.

Fixed crash in TYPE_UINT8_EXT feature validation

---

tests/vkrenderframework.cpp
tests/vkrenderframework.h

Fixes #1674, @krOoze, is this what you had in mind?

Correctly use locks in ErrorMonitor constructor

---

.travis.yml

- Turn on CCACHE_COMPRESSION
- Enable ccache for GN builds
For some time, the ccache hit rate in Travis-CI builds has been
very low, often 0 hits per run.
This happens because there is a limit on the ccache size imposed
by Travis-CI and our builds are easily exceeding it, resulting in
severe cache thrashing.
In particular, glslang/spirv-tools are built first, filling up the
cache. Then the rest of the build objects push the glslang/spriv-tools
objects out of the cache, replacing them with their own.
In the next Travis-CI build, the retrieved cache does not contain the
glslang/spirv-tools objects, so they get recompiled and push
the other objects out, continuing the thrashing.
Turning on CCACHE_COMPRESSION lets the entire build fit into the
cache.  This is especially beneficial for the …

travis: Improve ccache efficiency on Travis-CI builds

---

layers/descriptor_sets.cpp

The createInfo copy isn't deep, so use info stored in sampler state.

Fix custom border color check

---

layers/buffer_validation.cpp

A developer ran into this with a large array of attachments and would be nice to help save time and print index out

layers: Add attachment index to message

---

layers/buffer_validation.cpp
layers/core_validation.cpp
layers/core_validation.h
layers/core_validation_types.h
layers/state_tracker.cpp
layers/state_tracker.h
tests/vklayertests_others.cpp

These are new VUIDs added in 1.x.139 header
- VUID-vkGetImageMemoryRequirements-image-04004
- VUID-vkGetBufferMemoryRequirements-buffer-04003
- VUID-VkBufferMemoryRequirementsInfo2-buffer-04005
I also added check for non-null `IMAGE_STATE` in case function calling the `Validate*ANDROID` functions didn't check

Add AHB MemoryReq VUIDs

---

layers/core_validation.cpp
layers/core_validation.h
layers/core_validation_types.h
layers/state_tracker.cpp
tests/vklayertests_pipeline_shader.cpp

Add VUIDs for VK_EXT_pipeline_creation_cache_control
VUID-VkGraphicsPipelineCreateInfo-pipelineCreationCacheControl-02878
VUID-VkComputePipelineCreateInfo-pipelineCreationCacheControl-02875
VUID-VkPipelineCacheCreateInfo-pipelineCreationCacheControl-02892
VUID-VkRayTracingPipelineCreateInfoNV-pipelineCreationCacheControl-02905
VUID-VkRayTracingPipelineCreateInfoKHR-pipelineCreationCacheControl-02905

Validate VK_EXT_pipeline_creation_cache_control

---

layers/core_validation.cpp
layers/parameter_validation_utils.cpp
tests/vklayertests_pipeline_shader.cpp

I went through and added the index of the pipeline in pPipelineCreateInfo to the LogMessage. Ran into this when developer was creating multiple pipelines and error message didn't help narrow down which of the pipelines in the array was the issue

Add index to pipeline log messages

---

layers/core_validation.cpp
tests/vkpositivelayertests.cpp

If query reset was in a command buffer other than the one the BeginQuery was in, validation would report the query as not reset.  Fixes second problem referenced in #1818

Fix false positives in query validation

---

layers/gpu_validation.cpp
tests/layer_validation_tests.cpp
tests/vklayertests_gpu.cpp

vkGetAccelerationStructureMemoryRequirementsNV no longer returns anything other than zero in memoryTypeBits, causing vma to fail to find matching memory.  Just use vmaCreateBuffer instead of create, allocate, bind.  Also re-enable the GPU-AV ray tracing test that was mistakenly disabled.

Fix GPU-AV for RayTracing

---

tests/vklayertests_imageless_framebuffer.cpp

Some devices were failing test due to not supporting D32_S8

Add FindSupportedDepthStencilFormat check

---

layers/state_tracker.cpp

Make sure sampler_state is valid when accessing it.
Fixes #1883

layers: Fix crash in ValidationStateTracker::PreCallRecordDestroySampler

---

layers/core_validation_types.h
layers/state_tracker.cpp

Discussed in #1855 how this seems to be unused and misleading as StateTracker is a per-device object

Remove CB device tracking

---

layers/buffer_validation.cpp
tests/vklayertests_buffer_image_memory_sampler.cpp

VUID-VkImageSubresourceRange-levelCount-01720
VUID-VkImageSubresourceRange-layerCount-01721
The layers were correctly checking, but mislabeling these VUIDs as these are the same regardless of the caller function

Label 01720 and 01721

---

layers/core_validation.cpp
tests/vklayertests_descriptor_renderpass_framebuffer.cpp

Closes #1887 
Reversed modulo logic
Added a test 
```
sample_location_state.sampleLocationsInfo.sampleLocationGridSize.height = multisample_prop.maxSampleLocationGridSize.height / 2;
```
that doesn't expect to find VUID 01522 to match @csmartdalton86 case
> VkPipelineSampleLocationsStateCreateInfoEXT::sampleLocationsInfo::sampleLocationGridSize.height (1) must be be a multiple of VkMultisamplePropertiesEXT::sampleLocationGridSize.height (2)

Fix VK_EXT_sample_locations bug

---

layers/core_validation.cpp
layers/core_validation.h

Started with a few functions and decided to just go through and do a batch fix of many logs that don't have the function prefix. This is useful as I have found from people internally using the tool are not always Vulkan spec experts and seeing the function call that blew things up help save time to find where to triage their issue

Add function name prefix to more logs

---

layers/buffer_validation.cpp
tests/vklayertests_command.cpp

VUID-vkCmdResolveImage-srcImage-01386
While fixing the 01386 message, decided to fix the group of messages near it as well

Label VUID 01386 and fix log messages

---

tests/layer_validation_tests.cpp
tests/layer_validation_tests.h
tests/vklayertests_gpu.cpp

Previously, some BP and GPU tests disabled handle wrapping.

Leave handle wrapping enabled at all times in Layer Validation Tests

---

layers/buffer_validation.cpp
layers/core_validation.cpp
layers/descriptor_sets.cpp
layers/vk_layer_utils.h
tests/vklayertests_descriptor_renderpass_framebuffer.cpp

VUID-VkWriteDescriptorSet-descriptorType-00336
Added a `IsIdentitySwizzle` to help reduce redundancy

Add VUID 00336

---

layers/buffer_validation.cpp
layers/core_validation.cpp
layers/core_validation_types.h
tests/vklayertests_buffer_image_memory_sampler.cpp

As a corner case, it's arguably legal to release/acquire to and from an external queue family within a single command buffer.  As such, validation shouldn't complain.  Fixes #1919

Removing false positive for release/acquire with external queue families

---

layers/core_validation.cpp
layers/core_validation.h
tests/vklayertests_others.cpp

Within a command buffer, cannot have multiple queries created from commandpools with the same queryType.  Adds check and test.
Fixes #1874.

Catch invalid nested CmdBeginQuery[IndexedKHR] calls

---

layers/buffer_validation.cpp
tests/vklayertests_command.cpp

VUID-VkImageResolve-srcImage-00268
VUID-VkImageResolve-srcImage-00271
VUID-VkImageResolve-srcImage-00273 
VUID-VkImageResolve-dstImage-00276
VUID-VkImageResolve-dstImage-00278
I wasn't able to find support on my any local GPUs for a 1D multi-sampled image so `00271` doesn't have a test... I doubt that anyone will actually hit `00271` as not sure who supports multi-sampled 1D images to do the resolve command from

Add VkImageResolve VUIDs

---

BUILD.gn
build-android/jni/Android.mk
layers/CMakeLists.txt
layers/generated/chassis.cpp
layers/generated/chassis.h
layers/vk_layer_settings_ext.h
scripts/layer_chassis_generator.py
tests/layer_validation_tests.cpp
tests/layer_validation_tests.h
tests/vklayertests_best_practices.cpp
tests/vklayertests_others.cpp
tests/vkrenderframework.h

Initial stab at a cross-platform programmatic interface (private extension) allowing arbitrary layer settings to be set, in this case by the layer validation tests.  This could also be used by `VkConfig `to enumerate layer settings in the future.
- This extension provides the `VkInstanceLayerSettingsEXT `struct that can be included in the pNext chain of the `VkInstanceCreateInfo `structure passed as the pCreateInfo parameter of vkCreateInstance.  The structure contains an array of `VkLayerSettingValueEXT `structures that define layer specific settings.
- The extension also provides the `vkEnumerateInstanceLayerSettingsEXT `and `vkEnumerateInstanceLayerSettingInfoEXT `commands, useful for enumerating all layer settings and their possible values, respectively.
See the …

Add Private Settings Layer Extension

---

layers/buffer_validation.cpp
tests/vklayertests_buffer_image_memory_sampler.cpp

Fixed 1 or 2 and decided to a do a pass through and clean up as many as I could find
not sure why clang-format inserts a line break for some of the calls

Add function calls to error log messages

---

layers/core_validation.cpp
tests/vklayertests_buffer_image_memory_sampler.cpp

Same idea as `maxMemoryAllocationCount`
currently have a internal spec fix to add a VUID to both `maxMemoryAllocationCount` and `maxSamplerAllocationCount` which I will update when that is upstreamed

Validate maxSamplerAllocationCount

---

layers/core_validation.cpp
tests/vklayertests_buffer_image_memory_sampler.cpp

Closes #1870 
First commit is to handle issue 1870 and wrap all parts of that rely on the `requirements` to be only if it is not an external AHB memory
From there added 4 VUID related to exporting of external memory
VUID-vkBindBufferMemory-memory-02726
VUID-VkBindBufferMemoryInfo-handleTypes-02791
VUID-vkBindImageMemory-memory-02728
VUID-VkBindImageMemoryInfo-handleTypes-02793

Add export handleType VUIDs

---

layers/core_validation.cpp
layers/core_validation.h
layers/core_validation_types.h
layers/descriptor_sets.cpp
layers/descriptor_sets.h
layers/drawdispatch.cpp
layers/state_tracker.cpp
layers/state_tracker.h
tests/vklayertests_buffer_image_memory_sampler.cpp

Added check to descriptor_sets.cpp and test for the following:
If the VkFilter used to create a VkSampler is not supported
by the VkFormat used to create a VkImageView, the VkSampler
and VkImageView must not be used in the same Combined Image Sampler
descriptor set.
This is part of ongoing work to add additional validation checks for `vkCmdDraw*` commands.

layers: Add combined image sampler check

---

layers/core_validation.cpp
layers/state_tracker.cpp
tests/vklayertests_buffer_image_memory_sampler.cpp
tests/vklayertests_descriptor_renderpass_framebuffer.cpp
tests/vklayertests_pipeline_shader.cpp

The new `Potential Format Features` is now up in the Vulkan spec. This use to only apply to samplers, but was generalized to work for other calls. Here I added VUID around RenderPass creation
VUID-VkSubpassDescription-pInputAttachments-02647
VUID-VkSubpassDescription-pColorAttachments-02648
VUID-VkSubpassDescription-pResolveAttachments-02649
VUID-VkSubpassDescription-pDepthStencilAttachment-02650
VUID-VkSubpassDescription2-pInputAttachments-02897
VUID-VkSubpassDescription2-pColorAttachments-02898
VUID-VkSubpassDescription2-pResolveAttachments-02899
VUID-VkSubpassDescription2-pDepthStencilAttachment-02900

Add RP potentialFormatFeature VUID

---

layers/core_validation.cpp

Validation could croak if this two-part query was only called by the application to retrieve the count but not the images.
i.e., though it seems weird, it's legal to do this:
```
GetSwapchainImages(count, null);
AcquireNextImage(index);
GetSwapchainImages(count, pointer_to_image_array);
```
Wrote a positive test for this case, but it dies on Android consistently and so left it out.  Highlighted this in BP tracking issue #24 (it was already there) to spit out a warning when this happens.
Fixes #1955.

Prevent null pointer access for GetSwapchainImages out-of-order calls

---

CONTRIBUTING.md
layers/generated/chassis.cpp
layers/vk_layer_logging.h
layers/vk_layer_settings.txt
scripts/layer_chassis_generator.py
tests/vklayertests_others.cpp

Adds a new Khronos layer option, `duplicate_message_limit `that allows user control of the number of times a particular validation error is output by the layer.
No setting or a setting of zero (default) corresponds to no limit.  
Also took care of a couple of suggestions in the CONTRIBUTING doc.
Fixes #831.

Add option to limit validation message repetitions

---

layers/drawdispatch.cpp

Fixed mixup between the following VUIDs for vkCmdTraceRaysKHR and
vkCmdTraceRaysIndirectKHR:
`VUID-vkCmdTraceRaysKHR-None-02690` ->
`VUID-vkCmdTraceRaysIndirectKHR-None-02690`
`VUID-vkCmdTraceRaysKHR-None-02692` ->
`VUID-vkCmdTraceRaysIndirectKHR-None-02692`

layers: Fix vkCmdTraceRaysKHR VUID Mixup

---

layers/descriptor_sets.cpp
layers/descriptor_sets.h
layers/generated/chassis.cpp
scripts/layer_chassis_generator.py

`PostCallRecord `steps for `AllocateDescriptorSets `were inadvertently causing redundant state updates, causing false positives.
Modified the `AllocateDescriptorSets `chassis to use a dataset per VO, just as the `CreateXxxPipelines `chassis do.
Fixes #1981.

Fix inadvertent StateTracker validation object state-sharing

---

layers/core_validation.cpp
layers/core_validation.h
layers/core_validation_types.h
layers/state_tracker.cpp
tests/vklayertests_others.cpp

So there are 12 VUIDs being added here all related to checking the `handleType` for the buffer/image when importing external memory
there is one for bindBuffer, bindBuffer2, bindImage, bindImage2
there are then 3 groups of them
- Non-AHB with no extension present
VUID-vkBindBufferMemory-memory-02727
VUID-VkBindBufferMemoryInfo-memory-02792
VUID-vkBindImageMemory-memory-02729
VUID-VkBindImageMemoryInfo-memory-02794
- Non-AHB with extension present
VUID-vkBindBufferMemory-memory-02985
VUID-VkBindBufferMemoryInfo-memory-02987
VUID-vkBindImageMemory-memory-02989
VUID-VkBindImageMemoryInfo-memory-02991
- AHB vuid (due to the way importing handleTypes is different for AHB)
VUID-vkBindBufferMemory-memory-02986
VUID-VkBindBufferMemoryInfo-memory-02988
VUID-vkBindImageMemory-memory-02990 …

Add External Import handleType VUIDs

---

layers/gpu_validation.cpp

Addresses can be sent to shader without descriptor sets

Remove incorrect descriptor set requirement

---

tests/vklayertests_others.cpp

This is my fault, I usually test my PR on my Pixel device and either messed it up and/or forgot with #1963

tests: Fix AHB Test not covering 02251

---

layers/generated/object_tracker.cpp
layers/generated/thread_safety.cpp
layers/generated/thread_safety.h
scripts/object_tracker_generator.py
scripts/thread_safety_generator.py

Each of these validation objects must track active VkDisplayKHR and VkDisplayModeKHR objects, but both have non-standard methods for creating these objects.  Updated threading layer to properly add object creation for these.  Also, suppressed undestroyed object errors for them since there are no methods provided for an application to delete these objects properly.  
Fixes #1660. 
Fixes #1987.

Audit thread_safety and object_tracker for VkDisplayKHR/VkDisplayModeKHR creation and tracking

---

layers/core_validation.cpp
layers/core_validation.h
layers/core_validation_types.h
layers/drawdispatch.cpp
layers/state_tracker.cpp
tests/vklayertests_command.cpp

In process created a common function for [indirect commands](https://github.com/KhronosGroup/Vulkan-Docs/blob/master/chapters/commonvalidity/draw_dispatch_indirect_common.txt) which moved the 02708 and 02709 VUIDs to the DrawDispatchVuid look up table.
Also used `unprotected` for state tracking instead of `protected` due to it being a c++ keyword
Adds:
VUID-vkCmdDrawIndirect-commandBuffer-02711
VUID-vkCmdDispatchIndirect-commandBuffer-02711
VUID-vkCmdDrawIndexedIndirect-commandBuffer-02711
VUID-vkCmdDrawIndirectCount-commandBuffer-02711
VUID-vkCmdDrawIndexedIndirectCount-commandBuffer-02711
VUID-vkCmdTraceRaysIndirectKHR-commandBuffer-02711
VUID-vkCmdDrawMeshTasksIndirectCountNV-commandBuffer-02711
VUID-vkCmdDrawMeshTasksIndirectNV-commandBuffer-02711

Add VUID 02711

---

BUILD.md

Fix BUILD.md common case build instructions. Remove "build" folder prefix.

Update BUILD.md to use correct helper.cmake path

---

layers/buffer_validation.cpp
layers/parameter_validation_utils.cpp

Notices the `sparseResidencyImage` checks were in Stateless, but the `sparseResidencyBuffer` were in CoreCheck. Decided to make it all consistent and move all these stateless sparse checks out of CoreCheck

Move some sparse VU to stateless

---

layers/descriptor_sets.cpp
layers/gpu_utils.cpp
layers/gpu_validation.cpp
tests/layers/device_profile_api.cpp
tests/layers/vk_lunarg_device_profile_api_layer.h
tests/vklayertests_gpu.cpp

Also needed to fix a test that uses the lack of stores and atomics to get GPU-AV to abort

Fix stores and atomics feature enabling in GPU-AV

---

layers/buffer_validation.cpp
tests/vklayertests_buffer_image_memory_sampler.cpp

Restrict VkBufferViewCreateInfo with VK_WHOLE_SIZE maxTexelBufferElements.

Add Validation for VU 04059

---

layers/subresource_adapter.h

The warning -Wnon-virtual-dtor catches the following error:
'subresource_adapter::AspectParameters' has virtual functions but
non-virtual destruct
This adds a (empty) virtual dtor.

build: Add a virtual dtor to AspectParameters

---

layers/buffer_validation.cpp
layers/core_validation.cpp
layers/core_validation_types.h
layers/state_tracker.cpp
tests/vklayertests_others.cpp

Addresses some of #1996 
VUID-VkCommandPoolCreateInfo-flags-02860
VUID-VkBufferCreateInfo-flags-01887
VUID-VkImageCreateInfo-flags-01890
VUID-VkBufferCreateInfo-None-01888
VUID-VkImageCreateInfo-None-01891
VUID-vkBindBufferMemory-None-01898
VUID-vkBindBufferMemory-None-01899
VUID-vkBindImageMemory-None-01901
VUID-vkBindImageMemory-None-01902
VUID-VkMemoryAllocateInfo-memoryTypeIndex-01872

Add Protected Resource VUIDs

---

scripts/update_deps.py

We see spurious failures to connect to github when trying to
run update_deps.py (up to 7% of runs, depending on the machine).
This is an annoyance when running by hand, but a headache and
a serious resource waste when running in automation (as a single
broken "git clone" or "git fetch" can cause the whole run to fail).
These changes allow update_deps.py to automatically retry
"git fetch" and "git clone" operations on failure.
These changes will be duplicated in follow-on PRs to the
other repositories that include "update_deps.py", to keep
them all in sync.  These are KhronosGroup/Vulkan-Tools,
KhronosGroup/Vulkan-Loader, LunarG/VulkanSamples, and
LunarG/VulkanTools.
I'm also including a "technical debt" update here, because
VulkanTools/scripts/update_deps.py had diverged from the other …

scripts: update_deps retry on clone or fetch failure

---

layers/synchronization_validation.cpp
tests/vklayertests_buffer_image_memory_sampler.cpp

Fix assert in final layout transitions and add test that final layout transitions correctly run
Fix -Wrange-loop-construct range variable copy warning

Bugfix PR Fix assert and test gap for attachment final layout transitions and warnings fix.

---

tests/layer_validation_tests.cpp

In CI, the dialog causes the test to time out and future runs to fail.

Avoid "abort, retry, ignore" dialog boxes when running tests

---

layers/buffer_validation.cpp
layers/core_validation.cpp
layers/core_validation.h
tests/vklayertests_others.cpp

Validation was incorrectly limiting these to queue families supported by the device.
Fixes #317.

Allow queue families supported by physical device to be used for SHARING_MODE_CONCURRENT

---

layers/core_validation.cpp
layers/state_tracker.cpp
tests/vklayertests_others.cpp
tests/vkpositivelayertests.cpp

closes #2004
The first commit is a need dependency that removes
`VUID-vkGetBufferMemoryRequirements-buffer-04003`
`VUID-VkBufferMemoryRequirementsInfo2-buffer-04005`
From internal Vulkan MR 3982, it was decided these should never have been added (and will be gone in a future header now). I have written positive tests to prevent regression
Added positive test to check for export AHB from both a `vkBuffer` and `vkImage` which caught the issue reported in #2004 from calling `ValidateInsertImageMemoryRange()` when it is an export `VkImage` AHB and `allocationSize` is suppose to be `0`

Fixes to AHB VUs and Tests

---

tests/vkpositivelayertests.cpp

This test wasn't actually testing what it claimed because the
push-constant block was being optimized away.
Change-Id: Iecb599ee1f0d7d6bc17ee843a1a7d2d3a201643f

tests: Fix push-constant test

---

LAYER_CONFIGURATION.md

- Make more visible Vulkan Configurator
- Show visually that Layers configuration is not either by vkconfig or env vars

doc: Highlight Vulkan Configurator

---

CMakeLists.txt
layers/generated/spirv_tools_commit_id.h
scripts/known_good.json

KhronosGroup/glslang@b8c3386ec00b9de2925732c0a29c588d60f8c8fd split up
the glslang static library and resulted in some dependency cycles
between the new libraries that the Linux linker could not handle
properly. This change tells CMake about the imported static library
target dependencies via INTERFACE_LINK_LIBRARIES so it can invoke the
linker correctly on Linux. This was also a good opportunity to move
duplicated CMake code for importing the glslang libs into a common loop.
1.2.148 SDK glslang known-good update.
All changes passed internal CI on the latest master.

build: Handle glslang static lib dependency cycles

---

layers/synchronization_validation.cpp
layers/synchronization_validation.h
tests/vklayertests_buffer_image_memory_sampler.cpp

Update  the hazard model to reflect raster ordering rules for
input attachments, and enforce "most recent" hazard checking rule for
barrier ordered reads.  Caused false positives in CTS with matching incorrect unit test.
Update incorrect unit test.
Design document update to follow in subsequent PR.

Update ordering/most recent hazard checks

---

layers/debug_printf.cpp
layers/gpu_validation.cpp
layers/shader_validation.cpp
layers/shader_validation.h

The optimizer in spirv tools is used to instrument shaders for debug printf or gpu assisted validation.  Before it does that, it validates the shader and returns false if the shader fails.  Certain extensions relax requirements and can allow a shader to do things that are illegal without the extension.  This code sets the proper validator settings so that shaders don't fail validation when using valid extensions,  It also consolidates the validator setting code into a central location.

Fix validator settings for GPU-AV instrumentation

---

layers/core_validation.cpp

This fix is to allow KHR extension as well as core 1.2 feature flag for timeline semaphore support in validation layer.
Without this fix, the validation layer only checks the feature flag, and any attempt to use the KHR extension for timeline semaphore is treated as a validation error.

Allow KHR extension for timeline semaphore

---

docs/synchronization_usage.md
layers/subresource_adapter.cpp
layers/synchronization_validation.cpp

1. fixed log message.
2. Used floor instead of ceil. If using ceil to calculate memory address, it might be out of the memory size.

Syncval alpha sdk patch

---

layers/core_validation.cpp
layers/core_validation.h
tests/vklayertests_command.cpp

Addresses part of #1996
VUID-vkCmdBeginQuery-commandBuffer-01885
VUID-vkCmdBeginQueryIndexedEXT-commandBuffer-01885
VUID-vkCmdEndQuery-commandBuffer-01886
VUID-vkCmdEndQueryIndexedEXT-commandBuffer-02344
Also added `ValidateEndQueryVuids` to match how `ValidateBeginQueryVuids` grouped VUs

Add query protected memory VUID

---

layers/buffer_validation.cpp
layers/core_validation.cpp
layers/core_validation.h
tests/vklayertests_command.cpp

Addresses part of #1996
VUID-vkCmdBlitImage-commandBuffer-01834
VUID-vkCmdBlitImage-commandBuffer-01835
VUID-vkCmdBlitImage-commandBuffer-01836
VUID-vkCmdClearColorImage-commandBuffer-01805
VUID-vkCmdClearColorImage-commandBuffer-01806
VUID-vkCmdClearDepthStencilImage-commandBuffer-01807
VUID-vkCmdClearDepthStencilImage-commandBuffer-01808
VUID-vkCmdCopyBuffer-commandBuffer-01822
VUID-vkCmdCopyBuffer-commandBuffer-01823
VUID-vkCmdCopyBuffer-commandBuffer-01824
VUID-vkCmdCopyBufferToImage-commandBuffer-01828
VUID-vkCmdCopyBufferToImage-commandBuffer-01829
VUID-vkCmdCopyBufferToImage-commandBuffer-01830
VUID-vkCmdCopyImage-commandBuffer-01825
VUID-vkCmdCopyImage-commandBuffer-01826
VUID-vkCmdCopyImage-commandBuffer-01827
VUID-vkCmdCopyImageToBuffer-commandBuffer-01831 …

Add protected resource in commands

---

layers/buffer_validation.cpp
tests/vklayertests_command.cpp

Follow same sub-resource size logic as mainly vkCmdCopyImage since its image-to-image
VUID-VkImageResolve-dstOffset-00274
VUID-VkImageResolve-dstOffset-00275
VUID-VkImageResolve-dstOffset-00277
VUID-VkImageResolve-srcOffset-00269
VUID-VkImageResolve-srcOffset-00270
VUID-VkImageResolve-srcOffset-00272

Add vkCmdResolveImage size VUIDs

---

tests/layer_validation_tests.cpp

It turns out Windows has a separate mechanism for pretty much anything
that can cause a test to fail.  Without these changes, there are still
a class of errors that can cause a broken test to hang, which wreaks
havoc with CI testing.
With these changes, the same commits that were causing trouble last
week now will issue messages to stderr and will exit, which
allows the error process to finish more quickly (~11 minutes, instead
of a timeout at 45), provides useful information as to what went
wrong, and (most importantly) doesn't leave a hung process on
the test system that can interfere with future test jobs.

tests: avoid more dialog boxes

---

layers/core_validation.cpp
tests/vklayertests_buffer_image_memory_sampler.cpp

Implemented validation VUID-VkSwapchainCreateInfoKHR-imageFormat-01778. 
_The implied image creation parameters of the swapchain must be supported as reported by vkGetPhysicalDeviceImageFormatProperties_
Also added test for this VUID. Test is running vkCreateSwapchainKHR with imageUsage and imageFormat params, that meet GetPhysicalDeviceSurfaceCapabilitiesKHR capabilities, but confirmed to fail vkGetPhysicalDeviceImageFormatProperties function. Not trying to make it fail with imageArrayLayers or imageExtent params, since I wasn't able to get right values for that in my setup.
Partially used code from https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/496 pull request that was adding same VUID, but hasn't been merged ever since, and outdated a bit.
In Mesa we already had several …

Add VUID 01778

---

layers/generated/layer_chassis_dispatch.cpp
scripts/layer_chassis_dispatch_generator.py
tests/vklayertests_others.cpp

Dispatcher codegen was unaware of these object handles and neglected to unwrap them, causing crashes when used with handle wrapping enabled.  Moved to manually generated and unwrapped the handles.  Also added a test.
Fixes #2082.

Unwrap generic object handles in Get/SetPrivateDataEXT calls

---

layers/state_tracker.cpp

00683 only applies if the memory was allocated on >1 device

Fix check for 00683

---

layers/core_validation.cpp
layers/core_validation.h
layers/core_validation_types.h
layers/descriptor_sets.cpp
layers/drawdispatch.cpp
layers/shader_validation.cpp
layers/state_tracker.cpp
tests/layer_validation_tests.cpp
tests/layer_validation_tests.h
tests/vklayertests_command.cpp

#135 
```
VUID-vkCmdDraw-None-02691
VUID-vkCmdDrawIndexed-None-02691
VUID-vkCmdDrawIndirect-None-02691
VUID-vkCmdDrawIndirectCount-None-02691
VUID-vkCmdDrawIndexedIndirect-None-02691
VUID-vkCmdDrawIndexedIndirectCount-None-02691
VUID-vkCmdDrawIndirectByteCountEXT-None-02691
VUID-vkCmdDrawMeshTasksNV-None-02691
VUID-vkCmdDrawMeshTasksIndirectNV-None-02691
VUID-vkCmdDrawMeshTasksIndirectCountNV-None-02691
VUID-vkCmdDispatch-None-02691
VUID-vkCmdDispatchIndirect-None-02691
VUID-vkCmdTraceRaysNV-None-02691
VUID-vkCmdTraceRaysKHR-None-02691
VUID-vkCmdTraceRaysIndirectKHR-None-02691
VUID-vkCmdDispatchBase-None-02691 vkCmdDispatchBaseKHR
If a VkImageView is accessed using atomic operations as a result of this command, then the image view’s format features must contain …
```

If image view do atomic operations, the format MUST support VK_FORMAT_FEATURE_STORAGE_IMAGE_ATOMIC_BIT

---

layers/shader_validation.cpp

has_writable_descriptor is for the whole shader, not for a single descriptor.
@Tony-LunarG

layers: Fix has_writable_descriptor

---

layers/buffer_validation.cpp
layers/core_validation.cpp
layers/core_validation.h
layers/core_validation_types.h
layers/descriptor_sets.cpp
layers/descriptor_sets.h
layers/drawdispatch.cpp
layers/state_tracker.cpp
layers/state_tracker.h
tests/vklayertests_command.cpp
tests/vklayertests_descriptor_renderpass_framebuffer.cpp
tests/vkrenderframework.h

```
VUID-vkCmdDraw-None-02698
VUID-vkCmdDrawIndexed-None-02698
VUID-vkCmdDrawIndirect-None-02698
VUID-vkCmdDrawIndirectCount-None-02698
VUID-vkCmdDrawIndexedIndirect-None-02698
VUID-vkCmdDrawIndexedIndirectCount-None-02698
VUID-vkCmdDrawIndirectByteCountEXT-None-02698
VUID-vkCmdDrawMeshTasksNV-None-02698
VUID-vkCmdDrawMeshTasksIndirectNV-None-02698
VUID-vkCmdDrawMeshTasksIndirectCountNV-None-02698
VUID-vkCmdDispatch-None-02698
VUID-vkCmdDispatchIndirect-None-02698
VUID-vkCmdDispatchBase-None-02698
VUID-vkCmdExecuteGeneratedCommandsNV-None-02698
VUID-vkCmdTraceRaysNV-None-02698
VUID-vkCmdTraceRaysKHR-None-02698
VUID-vkCmdTraceRaysIndirectKHR-None-02698
For each push constant that is statically used by the VkPipeline bound to the pipeline bind point used by this command, a push constant …
```

Validate if push constants doesn't update and image subresources are used in attachments and descriptor sets

---

layers/descriptor_sets.cpp
tests/vklayertests_buffer_image_memory_sampler.cpp

I have a spec fix to add the 2 unassigned VUID label which should be ready when 1.2.152 gets merged in the future
There are 2 fixes here
1. Add `VK_DESCRIPTOR_TYPE_INPUT_ATTACHMENT` to being checked for image layouts
2. replace the `image_node->shared_presentable` check with `device_extensions.vk_khr_shared_presentable_image` as this part of the function is only checking the given image layouts are valid
currently
> VK_IMAGE_LAYOUT_SHARED_PRESENT_KHR is valid only for shared presentable images, and must be used for any usage the image supports.
is not a proper VU and needs to be added to the spec and check regardless of the descriptor type (as in it was currently only checked in `case VK_DESCRIPTOR_TYPE_STORAGE_IMAGE:` in the removed code)

layers: Fix Descriptor ImageLayout check

---

layers/generated/parameter_validation.cpp
layers/parameter_validation_utils.cpp
layers/stateless_validation.h
scripts/parameter_validation_generator.py
tests/vklayertests_descriptor_renderpass_framebuffer.cpp
tests/vklayertests_others.cpp
tests/vklayertests_pipeline_shader.cpp
tests/vkpositivelayertests.cpp

Some extensions contain structs that must not be used unless their extension is enabled, but can be used with other enabled-extension or core APIs.  This PR adds validation to version-check those structures.
The additional checks found several errors in the validation tests which are corrected as part of this PR as well, and new tests are added.
Fixes #1990.

Add pNext-struct version checking

---

layers/buffer_validation.cpp
layers/core_validation.cpp
tests/vklayertests_descriptor_renderpass_framebuffer.cpp

#2125 Fixed VUID-vkCmdDraw-None-02687 false positive.
Original it checked if (base0 < base1 && base0 + count0 >= base1), it returned TRUE, overlapping.  But it should be (base0 < base1 && base0 + count0 > base1).
But another big wrong is that the original code did that if either of layer or mip overlapped, it returned TRUE. But the correct is that both have to overlap, it overlap.

Fix wrong overlap image subresources check

---

layers/best_practices_utils.cpp
layers/core_validation.h
layers/core_validation_types.h
layers/shader_validation.cpp
layers/shader_validation.h
layers/state_tracker.cpp
tests/vklayertests_pipeline_shader.cpp

If a shader stage has a writable descriptor or a atomic descriptor, it should check if vertexPipelineStoresAndAtomics or fragmentStoresAndAtomics enable.
It original only checked has_writable_descriptors. Now add  checking has_atomic_descriptors.

Add has_atomic_descriptors to check if vertexPipelineStoresAndAtomics & fragmentStoresAndAtomics eanble

---

layers/core_validation.cpp
layers/core_validation.h

Was playing around with VK_KHR_timeline_semaphore and realized some of the error messages were less than desired to figure out the issue. Fixed up the vkQueueSubmit and vkQueueBindSparse messages to be more useful

layers: Better timeline semaphore error messages

---

BUILD.gn
layers/vk_layer_extension_utils.cpp

These missing dependencies were picked up by an automatic check in
ANGLE. They should fix some edge cases with incremental builds.

GN: Fix header dependencies.

---

layers/subresource_adapter.cpp

Fix the mip level size/offset computation that drive range computation for synchronization image operations.  Fixes #2093.

Fix range computation for 3D images

---

layers/core_validation.cpp
layers/core_validation_types.h
layers/shader_validation.cpp
layers/shader_validation.h
layers/state_tracker.cpp
tests/vklayertests_command.cpp

A bug fix for 
VUID-vkCmdDraw-None-02698
For each push constant that is statically used by the VkPipeline bound to the pipeline bind point used by this command, a push constant value must have been set for the same pipeline bind point, with a VkPipelineLayout that is compatible for push constants, with the VkPipelineLayout used to create the current VkPipeline, as described in Pipeline Layout Compatibility
The original code checked if every byte of push constants is updated. The fix added that only checked if the byte is used in shaders.
And get more accurate data size of push constants. Consider array, vector, matrix, and scalar type.

Check what bytes of push constants are used in shader

---

docs/synchronization_usage.md
layers/layer_options.cpp
layers/layer_options.h
layers/vk_layer_settings.txt
tests/layer_validation_tests.cpp
tests/layer_validation_tests.h

Add the VkValidationFeatureEnableEXT VK_VALIDATION_FEATURE_ENABLE_SYNCHRONIZATION_VALIDATION_EXT enabling
support to the Khronos validation layer.

Add extension enable support for sync val

---

build-android/test_APK.sh
layers/generated/parameter_validation.cpp
layers/parameter_validation_utils.cpp
layers/stateless_validation.h
scripts/parameter_validation_generator.py
tests/vklayertests_others.cpp

Many device extensions implement structures which can be valid as part of pNext chains _before_ a logical device is created and the extensions enabled.  This PR allows those structures, fixing false positives in CTS test runs.
*Also fixed an issue where Android log info was trunctated/incomplete when running the Android LVTs.
[Passed internal CI.](http://erusea:8080/job/Gerrit-ValidationLayers/3391/)

Allow use of supported device extension structures before enabling extensions

---

layers/core_validation.cpp
layers/core_validation_types.h
tests/vklayertests_descriptor_renderpass_framebuffer.cpp

This goes back to pull request https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/2080 where I originally added renderpass compatibility checks and tests for FDM and Multiview use. I wasn't previously aware that the Multiview now had the viewMask parameter directly in Vulkan 1.2 structs and no longer required the MultiviewCreateInfo struct to be attached through pNext. Only after I made these changes did I realize that this was addressed in this commit: https://github.com/KhronosGroup/Vulkan-ValidationLayers/commit/799a92b2f344c46f9d3495298148974a2504b930. Still, I present a solution for the check that shouldn't require the extra multiview_supported, my_view_offsets and my_view_masks parameters needed there and I've made the Multiview test more complete by incorporating the …

Modify renderpass compatibility Multiview check to work for Vulkan 1.2

---

layers/drawdispatch.cpp
layers/parameter_validation_utils.cpp
layers/stateless_validation.h

I ran into one of these (the null descriptor message) and grep found a few more. When using the `PRIu64` etc specifiers they don't include the prefixing `%` so if it's accidentally omitted all you'll get is `llu` instead of the actual value in the resulting message.

layers: Add a couple of missing % to printf specifiers

---

layers/generated/parameter_validation.cpp
layers/parameter_validation_utils.cpp
layers/stateless_validation.h
scripts/parameter_validation_generator.py

From internal issue 2326
Agreed in working group that it is indeed valid to have a `vertexCount` and `instanceCount` of zero. There is also already a best practice layer that checks for `instanceCount` of zero
This PR was fueled by the "start labeling unassigned VUs" effort

layers: Removed incorrect vkCmdDraw warnings

---

layers/synchronization_validation.cpp

Add write-after-write supression for general buffer descriptors.
@ShabbyX -- fixes an additional class of angle test false positives (WRITE-AFTER-WRITE)

Add missing WAW suppression

---

layers/core_validation.cpp
layers/core_validation.h

This was left over from the XGL days, and the validation layer is not the right place.  May add to best practices #24.

Remove memory shadow copies

---

tests/vkpositivelayertests.cpp

The `ToolingExtension` doesn't seem to work on `--devsim`

tests: ToolingExtension devsim check

---

tests/vklayertests_others.cpp

Protected memory was introduced in 1.1 and all protected memory test should have this check (I think I forgot this in a previous PR when added this test)

tests: DisabledProtectedMemory 1.1 check

---

layers/stateless_validation.h

Adds the function call to the error message of all `vkCreateRenderPass[2]` calls in the stateless validation

layers: Add function name to renderpass stateless

---

layers/debug_printf.cpp
layers/gpu_utils.h
layers/gpu_validation.cpp

State tracker cleans up leftover command buffers and can make vma and descriptor set manager
calls, so don't destroy or reset those until after state tracker has finished.

Move vma allocator destroy to after state tracker

---

docs/synchronization_usage.md

Add material from quick start into synchronization validation usage
documentation updated to reflect latest vkconfig changes.
@tobine -- do you have anything you like to suggest for Android in the quickstart...

Integrate quick start into usage doc

---

layers/core_validation_types.h
layers/state_tracker.cpp
layers/synchronization_validation.cpp
layers/synchronization_validation.h

Add support to correctly allow for multiple VKSubpassDependency structures between the same srcSubpass/dstSubpass pair.  This is a first pass fix for #2088 . It quashes false positives but is somewhat too generous (taking the union of the `src*Mask` and `dst*Mask` fields, which can generate unintended implied barrier effects, relative to treating the VkSubpassDependency's definitions as fully independent.  
Exact fix will take some detailed changes that will need careful testing.

Add multi subpass dependency support

---

BUILD.gn

layers/generated/thread_safety.h was being included twice. This was
causing the Visual Studio project generated with GN to fail to load.
PTAL
@timvpGoogle FYI

layers: Fix duplicate header in GN build.

---

layers/core_validation.cpp

The [Renderpass Compatibility Rules](https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#renderpass-compatibility) require that for two renderpass to be compatible, they must be identical (with special compatibility rules for the attachments, and certain other enumerated exceptions).
> Two render passes are compatible if their corresponding color, input, resolve, and depth/stencil attachment references are compatible **and if they are otherwise identical** except for...
This change specifically adds a check that the VkRenderPassCreateFlags must be identical for the renderpasses to be compatible.

Add fix for renderpass compatibility

---

layers/debug_printf.cpp
layers/debug_printf.h
layers/generated/chassis.h
layers/gpu_validation.cpp
layers/gpu_validation.h
scripts/layer_chassis_generator.py

Unlike the other 'special' chassis APIs, `PreCallRecordCreateDevice `didn't use a `void*` -- changed for consistency.

Change CreateDevice special parameter from safe_VkDeviceCreateInfo* to void*

---

layers/generated/chassis.cpp
scripts/layer_chassis_generator.py

Fixes #2193 by adding `SyncValidator` objects to the existing list of validation objects to free.

Fix validation object leaks

---

layers/best_practices_utils.cpp
layers/best_practices_validation.h
layers/core_validation.cpp
layers/core_validation_types.h
layers/generated/best_practices.cpp
layers/state_tracker.cpp
layers/state_tracker.h
scripts/best_practices_generator.py

Move CALL_STATE enum and associated checks outside of core_validation
and into best_practices.
Change-Id: Id842fe45f32feae73333f5bfbc20d6cf10878d02

refactor: Move CALL_STATE into best_practices

---

layers/buffer_validation.cpp
tests/vklayertests_buffer_image_memory_sampler.cpp

Fixes errors incorrectly getting triggered when an ImageView is created
with a different format from the Image, but the Image was created with
VK_IMAGE_CREATE_BLOCK_TEXEL_VIEW_COMPATIBLE_BIT_KHR set.
This fixes issue
https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/2203.
Change-Id: Iae069157d0195105353baa75792a3242e404bd13

layers: Fix ImageView format compatibility error

---

layers/generated/layer_chassis_dispatch.cpp
scripts/layer_chassis_dispatch_generator.py

The `BeginCommandBuffer `API has a VU that says if the CB wasn't allocated with `SECONDARY `that the `pInheritanceInfo `pointer must be ignored.  The dispatcher made a deep copy of this regardless, causing crashes for invalid `pInheritanceInfo `pointers.  Added CB tracking code in the dispatcher to keep a map of secondary CBs so `BeginCommandBuffer `dispatch will know when to avoid wrapping those objects.
This means that AllocateCommandBuffers, FreeCommandBuffers, DestroyCommandPool, and BeginCommandBuffer move from being autogenerated to manually generated.
Now, nearly every single thing in the world will just crash in the graphics driver.

Track secondary command buffers in dispatcher (handle-wrapping)

---

layers/core_validation.cpp

The depth/stencil resolve attachment in a render pass does not need to
have the same format as the depth/stencil attachment. The only
restriction is that if the resolve attachment has a depth or stencil
aspect, it must match in format and size with the depth/stencil
attachment.
This means the resolve attachment is free to remove image aspects (depth
or stencil) but not to add them. However, the layers were incorrectly
reporting errors when the resolve attachment did not have one of the two
aspects and the depth/stencil attachment did.
Fixes #2212

layers: Fix depth/stencil resolve false positives

---

layers/parameter_validation_utils.cpp
tests/vkpositivelayertests.cpp

Added fix and test for an issue where, if the multiViewport feature was not enabled, bad messages were generated when using dynamic viewport/scissor states.
Fixes #2224.

Fix bad interaction with Dynamic_viewport_with_count and multiViewport feature disabled

---

layers/core_validation.cpp
layers/core_validation.h
layers/state_tracker.cpp
layers/state_tracker.h
tests/vklayertests_others.cpp

~~Added WIP tag, waiting to hear back about [gitlab issue#2380](https://gitlab.khronos.org/vulkan/vulkan/-/issues/2380).~~
Issue is approved, a stride test will be added in a follow-on PR when the new VU appears in the header.
Added some stride/datasize checks to `GetQueryPoolResults`, a check or to to `CmdQueryPoolResults`, fixed a bug or two and removed some dead code.  Added tests.  
Fixes #2029.
[Passed internal CI](http://erusea:4040/#/c/7306/).

Expand vkGetQueryPoolResults/vkCmdCopyQueryPoolResults validation

---

layers/core_validation.cpp
layers/core_validation_types.h
tests/vklayertests_descriptor_renderpass_framebuffer.cpp

Fixed https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/2171
It removed checking if subpass sets input index, but shader doesn't do it. It only checks if shader sets input index, but sbupass doesn't setup it or VK_ATTACHMENT_UNUSED.

Fixed VUID-02686 bug

---

layers/stateless_validation.h
tests/vklayertests_others.cpp

Explicitly stated in the spec (thanks @Tony-LunarG!):
> Applications must not pass any other values than VK_TRUE or VK_FALSE into a Vulkan implementation where a VkBool32 is expected.
These are errors, still listed as warnings for some reason.

Changed stateless validaton VkBool32 variable checks from warnings to errors

---

layers/core_validation.cpp
layers/core_validation.h
layers/core_validation_types.h
layers/drawdispatch.cpp
layers/shader_validation.cpp
layers/shader_validation.h
layers/state_tracker.cpp
tests/vklayertests_command.cpp
tests/vklayertests_pipeline_shader.cpp

1) In CreateShaderModule, analyze shader code to get declarations of push constants, and then check if they are used in functions. SHADER_MODULE_STATE has a struct to save this result.
2) In Create*Pipeline, validate if push constant range of pipeline layout matches the struct in SHADER_MODULE_STATE.
3) In CmdPushConstants, record what byte of push constant is updated.
4)  In CmdDraw, validate if push constant that is used in shader is updated or match pipelline layouts' push constants range
It doesn't consider **Specialization Constants** situation.
Implements part of #135

[WIP] Validate if push constant buffer is updated

---

tests/layer_validation_tests.cpp
tests/vkrenderframework.cpp

Updating my clang to version 10 displayed the follow warnings on build
```
loop variable ... creates a copy from type
const std::__cxx11::basic_string<char> [-Wrange-loop-construct]
```

tests: Remove clang 10 warning for string copy

---

layers/buffer_validation.cpp
tests/vklayertests_command.cpp

- `VUID-VkCopyBufferToImageInfo2KHR-commandBuffer-04477`
- `VUID-vkCmdCopyBufferToImage-commandBuffer-04477`
moved to `ValidateCmdCopyBufferToImage` since its only for buffer to image, not image to buffer

layers: Label VUID 04477

---

layers/core_validation.cpp
layers/core_validation.h
layers/core_validation_types.h
layers/shader_validation.cpp
tests/vklayertests_descriptor_renderpass_framebuffer.cpp

https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/2243
VUID-vkCmdDraw-None-02686
Every input attachment used by the current subpass must be bound to the pipeline via a descriptor set
I made a mistake between input attachment index and attachment index, so it causes false positive. But it seems nothing need to do for 02686.
Verify if input attachment index matches between shader and subpass that have done in kVUID_Core_Shader_MissingInputAttachment, so removed VUID-02686.
Plus, verify if descriptor slot matches between shader and descriptorSet layout have done in VUID-VkGraphicsPipelineCreateInfo-layout-00756.
Verify if descriptorSet is updated that have done, too.

Remove vuid 02686

---

layers/descriptor_sets.cpp

VUID-VkDescriptorImageInfo-sampler-01564 only applies if the sampler is
"used", and "sampler is a sampler handle, and is used [...]
if the binding being updated does not use immutable samplers." So if the
binding uses immutable samplers then the VU should not apply.
This reverts commit 95d480bbab0a7633520d82cea385f7a464e25e9a.

Revert "layers: Fix wrong if statement"

---

layers/core_validation.cpp
layers/core_validation.h
layers/core_validation_error_enums.h
layers/core_validation_types.h
layers/drawdispatch.cpp
layers/state_tracker.cpp
layers/state_tracker.h
tests/vklayertests_command.cpp
tests/vklayertests_descriptor_renderpass_framebuffer.cpp

VUID-vkCmdDrawIndexed-None-02721
For a given vertex buffer binding, any attribute data fetched must be entirely contained within the corresponding vertex buffer binding, as described in Vertex Input Description
1) Changed kVUID_Core_DrawState_InvalidVtxAttributeAlignment into VUID-02721
2) Print a message when vertex input binding doesn't match with the binding in VkVertexInputAttributeDescription

VUID-02721 validate vertex binding & VUID-02859 validate dynamic state setting commands.

---

layers/buffer_validation.cpp
layers/core_validation.cpp
layers/core_validation.h
layers/core_validation_types.h
layers/descriptor_sets.cpp
layers/shader_validation.cpp
layers/state_tracker.cpp

The index of Images or Samplers in shader might not be a constant. Skip it if the index is not a constant.
This bug fix is related to 
VUID-vkCmdTraceRaysIndirectKHR-None-02702
If the VkPipeline object bound to the pipeline bind point used by this command accesses a VkSampler object that uses unnormalized coordinates, that sampler must not be used to sample from any VkImage with a VkImageView of the type VK_IMAGE_VIEW_TYPE_3D, VK_IMAGE_VIEW_TYPE_CUBE, VK_IMAGE_VIEW_TYPE_1D_ARRAY, VK_IMAGE_VIEW_TYPE_2D_ARRAY or VK_IMAGE_VIEW_TYPE_CUBE_ARRAY, in any shader stage.

Some bug fixed for shader validation and perf improvement

---

layers/buffer_validation.cpp
tests/vklayertests_command.cpp

Addresses part of #2235
The first commit is to remove redundant check
- `VUID-VkClearAttachment-aspectMask-requiredbitmask`
- `VUID-VkClearAttachment-aspectMask-parameter`
second commit adds tests to confirm they are still being properly checked in the generated code
third commit labels `VUID-VkBufferImageCopy2KHR-aspectMask-00212`

Remove redundant implicit VU checks

---

layers/generated/object_tracker.h
layers/generated/thread_safety.cpp
layers/generated/thread_safety.h
layers/object_tracker_utils.cpp
scripts/object_tracker_generator.py
scripts/thread_safety_generator.py
tests/vkpositivelayertests.cpp

`vkGetPhysicalDeviceDisplayPlaneProperties[2]KHR` is yet another API that can create `VkDIsplayKHR `objects.  This object creation was missed by the thread safety and object lifetime validation, resulting in crashes or false-positive errors when using these objects.
Also added positive test.
Fixes #2221.  
Fixes #2222.

Close another VkDisplayKHR creation hole

---

layers/buffer_validation.cpp
layers/image_layout_map.cpp
layers/image_layout_map.h

Loop through intervals instead of subresources in an attempt
to improve performance, specifically of a trace of Counter-Strike

Tune image layout loop

---

layers/buffer_validation.cpp
layers/core_validation.cpp
tests/vklayertests_command.cpp
tests/vklayertests_descriptor_renderpass_framebuffer.cpp

Address part of #2235
- VUID-VkClearAttachment-aspectMask-02246
- VUID-VkImageSubresourceLayers-aspectMask-02247
- VUID-VkInputAttachmentAspectReference-aspectMask-02250
Fixed up labeling on `VUID-VkClearAttachment-aspectMask-00020`
The `UNASSIGNED-VkSubpassDescription2-attachment` was brought up my me in an internal WG meeting and just waiting for it to propagate through, will update when it lands in a header update

Add drm format aspect planes

---

layers/descriptor_sets.cpp
layers/drawdispatch.cpp
tests/vklayertests_buffer_image_memory_sampler.cpp

The last few VUIDs that needed to be reconciled for the 158 header.
Passed internal CI.
Will be squashed into one commit

build: Reconcile final 158 VUID inconsistencies

---

layers/core_validation.cpp
layers/core_validation.h
tests/layer_validation_tests.cpp
tests/layer_validation_tests.h
tests/vklayertests_descriptor_renderpass_framebuffer.cpp

This is to address
https://github.com/KhronosGroup/Vulkan-Docs/issues/1378
There is an internal MR 4163 that will probably update the VUID names later, or as I purposed maybe just removing all of these due to the fact `VUID-VkSubpassDescription2-None-04439` or `VUID-VkRenderPassCreateInfo2-attachment-02525` are needed for ALL the tests for any `VUID-VkAttachmentReference2-attachment-*` VU
The spec fixes will probably be a while to propagate, but ultimately, the current validation layers are incorrectly checking for non-input attachments and was agreed in a WG call that it should be only for input attachments. With this, this change should hopefully resolve that

Description of VkAttachmentReference2 contradicts the Valid Usage of aspectMask

---

layers/drawdispatch.cpp
layers/parameter_validation_utils.cpp
tests/vklayertests_command.cpp

These were just recently removed by accident in
https://github.com/KhronosGroup/Vulkan-ValidationLayers/commit/c505df6e9978052e184dbbd9b0183d208841797b#diff-e8d5d9f968d7cedb9e742c3ad9251260f6dfb15c79d9feea206df88d17e42061
I realize the issue was they weren't real VUs, so understand, but luckily I have the proper VUs for them
I would also point out to @mark-lunarg that the `struct DrawDispatchVuid` has grown out of size and hard to map the exact field to the list, which results it the commit above actually producing wrong results
Granted the best solution is to just have test for all these VUs, but think I might just make a PR adding the `// field_name` as trying to count where in the struct it is has become tedious

layers: Relabel vkCmdDrawIndirectByteCountEXT VUs

---

layers/buffer_validation.cpp

VK_ATTACHMENT_UNUSED is allowed for both checks, and specifically check for depth and stencil

Fix checks for 02502 and 02503

---

layers/subresource_adapter.cpp
layers/synchronization_validation.cpp
layers/synchronization_validation.h
tests/vklayertests_buffer_image_memory_sampler.cpp

Fixes errors in barrier application model s.t. unintended dependency chains are no longer created for barriers within the same "batch" whether a barrier command or subpass definition.
Includes clean of subpass transition/load store validation/record as they were affected by the model changes, and the plumbing needed to support them.

syncval: Rework sync model to correct order independence of barrier batches and subpass dependencies

---

layers/parameter_validation_utils.cpp

Currently, the validation layers check for VUID 02084 in 2 spots, one
for images with usage VK_IMAGE_USAGE_SHADING_RATE_IMAGE_BIT_NV and one
for VK_IMAGE_USAGE_FRAGMENT_DENSITY_MAP_BIT_EXT. However, VUID 02084
only applies to VK_IMAGE_USAGE_SHADING_RATE_IMAGE_BIT_NV, not FDM,
so this check can be removed for the FDM path.

layers: Remove unnecessary FDM tiling check

---

layers/core_validation.cpp

The warn occurs if VkMemoryDedicatedAllocateInfo was provided and its image entry was VK_NULL_HANDLE, but the Vulkan spec states that this warn should only occur when VkMemoryDedicatedAllocateInfo::image was not VK_NULL_HANDLE. (Similarly for the VkMemoryDedicatedAllocateInfo::buffer)

layers: Fix checks for 01508 and 01509

---

BUILD.md
layers/android_ndk_types.h
layers/core_validation.cpp
layers/core_validation_types.h
layers/generated/thread_safety.h
layers/state_tracker.cpp
layers/vk_layer_config.cpp
scripts/thread_safety_generator.py
tests/vklayertests_others.cpp
tests/vkpositivelayertests.cpp

closes #2287 
- This adds a `AHB_VALIDATION_SUPPORT` macro depending on building for Android and the version
- replaced `VK_USE_PLATFORM_ANDROID_KHR` with new macro where needed
- BUILD.md update how to switch to `android-24` (which will work with `android-25`)
- added a `CheckAndroidVersion` call to run before `dlopen` so that if another developer runs into this same issue it will point them to what is wrong and hopefully save them time
----
@izhido I applied the following patch and built the layers, here are binary drops so they should work on your device
```patch
diff --git a/build-android/jni/Application.mk b/build-android/jni/Application.mk
index 243c28538..db1323a15 100644
--- a/build-android/jni/Application.mk
+++ b/build-android/jni/Application.mk
@@ -13,9 +13,9 @@
-APP_ABI := …
```

layers: Add Android 24 and 25 support

---

layers/core_validation.cpp
tests/vklayertests_buffer_image_memory_sampler.cpp

Adds `VUID-VkImageMemoryRequirementsInfo2-image-01591` which is just a mirror VU for `VUID-VkImageMemoryRequirementsInfo2-image-02280`

layers: Add VUID 01591

---

BUILD.md
CMakeLists.txt

The user's compiler may not be the same as the developer's compiler and its useful to allow disabling `-Werror` in such cases. By default it will be enabled to avoid changing the current behavior, but can be disabled by passing `-DBUILD_WERROR=OFF` as a cmake argument.
Also see the similar PR https://github.com/LunarG/gfxreconstruct/pull/459 for reference.

cmake: Add BUILD_WERROR

---

cmake/FindVulkanHeaders.cmake
cmake/FindXCB.cmake

Silences two cmake verbose warnings as reproduced with `cmake-3.18.4`.
```
CMake Warning (dev) at /usr/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:273 (message):
The package name passed to `find_package_handle_standard_args`
(VulkanRegistry) does not match the name of the calling package
(VulkanHeaders).  This can lead to problems in calling code that expects
`find_package` result variables (e.g., `_FOUND`) to follow a certain
pattern.
Call Stack (most recent call first):
cmake/FindVulkanHeaders.cmake:82 (find_package_handle_standard_args)
CMakeLists.txt:53 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.
```
```
CMake Warning (dev) at /usr/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:273 (message):
The package name …
```

cmake: Silence warnings
