layers/buffer_validation.cpp
As discussed in original PR, I think this is the proper way this should have been done in the first place
Can't think of a legit reason to not use string as its more searchable and performance shouldn't be an issue as this is only for when its about to log a validation error
=> layers: Change copy2 VU from int to string

BUILD.gn
The export_targets.py script detected that vk_layer_config.cpp added a
reference to android_ndk_types.h but didn't declare it as a related
source file.
Bug: 2305
=> Fix missing source reference

BUILD.gn, build-gn/generate_vulkan_layers_json.py
This change adds an optional argument `--platform Linux|Darwin|Windows|...` to `generate_vulkan_layers_json.py`, so that it could
generate layers json file with correct library filename for specific target platforms. It is useful when making cross-platform builds.
Test: Run `generate_vulkan_layers_json.py`
1) without `--platform` argument, 2) with `--platform Windows`, 3) with "--platform Linux` and 4) `--platform Darwin`.
=> build: Allow generating layers json file for cross-compiling

layers/CMakeLists.txt
When building with `BUILD_LAYER_SUPPORT_FILES` enabled which is required when building `VulkanTools` (https://github.com/LunarG/VulkanTools) it will install all of the files into `/usr/include` by default. However at least one file, `xxhash.h`, will conflict with `xxHash` package. I think its better to instead install to `/usr/include/vulkan` which is used by the `Vulkan-Headers` already and entirely avoid any conflicts. If you have any better ideas where to install it I can change that.
I have a patch for `VulkanTools` already for if and when this is merged, I am not sure if there are any other projects that would need to be changed?
=> cmake: Install the header files into the vulkan directory

layers/core_validation.cpp
The vertex buffer can be VK_NULL_HANDLE if the nullDescriptor feature is enabled on the device.
Fixes #2309.
=> layers: Check nullDescriptor when validating vertex attributes

layers/core_validation_types.h, layers/state_tracker.cpp, tests/vkpositivelayertests.cpp
I encountered false-positive validation errors doing this:
1. Submit work CB1 to queue Q1 that signals timeline semaphore S with value V.
2. Submit work CB2 to queue Q2 that wait on S with value V and signals fence F.
3. Wait for F.
4. Destroy resources used only in CB1.
This PR fixes propagation of queue work retirement through timeline semaphores across queues.
=> Fix queue retirement propagation via timeline semaphores

layers/core_validation.h, layers/core_validation_types.h, layers/descriptor_sets.cpp, layers/descriptor_sets.h
- Apply the BindingReqMap typedef to where it should have been used.
This will make it easier to modify the typedef in the future.
- Fix spelling of DescriptorRequirement.
Change-Id: If199357cbedb7249245ab62d0785957206ecb6c6
=> layers: Fix typedef and spelling

layers/best_practices_error_enums.h, layers/best_practices_utils.cpp, layers/best_practices_validation.h, layers/generated/best_practices.h, scripts/best_practices_generator.py, tests/vklayertests_best_practices.cpp
XML tags half a dozen categories of special use extensions and layers should warn if one is used.
=> Warn for an application's use of 'specialuse' extensions

layers/generated/thread_safety.cpp, layers/generated/thread_safety.h, scripts/thread_safety_generator.py, tests/vkpositivelayertests.cpp
It is valid for the `oldSwapchain `parameter of `VkSwapchainCreateInfoKHR `to be created on a different device than `vkCreateSwapchainKHR `is called with, so long as they have the same parent instance.  This PR will allow this relationship to be valid for these objects, preventing crashes/asserts.  
ObjectTracker correctly handles this situation.  Also added a positive test.  [Passed internal CI](http://erusea:4040/#/c/7706/).
Fixes #2256.
=> Fix oldSwapchain handling in thread_safety

layers/descriptor_sets.cpp, layers/descriptor_sets.h, tests/vklayertests_descriptor_renderpass_framebuffer.cpp
Remove buffer handle from the BufferDescriptor so we have only one buffer handle (in BUFFER_STATE) in our data structures.
Also, add a test that exercises the small logic change that was needed.
The new test doesn't depend on the code changes, so the test commit can be in any order or squashed with the layer commit.
=> Descriptor subclass handle dedup

layers/generated/object_tracker.cpp, scripts/object_tracker_generator.py
Many of these were being incorrectly validated against the owning vkDevice objects. These are now special case and the code-gen'd device checks are properly skipped.  
Fixes #2256. 
[Passed internal CI](http://erusea:4040/#/c/7749/).
=> Correct for non-device parent object validation in Object Lifetimes

layers/synchronization_validation.cpp
This fixes sync validation for the dEQP-VK.renderpass2.depth_stencil_resolve.*
CTS cases.
Change-Id: I4aa0cd9309d0b36707c18b7af645f321bb682605
=> syncval: Use correct raster order for depth/stencil resolve reads

layers/best_practices_utils.cpp, layers/buffer_validation.cpp, layers/gpu_utils.cpp, layers/layer_options.cpp, layers/subresource_adapter.cpp, layers/vk_mem_alloc.h
Latest clang generated multiple build warnings.  This should resovle
the issues encountered.
=> build: Fix clang warnings

layers/best_practices_utils.cpp, layers/buffer_validation.cpp, layers/core_validation.cpp, layers/core_validation.h, layers/core_validation_types.h, layers/debug_printf.cpp, layers/descriptor_sets.cpp, layers/descriptor_sets.h, layers/drawdispatch.cpp, layers/gpu_validation.cpp, layers/shader_validation.cpp, layers/state_tracker.cpp, layers/state_tracker.h, layers/synchronization_validation.cpp, tests/vklayertests_command.cpp
> VUID-vkCmdDraw-commandBuffer-02707
> If commandBuffer is an unprotected command buffer, any resource accessed by the VkPipeline object bound to the pipeline bind point used by this command must not be a protected resource
Validate the image and buffer in DescriptorSet. If the commandbuffer is unprotected, they MUST be unprotected.
> VUID-vkCmdTraceRaysNV-commandBuffer-02712
> If commandBuffer is a protected command buffer, any resource written to by the VkPipeline object bound to the pipeline bind point used by this command must not be an unprotected resource
Validate the image and buffer in DescriptorSet. If the commandbuffer is protected, they MUST be protected or only-read unprotected.
> VUID-vkCmdDraw-filterCubic-02694
> Any VkImageView being sampled with VK_FILTER_CUBIC_EXT as a …
=> Validate protected command buffer and filter cubic, and some refactors

layers/parameter_validation_utils.cpp, tests/vklayertests_buffer_image_memory_sampler.cpp
Spec defines these two state 'consolidations' but they were not properly accounted for in `VUID-VkImageCreateInfo-samples-02257`.  They were also used in the `VUID-VkImageCreateInfo-flags-02259` check, so that was added as well, along with some tests for both.
Fixes #1670.
> • Let uint64_t imageCreateDrmFormatModifiers[] be the set of Linux DRM format modifiers that the resultant image may have.
>      ◦ If tiling is not VK_IMAGE_TILING_DRM_FORMAT_MODIFIER_EXT, then imageCreateDrmFormatModifiers is empty.
>      ◦ If VkImageCreateInfo::pNext contains VkImageDrmFormatModifierExplicitCreateInfoEXT, then imageCreateDrmFormatModifiers contains exactly one modifier, VkImageDrmFormatModifierExplicitCreateInfoEXT::drmFormatModifier.
>      ◦ If VkImageCreateInfo::pNext contains …
=> Add imageFormatMaybeLinear/imageCreateDrmFormatModifiers calculation to 02257, add 02259 check

layers/core_validation.cpp, tests/vklayertests_command.cpp
1) Some command buffer of cmd_type couldn't be protected. They should keep this validation.
See
> VUID-vkCmdDrawIndirect-commandBuffer-02711
> commandBuffer must not be a protected command buffer
2) Using  a wrong descriptor type to cause Galaxy S10 crash.
=> Fixed bug for protected command buffer

docs/portability_validation.md, layers/core_validation.cpp, layers/core_validation.h, layers/core_validation_types.h, layers/parameter_validation_utils.cpp, layers/state_tracker.cpp, tests/CMakeLists.txt, tests/vklayertests_portability_subset.cpp
Add checks for the following VUIDs:
- VUID-VkDeviceCreateInfo-pProperties-04451.
- VUID-vkCreateEvent-events-04468.
Change-Id: I61743dc7ceddd2f4e627a7caeafacfcd0ff19d77
=> layers: Initial VK_KHR_portability_subset support

layers/buffer_validation.cpp, tests/vklayertests_portability_subset.cpp
Add support for VUIDs
- VUID-VkImageCreateInfo-imageView2DOn3DImage-04459
> If the VK_KHR_portability_subset extension is enabled, and VkPhysicalDevicePortabilitySubsetFeaturesKHR::imageView2DOn3DImage is VK_FALSE, flags must not contain VK_IMAGE_CREATE_2D_ARRAY_COMPATIBLE_BIT.
- VUID-VkImageCreateInfo-multisampleArrayImage-04460
> If the VK_KHR_portability_subset extension is enabled, and VkPhysicalDevicePortabilitySubsetFeaturesKHR::multisampleArrayImage is VK_FALSE, and samples is not VK_SAMPLE_COUNT_1_BIT, then arrayLayers must be 1.
Change-Id: I2335876f079e661983a69b757fd9e0c9979e42cb
=> layers: Portability validation for CreateImage

layers/buffer_validation.cpp, tests/vklayertests_portability_subset.cpp
Adds validation for VUIDs:
- VUID-VkImageViewCreateInfo-imageViewFormatSwizzle-04465
> If the VK_KHR_portability_subset extension is enabled, and VkPhysicalDevicePortabilitySubsetFeaturesKHR::imageViewFormatSwizzle is VK_FALSE, all elements of components must be VK_COMPONENT_SWIZZLE_IDENTITY.
- VUID-VkImageViewCreateInfo-imageViewFormatReinterpretation-04466
> If the VK_KHR_portability_subset extension is enabled, and
VkPhysicalDevicePortabilitySubsetFeaturesKHR::imageViewFormatReinterpretation is
VK_FALSE, the VkFormat in format must not contain a different number of components, or
a different number of bits in each component, than the format of the VkImage in image.
Change-Id: Ib5e70d73d175d15b09923db54b91ba5d91b62366
=> layers: Portability validation for CreateImageView

layers/core_validation.cpp, tests/vklayertests_portability_subset.cpp
Adds support for VUID:
- VUID-VkSamplerCreateInfo-samplerMipLodBias-04467
Change-Id: Ib0f4c0b2b88c4547a469a353d62fed0244b00ab0
=> layers: Portability validation for CreateSampler

layers/core_validation.cpp, layers/state_tracker.cpp, layers/state_tracker.h, tests/vklayertests_portability_subset.cpp
Adds validation for VUIDs
- VUID-VkPipelineInputAssemblyStateCreateInfo-triangleFans-04452
- VUID-VkVertexInputBindingDescription-stride-04456
- VUID-VkVertexInputAttributeDescription-vertexAttributeAccessBeyondStride-04457
- VUID-VkPipelineRasterizationStateCreateInfo-pointPolygons-04458
- VUID-VkPipelineDepthStencilStateCreateInfo-separateStencilMaskRef-04453
- VUID-VkPipelineColorBlendAttachmentState-constantAlphaColorBlendFactors-04454
- VUID-VkPipelineColorBlendAttachmentState-constantAlphaColorBlendFactors-04455
Change-Id: I5af3dccf8065b51a8ac31c835366c5391bfd7ea6
=> layers: Portability - CreateGraphicsPipelines

tests/vklayertests_command.cpp
`VerifyFilterCubicSamplerInCmdDraw` will give the wrong VUID error if the format feature isn't supported for `VK_FORMAT_R8G8B8A8_UNORM`
=> tests: Fix VerifyFilterCubicSamplerInCmdDraw

layers/parameter_validation_utils.cpp
For VUID-vkCmdBuildAccelerationStructuresKHR-pInfos-03810, the layers were
incorrectly checking geometry.triangles.indexData.deviceAddress instead of
geometry.triangles.transformData.deviceAddress.
Fixes #2362.
=> layer: Fix incorrect transformData check

layers/descriptor_sets.cpp, tests/vklayertests_portability_subset.cpp
Portability validation for UpdateDescriptorSets.
Adds validation for VUID:
- VUID-VkDescriptorImageInfo-mutableComparisonSamplers-04450
Change-Id: Iac5fe71491a313e12d5dc9163bc73969adcb42ba
=> layers: Portability VUID 04450

layers/descriptor_sets.cpp
Building top level AS is not necessary, updating the check to reflect
that, VUID description will be updated after necessary spec change
=> layers: Relax descriptor set VUID check

layers/core_validation.h, layers/descriptor_sets.cpp, layers/drawdispatch.cpp, tests/vklayertests_command.cpp
Similar to the 02694 and 02695 VUIDs, this is a set of simpler checks related to the `VK_IMG_filter_cubic` extension.  Added checks and tests.
Passes internal CI.
=> DrawDispatch 02693 VUID checks

docs/gpu_validation.md, layers/debug_printf.cpp, layers/debug_printf.h, layers/generated/chassis.h, layers/gpu_validation.cpp, layers/gpu_validation.h, layers/vk_layer_settings.txt, scripts/layer_chassis_generator.py, tests/layer_validation_tests.h, tests/vklayertests_gpu.cpp, tests/vktestbinding.h
Also cleans up some GPU-AV warts.  This does not validate texel buffers, that validation will be coming in a follow on PR once VVL glslang is updated.
=> Add buffer out of bounds checking to GPU Assisted Validation

layers/best_practices_validation.h, layers/core_validation.h, layers/debug_printf.h, layers/generated/best_practices.h, layers/generated/object_tracker.cpp, layers/generated/object_tracker.h, layers/generated/parameter_validation.h, layers/generated/thread_safety.cpp, layers/generated/thread_safety.h, layers/gpu_validation.h, layers/object_lifetime_validation.h, layers/parameter_validation_utils.cpp, layers/state_tracker.h, layers/stateless_validation.h, scripts/best_practices_generator.py, scripts/object_tracker_generator.py, scripts/parameter_validation_generator.py, scripts/thread_safety_generator.py
To cut down on self-inflicted injuries.
=> Universally add 'override' keywords to all chassis virtual functions

layers/core_validation.cpp, layers/drawdispatch.cpp, tests/vklayertests_command.cpp
Current VUIDs don't exists in spec, simple label typo fix
=> Fix incorrect VUID labels

BUILD.gn, build-android/cmake/layerlib/CMakeLists.txt, build-android/jni/Android.mk, layers/CMakeLists.txt, layers/core_validation.h, layers/core_validation_types.h, layers/generated/layer_chassis_dispatch.cpp, layers/generated/spirv_validation_helper.cpp, layers/shader_validation.cpp, layers/state_tracker.cpp, scripts/best_practices_generator.py, scripts/command_counter_generator.py, scripts/dispatch_table_helper_generator.py, scripts/generate_source.py, scripts/helper_file_generator.py, scripts/layer_chassis_dispatch_generator.py, scripts/layer_chassis_generator.py, scripts/layer_dispatch_table_generator.py, scripts/lvl_genvk.py, scripts/lvt_file_generator.py, scripts/object_tracker_generator.py, scripts/parameter_validation_generator.py, scripts/spirv_validation_generator.py, scripts/thread_safety_generator.py, scripts/vk_validation_stats.py, tests/vklayertests_pipeline_shader.cpp, tests/vkpositivelayertests.cpp
Closes #1022 
This uses the new SPIR-V tags in the XML starting in 1.2.159 which contain the information of all SPIR-V capabilities and extension and what they need (vulkan features, version, ext, etc) to be used
There is still some manual work needed in top of `spirv_validation_generator.py` do to nature of mapping to variable names and cases where the public SPIR-V Header isn't updated before the Vulkan Header are for a new extension
---
Adds 
- VUID-VkShaderModuleCreateInfo-pCode-01090
- VUID-VkShaderModuleCreateInfo-pCode-01091
- VUID-VkShaderModuleCreateInfo-pCode-04146
- VUID-VkShaderModuleCreateInfo-pCode-04147
=> layers: Generate SPIR-V Capability/Extension

layers/core_validation_error_enums.h, layers/generated/spirv_validation_helper.cpp, layers/shader_validation.cpp, scripts/spirv_validation_generator.py, tests/vklayertests_portability_subset.cpp
Validates the following contextual VUs:
- If vkPhysicalDevicePortabilitySubsetFeaturesKHR::tessellationIsolines is VK_FALSE, then isoline tessellation is not supported by the implementation, and IsoLines must not be used in either tessellation shader stage.
- If VkPhysicalDevicePortabilitySubsetFeaturesKHR::tessellationPointMode is VK_FALSE, then point mode tessellation is not supported by the implementation, and PointMode must not be used in either tessellation shader stage.
- GLSL.std.450 fragment interpolation functions are not supported by the implementation and OpCapability must not be set to InterpolationFunction if VkPhysicalDevicePortabilitySubsetFeaturesKHR::shaderSampleRateInterpolationFunctions is VK_FALSE.
This to resolve the remaining VUs in #2208.
Initial commit is passing …
=> layers: Portability Shader Validation

layers/CMakeLists.txt
CMake's RelWithDebInfo build type reduces the optimization level of the
code generation.  This change allows us to make a fully-optimized
Release build and still get a PDB file.
Change-Id: I84dfc8fbed9fcd593ab065fc53c2836a87548ff9
=> build: Generate PDB file for Release builds

tests/vklayertests_buffer_image_memory_sampler.cpp, tests/vklayertests_descriptor_renderpass_framebuffer.cpp, tests/vkrenderframework.cpp, tests/vkrenderframework.h
**InvalidMemoryMapping**
Simple missing VUID might be hit
**DrawWithPipelineIncompatibleWithRenderPassMultiview**
This one was missing the check if the device supports Multiview but not Renderpass2 which caused some issues on one device
**ImageSubresourceOverlapBetweenAttachmentsAndDescriptorSets**
Was crashing on updating the descriptor, realized the test was doing an invalid update and hitting `UNASSIGNED-CoreValidation-DrawState-InvalidImageView`, added simple fix to choose AspectMask manually for image
=> Fix various tests failing on Android

layers/state_tracker.h
Make sure the proper version of GetPhysicalDeviceProperties2[KHR] gets
called.
Change-Id: I3fa490286d52957416fac6c2698d38c3a37d5537
=> layers: Github issue 2390

layers/layer_options.cpp
The `vk_layer_settings.txt` file was not intended to support settings options that are quoted, but it is documented that way.  If a layer settings token has quotation marks at the beginning or ending, remove them.
[Passes CI.](http://erusea:4040/#/c/7980/)
Fixes #2378.
=> Account for quoted layer settings file strings

.clang-tidy, layers/best_practices_utils.cpp, layers/buffer_validation.cpp, layers/convert_to_renderpass2.cpp, layers/core_validation.cpp, layers/debug_printf.cpp, layers/descriptor_sets.cpp, layers/descriptor_sets.h, layers/drawdispatch.cpp, layers/gpu_utils.cpp, layers/gpu_validation.cpp, layers/layer_options.cpp, layers/object_tracker_utils.cpp, layers/parameter_validation_utils.cpp, layers/shader_validation.cpp, layers/state_tracker.cpp, layers/subresource_adapter.cpp, layers/synchronization_validation.cpp, layers/vk_format_utils.cpp, layers/vk_layer_config.cpp, layers/vk_layer_utils.cpp
refactor: Use clang-tidy on layers/*.cpp files
This change was automatically generated with the following clang-tidy
checks:
- -*
- google*
- readability-identifier-naming
- -google-readability-todo
Plus the following check options:
- readability-identifier-naming.VariableCase
- readability-identifier-naming.GlobalConstantCase
- readability-identifier-naming.GlobalConstantPrefix
Plus the following "one-time regex fixups":
- s/(^+.*\W)p_(semaphore|fence|cb|queue)(\W)/\1\2_state\3/g: fix
duplicate variable names
- s/(^+.*\W)p_([a-z])/\1\2/g: fix non-function-parameter variable names
with p prefix
=> refactor: Clean up variable names with clang-tidy

.github/workflows/ci_build.yml, scripts/common_ci.py, scripts/github_ci_android.py, scripts/github_ci_gn.py, scripts/github_ci_win_linux.py
Added Github actions workflow file for non-Windows CI checks. Actions are controlled by a yml file in the /.github/workflows directory.  The yml script relies on python scripts for checks that cover the CI steps listed below.  Note that these scripts can be run directly, for instance to check your Android or GN builds locally.
Travis checks are still enabled, they'll run in parallel during the initial testing phase, and will then be disabled.  The functionality covered by AppVeyor will also be integrated in the near-term [just realized that Actions will only support 2017 for a limited time, or 2019, but not 2015].
Also! Note the times.  The Actions steps all finished in about 15 minutes -- right now it's been 25 minutes, neither of the travis steps are done, and one has not yet started.
- …
=> Implement Travis CI Checks using Github Actions

layers/state_tracker.cpp
Found a case where the new generated SPIR-V shader capability was failing due to a few missing state tracking of the core 1.2 features.
The change/tests for this is in another upcoming PR, but wanted to get this fixed ASAP
=> layers: Add missing core features tracking

layers/state_tracker.cpp, layers/state_tracker.h, layers/subresource_adapter.cpp, layers/subresource_adapter.h, layers/synchronization_validation.cpp, layers/synchronization_validation.h, tests/vkrenderframework.h, tests/vksyncvaltests.cpp, tests/vktestbinding.cpp, tests/vktestbinding.h
Implements #2308 .
SetEvent -- creates map of accesses in first sync scope
WaitEvent -- applies barriers within first sync scope (and not newer than SetEvent)
ResetEvent -- resets.
All: State machine checks for inter-event-call race conditions.
=> syncval: Implement Cmd*Event synchronization validation

docs/synchronization_usage.md
Update the syncval usage documentation to reflect exit from alpha/beta
test phases.
=> syncval: Update usage docs to reflect syncval v1.0

layers/core_validation.cpp
Incorrect text on Subpass with multisample resolve of VK_SAMPLE_COUNT_1_BIT error message:
ubpass -> Subpass
=> layers: Fixed a typo on VUID 03066/00848 error message

layers/drawdispatch.cpp
These particular `CmdDispatch*` vuids are no-ops as they apply only to graphics/raytracing pipelines, while the dispatch APIs are only usable on compute pipelines.  The other DrawDispatch commands for this VUID are present and implemented, this just changes the VUID from `kVUIDUndefined `to the correct value.
=> Add 2701 dispatch vuids

layers/descriptor_sets.cpp, layers/parameter_validation_utils.cpp
Remove pNext null check so that subsequent validation code is hit
and we return fail early
Also update VUID desccription of
VUID-VkWriteDescriptorSetAccelerationStructureKHR-pAccelerationStructures-03579
=> layers : Fix crash due to NULL pNext

layers/synchronization_validation.cpp, layers/synchronization_validation.h
Now that index has 3 different sub-fields, herd all of the shift
logic into methods before it ends up scattered everywhere.
Change-Id: I3a944acfb2fa9a809be75b20a5c553fefac00870
=> syncval: Consolidate ResourceUsageTag.index bit twiddling

layers/core_validation.cpp, tests/vklayertests_others.cpp
**VUID-vkCmdBindVertexBuffers2EXT-pStrides-03361**
If the bound pipeline state object was created with the `VK_DYNAMIC_STATE_VERTEX_INPUT_BINDING_STRIDE_EXT `dynamic state enabled then `pStrides `must not be NULL, otherwise `pStrides `must be NULL
And the appropriate tests.
[Passes internal CI](http://erusea:4040/#/c/8039/).
Fixes #2376
=> Add VU for CmdBindVertexBuffers2EXT pStrides values

layers/core_validation.cpp, layers/core_validation.h, layers/state_tracker.cpp, layers/state_tracker.h
`vkCmdWriteAccelerationStructuresPropertiesKHR` did not have the affected querypool slots marked as `QUERYSTATE_ENDED`, resulting in the following validation layer error when copying results out:
Validation Error: [ UNASSIGNED-CoreValidation-DrawState-InvalidQuery ] Object 0: handle = 0x7f54ecc529b8, type = VK_OBJECT_TYPE_COMMAND_BUFFER; | MessageID = 0x46ab3a6e | vkCmdCopyQueryPoolResults(): Requesting a copy from query to buffer on VkQueryPool 0xff00000000ff[] query 0: waiting on a query that has been reset and not issued yet
This is simply fixed by marking the slots as containing valid data (`QUERYSTATE_ENDED`) in the `PostCall` handler.
Similarly it does not check whether every affected slot is in reset state like `vkCmdWriteTimestamp`, which has been added in `PreCall`.
EDIT: Are …
=> Mark querypool slots as ENDED in vkCmdWriteAccelerationStructuresPropertiesKHR

layers/synchronization_validation.cpp, layers/synchronization_validation.h, layers/vk_layer_data.h
Add a "small vector optimized" vector work-alike container and convert
sync last_reads to use it instead of the fixed sized array.
small vector interface is a strict subset of std::vector, implementing only the entry-points needed, and in STL not google style s.t. that it functions with range based for algorithms, etc.
=> Convert read stage tracking to new small_vector container

layers/synchronization_validation.cpp, layers/synchronization_validation.h
Add struct SyncExecScope to store the different
forms of execution scope flags so that it is easier
to set and pass them consistently.
Change-Id: I60e15955dafab01fba0183c5d8023f7c016fc761
=> syncval: Clean up execution scope data

layers/best_practices_utils.cpp, layers/best_practices_validation.h, tests/vklayertests_best_practices.cpp
Ensure the call state for all vkGetPhysicalDeviceQueueFamilyProperties*
variations are tracked properly.
This resolves Github issue #2437.
[Internal CI passing](http://erusea:4040/8041/).
=> layers: Update best practices CALL_STATE

layers/vk_format_utils.cpp
These guys were missing:
- VK_FORMAT_B5G5R5A1_UNORM_PACK16
- VK_FORMAT_BC1_RGBA_UNORM_BLOCK
- ~~VK_FORMAT_D16_UNORM~~
- ~~VK_FORMAT_D16_UNORM_S8_UINT~~
- ~~VK_FORMAT_D24_UNORM_S8_UINT~~
- VK_FORMAT_PVRTC1_2BPP_UNORM_BLOCK_IMG
- VK_FORMAT_PVRTC1_4BPP_UNORM_BLOCK_IMG
- VK_FORMAT_PVRTC2_2BPP_UNORM_BLOCK_IMG
- VK_FORMAT_PVRTC2_4BPP_UNORM_BLOCK_IMG
- VK_FORMAT_R10X6_UNORM_PACK16
- VK_FORMAT_R10X6G10X6_UNORM_2PACK16
- VK_FORMAT_R12X4_UNORM_PACK16
- VK_FORMAT_R12X4G12X4_UNORM_2PACK16
- ~~VK_FORMAT_X8_D24_UNORM_PACK32~~
Fixes #2449.
=> Update FormatIsUNorm()  list with missing formats

tests/vklayertests_pipeline_shader.cpp, tests/vkpositivelayertests.cpp, tests/vkrenderframework.cpp, tests/vkrenderframework.h
There is some language around making sure the features are enabled in `VK_KHR_8bit_storage` and `VK_KHR_16bit_storage` , but after writing the test, I realized that the SPIR-V capability generation catches everything perfectly already. Since I already had the test, decided to add just for sake of there are no tests currently targeting either extension.
=> tests: Add 8bit and 16bit storage

layers/core_validation.h, layers/core_validation_types.h, layers/shader_validation.cpp, layers/state_tracker.cpp, tests/vklayertests_pipeline_shader.cpp, tests/vkpositivelayertests.cpp
Spec has (for now unassigned) VUs
> if shaderSubgroupClock is not enabled, the Subgroup scope must not be used for OpReadClockKHR.
and 
> if shaderDeviceClock is not enabled, the Device scope must not be used for OpReadClockKHR.
so added coverage for them
=> Add VK_KHR_shader_clock support

layers/gpu_utils.cpp
Fixes #2422 and should allow vkcube to run on MacOS with GPU-AV enabled
=> Fix GPU-AV features path when no app features

layers/core_validation.cpp, layers/core_validation.h, layers/parameter_validation_utils.cpp
Spec language for `VUID-vkCmdWriteAccelerationStructuresPropertiesNV-queryType-03432` was incorrect.  There is an [approved spec MR](https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/4310) in flight and this PR updates the validation to match the corrected VU language.
This change also implements 03431 and brings the `vkCmdWriteAccelerationStructuresPropertiesNV `validation up to par with the `vkCmdWriteAccelerationStructuresPropertiesKHR` checks.
Fixes #2448.
@pixeljetstream, @souravpNV, please feel free to have a look as well.  Thanks!
=> Change validation for incorrect spec VU

layers/parameter_validation_utils.cpp, layers/stateless_validation.h
Move EnumeratePhysicalDevices calls from PostCallRecordCreateInstance to
PostCallRecordEnumeratePhysicalDevices. This is to avoid a crash that
occurs in AMD drivers when VVL is used with devsim.
See https://gitlab.khronos.org/vulkan/Vulkan-SDK-Packaging/-/issues/607
for more information about the crash in devsim.
Change-Id: I1e164597e8c9a60115f986887bf4590b6b469f9f
=> layers: Remove device calls from CreateInstance

.github/workflows/ci_build.yml
Use default Ubuntu cmake package for linux builds due to apparent
problems with the jwlawson/actions-setup-cmake script.
Change-Id: Ie946d5277cd334123b809f28df99aea596582fe6
=> build: Fix Github actions CI

layers/descriptor_sets.cpp, tests/vklayertests_descriptor_renderpass_framebuffer.cpp
VUID-VkDescriptorSetLayoutBinding-descriptorType-04604
Before the check was using the enabling of the extension but it should be the use of the feature bit
=> Fix inlineUniformBlock test

layers/buffer_validation.cpp, layers/core_validation.h, layers/parameter_validation_utils.cpp
Someone internally found an error while looking at an image copy, I realized the message lacked giving the information needed (mainly which `pRegion` the copy error belonged too... went through and improved some other error messaging for image copies and creation to display values
Also instead of having to pass the `pRegion` index also into `CopyImageMultiplaneValidation`, it seemed worth just inlining as it fits well where it is now
=> layers: Improve Image copy/create message

layers/parameter_validation_utils.cpp, tests/vklayertests_pipeline_shader.cpp
adds
VUID-VkGraphicsPipelineCreateInfo-flags-03371
VUID-VkGraphicsPipelineCreateInfo-flags-03372
VUID-VkGraphicsPipelineCreateInfo-flags-03373
VUID-VkGraphicsPipelineCreateInfo-flags-03374
VUID-VkGraphicsPipelineCreateInfo-flags-03375
VUID-VkGraphicsPipelineCreateInfo-flags-03376
VUID-VkGraphicsPipelineCreateInfo-flags-03577
Also moved 
VUID-VkGraphicsPipelineCreateInfo-flags-00764
VUID-VkGraphicsPipelineCreateInfo-flags-03377
to be next to them in the function (and unified error message)
=> Add graphics pipeline flags VU

layers/buffer_validation.cpp, layers/core_validation.cpp, layers/core_validation.h, layers/descriptor_sets.cpp
Disable queue submit time image layout validation for update-after-bind
bindings, as currently not enough information is tracked for correct
validation at that point.
All other queue submit time checks for update-after-bind are retained.
Fixes false positive from #1519
=> Disable image layout check at queue submit time for update-after-bind

layers/descriptor_sets.cpp, layers/descriptor_sets.h, layers/generated/layer_chassis_dispatch.cpp, scripts/layer_chassis_dispatch_generator.py
add state tracker for acceleration structure when updated using
vkUpdateDescriptorSetWithTemplate
=> layers: Fix vkUpdateDescriptorSetWithTemplate crash

layers/core_validation.cpp
From https://github.com/KhronosGroup/Vulkan-Docs/issues/1392
@shannon-lunarg In case you are working on new head integration
` VUID-VkGraphicsPipelineCreateInfo-blendEnable-02023` became ` VUID-VkGraphicsPipelineCreateInfo-blendEnable-04717` but the wording was completly redone... the only difference was using potential format features which this does
=> layers: Update 02023 to use potential format features

BUILD.gn
On macOS vk_mem_alloc.h defines aligned_alloc and then uses it, which is
valid. However since aligned_alloc was added in macOS 10.15, clang
complains that it is used without it being in the deployment target (if
deploying for a version <10.15). This commit suppresses the warning at
the GN level since vk_mem_alloc.h is a copied from VMA.
=> GN: Suppress -Wunguarded-availability-new on macOS

layers/core_validation.cpp
When submitting work with vkQueueSubmit and using a VkSubmitInfo
structure that has a non-zero waitSemaphoreCount and a null
pWaitDstStageMask pointer, the layers will correctly validate that the
parameter should not be null, but later crash while attempting to
validate some other aspects of the call.
=> Fix crash with null pWaitDstStageMask

layers/state_tracker.cpp
The logic used to query the compatible DRM format modifiers in GetPotentialFormatFeatures is not aligned with the API specification requirements.
The current logic sets pDrmFormatModifierProperties to NULL while expecting to be filled after the vkGetPhysicalDeviceFormatProperties2 call.
And this is how it should be:
- First, call vkGetPhysicalDeviceFormatProperties2 with pDrmFormatModifierProperties=NULL to get the number of DRM format modifiers.
- Then, call vkGetPhysicalDeviceFormatProperties2 a second time with pDrmFormatModifierProperties pointing to an allocated array big enough to fit the number of requested DRM format modifiers.
=> layers: Fix segfault when querying a list of DRM format modifiers

layers/core_validation.cpp, layers/core_validation.h, layers/core_validation_types.h, layers/shader_validation.cpp, tests/vklayertests_command.cpp
If a shader module used to create a graphics pipeline was destroyed between pipeline creation and a draw, the fragment shading rate validation would crash trying to access shader module state that no longer existed.  This moves the shader parsing to CreateGraphicsPipelines, saving the stages that write to the primitive shading rate builtin, to use in validation at draw time.
=> Fix fragment shading rate validation

layers/core_validation.cpp
Change the VUID to report to reflect the condition being tested.  Corrects issue of returning the "buffer must be bound" VUID instead of the "image must be bound" VUID
=> layers: Correct VUID to the image version

tests/vklayertests_arm_best_practices.cpp, tests/vklayertests_best_practices.cpp, tests/vklayertests_buffer_image_memory_sampler.cpp, tests/vkpositivelayertests.cpp, tests/vkrenderframework.cpp, tests/vkrenderframework.h
With more WSI tests I plan to write, I noticed some redundant code that would be nicer to just put in a function in the renderframework
=> tests: Add swapchain query function

layers/state_tracker.cpp, layers/state_tracker.h, layers/synchronization_validation.cpp, layers/synchronization_validation.h
Encapsulate Event and RenderPass synchronization operations in objects suitable for record/playback during inter-command buffer validation.  This is "plumbing only" no inter-command buffer operations supported by this PR.  However changes make code somewhat DRY'r in current usage.
Note changes to better encapsulate state for RenderPass operations, s.t. stale command buffer state is not reference at a future replay.
=> Encapsulate Remaining sync operations into (potentially) replayable objects

layers/shader_validation.cpp
Used by VK_KHR_workgroup_memory_explicit_layout.
=> layers: Set workgroup scalar block layout in SPIR-V validator

layers/synchronization_validation.cpp
So not sure with the `todo` above this what the goal was but I am unable to build ToT with my clang/ubuntu.20.4 setup due to the following
```
synchronization_validation.cpp:5428:29: error: loop variable 'attachment' of type 'const std::shared_ptr<const IMAGE_VIEW_STATE>' creates a copy from type 'const std::shared_ptr<const IMAGE_VIEW_STATE>' [-Werror,-Wrange-loop-construct]
for (const auto attachment : shared_attachments_) {
```
It seem to have been added here
https://github.com/KhronosGroup/Vulkan-ValidationLayers/commit/64ffe55c3bf6ca2063a249f642601f661ae7e2ec#diff-4db5972bac4fb44578a6e0b54f24064bda9106222ea62ed20e34814a90326110
cc @jzulauf-lunarg
=> layers: silent clang warning

layers/best_practices_utils.cpp, layers/best_practices_validation.h, layers/debug_printf.cpp, layers/debug_printf.h, layers/gpu_validation.cpp, layers/gpu_validation.h
Update debug_printf, gpu_validation and best_practices to support
VK_KHR_synchronization2 entry points.
Change-Id: Icb742d14fbadbc47e2b7d8bb683c03dbd4ee97c5
=> layers: Add sync2 support to simple validators

layers/buffer_validation.cpp, layers/core_validation.cpp, layers/core_validation_types.h, layers/state_tracker.cpp, layers/subresource_adapter.h, layers/vk_layer_data.h
Reduce map lookups and memory allocation by only constructing needed maps, and allowing efficient `[]` lookups for new entries without unneeded constructions.
struct Optional approximates std::optional which is not support on C++11.
=> Lazier map creation to improve image layout validation performance

layers/core_validation.h, layers/generated/spirv_validation_helper.cpp, layers/shader_validation.cpp, scripts/spirv_validation_generator.py
Looking at how `spirv-val` does stuff, it reduces having to keep re-looping the module by emitting "passes" which then switch case the instructions
For now, I took the 3 functions I quick found in shader_validation that are "stateless" and packed in single loop
=> layers: Reduce shader validation passes

layers/shader_validation.cpp, layers/shader_validation.h
There are many cases where we are looping the entire module just to fine the `OpMemberDecorate` and `OpDecorate`
=> layers: Reduce looping shader for decoration

layers/CMakeLists.txt
- Macro `AddVkLayer` is simplified, since many things are shared.
- Windows:
- Fix source folder during installation of json file (it was too fragile)
- ~Install dll and json files in bin folder (see https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/2550)~ => modification cancelled
- remove `copy-${target}-def-file` custom target which is useless
- Macos: Install .dylib in lib folder.
Also, there are a lot of global definitions and compile_options in this CMakeLists, while some others are added to layer targets through this macro, it's weird and hard to read. All these global `add_definitions` and `add_compile_options` should go in this macro (or in specific properties of khronos_validation? It's not clear)
=> cmake: Simplify AddVkLayer and fix installation of json on Windows

layers/sync_vuid_maps.cpp, tests/vklayertests_buffer_image_memory_sampler.cpp
The matching for the sync2 functions in
sync_vuid_maps::GetStageQueueCapVUID() was insufficiently fuzzy.
This is a short term fix until there's a chance to redo the
location to be a) not string based and b) much more robust.
Fixes #2590
=>     corechecks: Fix sync2 queue caps vs pipeline stage checks

scripts/github_ci_win_linux.py
Previously this was allowed to keep running and just reported the status
at the end. In hindsight, this just buries the error message in the CI
log.
Also change CI order to run codegen last so a failure doesn't interfere
with other checks. Finally, fix bug where failure code from LVT was not
passed back to the CI script.
Change-Id: I62a9a4c959258518a60a49d24b4ca0959ecc9cb9
=> scripts: Exit CI script if codegen check fails

layers/core_validation.cpp, layers/core_validation.h, layers/descriptor_sets.cpp, layers/descriptor_sets.h, tests/layer_validation_tests.cpp, tests/layer_validation_tests.h, tests/vklayertests_command.cpp, tests/vklayertests_descriptor_renderpass_framebuffer.cpp, tests/vklayertests_gpu.cpp, tests/vklayertests_others.cpp, tests/vkpositivelayertests.cpp, tests/vksyncvaltests.cpp
So to break this down
1. Currently `VUID-vkCmdBindDescriptorSets-pDescriptorSets-01979` was being down at draw time, but I see no reason why not to just do it at bind time
2. To make life easier with the looping of the `pDynamicOffset` I needed to move `ValidateDynamicOffsetAlignment` inlined to the function for the 2 cases
3. Added a `IsDyanmicDescriptor` to future proof the case where a new descriptor type is also used to check the various spots in the code
4. For the the tests, I needed to access the `offset` in the `OneOffDescriptorSet::WriteDescriptorBufferInfo`
@locke-lunarg for if there is a reason I am missing this was done at draw time?
=> Move pDynamicOffset to bind time

layers/generated/spirv_validation_helper.cpp, scripts/spirv_validation_generator.py
Before items like `CapabilitySignedZeroInfNanPreserve` were only being checked from the last property listed in the XML instead of using them all
=> layers: Check all properties for SPIR-V gen

layers/best_practices_utils.cpp, layers/core_validation.h, layers/shader_validation.cpp, layers/shader_validation.h, tests/vklayertests_pipeline_shader.cpp, tests/vkpositivelayertests.cpp
On first step to fix the 2 open Entry Point issues, first fixed up how we check `OpExecutionMode` because execution modes are not tied to a single entry point
Also added a `VK_KHR_float_controls` to verify myself on this change
=> Add better OpExecutionMode logic

layers/core_validation.cpp, layers/sync_vuid_maps.cpp, layers/synchronization_validation.cpp
Commit e60d417b5 garbled several VUIDs, fix them.
Change-Id: I5c611010c3c45a4a4c826d5d1d63eef5dbe65b86
=> corechecks: Correct VUID strings for synchronization APIS

layers/core_validation.cpp, layers/core_validation.h
Transform feedback queries are indexed for multiple streams.  That
means somthing like this is can be done:
vkCmdBeginQueryIndexedEXT(cmdBuf, xfbPool, queryIndex42, 0x0, 0); // stream 0
vkCmdBeginQueryIndexedEXT(cmdBuf, xfbPool, queryIndex43, 0x0, 1); // stream 1
vkCmdBeginQueryIndexedEXT(cmdBuf, xfbPool, queryIndex44, 0x0, 2); // stream 2
...draw...
vkCmdEndQueryIndexedEXT(cmdBuf, xfbPool, queryIndex42, 0);
vkCmdEndQueryIndexedEXT(cmdBuf, xfbPool, queryIndex43, 1);
vkCmdEndQueryIndexedEXT(cmdBuf, xfbPool, queryIndex44, 2);
But as-is, the validation layer was generating an error on the second
begin-query saying that a query of that type was already active.
This fix is to also compare the query's index in addition to its type
during validation.  For non-xfb queries the index is always …
=> layers: handle nested transform feedback queries

layers/core_validation.cpp, tests/vklayertests_buffer_image_memory_sampler.cpp
For VUID-VkMappedMemoryRange-size-01389, the layers were incorrectly
applying the spec requirement that the mapping must end at a multiple of
the non-coherent atom size. Instead, they were calculating if the end of
the allocation minus the range offset was a multiple of the non-coherent
atom size.
In addition, this commit also takes into account the new possibility of
the memory mapping actually ending at the end of the allocation, which
is considered legal.
For VUID-VkMappedMemoryRange-size-01390, the error message is improved
to show every affected value and the second part of the spec condition.
=> layers: Fix VUID-VkMappedMemoryRange-size-01389/90

layers/core_validation.cpp, layers/descriptor_sets.h, tests/layer_validation_tests.cpp, tests/layer_validation_tests.h, tests/vklayertests_descriptor_renderpass_framebuffer.cpp
closes #2600 
So the CTS test had a descriptor layout with bindings `0` and `2` and the loop of the bindings when it was `1` 
```c++
// binding_idx == 1
// Returned binding index of 2
VkDescriptorSetLayoutBinding *binding = dsl->GetDescriptorSetLayoutBindingPtrFromIndex(binding_idx);
// Was looking for binding index of 1
Descriptor *descriptor = descriptor_set->GetDescriptorFromBinding(binding_idx);
```
So the simple fix was fixing some naming so that the `binding_index` is the actual binding index value and not the loop of the **number** of bindings
----
Second commit is various tests and small tweaks that are general improvements and replicated the same error the CTS tests had
=> Fix binding index bug for dynamic offsets

layers/core_validation.cpp, layers/descriptor_sets.cpp, layers/descriptor_sets.h, tests/layer_validation_tests.cpp, tests/layer_validation_tests.h, tests/vklayertests_buffer_image_memory_sampler.cpp, tests/vklayertests_command.cpp, tests/vklayertests_descriptor_renderpass_framebuffer.cpp
Closes #2600 
From spec
> dynamicOffsetCount must equal the total number of dynamic **descriptors** in the sets being bound
I didn't even realize until now you could have a `VkDescriptorSetLayoutBinding` with a `dynamicOffsetCount` of zero (special case in spec) and now it will skip a binding with a dynamic descriptor type that doesn't actually have a descriptor to it.. this solves #2600
While adding this, I realize I wasn't handling the case where `descriptorCount` was greater then `1` so added that support. It consisted of removing the old descriptor dynamic index helper functions and added a new one that will just track which `cvdescriptorset::Descriptor` to grab by the offset.
I also added the `dstArrayElement` field to all the `VkWriteDescriptorSet` wrappers in the testing framework
=> Fix descriptorCount bindings being checked

layers/buffer_validation.cpp, layers/core_validation.cpp, layers/core_validation.h, layers/core_validation_types.h, layers/state_tracker.cpp, layers/state_tracker.h, layers/subresource_adapter.cpp, layers/subresource_adapter.h, layers/synchronization_validation.cpp
Add support for swapchain images (from GetSwapchainImage and VkBindImageMemorySwapchainInfoKHR) in hazard detection and update paths.
Store image state pointers in the swapchain state data instead of continually looking it up.
Fixes #2603
=> Add swapchain image hazard detection

layers/descriptor_sets.cpp, tests/vklayertests_descriptor_renderpass_framebuffer.cpp
Went through and added some more detailed logging to the error messages in `descriptor_sets.cpp`
----
Note I ran clang-format with
```bash
$ clang-format-7 --version
clang-format version 7.0.1-12 (tags/RELEASE_701/final)
```
and surprised it changed the layout of the `LogError` for them as much as it did
=> layers: Improve descriptor_sets.cpp logs

tests/vklayertests_arm_best_practices.cpp, tests/vklayertests_best_practices.cpp, tests/vklayertests_others.cpp, tests/vkpositivelayertests.cpp, tests/vkrenderframework.cpp
First part/commit of #2572 as separate PR to make sure it works
The issue was I didn't realize the validation layers were not checking `VK_KHR_android_surface` due to the spec stating
> Currently on Android, any physical device is expected to be able to present to the system compositor, and all queue families must support the necessary image layout transitions and synchronization operations.
=> tests: Add vkGetPhysicalDeviceSurfaceSupportKHR check

layers/shader_validation.cpp, layers/shader_validation.h
Related to https://github.com/KhronosGroup/Vulkan-ValidationLayers/projects/4#card-50486050.
Few spots were looping the first part of the shader just to find the built-in information. Moved that to the initial pass since we are already collecting the decorations there for other reasons
----
(note: this will totally merge conflict in the head file with !2596 and I will fix the later, in case you want to save yourself a internal CI run on this until the other PR is in)
=> layers: Reduce looping for builtins

layers/core_validation.cpp, layers/generated/parameter_validation.cpp, layers/parameter_validation_utils.cpp, layers/stateless_validation.h, scripts/parameter_validation_generator.py, tests/vklayertests_others.cpp
The first commit is to fix the fact the swapchain tests were not calling `vkGetPhysicalDeviceSurfaceSupportKHR` and tripping `VUID-VkSwapchainCreateInfoKHR-surface-01270` (just happened to still work in drivers I guess)
Then moved `VUID-VkSwapchainCreateInfoKHR-flags-03168` from `core_validation` to `parameter_validation_utils` (also wrote missing test for it). Also `vkCreateSharedSwapchainsKHR` was missing from having its create info checked in parameter utils
Lastly this adds support for `VUID-VkSwapchainCreateInfoKHR-pNext-04099` and `VUID-VkSwapchainCreateInfoKHR-flags-04100`
=> VK_KHR_image_format_list for swapchain

scripts/spirv_validation_generator.py
So this seems to do nothing, but because of https://github.com/KhronosGroup/Vulkan-Docs/issues/1437 there is a fix coming (internal Vulkan MR 4399) to fix the XML.
The new XML will break the build with a difference in `spirv_validation_helper.cpp` of
```patch
{spv::CapabilityDrawParameters, {0, &VkPhysicalDeviceVulkan11Features::shaderDrawParameters, nullptr, ""}},
+    {spv::CapabilityDrawParameters, {0, &VkPhysicalDeviceShaderDrawParametersFeatures::shaderDrawParameters, nullptr, ""}},
```
This change will prevent ` {spv::CapabilityDrawParameters, {0, &VkPhysicalDeviceShaderDrawParametersFeatures::shaderDrawParameters, nullptr, ""}},` from being generated and breaking the build. This is valid because how state_tracker absorbs everything to the `core11` and `core12` structs
=> scripts: Handle XML spirvcapability using alias

layers/buffer_validation.cpp, layers/state_tracker.cpp, tests/vkpositivelayertests.cpp
In some places, GetPhysicalDeviceFormatProperties2 was not called twice as it is needed when checking supported modifier properties (the first call to retrieve the count, the second to retrieve the actual properties).
This lead to crashes inside the layer when using the extension.
The fix is pretty much just copied from other places inside the layer where it's done correctly.
=> Fix VK_EXT_image_drm_format_modifier validation

layers/core_validation.cpp, layers/descriptor_sets.cpp, layers/descriptor_sets.h
So after diving more into the code
- If the a new descriptor type is ever added, finding all the spots being used to add it is just as error prone as someone using `IsDyanmicDescriptor` incorrectly as descriptor types are used for various checks of different scopes anyways
- The `Descriptor` class had a virtual function for this already, but no one is using it anyway as it is easier to check the enum you want instead of hoping some abstracted function is doing it correctly. Plus there isn't any fancy logic picking which to use
- The functions ruins the places where switch statements make more scene
=> layers: Remove unnecessary descriptor_sets functions

layers/descriptor_sets.cpp, layers/descriptor_sets.h
This method ends up being a performance hotspot in applications
that use many descriptors. It doesn't look like it needs to be
virtual.
Change-Id: I4193b1da3ba76159dbb9c4d6814073773f261752
=> corechecks: Descriptor::GetClass() shouldn't be virtual

layers/core_validation.cpp
The `sType` was missing from `VkMultisamplePropertiesEXT` which is invalid Vulkan and found causes issues with drivers
Also I have ran on some mobile platforms where the uninitialized struct value is not always zero'ed out and `pNext` should be explicitly set
I scanned for other `Dispatch*` calls we make in the layer and these are the only ones using pNext structs missing this stuff
=> layers: Fix missing pNext and sType

layers/buffer_validation.cpp, layers/core_error_location.cpp, layers/core_error_location.h, layers/core_validation.cpp, layers/sync_vuid_maps.cpp
Make the fuzzy matching of location to VUID be based on
enums rather than strings. Also try to assert() if there's
a problem with the lookup (in debug builds).
=> corechecks: Improve core_error::Location to VUID lookups

layers/buffer_validation.cpp, layers/buffer_validation.h, layers/core_validation.cpp, layers/core_validation.h, layers/image_layout_map.cpp, layers/image_layout_map.h
The InitialLayoutStates vector appears to perform better if
it contains the InitialLayoutState struct directly. This change also
switches parameters in calls related to this vector to use references
when possible.
=> corechecks: Remove unique_ptr from image layout states vector

BUILD.gn, CMakeLists.txt, build-android/jni/Android.mk, layers/CMakeLists.txt, layers/vk_layer_data.h, tests/CMakeLists.txt
Add some infrastructure to make robin-hood-hashing optional. This change
1. Removes the use of robin-hood-hashing from the GN build
2. Makes the use of robin-hood-hashing optional for cmake builds via the
USE_ROBIN_HOOD_HASHING cmake variable
3. Leaves robin-hood-hashing as the default for Android with no
"configuration" option (i.e., additional changes to Android.mk must
be made to _not_ use robin-hood-hashing on Android).
=> build: Revert robin-hood-hashing for GN

layers/core_validation.cpp, layers/descriptor_sets.cpp, layers/generated/layer_chassis_dispatch.cpp, layers/parameter_validation_utils.cpp, layers/shader_validation.cpp, layers/state_tracker.cpp, layers/vk_layer_logging.h, scripts/layer_chassis_dispatch_generator.py
The insert() call in  ValidationStateTracker::AddCommandBufferBinding() had a measurable performance impact, I'm unsure about the others.
=> layers: Remove accidental object copies from for loops and map insert() calls

layers/synchronization_validation.cpp
Added a missing parenthesis in synchronization_validation.cpp.
=> layers: Fix missing parenthesis in sync validation

CMakeLists.txt
This is required for building the LunarG/VulkanTools repository.
=> build: Set robin-hood path when building only layer utils

layers/vk_loader_platform.h
On MinGW from Linux this fails because winsock2.h is lowercase.
=> layers: Fix winsock include on case-sensitive fs

layers/shader_validation.cpp, layers/shader_validation.h, tests/vkpositivelayertests.cpp
I have started working on a solution for the multi- `OpEntryPoint` fix for the layers, but it is a much bigger change to go tracking each function block that is used in an entry point, for now, purpose to just add this to stop the false errors seen in https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/2583 and https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/2450 for the short term
Note: the 2 `VkPositiveLayerTest` will fail without this patch, but are both fully valid and show the issue where flipping the entry points around was the main issue
=> layers: Temp fix for multi-EntryPoint pc

layers/core_validation.cpp, tests/vklayertests_others.cpp
Fixes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/2659
Even if someone is using Vulkan 1.0/1.1 and enables the `VK_KHR_timeline_semaphore` extension, they still need to enable `VkPhysicalDeviceTimelineSemaphoreFeatures::timelineSemaphore` to use (which we map to `enabled_features.core12.timelineSemaphore` in state tracking)
The issue was these 2 VUs didn't have a test, so added 2 tests to check with both extensions and 1.2 core path
=> Fix VK_KHR_timeline_semaphore feature bug

docs/khronos_validation_layer.md, layers/vk_layer_config.h, layers/vk_layer_logging.h
It's useful for certain downstream tools/systems(like automation)
to parse the log output of validation layers. On Android via logcat,
the default validation layer callback only prints when the Vulkan app
explicitly doesn't subscribe to the VK_EXT_debug_utils callback via
vkCreateDebugUtilsMessengerEXT. When the app does subscribe, then only
the app's callback is executed. To allow such downstream tools to
parse logcat for validation layer errors, this PR adds a mechanism to
force the default log to always be printed, regardless of whether the
app subscribes via vkCreateDebugUtilsMessengerEXT. This PR is currently
limited to Android-only, and opt-in with an Android system property.
This allows downstream tools to set the property and parse the logcat
in a known form(accessing key info …
=> layers: Add an Android default log force option via setprop

layers/state_tracker.cpp, tests/vkpositivelayertests.cpp
Currently the `VkImage`s from a Swapchain with `VK_SWAPCHAIN_CREATE_PROTECTED_BIT_KHR` were not being marked as protected and throwing a false error for `VUID-vkCmdDraw-commandBuffer-02712`
Simple 1 line fix and added a test to show a case it was failing prior
=> Fix protected swapchain images

layers/best_practices_utils.cpp, tests/vklayertests_best_practices.cpp
A present mode of `VK_PRESENT_MODE_FIFO_KHR` is required to be
supported, so this is now checked and no longer issues a warning
about `vkCreateSwapchainKHR()` being called before first getting surface
present mode(s) from `vkGetPhysicalDeviceSurfacePresentModesKHR()`
Test added for three checks using
`UNASSIGNED-BestPractices-vkCreateSwapchainKHR-surface-not-retrieved`
which make sure `GetPhysicalDeviceSurfaceCapabilitiesKHR()`,
`GetPhysicalDeviceSurfaceFormatsKHR()`, and
`GetPhysicalDeviceSurfacePresentModesKHR()` are all queried before
swapchain creation--except for when `presentMode` ia
`VK_PRESENT_MODE_FIFO_KHR` which is guaranteed to be supported.
=> Remove warning if swapchain present mode is FIFO_KHR [WIP]

layers/core_validation.cpp, layers/core_validation.h, layers/descriptor_sets.cpp
When there are a large number of image layouts, keep track of the ones
that have been validated and avoid rechecking the same layouts.
This provides some performance improvement for applications providing
repeated layouts without significant impact to others.
=> layers: Avoid redundant image layout checks

layers/core_validation.cpp, layers/state_tracker.cpp, tests/vkpositivelayertests.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/2654
- Use of when `ResetCommandBufferPushConstantDataIfIncompatible` was called was wrong (as noted in comment)
- `// case 6` is example of `dEQP-VK.pipeline.push_constant.lifetime.push_range0_bind_layout1_overlapping_range_bind_layout0` from CTS that was failing previously
- `PushConstantsStaticallyUnused` tests used to make sure validation doesn't assume a range in the layout means the shader in the pipeline will use them
=> Fix PushConstants drawtime compatibility

layers/generated/chassis.h, layers/vk_layer_logging.h, scripts/layer_chassis_generator.py
These checks can happen before the full message gets built, which
will make reduce the performance cost of hitting a disabled or duplicate
error.
Change-Id: I0d527892947ccab37c7d56e9d5ade946062dd6e9
=> layers: Check for disabled log messages more efficiently

layers/image_layout_map.h
Many images appear to need only 1 or 2 InitialLayoutStates, so using
a small vector prevents new calls in these cases. Performance appears
to fall off if the small vector is size 4. In some cases we're getting
over entries 255, so the small vector cannot use uint8_t for its size.
Change-Id: I54867270c75934c3440986d18e5c9d7f51255780
=> corechecks: Make InitialLayoutStates be a small_vector

layers/core_validation.cpp
Ran across in ANGLE testing, messages needed a bit of clarification.
=> Fix CreateFrameBuffer width/height typos

tests/vklayertests_others.cpp, tests/vkrenderframework.cpp, tests/vkrenderframework.h, tests/vktestframework.cpp, tests/vktestframework.h, tests/vktestframeworkandroid.cpp, tests/vktestframeworkandroid.h
Choose the VkPhysicalDevice for testing based on device type rather than
the first device returned from vkEnumeratePhysicalDevices.
This change also adds a `--device-index` command line argument to manually choose the device index.
=> tests: Choose device based on type

layers/core_validation.cpp, layers/shader_validation.cpp, tests/vkpositivelayertests.cpp
Fixes a null de-reference when validating a pipeline that contains a mesh shader, but not a vertex shader. Per the spec:
> pVertexInputState is a pointer to a VkPipelineVertexInputStateCreateInfo structure. **It is ignored
if the pipeline includes a mesh shader stage**.
This change also adds a test for when `pInputAssemblyState` is null, as that should also be ignored (this appears to work without any additional VVL changes):
> pInputAssemblyState is a pointer to a VkPipelineInputAssemblyStateCreateInfo structure which
determines input assembly behavior, as described in Drawing Commands. **It is ignored if the
pipeline includes a mesh shader stage.**
Closes #2696.
=> Fix mesh pipeline validation

BUILD.md
Restore a line that was accidentally removed by #2618.
The line gives the option to specify the SPIRV-Tools install location,
in the case of building via XCode.
=> BUILD.md: Restore XCode SPIRV-Tools config line

layers/subresource_adapter.cpp
The current layer hits a driver assert (mesa, anv) when calling vkBindImageMemory2 on an image with `VK_IMAGE_TILING_DRM_FORMAT_MODIFIER_EXT`. This happens because the layer queries subresource layouts with invalid aspect bits (only `VK_IMAGE_ASPECT_MEMORY_PLANE_*_BIT_EXT` would be allowed).
The issue can be reproduced with existing tests from positivelayertests.
=> layers: Fix drm_format_modifier tiling subresource querying

layers/descriptor_sets.cpp
Take into account descriptors can be mutable in a couple more places in the code to avoid false positives.
Related to #2692.
=> layers: Fix mutable descriptor false positives

layers/core_validation.cpp, tests/vklayertests_portability_subset.cpp
Fix null de-reference for when
`VkGraphicsPipelineCreateInfo::pDepthStencilState` can be ignored/null.
Closes #2699.
=> Fix null depth/stencil when portability is enabled

layers/core_validation.cpp, layers/debug_printf.cpp, layers/generated/vk_typemap_helper.h, layers/gpu_utils.cpp, layers/gpu_utils.h, layers/gpu_validation.cpp, layers/state_tracker.cpp, layers/vk_layer_logging.h, layers/vk_layer_utils.cpp, scripts/helper_file_generator.py
Use LvlInitStruct to initialize "sType" structures to ensure pNext is
initialized as null.
Closes #2628.
=> layers: Use LvlInitStruct

layers/json/VkLayer_khronos_validation.json.in
Surrender validation layer settings to validation layers developers.
Vulkan Configurator will use these settings when loading the validation layer.
The settings are data-driven except for the "validation areas". If you want to add a new setting in this section, you still need to contact me. The rest you are fully in control.
=> layers: add settings to the layer manifest

layers/core_validation.cpp, tests/vklayertests_command.cpp
Remove reports of VUID 02698 where the spec is ambiguous.
See https://gitlab.khronos.org/vulkan/vulkan/-/issues/2602 for more
details.
Closes #2689.
=> layers: Remove some cases of 02698

layers/descriptor_sets.cpp
Part of the mutable descriptor compatibility validation
No state is tracked nor validation applied to mutable descriptors, so if a descriptor is copied from a mutable descriptor, it cannot be validated.
=> Stop validating descriptors copied from mutable descriptors

layers/generated/vk_object_types.h, layers/object_lifetime_validation.h, layers/object_tracker_utils.cpp, scripts/helper_file_generator.py
https://github.com/KhronosGroup/Vulkan-Headers/commit/e01b00657664ac34389d51b04c58dff3eb19a026 fixed some broken logic around `VK_DEFINE_NON_DISPATCHABLE_HANDLE`  that was causing `VK_NULL_HANDLE` to always be defined as `0`.
`VK_NULL_HANDLE` is now correctly defined as `nullptr`, `((void*)0)`, `0ULL` or `0`.
This has exposed some type mismatches in the VVL, which this change fixes.
=> Fix Handle <-> uint64 logic

layers/buffer_validation.cpp, tests/vklayertests_others.cpp
Closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/2718
Was a simple fix so just created this PR quick
Will update VUID when internal MR 4505 is brought into a future header
=> Add check destroying presentable image

BUILD.gn
command_validation.h was included by core_validation_types.h in #2728
=> layers: Fix BUILD.gn

build-android/known_good.json, layers/generated/spirv_tools_commit_id.h, scripts/known_good.json
Also bump Vulkan-Tools to v1.2.176 because the tag is now available
Waiting on internal CI
=> build: Update shader toolchain dependencies

layers/core_validation.h, layers/descriptor_sets.cpp, layers/descriptor_sets.h
Split this giant method into separate methods for each type of descriptor.
NOTE: viewing this change with 'ignore whitespace' on will show that no logic is changed in this refactor.
=> corechecks: Refactor ValidateDescriptorSetBindingData

layers/CMakeLists.txt
The @ONLY option makes the configure_file not change any code which uses
${foo} that is in the file.
=> cmake: configure_file to use @ONLY

layers/buffer_validation.cpp, layers/core_validation.cpp, layers/core_validation.h, layers/core_validation_types.h, layers/descriptor_sets.cpp, layers/image_layout_map.cpp, layers/image_layout_map.h, layers/range_vector.h, layers/vk_layer_data.h
Use a single range_map in ImageSubresourceLayoutMap instead of having 3 separate maps for each type of data tracked. This speeds up construction, lookups and iteration.
Make InitialLayoutStates be a small_vector
Many images appear to need only 1 or 2 InitialLayoutStates, so using a small vector prevents new calls in these cases. Performance appears to fall off if the small vector is size 4. In some cases we're getting over entries 255, so the small vector cannot use uint8_t for its size.
=> corechecks: Simplify Image Layout Transition maps

layers/json/VkLayer_khronos_validation.json.in
A bug caused old versions of vkconfig to crash when loading the layers settings from the layer repository.
To workaround this issue, the layer schema was modified, this change makes the layer manifest to match the updated layer schema.
This change need to be cherry picked to SDK-1.2.176 branch.
=> manifest: Fix layer settings to match layer manifest schema

layers/core_validation.cpp, layers/core_validation.h, layers/core_validation_types.h, layers/parameter_validation_utils.cpp, layers/state_tracker.cpp, tests/CMakeLists.txt, tests/vklayertests_viewport_inheritance.cpp
Add coverage for VK_NV_inherited_viewport_scissor extension
- Don't report validation errors for missing vkCmdSetViewport or vkCmdSetScissor calls when inheriting the viewport and scissor state is enabled.
- Validate a bunch of requirements on vkCmdExecuteCommands. To avoid slowing down validation for those not interested in the extension, these checks are only done when the inheritedViewportScissor2D feature is enabled.
Can be tested with latest NVIDIA Beta Driver: https://developer.nvidia.com/vulkan-driver
Spec: https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#VK_NV_inherited_viewport_scissor
Issues:
- I found it difficult to pick a relevant VUID for reporting many incorrect uses of this extension (failing to provide correct viewport/scissor state for the …
=> VK_NV_inherited_viewport_scissor coverage

layers/image_layout_map.cpp, layers/image_layout_map.h
Commit 5363130b introduced a bug in Image Layout Transition
validation that would cause false postive errors if a program
did multiple updates to a subresource range with different layout
values. Fix this by updating the correct ranges when changing
an existing LayoutEntry.
=> layers: Fix Image Layout range splitting

layers/core_validation.cpp, tests/vklayertests_descriptor_renderpass_framebuffer.cpp
It appears the layers will incorrectly flag the following situation:
- Subpass N renders to an attachment (OPTIMAL layout)
- Subpass N+1 reads the attachment as an input attachment (READ_ONLY_OPTIMAL layout)
* So far so good; no errors. Most use-cases stop here.
- Subpass N+2 renders to the attachment again (OPTIMAL layout)
* Now a warning is emitted saying the attachment is used as _both_ and input-attachment _and_ a color-attachment, but is not GENERAL layout (as is needed when this is the case). This error is incorrect; the attachment is _not_ used as both input- and color-attachment in this sub-pass, so OPTIMAL layout should be OK.
An example of an incorrect error is:
`04-29 13:47:59.294 21585 21625 I VALIDATION: VUID-VkSubpassDescription2-None-04439(ERROR / SPEC): msgNum: 1708087736 …
=> Fix input-attachment checks

layers/core_validation.cpp, tests/vklayertests_descriptor_renderpass_framebuffer.cpp
Both 
- VUID-VkSubpassDescription2-pDepthStencilAttachment-04440
- VUID-VkSubpassDescription-pDepthStencilAttachment-04438
were added recently to the spec, the code was already there to validate, just needed proper label (and test to verify)
=> Label VU for color and depthStencil attachments being the same

layers/core_validation.cpp, layers/core_validation_types.h, layers/state_tracker.cpp, layers/state_tracker.h, tests/vklayertests_pipeline_shader.cpp
closes: https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/2755
Added two validations.
```
VUID-VkPipelineRasterizationProvokingVertexStateCreateInfoEXT-provokingVertexMode-04883
If provokingVertexMode is VK_PROVOKING_VERTEX_MODE_LAST_VERTEX_EXT, then the provokingVertexLast feature must be enabled
```
```
VUID-vkCmdBindPipeline-pipelineBindPoint-04881
If pipelineBindPoint is VK_PIPELINE_BIND_POINT_GRAPHICS and the provokingVertexModePerPipeline limit is VK_FALSE, then pipeline’s VkPipelineRasterizationProvokingVertexStateCreateInfoEXT::provokingVertexMode must be the same as that of any other pipelines previously bound to this bind point within the current renderpass instance, including any pipeline already bound when beginning the renderpass instance
```
The extension …
=> Provoking vertex validation

layers/core_validation_types.h, layers/range_vector.h, layers/state_tracker.cpp, layers/subresource_adapter.cpp, layers/subresource_adapter.h, layers/synchronization_validation.cpp, layers/synchronization_validation.h, layers/vk_layer_data.h
Implement several range traversal optimizations:
1. Reduce recursion and unneeded map copies when traversing ranges in to AccessContext hierarchies
2. Store range generators for attachments, generated at begin renderpass time to minimize construction time
3. Refactor ImageRangeGenerator and ImageRangeEncoder to reduce generator construction time
4. Replace "upper_bound" based range termination checks with direct range value inspection
Useful diagnostic code exists for range generation and traversal temporarily in commit list, but is removed... but obviously can be found again if needed.
=> SyncVal ImageRange traversal optimizations

layers/core_validation_types.h, layers/state_tracker.cpp
Change ValidationStateTracker::PreCallRecordCmdBindPipeline so that it doesn't dereference pViewportState when rasterizerDiscardEnable is true.
[  PASSED  ] 900 tests.
[  FAILED  ] 2 tests, listed below:
[  FAILED  ] VkLayerTest.DisplayPlaneSurface
[  FAILED  ] VkLayerTest.ValidateImportMemoryHandleType
=> Fix: Null pointer dereference in state tracker in PreCallRecordCmdBindPipeline #2770

tests/vkpositivelayertests.cpp
This would have detected 2770 and requires 2776 before merging
=> Add positive test case for ignored pointers at pipeline bind

layers/core_validation.cpp, layers/core_validation.h, layers/parameter_validation_utils.cpp, layers/state_tracker.cpp, layers/state_tracker.h, tests/vklayertests_others.cpp, tests/vkpositivelayertests.cpp
So a bit to digest here but for resources see [internal issue](https://gitlab.khronos.org/vulkan/vulkan/-/issues/2645) and [Vulkan guide section on protected queues](https://github.com/KhronosGroup/Vulkan-Guide/blob/master/chapters/protected.md#protected-queues)
The main thing/issue with the current code is it assumes `queueFamilyIndex` is unqiue, but starting in 1.1 you can have cases for protected queues where it isn't unique (see guide link above).
The core changes are:
- at device creation if 1.1 it will track multiple `VkDeviceQueueCreateInfo` with same `queueFamilyIndex`
- remove duplicate `VkDeviceQueueCreateInfo` check from `StatelessValidation` and moved to `CoreCheck` since I need the Physical Device API version
- changed state tracking to just track the entire queue info (gives …
=> Add missing device queue VUs

layers/generated/vk_safe_struct.cpp, layers/shader_validation.cpp, layers/stateless_validation.h, scripts/helper_file_generator.py, tests/vklayertests_descriptor_renderpass_framebuffer.cpp, tests/vklayertests_gpu.cpp, tests/vklayertests_others.cpp, tests/vklayertests_pipeline_shader.cpp, tests/vkpositivelayertests.cpp, tests/vksyncvaltests.cpp
Changes that let vk_validation_layer_tests run to completion with the following settings:
gcc version 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04)
CMAKE_BUILD_TYPE Debug
CMAKE_CXX_FLAGS_DEBUG -g -Og -D_DEBUG=1 -fsanitize=address
Note there still are many leaks reported with <unknown module> in the stack but no ValidationLayers or test code. These might be caused by failing to clean up vulkan objects allocated by the driver. But the tests will run to completion and it is possible to see leaks or other errors.
=> layers: Fixes to allow unit tests to run with ASan enabled

layers/best_practices_utils.cpp, layers/buffer_validation.cpp, layers/core_validation.cpp, layers/descriptor_sets.cpp, layers/drawdispatch.cpp, layers/generated/chassis.h, layers/parameter_validation_utils.cpp, scripts/layer_chassis_generator.py
gcc and clang both can generate warnings about printf()
errors for any function if they are marked with:
__attribute__ ((format (printf, 4, 5)))
Change-Id: I91535aa12649f6a3a127f6141382a7598e198510
=> layers: Enable printf warnings for Log* methods

tests/vkpositivelayertests.cpp
Skip VkPositiveLayerTest.ProtectedAndUnprotectedQueue on the Shield TV
as it is failing in vkCreateDevice with a return code of
VK_ERROR_INITIALIZATION_FAILED (i.e., not
VK_ERROR_VALIDATION_FAILED_EXT).
=> layers: Skip test failing on Shield TV

layers/buffer_validation.cpp, layers/core_validation_types.h, tests/vklayertests_buffer_image_memory_sampler.cpp
According to Vulkan spec section 7.7.4: Queue Family Ownership Transfer,
If the values of `srcQueueFamilyIndex` and `dstQueueFamilyIndex` are equal, no ownership transfer is performed, and the barrier operates as if they were both set to `VK_QUEUE_FAMILY_IGNORED`.
However the validation layers actually detect ownership transfers by checking that both `srcQueueFamilyIndex` and `dstQueueFamilyIndex` are  `VK_QUEUE_FAMILY_IGNORED`; this leads to incorrect validation errors where the user orders no ownership transfer by setting both barrier queue families to an equal value, but that value does not match the family index of the queue that the barrier is submitted to. This happened to me when I left both queue family indices as the default 0 value but did not submit to queue family 0.
It's …
=> fix false positives for barrier queue ownership transfer detection

layers/core_validation.cpp, layers/core_validation.h, layers/core_validation_error_enums.h, layers/core_validation_types.h, layers/drawdispatch.cpp, layers/shader_validation.cpp, layers/state_tracker.cpp, layers/state_tracker.h
Validation fixes for VK_EXT_vertex_input_dynamic_state:
- Add draw-time validation to check that if the active pipeline has VK_DYNAMIC_STATE_VERTEX_INPUT_EXT enabled then vkCmdSetVertexInputEXT() must have been called (pending spec change https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/4585)
- Add draw-time validation to check that if the active pipeline has VK_DYNAMIC_STATE_VERTEX_INPUT_BINDING_STRIDE_EXT enabled then vkCmdBindVertexBuffers2EXT() or vkCmdSetVertexInputEXT() must have been called
- Ignore the graphics pipeline pVertexInput state if VK_DYNAMIC_STATE_VERTEX_INPUT_EXT is enabled for SPIR-V vertex shader input checking
This was originally in PR https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/2809
=> layers: VK_EXT_vertex_input_dynamic_state fixes

BUILD.gn, layers/CMakeLists.txt, layers/base_node.h, layers/best_practices_utils.cpp, layers/buffer_validation.cpp, layers/core_validation.cpp, layers/core_validation.h, layers/core_validation_types.h, layers/debug_printf.cpp, layers/descriptor_sets.cpp, layers/descriptor_sets.h, layers/drawdispatch.cpp, layers/generated/command_validation.cpp, layers/gpu_utils.h, layers/gpu_validation.cpp, layers/image_layout_map.cpp, layers/shader_module.h, layers/shader_validation.cpp, layers/state_tracker.cpp, layers/state_tracker.h, layers/subresource_adapter.cpp, layers/synchronization_validation.cpp, layers/synchronization_validation.h, scripts/command_validation_generator.py, tests/vklayertests_buffer_image_memory_sampler.cpp, tests/vklayertests_descriptor_renderpass_framebuffer.cpp
Replace the flat command buffer <-> every vulkan object tracking
structures with a tree-like implementation. Now, every vulkan object
is linked directly to the object(s) using it. For example, with the old
implementation, if a descriptor set uses 65k image descriptors,
any command buffer using it would have to maintain links to all 65k
image views. In the new implementation, the descriptor set maintains
65k links and the command buffer only has to track the descriptor set.
This saves many hash map insertions per draw call.
Additionally, the tree structure allows the removal of the in_use
refcounting from all vulkan objects except those directly used by
the queue submit functions. This saves many atomic increments per
submit. Instead, when checking if a non-refcounted object is in use,
the …
=> layers: Optimize command buffer state tracking

layers/generated/vk_extension_helper.h, scripts/helper_file_generator.py, tests/vklayertests_portability_subset.cpp, tests/vkpositivelayertests.cpp
Attempt to test if extensions are being called inside the CreateInstance
hook of any layers.
See Github issues #2468 for motivation and link to more details.
If someone has other ideas as to how to test this, please let me know!
=> tests: Add test for devsim/loader crash

tests/vkpositivelayertests.cpp
This test does a vk::QueueSubmit(), so it needs to vk::QueueWaitIdle()
to make sure the driver is in a good state for the next test.
=> tests: Fix cleanup in VkPositiveLayerTest.CopyImageSubresource

layers/core_validation.cpp, tests/vkpositivelayertests.cpp
Removes the order dependency in CoreChecks::AddAttachmentUse. Also
removes incorrect error report when using the same attachment as a
resolve and input attachment.
Closes #2815.
=> Fix AddAttachmentUse 

BUILD.md, CMakeLists.txt, scripts/common_ci.py
This moves calling `update_deps.py` inside CMakeLists.txt in an attempt to streamline the build a bit and make it look more like a "standard cmake project." i.e., "git clone ... -> cmake ... -> cmake --build ..."
The build type and generator will get passed to `update_deps.py` by default. I also updated the docs to put a sort of "TL;DR" up front; I may be missing something important there, though.
@lunarpapillo @johnzupin This change would break 32b internal CI. If this change looks like something we want, adding the cmake var `NO_UPDATE_DEPS=ON` would need to be added so that things function the same as before (I can make that change...maybe even without breaking all of CI). Or we can change the default behavior to prefer what is necessary for CI, but this seems backwards to me. OR, …
=> build: Update build docs

layers/core_validation_types.h
This works around CFI error for accessing destroyed parts
of IMAGE_STATE from BINDABLE destructor.
Fixes #2825
=> layers: Avoid destroying BINDABLE multiple times

layers/state_tracker.cpp, tests/vklayertests_pipeline_shader.cpp
Previous code recorded provoking vertex info in vulkan v1.1+, but VK_EXT_provoking_vertex supports vulkan v1.0+.
closes: https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/2800
=> Record provoking vertex info in vulkan v1.0+

layers/best_practices_utils.cpp
Fixes running:
dEQP-VK.wsi.win32.swapchain.create.image_swapchain_create_info and
dEQP-VK.wsi.win32.swapchain.destroy.null_handle
with Best Practices enabled
=> Fix swapchain test crashes in Best Practices

tests/vklayertests_buffer_image_memory_sampler.cpp, tests/vkrenderframework.cpp, tests/vkrenderframework.h
The same call sequence to initialize the framework, validate extensions, and get available features has been used in many tests.  This adds a utility and replaces the call sequence in vklayertests_buffer_image_memory_sampler.cpp and can be used in new tests / other files in the future
=> Add utility to check extensions and retrieve features

layers/core_validation.cpp, layers/core_validation_types.h, layers/state_tracker.cpp, tests/vklayertests_buffer_image_memory_sampler.cpp
When the dedicatedAllocationImageAliasing is enabled, it should be possible to bind a compatible image to a VkDeviceMemory even after  the original dedicated image is destroyed. Fix this check by caching the dedicated create info in DEVICE_MEMORY_STATE and using this instead  of looking up the dedicated image at bind time.
Update VkLayerTest.DedicatedAllocationImageAliasing to cover it.
Fixes #2730
=>  layers: Improve VUID-VkBindImageMemoryInfo-memory-02629 checking

tests/vklayertests_best_practices.cpp
Guard against possible overflow in
VkBestPracticesLayerTest.GetSwapchainImagesInvalidCount.
=> tests: Guard against possible overflow

BUILD.md
Trivial fix since the previous instruction is `cd build`
=> docs: Fix build.md example path

layers/descriptor_sets.cpp
This VUID requires that the image layout be VK_IMAGE_LAYOUT_GENERAL
or VK_IMAGE_LAYOUT_SHARED_PRESENT_KHR. By DeMorgan's law that means
the check needs to be !GENERAL && !SHARED_PRESENT.
Fixes #2854
=> corechecks: Fix logic for VUID 04152 checking

layers/best_practices_error_enums.h, layers/best_practices_utils.cpp, tests/vklayertests_best_practices.cpp
Add a best practices check for when depthBiasEnable == VK_TRUE, but there is no depth stencil attachment.
Closes #2855.
=> layers: Depth bias enabled without attachment

BUILD.gn
Missing header from BUILD.gn file.
=> gn: Fix build

layers/core_validation.cpp, layers/core_validation.h, layers/generated/chassis.h, layers/json/VkLayer_khronos_validation.json.in, layers/layer_options.cpp, layers/layer_options.h, layers/shader_validation.cpp, scripts/layer_chassis_generator.py
Skips shader validation if the shader has already been validated and is in the validation cache.
The disable of this feature is a little messy.  I wanted it to be consistent with other disables, but didn't see a need to get it put into the spec.  If others find it too messy, I can start the process of adding it to the spec.
=> Add a shader validation cache to shader validation

CMakeLists.txt, layers/buffer_validation.cpp, layers/gpu_utils.cpp, layers/layer_options.cpp, layers/pipeline_state.h, layers/subresource_adapter.h, layers/synchronization_validation.h, layers/xxhash.c
By default, small_vector class uses uint8_t as size_type. However, there are a couple of spots where uint32_t is used as index for such small_vectors and this generates error in CLANG in strict mode. This PR fixes this error.
The errors look as follows:
```
../layers/subresource_adapter.h:365:88: error: implicit conversion loses integer precision: 'uint32_t' (aka 'unsigned int') to 'small_vector<unsigned long, 4, unsigned char>::size_type' (aka 'unsigned char') [-Werror,-Wimplicit-int-conversion]
inline IndexType GetAspectSize(uint32_t aspect_index) const { return aspect_sizes_[aspect_index]; }
~~~~~~~~~~~~~ ^~~~~~~~~~~~
../layers/synchronization_validation.cpp:2748:49: error: implicit conversion loses integer precision: 'uint32_t' (aka 'unsigned int') to …
```
=> Fixing compilation error by CLANG

layers/best_practices_validation.h
Fixes the following warning on some versions of clang:
```
error: anonymous non-C-compatible type given name for linkage purposes by typedef declaration; add a tag name here
```
=> build: Fix clang build error

BUILD.gn, build-android/cmake/layerlib/CMakeLists.txt, build-android/jni/Android.mk, layers/CMakeLists.txt, layers/core_validation.cpp, layers/pipeline_state.cpp, layers/pipeline_state.h, layers/state_tracker.cpp, layers/state_tracker.h
Somehow these non-inline method definitions escaped the first pass.
=> layer: Move Pipeline state methods to their own file

build-android/known_good.json, scripts/known_good.json
This version picks up fixes that should reduce the possibility
of getting "robin_hood::map overflow" errors.
=> build: Update robin-hood-hashing to 3.11.2

layers/drawdispatch.cpp
`vkCmdDispatchBase` recently added missing common VUs
=> layers: Label vkCmdDispatchBase 02712

layers/gpu_validation.cpp
Now that we have a spirv-tools with the correct enum, use it.
=> gpu: Use correct constant for end of errors

layers/best_practices_utils.cpp, layers/buffer_state.h, layers/buffer_validation.cpp, layers/core_validation.cpp, layers/descriptor_sets.cpp, layers/device_memory_state.cpp, layers/device_memory_state.h, layers/image_state.cpp, layers/image_state.h, layers/ray_tracing_state.h, layers/state_tracker.cpp, layers/state_tracker.h, layers/synchronization_validation.cpp
-Make most fields in DEVICE_MEMORY_STATE and BINDABLE be const.
Fields that don't change after object creation may not need as much
locking for safe accesses.
-Remove DEVICE_MEMORY_STATE::bound_images. All bound images of a
DeviceMemory are already tracked as its parents. Also, they can
clean up their aliasing_images sets in NotifyInvalidate().
-Move memory requirements tracking out of BINDABLE, since all four
derived classes need to implement it differently.
=> layers: Simplify DeviceMemory state objects

layers/core_validation.cpp
VkGraphicsPipelineCreateInfo->pColorBlendState* should be ignored
if the pipeline has rasterization disabled or if the subpass of
the render pass the pipeline is created against does not use
any color attachment.
Fixes #2912
Signed-off-by: Samuel Iglesias Gonsálvez <siglesias@igalia.com>
=> layers: Ignore pColorBlendState in some cases

layers/core_validation.cpp, layers/state_tracker.cpp, layers/state_tracker.h, tests/vklayertests_buffer_image_memory_sampler.cpp
Record these objects as in use by the command buffer executing the barrier so that we can detect if they are deleted too soon.
Fixes #2900
=> layers: Record Buffer and Image objects used in barriers

layers/core_validation.cpp
Fixed a typo on `VUID-vkCmdBindDescriptorSets-pDescriptorSets-01979` error message, than must be used instead of then:
> ... buffer descriptor's range is greater **then** the size of the buffer ...
> ... buffer descriptor's range is greater **than** the size of the buffer ...
=> layers: Fix typo on VUID-01979 error message

layers/debug_printf.cpp, layers/gpu_validation.cpp
SDK testing found some holes in checking for aborts in Debug Printf that are also present in GPU-AV.  This fills those holes.
=> Cover more entry points with checks for abort

layers/core_validation.h, layers/core_validation_error_enums.h, layers/device_state.h, layers/drawdispatch.cpp, layers/generated/parameter_validation.cpp, layers/parameter_validation_utils.cpp, layers/state_tracker.cpp, layers/state_tracker.h, layers/stateless_validation.h, scripts/parameter_validation_generator.py, tests/vklayertests_command.cpp
This brings vkCmdDrawMultiEXT and vkCmdDrawMultiIndexedEXT up to CPU side validation parity with the rest of the draw/dispatch calls.  GPU-AV and Debug Printf support will be in a future PR
=> Add CPU side validation for VK_EXT_multi_draw

layers/core_validation.cpp, layers/generated/chassis.h, layers/json/VkLayer_khronos_validation.json.in, layers/layer_options.cpp, layers/layer_options.h, scripts/layer_chassis_generator.py
VALIDATION_CHECK_DISABLE_IDLE_DESCRIPTOR_SET is now part of ...DISABLE_OBJECT_IN_USE,
because it does the same thing for all non-descriptor objects.
VALIDATION_CHECK_DISABLE_PUSH_CONSTANT_RANGE is removed because it was
not used by the code.
Add manifest descriptions for the rest, and add some other fields needed
by vkconfig.
Fixes #2897
=> layers: Clean up and document check disable options

layers/best_practices_utils.cpp
The imageless flag is in the framebuffer create info, not the renderpass create info
=> Fix imageless framebuffer check

layers/shader_validation.cpp, tests/vklayertests_pipeline_shader.cpp
I wrote these tests a while ago while looking into https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/2835
I was unaware before of the implicit 7 components GLSL injects for vertex shaders and figured other people would be caught off guard. The validation layers properly handle it, but think it could be a better error message. Added to the TODO until I have more time to refactor the shader module code, but for now, the extra tests don't hurt just getting checked in IMO
=> tests: Add Extra Max Component test

layers/best_practices_utils.cpp, layers/best_practices_validation.h, layers/generated/best_practices.cpp, layers/state_tracker.cpp, layers/state_tracker.h, scripts/best_practices_generator.py
Make SWAPCHAIN_STATE_BP derive from SWAPCHAIN_NODE (base swapchain
state) and remove associated state life cycle management in BP VO.
If this seems like a good idea I'll start making these changes incrementally with other state structures.
=> layers: Refactor Swapchain BP state

layers/core_validation.cpp, layers/parameter_validation_utils.cpp, tests/vklayertests_buffer_image_memory_sampler.cpp, tests/vkpositivelayertests.cpp
From https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/2619 this fixes the check for the promoted `samplerMirrorClampToEdge` feature with tests
Also improved error message to make it easier to know which value is the issue instead of making user just check all 3
=> Fix samplerMirrorClampToEdge check

layers/generated/spirv_validation_helper.cpp, scripts/spirv_validation_generator.py, tests/vklayertests_pipeline_shader.cpp, tests/vkpositivelayertests.cpp
https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/2619
Added tests and fixed generated SPIR-V validation to use `kEnabledByCreateinfo`
=> Add shaderDrawParameters tests

layers/generated/chassis_dispatch_helper.h, scripts/layer_chassis_generator.py
ValidationObject::InitObjectDispatchVectors() was previously, after
macro expansion, a ~40000 line function. Some compilers don't handle
huge functions well when performing optimzations, especially ones with
lots of control flow.
Rather than copy pasting a loop ~1000 times, make the loop into a lambda
and call it ~1000 times.
This reduces the compile time of chassis.cpp on my machine from 154s to 33s.
Fixes #2889.
=> chassis: Drastically reduce chassis.cpp compile times

layers/buffer_state.h, layers/state_tracker.cpp
The main change is to use safe_VkBufferCreateInfo to avoid having
to copy parts of it manually.
=> layers: Simplify Buffer and BufferView state objects

layers/buffer_validation.cpp, tests/vkpositivelayertests.cpp
In vkd3d-proton, I ran into many issues with image layout tracking. The main issue is that while the current validation layers track layout per aspect, the validation code would naively check the layout for all aspects at a time, leading to non-sensical errors where a depth-stencil layout would be compared against the stencil layout. The code also didn't handle the `VK_IMAGE_LAYOUT_{DEPTH,STENCIL}_{ATTACHMENT,READ_ONLY}_OPTIMAL` layouts in normalization path. The spec says that the combined image layout enums are equivalent to the separate ones, so the added test case should be in-spec as far as I can tell.
I added a reasonable exhaustive test here that trips all the cases I found.
I'm not sure if I did it the right way since I've never poked into this part of the validation layers …
=> Fix handling of separate depth-stencil layouts

layers/best_practices_error_enums.h, layers/best_practices_utils.cpp, layers/best_practices_validation.h, layers/cmd_buffer_state.cpp, layers/cmd_buffer_state.h, tests/layer_validation_tests.cpp, tests/layer_validation_tests.h, tests/vklayertests_arm_best_practices.cpp, tests/vklayertests_best_practices.cpp, tests/vkrenderframework.cpp, tests/vkrenderframework.h
This is a fairly long-winded PR, but I've tried my best to make the commits flow logically and atomically so that it is easier to review in isolation. I can split the PR into several stages if it helps.
This PR accomplishes:
- First, fix a bug with deferred command buffer ops. They should be cmd_buffer local, not global. Fixes a regression in the state tracking.
- Rewrite clear attachments check to be more accurate. Track which attachments are actually written, and only report errors if clear attachments happens before any access is made to the attachment.
- Repurpose the depth-prepass state tracking struct to be more general, since we will use it to handle attachment access tracking now as well.
- Handle secondary command buffers w.r.t. tracking.
- Add tests to check secondary behavior. …
=> practices: Improve check for redundant clear attachments and redundant attachment usage

layers/shader_module.cpp, layers/shader_module.h, layers/shader_validation.cpp, tests/vklayertests_pipeline_shader.cpp, tests/vkpositivelayertests.cpp
Closes #2950
- `GetSpecConstantByteSize` was only used once, so didn't see a need to break it out as own function. Also make logic easier in one place then trying to over-engineer the function
- confirmed in `spirv-val` source what coverage it does (will make sure its a bool/int/float)
- Added `SpecializationUnused` which should cover @ShabbyX use case
- Added some more test in `SpecializationInvalidSizeMismatch` with various spec constant types to confirm change is still working finding the right size
=> Fix Spec Constant ID not found

layers/best_practices_error_enums.h, layers/best_practices_utils.cpp, layers/best_practices_validation.h, tests/vklayertests_best_practices.cpp
As discussed in #2890, I changed the existing VUIDs for best practices warnings that get logged when enabling special use instance or device extensions. This way, people can filter out messages that apply to special use extension categories specifically. Especially ones related to debugging extensions, which are typically enabled when best practices warnings are enabled, but without disabling warnings on other special use extensions.
=> Making VUIDs for special use extension warning more granular

layers/drawdispatch.cpp
Several VK_EXT_multi_draw indexed CTS tests were failing validation due to
incorrectly triggering VUID-vkCmdDrawMultiIndexedEXT-firstIndex-04938
when calling vkCmdDrawMultiIndexedEXT().
The layers were not taking into account the stride passed to the
function, which was being used to signal extra data between each
VkMultiDrawIndexedInfoEXT structure.
=> layers: Take multi draw stride into account

layers/core_validation.cpp, layers/core_validation.h, layers/descriptor_sets.cpp, tests/vklayertests_pipeline_shader.cpp
Since it's null for compute pipelines. Similar to the attachments pointer.
Intended to fix https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/2932
=> Pass subpasses as pointer rather than reference

layers/best_practices_utils.cpp, layers/buffer_validation.cpp, layers/core_validation.cpp, layers/descriptor_sets.cpp, layers/device_state.h, layers/image_layout_map.cpp, layers/image_state.cpp, layers/image_state.h, layers/state_tracker.cpp, layers/state_tracker.h
Clean up construction of these state objects, especially for
swapchain images.
NOTE that we no longer do 'light normalization' of
IMAGE_VIEW_STATE::create_info.subresourceRange. Code that needs
the normalized version should just use normalized_subresource_range.
=> layers: Simplify Image, ImageView and Swapchain state objects

layers/buffer_validation.cpp, tests/vklayertests_buffer_image_memory_sampler.cpp
Temporarily revert due to crashes seen on AMD hardware.
=> layers: Temporarily revert #2970

tests/vklayertests_buffer_image_memory_sampler.cpp, tests/vklayertests_descriptor_renderpass_framebuffer.cpp, tests/vklayertests_others.cpp, tests/vklayertests_pipeline_shader.cpp
Some devices/devsim locally were failing tests for various reasons, this lets them skip/pass now
=> tests: Fix tests failing on same devices

layers/image_state.cpp, layers/image_state.h, layers/state_tracker.cpp, tests/vkpositivelayertests.cpp
-Fix a crash due to corrupting SWAPCHAIN_IMAGE::bound_images (Issue #2975)
-Fix another crash due to a bad pNext value when creating swapchain images.
=> layers: Fix regressions from PR #2964

CMakeLists.txt, layers/CMakeLists.txt, tests/CMakeLists.txt
@lunarpapillo, assuming this is correct (pending @jeremyg-lunarg's review), the usage would be:
```bash
cmake ... -DVVL_ENABLE_ASAN=ON
```
=> layers: Add ASAN cmake option

tests/layer_validation_tests.cpp
Don't leak expensive window system objects when checking if we
have a window system. There's some non-transient versions of these
objects leaked from VkRenderFramework::InitSurface() that will
require much more effort to clean up.
=> tests: Fix some leaks of X Displays and XCB connections

layers/core_validation.h, layers/core_validation_error_enums.h, layers/shader_module.cpp, layers/shader_module.h, layers/shader_validation.cpp, tests/vklayertests_pipeline_shader.cpp
Reads & writes on storage images require formats based of
VkPhysicalDeviceFeatures:
- shaderStorageImageReadWithoutFormat
- shaderStorageImageWriteWithoutFormat
=> layers: validate storage image reads/writes formats

tests/vklayertests_buffer_image_memory_sampler.cpp, tests/vklayertests_command.cpp
I started a prototype for enabling all tests via an environment variable, but there's some refactoring I want to do that is going to end up taking more time than I'd like.
I will put up a corresponding change for the VulkanTests repo shortly.
=> tests: Temporarily disable failing tests on S10

tests/vkpositivelayertests.cpp
A [recent change](https://github.com/KhronosGroup/Vulkan-ValidationLayers/commit/f4fb2a0b00d10942997e3ff7b93c40b1409a8b2b#diff-6183b85cdce951826f4a64c0a57a1e69a632eb9d464bcffb65b9e5201428b500L96) caused a false positive error for external AHB Formats (the bug has been fixed) but still caused some churn figuring out why internally
I realized I wrote a positive test to protect against this exact regression a year ago #1948 but due to reasons, I never pushed through with it
Here is the same tests (with slight fixes) to prevent another regression going undetected
=> tests: Prevent AHB external image regression

layers/core_validation.cpp, tests/vklayertests_best_practices.cpp, tests/vklayertests_buffer_image_memory_sampler.cpp, tests/vklayertests_others.cpp, tests/vkpositivelayertests.cpp, tests/vkrenderframework.cpp, tests/vkrenderframework.h
Currently when using `VK_KHR_shared_presentable_image` it was always giving an error because `minImageCount` needs to be `1` but `VUID-VkSwapchainCreateInfoKHR-minImageCount-01271` was firing off
This also labels `VUID-VkSwapchainCreateInfoKHR-presentMode-02839`
Wrote a test for both `VUID-VkSwapchainCreateInfoKHR-minImageCount-01271` and `VUID-VkSwapchainCreateInfoKHR-minImageCount-01383` which were missing
=> Fix VK_KHR_shared_presentable_image minImageCount

layers/shader_module.cpp, layers/shader_module.h, layers/shader_validation.cpp
By just adding OpLoad instructions to the def_index map.
=> Simplify shader module GetImageFormatInst()

layers/shader_validation.cpp
This check was making a lot of ANGLE and Dawn tests fail because it
requires that regular sampled images have the NonWritable decoration
(since the format is Unknown), and that's disallowed by the SPIR-V
specification (these decorations are only allowed on storage images).
See also https://github.com/KhronosGroup/Vulkan-Docs/issues/1588
CC @djdeath @ncesario-lunarg
=> layers: Fix ValidateShaderStorageImageFormats to only check storage images

layers/gpu_validation.cpp, layers/gpu_validation.h, layers/state_tracker.cpp
If an opaque buffer address is available by means other than vkGetBufferDeviceAddress/vkGetBufferDeviceAddressKHR/vkGetBufferDeviceAddressEXT a buffer may be requested to be created using this handle (as may be the case with capture/playback tools). In this case calling vkGetBufferDeviceAddress/vkGetBufferDeviceAddressKHR/vkGetBufferDeviceAddressEXT is redundant and may be skipped.
=> layers: Handle pNext usage of VkBufferOpaqueCaptureAddressCreateInfo

layers/core_validation.h, layers/shader_validation.cpp
I want to add more Builtin Limits VU (such as those I left behind in #1950) but realized the VU statement says
> If the **identified entry point** includes any variable in its **interface** that is declared with the SampleMask BuiltIn decoration
So fixed up the function to use `FindEntrypointInterfaces` instead
=> layers: Cleanup ValidateBuiltinLimits

tests/vkrenderframework.cpp
Mesa Intel and RADV (and possibly other drivers) are returning null for
vkGetPhysicalDeviceProperties2KHR when trying to print driver info. Add
a check before using this function.
See https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/3013#issuecomment-885453863 for context.
FYI @nisse-work.
=> tests: Check properties function for valid pointer

tests/vksyncvaltests.cpp
@jeremyg-lunarg looks like this is still causing a crash after #3050. I'm inclined to revert it until we can figure out what's going on. Thoughts?
=> tests: Disable RenderPassAsyncHazard on Pixel 3

layers/buffer_validation.cpp, tests/vklayertests_others.cpp
If VK_KHR_get_physical_device_properties2 is not enabled the VUID for checking queue families in CreateBuffer is different
=> Adding vuid 01391

layers/best_practices_utils.cpp, layers/best_practices_validation.h, layers/buffer_validation.cpp, layers/core_validation.cpp, layers/device_memory_state.cpp, layers/device_memory_state.h, layers/image_state.cpp, layers/image_state.h, layers/state_tracker.cpp, layers/state_tracker.h, layers/synchronization_validation.cpp
PRs #2964 and #2980 made bad assumptions about how these objects interact, especially how SWAPCHAIN_IMAGE::bound_images was handled. 
Remove SWAPCHAIN_NODE::bound_images, which was used to allow all images bound to the same swapchain and index to share the same fake virtual address for sync validation. Instead, store a fake address in SWAPCHAIN_IMAGE and allow Swapchains to have Images as their parent. This allows Swapchain and VK_IMAGE_CREATE_ALIAS_BIT aliasing to work in almost the same way. This also lets bound Images be invalidate if their Swapchain or Surface gets destroyed.
Give SWAPCHAIN_NODE a back pointer to the state tracker so that  its Destroy() can remove Images from the device level handle map.
Fake address lookup is now hidden behind a BINDABLE / IMAGE_STATE method. This …
=> layers: Fix state tracking of Surfaces, Swapchains and Images

layers/core_validation.cpp, tests/vklayertests_imageless_framebuffer.cpp
In CreateFramebuffer if VkFramebufferAttachmentsCreateInfo is in the pNext chain, then all VkFramebufferAttachmentImageInfo in it must have pNext NULL
=> Adding vuid framebuffer attachment image info pnext

layers/core_validation.cpp, tests/vksyncvaltests.cpp
If CmdWaitEvents2KHR is called synchronization2 feature must be enabled
=> Adding vuid 03836

tests/vklayertests_others.cpp, tests/vkpositivelayertests.cpp
Due to the nature of all AHB test being just a copy and paste of a previous tests, went through and added the `LvlInitStruct` to them for future tests as well (such as #3029)
=> tests: Use LvlInitStruct for AHB tests

layers/image_state.h, tests/vkpositivelayertests.cpp
This field used to be a smart pointer and skated by with default
constructor initialization.
Fixes #3087
=> layers: Initialize SURFACE_STATE::swapchain in the constructor

layers/core_validation.cpp, tests/vklayertests_pipeline_shader.cpp
When creating a graphics pipeline, if subpass uses a read-only depth/stencil attachment then depthWriteEnable member of pDepthStencilState must be VK_FALSE
=> Adding vuid 04890

layers/buffer_validation.cpp, tests/vklayertests_buffer_image_memory_sampler.cpp
If VK_KHR_get_physical_device_properties2 is not enabled the VUID for checking queue families in CreateImage is different
=> Adding vuid 01392

layers/core_validation.cpp, tests/vklayertests_descriptor_renderpass_framebuffer.cpp
AcquireNextImage2KHR has a different vuid than AcquireNextImageKHR for retired swapchain
=> Adding vuid 01675

BUILD.md, CMakeLists.txt, build-gn/secondary/build_overrides/spirv_tools.gni, build-gn/secondary/build_overrides/vulkan_validation_layers.gni, build-gn/update_deps.sh, external/CMakeLists.txt, layers/CMakeLists.txt, scripts/known_good.json, scripts/update_deps.py, tests/CMakeLists.txt, tests/vktestframework.cpp, tests/vktestframework.h
Previously we relied on glslang to fetch its known-good SPIRV-Tools, but
this doesn't work if we need a newer version than they provide. This
change adds an entry for SPIRV-Tools to the repo known_good.json so we
can manage the dependency ourselves.
=> Add SPIRV-Tools to known_good.json

layers/shader_validation.cpp
In general warnings are reserved for best practices unless explicitly stated in the Vulkan spec (I missed this in #2777).
FYI @llandwerlin-intel.
=> layers: Remove added warnings from #2777

layers/buffer_validation.cpp, tests/vklayertests_buffer_image_memory_sampler.cpp
If ImageSubresourceRange includes VK_IMAGE_ASPECT_COLOR_BIT then it must not include any of VK_IMAGE_ASPECT_PLANE_0_BIT, VK_IMAGE_ASPECT_PLANE_1_BIT or VK_IMAGE_ASPECT_PLANE_2_BIT
=> Adding vuid 01670

layers/core_validation.cpp, tests/vklayertests_wsi.cpp
AcquireNextImage2KHR has a different vuid than
AcquireNextImageKHR for signaled semaphore
=> Adding vuid 01288

layers/parameter_validation_utils.cpp, tests/vklayertests_others.cpp
If bufferDeviceAddress feature is enabled then VK_EXT_BUFFER_DEVICE_ADDRESS extension must not be in ppEnabledExtensionNames
=> Adding vuid 04748

layers/core_validation.cpp, tests/vklayertests_others.cpp
All elements of pMemoryBarries and pImageMemoryBarriers in CmdWaitEvents must have the same src and dst queue family
=> Adding vuid 02803

layers/core_validation.cpp, layers/generated/parameter_validation.cpp, layers/parameter_validation_utils.cpp, layers/stateless_validation.h, scripts/parameter_validation_generator.py, tests/vklayertests_command.cpp, tests/vklayertests_descriptor_renderpass_framebuffer.cpp
Adds missing manual parameter validation for `vkCmdClearColorImage` and `vkCmdBeginRenderPass*`.
This also adds a null check to avoid a crash at CmdBeginRenderPass time.
Closes #3097.
=> layers: Add VUIDs 04961 and 04962

tests/vklayertests_others.cpp
The test case didn't provide an object when it should of, thus causing driver to crash.
This crash is preventing Vulkan-Loader CI tests from passing.
=> test: Fix ValidateGetPhysicalDeviceVideoFormatProperties

layers/core_validation.cpp, tests/vklayertests_others.cpp
The buffer associated with VkAccelerationStructureBuildGeometryInfoKHR scratchData.deviceAddress must have been created with
VK_BUFFER_USAGE_STORAGE_BUFFER_BIT bit
=> Adding vuid 03674, Validate VkAccelerationStructureBuildGeometryInfoKHR scratchData 

layers/json/VkLayer_khronos_validation.json.in
Old:
0 was allowed but totally disable messages which should be controlled by Debug Action instead to avoid redundant setting.
New: 
Message duplications is explicitly controlled. It requires https://github.com/LunarG/VulkanTools/pull/1584 so that the Duplicated Messages Limit is effectively not outputted in vk_layer _settings.txt which turns out to enable unlimited messages. 
**_I think enable_message_limit should be implemented in the layer side but I live is to the validation layer developers._**
=> Workaround for unlimited duplicate messages

layers/core_validation.cpp, tests/vklayertests_wsi.cpp
Closes #3012
vkGetSwapchainImagesKHR must be called with non-NULL pSwapchainImages
before calling vkQueuePresentKHR
=> Fix issue 3012

layers/core_validation.cpp, tests/vklayertests_viewport_inheritance.cpp
Check if pipeline has discard rectangle dynamic state when inherited viewports and discard rectangles are used
=> Adding vuid 04809

tests/vkpositivelayertests.cpp
This test was using VK_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST without
enabling tessellation.  That caused crashes on some devices.
=> tests: Fix crash in CreatePipelineWithCoreChecksDisabled test

layers/best_practices_utils.cpp, layers/best_practices_validation.h, tests/vklayertests_best_practices.cpp
Use optional rather than raw new to avoid having to remember to clean up this structure.
Fix leaks in test cases too.
=> practices: Fix leaks in struct GraphicsPipelineCIs

layers/vk_layer_utils.cpp
Add the logic to *not* surpress callback actions from vk_layer_settings
to the debug_messenger setup.
=> layers: Add detect default to messenger setup

layers/buffer_validation.cpp, tests/vklayertests_buffer_image_memory_sampler.cpp, tests/vkpositivelayertests.cpp
Check if the command buffer used in CmdFillBuffer was allocated from a pool that supported either graphics or compute operations
=> Adding vuid 00030

layers/parameter_validation_utils.cpp, tests/vklayertests_buffer_image_memory_sampler.cpp
Validate tiling is VK_IMAGE_TILING_DRM_FORMAT_MODIFIER_EXT if and only if VkPhysicalDeviceImageDrmFormatModifierInfoEXT is in pNext chain and if it is and flags contain VK_IMAGE_CREATE_MUTABLE_FORMAT_BIT that pNext also includes VkImageFormatListCreateInfo with non-zero viewFormatCount
=> Adding vuid 02249 02313, Validate VkPhysicalDeviceImageFormatInfo2 with VK_IMAGE_TILING_DRM_FORMAT_MODIFIER_EXT 

layers/cmd_buffer_state.h, layers/core_validation.cpp, layers/state_tracker.cpp, layers/state_tracker.h, tests/vklayertests_command.cpp
Conditional rendering must not be active when EndCommandBuffer is called
=> Adding vuid 01978, Validate EndCommandBuffer conditional rendering is not active

layers/subresource_adapter.h, tests/vklayertests_buffer_image_memory_sampler.cpp, tests/vklayertests_descriptor_renderpass_framebuffer.cpp
This class makes use of placement new to share storage for the 2 different map implementations. But it wasn't calling  the destructor for the maps. This probably only matters for the "big" map (std::map), which allocates separate node  buffers in the heap.
Fix *some* of the leaks in Image and Layout test cases so it is easier to see stuff like this.
=> layers: Fix memory leaks from class BothRangeMap

layers/best_practices_error_enums.h, layers/best_practices_utils.cpp, tests/vklayertests_best_practices.cpp
A mistake that's caught me far too many times. Render passes with a zero-sized render area seem to be allowed by the spec but seem to be rarely intended. They can cause useful side-effects like layout transitions (amongst a whole host of other things), but there's generally a simpler/better replacement if you aren't actually writing to any framebuffer attachments.
I assume I need to write a test for this? If so ping me and I'll add one.
=> Add warning for zero-sized render area

layers/core_validation.cpp, layers/core_validation.h, tests/vklayertests_buffer_image_memory_sampler.cpp
Memory type used in SparseMemoryBind must not have VK_MEMORY_PROPERTY_LAZILY_ALLOCATED_BIT bit
=> Adding vuid 01097, Validate SparseMemoryBind memory type 

layers/best_practices_utils.cpp, layers/best_practices_validation.h, layers/cmd_buffer_state.cpp, layers/cmd_buffer_state.h, layers/core_validation.cpp, layers/core_validation.h, layers/debug_printf.h, layers/gpu_validation.h, layers/state_tracker.cpp, layers/state_tracker.h
Upcoming work in this validation object will require some rather expensive tracking of every command.  Using derived command buffer state object will make it easier to capture this data without forcing the overhead onto all the other validation objects.
=> practices: Use subclassed CMD_BUFFER_STATE

layers/synchronization_validation.cpp, tests/vksyncvaltests.cpp
Add basic support for VK_EXT_load_store_op_none load and store operations, ignoring the memory is "undefined" portion of the behavior as access to undefined memory is not yet tracking in syncval.
=> Add validation for load store op none

layers/state_tracker.cpp
PR #3167 removed these methods from state tracker, but a different
PR added a few more calls right before 3167 merged.
=> layers: Fix state tracker GetCBState() calls that snuck in

layers/core_validation.cpp, layers/core_validation.h, tests/vklayertests_buffer_image_memory_sampler.cpp
The buffer used in CmdBeginConditionalRenderingEXT must have be created with VK_BUFFER_USAGE_CONDITIONAL_RENDERING_BIT_EXT bit
=> Adding vuid 01982, Validate ConditionalRendering buffer usage

layers/core_validation.cpp, tests/vklayertests_buffer_image_memory_sampler.cpp
splintInstanceBindRegionCount in BindImageMemoryDeviceGroupInfo must either be 0 or equal to the number of physical devices in the logical device squared
=> Adding vuid 01636

layers/buffer_validation.cpp, layers/buffer_validation.h, layers/core_validation.cpp, layers/descriptor_sets.cpp, layers/image_layout_map.cpp, layers/image_state.cpp, layers/image_state.h, layers/range_vector.h, layers/subresource_adapter.cpp, layers/subresource_adapter.h, layers/synchronization_validation.cpp, tests/vkpositivelayertests.cpp
Handle more cases where the range we're updating partially overlaps  with an existing range, by only updating the intersection of the two. This seems to require more paranoia about invalidating the cached lower bound after changes.
This fix exposes another problem with VK_IMAGE_CREATE_2D_ARRAY_COMPATIBLE_BIT Images.  These ImageViews affect the entire mip level, not just the slice the view references. Rather than swapping depth and arrayLayer in the Image subresource range, just store the simpler subresource range in the ImageView. 
Fixes #2910
=> layers: Fix ImageSubresourceLayoutMap update corner cases

layers/cmd_buffer_state.cpp, layers/cmd_buffer_state.h, layers/generated/command_validation.cpp, layers/state_tracker.cpp, layers/state_tracker.h, scripts/command_validation_generator.py
This method can be overriden by validation objects to do more detailed tracking, if desired.
Move some parts of command recording to CMD_BUFFER_STATE.
=>  layers: Move command counting to CMD_BUFFER_STATE::RecordCmd()

layers/shader_module.cpp, tests/vkpositivelayertests.cpp
Fixes the case where a shader builtin output is an array. Previously,
writes to built-ins were not correctly identified if the output was an
OpTypeArray.
Closes #3187.
=> layers: Fix shader builtin arrays

layers/android_ndk_types.h, tests/vkpositivelayertests.cpp
For #3155
sets
```c++
// 0x22 (34)
ahb_desc.format = AHARDWAREBUFFER_FORMAT_IMPLEMENTATION_DEFINED;
// 0x20130
ahb_desc.usage = AHARDWAREBUFFER_USAGE_CAMERA_WRITE | AHARDWAREBUFFER_USAGE_GPU_SAMPLED_IMAGE | AHARDWAREBUFFER_USAGE_CPU_WRITE_OFTEN;
```
=> tests: Add external camera AHB test

layers/buffer_validation.cpp, tests/layer_validation_tests.cpp, tests/layer_validation_tests.h, tests/vklayertests_buffer_image_memory_sampler.cpp, tests/vklayertests_command.cpp, tests/vklayertests_descriptor_renderpass_framebuffer.cpp, tests/vklayertests_imageless_framebuffer.cpp, tests/vklayertests_others.cpp, tests/vklayertests_pipeline_shader.cpp, tests/vkrenderframework.cpp, tests/vkrenderframework.h, tests/vktestbinding.h
Changes the default behavior of the ErrorMonitor to always "expect
success." Previously, all validation errors were ignored unless
ExpectSuccess was explicitly called.
Still some failing tests, but getting this up there to see what else CI catches.
Commit summary:
1. Removes a duplicate check in core validation
2. Fixes a bug with 04739
3. Testing framework updates for optionally making the default behavior "expect success" (had to make the default "ignore failures" in order to get the fixes in incrementally)
4. Test fixes found by running the tests with "expect success" default behavior
For the 04739 check, I'm fairly certain it is correct, but still need to verify (planning to with CTS).
This is related to #3177, which should be closed once making default behavior "expect success" can …
=> tests: Change error monitor default

BUILD.md, layers/android_ndk_types.h
The `android_ndk_types.h` needed some cleaning up
PS - this should hopefully not mess with #3088
=> layers: Clean up android_ndk_types.h

layers/shader_validation.cpp, tests/vklayertests_pipeline_shader.cpp, tests/vkpositivelayertests.cpp, tests/vkrenderframework.cpp, tests/vkrenderframework.h, tests/vktestframework.cpp, tests/vktestframework.h, tests/vktestframeworkandroid.cpp, tests/vktestframeworkandroid.h
Closes #2955.
Completely forgot about this (along with many other things I'm sure...).
@sfricke-samsung I think I've convinced myself that your `shaderInt8` tests cover the "less than 4 byte" case I was worried about. I had made some tweaks a while back, but think I reverted them all (let me know if something looks awry).
=> layers: Address issue 2955

layers/core_validation.cpp, tests/vklayertests_descriptor_renderpass_framebuffer.cpp
When creating a renderPass, if pNext chain of VkSubpassDescripton2 contains pDepthStencilResolveAttachment and attachment is not unused, its format features must support VK_FORMAT_FEATURE_DEPTH_STENCIL_ATTACHMENT_BIT
=> Adding vuid 02651, Validate pDepthStencilResolveAttachment

layers/core_validation.cpp, tests/vklayertests_command.cpp
CmdBindPipeline must not be called when transform feedback is active
=> Adding vuid 02323, Validate CmdBindPipeline and transform feedback 

layers/vk_format_utils.cpp, layers/vk_format_utils.h, layers/vk_layer_utils.h
`GetIndexAlignment` should not be in format utils as it has nothing to do with `VkFormats`
=> layers: Move VkIndexType from formats untils

layers/buffer_validation.cpp, tests/vklayertests_buffer_image_memory_sampler.cpp
Closes #2945 
If image has more than 1 sample then imageViewType must be either VK_IMAGE_VIEW_TYPE_2D or VK_IMAGE_VIEW_TYPE_2D_ARRAY
=> Adding vuid 04972, Validate imageViewType with multisample image 

layers/best_practices_utils.cpp
Fix a crash that would occur in the (unlikely) event no vertex
shader (and therefore no pInputAssemblyState) is present at
CreateGraphicsPipelines time.
See https://github.com/KhronosGroup/Vulkan-ValidationLayers/commit/f08084490093b33374e17fbd434b39308bafc4a8#r55614446 for context.
There is no test added as `VkPositiveLayerTest.MeshShaderOnly` will cover this case if mesh shaders are supported on AMD hardware in the future (although, if that happens I would imagine a different extension would be used).
=> layers: Avoid crash without vertex shader

layers/core_validation.cpp, layers/core_validation.h, tests/vklayertests_wsi.cpp
Closes #3222 
Swapchain must not be retired and must have been created with VkSurfaceFullScreenExclusiveInfoEXT in the pNext chain with
fullScreenExclusive equal to VK_FULL_SCREEN_EXCLUSIVE_APPLICATION_CONTROLLED_EXT
=> Fix issue 3222, Adding vuid 02674 02675, Validate AcquireFullScreenExclusiveModeEXT 

layers/core_validation.cpp, layers/core_validation.h, layers/drawdispatch.cpp, tests/vklayertests_command.cpp, tests/vklayertests_pipeline_shader.cpp
Closes #2681
At draw active subpasses image views format features must contain VK_FORMAT_FEATURE_COLOR_ATTACHMENT_BLEND_BIT if pipelines blendEnabled is VK_TRUE
=> Adding vuid 04727, Validate image view format features support blend 

layers/core_validation.cpp, tests/vklayertests_others.cpp
Query pools query type in CmdCopyQueryPoolResults must not be VK_QUERY_TYPE_VIDEO_ENCODE_BITSTREAM_BUFFER_RANGE_KHR or VK_QUERY_TYPE_RESULT_STATUS_ONLY_KHR
=> Adding vuid 04812, Validate CmdCopyQueryPoolResults queryType

tests/vklayertests_pipeline_shader.cpp, tests/vkpositivelayertests.cpp, tests/vkrenderframework.cpp, tests/vktestframework.cpp, tests/vktestframework.h, tests/vktestframeworkandroid.cpp, tests/vktestframeworkandroid.h
Use `uint32_t` instead of `unsigned int` for SPIR-V word size
This is also what `libspirv.h` uses
```c
typedef struct spv_binary_t {
uint32_t* code;
size_t wordCount;
} spv_binary_t;
typedef spv_binary_t* spv_binary;
```
=> tests: Use uint32_t for SPIR-V word size

layers/generated/parameter_validation.cpp, layers/stateless_validation.h, scripts/parameter_validation_generator.py, tests/vkpositivelayertests.cpp
Changes pNext parameter validation to differentiate between physical and
logical devices API calls.
This addresses some discussions found in #3230.
=> layers: Change pNext parameter validation

layers/core_validation.cpp, layers/render_pass_state.cpp, layers/render_pass_state.h
All data in these state objects is set up during construction.
=> layers: Clean up RENDER_PASS_STATE and FRAMEBUFFER_STATE

layers/cmd_buffer_state.h, layers/core_validation.cpp, layers/core_validation.h, layers/state_tracker.cpp, tests/vklayertests_command.cpp
When CmdEndConditionalRenderingEXT is called, conditional rendering must be active, if it was begun outside of a render pass instance it also must be ended outside of a render pass instance, otherwise it must be begun and ended in the same subpass
=> Adding vuid 01985 01986 01987, Validate CmdEndConditionalRenderingEXT 

layers/generated/parameter_validation.cpp, layers/stateless_validation.h, scripts/parameter_validation_generator.py, tests/vkpositivelayertests.cpp
Ignore validating pNext structures that are non-const as this indicates
these structures will be written to by the implementation and may
contain invalid data.
Closes #3122.
=> layers: Ignore non-const pNext validation

layers/buffer_validation.cpp
WG [approved change](https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/4812) for `VUID-VkImageCreateInfo-flags-01572`
=> layers: Fixes to VU 01572

layers/core_validation.h, layers/descriptor_sets.cpp, tests/vkpositivelayertests.cpp
Closes #2518
VUID-VkWriteDescriptorSet-descriptorType-02752 doesn't apply to vkCmdPushDescriptorSetKHR, as it it valid to push an immutable sampler.
=> Fix issue 2518, pushing immutable sampler with vkCmdPushDescriptorSetKHR

layers/descriptor_sets.cpp, layers/descriptor_sets.h, tests/vklayertests_descriptor_renderpass_framebuffer.cpp
Descriptor set update wasn't handling an update larger than the size
of the original binding correctly (Writing multiple bindings with one update).
The specs says "If a binding has a descriptorCount of zero, it is skipped."
Pull request https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/2908 has been closed due to my rebase.
Test has been tested with and without the fix. Test is failing without the fix.
=> Fix overlap descriptor set

.gitignore, docs/creating_tests.md, tests/layer_validation_tests.cpp, tests/layer_validation_tests.h, tests/vklayertests_buffer_image_memory_sampler.cpp, tests/vkrenderframework.cpp, tests/vkrenderframework.h
A common "silent test failure" is not enabling all required extensions
before device creation. This change leverages the information generated
in vk_extension_helper.h to streamline enabling required extensions in
tests.
Related to #3177.
This change more or less "deprecates" using `m_instance_extension_names` and `m_device_extension_names` directly in tests in favor of the various `AddRequired*Extensions` functions. Let me know if anyone has other ideas on how to tackle this problem; I'm not particularly happy with this solution, but it seems to work... If this looks ok, I'll start to convert the other test files incrementally.
=> tests: Add required extension helpers

layers/core_validation_error_enums.h, layers/generated/spirv_validation_helper.cpp, layers/shader_validation.cpp, scripts/spirv_validation_generator.py, tests/vklayertests_pipeline_shader.cpp, tests/vklayertests_portability_subset.cpp
Part of #3288 
This is the initial pass of labeling the majority of the runtime SPIR-V VUs
There a few more VUIDs left (that don't have an issue tracking them yet) because they need to take more time making sure they are actually correct
=> layers: Label Runtime SPIR-V VUs

layers/shader_validation.cpp, tests/vklayertests_pipeline_shader.cpp
part of #3288
Label `VUID-RuntimeSpirv-Location-06272`
> note: currently DeviceProfileLayer layer is not working locally, in case CI fails, I will fix locally and fix tests
=> layers: Label VUID 06272

layers/parameter_validation_utils.cpp, tests/vklayertests_pipeline_shader.cpp
All elements of CreateRayTracingPipelinesKHR must be VK_DYNAMIC_STATE_RAY_TRACING_PIPELINE_STACK_SIZE_KHR
=> Adding vuid 03602, Validate RayTracing DynamicStates 

layers/core_validation.h, layers/shader_validation.cpp
trivial fix to match the function as discussed in https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/3297#discussion_r710224462
=> layers: Fix function name for runtime shader check

CMakeLists.txt, layers/vk_layer_utils.h
Using VVL_CPP_STANDARD set to 17 or higher, which allows use of std::shared_mutex, will improve performance. Make it possible to enable this setting on non-MSVC compilers.
=> layers: Fix option for seting C++ standard and check for std::shared_mutex

layers/vk_layer_utils.h
On Windows, clang sets _MSC_VER and _MSC_FULL_VER so we should
only look at these variables if !defined(__clang__). Add comments
explaining as much of the conditions as are still known.
Closes #3323
=> layers: Fix checking for std::shared_mutex support

tests/vklayertests_gpu.cpp
Shader wasn't executing, so no printfs received, so put reasonable data in the index buffer
=> tests: Fix GpuDebugPrintf on RADV

tests/vklayertests_wsi.cpp
Disable VkLayerTest.TestvkAcquireFullScreenExclusiveModeEXT by default
until test failures are root caused.
We're missing a bunch of test results while this continues to fail. Disabling for now.
=> tests: Disable exclusive FS test

layers/core_validation.cpp, layers/core_validation_error_enums.h, layers/descriptor_sets.cpp, layers/sync_vuid_maps.cpp, tests/layer_validation_tests.cpp, tests/vklayertests_others.cpp
Just some small clean up in the `core_validation_error_enums.h` file as going through seeing what needs to be added to the spec yet
=> layers: Remove unused unassigned VUs

layers/parameter_validation_utils.cpp
Hiya, I ran into a bug with this bit of code always displaying the first format in pViewFormats as the erroneous one. The index printed is correct but the format name isn't (unless i is 0).
This resulted in a very puzzling error message:
```
vkCreateImage(): VkImageFormatListCreateInfo::pViewFormats[1] (VK_FORMAT_R32_SFLOAT) and VkImageCreateInfo::format (VK_FORMAT_R32_SFLOAT) are not compatible.
```
I scanned the contributing guidelines and I'm not too sure if just submitting a pull request like this is all I need to do - let me know if I've missed anything.
Thanks!
=> layers: Fix 04737 error message always printing first format

layers/core_validation.cpp, tests/vklayertests_others.cpp
Buffers used in VkAccelerationStructureKHR must be bound to memory when used in copy command
=> Adding vuid 03718 03719, Validate copied acceleration structures are bound to memory 

layers/buffer_validation.cpp, layers/core_validation_error_enums.h, layers/parameter_validation_utils.cpp
First part of #3225
The WG agreed there should never be a depth/stencil `VkFormat` used for `VkBufferView` or Vertex Input Attribute as they should be using the color formats instead.
There is not going to be a dedicated VU, but we are going to start enforcing CTS to prevent drivers from accidentally exposing the wrong feature flags for depth/stencil formats
This adds 2 checks and wraps a few uses of `FormatElementSize` that should never be called with a depth/stencil format
=> layers: Prevent invalid depth/stencil format

BUILD.gn, build-android/cmake/layerlib/CMakeLists.txt, build-android/jni/Android.mk, layers/CMakeLists.txt, layers/buffer_state.cpp, layers/buffer_state.h, layers/state_tracker.cpp
Query memory requirements and device address during creation.
Add buffer_state.cpp to avoid circular include madness with
state_tracker.h.
=> layers: Make more BUFFER_STATE member data be const

scripts/update_deps.py
Replaces backslashes with forward slashes.
This was necessary for the Vulkan-Loader repo. I built this locally and didn't find any issues, but am okay with dropping the PR if this rocks the boat too much.
=> build: Use forward slashes in update_deps

layers/parameter_validation_utils.cpp
as promised in https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/3346#discussion_r717668075
Changed all the `%d`/`%u` to `PRIu32`
There was only 2 spots where `%d` was actually an `int32_t` instead of `uint32_t` and those are `PRId32`
=> layers: inttypes.h size in parameter validation

layers/state_tracker.cpp
From https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/2766 it seems this adding of `enabled_features.provoking_vertex_features` was added twice
=> layers: Remove redundant provoking vertex feature

layers/render_pass_state.cpp
A recent change to InitRenderPassState (e83bd44) inadvertently switched
the subpass dependency index used to add an implicit barrier to external
from `last_use` to `first_use`. This commit just reverts the index back
to `last_use`.
Fixes #3360
=> layers: Revert typo in RENDER_PASS_STATE init

layers/core_validation.cpp
This avoids permission problems when the layers are used in multi-user systems. Otherwise the user running the layers may not be able to write to that file.
We were hitting this issue in one of our test systems. Note I've only added the solution to the Linux build.
=> layers: make the shader validation cache per-user

layers/shader_validation.cpp
Negative offsets were being cast to unsigned integers, causing them to
wrap and fail the comparison against
VkPhysicalDeviceLimits::maxTexelGatherOffset.
Error found here: https://ci.chromium.org/ui/p/angle/builders/try/linux-clang-rel/24675/overview
Sample validation output before the fix:
> RendererVk.cpp:562 (DebugUtilsMessenger): [ VUID-RuntimeSpirv-OpImage-06377 ] Validation Error: [ VUID-RuntimeSpirv-OpImage-06377 ] Object 0: handle = 0x55b0ea2e74b8, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0xd630c4bb | vkCreateShaderModule(): Shader uses OpImageGather with offset (-32) greater than VkPhysicalDeviceLimits::maxTexelGatherOffset (31). The Vulkan spec states: If an OpImage*Gather operation has an image operand of Offset, ConstOffset, or ConstOffsets the offset value must be less …
=> layers: Fix maxTexelGatherOffset check

layers/render_pass_state.cpp, layers/vk_layer_data.h
Simplify external barriers creation code at DAG creation time and not
during attachment processing.
Also removed  layer_data::make_unique aliasing attempt for C++14
=> Simplify external barrier creation

build-android/known_good.json, layers/generated/spirv_tools_commit_id.h, scripts/generate_source.py, scripts/known_good.json
Includes build fix for SPIRV-tools on some versions of gcc. See
https://github.com/KhronosGroup/SPIRV-Tools/pull/4556.
Closes #3367.
@mikes-lunarg Not sure what else needs to be updated for this?
=> build: Update SPIRV-Tools

layers/buffer_validation.cpp, layers/core_validation.h, layers/device_state.h, layers/state_tracker.cpp
Wraps `FormatRequiresYcbcrConversion` from preventing a false positive when using the extension
=> layers: Add VK_EXT_rgba10x6_formats

layers/core_validation.cpp, layers/core_validation.h, layers/state_tracker.h
The name
```
enum CommandVersion { CMD_VERSION_1 = 0, CMD_VERSION_2 = 1 };
```
was misleading for how it was being used so made everything consistent and added some comments
=> layers: Clean up cmd version naming

layers/buffer_validation.cpp, layers/core_validation.h
When doing https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/3371 I realized we have a single function for `vkCmdCopyImage`, `vkCmdCopyImageToBuffer` and `vkCmdCopyBufferToImage` but was missing the same logic for `vkCmdCopyBuffer`
This just makes it a single nice function
=> layers: Combine ValidateCmdCopyBuffer functions

layers/core_validation.cpp, tests/vkpositivelayertests.cpp, tests/vktestbinding.h
When using 1D image views with imageless framebuffers, ensure that
the height of 1-dimensional image views does not get truncated to 0.
This change also clarifies the wording of 03211 and 03212.
Closes #3484 and #3485.
=> layers: Fix FB size check for 1D images

layers/core_validation.cpp, tests/vkpositivelayertests.cpp
Fix checking line topology class when setting input assembly topology
dynamically.
Closes #3486.
FYI @pdaniell-nv as I _think_ this is correct, but it looks like the original change was intentional.
=> layers: Fix line topology class check

layers/core_validation.h, layers/shader_validation.cpp, tests/vklayertests_pipeline_shader.cpp
adds
- VUID-RuntimeSpirv-OpImageSample-06435
- VUID-RuntimeSpirv-OpImageSample-06436
Tried to make use of the logic already there for the `(max)/(min)TexelGatherOffset` check
=> layers: Add min/maxTexelOffset check

layers/state_tracker.h
Make sure we clear out any old values in the map in Add().
Since this is likely a bug in the state tracker if it happens,
assert if the entry is an overwrite.
=> layers: Stomp old values in ValidationStateTracker::Add()

scripts/spirv_validation_generator.py
To make other things easier (see https://gitlab.khronos.org/vulkan/vulkan/-/issues/2896)
```patch
<spirvextension name="SPV_KHR_variable_pointers">
-    <enable version="VK_API_VERSION_1_1"/>
+    <enable version="VK_VERSION_1_1"/>
<enable extension="VK_KHR_variable_pointers"/>
</spirvextension>
```
will happen in the future XML
Nice part of this change is if merged now, the comment will be a lie for a bit, but when the new headers come in things will just work as :magic_wand:
=> layers: Update spirv xml version generator

layers/core_validation.cpp, layers/device_state.h, layers/state_tracker.cpp, tests/vklayertests_pipeline_shader.cpp
Handle null render pass handles in vkCreateGraphicsPipeline(). This is an error if the feature is not enabled. But it needs to fail in any case until the pipeline creation code can be updated to properly create state objects using the extension.
Add a test case to pass null render pass handles without enabling the extension.
=>  layers: Avoid crashing if VK_KHR_dynamic_rendering is enabled

layers/best_practices_error_enums.h, layers/best_practices_utils.cpp, layers/generated/chassis.cpp, scripts/generate_source.py, scripts/layer_chassis_generator.py, scripts/lvl_genvk.py
All types of validation will output:
`Validation Warning: [ VUID_Undefined ] Object 0: handle = 0x55e86db81ee0, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x79de34d4 | Device Extension VK_KHR_dynamic_rendering support is incomplete, incorrect results are possible.`
Best Practices has problems in vkCreateGraphicsPipelines() so it also warns there:
`Validation Warning: [ UNASSIGNED-BestPractices-DynamicRendering-NotSupported ] Object 0: handle = 0x55f9555b6360, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0xeac72bc0 | vkCreateGraphicsPipelines: pCreateInfos[0].renderPass is VK_NULL_HANDLE, VK_KHR_dynamic_rendering is not supported.`
=> layers: Add warnings if VK_KHR_dynamic_rendering is enabled

layers/core_validation.cpp, layers/parameter_validation_utils.cpp, layers/queue_state.h, layers/state_tracker.cpp, layers/sync_vuid_maps.cpp, tests/vklayertests_others.cpp, tests/vklayertests_pipeline_shader.cpp
Deferred from the last 2 header updates, these commits resolve all outstanding VUID inconsistencies.
=> VUID cleanup

BUILD.gn, build-gn/secondary/build_overrides/vulkan_validation_layers.gni
use_x11 that was added in https://github.com/KhronosGroup/Vulkan-ValidationLayers/commit/1ca0960a36fc9d4a2f5ce1364ece8d45cd66151b
is deprecated in Chromium. Instead, chrome is going to use
Ozone abstraction which has ozone_platform_x11 backend.
Thus, rename this gn to ozone_platform_x11.
=> build: Renamed use_x11 to ozone_platform_x11

layers/core_validation.cpp, layers/gpu_validation.cpp, layers/state_tracker.h
Reduce visibility of state tracker data members, especially the state maps, which are now all private.
=> layers: Make many state tracker data members protected or private

layers/core_validation.cpp, layers/vk_layer_utils.h
Add additional VUs for the VK_KHR_dynamic_rendering extension.
VUIDs for VkRenderingFragmentShadingRateAttachmentInfoKHR, VkRenderingAttachmentInfoKHR
VkCommandBufferBeginInfo, and VkCommandBufferInheritanceRenderingInfoKHR
VUID-VkDeviceQueueCreateInfo-flags-06449
VUID-VkRenderingInfoKHR-imageView-06124
VUID-VkRenderingInfoKHR-imageView-06125
VUID-VkRenderingFragmentShadingRateAttachmentInfoKHR-imageView-06147
VUID-VkRenderingFragmentShadingRateAttachmentInfoKHR-imageView-06149
VUID-VkRenderingFragmentShadingRateAttachmentInfoKHR-imageView-06150
VUID-VkRenderingFragmentShadingRateAttachmentInfoKHR-imageView-06151
VUID-VkRenderingFragmentShadingRateAttachmentInfoKHR-imageView-06152
VUID-VkRenderingFragmentShadingRateAttachmentInfoKHR-imageView-06153 …
=> layers: Add VK_KHR_dynamic_rendering VUs - Change Set #1

layers/buffer_validation.cpp, layers/core_validation.cpp, tests/vklayertests_command.cpp, tests/vklayertests_others.cpp
Based off (and waiting for change to get merged in headers) https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/4775
- Uses `protectedNoFault` correctly by not throwing the validation warnings
- remove `VUID-VkProtectedSubmitInfo-protectedSubmit-01816` and `VUID-VkSubmitInfo2KHR-flags-03885`
- Adds 3 new VUs (not labeled yet) `VUID-VkDeviceCreateInfo-flags-TODO`, `VUID-vkQueueSubmit-queue-TODO`, `VUID-vkQueueSubmit2KHR-queue-TODO`
=> layers: Use protectedNoFault correctly

layers/best_practices_utils.cpp, layers/buffer_validation.cpp, layers/cmd_buffer_state.h, layers/core_validation.cpp, layers/core_validation.h, layers/descriptor_sets.cpp
Remove some places where we were doing unnecessary lookups of
state objects from handles, when there is already a pointer to the
state object available. None of these seem to have a measurable
performance difference, but that might change once we move to
fine grained locking.
=> layers: Remove excess state object lookups

layers/ray_tracing_state.h, layers/state_tracker.cpp, layers/state_tracker.h
Adds the functions:
PostCallRecordBuildAccelerationStructuresKHR
PostCallRecordCopyAccelerationStructureKHR
to the ValidationStateTracker.
This allows for validation of host built acceleration structures
=> layers: Add state tracking for host AS builds

layers/parameter_validation_utils.cpp
Check against stippledRectangularLines being enabled, not
stippledSmoothLines
=> Fix validation error when using VK_LINE_RASTERIZATION_MODE_DEFAULT_EXT

layers/best_practices_utils.cpp, layers/best_practices_validation.h, layers/buffer_validation.cpp, layers/cmd_buffer_state.h, layers/core_validation.cpp, layers/core_validation.h, layers/drawdispatch.cpp
Avoid 2-3 lookups of the same CommandBuffer handle in each draw call.
Fix yet another place where  ImageView and Images are needlessly lookedup.
=> corechecks: Remove extra CommandBuffer, Image and ImageView Get<> calls

layers/cmd_buffer_state.cpp
This function was incorrectly marking queries as RESET rather than
ENDED.
This fixes ValidationStateTracker::PostCallRecordCmdWriteAccelerationStructuresPropertiesKHR.
=> layers: Fix CMD_BUFFER_STATE::EndQueries

layers/subresource_adapter.h, layers/synchronization_validation.h, layers/vk_mem_alloc.h
Starting in C++11, the use of the default copy constructor and
assignment operator is deprecated. The fix is to make the use of the
default copy constructor and assignment operator explicit.
Closes #3520.
=> build: Fix deprecated-copy warnings in clang 13

layers/buffer_validation.cpp, layers/core_validation.cpp, layers/descriptor_sets.cpp, layers/parameter_validation_utils.cpp, layers/shader_validation.cpp, layers/vk_format_utils.cpp, layers/vk_format_utils.h, layers/vk_layer_utils.h
I have a change that generates the `vk_format_utils.cpp` file using the new `<formats>` tags in the 1.2.199 Header's `vk.xml`
There are some things that distract from the real change of generating the code, so decided to make it as a first commit/PR to ease the next on the eyes a bit
commented reasons inline
=> layers: Pre generated format utils changes

layers/core_validation.cpp, layers/core_validation.h
Add VUs for:
VUID-vkCmdBeginRenderingKHR-dynamicRendering-06446
VUID-vkCmdBeginRenderingKHR-commandBuffer-06068
VUID-VkDeviceGroupRenderPassBeginInfo-offset-06166
VUID-VkDeviceGroupRenderPassBeginInfo-offset-06167
VUID-VkDeviceGroupRenderPassBeginInfo-offset-06168
VUID-VkDeviceGroupRenderPassBeginInfo-offset-06169
VUID-vkCmdEndRenderPass-None-06170
VUID-vkCmdEndRenderPass2-None-06171
VUID-VkPipelineRenderingCreateInfoKHR-pColorAttachmentFormats-06064
VUID-VkPipelineRenderingCreateInfoKHR-depthAttachmentFormat-06065
VUID-VkPipelineRenderingCreateInfoKHR-stencilAttachmentFormat-06164
VUID-VkPipelineRenderingCreateInfoKHR-depthAttachmentFormat-06165
VUID-VkPipelineRenderingCreateInfoKHR-multiview-06066
VUID-VkPipelineRenderingCreateInfoKHR-viewMask-06067 …
=> layers: Add various VK_KHR_dynamic_rendering VUs

layers/generated/parameter_validation.cpp, layers/parameter_validation_utils.cpp, scripts/parameter_validation_generator.py
Adds checking of the optional-flag for dereferenced count fields in
other structs when used to specify length of arrays.
This fixes validation issues when the count fields are optional, and the
array length is therefore allowed to be zero.
Specifically, this fixes the following erroneous validation error in
vkGetAccelerationStructureBuildSizesKHR when using a BLAS with
geometryCount of zero:
vkGetAccelerationStructureBuildSizesKHR: parameter pBuildInfo->geometryCount must be greater than 0.
=> scripts: Check optional for deref array lengths

layers/core_validation.cpp, tests/vklayertests_command.cpp, tests/vklayertests_others.cpp
Added tests for the following:
VUID-vkCmdExecuteCommands-pCommandBuffers-06019
VUID-vkCmdExecuteCommands-pBeginInfo-06020
VUID-vkCmdExecuteCommands-pBeginInfo-06025
VUID-vkCmdExecuteCommands-flags-06026
VUID-vkCmdExecuteCommands-colorAttachmentCount-06027
VUID-vkCmdExecuteCommands-imageView-06028
VUID-vkCmdExecuteCommands-pDepthAttachment-06029
VUID-vkCmdExecuteCommands-pStencilAttachment-06030
VUID-vkCmdExecuteCommands-viewMask-06031
VUID-vkCmdBeginRenderingKHR-commandBuffer-06068
VUID-vkCmdBeginRenderingKHR-dynamicRendering-06446
I also added tests for VUID-vkCmdExecuteCommands-contents-06018 and VUID-vkCmdExecuteCommands-flags-06024, but they also generate the following:
UNASSIGNED-CoreValidation-DrawState-InvalidCommandBuffer(ERROR / SPEC): msgNum: 298202768 - 
Validation Error: [ …
=> Tests: Added tests for some dynamic rendering VUIDs

.github/workflows/build_windows.yml
This runner has been deprecated and will be completely removed in the future.
https://github.blog/changelog/2021-10-19-github-actions-the-windows-2016-runner-image-will-be-removed-from-github-hosted-runners-on-march-15-2022/
=> ci: Remove windows-2016 github actions runner

layers/cmd_buffer_state.cpp, layers/core_validation.cpp, layers/query_state.h, layers/state_tracker.cpp, layers/state_tracker.h
To avoid having to lock guard this global map, store query state
in vectors inside the QUERY_POOL_STATE object. These vectors are
allocated at creation time and never resized.
=> layers: remove global queryToStateMap

layers/core_validation.cpp, layers/core_validation.h, tests/vklayertests_descriptor_renderpass_framebuffer.cpp
closes #2311
Redone version of https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/2677 (all information there)
Pending on spec changes in https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/4331
Changes from old PR
- Kept in corechecks for now for ease of feature bits
- Using new wording of spec change, can `continue` out earlier instead of ugly conditional logic used before
- `%u` to `PRIu32`
=> Fix up depthStencilResolve

CMakeLists.txt, layers/CMakeLists.txt, scripts/common_ci.py, scripts/known_good.json, tests/CMakeLists.txt
This allows the build to find dependencies that are in CMAKE_PREFIX_PATH, but the old \*_INSTALL_DIR variables are still supported as well. The only dependency still using the old way is glslang, which will either require a Find\*.cmake script or changes in that repo.
Fixes #3558
=> layers: Use find_package() for the dependencies that support it

layers/best_practices_utils.cpp, layers/best_practices_validation.h, layers/buffer_validation.cpp, layers/cmd_buffer_state.cpp, layers/cmd_buffer_state.h, layers/core_validation.cpp, layers/debug_printf.cpp, layers/debug_printf.h, layers/descriptor_sets.cpp, layers/drawdispatch.cpp, layers/gpu_utils.h, layers/gpu_validation.cpp, layers/gpu_validation.h, layers/pipeline_state.cpp, layers/queue_state.cpp, layers/shader_validation.cpp, layers/state_tracker.cpp, layers/state_tracker.h, layers/synchronization_validation.cpp, layers/synchronization_validation.h
In order to make it feasible to use reduced locking in the validation
layers, it will be necessary for the validation code to hold a
reference count on any state objects that are being used.
Copying shared_ptr's involves atomic operations and is more expensive
than copying raw pointers, so it should be avoided if possible.
Some guidelines:
-Avoid repeated Get<> calls whenever possible. These are a hash lookup,
shared_ptr<> copy, and (eventually) map locking operations.
-Functions that use a state object but don't change ownership should
pass by reference (preferred) or raw pointer.
`void func(Foo &);` or `void func(Foo *);`
-Functions that share ownership (caller keeps reference and callee takes
an addiional reference) should pass a shared_ptr lvalue reference
`void …
=> layers: Only support shared_ptr Get<>() methods

layers/core_validation.cpp
Fixes crash in dEQP-VK.fragment_shading_rate.dynamic_rendering.basic.dynamic.attachment.noshaderrate.keep.keep.1x1.samples1.vs
=> Guard against null pointer dereferences

scripts/common_ci.py
This runs Vulkan-Tools' update_deps.py instead of attempting to
generate Vulkan-Tools files manually. This is less efficient as it
re-clones repos such as Vulkan-Headers, but allows the mock ICD to build
"independently" from VVL.
=> build: Fix mock ICD build in CI

layers/core_validation.cpp
Closes #3270 
The corresponding element of color attachment in the subpass is not identified by the attachment, but the index.
=> Fix colorBlendState attachment index

layers/core_validation.cpp, tests/positive/dynamic_rendering.cpp, tests/positive/pipeline.cpp, tests/vklayertests_command.cpp, tests/vklayertests_descriptor_renderpass_framebuffer.cpp, tests/vklayertests_others.cpp
Removed VUIDs (recently removed from spec):
VUID-VkRenderPassBeginInfo-pNext-02854
VUID-VkRenderPassBeginInfo-pNext-02855
VUID-VkRenderingInfoKHR-pNext-06081
VUID-VkRenderingInfoKHR-pNext-06082
which are duplicates of:
VUID-VkDeviceGroupRenderPassBeginInfo-offset-06166
VUID-VkDeviceGroupRenderPassBeginInfo-offset-06167
Added VUIDs:
VUID-VkDeviceGroupRenderPassBeginInfo-offset-06168
VUID-VkDeviceGroupRenderPassBeginInfo-offset-06169
Updated VUIDs in InvalidDeviceGroupRenderArea test from:
VUID-VkRenderPassBeginInfo-pNext-02854
VUID-VkRenderPassBeginInfo-pNext-02855
to:
VUID-VkDeviceGroupRenderPassBeginInfo-offset-06166
VUID-VkDeviceGroupRenderPassBeginInfo-offset-06167
Added InvalidDeviceGroupRenderAreaDynamicRendering test to cover:
VUID-VkDeviceGroupRenderPassBeginInfo-offset-06168 …
=> Updated render area VUIDs

layers/core_validation.cpp, layers/core_validation.h, layers/drawdispatch.cpp, layers/shader_validation.cpp, tests/CMakeLists.txt, tests/positive/dynamic_rendering.cpp, tests/vklayertests_dynamic_rendering.cpp
VU Statements:
VUID-VkCommandBufferInheritanceRenderingInfoKHR-colorAttachmentCount-06004
VUID-VkCommandBufferInheritanceRenderingInfoKHR-variableMultisampleRate-06005
VUID-vkCmdDraw*-pDepthAttachment-06189
VUID-vkCmdDraw*-pStencilAttachment-06190
VUID-vkCmdDraw*-renderPass-06198
VUID-VkGraphicsPipelineCreateInfo-renderPass-06055
VUID-VkGraphicsPipelineCreateInfo-renderPass-06057
VUID-VkGraphicsPipelineCreateInfo-renderPass-06058
VUID-VkGraphicsPipelineCreateInfo-renderPass-06060
VUID-VkGraphicsPipelineCreateInfo-renderPass-06062
VUID-VkRenderingAttachmentInfoKHR-imageView-06129
VUID-VkRenderingAttachmentInfoKHR-imageView-06130
Tests:
VUID-VkCommandBufferInheritInfoKHR-colorAttachmentCount-06004
VUID-VkCommandBufferInheritInfoKHR-variableMultisampleRate-06005 …
=> layers: Add VK_KHR_dynamic_rendering VUs

tests/vklayertests_descriptor_renderpass_framebuffer.cpp
lack of `LvlInitStruct<VkMultisamplePropertiesEXT>();` was crashing on my machine, fixed rest of test to use `LvlInitStruct` as well
=> tests: Fix InvalidSampleLocations test

layers/generated/parameter_validation.cpp, scripts/parameter_validation_generator.py, tests/vklayertests_wsi.cpp
Function manual_PreCallValidateCreateWin32SurfaceKHR already existed, but was never called
Closes #3628
=> Validate creating win32 surface

layers/state_tracker.cpp
Per Vulkan specs for VkGraphicsPipelineCreateInfo (see https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkGraphicsPipelineCreateInfo.html), its `pDynamicState` member can be a nullptr. Dereferencing nullptr could cause an undefined behavior.
=> layers: Fix a deref nullptr bug in StateTracker

layers/core_validation.cpp, layers/descriptor_sets.cpp, layers/descriptor_sets.h, layers/image_state.cpp, layers/image_state.h, layers/query_state.h, layers/shader_validation.h
These state objects are 'easy' to make thread safe because non-const data can be fully encapsulated with get methods that do appropriate locking.
=> layers: Make SURFACE_STATE, DESCRIPTOR_POOL_STATE, QUERY_POOL_STATE and ValidationCache threadsafe

layers/buffer_validation.cpp, layers/core_validation.cpp, layers/state_tracker.cpp, layers/state_tracker.h, layers/vk_layer_utils.h
Use the thread safe unordered_map for all state objects. This makes
it safe to call Add<>(), Get<>() or Remove<>() without holding a
lock. Note that because Get<>() returns a shared_ptr to the state
object, it will not be deleted while the caller holds this reference.
This does make iterating all state objects even more expensive, but
that was already a bad thing to do anyways.
=> layers: Use concurrent_ordered_map for state objects

layers/state_tracker.cpp, layers/state_tracker.h
A previous change (https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/3370) makes state tracker only set up the queue state objects on vkCreateDevice() instead of on each vkGetDeviceQueue() call.
However, this breaks some devices (e.g. goldfish-vulkan virtual ICD which is used for Android and Fuchsia emulator) where it could possibly return different queue handles on vkGetDeviceQueue().
In order to handle this case, state tracker should still try to update the queue map on each vkGetDeviceQueue() call.
TEST: vkreadback (on Fuchsia emulator)
Change-Id: Ib7a3f3b9808b5a7067bbcf0d1d97f7d7869dfd84
=> layers: Set up QUEUE_STATE when getting device queue

layers/core_validation.cpp, tests/vklayertests_descriptor_renderpass_framebuffer.cpp
Added tests for:
VUID-vkCmdEndRenderingKHR-None-06161
VUID-vkCmdEndRenderingKHR-commandBuffer-06162
VUID-vkCmdEndRenderPass-None-06170
VUID-vkCmdEndRenderPass2-None-06171
Tweaked a couple of EndRendering/EndRenderpass VUIDs that were incorrectly triggering when incorrectly mixing types of renderpass instance
=> 2 EndRendering/EndRenderpass tests and some minor VUID tweaks

layers/core_validation.cpp, layers/core_validation.h, layers/queue_state.cpp, layers/queue_state.h, layers/state_tracker.cpp, tests/positive/sync.cpp
Make all non-const member data private and restructure semaphore tracking to allow it to eventually be made thread safe. The biggest change is that each semaphore's state now keeps a queue of pending operations, which removes the need to frequently walk all pending submissions in every queue.
Add VkPositiveLayerTest.QueueSubmitTimelineSemaphore2Queue to show that this PR fixes #3590
=> layers: Further clean up of FENCE_STATE, SEMAPHORE_STATE and QUEUE_STATE

layers/shader_validation.h
Even though it is invalid to try to merge a validation cache with
itself, avoid deadlock if it happens.
VkLayerTest.ValidationCacheTestBadMerge already tests that self-merging
is invalid.
=> layers: Avoid self-merge deadlock in ValidationCache::Merge()

layers/generated/layer_chassis_dispatch.cpp, layers/generated/layer_chassis_dispatch.h, scripts/layer_chassis_dispatch_generator.py
Fixes #3645. Object wrapping should be independent to memory tracking.
=> scripts: Fix object wrapping in ray trace pipeline creation

layers/core_validation.cpp
This was causing a crash in
dEQP-VK.synchronization.timeline_semaphore.sparse_bind.no_wait_sig
=> corechecks: Fix a crash in PreCallValidateQueueBindSparse()

layers/cmd_buffer_state.cpp, layers/cmd_buffer_state.h, layers/core_validation.cpp, layers/descriptor_sets.cpp, layers/descriptor_sets.h, layers/gpu_validation.cpp, layers/pipeline_state.cpp, layers/pipeline_state.h, layers/state_tracker.cpp, layers/synchronization_validation.cpp
Create push DescriptorSets with std::make_shared<>() so that
they can be used more like normal ones.
=> layers: Simplify push DescriptorSet management

layers/core_validation.cpp, layers/generated/parameter_validation.cpp, layers/generated/parameter_validation.h, layers/parameter_validation_utils.cpp, layers/stateless_validation.h, scripts/parameter_validation_generator.py, tests/vklayertests_others.cpp, tests/vklayertests_pipeline_shader.cpp
- Fix all of the 203 VUID inconsistencies
- Add validation for surface handles which are marked optional in vk.xml but are really only optional if VK_GOOGLE_surfaceless_query is enabled.
=> Validation fixes for the 1.2.203 header

layers/state_tracker.cpp
vkEnumerateDeviceExtensionProperties can return 0 for propertyCount
See dEQP-VK.api.device_init.create_instance_device_intentional_alloc_fail
=> Don't index into empty vector

scripts/common_ci.py
There's a problem with this new feature in the mock ICD-only CI environment.
=> build: Disable loader physical device sorting in github CI

BUILD.gn, build-android/cmake/layerlib/CMakeLists.txt, build-android/jni/Android.mk, layers/CMakeLists.txt, layers/base_node.cpp, layers/base_node.h, layers/best_practices_utils.cpp, layers/buffer_state.h, layers/cmd_buffer_state.cpp, layers/cmd_buffer_state.h, layers/core_validation.cpp, layers/descriptor_sets.cpp, layers/descriptor_sets.h, layers/device_memory_state.h, layers/image_state.cpp, layers/image_state.h, layers/pipeline_state.cpp, layers/render_pass_state.cpp, layers/render_pass_state.h, layers/state_tracker.h
Maintaining the tree of which objects are in use by command buffers is performance critical and also likely to cause interactions between threads. Make access to the tree thread safe by guarding each nodes parent_nodes_ set with a separate r/w lock.
=> layers: Add BASE_NODE tree locking

layers/buffer_validation.cpp, layers/cmd_buffer_state.cpp, layers/cmd_buffer_state.h, layers/core_validation.cpp, layers/core_validation.h, layers/drawdispatch.cpp, layers/queue_state.cpp, layers/state_tracker.cpp, layers/state_tracker.h, layers/vk_layer_utils.h
CMD_BUFFER_STATE is much more complicated than other state
objects. At this point it is not possible to encapsulate
all of its non-const member data without massive code changes
and probably much worse performance.
Instead, code that uses this object must manage its locking.
The easiest way is to use GetRead() or GetWrite() to retrieve
a pre-locked pointer. Code in a class derived from
ValidationStateTracker MUST NOT hold a lock on a command buffer
when it calls a method in the base class or deadlock will result.
There are some holes in the locking in the lamda / std::function callbacks
used to set up submit-time validation.  This is because for secondary
command buffers, some of the callbacks are transferred to the
primary command buffer so it isn't easy to keep track on if the
state …
=> layers: Make CMD_BUFFER_STATE threadsafe

layers/core_validation.cpp, layers/drawdispatch.cpp, tests/vklayertests_dynamic_rendering.cpp
Add VUIDs for:
VUID-vkCmdDraw-pDepthAttachment-06181
VUID-vkCmdDraw-pStencilAttachment-06182
Moved VUID for:
VUID-vkCmdDraw-colorAttachmentCount-06188
Fixes for dynamic rendering with sample count structure
Added tests for:
VUID-vkCmdDraw-viewMask-06178
VUID-vkCmdDraw-colorAttachmentCount-06179
VUID-vkCmdDraw-colorAttachmentCount-06180
VUID-vkCmdDraw-pDepthAttachment-06181
VUID-vkCmdDraw-pStencilAttachment-06182
VUID-vkCmdDraw-colorAttachmentCount-06185
VUID-vkCmdDraw-pDepthAttachment-06186
VUID-vkCmdDraw-pStencilAttachment-06187
VUID-vkCmdDraw-colorAttachmentCount-06188
VUID-vkCmdDraw-pDepthAttachment-06189
VUID-vkCmdDraw-pStencilAttachment-06190
=> More dynamic rendering draw time VUIDs and tests

layers/core_validation.cpp
layers: Fix ValidatePipelineDrawtimeState crash
Exception thrown: read access violation.
pPipeline->create_info.graphics.**pColorBlendState** was nullptr.
=> layers: Fix ValidatePipelineDrawtimeState crash

build-android/jni/Android.mk
Add vklayertests_imageless_framebuffer.cpp to Android build.
=> build: Add missing Android tests

layers/buffer_validation.cpp, layers/cmd_buffer_state.cpp, layers/cmd_buffer_state.h, layers/core_validation.cpp, layers/core_validation.h, layers/image_state.cpp, layers/image_state.h, layers/qfo_transfer.h, layers/vk_layer_utils.h, tests/vklayertests_wsi.cpp
Make the global Queue Family Ownership Transfer state be thread safe by using vl_concurrent_unordered_map.
Move the global Image Layout state into an IMAGE_STATE shared_ptr member that is only setup by CoreChecks code.  This avoids repeated lookups into a global map.  It also allows aliasing images to directly use the same layout state, rather than repeating layout state updates by walking IMAGE_STATE::aliasing_images, This lets it be thread safe with a lock around each layout map. The original code would have a required some way to manage locking of all IMAGE_STATE structures whenever an aliasing image was created or destroyed.
=> layers: Make global QFO and Image Layout state threadsafe

layers/core_validation.cpp, layers/core_validation.h, layers/core_validation_error_enums.h, layers/generated/chassis.cpp, layers/generated/chassis.h, layers/generated/chassis_dispatch_helper.h, layers/json/VkLayer_khronos_validation.json.in, layers/layer_options.cpp, layers/layer_options.h, layers/vk_layer_config.cpp, layers/vk_layer_settings.txt, scripts/layer_chassis_generator.py
WIP! This is one of the last changes I intend to merge for the locking improvements, but it needs sooner review because it involves user-visible names that need to end up in documentation in several different places.
Add a setting to make calls to ValidationObject::ReadLock() and
WriteLock() be no-ops, because locking in other parts of the code
has made these global locks unnecessary.
Currently this only affects Core Validation, but eventually it should
also change the behavior of Best Practices and Synchronization
Validation.
The setting defaults to off for now and there is logging when fine grained
locking is enabled, since this is an experimental feature which
make cause stability problems or incorrect errors to be reported.
Once this stabilizes, the setting will default to on and the …
=> corechecks: Add setting to enable fine-grained locking

layers/core_validation.cpp
ValidateRenderingAttachmentInfoKHR() doesn't need to access
command buffer state. Its calling code already has a read-locked
command buffer, so this extra call could lead to deadlock.
=> corechecks: Remove extra GetRead() call in dynamic rendering

layers/core_validation.cpp, tests/layer_validation_tests.cpp, tests/vklayertests_buffer_image_memory_sampler.cpp, tests/vklayertests_descriptor_renderpass_framebuffer.cpp, tests/vklayertests_others.cpp, tests/vklayertests_pipeline_shader.cpp
List of tests that fixes this PR (between brackets are [status before change] [marked as fixed] [status after change]):
```
VkLayerTest.RayTracingPipelineCreateInfoKHR                         [CRASH] [FIXED] [PASS]
VkLayerTest.ValidateGetRayTracingCaptureReplayShaderGroupHandlesKHR [CRASH] [FIXED] [CAN'T RUN]
VkLayerTest.RayTracingLibraryFlags                                  [CRASH] [FIXED] [PASS]
VkLayerTest.CreateImageViewInvalidSubresourceRange                  [CRASH] [FIXED] [PASS]
VkLayerTest.ValidateCreateAccelerationStructureKHR                  [CRASH] [FIXED] [FAILS]
VkLayerTest.ValidateCreateAccelerationStructureKHRReplayFeature     [CRASH] [FIXED] [FAILS]
VkLayerTest.ValidateCmdTraceRaysKHR                                 [CRASH] [FIXED] [FAILS] …
```
=> Fix crashes when running with DefaultSuccess

layers/shader_module.cpp, layers/shader_module.h
Was touching other code in `shader_module.cpp` and wanted to quick add this nit as would be confusing in the next slightly larger PR
=> layers: Consistent shader module names

layers/core_validation.cpp, tests/vklayertests_descriptor_renderpass_framebuffer.cpp, tests/vklayertests_imageless_framebuffer.cpp
- Adding validations for 02746 and 02747 regarding fragment density map extension + tests
- Removed obsolete validation 02744 (which seems to come from an older version of the spec)
=> Adding validations for 02746 and 02747 regarding fragment density map extension + tests

tests/vklayertests_best_practices.cpp
Most tests don't look at performance warnings, but
VkBestPracticesLayerTest.UseDeprecatedInstanceExtensions does.
Make it ignore the fine grained locking warning if it comes out.
=> tests: Ignore locking perf warning in best practices test

tests/vkrenderframework.cpp
Adds support for setting the VK_LAYER_TESTS_SKIP_PLATFORM_CHECK
environment variable to ignore platform checks per test, effectively
forcing all tests to run regardless of platfom (except for tests that
are removed/disabled at compile time such as Android, Win32, etc.).
@lunarpapillo found this while going though some stale local branches. Do you still want this?
=> tests: Add env var to enable all tests

LAYER_CONFIGURATION.md, docs/fine_grained_locking_usage.md
This change also documents settings related to message filtering
and the environment variable equivalents to some of the file
settings.
=> docs: Document layer settings for fine grained locking

layers/shader_module.cpp, layers/shader_module.h, layers/shader_validation.cpp
Adds `DescribeInstruction` to improve SPIR-V based error message
In future plan to add to more `LogError` as well as make use of the `OpName` when possible
------
Example 1
```
[ VUID-RuntimeSpirv-vulkanMemoryModel-06265 ] Object 0: handle = 0x3853790, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x7ab8899 | VkPhysicalDeviceVulkan12Features::vulkanMemoryModel is enabled and VkPhysicalDeviceVulkan12Features::vulkanMemoryModelDeviceScope is disabled, but Device memory scope is used.
```
now looks like
```
[ VUID-RuntimeSpirv-vulkanMemoryModel-06265 ] Object 0: handle = 0x2f37850, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x7ab8899 | VkPhysicalDeviceVulkan12Features::vulkanMemoryModel is enabled and VkPhysicalDeviceVulkan12Features::vulkanMemoryModelDeviceScope is disabled, but …
```
=> layers: Add helper to print out spirv instruction

layers/core_validation.h, layers/shader_module.cpp, layers/shader_module.h, layers/shader_validation.cpp
Slight refactoring of #2777 (cc @djdeath)
1. Moved to the per-instruction static check loop to avoid looping entire module 2 extra times
2. Got rid of `GetImageFormatInst` in favor of being able to make assumptions that the `spirv-val` check will give us
a. To be fair, this function had warnings removed (#3037) and also didn't account for non-storage images using `OpTypeSampledImage`
3. Created new `GetTypeId` helper function (matches `spirv-val` logic) which we can now use thanks to the new `OpcodeHasType` SPIR-V generated function we have now!
=> layers: Refactoring ValidateShaderStorageImageFormats

tests/vkrenderframework.cpp, tests/vkrenderframework.h
Disable the IsDriver check if the VK_LAYER_TESTS_SKIP_PLATFORM_CHECK
environment variable is set.
=> tests: Disable driver check

scripts/common_ci.py
Ensure the mock ICD builds with its own version of Vulkan-Headers.
=> build: Fix mock ICD build

layers/best_practices_utils.cpp, layers/core_validation.cpp, layers/core_validation.h, layers/debug_printf.cpp, layers/debug_printf.h, layers/generated/spirv_validation_helper.cpp, layers/gpu_utils.cpp, layers/gpu_utils.h, layers/gpu_validation.cpp, layers/gpu_validation.h, layers/pipeline_state.cpp, layers/pipeline_state.h, layers/shader_module.cpp, layers/shader_module.h, layers/shader_validation.cpp, layers/state_tracker.h, scripts/spirv_validation_generator.py
- Consistent name for `SHADER_MODULE_STATE` variables
- use `uint32_t` instead of `unsigned`/`unsigned int` as SPIR-V is specified as a 32-bit word IR
=> Shader Module consistency cleanup

scripts/common_ci.py
This reverts commit df4e586b435b0ab69c5b4e188e1b7fbac28b2212.
The loader bug that required this change has been fixed.
=> build: Reenable loader physical device sorting in github CI

tests/positive/pipeline.cpp, tests/vklayertests_command.cpp, tests/vklayertests_descriptor_renderpass_framebuffer.cpp, tests/vklayertests_imageless_framebuffer.cpp, tests/vklayertests_viewport_inheritance.cpp, tests/vklayertests_wsi.cpp
Fixed following tests when `defaultSuccess` is enabled:
```
VkPositiveLayerTest.PhysicalStorageBuffer                                [CRASH] [FIXED] [PASS]
VkLayerTest.TransformFeedbackCmdBindTransformFeedbackBuffersEXT          [CRASH] [FIXED] [PASS]
VkLayerTest.TransformFeedbackCmdBeginTransformFeedbackEXT                [CRASH] [FIXED] [PASS]
VkLayerTest.TransformFeedbackCmdEndTransformFeedbackEXT                  [CRASH] [FIXED] [PASS]
VkLayerTest.InvalidClearColorAttachmentsWithMultiview                    [CRASH] [FIXED] [PASS]
VkLayerTest.InvalidSampleLocations                                       [CRASH] [FIXED] [PASS]
VkLayerTest.DrawWithPipelineIncompatibleWithRenderPassFragmentDensityMap [CRASH] [FIXED] [PASS]
VkLayerTest.InvalidCreateDescriptorPoolAllocateFlags …
```
=> Fix errors when defaultSuccess is chosen

layers/best_practices_utils.cpp, layers/buffer_validation.cpp, layers/cmd_buffer_state.cpp, layers/core_validation.cpp, layers/descriptor_sets.cpp, layers/drawdispatch.cpp, layers/shader_validation.cpp, layers/state_tracker.cpp, layers/synchronization_validation.cpp
For GetRead<>, GetWrite<> and Get<>, adding const to the return value declaration makes the returned pointer object const, which is irrelevant. The pointer held by the object should already have the appropriate constness.
But shared_ptr<>.get() returns a raw pointer that should have 'const' and / or '*' in the declaration for a variable holding its result.
This was raised as a problem in PR #3659
=> layers: Clean up result variable declarations for GetRead<>(), GetWrite<>(), Get<>() and shared_ptr<>.get()

layers/shader_validation.cpp, tests/positive/pipeline.cpp
Don't try to validate FS outputs if rasterization is disabled. We rely
on information from pColorBlendState, which _must_ be null (as it must
be ignored) if rasterization is disabled.
FYI @zmike.
=> layers: FS output validation crash

layers/buffer_validation.cpp, tests/vklayertests_command.cpp
Fixes issue #3651. Correct optimal layout chosen when copying image for performance warning. If we are copying from and to the same image and subresource, layout should be VK_IMAGE_LAYOUT_GENERAL since it's the only option.
=> No perf warning when copying from and to same image

tests/layer_validation_tests.cpp, tests/positive/shaderval.cpp, tests/vklayertests_descriptor_renderpass_framebuffer.cpp, tests/vklayertests_others.cpp, tests/vkrenderframework.h, tests/vksyncvaltests.cpp
As promised in my 1.3 PR, here are changes to SetTargetApiVersion to avoid the gymnastics formerly necessary to get the best available api version.  Also adds a SPIRV 1.6 sanity test, and uses AddRequiredExtensions in the tests added with 1.3.  The best available api version change caused some tests to run on Android when they used to be skipped and some changes were necessary in those cases.
=> Follow-on test changes from 1.3 PR

layers/core_validation.cpp, layers/drawdispatch.cpp, layers/pipeline_state.h, tests/vklayertests_dynamic_rendering.cpp, tests/vklayertests_pipeline_shader.cpp
VU Statements:
VUID-VkGraphicsPipelineCreateInfo-renderPass-06053
VUID-VkGraphicsPipelineCreateInfo-renderPass-06054
VUID-VkRenderingAttachmentInfoKHR-imageView-06145
VUID-VkRenderingAttachmentInfoKHR-imageView-06146
VUID-VkRenderingInfoKHR-imageView-06107
VUID-VkRenderingInfoKHR-imageView-06108
VUID-VkRenderingInfoKHR-imageView-06109
VUID-vkCmdDrawMeshTasksIndirectNV-*
VUID-vkCmdDrawMeshTasksIndirectCountNV-*
VUID-vkCmdDrawIndirectByteCountEXT-*
Tests:
VUID-VkGraphicsPipelineCreateInfo-renderPass-06053
VUID-VkGraphicsPipelineCreateInfo-renderPass-06054
VUID-VkRenderingAttachmentInfoKHR-imageView-06129
VUID-VkRenderingAttachmentInfoKHR-imageView-06132
VUID-VkRenderingAttachmentInfoKHR-imageView-06135
VUID-VkRenderingAttachmentInfoKHR-imageView-06136 …
=> layers: Add VK_KHR_dynamic_rendering VUs and Tests

layers/core_validation_error_enums.h, layers/shader_validation.cpp, tests/positive/shaderval.cpp, tests/vklayertests_pipeline_shader.cpp
Label `VUID-RuntimeSpirv-Workgroup-06530`
`maxComputeSharedMemorySize` has a statement for `VK_KHR_workgroup_memory_explicit_layout`
> When variables declared with the Workgroup storage class are explicitly laid out (hence they are also decorated with Block), the amount of storage consumed is the size of the largest Block variable, not counting any padding at the end.
So added tests making sure validation was not doing a `ADD` and was doing a `MAX` (which it does :tada:)
=> layers: Label 06530 and add testing

tests/positive/shaderval.cpp
Wrote test for #3035 but seems to be not properly setting the `shaderInt8` values for `CreateSetSpecConstantDefaultValuePass`... but this might be a `spirv-opt` issue actually
Wanted to post the test so it doesn't get lost
=> tests: Add extra positive spec constant

layers/core_validation.cpp, tests/vklayertests_others.cpp
This validation change is related to this Vulkan 1.3 spec fix: https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/5034
Without this change an application attempting to use the new Vulkan 1.3 extended dynamic state will get false validation errors:
```
Validation Error: [ VUID-vkCmdSetStencilOp-None-03351 ] Object 0: handle = 0x27441dea3c0, type = VK_OBJECT_TYPE_COMMAND_BUFFER; | MessageID = 0x792ad08 | vkCmdSetStencilOp: extendedDynamicState feature is not enabled. The Vulkan spec states: The extendedDynamicState feature must be enabled ([https://vulkan.lunarg.com/doc/view/1.3.203.0/windows/1.3-extensions/vkspec.html#VUID-vkCmdSetStencilOp-None-03351](https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fvulkan.lunarg.com%2Fdoc%2Fview%2F1.3.203.0%2Fwindows%2F1.3-extensio …
```
=> layers: Fix Vulkan 1.3 extended dynamic state validation

layers/generated/vk_safe_struct.cpp, scripts/helper_file_generator.py
Fixes crash with BP running dEQP-VK.dynamic_rendering.basic.single_cmdbuffer and other dynamic rendering tests
=> Initialize safe struct counts

layers/best_practices_utils.cpp, tests/vklayertests_arm_best_practices.cpp
Fixes a crash running dEQP-VK.api.pipeline.pipeline_invalid_pointers_unused_structs.graphics with BP enabled.
Requires adding depth attachment to VkArmBestPracticesLayerTest.DepthPrePassUsage
=> Ignore pointers where appropriate in Best Practices

layers/base_node.h, layers/buffer_state.h, layers/descriptor_sets.cpp, layers/descriptor_sets.h, layers/device_memory_state.h, layers/image_state.h, layers/synchronization_validation.cpp, tests/vksyncvaltests.cpp
If a descriptor set is created with VK_DESCRIPTOR_BINDING_PARTIALLY_BOUND_BIT, it is valid to destroy buffers or images (or views) used by one of its descriptors, as long as that descriptor is not 'dynamically used' by any shader invocations. Because these descriptor sets are often quite large, the state tracker does not remove state pointers from descriptors when a resource is destroyed. Avoid crashing in this case by checking for destroyed state objects.
Fixes #3717
=> syncval: Handle destruction of bindless descriptor resources

layers/vk_layer_data.h
This could cause memory leaks if small_vector was used with
types that manage their own memory.
Fixes #3752
=> layers: Add missing small_vector<> destructor

layers/core_validation.cpp, tests/vklayertests_command.cpp
To prevent future confusion such as that found in https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/3733
new message looks like
> Validation Error: [ VUID-vkCmdDraw-None-02721 ] Object 0: handle = 0xb6bee80000000073, type = VK_OBJECT_TYPE_BUFFER; Object 1: handle = 0x2894590000000072, type = VK_OBJECT_TYPE_PIPELINE; | MessageID = 0x99ef63bb | vkCmdDraw: Format VK_FORMAT_R32_SFLOAT has an alignment of 4 but the alignment of attribAddress (1) is not aligned in pVertexAttributeDescriptions[0] (binding=0 location=0) where attribAddress = vertex buffer offset (0) + binding stride (1) + attribute offset (0).
=> layers: Better attribAddress error message

tests/layer_validation_tests.cpp, tests/positive/shaderval.cpp, tests/vklayertests_command.cpp, tests/vklayertests_pipeline_shader.cpp, tests/vklayertests_wsi.cpp
Found when running MockICD with a 1.3 device via devsim layer
=> tests: Fix tests failing with 1.3 devsim

docs/creating_tests.md, layers/best_practices_error_enums.h, layers/best_practices_utils.cpp, tests/vklayertests_best_practices.cpp
From the SPIR-V Spec
> #620: The WorkgroupSize [built-in](https://www.khronos.org/registry/SPIR-V/specs/unified1/SPIRV.html#BuiltIn) is deprecated starting with version 1.6.
added check to warn user if they have `VK_KHR_maintenance4`
=> layers: Add depcrecated WorkgroupSize BP warning

docs/creating_tests.md, layers/descriptor_sets.cpp, tests/layers/device_profile_api.cpp, tests/positive/pipeline.cpp, tests/vklayertests_buffer_image_memory_sampler.cpp, tests/vklayertests_others.cpp, tests/vklayertests_pipeline_shader.cpp, tests/vkrenderframework.cpp, tests/vkrenderframework.h
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/3736
- `VUID-*-OpTypeImage-06423` and `VUID-*-OpTypeImage-06424` should be checking image view format
- spec fix - https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/5041
- `VUID-*-None-06479` also says "image view" but was checking the image format features
- Added a slight more information at error message time
cc @djdeath
=> layers: Fix format_feature_2 format features

layers/best_practices_utils.cpp
I encountered this issue when I tried to use current master with dynamic rendering.
This seems to be caused by commit https://github.com/KhronosGroup/Vulkan-ValidationLayers/commit/f9b894b68a712ba0f7880c176074ac9fbb67cc7d which forgot to move renderPass null check before trying to use it.
=> layers: Fix crashing in best practices

layers/image_layout_map.cpp, tests/positive/render_pass.cpp
Fixes issue #3751. Correctly updates subresource generator when subresource layout map's const iterator is incremented via IncrementInterval that sets the index to next constant value range.
=> Update subresource generator when iterator is incremented to next constant value range

CMakeLists.txt, layers/CMakeLists.txt, tests/CMakeLists.txt
If the SPIRV-Headers package is not found, fall back to looking for
headers in SPIRV_HEADERS_INSTALL_DIR or SPIRV_HEADERS_INCLUDE_DIR.
Fixes #3765
=> build: Handle many permutations of SPIRV-Headers locations

layers/generated/parameter_validation.cpp, layers/parameter_validation_utils.cpp, layers/stateless_validation.h, scripts/parameter_validation_generator.py, tests/positive/image_buffer.cpp
Addresses #3763 
The planeAspect field needs to be able to be set to VK_IMAGE_ASPECT_NONE, which is 0, but parameter validation will flag it as invalid because the field is not marked as optional.  There is an xml MR to correct this, and this is a workaround until it lands, at which time I plan to undo this.
=> Allow VkDeviceImageMemoryRequirements.planeAspect to be VK_IMAGE_ASPECT_NONE

layers/core_validation.cpp, layers/generated/object_tracker.cpp, scripts/object_tracker_generator.py
Use the object tracker generator to make code for:
VUID-vkDestroyAccelerationStructureKHR-accelerationStructure-02443
VUID-vkDestroyAccelerationStructureKHR-accelerationStructure-02444
VUID-vkDestroyAccelerationStructureNV-accelerationStructure-03753
VUID-vkDestroyAccelerationStructureNV-accelerationStructure-03754
Because there are 2 different handle types for acceleration structures,
the code generator needed to be extended to handle
param_type-param_name-alloc_type keys.
=> layers: Use allocator codegen hooks for acceleration structures

tests/layer_validation_tests.cpp, tests/positive/command.cpp, tests/positive/descriptors.cpp, tests/positive/dynamic_rendering.cpp, tests/positive/image_buffer.cpp, tests/positive/instance.cpp, tests/positive/other.cpp, tests/positive/pipeline.cpp, tests/positive/render_pass.cpp, tests/positive/shaderval.cpp, tests/positive/sync.cpp, tests/positive/tooling.cpp, tests/vklayertests_descriptor_renderpass_framebuffer.cpp, tests/vklayertests_dynamic_rendering.cpp, tests/vklayertests_others.cpp, tests/vklayertests_pipeline_shader.cpp, tests/vklayertests_portability_subset.cpp, tests/vklayertests_viewport_inheritance.cpp, tests/vkrenderframework.cpp, tests/vkrenderframework.h, tests/vksyncvaltests.cpp, tests/vktestbinding.cpp, tests/vktestbinding.h
Notice some cases being left turns into new tests copy-and-pasting the non `LvlInitStruct` way so had some down time and just fixed them all
=> tests: Convert rest of tests to LvlInitStruct

layers/cmd_buffer_state.cpp
I'm not 100% sure how this happens -- I'm debugging a third-party application through Mesa/Zink.  I think the problem is as simple as binding a pipeline that uses *n* descriptor sets with only *n - 1* of those descriptor sets bound.
Using the validation layers from the Vulkan SDK 1.3.204.0 I get a crash in STL code beneath `CMD_BUFFER_STATE::UpdateDrawState()` line 1007.
Using locally built validation layers in debug mode I get an assert that access to `state.per_set[set_index]` in `CMD_BUFFER_STATE::UpdateDrawState()` is out of bounds.  Where `set_index` is 5 but there are only 5 elements in `state.per_set`.  Note that assert is not the same position as the crash but it seems to be the same call-stack.
With this fix in place I'm able to run successfully with locally built validation …
=> layers: Avoid out of bounds access in UpdateDrawState()

layers/buffer_state.h, layers/buffer_validation.cpp, layers/core_validation.cpp, layers/core_validation.h, layers/descriptor_sets.cpp, layers/ray_tracing_state.h, layers/state_tracker.cpp, layers/state_tracker.h, tests/layer_validation_tests.cpp, tests/layer_validation_tests.h, tests/vklayertests_others.cpp
Remove unneeded data members and make many others const.
The KHR state object shouldn't inherit from BINDABLE, because memory is never bound to it.
Add tracking for buffers used in the build acceleration structure commands, including those that are passed by VkDeviceAddress.
Fixes #3664
=> layers: Refactor and improve acceleration structure state tracking

layers/core_validation.cpp
This would crash if `vkCmdBeginRenderPass()` is not called.
=> layers: Check if render pass is set before use

layers/buffer_validation.cpp
Calling LogError(..., 0, ...) is undefined because the second
argument is an std::string (and this generally crashes). Use an
empty string instead. Discovered while experimenting with a
(partial) C++23 build, where constructing a string from nullptr
doesn't compile.
=> Avoid creating an std::string from nullptr in LogError call

tests/vklayertests_dynamic_rendering.cpp
This test will crash on nvidia drivers that do not support dynamic rendering due to the `VkPhysicalDeviceDynamicRenderingFeatures::dynamicRendering` being manually set to true when the logical device is created, and the dynamic rendering extension is not enabled/supported.
=> tests: Fix extension and feature check

layers/best_practices_utils.cpp, layers/best_practices_validation.h, layers/debug_printf.cpp, layers/debug_printf.h, layers/gpu_validation.cpp, layers/gpu_validation.h, layers/state_tracker.h
Rework the templated state tracker accessor methods so that they
can work with derived types, such as those used by BP, GPUAV and
DebugPrintf.
=> layers: Let state tracker accessors to work with derived classes

layers/buffer_validation.cpp, tests/vklayertests_buffer_image_memory_sampler.cpp
First, I cleaned up some tests to just assume Vulkan 1.1 to make the logic much cleaner (some tests were missing the pNext struct as well)
Second, add coverage and a test for `VUID-VkImageViewCreateInfo-format-06415`
(ps, I wrote those YCbCr tests long ago and it was back when I only had 1.0 devices to test with but now not an issue as most things are 1.1+ now)
=> Add VUID 06415

layers/core_validation.cpp, layers/core_validation.h, tests/vklayertests_others.cpp
Add VUIDs to validate memory for buffers used in acceleration structures copies. 
Part of #3792
=> Add vuid 03737 03738 03727 03728, validate memory in acceleration structure copies

layers/core_validation.h, layers/shader_module.cpp, layers/shader_module.h, layers/shader_validation.cpp, tests/positive/shaderval.cpp, tests/vklayertests_pipeline_shader.cpp
spiritual successor to https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/3499
So this change does a few things, which I tried to test all cases
- Add proper support for `LocalSizeId` which was added in Vulkan 1.3 / `VK_KHR_maintenance4` (pending https://github.com/KhronosGroup/SPIRV-Tools/pull/4719 still though as tests will fail when it hits `spirv-opt` otherwise)
- Make sure if the `WorkgroupSize` built-in is used, it takes  precedence over any `LocalSize` or `LocalSizeId`
- Fix the "how we use `spirv-opt`" issue
- A `OpSpecConstant` has a default value, so IF the pipeline has a value to override it, then we add `CreateSetSpecConstantDefaultValuePass`
- If there are any `OpSpecConstant` we always will run `CreateFreezeSpecConstantValuePass` and …
=> layers: ComputeWorkGroupSize with spec const

layers/cmd_buffer_state.cpp, layers/cmd_buffer_state.h, layers/render_pass_state.cpp, layers/render_pass_state.h, tests/vklayertests_command.cpp
Fixes issue #3745. As stated in the spec, all resources should be rebound after `vkCmdBeginRenderPass` or `vkNextSubpass` if render pass is using multiview.
=> Unbind resources with multiview at render/subpass start

layers/cmd_buffer_state.cpp, layers/cmd_buffer_state.h, layers/queue_state.cpp, tests/positive/sync.cpp
When a command buffer is executed only update query status if no command buffer submitted after updates the same query
Closes #1458 and #2521
=> Fix issue 1458 2521, Fix updating queries 

layers/core_validation.cpp, tests/vklayertests_dynamic_rendering.cpp
Fix for CTS test dEQP-VK.fragment_shading_rate.dynamic_rendering.attachment_rate.setup_with_copying_using_transfer_queue_concurent.r8_uint.rate_1x1
=> Fix vuid 06183 06184, dynamic rendering with density map and shading rate

layers/buffer_validation.cpp, layers/core_validation.h, layers/state_tracker.h, layers/synchronization_validation.cpp, layers/synchronization_validation.h
When we added `VK_KHR_copy_commands2` a log time ago we had to get all the "it might be `vkCmdCopyImage` or `vkCmdCopyImage2`" fun logic setup and it took few different iterations to become what it is now
Not trying to bikeshed here, but I have found it quite pointless and actually unhelpful now that the use of `RegionType` is not consistent. The only purpose of it is to allow the 2 different possible `pRegions` from the 2 different functions.
=> layers: Consistent use of RegionType

layers/cmd_buffer_state.cpp
Fixes crash in dEQP-VK.multiview.draw_indexed.1_2_4_8
Tests are coming as stated in #3774
=> Update command buffer index buffer status at unbind

layers/core_validation.cpp
When validating the imageView members of color attachments
associated with VkRenderingInfo, fix assumption that the
first attachment in the array will have always a valid
image view sample count.
=> layers: Fix sample count for non-sequential color attachments

layers/best_practices_error_enums.h, layers/best_practices_utils.cpp, tests/vklayertests_best_practices.cpp
Closes #3859 
If VK_IMAGE_CREATE_EXTENDED_USAGE_BIT is set without VK_IMAGE_CREATE_MUTABLE_FORMAT_BIT, it will have no effect.
=> Best practices validate image create flags

layers/best_practices_utils.cpp, layers/best_practices_validation.h, layers/generated/best_practices.cpp, layers/pipeline_state.cpp, layers/pipeline_state.h, layers/state_tracker.cpp, layers/state_tracker.h, scripts/best_practices_generator.py, tests/vklayertests_best_practices.cpp, tests/vklayertests_others.cpp
This change converts several separate 'add on' state maps into fields in derived state objects, to avoid the need for additional locked map lookups.
=> practices: Implement fine-grained locking

layers/core_validation.cpp, layers/vk_layer_utils.h
For a Vulkan 1.0 application, `phys_dev_props_core11.maxMultiviewViewCount` seems to be 0. This can cause the following indirect validation error when the app tries to use dynamic rendering, also see issue #3796:
[ VUID-VkPipelineRenderingCreateInfo-viewMask-06067 ] Object 0: handle = 0x7fc6e0cbae40, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x66903323 | vkCreateGraphicsPipelines() pCreateInfos[0]: Most significant bit in VkPipelineRenderingCreateInfo->viewMask(0) must be less maxMultiviewViewCount(0) The Vulkan spec states: The index of the most significant bit in viewMask must be less than maxMultiviewViewCount (https://vulkan.lunarg.com/doc/view/1.3.204.0/linux/1.3-extensions/vkspec.html#VUID-VkPipelineRenderingCreateInfo-viewMask-06067)
This PR changes `MostSignificantBit(0)`'s …
=> layers:  Make MostSignificantBit(0) yield -1

layers/debug_printf.cpp, layers/debug_printf.h, layers/gpu_validation.cpp, layers/gpu_validation.h
Update to using the new namespace naming scheme.
=> layers: Rename GPUAV and DebugPrintf derived command buffer state

tests/positive/image_buffer.cpp
Swapchain image must be acquired before use.
=> tests: Fix transfer image test

layers/cmd_buffer_state.cpp, layers/synchronization_validation.cpp
This would crash if `vkCmdNextSubpass` was called in a render pass using a single subpass.
=> layers: Fix invalid next subpass

layers/buffer_validation.cpp
Notices these 2 spots (looked and didn't see anymore) were not actually passing in the `LogObjectList` object to the error call
=> layers: Fix LogObjectList not being used

layers/core_validation.cpp, layers/core_validation.h, tests/vklayertests_wsi.cpp
Closes #1340 
This PR removes the false positives, by allowing the values from the last `vkGetPhysicalDeviceSurfaceCapabilitiesKHR` call to be valid. A warning is still produced if the extent is not within the bounds of current values returned by `vkGetPhysicalDeviceSurfaceCapabilitiesKHR`.
=> Fix vkCreateSwapchainKHR imageExtent check

layers/vk_layer_utils.h
While working on a different PR I found we didn't use the best approach for the insert of the concurrent unordered map. This should allow for correct use of move constructors and extends it to allow multiple arguments for in place construction with correct forwarding if wanted.
The previous approach always did a copy due to the constant reference when assigning or constructing the inserted value.
Let me know what you think
=> layers: Let concurrent unordered map's insert use templated args

layers/best_practices_utils.cpp
Fixes some dynamic_rendering CTS crashes
=> Avoid renderpass attachments in BP if dynamic rendering

layers/gpu_validation.cpp, layers/gpu_validation.h, layers/state_tracker.h
This map was rendundant with the buffer_address_map_ in the state
tracker, now that the latter also tracks buffer sizes.
=> gpuav: Remove buffer_map

layers/stateless_validation.h, tests/vklayertests_descriptor_renderpass_framebuffer.cpp
This change adds validation for 2 new VUs :
* VUID-VkAttachmentDescription2-separateDepthStencilLayouts-06556
* VUID-VkAttachmentDescription2-separateDepthStencilLayouts-06557
They restrict the layout used in VkAttachmentDescription2 for separate
depth/stencil attachments with depth/stencil aspects.
=> layers: Validation for new separate DS layouts

layers/synchronization_validation.cpp, tests/vksyncvaltests.cpp
Closes #3894 
ImageRangeGenerator already handles texel sizes, adjusting extent for copying to compressed format is not needing.
=> Fix tracking compressed format extents

layers/core_validation.cpp, layers/device_state.h, layers/state_tracker.cpp
Add working support for the VK_GOOGLE_surfaceless_query extension.  This PR adds no additional validation checks, only compatibility support.
Change-Id: Ifb7d548a445d327bee7c18928a6b539228b2bf65
=> Add compatible support for the surfaceless_query extension

layers/core_validation.cpp, layers/core_validation.h, layers/device_state.h, layers/parameter_validation_utils.cpp, layers/state_tracker.cpp
There is a `ValidateExtendedDynamicState` and I assumed all the `vkCmdSet` commands would be going through there, but seemed only some where. Went through and made sure each dynamic state is piped through there
1. this adds some missing implicit VUID checks that `ValidateCmd` called for some functions
2. Allows future extended state to have something consistent to copy and paste from
3. Easy to update future changes in one spot
=> layers: All dynamic state use same helper

layers/best_practices_utils.cpp, layers/best_practices_validation.h, layers/core_validation.cpp, layers/core_validation.h, layers/debug_printf.cpp, layers/debug_printf.h, layers/gpu_validation.cpp, layers/gpu_validation.h, layers/state_tracker.cpp, layers/state_tracker.h, layers/synchronization_validation.cpp, layers/synchronization_validation.h
This virtual method can be used to do device level setup.
PostCallRecordCreateDevice() gets called on the validation object
representing the VkInstance, making it awkward to set up the device
state object there.
=> layers: Add ValidationStateTracker::CreateDevice

layers/state_tracker.cpp
An extra state_tracker-> snuck in from the 1.3.210 header update.
=> layers: Fix build failure in ValidationStateTracker::CreateDevice()

layers/core_validation.cpp, layers/state_tracker.cpp
Fixes crash in dEQP-VK.memory.binding.priority_dynamic.aliasing.suballocated.buffer_33
=> Guard against empty cb_state

layers/buffer_validation.cpp, layers/core_validation_error_enums.h, layers/state_tracker.h, tests/vklayertests_command.cpp
Waiting on approval of [internal Vulkan Change](https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/5105) first... hence the `todo` in the VUIDs
edit: I guess there was a `LogWarning` for `kVUID_Core_Image_ZeroAreaSubregion` already... will update
edit: working group approved change, just waiting on new spec to rollout to get VUID and will update and can roll this in with 1.3.209 header update
**update:** has new VUIDs ready to go
=> Add empty copy checks

layers/debug_printf.cpp, layers/generated/chassis.h, layers/generated/layer_chassis_dispatch.cpp, layers/generated/object_tracker.cpp, layers/generated/thread_safety.cpp, layers/gpu_utils.h, layers/gpu_validation.cpp, layers/object_tracker_utils.cpp, layers/state_tracker.cpp, scripts/layer_chassis_dispatch_generator.py, scripts/layer_chassis_generator.py, scripts/object_tracker_generator.py, scripts/thread_safety_generator.py, tests/vklayertests_others.cpp
Fixes the last issue mentioned in #2767. Objects that were created through a deferred operation will be tracked after that operation has completed successfully.
=> Track deferred objects after successful creation

tests/vklayertests_buffer_image_memory_sampler.cpp
The `InvalidExportExternalImageHandle` and `InvalidExportExternalBufferHandle` tests were crashing on Pixel 6 devices.  This was due to not checking a VkCreateXxx return code which had failed.
Also removed the Galaxy S10 temp workarounds as I'm guessing this fixes those as well. 
Note that other tests still crash on Pixel 6 devices, including `VkLayerTest.AndroidHardwareBufferMemoryAllocation`, which has a host of issues.
=> Fix external Img/Bfr handle tests for Android devices

layers/generated/vk_safe_struct.cpp, layers/generated/vk_safe_struct.h, layers/pipeline_state.h, scripts/helper_file_generator.py
=> Prevent safe struct pNext leak in initialize()

build-android/known_good.json, layers/generated/spirv_grammar_helper.cpp, layers/generated/spirv_tools_commit_id.h, scripts/known_good.json, tests/vklayertests_pipeline_shader.cpp
Prep for next SDK. Note that shaderc is intentionally unchanged since there have been no commits since the last known-good snapshot.
=> build: Update shader toolchain commits

layers/best_practices_error_enums.h, layers/best_practices_utils.cpp, layers/best_practices_validation.h, layers/generated/chassis.h, layers/layer_options.cpp, layers/layer_options.h, scripts/layer_chassis_generator.py
Allow Imagination technologies best practices to be enabled through the VALIDATION_CHECK_ENABLE_VENDOR_SPECIFIC_IMG property.
From there, most validation checks are simply ports from ARM as there is a large overlap. Finally there is a new warning to advice users to stop using PVRTC
=> Imagination best practices

layers/buffer_validation.cpp, tests/vklayertests_buffer_image_memory_sampler.cpp, tests/vklayertests_command.cpp
Adds check for subresource overlap in blit operations, same approach as the one used in `vkCmdCopyImage`. There's an issue that we may want to tackle at some point, but since there has not been any complain on how the check is done in `vkCmdCopyImage` we can keep as things are for now.
The issue I found is the following: We currently only check for overlap if the same `VkImage` is used, and we only check against the subresource dimensions. What happens if we have 2 images that bind to the same memory and we use as src (the first one for example) and dst (the second one) with same subresource dimensions such that the memory is overlapped.
Ideally we would need to compute all memory locations and check that none overlap. Let me know what you think and how we should try to tackle the …
=> Check subresource overlap in blit operations

layers/descriptor_sets.cpp, layers/pipeline_state.cpp, layers/pipeline_state.h, layers/shader_module.cpp, layers/shader_module.h, tests/positive/shaderval.cpp
Closes #3971 
Before descriptor types were only checked against used variables, but we need to allow binding descriptor types from unused variables as well, to prevent false positives.
=> layers: Find all shader variable ids, fix false positive wrong descriptor type

layers/descriptor_sets.cpp, tests/vklayertests_descriptor_renderpass_framebuffer.cpp
Image used as framebuffer attachment can be sampled from if it's in a read only layout.
Closes #3932
=> Fix issue 3932,  Fix read only attachments validation

layers/core_validation.cpp, tests/vklayertests_descriptor_renderpass_framebuffer.cpp
This VU was explicitly added in new 1.3.211 headers to prevent future issues such as https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/2846 from being reported as the spec was slightly ambiguous
=> layers: Label new VUID 06715

layers/core_validation.cpp
this needs to be clamped to 1 to avoid spurious validation errors
=> layers: fix framebuffer miplevel-based extents calculation

layers/best_practices_utils.cpp
Fixes crash in dEQP-VK.fragment_shading_rate.renderpass2.multiview.dynamic.noattachment.noshaderrate.keep.keep.1x1.samples2.vs with BP
=> Don't dereference null pipeline state pointer in Best Practices

layers/cmd_buffer_state.cpp, tests/positive/command.cpp
I think with this test we are able to replicate issue #1556. If the mentioned issue has nothing to do with this, this PR fixes an issue we have with event updates not being transfered from secondary to primary command buffers when executed.
=> Transfer event updates from secondary to primary command buffers

layers/core_validation.cpp
The local string is masking the path in the class, and then the cache never gets written.  Remove the local variable.
Fixes https://gitlab.khronos.org/vulkan/Vulkan-SDK-Packaging/-/issues/1013
=> Fix shader validation cache file path

layers/buffer_validation.cpp
Print the number of mipLevels instead of arrayLayers in
VUID-VkImageCreateInfo-format-06410 validation.
=> layers: Fix message in VUID 06410 validation

layers/core_validation.cpp, layers/device_state.h, layers/state_tracker.cpp, tests/vklayertests_graphics_library.cpp
Adds VUIDs that check for invalid graphics pipeline state when
VK_EXT_graphics_pipeline_library is enabled.
=> layers: Add VUIDs 06606, 06607, 06608

layers/best_practices_error_enums.h, layers/best_practices_utils.cpp, tests/vklayertests_best_practices.cpp
Closes #2488
Closes #3510
This is the same as VUID 00306, but that VUID does not apply when VK_KHR_maintenance1 is enabled. As this is not invalid per the spec it can only fit in best practices.
=> Warn when overallocating from descriptor pool

tests/vklayertests_buffer_image_memory_sampler.cpp
VK_KHR_maintenance4 requires VK_API_VERSION_1_1, this crashed with the latest amd driver.
=> tests: Fix device memory requirements test

layers/core_validation.cpp, layers/parameter_validation_utils.cpp, tests/vklayertests_others.cpp, tests/vklayertests_pipeline_shader.cpp
Also moves 06688 into CoreChecks and CmdBeginQuery
I'll wait to rebase on #4010 after it lands.
=> Remaining validation for VK_EXT_primitives_generated_query

layers/buffer_validation.cpp, tests/vklayertests_buffer_image_memory_sampler.cpp
Due to some issues in CI, there's a need to revert how we check VUID-VkCopyBufferInfo2-pRegions-00117 and VUID-vkCmdCopyBuffer-pRegions-00117.
The change will be reintroduced once the sparse resource validation correctly checks what is causing the issue
=> Revert part of 4038

layers/core_validation.cpp
Fixed typos on VUID-VkRenderingAttachmentInfo-imageView-06129 and VUID-VkRenderingAttachmentInfo-imageView-06130 error messages: "integar" to "integer". 
`"VK_RESOLVE_MODE_AVERAGE_BIT for non-integar formats (%s)"` -> `"VK_RESOLVE_MODE_AVERAGE_BIT for non-integer formats (%s)"`
`"VK_RESOLVE_MODE_SAMPLE_ZERO_BIT for integar formats (%s)"` -> `"VK_RESOLVE_MODE_SAMPLE_ZERO_BIT for integer formats (%s)"`
=> layers: Fix typo on VUID-06129 and VUID-06130 error messages

layers/core_validation.cpp
The order of the current timeline semaphore value and the signal value was backwards, leading to confusing errors like:
```
Validation Error: [ VUID-VkSubmitInfo2-semaphore-03881 ] vkQueueSubmit2():
pSubmits[0].pSignalSemaphoreInfos[0] signal value (0x1) must be greater than current timeline semaphore
VkSemaphore 0x100000000010[] value (0x0)
```
On another note, the VUID which this code is implementing (VUID-VkSubmitInfo2-semaphore-03881), says nothing about the signal value having to be greater than the current value, which I think also led to the confusion in issue #2340.
=> layers: Fix print order upon invalid timeline semaphore signal

layers/core_validation.cpp, tests/positive/dynamic_rendering.cpp
VK_IMAGE_CREATE_SUBSAMPLED_BIT_EXT is part of VkImageCreateInfo and not VkImageViewCreateInfo
ImageView layoutCount must be retrieved from normalized_subresource_range
=> layers: Fix dynamic rendering validation usage and layerCount

layers/core_validation.cpp, tests/vklayertests_descriptor_renderpass_framebuffer.cpp
Move validation for VkRenderPassFragmentDensityMapCreateInfoEXT to common function used in both createRenderPass and createRenderPass2 and use correct vuid.
=> Add vuid 06472, add RenderPass2 validation for FragmentDensityMap

layers/core_validation.cpp, layers/descriptor_sets.cpp
This method only needs to process Image-related descriptors. Optimize it by checking the descriptor type per binding instead of for every descriptor (except for mutable descriptors). Avoid a redundant bounds check on every loop iteration as well.
=> layers: Optimize DescriptorSet::UpdateDrawState()

layers/descriptor_sets.cpp, layers/descriptor_sets.h
Add cvdescriptorset::DescriptorTypeToClass() to avoid errors
in descriptor processing, which uses way too much static_cast<>.
PR #4706 had such an error...
=> layers: Add VkDescriptorType -> DescriptorClass function

tests/positive/other.cpp
The test fails randomly with `VK_TIMEOUT`, most likely a driver bug
=> tests: Disable QueueThreading test on amd

layers/core_validation.cpp, layers/core_validation.h, tests/vklayertests_buffer_image_memory_sampler.cpp
While looking into sparse memory validation, found there were some VUIDs that would be helpful for what I'm currently looking into. They are related to VkSparseMemoryBind.
Added:
- VUID-VkSparseMemoryBind-size-01098
- VUID-VkSparseMemoryBind-resourceOffset-01099
- VUID-VkSparseMemoryBind-size-01100
- VUID-VkSparseMemoryBind-size-01102
Already implemented:
- VUID-VkSparseMemoryBind-memory-01097
- VUID-VkSparseMemoryBind-memoryOffset-01101 (moved to where we currently check all the similar ones)
Still missing:
- VUID-VkSparseMemoryBind-memory-01096 (planning to look into this one)
- VUID-VkSparseMemoryBind-memory-02730 (I can look into this one once finished with what I'm doing)
- VUID-VkSparseMemoryBind-memory-02731 (I can look into this one once finished with what I'm doing)
=> Missing VkSparseMemoryBind VUIDs

layers/core_validation.cpp, layers/core_validation.h, tests/positive/pipeline.cpp, tests/vklayertests_buffer_image_memory_sampler.cpp, tests/vklayertests_others.cpp, tests/vktestbinding.cpp, tests/vktestbinding.h
Closes #4029 
Validate render pass compatibility, matching of subpass dependencies and correlated view masks.
=> layers: Complete validation of compatible render passes

layers/debug_printf.cpp, layers/gpu_utils.h, layers/gpu_validation.cpp, layers/gpu_validation.h, layers/json/VkLayer_khronos_validation.json.in, layers/vk_layer_settings.txt
VMA allocations are GPU-AV's biggest performance hotspot, and this change improves performance significantly at the cost of using nominally more device memory.  No new out-of-memories were found running the set of performance traces with this option enabled.
Also cleaned up option checking and added VMA stats to out of memory errors.
=> Use VMA linear allocation algorithm for GPU-AV output buffers

layers/core_validation.cpp, layers/core_validation.h, layers/gpu_utils.cpp, layers/pipeline_state.cpp, layers/pipeline_state.h, layers/shader_validation.cpp, layers/vk_layer_data.h
Removes PIPELINE_STATE::GetUnifiedCreateInfo, instead utilizing template
specialization to return the correct information based on *CreateInfo
type.
=> layers: Remove GetUnifiedCreateInfo

layers/generated/layer_chassis_dispatch.cpp, scripts/layer_chassis_dispatch_generator.py
it's never explicitly spelled out in text, but this combination of VUs
allows for depthAttachmentFormat to be unset while stencilAttachmentFormat is set:
VUID-VkCommandBufferInheritanceRenderingInfo-depthAttachmentFormat-06200
* If depthAttachmentFormat is not VK_FORMAT_UNDEFINED and stencilAttachmentFormat is not
VK_FORMAT_UNDEFINED, depthAttachmentFormat must equal stencilAttachmentFormat
VUID-VkGraphicsPipelineCreateInfo-renderPass-06053
* If renderPass is VK_NULL_HANDLE, the pipeline is being created with fragment shader
state and fragment output interface state, and either of
VkPipelineRenderingCreateInfo::depthAttachmentFormat
or
VkPipelineRenderingCreateInfo::stencilAttachmentFormat
are not VK_FORMAT_UNDEFINED, pDepthStencilState must be a valid pointer to a valid …
=> layers: Fix depthstencil attachment usage detection with dynamic render

layers/buffer_state.h, layers/descriptor_sets.cpp, layers/state_tracker.cpp, tests/vklayertests_pipeline_shader.cpp
If we use a VkBufferView with OpImageRead/OpImageWrite then the format
features that apply are the ones of the image, not the buffer.
This fixes 934991a2ee
Closes #4049.
=> layers: Fix format features check for buffer views

layers/core_validation.cpp
ImageSubresourceOverlapBetweenCurrentRenderPassAndDescriptorSets
showed that CoreChecks::ValidateDependencies was using the wrong
attachmentCount to iterate over the framebuffer pAttachments array.
=> corechecks: Fix ASan heap buffer overflow

layers/core_validation.cpp
When validating graphics pipeline creation for portability
implementations, no check was implemented to determine if the pipeline
was using dynamic rendering and would have a null render pass, causing
a SEGFAULT by attempting to dereference a null pointer to the render
pass state. A check for whether the VkPipelineRenderingCreateInfo
struct was included in the pNext chain of the
VkGraphicsPipelineCreateInfo struct was implemented to fix this.
=> layers: Fix Dynamic Rendering SEGFAULT for Portability

layers/core_validation.cpp
When validating the semaphore set in VkPresentInfoKHR, make
PreCallValidateQueuePresentKHR only check semaphores with internal
scope.
Validation Error: [
VUID-vkQueuePresentKHR-pWaitSemaphores-03268 ] vkQueuePresentKHR: Queue
VkQueue 0xde3a98[] is waiting on pWaitSemaphores[0] (VkSemaphore
0xab64de0000000020[]) that has no way to be signaled.
Fixes #4128
=> layers: Fix semaphore check logic in PreCallValidateQueuePresentKHR

layers/core_validation.cpp, tests/positive/pipeline.cpp
Ensure ColorBlendState is not null, which is legal when no color
attachments are used.
Closes #4118.
=> layers: Fix null ColorBlendState crash

layers/core_validation.cpp, layers/stateless_validation.h
Replaces https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/3927
Can just close that PR, when I wrote it, the VUIDs were added in another PR and got in first. The logic for them was a little redundant so cleaned that up as well
=> layers: Remove unused warning and cleanup

layers/core_validation.cpp, layers/core_validation_error_enums.h, tests/positive/image_buffer.cpp, tests/vklayertests_buffer_image_memory_sampler.cpp
I couldn't find any VUID (I think there's none and one should be added) that states a `VkBindImagePlaneMemoryInfo` is needed in the `pNext` of `VkBindImageMemoryInfo` when binding planes of disjoint images.
Without adding it to `pNext`, there's no way to specify to which plane we are binding the memory, and the spec states the following `In order to bind planes of a disjoint image, add a VkBindImagePlaneMemoryInfo structure to the pNext chain of VkBindImageMemoryInfo (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkBindImageMemoryInfo.html).`.
=> Validate VkBindImagePlaneMemoryInfo is in pNext when binding planes

layers/core_validation.cpp, layers/pipeline_sub_state.h, layers/vk_layer_data.h, tests/vklayertests_graphics_library.cpp
Adds checks to verify that shader stages in non-null DSL bindings do not
overlap stages in a subset that contains a null DSL for the same DSL
index.
=> layers: Add VUs 06756-06758

docs/creating_tests.md, tests/vklayertests_buffer_image_memory_sampler.cpp, tests/vklayertests_descriptor_renderpass_framebuffer.cpp
few places uses `CanEnableDeviceExtension` instead of `AreRequestedExtensionsEnabled` I found
=> tests: Cleanup use of CanEnableDeviceExtnsion

layers/core_validation.cpp
Pipeline creation flags were being checked in the wrong place. This was
creating some spurious validation errors in a few CTS tests.
=> layers: Do not check pipeline flag bits in render pass flags

tests/positive/command.cpp, tests/positive/descriptors.cpp, tests/positive/dynamic_rendering.cpp, tests/positive/graphics_library.cpp, tests/positive/image_buffer.cpp, tests/positive/other.cpp, tests/positive/pipeline.cpp, tests/positive/render_pass.cpp, tests/positive/shaderval.cpp, tests/vklayertests_buffer_image_memory_sampler.cpp, tests/vklayertests_command.cpp, tests/vklayertests_descriptor_renderpass_framebuffer.cpp, tests/vklayertests_dynamic_rendering.cpp, tests/vklayertests_gpu.cpp, tests/vklayertests_graphics_library.cpp, tests/vklayertests_imageless_framebuffer.cpp, tests/vklayertests_others.cpp, tests/vklayertests_pipeline_shader.cpp, tests/vklayertests_wsi.cpp
uses `GTEST_SKIP` for `DeviceValidationVersion` checks
few surface tests were checking twice and removed the 2nd check
=> tests: Version check unified

layers/state_tracker.h, layers/synchronization_validation.h
Ensure that callbacks into the syncval object aren't called after the
validation object subclass is destroyed.
=> syncval: Cleanup callbacks on syncval destroy

layers/core_validation.cpp
I promised to do this in a previous PR
=> Use ofstream to write shader validation cache

layers/core_validation.cpp, layers/core_validation.h, tests/vklayertests_buffer_image_memory_sampler.cpp
The added VUIDs only apply if the image is sparse and resident. Otherwise, there's no VUIDs that check for correct alignment, although there's mention to what it should be (I will probably add another unassigned VUID for this). I left a comment to point it out.
=> VkSparseImageMemoryBind check offset VUIDs

layers/core_validation.cpp, layers/image_state.cpp, layers/image_state.h, tests/vklayertests_buffer_image_memory_sampler.cpp
I also moved the `IMAGE_STATE::GetSubresourceExtent` to a more generic function so it can be used without requiring `VkImageSubresourceLayers`.
=> VkSparseImageMemoryBind check extent VUIDs

layers/vk_layer_data.h, tests/vktestbinding.h
1) small vector::reserve wasn't updating capacity_ , meaning that large_store_ emplace was going to be N^2.  Also added a debug-only feature as reading the backing_store was driving me batty
2) return queue_index information as uint32_t which is consistent with the queue count in the queue family props
=> Two small fixes, one might have performance implications.

scripts/spirv_validation_generator.py
There was already an "Alias SPIR-V Capability list" in the generation script, but not where you would expect it. Just cleaned up the script files to make it easier for the next time to find. No change in the generated code with this change
related: https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/4151 and https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/4152
=> scripts: Unify SPIR-V alias capability list

layers/core_validation.cpp, layers/descriptor_validation.cpp, layers/parameter_validation_utils.cpp, tests/vklayertests_graphics_library.cpp
This also updates these checks to align with the updated [spec change](https://github.com/KhronosGroup/Vulkan-Docs/commit/028789841d7ba54cabc678a128e7b98d30c0b4cd).
=> Rename VUs 06562 -> 06753, 06564 -> 06754

layers/core_validation.cpp
This should fix the VUID that popped in the traces. The check needs to be pushed back to queue submission if any of the images is sparse. Patching this so we don't get false positive with traces.
=> layers: Hotfix sparse subpass dependency check

layers/core_validation.cpp, layers/core_validation.h, layers/drawdispatch.cpp, tests/vklayertests_command.cpp
`VUID-vkCmdDrawIndirectCount-countBufferOffset-04129` (all 3 versions) were missing. Grouped the common VUs together into new function and added common VUID for them
The tests had a "todo" that seems to be old and the tests were already added
=> Add and refactor drawIndirectCount VU

layers/image_state.cpp
Fixes issue in `dEQP-VK.ycbcr.plane_view.memory_alias.g8_b8_r8_3plane_420_unorm_plane_0`. The issue happens whenever we have a multiplane image. Due to backwards compatibility, I kept the `Binding` function, but I overlooked this part of its usage which would always result in an assert with multiplane images
=> Fix assert with multiplane images

layers/buffer_validation.cpp, layers/core_validation.cpp, layers/core_validation.h, layers/descriptor_validation.cpp, layers/image_layout_map.cpp, layers/image_layout_map.h, layers/subresource_adapter.h
Remove ImageSubresourceLayoutMap::ConstIterator, which went through
a bunch of trouble to iterate over every single subresource in a
range with the same layout. It is sufficient to check each range
once.
=> layers: Use range based iteraton for subresource layout checking

layers/core_validation.cpp, layers/pipeline_state.cpp, layers/pipeline_state.h
Ensure valid pipeline layout handles get printed when logging errors
involving graphics pipeline libraries containing merged layouts.
When using graphics pipeline libraries, it is possible that the "executable pipeline" used at draw time is actually a union of layouts from pre-raster and fragment shader libraries. If this is the case, then currently no information about the original layouts are printed to the user.
=> layers: Update 02697 logging for GPLs

docs/synchronization.md, layers/generated/chassis.h, layers/layer_options.cpp, layers/layer_options.h, layers/state_tracker.h, layers/synchronization_validation.cpp, layers/synchronization_validation.h, layers/vk_layer_data.h, scripts/layer_chassis_generator.py, tests/layer_validation_tests.cpp, tests/layer_validation_tests.h, tests/vksyncvaltests.cpp, tests/vktestbinding.h
Mostly this is notes to myself, but this is the general shape, and should support multi-queue when complete.
- The analog to the CommandBufferAccessContext is the "QueueBatchAccessContext"
- See updated documentation for full details
- Tagging is global with ranges assigned at queuesubmit time
- Queue submit order hazard detection (single queue) functional
- PipelineBarrier now correctly scopes for access outside queue submit order
- Trivial semaphore examples function
- Semaphore barrier modelling is incorrect
- SetEvent replay must be define and event scope creation must be rerun(and merged) at submit time
- Wait event chaining must look at the *set* time chaining info to be correct (will need additional state)
- Other submit types need support (including submit2
- Fence support is …
=>   syncval: QueueSubmit validation -- partial implementation -- default disabled

.gitignore
Used by the MSVC guidelines plugin.
=> git: Add .editorconfig to gitignore

layers/generated/chassis.cpp, layers/generated/vk_dispatch_table_helper.h, scripts/dispatch_table_helper_generator.py, scripts/helper_file_generator.py, scripts/layer_chassis_generator.py, tests/layers/device_profile_api.cpp
This function must be queryable from vkGetInstanceProcAddr() - see https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/blob/master/loader/LoaderAndLayerInterface.md
This fixes the crash reported in https://github.com/KhronosGroup/Vulkan-Loader/issues/950
=> Fix layer implementation of vk_layerGetPhysicalDeviceProcAddr

layers/core_validation.h, layers/shader_module.cpp, layers/shader_module.h, layers/shader_validation.cpp
I have an upcoming change that is a lot easier if we save the `OpVariable` in a list as static SPIR-V information. I noticed some other code also would benefit from that, so broke that out into this PR to make the 2 changes easier to distinguish
=> layers: Store OpVariables separately

layers/core_validation.cpp, layers/core_validation.h, tests/vklayertests_buffer_image_memory_sampler.cpp
Validates `VkImageSubresource` used at sparse binding in `VkSparseImageMemoryBind`. I noticed the existence of `ValidateImageAspectMask` which validates the aspect mask used. In a previous PR #4143 I completed a VUID for aspect mask checking for `vkGetImageSubresourceLayout` which does not use this function (unsure why). Should I unify everything so we don't have similar code all over the place?
=> VkSparseImageMemoryBind check subresource

layers/buffer_validation.cpp, layers/core_validation.cpp, layers/core_validation.h, layers/descriptor_validation.cpp
Use reference arguments in VerifyImageLayout() methods and optimize some local variables in ValidateImageDescriptor()
=> corechecks: Clean up some Image descriptor and layout methods

CMakeLists.txt
There are 2 spots with `if(MAKE_C_COMPILER_ID MATCHES "Clang")` so removed one (kept the first one as it seems the spot I would expect it to be)
=> build: Remove duplicate compiler options

cmake/FindVulkanHeaders.cmake
On a system that has the vulkan headers installed in a "standard" search
location, make sure that if VULKAN_HEADERS_INSTALL_DIR is defined,
"standard" directories are not added to the search path.
I feel like someone else brought this up in the past, and there was a reason we did _not_ already have this, but can't seem to find it now. The reason I'm adding it now is that a package update on my local linux system added the repo's vulkan header package, and only the installed package headers are used, which is causing build errors.
Adding @mikes-lunarg, as I think he is also using Arch and wondering if he's run into the same thing recently (qt6-base appears to be the package responsible, which I'm not even using anymore...)
=> build: Fix search path for Vulkan-Headers

layers/subresource_adapter.cpp, layers/subresource_adapter.h, layers/synchronization_validation.cpp, layers/synchronization_validation.h
`ImageRangeGenerator::Convert2DCompatibleTo3D` did not correctly detect if a subresource range was a slice of a 3D image. If `levelCount` is 1, `baseArrayLayer` is 0 and `layerCount` is 1 it will take it as non sliced. The mentioned subresource range is used to access first mip first depth which is actually a slice of a 3D image.
=> layers: Fix ImageRangeGenerator depth sliced check

docs/creating_tests.md, tests/layer_validation_tests.cpp, tests/positive/command.cpp, tests/positive/descriptors.cpp, tests/positive/dynamic_rendering.cpp, tests/positive/graphics_library.cpp, tests/positive/image_buffer.cpp, tests/positive/other.cpp, tests/positive/pipeline.cpp, tests/positive/render_pass.cpp, tests/positive/shaderval.cpp, tests/vklayertests_best_practices.cpp, tests/vklayertests_buffer_image_memory_sampler.cpp, tests/vklayertests_command.cpp, tests/vklayertests_descriptor_renderpass_framebuffer.cpp, tests/vklayertests_dynamic_rendering.cpp, tests/vklayertests_graphics_library.cpp, tests/vklayertests_imageless_framebuffer.cpp, tests/vklayertests_others.cpp, tests/vklayertests_pipeline_shader.cpp, tests/vklayertests_viewport_inheritance.cpp, tests/vklayertests_wsi.cpp, tests/vkrenderframework.cpp, tests/vkrenderframework.h, tests/vksyncvaltests.cpp
This is a decent size change to start the week, but I find it needed as adding "optional extensions" to enable is currently a pain
this change looks big, but the real core change is all seen in `vkrenderframework.h`
- It now only exposes a Add**Required**Extensions and Add**Optional**Extensions function to add extensions 
- `AddRequiredExtensions` is now `void` because no one should be using it to check since we have `AreRequiredExtensionsEnabled`
- `AddOptionalExtensions` allows an easy way to attempt to add extensions and then use the new `IsExtensionsEnabled` after to get the status
- the word `request` we misleading, so now `request` is reserved for the internal functions that actually "request" the extensions to be added
=> tests: Refactor requiring extension

layers/synchronization_validation.cpp, layers/synchronization_validation.h
Some of synch val was using `CMD_TYPE` but added it where it wasn't being used
Also unified the naming to `cmd_type` to be consistent with the rest of the code base
=> layers: Use CMD_TYPE in synch validation

layers/shader_validation.cpp, tests/positive/pipeline.cpp, tests/positive/shaderval.cpp, tests/vklayertests_pipeline_shader.cpp
Relaxed interfacing matching rules when maintenance4 extension is enabled
and increased severity for messages when maintenance4 is not enabled
This is a possible fix for https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/4148
=> Relax interface matching rules maintenance4

layers/CMakeLists.txt, layers/gpu_utils.cpp
Update cmake for windows to treat unused local variable as error to
avoid platform specific errors in CI.
One required pragma added to suppress the error in an included 3rd party file.
=> Add unused local variable error to MSVC

layers/buffer_validation.cpp, layers/core_validation.h, tests/positive/image_buffer.cpp, tests/vklayertests_buffer_image_memory_sampler.cpp
Now that we track bound memory for sparse resources (#4122), we can introduce the change I intended to introduce some time ago. This tries to fix mentioned issues in the following issues: #57 and #3993.
We now correctly check buffer copy. Check is done at queue submission if any of the buffers is sparse since it's when we know what device memory is bound to the buffer.
Added 2 tests for sparse buffers, one positive and one expecting the error so we know everything is working as expected.
=> Correctly check if buffers are overlapping resource memory at copy

tests/vklayertests_command.cpp
I was using this test as a base for one I'm working on and noticed an struct initialized the old way.
=> tests: Use LvlInitStruct in test

tests/vksyncvaltests.cpp
Disable VkSyncValTest.SyncQSBufferCopyVsIdle until crash can further
investigated.
https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/4225 for tracking investigation into the crash.
=> tests: Disable SyncQSBufferCopyVsIdle

layers/generated/layer_chassis_dispatch.cpp, scripts/layer_chassis_dispatch_generator.py
Don't add const qualifier to pMetalObjectsInfo,
since it can't be passed to ExportMetalObjectsEXT this way.
Fixes #4221
=> build: Fix DispatchExportMetalObjectsEXT generation

.github/workflows/build_macos.yml
Provides basic build coverage for macOS code paths
Would have caught #4227 before the 217 update got merged
=> ci: Add macos build to github CI

layers/core_validation.cpp, tests/vklayertests_dynamic_rendering.cpp
`VK_IMAGE_LAYOUT_SHADING_RATE_OPTIMAL_NV` and `VK_IMAGE_LAYOUT_FRAGMENT_SHADING_RATE_ATTACHMENT_OPTIMAL_KHR` are aliased so combined the VU check instead of having it print out 2 separate error messages when using
=> layers: Fix SHADING_RATE_OPTIMAL_NV being aliased

layers/core_validation.cpp, tests/vklayertests_descriptor_renderpass_framebuffer.cpp
Rename 00867 to 06809 and 03087 to 06810. This also removes the ordering
restrictions on these VUs.
Closes #4236.
=> layers: Relax sync VUs in 1.3.218

layers/descriptor_validation.cpp, tests/positive/graphics_library.cpp, tests/vklayertests_graphics_library.cpp, tests/vktestbinding.h
Check that immutable samplers match between the bound pipeline layout
and currently bound pipeline for descriptor set compatibility.
Closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/4165.
=> layers: Check DSL immutable samplers

layers/synchronization_validation.cpp, tests/vksyncvaltests.cpp
Access masks should only expand for the pipeline stages explicitly set in the stage mask. So we shouldn't include the earlier or later stages when doing the access mask expansion.
Add a test makes sure sync validation properly handles the pipeline stage and access mask expansion rules.
=> syncval: Fix access mask expansion

layers/core_validation.cpp
as of the latest spec, the comparison for this has changed such that
the only failure case is when the number of bools passed is less
than the number of blend attachments
=> layers: Update dynamic color write enable state comparison

layers/best_practices_error_enums.h, layers/best_practices_utils.cpp, tests/vklayertests_best_practices.cpp
Add warning message when VkRenderPassBeginInfo.clearValueCount>0
but none of the attachments have VK_ATTACHMENT_LOAD_OP_CLEAR
Close https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/3123
=> Check for ClearValue without LoadOpClear

layers/best_practices_error_enums.h, layers/best_practices_utils.cpp, tests/vklayertests_best_practices.cpp
Add warning message for when VkRenderPassBeginInfo.clearValueCount > VkRenderPassCreateInfo.attachmentCount.
Add test for this message.
The spec states that this is allowed but that the overflowing clearValues will be ignored, thus the values could even be invalid or undefined. Since these values are ignored, it would always make more sense to pass a maximum value of attachmentCount to clearValueCount.
Since there seems to be no reason to pass a higher clearValueCount, this check could help find some bugs.
=> layers: Add check for clearValueCount > attachmentCount

layers/best_practices_utils.cpp, layers/core_validation.cpp, layers/debug_printf.cpp
This commit modifies sprintf calls to fix the following compilation
errors using XCode 14.0 beta on MacOS:
> 'sprintf' is deprecated: This function is provided for compatibility
> reasons only.  Due to security concerns inherent in the design of
> sprintf(3), it is highly recommended that you use snprintf(3) instead.
=> build: Fix compilation errors with deprecated sprintf function

layers/cmd_buffer_state.cpp, tests/vklayertests_command.cpp
Closes #3745. Adds remaining tests for unbound resources after render pass begin or next subpass (push constants, descriptor sets, dynamic state, vertex buffer and index buffer). It also fixes a small issue the unbinding of resources had.
Let me know if I forgot any resource.
=> Add remaining multiview unbound tests

layers/best_practices_error_enums.h, layers/best_practices_utils.cpp, layers/best_practices_validation.h, tests/vklayertests_best_practices.cpp, tests/vktestbinding.h
Add warning message when loading an image in a renderpass with LOAD_OP_LOAD when the last operation on the image was a discard with STORE_OP_DONT_CARE, which results in undefined behaviour.
Closes #293
=> layers: Check StoreOpDontCare then LoadOpLoad

tests/positive/command.cpp, tests/positive/pipeline.cpp, tests/positive/sync.cpp, tests/vklayertests_best_practices.cpp, tests/vklayertests_buffer_image_memory_sampler.cpp, tests/vklayertests_command.cpp, tests/vklayertests_descriptor_renderpass_framebuffer.cpp, tests/vklayertests_gpu.cpp, tests/vklayertests_others.cpp, tests/vksyncvaltests.cpp
Just a quick drive by fix to use more `AddRequiredExtensions` and `AreRequiredExtensionsEnabled` where possible (slowly get all the tests to use it properly). Found some low-hanging fruit tests to easily replace with. Also removed  some `AddRequiredExtensions(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);` where it is redundant
=> tests: More tests to use new extension functions

tests/layer_validation_tests.cpp, tests/positive/command.cpp, tests/positive/other.cpp, tests/positive/pipeline.cpp, tests/positive/shaderval.cpp, tests/positive/tooling.cpp, tests/vklayertests_arm_best_practices.cpp, tests/vklayertests_best_practices.cpp, tests/vklayertests_buffer_image_memory_sampler.cpp, tests/vklayertests_command.cpp, tests/vklayertests_gpu.cpp, tests/vklayertests_instanceless.cpp, tests/vklayertests_others.cpp, tests/vklayertests_pipeline_shader.cpp, tests/vklayertests_wsi.cpp
`SurfacelessQueryTest` was crashing on `DevSim`
While fixing it, I went and added `GTEST_SKIP` to all the places that check for devsim/mockicd
=> tests: Skip SurfacelessQueryTest for devsim

scripts/known_good.json
googletest is removing support for C++11 (and seemingly older compilers,
too). Hard-code GTest to a known working good version.
=> tests: Hard-code GTest

build-gn/generate_vulkan_layers_json.py, layers/vk_layer_utils.h, tests/layers/device_profile_api.cpp
Fixes #4240
The layer without JSON API reports an incorrect version of `1.0.$VK_HEADER_VERSION`, because the constant here was never updated.  Base it on the full version instead to turn this into the correct `1.3.$VK_HEADER_VERSION` (as of writing) to match what is currently used for the `api_version` field in JSON.
---
Creating this as draft because I'd rather _also_ update the scripts to read `VK_HEADER_VERSION_COMPLETE` instead of hardcoding `1.3.{}` all over the place, if maintainers agree?
=> Replace `VK_HEADER_VERSION` with `VK_HEADER_VERSION_COMPLETE`

tests/vklayertests_buffer_image_memory_sampler.cpp, tests/vklayertests_command.cpp, tests/vklayertests_descriptor_renderpass_framebuffer.cpp, tests/vklayertests_pipeline_shader.cpp
addresses some tests from #4273 
Fixes the following:
- VkLayerTest.NotSupportProvokingVertexModePerPipeline
- VkLayerTest.PipelineInvalidAdvancedBlend
- VkLayerTest.InvalidFragmentDensityMapLayerCount
- VkLayerTest.InvalidMixingProtectedResources
- VkLayerTest.InvalidMemoryMapping
=> tests: Fixes for tests on Android

tests/layer_validation_tests.cpp
A recent refactor in [#4253] made it so that `bSupport` is exclusively used to skip XCB initialization when Xlib is already initialized.  This local variable is not used on any other platform, and shows as the following warning-as-error since clang 13 (used in NDK r24, current stable release) when compiling for Android:
[arm64-v8a] Compile++      : VulkanLayerValidationTests <= layer_validation_tests.cpp
jni/../../tests/layer_validation_tests.cpp:1072:10: error: variable 'bSupport' set but not used [-Werror,-Wunused-but-set-variable]
bool bSupport = false;
^
1 error generated.
It was "addressed" for older Android compilers in the `#elif defined(VK_USE_PLATFORM_ANDROID_KHR)` case, but the warning above has its roots inside `#if defined(VK_USE_PLATFORM_ANDROID_KHR) && …
=> tests: Prevent bSupport variable being unused

tests/layer_validation_tests.cpp, tests/layer_validation_tests.h, tests/positive/sync.cpp, tests/test_common.h, tests/vklayertests_best_practices.cpp, tests/vklayertests_others.cpp, tests/vkrenderframework.cpp, tests/vkrenderframework.h
Since std::thread is part of C++11 and we only support that version or higher, I don't think we need our own thread wrappers.
=> tests: Replace test_platform_thread with std::thread

tests/vkrenderframework.cpp, tests/vkrenderframework.h, tests/vktestbinding.cpp
Help speed up tests by calling the enumerate extension and layer functions
with an already provided buffer of adequate size, then storing the found
list in a vector for any subsequent queries.
In my rudimentary performance analysis, I found that master would execute in about 2m 9s while this PR in about 2m 5s. Not a huge difference, but its a relatively simple change to claw back a bit of time.
=> tests: Cache instance layer and extension enumeration

tests/layer_validation_tests.cpp, tests/layer_validation_tests.h, tests/positive/pipeline.cpp, tests/vklayertests_descriptor_renderpass_framebuffer.cpp, tests/vklayertests_gpu.cpp, tests/vklayertests_others.cpp, tests/vklayertests_pipeline_shader.cpp
going to add supports/tests for some Ray Tracing stuff, but the `InitFrameworkForRayTracingTest` function was a little outdated and needed some refactoring and moved this out to its own PR
=> tests: Clean up InitFrameworkForRayTracingTest

layers/layer_options.cpp, layers/vk_layer_config.cpp, layers/vk_layer_config.h
This function was using layer_config.vk_layer_disables_env_var
as temporary storage so that it can return a char * which doesn't
have permanent storage. "Fix" this by using a static std::string
instead.
But really, there's not a safe way to implement this function on
all platforms we support. GetEnvironment() returns a std::string,
which solves this problem. Use that instead.
Fixes #3048
=> layers: GetLayerEnvVar shouldn't change the layer_config object

tests/layer_validation_tests.cpp, tests/layer_validation_tests.h, tests/vklayertests_descriptor_renderpass_framebuffer.cpp, tests/vklayertests_others.cpp, tests/vklayertests_pipeline_shader.cpp, tests/vktestbinding.cpp, tests/vktestbinding.h
Addresses #4296
Moving extension check to after call to InitFramework to make fewer tests skip
Fix validation errors in now running tests, mostly around use of buffer device address
=> Fix ray tracing tests and check extensions after InitFramework

layers/parameter_validation_utils.cpp, tests/layer_validation_tests.cpp, tests/layer_validation_tests.h, tests/positive/command.cpp, tests/positive/dynamic_rendering.cpp, tests/positive/image_buffer.cpp, tests/positive/other.cpp, tests/positive/pipeline.cpp, tests/positive/render_pass.cpp, tests/positive/shaderval.cpp, tests/vklayertests_arm_best_practices.cpp, tests/vklayertests_best_practices.cpp, tests/vklayertests_buffer_image_memory_sampler.cpp, tests/vklayertests_command.cpp, tests/vklayertests_descriptor_renderpass_framebuffer.cpp, tests/vklayertests_dynamic_rendering.cpp, tests/vklayertests_others.cpp, tests/vklayertests_pipeline_shader.cpp, tests/vklayertests_wsi.cpp, tests/vkrenderframework.cpp, tests/vkrenderframework.h, tests/vktestbinding.cpp, tests/vktestbinding.h
This PR enables validation errors after the end of the test until after cleanup.
It also reenables all validation errors (kErrorBit) which in some cases were ignored
It adds DeviceWaitIdle after the test before cleanup
It adds many fixes, mostly destroy calls and vk_testing
=> Reveal errors

tests/vklayertests_best_practices.cpp, tests/vkrenderframework.cpp
Many tests currently disable
other types of validation messages
however to make sure a test is working
we need a way to temporarily re-enable them.
This is now done with an environment variable like so :
VK_LAYER_TESTS_DISABLE_CORE_VALIDATION=false
or
VK_LAYER_TESTS_DISABLE_CORE_VALIDATION=FALSE
or
VK_LAYER_TESTS_DISABLE_CORE_VALIDATION=0
other values will not change the behaviour.
=> tests: Add env var to undisable validation

layers/generated/chassis.cpp, scripts/layer_chassis_generator.py
DestroyDevice should _always_ dispatch down to the driver (similar to
DestroyInstance) regardless of whether or not a validation error was
encountered.
=> layers: Always dispatch DestroyDevice

layers/queue_state.cpp, layers/queue_state.h, tests/positive/sync.cpp
This method could get called concurrently, such as if a wait on a semaphore and the fence occur simultaneously in different threads. Avoid bad state transitions in Retire() by only changing state if the fence is INFLIGHT, which will weed out any extra Retire() calls that happen.
Fixes #4271
=> layers: Fix a race condition in FENCE_STATE::Retire()

layers/best_practices_utils.cpp, layers/buffer_validation.cpp, layers/core_validation.cpp, layers/core_validation.h, layers/descriptor_sets.cpp, layers/descriptor_sets.h, layers/descriptor_validation.cpp, layers/gpu_validation.cpp, layers/gpu_validation.h, layers/image_layout_map.h, layers/synchronization_validation.cpp, layers/vk_layer_data.h
Storing descriptors in type specific, per binding vectors saves
memory (and improves cache utilization). Most descriptor objects are
are 48 bytes or less, but MutableDescriptor is almost 200 bytes.
Per binding storage also allows tight inner loops, which helps
performance for large bindless descriptor sets.
=> layers: Store descriptors in per-binding vectors

build-android/known_good.json, scripts/known_good.json, tests/positive/shaderval.cpp, tests/vklayertests_pipeline_shader.cpp
Update glslang to pull in this fix:
https://github.com/KhronosGroup/glslang/pull/2976.
@mikes-lunarg not sure if it's ok to "just update" glslang, or if there are other projects that also need to get updated. If there's more of a process involved, we can disable the affected tests for now.
cc @paul-lunarg.
=> build: Update glslang

layers/core_validation.h, layers/shader_module.cpp, layers/shader_module.h, layers/shader_validation.cpp, tests/positive/shaderval.cpp, tests/vklayertests_pipeline_shader.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/3282 (and https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/3283)
Just as we did for Spec Constants and `WorkGroupSize` this does the same for `ComputeSharedMemory`. This will apply the spec constant values and then rebuild the `def_index` and use that to get the correct size
=> Add Spec Constants Shared Memory

layers/descriptor_sets.h, layers/vk_layer_data.h
This reverts commit 94b7c2feac812e060041dff0c243b6950e122a78.
It is also causing CFI errors. Based on:
https://clang.llvm.org/docs/ControlFlowIntegrity.html#bad-cast-checking
this is probably only showing up for Descriptors because:
>    The checks are currently only introduced where the class being casted
>    to is a polymorphic class.
Presumably the other objects stored in small_vector are not polymorphic, but Descriptors are.
This is also for Issue #4333
=> layers: Revert "Use small_vector for storing Descriptors"

layers/shader_validation.cpp, tests/vklayertests_pipeline_shader.cpp
In release 1.3.220, the spec was clarified to say that the RelaxedPrecision qualifier does not need to match across interfaces. See section 15.1.3. Interface Matching.
This commit removes that check and the two associated tests I found.
=> Remove check for RelaxedPrecision interface matching

layers/core_validation.cpp
Moved checks using `src_as_state` inside `if (src_as_state) {`
=> layers: Fix crash in build acc struct

tests/vklayertests_descriptor_renderpass_framebuffer.cpp
If `layeredShadingRateAttachments` is `VK_FALSE` then VUID 04551 will be hit.
=> tests: Fix fsr framebuffer dimensions test

tests/vklayertests_pipeline_shader.cpp
This test would crash if `VK_KHR_ACCELERATION_STRUCTURE_EXTENSION_NAME` was supported but `VK_KHR_RAY_TRACING_PIPELINE_EXTENSION_NAME` wasn't.
=> tests: Fix ray tracing pipeline shader groups test

layers/generated/layer_chassis_dispatch.cpp, layers/generated/vk_safe_struct.cpp, layers/generated/vk_safe_struct.h, layers/ray_tracing_state.h, layers/state_tracker.cpp, scripts/helper_file_generator.py, scripts/layer_chassis_dispatch_generator.py
Hi maintainers,
I'm creating this draft PR mostly as a basis for discussion, as I'm not sure the current approach is the best way to solve this problem.
The issue I'm trying so solve is that [accelerationStructureReference in VkAccelerationStructureInstanceKHR](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkAccelerationStructureInstanceKHR.html) are wrapped when using the Validation Layer, which leads to issues for host builds when dereferencing them.
The current solution adds an unwrap of the accelerationStructureReference to [DispatchBuildAccelerationStructuresKHR](https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/3559/files#diff-dd8b2540519d29de84eacbb70d2221a96f68acabcb7e0a363743f51fb6f4878aR1263) in case of host builds, which requires additional …
=> layers: Add unwrap of ASReference in host builds

layers/descriptor_sets.cpp, layers/descriptor_sets.h, layers/descriptor_validation.cpp, tests/vklayertests_buffer_image_memory_sampler.cpp
Fix a problem with tracking the active descriptor type, which was introduced by https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/4126
Fix the check for VUID 04613, which was a preexisting condition. Improve the test case to show what the problem was.
=> layers: Fix mutable descriptor state active type state and checking

layers/core_validation.cpp
Closes #4347 
I agree with @CarloWood on the issue that the message isn't good, I purposed this fix that changes it from
> vkCmdDispatch(): VkPipeline 0x967dd1000000000e[] defined with VkPipelineLayout 0xead9370000000008[] is not compatible for maximum set statically used 0 with bound descriptor sets, last bound with VkPipelineLayout 0xe88693000000000c[]
to 
> vkCmdDispatch(): The VkPipeline 0x967dd1000000000e[] (created with VkPipelineLayout 0xead9370000000008[]) maximum descriptor set statically used (index #0) is not compatible with the currently bound descriptor sets' pipeline layout (VkPipelineLayout 0xe88693000000000c[])
=> layers: Improve VUID 02697 error message

tests/vkrenderframework.cpp, tests/vkrenderframework.h, tests/vksyncvaltests.cpp
Fix the broken begin render pass and restore the test that required
success.
=> tests: Restore Sync ordering test.

layers/synchronization_validation.cpp, layers/synchronization_validation.h, tests/layer_validation_tests.cpp, tests/layer_validation_tests.h, tests/vkrenderframework.cpp, tests/vkrenderframework.h, tests/vksyncvaltests.cpp, tests/vktestbinding.cpp, tests/vktestbinding.h
Update the first use/replay models to support renderpass and subpass operation validation at queue submit time.
=> Queue Submit Time Support for RenderPass based operations (default off)

layers/best_practices_utils.cpp
Fixes crash in dEQP-VK.draw.dynamic_rendering.instanced.dynamic_state_draw_vk_primitive_topology_point_list
=> Fix bad pVertexInputState dereference in Best Practices

layers/cmd_buffer_state.cpp, layers/cmd_buffer_state.h, layers/core_validation.cpp, layers/pipeline_state.h, layers/state_tracker.cpp, tests/vklayertests_graphics_library.cpp
The first commit fixes 06896 to only trigger the missing fragment shader error when rasterization is enabled. The second commit removes this check (see internal issue 3178 for details). I've left the "fix commit" in history because it is my understanding this change will be coming back in the near future, just gated behind something like a maintenance extension check.
=> Fix, then remove the fragment shader portion of 06896

layers/debug_printf.cpp, layers/descriptor_validation.cpp, layers/gpu_utils.cpp, layers/gpu_validation.cpp, layers/shader_module.cpp, layers/shader_validation.cpp, tests/vktestframework.cpp
Currently doing more validation work for ray tracing (`spirv-val` and now here) and updated some enum to use the `KHR` alias where it is used as a general enum (left if directly dealing with `VK_NV_ray_tracing`) as makes grepping much easier
=> layers: Use KHR RayTracing shader alias

layers/cmd_buffer_state.cpp, tests/vksyncvaltests.cpp
Many of these tests submit commands to multiple queues, but only detect errors on one queue. They should wait before ending to ensure that the successful commands complete before vulkan handles are destroyed.
These errors were hidden by a bug in CMD_BUFFER_STATE::Reset(), which shouldn't have been resetting the object in use count.
=> tests: Add missing device waits in SyncQS* tests

layers/shader_validation.cpp, tests/vklayertests_pipeline_shader.cpp
Adds the rest of the validation for `VK_EXT_subgroup_size_control`
-  VUID-VkPipelineShaderStageRequiredSubgroupSizeCreateInfo-requiredSubgroupSize-02760
-  VUID-VkPipelineShaderStageRequiredSubgroupSizeCreateInfo-requiredSubgroupSize-02761
-  VUID-VkPipelineShaderStageRequiredSubgroupSizeCreateInfo-requiredSubgroupSize-02762
=> Add VkPipelineShaderStageRequiredSubgroupSizeCreateInfo

layers/image_state.cpp
This new flag also needs to make IsDepthSliced() return true,
so it works just like VK_IMAGE_CREATE_2D_ARRAY_COMPATIBLE_BIT.
=> layers: Fix VK_IMAGE_CREATE_2D_VIEW_COMPATIBLE_BIT_EXT handling

layers/cmd_buffer_state.cpp, layers/cmd_buffer_state.h, layers/core_validation.cpp, layers/state_tracker.cpp, tests/positive/dynamic_rendering.cpp
Track if there are any commands called since CmdBeginRendering before
checking 06194, 01695, 06196, and 06197.
Closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/4235.
=> layers: Track commands since begin rendering

layers/best_practices_utils.cpp, layers/core_validation.cpp, layers/render_pass_state.h, layers/shader_validation.cpp
Add RENDER_PASS_STATE::UsesDynamicRendering() because several code
paths were going in the 'normal' RenderPass code when
use_dynamic_rendering_inherited == true but use_dynamic_rendering ==
false.
=> layers: Avoid crashes when dynamic_rendering is enabled

docs/creating_tests.md, tests/layer_validation_tests.cpp, tests/layer_validation_tests.h, tests/positive/pipeline.cpp, tests/vklayertests_buffer_image_memory_sampler.cpp, tests/vklayertests_command.cpp, tests/vklayertests_descriptor_renderpass_framebuffer.cpp, tests/vklayertests_gpu.cpp, tests/vklayertests_pipeline_shader.cpp, tests/vkrenderframework.cpp, tests/vkrenderframework.h
This came up as I was touching a GPU validation test (which doesn't use devsim) and realized `EnableDeviceProfileLayer` was never called it still was working
- Renamed `EnableDeviceProfileLayer` to a more accurate name `OverrideDevsimForDeviceProfileLayer`
- Everything using `GTEST_SKIP` now
- Create Test doc updated
- Moved all tests to use the `LoadDeviceProfileLayer` function
=> tests: Fix how device_profile_api layer is enabled

.github/workflows/build_linux.yml, .github/workflows/build_macos.yml, .github/workflows/build_windows.yml
Cache the builds of components that this project depends on to speed up
GitHub Actions builds.
The dependent components are specified in scripts/known_good.json whose
hash is used as a key for the cache.  When the known good file is
updated, a cache won't be found for that hash/key and the components are
rebuilt and cached again.
For the more common case for when the known good file does not change,
the cache is found and the dependent components don't need to be
rebuilt.
Documentation for this GitHub Actions feature can be found at:
https://docs.github.com/en/actions/using-workflows
in the "Caching dependencies to speed up workflows" section.  There are
also APIs available for managing the caches.
=> build: Add GitHub Actions dependency caching

tests/layer_validation_tests.cpp
I introduced this in https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/4369 by accident. Only 1 GPU-VA test is using this so it was just skipping instead of running
=> layers: Fix device profile regression typo

layers/debug_printf.cpp, layers/gpu_utils.cpp, layers/gpu_utils.h, layers/gpu_validation.cpp, layers/gpu_validation.h
- Moved `kShaderStageAllRayTracing` to `gpu_utils.h`
- use underscore naming convention in a few spots it was missing
- created a dedicated `Destroy` for `GpuAssistedPreDrawValidationState` to better give it ownership
- removed redundant `validation_` in `pre_draw_validation_state.validation_shader_module` and others related
- Replaced some magic numbers with `const`s
=> layers: More cleanup for GPUVA

tests/vklayertests_gpu.cpp, tests/vkrenderframework.cpp, tests/vkrenderframework.h, tests/vktestbinding.cpp, tests/vktestbinding.h
So I originally thought there was a bug with `vkQueueSubmit2` for GPU-Validation, but after writing a test I realize there isn't.
This test still adds a missing test for `VUID-vkCmdDrawIndexedIndirectCount-countBuffer-02717` and cleans up the `GpuDrawIndirectCountDeviceLimit` a bit. Also, I can see using the `submit2` for future tests
=> tests: Add submit2 GPU-Val test

layers/buffer_validation.cpp, layers/core_validation.cpp, layers/core_validation.h, layers/device_state.h, layers/state_tracker.cpp, tests/vklayertests_descriptor_renderpass_framebuffer.cpp, tests/vklayertests_dynamic_rendering.cpp, tests/vklayertests_pipeline_shader.cpp
Addresses #4267 
Does not include validation for VUID-VkMultisampledRenderToSingleSampledInfoEXT-pNext-06879
which is under question here https://gitlab.khronos.org/vulkan/vulkan/-/issues/3169
=> Validation and tests for VK_EXT_multisampled_render_to_single_sampled

layers/gpu_pre_draw_constants.h, layers/gpu_validation.cpp
I commented this in the code well I hope, but this prevents the case when `instrument.hpp` is updated and we will fail the `static_assert` and then only need to update the single `#define`
=> layers: Add static assert for instrument.hpp values

layers/synchronization_validation.cpp, layers/synchronization_validation.h
Store renderpass access contexts as unique pointers, s.t. refernces held stay valid.
=> SyncQS Alpha fix: Make RP access context pointers stable

layers/best_practices_utils.cpp, layers/cmd_buffer_state.cpp, layers/cmd_buffer_state.h, layers/core_validation.cpp, layers/debug_printf.cpp, layers/debug_printf.h, layers/gpu_validation.cpp, layers/gpu_validation.h, layers/state_tracker.cpp
So I want to use `has_dispatch_cmd` but currently, a `vkCmdDraw` is setting it so this change is to refactor/cleanup those variables
- Changed variable names to match code style
- When `vkCmdExecuteCommands` is called, updates the state for all the values (before only did for `draw` in the best practice layers)
- Moved the `PostCallRecordCmdTraceRays*` calls to `GpuAssistedBase` as they are just there to call `ValidationStateTracker` and noticed the GPU-AV was missing the `PostCallRecordCmdTraceRaysIndirect2KHR` call (but debug_printf had it)
-  edit:  `ValidationStateTracker` is a base class, so just removed functions all together
(cc @jeremyg-lunarg if you were touching this)
=> layers: Clean up CB state used in GPU-AV

layers/cmd_buffer_state.cpp, layers/pipeline_state.cpp, layers/pipeline_state.h, tests/positive/render_pass.cpp, tests/vklayertests_others.cpp
The push descriptorset state object should have cb->RemoveChild() called on it before it is destroyed, to avoid deadlock in CMD_BUFFER_STATE::NotifyInvalidate().
Fixes #4376
=> layers: Fix deadlock in vkCmdBeginRenderPass()

layers/shader_module.cpp, layers/shader_module.h, layers/shader_validation.cpp
Using `GetConstantValueById` and `GetConstantDef` is better as it checks for `OpCopyObject`. Also the function was not adding anything useful and wasn't even in the `SHADER_MODULE_STATE` class
=> layers: Move GetConstantValue

layers/cmd_buffer_state.cpp
This fixes race conditions in the commmand buffer destroy path.
=> layers: Hold the write lock in CMD_BUFFER_STATE::Destroy()

tests/layer_validation_tests.h, tests/positive/sync.cpp, tests/vklayertests_best_practices.cpp, tests/vklayertests_others.cpp, tests/vkrenderframework.cpp, tests/vkrenderframework.h
Since this is supposed be used to control multithreaded tests it should use std::atomic<bool>.
=> tests: Make ErrorMonitor::SetBailout use an atomic flag

layers/buffer_validation.cpp, layers/core_validation.h
There's not a good reason for a special buffer method that does the same thing.
=> corechecks: Use ValidateObjectNotInUse() for VkBuffers

build-android/jni/Application.mk, build-android/jni/shaderc/Application.mk
https://developer.android.com/ndk/guides/cpp-support recommends using
c++_shared for applications that use more than one shared library.
If multiple libraries using c++_static are loaded you end up with
several copies of the globals in the C++ runtime. This also happens
if the same library is dlopen/dlclosed several times. Some of the
c++ runtime globals are thread_local, so each copy consumes a
TLS key. There are only 128 TLS keys allowed on android, and the
unit tests can hit this because of repeatedly loading and unloading
VVL.
See https://github.com/android/ndk/issues/789 and the many issues
linked to it for more info.
=> build-android: Use c++_shared

layers/parameter_validation_utils.cpp, layers/stateless_validation.h, layers/vk_layer_utils.h, tests/layer_validation_tests.cpp, tests/layer_validation_tests.h, tests/layers/device_profile_api.cpp, tests/layers/vk_lunarg_device_profile_api_layer.h, tests/vklayertests_pipeline_shader.cpp
- VUID-VkPipelineColorBlendAttachmentState-colorBlendOp-01406
- VUID-VkPipelineColorBlendAttachmentState-advancedBlendIndependentBlend-01407
- VUID-VkPipelineColorBlendAttachmentState-advancedBlendIndependentBlend-01408
- VUID-VkPipelineColorBlendAttachmentState-colorBlendOp-01410
For the test I found it would be easier to set `VkPhysicalDeviceBlendOperationAdvancedPropertiesEXT` so added a commit to add support for `SetPhysicalDeviceProperties2EXT` to the Device Profile Layer
=> Add remaining VK_EXT_blend_operation_advanced VUID

layers/gpu_validation.cpp, layers/gpu_vuids.h, tests/vklayertests_gpu.cpp
I noticed that `VUID-VkDrawIndirectCommand-firstInstance-00501` and `VUID-VkDrawIndexedIndirectCommand-firstInstance-00554` were not "implemented" but realized there are 2 VUIDs doing the same thing, talking to Tobias offline, also agreed the function VUID should be removed in favor of the structure VUID. Raised issue to remove from the spec as well https://github.com/KhronosGroup/Vulkan-Docs/pull/1913
=> layers: Update drawIndirectFirstInstance VUID

layers/shader_module.cpp, layers/shader_module.h, tests/vklayertests_buffer_image_memory_sampler.cpp
the only difference between `OpInBoundsAccessChain` and `OpAccessChain` is `OpInBoundsAccessChain` guarantees to the driver that the pointer will not be out of bounds. I wrote a test but took the generated GLSL and replaced it for `OpInBoundsAccessChain` and found we were missing it when checking.
Also moved `shader_module_used_operators` reference out of the header as it wasn't needed (was struct accessing `OpAccessChain` values)
=> layers: Add OpInBoundsAccessChain to shader val

layers/generated/chassis.cpp, scripts/layer_chassis_generator.py
The message "Device Extension %s support is incomplete,
incorrect results are possible." makes it sound like the
driver does not fully support the extension while the real
reason of this message is the incomplete validation support
(mostly fixed by downloading a newer SDK when available).
=> layers: Explicit incomplete validation support

tests/vklayertests_dynamic_rendering.cpp
Currently fails on my AMD system with no fsr
=> Fix depth image usage in TestDynamicRenderingPipelineMissingFlags if no fragment shading rate

layers/shader_validation.cpp
I don't have a `SPV_NV_cooperative_matrix` capable device currently to test, but assuming CI passes this should be a trivial cleanup using the grammar file helper
=> layers: Use helper for CooperativeMatrix

layers/best_practices_utils.cpp, layers/best_practices_validation.h
The best practice layer had a few cases wher GetRead<> was called
sequentially and resulted in a hang as it waited on a lock that
the callstack it was already in had already locked on.
=> layers: Fix hangs in NV best practices

layers/gpu_validation.cpp, layers/gpu_validation.h
Use the current renderpass to create the pre-draw pipeline instead of the renderpass used to create the currently bound pipeline, which may have been destroyed
=> Use current renderpass to create pre-draw GPU-AV pipeline

scripts/format_utils_generator.py
I added this workaround in the original version of the script, can't see the gitlab, but XML seems updated to `16` now and this can be safely removed
=> layers: Remove todo and code workaround

tests/positive/command.cpp, tests/positive/descriptors.cpp, tests/positive/dynamic_rendering.cpp, tests/positive/graphics_library.cpp, tests/positive/image_buffer.cpp, tests/positive/other.cpp, tests/positive/pipeline.cpp, tests/positive/render_pass.cpp, tests/positive/shaderval.cpp, tests/vklayertests_best_practices.cpp, tests/vklayertests_buffer_image_memory_sampler.cpp, tests/vklayertests_command.cpp, tests/vklayertests_descriptor_renderpass_framebuffer.cpp, tests/vklayertests_dynamic_rendering.cpp, tests/vklayertests_gpu.cpp, tests/vklayertests_graphics_library.cpp, tests/vklayertests_nvidia_best_practices.cpp, tests/vklayertests_others.cpp, tests/vklayertests_pipeline_shader.cpp, tests/vklayertests_portability_subset.cpp, tests/vksyncvaltests.cpp
Went through a scrubbed most of the uses for `GetPhysicalDeviceFeatures2` so future tests can copy the good design pattern
We will see how CI likes this
=> tests: Better use of GetPhysicalDeviceFeatures2

tests/vklayertests_others.cpp
Nvidia exposes multiple memory types that have 0 properties.  This
causes a problem if one of those memory types is first for the
ValidateImportMemoryHandleType test because the test will still
select it and then the allocation for the buffer and image
memory import memory will fail with VK_OUT_OF_DEVICE_MEMORY.
Fix this by forcing device local memory flag to be used when querying
a proper memory allocation for this test.
Verified this still works for integrated Intel as well.
=> tests: Fix ValidateImportMemoryHandleType test on Nvidia laptop

tests/vklayertests_others.cpp
This reverts commit e79cd33a4b10e6f37468d142a3a17171a4e566cc.
This is because internal testing failed on both AMD and Nvidia even though
it works on Github and my machine.  Will investigate more later.
=> Revert "tests: Fix ValidateImportMemoryHandleType test on Nvidia laptop"

layers/buffer_validation.cpp, layers/descriptor_validation.cpp, layers/sync_vuid_maps.cpp, tests/vklayertests_buffer_image_memory_sampler.cpp, tests/vklayertests_descriptor_renderpass_framebuffer.cpp
This will still get false positives for 04437/04439, but those have been removed from the spec and will be addressed by the solution to #4312
=> Add validation and tests for VK_EXT_attachment_feedback_loop_layout

layers/gpu_shaders/README.md
I forgot about the `BUILD.gn` file and to prevent another version of https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/4453 I just added a note (for myself and others)
=> docs: Add new gpu_shader instructions

layers/descriptor_validation.cpp, layers/parameter_validation_utils.cpp, tests/vklayertests_descriptor_renderpass_framebuffer.cpp
This function I feels like it was from the original style of the VVL but duct taped with more stuff
removed the unneeded indirect function passing in all the object pointers. Moved the extension enum check out to stateless as well
=> layers: Refactor PreCallValidateCreateDescriptorSetLayout

layers/render_pass_state.cpp, layers/render_pass_state.h, layers/state_tracker.cpp, tests/positive/render_pass.cpp
From the spec:
> If queries are used while executing a render pass instance that has multiview enabled, the query uses N consecutive query indices in the query pool (starting at query) where N is the number of bits set in the view mask in the subpass the query is used in.
=> Fix queries in render pass with multiview

layers/best_practices_utils.cpp, tests/vklayertests_nvidia_best_practices.cpp
Fix the usage of VK_REMAINING_ARRAY_LAYERS and VK_REMAINING_MIP_LEVELS on NVIDIA Best Practices when tracking Z-Cull state.
This adds a generic function for iterating over all subresources while having VK_REMAINING_* in mind.
I tried using `IMAGE_STATE::subresource_encoder`, but I couldn't find a way to iterate all subresources with it.
I haven't been able to test this yet, for some unknown reason the tests are not picking up my locally built validation layers.
Fixes #4456.
=> layers: Fix VK_REMAINING_* on Z-Cull tracking

layers/core_validation.cpp
VUs that enforced render pass being valid where not actually checking
that, incorrectly triggering when render pass was indeed valid.
=> Fix validation of VK_EXT_rasterization_order_attachment_access

tests/vkrenderframework.cpp, tests/vkrenderframework.h
Given how it is used, VkRenderFramework::physDevProps() should return a const reference to avoid unnecessary copy of a not so small structure. Besides, the copy not being deep, copying the `char*` may lead to memory issues in the future (and we are not so far from one at the moment).
This method is used twice:
https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/6086f7993dde6e6d8a9e0f8eef29584289bd216f/tests/vkrenderframework.cpp#L757-L759
https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/6086f7993dde6e6d8a9e0f8eef29584289bd216f/tests/layer_validation_tests.cpp#L1027-L1030
=> Make VkRenderFramework::physDevProps() return const ref

layers/shader_module.cpp, layers/shader_module.h, tests/positive/shaderval.cpp
The shader from `spv_source` in the test was never actually being used in the test, Luckily it seems to work correctly locally.
Not sure how this never triggered any `-Wunused-variable` warning (including locally)
=> tests: Fix SpirvGroupDecorations test

layers/json/VkLayer_khronos_validation.json.in, layers/vk_layer_settings.txt
layers/vk_layer_config.cpp defaults "report_flags" to just "error":
value_map_["khronos_validation.report_flags"] = "error";
while "error,warn,perf" is listed as the default in both vk_layer_settings.txt:
khronos_validation.report_flags = error,warn,perf
and layers/json/VkLayer_khronos_validation.json.in:
"default": [
"error",
"warn",
"perf"
]
This change makes the latter two files match the current code by changing the
default to be just "error".
This affects shipped SDK files as well as vkconfig behavior and SDK documentation.
=> docs: fix default value of report_flags

tests/layer_validation_tests.cpp, tests/layer_validation_tests.h, tests/positive/image_buffer.cpp, tests/positive/pipeline.cpp, tests/vklayertests_best_practices.cpp, tests/vklayertests_buffer_image_memory_sampler.cpp, tests/vklayertests_dynamic_rendering.cpp, tests/vklayertests_others.cpp, tests/vklayertests_pipeline_shader.cpp, tests/vklayertests_wsi.cpp
Fix for issue [#4449](https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/4449)
Using DeviceValidationVersion() is the correct way to get the supported API version, since it returns the API version supported by the device. SetTargetApiVersion() used to return the API version supported by the Vulkan instance. It now returns void to prevent further harm.
Replaced every call where the return value was used with a subsequent call to DeviceValidationVersion() after the init step (except when that call was already done).
=> Fix Issue #4449

tests/vkrenderframework.cpp
Spotted by @jeremy-lunarg 
The return value of find can be invalid, thus must be checked before use.
=> Fix VkRenderFramework::IsPlatform()

layers/descriptor_validation.cpp
realize we never added the `if (has_format_feature2) {` around the buffer view check as we did for the image view
=> layers: Add format_feature_2 wrapper around buffer views

tests/layer_validation_tests.cpp, tests/layer_validation_tests.h, tests/positive/pipeline.cpp, tests/vklayertests_buffer_image_memory_sampler.cpp, tests/vklayertests_descriptor_renderpass_framebuffer.cpp, tests/vklayertests_gpu.cpp, tests/vklayertests_others.cpp, tests/vklayertests_pipeline_shader.cpp
The main goal/point of this PR is to have all the `VkGpuAssistedLayerTest` go through `GetValidationFeatures` to get the base `VkValidationFeaturesEXT` struct so there is a single place to adjust the `VkValidationFeatureDisableEXT` set when developing new tests (previously done in `InitGpuAssistedFramework` and `InitFrameworkForRayTracingTest`)
Also just general cleanup such as using the new `AddRequiredExtensions` and `GTEST_SKIP` pattern
cc @jeremyg-lunarg if we decide to use `VK_LAYER_TESTS_DISABLE_CORE_VALIDATION` that is fine as well, but still think this change better makes the tests consistent with each other
=> tests: Add single entry for VkGpuAssistedLayerTest

layers/core_validation.h, layers/core_validation_error_enums.h, layers/shader_validation.cpp, tests/vklayertests_pipeline_shader.cpp
So I am 99% sure no one (including CI) was running these tests as they did not have valid SPIR-V and I just ran on a device without `shaderStorageImageReadWithoutFormat` feature support and realized this
- The `UNASSIGNED-features-shaderStorageImageReadWithoutFormat` (and `write`) VU is redundant as `spirv-val` is checking it and there is no way to hit this VU in the VVL https://github.com/KhronosGroup/SPIRV-Tools/pull/2486/files
- With the `UNASSIGNED` VU gone, the only thing being checked in `ValidateShaderStorageImageFormats()` was the `OpVariable` so moved that function into the `ValidateVariables` to save from call it every instruction
=> layers: Refactor StorageImageFormat tests

layers/core_validation.cpp, tests/vklayertests_descriptor_renderpass_framebuffer.cpp
Previous interpretation of "If multisampled-render-to-single-sampled is enabled" was that the extension was enabled. This changes the interpretation to mean that it is enabled for the subpass.
=> Fix multisampled_render_to_single_sampled interpretation of "enabled"

layers/buffer_validation.cpp, tests/vklayertests_buffer_image_memory_sampler.cpp
Closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/4305
Added a commit to also remove the redundant `else { if () { }` statement below this VU
=> Fix VUID 01586 format check

tests/layer_validation_tests.cpp, tests/vklayertests_amd_best_practices.cpp, tests/vklayertests_arm_best_practices.cpp, tests/vklayertests_best_practices.cpp, tests/vklayertests_command.cpp, tests/vklayertests_gpu.cpp, tests/vkrenderframework.cpp, tests/vkrenderframework.h, tests/vksyncvaltests.cpp
Since core checks are currently disabled in best practices (as well as GPU-AV and SyncVal) many tests are invalid, and may cause undefined behavior in the drivers.
=> Fix testing framework

tests/vkrenderframework.cpp
Add back unexpected errors to other_messages_ so VerifyFound and VerifyNotFound can fail the test when finding unexpected messages, while also removing DumpFailureMsgs because unexpected errors are now immediately printed, to avoid a double print.
=> Fix unexpected errors not failing tests

layers/best_practices_utils.cpp, tests/vklayertests_best_practices.cpp
When requesting an API version that deprecates an extension that is enabled on the device, a BP warning is always triggered, even if the device doesn't support the requested API version and hasn't deprecated the extension.
This fix compares the extension deprecation version to the device version instead of the instance API version.
Closes #4293
=> Fix warning for loading deprecated extension

CMakeLists.txt, layers/buffer_validation.cpp
(Previously PR https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/4486)
CMAKE_COMPILER_IS_GNUCC usage is not recommended by official doc. Besides, it may be true for clang, potentially leading to errors. So use CMAKE_GNU_COMPILER_ID instead, a variable already available in CMake 3.10
[Official CMAKE_COMPILER_IS_GNUCC  doc](https://cmake.org/cmake/help/v3.10/variable/CMAKE_COMPILER_IS_GNUCC.html)
=> Fix deprecated CMAKE_COMPILER_IS_GNUCC

tests/layer_validation_tests.h, tests/positive/pipeline.cpp, tests/vklayertests_gpu.cpp, tests/vklayertests_wsi.cpp
should fix the following from https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/4425
`VkPositiveLayerTest.OpCopyObjectSampler`
`VkLayerTest.BindImageMemorySwapchain`
`VkGpuAssistedLayerTest.GpuValidationInlineUniformBlockAndMiscGpu`
`VkGpuAssistedLayerTest.DrawTimeShaderUniformBufferTooSmall`
`VkGpuAssistedLayerTest.DrawTimeShaderStorageBufferTooSmall`
`VkGpuAssistedLayerTest.DrawTimeShaderUniformBufferTooSmallArray`
`VkGpuAssistedLayerTest.DrawTimeShaderUniformBufferTooSmallNestedStruct`
`VkGpuAssistedLayerTest.GpuDrawIndirectFirstInstance`
(cc @lunarpapillo )
=> tests: Fix tests failing on pixel 6

.github/workflows/build_linux.yml, .github/workflows/build_macos.yml, .github/workflows/build_windows.yml, CMakeLists.txt, scripts/common_ci.py, scripts/update_deps.py
- Extend update_deps.py to skip repos if install dir is present
- Cache only build/install directories from dependent repos in the
external directory
This change keeps update_deps from fetching a repo on top of a cached
repo and building an already built repo. (Previously, the entire
external directory was cached.)
It also significantly lowers the amount of data cached, allowing more
caches (related to versions of known_good.json) to be saved.
=> build: Improve GitHub Actions caching

layers/generated/thread_safety.h, layers/range_vector.h, layers/state_tracker.h, layers/vk_layer_utils.h, scripts/thread_safety_generator.py
Issue https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/4460
Remove some calls to `std::move` that prevent copy elision.
=> Remove std::move calls preventing copy elision

layers/core_validation.cpp, layers/core_validation.h, layers/shader_validation.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/4478
Make use of `LogObjectList` and putting the actual `VkShaderModule` handle
Also removed `pipeline->pipeline()` as this is pre-pipeline validation so that handle is going to be NULL
=> layers: Improve objects reported in shader val messages

tests/vktestbinding.cpp
adf933c0d3f1ff2cffaefb21093176c0bd0af40a broke extension enumeration by returning {} for VK_INCOMPLETE. Found because header 1.3.226 pushed the device extension count > 256.
=> tests: Fix layer/extension enumeration

layers/buffer_validation.cpp, tests/vklayertests_command.cpp
This PR adds a check and a test for using VK_REMAINING_ARRAY_LAYERS with VkImageSubresourceLayers.layerCount, which is unsupported. 
This check will trigger in place of the currently established check for VUID-vkCmdCopyImage-srcSubresource-01698 (for example in the case of vkCmdCopyImage), since there is no VUID for this yet. 
Closes #4485
=> Add check for VkImageSubresourceLayers.layerCount == VK_REMAINING_ARRAY_LAYERS

layers/buffer_validation.cpp
Fix for issue https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/4487
VK_QUEUE_FAMILY_IGNORED is considered special.
=> Fix ValidatorState::IsValidOrSpecial(queue_family)
