KhronosGroup/Vulkan-ValidationLayers

- layers/core_validation.cpp
- layers/queue_state.cpp
- layers/queue_state.h
- tests/vklayertests_others.cpp
> Fix issue 2334, fix checking multiple queues waiting on same semaphore

- tests/vklayertests_buffer_image_memory_sampler.cpp
Closes #2500
The CTS test in the issue is not active anymore, but the issues appears to be fixed already.
> tests: Test creating image view with invalid aspect

- tests/vklayertests_descriptor_renderpass_framebuffer.cpp
> tests: Test using pipeline with incompatible subpass

- layers/descriptor_sets.cpp
- tests/vklayertests_descriptor_renderpass_framebuffer.cpp
> Fix variable descriptor sizes

- layers/core_validation.cpp
- tests/positive/pipeline.cpp
> layers: Fix dual source blend with dynamic rendering

- layers/best_practices_error_enums.h
- layers/best_practices_utils.cpp
- tests/vklayertests_best_practices.cpp
> Warn when semaphore is set but semaphore count is 0

- layers/core_validation.cpp
- tests/vklayertests_graphics_library.cpp
Ensure matching link time optimization flags for GPLs.
> layers: Add VUID 06609, 06610

- layers/core_validation.cpp
- tests/vklayertests_others.cpp
Fixes incorrect VUIDs for invalid command buffers used at queue submit
time.
Closes #4046.
> layers: Fix valid CB queue submission

- layers/core_validation.cpp
- tests/positive/dynamic_rendering.cpp
- tests/vklayertests_dynamic_rendering.cpp
> layers: Fix checking color integer formats with dynamic rendering

- layers/core_validation.cpp
- tests/positive/render_pass.cpp
> layers: Fix checking enabled multiview feature

- layers/descriptor_sets.cpp
- layers/descriptor_sets.h
- tests/positive/pipeline.cpp
Closes #3835 
Closes #3977 
Closes #3729
> Fix destroying descriptors with UPDATE_AFTER_BIND

- layers/json/VkLayer_khronos_validation.json.in
- layers/vk_layer_config.cpp
- layers/vk_layer_settings.txt
This should have been part of PR #4073
> layers: Enable fine-grained locking in settings and manifest

- layers/core_validation.cpp
- layers/core_validation.h
Closes #4060 
Don't think I can write a test for that, but the change is simple.
> layers: Check if zero allocation size is allowed

- scripts/check_code_format.py
There was a recent cleanup of test code to use LvlInitStruct and this check is an effort to avoid new non-use cases from sneaking in. There are, of course, legitimate cases where LvlInitStruct cannot be used, but I expect the majority of cases this new check catches will be places that LvlInitStruct can be used.
> Check for sType assignment instead of LvlInitStruct

- layers/core_validation.cpp
- tests/vklayertests_descriptor_renderpass_framebuffer.cpp
> layers: Fix getting imageView layerCount

- CMakeLists.txt
- layers/pipeline_state.h
- tests/vktestbinding.h
> build: Enable -Wstring-conversion

- layers/parameter_validation_utils.cpp
- layers/stateless_validation.h
> layers: Use correct GetPhysicalDeviceProperties2 function

- scripts/known_good.json
Use the main branch per GoogleTest's recommendation.
> tests: Update GoogleTest to latest

- layers/parameter_validation_utils.cpp
- tests/vklayertests_pipeline_shader.cpp
Addresses https://vulkan.lunarg.com/issue/view/627f6bae5df112b82c77a71d
> Fix handling of a null stage pName

- layers/core_validation.cpp
- layers/vk_layer_utils.h
- tests/vklayertests_pipeline_shader.cpp
This is the same VUID that caused #3115
> Add vuid 06039 06040, Validate depth stencil read only attachment

- docs/creating_tests.md
- tests/positive/command.cpp
- tests/positive/descriptors.cpp
- tests/positive/dynamic_rendering.cpp
- tests/positive/graphics_library.cpp
- tests/positive/image_buffer.cpp
- tests/positive/other.cpp
- tests/positive/pipeline.cpp
- tests/positive/render_pass.cpp
- tests/positive/shaderval.cpp
- tests/vklayertests_buffer_image_memory_sampler.cpp
- tests/vklayertests_command.cpp
- tests/vklayertests_descriptor_renderpass_framebuffer.cpp
- tests/vklayertests_dynamic_rendering.cpp
- tests/vklayertests_graphics_library.cpp
- tests/vklayertests_others.cpp
- tests/vklayertests_pipeline_shader.cpp
- tests/vkrenderframework.cpp
- tests/vkrenderframework.h
- tests/vksyncvaltests.cpp
saw https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/4121#discussion_r876337947 and decided to just fix this now this is a long time needed cleanup/fix IMO
> tests: Extension check unified

- layers/buffer_validation.cpp
- tests/vklayertests_command.cpp
Could not find a format to test 06763 and 06765
> Add vuid 06762 06763 06764 06765, Validate resolve image usage and format features

- layers/buffer_validation.cpp
- tests/vklayertests_buffer_image_memory_sampler.cpp
I was checking a few things for subresource layouts and VUID-02271 was halfway implemented. I'm not very familiar with DRM formats, so if there's anything to be changed let me know.
> Complete missing 02271 check

- layers/parameter_validation_utils.cpp
- tests/vklayertests_buffer_image_memory_sampler.cpp
Adds `VUID-VkDeviceImageMemoryRequirementsKHR-pCreateInfo-06776`
> layers: Add VU 06776

- docs/fine_grained_locking.md
- docs/fine_grained_locking_usage.md
- layers/json/VkLayer_khronos_validation.json.in
This feature is no longer beta since it is enabled by default.
> Update docs and json for fine-grained locking

- layers/core_validation.cpp
nit small fix to use the `GetPipelineTypeName` helper function
> layers: Use GetPipelineTypeName for message

- layers/core_validation.cpp
Fixes an old hidden bug that never saw the light of the day until the sparse rework was introduced. Before the rework, the check was just trying to see if the images would overlap taking the data from the device memory bound to the resource (offset and size were used), all the resource. However, size was always 0, so no matter what the check would always not find any overlap. After the rework was introduced, the size started being the correct one. However, we still checked the whole resource instead of the subresource range that the image view covered.
With this change, we should now be correctly checking attachment overlap.
> layers: Fix attachment overlap check

- tests/vklayertests_dynamic_rendering.cpp
Same tests as `VUID-VkRenderingAttachmentInfo-imageView-06130` just with different format
> tests: Add dynamic rendering VUID 06129

- tests/positive/dynamic_rendering.cpp
- tests/positive/image_buffer.cpp
- tests/vklayertests_best_practices.cpp
- tests/vklayertests_buffer_image_memory_sampler.cpp
- tests/vklayertests_command.cpp
- tests/vklayertests_descriptor_renderpass_framebuffer.cpp
- tests/vklayertests_dynamic_rendering.cpp
- tests/vklayertests_graphics_library.cpp
- tests/vklayertests_pipeline_shader.cpp
Just more cleanup to use `GTEST_SKIP` when possible
> tests: Use GTEST_SKIP

- layers/core_validation.cpp
- tests/positive/dynamic_rendering.cpp
Ensure that resuming _and_ suspending at vkCmdBeginRendering time works
as expected.
Closes #4195.
> layers: Fix resume + suspend rendering

- layers/core_validation.cpp
In the previous fix I chose the wrong range generator. I should have used `ImageRangeGenerator` that will correctly return resource offsets. ~This PR needs to have #4206 merged first. Otherwise, the check will not correctly happen with the subresource range that covers first mip and depth.~
> Use ImageRangeGenerator instead of RangeGenerator for renderpass check

- layers/core_validation.cpp
- tests/vklayertests_graphics_library.cpp
This also avoids crashing in the case where 06642 is violated as CTS
currently does this.
> layers: Add VUID 06642

- tests/positive/image_buffer.cpp
Create renderpass with multiple subpasses that draw to color attachments. These attachments won't overlap since the framebuffer will have different slices of a 3D image as attachments.
Test was requested in #4207. Without #4207 this test fails due to incorrectly reporting attachment overlap.
> tests: Test no false overlap with sliced 3d image as framebuffer

- tests/vksyncvaltests.cpp
> build: Fix build after test refactor

- layers/gpu_validation.cpp
Fixes DEVICE_LOST seen recently running VkGpuAssistedLayerTest.GpuValidationArrayOOBRayTracingShaders
> Fix diagnostic acceleration structure creation

- layers/CMakeLists.txt
- layers/synchronization_validation.cpp
- layers/synchronization_validation.h
- tests/vkrenderframework.cpp
- tests/vkrenderframework.h
- tests/vksyncvaltests.cpp
- tests/vktestbinding.cpp
- tests/vktestbinding.h
Progress toward Phase II goals, adding correct queue scoping for barrier effects and improving barrier chain correctness for both submit time and CmdExec record time
> Adding QueueSubmit Cmd*Event suppport

- layers/synchronization_validation.cpp
- layers/synchronization_validation.h
- tests/vksyncvaltests.cpp
Model update and test for QSO restrictions on sync ops.
> Apply queue submit order logic to barriers and first use error detection

- layers/core_validation.cpp
- layers/generated/parameter_validation.cpp
- layers/parameter_validation_utils.cpp
- scripts/parameter_validation_generator.py
- tests/layer_validation_tests.cpp
- tests/layer_validation_tests.h
- tests/positive/descriptors.cpp
- tests/positive/graphics_library.cpp
- tests/positive/image_buffer.cpp
- tests/positive/other.cpp
- tests/positive/pipeline.cpp
- tests/positive/shaderval.cpp
- tests/vklayertests_amd_best_practices.cpp
- tests/vklayertests_arm_best_practices.cpp
- tests/vklayertests_best_practices.cpp
- tests/vklayertests_buffer_image_memory_sampler.cpp
- tests/vklayertests_command.cpp
- tests/vklayertests_descriptor_renderpass_framebuffer.cpp
- tests/vklayertests_dynamic_rendering.cpp
- tests/vklayertests_gpu.cpp
- tests/vklayertests_imageless_framebuffer.cpp
- tests/vklayertests_others.cpp
- tests/vklayertests_pipeline_shader.cpp
- tests/vklayertests_viewport_inheritance.cpp
- tests/vklayertests_wsi.cpp
- tests/vkrenderframework.cpp
- tests/vkrenderframework.h
- tests/vksyncvaltests.cpp
- tests/vktestbinding.cpp
- tests/vktestbinding.h
Test fixes after ensuring all test code is "expect success" by default.
> tests: Enable ExpectSuccess default

- docs/creating_tests.md
Update test documentation to reflect recent updates to the
ErrorMonitor's behavior.
Also removes more references to devsim.
> tests: Update documentation

- layers/generated/chassis.cpp
- scripts/generate_source.py
Validation for this extension was completed.
Fixes #3764
> scripts: Remove VK_KHR_dynamic_rendering warning

- layers/buffer_state.h
- layers/cmd_buffer_state.h
- layers/core_validation.cpp
- layers/core_validation.h
- layers/device_memory_state.cpp
- layers/device_memory_state.h
- layers/generated/object_tracker.cpp
- layers/generated/parameter_validation.cpp
- layers/image_state.cpp
- layers/image_state.h
- layers/object_tracker_utils.cpp
- layers/parameter_validation_utils.cpp
- layers/queue_state.h
- layers/state_tracker.cpp
- layers/state_tracker.h
- layers/stateless_validation.h
- scripts/object_tracker_generator.py
- scripts/parameter_validation_generator.py
- tests/CMakeLists.txt
- tests/vklayertests_others.cpp
- tests/vkrenderframework.cpp
Addresses #4215 
The new test passed on an M1 and Intel Mac
> Add validation and tests for VK_EXT_metal_objects

- tests/vklayertests_gpu.cpp
Works around shader input/output mismatches
> Add maintenance4 to GpuValidationArrayOOBGraphicsShaders

- layers/shader_validation.cpp
- tests/vklayertests_pipeline_shader.cpp
If a shader stage does not consume an input, it should be a warning, not
an error.
Closes #4352.
> layers: Make outputs not consumed a warning

- layers/range_vector.h
- layers/synchronization_validation.cpp
- layers/synchronization_validation.h
- layers/vk_layer_data.h
- tests/vksyncvaltests.cpp
Alpha Candidate for phase II -- with known gaps (missing Submit2)
> Add fence wait support to the queue submit feature.  

- layers/debug_printf.cpp
- layers/debug_printf.h
- layers/gpu_pre_draw_constants.h
- layers/gpu_utils.cpp
- layers/gpu_utils.h
- layers/gpu_validation.cpp
- layers/gpu_validation.h
In my effort to learn more about the GPU-Validation code to add more runtime SPIR-V validation I had some house cleaning fixes decided to push here
> layers: Some cleanup and comments for GPU-Val

- layers/shader_validation.cpp
- tests/vklayertests_pipeline_shader.cpp
Ensures that OutputNotConsumed is a warning in _all_ cases.
> layers: Make OutputNotConsumed a warning

- layers/pipeline_state.cpp
- layers/shader_validation.cpp
- tests/positive/shaderval.cpp
> Fix compatibility with VK_EXT_shader_module_identifier

- tests/vklayertests_descriptor_renderpass_framebuffer.cpp
- tests/vktestbinding.cpp
Fix case where test failure should be a test skipped.
> tests: Fix DSBufferLimitErrors

- docs/synchronization_usage.md
- layers/json/VkLayer_khronos_validation.json.in
Add the enable for QueueSubmit time synchronization validation, set as
alpha.
@christophe-lunarg  -- not sure how to test this.
> Add SyncVal QueueSubmit as ALPHA

- scripts/generate_spirv.py
Useful for CIs with strict sandboxing rules (i.e. @google).
The recent change to this script has broken our internal CI builds. This adds back the optional 'outfilename' arg that we need so that we can specify a safe path.
> Add back 'outfilename' arg to generate_spirv.py

- tests/positive/sync.cpp
- tests/vklayertests_buffer_image_memory_sampler.cpp
- tests/vklayertests_command.cpp
- tests/vksyncvaltests.cpp
About to make PR for something related to sync2 and pulled these extra tests out into own PR
> tests: Add AccessMask2 tests

- tests/positive/shaderval.cpp
In response to https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/4399#issuecomment-1215074307 I quick wrote a test using `OpSpecConstant` for `OpTypeArray` to verify to myself that it should never be hitting `GetConstantValue` for `GetTypeBitsSize` when it has a spec constant
> tests: Add OpTypeArray spec constant tests

- layers/shader_module.cpp
- layers/shader_validation.cpp
- tests/positive/shaderval.cpp
cc @amaiorano - should fix your issue until I get a fix in SPIRV-Tools and we pull it in... the test I change reproduces the issue you were having
> layers: Rerun spec const fold pass temporarily

- layers/synchronization_validation.cpp
- layers/synchronization_validation.h
Modify the apply barriers functors to reflect queue submit time
validation needs.
> syncval: Add queue submit apply barriers support

- layers/gpu_utils.cpp
> Fix new VMA by supplying Get*ProcAddr

- tests/layer_validation_tests.cpp
- tests/layer_validation_tests.h
- tests/positive/command.cpp
- tests/positive/descriptors.cpp
- tests/positive/dynamic_rendering.cpp
- tests/positive/graphics_library.cpp
- tests/positive/image_buffer.cpp
- tests/positive/other.cpp
- tests/positive/pipeline.cpp
- tests/positive/render_pass.cpp
- tests/positive/shaderval.cpp
- tests/vklayertests_buffer_image_memory_sampler.cpp
- tests/vklayertests_command.cpp
- tests/vklayertests_descriptor_renderpass_framebuffer.cpp
- tests/vklayertests_dynamic_rendering.cpp
- tests/vklayertests_gpu.cpp
- tests/vklayertests_graphics_library.cpp
- tests/vklayertests_nvidia_best_practices.cpp
- tests/vklayertests_others.cpp
- tests/vklayertests_pipeline_shader.cpp
- tests/vklayertests_portability_subset.cpp
- tests/vksyncvaltests.cpp
should help address some failures in https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/4425
> tests: Use new GetPhysicalDevice helpers

- BUILD.gn
> build: Disable -Wnullability-completeness for VMA

- layers/core_validation.cpp
- tests/vklayertests_others.cpp
Adds an allowed zero-sized allocation case based on VUID 01874.
> layers: Add zero-size alloc case

- layers/shader_module.cpp
- layers/shader_validation.cpp
address issue in https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/4255#issuecomment-1219214198
> layers: Handle OpTypeBool in structs

- BUILD.gn
Add missing include "layers/generated/gpu_pre_dispatch_comp.h"
Fixes #4398
> Fix BUILD.gn

- tests/vklayertests_pipeline_shader.cpp
I'm finding that some drivers wont create a pipeline from a shader module id without creating one with the shader module
> Fix ShaderModuleIdentifier test

- layers/synchronization_validation.cpp
- layers/synchronization_validation.h
- tests/vksyncvaltests.cpp
Refactored the Sync1 QueueSubmit code to support both paths.  Simplifying some of the template madness by simply converting the Sync 1 parameter to the Sync 2 set, and using plain common functions for the validate and record functions.
Some minor flattening of twoliner functions that were called once.
A simple Submit2 test case with test helper object refinements.
> Enable QueueSubmit2 and 2KHR in SyncVal

- layers/best_practices_utils.cpp
- tests/vklayertests_nvidia_best_practices.cpp
Fix Issue #4457
Add positive test for correct behavior with one time submit
Fix typo in NV layers
> Fix Issue #4457

- layers/shader_module.cpp
- layers/shader_validation.cpp
- tests/positive/pipeline.cpp
Should fix https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/4255#issuecomment-1225956592 (cc @Tony-LunarG the CTS ran for me without crashing now too)
> layers: Handle PhysicalStorageBuffer to itself

- layers/synchronization_validation.h
Add logic to correctly apply cross queue synchronization.
> syncval: Fix ILT hazard rules across queues.

- layers/buffer_validation.cpp
- layers/core_validation.cpp
- layers/core_validation.h
- layers/image_state.h
- tests/vklayertests_descriptor_renderpass_framebuffer.cpp
Also remove incorrect 06881 checks in imageless framebuffer path that has no attachments to check yet.
> Add new multisampled_render_to_single_sampled VUIDs  07009 07010

- layers/sync_vuid_maps.cpp
> layers: Fix error message for kQueueErrorSummary

- layers/buffer_validation.cpp
- tests/vklayertests_buffer_image_memory_sampler.cpp
Change 01584 to 07072 and check for uncompressed format
Remove 04739
Closes #4503
Closes #4502
> Update VkImageViewCreateInfo VUIDs 01584 and 04739

- layers/shader_module.cpp
The variable names in `shader_module_used_operators` are not helpful so renamed them to better suit what they are actually used for now
> layers: Rename misleading shader_module variables

- layers/generated/spirv_grammar_helper.cpp
- layers/generated/spirv_grammar_helper.h
- layers/shader_module.cpp
- scripts/spirv_grammar_generator.py
to be used for `VK_EXT_mesh_shader` PR
> layers: Generate ExecutionModel string util

- layers/core_validation.cpp
Breaks early if no input attachments in subpass.
Looks for input attachment descriptors in layout instead of descriptors, then accesses descriptor state correctly this time (I hope ?)
Closes #4555
> Rework VUID 02686

- layers/buffer_validation.cpp
- layers/core_validation.cpp
- layers/device_state.h
- layers/state_tracker.cpp
- layers/stateless_validation.h
- layers/sync_vuid_maps.cpp
- layers/sync_vuid_maps.h
- tests/vklayertests_buffer_image_memory_sampler.cpp
- tests/vklayertests_descriptor_renderpass_framebuffer.cpp
New VUIDs were added, requiring the feature to use the layout.
> Validate the attachment_feedback_loop_layout feature

- tests/positive/sync.cpp
Test case for Issue #2756. I cannot get the error to reproduce, even running against the old version of VVL mentioned in the Issue. But it is still a good test to have.
> tests: Add VkPositiveLayerTest.SubmitFenceButWaitIdle

- layers/core_validation.cpp
- tests/layer_validation_tests.cpp
- tests/vklayertests_descriptor_renderpass_framebuffer.cpp
labels `VUID-VkAttachmentReference2-layout-03077` and `VUID-VkAttachmentReference2-synchronization2-06910`
> layers: Label RP1 version of Attachment Ref VU

- layers/best_practices_utils.cpp
> Add null check for descriptor sets

- .gitignore
Allows users to have their own custom presets to speed up local workflows.
> git: Ignore CMakerUserPresets.json

- layers/buffer_validation.cpp
- tests/vklayertests_dynamic_rendering.cpp
I was forgetting an indirection level, since `vkCmdClearAttachments` refers to sub pass attachments, not render pass attachments.
This PR also adds a corresponding test case.
> Fix for PR #4595 - Color attachments indices are incorrectly managed

- build-android/known_good.json
- layers/generated/spirv_tools_commit_id.h
- scripts/known_good.json
I also included the changes from running clang-format on the known-good.json files in this PR. Been meaning to do that for a while...
> build: Update glslang for mesh shader extension

- BUILD.md
- Address concerns from PR#4659
- Use bash syntax highlighting
- Update Visual Studio docs
> docs: Improve BUILD.md

- layers/parameter_validation_utils.cpp
- tests/vklayertests_command.cpp
Check if offset in CmdDrawIndexedIndirect is a multiple of 4
> Adding vuid cmd draw indexed indirect 02710

- layers/best_practices_error_enums.h
- layers/best_practices_utils.cpp
- layers/best_practices_validation.h
- tests/vklayertests_best_practices.cpp
> Validate image barrier access layout combinations

- layers/buffer_validation.cpp
Seems this VUID was [internally updated](https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/5324) without a VUID update
> layers: Fix VUID 06415

- tests/positive/other.cpp
- tests/vklayertests_best_practices.cpp
- tests/vklayertests_buffer_image_memory_sampler.cpp
- tests/vklayertests_command.cpp
- tests/vklayertests_descriptor_renderpass_framebuffer.cpp
- tests/vklayertests_others.cpp
- tests/vklayertests_pipeline_shader.cpp
- tests/vklayertests_wsi.cpp
- tests/vkrenderframework.cpp
Fail the test on reception of unexpected message
> Fix unexpected messages

- BUILD.gn
Format with gn version "2065 (b9c6c19be95a)"
> build: Run gn format on BUILD.gn

- layers/parameter_validation_utils.cpp
- tests/vklayertests_others.cpp
Found these are missing when implementing relevant CTSes.
> layers: Add check for 02267, 02268 and 02269

- layers/best_practices_utils.cpp
- tests/vklayertests_best_practices.cpp
> practices: Fix VK_IMAGE_LAYOUT_PRESENT_SRC_KHR access mask check

- layers/parameter_validation_utils.cpp
- tests/vklayertests_wsi.cpp
Validate pNext structs in vkGetPhysicalDeviceSurfaceCapabilities2KHR
> Adding vuid 02671

- layers/cmd_buffer_state.cpp
- layers/cmd_buffer_state.h
- layers/core_validation.cpp
- layers/core_validation.h
- layers/generated/command_validation.cpp
- layers/generated/command_validation.h
- layers/parameter_validation_utils.cpp
- scripts/command_validation_generator.py
More improvements to make the Dynamic State code cleaner
For some reason the `git` diff looks way worse then it actually is for `core_validation.cpp`
> More dynamic state refactoring

- layers/core_validation.cpp
- tests/vklayertests_others.cpp
> layers: Fix extendedDynamicState2 bug

- layers/core_validation.cpp
- tests/vklayertests_command.cpp
Transform feedback must not be active when CmdExecuteCommands is called
> Adding vuid 02286, CmdExecuteCommands and transform feedback

- layers/core_validation.cpp
- tests/vklayertests_descriptor_renderpass_framebuffer.cpp
Check that transform feedback is not active during CmdNextSubpass call
> Adding vuid 02349 02350

- layers/core_validation.h
- layers/generated/spirv_grammar_helper.cpp
- layers/generated/spirv_grammar_helper.h
- layers/shader_instruction.h
- layers/shader_module.cpp
- layers/shader_validation.cpp
- scripts/spirv_grammar_generator.py
adds a `Instruction::StorageClass()` that is generated from the SPIR-V grammar instead of having arbitrary indexes into the word array
> layers: Generate Instruction storage class

- layers/generated/object_tracker.cpp
- scripts/object_tracker_generator.py
- tests/vklayertests_wsi.cpp
- tests/vkrenderframework.cpp
Ensure that a leaked swapchain is reported by the validation layers.
closes #4608
> tests: LeakASwapchain

- layers/parameter_validation_utils.cpp
- tests/vklayertests_buffer_image_memory_sampler.cpp
` VUID-VkDeviceImageMemoryRequirementsKHR-pCreateInfo-06417`
> Add VUID 06417

- BUILD.md
- CMakeLists.txt
- scripts/update_deps.py
> cmake: Add toolchain file support to update_deps.py

- layers/best_practices_utils.cpp
- tests/vklayertests_best_practices.cpp
It turns out that the table from #2918 had an implicit "(can be 0)" on almost every line. The only weird case is:
- PRESENT_SRC_KHR - Must be 0
Fixes #4735
> practices: Fix BestPractices-ImageBarrierAccessLayout again

- layers/parameter_validation_utils.cpp
- tests/vklayertests_others.cpp
Cleanup I've done while investigating `VkLayerTest.ValidateImportMemoryHandleType`
Split into 2 commits
> Import Operations Minor Cleanup

- layers/synchronization_validation.cpp
- layers/synchronization_validation.h
Enables additional handle information for each tagged access.  Limited usage to test, and as exmplar.
The specific additional information was added as when debugging a vkquake hazard, there just wasn't the needed information.  More is needed, for example the layout transitions, loads, and stores, could be individually tagged with the affected view handles and attachment id captured. But that would require plumbing down the tag generation and access log info into the renderpass access context.
Some of the ideas may be of general interest to improve VVL message generation, both the NamedHandle captures and the Formatter/FormatterState to enable "streamed out which needs external referants.
> syncval: Improve access log information

- layers/queue_state.cpp
The spec says:
> Additionally, exporting a semaphore payload to a handle with copy
> transference has the same side effects on the source semaphore’s payload as
> executing a semaphore wait operation.
Insert a wait operation on vkGetSemaphoreFdKHR() with VK_EXTERNAL_SEMAPHORE_HANDLE_TYPE_SYNC_FD_BIT.
Fixes this bogus validation error when submitting a queue with a signal operation on a binary VkSemaphore, then exporting it to a sync_file:
00:00:01.582 [render/vulkan/vulkan.c:57] Validation Error: [ UNASSIGNED-CoreValidation-DrawState-QueueForwardProgress ] Object 0: handle = 0xa2eb680000000026, type = VK_OBJECT_TYPE_SEMAPHORE; Object 1: handle = 0x616000033980, type = VK_OBJECT_TYPE_QUEUE; Object 2: handle = 0x616000033980, type = VK_OBJECT_TYPE_QUEUE; | MessageID = 0xe825f293 | …
> layers: insert wait operation on SYNC_FD export

- tests/vklayertests_others.cpp
Code doesn't properly check if external memory supports dedicated allocation
I used [`VkPositiveLayerTest.ExternalMemory`](https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/226b595aeec0dc014bfc610f1df986eaf78f3578/tests/positive/image_buffer.cpp#L977) as the primary reference for correctness.
> tests: Fix ValidateImportMemoryHandleType

- CMakeLists.txt
DEMOS_WSI_SELECTION does nothing.
> cmake: Remove DEMOS_WSI_SELECTION

- tests/layer_validation_tests.cpp
> Fix out of scope variable in ValidationArrayOOBRayTracingShaders

- layers/core_validation.h
- layers/descriptor_validation.cpp
- layers/pipeline_state.h
- layers/shader_module.cpp
- layers/shader_module.h
- layers/shader_validation.cpp
- layers/synchronization_validation.cpp
Tried moving more things into `StaticData`, move things into `SHADER_MODULE_STATE`, and rename structs to match coding style
> layers: Cleanup Shader Module interface

- layers/best_practices_utils.cpp
- layers/cmd_buffer_state.cpp
- layers/cmd_buffer_state.h
- layers/core_validation.cpp
- layers/core_validation_error_enums.h
- layers/gpu_validation.cpp
- layers/pipeline_layout_state.cpp
- layers/pipeline_layout_state.h
- layers/pipeline_state.h
- tests/layer_validation_tests.cpp
- tests/vklayertests_command.cpp
- tests/vklayertests_descriptor_renderpass_framebuffer.cpp
- tests/vklayertests_pipeline_shader.cpp
While looking into https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/4775 I noticed a lot of small code cleanup that would be nice. Each commit breaks down the changes step by step
> Descriptor Set Tracking code cleanup

- BUILD.gn
> build: Fix MSVC GN build

- layers/parameter_validation_utils.cpp
- tests/positive/pipeline.cpp
Closes #4161
I opened this PR so I wont forget it, but the test currently crashes in the driver as @ShabbyX already noticed.
> layers: Fix validating pipeline creation feedback

- .github/workflows/build_macos.yml
- scripts/common_ci.py
Mainly useful for logging/verification.
> cmake: Install during CI builds

- BUILD.gn
- BUILD.md
- CMakeLists.txt
- build-android/jni/Android.mk
- layers/buffer_validation.cpp
- layers/synchronization_validation.cpp
- layers/synchronization_validation.h
- layers/vk_layer_data.h
- tests/CMakeLists.txt
- tests/layers/CMakeLists.txt
@juan-lunarg showed that we are already using C++14 features, so making the minimum explicit.
> build: Use C++17 standard

- layers/buffer_validation.cpp
- layers/core_validation.cpp
- scripts/spirv_validation_generator.py
- tests/vklayertests_buffer_image_memory_sampler.cpp
- tests/vklayertests_command.cpp
- tests/vklayertests_others.cpp
- tests/vksyncvaltests.cpp
Some low hanging fruit was able to do quick
> Remove some open TODOs

- layers/generated/chassis.h
- layers/state_tracker.h
- layers/stateless_validation.h
- scripts/layer_chassis_generator.py
> build: Fix extra semicolon

- layers/CMakeLists.txt
This custom target does nothing now that the logic for generating json is completely different.
> cmake: Remove mk_layer_config_dir

- layers/CMakeLists.txt
- tests/layers/CMakeLists.txt
> cmake: Layers should be MODULE instead of SHARED

- layers/sync_utils.cpp
> layers: Fix sync2 string print helper

- layers/json/VkLayer_khronos_validation.json.in
After discussion with @Tony-LunarG, this is a proposed manifest improvement to better expose to the user the layer settings dependence.
> manifest: improve warn robust oob setting dependency

- layers/synchronization_validation.cpp
- layers/synchronization_validation.h
Currently code doesn't check if std::optional has a value
closes #4853
> layers: Fix std::optional crash

- tests/vklayertests_pipeline_shader.cpp
> macos: Remove sprintf

- .github/workflows/build_macos.yml
Prevents build failures against newer MacOS SDKs
> ci: Build against latest MacOS SDK

- layers/generated/layer_chassis_dispatch.cpp
- layers/parameter_validation_utils.cpp
- scripts/layer_chassis_dispatch_generator.py
- tests/positive/other.cpp
> layers: Fix vkExportMetalObjects

- layers/core_validation.cpp
- layers/core_validation_error_enums.h
- tests/vklayertests_buffer_image_memory_sampler.cpp
Labels new `VUID-VkBindImageMemoryInfo-image-07736 from 1.3.236 spec
> layers: Label BindImage2 VU 07736

- .github/workflows/build_macos.yml
- scripts/update_deps.py
- Tests Xcode builds work
- Tests Ninja builds work
- Ensure CMakePresets.json is valid
> ci: Test Xcode/Ninja/CMakePresets.json on MacOS CI

- layers/core_validation.cpp
- tests/vklayertests_ray_tracing.cpp
labels `VUID-vkGetAccelerationStructureHandleNV-accelerationStructure-02787`
> layers: Label NV RTX 02787 VUID

- layers/gpu_validation.cpp
- tests/vklayertests_gpu.cpp
Also fixes VMA memory leak
Also addresses #4414
> Better handle unavailable pipeline layout in GPU-AV

- LAYER_CONFIGURATION.md
Update layer config doc with latest changes on enabling environment variables using the command-line.
> docs: Update layer config

- layers/buffer_validation.cpp
- layers/core_validation.cpp
- layers/render_pass_state.cpp
- layers/synchronization_validation.cpp
- layers/vk_layer_utils.h
Create a `GetBitSetCount` util for all the spots doing 32-bit mask bit counting
> layers: Add helper function for counting bits set

- layers/core_validation.cpp
Currently this was not checking if Mesh/Task were set twice
> layers: Fix 06897 check for mesh shaders

- layers/buffer_validation.cpp
- layers/parameter_validation_utils.cpp
- tests/vklayertests_buffer_image_memory_sampler.cpp
Adds `VUID-VkImageCreateInfo-flags-07755`
> Add 2d view compatible VU

- tests/vklayertests_gpu.cpp
I found this working on another GPU-AV test
> Fix GPU-AV test getting 06481

- layers/buffer_validation.cpp
- tests/vklayertests_command.cpp
Adds `VUID-vkCmdCopyImage-srcImage-07742`, `VUID-VkCopyImageInfo2-srcImage-07742`,  `VUID-vkCmdCopyImage-srcImage-07743` and `VUID-VkCopyImageInfo2-srcImage-07743`
> Add CopyImage IMAGE_TYPE VU

- tests/positive/sync.cpp
This test isn't functioning correctly on most platforms we test.
Fixes #4917
> tests: Remove VkPositiveLayerTest.GetTimelineSemThreadRace

- .github/workflows/build_android.yml
- .github/workflows/build_linux.yml
- .github/workflows/build_linux_gn.yml
- .github/workflows/build_macos.yml
- .github/workflows/build_windows.yml
Update to checkout@v3
Update to setup-python@v4
> ci: Fix CI deprecation warnings

- layers/core_validation.cpp
- tests/vklayertests_ray_tracing.cpp
VUIDs were added in 1.3.238 spec
> layers: Label new NV RTX VUID

- .github/workflows/build_macos.yml
- tests/vktestframework.cpp
Checks VK_ICD_FILENAMES and VK_LAYER_PATH before running tests.
> tests: Check developer environment variables

- tests/vktestframework.cpp
My `VK_LAYER_PATH` for using the Profiles layer is
`VK_LAYER_PATH=/path/to/profile/:/path/to/validation_layer_repo:/path/to/sync2/layer/in/sdk`
the current check had 2 issues
1. It was not able to handle 3 or more paths due to using the `pos` instead of `length` with `std::substr`
2. Checking each path for the validation layers json file
> tests: Fix VK_LAYER_PATH check

- layers/generated/chassis.cpp
- scripts/layer_chassis_generator.py
The generated file is so large my vscode intellisense gives up and can't deduce the auto. Provide the type for simplicity.
> layers: Use ValidationObject pointer instead of auto

- tests/positive/image_buffer.cpp
- tests/positive/pipeline.cpp
- tests/positive/sync.cpp
- tests/vklayertests_command.cpp
- tests/vklayertests_descriptor_renderpass_framebuffer.cpp
- tests/vklayertests_dynamic_rendering.cpp
- tests/vklayertests_imageless_framebuffer.cpp
- tests/vklayertests_others.cpp
- tests/vklayertests_pipeline_shader.cpp
- tests/vklayertests_portability_subset.cpp
- tests/vklayertests_wsi.cpp
- tests/vksyncvaltests.cpp
remove `m_device_extension_names` to `AddRequiredExtensions`/`AddOptionalExtensions` system for a lot more of tests
> tests: Update extension enabling

- layers/cmd_buffer_state.cpp
- layers/cmd_buffer_state.h
- layers/debug_printf.cpp
- layers/debug_printf.h
- layers/gpu_validation.cpp
- layers/gpu_validation.h
- layers/synchronization_validation.cpp
- layers/synchronization_validation.h
> layers: Fix CMD_BUFFER_STATE potential deadlock

- BUILD.md
- CONTRIBUTING.md
> Update CONTRIBUTING / BUILD docs

- layers/debug_printf.cpp
- layers/gpu_utils.cpp
- layers/shader_module.h
`spirv_inst_iter` was only used in GPU AV and DebugPrintf, this removes it in favor for the new dedicated `Instruction` class
> layers: Remove old spirv_inst_iter system

- scripts/check_code_format.py
VerifyCopyrights() checks the date range on the LunarG copyright lines. Only LunarG employees should claim copyright for LunarG.
VerifyCopyrights() should use the author date of the commit(s) in the PR, rather than the year on whichever day the script runs.
Happy New Year!!!
> scripts: Improve copyright checking in check_code_format.py

- scripts/check_code_format.py
Run each part of the code format check on each commit in a PR so that we ensure that each commit is correct rather than the whole set ends up correct even if there are errors in the middle.
> scripts: Run code format checks commit-by-commit

- layers/shader_validation.cpp
Noticed this function was reusing the same logic in checks instead of just grouping it together
> layers: Collapse ValidateShaderModuleId logic

- CMakeLists.txt
- layers/CMakeLists.txt
- Add vital documentation
- Use modern CMake features
- Generate LAYER_UTIL_FILES from SOURCES property
> cmake: Cleanup VkLayer_utils

- BUILD.gn
- build-android/cmake/layerlib/CMakeLists.txt
- build-android/jni/Android.mk
- layers/CMakeLists.txt
- layers/core_validation.cpp
- layers/core_validation.h
- layers/wsi_validation.cpp
- scripts/vk_validation_stats.py
Creates a new `wsi_validation.cpp` file to move WSI related `CoreChecks` into
> layers: New wsi_validation for CoreChecks

- layers/cmd_buffer_state.cpp
- layers/core_validation.cpp
- tests/positive/dynamic_rendering.cpp
Enhance validation state checking for renderpass instance suspend and resume to include secondary command buffers.
> layers: Update validation layer checks for dynamic rendering

- tests/README.md
Add section to tests README.
~~Update VS debugging environment to exclude known implicit layers that affect validation output.~~
> tests: Add note about implicit validation layers

- CMakeLists.txt
Adds thread sanitization to the build.
> cmake: Add VVL_ENABLE_TSAN

- tests/positive/image_buffer.cpp
- tests/vklayertests_buffer_image_memory_sampler.cpp
- tests/vklayertests_debug_printf.cpp
- tests/vklayertests_descriptor_renderpass_framebuffer.cpp
- tests/vklayertests_dynamic_rendering.cpp
- tests/vklayertests_others.cpp
- tests/vklayertests_pipeline_shader.cpp
Fixed more tests using profiles from things such as Lavapipe/desktop profiles
cc @karl-lunarg
> tests: More tests fixes for profiles

- .github/workflows/build_linux.yml
- scripts/common_ci.py
- scripts/github_ci_win_linux.py
- tests/positive/command.cpp
- tests/positive/pipeline.cpp
- tests/positive/shaderval.cpp
- tests/vklayertests_command.cpp
- tests/vklayertests_descriptor_renderpass_framebuffer.cpp
- tests/vklayertests_dynamic_rendering.cpp
- tests/vklayertests_graphics_library.cpp
- tests/vklayertests_others.cpp
- tests/vklayertests_pipeline_shader.cpp
Sets up CI to build the Profile Layers and then run the tests with device profiles
closes #4867
> Run CI with Profiles Layer

- layers/parameter_validation_utils.cpp
- layers/pipeline_validation.cpp
- layers/stateless_validation.h
- tests/layer_validation_tests.cpp
- tests/layer_validation_tests.h
- tests/positive/ray_tracing_pipeline.cpp
- tests/vklayertests_ray_tracing.cpp
- tests/vklayertests_ray_tracing_pipeline.cpp
- tests/vkrenderframework.cpp
- tests/vkrenderframework.h
- tests/vktestbinding.cpp
- tests/vktestbinding.h
Add VUIDs mentioned in https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/4860
` VUID-VkAccelerationStructureGeometryAabbsDataKHR-stride-03820` was already checked, but was lacking a test.
> Add 6 RT VUIDs

- .github/workflows/build_linux.yml
- .github/workflows/build_macos.yml
- .github/workflows/build_windows.yml
- CMakeLists.txt
- scripts/common_ci.py
- scripts/github_ci_build_desktop.py
- scripts/github_ci_win_linux.py
Set the --dir value passed to update_deps.py via cmake variable (-DUPDATE_DEPS_DIR), or automatically based on build type.
> build: Set external dir based on build type

- CMakeLists.txt
- scripts/CMakeLists.txt
- tests/CMakeLists.txt
- Cleans up the top level CMakeLists.txt
- Add UPDATE_DEPS `option` so it shows up in cmake-gui
- Minor cleanup of CMake testing code
> cmake: Create scripts/CMakeLists.txt

- tests/positive/descriptors.cpp
This PR adds regression test for the second issue (https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/4576) mentioned in: https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/4604
The original code was removed in https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/4892, so it's unlikely to have the same regression, but it might happen when similar functionality is implemented (one of the variations of accessing unbound descriptor set).
> tests: Add regression test for null set crash in core validation

- layers/descriptor_validation.cpp
- tests/vklayertests_buffer_image_memory_sampler.cpp
These were added in the 1.3.239 header
> layers: Label new VK_EXT_image_2d_view_of_3d VUID

- scripts/check_code_format.py
See https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/5142#discussion_r1083124269
> scripts: Check that LunarG / Valve Copyright is updated

- tests/layer_validation_tests.cpp
- tests/positive/dynamic_rendering.cpp
- tests/positive/pipeline.cpp
- tests/vklayertests_buffer_image_memory_sampler.cpp
- tests/vklayertests_command.cpp
- tests/vklayertests_descriptor_renderpass_framebuffer.cpp
- tests/vklayertests_others.cpp
- tests/vklayertests_pipeline_shader.cpp
The following tests were not working with local max profile
> tests: More cleanup to tests using profiles

- .git-blame-ignore-revs
Add `Move files into dedicated folders` commit
> git: Update git-blame-ignore-revs

- .github/workflows/build_macos.yml
- tests/vklayertests_pipeline_shader.cpp
Warning: "macOS-latest pipelines will use macOS-12 soon"
Required fixing -Wimplicit-fallthrough compilation failures
> ci: Fix MacOS CI warning

- scripts/update_deps.py
- Specify `--config` regardless of platform/generator
- Use `--paralell` functionality
> scripts: Cleanup update_deps `CMakeBuild` step

- BUILD.gn
- build-gn/generate_vulkan_layers_json.py
Should have been part of https://github.com/KhronosGroup/Vulkan-ValidationLayers/commit/ac7c75bb519ede9ee65e43778da2274002c525b0
> gn: Remove deprecated vulkan_core.h parsing

- CMakeLists.txt
- layers/cast_utils.h
- layers/generated/chassis.h
- layers/generated/layer_chassis_dispatch.cpp
- layers/gpu_validation/gpu_validation.cpp
- scripts/layer_chassis_dispatch_generator.py
- scripts/layer_chassis_generator.py
- tests/CMakeLists.txt
- tests/vklayertests_buffer_image_memory_sampler.cpp
- tests/vklayertests_descriptor_renderpass_framebuffer.cpp
- tests/vklayertests_pipeline_shader.cpp
- tests/vklayertests_ray_tracing_pipeline.cpp
>  Remove -fno-strict-aliasing and -fno-builtin-memcmp #5161 

- layers/gpu_validation/debug_printf.cpp
- layers/gpu_validation/gpu_validation.cpp
- layers/state_tracker/state_tracker.cpp
- layers/state_tracker/state_tracker.h
fixes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/5197
> gpu: Add state tracking to GPU-AV and debug printf for EXT mesh_shader

- layers/generated/vk_safe_struct.h
- scripts/helper_file_generator.py
- tests/vklayertests_gpu.cpp
- tests/vklayertests_instanceless.cpp
- tests/vktestframework.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/5213
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/5212
> layers: Improve C/C++ std error checking

- build-android/cmake/layerlib/CMakeLists.txt
- build-android/jni/Android.mk
- layers/layer_options.cpp
- layers/vk_layer_logging.cpp
- layers/vk_layer_logging.h
- tests/vklayertests_others.cpp
Ensure we don't have any VUID hash collisions
Ensure we don't accidentally break hash stability
NOTE: I had to fix the Android build to make the testing work. Android fix is in a separate commit.
> layers: Add vuid hash testing

- layers/core_checks/ray_tracing_validation.cpp
- layers/state_tracker/device_state.h
- layers/state_tracker/state_tracker.cpp
- tests/vklayertests_ray_tracing_pipeline.cpp
> Validation for VK_EXT_pipeline_library_group_handles

- layers/core_checks/pipeline_validation.cpp
it's illegal to read this in any other GPL stage
Fixes #5233
> layers: Fix VkPipelineRenderingCreateInfo parsing for fragment output

- .github/workflows/contributors.yml
- CONTRIBUTORS.md
- Updates CONTRIBUTORS.md when needed
- Works with existing action workflow
- Shows all contributors/collaborators
> docs: Fix contributors.yml

- .git-blame-ignore-revs
Add recent large find-and-replace / copy-and-paste commits
> layers: Update .git-blame-ignore-revs

- tests/vklayertests_imageless_framebuffer.cpp
Wanted to make sure the pNext implicit VUs were correct, they are, but decided to bring the tests in
>  VUID-VkFramebufferAttachmentImageInfo-pNext-pNext 
> vkCreateFramebuffer(): VkFramebufferAttachmentsCreateInfo[0].pNext is not NULL.
> VUID-VkFramebufferCreateInfo-pNext-pNext 
> vkCreateFramebuffer: pCreateInfo->pNext chain includes a structure with unexpected VkStructureType VK_STRUCTURE_TYPE_COMMAND_POOL_CREATE_INFO; Allowed structures are [VkFramebufferAttachmentsCreateInfo]
> tests: Extend Framebuffer pNext tests

- CMakeLists.txt
- layers/generated/parameter_validation.cpp
- layers/stateless/parameter_validation_utils.cpp
- layers/stateless/stateless_validation.h
- scripts/parameter_validation_generator.py
- tests/CMakeLists.txt
- tests/layer_validation_tests.cpp
- tests/layer_validation_tests.h
- tests/vklayertests_wsi.cpp
- VUID-VkWaylandSurfaceCreateInfoKHR-display-01304
- VUID-VkWaylandSurfaceCreateInfoKHR-surface-01305
closes #4790
> layers: Add remaining VUIDs for wayland surface creation

- build-android/cmake/layerlib/CMakeLists.txt
> android: Fix layerlib/CMakeLists.txt

- layers/generated/vk_extension_helper.h
- scripts/helper_file_generator.py
Use 'promotedto' attribute for identifying promoted extensions in vk.xml.
FYI @Tony-LunarG.
> layers: Add missing promoted extensions

- layers/core_checks/pipeline_validation.cpp
- tests/vklayertests_graphics_library.cpp
adds
- VUID-VkGraphicsPipelineCreateInfo-flags-06645
- VUID-VkGraphicsPipelineCreateInfo-pLibraries-06646
- VUID-VkGraphicsPipelineCreateInfo-pLibraries-06647
> Add VK_KHR_pipeline_executable_properties GPL VU

- tests/positive/image_buffer.cpp
- tests/vklayertests_descriptor_renderpass_framebuffer.cpp
- tests/vklayertests_others.cpp
- tests/vklayertests_pipeline_shader.cpp
- tests/vklayertests_ray_tracing.cpp
Same idea as https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/5291
Some tests were not fully correct
> tests: Fix tests for use with Profile layer 

- tests/vklayertests_video.cpp
- tests/vklayertests_video.h
This PR fixes some minor issues with the test framework for Vulkan Video tests found by valgrind and further review.
> tests: Fix minor video test framework issues

- layers/core_checks/pipeline_validation.cpp
- tests/vklayertests_graphics_library.cpp
Adds `VUID-VkGraphicsPipelineCreateInfo-None-07826`
> Add Complete Set VkPipelineLayout check

- layers/core_checks/image_validation.cpp
Return early to avoids nesting majority of logic
Minor C++17 cleanup
Minor const correctness
Use image_usage consistently, since it can be modified by VkImageViewUsageCreateInfo in the pNext chain
> layers: Cleanup PreCallValidateCreateImageView

- tests/positive/image_buffer.cpp
The main intent here is to have useful reference code for my upcoming PR which deals with 3D image views
> tests: VkPositiveLayerTest.Create3DImageView

- tests/layer_validation_tests.cpp
- tests/layer_validation_tests.h
- tests/vklayertests_others.cpp
- tests/vklayertests_pipeline_shader.cpp
remove old extension adding system for the new `AddRequiredExtensions` system
> tests: Remove old extension adding mechanisms

- layers/core_checks/synchronization_validation.cpp
- layers/sync/sync_vuid_maps.cpp
- layers/sync/sync_vuid_maps.h
- tests/vklayertests_sync.cpp
adds
- VUID-VkImageMemoryBarrier2-synchronization2-07793
- VUID-VkImageMemoryBarrier2-synchronization2-07794
- VUID-VkImageMemoryBarrier-synchronization2-07793
- VUID-VkImageMemoryBarrier-synchronization2-07794
> Add Sync2 image barrier layout VU

- layers/core_checks/image_validation.cpp
- layers/state_tracker/device_state.h
- layers/state_tracker/image_state.cpp
- layers/state_tracker/state_tracker.cpp
- layers/vk_layer_utils.h
- tests/device_profiles/max_profile.json
- tests/positive/image_buffer.cpp
- tests/vklayertests_image.cpp
- layers: Add validation for VkImageViewSlicedCreateInfoEXT
- layers: Add testing for VkImageViewSlicedCreateInfoEXT
closes #5314
> Add VK_EXT_image_sliced_view_of_3d validation

- layers/core_checks/shader_validation.cpp
- tests/positive/pipeline.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/5302
Makes sure `VUID-VkGraphicsPipelineCreateInfo-renderPass-06038` only cares if there is a `read` access to the input attachment
> layers: Verify input attachment is only validated if read from

- layers/state_tracker/render_pass_state.cpp
- layers/sync/sync_validation.cpp
- layers/sync/sync_validation.h
- tests/vksyncvaltests.cpp
Addresses #5080, and test and syncval issues discovered by fixing it.
> several syncval attachment and test  fixes

- tests/vklayertests_pipeline_shader.cpp
- tests/vklayertests_ray_tracing_pipeline.cpp
Improves testings for missing entry point (taken out of from future change that was violating these)
> tests: Add extra missing entrypoint tests

- tests/layer_validation_tests.h
- tests/positive/ray_tracing_pipeline.cpp
- tests/vklayertests_ray_tracing.cpp
- tests/vklayertests_ray_tracing_pipeline.cpp
Use the helper shaders strings in `tests/layer_validation_tests.h`
> layers: Use common minimal shader string

- layers/core_checks/buffer_validation.cpp
- layers/core_checks/core_validation.h
- layers/core_checks/image_layout_validation.cpp
- layers/core_checks/image_validation.cpp
- layers/stateless/parameter_validation_utils.cpp
Improves the error messages of various image and buffer validation
> layers: Better image/buffer error messages

- docs/fine_grained_locking.md
- layers/core_checks/cmd_buffer_dynamic_validation.cpp
- layers/core_checks/core_validation.h
- layers/core_checks/device_memory_validation.cpp
- layers/core_checks/pipeline_validation.cpp
- tests/vklayertests_command.cpp
Add more LogObjectList in more places
> Add more LogObjectList for error messages

- layers/generated/parameter_validation.cpp
- layers/stateless/parameter_validation_utils.cpp
- layers/stateless/stateless_validation.h
- scripts/parameter_validation_generator.py
- tests/positive/wsi.cpp
- tests/vklayertests_wsi.cpp
- Add VUIDs/testing for X11 surface creation
- Fix typo in Xcb validation
> layers: Add validation for XCB surface creation

- layers/core_checks/cmd_buffer_dynamic_validation.cpp
- layers/core_checks/cmd_buffer_validation.cpp
- layers/core_checks/copy_blit_resolve_validation.cpp
- layers/core_checks/device_memory_validation.cpp
- layers/stateless/parameter_validation_utils.cpp
- tests/vklayertests_command.cpp
- tests/vklayertests_descriptor_renderpass_framebuffer.cpp
- tests/vklayertests_dynamic_rendering.cpp
- tests/vklayertests_image.cpp
Fixes for the Vulkan 1.3.243 spec with new VUs
> VUID fixes for 243 Vulkan Spec

- layers/core_checks/image_validation.cpp
- tests/vklayertests_image.cpp
Fixed using VUID created as of 1.3.243
> layers: Replace UNASSIGNED-VkImageViewSlicedCreateInfoEXT

- .github/workflows/vvl.yml
- scripts/common_ci.py
- scripts/github_ci_win_linux.py
- Use Ninja for all platforms (perf/simplicity)
- Specify source/binary dir explitily (-S / -B)
> ci: Modernize CMake usage in CI scripts

- layers/gpu_validation/gpu_utils.cpp
Old GCC versions are not supported anymore
> layers: Remove old GCC regex workaround

- layers/CMakeLists.txt
> cmake: Don't set LINKER_LANGUAGE property

- layers/core_checks/render_pass_validation.cpp
- layers/core_checks/synchronization_validation.cpp
- layers/gpu_validation/debug_printf.cpp
- layers/state_tracker/cmd_buffer_state.cpp
- layers/state_tracker/descriptor_sets.cpp
- layers/state_tracker/pipeline_state.h
- layers/state_tracker/shader_module.h
- layers/stateless/parameter_validation_utils.cpp
- layers/sync/sync_validation.cpp
- layers/vk_layer_utils.cpp
Running code analysis, many expressions could be simplified
> layers: Simplify expressions

- layers/state_tracker/pipeline_state.cpp
Make a fragment shader unconditionally optional.
> layers: Remove all fragment shader requirements

- layers/stateless/parameter_validation_utils.cpp
- tests/negative/memory.cpp
First step in https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/5431 to get started.
> layers: Add VU 00641

- layers/generated/vk_safe_struct.cpp
- scripts/helper_file_generator.py
- tests/positive/other.cpp
> layers: Fix deep copy of pData/dataSize in vk_safe_struct.*

- .mailmap
This enables Git command-line tools to remap my name properly.
> Add a .mailmap

- layers/core_checks/shader_validation.cpp
- layers/core_checks/synchronization_validation.cpp
- layers/error_message/validation_error_enums.h
- layers/generated/chassis.cpp
- layers/sync/sync_vuid_maps.cpp
- layers/sync/sync_vuid_maps.h
- scripts/layer_chassis_generator.py
- tests/negative/others.cpp
- tests/negative/pipeline_shader.cpp
- tests/negative/sync_object.cpp
Created some Spec issues to remove more, but some UNASSIGNED VUIDs actually had a proper VUID to give it
> layers: Cleanup of UNASSIGNED VUIDs

- layers/state_tracker/base_node.h
- layers/sync/sync_validation.cpp
- layers/sync/sync_validation.h
- tests/negative/sync_val.cpp
> Syncval: Leak fix of circular share_ptr between swapchains and queue batch contexts

- layers/stateless/parameter_validation_utils.cpp
- tests/device_profiles/max_profile.json
- tests/negative/best_practices.cpp
- tests/negative/command.cpp
- tests/negative/image.cpp
- tests/negative/pipeline_shader.cpp
Adds a few more tests to run properly on Max Profiles while still being able to run on my local machine
This the last of the low-hanging fruit for Max Profiles, the rest of the tests will need more work in order to work
> tests: Fix more tests for Max Profiles

- layers/sync/sync_validation.cpp
- layers/sync/sync_validation.h
- tests/CMakeLists.txt
- tests/framework/render.h
- tests/negative/sync_val.cpp
- tests/positive/sync_val.cpp
Closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/4946
> vkCmdClearAttachments sync validation

- layers/core_checks/descriptor_validation.cpp
Improve some Descriptor Validation messages
> layers: Fix descriptor validation messages

- build-android/jni/Android.mk
- tests/CMakeLists.txt
- tests/containers/small_vector.cpp
> tests: Add small_vector::resize tests

- .github/workflows/vvl.yml
- scripts/common_ci.py
Minor test/scripting improvements
> Test FINE_GRAINED_LOCKING disabled and use absolute path for VK_KHRONOS_PROFILES_PROFILE_FILE

- layers/core_checks/core_validation.h
- layers/core_checks/descriptor_validation.cpp
- layers/core_checks/image_validation.cpp
- layers/generated/spirv_validation_helper.cpp
- layers/generated/vk_safe_struct.cpp
- layers/state_tracker/descriptor_sets.cpp
- layers/state_tracker/device_state.h
- layers/state_tracker/state_tracker.cpp
- layers/state_tracker/state_tracker.h
- layers/stateless/parameter_validation_utils.cpp
- scripts/helper_file_generator.py
- scripts/spirv_validation_generator.py
- tests/device_profiles/max_profile.json
- tests/negative/image.cpp
Rebase of https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/4611
Adds `VK_QCOM_image_processing`
> Add VK_QCOM_image_processing

- CONTRIBUTING.md
from (https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/4865)
- Better describe the Incomplete VUIDs
- Discuss roles of maintainers
- Re-organize markdown headers
> docs: Describe Incomplete VUIDs and role of maintainers

- CONTRIBUTING.md
Add example of writing a good error message
> docs: What is a good error message

- layers/stateless/parameter_validation_utils.cpp
- tests/positive/graphics_library.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/5553
went through all other VUs in function, the rest that VU talk about having a GPL substate will always be correct because they are consuming the structure 
The issue is the fixed VUs below are checking if the structure is `null` but not accounting it might because of GPL
> Check Pre-Rasterization state for stateless

- README.md
Remove outdated information about change to main
Remove outdated CI badges
> docs: Cleanup README.md

- layers/core_checks/descriptor_validation.cpp
- tests/negative/ray_tracing.cpp
- Closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/5514
I got VUID-VkPipelineLayoutCreateInfo-descriptorType-03572 wrong the first time (I was reading data from the wrong map), I fixed it
> layers: Add 03571 03573 03574 Fix 03572

- layers/core_checks/drawdispatch_validation.cpp
- tests/negative/command.cpp
Fixing earlier change that make bound index buffer size *consistent* with bound vertex buffers, but didn't account for it's usage a CoreChecks validation.
Fixes #5575
> layers: Fix index buffer size treatment

- tests/negative/descriptors.cpp
- tests/negative/ycbcr.cpp
there was a `VUID-VkWriteDescriptorSet-descriptorType-07729` but when I wrote this test I hit `VUID-VkDescriptorImageInfo-imageView-01976` before getting to it. The `07729` was [removed](  https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/5815)
This splits `DSAspectBitsErrors` and creates a dedicated `InputAttachmentDepthStencilAspect` and `MultiplaneAspectBits`
> tests: Add Depth/Stencil input attachment test

- layers/state_tracker/shader_module.cpp
- layers/state_tracker/shader_module.h
adds a `TypeStructInfo` class
This is used to help manage `OpTypeStruct` information
Currently there is a `StructInfo` but that was used only to manage the Push Constants (and has to deal with structs of struct, currently the only user for `TypeStructInfo` is `StageInterfaceVariable` which is not allowed to have nested Structs)
The next goal is to migrate all of `StructInfo` into `OpTypeStruct`
> layers: Add new TypeStructInfo class

- build-android/cmake/layerlib/CMakeLists.txt
- build-android/jni/Android.mk
> android: Remove VK_PROTOTYPES define

- .github/workflows/vvl.yml
- tests/negative/command.cpp
- build: Fix C++20 compiler warning
- ci: Add Ubuntu 22.04 to testing
> ci: Add Ubuntu 22.04 to testing

- layers/core_checks/shader_validation.cpp
- layers/state_tracker/shader_module.cpp
- layers/state_tracker/shader_module.h
- tests/positive/pipeline.cpp
I miss read (as commented below) the spec and forgot about nested structs inbetween the interface
For now just skip checking nested struct User Defined Variables until proper fix (and VVL tests) are added
@Tony-LunarG  this fixes CTS on my end
> layers: Hotfix for nested struct interface

- layers/stateless/parameter_validation_utils.cpp
Also fix for 07985 (see specific commit)
> layer: Improve error messages in manual_PreCallValidateCreateRayTracingPipelinesKHR

- layers/core_checks/core_validation.h
- layers/core_checks/drawdispatch_validation.cpp
- layers/core_checks/pipeline_validation.cpp
- tests/negative/command.cpp
- tests/negative/pipeline_shader.cpp
Two spots I realize we could easily split things up
This is only just moving code (into new functions)
> Split up draw time functions

- layers/core_checks/pipeline_validation.cpp
- tests/framework/layer_validation_tests.cpp
- tests/negative/dynamic_rendering.cpp
- tests/negative/portability_subset.cpp
- tests/negative/query.cpp
- tests/positive/graphics_library.cpp
- tests/positive/pipeline.cpp
This is an attempt to take out all the nit fixes/improvements from https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/5478
> Improvement from 5478 pulled out 

- .github/workflows/vvl.yml
- layers/CMakeLists.txt
- tests/integration/CMakeLists.txt
- tests/integration/main.cpp
- cmake: Fix `vk_enum_string_helper.h` installation
- ci: Add integration tests for installation
> cmake: Fix vk_enum_string_helper.h installation

- README.md
Provide links to community assistance.
> docs: Community Assistance

- layers/best_practices/best_practices_utils.cpp
- layers/best_practices/best_practices_validation.h
- layers/generated/best_practices.cpp
- scripts/best_practices_generator.py
Utilize the fact positive return codes are greater than 0. And error codes are less than 0.
> bp: Optimize best practices for return codes

- tests/negative/command.cpp
Testing the work of https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/5621 with a single file first
If this is good, can start slowly getting rid of the rests across the tests
> tests: Remove ProcAddr calls from command tests

- layers/state_tracker/pipeline_sub_state.h
> layers: Remove duplicated if in FragmentOutputState

- layers/gpu_validation/gpu_validation.cpp
The memory used for storing descriptor set state can be very large, (32 bits for every descriptor, some apps have 1m+ descriptors). Changing this memory from HOST_COHERENT to HOST_CACHED and manually flushing it saves about 1/3rd of the time spent updating this memory.
The buffer device address state could also grow quite large, so do the same for it.
> gpu: Use HOST_CACHED memory for descriptor set and bda state

- tests/CMakeLists.txt
- Add android_native_app_glue support
- Error check CMAKE_ANDROID_STL_TYPE
- Minor cleanup
> cmake: Fixup tests/CMakeLists.txt for Android

- layers/utils/vk_layer_utils.cpp
- layers/vk_layer_config.h
- layers: Move globals to layer_debug_messenger_actions
- layers: Remove vk_layer_config.h C support
> vk_layer_config.h cleanup

- build-android/jni/Android.mk
- layers/external/vma/vk_mem_alloc.h
- layers/stateless/parameter_name.h
- scripts/known_good.json
- Update VMA to ff37e927
- Update googletest v1.13.0
> build: Fixes for GCC 13

- layers/core_checks/cc_device_memory.cpp
The logic for this function was scattered and seemed added little by little 
This groups things by the `VkImagePlaneMemoryRequirementsInfo` which is the main thing being checked in the function
> layers: Cleanup ValidateGetImageMemoryRequirements2

- layers/core_checks/cc_render_pass.cpp
Clarify that the "logical or" of the mentioned flags is not what is expected, rather it is a set of possible values
> layers: Clarify VUID error message

- layers/best_practices/bp_instance_device.cpp
- layers/core_checks/cc_descriptor.cpp
- layers/core_checks/cc_drawdispatch.cpp
- layers/core_checks/cc_queue.cpp
- layers/core_checks/core_validation.h
- layers/state_tracker/image_state.cpp
- layers/state_tracker/image_state.h
- tests/negative/atomics.cpp
- tests/positive/atomics.cpp
adds `VK_EXT_shader_image_atomic_int64` - `VUID-vkCmdDispatch-sparseImageInt64Atomics-04474`
> Add sparseImageInt64Atomics ImageView

- layers/core_checks/cc_wsi.cpp
- tests/negative/wsi.cpp
- tests/positive/wsi.cpp
- Closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/5595
Given vk_ext_full_screen_exclusive is needed for this VUID, can I make a test?
> layers: Add 02672

- layers/core_checks/cc_copy_blit_resolve.cpp
- layers/core_checks/cc_image.cpp
- layers/utils/vk_layer_utils.h
- tests/negative/ycbcr.cpp
- tests/positive/layer_utils.cpp
Adds `VUID-VkImageViewCreateInfo-subresourceRange-07818` using new `IsOnlyOneValidPlaneAspect` helper
> Multiplane ImageView aspect mask check

- layers/core_checks/cc_descriptor.cpp
- layers/core_checks/core_validation.h
- layers/state_tracker/cmd_buffer_state.h
- layers/state_tracker/pipeline_state.cpp
- layers/state_tracker/pipeline_state.h
Attempt to fix 898721a7a9e98689e0b8ec75ebc77896a295cdf4 perf issues
This shows the perf issues resolved, if I can't figure out another way, I would like to get this in
> layers: Revert ActiveSlot mapping type

- layers/best_practices/bp_pipeline.cpp
- tests/positive/best_practices.cpp
Fixes a crash running dEQP-VK.pipeline.monolithic.extended_dynamic_state.cmd_buffer_start.null_color_blend_att_ptr with BP enabled
Spec:
pAttachments is a pointer to an array of [VkPipelineColorBlendAttachmentState] structures defining blend state for each color attachment. It is ignored if the pipeline is created with VK_DYNAMIC_STATE_COLOR_BLEND_ENABLE_EXT, VK_DYNAMIC_STATE_COLOR_BLEND_EQUATION_EXT, and VK_DYNAMIC_STATE_COLOR_WRITE_MASK_EXT dynamic states set.
> Fix BP illegal access

- layers/CMakeLists.txt
- layers/generated/lvt_function_pointers.cpp
- scripts/lvt_file_generator.py
- tests/CMakeLists.txt
This improves Visual Studio experience
> cmake: Configure files grouping in IDE

- layers/generated/lvt_function_pointers.cpp
- scripts/lvt_file_generator.py
- tests/framework/error_monitor.cpp
- tests/framework/error_monitor.h
- tests/framework/layer_validation_tests.cpp
- tests/framework/render.cpp
- tests/framework/render.h
- tests/positive/other.cpp
Move debug reporter code into error_monitor.h/error_monitor.cpp respectively.
> DebugReporter cleanup

- docs/shader_validation.md
While refactoring shader validation I have been improving this, but figured it didn't make sense in any of the other PRs
> docs: Add more to Shader Validation docs

- tests/CMakeLists.txt
- tests/android/README.md
See tests/android/README.md for explanation.
> android: Build vk_layer_validation_tests as a MODULE library

- layers/state_tracker/pipeline_state.h
- layers/state_tracker/state_tracker.cpp
- tests/positive/graphics_library.cpp
Assume rasterization is enabled for non-pre-raster graphics libraries
and linked libraries that do not contain pre-raster state.
> layers: Default to enabled rasterization

- layers/core_checks/cc_device_memory.cpp
I want to keep since change separately from the following changes,
since it's impossible to diff.
Clean up is about reordering validation sections and  indentation
changes. It's better to keep vkAllocateInfo-related checks before
vkBindBufferMemory checks to have chronological sequence of
events.
And the reason why we have vkAllocateInfo checks here in the first
place is because they depend on buffer/image properties.
> layers: Prepare ValidateBindBufferMemory for new changes

- build-android/jni/Android.mk
- layers/state_tracker/image_state.cpp
- tests/negative/wsi.cpp
- tests/positive/wsi.cpp
This request fixes the issue: #5781
> Fix false positive VUID-VkPresentInfoKHR-pImageIndices-01430 error, when presenting shared presentable image

- scripts/common_ci.py
See KhronosGroup/Vulkan-Loader/pull/1186
> ci: Enable LOADER_DISABLE_DYNAMIC_LIBRARY_UNLOADING on WIN32

- layers/generated/layer_chassis_dispatch.cpp
- scripts/layer_chassis_dispatch_generator.py
> layers: Fix check for deferred ray tracing pipeline creation

- tests/negative/shader_compute.cpp
- tests/negative/shader_interface.cpp
- tests/negative/shader_limits.cpp
- tests/negative/shader_push_constants.cpp
- tests/negative/shader_spirv.cpp
- tests/negative/sync_val.cpp
- tests/positive/android_hardware_buffer.cpp
- tests/positive/command.cpp
- tests/positive/descriptors.cpp
- tests/positive/image.cpp
- tests/positive/instance.cpp
- tests/positive/ray_tracing.cpp
- tests/positive/ray_tracing_pipeline.cpp
- tests/positive/render_pass.cpp
- tests/positive/sparse.cpp
- tests/positive/sync_object.cpp
- tests/positive/vertex_input.cpp
- tests/positive/wsi.cpp
Just renaming the test names to new format
> tests: Rename tests with the naming system

- tests/framework/layer_validation_tests.cpp
- tests/negative/graphics_library.cpp
- tests/positive/graphics_library.cpp
> tests: Remove redundant renderpass in GPL tests

- build-android/jni/Android.mk
- tests/CMakeLists.txt
- tests/negative/command.cpp
- tests/negative/descriptors.cpp
- tests/negative/dynamic_state.cpp
- tests/negative/image.cpp
- tests/negative/pipeline.cpp
- tests/negative/pipeline_advanced_blend.cpp
- tests/negative/pipeline_layout.cpp
- tests/negative/pipeline_topology.cpp
- tests/negative/shader_compute.cpp
- tests/negative/shader_spirv.cpp
- tests/negative/sync_object.cpp
turn `pipeline_shader` into 4 separate files
> tests: Split up pipeline_shader.cpp tests

- layers/core_checks/cc_drawdispatch.cpp
- layers/core_checks/cc_pipeline_graphics.cpp
- layers/core_checks/core_validation.h
- tests/negative/dynamic_rendering.cpp
- tests/positive/dynamic_rendering.cpp
- Closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/5798
> layers: Add 07616 07617 07618

- layers/core_checks/cc_cmd_buffer_dynamic.cpp
- layers/core_checks/cc_drawdispatch.cpp
- layers/core_checks/core_validation.h
- layers/state_tracker/device_state.h
- layers/state_tracker/state_tracker.cpp
- tests/device_profiles/max_profile.json
- tests/negative/dynamic_state.cpp
- tests/positive/dynamic_state.cpp
adds
- VUID-vkCmdDraw-None-08877
- VUID-vkCmdSetAttachmentFeedbackLoopEnableEXT-attachmentFeedbackLoopDynamicState-08862
- VUID-vkCmdSetAttachmentFeedbackLoopEnableEXT-aspectMask-08863
- VUID-vkCmdSetAttachmentFeedbackLoopEnableEXT-attachmentFeedbackLoopLayout-08864
> Add VK_EXT_attachment_feedback_loop_dynamic_state

- tests/positive/memory.cpp
- vkGetDeviceBufferMemoryRequirements
- vkGetDeviceImageMemoryRequirements
> tests: Add positive for 1.3 memory requirements functionality

- tests/negative/descriptor_buffer.cpp
https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/5826#issuecomment-1541143379
> tests: Add NegativeDescriptorBuffer.NullHandle

- layers/state_tracker/cmd_buffer_state.cpp
- layers/state_tracker/descriptor_sets.cpp
- layers/state_tracker/descriptor_sets.h
- layers/state_tracker/state_tracker.cpp
- layers/state_tracker/state_tracker.h
Remove some unnecessary method arguments and convert pointers into references.
> layers: DescriptorSet state cleanup

- layers/core_checks/cc_cmd_buffer.cpp
- tests/negative/dynamic_rendering.cpp
- tests/positive/dynamic_rendering.cpp
- Closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/5064
VUID-vkCmdDraw-colorAttachmentCount-07616,
VUID-vkCmdDraw-pDepthAttachment-07617 and
VUID-vkCmdDraw-pStencilAttachment-07618 
are added in https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/5815
> layers: Add 07606

- layers/core_checks/cc_device_memory.cpp
- layers/core_checks/cc_image.cpp
Several codepaths in the layers called into
vkGetPhysicalDeviceImageFormatProperties2KHR without including a valid VkPhysicalDeviceImageDrmFormatModifierInfoEXT, despite this being a requirement for images with DRM format modifier tiling.
For the vkBindImageMemory check, there is a hypothetical possibility of the driver returning VK_ERROR_OUT_OF_HOST_MEMORY when querying the image's DRM format. In this case, for lack of anything better to do, we preserve the current behavior.
It might make more sense to query the DRM format modifier immediately after image creation and cache it inside the image state, but I didn't want to make that (more invasive) change myself.
Fixes: https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/5649
Supersedes: …
> layers: Fix UB for VK_IMAGE_TILING_DRM_FORMAT_MODIFIER_EXT

- tests/negative/command.cpp
For https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/5838
> tests: Add tests for multiDrawIndirect feature

- layers/core_checks/cc_shader.cpp
- tests/negative/shader_interface.cpp
- tests/positive/shader_interface.cpp
add `VUID-RuntimeSpirv-OpTypeVector-06816` VUID
Add a negative test also (`PositiveShaderInterface.RelaxedTypeMatch` is already testing this in for a Positive test)
> layers: Relabel maintenance4 VUID

- tests/negative/sparse.cpp
Add test that show https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/5851 bug and prevents regression
> tests: Add tests for imageOpaque sparse bind bug

- tests/positive/image.cpp
Prevents regression of https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/5649
> tests: Add PositiveImage.CreateDrmImageWithExternalMemory

- tests/positive/shader_push_constants.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/2646
We now properly handle checking Push Constants only if accessed from the Entrypoint, so having an unused Push Constant block now will just be ignored
> tests: Add test for Multiple Push Constants

- layers/stateless/sl_instance_device.cpp
Provide better error messages for `VkCreateDevice` error messages
> layers: Improve stateless device creation error messages

- layers/vk_layer_settings.txt
> docs: Show usage of Vendor Specific Best Practices

- .github/workflows/vvl.yml
- ci: Use ccache for MinGW CI
- ci: Fix integration_test failing on CI
> Use ccache for MinGW

- tests/negative/descriptor_buffer.cpp
- tests/negative/mesh.cpp
- tests/positive/fragment_shading_rate.cpp
I noticed these during my SDK testing.
> Fix some tests failing on AMD

- scripts/common_ci.py
- scripts/github_ci_win_linux.py
Currently can't run on GHA due to security permissions.
It works locally on my Windows machine now though.
> scripts: Enable testing script on Windows

- .github/workflows/vvl.yml
1.) Fix ccache misses due to not using matrix.os
2.) Only run 1 job for ubuntu-20.04
> ci: Fix linux performance

- tests/negative/command.cpp
adds 3 more missing tests for https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/5842
> tests: Add missing command negative tests

- tests/negative/command.cpp
- tests/negative/descriptor_buffer.cpp
- tests/negative/descriptors.cpp
- tests/negative/dynamic_rendering.cpp
- tests/negative/dynamic_state.cpp
- tests/negative/fragment_shading_rate.cpp
- tests/negative/multiview.cpp
- tests/negative/pipeline.cpp
- tests/negative/query.cpp
- tests/negative/ray_tracing.cpp
- tests/negative/renderpass.cpp
- tests/negative/sampler.cpp
- tests/negative/subgroups.cpp
- tests/negative/subpass.cpp
- tests/negative/sync_object.cpp
- tests/negative/transform_feedback.cpp
- tests/negative/vertex_input.cpp
- tests/positive/dynamic_rendering.cpp
- tests/positive/ray_tracing.cpp
- tests/positive/shader_interface.cpp
Tried to find the remaining spots not making best use of the `GetPhysicalDeviceFeatures2` and `GetPhysicalDeviceProperties2`
> tests: Use GetPhysicalDeviceFeatures2 and GetPhysicalDeviceProperties2 helpers

- tests/negative/memory.cpp
- tests/negative/sampler.cpp
Adds the following tests for  https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/5842
- VUID-VkSamplerCreateInfo-addressModeU-01078
- VUID-VkSamplerCreateInfo-compareEnable-01080
- VUID-VkSamplerCreateInfo-customBorderColors-04085
- VUID-VkMemoryMapInfoKHR-memory-07962 
Also cleaned up some of the memory tests while in that file
> Add missing Sampler and Memory tests

- layers/core_checks/cc_pipeline_graphics.cpp
- layers/core_checks/cc_shader.cpp
- tests/negative/geometry_tessellation.cpp
- tests/negative/pipeline_topology.cpp
- tests/positive/pipeline_topology.cpp
[change](https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/5916) from the 1.3.251 spec
This adds a VUID (and tests) for 
- VUID-VkGraphicsPipelineCreateInfo-pStages-08888
- VUID-VkGraphicsPipelineCreateInfo-topology-08889
- VUID-VkGraphicsPipelineCreateInfo-topology-08890
> Add new PrimitiveTopology VUIDs

- layers/core_checks/cc_external_object.cpp
- layers/state_tracker/queue_state.cpp
- tests/framework/layer_validation_tests.cpp
- tests/framework/layer_validation_tests.h
- tests/negative/object_lifetime.cpp
- tests/positive/sync_object.cpp
Might also fix https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/5295
> layers: Fix queue progression with imported semaphore

- layers/core_checks/cc_query.cpp
- tests/negative/query.cpp
adds `VUID-VkQueryPoolCreateInfo-meshShaderQueries-07068` and `VUID-VkQueryPoolCreateInfo-meshShaderQueries-07069`
Does a lot of refactoring of the Query CoreCheck code to make next future PRs more easy to read
> Improvements to CoreChecks Query

- layers/core_checks/cc_buffer.cpp
- layers/core_checks/core_validation.h
Move more items in Buffer to use const ref where we know we can
> layers: Add Const Ref for Buffer CoreChecks

- layers/core_checks/cc_image.cpp
- layers/core_checks/cc_image_layout.cpp
- layers/core_checks/cc_synchronization.cpp
- layers/core_checks/core_validation.h
Move more items in Image to use const ref where we know we can
> layers: Add Const Ref for Image CoreChecks

- tests/negative/ray_tracing.cpp
Saw that when running ray tracing tests
> tests: Add missing new lines

- layers/core_checks/cc_cmd_buffer_dynamic.cpp
- layers/core_checks/cc_descriptor.cpp
- layers/core_checks/cc_device_memory.cpp
- layers/core_checks/cc_image.cpp
- layers/core_checks/cc_pipeline_graphics.cpp
- layers/core_checks/cc_render_pass.cpp
- layers/core_checks/cc_synchronization.cpp
- layers/core_checks/cc_wsi.cpp
- layers/stateless/sl_image.cpp
- layers/vulkan/generated/vk_extension_helper.h
- scripts/generators/helper_file_generator.py
This was my first pass attempt to try and unify how we use `IsExtEnabled`
Decided to write the "documentation" in `IsExtEnabled` itself
> layers: Define when to use IsExtEnabled

- layers/core_checks/cc_wsi.cpp
- tests/negative/wsi.cpp
- tests/positive/wsi.cpp
- Closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/5938
Also add a regression test
> layers: Fix 02679 validation

- BUILD.md
Add documentation explaining what UPDATE_DEPS is and how we manage C++ dependencies.
Removes unessential information from BUILD.md
Minor re-ordering of documentation.
> docs: Streamline build information

- tests/negative/dynamic_state.cpp
**actually** fixes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/6020
Realize the test was trying to test 2 things and overloaded
`VUID-vkCmdDraw-None-07637` is already being tested in another test
wrote a separate test for `VUID-vkCmdDraw-None-07638`
> tests: Fix RasterizationLineModeDefault

- .github/workflows/vvl.yml
The chromium folks and some package managers disable robin hood.
> ci: Test with robin hood disabled

- layers/sync/sync_validation.cpp
- tests/positive/sync_val.cpp
This PR fixes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/5994. Some linux distributions provide VVL packages that report false-positive syncval errors and this does not happen when VVL is built according to official build configuration.
The issue is reported on Arch Linux but the problem is also reproducible on Ubuntu (and probably other distributions) both in debug and release configurations and also with different versions of GCC compiler (I tested on 11.xx and 13.1.1).
The issue is observable when using link time optimization `-flto`. Some linux packages are built by specifying it through `CXXFLAGS` environment variable that is consumed by cmake.
UPDATE: after thinking more about this it looks it's not a compiler problem but rather our code goes into the territory …
> layers: Fix syncval undefined initialization order

- BUILD.gn
- build-android/jni/Android.mk
- layers/CMakeLists.txt
- layers/stateless/sl_buffer.cpp
- layers/stateless/sl_image.cpp
- layers/stateless/sl_instance_device.cpp
- layers/stateless/sl_render_pass.cpp
- layers/stateless/sl_utils.cpp
- layers/stateless/sl_wsi.cpp
- layers/stateless/stateless_validation.h
- layers/vulkan/generated/parameter_validation.cpp
- scripts/generators/parameter_validation_generator.py
While trying to update the Parameter Validation generator scripts, realized what we need first is just a basic Stateless Validation Util as there were a few functions that were just C++ code in a python string
> layers: Create a Stateless Util source file

- layers/vulkan/generated/spirv_validation_helper.cpp
- layers/vulkan/generated/vk_enum_string_helper.h
- scripts/generators/enum_string_helper_generator.py
- scripts/generators/spirv_validation_generator.py
Try and remove the `#pragma warning( disable : 4065 )` warning from `vk_enum_string_helper.h` as not sure if needed anymore
> layers: Remove Warning from Enum String helper

- layers/error_message/logging.cpp
- layers/error_message/logging.h
- layers/layer_options.cpp
- layers/layer_options.h
> layers: Change message filter container to unordered_set

- scripts/android.py
- Ensure environment is setup properly
- More error checking
> android: Cleanup android.py script

- scripts/android.py
- scripts/check_code_format.py
- scripts/clang-format-diff.py
- scripts/common_ci.py
- scripts/lvl_genvk.py
- scripts/update_deps.py
- scripts/vk_validation_stats.py
using my pep8 linter, some various cleanup of the scripts
> scripts: Clean up scripts to be Pep8 friendly

- layers/vulkan/generated/chassis.cpp
- layers/vulkan/generated/chassis.h
- layers/vulkan/generated/chassis_dispatch_helper.h
- scripts/generators/layer_chassis_generator.py
- scripts/generators/vulkan_object.py
Chassis scripts now use `VulkanObject`
> scripts: Move chassis to use VulkanObject

- scripts/android.py
You can now specify
- Debug/Release
- The ABI(s) you are targetting
- If you want to build an APK or not
- static vs shared stl
- Building with tests
> android: Add argparse to android.py

- layers/core_checks/cc_shader.cpp
- layers/core_checks/core_validation.h
- tests/unit/subgroups.cpp
Adds `VUID-VkPipelineShaderStageCreateInfo-flags-08988` (added in 1.3.256 header)
> Add computeFullSubgroups stage VU

- docs/generated_code.md
Small write up of things I observed when refactoring all the python scripts
> docs: Add design philosophy for new code gen flow

- tests/device_profiles/max_profile.json
`vkconfig` complains about invalid json and this allowed to detect this minor issue
> tests: Fix json in max profile

- layers/containers/subresource_adapter.cpp
@artem-lunarg -- here's the small clarification you requested...
> sync: Clarify aspect mask specification

- layers/core_checks/cc_shader.cpp
- tests/unit/vertex_input.cpp
- tests/unit/vertex_input_positive.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/5906
Wrote many tests and now can handle vertex input of all variations when it is a struct
> Handle vertex input struct

- layers/core_checks/cc_shader.cpp
- layers/core_checks/cc_shader_interface.cpp
- layers/state_tracker/shader_instruction.cpp
- layers/state_tracker/shader_instruction.h
- layers/state_tracker/shader_module.cpp
- layers/state_tracker/shader_module.h
- tests/device_profiles/spirv_hopper_profile.json
- tests/unit/shader_interface.cpp
- tests/unit/shader_interface_positive.cpp
There is at least more commit to follow this (to better organize the code and remove the `bool nested_struct` workaround), but this adds many more tests. It also fixes issues having structs in the interface blocks as well as having  Multidimensional Arrays interface
> Add support for structs in interface block and Multidimensional Arrays 

- BUILD.gn
> build: Fix Chromium build

- scripts/generate_source.py
Example: --target chassis.h chassis.cpp
> scripts: Support multiple files with --target option

- .github/workflows/sdk_android_build.yml
Important information regarding how we ship the binaries for Android.
> docs: Document Android middleware

- tests/framework/layer_validation_tests.h
- tests/unit/descriptor_buffer.cpp
- tests/unit/descriptor_buffer_positive.cpp
Adds a `InitBasicDescriptorBuffer`
> tests: Add common init for Descriptor Buffers

- layers/core_checks/cc_descriptor.cpp
- tests/unit/descriptor_buffer.cpp
- tests/unit/descriptor_buffer_positive.cpp
Closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/6050
> layers: Add descriptor buffer offset VU 09006

- layers/containers/qfo_transfer.h
- layers/core_checks/cc_copy_blit_resolve.cpp
- layers/core_checks/cc_pipeline_graphics.cpp
- layers/core_checks/cc_render_pass.cpp
- layers/core_checks/cc_synchronization.cpp
- layers/stateless/sl_pipeline.cpp
- layers/sync/sync_vuid_maps.cpp
- layers/sync/sync_vuid_maps.h
- tests/unit/command.cpp
- tests/unit/dynamic_rendering.cpp
- tests/unit/dynamic_state.cpp
- tests/unit/geometry_tessellation.cpp
- tests/unit/graphics_library.cpp
- tests/unit/image.cpp
- tests/unit/imageless_framebuffer.cpp
- tests/unit/mesh.cpp
- tests/unit/pipeline.cpp
- tests/unit/sync_object.cpp
VUID churn for https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/6182
> Fix 1.3.258 VUID Churn

- layers/core_checks/cc_image.cpp
- layers/core_checks/cc_image_layout.cpp
- layers/stateless/sl_image.cpp
- Address https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/4928
> layers: Improve logged objects in cc_image_layout.cpp

- tests/unit/render_pass_positive.cpp
Add positive test `ImageLayoutTransitionOf3dImageWith2dViews` to try to reproduce issue https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/5552
But this new test does produce any validation error.
It does the following:
- Create a 3D image of depth 2
- Create 2D views, one for each depth level
- Create a render pass using the first image view to perform a layout transition from `VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL` to `VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL`
- Create a second render pass using the second image view with an initial layout of `VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL` => this is where I was expecting `UNASSIGNED-CoreValidation-DrawState-InvalidRenderpass` to be reported. But its seems layout transition is correctly tracked for the second image view.
> tests: ImageLayoutTransitionOf3dImageWith2dViews

- scripts/generators/generator_utils.py
- scripts/generators/layer_chassis_dispatch_generator.py
- scripts/generators/object_tracker_generator.py
Adds a `addIndent` helper to improve readability of f-strings we have in some location of our scripts
> scripts: Add addIndent helper

- layers/state_tracker/queue_state.cpp
> layers: Fix typo in logging output

- tests/unit/image.cpp
Adds more tests for https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/5842
> tests: Add missing negative image tests

- layers/core_checks/cc_image.cpp
- tests/unit/image_positive.cpp
This "solves" https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/6256 ... but I really hate how this code looks
We probably need a more elegant solution for the future as other calls might need this
The goal is to take a copy of the `pNext` structs from the incoming call that might be needed when making `DisaptchvkGetPhysicalDevice*` queries
> layers: Pass pNext from vkCreatImage to dispatch

- layers/core_checks/cc_buffer.cpp
- layers/core_checks/cc_cmd_buffer.cpp
- layers/core_checks/cc_descriptor.cpp
- layers/core_checks/cc_drawdispatch.cpp
- layers/core_checks/cc_pipeline.cpp
- layers/core_checks/core_validation.h
- layers/state_tracker/device_state.h
- layers/state_tracker/state_tracker.cpp
- layers/stateless/sl_cmd_buffer.cpp
- layers/stateless/stateless_validation.h
- layers/vulkan/generated/stateless_validation_helper.cpp
- scripts/generators/stateless_validation_helper_generator.py
- tests/device_profiles/max_profile.json
- tests/unit/buffer.cpp
- tests/unit/buffer_positive.cpp
- tests/unit/command.cpp
- tests/unit/graphics_library.cpp
- tests/unit/shader_storage_image.cpp
Adds some initial support for `VK_KHR_maintenance5`
> layers: Add initial VK_KHR_maintenance5

- layers/core_checks/cc_image.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/6255
> layers: Improve ValidateImageFormatFeatureFlags error

- layers/core_checks/cc_ray_tracing.cpp
- tests/framework/ray_tracing_objects.cpp
- tests/framework/ray_tracing_objects.h
- tests/unit/ray_tracing.cpp
- tests/unit/ray_tracing_positive.cpp
- Closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/6040
Add a positive test to track regressions
> layers: Fix validation of 03704

- layers/core_checks/cc_device_memory.cpp
- tests/unit/descriptor_buffer.cpp
Also update related error messages
> layers: Add 09200 09201 09202

- layers/state_tracker/shader_module.cpp
- tests/framework/test_framework.cpp
These 2 files had some encoding issues which could cause build errors on some systems
> layers: Fix encoding

- scripts/android.py
- tests/android/AndroidManifest.xml
- tests/android/res/values/strings.xml
Allows Jenkins CI to clean Android builds
> android: Move APK XML files

- tests/framework/render.cpp
- tests/framework/test_common.h
- tests/unit/image_positive.cpp
- tests/unit/instanceless.cpp
- tests/unit/wsi_positive.cpp
> tests: Remove vk_result_string

- .github/workflows/vvl.yml
Avoids code duplication between the individual jobs
> ci: Set environment variables for the entire workflow

- tests/unit/shader_object_positive.cpp
Wrote these while fixing CTS shader object tests
> tests: Add more shader object positive tests

- layers/core_checks/cc_buffer.cpp
- layers/core_checks/cc_cmd_buffer.cpp
- layers/core_checks/cc_cmd_buffer_dynamic.cpp
- layers/core_checks/cc_copy_blit_resolve.cpp
- layers/core_checks/cc_descriptor.cpp
- layers/core_checks/cc_device.cpp
- layers/core_checks/cc_device_memory.cpp
- layers/core_checks/cc_drawdispatch.cpp
- layers/core_checks/cc_external_object.cpp
- layers/core_checks/cc_image.cpp
- layers/core_checks/cc_image_layout.cpp
- layers/core_checks/cc_pipeline_graphics.cpp
- layers/core_checks/cc_query.cpp
- layers/core_checks/cc_queue.cpp
- layers/core_checks/cc_ray_tracing.cpp
- layers/core_checks/cc_render_pass.cpp
- layers/core_checks/cc_spirv.cpp
- layers/core_checks/cc_synchronization.cpp
- layers/core_checks/cc_video.cpp
- layers/core_checks/cc_wsi.cpp
- layers/core_checks/core_validation.h
- layers/stateless/sl_cmd_buffer_dynamic.cpp
- layers/stateless/sl_pipeline.cpp
- layers/stateless/sl_ray_tracing.cpp
- tests/unit/command.cpp
- tests/unit/render_pass_positive.cpp
Probably the last "large cleanup" of using `Location` everywhere. There are still a few areas left, but the follow-up PRs will be likely focused on a single area
>  Remove more const char and used Location 

- layers/vulkan/generated/spirv_grammar_helper.cpp
- layers/vulkan/generated/spirv_tools_commit_id.h
- scripts/generators/spirv_grammar_generator.py
- scripts/known_good.json
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/6350
there is a new `IdScope` we need to handle
> scripts: Fix new Visibility IdScope in SPIRV Grammar

- layers/core_checks/cc_render_pass.cpp
- tests/framework/render.cpp
- tests/unit/dynamic_rendering.cpp
- tests/unit/dynamic_rendering_positive.cpp
- tests/unit/graphics_library_positive.cpp
- tests/unit/renderpass.cpp
- tests/unit/shader_object_positive.cpp
https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/5972/diffs adds that Render Area need not to be zero
> layers: Add remaining RenderArea VUs

- .github/workflows/vvl.yml
- tests/integration/main.cpp
https://github.com/KhronosGroup/Vulkan-Profiles/pull/487
> tests: Profiles no longer depends on VVL

- layers/core_checks/cc_cmd_buffer_dynamic.cpp
- tests/unit/shader_object_positive.cpp
> Fix validating shader inputs

- tests/unit/shader_spirv_positive.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/6370
So this was fixed post SDK release already (@ziga-lunarg probably knows the exact PR)
@juan-lunarg is working to provide [newer binaries](https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/6356) to help provide a solution faster
> tests: Add SpecConstantTextureArray test

- layers/gpu_validation/debug_printf.cpp
- layers/gpu_validation/gpu_state_tracker.h
- layers/gpu_validation/gpu_validation.cpp
> Fix threaded access to unique_shader_module_id

- layers/core_checks/cc_copy_blit_resolve.cpp
- tests/unit/image.cpp
New error message looks like this:
> Validation Error: [ VUID-vkCmdCopyImage-pRegions-00124 ] Object 0: handle = 0x2123bf53290, type = VK_OBJECT_TYPE_COMMAND_BUFFER; Object 1: handle = 0xe7f79a0000000005, type = VK_OBJECT_TYPE_IMAGE; Object 2: handle = 0xe7f79a0000000005, type = VK_OBJECT_TYPE_IMAGE; | MessageID = 0x384abddf | vkCmdCopyImage: pRegion[0] src overlaps with pRegions[0]. Overlap info: { subresource { aspectMask: VK_IMAGE_ASPECT_COLOR_BIT, mipLevel: 0, baseArrayLayer: 0, layerCount: 1 }, offset {0, 0, 0}, extent {64, 64, 1} }. The Vulkan spec states: The union of all source regions, and the union of all destination regions, specified by the elements of pRegions, must not overlap in memory (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-vkCmdC …
> layers: Improve 00124 (image copy overlaps) message

- layers/core_checks/cc_wsi.cpp
- tests/unit/wsi_positive.cpp
When using VK_EXT_surface_maintenance1 and providing a VkSurfacePresentModeEXT, the values in VkSurfaceCapabilities can change. This can result in a false positive for VUID-VkSwapchainCreateInfoKHR-presentMode-02839. (e.g. on my machine without VkSurfacePresentModeEXT the minImageCount is 4, with a VkSurfacePresentModeEXT specifying FIFO the minImageCount is 2).
When the extension is enabled, always pass a VkSurfacePresentModeEXT to get the most accurate capabilities of the surface.
Question for maintainer: Why is vk_ext_surface_maintenance1 stored in device_extensions when it is an instance_extension?
> layers: Support per-present-mode capabilities for VK_EXT_surface_maintenance1

- layers/core_checks/cc_shader_object.cpp
- layers/stateless/sl_shader_object.cpp
adds `Location` to errors for `VK_EXT_shader_object` (cc @ziga-lunarg)
> layers: Use Location for VK_EXT_shader_object

- scripts/android.py
- tests/android/AndroidManifest.xml
I'll remove strings.xml in a follow up PR since it will require a corresponding change in VulkanTests
> android: Remove dependency on strings.xml

- layers/core_checks/cc_image_layout.cpp
- layers/core_checks/cc_render_pass.cpp
- layers/core_checks/core_validation.h
Add better `Location` support and improve error messages for the `vkCmdBeginRenderPass` VUs related to Image Layouts
> layers: Improve ImageLayout error messages

- layers/thread_tracker/thread_safety_validation.cpp
- layers/vulkan/generated/thread_safety_commands.h
- scripts/generators/thread_safety_generator.py
Add manual Pre- and Post- for thread safety checks of `vkQueuePresentKHR`. Regenerated files.
> layers: Add thread safety checks for vkQueuePresentKHR

- layers/core_checks/cc_buffer.cpp
- layers/core_checks/cc_cmd_buffer.cpp
- layers/core_checks/cc_copy_blit_resolve.cpp
- layers/core_checks/cc_device.cpp
- layers/core_checks/cc_image.cpp
- layers/core_checks/cc_pipeline.cpp
- layers/core_checks/cc_pipeline_graphics.cpp
- layers/core_checks/cc_queue.cpp
- layers/core_checks/cc_shader_interface.cpp
- layers/core_checks/cc_spirv.cpp
- layers/core_checks/core_validation.h
some misc improvements for use of `Location`
> More Improvements using Location

- tests/unit/shader_interface.cpp
- tests/unit/shader_interface_positive.cpp
- tests/unit/sync_object.cpp
- tests/unit/sync_object_positive.cpp
- tests/unit/vertex_input.cpp
- tests/unit/vertex_input_positive.cpp
some mixing of `Positive` and `Negative` in the test names
> tests: Fix mixing of Positive and Negative test names

- layers/core_checks/cc_drawdispatch.cpp
- layers/core_checks/cc_pipeline_graphics.cpp
- layers/core_checks/core_validation.h
I still want to come back and improve all our drawtime error message to include more information, but for now, this gets rid of the old `const char* caller` in favor for the new `Location`
> layers: Add Location to drawtime errors

- layers/vulkan/generated/error_location_helper.cpp
- scripts/generators/error_location_helper_generator.py
Fix typo in script and not populating the `IsFieldPointer` correctly
> scripts: Fix struct members not in IsFieldPointer

- layers/thread_tracker/thread_safety_validation.h
Refactoring to remove duplication :
* Extract error message string construction into a function (3 duplicates)
* Extract read and write error handling into functions (2 duplicates for write)
Functionality has not changed, except the error message adds word "current" to the current reporting thread. Sometimes, it's convenient to distinguish threads and will be more important for the future PR that will add reporting of command name for the second thread.
> layers: Thread safety cleanup

- tests/unit/dynamic_rendering.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/6403
creating issue in spec to figure out why this wasn't caught as expected https://gitlab.khronos.org/vulkan/vulkan/-/issues/3618
> tests: Fix LibraryViewMask test

- layers/core_checks/cc_spirv.cpp
- layers/core_checks/core_validation.h
- layers/state_tracker/shader_module.cpp
- layers/state_tracker/shader_module.h
- layers/vulkan/generated/spirv_grammar_helper.cpp
- layers/vulkan/generated/spirv_grammar_helper.h
- scripts/generators/spirv_grammar_generator.py
- tests/device_profiles/max_profile.json
- tests/unit/shader_cooperative_matrix.cpp
- tests/unit/shader_cooperative_matrix_positive.cpp
- Combines the NV and KHR logic together
- Use more of the logic already done in `SPIRV_MODULE_STATE`
- Improve error messages to provide more info and use `Location`
- Rework tests so we can test with MockICD
- Add Max Profile support so we run these tests on GitHub CI
> layers: Combine and cleanup CooperativeMatrix

- layers/layer_options.cpp
Layer settings where read both by the old and the new system as a first step, removing the old system which is entirely covered by the new system and more use of the `Vulkan-Layer-Settings` library capabilities
> layer: Clean up layer settings code

- layers/core_checks/cc_ray_tracing.cpp
- layers/core_checks/core_validation.h
- layers/stateless/sl_ray_tracing.cpp
Improves the rest of the Ray Tracing messages to use `Location`
> layers: Add Location to remaining Ray Tracing

- layers/core_checks/cc_cmd_buffer_dynamic.cpp
Fixes crashes in some of the shader_object CTS tests
> Fix crash when no stage entrypoint

- layers/core_checks/cc_copy_blit_resolve.cpp
- layers/core_checks/cc_pipeline.cpp
- layers/core_checks/cc_pipeline_graphics.cpp
follow up of https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/6491
> layers: Remove an extra whitespace in the messages

- layers/core_checks/cc_copy_blit_resolve.cpp
- layers/error_message/unimplementable_validation.h
- tests/unit/host_image_copy.cpp
> More host image copy validation

- layers/core_checks/cc_ray_tracing.cpp
- layers/stateless/sl_ray_tracing.cpp
- Some cleanups following https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/6485
> layers: Cleanup RT error messages

- layers/object_tracker/object_lifetime_validation.h
Restructure code to simplify it for further modifications. No changes in functionality.
> layers: Refactor CheckObjectValidity

- layers/core_checks/cc_android.cpp
- layers/core_checks/cc_cmd_buffer_dynamic.cpp
- layers/core_checks/cc_device.cpp
- layers/core_checks/cc_device_memory.cpp
- layers/core_checks/cc_external_object.cpp
- layers/core_checks/cc_image.cpp
- layers/core_checks/cc_image_layout.cpp
- layers/core_checks/cc_render_pass.cpp
- layers/core_checks/cc_shader_object.cpp
- layers/core_checks/cc_synchronization.cpp
- layers/core_checks/cc_wsi.cpp
- layers/core_checks/core_validation.h
More error messages I found not using `Location`
some examples of improvements commented below
> layers: More error message to use Location

- layers/core_checks/cc_cmd_buffer_dynamic.cpp
- layers/core_checks/cc_drawdispatch.cpp
- layers/core_checks/core_validation.h
- tests/unit/dynamic_state.cpp
> Add vuid 07939, validate all required vertex shader inputs are provided with vkCmdSetVertexInputEXT()

- layers/core_checks/cc_spirv.cpp
- layers/gpu_validation/debug_printf.cpp
- layers/gpu_validation/gpu_error_message.cpp
- layers/gpu_validation/gpu_error_message.h
- layers/gpu_validation/gpu_state_tracker.cpp
- layers/gpu_validation/gpu_state_tracker.h
- layers/gpu_validation/gpu_validation.cpp
- layers/state_tracker/shader_module.h
- layers/state_tracker/shader_object_state.cpp
- layers/state_tracker/shader_object_state.h
- layers/state_tracker/state_tracker.cpp
- layers/state_tracker/state_tracker.h
- layers/vulkan/generated/best_practices.cpp
- layers/vulkan/generated/best_practices.h
- layers/vulkan/generated/chassis.cpp
- scripts/generators/best_practices_generator.py
- scripts/generators/layer_chassis_generator.py
- tests/framework/layer_validation_tests.h
- tests/framework/pipeline_helper.cpp
- tests/framework/pipeline_helper.h
- tests/unit/debug_printf.cpp
- tests/unit/gpu_av.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/5580
> Add gpu assisted validation for shader objects

- layers/best_practices/bp_pipeline.cpp
- layers/core_checks/cc_cmd_buffer_dynamic.cpp
- layers/core_checks/cc_drawdispatch.cpp
- layers/core_checks/cc_pipeline_graphics.cpp
- layers/core_checks/cc_shader_interface.cpp
- layers/core_checks/cc_spirv.cpp
- layers/gpu_validation/gpu_state_tracker.cpp
- layers/state_tracker/pipeline_state.cpp
- layers/state_tracker/shader_instruction.cpp
- layers/state_tracker/shader_module.cpp
- layers/state_tracker/shader_module.h
- layers/sync/sync_validation.cpp
- layers/utils/shader_utils.cpp
- layers/utils/shader_utils.h
things I wanted to fix, but didn't have a place to put them
> Misc cleanup to shader logic

- layers/core_checks/cc_device_memory.cpp
- layers/core_checks/cc_query.cpp
- layers/core_checks/core_validation.h
- layers/stateless/sl_cmd_buffer_dynamic.cpp
- layers/stateless/sl_descriptor.cpp
- layers/stateless/sl_instance_device.cpp
- layers/stateless/sl_pipeline.cpp
- layers/stateless/stateless_validation.h
Some more misc spots found needed the `Location` version of `LogError` still
> layers: Add Location to more spots

- tests/unit/graphics_library.cpp
We have positive tests, but an extra negative test after getting confirmation from https://gitlab.khronos.org/vulkan/vulkan/-/issues/3485
> tests: Add extra Dynamic GPL test

- tests/unit/graphics_library.cpp
> Fix CI - Remove vk_testing

- layers/layer_options.cpp
- scripts/known_good.json
Fixes chromium build using ToT
> layers: Update utility libraries

- layers/core_checks/cc_ray_tracing.cpp
- tests/framework/pipeline_helper.cpp
- tests/framework/pipeline_helper.h
- tests/framework/shader_templates.h
- tests/unit/ray_tracing_pipeline_positive.cpp
- Closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/6282
Add a regression test, `PositiveRayTracingPipeline.GetCaptureReplayShaderGroupHandlesKHR`
> layers: Fix group count calculation

- layers/core_checks/cc_cmd_buffer_dynamic.cpp
- layers/core_checks/cc_drawdispatch.cpp
- layers/core_checks/core_validation.h
- tests/unit/dynamic_state.cpp
> Add vertex input validation, vuid 04912 and fix vuid 04913

- layers/core_checks/cc_buffer.cpp
- layers/core_checks/cc_device_memory.cpp
- layers/core_checks/cc_image.cpp
- layers/core_checks/cc_pipeline_graphics.cpp
- layers/stateless/sl_pipeline.cpp
- tests/unit/atomics.cpp
- tests/unit/buffer.cpp
- tests/unit/descriptor_buffer.cpp
- tests/unit/graphics_library.cpp
- tests/unit/host_image_copy.cpp
- tests/unit/pipeline_topology.cpp
We have some VUID left that aren't in the spec so this fixes them up
> layers: Fix broken VUIDs

- layers/core_checks/cc_descriptor.cpp
> Improve VUID 01979 message

- layers/gpu_validation/debug_printf.cpp
From my go back and fix it someday list.
> Use std::string for better memory management in Debug Printf

- layers/state_tracker/state_tracker.cpp
- tests/unit/dynamic_state_positive.cpp
> Fix tracking dynamic viewports

- layers/state_tracker/query_state.h
- tests/unit/query_positive.cpp
> Fix resetting performance queries

- layers/core_checks/cc_cmd_buffer.cpp
- tests/unit/viewport_inheritance.cpp
> Fix and re-enable viewport inheritance tests

- layers/core_checks/cc_copy_blit_resolve.cpp
- tests/unit/command.cpp
- tests/unit/command_positive.cpp
Add new `VUID-VkImageSubresourceLayers-layerCount-09243` in 1.3.265 spec for `VK_REMAINING_ARRAY_LAYERS` usage when `maintenance5` is not on
> Add VK_REMAINING_ARRAY_LAYERS maintenance5 VU

- layers/core_checks/cc_device.cpp
- layers/core_checks/core_validation.h
- tests/unit/other_positive.cpp
- tests/unit/others.cpp
Adds `VUID-vkGetCalibratedTimestampsEXT-timeDomain-09246` and `VUID-VkCalibratedTimestampInfoEXT-timeDomain-02354`
> Add VK_EXT_calibrated_timestamps

- layers/core_checks/cc_device.cpp
Lil cleanup following https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/6562/
> layers: Use IsValueIn

- layers/core_checks/cc_cmd_buffer.cpp
- tests/unit/query.cpp
> Update query VUID 00105

- layers/core_checks/cc_synchronization.cpp
- layers/core_checks/core_validation.h
> Fix log message for barrier stage mask

- layers/core_checks/cc_cmd_buffer_dynamic.cpp
- tests/unit/dynamic_state_positive.cpp
> Fix checking aspect mask in vkCmdSetAttachmentFeedbackLoopEnableEXT

- layers/core_checks/cc_image.cpp
when a list of modifiers is passed, only one of them must be valid, not all of them
successor to https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/6573
> layers: Fix modifier selection validation

- layers/best_practices/bp_pipeline.cpp
Only the first index in VkGraphicsPipelineCreateInfo* was validated for some checks
> layers: Fix pipeline create info best practices

- layers/core_checks/cc_image_layout.cpp
- tests/unit/wsi.cpp
> layers: Verify swapchain image is valid in render pass

- layers/core_checks/cc_cmd_buffer_dynamic.cpp
- layers/core_checks/cc_drawdispatch.cpp
- layers/core_checks/core_validation.h
- tests/unit/pipeline.cpp
> Validate VkMultisampledRenderToSingleSampledInfoEXT rasterization samples

- layers/core_checks/cc_shader_interface.cpp
- layers/core_checks/cc_spirv.cpp
- layers/core_checks/core_validation.h
- layers/state_tracker/shader_module.cpp
- layers/state_tracker/shader_module.h
- tests/unit/fragment_shading_rate.cpp
- tests/unit/geometry_tessellation.cpp
- tests/unit/multiview.cpp
- tests/unit/pipeline_topology_positive.cpp
> layers: Validate geometry shader input topology

- layers/core_checks/cc_pipeline_graphics.cpp
- tests/unit/dynamic_rendering.cpp
> Validate VkCommandBufferInheritanceRenderingInfo formats match pipeline formats

- tests/unit/renderpass.cpp
Part of #5842 
VUID-VkAttachmentDescription-format-06243
VUID-VkAttachmentDescription-format-06242
VUID-VkAttachmentDescription-format-06487
VUID-VkAttachmentDescription-format-06488
> tests: Add invalid attachment description layout tests

- layers/core_checks/cc_cmd_buffer_dynamic.cpp
Check if a dynamic state was set before reading the value
> layers: Add missing shader object state checks

- layers/best_practices/best_practices_error_enums.h
- layers/best_practices/bp_pipeline.cpp
- tests/unit/best_practices.cpp
> Warn if pipeline is being created without a render pass and without VkPipelineRenderingCreateInfo 

- tests/unit/descriptors.cpp
Part of #5842
VUID-VkCopyDescriptorSet-srcSet-01918
VUID-VkCopyDescriptorSet-srcSet-01920
> tests: Add copy descriptor tests with invalid layout flags

- layers/core_checks/cc_cmd_buffer_dynamic.cpp
- layers/core_checks/cc_drawdispatch.cpp
- layers/core_checks/core_validation.h
- tests/unit/dynamic_state.cpp
> Add VUID 07480, validate color attachments with advanced blend

- tests/unit/portability_subset.cpp
Part of #5842
VUID-VkColorBlendEquationEXT-constantAlphaColorBlendFactors-07362
VUID-VkColorBlendEquationEXT-constantAlphaColorBlendFactors-07363
> tests: Test color blend factor with portability subset

- tests/unit/renderpass.cpp
Part of #5842 
VUID-VkFramebufferCreateInfo-pAttachments-00877
VUID-VkFramebufferCreateInfo-pAttachments-00879
> tests: Test invalid framebuffer attachment image usage

- layers/core_checks/cc_query.cpp
- tests/framework/android_hardware_buffer.h
- tests/unit/android_hardware_buffer.cpp
- tests/unit/android_hardware_buffer_positive.cpp
- tests/unit/best_practices.cpp
- tests/unit/buffer.cpp
- tests/unit/command.cpp
- tests/unit/command_positive.cpp
- tests/unit/descriptors.cpp
- tests/unit/dynamic_rendering.cpp
- tests/unit/dynamic_rendering_positive.cpp
- tests/unit/external_memory_sync.cpp
- tests/unit/fragment_shading_rate.cpp
- tests/unit/gpu_av.cpp
- tests/unit/gpu_av_positive.cpp
- tests/unit/memory.cpp
- tests/unit/other_positive.cpp
- tests/unit/query.cpp
- tests/unit/query_positive.cpp
- tests/unit/ray_tracing.cpp
- tests/unit/sampler.cpp
- tests/unit/shader_spirv_positive.cpp
- tests/unit/shader_storage_image.cpp
- tests/unit/shader_storage_texel.cpp
- tests/unit/sync_object.cpp
- tests/unit/sync_object_positive.cpp
- tests/unit/transform_feedback.cpp
- tests/unit/wsi.cpp
- tests/unit/ycbcr.cpp
Various fixes to help remove tests from the Pixel 7 and S23 blacklist
> tests: Fix Android blacklist tests

- tests/unit/descriptors.cpp
Part of #5842
VUID-VkDescriptorImageInfo-imageView-07795
> tests: Test invalid descriptor type in update descriptors

- tests/unit/geometry_tessellation.cpp
Part of #5842 
VUID-VkGraphicsPipelineCreateInfo-TessellationEvaluation-07723
VUID-VkGraphicsPipelineCreateInfo-TessellationEvaluation-07724
> tests: Test tessellation point size

- layers/core_checks/cc_spirv.cpp
Fixes `dEQP-VK.mesh_shader.ext.api.draw_indirect.draw_count_0.offset_0_stride_0.no_count_limit.no_count_offset.with_task_shader_secondary_cmd`
and others
> layers: Validate mesh count if values are found

- layers/VkLayer_khronos_validation.json.in
- layers/core_checks/cc_device.cpp
- layers/core_checks/cc_spirv.cpp
- layers/gpu_validation/debug_printf.cpp
- layers/gpu_validation/debug_printf.h
- layers/gpu_validation/gpu_state_tracker.cpp
- layers/gpu_validation/gpu_state_tracker.h
- layers/gpu_validation/gpu_validation.cpp
- layers/gpu_validation/gpu_validation.h
- layers/utils/shader_utils.h
- layers/utils/vk_layer_utils.cpp
- layers/utils/vk_layer_utils.h
- layers/vk_layer_settings.txt
- layers/vulkan/generated/gpu_inst_shader_hash.h
- scripts/generate_source.py
- scripts/generators/gpuav_inst_shader_hash_generator.py
Cache instrumented shaders to disk to keep from having to instrument them on every run.
> Cache instrumented shaders when running with GPU-AV

- tests/unit/shader_object.cpp
Descriptor set layout was not passesd to shader create
> tests: Fix incompatible descriptor set test

- layers/best_practices/best_practices_validation.h
- layers/best_practices/bp_synchronization.cpp
> layers: Improve best practice barrier message

- layers/stateless/sl_wsi.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/6629
> layers: Fix vkGetPhysicalDeviceSurfaceCapabilities2KHR

- scripts/generate_source.py
Also allows verification of gpu_inst_shader_hash.h
> Explicitly exclude shaders from codegen verification

- tests/unit/command.cpp
- tests/unit/descriptors.cpp
- tests/unit/sync_object.cpp
Part of #5842 
VUID-vkResetEvent-event-03823
VUID-vkSetEvent-event-03941
VUID-vkUpdateDescriptorSets-pDescriptorWrites-06493
VUID-vkCmdClearDepthStencilImage-aspectMask-02824
VUID-vkCmdClearColorImage-image-01993
VUID-vkCmdClearAttachments-aspectMask-07884
VUID-vkCmdClearAttachments-aspectMask-07885
VUID-vkCmdBindDescriptorSets-pDynamicOffsets-01972
> Add more missing negative tests

- layers/best_practices/bp_synchronization.cpp
- tests/unit/best_practices_positive.cpp
> Add missing best practice image access layout combination

- tests/unit/descriptors.cpp
Part of #5842 
VUID-VkDescriptorSetLayoutBindingFlagsCreateInfo-descriptorBindingPartiallyBound-03013
VUID-VkDescriptorSetLayoutBindingFlagsCreateInfo-descriptorBindingSampledImageUpdateAfterBind-03006
VUID-VkDescriptorSetLayoutBindingFlagsCreateInfo-descriptorBindingStorageImageUpdateAfterBind-03007
VUID-VkDescriptorSetLayoutBindingFlagsCreateInfo-descriptorBindingStorageBufferUpdateAfterBind-03008
VUID-VkDescriptorSetLayoutBindingFlagsCreateInfo-descriptorBindingStorageTexelBufferUpdateAfterBind-03010
VUID-VkDescriptorSetLayoutBindingFlagsCreateInfo-descriptorBindingUniformTexelBufferUpdateAfterBind-03009
VUID-VkDescriptorSetLayoutBindingFlagsCreateInfo-descriptorBindingUpdateUnusedWhilePending-03012
VUID-VkDescriptorSetLayoutBindingFlagsCreateInfo-descriptorBindingVariableDescriptorCoun …
> tests: Add descriptor indexing missing features tests

- layers/core_checks/cc_device_memory.cpp
- layers/core_checks/cc_ray_tracing.cpp
- layers/core_checks/core_validation.h
- tests/unit/ray_tracing.cpp
> Add missing vkCmdCopyAccelerationStructureNV validation

- layers/core_checks/cc_descriptor.cpp
- tests/unit/descriptors_positive.cpp
> Update VUID 09003 for feedback loop

- layers/core_checks/cc_cmd_buffer_dynamic.cpp
- layers/core_checks/cc_drawdispatch.cpp
- layers/core_checks/core_validation.h
- tests/unit/dynamic_state.cpp
> layers: Validate color blend format features

- layers/best_practices/best_practices_error_enums.h
- layers/best_practices/bp_render_pass.cpp
- tests/unit/best_practices.cpp
> Add performance warning for non optimal resolve attachment formats

- layers/core_checks/cc_spirv.cpp
- layers/core_checks/core_validation.h
- tests/unit/subgroups.cpp
> Update VUID 02756, validate required subgroup size in task and mesh shaders

- layers/core_checks/cc_pipeline_graphics.cpp
- layers/stateless/sl_pipeline.cpp
- tests/unit/dynamic_rendering.cpp
- tests/unit/dynamic_rendering_positive.cpp
- tests/unit/mesh.cpp
https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/6171 was added in 1.3.267 headers
> layers: Fix pColorBlend dynamic rendering

- tests/framework/binding.cpp
This was just a fancy way to check for errors. It doesn't provide any benefit over using gtest ASSERT_* and EXPECT_* macros directly.
> tests: Remove EXPECT() macro

- tests/unit/descriptors.cpp
Part of #5842 
VUID-VkDescriptorSetLayoutBindingFlagsCreateInfo-flags-03003
VUID-VkDescriptorSetLayoutBindingFlagsCreateInfo-pBindingFlags-03004
VUID-VkDescriptorSetLayoutBindingFlagsCreateInfo-pBindingFlags-03015
VUID-VkDescriptorSetVariableDescriptorCountAllocateInfo-descriptorSetCount-03045
> tests: Add missing descriptors tests

- layers/containers/subresource_adapter.h
- layers/state_tracker/descriptor_sets.cpp
- layers/state_tracker/descriptor_sets.h
- layers/state_tracker/image_state.cpp
- layers/state_tracker/image_state.h
- layers/sync/sync_validation.cpp
- layers/sync/sync_validation.h
A series of small hotspot removals.
> Second set of performance optimizations for synchronization

- layers/core_checks/cc_buffer.cpp
- layers/core_checks/cc_copy_blit_resolve.cpp
- layers/stateless/sl_descriptor.cpp
- layers/stateless/sl_pipeline.cpp
- tests/unit/atomics.cpp
- tests/unit/buffer.cpp
- tests/unit/command.cpp
- tests/unit/descriptors.cpp
- tests/unit/image.cpp
- tests/unit/pipeline.cpp
Fixing VUID found after 268 header update
> layers: Fix VUID churn for 268

- layers/core_checks/cc_copy_blit_resolve.cpp
- layers/state_tracker/state_tracker.h
- layers/sync/sync_validation.cpp
- tests/unit/command_positive.cpp
> layers: Fix getting buffer size from image

- layers/containers/custom_containers.h
- tests/vvl_utils/small_vector.cpp
Dry and cleanup.  Improved perf and debuggability.
> Small vector cleanup

- scripts/generate_spirv.py
Now that generate_spirv.py will always generate gpu_inst_shader_hash.h,
I want to change the parameter to give a directory that will be the base
directory for the generated outputs. This makes the script work better
when there are multiple outputs.
> scripts: Change the outfilename parameter to a directory

- layers/core_checks/cc_cmd_buffer_dynamic.cpp
- layers/core_checks/cc_drawdispatch.cpp
- layers/core_checks/core_validation.h
- layers/state_tracker/cmd_buffer_state.h
- layers/state_tracker/state_tracker.cpp
- tests/unit/dynamic_state.cpp
> Add vuid 07482, Validate sample locations samples count

- layers/core_checks/cc_copy_blit_resolve.cpp
- tests/unit/host_image_copy.cpp
> Add validation for host_image_copy 09393 and 09394

- layers/core_checks/cc_shader_interface.cpp
- tests/unit/geometry_tessellation.cpp
- tests/unit/geometry_tessellation_positive.cpp
> Skip pipeline topology validation at pipeline create time if it's dynamic

- layers/core_checks/cc_image_layout.cpp
- tests/unit/renderpass.cpp
> Replace unassigned VUID for image layout with 00900 and 03100

- layers/core_checks/cc_pipeline_graphics.cpp
- layers/core_checks/cc_render_pass.cpp
Some misc error messages saw need improvements
> layers: Fix misc error messages

- layers/core_checks/cc_android.cpp
- tests/unit/android_hardware_buffer.cpp
Adds some AHB VUs that seemed to never have got added
- VUID-VkMemoryAllocateInfo-pNext-07900
- VUID-VkMemoryAllocateInfo-pNext-07901
- VUID-VkMemoryAllocateInfo-pNext-02586
> layers: Add Dedicated Memory VUs for AHB

- layers/stateless/sl_instance_device.cpp
- tests/framework/layer_validation_tests.h
- tests/unit/atomics.cpp
- tests/unit/mesh.cpp
- tests/unit/mesh_positive.cpp
- tests/unit/others.cpp
- tests/unit/query.cpp
- tests/unit/shader_limits_positive.cpp
- tests/unit/shader_mesh.cpp
- tests/unit/shader_object.cpp
- tests/unit/shader_object_positive.cpp
- tests/unit/subgroups.cpp
> Validate mesh shader required features

- layers/core_checks/cc_render_pass.cpp
- tests/unit/multiview.cpp
- tests/unit/query.cpp
- tests/unit/renderpass.cpp
> layers: Validate multiview feature is enabled when render pass view masks are used

- layers/core_checks/cc_cmd_buffer.cpp
- tests/unit/dynamic_rendering.cpp
> layers: Validate render pass continue flag, add VUID 09240

- layers/core_checks/cc_descriptor.cpp
- tests/unit/descriptors.cpp
Part of #6738 
Inline uniform blocks are different from other descriptor types and require some separate validation checks. 
I have modified the `GetDescriptorSum()` to use the same logic as other descriptor types and created a separate function for the special cases inline uniform blocks use.
> layers: Validate total byte limit of inline uniform blocks

- layers/core_checks/cc_pipeline.cpp
- tests/unit/protected_memory.cpp
> Validate binding ray tracing pipeline in protected command buffer

- layers/core_checks/cc_cmd_buffer_dynamic.cpp
- layers/core_checks/cc_drawdispatch.cpp
- layers/core_checks/core_validation.h
- tests/unit/dynamic_state.cpp
> Validate dynamic sample locations and rasterization samples mismatch, add vuid 07483

- layers/vulkan/generated/object_tracker.cpp
- scripts/generators/object_tracker_generator.py
- tests/unit/parent.cpp
adds `VUID-VkRenderPassBeginInfo-framebuffer-02780`
> layers: Add Imageless Framebuffer ObjectTracker

- scripts/update_deps.py
Reduce the amount of useless information update_deps.py provides while still being able to produce high quality error messages when something goes wrong.
If a user needs to though they can still use the VERBOSE environment variable to get detailed logs.
> scripts: Minimize update_deps.py noise

- layers/core_checks/cc_cmd_buffer_dynamic.cpp
- layers/core_checks/cc_drawdispatch.cpp
- layers/core_checks/core_validation.h
- layers/state_tracker/cmd_buffer_state.cpp
- tests/unit/dynamic_state.cpp
> layers: Validate dynamic rasterization samples, add vuid 07471

- layers/core_checks/cc_image.cpp
- layers/core_checks/cc_wsi.cpp
- tests/unit/image.cpp
- tests/unit/wsi.cpp
> Add missing validation for image compression control

- layers/core_checks/cc_descriptor.cpp
- layers/core_checks/cc_drawdispatch.cpp
- layers/core_checks/core_validation.h
- layers/state_tracker/cmd_buffer_state.cpp
- layers/state_tracker/cmd_buffer_state.h
- layers/state_tracker/render_pass_state.h
- layers/state_tracker/state_tracker.cpp
- layers/utils/convert_utils.cpp
- tests/unit/descriptors.cpp
> Update attachment access validation

- tests/unit/command.cpp
> tests: Test invalid command buffer begin inheritance info

- tests/unit/dynamic_rendering.cpp
> tests: Test image without required subsampled flag

- tests/unit/ray_tracing_pipeline.cpp
This change doesn't affect the way the test runs, but it provides a descriptor set layout of type VK_DESCRIPTOR_TYPE_ACCELERATION_STRUCTURE_KHR which the AMD driver needs, otherwise it crashes
Closes #4912
> tests: Change ray tracing test to avoid amd crash

- layers/core_checks/cc_cmd_buffer_dynamic.cpp
- layers/core_checks/cc_drawdispatch.cpp
- layers/core_checks/core_validation.h
- tests/unit/dynamic_state.cpp
> Validate sample locations with rasterization samples, add vuids 07936 07937 07938

- layers/core_checks/cc_pipeline_graphics.cpp
- tests/unit/graphics_library.cpp
- tests/unit/pipeline.cpp
- tests/unit/pipeline_positive.cpp
Fix the labeling of ` VUID-VkGraphicsPipelineCreateInfo-renderPass-09028` and make sure test coverage for it
> layers: Fix valid null pDepthStencilState

- tests/unit/command_positive.cpp
- tests/unit/ray_tracing_gpu_nv.cpp
2 PRs collided and main is failing
> layers: Fix broken build

- layers/layer_chassis_dispatch_manual.cpp
- tests/unit/pipeline_positive.cpp
> layers: Unwrap device generated commands shader modules

- layers/stateless/sl_pipeline.cpp
- tests/unit/pipeline.cpp
- tests/unit/pipeline_positive.cpp
> Validate viewport state in graphics pipeline create, add vuid 04892

- layers/core_checks/cc_cmd_buffer_dynamic.cpp
- layers/core_checks/cc_drawdispatch.cpp
- layers/core_checks/cc_pipeline_graphics.cpp
- layers/core_checks/cc_query.cpp
- layers/core_checks/cc_render_pass.cpp
- layers/core_checks/core_validation.h
- layers/error_message/validation_error_enums.h
- tests/unit/best_practices.cpp
- tests/unit/dynamic_state.cpp
- tests/unit/fragment_shading_rate.cpp
- tests/unit/graphics_library.cpp
- tests/unit/pipeline.cpp
- tests/unit/query.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/6792
> layers: Fix VUID from 1.3.269

- layers/core_checks/cc_device_memory.cpp
- tests/unit/sparse_image.cpp
Closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/6757
> layers: Add 02732 02733

- BUILD.gn
- layers/CMakeLists.txt
- tests/layers/CMakeLists.txt
FYI @charles-lunarg / @mikes-lunarg
> Cleanup linker options and copy pasted defines

- layers/error_message/logging.h
- tests/unit/threading_positive.cpp
> layers: Add missing lock to FormatHandle

- layers/stateless/sl_image.cpp
- tests/unit/image.cpp
> layers: Validate image create flags

- layers/object_tracker/object_lifetime_validation.h
- layers/object_tracker/object_tracker_utils.cpp
- layers/vulkan/generated/object_tracker.cpp
- scripts/generators/object_tracker_generator.py
Pass `Location` for `CreateObject` to know where the error occurred
> layers: Add Location to Object Tracker errors

- layers/sync/sync_validation.cpp
- layers/sync/sync_validation.h
Add `Location` to the rest of Sync Val errors
> layers: Add Location to Sync Val errors

- layers/core_checks/cc_android.cpp
- layers/core_checks/cc_copy_blit_resolve.cpp
- layers/core_checks/cc_descriptor.cpp
- layers/core_checks/cc_device_memory.cpp
- layers/core_checks/cc_query.cpp
- layers/core_checks/core_validation.h
- layers/stateless/sl_instance_device.cpp
- layers/stateless/stateless_validation.h
cleans out some TODO, comment for each below
> layers: Remove some old TODOs

- layers/core_checks/cc_buffer_address.h
- layers/core_checks/cc_cmd_buffer.cpp
- layers/core_checks/cc_descriptor.cpp
- layers/core_checks/cc_image_layout.cpp
- layers/core_checks/cc_pipeline.cpp
- layers/core_checks/cc_pipeline_graphics.cpp
- layers/core_checks/cc_queue.cpp
- layers/core_checks/cc_ray_tracing.cpp
- layers/core_checks/cc_spirv.cpp
- layers/core_checks/cc_synchronization.cpp
- layers/core_checks/core_validation.h
- layers/gpu_validation/debug_printf.cpp
- layers/gpu_validation/debug_printf.h
- layers/gpu_validation/gpu_state_tracker.cpp
- layers/gpu_validation/gpu_state_tracker.h
- layers/gpu_validation/gpu_validation.cpp
- layers/gpu_validation/gpu_validation.h
- layers/object_tracker/object_lifetime_validation.h
- layers/state_tracker/cmd_buffer_state.cpp
- layers/state_tracker/cmd_buffer_state.h
- layers/state_tracker/queue_state.cpp
- layers/state_tracker/queue_state.h
- layers/state_tracker/state_tracker.cpp
- layers/state_tracker/state_tracker.h
- layers/stateless/sl_descriptor.cpp
- scripts/common_ci.py
In effort to remove the old `LogError`, adds `Location` in some places in order to use the new `LogError`
> layers: Add more LogError with Location

- layers/core_checks/cc_query.cpp
> layers: Improve VUID 01922 message

- .github/workflows/vvl.yml
Quickest way to fix Windows CI
> ci: Disable linker warnings as errors

- layers/core_checks/cc_cmd_buffer.cpp
- layers/core_checks/cc_image.cpp
- layers/core_checks/cc_image_layout.cpp
- layers/core_checks/cc_ray_tracing.cpp
- layers/core_checks/cc_synchronization.cpp
- layers/core_checks/cc_wsi.cpp
> layers: Replace hex values with enum names

- layers/core_checks/cc_cmd_buffer_dynamic.cpp
- layers/core_checks/cc_drawdispatch.cpp
- layers/core_checks/core_validation.h
- layers/state_tracker/cmd_buffer_state.h
- layers/state_tracker/state_tracker.cpp
- tests/unit/shader_object.cpp
- tests/unit/shader_object_positive.cpp
> layers: Update shader object VUIDs

- layers/stateless/sl_instance_device.cpp
- tests/unit/instanceless.cpp
- tests/unit/others.cpp
> layers: Validate instance create info pNext

- layers/core_checks/cc_cmd_buffer.cpp
- layers/core_checks/cc_copy_blit_resolve.cpp
- layers/core_checks/cc_render_pass.cpp
- layers/core_checks/cc_shader_object.cpp
- layers/core_checks/cc_synchronization.cpp
- layers/error_message/validation_error_enums.h
- tests/unit/descriptors.cpp
- tests/unit/external_memory_sync.cpp
- tests/unit/renderpass.cpp
- tests/unit/shader_object.cpp
Another round to remove some UNASSIGNED VUIDs
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/6727
> layers: Remove more UNASSIGNED VUs

- layers/core_checks/cc_ray_tracing.cpp
- layers/core_checks/core_validation.h
- layers/utils/ray_tracing_utils.cpp
- layers/utils/ray_tracing_utils.h
- tests/unit/ray_tracing.cpp
Also refacto the ray tracing memory aliasing validation code
> layers: Add 03668

- layers/best_practices/bp_pipeline.cpp
- tests/unit/best_practices_positive.cpp
> layers: Fix best practice check for pipeline library with no rendering

- layers/core_checks/cc_pipeline_graphics.cpp
- tests/unit/graphics_library.cpp
- tests/unit/graphics_library_positive.cpp
> layers: Update pipeline layout check for libraries

- layers/core_checks/cc_cmd_buffer_dynamic.cpp
- layers/core_checks/cc_drawdispatch.cpp
- layers/core_checks/core_validation.h
- tests/unit/dynamic_state.cpp
Part of https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/5507
> layers: Validate conservative rasterization with points and lines

- layers/core_checks/cc_cmd_buffer_dynamic.cpp
- layers/core_checks/cc_drawdispatch.cpp
- layers/core_checks/core_validation.h
- layers/state_tracker/cmd_buffer_state.h
- layers/state_tracker/state_tracker.cpp
- tests/unit/android_external_resolve.cpp
- tests/unit/dynamic_state.cpp
> layers: Validate sample mask and rasterization samples

- layers/core_checks/cc_pipeline_graphics.cpp
- layers/core_checks/core_validation.h
- layers/state_tracker/pipeline_state.h
- layers/stateless/sl_pipeline.cpp
- tests/unit/graphics_library_positive.cpp
> layers: Fix tessellation validation with libraries

- layers/core_checks/cc_copy_blit_resolve.cpp
- layers/core_checks/core_validation.h
- tests/unit/command.cpp
- tests/unit/command_positive.cpp
> Add validation for 00173 & 00184

- layers/best_practices/best_practices_error_enums.h
- layers/best_practices/best_practices_validation.h
- layers/best_practices/bp_drawdispatch.cpp
- layers/best_practices/bp_render_pass.cpp
- tests/unit/best_practices.cpp
Closes #3518
Most of this was taken from #3923
> Add best practice warning for not setting all push constant bytes

- layers/core_checks/cc_cmd_buffer_dynamic.cpp
- layers/core_checks/cc_drawdispatch.cpp
- layers/core_checks/core_validation.h
- layers/state_tracker/shader_module.cpp
- layers/state_tracker/shader_module.h
- tests/unit/dynamic_state.cpp
- tests/unit/pipeline_positive.cpp
> layers: Validate sample locations enable

- layers/core_checks/cc_image.cpp
- tests/unit/android_hardware_buffer_positive.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/6856
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/6646
> layers: Fix checking VK_FORMAT_UNDEFINED for image props

- layers/vulkan/generated/chassis.cpp
- scripts/generators/layer_chassis_generator.py
- tests/framework/gpu_av_helper.h
- tests/framework/layer_validation_tests.h
- tests/unit/gpu_av.cpp
- tests/unit/gpu_av_positive.cpp
- tests/unit/ray_tracing_gpu_nv.cpp
- tests/unit/shader_object_positive.cpp
- tests/unit/ycbcr.cpp
Also fix a GPU-AV problem with shader objects
> Add test for GPU-AV shader selection using shader objects

- layers/best_practices/best_practices_error_enums.h
- layers/best_practices/bp_pipeline.cpp
- tests/unit/best_practices.cpp
> layers: Add warning for missing input attachment

- scripts/vk_validation_stats.py
adds a `-remove_duplicates` to stats script to remove VUs with same number VUID
so now `VUID-vkCmdDraw-magFilter-04553` is the only thing that comes up for `04553` and removes the other 28 current VUs with same number
> scripts: Add remove duplicates from stats script

- layers/object_tracker/object_tracker_utils.cpp
- tests/unit/parent.cpp
adds
- VUID-vkUpdateDescriptorSets-pDescriptorWrites-06236
- VUID-vkUpdateDescriptorSets-pDescriptorWrites-06237
- VUID-vkUpdateDescriptorSets-pDescriptorWrites-06239
- VUID-vkUpdateDescriptorSets-pDescriptorWrites-06240
- VUID-vkUpdateDescriptorSets-pDescriptorWrites-06241
> layers: Add Descriptor Update parent check

- layers/core_checks/cc_copy_blit_resolve.cpp
- tests/unit/command_positive.cpp
> Fix texel size in image/buffer copies

- layers/stateless/sl_pipeline.cpp
adds `VUID-VkGraphicsPipelineCreateInfo-pRasterizationState-09040`
> layers: Label pRasterizationState VU

- layers/best_practices/bp_pipeline.cpp
Fixes crash in dEQP-VK.pipeline.monolithic.shader_module_identifier.pipeline_from_id.graphics.1_variants.no_spec_constants.no_pipeline_cache.all_zeros_id.no_exec_properties.vert_frag
> Fix BP case with no stage entrypoint

- layers/VkLayer_khronos_validation.json.in
- layers/gpu_validation/gpu_validation.cpp
> Fix GPU-AV setting name

- layers/thread_tracker/thread_safety_validation.cpp
- layers/vulkan/generated/thread_safety.cpp
- scripts/generators/thread_safety_generator.py
Closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/3615
> layers: Use manual WaitForPresentKHR in thread-safety

- layers/core_checks/cc_pipeline_graphics.cpp
- tests/unit/dynamic_rendering_positive.cpp
> Update VUID 06179 for dynamic rendering unused attachments

- tests/unit/gpu_av.cpp
https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/6948
> tests: Disable GpuBufferDeviceAddressOOB

- layers/core_checks/cc_descriptor.cpp
- scripts/vk_validation_stats.py
- tests/unit/others.cpp
Fixes current VUID consistency warnings
> scripts: Cleanup remaining VUID consistency warnings

- layers/core_checks/cc_cmd_buffer.cpp
- tests/unit/query.cpp
> layers: Fix pipeline statistics query with secondary command buffers

- layers/stateless/sl_descriptor.cpp
- tests/framework/descriptor_helper.cpp
- tests/framework/descriptor_helper.h
- tests/unit/descriptors.cpp
- tests/unit/gpu_av.cpp
adds VUID-VkDescriptorPoolCreateInfo-pPoolSizes-09424
> layers: Add check for maxInlineUniformBlockBindings

- layers/containers/custom_containers.h
- layers/sync/sync_validation.cpp
- layers/sync/sync_validation.h
- tests/framework/render.h
- tests/unit/sync_val.cpp
Includes tests from @artem-lunarg 's branch.
> syncval: Add dynamic rendering support

- layers/best_practices/bp_pipeline.cpp
- layers/best_practices/bp_render_pass.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/6963
> bp: Check for valid RenderPass state

- docs/shader_validation.md
- layers/drawdispatch/descriptor_validator.cpp
- layers/state_tracker/shader_module.cpp
- layers/state_tracker/shader_module.h
- layers/utils/image_layout_utils.cpp
- layers/utils/image_layout_utils.h
- tests/CMakeLists.txt
- tests/framework/layer_validation_tests.h
- tests/unit/command.cpp
- tests/unit/gpu_av.cpp
- tests/unit/pipeline.cpp
- tests/unit/sampler.cpp
- tests/unit/shader_image_access.cpp
- tests/unit/shader_image_access_positive.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/5614
Now track functions to detect where variables are found in `ImageAccess`
> layers: Add Function support for ImageAccess

- layers/core_checks/cc_buffer.cpp
- tests/unit/buffer_positive.cpp
Some CTS tests were incorrectly reporting this VUID
> layers: Fix buffer view usage flags check

- scripts/common_ci.py
DYLD_LIBRARY_PATH is basically the same thing as LD_LIBRARY_PATH except for .dylib
Tests will not run otherwise
> scripts: Allow running tests on Mac

- docs/gpu_av_shader_instrumentation.md
- docs/shader_validation.md
- layers/gpu_shaders/README.md
- scripts/generate_spirv.py
- tests/unit/gpu_av.cpp
Adds more information about the GPU-AV system for instrumenting shaders
> gpuav: Cleanup docs and script

- tests/unit/gpu_av.cpp
> tests: Disable GpuBufferOOB

- docs/fine_grained_locking.md
- layers/best_practices/best_practices_utils.cpp
- layers/best_practices/best_practices_validation.h
- layers/best_practices/bp_instance_device.cpp
- layers/best_practices/bp_synchronization.cpp
- layers/core_checks/cc_copy_blit_resolve.cpp
- layers/core_checks/cc_external_object.cpp
- layers/core_checks/cc_queue.cpp
- layers/core_checks/cc_synchronization.cpp
- layers/core_checks/cc_wsi.cpp
- layers/core_checks/core_validation.h
- layers/gpu_validation/gpu_state_tracker.cpp
- layers/gpu_validation/gpu_state_tracker.h
- layers/state_tracker/cmd_buffer_state.h
- layers/state_tracker/image_state.cpp
- layers/state_tracker/image_state.h
- layers/state_tracker/queue_state.cpp
- layers/state_tracker/queue_state.h
- layers/state_tracker/state_tracker.cpp
- layers/state_tracker/state_tracker.h
- layers/sync/sync_validation.cpp
- layers/sync/sync_validation.h
QUEUE_STATE -> vvl::Queue
SEMAPHORE_STATE -> vvl::Semaphore
FENCE_STATE -> vvl::Fence
> layers: De-shoutify queue_state.{h,cpp}

- layers/core_checks/cc_pipeline_graphics.cpp
- layers/drawdispatch/drawdispatch_vuids.cpp
- layers/drawdispatch/drawdispatch_vuids.h
- tests/unit/dynamic_rendering.cpp
08916 is for stencil attachment, 08913 is for depth attachment
> layers: Use correct 08913 VUID for depth attachment

- layers/core_checks/cc_synchronization.cpp
Response to https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/5589#issuecomment-1826832503 which is a good point.
> layeres: Fix semaphore signal error message

- docs/creating_tests.md
- layers/core_checks/cc_cmd_buffer.cpp
- layers/core_checks/cc_image.cpp
- layers/core_checks/cc_synchronization.cpp
- layers/state_tracker/state_tracker.cpp
- tests/unit/android_hardware_buffer.cpp
- tests/unit/image_drm.cpp
- tests/unit/object_lifetime.cpp
cc @mikes-lunarg 
Changes from 1.3.171 spec
> layers: Fix VUID Churn for 1.3.171

- layers/gpu_validation/gpu_error_message.cpp
Use gpuav::GetGpuVuid to pick the correct VUID
in PreDrawResources::LogValidationMessage
> gpu: Improve VUID selection

- tests/unit/descriptor_buffer.cpp
The test failed when bufferlessPushDescriptor is not supported
> tests: Fix descriptor buffer BindingAndOffsets test

- layers/core_checks/cc_pipeline_graphics.cpp
- layers/core_checks/cc_spirv.cpp
Some quality-of-life fixes to prevent deep nesting by doing reasonable early returns
broke off in separate PR for ease of review
> layers: Early return in cc_pipeline_graphics.cpp

- layers/vulkan/generated/spirv_tools_commit_id.h
- scripts/known_good.json
Pull in https://github.com/KhronosGroup/SPIRV-Tools/pull/5493
> build: Update SPIRV-Tools to fix a CTS problem

- layers/core_checks/cc_cmd_buffer_dynamic.cpp
- tests/unit/dynamic_state.cpp
> layers: Fix check for drawing with dynamic viewport with count and scissor with count

- layers/core_checks/cc_device.cpp
- layers/core_checks/core_validation.h
- scripts/known_good.json
- tests/device_profiles/max_profile.json
- tests/unit/other_positive.cpp
- tests/unit/others.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/7116
> layers: Add VK_KHR_calibrated_timestamps support

- layers/object_tracker/object_lifetime_validation.h
- layers/object_tracker/object_tracker_utils.cpp
- scripts/known_good.json
- tests/unit/parent.cpp
- tests/unit/wsi_positive.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/7123
> layers: Add VkDisplayKHR support for ObjectTracker

- layers/stateless/sl_descriptor.cpp
- tests/unit/descriptors.cpp
@spencer-lunarg This is the change if VU 06493 will be updated
> layers: Update push descriptor imageInfo VUID

- layers/core_checks/cc_query.cpp
- layers/core_checks/cc_render_pass.cpp
- layers/core_checks/core_validation.h
- layers/state_tracker/cmd_buffer_state.cpp
- layers/state_tracker/cmd_buffer_state.h
- layers/state_tracker/query_state.h
- layers/state_tracker/state_tracker.cpp
- tests/unit/query.cpp
- tests/unit/query_positive.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/6732
> Add RenderPass Query check

- layers/core_checks/cc_pipeline_graphics.cpp
- tests/unit/best_practices.cpp
- tests/unit/dynamic_state.cpp
- tests/unit/geometry_tessellation.cpp
- tests/unit/graphics_library.cpp
- tests/unit/graphics_library_positive.cpp
- tests/unit/image.cpp
- tests/unit/wsi.cpp
- tests/unit/wsi_positive.cpp
> tests: Fix tests crashing on Intel Mesa

- layers/core_checks/cc_pipeline.cpp
- layers/core_checks/core_validation.h
- layers/state_tracker/cmd_buffer_state.cpp
- layers/state_tracker/cmd_buffer_state.h
- layers/state_tracker/state_tracker.cpp
- layers/vulkan/generated/dynamic_state_helper.cpp
- layers/vulkan/generated/dynamic_state_helper.h
- scripts/generators/dynamic_state_generator.py
- tests/unit/dynamic_state.cpp
> layers: Warn if pipeline is rebound when dynamic state was set

- docs/debug_printf.md
Fix some formatting and add an explanation of the changes made for Issue #4350, just in case someone runs into them.
> docs: Update debug printf docs

- layers/core_checks/cc_device_memory.cpp
- tests/unit/external_memory_sync.cpp
Part of https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/6876
> layers: Add external memory VUs 01876 01877

- layers/core_checks/cc_external_object.cpp
- layers/core_checks/core_validation.h
- layers/stateless/sl_external_object.cpp
- layers/stateless/stateless_validation.h
- layers/vulkan/generated/stateless_validation_helper.cpp
- scripts/generators/stateless_validation_helper_generator.py
- tests/unit/external_memory_sync.cpp
Part of https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/6876
> layers: Add external memory VUs 00662 00664

- layers/gpu_validation/gpu_validation.cpp
- tests/unit/gpu_av_positive.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/7161
> layers: Fix drawIndirectFirstInstance GPU-AV regression

- layers/core_checks/cc_render_pass.cpp
for https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/7141
> layers: Add VkFragmentShadingRateAttachmentInfoKHR for AHB External Resolve Format

- layers/core_checks/cc_drawdispatch.cpp
- layers/drawdispatch/drawdispatch_vuids.cpp
- layers/drawdispatch/drawdispatch_vuids.h
- layers/state_tracker/cmd_buffer_state.h
- layers/state_tracker/state_tracker.cpp
- layers/state_tracker/state_tracker.h
- layers/stateless/sl_instance_device.cpp
- layers/stateless/stateless_validation.h
- tests/device_profiles/max_profile.json
- tests/unit/vertex_input.cpp
> Add support for VK_KHR_vertex_attribute_divisor

- layers/core_checks/cc_query.cpp
- layers/core_checks/core_validation.h
- layers/state_tracker/query_state.h
- layers/state_tracker/state_tracker.cpp
- tests/unit/query.cpp
adds `VUID-vkCmdBeginQuery-queryPool-07289` / `VUID-vkCmdBeginQueryIndexedEXT-queryPool-07289`
> Add Perf Query queue family index check

- layers/core_checks/cc_pipeline_graphics.cpp
- layers/core_checks/core_validation.h
- layers/stateless/sl_pipeline.cpp
- tests/unit/gpu_av_oob.cpp
- tests/unit/graphics_library.cpp
- tests/unit/graphics_library_positive.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/7187
some cleanup commits in PR as well
> layers: Add GPL Push Constant check

- layers/core_checks/cc_spirv.cpp
- tests/unit/shader_interface.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/6928
> tests: Add invalid Static SPIR-V test

- layers/core_checks/cc_query.cpp
- tests/unit/query.cpp
- tests/unit/render_pass_positive.cpp
adds `VUID-vkCmdCopyQueryPoolResults-queryCount-09438` and `VUID-vkGetQueryPoolResults-queryCount-09438`
> layers: Add queryCount and stride check

- tests/unit/gpu_av_positive.cpp
Two gpu av tests were failing when using --gpuav-enable-core 
It was due to bad usage of the "helper" CreateComputePipelineHelper
> tests: Fix gpu av tests

- tests/unit/shader_object.cpp
> tests: Fix api version in shader object tests

- CMakeLists.txt
> layers: Set encoding to utf-8

- tests/CMakeLists.txt
- tests/framework/layer_validation_tests.h
- tests/framework/shader_templates.h
- tests/unit/gpu_av.cpp
- tests/unit/gpu_av_buffer_device_address.cpp
- tests/unit/gpu_av_buffer_device_address_positive.cpp
- tests/unit/gpu_av_descriptor_indexing.cpp
- tests/unit/gpu_av_descriptor_indexing_positive.cpp
- tests/unit/gpu_av_oob.cpp
- tests/unit/gpu_av_oob_positive.cpp
Extra tests to exercise end-to-end usage of the SPIR-V instrumentation
> tests: Add more GPU-AV tests

- layers/CMakeLists.txt
> build: Remove "lib" prefix in output binary

- layers/stateless/sl_ray_tracing.cpp
- layers/stateless/stateless_validation.h
- layers/vulkan/generated/stateless_validation_helper.cpp
- scripts/generators/stateless_validation_helper_generator.py
- tests/unit/ray_tracing.cpp
- tests/unit/ray_tracing_positive.cpp
Adds missing RTX checks for the `accelerationStructure` feature being enabled
> layers: Add accelerationStructure feature check

- tests/framework/ray_tracing_objects.cpp
- tests/framework/ray_tracing_objects.h
- tests/unit/ray_tracing_positive.cpp
Fix handling of ray tracing indirect builds
> tests: Add Positive.CmdBuildAccelerationStructuresIndirect

- layers/core_checks/cc_ray_tracing.cpp
- layers/stateless/sl_ray_tracing.cpp
- tests/unit/ray_tracing.cpp
adds `VUID-vkCmdBuildAccelerationStructuresIndirectKHR-mode-04628` and `VUID-vkBuildAccelerationStructuresKHR-mode-04628`
> layers: Validate VkBuildAccelerationStructureModeKHR

- layers/core_checks/cc_shader_object.cpp
- tests/unit/shader_object.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/7211
> layers: Add spirv-val for shader objects

- layers/core_checks/cc_pipeline_ray_tracing.cpp
- layers/core_checks/cc_ray_tracing.cpp
- layers/core_checks/core_validation.h
call `vkGetDeferredOperationResultKHR` to see if  `VkDeferredOperationKHR` is completed
> layers: Add VkDeferredOperationKHR complete check

- layers/object_tracker/object_tracker_utils.cpp
- tests/CMakeLists.txt
- tests/framework/layer_validation_tests.h
- tests/unit/debug_extensions.cpp
- tests/unit/debug_extensions_positive.cpp
- tests/unit/tooling.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/7241
> layers: Fix SetDebugUtils setting its own VkDevice

- layers/core_checks/cc_external_object.cpp
- layers/state_tracker/fence_state.cpp
- layers/state_tracker/fence_state.h
- layers/state_tracker/semaphore_state.cpp
- layers/state_tracker/semaphore_state.h
- tests/unit/external_memory_sync.cpp
- tests/unit/external_memory_sync_positive.cpp
Part of https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/6876
> layers: Add external sync VUs 01128 01450

- layers/vulkan/generated/chassis.cpp
- layers/vulkan/generated/chassis.h
- layers/vulkan/generated/chassis_dispatch_helper.h
- scripts/generators/layer_chassis_generator.py
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/3706
> layers: Fix vkGetPhysicalDeviceToolProperties

- layers/core_checks/cc_external_object.cpp
- tests/unit/external_memory_sync.cpp
Adds `VUID-VkSemaphoreGetFdInfoKHR-semaphore-01133` and `VUID-VkFenceGetFdInfoKHR-fence-01455`
> layers: Add exportFromImportedHandleTypes for SyncFD

- layers/core_checks/cc_ray_tracing.cpp
- tests/unit/ray_tracing_pipeline.cpp
adds `VUID-vkGetRayTracingShaderGroupHandlesKHR-pipeline-04619` and `VUID-vkGetRayTracingCaptureReplayShaderGroupHandlesKHR-pipeline-04620`
> layers: Add Raytracing Pipeline check

- layers/core_checks/cc_device_memory.cpp
Part of https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/6876
This does not contain any test. For testing this requires exporting handle outside of Vulkan API. In practice this would be DX11/DX12 resource. It's possible in theory but requires support for DX initialization within test framework.
Comparing to similar VU for Fd from stateless validation, this one should be in the core validation because we need state that tracks handles created inside Vulkan API (`GetOpaqueInfoFromWin32Handle`)
> layers: Add external memory VU 00645

- layers/core_checks/cc_pipeline_graphics.cpp
- tests/unit/graphics_library.cpp
Adds `VUID-VkGraphicsPipelineCreateInfo-flags-06682` and `VUID-VkGraphicsPipelineCreateInfo-flags-06683`
> Add NullLayout check with GPL Flags

- layers/core_checks/cc_device_memory.cpp
- layers/stateless/sl_external_object.cpp
Some misc cleanup of the external handle VUs added recently
> layers: Cleanup with External Handle messages

- layers/error_message/error_location.cpp
- layers/error_message/error_location.h
- layers/gpu_validation/debug_printf.cpp
- layers/gpu_validation/debug_printf.h
- layers/gpu_validation/gpu_record.cpp
- layers/gpu_validation/gpu_state_tracker.cpp
- layers/gpu_validation/gpu_state_tracker.h
- layers/gpu_validation/gpu_subclasses.cpp
- layers/gpu_validation/gpu_subclasses.h
- layers/gpu_validation/gpu_validation.cpp
- layers/gpu_validation/gpu_validation.h
- layers/state_tracker/queue_state.cpp
- layers/state_tracker/queue_state.h
- layers/state_tracker/state_tracker.cpp
- layers/state_tracker/state_tracker.h
This change is causing instability in internal CI.
This reverts commit bfaa879ee26d14c359a25aaa0787dfed876adaa5.
> gpu: Revert "Don't wait for idle after every submit"

- layers/core_checks/cc_pipeline_graphics.cpp
- tests/unit/graphics_library.cpp
- tests/unit/graphics_library_positive.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/7282
> layers: Add check for GPL linking layout

- layers/core_checks/cc_drawdispatch.cpp
Improves error message for dynamic version, seems to had been slightly copied-and-pasted from non-dynamic pipeline version
> layers: Fix 09462 error message

- layers/core_checks/cc_cmd_buffer_dynamic.cpp
- layers/core_checks/cc_shader_interface.cpp
- layers/drawdispatch/descriptor_validator.cpp
@artem-lunarg pointed out some of these areas are not fast to review, so tried to clean things up a bit
> layers: Cleanup on shader interface variables

- layers/core_checks/cc_cmd_buffer_dynamic.cpp
- layers/state_tracker/cmd_buffer_state.cpp
- tests/unit/dynamic_rendering_positive.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/7261
> layers: Fix dynamic rendering crash

- BUILD.gn
@charles-lunarg please take a look! FYI @lokokung as next gardener
> Fix GN build after introduction of vk_dispatch_table_helper.cpp

- tests/unit/instanceless.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/7294
Confirm we do produce an error at `vkCreateInstance` time when nested dependency is not enabled
> tests: Add test for WSI extension check

- layers/error_message/unimplementable_validation.h
- layers/stateless/sl_descriptor.cpp
- layers/stateless/sl_pipeline.cpp
- layers/stateless/stateless_validation.h
- layers/vulkan/generated/stateless_validation_helper.cpp
- layers/vulkan/generated/stateless_validation_helper.h
- scripts/generators/stateless_validation_helper_generator.py
- tests/unit/descriptor_buffer.cpp
- tests/unit/image.cpp
- tests/unit/instanceless.cpp
- tests/unit/wsi.cpp
Some implicit VUs were just missing the correct VUID label, some were missing, this does a nice cleanup, there is still a few more left to do after
> Add and fix labels for implicit VUs

- tests/unit/gpu_av_descriptor_indexing.cpp
This test case is huge and hard to debug, so split it into a bunch of smaller tests.
> tests: Split up ArrayOOBGraphics

- layers/best_practices/bp_render_pass.cpp
- tests/unit/best_practices_positive.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/7316
> bp: Don't reset every vkCmdPushConstants

- layers/error_message/unimplementable_validation.h
- layers/object_tracker/object_tracker_utils.cpp
- layers/stateless/sl_utils.cpp
- layers/stateless/stateless_validation.h
- layers/vulkan/generated/stateless_validation_helper.cpp
- scripts/generators/stateless_validation_helper_generator.py
- tests/unit/command.cpp
- tests/unit/descriptors.cpp
- tests/unit/dynamic_state.cpp
- tests/unit/memory.cpp
- tests/unit/others.cpp
- tests/unit/render_pass.cpp
- tests/unit/sync_object.cpp
- tests/unit/wsi.cpp
Various fixes from adding VUID labels to adding missing VUs that were missing
> Fix more implicit VUID labeling

- tests/unit/gpu_av_descriptor_indexing.cpp
- tests/unit/gpu_av_oob.cpp
- tests/unit/gpu_av_oob_positive.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/6980
unify test, broke up large tests, and moved positive tests to correct file
> tests: Cleanup GPU-AV tests

- layers/core_checks/cc_image.cpp
- tests/unit/ycbcr.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/4951
> layers: Add 04714 04715

- layers/core_checks/cc_device_memory.cpp
Add the required `VkPhysicalDeviceImageDrmFormatModifierInfoEXT` extension structure to the `VkPhysicalDeviceImageFormatInfo2` `pNext` chain when calling `vkGetPhysicalDeviceImageFormatProperties2` with tiling set to `VK_IMAGE_TILING_DRM_FORMAT_MODIFIER_EXT`.
> layers: Fix HasExternalMemoryImportSupport with DRM modifiers

- layers/stateless/sl_pipeline.cpp
- layers/stateless/stateless_validation.h
- layers/vulkan/generated/stateless_validation_helper.cpp
- scripts/generators/stateless_validation_helper_generator.py
- tests/unit/pipeline.cpp
adds `vkGetPipelinePropertiesEXT` VUs
> layers: Add vkGetPipelinePropertiesEXT

- layers/vulkan/generated/stateless_validation_helper.cpp
- scripts/generators/stateless_validation_helper_generator.py
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/7350
this is a quick fix, going to look more into fixing the root cause after
> scripts: Workaround for 7350

- layers/stateless/sl_ray_tracing.cpp
- tests/framework/ray_tracing_objects.cpp
- tests/framework/ray_tracing_objects.h
- tests/unit/ray_tracing.cpp
Follow up to https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/7226
> layers: Add 03750 03787

- layers/core_checks/cc_ray_tracing.cpp
- tests/unit/ray_tracing.cpp
**VUID-vkCmdCopyAccelerationStructureToMemoryKHR-pInfo-03739**
pInfo->dst.deviceAddress must be a valid device address for a buffer bound to device memory
**VUID-vkCmdCopyAccelerationStructureToMemoryKHR-pInfo-03741**
If the buffer pointed to by pInfo->dst.deviceAddress is non-sparse then it must be bound completely and contiguously to a single [VkDeviceMemory](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkDeviceMemory.html) object
> layers: Add 03739 03741

- layers/core_checks/cc_buffer.cpp
- layers/core_checks/cc_copy_blit_resolve.cpp
- layers/core_checks/cc_descriptor.cpp
- layers/core_checks/cc_device_memory.cpp
- layers/core_checks/cc_image.cpp
- layers/core_checks/cc_image_layout.cpp
- layers/core_checks/cc_queue.cpp
- layers/core_checks/cc_spirv.cpp
- layers/core_checks/cc_synchronization.cpp
- layers/core_checks/cc_video.cpp
- layers/stateless/sl_ray_tracing.cpp
- layers/stateless/sl_utils.cpp
Noticed by @artem-lunarg in my other PR, went through and fixed all spots not applying onto the `skip` bool
> layers: Fix not appending to skip bool

- layers/core_checks/cc_render_pass.cpp
- layers/core_checks/cc_synchronization.cpp
- layers/core_checks/core_validation.h
- layers/error_message/unimplementable_validation.h
- tests/unit/sync_object.cpp
adds `VUID-vkCmdPipelineBarrier-None-07892`/`VUID-vkCmdPipelineBarrier-None-07893` that were missing
> layers: Add renderpass vkCmdPipelineBarrier VUs

- scripts/generators/base_generator.py
- scripts/generators/stateless_validation_helper_generator.py
follow-up as a more "correct" fix for https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/7350
> scripts: Add struct extension re-lookup in base generator

- tests/unit/ray_tracing.cpp
Attempt at fixing `NegativeRayTracing.TransformBufferInvalid`
> tests: Fix NegativeRT.TransformBufferInvalid

- layers/core_checks/cc_pipeline_graphics.cpp
- layers/state_tracker/pipeline_state.h
- tests/unit/graphics_library.cpp
- tests/unit/graphics_library_positive.cpp
There is a [spec issue](https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/6408) to clarify which VUs are which, but this adds the logic and is conservative (no false positives) so if the spec issue it will be an easy update
> layers: Add GPL MultisampleState VUs

- tests/unit/ray_tracing.cpp
Closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/7330
> tests: Fix scratch management in some RT tests

- layers/stateless/sl_pipeline.cpp
- tests/unit/dynamic_rendering.cpp
Adds new 1.3.276 VU
VUID-VkPipelineRenderingCreateInfo-colorAttachmentCount-09533
> layers: Add maxColorAttchments VU

- layers/core_checks/cc_descriptor.cpp
- tests/unit/descriptor_buffer.cpp
- tests/unit/sampler.cpp
Add new VUs from 276 spec related to `nullDescriptor`
- VUID-VkWriteDescriptorSet-descriptorType-09506
- VUID-vkGetDescriptorEXT-pDescriptorInfo-09507
> layers: Add Null YCbCr descriptor VUs

- layers/stateless/sl_descriptor.cpp
- tests/unit/query.cpp
Adds ` VUID-VkQueryPoolCreateInfo-queryType-09534` (added in 1.3.276 spec)
> layers: Add pipelineStatistics zero VU

- layers/stateless/sl_ray_tracing.cpp
- tests/unit/ray_tracing.cpp
**VUID-vkGetAccelerationStructureBuildSizesKHR-pBuildInfo-03785**
If pBuildInfo->pGeometries or pBuildInfo->ppGeometries has a geometryType of VK_GEOMETRY_TYPE_INSTANCES_KHR, each pMaxPrimitiveCounts[i] must be less than or equal to [VkPhysicalDeviceAccelerationStructurePropertiesKHR](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkPhysicalDeviceAccelerationStructurePropertiesKHR.html)::maxInstanceCount
> layers: Add 03785

- layers/core_checks/cc_render_pass.cpp
- tests/unit/fragment_shading_rate.cpp
add `VUID-VkRenderPassCreateInfo2-pAttachments-09387`
> layers: Add fragment shading rate VU

- layers/core_checks/cc_pipeline_graphics.cpp
- tests/unit/graphics_library.cpp
Add VUs checking for `VkPipelineFragmentShadingRateStateCreateInfoKHR` in GPL
- VUID-VkGraphicsPipelineCreateInfo-flags-06638
- VUID-VkGraphicsPipelineCreateInfo-flags-06639
> layers: Add GPL VkPipelineFragmentShadingRateStateCreateInfo

- layers/core_checks/cc_render_pass.cpp
- layers/stateless/sl_descriptor.cpp
- layers/stateless/sl_image.cpp
- tests/unit/descriptor_buffer.cpp
- tests/unit/image.cpp
- tests/unit/imageless_framebuffer.cpp
Adds new VUs from 1.3.276
- VUID-VkDescriptorAddressInfoEXT-None-09508
- VUID-VkFramebufferAttachmentImageInfo-viewFormatCount-09536
- VUID-VkImageFormatListCreateInfo-viewFormatCount-09540
> layers: Add VK_FORMAT_UNDEFINED check

- layers/best_practices/bp_pipeline.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/7394
> bp: Improve SpirvDeprecated WorkgroupSize message

- layers/core_checks/cc_drawdispatch.cpp
- tests/unit/ray_tracing.cpp
VUID-vkCmdTraceRaysKHR-flags-03511
If the currently bound ray tracing pipeline was created with flags that included VK_PIPELINE_CREATE_RAY_TRACING_NO_NULL_MISS_SHADERS_BIT_KHR, the shader group handle identified by pMissShaderBindingTable->deviceAddress must not be set to zero
> layers: Add 03511

- layers/sync/sync_access_state.cpp
- layers/sync/sync_access_state.h
- tests/unit/sync_val.cpp
Closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/7353
> sync: Fix issue 7353

- layers/sync/sync_utils.cpp
- tests/unit/sync_val.cpp
Closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/7349
> sync: Fix SHADER_READ expansion

- layers/sync/sync_utils.cpp
- layers/vulkan/generated/sync_validation_types.h
- scripts/generators/sync_validation_generator.py
Follow-up to https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/7410
> scripts: Generate expansion for shader read/write

- layers/VkLayer_khronos_validation.json.in
This PR changes the Synchronization Preset from:
To:
> layer: Updated synchronization preset

- layers/core_checks/cc_spirv.cpp
- layers/gpu_validation/spirv/bindless_descriptor_pass.cpp
- layers/gpu_validation/spirv/function_basic_block.cpp
- layers/gpu_validation/spirv/function_basic_block.h
- layers/gpu_validation/spirv/instruction.cpp
- layers/gpu_validation/spirv/pass.cpp
- layers/gpu_validation/spirv/pass.h
- layers/vulkan/generated/spirv_grammar_helper.cpp
- layers/vulkan/generated/spirv_grammar_helper.h
- scripts/generators/spirv_grammar_generator.py
- tests/spirv/validate_instrumentation.py
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/7402
The issue was simply missing the `Label` operand for `OpSwitch`
> gpuav: Fix shader instrumentation on switch cases

- layers/core_checks/cc_pipeline_graphics.cpp
- tests/unit/graphics_library.cpp
`UNASSIGNED-VkGraphicsPipelineCreateInfo-MultisampleState` to `VUID-VkGraphicsPipelineCreateInfo-pLibraries-09567`
> layers: Label new VUID from 277 headers

- layers/gpu_validation/gpu_validation.cpp
- tests/unit/gpu_av_positive.cpp
Closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/7434
Do not store empty `CommandResources`, they do not need to be processed anyway
Before https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/7183, null `CommandResources` would only be created when an error was encountered. Now, thanks to this line, a null `CommandResources` can be created when there is no need to perform validation:
```cpp
// Only need to perform validation for depth image having a depth format that is not unsigned normalized.
// For unsigned normalized formats, depth is by definition in range [0, 1]
if (!IsValueIn(image_state->safe_create_info.format, {VK_FORMAT_D32_SFLOAT, VK_FORMAT_D32_SFLOAT_S8_UINT})) {
return nullptr;
}
```
Null `CommandResources` are now just not stored, no need to
> gpu: Fix null CommandResources mangaement

- .github/workflows/weekly-tag.yml
- README.md
> github: Add a workflow to generate weekly tags

- layers/core_checks/cc_pipeline_graphics.cpp
- layers/state_tracker/pipeline_state.h
- tests/unit/graphics_library.cpp
- tests/unit/graphics_library_positive.cpp
As per discussion in https://gitlab.khronos.org/vulkan/vulkan/-/issues/3764#note_451564 the understanding of GPL was wrong
> layers: Fix how checking for required pipeline state

- layers/core_checks/cc_ray_tracing.cpp
- tests/unit/ray_tracing.cpp
Validate that acceleration structures are built
> layers: Add 04964 04963

- layers/vulkan/generated/spirv_grammar_helper.cpp
- layers/vulkan/generated/spirv_grammar_helper.h
- layers/vulkan/generated/spirv_tools_commit_id.h
- scripts/known_good.json
We'd like to start updating these on a more regular cadence and this is a trial run to see how it goes.
> build: Update SPIRV-Headers and -Tools

- layers/vulkan/generated/vk_safe_struct_core.cpp
- layers/vulkan/generated/vk_safe_struct_ext.cpp
- layers/vulkan/generated/vk_safe_struct_khr.cpp
- layers/vulkan/generated/vk_safe_struct_vendor.cpp
- scripts/generators/safe_struct_generator.py
Fix string formatting in the script file to make updating easier
> scripts: Use string blocks for safe struct

- layers/core_checks/cc_device_memory.cpp
- layers/core_checks/cc_ray_tracing.cpp
- layers/core_checks/core_validation.h
- layers/error_message/logging.h
- tests/unit/ray_tracing.cpp
> layers: Add 07791

- layers/gpu_validation/spirv/module.cpp
- layers/gpu_validation/spirv/module.h
- layers/gpu_validation/spirv/pass.cpp
- layers/gpu_validation/spirv/pass.h
- tests/CMakeLists.txt
- tests/framework/layer_validation_tests.h
- tests/spirv/validate_instrumentation.py
- tests/unit/gpu_av_buffer_device_address.cpp
- tests/unit/gpu_av_buffer_device_address_positive.cpp
- tests/unit/gpu_av_spirv_positive.cpp
Various fixes applied as well as more tests
> More Fixes for GPU-AV Shader Instrumentation

- layers/VkLayer_khronos_validation.json.in
- layers/gpu_validation/gpu_settings.h
- layers/gpu_validation/gpu_setup.cpp
- layers/gpu_validation/gpu_validation.cpp
- layers/gpu_validation/gpu_validation.h
- layers/layer_options.cpp
- layers/vulkan/generated/chassis.cpp
- scripts/generators/layer_chassis_generator.py
> layers: Move GPU debugging variables to layer settings
