KhronosGroup/Vulkan-ValidationLayers

- layers/gpu_validation.cpp
Fixes the case where descriptor sets are not contiguous
> Fix GPU-AV pre draw save/restore

- build-android/known_good.json
- layers/generated/spirv_grammar_helper.cpp
- layers/generated/spirv_tools_commit_id.h
- layers/generated/spirv_validation_helper.cpp
- scripts/known_good.json
- scripts/spirv_validation_generator.py
https://github.com/KhronosGroup/SPIRV-Headers/pull/288
https://github.com/KhronosGroup/SPIRV-Tools/pull/4915
Reenable spv::CapabilityMeshShadingEXT in spirv_validation_generator.py
Fixes #4515
> build: Update SPIRV-Headers and -Tools for SPV_EXT_mesh_shader

- tests/vktestbinding.cpp
Saw that while working on another PR.
The way all extensions/layers are queried is not really what you are supposed to do. And `GetGlobalExtensions` was not using its `pLayerName` parameter.
> tests: fix how global list of extensions/layers is obtained

- layers/best_practices_utils.cpp
- tests/vklayertests_nvidia_best_practices.cpp
Was looking to use ForEachSubresource and saw something weird.
the function would crash when using VK_REMAINING_ARRAY_LAYERS and baseArrayLayer > 0  or VK_REMAINING_MIP_LEVELS and baseMipLevel > 0.
Fix to correctly calculate layerCount/levelCount with REMAINING values.
Modify test to use layer index 1 to test this new behavior.
> Fix ForEachSubresource

- layers/buffer_state.h
- layers/descriptor_validation.cpp
- layers/state_tracker.cpp
- tests/vklayertests_pipeline_shader.cpp
These 2 VUIDs were recently updated and made more clear that `bufferFeatures` needs to be checked.
> layers: Fix checking buffer view format support

- layers/best_practices_utils.cpp
- tests/vklayertests_best_practices.cpp
STORE_OP_NONE was counting as discarded and triggering the warning although the contents way not be undefined
Closes #4533
> Fix StoreOpDontCareThenLoadOpLoad

- layers/core_validation.cpp
- layers/core_validation.h
- layers/core_validation_error_enums.h
- tests/vklayertests_descriptor_renderpass_framebuffer.cpp
Add check for not binding all input attachments that are used in a subpass.
Also adds a check for when an input attachment descriptor image view isn't used as input attachment in current subpass/framebuffer. Is this already a VUID ? I can't find it anywhere, and seems like it should be.
Closes #4494
> Add check for VUID-vkCmdDraw-None-02686

- layers/best_practices_error_enums.h
- layers/best_practices_utils.cpp
- layers/best_practices_validation.h
- tests/vklayertests_best_practices.cpp
Keeps the last used queue family with usage per subresource for images
Whenever a new usage appears on queue on a different queue family, check if it is a read operation because it will be undefined
Check for an image pipeline barrier defining an ownership acquisition operation and change the queue family index
Only for images for now, buffers later
Closes #2412
> Implement check for ownership transfer

- layers/core_validation.cpp
Check was using framebuffer state to check attachment image views which was causing a crash in CTS, because imageless framebuffers have no image views.
> Use correct attachment storage for imageless

- BUILD.gn
- CMakeLists.txt
- build-android/jni/Android.mk
- build-gn/secondary/build_overrides/vulkan_validation_layers.gni
- layers/core_validation.h
- layers/generated/vk_format_utils.cpp
- layers/generated/vk_format_utils.h
- layers/shader_validation.cpp
- scripts/format_utils_generator.py
- tests/CMakeLists.txt
- tests/positive/shaderval.cpp
- tests/vklayertests_pipeline_shader.cpp
Adds new `VUID-RuntimeSpirv-OpImageWrite-07112` support
This only validates of the `OpImageType` format is not `Unknown`, if it is then `VUID-vkCmdDispatch-None-04115` and `VUID-vkCmdDispatch-OpImageWrite-04469` are used... I was going to add these 2 as well in here, but some other refactoring was needed and bloated this PR
New `CompatibleSpirvImageFormat` generated to map the table in the Spec which SPIR-V image formats go with which `VkFormat`
> Add OpImageWrite component count check

- layers/buffer_validation.cpp
- layers/core_validation.cpp
- layers/state_tracker.cpp
- tests/positive/pipeline.cpp
- tests/vklayertests_buffer_image_memory_sampler.cpp
- tests/vklayertests_wsi.cpp
- tests/vkrenderframework.cpp
Fixes for issue https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/4274
This PR aims at fixing checks for 2 VUIDs:
`VUID-VkSwapchainCreateInfoKHR-physicalDeviceCount-01429`:
> If the logical device was created with VkDeviceGroupDeviceCreateInfo::physicalDeviceCount equal to 1, flags must not contain VK_SWAPCHAIN_CREATE_SPLIT_INSTANCE_BIND_REGIONS_BIT_KHR
`VUID-VkSwapchainCreateInfoKHR-flags-03187`:
> If flags contains VK_SWAPCHAIN_CREATE_PROTECTED_BIT_KHR, then VkSurfaceProtectedCapabilitiesKHR::supportsProtected must be VK_TRUE in the VkSurfaceProtectedCapabilitiesKHR structure returned by vkGetPhysicalDeviceSurfaceCapabilities2KHR for surface
The root issue is how `device_group_create_info`, a member variable that was only correctly initialised when a …
> Fixes for swapchain flags VUIDs

- layers/generated/thread_safety.h
- scripts/thread_safety_generator.py
Use std::this_thread::get_id(), rather than pthread_self() as get_id() usually maps to a system wide thread id rather than a pthread_t pointer.
Fixes #4552
> threading: Use a better thread id

- layers/cmd_buffer_state.cpp
- layers/cmd_buffer_state.h
- layers/core_validation.cpp
- tests/positive/dynamic_rendering.cpp
The spec says to check for the current render pass instance,
but code was checking if there were any draw calls at all in the command
buffer.
> layers: Fix check for dynamic rendering attachment format use

- layers/buffer_validation.cpp
- layers/core_validation.cpp
- tests/positive/render_pass.cpp
Layer count 1 is allowed for the fragment shading rate attachment according to the VUID
> Fix fragment shading rate attachment with multiview

- layers/shader_module.cpp
- tests/positive/shaderval.cpp
- tests/vklayertests_pipeline_shader.cpp
The 1.3.228 Vulkan Spec added a new clarification that `OpTypeBool` are the same size as 32-bit int for calculating the limits, prior they were being counted as `0` bytes
https://github.com/KhronosGroup/Vulkan-Docs/commit/355367640f2eabd2a0d492010a0afc166696aa72#diff-d753f04f744ff6c91e6b57979b21d920c15f1b59f955cff57d7cc942a0f96e6dR484-R485
> layers: Calculate OpTypeBool as 32-bit ints for limits

- layers/core_validation.cpp
- tests/vklayertests_dynamic_rendering.cpp
Changed dynamic rendering messages to stop using the VkRenderPass object as it is always VK_NULL_HANDLE
Closes #4543
> Add checks for 06774 and 06775

- layers/core_validation.cpp
Since it is not technically illegal to not bind as many sets as set by the pipeline layout, need to check that we are not reading more
> Add check to avoid crash in CTS

- layers/cmd_buffer_state.cpp
- layers/cmd_buffer_state.h
- layers/core_validation.cpp
- layers/core_validation.h
- layers/queue_state.cpp
- tests/vklayertests_others.cpp
There were deadlocks and race conditions when running the callbacks in CMD_BUFFER_STATE::queryUpdates. This was because secondary command buffer callbacks were copied into the primary's callback list. Then the callbacks were all called with the primary buffer's lock locked, but not the secondary. Instead, make a callback that loops through the secondary's callbacks in place rather than copying. Then the callback can safely lock the secondary.
Hopefully this is only an interim fix and we can find a better way to implement this without callback lambda voodoo.
Fixes #4243
This PR also un-deletes and updates the tests, and fixes another problem with how perf passes were tracked (see individual commit messages).
>  layers: Fix CB locking during query callback functions

- layers/best_practices_utils.cpp
- layers/best_practices_validation.h
- layers/cmd_buffer_state.cpp
- layers/cmd_buffer_state.h
Remove validated_descriptor_sets as it was only used in one place and was not cleared correctly, causing a crash.
Replaced usage with lastBound[].per_set
> Remove validated_descriptor_sets

- layers/generated/vk_safe_struct.cpp
- scripts/helper_file_generator.py
- tests/positive/pipeline.cpp
Several tests in the dEQP-VK.transform_feedback.* group are passing a valid pMultisampleState pointer when creating pipelines with rasterization disabled, and the layers are still generating VUID-VkGraphicsPipelineCreateInfo-renderpass-06631.
The VUID requires multisample state to be passed if the pipeline contains fragment shader state and a non-NULL render pass, but the layers do not save the provided multisample state info due to rasterization being disabled and later emit the validation error incorrectly.
This commit makes the layers save the multisample state if a render pass is provided.
> layers: Save multisample state if render pass is not null

- tests/vklayertests_buffer_image_memory_sampler.cpp
Part fix for #4587 
for `VkLayerTest.DeviceCoherentMemoryDisabledAMD` this seems like the device is exposing `VK_AMD_device_coherent_memory` and `deviceCoherentMemory` feature without `VK_MEMORY_PROPERTY_DEVICE_COHERENT_BIT_AMD` or `VK_MEMORY_PROPERTY_DEVICE_UNCACHED_BIT_AMD` which makes the extension useless, but also broke the assumption the test had
> tests: Fix DeviceCoherentMemoryDisabledAMD

- layers/range_vector.h
- layers/synchronization_validation.cpp
- layers/synchronization_validation.h
- tests/vksyncvaltests.cpp
Reorganize access log storage s.t. unreferenced command buffer access logs can be discared.
Needed
* detailed review of the BatchLog trimming algorithm
* detailed review of sparse_container::consolidate  (which seemed way simpler than I had thought it would be)
> Reduce long term memory use growth for SyncVal with submit time validation enabled

- layers/core_validation.cpp
Several CTS test in the dEQP-VK.transform_feedback.* group were incorrectly reporting VUID-vkCmdEndQueryIndexedEXT-queryType-06696. The cause is some of these tests using two query pools and the layers not verifying the query pool being checked matched the expected one.
> layers: Fix spurious VUID-vkCmdEndQueryIndexedEXT-queryType-06696

- layers/best_practices_utils.cpp
Fixes crash in dEQP-VK.pipeline.pipeline_library.stencil.format.s8_uint.states.fail_keep.pass_keep.dfail_incc.comp_never and other pipeline_library tests.  Core validation indicates that the test is conformant.
> Fix Best Practices crash with no rasterization state

- layers/shader_validation.cpp
In CoreChecks::ValidatePipelineShaderStage, the SPIR-V optimizer is run followed by validation of the optimized shader.  However, the SPIR-V optimizer itself is also validating the optimized SPIR-V.
This change disables the validation done by the optimizer, and lets it be done by CoreChecks::ValidatePipelineShaderStage.
As a result, pipeline-creation-heavy tests in ANGLE see ~10% speed up.
> layers: Don't auto-validate SPIR-V after optimization

- layers/core_validation.cpp
- layers/gpu_utils.cpp
- layers/image_state.cpp
- layers/image_state.h
- layers/queue_state.cpp
- layers/queue_state.h
- layers/state_tracker.cpp
- layers/state_tracker.h
- layers/vk_layer_data.h
- tests/layer_validation_tests.cpp
- tests/positive/image_buffer.cpp
- tests/positive/sync.cpp
- tests/vklayertests_others.cpp
Rewrite QUEUE_STATE to use a worker thread to update state. This was necessary to fix a race condtion if multiple threads wait on the same timeline semaphore.
Thread 1:
vkWaitSemaphores() : wait on semaphore for value N
Thread 2:
vkQueueSubmit()    : signal semaphore for value N
vkWaitSemaphores() : wait on semaphore for value N
Thread 1 starts waiting before we have any information about which queues(s) will need to make progress before value N will be complete. In the old implementation, that might cause it to not correctly update the queue(s) state after it woke up. That would then lead to false 'object in use' errors. In theory, it might have been possible to fix this problem, but the logic was already confusing. Also, this opens up the possiblity of moving execute time validation and …
> layers: Use a thread for QUEUE_STATE submission processing

- .github/workflows/build_macos.yml
- CMakeLists.txt
- README.md
- scripts/update_deps.py
- Add MacOS to CI build status
- Use CMake idioms
- Fix invalid CMake warning, CMAKE_GENERATOR_PLATFORM only makes sense for VS builds in the context of update_deps.py
> build: Minor build fixes

- layers/core_validation.h
- layers/descriptor_validation.cpp
- layers/drawdispatch.cpp
- tests/vklayertests_pipeline_shader.cpp
`VUID-vkCmd*-magFilter-04553` was already covered and `VUID-vkCmd*-mipmapMode-04770` is almost the same check so not sure how it was not added before
> Add Linear Mipmap format feature VU

- layers/buffer_validation.cpp
- tests/vklayertests_command.cpp
Fixes #4531 and, at least for the moment, allows the vuid checker script to run cleanly.
Also applies validation formerly reserved for compressed images to all images
Blocked image definition was removed:
https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/5370
> Fix layers and tests to use new copy VUIDs

- layers/buffer_validation.cpp
- tests/positive/render_pass.cpp
- tests/positive/shaderval.cpp
- tests/vklayertests_buffer_image_memory_sampler.cpp
- tests/vklayertests_descriptor_renderpass_framebuffer.cpp
I had the positive test as `VkLayerTest`
also found some white space my editor noticed that figured could go well with this nit cleanup PR
> tests: Fix test group and whitespace

- CMakeLists.txt
- tests/CMakeLists.txt
CMake will now discover the tests inside vk_layer_validation_tests: https://cmake.org/cmake/help/latest/module/GoogleTest.html
This makes running ctest much more useful for users. Since it will report all of the tests appropriately. Instead of running 1 giant test.
Plus minor CMake cleanup
> build: Use GoogleTest CMake Module

- layers/shader_validation.cpp
The friendly-name-mapper in spirv-val is slow. Disabling it in VVL improves performance of an ANGLE test that creates numerous shaders by ~10%.  The cost of SPIR-V validation itself is reduced by ~40%.
> layers: Disable friendly names in SPIR-V validation

- layers/subresource_adapter.cpp
- layers/subresource_adapter.h
- layers/synchronization_validation.cpp
- layers/synchronization_validation.h
Ensure async hazard checks apply to all accesses since most recent sync point (including indirectly through a semaphore chain).  Previously only checked "last_batch" operations.
> syncval: Rework async hazard check range bounds

- layers/CMakeLists.txt
- layers/layer_options.cpp
- layers/shader_validation.cpp
- layers/vk_layer_logging.h
- layers/vk_xxhash.h
Fixes clang-cl builds by ifdefing out problematic code sections. Minor improvements to source code by avoiding strlen, and using const. Created vk_xxhash.h to define XXH_NO_LONG_LONG instead of defining it in multiple build systems.
closes #4640
> build: xxhash fixes

- layers/core_validation.cpp
VUID-VkGraphicsPipelineCreateInfo-graphicsPipelineLibrary-06607 contains duplicate text.
> layers: Fix typo in error message related to graphics pipeline libraries

- layers/cmd_buffer_state.cpp
- layers/state_tracker.h
- layers/synchronization_validation.cpp
- layers/synchronization_validation.h
Get rid of the core validation command buffer callbacks, and make the only remaining user (syncval) switch to using a derived state object like everyone else.  This is necessary but not sufficient to make syncval support fine grained locking. It does fix some problems with CTS from PR #4328
> syncval: Use subclassed CMD_BUFFER_STATE

- BUILD.gn
- CMakeLists.txt
- build-android/jni/Android.mk
- layers/core_validation.h
- layers/generated/spirv_validation_helper.cpp
- layers/generated/vk_format_utils.cpp
- layers/generated/vk_format_utils.h
- scripts/format_utils_generator.py
- scripts/lvl_genvk.py
- scripts/spirv_validation_generator.py
- tests/CMakeLists.txt
This "reverts" (really moves) `CompatibleSpirvImageFormat` to not be in `vk_format_utils` this would be a replacement for https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/4647 as a "temp fix" until we properly deal with how the format utils folder is being used outside the scope of the VVL 
cc @ncesario-lunarg
> scripts: Move CompatibleSpirvImageFormat

- tests/vklayertests_pipeline_shader.cpp
- tests/vkrenderframework.h
Adds support for Vulkan 1.3 and SPV 1.6 (apparently we did not have any tests relying on any SPV features > 1.5 up to this point).
> tests: Fix glslang target env

- .github/workflows/build_macos.yml
- BUILD.md
- CMakeLists.txt
- This approach matches what our SDK release process does
- CMAKE_MACOS_DEPLOYMENT_TARGET doesn't propagate to dependencies
closes #4614
> ci: Use MACOS_DEPLOYMENT_TARGET

- BUILD.md
- CMakeLists.txt
- scripts/known_good.json
Remove CMake code for
- USE_CCACHE
- CMAKE_EXPORT_COMPILE_COMMANDS
Show in the docs how to enable these features via cli or environment variables.
> cmake: Remove implict ccache/compile_commands.json

- layers/synchronization_validation.cpp
This caused an assert to fire when running CTS in:
dEQP-VK.memory.pipeline_barrier.host_write_uniform_texel_buffer.1024
and similar tests.
> syncval: Fix copy/paste error in PreCallRecordCmdExecuteCommands

- layers/queue_state.cpp
- layers/queue_state.h
Close a race condition in very common code in the test suite that does:
vkQueueSubmit(..., VK_NULL_HANDLE /*fence*/);
vkQueueWaitIdle(...);
While the thread function is processing a CB_SUBMISSION structure, it needs to stay on the deque so that QUEUE_STATE::Wait() can find it.
> layers: Fix a vkQueueSubmit()/vkQueueWaitIdle() race

- CMakeLists.txt
Currently builds break when `-D BUILD_LAYERS=OFF -D BUILD_TESTS=OFF`
Because of vvlgeneratedsourcecode depending on spirv/unified1
> cmake: Fix spirv dependency

- layers/queue_state.cpp
- layers/state_tracker.cpp
- layers/state_tracker.h
- tests/positive/sync.cpp
Try to avoid race conditions by moving queue submit state tracking to PreCallRecord. This makes sure the submit state is set up before any wait calls can possibly complete. Set up wait and signal operations in the PreCallRecord hooks for vkSignalSemaphore() vkWaitSemaphores() as well.
Improve the TimelineSemThreadRace cases to be better at reproducing problems in this part of the code.
> layers: Fix host side timeline semaphore operation handling

- layers/core_validation.cpp
- layers/core_validation.h
- layers/image_state.cpp
- layers/image_state.h
- layers/state_tracker.cpp
- layers/state_tracker.h
- tests/vklayertests_wsi.cpp
Full-screen exclusive access must not be acquired when it is already active.
When releasing full-screen exclusive access swapchain must not be retird and must have been created with VkSurfaceFullScreenExclusiveInfoEXT in the pNext chain with fullScreenExclusive equal to VK_FULL_SCREEN_EXLUSIVE_APPLICATION_CONTROLLED_EXT
> Adding vuid 02676 02677 02678, Validate acquire and release full screen exclusive access

- layers/generated/layer_chassis_dispatch.cpp
- layers/generated/thread_safety.cpp
- layers/generated/thread_safety.h
- scripts/layer_chassis_dispatch_generator.py
- scripts/thread_safety_generator.py
This creates the `display` object so it needs to be added to this list.
> layers: Fix crash when validating GetDrmDisplayEXT

- BUILD.gn
- build-android/cmake/layerlib/CMakeLists.txt
- build-android/jni/Android.mk
- layers/CMakeLists.txt
- layers/best_practices_utils.cpp
- layers/core_validation.h
- layers/debug_printf.cpp
- layers/generated/spirv_grammar_helper.cpp
- layers/generated/spirv_grammar_helper.h
- layers/generated/spirv_validation_helper.cpp
- layers/gpu_utils.cpp
- layers/pipeline_state.cpp
- layers/pipeline_state.h
- layers/shader_instruction.cpp
- layers/shader_instruction.h
- layers/shader_module.cpp
- layers/shader_module.h
- layers/shader_validation.cpp
- layers/state_tracker.cpp
- layers/state_tracker.h
- layers/vk_layer_data.h
- scripts/spirv_grammar_generator.py
- scripts/spirv_validation_generator.py
This adds a new `Instruction` class in favor of the old `spirv_inst_iter` method. 
- **What this provides** 
- Having a capsulated `Instruction`  class makes the code more readable that only a single instruction is being passed around and not a random iterator.
- This makes the code more like `SPIRV-Tools`/`spirv-val`
- Opens up for more refactoring to move Instruction logic (ex. `Instruction::GetStorageClass` or `Instruction::GetBitWidth`) to be added
- Will allow us to finally solve issues such as https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/4355#issuecomment-1266428301
- **What is not done**
- I didn't remove `spirv_inst_iter` completely because both GPU-AV and debug-printf make use of the iterator more and wanted to test it separately as it might include more …
> layers: SPIR-V Instruction class

- layers/best_practices_utils.cpp
- layers/core_validation.cpp
- layers/drawdispatch.cpp
- layers/parameter_validation_utils.cpp
- layers/synchronization_validation.cpp
- layers/vk_layer_utils.h
Found a place not using `GetIndexAlignment` and went through and updated everyone to use it (and added `VK_INDEX_TYPE_NONE_KHR` support)
Changed from `VkDeviceSize` to `uint32_t` as only one location actually needed `VkDeviceSize` directly
> layers: Use GetIndexAlignment everywhere

- layers/shader_validation.cpp
We added this re-run in https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/4420 but now with the changes from `spirv-opt` pulled in (https://github.com/KhronosGroup/SPIRV-Tools/pull/4932) there is no need to re-run `spirv-opt`
Note: Some operations are still not supported in the `spirv-opt` pass ([CompositeInsert](https://github.com/KhronosGroup/SPIRV-Tools/pull/4943), non-32 bit ints, and 16 bit floats) but I am actively working on adding support. By "not supported" I mean it will remain as a `OpSpecConstantOp` and not get turned into the desirable `OpConstant`
> layers: Remove temp fix for re-running spirv-opt

- layers/cmd_buffer_state.h
- layers/core_validation.cpp
- layers/core_validation.h
- layers/drawdispatch.cpp
- layers/state_tracker.cpp
- layers/synchronization_validation.cpp
- tests/vklayertests_command.cpp
Labels `VUID-vkCmdDraw*-None-07312` ([recently added](https://github.com/KhronosGroup/Vulkan-Docs/pull/1945)) as well as moves away from using `CBSTATUS_INDEX_BUFFER_BOUND` and using the already dedicated binding struct we have
(cc @pdaniell-nv - I plan to still do more generating after, but this might be useful for your change as you can safely remove `CBSTATUS_INDEX_BUFFER_BOUND` after this change)
> layers: Move index buffer out of CBStatus

- layers/descriptor_sets.cpp
Minor bugfix for descriptor sets. 
I'm using `VkAccelerationStructureKHR` in my game-engine together with `VkCopyDescriptorSet`. Basically validation layer loses track of `is_khr_`, after copy, and then things start to fall apart causing false validation messages.
```
vkCmdDrawIndexed time: Descriptor in binding #5 index 0 is using acceleration structure VkAccelerationStructureNV 0x0[] that is invalid or has been destroyed.
```
> Fix state tracking of VkCopyDescriptorSet for KHR-acceleration-structure case

- layers/core_validation.cpp
- tests/vklayertests_command.cpp
Add `VUID-vkCmdBeginTransformFeedbackEXT-None-06233` which a few TransformFeedback tests were violating and causing some tests to crash with the undefined behavior
Should also fix the following from https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/4425
- VkLayerTest.TransformFeedbackCmdBindTransformFeedbackBuffersEXT
- VkLayerTest.TransformFeedbackCmdBeginTransformFeedbackEXT
- VkLayerTest.TransformFeedbackCmdEndTransformFeedbackEXT
> Check TransformFeedback bound pipeline

- layers/layer_options.cpp
- tests/vklayertests_others.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/4490
Locally ran the test constantly and haven't seen the issue anymore
> tests: Clear custom_stype_info before use

- tests/positive/command.cpp
- tests/positive/image_buffer.cpp
- tests/positive/other.cpp
- tests/positive/pipeline.cpp
- tests/positive/render_pass.cpp
- tests/positive/sync.cpp
- tests/vklayertests_amd_best_practices.cpp
- tests/vklayertests_descriptor_renderpass_framebuffer.cpp
- tests/vklayertests_wsi.cpp
- tests/vkrenderframework.h
A UINT64_MAX timeout is about 585 years. We want tests to complete before then, even if everything has gone wrong.
> tests: Don't wait for all the nanoseconds

- tests/layer_validation_tests.cpp
- tests/positive/command.cpp
- tests/positive/image_buffer.cpp
- tests/positive/pipeline.cpp
- tests/positive/render_pass.cpp
- tests/vklayertests_arm_best_practices.cpp
- tests/vklayertests_buffer_image_memory_sampler.cpp
- tests/vklayertests_command.cpp
- tests/vklayertests_descriptor_renderpass_framebuffer.cpp
- tests/vklayertests_dynamic_rendering.cpp
- tests/vklayertests_imageless_framebuffer.cpp
- tests/vklayertests_pipeline_shader.cpp
- tests/vklayertests_portability_subset.cpp
- tests/vksyncvaltests.cpp
Reduces unnecessary checks in test code. Also, there were many spots that were not already checking for `FindSupportedDepthOnlyFormat` or `FindSupportedDepthStencilFormat` currently anyway
> tests: Clean up checking for depth stencil format

- layers/gpu_validation.cpp
- layers/gpu_validation.h
Improves GPU-AV performance and memory use running apps with large descriptor sets
> Move GPU-AV input buffer allocation and initialization to CmdBindDescriptorSets

- tests/vklayertests_viewport_inheritance.cpp
Currently the ViewportInheritanceTestData constructor tries to catch and re-throw an exception.
However, none of the functions throws an exception.
> tests: Remove pointless try/catch

- layers/shader_instruction.cpp
- layers/shader_instruction.h
- layers/shader_module.cpp
- layers/shader_module.h
- layers/shader_validation.cpp
Moves both `Describe()` and `GetConstantValue` into the new `Instruction` class
These are pretty low hanging fruit that give a nice little readability boost
> layers: Move some utils into Instruction

- layers/parameter_validation_utils.cpp
- layers/stateless_validation.h
- tests/vklayertests_others.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/4680
adds `VUID-vkSetDebugUtilsObjectNameEXT-pNameInfo-02587` and `VUID-vkSetDebugUtilsObjectNameEXT-pNameInfo-02588`
cleans up `DebugUtilsNameTest` test to match new coding standard for test
> layers: Fix vkSetDebugUtilsObjectNameEXT VUID label

- layers/best_practices_utils.cpp
- layers/buffer_validation.cpp
- layers/cmd_buffer_state.cpp
- layers/core_validation.cpp
- layers/core_validation.h
- layers/debug_printf.cpp
- layers/debug_printf.h
- layers/gpu_utils.cpp
- layers/gpu_validation.cpp
- layers/gpu_validation.h
- layers/layer_options.cpp
- layers/object_tracker_utils.cpp
- layers/parameter_validation_utils.cpp
- layers/pipeline_layout_state.cpp
- layers/pipeline_state.cpp
- layers/pipeline_state.h
- layers/queue_state.cpp
- layers/queue_state.h
- layers/shader_module.cpp
- layers/shader_validation.cpp
- layers/stateless_validation.h
- layers/synchronization_validation.cpp
- layers/vk_layer_config.cpp
- layers/vk_layer_config.h
- tests/layer_validation_tests.cpp
- tests/layer_validation_tests.h
- tests/vklayertests_buffer_image_memory_sampler.cpp
- tests/vkrenderframework.cpp
- tests/vkrenderframework.h
- tests/vksyncvaltests.cpp
Various clang-tidy performance fixes:
- [performance-unneccessary-value-param](https://clang.llvm.org/extra/clang-tidy/checks/performance/unnecessary-value-param.html)
- [performance-for-range-copy.](https://releases.llvm.org/14.0.0/tools/clang/tools/extra/docs/clang-tidy/checks/performance-for-range-copy.html)
- [performance-faster-string-find](https://releases.llvm.org/14.0.0/tools/clang/tools/extra/docs/clang-tidy/checks/performance-faster-string-find.html)
- [performance-type-promotion-in-math-fn](https://releases.llvm.org/14.0.0/tools/clang/tools/extra/docs/clang-tidy/checks/performance-type-promotion-in-math-fn.html)
> Clang tidy performance

- layers/core_validation.cpp
- layers/sync_vuid_maps.cpp
- tests/vklayertests_others.cpp
This specifies that within a single queue submission, any waits on a timeline semaphore must use a lower value than any signals for that same semaphore. This is only a required for vkQueueSubmit2(), but it could also apply to vkQueueSubmit() and vkQueueBindSparse(), if we wanted to make an UNASSIGNED check for it.
> corechecks: Add VUID 03881 checking

- layers/cmd_buffer_state.cpp
- layers/gpu_utils.cpp
- layers/gpu_utils.h
- layers/gpu_validation.cpp
- layers/gpu_validation.h
Also remove an assert that an app leaking in flight command buffers can reach and trigger
Fixes a crash playing back a game trace with GPU-AV
> Move pool destroy in GPU-AV to after state tracker call

- tests/vklayertests_wsi.cpp
Currently NVIDIA's driver support for "VK_KHR_present_wait" for "VK_KHR_present_id" is broken. 
<details>
<summary>I verified this by running the relevant CTS tests.</summary>
```
juan@pop-os:~/projects/VK-GL-CTS$ export VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/nvidia_icd.json
juan@pop-os:~/projects/VK-GL-CTS$ ./build/external/vulkancts/modules/vulkan/deqp-vk --deqp-case=dEQP-VK.wsi.x*.present_id_wait.*
Writing test log into TestResults.qpa
dEQP Core git-acb25bf242c31cef2d82d4ebdb8d8d2f67af0ef6 (0xacb25bf2) starting..
target implementation = 'Default'
Test case 'dEQP-VK.wsi.xlib.present_id_wait.id.zero'..
Fail (vk.createSwapchainKHR(device, pCreateInfo, pAllocator, &object): VK_ERROR_INITIALIZATION_FAILED at vkRefUtilImpl.inl:385)
Test case …
```
> tests: Workaround PresentId driver bugs

- layers/object_tracker_utils.cpp
Fix for false positive VUID-VkPipelineShaderStageCreateInfo-module-parameter error.
VUID-VkPipelineShaderStageCreateInfo-module-parameter allows the shader module to be null everywhere else except for raytracing pipelines.
> layers: Fix validation of raytracing pipeline creation with null shader module

- layers/core_validation.cpp
- layers/core_validation.h
- layers/queue_state.cpp
- layers/queue_state.h
- layers/state_tracker.cpp
- layers/sync_vuid_maps.cpp
- layers/sync_vuid_maps.h
- tests/vklayertests_others.cpp
Restructure timeline semaphore checking so that it is easier to be aware of of timeline values within a single submission.
Redo vkQueueBindSparse() to use the common semaphore submission checking code.
>  corechecks: Improve timeline semaphore VUID checks

- BUILD.gn
- layers/vk_layer_config.cpp
- tests/test_common.h
None of the macros it defines are being used.
> build: Do not include vk_sdk_platform.h

- layers/generated/vk_enum_string_helper.h
- scripts/helper_file_generator.py
Error message before and after
> Validation Error: [ VUID-VkDescriptorSetLayoutBinding-descriptorType-01510 ] /*...*/ stageFlags must be 0 or VK_SHADER_STAGE_FRAGMENT_BIT but is currently VK_SHADER_STAGE_VERTEX_BIT|VK_SHADER_STAGE_TESSELLATION_CONTROL_BIT|VK_SHADER_STAGE_TESSELLATION_EVALUATION_BIT|VK_SHADER_STAGE_GEOMETRY_BIT|VK_SHADER_STAGE_FRAGMENT_BIT|VK_SHADER_STAGE_COMPUTE_BIT|VK_SHADER_STAGE_TASK_BIT_EXT|VK_SHADER_STAGE_MESH_BIT_EXT|VK_SHADER_STAGE_RAYGEN_BIT_KHR|VK_SHADER_STAGE_ANY_HIT_BIT_KHR|VK_SHADER_STAGE_CLOSEST_HIT_BIT_KHR|VK_SHADER_STAGE_MISS_BIT_KHR|VK_SHADER_STAGE_INTERSECTION_BIT_KHR|VK_SHADER_STAGE_CALLABLE_BIT_KHR|VK_SHADER_STAGE_SUBPASS_SHADING_BIT_HUAWEI|Unhandled VkShaderStageFlagBits|Unhandled VkShaderStageFlagBits|Unhandled VkShaderStageFlagBits|Unhandled …
> layers: Improve error message for VkShaderStageFlags

- layers/core_validation.cpp
This patch fixes compilation and adds validation of more properties, including that the object isn't in use and that it's not a timeline semaphore.
> layers: Improve ImportSemphoreFUCHSIA validation

- tests/test_common.h
- tests/vksyncvaltests.cpp
So to handle the timeout in my acquire/present testing, initially had a lamba doing the timeout check, but didn't actually "FAIL" correctly (i.e. return from the test).
This refactors that logic into a macro which will, and incorporates cleanup support.  Relocated to tests_common as REQUIRE_SUCCESS is likely useful anywhere we're failing on timeout, as it includes that cleanup capability.
> tests: Rework require_success to REQUIRE_SUCCESS

- layers/core_validation.cpp
These messages seem to be copy-pasted from the VkFence logic.
> layers: fix typo in semaphore export handle type checks

- layers/core_validation.cpp
- tests/vklayertests_buffer_image_memory_sampler.cpp
- tests/vklayertests_others.cpp
If image was created with disjoint bit and drm format modifier tiling there must be a VkImagePlaneMemoryRequirementsInfo in pNext chain
> Adding vuid 02279

- BUILD.gn
- build-gn/generate_vulkan_layers_json.py
- build-gn/layers-fuchsia.gni
This change lets us build the validation layers for the Fuchsia operating system. The layers are normally packaged with the Fuchsia SDK, so this repo must be checked out as part of the Fuchsia source tree [0] to build the layers.
[0]: https://fuchsia.dev/fuchsia-src/get-started/learn/build/source-tree?hl=en
> build: Add Fuchsia build

- scripts/utils/utils.py
Basically just a cleaned up version of https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/4715 since the bot can't sign a CLA
> scripts: Address python tarfile exploit

- tests/layer_validation_tests.cpp
- tests/vklayertests_arm_best_practices.cpp
- tests/vklayertests_buffer_image_memory_sampler.cpp
- tests/vklayertests_command.cpp
- tests/vklayertests_descriptor_renderpass_framebuffer.cpp
Part of https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/4425
Should fix
- VkArmBestPracticesLayerTest.RedundantRenderPassStore
- VkLayerTest.InvalidMixingProtectedResources
- VkLayerTest.CreateImageMaxLimitsViolation
These were cases where the test logic was wrong
> tests: Pixel6 failure tests fixed

- layers/best_practices_error_enums.h
- layers/best_practices_utils.cpp
- layers/core_validation.cpp
- layers/core_validation_error_enums.h
- layers/drawdispatch.cpp
- layers/generated/spirv_validation_helper.cpp
- layers/parameter_validation_utils.cpp
- scripts/spirv_validation_generator.py
- tests/vklayertests_best_practices.cpp
- tests/vklayertests_others.cpp
- move some items to `best_practices_error_enums.h` that are already being checked in the BP layers
- Added Dynamic Vertex Input VUIDs added into the spec a while ago
- removed some unused UNASSIGNED VUIDs
> layers: Clean up outdated UNASSIGNED VUIDs

- layers/core_validation.h
- layers/core_validation_error_enums.h
- layers/parameter_validation_utils.cpp
- layers/shader_validation.cpp
I realized that `ValidateViConsistency` is not being checked because there is already 
> VUID-VkPipelineVertexInputStateCreateInfo-pVertexBindingDescriptions-00616
>
> All elements of pVertexBindingDescriptions must describe distinct binding numbers
That is validating this
Also while at it, took the `vkCmdSetVertexInputEXT` logic and made it consistent and improved the error message
> layers: Remove unused ValidateViConsistency

- layers/core_validation.cpp
- tests/positive/pipeline.cpp
- tests/positive/shaderval.cpp
- tests/vklayertests_others.cpp
- tests/vklayertests_wsi.cpp
- tests/vktestframeworkandroid.cpp
- tests/vktestframeworkandroid.h
Went through each `AndroidHardwareBuffer` test, cleaned it up to be more like the other test code, broke up `AndroidHardwareBufferMemoryAllocation` as it was to large. Tested on Adreno  and Mali Pixel device.
Should fix quite a few tests in https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/4425 (and hopefully https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/4587)
> tests: Fix AHB tests

- layers/shader_validation.cpp
Fix a crash in
dEQP-VK.pipeline.pipeline_library.graphics_library.misc.other .null_descriptor_set_in_monolithic_pipeline
when independent sets/null DSLs are used in.
> layers: Fix null DSLs

- build-android/jni/Android.mk
- build-android/known_good.json
- build-android/update_external_sources_android.bat
- tests/layer_validation_tests.h
@juan-lunarg asked why the Android build needs Vulkan-Tools and I couldn't find a good reason!
> build: Remove Android dependency on Vulkan-Tools

- layers/best_practices_error_enums.h
- layers/best_practices_utils.cpp
- layers/best_practices_validation.h
- layers/buffer_validation.cpp
- layers/core_validation_error_enums.h
- tests/vklayertests_best_practices.cpp
- tests/vklayertests_command.cpp
Moves warning (discussed to be valid in WG) to BP layers
> layers: Move InvalidExtents to BP

- CMakeLists.txt
- layers/CMakeLists.txt
- Remove pointless macro AddVkLayer that makes reading/debugging
much more difficult.
- Remove TARGET_NAMES since it also makes reading/debugging much
more difficult
- Move VkLayers_Utils to appropriate location
> cmake: Cleanup layers/CMakeLists.txt

- tests/positive/pipeline.cpp
- tests/positive/shaderval.cpp
- tests/vklayertests_others.cpp
- tests/vklayertests_pipeline_shader.cpp
Fixes a few missing feature checks
- check for `primitiveFragmentShadingRate`
- `shaderSharedFloat32AtomicMinMax` to `shaderImageFloat32AtomicMinMax`
- check for `primitivesGeneratedQueryWithNonZeroStreams`
> tests: Fix tests on Mesa

- layers/shader_validation.cpp
- tests/vklayertests_pipeline_shader.cpp
The error message `Shader uses descriptor slot 1.0` is not helpful for most people, explicitly say `Set 1 Binding 0` now
> layers: Improve shader descriptor error message

- tests/CMakeLists.txt
The short default timeout of 1 second caused CI runs to fail when the call to gtest_discover_tests would error. Setting it to 100 makes the timeout be one hundred seconds, giving ample time for the command to run.
> test: Increase gtest discovery timeout

- tests/vklayertests_pipeline_shader.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/3070
1. Adds another tests for Non-InputAttachment shader input with unknown image format
2. Fix some tests that were invalid and not running correctly
> tests: Add and fix unknown format shader test

- tests/vklayertests_buffer_image_memory_sampler.cpp
Temp fix as pointed out in https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/4793
> tests: Disable DRM Format Modifier disjoint check

- layers/core_validation.cpp
Some CTS tests create a gpl without a valid pipeline layout and get the expected 06642 and then crash.  This fixes the crash.
> Handle invalid pipeline layout creating graphics pipeline library

- layers/object_tracker_utils.cpp
- tests/vklayertests_descriptor_renderpass_framebuffer.cpp
This adds `VUID-VkWriteDescriptorSet-descriptorType-07683` split out from the ` VUID-VkWriteDescriptorSet-descriptorType-02996`/` VUID-VkWriteDescriptorSet-descriptorType-02997` in the 1.3.233 headers
> Refactor ValidateDescriptorWrite to use switch and add VUID 07683

- layers/CMakeLists.txt
Now the build directory will only contain 1 json file named VkLayer_khronos_validation.json
This caused an issue for CI projects that searched the build dir for the json file.
> cmake: Avoid duplicate VkLayer_khronos_validation.json

- BUILD.md
- CONTRIBUTING.md
- README.md
- docs/README.md
- docs/core_checks.md
- docs/creating_tests.md
- docs/generated_code.md
- docs/khronos_validation_layer.md
- docs/shader_validation.md
- docs/stateless_validation.md
- tests/README.md
In effort to make it easier for new developers to get up and running with the code
Highlights:
- Reduce `BUILD.md` to just what it takes to build
- Created `tests/README.md` to hold information about running the tests
- Added a `docs/generated_code.md` and `docs/shader_validation.md`
> docs: Documentation cleanup

- tests/vklayertests_command.cpp
- tests/vklayertests_pipeline_shader.cpp
Also move tests to shader test file
Prevent tests from failing in glslang from `ERROR: 0:6: 'local_size' : too large, see gl_MaxTaskWorkGroupSizeEXT`
> tests: Move mesh shader limits to SPIR-V

- layers/core_validation.cpp
- layers/queue_state.cpp
- layers/queue_state.h
- tests/vklayertests_others.cpp
Store signal and wait operation(s) in a single std::map entry. For timeline semaphores, there can only ever be 1 signal operation for each value. For binary semaphores, each signal operation must have exactly 1 wait. Storing the signals and waits together makes it easier to keep track of these conditions. (Reminder: for binary semaphores, timeline-like values are assigned to every signal/wait signal pair by SEMAPHORE_STATE itself)
Stop assuming that completion of any signal operation implies anything about operations with lower timeline values. Instead, only retire the exact timeline value for each semaphore when its queue submission (or host signal operation) completes. The retire should trigger a chain reaction through all of the queues causing prior operations to retire in the correct …
> layers: Attempt (again) to solve semaphore race conditions

- layers/cmd_buffer_state.cpp
This method in CMD_BUFFER_STATE was dereferencing a vector before checking that the index in bounds.
> layers: Fix invalid memory access in UpdatePipelineState()

- layers/parameter_validation_utils.cpp
The check was attempting to add a pointer to an integer. Instead we want to check if the pointer is present, and if so add 1 to the integer.
> layers: Fix fuchsia buffer import check

- tests/positive/render_pass.cpp
A vector::clear call in VkPositiveLayerTest.DestroyPipelineRenderPass is causing a pointer setup during VkLayerTest::Init time to be invalid.
Closes #4836.
> tests: Remove unnecessary vector::clear

- layers/core_validation.cpp
- tests/positive/graphics_library.cpp
This issue was discovered using graphics pipeline libraries, where a fragment library doesn't need to have a raster state defined.
In that case there was a crash in the validation layers.
Unsure where best to add the check, or whether to use `&& !pipeline->IsGraphicsLibrary()` in the parent branch.
> layers: Adds missing null check for raster_state

- layers/core_validation.cpp
- layers/core_validation.h
- layers/drawdispatch.cpp
- layers/vk_layer_utils.h
- tests/vklayertests_command.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/4137
adds `VUID-vkCmdDraw-None-06886`/`VUID-vkCmdDraw-None-06887` (and all other draws)
The 2 original VUs were added in https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/4103 but were then removed when the new headers moved from pipeline creation time to draw time.
> Add DS draw time read only VUID

- layers/CMakeLists.txt
After looking into this for a while. CMake doesn't have a standard location for `MODULE` libraries. Because there is no standard for plugin type libraries.
As a result just match our SDK creation process. This doesn't change UNIX platforms, it only matches our WIN32 SDK installation.
closes #4805
Example install ouput
```
-- Installing: D:/a/.../install/bin/VkLayer_khronos_validation.json
-- Installing: D:/a/.../install/bin/VkLayer_khronos_validation.dll
```
> cmake: Fix incorrect install location

- layers/CMakeLists.txt
CMake requires the same argument in if(), else(), endif() sequences.
"elseif(LINUX)" may have been intended here, but simply removing the LINUX from the else() retains current behavior and is arguably clearer than replacing it with "APPLE" to match the else with the if.
> cmake: Fix incorrect else() argument warning

- scripts/sync_val_gen.py
This fixes a "pythonic" style checker warning in my downstream flows.
> Use pythonic  "foo not in blah" instead of "not foo in blah"

- layers/core_validation.cpp
- layers/core_validation.h
- layers/descriptor_validation.cpp
- layers/drawdispatch.cpp
08903 and 08125 had typos in their VUID strings.
08116 isn't implemented but VUID strings were in the code so vk_validation_stats.py got confused.
Unimplemented VUIDs for this extension are tracked in #4832
> VK_EXT_descriptor_buffer: Fix problems with VUIDS 08903, 08125 and 08116

- layers/debug_printf.cpp
- layers/debug_printf.h
- layers/gpu_validation.cpp
- layers/gpu_validation.h
I didn't add the entrypoints to state_tracker, or calls to those entrypoints from GPU-AV or DbPf because I don't think anything is checking them, but I could be wrong and will happily add them if so.
> Add GPU-AV and debug printf allocations for EXT mesh_shader

- layers/cmd_buffer_state.h
- layers/core_validation.h
- layers/descriptor_validation.cpp
- layers/drawdispatch.cpp
- layers/pipeline_state.cpp
- layers/pipeline_state.h
- layers/shader_module.cpp
- layers/shader_module.h
- layers/shader_validation.cpp
- tests/positive/shaderval.cpp
- tests/vklayertests_pipeline_shader.cpp
Adds `VUID-vkCmdDispatch-None-04115` and `VUID-vkCmdDispatch-OpImageWrite-04469`
These are the draw time version of `VUID-RuntimeSpirv-OpImageWrite-07112`
It maps the `OpImageWrite` -> `OpLoad`/`OpAccessChain` -> Descriptor `OpVariable` . From there the descriptor can see all the `OpImageWrite` used on it.
------
I think there is improvement in how we are having to copy the data from `InterfaceVariable` to `DescriptorRequirement`, but realize that becomes messy due to `UPDATE_AFTER_BIND` descriptors being a thing. I decided to defer that to a follow-up PR
> Add draw time Unknown format texel count

- layers/core_validation.cpp
- layers/vk_layer_logging.h
- tests/vklayertests_ray_tracing.cpp
- tests/vklayertests_ray_tracing_gpu.cpp
- tests/vktestbinding.cpp
- tests/vktestbinding.h
- Fix for https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/4589
Adds VUID-vkCmdBuildAccelerationStructuresKHR-pInfos-04630
Also some cleanups in ray tracing tests:
- Make `AccelerationStructure{KHR}::create_scratch_buffer` return a buffer
- Use `device()` instead of `m_device->handle()`
- Remove unhelpful usage of `std::make_unique`
> Fix for PreCallValidateCmdBuildAccelerationStructuresKHR nullptr handling + new VUID

- layers/core_validation.cpp
- layers/core_validation.h
- layers/drawdispatch.cpp
- tests/vklayertests_others.cpp
Splits the new 1.3.236 VUID from `VUID-vkCmdDraw-attachmentCount-06667` to `VUID-vkCmdDraw-None-07749` and `VUID-vkCmdDraw-attachmentCount-07750`
> layers: Split dynamic color blend enable VUID

- layers/core_validation.cpp
- layers/core_validation.h
- layers/core_validation_error_enums.h
- layers/drawdispatch.cpp
- tests/vklayertests_descriptor_renderpass_framebuffer.cpp
The 1.3.236 spec fix changed this
[Issue 4891](https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/4891) created to track this
> layers: Remove VUID-vkCmdDraw-None-02686

- BUILD.md
Easy to not maintain, and get out of date
> docs: Remove 'CMake Generators' section

- layers/parameter_validation_utils.cpp
Currently validation for vkExportMetalObjectsEXT is a mixture of code-gen / manual code. This static assert ensures the existing code is fine.
> layers: Ensure ExportMetalObjects is valid

- layers/core_validation.cpp
- layers/core_validation.h
- layers/drawdispatch.cpp
- tests/vklayertests_others.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/3417 and https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/3505
adds new `VUID-vkCmdDraw-None-07751` from 1.3.236
> Add Dynaimc state Discard Rectangle VU

- layers/buffer_validation.cpp
- layers/core_validation_error_enums.h
- tests/vklayertests_buffer_image_memory_sampler.cpp
- tests/vklayertests_command.cpp
These VUIDs were shuffled around in the last 1.3.236 header update
`VUID-VkImageCopy-extent-00140` was not replaced correctly, will be making another internal spec fix for that
> layers: Relabel copy cmd VUID from 1.3.236

- CMakeLists.txt
- layers/CMakeLists.txt
Currently MINGW call is nested under a check for MSVC. MINGW doesn't  use MSVC.
> cmake: Fix MINGW build

- layers/core_validation.h
- layers/descriptor_validation.cpp
- layers/drawdispatch.cpp
- tests/vklayertests_command.cpp
adds `VUID-vkCmdDrawIndexed-viewType-07752` and `VUID-vkCmdDrawIndexed-format-07753` in effort to reduce how many checks `vuids.descriptor_valid` has
> layers: Label 1.3.236 descriptor VUs

- .gitignore
- layers/pipeline_state.cpp
- layers/pipeline_state.h
- layers/shader_validation.cpp
- tests/positive/graphics_library.cpp
- tests/vklayertests_debug_printf.cpp
- tests/vklayertests_gpu.cpp
- tests/vklayertests_graphics_library.cpp
- tests/vklayertests_pipeline_shader.cpp
- tests/vktestbinding.h
Fixes the IsGraphicsLibrary and a shader module identifier check that
prevented all shader stage validation from happening when GPL was in
use.
Closes #4811.
> layers: Ensure shader stage validation for GPL 

- layers/cmd_buffer_state.cpp
- layers/cmd_buffer_state.h
Remove the `framebuffers` map since it is redundant with `object_bindings`.
Work around a possible race condition in NotifyInvalidate. Due to interactions between the `BASE_NODE::tree_lock_` and `CMD_BUFFER_STATE::lock` it was possible for a (not really) 'bad' binding to get added to `broken_bindings`. Try to fix this by only adding a node to `broken_bindings` if it was still found in `object_bindings`.
> state: Simplify CMD_BUFFER_STATE object tracking

- layers/core_validation.cpp
- layers/core_validation.h
The function was hitting over 2000 lines and hard to maintain and some redundant work being done. Broke the function into some helper functions, makes it easier to make improvements in the future for this change
Made a per-commit change because moving the Dynamic and Multisample state code seems to trip up `git` and does a **bad** job showing the simple move diff
> Breakup ValidatePipeline function

- layers/cmd_buffer_state.cpp
- layers/cmd_buffer_state.h
- layers/core_validation.cpp
- layers/descriptor_validation.cpp
- layers/pipeline_state.h
- layers/state_tracker.cpp
- tests/vklayertests_descriptor_renderpass_framebuffer.cpp
- tests/vktestbinding.cpp
- tests/vktestbinding.h
These 2 VUIDs are about which pipelines are compatible with vkCmdBindDescriptorSets() or vkCmdSetDescriptorBufferOffsetsEXT(). The old code was looking at state set by vkCmdBindDescriptorBuffersEXT(). It should be valid to have descriptor buffers bound but not used to allow switching back and forth between pipelines that use descriptor sets and descriptor buffers.
Fixes #4913
> layers: Fix descriptor buffer VUIDs 08115 and 08117

- layers/cmd_buffer_state.h
- layers/core_validation.cpp
- layers/state_tracker.cpp
- layers/state_tracker.h
- tests/vklayertests_command.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/4921
The spec was updated in 1.3.237 to have the VU check the `writeMask` (static or dynamic)
> layers: Fix 06887 to check stencil write mask

- layers/descriptor_validation.cpp
This check had a copy / paste error, which was found by a 'set but not used' warning from clang-15.
> corechecks: Fix VUID 08049

- layers/best_practices_utils.cpp
- layers/buffer_validation.cpp
- layers/cmd_buffer_state.cpp
- layers/core_validation.cpp
- layers/debug_printf.cpp
- layers/descriptor_sets.cpp
- layers/descriptor_validation.cpp
- layers/generated/thread_safety.cpp
- layers/generated/vk_safe_struct.cpp
- layers/gpu_utils.cpp
- layers/gpu_validation.cpp
- layers/image_state.cpp
- layers/image_state.h
- layers/object_lifetime_validation.h
- layers/parameter_validation_utils.cpp
- layers/shader_module.cpp
- layers/shader_validation.cpp
- layers/state_tracker.cpp
- layers/subresource_adapter.cpp
- layers/subresource_adapter.h
- layers/synchronization_validation.cpp
- layers/synchronization_validation.h
- layers/vk_layer_utils.cpp
- layers/vk_layer_utils.h
- scripts/helper_file_generator.py
- scripts/thread_safety_generator.py
`^((?!const).)*bool (?!skip)\w* = ((?!false)(?!true))` seemed to work well finding cases where `bool` were able to be `const`
> layers: Make bool const where possible

- layers/core_validation.cpp
- tests/vklayertests_graphics_library.cpp
00736 should only be triggered when vertex input state (not just
pre-raster state) is present.
> layers: Fix 00736 trigger

- tests/layer_validation_tests.cpp
- tests/layer_validation_tests.h
- tests/positive/pipeline.cpp
- tests/positive/render_pass.cpp
- tests/vklayertests_descriptor_renderpass_framebuffer.cpp
replaced `CheckCreateRenderPass2Support` with the new `AddRequiredExtensions` and `AddOptionalExtensions` mechanism
> tests: Remove CheckCreateRenderPass2Support

- layers/cmd_buffer_state.h
- layers/core_validation.cpp
- layers/state_tracker.cpp
- layers/state_tracker.h
- layers/synchronization_validation.cpp
- First move all the dynamic state in `ValidationStateTracker` to `PostCallRecord`
- collapse the `EXT` functions to use a single helper function
- For all "at draw time call" check if DepthStencil state was set dynamically (currently we are checking only the static value for most values)
- Note: I want to fix this with other pipeline states as well, but this is a good first step
> Use DS dynamic state for draw time checks

- tests/positive/descriptors.cpp
- tests/vklayertests_descriptor_renderpass_framebuffer.cpp
- tests/vktestbinding.cpp
- tests/vktestbinding.h
Add some stuff to make the vk_testing:: objects easier to use:
- vk_testing::*::destroy() methods 
- vk_testing::Buffer::address() and another constructor that makes it easy to set VK_MEMORY_ALLOCATE_DEVICE_ADDRESS_BIT
Then convert a bunch of descriptor tests to use these objects instead of raw vulkan handles.
> tests: Use vk_testing:: objects in descriptor tests

- docs/gpu_validation.md
- layers/cmd_buffer_state.h
- layers/core_validation.cpp
- layers/core_validation.h
- layers/descriptor_validation.cpp
- layers/drawdispatch.cpp
- layers/range_vector.h
- layers/state_tracker.cpp
- layers/state_tracker.h
- layers/vk_layer_data.h
- tests/vklayertests_ray_tracing.cpp
- tests/vktestbinding.h
Objectives:
=
- Add VUIDs listed in https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/4556
- Still some TODOs to properly handle new `GetBuffersByAddress` calls introduced by rebasing on master
- Fix for https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/4714
Summary:
=
Aside adding some VUIDS, how the mapping between `VkBuffer` and `VkDeviceAddress` has been updated. This mapping is not 1:1, multiple `VkBuffer` can return the same starting `VkDeviceAddress`. It can happen if for instance 2 `VkBuffer`s are bound to the same memory region. See 118ec423c61f9c0afc28e6be9f717a081743dc8b for how the mapping has been updated.
Tests:
`BuffersAndBufferDeviceAddressesMapping`: Test how that adding and removing elements in the buffer <-> address map is correctly handled. …
> Add several RTX VUIDs, Update `buffer` <-> `device address` mapping

- layers/best_practices_error_enums.h
- layers/best_practices_utils.cpp
- layers/best_practices_validation.h
- tests/vklayertests_best_practices.cpp
This change adds a new VU to the best practices layer that detects `vkAllocateCommandBuffers` calls trying to allocate secondary command buffers for queue families that do not support the `vkCmdExecuteCommands` command (queues that do not support graphics, compute, or transfer) and reports a warning about the allocated command buffer not being submittable.
> Add best practices VU for useless secondary command buffer

- layers/shader_validation.cpp
Should fix https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/3672
> layers: Use stage from pipleline library

- layers/drawdispatch.cpp
The 1.3.238 headers moved `VUID-vkCmdDrawIndexed-firstIndex-04932` to `VUID-vkCmdDrawIndexed-robustBufferAccess2-07788` adding a
> If robustBufferAccess2 is not enabled
restriction.
Created https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/5623 as all functions calling `ValidateCmdDrawIndexedBufferSize` should also make the check
> layers: Update ValidateCmdDrawIndexedBufferSize to check robustness

- tests/positive/command.cpp
- tests/positive/image_buffer.cpp
- tests/positive/pipeline.cpp
- tests/positive/render_pass.cpp
- tests/vklayertests_arm_best_practices.cpp
- tests/vklayertests_buffer_image_memory_sampler.cpp
- tests/vklayertests_command.cpp
- tests/vklayertests_dynamic_rendering.cpp
- tests/vklayertests_pipeline_shader.cpp
- tests/vklayertests_viewport_inheritance.cpp
use new `LvlInitStruct<VkRenderPassBeginInfo>` everywhere
> tests: Use LvlInitStruct<VkRenderPassBeginInfo>

- layers/buffer_validation.cpp
- layers/core_validation.cpp
- tests/vklayertests_buffer_image_memory_sampler.cpp
- tests/vklayertests_command.cpp
the 1.3.238 headers removed the tiling check for `GetImageSubresourceLayout2`
This both removes the VU and relabels the `GetImageSubresourceLayout` VUIDs
> layers: Remove GetImageSubresourceLayout2 tiling VU

- layers/descriptor_validation.cpp
- tests/positive/graphics_library.cpp
- tests/vklayertests_graphics_library.cpp
This effectively reverts https://github.com/KhronosGroup/Vulkan-ValidationLayers/commit/c82d75fe22da9a1115e3a5b5f98cd220fc8653bb, which allowed binding empty
descriptor sets.
Closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/4768.
> layers: Do not allow binding empty DS

- scripts/common_ci.py
- tests/README.md
VK_ICD_FILENAMES is listed as a deprecated environment variable:
https://github.com/KhronosGroup/Vulkan-Loader/blob/master/docs/LoaderInterfaceArchitecture.md#deprecated-environment-variables
> Replace usage of VK_ICD_FILENAMES with VK_DRIVER_FILES

- layers/cmd_buffer_state.cpp
Make sure to remove the parent node if we're cleaning up an object_bindings entry in CMD_BUFFER_STATE::NotifyInvalidate(). Without this, child objects could have a stale parent and think they are in use when they're not.
Fixes #4981
> layers: Fix intermittent VUID 03047 false positives

- layers/buffer_validation.cpp
- layers/core_validation_error_enums.h
- tests/vklayertests_command.cpp
`VUID-vkCmdCopyImage-srcImage-07744`/`VUID-VkCopyImageInfo2-srcImage-07744` was added to the Vulkan Spec and covers the previous UNASSIGNED VU
> layers: Label VUID vkCmdCopyImage 07744

- layers/synchronization_validation.cpp
Ran into this when moving over to sync2 in Granite. A COMBINED_IMAGE_SAMPLER was trying to access STORAGE_READ rather than SAMPLED_READ, causing false positive. This fixed the issue for me, but I don't know the sync validation code enough to know if this fix is complete.
> layers: Handle SAMPLED_READ in sync2 validation

- layers/best_practices_utils.cpp
- layers/buffer_validation.cpp
- layers/core_validation.cpp
- layers/descriptor_validation.cpp
- tests/vklayertests_buffer_image_memory_sampler.cpp
- Created a internal Spec Fix to split `VUID-VkWriteDescriptorSet-descriptorType-06710` into proper 2 different VUs https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/5626/
- collapsed logic together
- Make sure to use `IsExtEnabled`
- Fix bug as `VK_IMAGE_VIEW_TYPE_2D_ARRAY` (`VUID-VkDescriptorImageInfo-imageView-06712`) is called regardless of the extension being enabled or not
Original PR (cc @Tony-LunarG) https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/3989
> Fix VK_EXT_image_2d_view_of_3d check

- layers/best_practices_utils.cpp
- layers/buffer_validation.cpp
- layers/cmd_buffer_state.cpp
- layers/core_validation.cpp
- layers/core_validation.h
- layers/descriptor_validation.cpp
- layers/drawdispatch.cpp
- layers/generated/chassis.h
- layers/object_tracker_utils.cpp
- layers/shader_validation.cpp
- scripts/layer_chassis_generator.py
- Uses the new multi argument constructor for `LogObjectList`
- make all `const` that can be constant
- unify name to `objlist` across repo
> layers: Use new LogObjectList multi arg constructor

- docs/fine_grained_locking.md
- layers/descriptor_sets.cpp
- layers/descriptor_sets.h
Found running ThreadUpdateDescriptorUpdateAfterBindNoCollision w/ -fsanitize=thread
> layers: Fix UpdateDescriptorSets race conditions

- layers/core_error_location.cpp
- layers/core_error_location.h
- layers/core_validation.cpp
- layers/sync_vuid_maps.cpp
- tests/vklayertests_wsi.cpp
- tests/vktestbinding.h
Use the common validation code to implement VUIDs 01294, 01295 and 03268.
Fixes #4869
> corechecks: Improve vkQueuePresentKHR semaphore validation

- layers/sync_vuid_maps.cpp
- tests/vklayertests_buffer_image_memory_sampler.cpp
`UNASSIGNED-{barrier}-{accesMask}-SHADER_BINDING_TABLE_READ` now has a definition: `VUID-{barrier}-{accesMask}-07272`
> Add VU 07272

- layers/cmd_buffer_state.cpp
- layers/cmd_buffer_state.h
- layers/state_tracker.cpp
- Use span
- Use MaxTypeValue
- Use |=
- Use emplace_back
> layers: Cleanup CMD_BUFFER_STATE::ExecuteCommands

- layers/shader_instruction.cpp
- layers/shader_instruction.h
- layers/shader_module.cpp
- Move the `GetBitWidth` logic into a per-`Instruction` function to be reused
- cleaned up `GetNumComponentsInBaseType` and `GetTypeBitsSize` a bit to be consistent with other similar helper functions
> layers: Add GetBitWidth SPIR-V helper

- layers/core_validation.h
- layers/core_validation_error_enums.h
- layers/shader_validation.cpp
- tests/vklayertests_descriptor_renderpass_framebuffer.cpp
- tests/vklayertests_pipeline_shader.cpp
- Created a `ValidateShaderInputAttachment` to hold logic (more to be added in future)
- Labeled `kVUID_Core_Shader_MissingInputAttachment` with `VUID-VkGraphicsPipelineCreateInfo-renderPass-06038`
- Removed `kVUID_Core_Shader_MissingInputAttachment` and created separate issue (https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/5027) to add back in the best practice layers as a warning
> layers: Add Shader input attachment VU

- build-android/known_good.json
- layers/generated/spirv_tools_commit_id.h
- scripts/external_revision_generator.py
- scripts/known_good.json
Current SPIR-V Tools had build issue that is now fixed
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/4947
> deps: Update SPIR-V Tools and Headers version

- BUILD.gn
- CMakeLists.txt
- build-android/cmake/layerlib/CMakeLists.txt
- build-android/jni/Android.mk
- layers/CMakeLists.txt
- layers/device_memory_state.h
- layers/generated/chassis.cpp
- layers/generated/chassis.h
- layers/generated/chassis_dispatch_helper.h
- layers/layer_options.cpp
- layers/render_pass_state.h
- layers/video_session_state.h
- layers/vk_layer_logging.cpp
- layers/vk_layer_logging.h
- layers/vk_layer_utils.cpp
- layers/vk_layer_utils.h
- scripts/layer_chassis_generator.py
- tests/vklayertests_others.cpp
- tests/vksyncvaltests.cpp
Add vk_layer_logging.cpp, so that most of the logging functions can be de-inlined. This appears to reduce compiled code size for the validation layer by 11% to 33% (on linux).
Change LogMsgLocked() to LogMsg() and restructure it to avoid duplicated code in class ValidationObject.
Remove use of vasprintf() and use stack buffers and snprintf() instead. vasprintf() calls malloc internally and VVL must call free. When overriding malloc, this gets complicated because libc and VVL can end up using different malloc and free implementations.
> layers: Clean up vk_layer_logging.h

- BUILD.md
- CMakeLists.txt
- scripts/cmake_test_min.py
spirv-tools updated their cmake minimum to 3.17.2
> cmake: Raise minimum to 3.17.2

- layers/cmd_buffer_state.h
- layers/core_validation.cpp
- layers/state_tracker.cpp
- tests/vklayertests_others.cpp
Have internal request to fix the draw time check for dynamic discard rectangle so it checks all indexes are set
https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/5625
> layers: Fix discard rectangle draw VU

- layers/core_validation.cpp
- layers/core_validation.h
- layers/pipeline_state.h
Trying to reduce the `CoreChecks::ValidatePipeline` more, moved the Fragment Shading Rate and Dynamic Rendering create info logic to its own function
> More cleaning up of ValidatePipeline

- BUILD.md
According to requirements Python 3.x is required to build the project. Python 3.x Windows distributions usually provide python.exe but not python3.exe. Windows app store distribution has both python3.exe and python.exe.
> docs: Update python executable name on Windows

- layers/core_validation_error_enums.h
- layers/drawdispatch.cpp
- tests/vklayertests_ray_tracing.cpp
- Fix for https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/5035
(The issue was spotted in the CTS)
When VkStridedDeviceAddressRegionKHR.deviceAddress is 0, the region is considered unused, and this is a valid behaviour, [as per the spec](https://registry.khronos.org/vulkan/specs/1.3-extensions/html/vkspec.html#VkStridedDeviceAddressRegionKHR).
Also, the case where a user provided device address cannot be associated to a buffer using the internal `buffer_address_map_` does not fall under the umbrella of any VUID it seems. So I added `UNASSIGNED-CoreValidation-VkDeviceAddress-NoAssociatedBuffer` to output a proper error for that case. Using an invalid address (or one that became invalid following a buffer destruction) seems likely to me, so better have a custom error.
> Fix shader binding table with device address == 0

- layers/core_validation.cpp
- layers/core_validation.h
There was no reason not to use `RENDER_PASS_STATE` as a const ref as we are dereferencing without checking already
> layers: Make RENDER_PASS_STATE const ref

- layers/gpu_validation.cpp
- layers/gpu_validation.h
This is for debugging GPU-AV, and not really valuable to an end user.  It does catch the current problem with VkGpuAssistedLayerTest.GpuBufferDeviceAddressOOB.
> Add GPU-AV debug option to validate instrumented shaders

- layers/best_practices_utils.cpp
- layers/descriptor_validation.cpp
- layers/pipeline_state.cpp
- layers/pipeline_state.h
- layers/shader_module.cpp
- layers/shader_module.h
- layers/shader_validation.cpp
- layers/synchronization_validation.cpp
Currently the shader validation code gets the same information from many different ways resulting in a tangled mess.
This attempts to move more information over to `InterfaceVariable` and then have it at a per-EntryPoint level (which will be needed to support multiple entry points correctly)
This is just a first step PR, the biggest issue is an "Interface Variable" being used for a descriptor is not being treated the same as the Input/Output shader stage interface variables, but yet are sharing some of the same logic. The Input/Output interface is a slight more tricky due to the fact it can have `OpMemberDecorate`
In the process of trying to refactor this, had some generic cleanup as well
> Using InterfaceVariable in EntryPoint 

- layers/drawdispatch.cpp
(I forgot to add that to https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/5039)
For the shader binding table buffers mentioned in trace rays commands, their memory binding needs to be validated if and only if the buffer is not sparse.
The concerned VUID family is the one mentioned in https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/5035
Their definition is the same, only the `deviceAddress` member changes. e.g.:
> VUID-vkCmdTraceRaysKHR-pRayGenShaderBindingTable-03680
If the buffer from which pRayGenShaderBindingTable->deviceAddress was queried is non-sparse then it must be bound completely and contiguously to a single VkDeviceMemory object
> Fix for sparse shader binding table buffer validation

- layers/descriptor_validation.cpp
- tests/positive/descriptors.cpp
Allow an empty descriptor set to be bound if the current layout also
defines an empty descriptor set.
> layers: Allow binding empty DS with empty layout

- layers/core_validation.cpp
- tests/positive/pipeline.cpp
Fix bug were `dEQP-VK.draw.renderpass.discard_rectangles.inclusive_rect_1` was setting `VkPipelineDiscardRectangleStateCreateInfoEXT` but not `VK_DYNAMIC_STATE_DISCARD_RECTANGLE_EXT` and the layers were still checking if the dynamic state was set
cc @Tony-LunarG
> layers: Fix check for VK_DYNAMIC_STATE_DISCARD_RECTANGLE_EXT

- layers/CMakeLists.txt
- scripts/known_good.json
Vulkan::Registry was deprecated by Vulkan-Headers
Use 'VULKAN_HEADERS_REGISTRY_DIRECTORY' instead.
> cmake: Fix usage of Vulkan::Registry

- tests/vklayertests_buffer_image_memory_sampler.cpp
Found on lavapipe 22.3.2.
Lavapipe doesn't support the VK_KHR_SAMPLER_YCBCR_CONVERSION_EXTENSION.
This test uses this extension by calling one of its functions to test the case where one of its dependent extensions isn't enabled.  The trouble with this is that if the sampler extension isn't supported, the test should not call the extension function and should skip the rest of the test.
This commit modifies the check for the extension to skip the test in this situation.
> tests: Fix jump to null function pointer

- CMakeLists.txt
- layers/CMakeLists.txt
- tests/CMakeLists.txt
Regression caused by 4050be7c1960ae0aec00b421bb47be8d67cabe63
Currently LunarG/VulkanTools will fail to build.
This is due to disabling BUILD_LAYERS and BUILD_TESTS, which causes the SPIRV-Headers::SPIRV-Headers dependency to not exist.
> cmake: Fix LunarG/VulkanTools build

- layers/generated/chassis.h
- scripts/layer_chassis_generator.py
It's a safeguard against potential bugs in other layers or the loader.
According to specification, successfully created non-dispatchable object can not be VK_NULL_HANDLE.
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/4705
> layers: Ensure object handle is not null

- layers/parameter_validation_utils.cpp
- layers/pipeline_validation.cpp
- tests/vklayertests_pipeline_shader.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/4727
most of these are just labeling if it is using the `vk_ext_extended_dynamic_state3` extension or not
> Add remaining VK_EXT_extended_dynamic_state3 VU

- CMakeLists.txt
- layers/best_practices_utils.cpp
- layers/buffer_validation.cpp
- layers/descriptor_validation.cpp
- layers/layer_options.cpp
- layers/subresource_adapter.cpp
- layers/vk_mem_alloc.h
- tests/vklayertests_pipeline_shader.cpp
Enables `-Wimplicit-fallthrough` in both gcc and clang. 
`[[fallthrough]]`s and `break`s are added in a few places.
There are no compiler version checks regarding `-Wimplicit-fallthrough` support. The assumption that this warning is supported by GCC/Clang versions that support C++17/`[[fallthrough]]`.
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/4809
> layers: Use fallthrough attribute and enable warning

- scripts/vk_validation_stats.py
Add option -extension_coverage to generate a csv report with VUID counts broken down by extension. If a single VUID interacts with multiple extensions, it will be added to the counts for each one.
> scripts: Add extension VU coverage report

- layers/core_validation.h
- layers/device_memory_validation.cpp
- layers/generated/layer_chassis_dispatch.cpp
- layers/image_state.cpp
- layers/image_state.h
- layers/parameter_validation_utils.cpp
- layers/state_tracker.cpp
- layers/wsi_validation.cpp
- scripts/layer_chassis_dispatch_generator.py
- tests/vklayertests_wsi.cpp
Most if not all of the existing review feedback has been addressed. Should be in fully reviewable form -- see the top two commits for the newer, more questionable changes.
replaces `VUID-vkAcquireNextImage2KHR-swapchain-01803` and `VUID-vkAcquireNextImageKHR-swapchain-01802` for `VUID-vkAcquireNextImage2KHR-surface-07784` and `VUID-vkAcquireNextImageKHR-surface-07783`
Fixes #4985.
When final, update tracking issue [here](https://github.com/KhronosGroup/Vulkan-Docs/issues/2006).
> Add support for VK_EXT_surface_maintenance1 and VK_EXT_swapchain_maintenance1

- CMakeLists.txt
- layers/CMakeLists.txt
CMake docs don't recommend using `add_definitions` anymore.
> cmake: Use target_compile_definitions & add_compile_definitions

- layers/shader_module.h
Fixes a warning on gcc 12.2 when building release with -Werror.
> layers: Fix GCC release build with -Werror

- layers/generated/enum_flag_bits.h
- layers/generated/parameter_validation.cpp
- layers/generated/parameter_validation.h
- scripts/parameter_validation_generator.py
Currently tests are showing false positive
```
[ RUN      ] VkLayerTest.DescriptorUpdateTemplate
Validation Error: [ VUID-VkDescriptorSetLayoutCreateInfo-pNext-pNext ] Object 0: handle = 0x55cc55a46570, type = VK_OBJECT_TYPE_INSTANCE; | MessageID = 0x2b747b43 | vkCreateDescriptorSetLayout: Includes a pNext pointer (pCreateInfo->pNext) to a VkStructureType (VK_STRUCTURE_TYPE_MUTABLE_DESCRIPTOR_TYPE_CREATE_INFO_EXT), but its parent extension VK_VALVE_mutable_descriptor_type has not been enabled. The Vulkan spec states: Each pNext member of any structure (including this one) in the pNext chain must be either NULL or a pointer to a valid instance of VkDescriptorSetLayoutBindingFlagsCreateInfo or VkMutableDescriptorTypeCreateInfoEXT (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/ …
```
> scripts: Remove false positive for sType

- layers/buffer_validation.cpp
- layers/core_validation.cpp
- layers/core_validation.h
- layers/descriptor_validation.cpp
- layers/device_memory_validation.cpp
- layers/drawdispatch.cpp
- layers/query_validation.cpp
- layers/ray_tracing_validation.cpp
- layers/video_validation.cpp
Many transfer commands VUIDs were not including the VkCommandBuffer, VkBuffer or VkImage in their error messages. Improve this, and de-pointer many of the invovled helper methods.
> corechecks: Include relevant objects in transfer command errors

- tests/positive/sync.cpp
- tests/vklayertests_buffer_image_memory_sampler.cpp
- tests/vklayertests_command.cpp
- tests/vklayertests_dynamic_rendering.cpp
- tests/vklayertests_nvidia_best_practices.cpp
- tests/vklayertests_others.cpp
- tests/vklayertests_pipeline_shader.cpp
Using swiftshader as the ICD on Windows, running the validation tests generated errors, hangs, or  crashes on the following tests:
- VkNvidiaBestPracticesLayerTest.BindPipeline_SwitchTessGeometryMesh
- VkPositiveLayerTest.FenceSemThreadRace
- VkLayerTest.ExerciseGetImageSubresourceLayout
- VkLayerTest.CreateImageYcbcrFormats
- VkLayerTest.ResolveInvalidUsage  
- VkLayerTest.DynamicRenderingGraphicsPipelineCreateInfo
- VkLayerTest.DynamicRenderingAndExecuteCommandsWithMismatchingDepthStencilImageViewFormat
- VkLayerTest.ValidateExtendedDynamicStateEnabled
- VkLayerTest.PrimitiveTopologyListRestart
- VkLayerTest.ValidateGeometryShaderEnabled
- VkLayerTest.IncompatibleScissorCountAndViewportCount
> Fix test issues encountered using Swiftshader

- layers/core_validation_error_enums.h
- layers/drawdispatch.cpp
as discussed in https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/5635#note_392038 this should just be `VUID-VkStridedDeviceAddressRegionKHR-size-04631` (it is not uncommon to have more than one spot produce the same VUID)
> layers: Label VkStridedDeviceAddressRegionKHR 04631 VU

- BUILD.md
- layers/CMakeLists.txt
- tests/vktestframework.cpp
> VS2015 is no longer supported
Here is my source in case someone needs it:
https://www.lunarg.com/wp-content/uploads/2023/01/Progress-Report-DEC2021-Vulkan-Ecosystem-Survey-Public-Report.pdf
> Deprecate Visual Studio 2015 - Completed
a. SDK and several repositories will no longer build, test, and support VS2015
> build: Remove VS2015 support

- layers/render_pass_state.cpp
I noticed this mistake, perhaps reflecting an older state of the spec. The current spec says this:
> If an attachment is not used by any subpass, `loadOp`, `storeOp`, `stencilStoreOp`, and `stencilLoadOp` will be ignored for that attachment, and no load or store ops will be performed. However, any transition specified by `initialLayout` and `finalLayout` will still be executed.
The code previously added the transition to `finalLayout` only if the attachment was used at least one subpass (via the `last` variable) but that is wrong.
> Apply render pass final transitions even if attachment is not used

- layers/best_practices_utils.cpp
- layers/descriptor_validation.cpp
- layers/pipeline_state.cpp
- layers/pipeline_state.h
- layers/shader_module.cpp
- layers/shader_module.h
- layers/shader_validation.cpp
- layers/synchronization_validation.cpp
Split `InterfaceVariables` into both `UserDefinedInterfaceVariable` and `ResourceInterfaceVariable` as they are used differently. Moved more logic into `ResourceInterfaceVariable` constructor which is done at `Entrypoint` creation time now once
> Make separate Interface Variables 

- tests/positive/descriptors.cpp
- tests/vklayertests_descriptor_renderpass_framebuffer.cpp
Also fix a compilation error seen on VS 2022 + release + -DBUILD_WERROR=ON.
NOTE: some of these fixes are for #4228.
> tests: Fix descriptor buffer tests

- layers/generated/chassis.h
- scripts/layer_chassis_generator.py
This should help with https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/5115.
Put the checks inside WrapNew/Unwrap to minimize code changes (even if generated). There are over 1000 usages of Unwrap. Far fewer use cases of WrapNew, but it was changed to be symmetrical to Unwrap.
> layers: Do not wrap/unwrap VK_NULL_HANDLE

- tests/vktestbinding.cpp
- tests/vktestbinding.h
- tests/vktestframework.cpp
That's interesting compilers did not report this before (and not only on macos).
> tests: Fix new CI warnings on macos-min-sdk

- tests/positive/other.cpp
- tests/vklayertests_others.cpp
- tests/vkrenderframework.cpp
With this the majority of the testing on MacOS passes.
> macos: Require VK_KHR_PORTABILITY_SUBSET_EXTENSION_NAME

- .git-blame-ignore-revs
- tests/positive/descriptors.cpp
- tests/positive/other.cpp
git 2.23 added a `--ignore-revs-file <file>` option
GitHub picks up this file name by default
> git: Add git-blame-ignore-revs file

- layers/core_validation.cpp
- layers/parameter_validation_utils.cpp
- layers/pipeline_validation.cpp
- layers/ray_tracing_validation.cpp
- layers/shader_validation.cpp
- layers/state_tracker.cpp
- layers/state_tracker.h
- layers/stateless_validation.h
Cleanup from working in the stateless files
> Use CMD_TYPE and consistent promotion variable names in stateless

- layers/device_memory_validation.cpp
- layers/generated/vk_extension_helper.h
- layers/gpu_validation.cpp
- layers/parameter_validation_utils.cpp
- scripts/helper_file_generator.py
- tests/layer_validation_tests.cpp
- tests/layer_validation_tests.h
- tests/positive/ray_tracing.cpp
- tests/vklayertests_command.cpp
- tests/vklayertests_descriptor_renderpass_framebuffer.cpp
- tests/vklayertests_others.cpp
- tests/vklayertests_pipeline_shader.cpp
- tests/vklayertests_ray_tracing.cpp
- https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/5105
Use `std::array` instead of `std::vector` where the change is straightforward. 
Used `layer_data::span` here: https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/5140/commits/2655edcc019e78564cf2dc0124f36af2e039a25f#diff-5d94eb97b814705828a8d76adbc1ae6b9f737b290575780736e7899cdc9fd7cdR5780
> Cleaning: convert const std::vector to std::array

- layers/generated/parameter_validation.cpp
- layers/stateless_validation.h
- scripts/parameter_validation_generator.py
- tests/vklayertests_descriptor_renderpass_framebuffer.cpp
- tests/vklayertests_others.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/5149
Adds proper support for
- `VUID-VkDescriptorSetLayoutBindingFlagsCreateInfo-pBindingFlags-parameter`
- `VUID-VkSubmitInfo-pWaitDstStageMask-parameter`
- `VUID-vkCmdSetColorWriteMaskEXT-pColorWriteMasks-parameter`
These are the only 3 things that use `ValidateFlagsArray`
> Add missing Flag Array parameter VU

- layers/generated/enum_flag_bits.h
- layers/generated/parameter_validation.cpp
- layers/generated/parameter_validation.h
- layers/parameter_validation_utils.cpp
- layers/render_pass_validation.cpp
- layers/stateless_validation.h
- scripts/parameter_validation_generator.py
- tests/vklayertests_dynamic_rendering.cpp
The `ValidateCmdBeginRendering` was growing quite large and there are some new VUs that need to be added, this first moves more checks to statelesss
> layers: Move some CmdBeginRendering VUs to stateless

- build-gn/generate_vulkan_layers_json.py
- layers/CMakeLists.txt
- layers/json/VkLayer_khronos_validation.json.in
- scripts/generate_source.py
- tests/layers/CMakeLists.txt
- tests/layers/VkLayer_device_profile_api.json.in
The `api_version` in the manifest shouldn't depend on the version of `Vulkan-Headers` we build against.
Helps Conan port and users who build against different `Vulkan-Headers` versions.
This also makes us consistent with the loader:
https://github.com/KhronosGroup/Vulkan-Loader/pull/1104
It also helps the GN build which hardcoded the `1.3`
closes #4973
> build: Update 'api_version' via `generate_source.py`

- layers/state_tracker/state_tracker.cpp
- tests/positive/image_buffer.cpp
- tests/vklayertests_buffer_image_memory_sampler.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/5163
> Add texelBufferAlignment support in 1.3

- layers/core_checks/pipeline_validation.cpp
- tests/vklayertests_graphics_library.cpp
- tests/vktestbinding.cpp
The spec says:
```
VUID-VkGraphicsPipelineCreateInfo-renderPass-06053
If renderPass is VK_NULL_HANDLE, the pipeline is being created with fragment shader state and fragment output interface state, and either of VkPipelineRenderingCreateInfo::depthAttachmentFormat or VkPipelineRenderingCreateInfo::stencilAttachmentFormat are not VK_FORMAT_UNDEFINED, pDepthStencilState must be....
```
```
VUID-VkGraphicsPipelineCreateInfo-renderPass-06054
If renderPass is VK_NULL_HANDLE, the pipeline is being created with fragment output interface state, and VkPipelineRenderingCreateInfo::colorAttachmentCount is not equal to 0, pColorBlendState must be .....
```
> layers: Check pipeline state for 06053 and 06054

- layers/core_checks/core_validation.cpp
- layers/core_checks/pipeline_validation.cpp
- layers/state_tracker/cmd_buffer_state.h
- layers/state_tracker/pipeline_state.h
- layers/state_tracker/state_tracker.cpp
- tests/vklayertests_others.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/5136
There is [future spec language](https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/5678) for this as well
The 3 main things done in the 2 layer commits
- Group all the checks in `ValidateGraphicsPipelineMultisampleState` that were dependent of the pipeline using `VK_DYNAMIC_STATE_RASTERIZATION_SAMPLES_EXT`
- Move the `GetNumSamples` from `PIPELINE_STATE` to `CMD_BUFFER_STATE` (and rename to `GetRasterizationSamples`)
- Track `vkCmdSetRasterizationSamplesEXT` value being set
> Fix dynamic rasterizationSamples

- layers/state_tracker/render_pass_state.cpp
The change as written causes CTS crashes, as it doesn't make changes to the consumers of the altered data structures.
Fixes #5157, but leaves issue identified by @Rua in https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/5054 unaddressed.
> Revert "layers: Apply render pass final transitions always"

- layers/core_checks/cmd_buffer_dynamic_validation.cpp
- layers/core_checks/core_validation.cpp
- layers/core_checks/core_validation.h
- layers/core_checks/drawdispatch_validation.cpp
- tests/vklayertests_command.cpp
- tests/vklayertests_pipeline_shader.cpp
- tests/vklayertests_viewport_inheritance.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/5135
These VUID were added in Vulkan 1.3.240 spec, they replace the old, overloaded, `VUID-vkCmdDraw-commandBuffer-02701` VUID
> layers: Relabel new Dynamic State VUIDs

- layers/CMakeLists.txt
This fixes build in mingw toolchain which does not support PDB file.
Here was the CMake Error:
Error evaluating generator expression:
$<TARGET_PDB_FILE:VkLayer_khronos_validation>
TARGET_PDB_FILE is not supported by the target linker.
> cmake: Check MSVC before installing PDB file

- layers/generated/vk_enum_string_helper.h
- scripts/helper_file_generator.py
The `string_***FlagBits()` family of functions format zero _***FlagBits_  variables as `"Unhandled FlagBits"` because zero is not a valid flag.
But zero is a valid value of _***Flags_ variable.
Previous Flags formatting:
"flags (Unhandled VkImageCreateFlags)"
New Flags formatting:
"flags (VkImageCreateFlags(0))"
The formatting of FlagBits remains unchanged.
> layers: Fix formatting of zero flags

- layers/core_checks/buffer_validation.cpp
- layers/vk_layer_utils.h
- tests/layer_validation_tests.cpp
- tests/layer_validation_tests.h
- tests/vklayertests_buffer_image_memory_sampler.cpp
- tests/vklayertests_others.cpp
- tests/vkrenderframework.cpp
- tests/vkrenderframework.h
VUIDs: 00920, 00990, 00991. (fixes part of https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/4539)
External memory types specified in buffer/image create info structures should be compatible.
The compatibility property also includes supported status. If a handle type is not supported, it is not reported as compatible (even with itself).
Fixes to existing tests where new VUs detected issues.
> VUIDs for external memory compatibility when creating resource

- layers/CMakeLists.txt
```
This checks MSVC before adding /DEF: linker option and
use the .def file as a source file for mingw toolchain.
Within binutils' ld, the .def file is added as any other
object file to the linker’s command line[1]. This is also
true in clang used in mingw environment.
Otherwise, the following error is shown in mingw:
c++: error: no such file or directory: '/DEF:C:/Vulkan-ValidationLayers/layers/VkLayer_khronos_validation.def'
[1]: https://sourceware.org/binutils/docs/ld/WIN32.html
```
> cmake: Fix using DEF file with mingw

- tests/vklayertests_gpu.cpp
err variable was being shadowed in testcase.  compiler update reported it.
> tests: Fix variable shadowing warning

- layers/best_practices/best_practices_error_enums.h
- layers/best_practices/best_practices_utils.cpp
- layers/state_tracker/descriptor_sets.h
- tests/vklayertests_best_practices.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/5167 (cc @zhangyiwei)
This will check, for example, if the `VkDescriptorPool` was created `VkDescriptorType` of `{SAMPLER, STORAGE_BUFFER}` but then when calling `vkAllocateDescriptorSets` with a `VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER` it will throw a best practice warning (if using `VK_KHR_maintenance1`/Vulkan 1.1)
> bp: Add DescriptorTypeNotInPool support

- layers/core_checks/cmd_buffer_dynamic_validation.cpp
- layers/core_checks/core_validation.h
- layers/core_checks/pipeline_validation.cpp
- layers/state_tracker/pipeline_state.h
- layers/stateless/parameter_validation_utils.cpp
- tests/positive/graphics_library.cpp
- tests/vklayertests_pipeline_shader.cpp
The combination of `VK_EXT_graphics_pipeline_library` / `VK_EXT_vertex_input_dynamic_state` / `VK_EXT_vertex_attribute_divisor` provides some awful edge cases, this addresses them
- Moves `VUID-VkVertexInputAttributeDescription-format-00623` to stateless (it's counterpart `VUID-VkVertexInputAttributeDescription2EXT-format-04805` is already in stateless)
- make sure `ValidatePipelineVertexDivisors()` (for `VK_EXT_vertex_attribute_divisor`) is not called unless a valid vertex input state is being used
- add missing `VUID-VkGraphicsPipelineCreateInfo-pVertexInputState-04910` label for `VK_EXT_vertex_input_dynamic_state`
- Group this logic all together
- Add `VkPositiveGraphicsLibraryLayerTest` version of other tests to make sure `VK_EXT_graphics_pipeline_library` enabled doesn't throw false …
> Fix Vertex Input Pipeline State

- layers/core_checks/shader_validation.cpp
- layers/gpu_validation/debug_printf.cpp
- layers/gpu_validation/debug_printf.h
- layers/gpu_validation/gpu_utils.cpp
- layers/gpu_validation/gpu_utils.h
- layers/gpu_validation/gpu_validation.cpp
- layers/state_tracker/shader_module.h
Reduce the number of `SHADER_MODULE_STATE` constructors to only what is needed
> layers: Remove extra SHADER_MODULE_STATE constructor

- layers/best_practices/best_practices_utils.cpp
- layers/core_checks/device_memory_validation.cpp
- layers/core_checks/shader_validation.cpp
- layers/core_checks/wsi_validation.cpp
- layers/core_error_location.h
- layers/gpu_validation/gpu_validation.cpp
- layers/state_tracker/cmd_buffer_state.cpp
- layers/state_tracker/queue_state.cpp
- layers/state_tracker/queue_state.h
- layers/stateless/parameter_validation_utils.cpp
- layers/sync/sync_validation.cpp
- layers/vk_layer_data.h
- tests/layer_validation_tests.cpp
- tests/layer_validation_tests.h
- tests/positive/image_buffer.cpp
- tests/positive/pipeline.cpp
- tests/positive/sync.cpp
- tests/vklayertests_buffer_image_memory_sampler.cpp
- tests/vklayertests_command.cpp
- tests/vklayertests_descriptor_renderpass_framebuffer.cpp
- tests/vklayertests_nvidia_best_practices.cpp
- tests/vklayertests_others.cpp
- tests/vklayertests_pipeline_shader.cpp
- tests/vklayertests_ray_tracing.cpp
- tests/vklayertests_video.cpp
- tests/vklayertests_wsi.cpp
- tests/vkrenderframework.cpp
Originally I was going to use `std::numeric_limits` or `vvl::MaxTypeValue` everywhere. But this made the code less readable in certain areas.
Instead I created `constexpr` constants in the vvl namespace for the most common use cases in vvl:
```c++
// Typesafe UINT32_MAX
constexpr auto kU32Max = std::numeric_limits<uint32_t>::max();
// Typesafe UINT64_MAX
constexpr auto kU64Max = std::numeric_limits<uint64_t>::max();
// Typesafe INT32_MAX
constexpr auto kI32Max = std::numeric_limits<int32_t>::max();
// Typesafe INT64_MAX
constexpr auto kI64Max = std::numeric_limits<int64_t>::max();
```
Note how `vvl::kU64Max` is the same amount of characters as `UINT64_MAX`
Also these constants are available from the vvl namespace
closes #3797
> layers: Remove macro constants for numeric limits

- layers/core_checks/cmd_buffer_dynamic_validation.cpp
- layers/generated/command_validation.cpp
- layers/generated/command_validation.h
- scripts/command_validation_generator.py
I realized the REAL issue with https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/5135 was the printing logic was wrong, before this PR it was
>  vkCmdDraw: VK_DYNAMIC_STATE_VIEWPORT|VK_DYNAMIC_STATE_SCISSOR|VK_DYNAMIC_STATE_LINE_WIDTH|VK_DYNAMIC_STATE_BLEND_CONSTANTS state not set for this command buffer
but not correctly is
> vkCmdDraw: VK_DYNAMIC_STATE_COLOR_BLEND_EQUATION_EXT state not set for this command buffer
> layers: Fix printing dynamic states

- layers/core_checks/buffer_validation.cpp
- layers/core_checks/image_validation.cpp
The original version tried to derive too much information from `VkExternalMemoryProperties::compatibleHandleTypes`. It tried to categorize situation as _not supported_ or _not compatible_ which is not something defined by spec and it's more safe just to say that flags are not reported as compatible (for support checks there is a separate bitmask `VkExternalMemoryProperties::externalMemoryFeatures`).
The original motivation to categorize between supported/compatible based on `VkExternalMemoryProperties::compatibleHandleTypes` flags is that some android devices report a flag as not compatible with itself even if it is reported as supported by `VkExternalMemoryProperties::externalMemoryFeatures`. It's violation of spec which states that each handle type flag **must** be compatible with …
> layers: Improve external memory messages

- tests/vkerrormonitor.cpp
- tests/vkerrormonitor.h
This makes the testing environment consistent and prevent new validation issues from being introduced only into Android testing.
closes #4673
> tests: Treat unexpected messages as errors on Android

- layers/state_tracker/pipeline_sub_state.h
- tests/positive/graphics_library.cpp
- tests/vklayertests_pipeline_shader.cpp
In the interest of unblocking and closing https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/5199 I made this change. This change is not fully correct and https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/5208 was created for me to handle this better once I fix the many other surrounding issues relate to Dynamic state mixed with GPL
> layers: Prevent crash for dynamic state with FragmentOutputState

- BUILD.gn
Missing valid_param_values.h source
Fixes #4228
> build: Fix BUILD.gn

- CMakeLists.txt
- tests/CMakeLists.txt
Layer code doesn't need this warning disabled.
> cmake: Apply -Wno-shorten-64-to-32 to tests only

- tests/layer_validation_tests.cpp
- tests/positive/image_buffer.cpp
- tests/positive/pipeline.cpp
- tests/positive/sync.cpp
- tests/vklayertests_buffer_image_memory_sampler.cpp
- tests/vklayertests_command.cpp
- tests/vklayertests_descriptor_renderpass_framebuffer.cpp
- tests/vklayertests_nvidia_best_practices.cpp
- tests/vklayertests_others.cpp
- tests/vkrenderframework.cpp
- tests/vkrenderframework.h
Cleaner than checking UINT32_MAX, and less error prone due to stricter type checking.
> tests: Return std::optional for QueueFamilyIndex

- tests/vklayertests_buffer_image_memory_sampler.cpp
- tests/vktestbinding.cpp
- tests/vktestbinding.h
Commit 1.  Reverts a3d60640e6f0cb403493d4744881b5e78a8955f8.
That change duplicates what `EXPECT(set_memory_type())` already does, and arguably `set_memory_type()` does it better because it checks only memory types supported by the resource but not all types. Successfully run local test session without this code.
Commit 2.  Adds optional `pNext` to create_info/allocate_info helpers which is similar to how `pNext` is used in other places (for example, `LvLInitStruct`).
Commit 3.  Allows to use `vk_testing::Buffer` and `vk_testing::Image` in the negative tests when BindMemory causes validation error.
Commit 4.  (thanks Juan!) Removes `DeviceMemory::alloc_info` which brings little value and instead `DeviceMemory::get_resource_alloc_info`  can provide  a larger chunk of functionality.
> Improve test helpers

- layers/state_tracker/pipeline_state.cpp
closes #5218 
The task/mesh shaders were not being accounted for when linking the GPL
> layers: Check for mesh/task stages from GPL

- layers/generated/valid_param_values.cpp
- scripts/parameter_validation_generator.py
- tests/positive/render_pass.cpp
Fix extension -> enum maps used when performing valid enum checks.
Closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/5222.
> layers: Fix valid enum check 

- layers/core_checks/device_memory_validation.cpp
- layers/vk_layer_utils.h
- tests/layer_validation_tests.cpp
- tests/layer_validation_tests.h
- tests/vklayertests_buffer_image_memory_sampler.cpp
- tests/vklayertests_others.cpp
Commit 1. Clean up and fixes of existing tests to make sure they will work with VU 00656.
Commit 2 and 3. Implement and test VUID 00656.
Fixes one item from https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/4539
VU 00656 is about external memory handle types associated with a _memory object_. The type of the handles should be supported and compatible as defined in the spec. Previously similar VUs 00920/00990 were implemented and they are concerned with the handle types associated with the _resource_ itself (buffer or image).
> Vuid exernal memory 00656

- layers/state_tracker/pipeline_state.h
Fixes a crash in dEQP-VK.pipeline.monolithic.shader_module_identifier.pipeline_from_id.*
> Initialize descriptor_variables in synchronization validation

- layers/core_checks/cmd_buffer_dynamic_validation.cpp
- layers/core_checks/pipeline_validation.cpp
- layers/state_tracker/cmd_buffer_state.cpp
- layers/state_tracker/cmd_buffer_state.h
- layers/state_tracker/state_tracker.cpp
- tests/positive/graphics_library.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/5235 
I added a tests that tries and set the pipeline topology differently in the non vertex GPL libraries and makes sure the `VK_DYNAMIC_STATE_PRIMITIVE_TOPOLOGY` is running as expected
cleaned up the related code areas while at it
> layers: Test VK_DYNAMIC_STATE_PRIMITIVE_TOPOLOGY with GPL

- .github/workflows/build_android.yml
- .github/workflows/build_linux.yml
- .github/workflows/build_macos.yml
- .github/workflows/build_windows.yml
GitHub docs for reference:
https://docs.github.com/en/actions/using-jobs/using-concurrency
By default GitHub actions doesn't cancel old runs of workflows.
With the new `concurrency` support you can cancel in progress runs now.
This makes it so you don't have to manually cancel old runs when you force push. IE saving CI/developer time.
> ci: Use concurrency to prevent duplicate jobs for workflows

- CMakeLists.txt
This allows us to being the process of integrating clang-tidy into our CI process.
The [Makefile Generators](https://cmake.org/cmake/help/latest/manual/cmake-generators.7.html#makefile-generators) and the [Ninja](https://cmake.org/cmake/help/latest/generator/Ninja.html#generator:Ninja) generator will run this tool along with the compiler and report a warning if the tool reports any problems.
For VS and XCode users it looks like this clang-tidy cannot be run as part of the build:
https://discourse.cmake.org/t/how-to-add-clang-tidy-to-open-source-project/7311
>  the VS and XCode buildsystems don’t support running arbitrary commands to compile a file, which is required to run clang-tidy. This is beyond our control. 
However, VS and XCode both recognize clang-tidy and will display the …
> cmake: Add VVL_CLANG_TIDY

- layers/core_checks/render_pass_validation.cpp
pResolveAttachments from VkSubpassDescription can either be null or an array to of size colorAttachmentCount. When checking for VUID-06508, we weren't checking for if pResolveAttachments was null before iterating it.
> Fix crash in layers if pResolveAttachments/pDepthStencilAttachments are null and VkSubpassFragmentDensityMapOffsetEndInfoQCOM is used

- layers/core_checks/core_validation.h
- layers/core_checks/device_memory_validation.cpp
- layers/core_checks/synchronization_validation.cpp
- tests/layer_validation_tests.cpp
- tests/layer_validation_tests.h
- tests/vklayertests_buffer_image_memory_sampler.cpp
- tests/vklayertests_others.cpp
That's almost identical to external memory support and compatibility for images/buffers, but now for fences and semaphores.
Some variable naming clean up.
Closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/4539
> VUIDs for external fence and semaphore

- scripts/parameter_validation_generator.py
The files are currently generated regardless of the directory passed to `lvl_genvk.py`, which seems like an oversight.
> scripts: Use generated directory when writing valid_param_values

- tests/positive/image_buffer.cpp
- tests/positive/pipeline.cpp
- tests/positive/render_pass.cpp
- tests/vklayertests_buffer_image_memory_sampler.cpp
- tests/vklayertests_descriptor_renderpass_framebuffer.cpp
- tests/vklayertests_pipeline_shader.cpp
- tests/vklayertests_wsi.cpp
- tests/vkrenderframework.cpp
- tests/vkrenderframework.h
Replaced `InitFrameworkAndRetrieveFeatures` for the new `AddRequiredExtensions` and `GetPhysicalDeviceFeatures2` helper functions used in testing
> tests: Remove InitFrameworkAndRetrieveFeatures

- layers/core_checks/core_validation.h
- layers/core_checks/drawdispatch_validation.cpp
- layers/core_checks/pipeline_validation.cpp
- layers/state_tracker/cmd_buffer_state.h
- layers/state_tracker/state_tracker.cpp
- layers/stateless/parameter_validation_utils.cpp
- tests/layer_validation_tests.cpp
- tests/vklayertests_others.cpp
Adds the 4 draw time VUs
- `VUID-vkCmdDraw-stippledLineEnable-07495`
- `VUID-vkCmdDraw-stippledLineEnable-07496`
- `VUID-vkCmdDraw-stippledLineEnable-07497`
- `VUID-vkCmdDraw-stippledLineEnable-07498`
Fixes the Pipeline creation VUs (`VkGraphicsPipelineCreateInfo` and `VkPipelineRasterizationLineStateCreateInfoEXT`) to not check `lineRasterizationMode` or `stippledLineEnable` if they are dynamic state
> Add dynamic VK_EXT_line_rasterization

- layers/best_practices/best_practices_utils.cpp
- layers/best_practices/best_practices_validation.h
- layers/core_checks/core_validation.h
- layers/core_checks/pipeline_validation.cpp
- layers/core_checks/shader_validation.cpp
- layers/state_tracker/pipeline_state.cpp
- layers/state_tracker/pipeline_state.h
- layers/state_tracker/shader_module.h
- layers/state_tracker/state_tracker.cpp
- layers/state_tracker/state_tracker.h
The main thing this PR became was adding the index of `pCreateInfos`  of the pipeline to the `PIPELINE_STATE` and then updating and improving the error messages to help locate **where** the error occurred
> Pipeline Validation error message cleanup

- layers/CMakeLists.txt
KHRONOS_LAYER_COMPILE_DEFINITIONS isn't set anywhere
> cmake: Remove unused CMake code

- CMakeLists.txt
- layers/CMakeLists.txt
- tests/CMakeLists.txt
- tests/layers/CMakeLists.txt
Makes fixing warnings more feasible. Since you can tackle the problem one target at a time, instead of having to fix the entire project
> cmake: Disable warnings on a per target basis

- layers/best_practices/best_practices_utils.cpp
dEQP-VK.pipeline.monolithic.shader_module_identifier.pipeline_from_id.compute.1_variants.no_spec_constants.no_pipeline_cache.use_id.capture_irs.comp
> Fix crash in CreateComputePipelines best practices validation

- layers/core_checks/descriptor_validation.cpp
This was a spec bug, will be in next header update 
https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/5681/
> layers: Fix 08018 to include INLINE_UNIFORM_BLOCK

- tests/positive/image_buffer.cpp
- tests/vklayertests_descriptor_renderpass_framebuffer.cpp
- tests/vklayertests_imageless_framebuffer.cpp
- tests/vklayertests_wsi.cpp
Clean up some tests in order for Profile layer and MockICD to run with them
`MultisampledRenderToSingleSampled` and `RenderPassCreateFragmentDensityMapReferenceToInvalidAttachment` were not valid tests (not being tested in CI it seems)
> tests: Fix tests for use with Profile layer

- layers/core_checks/descriptor_validation.cpp
The spec is
```
ifndef::VK_EXT_fragment_density_map[]
* [[VUID-vkGetDescriptorEXT-dataSize-08120]]
pname:dataSize must: equal the size of a descriptor of type...
endif::VK_EXT_fragment_density_map[]
ifdef::VK_EXT_fragment_density_map[]
* [[VUID-vkGetDescriptorEXT-dataSize-08125]]
pname:dataSize must: equal the size of a descriptor of type...
endif::VK_EXT_fragment_density_map[]
```
> layers: Fix extension wrapping VUID 08120

- layers/core_checks/copy_blit_resolve_validation.cpp
- tests/vklayertests_command.cpp
This was updated in the 1.3.241 spec ([internal change](https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/5676))
Change to
- VUID-VkResolveImageInfo2-srcImage-04446
- VUID-vkCmdResolveImage-srcImage-04446
- VUID-VkResolveImageInfo2-srcImage-04447
- VUID-vkCmdResolveImage-srcImage-04447
> layers: Fix 3D image Resolve VU

- layers/core_checks/cmd_buffer_validation.cpp
- layers/core_checks/core_validation.h
- layers/state_tracker/cmd_buffer_state.h
- tests/vklayertests_others.cpp
- tests/vktestbinding.h
Check to see that each "EndLabel" has a corresponding "BeginLabel."
Closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/5230.
> layers: Add 01912, 01913

- CMakePresets.json
VS Code uses `out` directory by default. This PR suggests to use `build` name instead.
When mixing command line and IDE development, it was possible to end up with two build directories which might be confusing. It also allows to switch to IDE after command line session without rebuilding (assuming build settings in the preset match the command line settings).
> cmake: Set default build directory for presets

- layers/core_checks/device_validation.cpp
- layers/core_checks/pipeline_validation.cpp
- tests/device_profiles/max_profile.json
- tests/device_profiles/pixel_6_adreno.json
- tests/device_profiles/pixel_6_mali.json
- tests/positive/other.cpp
- tests/positive/pipeline.cpp
- tests/positive/shaderval.cpp
- tests/vklayertests_buffer_image_memory_sampler.cpp
- tests/vklayertests_command.cpp
- tests/vklayertests_others.cpp
- tests/vklayertests_pipeline_shader.cpp
- tests/vklayertests_query.cpp
- tests/vklayertests_wsi.cpp
Along with https://github.com/KhronosGroup/Vulkan-Tools/pull/745 this change adds about 60 tests to run on the Max Profile CI run (runs 1438 tests, skips 284)
Also fixed 2 bugs in the code not caught from tests not being ran
> Improve test coverage with Max Profile

- layers/core_checks/core_validation.h
- layers/core_checks/descriptor_validation.cpp
- layers/core_checks/shader_validation.cpp
- layers/state_tracker/pipeline_state.cpp
- layers/state_tracker/pipeline_state.h
- layers/state_tracker/shader_module.cpp
- layers/state_tracker/shader_module.h
- layers/sync/sync_validation.cpp
In the attempt to fix https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/5302 I ran into some spec clarification issues that need to be resolved first. This PR pulls out the "clean up" part of the change I was planning to make. 
The goal is nothing functional should have change in this PR and make the next PR have less noise to review
> Cleanup OpVariable access status code

- layers/stateless/parameter_validation_utils.cpp
Improves the error messages in `StatelessValidation::ValidateAccelerationStructureBuildGeometryInfoKHR` to give information about which index into the call caused the issue (and if it was `pGeometries` or `ppGeometries` causing it)
> layers: Improve AccelerationStructureBuildGeometryInfoKHR

- layers/vk_layer_logging.h
- tests/layer_validation_tests.cpp
- tests/layer_validation_tests.h
- tests/positive/command.cpp
Closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/5172
The attached regression test causes a crash on most runs both on linux and windows when the fix is not applied.
> Fix debug label segfault

- tests/device_profiles/max_profile.json
- tests/layer_validation_tests.cpp
- tests/layer_validation_tests.h
- tests/positive/ray_tracing.cpp
- tests/vklayertests_buffer_image_memory_sampler.cpp
- tests/vklayertests_descriptor_renderpass_framebuffer.cpp
- tests/vklayertests_ray_tracing.cpp
- tests/vklayertests_ray_tracing_pipeline.cpp
waiting on https://github.com/KhronosGroup/Vulkan-Tools/pull/747
Adds about 50+ tests and allows for testing most Ray Tracing without needing a supported physical device
> tests: Add MockICD support for Ray Tracing tests

- .github/workflows/vvl.yml
Currently if 2 PRs are merged in near the same time. The new job cancels the older one on main.
> ci: Fix issue of workflows being cancelled on main

- layers/convert_to_renderpass2.cpp
- layers/convert_to_renderpass2.h
- layers/core_checks/render_pass_validation.cpp
- layers/core_checks/synchronization_validation.cpp
- layers/generated/parameter_validation.cpp
- layers/state_tracker/render_pass_state.cpp
- layers/stateless/parameter_validation_utils.cpp
- layers/stateless/stateless_validation.h
- scripts/parameter_validation_generator.py
- tests/layer_validation_tests.cpp
- tests/vklayertests_descriptor_renderpass_framebuffer.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/2661
The spec says for `VkSubpassDependency2`
> If a [VkMemoryBarrier2](https://registry.khronos.org/vulkan/specs/1.3-extensions/html/vkspec.html#VkMemoryBarrier2) is included in the pNext chain, **srcStageMask**, **dstStageMask**, **srcAccessMask**, and **dstAccessMask** parameters are ignored. The synchronization and access scopes instead are defined by the parameters of [VkMemoryBarrier2](https://registry.khronos.org/vulkan/specs/1.3-extensions/html/vkspec.html#VkMemoryBarrier2).
We are already doing this in the Sync validation, but were not doing it in the parameter checking
some other notes about the PR/
- the `UNASSIGNED` were bogus, so removed
- `ConvertVkRenderPassCreateInfoToV2KHR` was not being used in the …
> Ignore fields with VkMemoryBarrier2 pNext

- layers/core_checks/core_validation.h
- layers/core_checks/shader_validation.cpp
- tests/device_profiles/max_profile.json
- tests/vklayertests_pipeline_shader.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/5323
Checks for `VUID-FullyCoveredEXT-conservativeRasterizationPostDepthCoverage-04235`
> Add conservativeRasterizationPostDepthCoverage check

- layers/core_checks/synchronization_validation.cpp
- layers/core_error_location.h
- tests/vklayertests_external_memory_sync.cpp
Resurrection of https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/3168.
I cannot re-open the original PR because it's on the old  `master` branch.
The goal is to address here the comments from the original PR.
Closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/4970
> Vuid 00080 00079

- tests/layer_validation_tests.cpp
- tests/layer_validation_tests.h
- tests/positive/sync.cpp
- tests/vklayertests_external_memory_sync.cpp
- tests/vklayertests_others.cpp
removed `CheckTimelineSemaphoreSupportAndInitState` because
- `GetPhysicalDeviceFeatures2` can be used
- new Profile CI make sure `maxTimelineSemaphoreValueDifference` is non-zero
> tests: Remove TimelineSemaphore custom helper

- layers/core_checks/core_validation.h
- layers/core_checks/descriptor_validation.cpp
- layers/core_checks/drawdispatch_validation.cpp
- tests/vklayertests_command.cpp
The 1.3.242 spec added `VUID-vkCmdDraw-None-07888` (and other draw/dispatches)
> layers: Label Buffer View Atomic VUID

- tests/device_profiles/max_profile.json
- tests/vklayertests_video.cpp
With https://github.com/KhronosGroup/Vulkan-Tools/pull/750 adds support for most Video tests to run on the Max Profile CI
brings testing to **1571** pass, **158** skipped
> tests: Add Video to Max Profile CI

- layers/core_checks/core_validation.h
- layers/core_checks/shader_validation.cpp
- layers/state_tracker/pipeline_state.cpp
- layers/state_tracker/pipeline_state.h
- layers/state_tracker/shader_module.cpp
- layers/state_tracker/shader_module.h
(related https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/5302 / https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/5310#discussion_r1111734088)
The logic for `VUID-RuntimeSpirv-NonWritable-06340` and `VUID-RuntimeSpirv-NonWritable-06341` was not fully complete
This PR does a few cleanup 
1. creates a dedicated `ValidateShaderDescriptorVariable` function 
2. add proper tracking for the type of resource (ex `is_storage_image`) needed for the moment (will add rest in future PR)
3. Fix the above 2 VUID logic
> layers: Fix shader module tracking of NonWritable

- BUILD.md
- build-android/build_all.sh
Seems the `jarsigner` was removed in recent Android SDK Build-Tools
> build: Use apksigner for Android APK

- tests/positive/descriptors.cpp
- tests/vktestbinding.cpp
- tests/vktestbinding.h
Closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/5121
Please note that reverting https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/4994 does not fail this test (@jeremyg-lunarg ). There are earlier checks in the code that ensure regression does not happen:
* `QueueWaitIdle` marks command buffer as not in use.
* Tried fence wait instance of `QueueWaitIdle` - also does not trigger the issue.
* When `vkBeginCommandBuffer` is called the second time (with the same command buffer), it resets the command buffer, and `CMD_BUFFER_STATE::ResetCBState` removes the bindings' command buffer reference.
> tests: Add regress for VU 03047

- layers/core_checks/core_validation.h
- layers/core_checks/shader_validation.cpp
- layers/state_tracker/shader_module.cpp
- layers/state_tracker/shader_module.h
Instead of keeping a list of Input attachments per Entrypoint, this just moves it to the Interface Variable itself. This is nice because future change needs to be able to map which index is which variable, and currently this was an extra step
> layers: Move input attachment to ResourceInterfaceVariable

- layers/core_checks/image_validation.cpp
- tests/positive/command.cpp
- tests/vklayertests_command.cpp
- tests/vklayertests_dynamic_rendering.cpp
- tests/vkrenderframework.cpp
The [1.3.242 spec update](https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/5348) removed `VUID-vkCmdClearAttachments-pAttachments-07270` and split it up as
- VUID-vkCmdClearAttachments-aspectMask-07884
- VUID-vkCmdClearAttachments-aspectMask-07885
- VUID-vkCmdClearAttachments-aspectMask-07886
- VUID-vkCmdClearAttachments-aspectMask-07887
The main change is
- The aspect mask is ignore, the image view format is what is important
- Color attachments don't have the restriction (allows to clear a plan of a multi-planar image)
- Dynamic rendering never gets to this situation because it will be cause before since it has a dedicated depth and stencil attachment instead of a shared `pDepthStencilAttachment`
> layers: Fix vkCmdClearAttachment aspect mask VU

- layers/core_checks/device_validation.cpp
- layers/state_tracker/state_tracker.cpp
When support for VK_KHR_format_feature_flags2 was added to the validation layers it assumed it's always supported when vkGetPhysicalDeviceFormatProperties2[KHR] is supported.
This fixes this assumption and will make the validation layer function properly again on implementations supporting Vulkan 1.1 or GPDP2, but not VK_KHR_format_feature_flags2.
> layers: Fix assumption that VK_KHR_format_feature_flags2 is always supported

- layers/core_checks/queue_validation.cpp
- tests/vklayertests_command.cpp
This request fixes the issue: https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/5363
> Fix ignoring VUID-VkSubmitInfo-pNext-04120 error

- layers/core_checks/shader_validation.cpp
SHADER_MODULE_STATE::GetBaseType returns zero when passed a physical storage buffer to a struct, which later results in a validation error, despite no check whether structs passed between shader stages are compatible. This change suppresses the validation error.
Conceptually, this change addresses a wider spectrum of cases, where in the `TypesMatch` function we failed to identify both of the compared types, and would return `false` (types don't match). Currently the only clear path for this to happen is dealing with a physical storage buffer to a struct, in which case a potentially unhelpful validation error is produced:
```
Validation Error: [ UNASSIGNED-CoreValidation-Shader-InterfaceTypeMismatch ] Object 0: handle = 0x9294aa0000036c76, type = VK_OBJECT_TYPE_SHADER_MODULE; | MessageID = …
```
> layers: Suppress incorrect validation error for buffer_reference

- tests/layer_validation_tests.cpp
- tests/vklayertests_best_practices.cpp
- tests/vklayertests_command.cpp
- tests/vklayertests_image.cpp
- tests/vklayertests_instanceless.cpp
- tests/vklayertests_memory.cpp
- tests/vklayertests_others.cpp
- tests/vklayertests_wsi.cpp
- tests/vkrenderframework.cpp
- tests/vkrenderframework.h
`std::vector<const char *> &m_instance_extension_names = instance_extensions_;  // compatibility alias name` seems like a useless thing to keep around
there are more instances of `m_instance_extension_names` so decided to keep it (also it matches `m_device_extension_names`)
Happy to rename the member variable to be consistent with each other later, but having 2 variables alias make it hard to search for anything
(also `InstanceExtensionEnabled` is not used so removed)
> tests: Clean up instance extension names

- layers/core_checks/shader_validation.cpp
- layers/state_tracker/shader_module.cpp
- layers/state_tracker/shader_module.h
The error message for mismatch interfaces was not that helpful as it gets more complex
Vertex shader
```glsl
layout(buffer_reference) buffer T0 {
int x[3];
};
layout(buffer_reference) buffer T1 {
int y;
float z[2];
T0 w[2];
};
layout(set = 0, binding = 0) layout(buffer_reference) buffer dataBuffer {
int a;
int b;
T1 c;
};
```
Error message before
> Validation Error: [ UNASSIGNED-CoreValidation-Shader-InterfaceTypeMismatch ] Object 0: handle = 0xee647e0000000009, type = VK_OBJECT_TYPE_SHADER_MODULE; | MessageID = 0xb6cf33fe | vkCreateGraphicsPipelines(): pCreateInfos[0] Type mismatch on location 0.0, between vertex shader and fragment shader: 'ptr to Output ptr to PhysicalStorageBuffer struct of (sint32, sint32, ptr to PhysicalStorageBuffer struct of (sint32, arr[2] of float32, ptr to …
> layers: Print better error for interface match

- tests/vklayertests_wsi.cpp
- tests/vkrenderframework.cpp
- tests/vkrenderframework.h
Most tests only need 1 swapchain & 1 surface, however a few tests create multiple surfaces and swapchains. This commit cleans up the code which handles that, separating the logic to initialize the swapchain, surface, and related variables that live inside of the VkRenderFramework from the actual logic necessary to do so. The result is a host of 'Create' functions that take variables by reference and initialize them with the appropriate calls. Then the 'Init' functions are used by tests to call the corresponding 'Create' call with the VkRenderFramework's variables as the destination of the functions.
This allows test which want to create additional swapchains and surface the ability to do so without overwriting the VkRenderFramework variables and later on clean up the created objects. …
> tests: Cleanup swapchain & surface creation

- tests/positive/image_buffer.cpp
- tests/vklayertests_memory.cpp
While the spec does say that mapped memory is automatically unmapped when the allocation is freed, the MockICD will leak memory if we do not call unmap memory. Thus to allow tests to run cleanly with leak sanitizer, this test should unmap memory before exiting.
> tests: Unmap memory which was mapped

- layers/generated/chassis.cpp
- layers/generated/chassis.h
- scripts/layer_chassis_generator.py
This commit makes it so that only validation objects that will be used will be created. This prevents the need of manually removing unused objects.
In addition, cleanup code was added when an error is detected, thus preventing the leaking of ValidationObjects, debug_report_data, and copied pNext chains.
Lastly, the various 'init' functions of the ValidationObject have been deleted by having their contents moved into the vkCreateInstance/vkCreateDevice functions instead of having a separate function.
> chassis: Cleanup ValidationObject creation

- layers/state_tracker/render_pass_state.cpp
- layers/sync/sync_validation.cpp
- layers/sync/sync_validation.h
VK_EXT_image_2d_view_of_3d is not supported by syncval at this time, but this changed causes depth sliced views to be ignored inside of asserting on their presence.  Fixes #4536.
> Remove crash caused by use of VK_EXT_image_2d_view_of_3d

- layers/core_checks/core_validation.h
- layers/core_checks/descriptor_validation.cpp
- layers/core_checks/drawdispatch_validation.cpp
- layers/core_checks/pipeline_validation.cpp
- layers/core_checks/shader_validation.cpp
- layers/core_checks/shader_validation.h
- layers/gpu_validation/gpu_utils.cpp
- layers/state_tracker/pipeline_state.cpp
- layers/state_tracker/pipeline_state.h
- layers/sync/sync_validation.cpp
- tests/vklayertests_pipeline_shader.cpp
This is in preparation for a much bigger change coming after
- Remove the `shader_stage_attributes`, it wasn't needed
- `shader_state` -> `shader_states` as it was hard to search or realize it was a vector
- Make it more clear what is a `VkPipelineShaderStageCreateInfo` struct, everything has the word `stage` in it so calling it `pStage` is not helpful for searching or code readability
> Shader validation cleanup

- .github/workflows/vvl.yml
- CMakeLists.txt
- layers/CMakeLists.txt
- layers/vk_layer_logging.cpp
- tests/test_common.h
Fixes regression caused by be666f39c462905ef245d88ff8f36bc8a8e7cf8e
In order to prevent further regressions to MinGW add it to CI.
- build: Fix MinGW winsock2.h warning
- cmake: Fix MINGW build regression
- ci: Add MinGW to github actions CI
> Fix MINGW build and add MINGW to CI

- layers/sync/sync_validation.cpp
- layers/sync/sync_validation.h
The Destroy call was calling ResetCBState() which results in Reset() being called. Reset adds in a self reference which causes a cycle in the shared_ptr's. Calling Destroy instead cleans everything up properly and doesn't leak any memory.
> sync: Call Destroy instead of Reset

- tests/layer_validation_tests.cpp
- tests/positive/command.cpp
- tests/positive/pipeline.cpp
- tests/vklayertests_amd_best_practices.cpp
- tests/vklayertests_arm_best_practices.cpp
- tests/vklayertests_best_practices.cpp
- tests/vklayertests_command.cpp
- tests/vklayertests_debug_printf.cpp
- tests/vklayertests_dynamic_rendering.cpp
- tests/vklayertests_nvidia_best_practices.cpp
- tests/vklayertests_pipeline_shader.cpp
- tests/vklayertests_portability_subset.cpp
- tests/vkrenderframework.cpp
- tests/vkrenderframework.h
- tests/vksyncvaltests.cpp
In most places the code works with uint32_t width and height. This change replaces many float->uint32 casts with only a few uint32->float casts.
> tests: Make width and height uint32

- layers/core_checks/pipeline_validation.cpp
`pCreateInfos` is an array of the create info, so currently only the first create info was being validated for `VUID-VkComputePipelineCreateInfo-pipelineCreationCacheControl-02875`
The other `ValidatePipelineCacheControlFlags` are doing this correctly
> layers: Fix PipelineCacheControlFlags bug

- layers/core_checks/drawdispatch_validation.cpp
- layers/core_checks/pipeline_validation.cpp
- layers/core_checks/ray_tracing_validation.cpp
- layers/core_checks/shader_validation.cpp
- layers/gpu_validation/gpu_utils.cpp
- layers/state_tracker/pipeline_state.cpp
- layers/state_tracker/pipeline_state.h
This change does 2 main things
1. Moves logic to member variables of `PIPELINE_STATE` that are part of the Create Info struct. These are constantly being queried and checking which sType, but we know this information at init time
2. Moves more away from using `stage_states` to indirectly get the information already known in create info (main idea is `stage_states` is re-doing a lot of work and future goal is to trim it down more)
> layers: Move more to PIPELINE_STATE init

- CMakeLists.txt
- layers/CMakeLists.txt
4189 and 5038 are pretty valuable warnings to also have for the testing code.
> cmake: Enable MSVC warnings 4189 and 5038 consistently

- .github/workflows/vvl.yml
The main intent here is to prevent niche MinGW warnings like 08ce2e77f92c6e09a75a1d686e0e2438ed783053
And given MinGW uses GCC there isn't much work to maintain this
> ci: Warnings as errors for MinGW build

- layers/core_checks/core_validation.h
- layers/core_checks/pipeline_validation.cpp
creates a `ValidatePipelineDerivatives` function to do all pipeline derivatives logic
> layers: Move Pipeline Derivatives to own function

- layers/core_checks/core_validation.h
- layers/core_checks/pipeline_validation.cpp
Tries to move more things out of `ValidatePipeline` and into better isolated functions
also adds a `ValidateGraphicsPipelineDepthStencilState`
> layers: Move pipeline check into correct function

- layers/core_checks/android_validation.cpp
- layers/core_checks/core_validation.h
- layers/core_checks/image_layout_validation.cpp
- layers/core_checks/image_validation.cpp
- layers/core_checks/render_pass_validation.cpp
`debug_report_data` was not being used in `ValidateCreateImageANDROID` or `ValidateLayoutVsAttachmentDescription`
> layers: Remove unused debug_report_data

- layers/core_checks/copy_blit_resolve_validation.cpp
- layers/core_checks/core_validation.h
went trough `copy_blit_resolve_validation.cpp` and added `LogObjectList` wherever it was missing objects that would be valuable to print out
> layers: Add LogObjectList to copy blit resolve

- layers/core_checks/shader_validation.cpp
`PIPELINE_STATE` already has a bool to know if `VkPipelineShaderStageModuleIdentifierCreateInfoEXT` was used to create the pipeline
> layers: Use PIPELINE_STATE uses_shader_module_id

- .github/workflows/vvl.yml
- layers/generated/chassis.h
- scripts/layer_chassis_generator.py
Properly fixes formatting warnings for MinGW instead of ignoring them.
Credit to @Biswa96 for the proper fix
> mingw: Fix formatting warnings

- layers/core_checks/pipeline_validation.cpp
- layers/state_tracker/pipeline_state.cpp
- layers/state_tracker/pipeline_state.h
- layers/stateless/parameter_validation_utils.cpp
- tests/positive/dynamic_rendering.cpp
- tests/positive/shaderval.cpp
- tests/vklayertests_debug_printf.cpp
- tests/vklayertests_dynamic_rendering.cpp
- tests/vklayertests_gpu.cpp
- tests/vklayertests_graphics_library.cpp
- tests/vklayertests_pipeline_shader.cpp
- tests/vkrenderframework.h
This change also fixes GPL sub-state tracking where some sub-states are
allowed to be missing. Specifically:
- Vertex input state is not necessary if there is no vertex shader
present
- Fragment shader/output state is not necessary if rasterizer discard
enabled
> layers: Fix 00751 check

- scripts/common_ci.py
Current CI logic broken by: https://github.com/KhronosGroup/Vulkan-Profiles/pull/377
> ci: Fix profiles CI

- layers/sync/sync_validation.h
Record only the needed information in the log, without the reference to the queue batch context, by storing the base class information only.
> sync: Remove circular shared_ptr reference between log and queue batch context

- .github/workflows/vvl.yml
- scripts/common_ci.py
- tests/CMakeLists.txt
- tests/layer_validation_tests.h
- tests/vklayertests_wsi.cpp
- tests/vksyncvaltests.cpp
This commit enabled Address Sanitizer in github actions CI runs. 
Currently, only Linux will have ASAN enabled with the MockICD.
ASAN requires enabling it in the loader with the option to disable unloading of dynamic libraries which enables useful stack traces.
Because leaks are unavoidable in certain circumstances, a mechanism has been setup to allow tests to disable leak detection if need be. The current tests which require this are:
* VkSyncValTest.SyncQSPresentAcquire - known leak with fix incoming
* VkLayerTest.LeakASwapchain - intentionally leaks memory to trigger test case
To disable leak checking in a test, add the following to the start of a test.
```
#if defined(VVL_ENABLE_ASAN)
auto leak_sanitizer_disabler = __lsan::ScopedDisabler();
#endif
```
__lsan::ScopedDisabler() is a …
> ci: Enable Address Sanitizer

- scripts/object_tracker_generator.py
vk.xml now properly sets the Device as the parent of the Swapchain
> scripts: Remove vk.xml workaround

- tests/vklayertests_external_memory_sync.cpp
- tests/vktestbinding.cpp
- tests/vktestbinding.h
With current spec (1.3.242) the validation of VU 00656 can be done only in vkBindMemory. With invalid input (e.g. handle type is not supported for any resource) vkAllocateMemory can legally fail. This does not give a chance for validation to run. This fix detects vkAllocateMemory failure and skips the test since validation is not possible.
> tests: Fix external memory tests for swiftshader

- layers/core_checks/shader_validation.cpp
- layers/state_tracker/shader_module.cpp
- layers/state_tracker/shader_module.h
- tests/positive/pipeline.cpp
https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/5366 didn't have a test with `InputAttachmentIndex` set to a non-zero value. @Tony-LunarG pointed out from a CTS test there was a bug which was because I added the offset where not needed
> layers: Fix if InputAttachmentIndex is non-zero

- tests/positive/sync.cpp
This test would corrupt the stack by only creating a single objects worth of space to query the display properties, but would then request the prop_count number of properties.
> tests: Fix ThreadSafetyDisplayObjects

- layers/android_ndk_types.h
- layers/best_practices/best_practices_error_enums.h
- layers/cast_utils.h
- layers/core_checks/shader_validation.h
- layers/core_validation_error_enums.h
- layers/generated/vk_extension_helper.h
- layers/gpu_shaders/gpu_shaders_constants.h
- layers/hash_util.h
- layers/hash_vk_types.h
- layers/sparse_containers.h
- layers/state_tracker/descriptor_sets.h
- layers/state_tracker/image_layout_map.h
- layers/state_tracker/shader_module.h
- layers/stateless/parameter_name.h
- layers/subresource_adapter.h
- scripts/helper_file_generator.py
- tests/icd-spv.h
- tests/layer_validation_tests.h
- tests/layers/vk_lunarg_device_profile_api_layer.h
- tests/vklayertests_video.h
- tests/vktestbinding.h
The code is using #pragma once in most headers, but some still had include guards, and most perplexingly some had both.
> style: Use #pragma once everywhere

- layers/core_checks/copy_blit_resolve_validation.cpp
- layers/core_checks/pipeline_validation.cpp
- tests/vklayertests_descriptor_renderpass_framebuffer.cpp
- `VUID-VkCopyImageToBufferInfo2-None-07930` was label wrong (and VUID like it)
- `VUID-vkCmdBindPipeline-pipeline-06856` was moved to a draw time error now (adding back in future PR)
> layers: More fixes for 243 header

- build-android/jni/Android.mk
- tests/CMakeLists.txt
- tests/positive/gpu_av.cpp
For https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/5321
adds tests to help debug issue by using push descriptors with GPU-AV
> tests: Add Positive GPU-AV push descriptor

- scripts/known_good.json
- scripts/update_deps.py
`update_deps.py` wouldn't specify `CMAKE_BUILD_TYPE` on Windows builds. Which breaks the new CI process, which uses Ninja for both Linux/Windows.
The fix is simple.
I made a change to `known_good.json` to ensure the ci cache is flushed, and it helps perf a little bit.
> Fix WIN32 CI

- layers/core_checks/pipeline_validation.cpp
- layers/core_checks/shader_validation.cpp
- layers/state_tracker/pipeline_state.cpp
- layers/state_tracker/pipeline_state.h
- layers/state_tracker/pipeline_sub_state.cpp
- layers/state_tracker/pipeline_sub_state.h
- tests/vklayertests_graphics_library.cpp
There are VUs that say
> If the pipeline is being created with [pre-rasterization shader state](https://registry.khronos.org/vulkan/specs/1.3-extensions/html/vkspec.html#pipelines-graphics-subsets-pre-rasterization)
But currently we were checking all stages, including those being linked in
Adding the `HasSameParent` function allows us to know only to check if the pipeline was created with the state (for GPL)
> layers: Fix which GPL shader stages are checked

- layers/best_practices/best_practices_utils.cpp
- layers/core_checks/cmd_buffer_validation.cpp
- layers/core_checks/image_validation.cpp
- layers/core_checks/pipeline_validation.cpp
- layers/core_checks/query_validation.cpp
- layers/core_checks/render_pass_validation.cpp
- layers/core_checks/synchronization_validation.cpp
- layers/state_tracker/cmd_buffer_state.cpp
- layers/state_tracker/cmd_buffer_state.h
- layers/state_tracker/state_tracker.cpp
- layers/state_tracker/state_tracker.h
- layers/sync/sync_validation.cpp
- tests/vklayertests_pipeline_shader.cpp
Add VUID-VkGraphicsPipelineCreateInfo-subpass-00758 after request in https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/4075
https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/5377
In the previous PR, validation was performed at pipeline creation time, using state stored in the supplied render pass. This is incorrect, as the supplied render pass only serves as a template in this context.
Validation is now done at pipeline bind time, using a new attribute `active_subpass_sample_count_` stored in `CMD_BUFFER_STATE`
VUID-VkGraphicsPipelineCreateInfo-subpass-00758
> If the pipeline is being created with fragment output interface state, and subpass does not use any color and/or depth/stencil attachments, then the rasterizationSamples member of pMultisampleState must …
> Add VUID 00758 (2nd PR)

- scripts/common_ci.py
- scripts/github_ci_build_desktop.py
- scripts/github_ci_win_linux.py
Have common_ci.py build/install release configs of the loader, profiles layer, and mock driver.
Installing them in 1 location simplifies the RunVVLTests function. Since all the shared libraries are all in 1 location.
> ci: Install Release loader/profiles/mockicd

- layers/CMakeLists.txt
- layers/layer_options.cpp
- layers/vk_layer_utils.cpp
VkLayer_utils is used by the LunarG/VulkanTools repository and having it require mimalloc causes build problems.
> build: Move mimalloc dependency to VVL from VkLayer_utils

- docs/shader_validation.md
- layers/best_practices/best_practices_utils.cpp
- layers/core_checks/core_validation.h
- layers/core_checks/drawdispatch_validation.cpp
- layers/core_checks/pipeline_validation.cpp
- layers/core_checks/shader_validation.cpp
- layers/gpu_validation/gpu_utils.cpp
- layers/state_tracker/pipeline_state.cpp
- layers/state_tracker/pipeline_state.h
- layers/state_tracker/shader_module.cpp
- layers/state_tracker/shader_module.h
- layers/sync/sync_validation.cpp
- tests/negative/dynamic_rendering.cpp
- tests/negative/pipeline_shader.cpp
This is pulled out of a large change I have been working on in the Shader validation code. (to help make managing `VK_EXT_graphics_pipeline_library` and  `VK_EXT_shader_module_identifier` better) 
This PR does
- Adds some documentation about shader val
- Makes dedicated function for `VkPipelineInputAssemblyStateCreateInfo`
- Move `ValidateShaderModuleId` out from "shader val" to "pipeline val" (there is no shader module to validate in `VK_EXT_shader_module_identifier`)
- Try to reduce more of `PipelineStageState` 
The future goal is to basically remove `PipelineStageState` and make use of the `EntryPoint` where ever possible
> More improvements to Pipeline Validation

- layers/state_tracker/pipeline_state.h
- layers/state_tracker/pipeline_sub_state.cpp
- layers/state_tracker/state_tracker.cpp
- layers/state_tracker/state_tracker.h
- layers/utils/hash_vk_types.h
- scripts/CMakeLists.txt
- tests/negative/ray_tracing.cpp
- tests/positive/pipeline.cpp
This PR does the following:
- `layers: Fix HasFullState`: Fixes issues where HasFullState() was incorrectly returning true
- `layers: Add shader identifier tracking`, `layers: User shader identifiers`: Adds state tracking for associating shader identifiers with shader state objects
> Fix issues related to pipeline library sub state and shader module identifiers

- layers/core_checks/cmd_buffer_dynamic_validation.cpp
- layers/core_checks/drawdispatch_validation.cpp
- layers/core_checks/pipeline_validation.cpp
- layers/core_checks/ray_tracing_validation.cpp
On 64-bit platform sizeof(DrawDispatchVuid) == 1184 bytes
This might not result in a measurable performance improvement, but it's a non-trivial amount of instructions for each draw call. And it's good for the programmer's soul 😊
Results from VS compiler, Release build.
With missing ampersand:
Ampersand magic:
> layers: Fix DrawDispatchVuid copy

- layers/best_practices/best_practices_utils.cpp
- layers/core_checks/core_validation.h
- layers/core_checks/pipeline_validation.cpp
- layers/core_checks/shader_validation.cpp
- layers/state_tracker/pipeline_state.cpp
- layers/state_tracker/pipeline_state.h
- layers/state_tracker/shader_module.cpp
- layers/state_tracker/shader_module.h
This change does
- Lower where "strip array" interface check is done
- Make `DecorationSet` a const ref
- Move `BuiltIn` checks to creation time when it is known
> Move more logic to Shader Module creation time

- BUILD.md
It is not possible to manually copy/install layer libraries on a development device if they are built with c++_shared. As this remains common practice, added a note to enable installing layer binaries without using an APK.
Change-Id: I4e315204afd1541a4eb50e73784a0958725b46f1
> android: Update BUILD.md for manual library installation

- layers/vk_layer_settings_ext.h
Currently there is an sType collision causing problems with the intel driver.
> layers: Workaround VkStructureType collision

- layers/core_checks/copy_blit_resolve_validation.cpp
- tests/negative/command.cpp
- tests/negative/image.cpp
Updates the new common VUID for 1.3.244 headers
This eliminates the duplicate VUID we had
> layers: Label new image/buffer copy VUID

- BUILD.gn
- layers/CMakeLists.txt
- layers/containers/custom_containers.h
- layers/containers/range_vector.h
- layers/core_checks/buffer_address_validation.h
- layers/core_checks/descriptor_validation.cpp
- layers/core_checks/drawdispatch_validation.cpp
- layers/core_checks/ray_tracing_validation.cpp
- layers/error_message/logging.h
- layers/state_tracker/device_memory_state.h
- layers/state_tracker/state_tracker.h
- tests/negative/descriptor_renderpass_framebuffer.cpp
- tests/negative/ray_tracing.cpp
This PR aims at fixing the remaining validation done to buffers obtained through a call to `GetBuffersByAddress`. I also updated `CoreChecks::ValidateRaytracingShaderBindingTable`. To help do this validation, a new helper class is introduced, `BufferAddressValidation`. I explained the problem it tries to solve right above its definition. Copy pasting here for convenience:
`BufferAddressValidation`class aims at helping with the validation of a family of VUIDs referring to the same buffer device address. For example, take those VUIDs for VkDescriptorBufferBindingInfoEXT:
*VUID-VkDescriptorBufferBindingInfoEXT-usage-08122*
> If usage includes VK_BUFFER_USAGE_SAMPLER_DESCRIPTOR_BUFFER_BIT_EXT, address must be an address within a valid buffer that was
created with …
> Validation: Properly validate buffers obtained with GetBuffersByAddress

- layers/VkLayer_khronos_validation.json.in
- layers/layer_options.cpp
Refactor validalation layer settings to leverage the data-driven layer settings in Vulkan Configurator but keeping backward compatbility with old flags approach, including extension.
The new settings override the old flags but old enables and disables flags remains supported.
This will allow modifying the layer settings in the validation layer without any change required in Vulkan Configurator and still ensure settings are displayed in Vulkan Configurator in such a way it's easy to understand the settings depedences.
This PR replaced https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/4551
_The UI in vkconfig fully generated using the updated layer manifest, no built-in UI used._
> Layer generic layer settings

- BUILD.md
Most users don't need to run the python script manually.
`UPDATE_DEPS` is the prefered workflow most developers
> docs: Simplify Building Overview

- BUILD.md
- build-android/jni/Application.mk
- build-android/jni/shaderc/Application.mk
Using the c++ shared library (libc++_shared.so) causes non-trivial install complications on Android, so changing back to using libc++_static.so.
Fixes #5491.
> Change back to using libc++_static.so for Android

- layers/core_checks/descriptor_validation.cpp
These two checks were using the wrong function's VUIDs
> layers: Fix vkCmdPushDescriptorSetWithTemplateKHR VUIDs

- scripts/vk_validation_stats.py
- tests/framework/layer_validation_tests.cpp
- tests/framework/layer_validation_tests.h
- tests/framework/render.cpp
- tests/framework/render.h
- tests/negative/wsi.cpp
- tests/positive/wsi.cpp
Currently WSI testing is a bit broken on linux since AddSurfaceExtension doesn't line up with CreateSurface.
In the new approach
- WSI extensions queried properly
- If AddSurfaceExtension is called at least 1 WSI will be required when calling AreRequiredExtensionsEnabled
- VkRenderFramework::CreateSurface checks if the extension is enabled
- Specific WSI tests now have to explicitly check for their desired WSI extension
> tests: Fix WSI extension logic

- build-android/jni/Application.mk
- build-android/jni/shaderc/Application.mk
Need to temporarily replace static libs with shared libs to fix CI though static is preferred long-term.
Tracking issue for static/shared lib issue is here: https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/5508
> Revert static lib changes to fix CI.

- CMakePresets.json
- docs/generated_code.md
- layers/CMakeLists.txt
- scripts/generate_source.py
Code generation should be OFF by default. It's not needed to build the vulkan validation layers.
- It's causing issues for add_subdirectory users.
- Package managers have no good way to disable this aside from patching.
> cmake: Add VVL_CODEGEN

- layers/core_checks/descriptor_validation.cpp
- layers/error_message/validation_error_enums.h
Adds VUID for new VUs added in 245 headers to replace to old UNASSIGNED VUIDs
- VUID-vkCmdPushDescriptorSetWithTemplateKHR-layout-07993
- VUID-vkCmdPushDescriptorSetWithTemplateKHR-descriptorUpdateTemplate-07994
- VUID-vkCmdPushDescriptorSetWithTemplateKHR-set-07995
> layers: Label new CmdPushDescriptorSetWithTemplate VUID

- layers/core_checks/shader_validation.cpp
- layers/state_tracker/shader_module.cpp
- layers/state_tracker/shader_module.h
- tests/positive/shaderval.cpp
Original issue https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/4657
Fix for ` VUID-VkGraphicsPipelineCreateInfo-Geometry-07725`
New 245 spec clarify that when not emitting any vertex, Geometry shaders don't need a PointSize
> layers: PointSize not needed if not emit vertex

- layers/core_checks/cmd_buffer_dynamic_validation.cpp
- layers/core_checks/cmd_buffer_validation.cpp
- layers/core_checks/pipeline_validation.cpp
- layers/core_checks/shader_validation.cpp
- layers/state_tracker/cmd_buffer_state.h
- layers/stateless/parameter_validation_utils.cpp
- tests/negative/command.cpp
- tests/negative/others.cpp
- tests/negative/pipeline_shader.cpp
- tests/negative/viewport_inheritance.cpp
- tests/positive/pipeline.cpp
Adds `VUID-VkGraphicsPipelineCreateInfo-pDynamicStates-04130` and `VUID-VkGraphicsPipelineCreateInfo-pDynamicStates-04131` which were already basically implemented minus checking for the new Viewport/Scissor dynamic state added in `VK_EXT_extended_dynamic_state`
>  Add dynamic state viewport/scissors count

- layers/core_checks/render_pass_validation.cpp
- tests/negative/dynamic_rendering.cpp
Adds `VUID-VkRenderingInfo-layerCount-07817` which is `VUID-VkFramebufferCreateInfo-layers-00890` but for Dynamic Rendering
> layers: Dynamic Rendering maxFramebufferLayers

- layers/stateless/parameter_validation_utils.cpp
- tests/negative/ray_tracing.cpp
- tests/negative/ray_tracing_pipeline.cpp
Fix up for Spencer's PR https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/5499
Add:
`VUID-VkRayTracingPipelineCreateInfoKHR-pLibraryInfo-07999`
>If pLibraryInfo is NULL or its libraryCount is 0, stageCount must not be 0
`VUID-VkRayTracingPipelineCreateInfoKHR-flags-08700`
>If flags does not include VK_PIPELINE_CREATE_LIBRARY_BIT_KHR and either pLibraryInfo is NULL or its libraryCount is 0, groupCount must not be 0
Remove `VUID-VkRayTracingPipelineCreateInfoKHR-pLibraryInfo-03600` and `VUID-VkRayTracingPipelineCreateInfoKHR-pLibraryInfo-03601`
> layers: Add 07999 08700 Remove 03600 03601

- layers/core_checks/core_validation.h
- layers/core_checks/drawdispatch_validation.cpp
This PR first renames `ValidateCmdDrawType` to `ValidateActionCmd` (there is no [direct name](https://github.com/KhronosGroup/Vulkan-Docs/issues/1908) for these, but confusing that `vkCmdTraceRays` is part of of "draw")
This PR also fixes that `VUID-vkCmdTraceRaysIndirectKHR-None-02700` was being called in two places, so removed the custom spot and have it use the one in `ValidateCmdBufDrawState`
> Fix Ray Tracing action command

- layers/core_checks/render_pass_validation.cpp
- tests/negative/dynamic_rendering.cpp
When using `VK_KHR_dynamic_rendering` the `VUID-VkRenderingInfo-pNext-07815` and `VUID-VkRenderingInfo-pNext-07816` VUs were missing
Fixed logic as the VUs were gated by the `VK_KHR_device_group` being enabled which is wrong, only the VUID changes
> layers: Fix and Label MaxFramebuffer extent

- layers/core_checks/core_validation.h
- layers/core_checks/external_object_validation.cpp
- layers/generated/parameter_validation.cpp
- layers/stateless/parameter_validation_utils.cpp
- layers/stateless/stateless_validation.h
- scripts/parameter_validation_generator.py
- tests/CMakeLists.txt
- tests/negative/external_memory_sync.cpp
- tests/positive/external_memory_sync.cpp
Part of https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/5431
This PR validates `VkMemoryGetFdInfoKHR` passed to `vkGetMemoryFdKHR`:
`VUID-VkMemoryGetFdInfoKHR-handleType-00671`
`VUID-VkMemoryGetFdInfoKHR-handleType-00672`
> layers: Add vkGetMemoryFdKHR VUs

- layers/core_checks/synchronization_validation.cpp
- layers/sync/sync_vuid_maps.cpp
- layers/sync/sync_vuid_maps.h
Add missing "StageMask must not be 0" when not using Sync2
Before there use to be a `VUID-vkCmdPipelineBarrier-srcStageMask-requiredbitmask` but it was fixed in an XML change a while ago and now became `VUID-vkCmdPipelineBarrier-srcStageMask-04996`
also fixed `VUID-vkCmdWriteTimestamp-pipelineStage-04074` should have been `VUID-vkCmdWriteTimestamp-synchronization2-06489`
> layers: Label non Sync2 STATE_NONE VUIDs

- layers/state_tracker/descriptor_sets.cpp
- layers/state_tracker/descriptor_sets.h
- tests/framework/ray_tracing_objects.cpp
- tests/framework/ray_tracing_objects.h
- tests/positive/descriptors.cpp
- Fix for https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/5300
AccelerationStructureDescriptor::is_khr_ was not initialised
Locally, I now have no validation error in this test, but it still fails:
```
Writing test log into TestResults.qpa
dEQP Core vulkan-cts-1.3.5.0-238-ge873c6862 (0xe873c686) starting..
target implementation = 'Default'
loader_get_json: Failed to open JSON file C:\Program Files (x86)\Epic Games\Epic Online Services\managedArtifacts\98bc04bc842e4906993fd6d6644ffb8d\EOSOverlayVkLayer-Win64.json
Test case 'dEQP-VK.binding_model.mutable_descriptor.single_nonmutable.acceleration_structure_khr.update_copy.mutable_source.normal_source.pool_same_types.pre_update.no_array.comp'..
InternalError (1 API usage errors found)
DONE!
Test run totals:
Passed:        0/1 …
```
> layers: Fix AccelerationStructureDescriptor::is_khr_ initialisation

- layers/stateless/parameter_validation_utils.cpp
- tests/negative/pipeline_shader.cpp
- tests/positive/pipeline.cpp
Update validation for viewportCount-01215
Instead of checking for `not equal` it should be `less than`
> layers: Fix VkLayerTest.ViewportSwizzleNV

- tests/positive/other.cpp
Found bug in [Profiles layer](https://github.com/KhronosGroup/Vulkan-Profiles/pull/392) that was causing a second call with `VkFormatProperties3` to return `VUID-VkFormatProperties2-pNext-pNext` because the `sType` was being overwritten
> tests: Add Profiles VkFormatProperties3 regression

- layers/core_checks/cmd_buffer_validation.cpp
- layers/core_checks/device_memory_validation.cpp
- layers/core_checks/image_layout_validation.cpp
- layers/core_checks/ray_tracing_validation.cpp
- layers/core_checks/render_pass_validation.cpp
- layers/core_checks/synchronization_validation.cpp
- layers/core_checks/video_validation.cpp
According to LunarG coding guidelines: "Use lowercase for all hex output".
> layers: Ensure hex output is in lowercase

- layers/best_practices/best_practices_error_enums.h
- layers/best_practices/best_practices_utils.cpp
- layers/best_practices/best_practices_validation.h
- layers/state_tracker/shader_module.h
- tests/negative/amd_best_practices.cpp
https://gpuopen.com/learn/rdna-performance-guide/#shaders
"Make the workgroup size a multiple of 64 to obtain best performance across all GPU generations."
> bp: Add best practice for AMD workgroup size

- BUILD.md
- build-android/build_all.sh
- build-android/jni/Application.mk
- build-android/jni/shaderc/Application.mk
Android builds targeted at CI testing need to use the shared C++ standard library, but Android binary releases and manually built layers need to use the static C++ standard library.
This PR modifies the `build-android\build_all.sh` script to produce builds using the static library.  Github Actions and LunarG internal CI do not use this script and will continue to use the shared version of the library.
See tracking issue #5508 for background and related issues.
Also added some descriptive text in the Android build scripts to server as guidance when the Android build is converted to use CMake.
Fixes #5508.
> Enable static C++ std library use for non-CI Android builds

- layers/state_tracker/buffer_state.h
- layers/state_tracker/cmd_buffer_state.h
- layers/state_tracker/state_tracker.cpp
- layers/sync/sync_validation.cpp
- layers/sync/sync_validation.h
- layers/utils/vk_layer_utils.h
Get rid of magic UINT32 max usage, and correctly set size for bind vertex buffer2
> syncval: Clean up and correct bound size code.

- BUILD.md
Our code doesn't compile with the version of GCC that comes with Ubuntu 18.04 by default.
closes #5473
> docs: Remove implication of 18.04 build support

- layers/core_checks/core_validation.h
- layers/core_checks/render_pass_validation.cpp
- tests/framework/layer_validation_tests.h
- tests/negative/dynamic_rendering.cpp
- tests/positive/dynamic_rendering.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/5492
We were not calling `ValidateCmd` for `vkCmdBeginRendering`/`vkCmdEndRendering` and missing the checks from it
> Fix DynamicRendering calling command cmd helper

- layers/core_checks/core_validation.h
- layers/core_checks/shader_validation.cpp
- layers/error_message/validation_error_enums.h
- layers/state_tracker/pipeline_state.cpp
- layers/state_tracker/pipeline_state.h
- layers/state_tracker/shader_instruction.h
- layers/state_tracker/shader_module.cpp
- layers/state_tracker/shader_module.h
- layers/state_tracker/state_tracker.cpp
- tests/framework/layer_validation_tests.h
- tests/negative/geometry_tessellation.cpp
- tests/negative/pipeline_shader.cpp
- tests/positive/pipeline.cpp
- tests/positive/shaderval.cpp
Main goal - Group `OpVariable` into 3 types
- Stage interface (input/output)
- Built Ins
- User Defined
- Resource Variables
From here the goal is to do as much as possible during the init prasing of the shader
> Refactoring how Variables are handles in Shader Module

- layers/core_checks/core_validation.h
- layers/core_checks/descriptor_validation.cpp
- layers/core_checks/pipeline_validation.cpp
- layers/state_tracker/pipeline_sub_state.cpp
- layers/state_tracker/pipeline_sub_state.h
- tests/negative/graphics_library.cpp
- tests/positive/graphics_library.cpp
- tests/positive/pipeline.cpp
- Move 07826 check to pipeline creation time
- Add 07827
Marking as a draft for now as there may be other missing VUIDs that should be added as part of this change.
> Ensure pipeline layout is always present

- layers/error_message/logging.cpp
- layers/error_message/logging.h
- layers/generated/chassis.h
- scripts/layer_chassis_generator.py
Most (if not all) VUIDs are defined as string literals, so this PR should prevent a bunch of string constructions.
> Log VUIDs using a string_view

- layers/core_checks/device_memory_validation.cpp
- layers/state_tracker/state_tracker.cpp
- layers/state_tracker/state_tracker.h
- tests/framework/render.h
- tests/negative/external_memory_sync.cpp
Part of https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/5431
This PR validates `VkMemoryAllocateInfo`'s allocation size and memory type index during memory import operation:
`VUID-VkMemoryAllocateInfo-allocationSize-01742`
`VUID-VkMemoryAllocateInfo-allocationSize-01743`
Updated `ValidateImportMemoryHandleType` to skip the test if there is no memory type that supports import and export that use different handle types. This happens on AMD drivers and is a valid situation. There is no guarantee the same memory type is supported by different handle types.
One lesson from this PR is that in some cases external memory requires dedicated allocation. It's the case on Android Pixel 3. 
We have scheduled work for dedicated memory VUs to improve detection of such cases.
> layers: Add VkMemoryAllocateInfo import VUs

- tests/framework/render.cpp
Various functions are being loaded using vkGetDeviceProcAddr then stored inside a static local variable. This means subsequent tests that use those functions will contain a *stale* function pointer, since the device is different and the dynamic libraries would have been unloaded.
> test: Remove static from Video function pointers

- layers/generated/thread_safety.h
- layers/utils/vk_layer_utils.h
- scripts/thread_safety_generator.py
Instead of using an array of bytes to pad structs/classes it's better to use `alignas` as shown in this `cppreference` example:
https://en.cppreference.com/w/cpp/thread/hardware_destructive_interference_size
I did initially try using `std::hardware_destructive_interference_size` and it worked on Windows/MacOS, but had issues on Linux/Android.
Even though `std::hardware_destructive_interference_size` is in C++17 it's not fully supported on all platforms and the only way to properly check for it is to use C++20 feature testing...
> layers: Cleanup false sharing code

- layers/best_practices/best_practices_utils.cpp
- layers/core_checks/core_validation.h
- layers/core_checks/shader_validation.cpp
- layers/state_tracker/pipeline_state.cpp
- layers/state_tracker/shader_module.cpp
- layers/state_tracker/shader_module.h
- tests/negative/pipeline_shader.cpp
Adds `ExecutionModeSet` to act like the `DecorationSet` we have
Instead of having to look up and re-find each `OpExecutionMode` value, this just stores them reducing many loops
While at it, I also moved all the `const Instruction& entrypoint` to `const EntryPoint& entrypoint` as it allows for grabbing more information as it is passed around
Also added a `transform_feedback_stream_inst` lookup for `ValidateTransformFeedback` instead of re-looping the module
Lastly, in attempt to make `SHADER_MODULE_STATE` simpler, I removed the getters in favor of just grabbing `static_data_` as it was not being done consistently and `StaticData` is const so can't write it anyway
> Add ExecutionModeSet

- layers/core_checks/shader_validation.cpp
- layers/generated/spirv_grammar_helper.cpp
- layers/generated/spirv_grammar_helper.h
- scripts/spirv_grammar_generator.py
generates a `string_SpvDecoration` helper so now the new error message looks like
```
vkCreateGraphicsPipelines(): pCreateInfos[0] Mistmatch in BuiltIn blocks:
VK_SHADER_STAGE_VERTEX_BIT Output Block {
0: RelaxedPrecision
1: SpecId
}
VK_SHADER_STAGE_GEOMETRY_BIT Input Block {
0: RelaxedPrecision
1: SpecId
2: BufferBlock
}
```
> layers: Improve Builtin Mismatch error message

- layers/core_checks/shader_validation.cpp
- tests/positive/graphics_library.cpp
Check that pointers such as
VkPipelineRenderingCreateInfo::pColorAttachmentFormats are ignored when creating a GPL with only FS state.
> tests: Check GPL + dyn rendering ignored pointers

- layers/core_checks/cmd_buffer_dynamic_validation.cpp
- layers/core_checks/core_validation.h
- layers/core_checks/drawdispatch_validation.cpp
- layers/generated/thread_safety.cpp
- layers/generated/vk_dispatch_table_helper.h
- layers/generated/vk_extension_helper.h
- layers/state_tracker/cmd_buffer_state.cpp
- layers/state_tracker/device_state.h
- layers/state_tracker/pipeline_state.h
- layers/state_tracker/state_tracker.cpp
- layers/state_tracker/state_tracker.h
- scripts/dispatch_table_helper_generator.py
- scripts/helper_file_generator.py
- scripts/thread_safety_generator.py
- tests/negative/dynamic_state.cpp
This PR introduces a number of changes needed to allow validation of applications that use VK_EXT_shader_object without the layer crashing or generating false positives:
ValidateExtendedDynamicState() and its callers are modified to check for either the specific EDS1/2/3/etc. feature originally associated with each function, or the shaderObject feature (which also makes it legal to call them, even when the corresponding dynamic state feature is disabled). This allows these commands to be called with only the shaderObject feature enabled, as expected by the spec.
ValidateCmdBufDrawState() is temporarily modified to early out if the shaderObject feature is enabled but there isn't a pipeline bound. This avoids a false positive error when shader objects have been bound instead of pipelines. …
> Compatible validation for VK_EXT_shader_object

- layers/core_checks/core_validation.h
- layers/core_checks/pipeline_validation.cpp
create a `ValidateGraphicsPipelinePortability` to group the `VK_KHR_portability_subset` code
it was split in 2 different areas
> layers: Group graphics portability validation

- layers/core_checks/core_validation.h
- layers/core_checks/wsi_validation.cpp
- layers/error_message/logging.cpp
- layers/generated/chassis.h
- layers/state_tracker/device_state.h
- layers/state_tracker/image_state.cpp
- layers/state_tracker/image_state.h
- layers/state_tracker/state_tracker.cpp
- layers/utils/vk_layer_utils.h
- scripts/layer_chassis_generator.py
- tests/negative/wsi.cpp
Originally was https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/4703, but since rebasing this old PR lead to terrible merge issues, I'd rather leave the old one untouched just in case.
- Closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/4594
The main thing about the fix is an update to `SURFACE_STATE` to use `VkSurfaceFormat2KHR`, `VkSurfaceCapabilities2KHR` and `VkPhysicalDeviceSurfaceInfo2KHR`. It now relies on `DispatchGetPhysicalDeviceSurfaceFormats2KHR` and `DispatchGetPhysicalDeviceSurfaceCapabilities2KHR` when `vk_khr_get_surface_capabilities2` is enabled. Otherwise it fall backs to the original functions.
This PR defines a `LogInternalError` used to log errors we get from our internal `DispatchVkFoo` calls.
> layers: Account for `VkSurfaceFullScreenExclusiveInfoEXT` when validating swapchain creation

- scripts/CMakeLists.txt
Remove need for `vvl_update_deps` custom target.
This fixes the bug where update_deps.py is run twice on CI for no reason. Which will help performance.
CMake will re-run the configure step when either known_good.json or update_deps.py are modified.
> cmake: Only run update_deps.py during configure step

- layers/core_checks/core_validation.h
- layers/core_checks/shader_validation.cpp
- layers/state_tracker/shader_module.cpp
- layers/state_tracker/shader_module.h
With all the refactoring in Shader Module state tracking, this tries to reduce the runtime logic that was being done in Shader Validation
> Use new Shader Module info in Shader Validation

- layers/core_checks/pipeline_validation.cpp
- tests/positive/command.cpp
- tests/positive/render_pass.cpp
- Closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/5608
Added a positive test that triggers 06887 without this patch
Will follow-up with https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/5624
> layers: Consider separate depth stencil layouts feature when validating 06887

- layers/core_checks/descriptor_validation.cpp
- tests/negative/command.cpp
` VUID-RuntimeSpirv-samples-08725` and `VUID-RuntimeSpirv-samples-08726` were added recently to help breakup that massive "if descriptors don't match pipeline" VU
> layers: Label new MS runtime VUID

- .github/workflows/vvl.yml
- scripts/github_ci_android.py
- Don't download the NDK unless we need to.
- Only test 1 ABI. New android_cmake tests both.
> ci: Speed up Android CI for Android.mk build

- layers/core_checks/pipeline_validation.cpp
- layers/gpu_validation/debug_printf.cpp
- layers/state_tracker/pipeline_state.cpp
- layers/state_tracker/pipeline_state.h
- tests/framework/binding.h
- tests/negative/debug_printf.cpp
- tests/negative/gpu_av.cpp
- tests/negative/pipeline_shader.cpp
- tests/negative/portability_subset.cpp
- tests/positive/graphics_library.cpp
It is possible to encounter VUID 06590 as a false positive if rasterizer discard is used. Fragment output state was masked out (incorrectly, since it did not consider dynamic state), and fragment shader state was not masked at all.
Ran into this in vkd3d-proton test suite.
> layers: Mask fragment shader state with rasterizerDiscard

- layers/core_checks/shader_validation.cpp
- layers/error_message/validation_error_enums.h
- tests/negative/geometry_tessellation.cpp
- tests/negative/pipeline_shader.cpp
adds `VUID-VkGraphicsPipelineCreateInfo-Input-08733` and `VUID-RuntimeSpirv-OpEntryPoint-08743` (from 1.3.247 spec) to remove 2 more `UNASSIGNED`
> layers: Label new shader interface VUIDs

- build-android/jni/Android.mk
- layers/core_checks/core_validation.h
- layers/core_checks/pipeline_cc_validation.cpp
- layers/core_checks/shader_cc_validation.cpp
- layers/state_tracker/device_state.h
- layers/state_tracker/state_tracker.cpp
- layers/state_tracker/state_tracker.h
- layers/stateless/pipeline_sl_validation.cpp
- layers/stateless/ray_tracing_sl_validation.cpp
- layers/stateless/stateless_validation.h
- tests/CMakeLists.txt
- tests/negative/robustness.cpp
- tests/positive/descriptors.cpp
- tests/positive/robustness.cpp
- tests/positive/shaderval.cpp
To help, but not fix yet, https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/5657
Enabling robustness features can cause performance on GPUs to go down, the `VK_EXT_pipeline_robustness` extension was added so people could just use that extension, but it took advantage of the other robustness features
This change
- Moves logic from Stateless to CoreCheck
- creates a `has_robust_image_access` to check if extension is expose
- Disables the 4 `VK_EXT_robustness2` VUs
- We will need to write up a way to query the device features if they are not provided, currently we just assumed the features were passed into CreateDevice
> Fix VK_EXT_pipeline_robustness to check if exposed

- layers/best_practices/best_practices_utils.cpp
- layers/core_checks/core_validation.h
- layers/core_checks/descriptor_cc_validation.cpp
- layers/core_checks/drawdispatch_cc_validation.cpp
- layers/core_checks/shader_cc_validation.cpp
- layers/generated/spirv_grammar_helper.cpp
- layers/generated/spirv_grammar_helper.h
- layers/state_tracker/cmd_buffer_state.cpp
- layers/state_tracker/cmd_buffer_state.h
- layers/state_tracker/descriptor_sets.cpp
- layers/state_tracker/descriptor_sets.h
- layers/state_tracker/image_state.cpp
- layers/state_tracker/pipeline_state.cpp
- layers/state_tracker/pipeline_state.h
- layers/state_tracker/shader_instruction.cpp
- layers/state_tracker/shader_instruction.h
- layers/state_tracker/shader_module.cpp
- layers/state_tracker/shader_module.h
- layers/sync/sync_validation.cpp
- scripts/spirv_grammar_generator.py
Before we were going:
1. Parse shader object
2. Copy info about the Shader to the Pipeline object
3. Have the Descriptors us the Pipeline object
This just skips the step 2
This can be seen in `PIPELINE_STATE::GetActiveSlots` where we not just give it the `ResourceInterfaceVariable` and not do all the "re-copy what found"
I also redefined `NUMERIC_TYPE` - There is an internal spec PR I have that will properly spec that
>  "Numeric Type" == Float vs SInt vs UInt
> Descriptors use ShaderModule Variable object

- layers/core_checks/core_validation.h
- layers/core_checks/image_layout_cc_validation.cpp
- layers/core_checks/render_pass_cc_validation.cpp
- layers/utils/vk_layer_utils.h
- tests/framework/layer_validation_tests.cpp
- tests/framework/layer_validation_tests.h
- tests/negative/multiview.cpp
- tests/negative/renderpass.cpp
- tests/negative/subpass.cpp
- Closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/5624
Add:
VUID-VkRenderPassCreateInfo2-attachment-06244
VUID-VkRenderPassCreateInfo2-attachment-06245
VUID-VkRenderPassCreateInfo2-attachment-06246
VUID-vkCmdBeginRenderPass-stencilInitialLayout-02843
VUID-vkCmdBeginRenderPass2-stencilInitialLayout-02845
VUID-vkCmdBeginRenderPass-initialLayout-02842
VUID-vkCmdBeginRenderPass2-initialLayout-02844
Two new tests: `RenderPassBeginLayoutsStencilBufferImageUsageMismatches` and `RenderPassBeginInvalidStencilFormat`
Split up `RenderPassCreateAttachmentReferenceInvalidLayout` into two tests because the `if (separate_depth_stencil_layouts_features.separateDepthStencilLayouts) { ... }` logic was not working as intended anymore, and one branch was dead. There is now one test for …
> layers: Add `VK_KHR_separate_depth_stencil_layouts` related VUIDs

- layers/stateless/sl_device_memory.cpp
- tests/negative/android_hardware_buffer.cpp
- tests/positive/android_hardware_buffer.cpp
`VK_KHR_maintenance4` added `vkGetDeviceImageMemoryRequirements`
this adds `VUID-VkDeviceImageMemoryRequirements-pNext-06996`
Also adds some cleanup to the AHB and a Null-AHB test
> Add VK_KHR_maintenance4 AHB check

- layers/core_checks/cc_synchronization.cpp
- layers/core_checks/core_validation.h
- layers/state_tracker/queue_state.cpp
- layers/state_tracker/queue_state.h
- layers/state_tracker/state_tracker.cpp
- layers/state_tracker/state_tracker.h
`vkAcquireNextImageKHR` and `vkAcquireNextImage2KHR` are not initiated on specific queue.
New functionality can also be used to update other places to include operation name in the output.
Closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/5589
> layers: Fix message for non-queue operation

- layers/stateless/sl_pipeline.cpp
- tests/negative/dynamic_state.cpp
- tests/positive/graphics_library.cpp
This will be fixed in the [248 spec](https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/5862), but `VK_DYNAMIC_STATE_COLOR_BLEND_ADVANCED_EXT` was missing from the list of dynamic states that effect the Color Blend State
> layers: Fix ColorBlendState dynamic check

- layers/core_checks/cc_shader.cpp
- layers/core_checks/core_validation.h
- layers/state_tracker/pipeline_state.cpp
- layers/state_tracker/pipeline_state.h
- layers/state_tracker/shader_module.cpp
- layers/state_tracker/shader_module.h
This does a few cleanup before future PR
- move `SHADER_MODULE_STATE::EntryPoint` to `EntryPoint`
- Didn't make sense having the struct nested as provides its own logic (unlike `SHADER_MODULE_STATE::StaticData`)
- adds a `GetStageInterfaceVariables` and `GetResourceInterfaceVariables` so those variables objects can be init as constants
- Moves the "Find Accessible Ids" logic out to own function for better readability
> layers: More init const for EntryPoint/Variables

- layers/stateless/sl_device_memory.cpp
- tests/negative/memory.cpp
Adds VUID-VkDeviceImageMemoryRequirementsKHR-pCreateInfo-06419 using new `IsOnlyOneValidPlaneAspect` helper
> VkDeviceImageMemoryRequirementsKHR plane aspect

- layers/core_checks/cc_ray_tracing.cpp
- tests/negative/ray_tracing.cpp
- tests/positive/ray_tracing.cpp
- Closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/5635
I got my info from here: https://gitlab.khronos.org/vulkan/vulkan/-/issues/3464#note_407581
> layers: Fix to the logic defining a `VkStridedDeviceAddressRegionKHR` as unused

- tests/positive/android_hardware_buffer.cpp
- tests/positive/command.cpp
- tests/positive/descriptors.cpp
- tests/positive/dynamic_rendering.cpp
- tests/positive/dynamic_state.cpp
- tests/positive/gpu_av.cpp
- tests/positive/image_buffer.cpp
- tests/positive/memory.cpp
- tests/positive/other.cpp
- tests/positive/pipeline.cpp
- tests/positive/render_pass.cpp
- tests/positive/shaderval.cpp
- tests/positive/sync.cpp
Should remove rest of the `GetDeviceProcAddr` outside the few that are dedicated for testing that function
> tests: Remove more GetDeviceProcAddr

- layers/best_practices/bp_instance_device.cpp
- tests/negative/best_practices.cpp
As highlighted in #4654 it isn't ideal to log this as a warning.
Downgrading it to VK_DEBUG_UTILS_MESSAGE_SEVERITY_INFO_BIT_EXT seems like a good compromise since the logging was requested by an engineer working on Vulkan CTS originally.
closes #4654
> bp: Log BestPractices-SemaphoreCount as informational

- scripts/CMakeLists.txt
Put Android dependencies under external/android when using UPDATE_DEPS=ON so that Android and desktop binaries can coexist in the same source directory by default.
> build: Put Android dependencies in separate dir

- docs/generated_code.md
- layers/CMakeLists.txt
- scripts/common_ci.py
- scripts/generate_source.py
- scripts/vk_validation_stats.py
The scripts all need to know the registry directory already, so they can update sys.path to include it.
> scripts: Remove the need to set PYTHONPATH everywhere

- layers/best_practices/best_practices_utils.cpp
- layers/best_practices/best_practices_validation.h
- layers/generated/best_practices.cpp
- scripts/best_practices_generator.py
The name `LogSuccess` does not suggest VK_SUCCESS is excluded.
`LogError` is already used and could be very confusing since it doesn't use LogError at all.
> bp: Rename logging helper functions

- layers/best_practices/best_practices_error_enums.h
- layers/best_practices/best_practices_validation.h
- layers/best_practices/bp_pipeline.cpp
- layers/core_checks/cc_shader.cpp
- layers/core_checks/core_validation.h
- layers/error_message/validation_error_enums.h
- tests/negative/best_practices.cpp
- tests/negative/geometry_tessellation.cpp
- tests/negative/pipeline_shader.cpp
Moves the Fragment shader output interface checks to Best Practice
They were before just reporting `LogWarning` in the `CoreChecks`
> bp: Move Fragment Output checks to BP

- tests/negative/android_hardware_buffer.cpp
- tests/positive/android_hardware_buffer.cpp
1. Fixes External Format tests to query before creating the image otherwise it was failing with `VUID-VkImageCreateInfo-pNext-00990`
2. Add 2 Null-AHB test to make sure we fail early
> Fix External Format Android tests

- layers/core_checks/cc_image_layout.cpp
- Add image usage to errors logged in `CoreChecks::ValidateRenderPassLayoutAgainstFramebufferImageUsage` and `CoreChecks::ValidateRenderPassStencilLayoutAgainstFramebufferImageUsage`
- Add missing periods
> layers: Add image usage to render pass layout error messages

- layers/core_checks/cc_shader.cpp
- layers/state_tracker/shader_module.cpp
- layers/state_tracker/shader_module.h
When I added this logic for Spec Constant we didn't have the `StaticData` or `EntryPoint` helpers
Currently we are doing the logic twice, so this eliminates the copy-and-pasted logic
> layers: Use new helpers for Spec Constant

- layers/state_tracker/queue_state.cpp
- layers/state_tracker/state_tracker.cpp
- tests/positive/sync.cpp
This request fixes the issue: https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/5694
> Fix false positive VUID-vkResetCommandBuffer-commandBuffer-00045 error after exporting submitted fence handle

- build-android/jni/Android.mk
- layers/core_checks/cc_query.cpp
- layers/core_checks/cc_synchronization.cpp
- layers/sync/sync_utils.cpp
- layers/sync/sync_vuid_maps.cpp
- layers/sync/sync_vuid_maps.h
- tests/CMakeLists.txt
- tests/negative/fragment_shading_rate.cpp
- tests/positive/fragment_shading_rate.cpp
The first commit fixes `VK_PIPELINE_STAGE_FRAGMENT_SHADING_RATE_ATTACHMENT_BIT_KHR` detection and closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/5662
UPDATE: @ziga-lunarg independently and simultaneously implemented fix for https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/5662 in a different PR https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/5726 . This PR integrates the test from that PR.
The second commit adds shading rate VUIDs that vary only based on enabled extensions.
> layers: Shading rate stage fixes

- tests/CMakeLists.txt
- tests/framework/android_hardware_buffer.h
- tests/framework/test_framework_android.cpp
- tests/framework/test_framework_android.h
- tests/negative/android_hardware_buffer.cpp
- tests/positive/android_hardware_buffer.cpp
Simplifies the Android build. This helper function has nothing to do with the test framework.
This makes it simpler to consolidate the 2 Android builds.
> android: Create android_hardware_buffer.h

- BUILD.md
Minimize docs as much as possible so they don't become out of date.
Refer to CMake docs which cover -A / -G usage.
> docs: Cleanup Windows build instructions

- build-android/jni/Android.mk
- layers/core_checks/cc_image.cpp
- layers/generated/vk_format_utils.cpp
- layers/generated/vk_format_utils.h
- scripts/format_utils_generator.py
- tests/CMakeLists.txt
- tests/negative/portability_subset.cpp
- tests/positive/format_utils.cpp
Closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/2361
Before (when issue was opened 2+ years ago) we didn't have a generated Format Util that could check against each component bit size
Even if it is compressed formats, it will still match correctly
> layers: Use FormatUtils for imageViewFormatReinterpretation

- tests/negative/command.cpp
- tests/negative/descriptors.cpp
- tests/negative/imageless_framebuffer.cpp
- tests/negative/object_lifetime.cpp
- tests/negative/pipeline_shader.cpp
- tests/positive/descriptors.cpp
- tests/positive/render_pass.cpp
These checks for a zero `maxPushDescriptors` seems like an artifact of the old DevSim/MockICD that didn't fill in all the properties, I assume this will run find on CI now
> tests: Remove check for zero maxPushDescriptors

- tests/negative/atomics.cpp
- tests/negative/mesh.cpp
- tests/negative/query.cpp
- tests/negative/robustness.cpp
- tests/negative/subgroups.cpp
- tests/negative/viewport_inheritance.cpp
- tests/positive/atomics.cpp
- tests/positive/format_utils.cpp
- tests/positive/fragment_shading_rate.cpp
- tests/positive/layer_utils.cpp
- tests/positive/mesh.cpp
- tests/positive/tooling.cpp
This is the first step to give better naming for tests, this is easy since it can just match the file name
These tests didn't have any exception with CI, so changing them should be no issue and a good "do we like this convention" test
> tests: Give better names for test groups

- layers/generated/parameter_validation.cpp
- scripts/parameter_validation_generator.py
- tests/positive/other.cpp
Parameter validation was missing the workaround required for recent
upstream vulkan XML changes.
Closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/5733.
> layers: Add XML workaround for param validation

- layers/core_checks/cc_shader.cpp
It was brought up in https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/5749 that
- `VUID-RuntimeSpirv-denormBehaviorIndependence-06289`
- `VUID-RuntimeSpirv-denormBehaviorIndependence-06290`
- `VUID-RuntimeSpirv-roundingModeIndependence-06291`
- `VUID-RuntimeSpirv-roundingModeIndependence-06292`
Seem to have false positive, but the spec is not clear **how** they should be
There is a spec issue to clarify this https://gitlab.khronos.org/vulkan/vulkan/-/issues/3471
For now, I would rather remove these the prevent false positive until the spec if fixed
> layers: Remove under specified shader_float_control

- layers/best_practices/bp_device_memory.cpp
- layers/core_checks/cc_android.cpp
- layers/core_checks/cc_device_memory.cpp
- layers/core_checks/core_validation.h
- layers/state_tracker/buffer_state.cpp
- layers/state_tracker/device_memory_state.cpp
- layers/state_tracker/device_memory_state.h
- layers/state_tracker/image_state.cpp
Use correct type (Flags vs FlagBits).
Use correct singular or plural form for handle type variables.
> layers: Fix naming and type selection of external handles

- layers/core_checks/cc_image.cpp
- layers/stateless/sl_image.cpp
- tests/negative/image.cpp
Touches up the following VUIDs:
- VUID-VkImageCreateInfo-flags-00949
- VUID-VkImageCreateInfo-imageType-00954
Move code to stateless validation.
Improve error messages.
Move code out of `NegativeImage.ImageMisc` which reveals issue
on known issue MacOS / Android where VUIDs are triggered.
Best solution is to just run on MockICD. Trying to fix the issue
complicates the tests and triggers other VUIDs for little gain.
There is also little gain to running this test on real hardware.
Minor cleanup:
- Create DefaultImageInfo helper funciton.
- Remove temp create infos
> layers: Cleanup various CUBE_COMPATIBLE_BIT validation

- scripts/vk_validation_stats.py
1. We were not tracking the tests anymore since making the new `negative` folder
2. It is annoying listing all the "main" layer files, so just use `glob`
> scripts: Use glob to get files for vk_validaiton_stats.py

- build-android/jni/Android.mk
- layers/core_checks/cc_shader.cpp
- layers/core_checks/core_validation.h
- layers/state_tracker/shader_module.cpp
- layers/state_tracker/shader_module.h
- tests/CMakeLists.txt
- tests/device_profiles/max_profile.json
- tests/framework/layer_validation_tests.h
- tests/negative/shader_mesh.cpp
- tests/positive/shaderval.cpp
Adds `VUID-RuntimeSpirv-maxMeshSharedMemorySize-08754` and `VUID-RuntimeSpirv-maxTaskSharedMemorySize-08759` which check the Workgroup Shader memory size against Mesh and Task shaders
> Add Mesh/Task shader workgroup memory limits

- tests/negative/dynamic_state.cpp
the `ExtendedDynamicState3Disabled` and `ExtendedDynamicState3Enabled` test were very large and hard to debug a single thing in them
This breaks them up to more manageable bite size pieces
> tests: Break up VK_EXT_extended_dynamic_state3 tests

- tests/negative/dynamic_rendering.cpp
This is an attempt to create a "common init" that is scoped to only the tests in the file 
We had something like this before but the difference 
- This is not global
- Kept this as "basic" to prevent having to read the Init logic to understand what you are init-ing
- We can prepend this call with `AddRequiredExtensions` to add more extension easily if needed
This alone reduces 1100 lines we copy-and-pasted from the Dynamic Rendering tests
> tests: Create a InitBasicDynamicRendering

- tests/framework/binding.cpp
- tests/framework/binding.h
- tests/negative/external_memory_sync.cpp
- tests/positive/external_memory_sync.cpp
- tests/positive/sync_object.cpp
Now we can run fd posix handle tests on Windows through MockICD.
Vulkan API for posix handles are defined in a cross platform way, so it's possible to write related code without platform #ifdefs. This change removes restriction in the test framework that vk_testing::Fence/Semaphore supports posix handle only in non-Windows environments.
If the test is built around `ExternalHandle` abstraction, then that abstraction if moved to corresponding test suite.
> tests: Allow fd posix handle testing on Windows

- layers/generated/dynamic_state_helper.cpp
- layers/generated/dynamic_state_helper.h
- layers/state_tracker/pipeline_state.cpp
- layers/state_tracker/pipeline_state.h
- scripts/dynamic_state_generator.py
The spec talks about 
> Dynamic state values set via pDynamicState must be ignored if the state they correspond to is not otherwise statically set by one of the state subsets used to create the pipeline.
This change I went through every `VkDynamicState` value and mapped to the structs that are listed for each GPL subset. The switch case has no `default` so we catch any new dynamic state values that get added
I plan to write some tests, but wanted to see CI first and make sure I have the idea correct here
> layers: Dynamic State for GPL

- layers/error_message/unimplementable_validation.h
- scripts/vk_validation_stats.py
from https://gitlab.khronos.org/vulkan/vulkan/-/issues/3475
This is in effort to mark VUs that are just not possible with the scope of a Vulkan Layer
Each item added in future should have an explanation as well
> layers: Add an unimplementable_validation.h file

- layers/core_checks/cc_pipeline_graphics.cpp
- layers/state_tracker/cmd_buffer_state.h
- layers/state_tracker/pipeline_state.cpp
- layers/state_tracker/pipeline_state.h
- tests/framework/render.cpp
- tests/framework/render.h
- tests/negative/command.cpp
- tests/positive/dynamic_state.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/5783
There is a lot more work to follow-up with the PR after, but for now, it adds a proper check to `LAST_BOUND_STATE` to check if `DepthWriteEnable` is really set or not
> DepthTestEnable overrides DepthWriteEnable

- build-android/known_good.json
- docs/gpu_validation.md
- layers/generated/spirv_tools_commit_id.h
- layers/gpu_validation/gpu_utils.cpp
- layers/gpu_validation/gpu_utils.h
- layers/gpu_validation/gpu_validation.cpp
- layers/gpu_validation/gpu_validation.h
- scripts/known_good.json
- tests/framework/layer_validation_tests.cpp
- tests/negative/gpu_av.cpp
- tests/positive/gpu_av.cpp
Split per-DescriptorSet state into separate memory blocks which are accessed via an array of buffer device addresses. This is being done to make it easier to update state for a single DescriptorSet without rebuilding the old giant flat buffer.
NOTE: This change requires SPIRV-Tools to be updated
> gpu: Split descriptor set status into separate buffers

- layers/core_checks/cc_descriptor.cpp
- tests/negative/descriptors.cpp
- tests/positive/descriptors.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/5784
We did not have `VUID-vkCmdPushDescriptorSetWithTemplateKHR-pData-01686` implemented and that was the root cause of the crash
> Validate DSL in UpdateTemplate was not destroyed

- build-android/known_good.json
- layers/generated/spirv_tools_commit_id.h
- layers/gpu_validation/gpu_validation.cpp
- scripts/known_good.json
- tests/negative/gpu_av.cpp
The descriptor set and binding numbers are now part of the error record produced by the GPU-AV SPIR-V instrumentation. Add it to the error messages so that it is easier to find which descriptor needs to be fixed.
Fixes #5495
NOTE: This change requires SPIRV-Tools to be updated
> gpu: Add descriptor set and binding numbers to GPU-AV errors

- tests/negative/dynamic_rendering.cpp
- tests/negative/graphics_library.cpp
- tests/negative/ycbcr.cpp
- tests/positive/graphics_library.cpp
- tests/positive/ycbcr.cpp
Adds a `InitBasicGraphicsLibrary` and `InitBasicYcbcr` helper to help reduce 400 more lines of copy-and-pasting
> tests: Add Init helper for GPL and YCbCr

- layers/core_checks/cc_render_pass.cpp
- tests/framework/binding.h
- tests/framework/layer_validation_tests.cpp
- tests/framework/layer_validation_tests.h
- tests/negative/fragment_shading_rate.cpp
- tests/negative/multiview.cpp
- tests/negative/others.cpp
- tests/negative/renderpass.cpp
- tests/negative/subpass.cpp
- tests/positive/pipeline.cpp
- tests/positive/render_pass.cpp
- Closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/5288
Add VUIDs listed from this one:
https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkSubpassDescription2.html#VUID-VkSubpassDescription2-attachment-06912
to this one:
https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkSubpassDescription2.html#VUID-VkSubpassDescription2-attachment-06251
No new positive test, it does not make much sense here
> Add subpass attachment layout VUIDS 

- tests/framework/ray_tracing_objects.cpp
- tests/framework/ray_tracing_objects.h
- tests/negative/descriptor_buffer.cpp
- tests/negative/ray_tracing.cpp
Try to consistently use `blas` (bottom level acceleration structure) and `tlas` (top level acceleration structure) for acceleration structure variable names. This naming convention can probably be considered as the standard found in the literature.
> Cleanup some RT tests variable names

- layers/core_checks/cc_cmd_buffer_dynamic.cpp
- layers/core_checks/cc_drawdispatch.cpp
- layers/core_checks/cc_pipeline_graphics.cpp
- layers/core_checks/core_validation.h
- layers/state_tracker/pipeline_state.cpp
- layers/state_tracker/pipeline_state.h
- layers/sync/sync_validation.cpp
This does
- Use `LAST_BOUND_STATE` to pass around draw time validation that need both
- Move dynamic state checks for Depth/Stencil into `LAST_BOUND_STATE`
> Move rest of dynamic depth/stencil to lastBoundState

- layers/state_tracker/pipeline_state.cpp
- tests/positive/graphics_library.cpp
Re-reading the spec, things like `VkPipelineMultisampleStateCreateInfo` dynamic state can be set in **either** fragment output OR fragment shader state
Added Positive tests as well
> layers: Fix dynamic GPL bug

- layers/core_checks/cc_cmd_buffer_dynamic.cpp
- layers/core_checks/core_validation.h
- layers/generated/dynamic_state_helper.cpp
- layers/generated/dynamic_state_helper.h
- layers/state_tracker/cmd_buffer_state.cpp
- layers/state_tracker/cmd_buffer_state.h
- layers/state_tracker/state_tracker.cpp
- scripts/dynamic_state_generator.py
- tests/negative/dynamic_state.cpp
- tests/positive/dynamic_state.cpp
Closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/5551 (maybe even https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/5677)
Refactor how we track dynamic state, the previous `status` had bugs, the way  around it was simply to us the same `CBDynamicFlags` in both the Command Buffer and Pipeline. Before, we were trying to track Pipeline state in `CMB_BUFFER_STATE`
> Fix how Dynamic State is tracked

- scripts/vk_validation_stats.py
Currently the tests were not being listed correctly, now it looks like
> scripts: Fix tests listed in vk_validation_stats

- layers/core_checks/cc_image.cpp
- tests/positive/command.cpp
Issue with `VkCmdClearAttachments` was spotted after changing VL version to 1.3.243 and higher.
This is very similar to issue #657.
While using `VkCmdClearAttachments` in secondary command buffer with null in framebuffer pointer at inheritance structure I see that application is crashing in `CoreChecks::PreCallValidateCmdClearAttachments`. VL are trying to operate on image view's that comes from framebuffer pointer which is NULL.
I propose to add additional conditions to if statement for covering that case (skip checking framebuffer related objects when framebuffer pointer is NULL).
> layers: Add condition to validate clear attachments

- layers/core_checks/cc_synchronization.cpp
- layers/core_checks/core_validation.h
- layers/sync/sync_vuid_maps.cpp
- layers/sync/sync_vuid_maps.h
- tests/negative/dynamic_rendering.cpp
- tests/positive/dynamic_rendering.cpp
This PR include the missing barrier support for vkCmdPipelineBarrier when extension enabled.
> layers: Add support VK_EXT_shader_tile_image 

- layers/best_practices/best_practices_error_enums.h
- layers/best_practices/bp_device_memory.cpp
closes #4730
Currently I'd just like to remove this false positive before our SDK release.
Here is my rational.
1.) It generates false positives. See issue for details.
2.) As discussed in the issue this way of checking for mem requirements is questionable. Just checking you called the function isn't very robust.
3.) It doesn't have any testing
My current plan of action is remove this invalid logging for the upcoming SDK release, then implement essentially the same thing except more robustly based on the advice here:
> Yeah it may end up being better to check the inputs for the memory binding function and emitting a warning based on that than to track which functions were called where + associated data. Looking for specific function calls probably really isn't that useful.
Thoughts?
> bp: Remove best practice warnings generating false positives

- layers/containers/subresource_adapter.cpp
- tests/framework/layer_validation_tests.cpp
- tests/framework/render.cpp
I noticed these 3 `WORKAROUND` but didn't want to remove them when trying to originally setup the Profile/MockICD flow
I pinpointed the 3 commits that added these
https://github.com/KhronosGroup/Vulkan-ValidationLayers/commit/3f6978b4da36395461e2c93b1e3e64550205c4db
https://github.com/KhronosGroup/Vulkan-ValidationLayers/commit/b9659a01b805b9b61520c4d1cd95521c065bd617
https://github.com/KhronosGroup/Vulkan-ValidationLayers/commit/4ac77b358bfb8e7d29db34c4ab72508cd02433ff
Looking at it seems to not be needed anymore, also passed all the tests locally, so going to hope CI also is just happy with this
> tests: Remove WORKAROUND for old devsim setup

- layers/core_checks/cc_render_pass.cpp
- layers/sync/sync_utils.cpp
- layers/sync/sync_utils.h
These functions can produce unexpected result. The problem is that `GetLogicallyEarLiest(Latest)GraphicsPipelineStage` tries to create global ordering of __all__ pipeline stages (not only graphics as the name suggests). So, if the mask specifies `fragment+raytracing` stages then the earliest stage will always be evaluated to a `fragment` stage (because it has lower index), independenty if the application logic is concerned with the fragment or with the raytracing stage.
Also added a comment here:
https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/4246#discussion_r1190329610
This PR is a side effect from a parallel work to update current syncval codegen to use xml input instead of `validusage.json` and adhoc text snippets.
> layers: Remove global stage ordering functions

- layers/core_checks/cc_queue.cpp
The sparse-binding check has a copy-paste issue, it uses `bind_info.bufferBindCount` when iterating over the opaque image binds, causing it to possibly read-out-of-bounds or access garbage pointers. I had a crash in the validation layers during a submission of sparse-buffer-binds where `pImageOpaqueBinds` was set to garbage since `imageOpaqueBindCount` was 0 (in which case the pointer is ignored per spec).
> Fix imageOpaque sparse binding crash

- layers/core_checks/cc_pipeline_graphics.cpp
cb_state.activeRenderPass will always be null when logging kVUID_Core_DrawState_NoActiveRenderpass.  Layers would always crash due to dereferencing cb_state.activeRenderPass for inclusion in the LogObjectList.
> layers: Prevent crash on Core_DrawState_NoActiveRenderpass

- tests/negative/shader_push_constants.cpp
- tests/positive/shader_storage_image.cpp
After much refactoring of the Shader Validation over last year, these tests show that both https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/4881 and https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/2450 can be closed as we are now properly handling things per-Entrypoint!
> tests: Add tests for Multi-Entrypoint

- BUILD.md
- layers/android/CMakeLists.txt
- layers/utils/android_ndk_types.h
- layers/vk_layer_config.cpp
Use system_properties.h functions instead of spawning a process to run the getprop command.
NOTE: These functions are only supported in Android API version 26 or higher.
Fixes #4605
> layers: Improve GetEnvironment() for android

- BUILD.gn
- build-android/jni/Android.mk
- layers/CMakeLists.txt
- layers/core_checks/cc_descriptor.cpp
- layers/gpu_validation/gpu_validation.cpp
- layers/gpu_validation/gpu_validation.h
- layers/gpu_validation/gv_descriptor_sets.cpp
- layers/gpu_validation/gv_descriptor_sets.h
- layers/state_tracker/cmd_buffer_state.cpp
- layers/state_tracker/descriptor_sets.cpp
- layers/state_tracker/descriptor_sets.h
- layers/state_tracker/state_tracker.cpp
- layers/state_tracker/state_tracker.h
Rather than allocating memory for each descriptorset in every vkCmdBindDescriptorSets() call, track changes to the descriptors and only allocate new memory when there is a change.
> gpu: Lazily allocate gpu-side DescriptorSet data

- layers/state_tracker/shader_module.cpp
- tests/positive/sparse.cpp
Closes #5870 and tests in `dEQP-VK.sparse_resources.shader_intrinsics.2d_sparse_fetch.*` for CTS
The issue is `OpImageSparseTexelsResident`, while being `OpImage*` actually has no `OpImage` operand, so there is no way to have a `ImageAccess` object around it
Test and special assert added in case this gets accidentally added in the future
> Remove OpImageSparseTexelsResident from ImageAccess

- docs/shader_validation.md
- tests/positive/atomics.cpp
I have an upcoming change for removing the final `FindVariableAccesses` usages
I pulled this test and doc out as can be used now
> Add OpImageTexelPointer atomic test

- build-android/jni/Android.mk
- layers/state_tracker/shader_module.cpp
- layers/state_tracker/shader_module.h
- tests/CMakeLists.txt
- tests/positive/shader_image_access.cpp
should now close https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/5870
This provides a workaround fix to not have apps crash if the `ImageAccess` hits a Function call
The https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/5614 issue already is tracking adding proper support. I added many tests, but want to fix the crash as adding a proper fix will take more time and testing
The way GLSL and Tint (Dawn's WGL compiler) handle function calls of Images is different so added both variation tests as well
> layers: Prevent crash for Image Access through function calls

- BUILD.md
- scripts/CMakeLists.txt
Remove error check entirely. Not very useful and easy to become outdated.
> cmake: Fix invalid VS version check

- tests/device_profiles/max_profile.json
- tests/negative/buffer.cpp
- tests/negative/descriptor_buffer.cpp
- tests/negative/sparse.cpp
Part of https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/5842
Adds missing tests for
- `VUID-VkBufferCreateInfo-flags-00915`   | sparse 
- `VUID-VkBufferCreateInfo-flags-00916`   | sparse 
- `VUID-VkBufferCreateInfo-flags-00917`   | sparse 
- `VUID-VkBufferCreateInfo-size-06409`    | (VK_VERSION_1_3,VK_KHR_maintenance4) 
- `VUID-VkBufferCreateInfo-usage-08103`   | (VK_EXT_descriptor_buffer)
> tests: Add missing vkCreateBuffer tests

- layers/android/CMakeLists.txt
- tests/CMakeLists.txt
- tests/android/CMakeLists.txt
Use CMAKE_SYSTEM_VERSION to check Android API level
Use CMAKE_ANDROID_NDK instead of ANDROID_NDK
Print Android API / NDK version.
Install tests/layer to the same location.
Remove INSTALL_TESTS for simplicity.
> android: Cleanup Android CMake code

- layers/state_tracker/shader_module.cpp
- tests/positive/shader_image_access.cpp
we were asserting for `OpCopyObject`
For now going to just skip all image access when not sure what we might have. This will require **much** more testing to re-enable
> layers: Fix crash on OpCopyObject being used for image access

- scripts/CMakeLists.txt
- scripts/update_deps.py
Makes switching architectures easier since CMake will delete old build artifacts.
> scripts: Clean fetched dependencies on new configuration

- .github/workflows/formatting.yml
- .github/workflows/vvl.yml
- ci: Use fail-fast judiciously
- ci: Fix permissions
- ci: Cleanup compiler usage for linux testing
- ci: Use 64 bit compiler when targeting x86
> Various GHA improvements

- layers/state_tracker/cmd_buffer_state.cpp
Remove unnecessary stage_flags variable in
CMD_BUFFER_STATE::ResetPushConstantDataIfIncompatible.
From https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/5829#discussion_r1200761011.
> layers: Remove unnecessary stage_flags variable

- layers/stateless/sl_descriptor.cpp
- tests/negative/descriptors.cpp
Adds 2 tests for https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/5842
Currently we validate `VUID-VkDescriptorSetLayoutBinding-descriptorType-00282` in  the `ObjectLifetimes::PreCallValidateCreateDescriptorSetLayout`
If you turn off `ObjectLifetimes` you can crash as the `VkSampler` is bad, but the stateless check was only checking if it was `VK_NULL_HANDLE`
> Remove ObjectLifetime check from stateless

- BUILD.md
- layers/core_checks/cc_android.cpp
- layers/core_checks/cc_device_memory.cpp
- layers/utils/android_ndk_types.h
- layers/vk_layer_config.cpp
- tests/CMakeLists.txt
- tests/framework/android_hardware_buffer.h
- tests/negative/android_hardware_buffer.cpp
- tests/positive/android_hardware_buffer.cpp
Removes usage of AHB_VALIDATION_SUPPORT and cleans up surrounding Android code.
Use C++17 std::from_chars to convert string to integer. It's also much safer to use considering it's non-allocating and non-throwing.
> android: Remove usage of AHB_VALIDATION_SUPPORT

- build-android/jni/Android.mk
- layers/core_checks/cc_shader.cpp
- tests/CMakeLists.txt
- tests/negative/pipeline_layout.cpp
- tests/positive/pipeline_layout.cpp
Make sure we are testing correctly that if both a `SAMPLER` and `SAMPLED_IMAGE` are sharing the same descriptor slot, it really is a `COMBINED_IMAGE_SAMPLER`
Also improved the VU wording to be more clear what is going on
> tests: Add tests if Sampler/SampledImage share same slot

- layers/core_checks/cc_shader.cpp
- tests/negative/vertex_input.cpp
- tests/positive/vertex_input.cpp
tied to https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/5906
We were giving false positives for Vertex Inputs if they were using a struct
This suppresses the false positive until the shader harness testing is setup and I can try fixing this
> layers: Remove false positive for Vertex Input Structs

- BUILD.gn
I believe this is the proper thing to do in chromium builds.  In chromiums buildroot the default is `no_rtti`:https://chromium.googlesource.com/chromium/src/+/master/build/config/BUILDCONFIG.gn#347
I think this may only work for some people because it appears when having `rtti` and `no_rtti`; the ordering of the flags may result in `rtti`.
I'm not sure what the criteria are for changing this behavior now though.
> Fixed rtti settings for chromium builds.

- layers/core_checks/cc_shader.cpp
- layers/state_tracker/shader_module.cpp
- tests/negative/shader_push_constants.cpp
- tests/positive/shader_push_constants.cpp
This is a temporary fix for https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/5911
It might still produce false positive  for `VUID-VkComputePipelineCreateInfo-layout-07987`, but decide that was **much better** then crashing from an assert.
I plan to put together a proper fix, but that will require a more work as we need more tests as it will be invasive, but want to get things unblocked for now
> layers: Fix crash with push constants using spec const

- layers/state_tracker/shader_module.cpp
- tests/positive/shader_image_access.cpp
Using `SPIRV-Hopper` I found a shader using `OpUndef` instead of a `OpLoad` in a `OpSampledImage`
I adjusted the logic to not just check if it is `OpFunctionParameter` but, if it is not the `OpLoad` I would expect, we just exit (as there might be other instructions this can be as well)
There is a lot left to this part of the code, but the goal of the PR is to not assert if someone's shader has a valid `OpUndef`
> layers: Handle OpUndef used for Image Accesses

- layers/error_message/unimplementable_validation.h
- layers/stateless/sl_external_object.cpp
- layers/stateless/stateless_validation.h
- layers/vulkan/generated/parameter_validation.cpp
- scripts/generators/parameter_validation_generator.py
- tests/negative/external_memory_sync.cpp
The wording of these VUs changed in 1.3.251 and they become implementable: 00665 and 00673.
Also added 00674/00666 for completeness.
No positive tests here. It's not trivial to create external non-opaque handles for testing purposes (for example, D3D11 surface). Validation is simple enough so probably not worth efforts.
> layers: Add previously unimplementable external memory VUs

- layers/vulkan/generated/spirv_grammar_helper.cpp
- layers/vulkan/generated/spirv_grammar_helper.h
- layers/vulkan/generated/vk_dispatch_table_helper.h
- scripts/generators/best_practices_generator.py
- scripts/generators/command_validation_generator.py
- scripts/generators/dispatch_table_helper_generator.py
- scripts/generators/dynamic_state_generator.py
- scripts/generators/external_revision_generator.py
- scripts/generators/format_utils_generator.py
- scripts/generators/helper_file_generator.py
- scripts/generators/layer_dispatch_table_generator.py
- scripts/generators/lvt_file_generator.py
- scripts/generators/object_tracker_generator.py
- scripts/generators/parameter_validation_generator.py
- scripts/generators/spirv_grammar_generator.py
- scripts/generators/spirv_validation_generator.py
Use `os.path.basename(__file__)` to print out file name, prevent needless typo errors (which we had some)
> scripts: Use python file built-in helper

- layers/core_checks/cc_cmd_buffer_dynamic.cpp
- layers/core_checks/cc_image.cpp
- layers/core_checks/cc_pipeline_graphics.cpp
- layers/core_checks/cc_render_pass.cpp
- layers/error_message/unimplementable_validation.h
- layers/stateless/sl_cmd_buffer.cpp
Now that we have a proper place to put these, I moved all these old VUIDs from old extensions that are not able to be hit ever, but currently are marked as "todo" from our stats script
> layers: Add unimplementable VUIDs from extensions

- .github/workflows/vvl.yml
- scripts/common_ci.py
- tests/negative/query.cpp
- tests/negative/wsi.cpp
- tests/positive/wsi.cpp
- Fix `NegativeQuery.PerformanceCreation`
- Enables FullScreen testing on MockICD only. Also made naming consistent Fullscreen -> FullScreen to make it easier to run tests.
- Enable CI testing
> Enable Win32 testing on CI

- layers/core_checks/cc_external_object.cpp
- tests/negative/object_lifetime.cpp
Adds VUIDs (fd and FUCHSIA handles) that it's illegal to import into the semaphore that is in use.
> layers: Add missing vkImportSemaphore{Type} VUIDs

- layers/stateless/sl_cmd_buffer.cpp
- layers/stateless/sl_descriptor.cpp
- layers/vulkan/generated/parameter_validation.cpp
- scripts/generators/parameter_validation_generator.py
- tests/negative/others.cpp
- tests/positive/other.cpp
Currently we have `kVUIDUndefined` where we should be using the proper VUID
Also `vk::FreeCommandBuffers(m_device->device(), m_commandPool->handle(), 2, nullptr);` was crashing because we were not actually calling into `manual_PreCallValidateFreeCommandBuffers`
> Fix VUID for CommandBuffers and DescriptorSets

- build-android/jni/Android.mk
- layers/core_checks/cc_render_pass.cpp
- layers/object_tracker/object_tracker_utils.cpp
- layers/stateless/sl_framebuffer.cpp
- tests/CMakeLists.txt
- tests/negative/imageless_framebuffer.cpp
- tests/negative/renderpass.cpp
- tests/positive/imageless_framebuffer.cpp
Adds ` VUID-VkFramebufferCreateInfo-flags-02778` for https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/5842
In adding the test, noticed we were actually getting a `VUID_Undefined`. I realize both Stateless and Object Tracker were actually doing the validation and it never made it to core
> Label framebuffer VUID correctly for non Imageless Framebuffers

- layers/CMakeLists.txt
- tests/CMakeLists.txt
- tests/README.md
- tests/device_profiles/spirv_hopper_profile.json
- tests/spirv_hopper/CMakeLists.txt
- tests/spirv_hopper/README.md
- tests/spirv_hopper/external/CMakeLists.txt
- tests/spirv_hopper/external/README.md
- tests/spirv_hopper/external/spirv_reflect.cpp
- tests/spirv_hopper/external/spirv_reflect.h
- tests/spirv_hopper/main.cpp
- tests/spirv_hopper/pass_through_shaders.cpp
- tests/spirv_hopper/spirv_hopper.cpp
- tests/spirv_hopper/spirv_hopper.h
- tests/spirv_hopper/vulkan_object.cpp
- tests/spirv_hopper/vulkan_object.h
Adds a new `SPIRV-Hopper` test harness
I have ran this on a lot of shaders generated from various places, and it now passes them all
As more shaders are added, this can be updated, but this is in good enough shape to start using for CI once merged
> tests: Add SPIRV-Hopper

- build-android/jni/Android.mk
- tests/CMakeLists.txt
- tests/negative/device_queue.cpp
- tests/negative/others.cpp
Adds `VUID-VkDeviceQueueCreateInfo-pQueuePriorities-00383` and `VUID-VkDeviceQueueCreateInfo-queueCount-00382` for https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/5842
Created new test file to put them in
> Add missing DeviceQueue tests

- layers/stateless/sl_cmd_buffer_dynamic.cpp
Improve the `vkCmdSetVertexInputEXT` limit errors by printing values
> layers: Add values to vkCmdSetVertexInput error

- layers/stateless/sl_cmd_buffer.cpp
- layers/stateless/sl_wsi.cpp
- tests/negative/wsi.cpp
There were 2 `ValidateArray` that were not correct, this removes them and adds tests
> Remove unused stateless for VkPresentRegionsKHR

- docs/creating_tests.md
- tests/framework/error_monitor.cpp
- tests/framework/error_monitor.h
- tests/framework/render.h
- tests/framework/test_framework.cpp
- tests/framework/test_framework.h
- tests/framework/test_framework_android.h
- tests/positive/other.cpp
Closes https://github.com/orgs/KhronosGroup/projects/15/views/1?pane=issue&itemId=22965268
Adds a `--print-vu` to view the VU error messages
This saves people time having to modify the VUID just to recompile and view what a new VU error message looks like for a test
> tests: Add --print-vu for viewing new VU messages

- layers/core_checks/cc_cmd_buffer.cpp
- layers/error_message/unimplementable_validation.h
- tests/negative/command.cpp
- tests/negative/others.cpp
- tests/positive/command.cpp
This VUID cannot be validated in vkCmdEndDebugUtilsLabelEXT
So I'm adding it to the unimplementable_validation.h file.
My plan is to help fix/clear up the specification.
Meanwhile fixing up this false positive and adding positive
testing to prevent a regression.
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/5671
> layers: Fix debug label validation

- layers/core_checks/cc_wsi.cpp
- layers/core_checks/core_validation.h
- layers/state_tracker/state_tracker.cpp
- layers/state_tracker/state_tracker.h
I suppose the change here: https://github.com/KhronosGroup/Vulkan-ValidationLayers/commit/2ece8add63fec67ae4716b0fc29d69d3508ae4ca only added VK_USE_PLATFORM_SCREEN_QNX elements to code generation. Still need core_checks/ and state_tracker/ updates in for QNX Screen Surface WSI.
Please let me know if there is a different process I should use for this. Thanks!
> layers: Add missing support for VK_QNX_screen_surface extension.

- layers/core_checks/cc_copy_blit_resolve.cpp
- layers/core_checks/core_validation.h
Move more items in copy_blit_resolve to use const ref where we know we can
Also unified naming to match other functions
> layers: Add Const Ref for CopyBlitResolve checks

- tests/framework/test_framework.cpp
These flags are not being consumes, most likely left over from old test framework code
> tests: Remove unused test args

- layers/core_checks/cc_render_pass.cpp
- tests/negative/imageless_framebuffer.cpp
`VUID-VkFramebufferCreateInfo-renderPass-08921` was added in the 1.3.252 headers
> layers: Label VUID 08921

- layers/core_checks/cc_image_layout.cpp
- layers/core_checks/cc_queue.cpp
- layers/core_checks/cc_render_pass.cpp
- layers/core_checks/core_validation.h
Move more items in Image Layout to use const ref where we know we can
also removed a `FRAMEBUFFER_STATE` that was never being used
There seems to be some code here that really belongs in state tracker, I can't remove `CMD_BUFFER_STATE *cb_state` because we are writing to it in this file, which seems strange
> layers: Add Const Ref for ImageLayout CoreChecks

- tests/framework/render.h
- tests/negative/android_hardware_buffer.cpp
- tests/negative/arm_best_practices.cpp
- tests/negative/best_practices.cpp
- tests/negative/descriptors.cpp
- tests/negative/dynamic_state.cpp
- tests/negative/gpu_av.cpp
- tests/negative/others.cpp
- tests/negative/pipeline.cpp
- tests/negative/protected_memory.cpp
- tests/negative/query.cpp
- tests/negative/renderpass.cpp
- tests/negative/shader_push_constants.cpp
- tests/negative/subpass.cpp
- tests/negative/sync_object.cpp
- tests/negative/sync_val.cpp
- tests/positive/android_hardware_buffer.cpp
- tests/positive/command.cpp
- tests/positive/descriptors.cpp
- tests/positive/gpu_av.cpp
- tests/positive/pipeline.cpp
- tests/positive/pipeline_topology.cpp
- tests/positive/protected_memory.cpp
- tests/positive/query.cpp
- tests/positive/render_pass.cpp
- tests/positive/shader_storage_image.cpp
These should in theory not be used anymore, so rather not leave them around for people to copy and paste wrongly
> tests: Remove unused IsPlatform checks

- scripts/common_ci.py
This tests fails sporadically with TSAN enabled.
Examples:
https://github.com/KhronosGroup/Vulkan-ValidationLayers/actions/runs/5231916205/jobs/9446352482
https://github.com/KhronosGroup/Vulkan-ValidationLayers/actions/runs/5226531209/jobs/9437280878
> ci: Skip PositiveSyncObject.WaitTimelineSemThreadRace

- CMakeLists.txt
- layers/core_checks/cc_shader.cpp
This warning is actually very useful and pointed out a real issue with the code.
See the compiler docs for a detailed walkthrough:
https://learn.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-4-c4754?view=msvc-170
> cmake: Fix MSVC warning 4754

- layers/core_checks/cc_pipeline_graphics.cpp
- layers/state_tracker/cmd_buffer_state.cpp
- layers/state_tracker/cmd_buffer_state.h
- layers/state_tracker/pipeline_state.cpp
- layers/state_tracker/pipeline_state.h
- layers/state_tracker/state_tracker.cpp
Moving 2 functions found in `CMD_BUFFER_STATE` that are better placed in `LAST_BOUND_STATE` as that is the new go-to location as it contains the pipeline and command buffer state together
> layers: Move Dynamic State helper to LastBoundState

- layers/core_checks/cc_pipeline_graphics.cpp
- layers/stateless/sl_pipeline.cpp
- tests/negative/vertex_input.cpp
- tests/positive/dynamic_state.cpp
Related (but not fixes) for https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/5954
This for the moment prevents false positives if using `VK_DYNAMIC_STATE_VERTEX_INPUT_EXT`
There is a lot more care that is needed in the vertex input logic then I realized, rather slowly fix it up, add many more tests before removing this dynamic state check
> layers: Remove false positive for dynamic vertex input

- tests/device_profiles/max_profile.json
Adds `VK_ARM_rasterization_order_attachment_access` features (goes with https://github.com/KhronosGroup/Vulkan-Profiles/pull/447)
Adds `VK_EXT_shader_object` as the one test that uses it was not running (and probably will be used in the near future more)
> tests: Add missing max_profile ext/features

- layers/core_checks/cc_shader.cpp
- tests/negative/vertex_input.cpp
The 1.3.253 spec introduced 2 of the VUs I added in https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/5757
This just gives them the proper VUID
> layers: Label new Vertex 64-bit VUIDs

- layers/core_checks/cc_cmd_buffer.cpp
- layers/core_checks/cc_pipeline_graphics.cpp
- layers/state_tracker/cmd_buffer_state.cpp
- layers/state_tracker/cmd_buffer_state.h
- layers/state_tracker/state_tracker.cpp
There seems to be a need to clean up the Viewport/Scissor dynamic state Secondary Command Buffer Inheritance logic, but for now, the goal is to move all dynamic state value data into the `DynamicStateValue` struct so it is in a single location
> layers: Move Viewport and Scissor to DynamicState

- layers/core_checks/cc_cmd_buffer.cpp
- layers/core_checks/cc_query.cpp
- layers/core_checks/cc_ray_tracing.cpp
- layers/core_checks/core_validation.h
- layers/state_tracker/cmd_buffer_state.cpp
- layers/state_tracker/query_state.h
- layers/state_tracker/state_tracker.cpp
The first thing this does is make `ValidatePerformanceQueryResults` use a const ref
Then I went through and notices a lot of cleanup needed around `QueryObject`
- Make all uses of `QueryObject` be consistent with name of `query_obj`
- We used `slot` in half the functions, I agree it makes reading the code easier, but went through and made it same everywhere
-  Removed a `QueryObject` constructor never being used
- Combined `QueryObject` constructors because it was confusing because they both wanted to use `uint32_t` parameters, so just combined into a single constructor
> layers: Improve Query state code

- CMakeLists.txt
- layers/stateless/sl_descriptor.cpp
- layers/utils/vk_layer_extension_utils.cpp
- layers/utils/vk_layer_extension_utils.h
- layers/vulkan/generated/chassis.cpp
- scripts/generators/layer_chassis_generator.py
The main issue is the globals instance_extensions and device_extensions defined in chassis.cpp
This name is already used by ValidationObject which is what is causing the warning.
https://learn.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-4-c4459?view=msvc-170
This commit also removes the usage of ARRAY_SIZE in favor of std::array and removes extern "C" usage that didn't need to exist.
> cmake: Fix MSVC warning 4459

- layers/stateless/sl_image.cpp
- tests/positive/image.cpp
VL falsely marks flag VK_IMAGE_COMPRESSION_DEFAULT_EXT as invalid. The value of this enum is 0 and ValidateFlags function used to check if flags are properly set has 'flag_type' parameter set to kRequiredSingleBit which doesnt allows 0 as flag value.
Changing flag_type to kOptionalSingleBit resolves issue.
This fixes issue #5971
> layers: VK_IMAGE_COMPRESSION_DEFAULT_EXT flag fix

- tests/framework/layer_validation_tests.cpp
- tests/framework/layer_validation_tests.h
- tests/negative/external_memory_sync.cpp
Reduces calls in `tests/framework/layer_validation_tests.h` and moves to the test file that is using them
> tests: Move ExternalMemorySync helpers to test file

- tests/negative/buffer.cpp
- tests/negative/descriptor_buffer.cpp
- tests/negative/dynamic_state.cpp
- tests/negative/external_memory_sync.cpp
- tests/negative/fragment_shading_rate.cpp
- tests/negative/image.cpp
- tests/negative/others.cpp
- tests/negative/protected_memory.cpp
- tests/negative/sampler.cpp
- tests/negative/sparse.cpp
- tests/negative/video.cpp
- tests/negative/wsi.cpp
- tests/negative/ycbcr.cpp
We have these `CreateBufferTest`/`CreateImageTest` helpers, tried to find all places that weren't using them to reduce code usage
> tests: Use Create*Test helpers

- scripts/common_ci.py
- tests/framework/layer_validation_tests.cpp
- tests/framework/layer_validation_tests.h
Fixes the following error reported by TSAN:
```
==================
WARNING: ThreadSanitizer: double lock of a mutex (pid=62035)
#0 pthread_mutex_lock ../../../../src/libsanitizer/sanitizer_common/sanitizer_common_interceptors.inc:4240 (libtsan.so.0+0x53908)
#1 __gthread_mutex_lock /usr/include/x86_64-linux-gnu/c++/11/bits/gthr-default.h:749 (vk_layer_validation_tests+0x120aa4a)
#2 std::mutex::lock() /usr/include/c++/11/bits/std_mutex.h:100 (vk_layer_validation_tests+0x120ace6)
#3 std::lock_guard<std::mutex>::lock_guard(std::mutex&) /usr/include/c++/11/bits/std_mutex.h:229 (vk_layer_validation_tests+0x120ed40)
#4 ThreadTimeoutHelper::OnThreadDone() /home/juan/projects/vvl/tests/framework/layer_validation_tests.cpp:195 (vk_layer_validation_tests+0x11dfd3e)
#5 …
```
> tests: Fix PositiveCommand.ThreadedCommandBuffersWithLabels

- BUILD.gn
- build-android/jni/Android.mk
- layers/CMakeLists.txt
- layers/core_checks/cc_render_pass.cpp
- layers/core_checks/cc_synchronization.cpp
- layers/state_tracker/render_pass_state.cpp
- layers/stateless/sl_render_pass.cpp
- layers/utils/convert_utils.cpp
- layers/utils/convert_utils.h
- tests/CMakeLists.txt
- tests/framework/layer_validation_tests.h
- tests/positive/subpass.cpp
* Removes duplicated call to `ValidateRenderPassPipelineBarriers`.
* Fixes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/4258
* Renames `convert_to_renderpass2` files to `convert_utils` to use it as a general place for conversion routines.
DETAILS:
`ValidateRenderPassPipelineBarriers` is used to validate subpass self-dependencies. It can be called through these code paths:
1. By ValidateCmdPipelineBarrier2
2. By ValidateCmdSetEvent2/ValidateCmdWaitEvents2
In the first case we have two duplicate calls to `ValidateRenderPassPipelineBarriers`. It's called directly by `ValidateCmdPipelineBarrier2`, but also as part of `ValidateDependencyInfo`.
```mermaid
flowchart LR
ValidateCmdPipelineBarrier2-->ValidateRenderPassPipelineBarriers …
```
> layers: Do not check self-dependency in ValidateDependencyInfo

- CMakeLists.txt
- layers/CMakeLists.txt
- tests/CMakeLists.txt
- tests/layers/CMakeLists.txt
This is consistent with how we treat GCC/Clang warnings
> cmake: Disable warnings per target

- layers/gpu_validation/debug_printf.cpp
- layers/gpu_validation/gpu_utils.h
- layers/layer_options.cpp
- layers/utils/vk_layer_utils.h
- tests/framework/render.cpp
- tests/negative/arm_best_practices.cpp
Using this function with std::transform on a std::string can result in truncation from int to char warnings with some compilers.
> layers: Avoid warnings from std::tolower

- docs/synchronization.md
- layers/best_practices/best_practices_validation.h
- layers/state_tracker/image_state.cpp
- layers/state_tracker/image_state.h
- layers/state_tracker/state_tracker.cpp
- layers/state_tracker/state_tracker.h
- layers/sync/sync_validation.cpp
- layers/sync/sync_validation.h
- tests/framework/render.h
- tests/negative/sync_val.cpp
1. DRY up the IMAGE_STATE subclass implementation.
2. Add sync val derived class for image
3. Add fake space allocation for opaque representations
4. Convert AccessContext to single flat range map for both linear bindings and opaque representations.
> Refactoring and infrastructure for syncval aliasing support

- tests/framework/layer_validation_tests.cpp
- tests/framework/layer_validation_tests.h
- tests/negative/dynamic_rendering.cpp
- tests/negative/transform_feedback.cpp
- tests/positive/dynamic_rendering.cpp
- tests/positive/graphics_library.cpp
- tests/positive/ycbcr.cpp
adds a `void *pNextFeatures = nullptr` to the `Init` tests helpers currently to allow more code to be reduced by using them
Goal is to add more `Init` helpers, but setting up the "how they should all look like" style with this
> tests: Expand Init helpers to allow other features

- tests/framework/layer_validation_tests.h
- tests/negative/dynamic_state.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/6020
1. splits tests up
2. Adds missing VUID from undefined values being set
> tests: Split and fix RasterizationLine tests

- layers/gpu_validation/gpu_validation.cpp
VK_EXT_descriptor_buffer GPU-AV is a WIP
Warn if it's used with GPU-AV.  #6025
> Warn if descriptor buffer is enabled with GPU-AV

- layers/core_checks/cc_ray_tracing.cpp
- tests/negative/ray_tracing.cpp
Temporary fix for https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/6040
Will soon work on a true fix
> layers: Disable calls to ComputeScratchSize (temporary CTS fix)

- tests/framework/video_objects.h
- tests/negative/arm_best_practices.cpp
- tests/negative/best_practices.cpp
- tests/negative/gpu_av.cpp
- tests/negative/nvidia_best_practices.cpp
- tests/negative/sync_val.cpp
- tests/negative/video.cpp
Remove the stateless/parameter validation option from config settings
and leave it enabled by default.
Validation makes the assumption that stateless validation has run. In
addition, stateless validation is usually innocuous, having a negligible
affect on performance. For these reasons, it was determined that
stateless validation should always be enabled.
> layers: Remove stateless validation from config

- tests/spirv_hopper/pass_through_shaders.cpp
- tests/spirv_hopper/spirv_hopper.cpp
Adds a few misc things for SPIRV-Hopper
- Per-EntryPoint enumeration (for future support to handle multi-entry point shaders)
- Handle case where multiple structs are not known for passthrough shader
- Set `pRasterizationState` as it was hitting a Validation Error otherwise
> SPIRV-Hopper cleanup

- layers/core_checks/cc_cmd_buffer.cpp
@Tony-LunarG pointed out https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/5988 crashes CTS for
`dEQP-VK.dynamic_state.monolithic.inheritance.split` and `dEQP-VK.dynamic_state.fast_linked_library.inheritance.split`
These are for `VK_NV_inherited_viewport_scissor`
I can't reproduce the CTS crash nor have any knowledge to write a test
> layers: Fix ViewportScissorInheritanceTracker range

- tests/framework/layer_validation_tests.cpp
- tests/negative/arm_best_practices.cpp
- tests/negative/atomics.cpp
- tests/negative/best_practices.cpp
- tests/negative/descriptors.cpp
- tests/negative/pipeline.cpp
- tests/negative/pipeline_layout.cpp
- tests/negative/shader_compute.cpp
- tests/negative/shader_push_constants.cpp
- tests/negative/shader_spirv.cpp
- tests/negative/shader_storage_image.cpp
- tests/negative/shader_storage_texel.cpp
- tests/negative/subgroups.cpp
- tests/negative/sync_val.cpp
- tests/positive/atomics.cpp
- tests/positive/pipeline.cpp
- tests/positive/shader_compute.cpp
- tests/positive/shader_image_access.cpp
- tests/positive/shader_limits.cpp
- tests/positive/shader_push_constants.cpp
- tests/positive/shader_spirv.cpp
- tests/positive/shader_storage_image.cpp
- tests/positive/shader_storage_texel.cpp
From https://clang.llvm.org/extra/clang-tidy/checks/modernize/make-unique.html
Use `std::make_unique` for `VkShaderObj` in all the tests
> tests: Use make_unique for VkShaderObj

- layers/containers/custom_containers.h
Elements of std::initializer_list are constants and applying std::move to such elements does not produce movable object `&&` but `const &&`. At least with current version of C++ copy is needed. The original code was correct (move does not have effect) but it signaled wrong intent.
> layers: Do not use std::move with std::initiailzer_list

- layers/CMakeLists.txt
When building the repo with both tests enabled and Link Time Optimization, the tests do not have USE_ROBIN_HOOD_HASHING defined. This causes an ODR violation in vk_layer_validation_tests and VkLayer_device_profile_api because they both link to VkLayer_utils statically which *does* define USE_ROBIN_HOOD_HASHING.
Fixing this requires all components linking to robin_hood, which required moving `find_package(robin_hood CONFIG)` to the top level CMakeLists.txt so that the package is visible.
Fixes #6052
> build: Apply Robinhood setting to tests

- layers/vulkan/generated/spirv_validation_helper.cpp
- scripts/generators/base_generator.py
- scripts/generators/spirv_validation_generator.py
- scripts/generators/vulkan_object.py
Most of the logic replaced was
- The old way we had to gather up information that is just now in `VulkanObject::SpirvEnable`
- use f-string and array of strings
- Remove the functions as they aren't helpful to bounce around IMO from editing this file in the past
The generated code has a lot of changes, but it is just the ordering, it is now just ordered the way it is seen in the `vk.xml` instead of the arbitrary `sorted()` order from before
> scripts: Move SpirvValidationHelper to VulkanObject

- scripts/update_deps.py
Currently update_deps.py breaks if a dependency doesn't work on Android like the Vulkan Loader.
This is because we detect build platforms based on the host platform.
Current fix is to check for Android toolchain explicitly.
> cmake: Fix build_platform usage when dealing with Android

- layers/core_checks/cc_image.cpp
These new VUs make it possible to use VK_NV_linear_color_attachment without always getting a VVL error.
See: https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/5884
> layers: VVL coverage for new linear attachment VUs

- layers/vulkan/generated/vk_safe_struct.h
- layers/vulkan/generated/vk_safe_struct_utils.cpp
- scripts/generators/base_generator.py
- scripts/generators/generator_utils.py
- scripts/generators/helper_file_generator.py
- scripts/generators/safe_struct_generator.py
- scripts/generators/vulkan_object.py
- scripts/lvl_genvk.py
Started to move SafeStruct out, plan to do the Utils and Source as well (either in this PR or follow up)
> scripts: Move SafeStruct to VulkanObject

- layers/containers/custom_containers.h
- layers/containers/range_vector.h
- layers/state_tracker/state_tracker.cpp
- layers/state_tracker/state_tracker.h
- layers/sync/sync_validation.cpp
- tests/unit/buffer_positive.cpp
- Closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/6056
Also should fix Dan G issue
Adding a buffer to `buffer_address_map_` should now work as expected (in some cases adding a buffer could fail), and be faster.
> layers: Fix `vkGetBufferDeviceAddress` state recording bug

- scripts/known_good.json
Relevant PRs I made to fix these warnings in these repos:
https://github.com/KhronosGroup/glslang/pull/3241
https://github.com/google/googletest/pull/4288
https://github.com/google/googletest/pull/4290
https://github.com/google/googletest/pull/4293
> cmake: Update googletest / glslang to fix CMake warnings

- scripts/android.py
- tests/android/CMakeLists.txt
- tests/framework/test_framework.cpp
APK generated from this script successfully ran on a Pixel 3!
Fixes to make this happen:
- The name of test binary was wrong.
- Added logic to copy libc++_shared.so
- CMake build doesn't use test_framework_android.cpp and failed due to lack of environment variables.
> android: Generate valid APK from CMake binaries

- layers/vk_layer_config.cpp
Android API 26 allows property keys longer than 32 characters. Since API level 26 is the minimum version required for VVL, allow system properties to be used for modifying any setting that is controlled via an environment variable on desktop.
> android: Use debug.vvl. for settings

- layers/VkLayer_khronos_validation.json.in
- layers/gpu_validation/gpu_validation.cpp
- layers/gpu_validation/gpu_validation.h
- layers/state_tracker/state_tracker.cpp
- layers/state_tracker/state_tracker.h
- layers/vk_layer_settings.txt
- tests/unit/gpu_av_positive.cpp
Should be better than 1 buffer per draw, and now accounts for buffers created after draw is recorded
> Use a single buffer for buffer device address GPU-AV

- layers/gpu_validation/gpu_validation.cpp
- tests/unit/gpu_av_positive.cpp
Addresses this test case: https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/4968#issuecomment-1354342939
> sync: Fix semaphore timeout with gpu av

- .github/workflows/vvl.yml
Adds ccache to CMake Android builds using CMAKE_\<LANG\>_COMPILER_LAUNCHER.
Also makes the macos build consistent with the other builds.
> Minor cccache CI fixes

- layers/state_tracker/state_tracker.cpp
- layers/state_tracker/state_tracker.h
- tests/framework/render.cpp
- tests/unit/dynamic_state.cpp
- tests/unit/dynamic_state_positive.cpp
- tests/unit/pipeline.cpp
- tests/unit/pipeline_positive.cpp
Update tests accordingly, accounting for VUID-vkCmdDraw-None-07834 and VUID-vkCmdDraw-None-08608
> layers: Add dynamic state tracking for `vkCmdSetDepthBias2EXT`

- layers/state_tracker/cmd_buffer_state.h
- layers/state_tracker/state_tracker.cpp
- layers/state_tracker/state_tracker.h
Doing so improve memory accesses, it can make a good difference when performing a linear search. 
Improves upon https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/6072
> layers: Store buffers in `buffer_address_map_` using raw pointers

- layers/state_tracker/state_tracker.cpp
- layers/state_tracker/state_tracker.h
- tests/unit/dynamic_state_positive.cpp
Fix state tracking for vkCmdSetAttachmentFeedbackLoopEnableEXT.
Fixes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/6092.
> layers: Fix attachment feedback EXT state tracking

- layers/containers/subresource_adapter.cpp
All images were being treated as opaque (non-linear) accidentally. Restored implementation derived parameterizations.
> syncval: Restore byte accurate linear images

- layers/state_tracker/queue_state.cpp
Found accidentally while working on a different sync issue. Not sure if we had actual issues because of this.
> layers: Add write lock to protect timeline modification

- layers/core_checks/cc_queue.cpp
- layers/core_checks/core_validation.h
- tests/unit/command.cpp
closes #6109
Now the error messages reads like this:
> Validation Error: [ UNASSIGNED-CoreValidation-DrawState-CommandBufferSingleSubmitViolation ] Object 0: handle = 0x7ba00000c000, type = VK_OBJECT_TYPE_COMMAND_BUFFER; | MessageID = 0xec5fc304 | VkCommandBuffer 0x7ba00000c000[] recorded with VK_COMMAND_BUFFER_USAGE_ONE_TIME_SUBMIT_BIT has been submitted 2 times.
> layers: CommandBufferSingleSubmitViolation cleanup

- scripts/common_ci.py
PositiveQuery.ResetQueryPoolFromDifferentCB sporadically fails.
See failed run for reference:
https://github.com/KhronosGroup/Vulkan-ValidationLayers/actions/runs/5484689187/jobs/9992567221
<details>
```
[ RUN      ] PositiveQuery.ResetQueryPoolFromDifferentCB
==================
WARNING: ThreadSanitizer: lock-order-inversion (potential deadlock) (pid=8499)
Cycle in lock order graph: M283862531850684912 (0x000000000000) => M287802992546052168 (0x000000000000) => M283862531850684912
Mutex M287802992546052168 acquired here while holding mutex M283862531850684912 in thread T384:
#0 pthread_mutex_lock ../../../../src/libsanitizer/sanitizer_common/sanitizer_common_interceptors.inc:4240 (libtsan.so.0+0x53908)
#1 std::_Function_handler<bool (QueryObject const&), …
```
> ci: Add to TSAN blacklist

- layers/state_tracker/descriptor_sets.cpp
- tests/unit/gpu_av_positive.cpp
We need to use the current type of each mutable descriptor in the binding, rather than the type of the binding (which would always be mutable).
> layers: Fix descriptor copies with a mutable source

- layers/core_checks/cc_image.cpp
- tests/unit/image.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/6134
If you take a deep look you find `02251` VU indeed is just a VERY complex way of saying `vkGetPhysicalDeviceImageFormatProperties` must be `VK_SUCCESS`
This improves it and adds a test (didn't have one because its hard to guarantee the result to be non-success)
> Validation Error: [ VUID-VkImageCreateInfo-imageCreateMaxMipLevels-02251 ] Object 0: handle = 0x56229a852780, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0xbebcae79 | vkCreateImage(): The following parameters -
format (VK_FORMAT_E5B9G9R9_UFLOAT_PACK32)
type (VK_IMAGE_TYPE_2D)
tiling (VK_IMAGE_TILING_OPTIMAL)
usage (VK_IMAGE_USAGE_STORAGE_BIT)
flags (VkImageCreateFlags(0))
returned a non-success result (VK_ERROR_FORMAT_NOT_SUPPORTED) when calling …
> Improve message for 02251

- layers/state_tracker/state_tracker.cpp
- layers/vulkan/generated/vk_extension_helper.h
- scripts/generators/extension_helper_generator.py
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/4841
The new scripts don't need to have a workaround for extensions with 2 properties
> layers: Remove manual logic for extensions with 2 properties

- scripts/vk_validation_stats.py
this hopefully (as I see no reason why) will not change again and can be happy with this
> scripts: Fix path to tests for vk_validation_stats.py

- layers/core_checks/cc_drawdispatch.cpp
- layers/core_checks/cc_pipeline_graphics.cpp
- layers/core_checks/cc_shader.cpp
- layers/core_checks/core_validation.h
- layers/state_tracker/cmd_buffer_state.h
- layers/state_tracker/pipeline_state.h
- layers/state_tracker/shader_module.cpp
- layers/state_tracker/shader_module.h
- layers/state_tracker/state_tracker.cpp
- tests/framework/layer_validation_tests.h
- tests/unit/dynamic_state.cpp
- tests/unit/dynamic_state_positive.cpp
- tests/unit/shader_interface.cpp
- tests/unit/shader_interface_positive.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/5520
this adds `VUID-VkGraphicsPipelineCreateInfo-alphaToCoverageEnable-08891` and `VUID-vkCmdDraw-alphaToCoverageEnable-08919`
> Add alphaToCoverageEnabled VUs

- BUILD.gn
- build-android/jni/Android.mk
- layers/CMakeLists.txt
- layers/best_practices/bp_descriptor.cpp
- layers/best_practices/bp_pipeline.cpp
- layers/core_checks/cc_device.cpp
- layers/core_checks/cc_shader.cpp
- layers/core_checks/core_validation.h
- layers/gpu_validation/debug_printf.cpp
- layers/gpu_validation/gpu_utils.cpp
- layers/gpu_validation/gpu_utils.h
- layers/gpu_validation/gpu_validation.cpp
- layers/state_tracker/state_tracker.cpp
- layers/utils/shader_utils.cpp
- layers/utils/shader_utils.h
currently we have things from `gpu_av`(and BP will to in future) trying to access code in `core_checks/cc_shader.cpp` which is just structurally wrong
Created a proper util file to hold the various shader related things not specific to core checks
> layers: Move cc_shader.h to proper util

- .github/workflows/vvl.yml
- layers/android/CMakeLists.txt
- scripts/android.py
- tests/android/CMakeLists.txt
Avoids legacy issues with older versions of these tools.
> android: Require CMake 3.21+ and ndk r24+

- layers/vulkan/generated/vk_format_utils.cpp
- layers/vulkan/generated/vk_format_utils.h
- scripts/generators/format_utils_generator.py
Move from the various random functions to a single generate style
```python
if self.filename == 'vk_format_utils.h':
self.generateHeader()
elif self.filename == 'vk_format_utils.cpp':
self.generateSource()
```
> scripts: Refactor format utils to use new generate style

- layers/state_tracker/queue_state.cpp
- layers/vulkan/generated/chassis.cpp
- layers/vulkan/generated/chassis.h
- scripts/generators/layer_chassis_generator.py
- tests/unit/sync_val_positive.cpp
Fixes `vkWaitSemaphores` timeouts while waiting for `vkSignalSemaphore` https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/4968#issuecomment-1613006858
Also fixes the same issue but for `vkGetSemaphoreCounterValue` <-> `vkSignalSemaphore` combination.
Potentially fixes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/4968
The root cause is that some commands perform blocking operations inside `Record` (ex. vkWaitSemaphores can't return until a signal is processed). `Record` calls themselves are protected by a mutex (except the case of fine grained locking). If the waiting condition of the blocked thread depends on another thread executing `Record` to update some state, this creates a deadlock. During a blocking operation, there's no need to keep the validation …
> sync: Fix semaphore wait timeout

- layers/best_practices/bp_copy_blit_resolve.cpp
- layers/best_practices/bp_render_pass.cpp
- layers/core_checks/cc_cmd_buffer.cpp
- layers/core_checks/cc_drawdispatch.cpp
- layers/core_checks/cc_image.cpp
- layers/core_checks/cc_pipeline.cpp
- layers/core_checks/cc_pipeline_graphics.cpp
- layers/core_checks/cc_render_pass.cpp
- layers/error_message/validation_error_enums.h
- layers/state_tracker/cmd_buffer_state.cpp
- layers/state_tracker/cmd_buffer_state.h
- layers/state_tracker/state_tracker.cpp
- layers/state_tracker/state_tracker.h
- layers/sync/sync_validation.cpp
- tests/framework/render.cpp
- tests/unit/command.cpp
- tests/unit/dynamic_rendering.cpp
- tests/unit/dynamic_rendering_positive.cpp
- tests/unit/renderpass.cpp
- tests/unit/subpass.cpp
- tests/unit/transform_feedback.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/5863
We have all these `if (activeRenderPass) {` which don't make sense because there is a bunch of implicit VUs in `ValidateCmd` that check if we are in a renderpass or not.
I went through and all the command that require to be in renderPass, I wrote a test (to confirm it won't crash) and then removed the redundant checks so now it is clear if we actually need to check for renderPass
some small house cleaning was done along the way
> layers: Guarantee there is an active renderpass

- layers/vulkan/generated/chassis.cpp
- layers/vulkan/generated/chassis.h
- scripts/generators/layer_chassis_generator.py
- tests/unit/sync_val_positive.cpp
Fixes the bug in my previous PR that it did not take into account multiple concurrent waiters (I tested only with a single one).
The test reproduces the issues with concurrent waiters and the test passes with this fix, also the client reports that long-standing issue finally works: https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/4968#issuecomment-1641676594
> layers: Add support for concurrent blocking operations

- CMakeLists.txt
- layers/CMakeLists.txt
- layers/vulkan/generated/object_tracker.cpp
- scripts/CMakeLists.txt
- scripts/generate_source.py
- scripts/generators/base_generator.py
- scripts/generators/enum_flag_bits_generator.py
- scripts/generators/extension_helper_generator.py
- scripts/generators/layer_chassis_generator.py
- scripts/generators/object_tracker_generator.py
- scripts/generators/stateless_validation_helper_generator.py
- tests/framework/layer_validation_tests.cpp
- tests/framework/layer_validation_tests.h
This re-does the API-specific parameterization needed to support downstream API variants like Vulkan SC after the generator script rewrites.
> build: Redo API parameterization

- .github/workflows/sdk_android_build.yml
Publishes binaries roughly 4 times faster since it uses a runner for each abi.
> ci: Improve Android SDK performance

- layers/core_checks/cc_shader_interface.cpp
- layers/state_tracker/shader_module.cpp
- layers/state_tracker/shader_module.h
- tests/unit/shader_interface_positive.cpp
Already have an issue #5374 
Found with `spirv-hopper` some shaders were crashing, added unit tests (since CI flow with spirv-hopper not fully setup)
> layers: Prevent crash for physicalStorageBuffer interface

- scripts/generate_source.py
The old script had a way to specify a custom output directory for generated files. The recent refactoring removed this option.
This option is important if your CI runs on a read-only version of the repository, and generated files/intermediates are written to a different folder before being processed (Bazel-like build).
> scripts: Restore the -o option on generate_source

- layers/core_checks/cc_shader.cpp
- scripts/known_good.json
- tests/CMakeLists.txt
I accidentally merged a fork of glslang in https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/6093
but proper glslang support is still in review https://github.com/KhronosGroup/glslang/pull/3248
this branch removes `CooperativeMatrixKHR` temporary if needed
> layers: Remove CooperativeMatrixKHR until glslang supports

- tests/android/CMakeLists.txt
Instruct linker to ignore dlclose for VVL
Links to relevant documentation:
https://github.com/android/ndk/issues/360
https://github.com/android/ndk/issues/360#issuecomment-339107521
https://github.com/android/ndk/releases/tag/r26-beta1
> android: Allow usage of c++_static when running tests

- layers/sync/sync_validation.cpp
- tests/unit/sync_val_positive.cpp
This can happen when core checks are disabled or when corresponding checks not implemented.
There are core validation checks for set-not-bound error for `vkCmdBindDescriptorSets` API.
That functionality is not implemented yet for `vkCmdBindDescriptorBuffers` + `vkCmdSetDescriptorBufferOffsets` API.
That is why, even with core checks enabled, we still need to do preventing checks in SyncVal.
Addresses https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/6112
> layers: Check out of bounds access in syncval

- layers/thread_tracker/thread_safety_validation.h
`get_hardware_destructive_interference_size()` value is specific to build machine and at least in theory no guarantee it's the same as on the user machine.
For threading/sync code it's good to be as specific and unambiguous as possible to simplify the reasoning and validation of the code.
There could be two options here.
1. Use maximum cache line size that we have on the market. Currently it's 128 bytes.
2. Use the most common cache line size of 64 bytes.
The choice here is the 2nd option, it decreases cache pressure which is helpful for Apple devices too.
In case of potential false sharing on devices with 128 cache line size we can use conditional compilation and specify 128 alignment there, but until evidence, prefer a unified solution. Also for regular workloads we don't expect a lot …
> layers: Use constant for ObjectUseData alignment

- layers/best_practices/bp_pipeline.cpp
- layers/core_checks/cc_cmd_buffer_dynamic.cpp
- layers/core_checks/cc_pipeline_graphics.cpp
- layers/core_checks/cc_shader_interface.cpp
- layers/core_checks/cc_spirv.cpp
- layers/gpu_validation/gpu_utils.cpp
- layers/gpu_validation/gpu_utils.h
- layers/state_tracker/pipeline_state.cpp
- layers/state_tracker/pipeline_state.h
- layers/state_tracker/pipeline_sub_state.cpp
- layers/state_tracker/pipeline_sub_state.h
- layers/state_tracker/shader_module.cpp
- layers/state_tracker/shader_module.h
- layers/state_tracker/state_tracker.cpp
- layers/state_tracker/state_tracker.h
Follow up for https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/6187 (cc @ziga-lunarg)
This breaks up the logic between a `SPIRV_MODULE_STATE` (which parses and holds the SPIR-V) and a `SHADER_MODULE_STATE` (and future `SHADER_OBJECT_STATE`) struct which is a thin wrapper around the SPIR-V
There is a lot of "fun" quirks around `SHADER_MODULE_STATE` and `VK_EXT_shader_module_identifier` / `VK_EXT_graphics_pipeline_library`, but luckily these extensions don't interact with `VK_EXT_shader_object`
This PR just separates the StateTracking objects, a follow up PR will adjust the GPU-AV to properly use `SPIRV_MODULE_STATE`
> layers: Separate SHADER_MODULE_STATE and SPIRV_MODULE_STATE

- layers/vulkan/generated/chassis.cpp
- layers/vulkan/generated/chassis.h
- scripts/generators/layer_chassis_generator.py
If control flow takes path that does not call `EndBlockingOperation` then `record_guard` stays initialized which triggers assert.
Reset record guard in destructor to ensure clean up always happens.
External semaphores do not call `{Begin/End}BlockingOperation`, and it triggered assert in CTS tests.
> layers: Fix record_guard misses clean up

- layers/core_checks/cc_shader_interface.cpp
- tests/unit/vertex_input.cpp
- tests/unit/vertex_input_positive.cpp
Discussed in https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/6008
This is illegal
> format = `R64`    | shader = `(location = 0) in f64vec2`
but this is actually legal
> format = `R64G64` | shader = `(location = 0) in float64_t`
So fixed the logic and moved test to positive
(new VUID will come in a spec update soon)
> layers: Fix 64-bit vertex input logic

- layers/core_checks/cc_descriptor.cpp
- layers/error_message/validation_error_enums.h
- layers/object_tracker/object_tracker_utils.cpp
- tests/unit/descriptors.cpp
- tests/unit/descriptors_positive.cpp
We had no tests for `kVUID_Core_DrawState_InvalidDescriptorSet` and I found we could not hit it as `VUID-VkWriteDescriptorSet-dstSet-00320` provides coverage for it already
> layers: Remove unused UNASSIGNED descriptor VU

- layers/core_checks/cc_query.cpp
- layers/core_checks/core_validation.h
- layers/error_message/validation_error_enums.h
- tests/unit/query.cpp
As a first step for https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/6107
This labels the VUIDs for the 2 UNASSIGNED VUs for queries
Also adds `VUID-vkCmdResetQueryPool-None-02841` and `VUID-vkCmdCopyQueryPoolResults-None-07429`
> Add Not Active query check and label unassigned Query VUIDs

- layers/core_checks/cc_copy_blit_resolve.cpp
- layers/core_checks/cc_descriptor.cpp
- layers/core_checks/cc_drawdispatch.cpp
- layers/sync/sync_vuid_maps.cpp
- scripts/vk_validation_stats.py
- tests/unit/command.cpp
- tests/unit/descriptors.cpp
- tests/unit/dynamic_state.cpp
- tests/unit/others.cpp
- tests/unit/sync_object.cpp
Over the last few headers, there were some VUID that got changed around with the validusage.json change https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/6008
This is just cleaning them up (there are few extra, but will be their own commit as they are more invasive of changes)
> layers: Fix VUID churn

- layers/core_checks/cc_descriptor.cpp
- layers/core_checks/core_validation.h
- tests/unit/descriptor_buffer.cpp
These `VK_EXT_descriptor_buffer` VUs were changed in https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/5929
`VUID-VkDescriptorAddressInfoEXT-range-08046` was split up into
- VUID-VkDescriptorAddressInfoEXT-nullDescriptor-08938
- VUID-VkDescriptorAddressInfoEXT-nullDescriptor-08939
-  VUID-VkDescriptorAddressInfoEXT-range-08940
- 
While at it, broke up the massive `NegativeDescriptorBuffer.DescriptorGetInfo` test we had into more manageable tests that can be debugged easier
> Fix VkDescriptorAddressInfoEXT VUs

- scripts/common_ci.py
The loader recently updated how the dynamic library unloading behavior is enabled, from a build option to an environment variable set at startup. this commit updates common_ci.py to respect that change.
> ci: Update Vulkan-Loader library unloading option

- layers/core_checks/cc_synchronization.cpp
- layers/sync/sync_vuid_maps.cpp
- layers/sync/sync_vuid_maps.h
- tests/unit/ray_tracing_positive.cpp
Closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/6195
It's similar to other GetVUID helpers to handle situation when VUID is not defined.
Can happen when VU is defined only for Sync2 but we still do the checks for Sync1.
This assumes that rules for compatible subset of Sync2 enums make sense for Sync1 too.
> Fix nullptr crash

- layers/stateless/sl_shader_object.cpp
- tests/unit/shader_object.cpp
Related Spec change https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/6031
@ziga-lunarg seems that `VUID-VkShaderCreateInfoEXT-flags-08413` was recently changed to `VUID-VkShaderCreateInfoEXT-flags-08992` with the logic as well
> layers: Fix VUID churn for VK_EXT_shader_object

- tests/framework/render.cpp
- tests/framework/render.h
Talking with @arno-lunarg , we should clean up the `VkRenderFramework` as things like creating a `InitRenderTarget` depends on so many random member variables.
this is a simple first PR to remove the unused variables we are not even using
> tests: Remove unused VkRenderFramework fields

- tests/framework/render.cpp
- tests/framework/render.h
- tests/unit/atomics.cpp
- tests/unit/atomics_positive.cpp
- tests/unit/dynamic_rendering.cpp
- tests/unit/dynamic_rendering_positive.cpp
- tests/unit/pipeline.cpp
- tests/unit/pipeline_positive.cpp
- tests/unit/pipeline_topology_positive.cpp
- tests/unit/shader_compute.cpp
- tests/unit/shader_compute_positive.cpp
- tests/unit/shader_interface_positive.cpp
- tests/unit/shader_limits.cpp
- tests/unit/shader_spirv.cpp
- tests/unit/transform_feedback.cpp
The parameters of `VkShaderObj` optional arguments are listed in order of most likely to be changed manually by a test
I wanted to move this over to `CreateFromGLSL`/`CreateFromASM` as it will make future changes easier to migrate tests over to them (that are using `VkShaderObj`) when we start testing things at shader creation time (instead of pipeline creation time)
> tests: Unify Shader creation parameters

- layers/core_checks/cc_spirv.cpp
- layers/core_checks/core_validation.h
Due to CI issues with SPIRV-Tools and old NDK versions (https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/6231#issuecomment-1659869849)  decided to just remove the code from building as we are still waiting for glslang support to land anyway (https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/6176)
> layers: Turn off VK_KHR_cooperative_matrix

- layers/core_checks/cc_spirv.cpp
VK_EXT_shader_tile_image validation should be skip if stage is not fragment OR if the extension is not enabled
> layers: Fix skip in shader tile image validation

- tests/framework/binding.h
- tests/unit/buffer.cpp
- tests/unit/command.cpp
- tests/unit/command_positive.cpp
- tests/unit/descriptor_buffer.cpp
- tests/unit/descriptor_buffer_positive.cpp
- tests/unit/descriptor_indexing.cpp
- tests/unit/dynamic_rendering.cpp
- tests/unit/gpu_av.cpp
- tests/unit/gpu_av_positive.cpp
- tests/unit/image.cpp
- tests/unit/ray_tracing.cpp
- tests/unit/sync_object_positive.cpp
- tests/unit/sync_val.cpp
- tests/unit/ycbcr_positive.cpp
Currently we have so many random ways to create a `VkBufferObj` that it becomes hard to follow which path does what
This also leads to a lot of times we need to do things like
```
VkMemoryPropertyFlags reqs = 0
VkBufferObj buffer_one(*m_device, 2048, reqs);
```
Because `VkBufferObj buffer_one(*m_device, 2048, 0);` is ambiguous with the various overloads
This just a small change to get things in cleaner direction
> tests: Remove some VkBufferObj overloads

- layers/core_checks/cc_cmd_buffer.cpp
- layers/core_checks/cc_query.cpp
- layers/core_checks/core_validation.h
- layers/state_tracker/query_state.h
- layers/state_tracker/state_tracker.cpp
- layers/state_tracker/state_tracker.h
- tests/unit/query.cpp
- tests/unit/query_positive.cpp
Part of https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/5430
This adds ` VUID-vkCmdExecuteCommands-commandBuffer-00103`
While here, I cleaned up things to use const ref for the command buffers
> Add VkCommandBufferInheritanceInfo::queryFlags check

- docs/shader_validation.md
- layers/core_checks/cc_spirv.cpp
- layers/core_checks/core_validation.h
- layers/gpu_validation/debug_printf.cpp
- layers/gpu_validation/debug_printf.h
- layers/gpu_validation/gpu_validation.cpp
- layers/gpu_validation/gpu_validation.h
- layers/state_tracker/pipeline_state.cpp
- layers/state_tracker/pipeline_sub_state.cpp
- layers/state_tracker/shader_module.h
- layers/state_tracker/state_tracker.cpp
- layers/state_tracker/state_tracker.h
- layers/vulkan/generated/chassis.cpp
- layers/vulkan/generated/chassis.h
- layers/vulkan/generated/chassis_dispatch_helper.h
- scripts/generators/layer_chassis_generator.py
This reworks the chassis for `vkCreateShaderModule` and `vkCreateShadersEXT` so it can after
1. Validate the SPIR-V without needing pipeline state (to solve issues like https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/2835)
2. Easier to add support for `VK_EXT_shader_object` in both Validation and GPU-AV (making separate PR as needs many tests added)
Overview of flow
> layers: Move SPIRV_MODULE_STATE creation to PreRecord

- layers/core_checks/cc_query.cpp
- tests/unit/query.cpp
This PR is the validation and test fixes for https://github.com/KhronosGroup/Vulkan-Docs/issues/2185.
I've also added some tests for VUID 03233 which didn't have any tests before.
@spencer-lunarg, I guess you'd like to take a look at it.
@llandwerlin-intel, I think you might want to look at this, considering you have an implementation of `VK_KHR_performance_query`.
> layers: Fix and test VUID 03230 and 03233

- layers/state_tracker/pipeline_state.cpp
- layers/state_tracker/pipeline_sub_state.cpp
- layers/state_tracker/shader_module.h
- layers/state_tracker/state_tracker.cpp
- layers/state_tracker/state_tracker.h
Replace the unique_ptr  with shared_ptr as the api state data is being shared across VO.
Need to revisit what we're doing re: shared and modified api_state...
@spencer-lunarg -- MNC to unbreak the multi-state-tracker config... needs more testing.
> layers: Minimal fix for doubly moved unique_ptr

- layers/vulkan/generated/object_tracker.cpp
- scripts/generators/generator_utils.py
- scripts/generators/object_tracker_generator.py
- tests/unit/multi_device.cpp
Cleanup how we generate the implicit VUs for `-parent` and `-commonparent`
notes:
- `parent` = There is a `VkDevice` (`VkInstance` is a todo) and another Handle in the same call
- `commonparent` = there are 2 Handles, that aren't `VkDevice`
> scripts: Fixes for parent and commonparent VUIDs

- layers/vulkan/generated/spirv_validation_helper.cpp
- scripts/generators/spirv_validation_generator.py
Before error message
> [ VUID-VkShaderModuleCreateInfo-pCode-08740 ]
vkCreateShaderModule(): The SPIR-V Capability (DrawParameters) was declared, but none of the requirements were met to use it.
> [ VUID-VkShaderModuleCreateInfo-pCode-08742 ]
vkCreateShaderModule(): The SPIR-V Extension (SPV_KHR_shader_draw_parameters) was declared, but none of the requirements were met to use it.
now
> [ VUID-VkShaderModuleCreateInfo-pCode-08740 ]
vkCreateShaderModule(): The SPIR-V Capability (DrawParameters) was declared, but the one of the following requirements is required (VkPhysicalDeviceVulkan11Features::shaderDrawParameters OR VK_KHR_shader_draw_parameters).
> [ VUID-VkShaderModuleCreateInfo-pCode-08742 ]
vkCreateShaderModule(): The SPIR-V Extension (SPV_KHR_shader_draw_parameters) was declared, …
> layers: Improve SPIR-V Capabilty/Extension error message

- layers/core_checks/cc_shader_interface.cpp
- tests/unit/vertex_input.cpp
adds VUID label for `VUID-VkGraphicsPipelineCreateInfo-pVertexInputState-09198` which came out in 1.3.261
logic was fixed in https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/6206 (incase someone git-blame in future)
> layers: Label new 09198 VUID

- tests/unit/ray_tracing_pipeline.cpp
- tests/unit/viewport_inheritance.cpp
There is an open issue against these tests/validation (#6082). This PR just disables them so they stop tripping up people running on the mock icd or recent Nvidia drivers.
> tests: Disable broken tests until they are fixed

- layers/core_checks/cc_cmd_buffer.cpp
- tests/unit/dynamic_rendering_positive.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/6271
Removes `VK_RENDERING_CONTENTS_SECONDARY_COMMAND_BUFFERS_BIT_KHR` from both flags being checked
also adds regression test and improves error message
> layers: Fix VkRenderingFlags matching logic

- layers/core_checks/cc_synchronization.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/6274
If you are looking at the current extension-less spec there is a `VUID-vkCmdPipelineBarrier2-None-06191` that says
> If vkCmdPipelineBarrier2 is called within a render pass instance, the render pass must not have been started with vkCmdBeginRendering
so not enabling the feature bits in `VK_EXT_shader_tile_image` still should produce the `VUID-vkCmdPipelineBarrier2-shaderTileImageColorReadAccess-08718` error
----
The error use to say
> vkCmdPipelineBarrier2 can not be used if none of the features of tile image read is enabled.
but now says
> vkCmdPipelineBarrier2 can not be called inside a dynamic rendering instance. This can be fixed by enabling the VK_EXT_shader_tile_image features.
to help explain what is going …
> layers: Improve VK_EXT_shader_tile_image feature VU message

- layers/state_tracker/shader_module.cpp
- layers/state_tracker/shader_module.h
- tests/framework/layer_validation_tests.h
- tests/unit/descriptor_indexing_positive.cpp
- tests/unit/pipeline.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/5465
Finally looking into this, I feel confident that we handle all cases of descriptor indexing correctly now in Shader Validation. I added some tests to confirm this
> tests: Confirm ShaderVal handles descriptorIndexing

- layers/error_message/logging.cpp
- layers/error_message/logging.h
- layers/vulkan/generated/chassis.cpp
- scripts/generators/layer_chassis_generator.py
Currently our error messages look like
> Validation Error: [ VUID-VkImageCreateInfo-mipLevels-00947 ] Object 0: handle = 0x561abf1affe0, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x4ca5e939 | vkCreateImage: parameter pCreateInfo->mipLevels is zero
but when using 1 `VkDevice` its quite obvious which device it is and this `VK_OBJECT_TYPE_DEVICE` serves no purpose and just adds noise
with this change it now just looks like
> Validation Error: [ VUID-VkImageCreateInfo-mipLevels-00947 ] | MessageID = 0x4ca5e939 | vkCreateImage: parameter pCreateInfo->mipLevels is zero
and when dealing with multi-device VUs it still works as normal
> Validation Error: [ VUID-vkCmdBindPipeline-commonparent ] Object 0: handle = 0x5567d5eae030, type = VK_OBJECT_TYPE_INSTANCE; Object 1: handle = 0x5567d6c32c70, …
> layers: Only print VK_OBJECT_TYPE_DEVICE if multi-device

- layers/core_checks/cc_buffer.cpp
- layers/core_checks/cc_cmd_buffer.cpp
- layers/core_checks/cc_descriptor.cpp
- layers/core_checks/cc_device_memory.cpp
- layers/core_checks/cc_image.cpp
- layers/core_checks/cc_ray_tracing.cpp
- layers/core_checks/cc_video.cpp
- layers/core_checks/core_validation.h
- layers/state_tracker/buffer_state.cpp
- layers/state_tracker/buffer_state.h
- layers/state_tracker/state_tracker.cpp
- tests/unit/buffer.cpp
- tests/unit/buffer_positive.cpp
- tests/unit/descriptors.cpp
- tests/unit/descriptors_positive.cpp
Part 3 of `VK_KHR_maintenance5`
Adds `VkBufferUsageFlags2CreateInfoKHR` support which is designed for now to be used at `vkCreateBuffer` and `vkCreateBufferView` time 
The spec says for `vkCreateBuffer`
> If a [VkBufferUsageFlags2CreateInfoKHR](https://registry.khronos.org/vulkan/specs/1.3-extensions/html/vkspec.html#VkBufferUsageFlags2CreateInfoKHR) structure is present in the pNext chain, [VkBufferUsageFlags2CreateInfoKHR](https://registry.khronos.org/vulkan/specs/1.3-extensions/html/vkspec.html#VkBufferUsageFlags2CreateInfoKHR)::usage from that structure is used **instead** of usage from this structure.
> Add VkBufferUsageFlags2CreateInfoKHR support (VK_KHR_maintenance5)

- BUILD.gn
All embedders use C++17 or newer now, and
language version should generally be set by the
embedder anyways.
This also happens to work around a bug in libc++
which currently doesn't work correctly in mixed
language version modes (https://crbug.com/1463881).
> build: Don't pass -std= in BUILD.gn

- layers/core_checks/cc_drawdispatch.cpp
- tests/unit/multiview.cpp
This VUID has to be checked with dynamic rendering too
And `enabled_features.core11` should be checked instead of `enabled_features.multiview_features`
> Fix VUID 02688

- layers/state_tracker/shader_module.cpp
https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/6249 seems to have caused an regression as pointed out by https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/6293
until I get a SPIR-V file (or a way to test), going to revert the `assert` for now
> layers: Revert GetConstantValueById assert assumption

- tests/unit/gpu_av.cpp
Android test framework uses glslang fully now
> android: Fix shaderc workaround done for Android

- layers/vulkan/generated/stateless_validation_helper.h
- layers/vulkan/generated/vk_enum_string_helper.h
- scripts/generators/enum_string_helper_generator.py
- scripts/generators/stateless_validation_helper_generator.py
the `vk_enum_string_helper.h` will soon [be moved to VUL](https://github.com/KhronosGroup/Vulkan-Utility-Libraries/pull/63/files#r1295272207) so moved this helper function out the the stateless validation helper generated file as this is only used by `sl_utils.cpp`
> scripts: Move IsDuplicatePnext to proper file

- layers/core_checks/cc_ray_tracing.cpp
- tests/unit/ray_tracing.cpp
- Reopen https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/6040
It seems that the disabled part is responsible for a hang when running specific CTS tests.
In this disabled code part, the only calls that go down to the driver are the ones to DispatchGetAccelerationStructureBuildSizesKHR, so something must be wrong around here.
> layers: Disable part of accel struct validation (Fix CTS)

- layers/error_message/logging.cpp
Starting with #6278, devices aren't printed if there's only one device.  The debug_report method of getting error callbacks cannot tolerate an empty object list, so use a null object to keep it working, even though it's been deprecated for years.
Fixes crashes in 
dEQP-VK.pipeline.monolithic.early_destroy.cache, 
dEQP-VK.pipeline.monolithic.extended_dynamic_state.between_pipelines.enable_raster
and other CTS tests.
Will target to add to the SDK branch once approved.
Error message with this fix:
Test case 'dEQP-VK.pipeline.monolithic.early_destroy.cache'..
Validation Error: [ VUID-VkGraphicsPipelineCreateInfo-pStages-06894 ] | MessageID = 0xdfcd6d41 | vkCreateGraphicsPipelines(): pCreateInfo[0] does not have fragment shader state, but stages …
> Fix debug_report with no objects

- layers/core_checks/cc_render_pass.cpp
The error checks for the height of the render area, but mentioned `pRenderingInfo->renderArea.extent.width` instead.
> layers: fix typo in 06080 error description

- .github/workflows/vvl.yml
cmake is now redundant now that ndk-build is gone.
ctest will return exit code 0 even if there are 0 tests.
> ci: Cleanup Android CI name

- tests/integration/CMakeLists.txt
Now that the layer factor is removed from LunarG/VulkanTools there is 1 less dependency on the validation layers.
> tests: Remove xxhash.cpp dependency

- layers/stateless/sl_instance_device.cpp
- layers/utils/vk_layer_utils.h
- layers/vulkan/generated/vk_extension_helper.h
- scripts/generators/extension_helper_generator.py
- tests/framework/layer_validation_tests.cpp
- tests/unit/descriptor_buffer_positive.cpp
- tests/unit/descriptor_indexing_positive.cpp
- tests/unit/dynamic_rendering_positive.cpp
- tests/unit/graphics_library_positive.cpp
- tests/unit/shader_object_positive.cpp
- tests/unit/transform_feedback.cpp
- tests/unit/ycbcr_positive.cpp
On some platforms the STL libraries include some platform headers which define C macros with names "major" and "minor" and thus cause compilation issues.
This change renames the methods of the APIVersion class to avoid these conflicts.
> scripts: Use uppercase names for APIVersion methods

- layers/core_checks/cc_copy_blit_resolve.cpp
- layers/state_tracker/device_memory_state.h
- tests/framework/binding.cpp
- tests/framework/binding.h
- tests/unit/sparse.cpp
- tests/unit/sparse_positive.cpp
- Closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/6144
Fixed validation. Validation message has been improved with the overlapping buffer ranges. Given validation is done at `vkQueueSubmit` time, finding which `vkCmdCopyBuffer` triggered validation errors is still a problem, but it goes beyond the scope of this PR.
> layers: Fix 00117 (buffer copy) for sparse resources

- layers/core_checks/cc_image.cpp
- layers/core_checks/core_validation.h
- tests/unit/image.cpp
All the VUIDs are old as they have been changed to the KHR version
Added test to make sure this works with `VK_KHR_maintenance5` as expected
> Add vkGetImageSubresourceLayout2KHR

- tests/unit/shader_cooperative_matrix_positive.cpp
Fixes test run on AMD when props_count comes back 0.
> Fix support check in CooperativeMatrixKHR

- docs/debug_printf.md
The documentation for debug printf includes a couple example shaders and a short example command for how to compile them. These commands include the `-x` flag which exports the code in text-based hexadecimal format, rather than the binary SPIR-V representation, which might be confusing for someone looking to learn from the document.
> docs: Correct SPIR-V compilation instructions

- layers/gpu_validation/gpu_validation.cpp
- layers/gpu_validation/gpu_validation.h
Fixes a crash in dEQP-VK.api.fill_and_update_buffer.suballocation_transfer_queue.fill_buffer_whole
> Add check for queue that supports graphics to ray tracing GPU-AV

- layers/core_checks/cc_synchronization.cpp
- layers/core_checks/core_validation.h
- layers/state_tracker/queue_state.cpp
- layers/state_tracker/queue_state.h
- layers/state_tracker/state_tracker.cpp
- layers/state_tracker/state_tracker.h
`TimePoint` objects are regularly created and destroyed.  When such
object registers semaphore wait operation it allocates memory.
This PR avoids allocation when semaphore has a single waiter.
*First commit:*
Reduces size of `TimePoint` structure on 64 bit platforms.
The numbers is for the Release build, Debug build can add additional
debug state.
SemOp    : 40  -> 32 bytes
TimePoint: 104 -> 96 bytes
That's preparation for the second commit which increases size of
`TimePoint` in order to use build-in storage of `small_vector` to avoid
allocation for the case when semaphore has a single waiter.
We try to reduce size enough, in order not to go over 2 cache lines
(128 bytes) when `std::set` is replaced with `small_vector`. If for some
compiler settings or std library implementation we start …
> layers: Avoid allocation for single semaphore wait

- scripts/vk_validation_stats.py
The change in https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/6084 will improve the strings such as
```patch
-    {"VUID-BaryCoordKHR-BaryCoordKHR-04154", "The BaryCoordKHR decoration must be used only within the Fragment {ExecutionModel}", "1.3-extensions"},
+    {"VUID-BaryCoordKHR-BaryCoordKHR-04154", "The BaryCoordKHR decoration must be used only within the Fragment Execution Model", "1.3-extensions"},
-    {"VUID-VkImageSubresourceRange-aspectMask-02278", "aspectMask must not include VK_IMAGE_ASPECT_MEMORY_PLANE{ibit}BIT_EXT for any index i", "1.3-extensions"},
+    {"VUID-VkImageSubresourceRange-aspectMask-02278", "aspectMask must not include VK_IMAGE_ASPECT_MEMORY_PLANE_i_BIT_EXT for any index i", "1.3-extensions"},
```
there are some new Unicode that we need to catch
> scripts: Add upcoming unicode to ascii in VUID

- layers/core_checks/cc_cmd_buffer_dynamic.cpp
- layers/core_checks/cc_descriptor.cpp
- layers/core_checks/cc_pipeline.cpp
- layers/core_checks/cc_pipeline_compute.cpp
- layers/core_checks/cc_pipeline_graphics.cpp
- layers/core_checks/cc_pipeline_ray_tracing.cpp
- layers/core_checks/cc_shader_interface.cpp
- layers/core_checks/cc_shader_object.cpp
- layers/core_checks/cc_spirv.cpp
- layers/core_checks/core_validation.h
- layers/state_tracker/pipeline_state.h
- layers/vulkan/generated/spirv_validation_helper.cpp
- scripts/generators/spirv_validation_generator.py
- tests/unit/pipeline_layout.cpp
- tests/unit/shader_object.cpp
This is just updating a LOT of `LogError` to use the new `Location` flow (not 100% coverage, some errors need more attention)
for Pipeline - we use to have the `create_index` and various other things carried around the pipeline state, this provides much better error messages, mainly focused knowing where in the massive `VkGraphicsPipelineCreateInfo` an error is
For shaders - before were almost never saying much about when the called occured, with the new `VK_EXT_shader_object` this is more important. This tries to replace the word `shader` for `SPIR-V` where it makes the most sense to prevent confusion about the new `VkShadersEXT` object
> layers: Add Location for Pipeline and Shaders

- layers/best_practices/best_practices_utils.cpp
- layers/best_practices/best_practices_validation.h
- layers/best_practices/bp_copy_blit_resolve.cpp
- layers/best_practices/bp_device_memory.cpp
- layers/best_practices/bp_drawdispatch.cpp
- layers/best_practices/bp_instance_device.cpp
- layers/best_practices/bp_render_pass.cpp
- layers/best_practices/bp_wsi.cpp
- layers/vulkan/generated/best_practices.cpp
- scripts/generators/best_practices_generator.py
the Best Practices had a lot of `const char*` for passing in function names
Replaced with `Location` (for `PreCallValidate`) and `vvl::Func` everywhere else
Still a todo to have the `LogWarning` make use of the `Loc`, but at least whoever gets to cleaning up Best Practice first in the future doesn't have to worry about the many strings we had passed around
> bp: Use Location and Func instead of const char

- layers/core_checks/cc_buffer.cpp
- layers/core_checks/cc_descriptor.cpp
- layers/core_checks/cc_device.cpp
- layers/core_checks/cc_device_memory.cpp
- layers/core_checks/cc_external_object.cpp
- layers/core_checks/cc_image.cpp
- layers/core_checks/cc_pipeline.cpp
- layers/core_checks/cc_query.cpp
- layers/core_checks/cc_ray_tracing.cpp
- layers/core_checks/cc_render_pass.cpp
- layers/core_checks/cc_synchronization.cpp
- layers/core_checks/cc_video.cpp
- layers/core_checks/core_validation.h
- layers/object_tracker/object_lifetime_validation.h
- layers/object_tracker/object_tracker_utils.cpp
- layers/vulkan/generated/object_tracker.cpp
- scripts/generators/object_tracker_generator.py
- tests/unit/sparse.cpp
This change is just replacing the old `const char*` with `Location` for the `ObjectTracker` helpers (While adding some `Location` to errors that didn't print where it came from
My next goal would be to provide a nested location where possible
> layers: Add Location for ObjectTracker (part 1)

- layers/core_checks/cc_pipeline.cpp
- tests/unit/device_queue.cpp
- tests/unit/dynamic_state.cpp
adds more tests for https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/5842
VUID-vkCmdSetDepthBias-depthBiasClamp-00790
VUID-vkCreateCommandPool-queueFamilyIndex-01937
VUID-vkCmdBindPipeline-pipelineBindPoint-00777
VUID-vkCmdBindPipeline-pipelineBindPoint-00778
> tests: Add more missing negative tests

- layers/core_checks/cc_cmd_buffer.cpp
- tests/unit/buffer.cpp
- tests/unit/buffer_positive.cpp
as clarified here https://gitlab.khronos.org/vulkan/vulkan/-/issues/3588
> VUID-vkCmdBindIndexBuffer-offset-08782
>
> offset must be less than the size of buffer
the `size` here is the `VkBufferCreateInfo` size, not the requirements, this is the only case we were doing it wrong
> layers: Fix buffer size not using createInfo size

- layers/core_checks/cc_synchronization.cpp
- tests/framework/layer_validation_tests.h
- tests/unit/sync_object.cpp
for `VUID-VkImageMemoryBarrier2-image-03320` 
before
> vkCmdPipelineBarrier2(): .pImageMemoryBarriers[0].image references VkImage 0x967dd1000000000e[] of format VK_FORMAT_D16_UNORM_S8_UINT that must have the depth and stencil aspects set, but its aspectMask is 0x4.
now
> vkCmdPipelineBarrier2(): pDependencyInfo.pImageMemoryBarriers[0].image (VkImage 0x967dd1000000000e[]) has depth/stencil format VK_FORMAT_D16_UNORM_S8_UINT, but its aspectMask is VK_IMAGE_ASPECT_STENCIL_BIT.
> Improve ValidateBarriersToImages messages

- layers/best_practices/best_practices_error_enums.h
- layers/best_practices/bp_cmd_buffer.cpp
- layers/core_checks/cc_cmd_buffer.cpp
- layers/core_checks/cc_queue.cpp
- layers/core_checks/core_validation.h
- layers/error_message/validation_error_enums.h
- tests/unit/best_practices.cpp
- tests/unit/command.cpp
- `UNASSIGNED-CoreValidation-DrawState-InvalidCommandBufferSimultaneousUse` was moved to Best Practices
- `UNASSIGNED-CoreValidation-DrawState-NoEndCommandBuffer` is just `VUID-vkCmdExecuteCommands-pCommandBuffers-00089` and `VUID-vkQueueSubmit-pCommandBuffers-00070`
> Remove CommandBuffer UNASSIGNED

- tests/unit/sync_val.cpp
- tests/unit/sync_val_positive.cpp
Negative tests check for PRESENT-AFTER-WRITE hazard when present does not wait on submit.
Positive tests check that presentation engine accesses do not generate any hazards (especially with regard to how swapchain image writes are made visible to the presentation engine).
> tests: Add vkQueuePresentKHR syncval submit time tests

- layers/core_checks/cc_copy_blit_resolve.cpp
- tests/unit/command.cpp
- tests/unit/host_image_copy.cpp
VUID cleanup from https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/6032 (cc @mikes-lunarg)
> layers: VUID fixes for VK_KHR_maintenance5 in 1.3.262

- layers/best_practices/best_practices_error_enums.h
- layers/best_practices/bp_wsi.cpp
- tests/unit/best_practices.cpp
This is needed by VK_EXT_swapchain_maintenance1 if using per-present-mode capabilities as documented [here](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkSurfacePresentModeEXT.html).
> layers: Warn if no present modes provided to create swapchain

- layers/vulkan/generated/object_tracker.cpp
- scripts/generators/object_tracker_generator.py
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/5210
Provides much better error messages for ObjectTracker errors
> layers: Add full Location to ObjectTracker

- layers/core_checks/cc_wsi.cpp
- tests/unit/wsi_positive.cpp
Follow up to https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/6351
Fix a case where part of the pnext chain passed down to `GetSurfaceCapabilities` could be lost.
Add a new positive test that takes the problematic path.
> layers: Fix pnext chain handling for GetSurfaceCapabilities in swapchain creation validation

- layers/stateless/sl_buffer.cpp
- layers/stateless/sl_device_memory.cpp
- layers/stateless/sl_external_object.cpp
- layers/stateless/sl_image.cpp
- layers/stateless/sl_synchronization.cpp
- layers/stateless/stateless_validation.h
using `Location` for all the error messages in `sl_external_object.cpp`
> layers: Use Location for stateless external objects

- layers/CMakeLists.txt
- tests/integration/CMakeLists.txt
- tests/integration/main.cpp
The utility libraries are ramping up and soon LunarG/VulkanTools will no longer depend on the validation layers.
Update the integration/installation code to reflect progress made in LunarG/VulkanTools.
We no longer need to install source files.
> cmake: Impending BUILD_LAYER_SUPPORT_FILES deprecation

- layers/best_practices/best_practices_validation.h
- layers/state_tracker/buffer_state.cpp
- layers/state_tracker/buffer_state.h
- layers/state_tracker/device_memory_state.cpp
- layers/state_tracker/device_memory_state.h
- layers/state_tracker/image_state.cpp
- layers/state_tracker/image_state.h
- layers/state_tracker/ray_tracing_state.h
- layers/state_tracker/sampler_state.h
- layers/state_tracker/state_tracker.cpp
- layers/state_tracker/state_tracker.h
- layers/sync/sync_validation.cpp
Make BindableMemoryTracker be a member of each state object instead of the 'leaf' of the inheritance hierarchy.
All of the trackers are now less than 64 bytes in size so they can be stored directly in a variant without excessive overhead.
I'm about to add subclasses of BUFFER_STATE and I don't want to go through the whole ValidationStateTracker::CreateImageStateImpl() mess again.
> layers: Simplify BINDABLE class hierarchy

- layers/core_checks/cc_descriptor.cpp
- layers/core_checks/cc_drawdispatch.cpp
- layers/core_checks/core_validation.h
FormatHandle() creates a string which adds malloc() overhead in per-draw call code paths. Don't do this unless an error is detected.
This fixes a perf regression from https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/6291
> corechecks: Fix perf regression from shader object validation

- layers/core_checks/cc_pipeline_graphics.cpp
- tests/unit/shader_object.cpp
https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/6104 will soon remove this VU and move it to draw time. This is already being tracked in https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/5208 as there were known issues
Will come back to this when the new VU lands and make sure all 3 tests (2 are already disabled) work with it
> layers: Remove incorrect Dual Source blending VU

- layers/core_checks/cc_descriptor.cpp
- layers/core_checks/cc_image.cpp
- layers/core_checks/core_validation.h
- tests/unit/descriptor_indexing.cpp
- tests/unit/descriptors.cpp
The Update Descriptor logic is quite old and is nothing like any other part of the code base, it used this `std::string *error_code, std::string *error_msg` system which was awful.
This change doesn't change any of the logic (except a few places it was wrong actually) and mainly just redid all the `LogError` to use the new `Location` 
The new error message provide better Object handle and info then before, **but** I do plan to come back through as there is a LOT that could still be cleaned up about this code
> layers: Use Location for Update Descriptor checks

- layers/best_practices/best_practices_validation.h
- layers/state_tracker/buffer_state.cpp
- layers/state_tracker/buffer_state.h
- layers/state_tracker/device_memory_state.cpp
- layers/state_tracker/device_memory_state.h
- layers/state_tracker/image_state.cpp
- layers/state_tracker/image_state.h
- layers/state_tracker/ray_tracing_state.h
- layers/state_tracker/sampler_state.h
- layers/state_tracker/state_tracker.cpp
- layers/state_tracker/state_tracker.h
- layers/sync/sync_validation.cpp
This reverts commit 1d1317e5761d926560a9ce11815483c6d73efeaa.
It is causing crashes in some internal tests.
> layers: Revert "Simplify BINDABLE class hierarchy"

- tests/unit/descriptors_positive.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/6401
> tests: Add poolSizeCount as zero test

- layers/core_checks/cc_buffer.cpp
- layers/core_checks/cc_cmd_buffer.cpp
- layers/core_checks/cc_copy_blit_resolve.cpp
- layers/core_checks/cc_descriptor.cpp
- layers/core_checks/cc_device_memory.cpp
- layers/core_checks/cc_drawdispatch.cpp
- layers/core_checks/cc_external_object.cpp
- layers/core_checks/cc_image.cpp
- layers/core_checks/cc_image_layout.cpp
- layers/core_checks/cc_pipeline_graphics.cpp
- layers/core_checks/cc_query.cpp
- layers/core_checks/cc_ray_tracing.cpp
- layers/core_checks/cc_render_pass.cpp
- layers/core_checks/cc_synchronization.cpp
- layers/core_checks/cc_video.cpp
- layers/core_checks/core_validation.h
- layers/stateless/sl_ray_tracing.cpp
- layers/stateless/stateless_validation.h
This PR is to hopefully remove all the remaining `const char` used for function names in CoreChecks
> layers: Remove more const char

- layers/stateless/sl_buffer.cpp
- tests/unit/buffer.cpp
- tests/unit/buffer_positive.cpp
- tests/unit/transform_feedback.cpp
redo of https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/6363 (realized I didn't fix the transform feedback tests)
The 1.3.262 spec removes the implicit VUs and made `VUID-VkBufferCreateInfo-None-09205` and `VUID-VkBufferCreateInfo-None-09206`
> layers: Add explicit VkBufferCreateInfo usage flag VUs

- layers/containers/qfo_transfer.h
- layers/core_checks/cc_image_layout.cpp
- layers/core_checks/cc_synchronization.cpp
- layers/core_checks/core_validation.h
- layers/state_tracker/cmd_buffer_state.h
- layers/sync/sync_utils.cpp
- layers/sync/sync_utils.h
The problem with templated methods is that parameterized barrier types have to be the most common denominator for sync1/sync2, so they do not include stage masks. Stage masks parameters have to be added where needed or new overloads are introduced.
This PR introduces helper barrier structures and converts some existing methods to untemplated form (more to follow). I started with the methods I worked with recently and had troubles with extending them due to the fact that stage mask is not included. Code got more compact in most cases too.
New types are similar to sync2 types with a benefit of hierarchical data organization. For example, `BufferBarrier can` also be used by the apis that accept `QueueFamilyBarrier` or `MemoryBarrier` types. New barrier types can be initialized with both …
> layers: Untemplate some barrier methods

- layers/core_checks/cc_cmd_buffer_dynamic.cpp
- tests/unit/shader_object.cpp
- tests/unit/shader_object_positive.cpp
The SetColorBlendEnable check VUID-08643 should check for the relevant `pColorBlendEnables[i]` bit set, which is tracked by `cb_state->dynamic_state_value.color_blend_enabled` in [state_tracker.cpp:5830-5843](https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/bea5beb302dc1add1bb9b52c8de37c0b92687159/layers/state_tracker/state_tracker.cpp#L5830-L5843)
Instead, it checks `cb_state->dynamic_state_value.color_blend_enable_attachments` which is set unconditionally.
Thus, with a color attachment that doesn't support `VK_FORMAT_FEATURE_COLOR_ATTACHMENT_BLEND_BIT`, this validation check always fails even when `VK_FALSE` is correctly passed to `vkCmdSetColorBlendEnableEXT` for the relevant attachment.
> layers: Check correct flag for SetColorBlendEnable

- layers/error_message/error_location.cpp
- layers/error_message/error_location.h
This PR allows a Location object to point to an entire structure within the pNext chain, which is necessary in order to allow a function to accept structure locations indifferent of whether they are specified as a member of another structure or chained to another structure.
> layers: Error location improvements

- layers/thread_tracker/thread_safety_validation.h
Probably an editing error from https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/1557
Does not affect correctness, for the second `DestroyObject` call the hash table's `erase` can't find the key and returns. Also, one fewer `WriteLockGuard` lock.
> layers: Fix double destruction in thread safety

- layers/core_checks/cc_image_layout.cpp
- layers/core_checks/cc_synchronization.cpp
- layers/core_checks/core_validation.h
- tests/unit/dynamic_rendering.cpp
Similar to the previous PR, and some cleanup. 
It looks there are few patterns how this can be done. Some (non-coherent) notes about approaches.
**Big template function -> Big non-template function + small dispatch functions**:
`RecordTransitionImageLayout` is an example where the main part of the algorithm can become a regular method that works with specific type, and there is a helper/thin wrapper (`TransitionImageLayouts`) that delegates requests and maps types from what was previously parameterized to our custom types.  We already had `TransitionImageLayouts`, so this update was cheap with regard to introducing new abstractions.
**Bit template function handles few type-specific scenarios -> extract scenarios into separate functions + common code**:
That's …
> layers: Untemplate image related methods

- layers/core_checks/cc_android.cpp
- layers/core_checks/cc_device_memory.cpp
- layers/core_checks/cc_image.cpp
- layers/state_tracker/device_memory_state.h
- layers/state_tracker/image_state.cpp
- layers/state_tracker/state_tracker.cpp
Add QNX buffer extension support for allocated memory size validation.
Validation message has mention of QNX, but not in the code:
ERROR : VALIDATION - Message Id Number: 1700101245 | Message Id Name: VUID-VkMemoryDedicatedAllocateInfo-image-02964
Validation Error: [ VUID-VkMemoryDedicatedAllocateInfo-image-02964 ] | MessageID = 0x65557c7d |
vkAllocateMemory: Allocation Size (8355840) needs to be equal to VkImage VkImage 0x2cfba2000000001c[]
VkMemoryRequirements::size (8896880) The Vulkan spec states: If image is not VK_NULL_HANDLE and the
memory is not an imported Android Hardware Buffer or an imported QNX Screen buffer,
VkMemoryAllocateInfo::allocationSize must equal the VkMemoryRequirements::size of the image
(https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html …
> corechecks: Make QNX buffer import validation according to spec

- layers/core_checks/cc_spirv.cpp
- tests/unit/atomics.cpp
- tests/unit/others.cpp
- tests/unit/shader_compute.cpp
- tests/unit/shader_cooperative_matrix.cpp
- tests/unit/shader_spirv.cpp
from https://github.com/KhronosGroup/Vulkan-Docs/issues/2208
I realized these VUIDs were labeled wrong from when `VK_EXT_shader_object` split them up
> layers: Fix VUID for invalid SPIR-V

- layers/core_checks/cc_copy_blit_resolve.cpp
- tests/unit/command.cpp
- tests/unit/host_image_copy.cpp
The 1.3.263 spec removed a lot of bad VUs and this is just cleaning them up
> layers: Fix VUIDs for image copies

- layers/core_checks/cc_pipeline_graphics.cpp
- layers/core_checks/core_validation.h
The messages before never told you where to look for your dynamic state, new errors look like
>  vkCreateGraphicsPipelines(): pCreateInfos[1].pDynamicState.pDynamicStates[3] is VK_DYNAMIC_STATE_LOGIC_OP_EXT, but the extendedDynamicState2LogicOp feature was not enabled.
> layers: Improve dynamic state feature messages

- layers/core_checks/cc_render_pass.cpp
- layers/stateless/sl_framebuffer.cpp
- tests/unit/renderpass.cpp
This cleans up a lot of functions in the `cc_render_pass.cpp` that get very nested, but realize we can just be returning early (or `continue` of `for` loops) more
Most of this is just shifting things over to the left
> layers: Fix CoreCheck RenderPass to return earlier

- layers/thread_tracker/thread_safety_validation.cpp
- layers/vulkan/generated/thread_safety_commands.h
- scripts/generators/thread_safety_generator.py
This reverts commit cea4a9ed5e2bff7388b738d9adfda5ac455ae578.
For the period of investigation of https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/6447
> layers: Revert "Add thread safety checks for vkQueuePresentKHR"

- layers/core_checks/cc_cmd_buffer.cpp
- layers/core_checks/cc_copy_blit_resolve.cpp
- layers/core_checks/cc_descriptor.cpp
- layers/core_checks/cc_device_memory.cpp
- layers/core_checks/cc_image.cpp
- layers/core_checks/cc_pipeline.cpp
- layers/core_checks/cc_pipeline_graphics.cpp
- layers/core_checks/cc_query.cpp
- layers/stateless/sl_buffer.cpp
- layers/stateless/sl_cmd_buffer.cpp
- layers/stateless/sl_cmd_buffer_dynamic.cpp
- layers/stateless/sl_descriptor.cpp
- layers/stateless/sl_device_memory.cpp
- layers/stateless/sl_image.cpp
- tests/unit/graphics_library.cpp
There are some functions that could really make use of an early return at top (or some `continue`) to prevent some deep nesting we have. This commit should have no semantic changes and just ending the function/loop sooner
also plan to add this to `.git-blame-ignore-revs` after
> layers: Improve nesting by returning back sooner

- scripts/vk_validation_stats.py
Removes multiple whitespace artifacts from the `validusage.json` file
> scripts: Fix extra whitespace in VU messages

- layers/core_checks/cc_pipeline_graphics.cpp
- layers/state_tracker/pipeline_state.h
- layers/stateless/sl_pipeline.cpp
- tests/framework/pipeline_helper.cpp
- tests/framework/pipeline_helper.h
- tests/unit/command.cpp
- tests/unit/descriptors.cpp
- tests/unit/dynamic_rendering.cpp
- tests/unit/dynamic_rendering_positive.cpp
- tests/unit/dynamic_state.cpp
- tests/unit/dynamic_state_positive.cpp
- tests/unit/graphics_library.cpp
- tests/unit/graphics_library_positive.cpp
- tests/unit/multiview.cpp
- tests/unit/object_lifetime.cpp
- tests/unit/pipeline_topology_positive.cpp
- tests/unit/sampler.cpp
closes #6431 and #6184
This uses the new VU language that allows `VK_EXT_extended_dynamic_state3` plus certain dynamic states to be used in order to allow `null` for the various Pipeline state info structs
Also improved the testing in the first commit to make adding dynamic state to tests easier
> Fix pipeline state that can be ignored with dynamic state

- layers/sync/sync_validation.cpp
- layers/sync/sync_validation.h
A series of changes that improved various traces between 1% and 10% reduction in frametime (cumulatively) in local testing.  Each change is in a separate commit.  Relative performance is batched, and relative to the previous batch reported (SB == Strange Brigade  TS == TheSurge)  
This branch is built on the QueueSubmit rework branch (which had a 5%-67% reduction in frametime on one trace all by itself).  
Some expansion on each 
syncval: Cleanup of ResourceAccessState for perf 
Mostly housekeeping change 0's to applicable constants, except for using `reset` for the bitsets vs. `= 0` which was more efficient in the profiling
syncval: Convert usage index to info part 1
Changed from passing around usage information as an index to passing around a pointer to an entry to a const (static) …
> Syncval Performance Set 1

- layers/vulkan/generated/object_tracker.cpp
- scripts/generators/object_tracker_generator.py
- tests/unit/graphics_library.cpp
- tests/unit/imageless_framebuffer.cpp
I found if `VkPipelineLibraryCreateInfoKHR::pLibraries` was a bad `VkPipeline` we were crashing inside the layers
I realized we never ran ObjectTracker on any of the extended `pNext` objects
> layers: Run ObjectTracker on pNext structs

- BUILD.gn
- layers/CMakeLists.txt
- layers/core_checks/cc_image.cpp
- layers/vulkan/generated/pnext_chain_extraction.cpp
- layers/vulkan/generated/pnext_chain_extraction.h
- layers/vulkan/generated/vk_typemap_helper.h
- scripts/generate_source.py
- scripts/generators/pnext_chain_extraction_generator.py
- scripts/generators/typemap_helper_generator.py
- tests/CMakeLists.txt
- tests/unit/image_positive.cpp
- tests/vvl_utils/pnext_chain_extraction.cpp
- tests/vvl_utils/small_vector.cpp
Follow up to https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/6295
- Should close https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/6256
Add utilities to make a selective copy of a pNext chain. Selected elements are the structs extending some reference struct.
> layers: Add pnext chain extraction logic and use it when validating image creation

- layers/core_checks/cc_pipeline_graphics.cpp
- layers/stateless/sl_pipeline.cpp
- tests/unit/dynamic_rendering.cpp
- tests/unit/dynamic_rendering_positive.cpp
- tests/unit/multiview.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/6473
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/4856
as stated in https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/4856 the issue was in `safe_VkGraphicsPipelineCreateInfo::initialize` we go 
```cpp
if (in_struct->pColorBlendState && ((has_rasterization && uses_color_attachment) || is_graphics_library))
pColorBlendState = new safe_VkPipelineColorBlendStateCreateInfo(in_struct->pColorBlendState);
else
pColorBlendState = nullptr; // original pColorBlendState pointer ignored
```
so it was never checking the `pColorBlendState` , so now it was moved to Stateless where it gets the original information to check
> layers: Fix DynamicRendering AttachmentCount check

- layers/core_checks/cc_image_layout.cpp
- layers/core_checks/cc_query.cpp
- layers/core_checks/cc_queue.cpp
- layers/core_checks/cc_synchronization.cpp
- layers/core_checks/core_validation.h
- layers/error_message/error_location.h
- layers/sync/sync_vuid_maps.cpp
- tests/unit/sync_object.cpp
- Improve the `Location` name for many variables
- Use `Location` in the `LogError`
- Improve some error messages
> layers: Cleanup Location code for Sync Objects

- layers/core_checks/cc_descriptor.cpp
- layers/core_checks/cc_device.cpp
- layers/state_tracker/base_node.cpp
- layers/state_tracker/base_node.h
- layers/state_tracker/descriptor_sets.cpp
- layers/state_tracker/descriptor_sets.h
currently we have error messages like
> Validation Error: [ VUID-vkUpdateDescriptorSets-None-03047 ] Object 0: handle = 0xec4bec000000000b, type = VK_OBJECT_TYPE_DESCRIPTOR_SET; Object 1: handle = 0xcfef35000000000a, type = VK_OBJECT_TYPE_DESCRIPTOR_SET_LAYOUT; | MessageID = 0x35d7ea98 | vkUpdateDescriptorSets(): pDescriptorWrites[0].dstBinding (0) was created with VkDescriptorBindingFlags(0), but VkDescriptorSet 0xec4bec000000000b[] is in use by a command buffer.
the ` is in use by a command buffer.` is not helpful
with the change to `InUse` to return a handle pointer instead of `bool`, we have error messages like
> ..., but VkDescriptorSet 0xec4bec000000000b[] is in use by VkCommandBuffer 0x55bad2cc4c20[].
> layers: Print command buffer handle from InUse

- layers/stateless/sl_pipeline.cpp
When incorrectly setting `lineWidth` to zero in `VkPipelineRasterizationStateCreateInfo`, the following validation error was produced, referencing `polygonMode` as the issue:
> Validation Error: [ VUID-VkGraphicsPipelineCreateInfo-pDynamicStates-00749 ] | MessageID = 0x1b1ca73 | vkCreateGraphicsPipelines(): pCreateInfos[0].pRasterizationState->polygonMode is 0.000000, but the line width state is static (pCreateInfos[0].pDynamicState->pDynamicStates does not contain VK_DYNAMIC_STATE_LINE_WIDTH) and wideLines feature was not enabled. The Vulkan spec states: If the pipeline requires pre-rasterization shader state, and the wideLines feature is not enabled, and no element of the pDynamicStates member of pDynamicState is VK_DYNAMIC_STATE_LINE_WIDTH, the lineWidth member of pRasterizationState …
> Fixed incorrect member variable "polygonMode" referenced in validation error, instead of "lineWidth".

- layers/error_message/logging.cpp
While it would be nice to add the period at the end of all error messages, rather just have it be added then having to go and update ALL the error messages (and nit pick PRs)
> layers: Add period automatically at end of message

- layers/core_checks/core_validation.h
- layers/object_tracker/object_lifetime_validation.h
- layers/object_tracker/object_tracker_utils.cpp
- layers/state_tracker/state_tracker.cpp
- layers/stateless/sl_instance_device.cpp
- layers/utils/vk_layer_utils.h
- layers/vulkan/generated/chassis.cpp
- layers/vulkan/generated/chassis.h
- scripts/generators/layer_chassis_generator.py
Further simplification of `CheckObjectValidity`.
Removes the need to manualy `static_cast` returned value  when object type is known at compile time.
Before:
```
ValidationObject *validation_data = GetValidationObject(instance_data->object_dispatch, LayerObjectTypeObjectTracker);
ObjectLifetimes *object_lifetimes = static_cast<ObjectLifetimes *>(validation_data);
```
After:
```
auto object_lifetimes = instance_data->GetValidationObject<ObjectLifetimes>();
```
> layers: Add templated GetValidationObject
