layers/stateless/sl_cmd_buffer.cpp
layers/stateless/sl_external_object.cpp
layers/stateless/sl_pipeline.cpp
layers/stateless/sl_ray_tracing.cpp
layers/stateless/sl_utils.cpp
layers/stateless/sl_wsi.cpp
layers/stateless/stateless_validation.h
layers/vulkan/generated/stateless_validation_helper.cpp
scripts/generators/stateless_validation_helper_generator.py
tests/unit/others.cpp

The old message printed out the list of all valid pNext structs twice (which leads to an error message like the following below)
This PR removes the first part of the message
> Validation Error: [ VUID-VkPhysicalDeviceProperties2-pNext-pNext ] | MessageID = 0xdd73dbcf | vkGetPhysicalDeviceProperties2KHR(): pProperties->pNext chain includes a structure with unexpected VkStructureType VK_STRUCTURE_TYPE_APPLICATION_INFO; Allowed structures are [VkPhysicalDeviceAccelerationStructurePropertiesKHR, VkPhysicalDeviceBlendOperationAdvancedPropertiesEXT, VkPhysicalDeviceClusterCullingShaderPropertiesHUAWEI, VkPhysicalDeviceConservativeRasterizationPropertiesEXT, VkPhysicalDeviceCooperativeMatrixPropertiesKHR, VkPhysicalDeviceCooperativeMatrixPropertiesNV, …

layers: Remove redudant message for valid pNext

---

layers/error_message/logging.cpp
layers/error_message/logging.h
layers/object_tracker/object_lifetime_validation.h
layers/object_tracker/object_tracker_utils.cpp

This function is no-op after chassis was introduced (years ago).
The chassis retrieves `ValidationObject` using a key derived from the dispatchable handle. This guarantees that there cannot be a mismatch between `ValidationObject` and the first dispatchable parameter.
If the dispatchable handle is invalid, this will be detected early by the chassis code (likely a crash during dereferencing in `get_dispatch_key`), and if it reaches `ValidationObject` callback then we know the validation object was created/initialized based on this dispatchable handle.
`ValidateDeviceObject` was added in the period when each validation object was a separate layer. For configurations where `ObjectLifetimes` was _the first layer in the chain_, `ValidateDeviceObject` had early opportunity to scan through …

layers: Remove ValidateDeviceObject

---

layers/state_tracker/cmd_buffer_state.h
layers/state_tracker/state_tracker.cpp
tests/unit/ray_tracing.cpp
tests/unit/ray_tracing_positive.cpp

- Closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/6461
The situation described in the issue showed that it is incorrect to add buffers obtained through a call do `GetBuffersByAddress` as children to a command buffer, given that there is no 1 to 1 mapping between a buffer and a device address. It can lead to false positives when tracking resources life span.
Add a regression test, `PositiveRayTracing.AccelerationStructuresReuseScratchMemory`:
It simulates 3 frames, where in each frame a new acceleration structure is built. Building an acceleration structure requires a _scratch_ buffer. Each frames has its own buffer, but they are all bound to the same memory.
When starting the last frame, the fence from the first frame is waited upon, then resources from frame 0 are …

layers: Fix issue 6461

---

layers/utils/vk_layer_utils.h

We no longer ship this file so the extern C usage is just confusing at this point.

layers: Remove extern C usage from vk_layer_utils.h

---

layers/core_checks/cc_cmd_buffer.cpp
layers/core_checks/cc_shader_interface.cpp
layers/core_checks/cc_spirv.cpp
layers/core_checks/core_validation.h
layers/state_tracker/pipeline_sub_state.cpp
layers/state_tracker/pipeline_sub_state.h
tests/unit/multiview.cpp
tests/unit/transform_feedback.cpp

closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/4158
adds support for `VUID-vkCmdBeginTransformFeedbackEXT-None-04128` and `VUID-VkGraphicsPipelineCreateInfo-pStages-02318`

layers: Add Xfb Execution Mode for PreRaster

---

layers/error_message/error_location.cpp
tests/unit/image.cpp

currently we print
> vkCreateImage(): pCreateInfo->pNext\<VkImageFormatListCreateInfo\>.pViewFormats->pViewFormats[1]
but we really want
> vkCreateImage(): pCreateInfo->pNext\<VkImageFormatListCreateInfo\>.pViewFormats[1]
The issue is related to https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/6464#discussion_r1321556117 (cc @artem-lunarg)
playing around with the code, rather put this edge case in the `AppendFields` then have `index` be non-const or some other random function to add more confusion to a new developer trying to add the correct Location

layers: Fix Location dot with index

---

layers/core_checks/cc_cmd_buffer.cpp
layers/core_checks/cc_copy_blit_resolve.cpp
layers/core_checks/cc_image_layout.cpp
layers/core_checks/core_validation.h

We had 2 different paths for `VerifyImageLayout` and not obvious which was being checked with the extra VUs so renamed to `VerifyImageLayoutSubresource`

layers: Cleanup VerifyImageLayout code

---

.github/workflows/vvl.yml

This should fix following CMake failure we have been seeing
```
CMake Error at C:/Program Files/CMake/share/cmake-3.27/Modules/CMakeTestCXXCompiler.cmake:60 (message):
The C++ compiler
"C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Tools/MSVC/14.35.32215/bin/HostX64/x86/cl.exe"
is not able to compile a simple test program.
-- Configuring incomplete, errors occurred!
It fails with the following output:
Change Dir: 'D:/a/Vulkan-ValidationLayers/Vulkan-ValidationLayers/build-ci/vvl/CMakeFiles/CMakeScratch/TryCompile-fbwgkz'
Run Build Command(s): C:/PROGRA~1/MICROS~2/2022/ENTERP~1/Common7/IDE/COMMON~1/MICROS~1/CMake/Ninja/ninja.exe -v cmTC_03c13
[1/2] ccache C:\PROGRA~1\MICROS~2\2022\ENTERP~1\VC\Tools\MSVC\1435~1.322\bin\HostX64\x86\cl.exe  /nologo /TP   /DWIN32 /D_WINDOWS /GR …
```

ci: Fix Windows CI

---

layers/core_checks/cc_cmd_buffer_dynamic.cpp
layers/state_tracker/pipeline_state.cpp
layers/state_tracker/pipeline_state.h
tests/unit/dynamic_state.cpp
tests/unit/dynamic_state_positive.cpp

it was confirmed in https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/6132 that we need to check for `depthBoundsTestEnable`/`stencilTestEnable`, but those values can be set dynamically but we currently were checking it from the pipeline

layers: Fix not checking for dynamic depth test state

---

layers/vulkan/generated/chassis.cpp
scripts/generators/layer_chassis_generator.py

Chassis needs to use modified createInfos especially if there aren't enough descriptor sets to do GPU-AV
Fixes crash in dEQP-VK.binding_model.descriptorset_random.sets32.noarray.ubolimitlow.sbolimitlow.sampledimglow.outimgtexlow.noiub.uab.sect.noia.0

Fix GPU-AV recovery in ray tracing

---

scripts/CMakeLists.txt
scripts/update_deps.py

Add --asan option for update_deps.py, allowing to build dependencies with ASAN enabled.
Augment VVL build option VVL_ENABLE_ASAN to automatically pass --asan option to update_deps.py when this build option is used in conjonction with UPDATE_DEPS

build: Add --asan option

---

scripts/vk_validation_stats.py

This helps with tracking stats diff.
Text mode was already deterministic.

scripts: Make html/csv stats output deterministic

---

layers/object_tracker/object_tracker_utils.cpp
layers/vulkan/generated/object_tracker.cpp
layers/vulkan/generated/object_tracker.h
scripts/generators/object_tracker_generator.py
tests/unit/object_lifetime.cpp

This is similar to https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/6509 but applied more broadly.
Do not generate validation code for the function's dispatchable parameter (the first one). Validation of such parameters is always successful based on the model of how the chassis dispactches the calls to `ValidationObject`. If invalid handle is used it will cause crash/corruption on the chassis level (in `get_dispatch_key` or later). And if correct handle is passed, then due to the mapping done by `get_dispatch_key()` the handle will belong to the retrieved validation object, which guarantees positive result of the parenting test. 
Added VVL's project item with idea to improve dispatchable handle validation: https://github.com/orgs/KhronosGroup/projects/22/views/1?pane=issue&item …

layers: Do not validate dispatchable handles in object tracker

---

layers/gpu_validation/gpu_validation.cpp
layers/gpu_validation/gpu_validation.h

Only disable descriptor checking if the app actually uses descriptor buffers

Relax descriptor checking disable in GPU-AV

---

layers/core_checks/cc_pipeline_graphics.cpp

layers: Fix VUID 06179 message

---

layers/core_checks/cc_cmd_buffer.cpp
tests/unit/command.cpp

Validate VK_COMMAND_BUFFER_USAGE_RENDER_PASS_CONTINUE_BIT is supported by command pool

Validate cmd buffer begin flags

---

tests/framework/layer_validation_tests.cpp
tests/framework/layer_validation_tests.h
tests/unit/atomics.cpp
tests/unit/descriptors.cpp
tests/unit/image.cpp
tests/unit/object_lifetime.cpp
tests/unit/robustness_positive.cpp
tests/unit/sampler.cpp

Some cleanup. Removes the need to manually adjust descriptor write thresholds in `OneOffDescriptorSet` (or theoretical possibility to go over default limits, which was 10). When write count goes over the limit then due to reallocation `vkUpdateDescriptorSets` works with dangled pointers and that's not always manifest itself in an immediate crash.
The second commit could be more subjective. The semantics of `OneOffDescriptorSet` methods that accept element count was a bit confusing. In Vulkan, element count means that multiple resources are consumed, and in our helpers, array count means a single resource will be duplicated this number of times.
Updated helpers remove element count parameter which duplicated writes. Single element is a majority of cases
If we need to specify multiple …

tests: OneOffDescriptorSet update

---

layers/core_checks/cc_cmd_buffer.cpp
tests/unit/renderpass.cpp

Part of #5842
VUID-VkCommandBufferBeginInfo-flags-00055

Fix render pass continue checks and add missing test

---

tests/unit/descriptors.cpp

Part of https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/5842
VUID-VkCopyDescriptorSet-dstBinding-00347

tests: Test invalid copy descriptor dst binding

---

tests/unit/descriptors.cpp

Part of #5842
VUID-VkDescriptorSetLayoutBindingFlagsCreateInfo-descriptorBindingInlineUniformBlockUpdateAfterBind-02211

tests: Test binding flags with inline uniform block

---

tests/unit/descriptors.cpp

Part of https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/5842
VUID-VkDescriptorSetLayoutBindingFlagsCreateInfo-None-03011

tests: Test set layout binding flags

---

tests/unit/pipeline.cpp

Part of #5842 
VUID-VkGraphicsPipelineCreateInfo-pDynamicStates-00754

tests: Test invalid pipeline depth bias clamp

---

layers/core_checks/cc_device_memory.cpp
tests/unit/image_drm.cpp
tests/unit/memory.cpp
tests/unit/ycbcr_positive.cpp

closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/5632
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/6467
This will catch the most likely error case of using `VK_IMAGE_ASPECT_PLANE_0_BIT` and not  `VK_IMAGE_ASPECT_MEMORY_PLANE_0_BIT_EXT`
Plan to add proper support for `drmFormatModifierPlaneCount` but need to first confirm spec related questions around it

Validate DRM Disjoint MultiPlanar PlaneAspect

---

layers/core_checks/cc_pipeline.cpp
layers/stateless/sl_pipeline.cpp
tests/unit/pipeline.cpp

Part of #5842
VUID-VkGraphicsPipelineCreateInfo-renderPass-06046
VUID-VkGraphicsPipelineCreateInfo-renderPass-06583
VUID-VkGraphicsPipelineCreateInfo-renderPass-06584

Test invalid pipeline rendering formats

---

tests/unit/shader_object.cpp

`kFragmentMinimalGlsl` requires a descriptor, but one was not provided.

tests: Fix shader object invalid draw test

---

layers/thread_tracker/thread_safety_validation.cpp
layers/vulkan/generated/thread_safety_commands.h
scripts/generators/thread_safety_generator.py

This re-applies https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/6400 by @AlinaKalyakina that was temporary reverted by https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/6448 for investigation.
One change comparing to the original PR is that Swapchain have to use `StartWriteObject` instead of `StartWriteObjectParentInstance` in the old version (after https://github.com/KhronosGroup/Vulkan-ValidationLayers/commit/73ba61f6321391b246177d0c47e957ea8b50af9d).

layers: Add thread safety checks for vkQueuePresentKHR

---

BUILD.gn

closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/6635

build: Add gpu_inst_shader_hash.h to BUILD.gn

---

layers/core_checks/cc_buffer.cpp
layers/core_checks/cc_descriptor.cpp
layers/core_checks/cc_device_memory.cpp
layers/core_checks/cc_drawdispatch.cpp
layers/core_checks/cc_image.cpp
layers/core_checks/cc_query.cpp
layers/core_checks/cc_ray_tracing.cpp
layers/stateless/sl_cmd_buffer.cpp
layers/stateless/sl_descriptor.cpp

For any error message that uses sizes, we should use the decimal and not a hex as it a decimal everywhere else

layers: Remove PRIxLEAST64 for sizes

---

tests/unit/descriptors.cpp
tests/unit/device_queue.cpp
tests/unit/image.cpp
tests/unit/memory.cpp
tests/unit/pipeline.cpp
tests/unit/ycbcr.cpp

Part of #5842 
VUID-VkImageBlit-aspectMask-00238
VUID-VkImageMemoryRequirementsInfo2-image-02279
VUID-VkImageResolve-aspectMask-00266
VUID-VkMemoryPriorityAllocateInfoEXT-priority-02602
VUID-VkPhysicalDeviceRobustness2FeaturesEXT-robustBufferAccess2-04000
VUID-VkPipelineColorWriteCreateInfoEXT-attachmentCount-06655
VUID-VkPipelineDepthStencilStateCreateInfo-depthBoundsTestEnable-00598
VUID-VkPipelineMultisampleStateCreateInfo-alphaToOneEnable-00785
VUID-VkPipelineRasterizationStateCreateInfo-depthClampEnable-00782
VUID-VkWriteDescriptorSet-descriptorType-04150
VUID-VkWriteDescriptorSet-descriptorType-04151

Add more missing negative tests

---

layers/core_checks/cc_device_memory.cpp
layers/core_checks/cc_ray_tracing.cpp
layers/core_checks/core_validation.h

before
> vkBindImageMemory2(): pBindInfos[0] MemoryRequirements->memoryTypeBits (0x8) for this object type are not compatible with the memory type (2) of VkDeviceMemory 0xf56c9b0000000004[].
and now
> vkBindImageMemory2(): pBindInfos[0].image require memoryTypeBits (0x8) but VkDeviceMemory 0xf56c9b0000000004[] was allocated with memoryTypeIndex (2).

layers: Improve ValidateMemoryTypes error message

---

.github/workflows/vvl.yml
scripts/common_ci.py
scripts/tests.py

It can be very confusing when these scripts fail at the end of a long run. Especially for open source contributors.

ci: Run vvl scripts in seperate action

---

.github/workflows/vvl.yml
scripts/common_ci.py
scripts/macos.py
scripts/tests.py
tests/CMakeLists.txt
tests/android/mock/README.md
tests/android/mock/android/api-level.h
tests/android/mock/android/hardware_buffer.cpp
tests/android/mock/android/hardware_buffer.h
tests/android/mock/android/log.h
tests/android/mock/android/ndk-version.h
tests/android/mock/android_native_app_glue.h
tests/android/mock/sys/system_properties.h
tests/device_profiles/max_profile.json
tests/framework/layer_validation_tests.cpp
tests/unit/android_hardware_buffer.cpp

Problem: No way to test `VK_ANDROID_external_format_resolve` (or `VK_ANDROID_external_memory_android_hardware_buffer`) with out an Android device that supports it (even then it is not fun). This means no coverage is done in Github CI and development is hard
Solution: Add a "Mock AHB" so we can simulate the Android Hardware Buffer to allow the tests to run on local desktop devices
This change
- Adds a bunch headers to allow things to compile
- CI job to test `--gtest_filter=*AndroidHardwareBuffer*` tests
- CMake support for this with a `-DVVL_MOCK_ANDROID=ON` flag to toggle it on

tests: Add support to Mock AHB 

---

tests/unit/gpu_av_positive.cpp

This new test used IsPlatform() which was just removed but I didn't rebase enough times to catch it.

tests: Fix PositiveGpuAssistedLayer.GpuValidationUnInitImage

---

layers/best_practices/bp_instance_device.cpp
layers/sync/sync_validation.cpp

The LogInfo function now consistently does not cause skipping of subsequent calls into the driver.

layers: Dont Skip on LogInfo

---

tests/framework/layer_validation_tests.cpp

This change adds a 'listener' to the googletest framework so that whenever a fatal assertion is made, an exception is thrown forcing the test to stop executing at the point the assertion was made. This is important to ensure that any failed assertions in nested function calls are caught.
Without the change, assertions deep within the test framework's init code will not cause execution to halt, potentially causing hard crashes which reduce debuggability.
The googletest framework sets up exception handlers so that the exception thrown by the failed assertion doesn't escape up the callstack, causing the process to abort.

tests: Throw exception upon ASSERT_* failure

---

layers/core_checks/cc_cmd_buffer.cpp
layers/core_checks/cc_image.cpp
layers/core_checks/cc_render_pass.cpp
layers/state_tracker/device_state.h
layers/state_tracker/state_tracker.cpp

Minimal changes to allow VVL to work with an application that enables the nestedCommandBuffer feature. A follow on PR will include coverage for the new VK_EXT_nested_command_buffer VUIDs.

layers: Compatibility for VK_EXT_nested_command_buffers

---

layers/best_practices/best_practices_validation.h
layers/best_practices/bp_pipeline.cpp
layers/core_checks/cc_pipeline.cpp
layers/core_checks/cc_pipeline_compute.cpp
layers/core_checks/cc_pipeline_ray_tracing.cpp
layers/core_checks/cc_shader_interface.cpp
layers/core_checks/cc_shader_object.cpp
layers/state_tracker/pipeline_state.cpp
layers/state_tracker/pipeline_state.h
layers/state_tracker/state_tracker.cpp
layers/state_tracker/state_tracker.h

both `create_index` and `StageCreateInfo::command` were only there for error messages prior to having `Location` in all error messages so now they can be removed

layers: Remove unused Pipeline state info

---

tests/framework/binding.cpp
tests/framework/binding.h
tests/framework/ray_tracing_objects.cpp
tests/framework/ray_tracing_objects.h
tests/unit/buffer_positive.cpp
tests/unit/descriptor_buffer.cpp
tests/unit/descriptors_positive.cpp
tests/unit/nvidia_best_practices.cpp
tests/unit/ray_tracing.cpp
tests/unit/ray_tracing_positive.cpp

We shouldn't need to pass version around the test framework because the function pointers will be null if using the wrong version and tests should be in charge of enabling extensions/versions needed

tests: Remove version from RTX tests

---

tests/framework/layer_validation_tests.cpp
tests/framework/layer_validation_tests.h
tests/unit/buffer.cpp
tests/unit/descriptors.cpp
tests/unit/object_lifetime.cpp

`VkBufferTest` was only being used for a single test and seems it wasn't even doing what it was expected

tests: Remove unused VkBufferTest class

---

layers/best_practices/bp_cmd_buffer.cpp
layers/best_practices/bp_copy_blit_resolve.cpp
layers/best_practices/bp_drawdispatch.cpp
layers/best_practices/bp_instance_device.cpp
layers/best_practices/bp_render_pass.cpp
layers/best_practices/bp_synchronization.cpp

We have done this already in Core Checks, with the new `ErrorObject` and `RecordObject` we can just use the aliased functions (goal is to just generate this in future)

bp: Use promoted alias function

---

layers/core_checks/cc_copy_blit_resolve.cpp
tests/unit/command_positive.cpp

1. Add check for `VK_REMAINING_ARRAY_LAYERS` in few missing VUs
2. unify `src_subresource` for the 3 different spots that hold a reference of `VkImageSubresourceLayers`

layers: Fix and unify VK_REMAINING_ARRAY_LAYERS logic

---

layers/vulkan/generated/vk_safe_struct.h
layers/vulkan/generated/vk_safe_struct_core.cpp
layers/vulkan/generated/vk_safe_struct_ext.cpp
layers/vulkan/generated/vk_safe_struct_khr.cpp
layers/vulkan/generated/vk_safe_struct_utils.cpp
layers/vulkan/generated/vk_safe_struct_vendor.cpp
scripts/generators/safe_struct_generator.py

With more and more extensions being added, recursions with long pNext chains can run out of stack memory. 
This PR breaks the recursion going through pNext chain into a while loop.
Closes #6696

layers: Break pNext recursion into a while loop

---

tests/framework/layer_validation_tests.cpp
tests/framework/layer_validation_tests.h
tests/framework/render.cpp
tests/unit/atomics.cpp
tests/unit/command.cpp
tests/unit/dynamic_rendering.cpp
tests/unit/dynamic_rendering_positive.cpp
tests/unit/image.cpp
tests/unit/image_drm.cpp
tests/unit/image_positive.cpp
tests/unit/instance_positive.cpp
tests/unit/others.cpp
tests/unit/sampler.cpp
tests/unit/shader_storage_image.cpp
tests/unit/shader_storage_image_positive.cpp
tests/unit/sync_val.cpp
tests/unit/ycbcr.cpp
tests/unit/ycbcr_positive.cpp

Make it clear which functions are calling vkGetPhysicalDeviceFormatProperties and which vkGetPhysicalDeviceImageFormatProperties from the name
Closes #5861

tests: Rename functions checking format support

---

layers/stateless/sl_device_memory.cpp
layers/stateless/stateless_validation.h
layers/vulkan/generated/stateless_validation_helper.cpp
scripts/generators/stateless_validation_helper_generator.py
tests/unit/sparse_image.cpp

- Closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/6703
`VkSparseImageMemoryBind` must not describe a null extent

layers: Add 09388 09389 09390

---

layers/sync/sync_validation.cpp
layers/sync/sync_validation.h
tests/unit/sync_val.cpp
tests/unit/sync_val_positive.cpp

Closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/6508
`PositiveSyncVal.LayoutTransitionWithAlreadyAvailableImage` recreates scenario described in the issue. When synchronize with *available* write it should not cause WAW hazard during ILT which makes this write visible.
Other tests are added to illustrate additional scenarios but they worked before.

layers: Ensure available accesses are not hazardous during ILT

---

layers/state_tracker/shader_module.cpp
layers/state_tracker/shader_module.h
layers/sync/sync_validation.cpp
tests/unit/sync_val_positive.cpp

Addresses https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/3450
Currently, validation of memory accesses based on declared descriptors can produce false-positives. The shader can decide not to do such accesses, it can perform accesses with more narrow scope (e.g. read access, when both reads and writes are allowed) or for an array of descriptors, not all elements are accessed in the general case.
This workaround disables validation for the runtime descriptor array case (`OpCapability RuntimeDescriptorArray`).

layers: Workaround sync validation of descriptor arrays

---

layers/sync/sync_vuid_maps.cpp

We had `04080` listed for both Mesh and Task

layers: Fix label for 04080 and 07077

---

layers/core_checks/cc_cmd_buffer.cpp
layers/core_checks/cc_queue.cpp
layers/core_checks/cc_render_pass.cpp
layers/core_checks/cc_synchronization.cpp
layers/core_checks/core_validation.h
layers/error_message/validation_error_enums.h
layers/vulkan/generated/command_validation.cpp
scripts/generators/command_validation_generator.py
tests/unit/command.cpp
tests/unit/descriptor_indexing.cpp
tests/unit/descriptors.cpp
tests/unit/object_lifetime.cpp
tests/unit/pipeline.cpp
tests/unit/query.cpp
tests/unit/sync_object.cpp
tests/unit/transform_feedback.cpp

Removes `UNASSIGNED-CoreValidation-DrawState-InvalidCommandBuffer` and`UNASSIGNED-CoreValidation-DrawState-InvalidEvent` with VUs that are already in spec

layers: Remove more UNASSIGNED VUs

---

layers/core_checks/cc_render_pass.cpp
tests/unit/renderpass.cpp

already had `VUID-VkAttachmentReference2-separateDepthStencilLayouts-03313` but was missing the RenderPass1 version (`VUID-VkAttachmentReference-separateDepthStencilLayouts-03313`)

layers: Add missing VkAttachmentReference VU

---

layers/sync/sync_validation.cpp
tests/unit/sync_val_positive.cpp

This is the follow up to https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/6605
We still validate common case of a non-arrayed descriptor. And for the arrays we assert the absence of false-positive behavior.
Re-enables tests for constant indexing. Later these tests can also validate any potential development based on SPIR-V analysis for constant indices. We can incrementally increase coverage but the tests will guard against false positives.

layers: Disable syncval for all descriptor arrays

---

BUILD.gn
docs/gpu_validation.md
layers/VkLayer_khronos_validation.json.in
layers/gpu_validation/gpu_settings.h
layers/gpu_validation/gpu_state_tracker.cpp
layers/gpu_validation/gpu_state_tracker.h
layers/gpu_validation/gpu_validation.cpp
layers/gpu_validation/gpu_validation.h
layers/layer_options.cpp
layers/layer_options.h
layers/vk_layer_settings.txt
layers/vulkan/generated/chassis.cpp
layers/vulkan/generated/chassis.h
scripts/generators/layer_chassis_generator.py
tests/framework/render.cpp
tests/framework/render.h
tests/unit/gpu_av.cpp
tests/unit/gpu_av_positive.cpp

Addresses #6009
Will also require a spec change to allow a VkValidationFeaturesEXT in the pNext chain of VkShaderModuleCreateInfo (06904)
Updated GPU-AV settings code to use the new utilities which made writing the test for this code much easier
The test does not get a 06904 error, because 06904 isn't implemented, presumably due to pNext being marked noautovalidity

Add GPU-AV option to select which shaders are instrumented

---

layers/core_checks/cc_pipeline_graphics.cpp
tests/unit/viewport_inheritance.cpp

There are 2 paths for the VUID, one does not have the pointer to VkPipelineDiscardRectangleStateCreateInfoEXT

Fix vuid 04809 nullptr dereference

---

layers/stateless/sl_render_pass.cpp
tests/unit/android_external_resolve.cpp
tests/unit/renderpass.cpp
tests/unit/subpass.cpp

Fix the logic for `VUID-VkAttachmentDescription2-format-09332` and `VUID-VkAttachmentDescription2-format-09334`

layers: Fix ExternalFormatResolve UNDEFINED format

---

layers/core_checks/cc_spirv.cpp
layers/gpu_validation/gpu_validation.cpp
tests/unit/pipeline.cpp

Few places `IsExtEnabled` is not needed

WIP layers: Remove unnecessary of IsExtEnabled

---

tests/framework/layer_validation_tests.cpp
tests/framework/layer_validation_tests.h
tests/unit/best_practices.cpp
tests/unit/fragment_shading_rate.cpp
tests/unit/gpu_av.cpp
tests/unit/gpu_av_positive.cpp
tests/unit/image_positive.cpp
tests/unit/nvidia_best_practices.cpp
tests/unit/other_positive.cpp
tests/unit/pipeline_positive.cpp
tests/unit/protected_memory.cpp
tests/unit/push_descriptor.cpp
tests/unit/push_descriptor_positive.cpp
tests/unit/ray_tracing_positive.cpp
tests/unit/sync_object_positive.cpp
tests/unit/transform_feedback.cpp
tests/unit/wsi.cpp
tests/unit/wsi_positive.cpp
tests/unit/ycbcr.cpp

all tests that are skipped are now moved to the internal blacklist so they can be triaged from a single location

tests: Remove IsDriver

---

layers/containers/custom_containers.h
layers/core_checks/cc_ray_tracing.cpp
layers/stateless/sl_ray_tracing.cpp
tests/framework/ray_tracing_objects.cpp
tests/framework/ray_tracing_objects.h
tests/unit/ray_tracing.cpp
tests/vvl_utils/small_vector.cpp

- Partially addresses https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/3792
Also add `04628`, that simply checks that the build mode is a valid value
Add a new utility similar to `vvl::span`, `vvl::enumerate`, that is basically a span where but with the addition of a loop variable holding the current iteration index. `vvl::make_span` and `vvl::enumerate` should cover the needs of the majority of our `for` loops, and probably should be preferred to the usual basic `for` loop. Usage example:
```cpp
std::vector<int> v = {1, 2, 3, 4};
for (auto [x, i] : vvl::enumerate(s.data(), s.size())) {// x is an int*
std::cout << "Value at iteration " << i << ": " << *x << '\n';
}
```

layers: Add `vkCmdBuildAccelerationStructuresKHR` VUIDs related to acceleration structures builds constraints

---

layers/core_checks/cc_pipeline_graphics.cpp
tests/unit/android_external_resolve_positive.cpp

Fix bug when using normal, non-resolve path with `VK_ANDROID_external_format_resolve`

layers: Fix non-Resolve flow in ExternalFormatResolve

---

tests/unit/debug_printf.cpp

I tried to remove these `AddDynamicState` a long time again but these 2 tests blew up... after many other fixes to the `CreatePipelineHelper` class, should be good to remove now

tests: Remove unused dynamic state in DebugPrintF

---

layers/core_checks/cc_device_memory.cpp

VUID was already implemented, but the VUID for vkBindBufferMemory was always reported instead of vkBindBufferMemory2
Last of #6738

layers: Fix VUID for bindBufferMemory2

---

tests/framework/layer_validation_tests.cpp
tests/unit/best_practices.cpp
tests/unit/gpu_av.cpp
tests/unit/gpu_av_positive.cpp
tests/unit/others.cpp
tests/unit/pipeline_positive.cpp
tests/unit/shader_compute_positive.cpp
tests/unit/shader_interface_positive.cpp
tests/unit/shader_limits.cpp
tests/unit/shader_spirv.cpp
tests/unit/shader_spirv_positive.cpp

Some tests are checking for both Error and Warning, some have justifications, but some are just left from when warnings were in CoreChecks
This removes the warning to prevent others from copy-and-pasting this without realizing there isn't a need for it

tests: Cleanup use of error and warning bit

---

layers/core_checks/cc_image.cpp
layers/state_tracker/cmd_buffer_state.h
tests/unit/command.cpp
tests/unit/command_positive.cpp
tests/unit/dynamic_rendering.cpp

we currently were printing
> vkCmdClearAttachments(): pAttachments[0].colorAttachment (1) is larger than colorAttachmentCount (1)
it looking, it seems our logic was messed up

layers: Fix Clear Attachment 07271

---

layers/core_checks/cc_render_pass.cpp
tests/unit/renderpass.cpp

closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/6545
There no core enum values in `VkSubpassDescriptionFlags` so it was going un-noticed in `ValidateSubpassCompatibility` as a field to compare against

layers: Compare VkSubpassDescriptionFlags bewteen RP

---

layers/core_checks/cc_copy_blit_resolve.cpp
tests/unit/command_positive.cpp
tests/unit/image.cpp
tests/unit/image_positive.cpp

For `VK_KHR_maintenance5` added VUs to check when copying images and only one has `VK_REMAINING_ARRAY_LAYERS`
- VUID-VkCopyImageInfo2-srcImage-08794
- VUID-VkCopyImageInfo2-srcImage-08794
- VUID-VkImageBlit-layerCount-08801
- VUID-VkImageBlit2-layerCount-08801
- VUID-VkImageResolve-layerCount-08804
- VUID-VkImageResolve2-layerCount-08804

layers: Add VK_REMAINING_ARRAY_LAYERS VUs

---

layers/best_practices/bp_pipeline.cpp
layers/core_checks/cc_descriptor.cpp
layers/core_checks/cc_spirv.cpp
layers/core_checks/core_validation.h
layers/error_message/logging.cpp
layers/gpu_validation/gpu_state_tracker.cpp
layers/gpu_validation/gpu_validation.cpp
layers/layer_options.cpp
layers/state_tracker/cmd_buffer_state.h
layers/state_tracker/descriptor_sets.cpp
layers/state_tracker/pipeline_layout_state.cpp
layers/state_tracker/shader_module.cpp
layers/state_tracker/shader_module.h
layers/utils/hash_util.cpp
layers/utils/hash_util.h
layers/utils/hash_vk_types.h
layers/utils/shader_utils.cpp
layers/utils/shader_utils.h
tests/unit/others.cpp

This is a rehash of https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/5703 for removing the `DescriptorReqFlags` as it is currently a trap to not realize if some `ResourceInterfaceVariable` are changed they may not be updated and when being validated at draw time

layers: Hash ResourceInterfaceVariable descriptor members

---

layers/core_checks/cc_cmd_buffer_dynamic.cpp

Fixes crashes (after error) in:
dEQP-VK.pipeline.monolithic.extended_dynamic_state.cmd_buffer_start.null_multisample_state
dEQP-VK.pipeline.monolithic.extended_dynamic_state.before_draw.null_multisample_state
dEQP-VK.pipeline.fast_linked_library.extended_dynamic_state.cmd_buffer_start.null_multisample_state
dEQP-VK.pipeline.monolithic.extended_dynamic_state.mesh_shader.cmd_buffer_start.null_multisample_state

Don't dereference missing multisample state

---

layers/best_practices/best_practices_error_enums.h
layers/best_practices/bp_descriptor.cpp
layers/core_checks/cc_descriptor.cpp
layers/core_checks/core_validation.h
tests/unit/best_practices.cpp
tests/unit/descriptors.cpp

closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/5167
as described in the comment (and more detail in https://gitlab.khronos.org/vulkan/vulkan/-/issues/3347) we decided to have a special check for a warning if `VK_ERROR_OUT_OF_POOL_MEMORY` is returned because the type is not in the descriptor pool

layers: Check for bad descriptor type with known error

---

layers/core_checks/cc_pipeline.cpp
layers/core_checks/cc_pipeline_graphics.cpp
layers/core_checks/cc_pipeline_ray_tracing.cpp
layers/core_checks/core_validation.h
layers/state_tracker/pipeline_state.cpp
layers/state_tracker/pipeline_state.h
layers/stateless/sl_pipeline.cpp
tests/unit/pipeline.cpp

Does 3 things at the same time
- Cleanup the `BasePipeline`, `BasePipelineIndex`, and `GetShaderModuleByCIIndex` helper not needed
- Cleanup use of Derivatives (only placed that used it)
- Added a early return to `manual_PreCallValidateCreateGraphicsPipelines` as it got really deeply nested

layers: Cleanup pipeline state generic helpers

---

layers/core_checks/cc_image_layout.cpp
layers/state_tracker/cmd_buffer_state.cpp
tests/framework/layer_validation_tests.cpp
tests/unit/render_pass_positive.cpp

- Closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/4696
Fix image layout transition for depth stencil image when only one aspect is supplied

layers: Fix image layout transition for depth stencil image when only one aspect is supplied

---

.github/workflows/vvl.yml

An attempt to use less minutes for our normal github actions
https://docs.github.com/en/billing/managing-billing-for-github-actions/about-billing-for-github-actions
Currently we are waiting hours for our GitHub CI to run
(redo of https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/6811)

git: Use less minutes for GitHub Actions

---

layers/core_checks/cc_descriptor.cpp
layers/state_tracker/image_state.cpp
layers/state_tracker/image_state.h
layers/state_tracker/shader_module.cpp
layers/state_tracker/shader_module.h
tests/unit/command_positive.cpp
tests/unit/ray_tracing.cpp
tests/unit/shader_spirv.cpp

closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/4355
The spec has a section that describes `SignExtended` and `ZeroExtended` can override the sign of the image access

layers: Check for explicit signedness

---

layers/core_checks/cc_queue.cpp
layers/core_checks/cc_synchronization.cpp
layers/core_checks/core_validation.h
layers/state_tracker/cmd_buffer_state.cpp
layers/state_tracker/cmd_buffer_state.h
layers/state_tracker/queue_state.cpp
layers/state_tracker/state_tracker.cpp
tests/unit/sync_object.cpp
tests/unit/sync_object_positive.cpp

Main logic of this PR is implemented in the `layers: Detect inter-queue event usage` commit.
Other commits are cleanup of existing code: comments for non-trivial parts, updated naming.

layers: Detect inter-queue event usage

---

layers/core_checks/cc_wsi.cpp
layers/state_tracker/image_state.cpp
layers/state_tracker/image_state.h
layers/vulkan/generated/chassis.h
scripts/generators/layer_chassis_generator.py

The `LogInternalError` was not using the new `LogError`, pass the `Location` when calling it

layers: Add new LogError to LogInternalError

---

layers/thread_tracker/thread_safety_validation.cpp
layers/thread_tracker/thread_safety_validation.h
layers/vulkan/generated/thread_safety.cpp
scripts/generators/thread_safety_generator.py
tests/unit/threading.cpp

Pass `Location` for `FindObject`, `HandleErrorOnWrite`, and `HandleErrorOnRead` to know where the error occurred

layers: Add Location to Thread Tracker errors

---

.github/workflows/vvl.yml

- Enable linker warnings as errors on all major platforms
- Cleanup matrix config usage
- Only test CMake 3.17.2 on `linuxBuild`
- Remove names that aren't that helpful

ci: Cleanup vvl.yml

---

tests/unit/sync_val.cpp

Closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/6537
Reverts https://github.com/LunarG/VulkanTests/pull/454
The bug was 100% reproducible on the local machine with regular nvidia drivers. Run `QSBufferEvents` test with `gtest_repeat=100` and run 3 or 4 such sessions in parallel. It fails like this:
Corruption due to `QSBufferEvents` affected `QSOBarrierHazard` that runs after it, but `QSOBarrierHazard` never fails when run alone. 
The issue was not detected by the core validation because it's disabled for syncval tests. There are other failures of core validation in syncval tests. The plan to fix them and also to have a separate run of syncval tests with core validation enabled.

tests: Fix test that breaks nvidia driver

---

layers/object_tracker/object_tracker_utils.cpp

These manual `ObjectTracker` spots were not using the full use of `Location`

layers: Add full Location on manual ObjectTracker

---

layers/stateless/sl_pipeline.cpp
layers/stateless/stateless_validation.h
tests/unit/pipeline.cpp

Move `VkPipelineRenderingCreateInfo` out of the fragment shader state condition and into a separate function

layers: Fix pipeline rendering info validation

---

layers/core_checks/cc_cmd_buffer_dynamic.cpp
layers/core_checks/cc_pipeline_graphics.cpp
layers/state_tracker/pipeline_sub_state.cpp
layers/state_tracker/pipeline_sub_state.h

Remove `todo` to provide a cleaner way to access the Fragment Shader entrypoint when using to get values from it later

layers: Add EntryPoint access to fragment_sub_state

---

layers/state_tracker/descriptor_sets.cpp
layers/state_tracker/descriptor_sets.h

Fixes a crash in dEQP-VK.binding_model.mutable_descriptor.single.acceleration_structure_khr.update_copy.mutable_source.normal_source.pool_same_types.update_after_bind.no_array.comp
with GPU-AV

Fix acceleration structure type when copied to mutable descriptor

---

layers/core_checks/cc_cmd_buffer.cpp
scripts/common_ci.py
tests/framework/layer_validation_tests.h
tests/framework/test_framework.cpp
tests/framework/test_framework.h
tests/unit/sync_val.cpp
tests/unit/sync_val_positive.cpp

* Fix syncval tests to work with core validation
* `--syncval-enable-core` command line option to conveniently test syncval+core during development
* Add pass to CI  (thanks Spencer for the guide) to run syncval with core validation enabled (in addition to regular syncval only)

tests: Make syncval to pass core validation

---

.github/workflows/vvl.yml
CMakeLists.txt

VVL_CPP_STANDARD doesn't provide much value.
Updated github actions CI correspondingly.

ci: Remove usage of VVL_CPP_STANDARD

---

layers/best_practices/bp_pipeline.cpp

`VK_GRAPHICS_PIPELINE_LIBRARY_FRAGMENT_OUTPUT_INTERFACE_BIT_EXT` was missing in #6849

layers: Fix pipeline library rendering best practice

---

scripts/common_ci.py

See:
https://github.com/juan-lunarg/Vulkan-ValidationLayers/actions/runs/6670729791/job/18131209667
<details>
```
[ RUN      ] PositiveSyncObject.WaitEventThenSet
==================
WARNING: ThreadSanitizer: lock-order-inversion (potential deadlock) (pid=13639)
Cycle in lock order graph: M4751765 (0x7b4c00002448) => M109066571313340336 (0x000000000000) => M4751690 (0x7bb00000b4c0) => M4751765
Mutex M109066571313340336 acquired here while holding mutex M4751765 in thread T437:
#0 pthread_rwlock_wrlock ../../../../src/libsanitizer/tsan/tsan_interceptors_posix.cpp:1368 (libtsan.so.0+0x3f778)
#1 __glibcxx_rwlock_wrlock /usr/include/c++/11/shared_mutex:80 (libVkLayer_khronos_validation.so+0x2f1f3c)
#2 std::__shared_mutex_pthread::lock() /usr/include/c++/11/shared_mutex:193 …
```

tsan: Blacklist PositiveSyncObject.WaitEventThenSet

---

layers/core_checks/cc_descriptor.cpp
layers/core_checks/cc_pipeline.cpp
layers/core_checks/core_validation.h

closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/6838
The `std::map` was getting corrupted, but looking more, I realized we really didn't need a hashmap for only 3 entries
The VUID hash map was also easy to replace with the new `Location` and we save carrying around the hash maps and move all the perf cost to error reporting time (as desired)

layers: Refactor ValidatePipelineBindPoint

---

layers/core_checks/cc_shader_interface.cpp
tests/unit/geometry_tessellation_positive.cpp

If tessellation evaluation shader uses point mode, the output primitive will be points

layers: Fix tessellation point mode output

---

tests/unit/other_positive.cpp
tests/unit/others.cpp

closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/2457 - we aren't giving the false positive anymore

tests: Confirm using VkPhysicalDeviceIDProperties

---

tests/unit/query_positive.cpp
tests/unit/sync_object_positive.cpp

The (not)hidden agenda behind this change is to simplify life for the Thread Sanitizer (TS). It can't recognize that queue mutex is private to each `QUEUE_STATE` object and produces false-positive.
If I'm wrong in any of the following considerations lets assume it's just a test cleanup (command pools owns command buffers and `FreeCommandBuffers` is optional).
TS reports possible deadlock due to inverted pair of locks:
(**Q**-mutex -> CmdBuf-mutex) and (CmdBuf->mutex -> **Q**-mutex)
but in our situation we can only have:
(**Q1**-mutex -> CmdBuf-mutex) and (CmdBuf->mutex -> **Q2**-mutex)
which can't lead to deadlock.
Also TS made the above analysis based only a single queue thread (the tests of interest run only single queue thread), which could not lead to a deadlock by definition.
The …

tests: Cleanup tests and help Thread Sanitizer

---

scripts/common_ci.py
scripts/known_good.json

Currently testing just grabs TOT main for Vulkan-Loader, Vulkan-Profile, and Vulkan-Tools.
This isn't great since it makes our testing unrepeatable.
Use known_good.json instead

testing: Use known_good.json for all testing dependencies

---

layers/best_practices/bp_device_memory.cpp
layers/core_checks/cc_android.cpp
layers/core_checks/cc_device_memory.cpp
layers/core_checks/cc_external_object.cpp
layers/state_tracker/device_memory_state.h
layers/state_tracker/queue_state.h
layers/state_tracker/state_tracker.cpp
layers/state_tracker/state_tracker.h
layers/stateless/sl_device_memory.cpp
layers/stateless/sl_external_object.cpp
layers/stateless/sl_instance_device.cpp
layers/stateless/stateless_validation.h
layers/vulkan/generated/stateless_validation_helper.cpp
scripts/generators/stateless_validation_helper_generator.py
tests/device_profiles/max_profile.json
tests/unit/external_memory_sync.cpp
tests/unit/external_memory_sync_positive.cpp
tests/unit/memory.cpp

for https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/5431
Does a lot of cleanup around the External Memory/Sync code
adds:
- VUID-VkMemoryDedicatedAllocateInfo-image-01878
- VUID-VkMemoryDedicatedAllocateInfo-buffer-01879
- VUID-VkImportMemoryFdInfoKHR-handleType-00669
- VUID-VkImportMemoryFdInfoKHR-handleType-00670
- VUID-VkMemoryAllocateInfo-allocationSize-07897
- VUID-VkMemoryAllocateInfo-allocationSize-01743
- VUID-VkImportSemaphoreFdInfoKHR-handleType-07307
- VUID-VkImportSemaphoreFdInfoKHR-handleType-03263
- VUID-vkGetMemoryHostPointerPropertiesEXT-handleType-01752
- VUID-vkGetMemoryHostPointerPropertiesEXT-pHostPointer-01753
- VUID-VkImportMemoryHostPointerInfoEXT-handleType-01748
- VUID-VkImportMemoryHostPointerInfoEXT-pHostPointer-01749
- …

layers: Add External memory/sync VU

---

tests/CMakeLists.txt
tests/framework/layer_validation_tests.h
tests/unit/parent.cpp
tests/unit/parent_positive.cpp

Adds test making sure imageless framebuffer is ignored in generated Object Tracker

tests: Add Positive Parent test

---

tests/unit/shader_storage_image.cpp

`NegativeShaderStorageImage.UnknownWriteComponentA8Unorm` was crashing in mesa because of an uncaught check in `spirv-val` (now added https://github.com/KhronosGroup/SPIRV-Tools/pull/5458)
You can't use `ZeroExtend` on a float image (`A8_UNORM`)

tests: Fix UnknownWriteComponentA8Unorm

---

layers/gpu_validation/debug_printf.cpp
layers/gpu_validation/gpu_state_tracker.cpp
layers/gpu_validation/gpu_validation.cpp
layers/state_tracker/state_tracker.cpp
layers/state_tracker/state_tracker.h

Have the EXT/KHR functions call directly into their promoted function now that we have `RecordObject` to track where it came from

layers: Consalidate alias functions in StateTracker

---

layers/stateless/sl_device_memory.cpp
layers/stateless/stateless_validation.h
layers/vulkan/generated/stateless_validation_helper.cpp
scripts/generators/stateless_validation_helper_generator.py
tests/unit/memory.cpp

adds `VUID-vkSetDeviceMemoryPriorityEXT-priority-06258` (which seems to be the only VU for `VK_EXT_pageable_device_local_memory`)

layers: Add vkSetDeviceMemoryPriorityEXT support

---

layers/core_checks/cc_cmd_buffer.cpp
tests/unit/command.cpp

adds `VUID-vkCmdExecuteCommands-commandBuffer-09375` (for https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/6702)
This was just an implicit VU that was converted to a explicit VU with a feature bit to disable it

layers: Fix new VU for vkCmdExecuteCommands secondary

---

layers/containers/custom_containers.h
layers/core_checks/cc_ray_tracing.cpp
layers/stateless/sl_ray_tracing.cpp
tests/vvl_utils/small_vector.cpp

The structured binding now becomes [index, element_ptr]

layers: Invert parameters order in vvl::enumerate

---

layers/vulkan/generated/object_tracker.cpp
scripts/generators/object_tracker_generator.py
tests/unit/parent.cpp

(slightly) overdue revision of https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/1855
adds 
- VUID-vkGetPipelineExecutableStatisticsKHR-pipeline-03273
- VUID-vkGetPipelineExecutablePropertiesKHR-pipeline-03271
- VUID-vkGetPipelineExecutableInternalRepresentationsKHR-pipeline-03277

layers: VK_KHR_pipeline_executable_properties Device parent

---

layers/layer_chassis_dispatch_manual.cpp
layers/state_tracker/render_pass_state.cpp

VK_ANDROID_external_format allows for the only color attachment to be VK_ATTACHMENT_UNUSED. This lead to the blend state not being copied for the safe_structs used by VVL. If run with GPUAV or shaderprint, the struct sent to the driver will not contain a blend state when the one from the application does. This change fixes that issue.

layers: Mark color attachment used when external resolve present

---

layers/core_checks/cc_pipeline.cpp
tests/unit/graphics_library.cpp
tests/unit/pipeline_positive.cpp

The spec says:
> If the shaderModuleIdentifier feature is enabled, applications can omit shader code for stage and instead provide a module identifier. This is done by including a VkPipelineShaderStageModuleIdentifierCreateInfoEXT struct with identifierSize not equal to 0 in the pNext chain
So this should only be validated if size is greater than 0

layers: Fix shader module identifier check

---

layers/state_tracker/queue_state.cpp

Gets rid of the code pass with two locked mutexes (queue and cmdbuf mutex) which causes false positive from TS (lock inversion). These mutexes can't cause deadlock due to lock inversion because queue mutex is per-thread state.

layers: Unconfuse thread sanitizer

---

tests/framework/external_memory_sync.cpp
tests/framework/external_memory_sync.h

This change fixes hard-coded API-specific include paths replacing them with the expected way to refer to generated files, i.e. `<generated/...>`.

tests: Fix API dependent includes

---

layers/best_practices/bp_drawdispatch.cpp
layers/core_checks/cc_copy_blit_resolve.cpp
layers/core_checks/cc_device_memory.cpp
layers/core_checks/cc_queue.cpp
layers/core_checks/cc_render_pass.cpp
layers/core_checks/cc_synchronization.cpp
layers/sync/sync_validation.cpp
layers/sync/sync_validation.h
layers/vulkan/generated/best_practices.cpp
layers/vulkan/generated/thread_safety.cpp
scripts/generators/best_practices_generator.py
scripts/generators/object_tracker_generator.py
scripts/generators/thread_safety_generator.py

This removes all the StateTracker based classes from calling into the promoted functions 
once  https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/6768 is fixed up, will just remove the promoted functions from `ValidationStateTracker` class so it can't be done by accident

layers: Remove calls to promoted func in StateTracker

---

layers/containers/range_vector.h
layers/containers/subresource_adapter.h
layers/sync/sync_validation.cpp
layers/sync/sync_validation.h

Targeted optimizations that help some traces, but don't hurt any.
1)  Use range/iterator combined walk to avoid pre-range lower_bound calls
2)  DetectHazard with range_gen/iterator walk
Benefits traces where resource access state ranges well match range generated one

Syncval: Perf:  Additional (up to 25%) performance gains for certain traces

---

layers/core_checks/cc_external_object.cpp
layers/state_tracker/state_tracker.cpp
layers/state_tracker/state_tracker.h
tests/unit/external_memory_sync.cpp
tests/unit/external_memory_sync_positive.cpp

part of https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/5431
adds VUID-VkImportSemaphoreFdInfoKHR-handleType-03264

layers: Add Sync FD Semaphore type

---

layers/stateless/sl_image.cpp
layers/stateless/stateless_validation.h
layers/vulkan/generated/stateless_validation_helper.cpp
scripts/generators/stateless_validation_helper_generator.py
tests/unit/image.cpp

I have https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/6264 which will fix the VUs as they were referring to a "created image" but this struct was designed to query prior to the image creation

layers: Add VkDeviceImageSubresourceInfoKHR

---

layers/core_checks/cc_synchronization.cpp
layers/core_checks/core_validation.h
layers/state_tracker/queue_state.cpp
layers/state_tracker/queue_state.h

Make sure it's more obvious when functions work with binary semaphores.
Clarify semantics of SemOp::CanBeWaited/CanBeSignaled. It checks if binary semaphore can be waited/signaled *after* this specific SemOp.

layers: Clarify naming for binary semaphore cases

---

layers/core_checks/cc_spirv.cpp
layers/state_tracker/shader_module.cpp
layers/state_tracker/shader_module.h
layers/utils/shader_utils.cpp
layers/utils/shader_utils.h
tests/unit/shader_spirv.cpp
tests/unit/shader_spirv_positive.cpp
tests/unit/subpass.cpp
tests/unit/subpass_positive.cpp

- Move SpecConstant look up into a `PipelineStageState` helper function
- Only track a single set of SpecConstant mappings
- Adds more tests (most are just getting ready for a proper fix for #5911 )

layers: Have single way to get SpecConstant values

---

layers/core_checks/cc_copy_blit_resolve.cpp
tests/unit/command.cpp

This was added in https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/6843/ and seems there are some issues being tracked in https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/6898
For now just removing the logic from running until proper testing can be added to confirm we have correctly added support

layers: Revert ImageBufferCopyMemoryOverlap

---

layers/sync/sync_validation.cpp

An assert was too broadly applied and could trigger in the valid condition that the lower_bound of a range also overlaps and early range (and thus been processed/advanced past).
Also added a missing check vs. end that could have resulted in an invalid access when `pos == map.end()`.
Addresses #6926 .

syncval: Remove bad assert/Avoid bad access

---

layers/core_checks/cc_descriptor.cpp
layers/error_message/validation_error_enums.h

adds `VUID-VkDescriptorImageInfo-imageLayout-09425` and `VUID-VkDescriptorImageInfo-imageLayout-09426`
Waiting to fix/remove `UNASSIGNED-CoreValidation-DrawState-InvalidImageAspect` in order to write tests

layers: Remove UNASSIGNED InvalidImageView

---

layers/drawdispatch/descriptor_validator.cpp
layers/drawdispatch/drawdispatch_vuids.cpp
layers/drawdispatch/drawdispatch_vuids.h
layers/state_tracker/shader_module.cpp
layers/state_tracker/shader_module.h
tests/unit/gpu_av.cpp
tests/unit/ycbcr.cpp
tests/unit/ycbcr_positive.cpp

adds `VUID-vkCmdDraw-None-06550` and `VUID-vkCmdDraw-ConstOffset-06551`
Checks the ImageAccesses of any Ycbcr sampled descriptor

layers: Check Ycbcr sampling instructions

---

layers/core_checks/cc_external_object.cpp
layers/core_checks/cc_synchronization.cpp
layers/core_checks/cc_wsi.cpp
layers/core_checks/core_validation.h
layers/state_tracker/queue_state.cpp
layers/state_tracker/queue_state.h

It's enough to have a single map to track both binary payload value and the status of whether the payload was updated by this submission.
Adds comments that explain two stages of querying payload value (current submission, then other submissions).
Documents more places where we know that binary semaphore is used and not an arbitrary semaphore.
It has to be an equivalent transformation of code (until it's not).

layers: Refactor how semaphore binary payload is tracked

---

layers/containers/range_vector.h

Avoids potential derefrence of end.

syncval: Add end check to pos increment shortcut

---

layers/gpu_shaders/gpu_shaders_constants.h
layers/gpu_validation/gpu_descriptor_set.cpp

gpuav_state::DescriptorHeap has to keep track of all resources that could be used in a descriptor, in gpu-accessible memory. Avoid an infinite loop if this limit is hit and raise the limit.

gpu: Fix handling of maximum descriptor records

---

layers/object_tracker/object_lifetime_validation.h
layers/object_tracker/object_tracker_utils.cpp
layers/vulkan/generated/object_tracker.cpp
scripts/generators/object_tracker_generator.py

1. Moves logic from headers to source (it seems it use to be small but now grown my larger then code in a header file should be)
2. Add missing VUs for `VkAllocationCallbacks` when destroyed
3. `swapchainImageMap` -> `swapchain_image_map`

ObjectTracker cleanup

---

tests/framework/binding.cpp
tests/framework/binding.h
tests/unit/wsi.cpp
tests/unit/wsi_positive.cpp

- Adds helper to create transition barriers (there are some subtleties there, and the tests often did that in a different ways).
- Rename  `NegativeWsi.UseSwapchainImageBeforeWait` -> `NegativeWsi.PresentImageWithWrongLayout` to show what the test actually does. It made attempt to create a "missing semaphore wait" scenario, but the actual validation was about image layout. At the moment we don't have the missing semaphore wait validation but it will be added in the future PR.

tests: Cleanup wsi tests

---

layers/core_checks/cc_render_pass.cpp
tests/unit/dynamic_rendering.cpp

VUID from https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/6702

layers: Validate dynamic rendering with VK_RENDERING_CONTENTS_INLINE_BIT_EXT flag

---

tests/android/CMakeLists.txt

TLDR: Keep `nodelete` for Android CI performance
https://github.com/LunarG/VulkanTests/pull/432

android: Document nodelete performance benefits

---

layers/vulkan/generated/vk_extension_helper.h
layers/vulkan/generated/vk_function_pointers.cpp
layers/vulkan/generated/vk_function_pointers.h
scripts/generators/extension_helper_generator.py
scripts/generators/function_pointers_generator.py
tests/framework/render.cpp
tests/framework/render.h
tests/unit/best_practices.cpp
tests/unit/command_positive.cpp
tests/unit/descriptors.cpp
tests/unit/external_memory_sync.cpp
tests/unit/image_drm.cpp
tests/unit/instance_positive.cpp
tests/unit/sampler_positive.cpp
tests/unit/shader_spirv_positive.cpp

This is just a draft to see whether this approach looks fine. This, as is, currently will fail CI, so we'll have to add some mechanisms to deal with extensions that intentionally depend on the old behavior.
What this does is that if the test requests both a core API version (target, not necessarily required) and an extension that's part of the effective core version, then it does not enable the extension, only the core version.
Maybe we should relax this and just remove the requirement, so this is for discussion for now based on our offline conversations with @spencer-lunarg.

tests: Draft for redundant core and extension dependencies

---

layers/core_checks/cc_pipeline_graphics.cpp

VUIDs 06183 and 06184 only apply if dynamic rendering is used
VUID 06183 was also checking for `VK_PIPELINE_RASTERIZATION_STATE_CREATE_FRAGMENT_SHADING_RATE_ATTACHMENT_BIT_KHR` instead of `VK_PIPELINE_CREATE_RENDERING_FRAGMENT_SHADING_RATE_ATTACHMENT_BIT_KHR`

layers: Fix flag check for VUID 06183

---

docs/fine_grained_locking.md
layers/best_practices/best_practices_validation.h
layers/best_practices/bp_drawdispatch.cpp
layers/best_practices/bp_pipeline.cpp
layers/core_checks/cc_descriptor.cpp
layers/core_checks/cc_drawdispatch.cpp
layers/core_checks/core_validation.h
layers/drawdispatch/descriptor_validator.cpp
layers/drawdispatch/descriptor_validator.h
layers/gpu_validation/gpu_descriptor_set.cpp
layers/gpu_validation/gpu_descriptor_set.h
layers/gpu_validation/gpu_subclasses.cpp
layers/gpu_validation/gpu_validation.cpp
layers/gpu_validation/gpu_validation.h
layers/state_tracker/cmd_buffer_state.cpp
layers/state_tracker/cmd_buffer_state.h
layers/state_tracker/descriptor_sets.cpp
layers/state_tracker/descriptor_sets.h
layers/state_tracker/pipeline_layout_state.cpp
layers/state_tracker/pipeline_layout_state.h
layers/state_tracker/pipeline_state.cpp
layers/state_tracker/pipeline_state.h
layers/state_tracker/shader_object_state.cpp
layers/state_tracker/shader_object_state.h
layers/state_tracker/state_tracker.cpp
layers/state_tracker/state_tracker.h
layers/sync/sync_validation.cpp
layers/vulkan/generated/chassis.cpp
scripts/generators/layer_chassis_generator.py

cvdescriptorset stood for Core Validation DescriptorSet, which is not a useful grouping of things. Start to move state tracker objects into the common namespace by renaming this one to include them.
Rename all vulkan handle accessors to VkHandle(), which makes it easier to remember than the old inconsistent names that violate coding standards in some cases. (eg. GetSet(), queue(), commandBuffer()).
Note that the VulkanTypedHandle accessor, Handle(), should be used with error logging functionality, such as FormatHandle(), LogObjectList(), and LogError().  The handle type is lost when passing raw non-Dispatchable handles to these functions on 32 bit systems.

layers: Move cvdescriptorset namespace contents to vvl::

---

tests/framework/gpu_av_helper.h
tests/framework/layer_validation_tests.h
tests/framework/test_framework.cpp
tests/framework/test_framework.h
tests/unit/gpu_av.cpp
tests/unit/gpu_av_positive.cpp
tests/unit/ray_tracing_gpu_nv.cpp
tests/unit/shader_object_positive.cpp

Add option --gpuav-enable-core to enable core validation when running gpu-av tests
With that option enabled, locally the only failing test is `VkGpuAssistedLayerTest.UnnormalizedCoordinatesSeparateSamplerSharedSampler`, the expected VUID `VUID-vkCmdDraw-None-08609` is not received.
I updated this test so that it works with core validation enabled, and added a comment describing the situation

tests: Add option --gpuav-enable-core

---

layers/core_checks/cc_wsi.cpp
layers/core_checks/core_validation.h
layers/state_tracker/image_state.cpp
layers/state_tracker/image_state.h
layers/state_tracker/state_tracker.cpp
tests/unit/wsi.cpp
tests/unit/wsi_positive.cpp

Validates that semaphore or fence from `vkAcquireNextImageKHR` has been waited on.
Closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/4593

layers: Validate image acquire wait

---

scripts/known_good.json
tests/framework/shader_helper.h

KhronosGroup/glslang/pull/3397 cleans up the header files glslang was installing.
Now only the intended files are being installed.
FYI @arcady-lunarg

glslang: Remove usage of non-public header file

---

layers/containers/subresource_adapter.cpp

Current ImageRangeGenerator doesn't emit monotonic ranges when the implementation packs MIP levels inside the "minimum stride" empty space.  The range map traversal engines require monotonic ranges.
This workaround forces the range generator encoder setup logic to use "idealized" memory organization for images with more than one mip level.
A better solution will be needed for full accurate aliasing support.

syncval: Add workaround to ensure monotonic rangegen

---

layers/gpu_shaders/gpu_shaders_constants.h
layers/gpu_validation/debug_printf.cpp
layers/gpu_validation/debug_printf.h
layers/gpu_validation/gpu_descriptor_set.cpp
layers/gpu_validation/gpu_descriptor_set.h
layers/gpu_validation/gpu_image_layout.cpp
layers/gpu_validation/gpu_state_tracker.cpp
layers/gpu_validation/gpu_state_tracker.h
layers/gpu_validation/gpu_subclasses.cpp
layers/gpu_validation/gpu_subclasses.h
layers/gpu_validation/gpu_validation.cpp
layers/gpu_validation/gpu_validation.h
layers/gpu_validation/gpu_vuids.cpp
layers/gpu_validation/gpu_vuids.h
layers/layer_options.cpp
layers/vulkan/generated/chassis.cpp
layers/vulkan/generated/chassis.h
layers/vulkan/generated/chassis_dispatch_helper.h
scripts/generators/layer_chassis_generator.py
tests/unit/gpu_av_positive.cpp

Convert `gpuav_state::` to `gpuav::`, `debug_printf_state::` to `debug_printf::` and `gpu_utils_state::` to `gpu_tracker::`. Move all definitions for each validation area into these namespaces. Having a separate `_state` namespace isn't very helpful.
Note that the 'main' objects are now called `namespace::Validator`. At some point these very large classes should be split up into at least `namespace::Instance` and `namespace::Device`, but possibly there should be a separate class for every dispatchable handle type. But this is not going to happen soon.
Add a `BaseClass` alias in each `Validator` class so that upcalls are easier to do. In the past, people have forgotten about `gpu_tracker::Validator()` and called directly into `ValidationStateTracker`, which lead to bugs.
Unfortunately, …

gpu: Put GPUAV and DebugPrintf in namespaces

---

.github/workflows/vvl.yml

1. Sets address/thread sanitizer in a much clearer fashion
1. Removes clang testing, we test clang for Android/Apple/Chromium/etc extensively already
1. Improves the naming of the runs
1. Removes unnecessary python usage from the linux runs

GitHub actions cleanup linux CI runs

---

layers/vulkan/generated/chassis.cpp
scripts/generators/layer_chassis_generator.py

vkGetInstanceProcAddr and vkGetDeviceProcAddr were occassionally linking to the libvulkan.so's functions rather than the validation layers own symbols. While the root cause of this is unclear, it is very easy to prevent, by directly using the vulkan_layer_chassis::Get<Instance|Device>ProcAddr.
Fixes #6890

chassis: Use vulkan_layer_chassis instead of globals

---

tests/unit/debug_printf.cpp
tests/unit/gpu_av.cpp
tests/unit/gpu_av_positive.cpp
tests/unit/subpass.cpp

The GPU-AV glsl code was never converted to the `R"glsl( ... )glsl";` format
It is much easier to maintain in this format

tests: Use GLSL multistrings

---

BUILD.gn
layers/CMakeLists.txt
layers/gpu_validation/gpu_record.cpp
layers/gpu_validation/gpu_setup.cpp
layers/gpu_validation/gpu_validation.cpp
layers/gpu_validation/gpu_validation.h

Cleanup gpu_validation.cpp by creating gpu_record.cpp for Record functions, and gpu_setup.cpp for validation related state objects creation/destruction
Reorganise function declarations in gpuav::Validator accordingly

gpu: Create gpu_record.cpp and gpu_setup.cpp

---

layers/VkLayer_khronos_validation.json.in
layers/gpu_validation/gpu_record.cpp
layers/gpu_validation/gpu_settings.h
layers/gpu_validation/gpu_validation.cpp
layers/layer_options.cpp
layers/vk_layer_settings.txt
layers/vulkan/generated/chassis.cpp
scripts/generators/layer_chassis_generator.py

Create a single `validate_indirect_buffer` to bundle all the GPU-AV settings together related to checking the indirect buffers
I find it not practical where someone would want to validate just the `Dispatch` but not the `Draws` indirect buffers

gpuav: Combine Indirect Buffer settings

---

scripts/generate_source.py
scripts/generate_spec_error_message.py
scripts/vk_validation_stats.py

`vk_validation_error_messages.h` use to be non-obviously generated from the `vk_validation_stats.py` file
this moves the logic to a dedicated file (that we don't need to use `subprocess.check_call` to call)

scripts: Separate vk_validation_error_messages.h script

---

layers/error_message/logging.cpp
layers/error_message/logging.h
layers/gpu_validation/gpu_error_message.cpp

* Updates function signatures to be more clear about consequences
* Adds missing lock to gpu-av reporting

layers: Clarify no-locking nature of debug reporting routines

---

docs/creating_tests.md
tests/framework/binding.cpp
tests/framework/binding.h
tests/framework/layer_validation_tests.cpp
tests/framework/render.cpp
tests/framework/render.h
tests/unit/best_practices.cpp
tests/unit/fragment_shading_rate.cpp
tests/unit/fragment_shading_rate_positive.cpp
tests/unit/host_image_copy_positive.cpp
tests/unit/image.cpp
tests/unit/imageless_framebuffer.cpp
tests/unit/multiview.cpp
tests/unit/others.cpp
tests/unit/pipeline.cpp
tests/unit/pipeline_positive.cpp
tests/unit/ray_tracing.cpp
tests/unit/render_pass_positive.cpp
tests/unit/renderpass.cpp
tests/unit/sampler.cpp
tests/unit/shader_storage_image.cpp
tests/unit/sync_object.cpp
tests/unit/sync_val.cpp
tests/unit/ycbcr.cpp
tests/unit/ycbcr_positive.cpp

This is a follow-up on https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/6923 with the following additions:
* Improved handling of promoted extensions
* Documentation updates regarding the suggested way to handle dependencies in test cases
* Fixes to various test cases with incorrect dependencies

tests: Fix test case dependencies

---

tests/unit/dynamic_rendering_positive.cpp

`VkImageObj::targetView()` is an error-prone design. The method suggests it will return target view based on provided parameters but it does this only for the first call. For subsequent calls it ignores provided parameters and returns cached value. When reading code it's not clear what the result of `targetView` will be without checking previous context. 
The plan for the future change. Get rid of targetView. Use vkt::ImageView directly. VkImageObj currently provides BasicViewCreateInfo() to initialize VkImageViewCreateInfo parameterized by aspect - that's convenient and can be kept. Additional constructor can be added to vkt::ImageView that creates image view based on provided image (and also parameterize by aspect).
Closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/70 …

tests: Fix MatchingAttachmentFormats2

---

tests/unit/dynamic_state.cpp

This test is validating maxSampleLocationGridSize.width modulo sampleLocationGridSize.width and used `max - 1` to get the used width, but this fails if max is 2

tests: Fix sample locations enable test

---

tests/unit/dynamic_state.cpp

This test could fail depending on `VkPhysicalDeviceSampleLocationsPropertiesEXT` limits

tests: Fix sample locations grid size test

---

tests/unit/mesh.cpp

The test would fail if any of the parameters are `UINT32_MAX`

tests: Fix task shader invocations test

---

CMakeLists.txt

Isn't used in CI, no plans to work on this at the moment.

cmake: Remove VVL_CLANG_TIDY

---

CMakeLists.txt

After looking at all the various package mangers they have updated to using the utility libraries.
This warning is no longer needed.

cmake: Remove warning

---

tests/unit/descriptors.cpp
tests/unit/image.cpp
tests/unit/others.cpp
tests/unit/sampler.cpp
tests/unit/shader_storage_image_positive.cpp
tests/unit/viewport_inheritance.cpp

I found some more test cases that had broken dependency code in my temporary change for the Vulkan SC Validation Layers.

tests: Fix some more test case dependency issues

---

layers/vulkan/generated/chassis.cpp
scripts/generators/layer_chassis_generator.py
scripts/generators/object_tracker_generator.py

This changes the following:
* Makes it possible for the validation layers to expose zero instance and/or device extensions (changes in `layer_chassis_generator.py`)
* Removes the need for API-specific undestroyed object VUIDs thanks to ifdef'd VUID support and related cleanup

scripts: Robustness improvements and cleanup

---

layers/gpu_validation/gpu_error_message.cpp
layers/gpu_validation/gpu_record.cpp
layers/gpu_validation/gpu_setup.cpp
layers/gpu_validation/gpu_subclasses.cpp
layers/gpu_validation/gpu_subclasses.h
layers/gpu_validation/gpu_validation.cpp
layers/gpu_validation/gpu_validation.h

Adding validation for a command that needs to track the lifetime of its specific validation resources is a bit painful, as you need to update "Uber" functions, and classes, mainly `AllocateValidationResources`, `GenerateValidationMessage`, and the `gpuav::CommandBuffer` class. 
This design does not scale well, this PR is the starting point I propose for an improved organisation. 
One of the root problem is how `AllocateValidationResources` is used. Every recorded command that needs to allocate validation resources and need them to survive until an eventual error message is generated uses `AllocateValidationResources`.
But not all of them want the same thing, right now this is handled with a big `if` block that allocates some resources or not depending on the command being validated. If …

gpu: Reorganise parts of the validation and error messages logic to simplify things

---

layers/core_checks/cc_image.cpp

Fixes crash seen in CTS tests in:
dEQP-VK.pipeline.monolithic.multisample.multisampled_render_to_single_sampled.clear_attachments.*
Somewhat related to the PR, it would be nice if I didn't have to break the CTS test name for the commit description into multiple lines.

layers: Check resolve attachment usage before access

---

tests/unit/shader_storage_image.cpp

SetDesiredFailureMsg() should be under the same condition as verifyFound()

tests: Fix shader storage image format test

---

layers/core_checks/cc_image.cpp
tests/unit/wsi.cpp
tests/unit/wsi_positive.cpp

VUID 00995 wasnt fully validated, because of it `VkPositiveLayerTest.DestroySwapchainWithBoundImages` was invalid and crashed on some drivers

layers: Add missing validation for 00995

---

layers/core_checks/cc_query.cpp
layers/stateless/sl_cmd_buffer.cpp
tests/unit/query.cpp
tests/unit/video.cpp

upcoming Spec PR https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/6304 will fix the VUs that were missing in 1.3.271 spec
this just gets the VU churn fixed now early

layers: Fix upcoming VUID in 272

---

layers/state_tracker/shader_instruction.cpp
layers/state_tracker/shader_instruction.h

While debugging `Instruction` is can be hard to understand what is going on with a raw `uint32_t[]` of the words
When seeing code calling `insn->Word(2)` it can be hard to understand what that is grabbing without having to execute the helper member functions in a debugger

layers: Add debug info for Instruction

---

layers/core_checks/cc_spirv.cpp
layers/gpu_validation/debug_printf.cpp
layers/gpu_validation/gpu_validation.cpp

I have seen this a few times where people hit an error from `spirv-val`/`spirv-opt`/etc and want to report it as a VVL issue
Add some more clear text to help describe that the VVL didn't do the SPIR-V parsing for these areas

layers: Improve SPIRV-Tools related error message

---

scripts/known_good.json
tests/CMakeLists.txt

KhronosGroup/glslang/pull/3426 removed the OGLCompiler and HLSL stub libraries.
Furthermore there was no reason for us to link OSDependent, MachineIndependent, GenericCodeGen, and glslang.

tests: Remove usage of unused glslang libraries

---

layers/core_checks/cc_cmd_buffer.cpp

Fixes crash in dEQP-VK.shader_object.misc.state.shaders.vert_geom_frag.geometry_streams.enabled

Fix crash when missing pipeline state

---

layers/sync/sync_commandbuffer.cpp
layers/sync/sync_commandbuffer.h
layers/sync/sync_op.cpp
layers/sync/sync_submit.h

Correct and clarify hazard messages at exec and submit command buffer time.

syncval: Correct hazard report for submit and exec

---

layers/error_message/logging.cpp
layers/sync/sync_commandbuffer.cpp
layers/sync/sync_commandbuffer.h
layers/sync/sync_validation.cpp
layers/sync/sync_validation.h

Closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/6698
Allows to trigger a breakpoint when a command stream reaches the location identified by the `command number`/`reset count` from the syncval error message. 
The implementation is experimental and can be replaced by a better debugging mechanism in the future. It assumes deterministic application behavior which is often not the case, but still can be useful for simpler scenarios.
In order to trigger a breakpoint for specific `command number`/`reset count` (*prior access* location):
1. Specify command to track by setting environment variables:
`VK_SYNCVAL_DEBUG_COMMAND_NUMBER` (mandatory, can be extracted from existing error message),
`VK_SYNCVAL_DEBUG_RESET_COUNT` (optional, default value is 1, can be extracted from …

layers: Report when syncval reaches requested command

---

layers/containers/subresource_adapter.cpp

Linear range generation needs to be reworked to correctly handle various implementation's use of interleave subresources with overlapping strides.
Rework must correctly divorce stride from size, and ensure monotonicity of generated ranges.

syncval: Disable all linear image range generation

---

.github/workflows/sdk_android_build.yml

- Remove usage of set-output it is deprecated
- Correctly get the version from the branch name
- Avoid name redundancy in the zip/tar

android: Minor Android SDK release fixes

---

tests/framework/render.h
tests/unit/android_external_resolve.cpp
tests/unit/android_external_resolve_positive.cpp
tests/unit/dynamic_rendering.cpp
tests/unit/fragment_shading_rate.cpp
tests/unit/imageless_framebuffer.cpp
tests/unit/multiview.cpp
tests/unit/render_pass_positive.cpp
tests/unit/ycbcr.cpp

Part one of replacing `targetView` due to the issue mentioned here https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/7013
While targetView is still here this PR adds asserts when it is used incorrectly. A couple of tests triggered that asserts and were fixed. `targetView` has two overloads. This PR starts with a simpler one (called only in a few places) and replaces it with `CreateView` that returns uncached `vkt::ImageView`.

tests: Replace targetView with CreateView (part 1)

---

tests/framework/render.cpp
tests/framework/render.h
tests/unit/arm_best_practices.cpp
tests/unit/command.cpp
tests/unit/command_positive.cpp
tests/unit/descriptors.cpp
tests/unit/dynamic_rendering.cpp
tests/unit/dynamic_state.cpp
tests/unit/dynamic_state_positive.cpp
tests/unit/imageless_framebuffer.cpp
tests/unit/mesh.cpp
tests/unit/multiview.cpp
tests/unit/pipeline_positive.cpp
tests/unit/portability_subset.cpp
tests/unit/renderpass.cpp
tests/unit/transform_feedback.cpp
tests/unit/wsi_positive.cpp

My goal is to improve the way we do Renderpass/Framebuffer so things are just magically done in the `InitRenderTarget` with hidden options
This tries to cleanup some of the member variables and soon move them behind a proper "render pass helper" object

tests: Cleanup of RenderPass/Framebuffer helper

---

layers/CMakeLists.txt

Use PUBLIC to ensure dependencies are propogated properly.
Libraries and targets following PUBLIC are linked to, and are made part of the link interface.
This nicely shares the code dependency so additional libraries only have to link against VkLayer_utils.

cmake: Cleanup mimalloc and robin_hood code

---

layers/core_checks/cc_render_pass.cpp
tests/unit/renderpass.cpp

closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/7076

layers: Fix 272 VUID Churn

---

tests/unit/other_positive.cpp
tests/unit/others.cpp

closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/5600
The logic for what is needed for each extension is currently working as expected

tests: Confirm extension dependency works correctly

---

tests/CMakeLists.txt
tests/framework/render.cpp
tests/framework/render.h
tests/framework/render_pass_helper.cpp
tests/framework/render_pass_helper.h
tests/unit/command.cpp
tests/unit/command_positive.cpp
tests/unit/descriptors.cpp
tests/unit/descriptors_positive.cpp
tests/unit/dynamic_rendering_positive.cpp
tests/unit/dynamic_state.cpp
tests/unit/image_positive.cpp
tests/unit/imageless_framebuffer.cpp
tests/unit/imageless_framebuffer_positive.cpp
tests/unit/multiview.cpp
tests/unit/pipeline.cpp
tests/unit/pipeline_positive.cpp
tests/unit/protected_memory.cpp
tests/unit/render_pass.cpp
tests/unit/render_pass_positive.cpp
tests/unit/shader_interface_positive.cpp
tests/unit/shader_object.cpp
tests/unit/shader_spirv.cpp
tests/unit/vertex_input_positive.cpp

Adds the first RenderPass helper `RenderPassSingleSubpass`
The goal is to make creating a basic `VkRenderPass` for most tests much easier. I wanted to fix the few tests that do crazy stuff inside `InitRenderTarget`, but in order to do that, we need a better way to create a simple RenderPass
It is not aimed to work with RenderPass2 or multi-subpasses... I figured those can be added as needed, potentially in a second class object
Final note, I plan to add this to more tests, but wanted to get "something" up for now

tests: Add RenderPassSingleSubpass

---

tests/CMakeLists.txt
tests/framework/apple_wsi.h
tests/framework/apple_wsi.mm
tests/framework/layer_validation_tests.cpp
tests/framework/render.cpp
tests/framework/render.h
tests/unit/arm_best_practices.cpp
tests/unit/wsi_positive.cpp

Required adding objective-c++ code into the test codebase to properly aquire the MetalLayer
closes #6412
<details>
```
Note: Google Test filter = *PositiveWsi*
[==========] Running 16 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 16 tests from PositiveWsi
[ RUN      ] PositiveWsi.UseDestroyedSwapchain
Driver Name = MoltenVK
Driver Info = 1.2.6
[       OK ] PositiveWsi.UseDestroyedSwapchain (2840 ms)
[ RUN      ] PositiveWsi.CreateWaylandSurface
/Users/juanramos/projects/vvl/tests/unit/wsi_positive.cpp:23: Skipped
test not supported on platform
[  SKIPPED ] PositiveWsi.CreateWaylandSurface (1 ms)
[ RUN      ] PositiveWsi.CreateXcbSurface
/Users/juanramos/projects/vvl/tests/unit/wsi_positive.cpp:94: Skipped
test not supported on platform
[  SKIPPED ] …
```

apple: Add WSI support for tests on MacOS

---

.github/workflows/vvl.yml

Per team meeting the limited amount of minutes due to the free account KhronosGroup uses.

ci: Remove MacOS from CI

---

layers/sync/sync_access_context.cpp
layers/sync/sync_access_context.h
layers/sync/sync_op.cpp
layers/sync/sync_op.h

`SyncImageMemoryBarrier` and `SyncBufferMemoryBarrier` were in different files. Logically they belong to a higher-level `sync_op` module, which uses them to define other structures and defines all implementation that works with those structures.

syncval: Move SyncImageMemoryBarrier to sync_op module

---

scripts/gn/generate_vulkan_layers_json.py

generate_vulkan_layers_json.py:31: SyntaxWarning: invalid escape sequence '\ '
"""Like regular glob but replaces \ with / in returned paths."""

[scripts] [gn] Fix Python 3.12 compatibility

---

scripts/common_ci.py
tests/framework/layer_validation_tests.h
tests/unit/command.cpp
tests/unit/other_positive.cpp
tests/unit/query_positive.cpp
tests/unit/sync_object_positive.cpp
tests/unit/sync_val.cpp
tests/unit/viewport_inheritance.cpp

Currently all of these tests aren't being run at all despite only having issues with thread sanitizer.

scripts: Move TSAN blacklist into C++ code instead of script

---

layers/vulkan/generated/stateless_validation_helper.cpp
scripts/generators/stateless_validation_helper_generator.py

Now that VK_STRUCTURE_TYPE_LAYER_SETTINGS_CREATE_INFO_EXT is an official sType we no longer need this workaround in the codegen.

scripts: Remove sType workaround

---

layers/vulkan/generated/spirv_grammar_helper.cpp
layers/vulkan/generated/spirv_grammar_helper.h
scripts/known_good.json
tests/unit/shader_compute.cpp
tests/unit/shader_limits.cpp

Fixes 2 tests @jeremyg-lunarg disabled to get the new SPIRV-Tools in https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/7062

tests: Fix disabled VK_KHR_workgroup_memory_explicit_layout

---

tests/framework/binding.cpp
tests/framework/binding.h
tests/framework/render.cpp
tests/unit/arm_best_practices.cpp
tests/unit/command.cpp
tests/unit/debug_printf.cpp

Note that vkt::CommandBuffer::begin() no longer sets VK_COMMAND_BUFFER_USAGE_ONE_TIME_SUBMIT_BIT by default, but it is instead added in the places it is needed. This mostly is in arm best practices because of
`UNASSIGNED-BestPractices-vkBeginCommandBuffer-one-time-submit`.

tests: Fix core validation errors in GPU-AV tests

---

layers/sync/sync_commandbuffer.cpp
layers/sync/sync_op.cpp

Addresses https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/7010
Adds buffer/image handles from CmdPipelineBarrier command to syncval error messages.
@jzulauf-lunarg any issues with adding handles this way? 
I also not sure if there's a reason that current formatting puts handle between `seq_no` and `reset_no`. It looks nicer if resource handles are listed after command buffer handle or at the end of the message.
Updated error message for `vkCmdPipelineBarrier2`:
> Validation Error: [ SYNC-HAZARD-WRITE-AFTER-WRITE ] Object 0: handle = 0x1b93f430d30, type = VK_OBJECT_TYPE_QUEUE; | MessageID = 0x5c0ec5d6 | vkQueueSubmit2():  Hazard WRITE_AFTER_WRITE for entry 0, VkCommandBuffer 0x1b94908b6c0[], Submitted access info (submitted_usage: SYNC_IMAGE_LAYOUT_TRANSITION, command: …

layers: Report barrier buffer/image in syncval messages

---

.github/workflows/vvl.yml

CMake 3.28 is having issues with the macos-11 runner.

ci: Update to macos-12 for iOS build

---

layers/sync/sync_commandbuffer.h
tests/unit/sync_val.cpp

Closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/7010
Addresses this comment https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/7010#issuecomment-1846751346 that  for barriers with many objects we have limitation of 8 bit type used to define size type of small vector.
The size of `small_vector<>` has not changed due to alignment gaps we had when used uint8_t (stats for msvc compiler):
uint8_t: 88 bytes
uint16_t 88 bytes
uint32_t 88 bytes

layers: Use 32bit size type for handle vector instead of 8bit

---

layers/core_checks/cc_cmd_buffer.cpp
layers/core_checks/cc_copy_blit_resolve.cpp
layers/core_checks/cc_image_layout.cpp
layers/core_checks/core_validation.h
tests/unit/image.cpp

closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/5967
This PR does 3 things
1. Removes the perf warning that I don't feel belongs there (or really even in BP atm)
2. Fixes the VUs that are just suppose to check if the `VkImageLayout` is valid (example `VUID-vkCmdCopyImage-dstImageLayout-01395`)
3. Adds the new 1.3.273 VUs (`VUID-vkCmdBlitImage-srcImage-09459`, `VUID-VkBlitImageInfo2-srcImage-09459`, `VUID-vkCmdCopyImage-srcImage-09460`, `VUID-VkCopyImageInfo2-srcImage-09460`)

Fix and add new VkImageLayout VUs

---

layers/sync/sync_commandbuffer.cpp
tests/unit/sync_val.cpp

Always detect access as WRITE when resource is marked as writeonly (the choice is between READ and WRITE).
Closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/7093
It looks like for buffers `ResourceInterfaceVariable::is_written_to` might not detect write access. Do you know about this @spencer-lunarg ? My thinking was if we have `writeonly` then it's a reliable metric and should have higher priority comparing to acess detection that can produce produce false-positive, but it's still interesting to know if `is_written_to` can detect write as in the test WriteOnlyBufferWriteHazard.

layers: Report write access for writeonly resources

---

docs/gpu_validation.md
docs/khronos_validation_layer.md

I only deleted some documentation that I believe was duplicated.
I'll add somewhere that `VK_EXT_validation_features` is deprecated.

docs: Update layer configuration documentation

---

tests/framework/binding.cpp
tests/framework/binding.h
tests/framework/render.cpp
tests/framework/render.h

(redo of https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/7106)
`VkImageObj` is the last remaining object we have both in binding.cpp and render.cpp and it is a mess currently
This is a first step of cleaning it up by removing things that are not being used anymore to make the migration process a bit nicer

tests: Remove unused functions from VkImageObj

---

docs/synchronization_usage.md
layers/VkLayer_khronos_validation.json.in
layers/layer_options.cpp
layers/layer_options.h
layers/sync/sync_validation.cpp
layers/vulkan/generated/chassis.h
scripts/generators/layer_chassis_generator.py
tests/CMakeLists.txt
tests/framework/layer_validation_tests.h
tests/framework/queue_submit_context.cpp
tests/framework/queue_submit_context.h
tests/unit/sync_val.cpp
tests/unit/sync_val_positive.cpp

Set queue submit time sync validation to be on by default.
Add disable setting for those that want to turn it off for performance.
Fixes #7127

syncval: Set queue submit time sync val to default on

---

.gitignore
BUILD.gn
layers/CMakeLists.txt
layers/vulkan/generated/feature_requirements_helper.cpp
layers/vulkan/generated/feature_requirements_helper.h
layers/vulkan/generated/pnext_chain_extraction.cpp
layers/vulkan/generated/pnext_chain_extraction.h
scripts/generate_source.py
scripts/generators/feature_requirements.py
scripts/generators/pnext_chain_extraction_generator.py
tests/CMakeLists.txt
tests/framework/feature_requirements.cpp
tests/framework/feature_requirements.h
tests/framework/layer_validation_tests.h
tests/framework/render.cpp
tests/framework/render.h
tests/unit/ray_tracing.cpp
tests/unit/ray_tracing_gpu.cpp
tests/unit/ray_tracing_gpu_nv.cpp
tests/unit/ray_tracing_nv.cpp
tests/unit/ray_tracing_pipeline.cpp
tests/unit/ray_tracing_pipeline_nv.cpp
tests/unit/ray_tracing_pipeline_positive.cpp
tests/unit/ray_tracing_pipeline_positive_nv.cpp
tests/unit/ray_tracing_positive.cpp

Add `FeatureRequirements` Class to help specifying the features a test requires to be enabled, or sometimes disabled
Right now only used in ray tracing tests, where this class is quite handy given the feature requirements can vary quite a lot and writing the boilerplate to run a test if and only if a test has some feature enabled is cumbersome.
Also:
- enable back running some ray tracing tests on the mock ICD, because now it supports them
- split 2 or 3 tests that had an `if (some feature enabled) { code code code }` logic, moving the `code code code` part to a dedicated test asking for the feature to be enabled

tests: Add `FeatureRequirements` class

---

tests/unit/gpu_av_buffer_device_address.cpp
tests/unit/gpu_av_buffer_device_address_positive.cpp

Adds all the tests from `inst_buff_addr_check_test.cpp` in `spirv-opt` here to be tested as an end-to-end test for GPU-AV

tests: Add more GPU-AV BDA tests

---

layers/core_checks/cc_wsi.cpp
tests/unit/wsi.cpp

Resolves #5532 
Test originally authored @jeremyg-lunarg in #3650 
PR is a rebase of https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/6407 with permission from author

Add WSI semaphore pending VUs

---

tests/framework/render_pass_helper.cpp
tests/framework/render_pass_helper.h
tests/unit/android_external_resolve.cpp
tests/unit/android_external_resolve_positive.cpp
tests/unit/fragment_shading_rate.cpp
tests/unit/fragment_shading_rate_positive.cpp
tests/unit/imageless_framebuffer.cpp
tests/unit/multiview.cpp
tests/unit/render_pass.cpp
tests/unit/render_pass_positive.cpp

While trying to add more tests for https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/7141 I realize we need a `RenderPass2SingleSubpass` helper to more easily create render passes that need things extended
This adds `RenderPass2SingleSubpass` and populates many spots with it.. in process cleaned up some of the tests I touched

tests: Create RenderPass2SingleSubpass

---

.github/workflows/vvl.yml
scripts/common_ci.py
scripts/known_good.json

profiles no longer requires jsonschema as of
KhronosGroup/Vulkan-Profiles/pull/583
Furthermore with the exception of the codegen CI check we don't need to install pyparsing.

scripts: Cleanup pip usage

---

layers/state_tracker/fence_state.cpp
layers/state_tracker/fence_state.h
layers/state_tracker/semaphore_state.cpp
layers/state_tracker/semaphore_state.h
layers/state_tracker/state_tracker.cpp
tests/framework/binding.h
tests/unit/wsi_positive.cpp

Closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/12
The test implements and explains a scenario where image-acquire-fence can synchronize frames and guarantees that resources are not in use. Will repeat sync chain structure here too:
1) wait on the image acquire fence -> image was acquired
2) image was acquired -> image was presented in one of the previous frames
3) image was presented ->  corresponding present waited on the submit semaphore
4) submit semaphore was waited on -> corresponding submit finished execution and can be retired/reused

layers: Retire submissions using acquire fence

---

layers/core_checks/cc_drawdispatch.cpp
tests/unit/transform_feedback.cpp

the `counterOffset` and `vertexStride` must be a multiple of 4 (https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/6310) 
will be out in 1.3.274 spec update

layers: Add new vkCmdDrawIndirectByteCountEXT VUs

---

layers/core_checks/cc_synchronization.cpp
layers/sync/sync_vuid_maps.cpp
layers/sync/sync_vuid_maps.h
tests/unit/android_external_resolve.cpp
tests/unit/android_external_resolve_positive.cpp

for https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/7141
- fixes VUID labeling for `09374`
- Adds `09373`
- Confirms `04073` works with Color Resolve

layers: Add AHB External Resolve pipeline barrier checks

---

tests/unit/sync_val.cpp

Galaxy s23 is failing to create a `VkDevice` (but only sometimes :cry: ) for the sync val tests
this reverts the 3 cases from https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/7140/ that would likely be  a problem

tests: Revert sync_val dynamicRendering feature check

---

layers/state_tracker/state_tracker.cpp
tests/unit/vertex_input_positive.cpp

VK_KHR_vertex_attribute_divisor introduces nonZeroFirstInstance property that the EXT version doesn't have, but in the EXT version it is always assumed as supported

layers: Fix VK_EXT_vertex_attribute_divisor properties

---

layers/core_checks/cc_render_pass.cpp
layers/state_tracker/state_tracker.cpp
layers/state_tracker/state_tracker.h
tests/unit/android_external_resolve.cpp

closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/7141
adds
- VUID-VkFramebufferCreateInfo-nullColorAttachmentWithExternalFormatResolve-09349
- VUID-VkRenderPassBeginInfo-framebuffer-09353
- VUID-VkRenderingAttachmentInfo-resolveMode-09330

layers: Add Remaining VK_ANDROID_external_format_resolve

---

layers/state_tracker/state_tracker.cpp
layers/vulkan/generated/stateless_validation_helper.cpp
scripts/generators/stateless_validation_helper_generator.py
tests/unit/shader_spirv.cpp

closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/7188
- Adds the missing `VUID-VkShaderModuleCreateInfo-codeSize-01085` VUID
- Add test
- Don't create `spirv::Module` objects with ill-formed empty shader create info objects

layers: Check against zero codeSize

---

layers/core_checks/cc_device_memory.cpp
layers/core_checks/cc_queue.cpp
tests/unit/sparse_image.cpp
tests/unit/sparse_image_positive.cpp

Adds proper VUID tags for `VUID-VkSparseImageMemoryBindInfo-subresource-01722` and `VUID-VkSparseImageMemoryBindInfo-subresource-01723`

layers: Fix label for VkSparseImageMemoryBindInfo VUs

---

tests/CMakeLists.txt

Because testing is OFF by default. We don't need to handle all the different edge cases for package managers.
Testing should just use the static binaries by default. This avoids complications for Windows / Android APK testing.

cmake: Use SPIRV-Tools-static for testing

---

.github/workflows/vvl.yml

Remove redundant names
Conistently set ccache usage
Cleanup MinGW CI. Out of date comments / verbosity.

ci: Minor cleanup

---

layers/core_checks/cc_device_memory.cpp
layers/core_checks/core_validation.h
tests/unit/external_memory_sync.cpp

for https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/5431
Adds `VUID-VkImportMemoryFdInfoKHR-handleType-00667`

layers: Add external memory import support check

---

layers/error_message/logging.cpp
layers/layer_chassis_dispatch_manual.cpp
layers/object_tracker/object_lifetime_validation.h
layers/object_tracker/object_tracker_utils.cpp
layers/vulkan/generated/chassis.cpp
layers/vulkan/generated/layer_chassis_dispatch.cpp
layers/vulkan/generated/object_tracker.cpp
layers/vulkan/generated/vk_object_types.h
scripts/generators/base_generator.py
scripts/generators/layer_chassis_dispatch_generator.py
scripts/generators/layer_chassis_generator.py
scripts/generators/object_tracker_generator.py
scripts/generators/object_types_generator.py
tests/CMakeLists.txt
tests/framework/layer_validation_tests.h
tests/unit/others.cpp
tests/unit/tooling.cpp
tests/unit/tooling_positive.cpp

closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/6993
- the core `vkGetPhysicalDeviceToolProperties` was not implemented
- Add `VUID-vkSetPrivateData-objectHandle-04016`,  `VUID-vkSetPrivateData-objectHandle-04017`, `VUID-vkGetPrivateData-objectType-04018`
- Fix code gen problem where `VkDisplayKHR` and `VkDisplayModeKHR` were not viewed as instance based handles
- Move (and added) testing to `tooling`

Fix core vkGetPhysicalDeviceToolProperties and Private Date

---

layers/core_checks/cc_shader_object.cpp
layers/core_checks/cc_spirv.cpp
layers/core_checks/core_validation.h
layers/error_message/unimplementable_validation.h
tests/unit/shader_spirv.cpp

Adds missing `VkShaderModuleCreateInfo` VUs and gets logic ready for https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/7211

layers: Add missing VkShaderModuleCreateInfo VUs

---

layers/core_checks/cc_cmd_buffer.cpp
layers/core_checks/cc_image_layout.cpp
layers/gpu_validation/gpu_image_layout.cpp
layers/gpu_validation/gpu_state_tracker.cpp
layers/state_tracker/cmd_buffer_state.cpp
layers/state_tracker/cmd_buffer_state.h

Prevent a crash when an image is destroyed while still in use by a bindless descriptor. Using a non-smart vvl::Image pointer as a key in a map and also dereferencing it blindly isn't safe in this case.

gpu: Fix a race condition in image layout validation

---

layers/core_checks/cc_pipeline_graphics.cpp
tests/unit/graphics_library.cpp
tests/unit/graphics_library_positive.cpp

Adds
-  `VUID-VkGraphicsPipelineCreateInfo-flags-06612`
- `VUID-VkGraphicsPipelineCreateInfo-pLibraries-06613`
- `VUID-VkGraphicsPipelineCreateInfo-flags-06616`
- `VUID-VkGraphicsPipelineCreateInfo-pLibraries-06617`
- `VUID-VkGraphicsPipelineCreateInfo-flags-06679`
- `VUID-VkGraphicsPipelineCreateInfo-pLibraries-06681`
note: `VUID-VkGraphicsPipelineCreateInfo-flags-06680` should be removed from spec as it is the same as `VUID-VkGraphicsPipelineCreateInfo-flags-06679`

Add more GPL pipeline layout checks

---

tests/framework/ray_tracing_objects.cpp
tests/framework/ray_tracing_objects.h
tests/unit/ray_tracing.cpp
tests/unit/ray_tracing_positive.cpp

there is a missing `VUID-vkBuildAccelerationStructuresKHR-deferredOperation-03677` VUID but these tests prove that it is really just `VUID-vkBuildAccelerationStructuresKHR-deferredOperation-parameter` (plan to remove the `03677` from the spec)

tests: Confirm we test for valid VkDeferredOperationKHR object

---

layers/core_checks/cc_descriptor.cpp
layers/core_checks/core_validation.h

fixes `VUID-vkGetDescriptorEXT-dataSize-08125` and adds `VUID-vkGetDescriptorEXT-descriptorType-09469` (note VU wording was slightly fixed in https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/6378)

layers: Fix new vkGetDescriptorEXT VU

---

tests/framework/render.h
tests/framework/shader_helper.cpp
tests/framework/shader_helper.h
tests/framework/test_framework.h
tests/unit/debug_printf.cpp
tests/unit/gpu_av.cpp
tests/unit/gpu_av_descriptor_indexing.cpp
tests/unit/gpu_av_indirect_buffer.cpp
tests/unit/gpu_av_positive.cpp
tests/unit/parent.cpp
tests/unit/pipeline_topology_positive.cpp
tests/unit/protected_memory.cpp
tests/unit/shader_object.cpp
tests/unit/shader_object_positive.cpp
tests/unit/shader_spirv.cpp
tests/unit/shader_spirv_positive.cpp
tests/unit/transform_feedback.cpp

The `debug` was added to help debug the shaders writing tests for, but something like that is better served as a runtime setting, not a baked in compile value

Cleanup shader testing helper functions

---

tests/unit/ray_tracing.cpp
tests/unit/ray_tracing_pipeline.cpp
tests/unit/ray_tracing_pipeline_positive.cpp

- Makes use of the new `AddRequiredFeature`
- Removed some un-used features/extensions being added
- break up tests (mainly for `accelerationStructureHostCommands` to be a `Host` and `Device` test separately)

tests: Fix/cleanup Ray Tracing tests

---

layers/core_checks/cc_drawdispatch.cpp
tests/unit/descriptor_buffer.cpp
tests/unit/descriptor_buffer_positive.cpp
tests/unit/shader_object_positive.cpp

closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/7233
If anyone is using `vkCmdBindDescriptorBuffersEXT` with `vkCmdBindShadersEXT` we need to not try and look if the descriptor is used
Just like the Pipeline path, we have no system in play to track the descriptor buffers bound yet

layers: Fix ShaderObject with DescriptorBuffers

---

layers/vulkan/generated/chassis.cpp
layers/vulkan/generated/chassis.h
layers/vulkan/generated/chassis_dispatch_helper.h
scripts/generators/layer_chassis_generator.py

redo of https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/6533
@christophe-lunarg the issue was you didn't re-run the code gen before... there is no reason this should be sitting around to not get in

layers: Expose VK_EXT_layer_settings

---

tests/framework/ray_tracing_objects.cpp
tests/framework/ray_tracing_objects.h
tests/unit/descriptor_buffer.cpp
tests/unit/descriptors_positive.cpp
tests/unit/nvidia_best_practices.cpp
tests/unit/ray_tracing.cpp
tests/unit/ray_tracing_positive.cpp

This is consistent with `binding.h` and `vkt::rt::Pipeline` as well
the idea is we should only need to pass in the `vkt::Device` once at the creation time, from there it can be known/moved around where needed
when calling `BuildCmdBuffer` you already should know the `VkDevice` to be used at this point

tests: Pass vkt::Device at RTX object creation

---

layers/core_checks/cc_ray_tracing.cpp
layers/core_checks/core_validation.h
tests/framework/ray_tracing_objects.cpp
tests/framework/ray_tracing_objects.h
tests/unit/ray_tracing.cpp

part of https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/3792
**VUID-vkCmdBuildAccelerationStructuresKHR-pInfos-03813**
For any element of pInfos[i].pGeometries or pInfos[i].ppGeometries with a geometryType of VK_GEOMETRY_TYPE_INSTANCES_KHR, geometry.instances.data.deviceAddress must be a valid device address obtained from [vkGetBufferDeviceAddress](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkGetBufferDeviceAddress.html)
**VUID-vkCmdBuildAccelerationStructuresKHR-pInfos-03814**
For any element of pInfos[i].pGeometries or pInfos[i].ppGeometries with a geometryType of VK_GEOMETRY_TYPE_INSTANCES_KHR, if geometry.instances.data.deviceAddress is the address of a non-sparse buffer then it must be bound completely and contiguously to a single …

layers: Add 03813 03814

---

layers/object_tracker/object_tracker_utils.cpp
scripts/generators/extension_helper_generator.py
tests/unit/tooling.cpp

- Add new VUID label
- `VK_KHR_maintenance6` had an incorrect dependency that we had a temp fix for in the scripts

Additional updates for 275 headers

---

layers/stateless/sl_descriptor.cpp
layers/stateless/stateless_validation.h
layers/vulkan/generated/stateless_validation_helper.cpp
layers/vulkan/generated/stateless_validation_helper.h
scripts/generators/stateless_validation_helper_generator.py
tests/unit/descriptor_buffer.cpp

manually add missing `VkDescriptorGetInfoEXT` implicit VUs that aren't being covered by the codegen

Add missing implicit VkDescriptorGetInfoEXT

---

tests/unit/external_memory_sync_positive.cpp

On windows handle and handle2 would be the same, so closing it twice would throw an exception.

tests: Fix closing handles in external sync test

---

tests/unit/video.cpp

`VK_QUERY_TYPE_VIDEO_ENCODE_FEEDBACK_KHR` requires `VK_KHR_video_encode_queue`, so `encode_config` must be supported

tests: Fix support check in video test

---

layers/stateless/sl_pipeline.cpp
tests/unit/gpu_av_oob.cpp
tests/unit/graphics_library.cpp

`VUID-VkGraphicsPipelineCreateInfo-flags-06644` was shown to be a mistake and currently being taken out of the upcoming spec

layers: Remove GPL StageCount VU

---

layers/core_checks/cc_ray_tracing.cpp
tests/framework/ray_tracing_objects.cpp
tests/framework/ray_tracing_objects.h
tests/unit/ray_tracing.cpp

**VUID-vkCmdBuildAccelerationStructuresKHR-pInfos-03804**
For any element of pInfos[i].pGeometries or pInfos[i].ppGeometries with a geometryType of VK_GEOMETRY_TYPE_TRIANGLES_KHR, geometry.triangles.vertexData.deviceAddress must be a valid device address obtained from [vkGetBufferDeviceAddress](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkGetBufferDeviceAddress.html)
**VUID-vkCmdBuildAccelerationStructuresKHR-pInfos-03805**
For any element of pInfos[i].pGeometries or pInfos[i].ppGeometries with a geometryType of VK_GEOMETRY_TYPE_TRIANGLES_KHR, if geometry.triangles.vertexData.deviceAddress is the address of a non-sparse buffer then it must be bound completely and contiguously to a single …

layers: Add 03804 03805

---

layers/core_checks/cc_buffer.cpp
layers/core_checks/cc_descriptor.cpp
layers/core_checks/core_validation.h
tests/device_profiles/max_profile.json
tests/unit/descriptor_buffer.cpp

closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/6027
adds
- `VUID-VkDescriptorGetInfoEXT-type-09427`
- `VUID-VkDescriptorGetInfoEXT-type-09428`
these are similar to VUs like `VUID-VkBufferViewCreateInfo-range-00930`
while here cleaned up the function as there were a few bugs

layers: Add maxTexelBufferElements for decriptor buffers

---

layers/core_checks/cc_ray_tracing.cpp
tests/framework/ray_tracing_objects.cpp
tests/framework/ray_tracing_objects.h
tests/unit/ray_tracing.cpp

part of https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/3792
**VUID-vkCmdBuildAccelerationStructuresKHR-pInfos-03806**
For any element of pInfos[i].pGeometries or pInfos[i].ppGeometries with a geometryType of VK_GEOMETRY_TYPE_TRIANGLES_KHR, if geometry.triangles.indexType is not VK_INDEX_TYPE_NONE_KHR, geometry.triangles.indexData.deviceAddress must be a valid device address obtained from [vkGetBufferDeviceAddress](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkGetBufferDeviceAddress.html)
**VUID-vkCmdBuildAccelerationStructuresKHR-pInfos-03807**
For any element of pInfos[i].pGeometries or pInfos[i].ppGeometries with a geometryType of VK_GEOMETRY_TYPE_TRIANGLES_KHR, if geometry.triangles.indexType is not VK_INDEX_TYPE_NONE_KHR, if …

layers: Add 03806 03807 03712

---

layers/core_checks/cc_ray_tracing.cpp
layers/core_checks/core_validation.h
layers/stateless/sl_ray_tracing.cpp
tests/framework/ray_tracing_objects.cpp
tests/framework/ray_tracing_objects.h
tests/unit/ray_tracing.cpp

**VUID-vkCmdBuildAccelerationStructuresKHR-pInfos-03675**
For each pInfos[i], dstAccelerationStructure must have been created with a value of [VkAccelerationStructureCreateInfoKHR](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkAccelerationStructureCreateInfoKHR.html)::size greater than or equal to the memory size required by the build operation, as returned by [vkGetAccelerationStructureBuildSizesKHR](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkGetAccelerationStructureBuildSizesKHR.html) with pBuildInfo = pInfos[i] and with each element of the pMaxPrimitiveCounts array greater than or equal to the equivalent ppBuildRangeInfos[i][j].primitiveCount values for j in …

layers: Add 03675 03676

---

layers/state_tracker/video_session_state.cpp
scripts/known_good.json
tests/device_profiles/max_profile.json

I noticed that despite the recent MockICD updates that enable the video related VVL test cases to run against MockICD, the tests still don't run on the CI.
The reason is that there are no profile-less runs, so there was a need to update the max profile to have everything in place for this to work. This also uncovered a Vulkan-Profiles bug that I've fixed here: https://github.com/KhronosGroup/Vulkan-Profiles/pull/591
With these changes there really should be 100% test coverage of video using MockICD + Profiles, not just using MockICD alone.
UPDATE: Apparently this also uncovered a bug that did not show up on our CI, despite having address sanitizer enabled (likely a non-deterministic issue), but did show up here on the github CI, so this change fixes that too.

tests: Device profile updates for video

---

layers/core_checks/cc_buffer_address.h
layers/core_checks/cc_device_memory.cpp
layers/core_checks/cc_ray_tracing.cpp
tests/unit/ray_tracing.cpp

part of https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/3792
**VUID-vkCmdBuildAccelerationStructuresKHR-pInfos-03808**
For any element of pInfos[i].pGeometries or pInfos[i].ppGeometries with a geometryType of VK_GEOMETRY_TYPE_TRIANGLES_KHR, if geometry.triangles.transformData.deviceAddress is not 0, it must be a valid device address obtained from [vkGetBufferDeviceAddress](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkGetBufferDeviceAddress.html)
**VUID-vkCmdBuildAccelerationStructuresKHR-pInfos-03809**
For any element of pInfos[i].pGeometries or pInfos[i].ppGeometries with a geometryType of VK_GEOMETRY_TYPE_TRIANGLES_KHR, if geometry.triangles.transformData.deviceAddress is the address of a non-sparse buffer then it must be bound completely and …

layers: Add 03808 03809

---

layers/sync/sync_commandbuffer.cpp
layers/sync/sync_commandbuffer.h
layers/sync/sync_validation.cpp
layers/sync/sync_validation.h
tests/unit/sync_val.cpp

This reports debug regions (defined by `vkCmdBeginDebugUtilsLabelEXT` and `vkCmdEndDebugUtilsLabelEXT`) where hazardous accesses happen.
For submit time validation the debug region is reported for the prior access and also for the current access (from practical side the
most interesting is the location of the prior access).
Error message as reported by record time validation:
> Validation Error: [ SYNC-HAZARD-WRITE-AFTER-READ ] Object 0: handle = 0xfa21a40000000003, type = VK_OBJECT_TYPE_BUFFER; | MessageID = 0x376bc9df | vkCmdCopyBuffer():  Hazard WRITE_AFTER_READ for dstBuffer VkBuffer 0xfa21a40000000003[], region 0. Access info (usage: SYNC_COPY_TRANSFER_WRITE, prior_usage: SYNC_COPY_TRANSFER_READ, read_barriers: VkPipelineStageFlags2(0), command: vkCmdCopyBuffer, seq_no: 1, reset_no: …

sync: Report debug region name

---

layers/containers/custom_containers.h
layers/sync/sync_access_state.cpp

The typo in the loop was not discovered because after running for 256 iterations the loop terminated due to uint8_t wrap around. Using uint32_t makes similar issues more noticeable.
We always had this typo. Not sure which scenarios this could affect, but as the first step this should be fixed.
Not the first issue with uint8_t we encountered, so start using uint32_t as default size type for small_vector. This does not affect the final size of the container due to alignment gaps. For specific case of small_vector<ResourceFirstAccess, 3> it's 96 bytes both for uint8_t and uint32_t size type parameterization.

sync: Fix loop and stop using uint8_t as size type

---

layers/core_checks/cc_cmd_buffer_dynamic.cpp
layers/core_checks/cc_shader_interface.cpp
layers/drawdispatch/drawdispatch_vuids.cpp
layers/drawdispatch/drawdispatch_vuids.h
layers/state_tracker/shader_module.cpp
tests/device_profiles/max_profile.json
tests/unit/dynamic_state.cpp
tests/unit/dynamic_state_positive.cpp
tests/unit/shader_object.cpp
tests/unit/shader_object_positive.cpp
tests/unit/vertex_input.cpp

- Adds the missing `VUID-vkCmdDraw-Input-08734`
- Improve error messages 
- Unify the logic for the Pipeline and DynamicState/ShaderObject version of vertex input checking (since they are the same)

layers: Add vertex type check for dynamic vert input

---

layers/core_checks/cc_drawdispatch.cpp
layers/core_checks/cc_ray_tracing.cpp
layers/core_checks/core_validation.h
layers/drawdispatch/drawdispatch_vuids.cpp
layers/drawdispatch/drawdispatch_vuids.h
tests/unit/protected_memory.cpp

1. adds the some missing VUs to check for protected command buffers
- VUID-vkCmdDraw-commandBuffer-04617
- VUID-vkCmdDrawIndexed-commandBuffer-04617
- VUID-vkCmdDrawMultiEXT-commandBuffer-04617
- VUID-vkCmdDrawMultiIndexedEXT-commandBuffer-04617
- VUID-vkCmdDispatch-commandBuffer-04617
- VUID-vkCmdDispatchBase-commandBuffer-04617
- VUID-vkCmdBuildAccelerationStructuresIndirectKHR-commandBuffer-03649
2. Clean up code also dealing with protected command buffers around ray tracing

layers: Fix Protected Ray Query checks

---

layers/core_checks/cc_buffer_address.h
layers/core_checks/cc_descriptor.cpp
layers/core_checks/cc_ray_tracing.cpp

A number of VU states something along the lines of "non sparse buffers accessed through a device address must be bound to memory" The current error message was not taking advantage of the error message generation in BufferAddressValidation, it now does
Then:
>Validation Error: [ VUID-vkCmdBindDescriptorBuffersEXT-pBindingInfos-08052 ] Object 0: handle = 0x204b7943830, type = VK_OBJECT_TYPE_COMMAND_BUFFER; Object 1: handle = 0x9fde6b0000000014, type = VK_OBJECT_TYPE_BUFFER; | MessageID = 0x17e3f381 | vkCmdBindDescriptorBuffersEXT(): pBindingInfos[0].address (VkBuffer 0x9fde6b0000000014[]) used with no memory bound and previously bound memory was freed. Memory must not be freed prior to this operation.
Now:
>Validation Error: [ VUID-vkCmdBindDescriptorBuffersEXT-pBindingInfos-08052 ] Object …

layers: Improve buffer address validation messages

---

layers/stateless/sl_pipeline.cpp
layers/stateless/sl_utils.cpp
layers/vulkan/generated/stateless_validation_helper.cpp
layers/vulkan/generated/stateless_validation_helper.h
scripts/generators/stateless_validation_helper_generator.py
tests/unit/pipeline.cpp
tests/unit/pipeline_topology.cpp

somehow the `VkPipelineRasterizationStateCreateInfo` implicit VUs were not added in https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/6824

layers: Add missing implicit RasterizationStateCreateInfo

---

tests/framework/shader_templates.h
tests/unit/dynamic_rendering.cpp
tests/unit/dynamic_rendering_positive.cpp
tests/unit/sync_val_positive.cpp

There are 2 tests that use subpass input attachments, but seems a lot of dynamic rendering tests were just using them as a side effect of the tests being copy-and-pasted
also removed `kFragmentColorOutputGlsl` as it is the same as `kFragmentMinimalGlsl`

tests: Remove unused items from DynamicRendering

---

layers/core_checks/cc_ray_tracing.cpp
layers/stateless/sl_ray_tracing.cpp
tests/unit/ray_tracing.cpp

Some ray tracing cleanups:
- move index buffer alignment check to stateless
- propagate the small refacto of BufferAddressValidation

layers: RT validation cleanups

---

layers/core_checks/cc_descriptor.cpp
layers/core_checks/cc_ray_tracing.cpp
tests/device_profiles/max_profile.json
tests/unit/ray_tracing.cpp

**VUID-VkAccelerationStructureGeometryTrianglesDataKHR-vertexFormat-03797**
The [format features](https://registry.khronos.org/vulkan/specs/1.3-extensions/html/vkspec.html#resources-buffer-view-format-features) of vertexFormat must contain VK_FORMAT_FEATURE_ACCELERATION_STRUCTURE_VERTEX_BUFFER_BIT_KHR
**VUID-vkCmdBuildAccelerationStructuresKHR-pInfos-03711**
For any element of pInfos[i].pGeometries or pInfos[i].ppGeometries with a geometryType of VK_GEOMETRY_TYPE_TRIANGLES_KHR, geometry.triangles.vertexData.deviceAddress must be aligned to the size in bytes of the smallest component of the format in vertexFormat
**VUID-VkAccelerationStructureGeometryTrianglesDataKHR-vertexStride-03735**
vertexStride must be a …

layers: Add 03797 03711 03735

---

tests/framework/render.cpp
tests/framework/render.h
tests/unit/amd_best_practices.cpp
tests/unit/arm_best_practices.cpp
tests/unit/best_practices.cpp
tests/unit/image_positive.cpp
tests/unit/parent.cpp
tests/unit/sync_object_positive.cpp
tests/unit/sync_val.cpp
tests/unit/sync_val_positive.cpp
tests/unit/wsi.cpp
tests/unit/wsi_positive.cpp

Cleanup for WSI tests to use the new `RETURN_IF_SKIP` to detect if the swapchain/surface failed to create

test: Add RETURN_IF_SKIP for Wsi

---

layers/core_checks/cc_ray_tracing.cpp
tests/framework/ray_tracing_objects.cpp
tests/framework/ray_tracing_objects.h
tests/unit/ray_tracing.cpp

part of https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/3792
**VUID-vkCmdBuildAccelerationStructuresKHR-pInfos-03811**
For any element of pInfos[i].pGeometries or pInfos[i].ppGeometries with a geometryType of VK_GEOMETRY_TYPE_AABBS_KHR, geometry.aabbs.data.deviceAddress must be a valid device address obtained from [vkGetBufferDeviceAddress](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkGetBufferDeviceAddress.html)
**VUID-vkCmdBuildAccelerationStructuresKHR-pInfos-03812**
For any element of pInfos[i].pGeometries or pInfos[i].ppGeometries with a geometryType of VK_GEOMETRY_TYPE_AABBS_KHR, if geometry.aabbs.data.deviceAddress is the address of a non-sparse buffer then it must be bound completely and contiguously to a single …

layers: Add 03811 03812

---

layers/layer_chassis_dispatch_manual.cpp
layers/vulkan/generated/layer_chassis_dispatch.cpp
scripts/generators/layer_chassis_dispatch_generator.py

The following commands don't "create" a handle, but rather return a handle the driver is managing:
vkGetWinrtDisplayNV
vkGetRandROutputDisplayEXT
vkGetDrmDisplayEXT

layers: Fix wrapping of returned driver managed VkDisplayKHR handles

---

tests/unit/ray_tracing_positive.cpp

It was crashing on AMD 780M, for valid reasons: missing extensions

tests: Fix GetAccelStructsBuildSizes

---

layers/core_checks/cc_ray_tracing.cpp

In the context of buffer device address validation, a mix of hex and non hex output was used for addresses. Move everything to hex values.

layers: Output device addresses as hex values

---

layers/core_checks/cc_image.cpp
layers/core_checks/cc_video.cpp
layers/core_checks/core_validation.h
layers/gpu_validation/gpu_error_message.cpp
layers/gpu_validation/gpu_image_layout.cpp
layers/state_tracker/video_session_state.cpp
layers/state_tracker/video_session_state.h
layers/vulkan/generated/chassis.h
scripts/generators/layer_chassis_generator.py

Removes the old `LogError` so everyone now **must** provide a `Location` when they create an error message

layers: Remove deprecated logError

---

layers/stateless/sl_utils.cpp
layers/vulkan/generated/stateless_validation_helper.cpp
scripts/generators/stateless_validation_helper_generator.py
tests/framework/video_objects.h
tests/unit/descriptor_buffer.cpp
tests/unit/device_queue.cpp
tests/unit/dynamic_rendering.cpp
tests/unit/dynamic_rendering_positive.cpp
tests/unit/dynamic_state.cpp
tests/unit/fragment_shading_rate.cpp
tests/unit/gpu_av.cpp
tests/unit/gpu_av_oob_positive.cpp
tests/unit/gpu_av_positive.cpp
tests/unit/mesh.cpp
tests/unit/other_positive.cpp
tests/unit/others.cpp
tests/unit/ray_tracing.cpp
tests/unit/ray_tracing_pipeline_nv.cpp
tests/unit/ray_tracing_positive.cpp
tests/unit/shader_object_positive.cpp
tests/unit/shader_spirv.cpp
tests/unit/sync_object.cpp
tests/unit/viewport_inheritance.cpp

closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/7189
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/7262
When including a feature structure at `vkCreateDevice` time, add logic to validate the corresponding extension is included too

layers: Check extensions are with features structs

---

layers/core_checks/cc_descriptor.cpp
layers/stateless/sl_cmd_buffer.cpp
tests/unit/command.cpp
tests/unit/descriptors.cpp

`VK_NV_per_stage_descriptor_set` lets you do dynamic pipeline layout (`dynamicPipelineLayout`) and so check was moved from implicit to explicit
- VUID-VkBindDescriptorBufferEmbeddedSamplersInfoEXT-layout-09496
- VUID-VkBindDescriptorSetsInfoKHR-layout-09496
- VUID-VkSetDescriptorBufferOffsetsInfoEXT-layout-09496
- VUID-VkPushConstantsInfoKHR-layout-09496
- VUID-VkPushDescriptorSetInfoKHR-layout-09496
- VUID-VkPushDescriptorSetWithTemplateInfoKHR-layout-09496

layers: Add Null Layout check

---

layers/object_tracker/object_tracker_utils.cpp
layers/vulkan/generated/object_tracker.cpp
layers/vulkan/generated/object_tracker.h
layers/vulkan/generated/vk_object_types.h
scripts/generators/object_tracker_generator.py
scripts/generators/object_types_generator.py
tests/unit/debug_extensions.cpp

`VK_EXT_debug_marker` is old and deprecated, but it had 6 simple VUs better to add then keep forever un-done
- VUID-VkDebugMarkerObjectNameInfoEXT-object-01491
- VUID-VkDebugMarkerObjectNameInfoEXT-object-01492
- VUID-VkDebugMarkerObjectNameInfoEXT-objectType-01490
- VUID-VkDebugMarkerObjectTagInfoEXT-object-01494
- VUID-VkDebugMarkerObjectTagInfoEXT-object-01495
- VUID-VkDebugMarkerObjectTagInfoEXT-objectType-01493

layers: Add VK_EXT_debug_marker

---

layers/core_checks/cc_cmd_buffer.cpp
layers/core_checks/cc_queue.cpp
layers/state_tracker/cmd_buffer_state.cpp
layers/state_tracker/cmd_buffer_state.h
layers/state_tracker/queue_state.h
tests/unit/command.cpp
tests/unit/command_positive.cpp
tests/unit/debug_extensions.cpp
tests/unit/debug_extensions_positive.cpp

The validation of labels in the primary command buffer happens on the queue level because debug regions can cross command buffer boundaries. Validation should be done at submit time.
This is more complicated comparing to a similar VU for a secondary command buffer where debug regions are not allowed to cross command buffer boundaries.
Error messages:
> Validation Error: [ VUID-vkCmdEndDebugUtilsLabelEXT-commandBuffer-01912 ] Object 0: handle = 0x20800790df0, type = VK_OBJECT_TYPE_COMMAND_BUFFER; | MessageID = 0x56146426 | vkQueueSubmit(): pSubmits[0].pCommandBuffers[0] (VkCommandBuffer 0x20800790df0[]) contains vkCmdEndDebugUtilsLabelEXT that does not have a matching vkCmdBeginDebugUtilsLabelEXT in this or one of the previously submitted command buffers. There are no previous debug …

layers: Add debug label tracking VU 01912

---

layers/core_checks/cc_ray_tracing.cpp
tests/unit/ray_tracing.cpp

**VUID-vkCmdBuildAccelerationStructuresKHR-primitiveCount-03769**
For each element of pInfos, if its mode member is VK_BUILD_ACCELERATION_STRUCTURE_MODE_UPDATE_KHR, then for each VkAccelerationStructureGeometryKHR structure referred to by its pGeometries or ppGeometries members, the primitiveCount member of its corresponding VkAccelerationStructureBuildRangeInfoKHR structure must have the same value which was specified when srcAccelerationStructure was last built

layers: Add 03769

---

tests/unit/android_hardware_buffer.cpp
tests/unit/android_hardware_buffer_positive.cpp
tests/unit/buffer.cpp
tests/unit/command.cpp
tests/unit/command_positive.cpp
tests/unit/debug_extensions.cpp
tests/unit/descriptor_buffer.cpp
tests/unit/descriptors.cpp
tests/unit/external_memory_sync.cpp
tests/unit/external_memory_sync_positive.cpp
tests/unit/image_positive.cpp
tests/unit/memory.cpp
tests/unit/memory_positive.cpp
tests/unit/mesh.cpp
tests/unit/object_lifetime.cpp
tests/unit/parent.cpp
tests/unit/protected_memory.cpp
tests/unit/ray_tracing.cpp
tests/unit/ray_tracing_gpu.cpp
tests/unit/ray_tracing_nv.cpp
tests/unit/ray_tracing_positive.cpp
tests/unit/sparse_buffer.cpp
tests/unit/sparse_buffer_positive.cpp
tests/unit/sparse_image.cpp
tests/unit/threading_positive.cpp
tests/unit/transform_feedback.cpp
tests/unit/video.cpp
tests/unit/video_positive.cpp
tests/unit/wsi_positive.cpp

- Make use of the `vkt::no_mem` in `vkt::Buffer`
- Realized some places were using `DeviceObj()` instead of just the `m_device` and made it all consistent

tests: Use vkt::no_mem

---

layers/error_message/unimplementable_validation.h
layers/stateless/sl_wsi.cpp
layers/sync/sync_utils.cpp
layers/sync/sync_vuid_maps.cpp
scripts/vk_validation_stats.py

- Fixes small typo from previous PR
- Adds VUID labels for vendor checks we are already doing (due to generating the sync val) and just needs a label
- Add few more `unimplementable_validation.h` VUIDs

layers: Labeling VUs already being validated

---

scripts/update_deps.py

After we switched from using subprocess.Popen() to subprocess.run() for command execution in commit bdc0ce89d388155124095b3b4f090574d2d843ea, we became sensitive to non-ASCII characters being emitted to the Windows console, which can happen if a developer tries to use update_deps.py() when their Windows console is set to use a non-ASCII or non-UTF code page.
See:
Can't update dependencies on Windows due to encoding problems
https://gitlab.khronos.org/vulkan/Vulkan-ValidationLayers/-/issues/34
One fix here is to specify the Windows-only "oem" encoding by passing:
encoding='oem'
to subprocess.run(); but this won't work on non-windows platforms.  The easier and more universal fix is to pass:
errors='replace'
to subprocess.run(), which will cause any encoding errors (that would normally cause …

scripts: fix international Windows update_deps

---

layers/gpu_validation/gpu_setup.cpp
layers/gpu_validation/gpu_subclasses.cpp
layers/gpu_validation/gpu_subclasses.h
layers/gpu_validation/gpu_validation.h
layers/state_tracker/ray_tracing_state.h
layers/state_tracker/state_tracker.cpp
layers/state_tracker/state_tracker.h

Closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/7325
If the underlying buffer is not bound to memory, do not try to call vkGetAccelerationStructureDeviceAddressKHR

layers: Fix accel struct device address recording

---

layers/stateless/sl_wsi.cpp
layers/stateless/stateless_validation.h
layers/vulkan/generated/stateless_validation_helper.cpp
scripts/generators/stateless_validation_helper_generator.py

This is a very basic WSI check we have for the other WSI platforms, but seem to have bypassed the Android one

layers: Add Android Surface creation check

---

layers/core_checks/cc_ray_tracing.cpp
layers/stateless/sl_ray_tracing.cpp
layers/stateless/stateless_validation.h
layers/utils/ray_tracing_utils.cpp
layers/utils/ray_tracing_utils.h
tests/framework/ray_tracing_objects.cpp
tests/framework/ray_tracing_objects.h
tests/unit/ray_tracing.cpp

Part of https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/3792 
**VUID-vkCmdBuildAccelerationStructuresKHR-pInfos-03801**
For each element of pInfos[i].pGeometries or pInfos[i].ppGeometries with a geometryType of VK_GEOMETRY_TYPE_INSTANCES_KHR, the corresponding ppBuildRangeInfos[i][j].primitiveCount must be less than or equal to [VkPhysicalDeviceAccelerationStructurePropertiesKHR](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkPhysicalDeviceAccelerationStructurePropertiesKHR.html)::maxInstanceCount
A test is not really feasible, the logic to add it would imply creating potentially enormous buffers
Also cleaned/refactored stuff in stateless ray tracing validation, especially the divergence we had for validating `pGeometries` and `ppGeometries` pointers …

layers: Add 03801, cleanup RT stateless validation

---

layers/core_checks/cc_synchronization.cpp
tests/unit/sync_object.cpp

these VUs were discussed in https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/6326
- `VUID-vkSetEvent-event-09543` came out in the 276 spec

layers: Label QueueForwardProgress VUs

---

layers/gpu_validation/gpu_setup.cpp
layers/gpu_validation/gpu_validation.cpp
layers/gpu_validation/gpu_validation.h

adds a `VK_LAYER_GPUAV_DEBUG_DUMP_INSTRUMENTED_SHADERS` 
also organizes GPU-AV Debug settings we might want to add to later

gpuav: Add debug env variable for shaders

---

layers/best_practices/best_practices_error_enums.h
scripts/vk_validation_stats.py
tests/unit/amd_best_practices.cpp
tests/unit/arm_best_practices.cpp
tests/unit/best_practices.cpp
tests/unit/nvidia_best_practices.cpp
tests/unit/video.cpp

There is no reason to have `UNASSIGNED` to all the Best Practice labels... they will never be assigned, it is just cluttering and only there because the first one had it and everyone just copied-and-pasted the rest

bp: Remove UNASSIGNED from BP

---

layers/core_checks/cc_spirv.cpp

This had me stumped for a little bit and I was *sure* the validation layers couldn't be lying to me but here we are :)

layers: Correcting check for vertexPipelineStoresAndAtomics

---

layers/error_message/unimplementable_validation.h

These VUs were fixed in https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/6392 as they were from "returned only" structs

layers: Update VUIDs removed from 276

---

layers/error_message/unimplementable_validation.h

closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/6734
realized these VUs have not been validated as there is no real way for us to do it

layers: Pipeline Cache VUs

---

layers/core_checks/cc_cmd_buffer.cpp
layers/core_checks/cc_queue.cpp
layers/core_checks/core_validation.h
layers/state_tracker/cmd_buffer_state.cpp
layers/state_tracker/cmd_buffer_state.h
layers/state_tracker/queue_state.h
layers/state_tracker/state_tracker.cpp
layers/state_tracker/state_tracker.h
layers/sync/sync_commandbuffer.cpp
layers/sync/sync_commandbuffer.h
layers/sync/sync_submit.cpp
layers/sync/sync_submit.h
layers/sync/sync_validation.cpp
layers/sync/sync_validation.h
tests/unit/sync_val.cpp

Previous sync validation label tracking assumed (incorrectly) that primary command buffer label commands (begin/end) are balanced. This PR implements proper label tracking as per-queue state. Reports debug labels both for prior and current access. Supports record time and submit time reporting.
Both primary and secondary command buffers are supported. Some of label tracking functionality from core validation was moved to state tracker to use in sync validation too. Added more tests and made sure it properly handles debug markers in UE5 engine as an example of non-trivial frame structure.
Only `VK_EXT_debug_utils` is supported and `VK_EXT_debug_marker` (deprecated) is not supported. For the Source engine  `-vulkan_force_enable_debug_utils` option should be used.
Closes …

sync: Rework debug region reporting

---

layers/core_checks/cc_pipeline_graphics.cpp
layers/stateless/sl_pipeline.cpp
layers/stateless/stateless_validation.h
tests/unit/dynamic_rendering.cpp
tests/unit/graphics_library.cpp
tests/unit/pipeline.cpp
tests/unit/pipeline_positive.cpp

Fixes VUs for `VK_EXT_rasterization_order_attachment_access` to check if `VkRenderPass` is null or not (now that there is `VK_KHR_dynamic_rendering_local_read`)
Also some VUID label churn
Lastly, tried moving some stuff out of the monolithic  `manual_PreCallValidateCreateGraphicsPipelines`

layers: Fix rasterizationOrderAttachmentAccess

---

layers/core_checks/cc_descriptor.cpp
tests/unit/descriptor_buffer.cpp

Was discussed in https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/6431
`pCombinedImageSampler` can't be null (when using `VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER`)

layers: Fix Null CombinedImageSampler

---

layers/core_checks/cc_pipeline_graphics.cpp
layers/core_checks/core_validation.h
layers/vulkan/generated/object_tracker.cpp
scripts/generators/object_tracker_generator.py
tests/unit/best_practices.cpp
tests/unit/dynamic_rendering.cpp
tests/unit/graphics_library.cpp
tests/unit/graphics_library_positive.cpp
tests/unit/memory.cpp
tests/unit/parent.cpp
tests/unit/pipeline.cpp
tests/unit/protected_memory.cpp

This adds `VUID-VkGraphicsPipelineCreateInfo-flags-06643` and `VUID-VkGraphicsPipelineCreateInfo-layout-06602`
In the process I found that the object tracker currently has some issue, spec issues were raised for them

layers: Fix GPL RenderPass/Layout check

---

docs/fine_grained_locking.md
layers/best_practices/bp_drawdispatch.cpp
layers/best_practices/bp_framebuffer.cpp
layers/best_practices/bp_render_pass.cpp
layers/best_practices/bp_synchronization.cpp
layers/core_checks/cc_cmd_buffer_dynamic.cpp
layers/core_checks/cc_copy_blit_resolve.cpp
layers/core_checks/cc_device.cpp
layers/core_checks/cc_device_memory.cpp
layers/core_checks/cc_drawdispatch.cpp
layers/core_checks/cc_image.cpp
layers/core_checks/cc_query.cpp
layers/core_checks/cc_queue.cpp
layers/core_checks/cc_ray_tracing.cpp
layers/core_checks/cc_render_pass.cpp
layers/core_checks/cc_synchronization.cpp
layers/drawdispatch/descriptor_validator.cpp
layers/stateless/sl_ray_tracing.cpp
layers/stateless/sl_render_pass.cpp
layers/sync/sync_commandbuffer.cpp
layers/sync/sync_op.cpp
layers/sync/sync_submit.cpp
layers/sync/sync_validation.cpp
tests/unit/image.cpp
tests/unit/image_positive.cpp
tests/unit/memory.cpp

I was trying to cleanup the Device Group tests, there I found a bug because we went `skip = ValidateSomething();` instead of `skip |=`
I have found sometimes we move around code and having `|=` everywhere is a good counter measure for future code refactoring

Cleanup of tests and add |= to skip 

---

layers/best_practices/bp_drawdispatch.cpp
layers/best_practices/bp_render_pass.cpp
layers/core_checks/cc_cmd_buffer_dynamic.cpp
layers/core_checks/cc_pipeline_graphics.cpp
layers/state_tracker/cmd_buffer_state.h
layers/state_tracker/pipeline_state.cpp
layers/stateless/sl_cmd_buffer.cpp
layers/stateless/sl_cmd_buffer_dynamic.cpp
layers/stateless/sl_pipeline.cpp
layers/sync/sync_renderpass.cpp
layers/utils/vk_layer_utils.h
tests/framework/pipeline_helper.cpp
tests/framework/pipeline_helper.h
tests/unit/buffer.cpp
tests/unit/dynamic_state.cpp
tests/unit/pipeline.cpp
tests/unit/ray_tracing.cpp
tests/unit/shader_object.cpp
tests/unit/sync_val.cpp
tests/unit/sync_val_positive.cpp

- VK_KHR_index_type_uint8
- VK_KHR_load_store_op_none
- VK_KHR_line_rasterization
were promoted from EXT, this updates the various spots using their alias values (That make sense)

layers: Update promoted KHR names

---

tests/unit/sync_val.cpp

This workarounds CI failures according to the statistic I gathered so far.
Manual feature initialization: no failures in 7-8 runs. 
Automatic feature initialization 3 failures in 5 runs.
~~Still I feel it could be luck and the reason is different, but so far good data to test this version.~~
More testing suggest this PR correctly determines the area that causes the issue.
I don't know details of automatic feature implementation but if it can enable *other* features in addition to requested ones then it can enable a feature that is not very stable for specific device/driver (Arno hopefully can clarify details).
The failures happen only on GalaxyS23Ultra Android CI.
@arno-lunarg

CI fix: Try manual feature init

---

tests/unit/instance_positive.cpp

Initialization is not required in this test and in the profiles repository had a similar test that only failed if an instance was not created before calling `vkEnumerateInstanceExtensionProperties`

tests: Remove init from instance extensions test

---

layers/core_checks/cc_pipeline_graphics.cpp
layers/core_checks/cc_spirv.cpp
layers/core_checks/cc_synchronization.cpp
layers/sync/sync_vuid_maps.cpp
tests/unit/dynamic_rendering.cpp

This fixes the "if feature is not enabled" VUs for `VK_KHR_dynamic_rendering_local_read` 
Full support is still needed
also `VUID-vkCmdPipelineBarrier2-None-08719` is still old, but needs fixing up since it was split into 3 different VUs

layer: Fix VUID labeling from dynamic_rendering_local_read

---

layers/best_practices/best_practices_validation.h
layers/best_practices/bp_pipeline.cpp
layers/containers/custom_containers.h
layers/state_tracker/pipeline_state.cpp
layers/state_tracker/pipeline_state.h
layers/state_tracker/state_tracker.cpp
layers/state_tracker/state_tracker.h

This change adds infrastructure that enables loading shader module data from pipeline caches.
Currently, this is intended to be used by the Vulkan SC validation layers, but it is general enough that it could be leveraged in the Vulkan validation layers too, if the need arises in the future.

layers: Support loading shader modules from pipeline caches

---

layers/core_checks/cc_ray_tracing.cpp
layers/stateless/sl_ray_tracing.cpp
tests/unit/ray_tracing.cpp

Closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/7230 (was missing extensions)
VUID-vkWriteAccelerationStructuresPropertiesKHR-pAccelerationStructures-04964
All acceleration structures in pAccelerationStructures must have been built prior to the execution of this command
VUID-vkWriteAccelerationStructuresPropertiesKHR-queryType-03449
If queryType is VK_QUERY_TYPE_ACCELERATION_STRUCTURE_COMPACTED_SIZE_KHR, then pData must point to a VkDeviceSize
VUID-vkWriteAccelerationStructuresPropertiesKHR-queryType-03451
If queryType is VK_QUERY_TYPE_ACCELERATION_STRUCTURE_SERIALIZATION_SIZE_KHR, then pData must point to a VkDeviceSize
VUID-vkWriteAccelerationStructuresPropertiesKHR-queryType-06732
If …

layers: Add 04964 03449 03451 06732 06734

---

layers/core_checks/cc_ray_tracing.cpp
layers/core_checks/core_validation.h
tests/framework/ray_tracing_objects.cpp
tests/framework/ray_tracing_objects.h
tests/unit/ray_tracing.cpp

VUID-vkGetAccelerationStructureDeviceAddressKHR-accelerationStructure-08935
The [VkPhysicalDeviceAccelerationStructureFeaturesKHR::accelerationStructure](https://registry.khronos.org/vulkan/specs/1.3-extensions/html/vkspec.html#features-accelerationStructure) feature must be enabled
VUID-vkGetAccelerationStructureDeviceAddressKHR-device-03504
If device was created with multiple physical devices, then the [bufferDeviceAddressMultiDevice](https://registry.khronos.org/vulkan/specs/1.3-extensions/html/vkspec.html#features-bufferDeviceAddressMultiDevice) feature must be enabled
VUID-vkGetAccelerationStructureDeviceAddressKHR-pInfo-09541
If the buffer on which pInfo->accelerationStructure was placed is non-sparse then …

layers: Add 08935 03504 09541 09542

---

layers/state_tracker/cmd_buffer_state.cpp

Fixed a crash in Validation layers when image/imageview are deleted in a descriptor indexing scenario.
**Do:**
* Install Vulkan SDK 1.3.275.0
* Run https://github.com/corporateshark/lightweightvk/blob/main/samples/Tiny_Mesh.cpp
* Press `T`
**Observe:**
A crash in Validation layers.

layers: Fix a crash when image resources are deleted

---

layers/core_checks/cc_ray_tracing.cpp
tests/framework/ray_tracing_objects.cpp
tests/framework/ray_tracing_objects.h
tests/unit/ray_tracing.cpp

VUID-vkBuildAccelerationStructuresKHR-pInfos-03779
For any element of pInfos[i].pGeometries or pInfos[i].ppGeometries with a geometryType of VK_GEOMETRY_TYPE_INSTANCES_KHR, each VkAccelerationStructureInstanceKHR::accelerationStructureReference value in geometry.instances.data.hostAddress must be a valid VkAccelerationStructureKHR object

layer: Add 03779

---

layers/stateless/sl_ray_tracing.cpp
tests/framework/ray_tracing_objects.cpp
tests/framework/ray_tracing_objects.h
tests/unit/ray_tracing.cpp

VUID-vkCmdBuildAccelerationStructuresIndirectKHR-pIndirectDeviceAddresses-03648
Each element of pIndirectDeviceAddresses must be a multiple of 4

layers: Add 03648

---

layers/core_checks/cc_device_memory.cpp

Closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/7445

layers: Fix list of handles created outside of Vulkan

---

.github/workflows/sdk_android_build.yml

This issue caused the android binaries to not be released. See https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/7449

actions: fix artifact name conflict using download-artifact v4

---

layers/core_checks/cc_ray_tracing.cpp
tests/unit/ray_tracing_pipeline.cpp

VUID-vkGetRayTracingShaderGroupStackSizeKHR-groupShader-03609
The shader identified by groupShader in group must not be VK_SHADER_UNUSED_KHR

layers: Add 03609

---

layers/stateless/sl_external_object.cpp
layers/stateless/sl_utils.cpp
layers/stateless/stateless_validation.h
layers/vulkan/generated/stateless_validation_helper.cpp
scripts/generators/stateless_validation_helper_generator.py
scripts/generators/valid_flag_values_generator.py
tests/framework/pipeline_helper.cpp
tests/unit/external_memory_sync.cpp
tests/unit/memory.cpp
tests/unit/others.cpp
tests/unit/pipeline_positive.cpp
tests/unit/portability_subset.cpp
tests/unit/vertex_input.cpp

closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/7433
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/5012
Adds logic to check if a struct is being used when you didn't enable the extension

layers: Add Struct extension check

---

BUILD.gn

Add gpu_pre_copy_buffer_to_image_comp.h
Addresses https://github.com/KhronosGroup/Vulkan-ValidationLayers/commit/ee21e34f2c2707acf3ba8f6e9bc5f1fe7d575ebf#commitcomment-138334216

build: Update build.gn

---

scripts/generate_spec_error_message.py

```
// length of VUs
VUID-VkColorBlendEquationEXT-colorBlendOp-07361 - 1242
VUID-VkDeviceCreateInfo-pNext-pNext - 9068
VUID-VkPhysicalDeviceProperties2-pNext-pNext - 4224
```
These over size error message are quite obnoxious and doing more harm then good

layers: Reduce size of oversized VUs

---

layers/sync/sync_access_state.cpp
layers/sync/sync_access_state.h
tests/unit/sync_val_positive.cpp

The fix is similar to the original fix but instead of replacing TOP_OF_PIPE with NONE we do the other way around because sync validation still loves TOP_OF_PIPE (and needs it).
Closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/7353

sync: Re-fix issue 7353

---

tests/framework/binding.cpp
tests/framework/binding.h

This was simply missing before.

tests: Add test binding for pipeline caches

---

layers/core_checks/cc_cmd_buffer_dynamic.cpp
layers/core_checks/cc_pipeline.cpp
layers/core_checks/cc_pipeline_graphics.cpp
layers/state_tracker/render_pass_state.cpp
layers/state_tracker/render_pass_state.h
layers/state_tracker/state_tracker.cpp
tests/unit/pipeline.cpp
tests/unit/subpass.cpp

closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/6844
- We were not checking for dynamic rendering when checking for "no-attachment subpasses" so made a common util function
- `VUID-VkGraphicsPipelineCreateInfo-subpass-00758` was mislabeled as `VUID-vkCmdBindPipeline-pipeline-00781`
- Added `VUID-VkGraphicsPipelineCreateInfo-subpass-00758`

layers: Fix no-attachment subpass

---

layers/sync/sync_access_state.cpp
tests/unit/sync_val_positive.cpp

`ALL_COMMANDS` includes all operations performed on the gpu, not only operations performed by the official stages.
This was also mentioned here (internal link): https://gitlab.khronos.org/vulkan/vulkan/-/issues/3783#note_453947
The issue was that `ALL_COMMANDS`, when used by the semaphore, did not protect the image layout transition (WRITE) done in the first submission from the shader READ access in the second submission.
Closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/7456

sync: Add layout transition access to ALL_COMMANDS scope

---

layers/sync/sync_commandbuffer.cpp
layers/sync/sync_commandbuffer.h
tests/unit/sync_val_positive.cpp

A unique thing about resolve operations is that they happen on the `COLOR_OUTPUT` stage both for color and depth attachments and use color-specific accesses. This requirement forced ordered accesses to be also color-specific. But for depth-stencil attachment, the participation of depth-stencil accesses is still possible. In the reported issue, it is a `LoadOp::Clear` write which did not pass color ordering barrier. The fix includes both Color and Depth accesses in `OrderingBarrier` for depth-stencil attachment during resolve operation.
Closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/7441
@jzulauf-lunarg DEFCON 4

sync: Fix ordered accesses for depth-stencil resolve

---

layers/stateless/sl_instance_device.cpp
layers/stateless/sl_pipeline.cpp
layers/stateless/sl_utils.cpp
layers/stateless/sl_wsi.cpp
layers/stateless/stateless_validation.h

These are now codegen, no need to keep these old one-off VU checks (these are VERY old)

layers: Remove old unassigned now codegen

---

tests/framework/binding.cpp
tests/framework/binding.h
tests/unit/host_image_copy.cpp
tests/unit/sparse_buffer.cpp
tests/unit/sparse_buffer_positive.cpp
tests/unit/sparse_image.cpp
tests/unit/sparse_image_positive.cpp
tests/unit/sync_object.cpp

RADV in Mesa 24 move there Sparse Queue to be by itself (instead of combined with the graphics/compute main queue family)
This caused various tests to fail on it

tests: Fix sparse queues

---

BUILD.gn
layers/CMakeLists.txt
layers/best_practices/bp_render_pass.cpp
layers/core_checks/cc_cmd_buffer.cpp
layers/core_checks/cc_copy_blit_resolve.cpp
layers/core_checks/cc_image.cpp
layers/core_checks/cc_pipeline_graphics.cpp
layers/core_checks/cc_render_pass.cpp
layers/core_checks/cc_video.cpp
layers/core_checks/cc_wsi.cpp
layers/core_checks/core_validation.h
layers/error_message/error_strings.h

The renderpass compatibility error messages were not well written and even I had to look at the code to understand them
This both unifies how we print things and adds some useful utils for printing other error strings

layers: Improve RenderPass Compatibility messages

---

layers/core_checks/cc_buffer_address.h
layers/core_checks/cc_descriptor.cpp
layers/core_checks/cc_ray_tracing.cpp

1. Move the `LogObjectList` from a per-VU value to just being like the `Location` and be set by the caller as it will be the same for all the checks grouped together
2. Make use of the `address_info` for the descriptor buffer version

layers: Improvement for BufferAddressValidation

---

layers/state_tracker/cmd_buffer_state.cpp
layers/state_tracker/cmd_buffer_state.h
layers/sync/sync_commandbuffer.cpp
layers/sync/sync_submit.cpp
layers/sync/sync_submit.h
tests/unit/sync_val.cpp

If there is no debug label for a specific position in the command
stream, we use `Uint32Max` as a label command index. We need to check
this case and skip debug region reporting. It was done in one place
but was missing in another place.
Adding necessary check allowed to simplify implementation. Two
implementations of `GetDebugRegionName` became almost identical
(in` CommandBuffer` and `QueueBatch` context). The main logic was moved
into a shared helper function.
Addresses the first part of https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/7502

sync: Handle command without debug label and simplify code

---

tests/unit/ray_tracing.cpp

`NegativeRayTracing.PipelineNullMissShader` was submitting a command buffer without anything in it, rather not have the code copy-and-pasted around in future

tests: Don't submit incomplete command buffers

---

layers/sync/sync_submit.cpp
layers/sync/sync_submit.h
tests/unit/sync_val.cpp

Timeline semaphores are not supported yet but the code should not crash
Closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/7502

sync: Fix label code crash when timeline semaphores are used

---

scripts/generate_spec_error_message.py
scripts/vk_validation_stats.py

- Removed unused code
- Remove tracking of UNASSIGNED/kVUID (we have got them almost all gone now!)
- `f' '` f strings for everything
- Improved how the `--remove_duplicates` worked
- Added a `IsVendor` (for testings only currently)
- removed the "Extension" item in the HTML/CSV as it is now only `core` due to the new script change in the spec

scripts: Improvements to vk_validation_stats.py

---

tests/unit/ray_tracing_pipeline.cpp
tests/unit/ray_tracing_pipeline_positive.cpp

We were calling `vkGetRayTracingCaptureReplayShaderGroupHandlesKHR::pData` with a `VkBuffer` handle which then caused everything to crash because the `vkDestroyBuffer` call got really confused

tests: Fix GetCaptureReplayShaderGroupHandlesKHR

---

layers/gpu_validation/spirv/bindless_descriptor_pass.cpp
layers/gpu_validation/spirv/bindless_descriptor_pass.h
layers/gpu_validation/spirv/buffer_device_address_pass.cpp
layers/gpu_validation/spirv/buffer_device_address_pass.h
layers/gpu_validation/spirv/function_basic_block.cpp
layers/gpu_validation/spirv/function_basic_block.h
layers/gpu_validation/spirv/pass.cpp
layers/gpu_validation/spirv/pass.h

closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/7506
The use of `insert` and `std::make_move_iterator` showed a 20x speed up and mostly got performance on par. The current way we do injection is not ideal for cases where we have tons of access in a huge Function block, but there are other things planned I have to help mitigate that

gpuav: Fix speed regression

---

layers/core_checks/cc_buffer_address.h
layers/core_checks/cc_descriptor.cpp
layers/core_checks/cc_ray_tracing.cpp
layers/state_tracker/state_tracker.h

Closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/7488
Is it really an improvement, with this new `const` madness?
EDIT: Since first push, I looked further and remove a useless `const` level, so I think things are fine now. Also, I ended having to reformat entire files, sorry for the noise...

layers: Remove BUFFER_STATE_PTR

---

layers/gpu_validation/spirv/function_basic_block.h
layers/gpu_validation/spirv/module.cpp
layers/gpu_validation/spirv/pass.cpp
tests/CMakeLists.txt
tests/unit/gpu_av_spirv.cpp
tests/unit/gpu_av_spirv_positive.cpp

> "when you look at the edge cases and the things that make control flow hard, 95% of them come from loops"
>
> ~ https://youtu.be/7C4PmtqBVqo?si=PNeLcGijKCNgqBdV&t=973
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/4827
I found that when dealing with a `OpPhi` inside a `Loop header block` it gets really tricky to generate valid SPIR-V that still injects the needed function call.
Since this is a rare case, I rather just ignore it for now (tracked in https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/7462) as generating invalid Control Flow is much worse

gpuav: Fix creating invalid SPIR-V from loop headers

---

BUILD.gn

Fixes #7523
This appears to have been a typo (it's not consistent with the
CMakeLists.txt files) and is blocking rolling in the latest
changes into the Dawn (WebGPU) project. Verified with a local
build.

build: Update gpu_resources.cpp to .h in BUILD.gn

---

layers/vulkan/generated/object_tracker.cpp
scripts/generators/object_tracker_generator.py

I tried adding `VUID-VkPhysicalDeviceSurfaceInfo2KHR-surface-07919` before and ran into spec issues, they were fixed here https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/6429
this applies the logic for the generator 
(there is another upcoming spec fix for the `MicromapEXT` one in the change)

scripts: Add VK_GOOGLE_surfaceless_query object tracker

---

layers/best_practices/best_practices_validation.h
layers/best_practices/bp_instance_device.cpp
layers/core_checks/cc_android.cpp
layers/core_checks/cc_buffer.cpp
layers/core_checks/cc_cmd_buffer.cpp
layers/core_checks/cc_cmd_buffer_dynamic.cpp
layers/core_checks/cc_descriptor.cpp
layers/core_checks/cc_device.cpp
layers/core_checks/cc_device_memory.cpp
layers/core_checks/cc_drawdispatch.cpp
layers/core_checks/cc_image.cpp
layers/core_checks/cc_image_layout.cpp
layers/core_checks/cc_pipeline.cpp
layers/core_checks/cc_pipeline_graphics.cpp
layers/core_checks/cc_queue.cpp
layers/core_checks/cc_ray_tracing.cpp
layers/core_checks/cc_render_pass.cpp
layers/core_checks/cc_spirv.cpp
layers/core_checks/cc_synchronization.cpp
layers/core_checks/cc_wsi.cpp
layers/core_checks/core_validation.h
layers/gpu_validation/gpu_image_layout.cpp
layers/gpu_validation/gpu_record.cpp
layers/gpu_validation/gpu_setup.cpp
layers/gpu_validation/gpu_validation.cpp
layers/gpu_validation/gpu_validation.h

To ensure better confidence as we pass more and more things around is valid, make more use of reference instead of pointers.
The caller should know the object is valid. We were already just blindly de-referencing it anyway right now

layers: More pass by reference

---

tests/unit/amd_best_practices.cpp
tests/unit/arm_best_practices.cpp
tests/unit/best_practices.cpp
tests/unit/command.cpp
tests/unit/descriptors.cpp
tests/unit/dynamic_state.cpp
tests/unit/fragment_shading_rate.cpp
tests/unit/gpu_av.cpp
tests/unit/gpu_av_oob.cpp
tests/unit/multiview.cpp
tests/unit/nvidia_best_practices.cpp
tests/unit/query.cpp
tests/unit/ray_tracing.cpp
tests/unit/ray_tracing_nv.cpp
tests/unit/ray_tracing_pipeline.cpp
tests/unit/ray_tracing_pipeline_nv.cpp
tests/unit/sampler.cpp
tests/unit/shader_image_access.cpp
tests/unit/shader_push_constants.cpp
tests/unit/subpass.cpp
tests/unit/sync_object.cpp
tests/unit/sync_val.cpp
tests/unit/transform_feedback.cpp
tests/unit/vertex_input.cpp

Basically this is a small clean up to use `kErrorBit` instead of `VK_DEBUG_REPORT_ERROR_BIT_EXT`
Goal is to squash any more spreading the old full name around anymore

tests: Use consistent error level alias

---

layers/sync/sync_validation.cpp
tests/unit/sync_val.cpp
tests/unit/sync_val_positive.cpp

`vkCmdFillBuffer` is a transfer clear command, and not a transfer copy command. I make this assumption because this command is described in the "Clear commands" section of the specification and not in the "Copy commands" section.
> VK_PIPELINE_STAGE_2_COPY_BIT specifies the execution of all [copy commands](https://registry.khronos.org/vulkan/specs/1.3-extensions/html/vkspec.html#copies)
> VK_PIPELINE_STAGE_2_CLEAR_BIT specifies the execution of [clear commands](https://registry.khronos.org/vulkan/specs/1.3-extensions/html/vkspec.html#clears)
Closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/7406

sync: Use CLEAR transfer stage for vkCmdFillBuffer

---

layers/gpu_validation/gpu_error_message.cpp
layers/gpu_validation/gpu_resources.h
layers/gpu_validation/gpu_subclasses.cpp

If instrumentation found an error, skip post processing. Errors detected by instrumentation are usually very serious, such as a prematurely destroyed resource and the state needed below is likely invalid.

gpu: Dont't run descriptor validation after an in-shader error

---

tests/unit/ray_tracing.cpp

Old size was too small to allow the buffer to contain its base address aligned to minAccelerationStructureScratchOffsetAlignment

tests: Fix scratch buffer size

---

tests/unit/gpu_av.cpp
tests/unit/gpu_av_positive.cpp

Cleanup tests that were failing with `--gpuav-enable-core` 
Broken up / moved some tests in the process

tests: Fix Core Check error in GPU-AV

---

tests/unit/gpu_av_ray_query_positive.cpp

closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/7546
Verified this works perfectly well on MESA 24 RADV driver, added to blacklist in CI and will remove when driver is updated

tests: Enable PositiveGpuAVRayQuery.GraphicsBasic

---

tests/unit/ray_tracing_positive.cpp

Fix PositiveRayTracing.ScratchBufferCorrectAddressSpaceOpBuild on MESA 24 for RADV

tests: Fix scratch size for RTX test

---

.github/workflows/vvl.yml
layers/CMakeLists.txt

Apples App store rules require dynamic libraries be packaged as Frameworks for iOS. This requirement is not applied for macOS, so all iOS libraries should be packaged as Frameworks moving forward to comply with Apples policy. Although this validation layer in particular is not likely to be shipped in an application bundle, it is being made a Framework as well to be consistent with all the other layers.

layers: Build layer as a framework for ios

---

tests/unit/external_memory_sync_positive.cpp

This is a duplicate pull request because I'm a git novice.
Simple change to external_memory_sync_positive.cpp:353 
Build succeeds with with change of `device()` to `this->device()`

tests: Fix building on Metal

---

layers/core_checks/cc_spirv.cpp

These atomic feature messages were repeating the entire list twice in the error message, for VUs that have more than one feature, re-worded it to not list everything twice
before
> Validation Error: [ VUID-RuntimeSpirv-None-06284 ] | MessageID = 0x6b26b332 | vkCreateShaderModule():  SPIR-V is using float atomics operations
%21 = OpAtomicLoad %6 %14 %15 %20
with StorageBuffer storage class, but shaderBufferFloat32Atomics or shaderBufferFloat32AtomicAdd or shaderBufferFloat64Atomics or shaderBufferFloat64AtomicAdd or shaderBufferFloat16Atomics or shaderBufferFloat16AtomicAdd or shaderBufferFloat16AtomicMinMax or shaderBufferFloat32AtomicMinMax or shaderBufferFloat64AtomicMinMax or shaderFloat16VectorAtomics was not enabled. **The Vulkan spec states:** shaderBufferFloat32Atomics, or …

layers: Improve Atomic error message

---

layers/core_checks/cc_spirv.cpp
layers/core_checks/core_validation.h
layers/state_tracker/shader_module.cpp
layers/state_tracker/shader_module.h
tests/device_profiles/max_profile.json
tests/unit/shader_spirv.cpp
tests/unit/shader_spirv_positive.cpp

Add support for `VK_KHR_shader_float_controls2`
- VUID-RuntimeSpirv-shaderSignedZeroInfNanPreserveFloat16-09559
- VUID-RuntimeSpirv-shaderSignedZeroInfNanPreserveFloat16-09560
-  VUID-RuntimeSpirv-shaderSignedZeroInfNanPreserveFloat32-09561
-  VUID-RuntimeSpirv-shaderSignedZeroInfNanPreserveFloat32-09562
-  VUID-RuntimeSpirv-shaderSignedZeroInfNanPreserveFloat64-09563
-  VUID-RuntimeSpirv-shaderSignedZeroInfNanPreserveFloat64-09564

layers: Add VK_KHR_shader_float_controls2 support

---

CMakeLists.txt
layers/CMakeLists.txt

Remove SPIRV-Link as we don't use it anymore

build: Remove spirv-link dependency

---

layers/sync/sync_submit.cpp
tests/unit/sync_val_positive.cpp

Do not expand stages associated with a signal semaphore during sync1->sync2 conversion. The stages get expanded later, down the pipeline. By expanding them early we lose information about operations that can't be covered by the standard Vulkan stages (e.g. layout transition).
This also ensures that `QueueSubmit` and `QueueSubmit2` behave the same way from syncval perspective with regard to signal semaphores.
The regression test implements false-positive scenario discovered by this project:
https://github.com/kennyalive/vulkan-ray-tracing
> SYNC-HAZARD-PRESENT-AFTER-WRITE(ERROR / SPEC): msgNum: -512052050 - Validation Error: [ SYNC-HAZARD-PRESENT-AFTER-WRITE ] Object 0: handle = 0x1a527fb5960, type = VK_OBJECT_TYPE_QUEUE; | MessageID = 0xe17ab4ae | vkQueuePresentKHR():  Hazard …

sync: Do not expand stages during sync1->sync2 conversion

---

tests/unit/sync_object_positive.cpp

`PositiveSyncObject.ExternalSemaphore` was not using the sparse binding queue (was failing on RADV for Mesa 24)

tests: Fix sync test to use sparse binding queue

---

scripts/tests.py
tests/framework/layer_validation_tests.cpp
tests/framework/render.cpp
tests/framework/test_framework.cpp
tests/framework/test_framework.h
tests/unit/gpu_av.cpp
tests/unit/gpu_av_positive.cpp
tests/unit/sync_val_positive.cpp

Switch --gpuav-enable-core to --gpuav-disable-core. Switch --syncval-enable-core to --syncval-disable-core.
Remove the env var VK_LAYER_TESTS_DISABLE_CORE_VALIDATION because it is a subset of VK_LAYER_TESTS_VALIDATION_FEATURES.

tests: Enable core validation for GPU-AV and SyncVal tests

---

tests/unit/gpu_av_oob.cpp

This test was hitting VUID-VkGraphicsPipelineCreateInfo-renderPass-06055 It is currently the only test using the shader_objects=true path in ShaderBufferSizeTest().

tests: Fix NegativeGpuAVOOB.ObjectUniformBufferTooSmall

---

layers/sync/sync_access_context.cpp
layers/sync/sync_access_context.h
layers/sync/sync_access_state.cpp
layers/sync/sync_access_state.h
layers/sync/sync_submit.cpp
tests/unit/sync_val.cpp
tests/unit/sync_val_positive.cpp

Closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/7386, https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/7455.
Only the accesses from the async queue participate in async hazard detection.
The resolved accesses from the other contexts might belong to different queues
and do not create async hazards.
The positive test is a regression test from:
https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/7386.
The `QSWriteRacingWrite`/`QSWriteRacingWrite2` negative tests were added to
increase `WRITE-RACING-WRITE` coverage, but they do not reproduce the
issue that was fixed.
The `QSWriteRacingRead` test is a regression test for the initial
incorrect attempt to fix the issue (using scalar async tag tracking
instead of per-queue), which nevertheless did …

sync: Filter accesses in async hazard detection

---

layers/core_checks/cc_device_memory.cpp
layers/state_tracker/state_tracker.cpp
layers/state_tracker/state_tracker.h
tests/unit/memory.cpp
tests/unit/memory_positive.cpp

The one VU I haven't validated is the one about `pPlacedAddress` not being inside the map of another Vulkan memory object. I don't know if that kind of tracking exists inside the validation layers or how to go about adding it if it doesn't. Everything else should be validated and tested.

Add validation for VK_EXT_map_memory_placed

---

layers/core_checks/cc_pipeline_graphics.cpp
layers/core_checks/core_validation.h
layers/state_tracker/pipeline_state.cpp
layers/state_tracker/pipeline_state.h
layers/state_tracker/pipeline_sub_state.cpp
layers/state_tracker/pipeline_sub_state.h
tests/unit/dynamic_rendering.cpp
tests/unit/graphics_library.cpp
tests/unit/graphics_library_positive.cpp
tests/unit/mesh.cpp
tests/unit/protected_memory.cpp

closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/7054
adds
- VUID-VkGraphicsPipelineCreateInfo-flags-08897
- VUID-VkGraphicsPipelineCreateInfo-flags-08898
- VUID-VkGraphicsPipelineCreateInfo-flags-08901
- VUID-VkGraphicsPipelineCreateInfo-flags-08909
This also fixes the crashing of `PositiveGraphicsLibrary.PushConstant` and `PositiveGraphicsLibrary.PushConstantOneLibrary` in CI
This also does some cleanup as I slowly converge all the GPL code to be more seamless

Add GPL check for missing linked pipelines

---

scripts/known_good.json
tests/device_profiles/max_profile.json
tests/unit/atomics.cpp
tests/unit/atomics_positive.cpp
tests/unit/memory.cpp
tests/unit/memory_positive.cpp

I realized from previous external PR, it would be good to always try and keep Max Profiles up-to-date with latest extensions so if someone wants to add the extension, they don't need to find out the hard way that CI is not running on it
This adds many extensions, a few required some cleanup

tests: Add missing extensions from Max Profiles

---

layers/gpu_validation/gpu_error_message.cpp
layers/gpu_validation/gpu_resources.h
layers/gpu_validation/gpu_validation.cpp
layers/gpu_validation/gpu_validation.h
layers/gpu_validation/gpu_vuids.cpp
tests/CMakeLists.txt
tests/framework/layer_validation_tests.h
tests/unit/gpu_av.cpp
tests/unit/gpu_av_buffer_device_address.cpp
tests/unit/gpu_av_oob.cpp
tests/unit/gpu_av_positive.cpp
tests/unit/gpu_av_shader_object_positive.cpp
tests/unit/shader_object_positive.cpp

These 2 VUs were split into 4 because and adjusted the VUID logic to represent that
(also moved our GPU-AV Shader Object test to a dedicated file)

gpuav: Fix VUID from pipeline vs shaderObject

---

tests/unit/graphics_library_positive.cpp

Pipeline is created with `VK_PIPELINE_CREATE_FAIL_ON_PIPELINE_COMPILE_REQUIRED_BIT`, which means `vkCreateGraphicsPipelines` can return `VK_PIPELINE_COMPILE_REQUIRED`, which was not accounted for.

tests: Fix shader module identifier test

---

tests/unit/sync_val_positive.cpp

Transfer queue was not waited on. Potentially fixes CI failure.

tests: Fix resource in use error

---

CMakeLists.txt

pkg-config is only required if WSI support is enabled.

cmake: Only require pkg-config if necessary

---

layers/core_checks/cc_shader_interface.cpp
tests/unit/shader_interface.cpp

closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/7566
When getting an interface wrong, it is easy to just get spammed with VU errors. Only print the first one as likely the user messed up the entire struct and doesn't need a repeated error for each byte

layers: Only print out a single interface error

---

layers/core_checks/cc_pipeline_graphics.cpp
tests/framework/pipeline_helper.cpp
tests/framework/pipeline_helper.h
tests/unit/graphics_library.cpp
tests/unit/graphics_library_positive.cpp

closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/7550
Logic for some GPL was not considering the fact you can create things like the Pre-Rasterization and Frag Shader state together

layers: Fix GPL not checking grouped substate

---

layers/core_checks/cc_cmd_buffer.cpp
layers/core_checks/cc_cmd_buffer_dynamic.cpp
layers/core_checks/cc_descriptor.cpp
layers/core_checks/cc_image.cpp
layers/core_checks/cc_image_layout.cpp
layers/core_checks/cc_pipeline.cpp
layers/core_checks/cc_pipeline_graphics.cpp
layers/core_checks/cc_render_pass.cpp
layers/core_checks/cc_shader_interface.cpp
layers/core_checks/cc_synchronization.cpp
layers/core_checks/core_validation.h
layers/state_tracker/cmd_buffer_state.cpp
layers/state_tracker/pipeline_state.cpp
layers/state_tracker/pipeline_state.h
layers/state_tracker/render_pass_state.cpp
layers/state_tracker/render_pass_state.h
layers/state_tracker/state_tracker.cpp
layers/state_tracker/state_tracker.h
layers/stateless/sl_cmd_buffer.cpp
layers/stateless/sl_render_pass.cpp
layers/sync/sync_vuid_maps.cpp
layers/sync/sync_vuid_maps.h
tests/CMakeLists.txt
tests/device_profiles/max_profile.json
tests/framework/layer_validation_tests.h
tests/unit/dynamic_rendering.cpp
tests/unit/dynamic_rendering_local_read.cpp
tests/unit/dynamic_rendering_local_read_positive.cpp

Validation still needed for (tests now are commented out):
* VUID-vkCmdExecuteCommands-pCommandBuffers-09504
* VUID-vkCmdExecuteCommands-pCommandBuffers-09505
Implemented and tested:
* VUID-VkAttachmentDescription-dynamicRenderingLocalRead-09544
* VUID-VkAttachmentDescription-dynamicRenderingLocalRead-09545
* VUID-VkAttachmentReference-dynamicRenderingLocalRead-09546
* VUID-vkCmdDraw-None-09548
* VUID-vkCmdDraw-None-09549
* VUID-VkImageMemoryBarrier2-srcQueueFamilyIndex-09550
* VUID-VkImageMemoryBarrier2-dynamicRenderingLocalRead-09551
* VUID-VkImageMemoryBarrier2-dynamicRenderingLocalRead-09552
* VUID-vkCmdPipelineBarrier2-None-09554
* VUID-vkCmdPipelineBarrier2-image-09555
* VUID-vkCmdPipelineBarrier2-srcStageMask-09556
* VUID-vkCmdClearAttachments-colorAttachment-09503
* …

Validation for VK_KHR_dynamic_rendering_local_read

---

scripts/generate_source.py
scripts/generators/base_generator.py

Currently it takes my machine `50.40 seconds` to generate all 53 files
This uses the python `pickle` module to cache the data so that we don't have to reparse the entire XML each time
This brought my machine down to `23.04` seconds

scripts: Use pickle to cache the VkObject

---

layers/gpu_shaders/gpu_pre_action.h
layers/gpu_shaders/inst_bindless_descriptor.comp
layers/gpu_shaders/inst_buffer_device_address.comp
layers/gpu_shaders/inst_ray_query.comp

The header was renamed in #7631 but not all shaders were updated.

Rename gpu_error_constants.h -> gpu_error_header.h

---

layers/containers/range_vector.h
layers/utils/vk_layer_utils.cpp
layers/utils/vk_layer_utils.h

fix for https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/7591#discussion_r1511292914
(cc @y-novikov)

build: Fix circular dependency

---

layers/vulkan/generated/spirv_validation_helper.cpp
scripts/generate_source.py
scripts/generators/spirv_validation_generator.py

Make the spirv_validation_generator.py more robust to header updates by replacing the hard-coded capability lists with ones generated from the SPIR-V grammar.
I consider this a prerequisite for adding more automation to the header updates since it breaks so frequently
The `string_SpvCapability` diff is kinda hard to read so here is the sorted version of the added/removed switch cases:
```diff
--- before.txt  2024-03-05 21:15:54.098254315 -0800
+++ after.txt   2024-03-06 08:39:45.904650307 -0800
@@ -1,3 +1,8 @@
+case spv::CapabilityAddresses
+case spv::CapabilityArbitraryPrecisionFixedPointINTEL
+case spv::CapabilityArbitraryPrecisionFloatingPointINTEL
+case spv::CapabilityArbitraryPrecisionIntegersINTEL
+case spv::CapabilityAsmINTEL
case spv::CapabilityAtomicFloat16AddEXT
case …
```

scripts: Remove manual header update step

---

layers/vulkan/generated/spirv_grammar_helper.cpp
layers/vulkan/generated/spirv_grammar_helper.h
layers/vulkan/generated/spirv_validation_helper.cpp
scripts/generators/generator_utils.py
scripts/generators/spirv_grammar_generator.py
scripts/generators/spirv_validation_generator.py

This creates a list of all OpenCL only SPIR-V to help reduce the size of the spirv helpers and remove things that we clearly will never see

scripts: Remove OpenCL SPIR-V from genearted helpers

---

layers/vulkan/generated/vk_object_types.cpp
scripts/generators/object_types_generator.py

`vk_object_types.cpp` only included `vulkan_core.h`, but some object type definitions may be platform specific and thus are defined in one of the other headers. So this is just a trivial fix to include `vulkan.h` instead.

script: Fix object types generator include issue

---

layers/core_checks/cc_pipeline_graphics.cpp
tests/unit/graphics_library.cpp
tests/unit/graphics_library_positive.cpp

In yet-another-turn for the GPL saga, the WG decided to just ban `stageCount` being non-zero when not need to make everyone's life easier... https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/6530

layers: Check for non-zero stageCount

---

layers/core_checks/cc_cmd_buffer.cpp
layers/core_checks/cc_descriptor.cpp
layers/core_checks/cc_drawdispatch.cpp
layers/core_checks/cc_image_layout.cpp
layers/core_checks/cc_synchronization.cpp
layers/core_checks/core_validation.h
layers/drawdispatch/descriptor_validator.cpp
layers/drawdispatch/descriptor_validator.h
layers/gpu_validation/gpu_image_layout.cpp
layers/gpu_validation/gpu_subclasses.cpp
layers/gpu_validation/gpu_validation.h
layers/state_tracker/cmd_buffer_state.cpp
layers/state_tracker/cmd_buffer_state.h
layers/state_tracker/state_object.h
layers/state_tracker/state_tracker.h

Rework management of CommandBuffer::image_layout_map to not contain invalid pointers and tolerate stale state when drivers reuse image handle values. More details in the commit messages for the PR
Fixes #7435

layers: Fix CommandBuffer image layout state tracking

---

layers/core_checks/cc_render_pass.cpp

Print both the expected and actual usage flags for VUIDs such as VUID-VkFramebufferCreateInfo-pAttachments-00877
old:
`vkCreateFramebuffer(): pCreateInfo->pAttachments[0] conflicts with the image's flags (VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT).`
new:
`vkCreateFramebuffer(): pCreateInfo->pAttachments[0] expected usage (VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT) conflicts with the image's flags (VK_IMAGE_USAGE_STORAGE_BIT|VK_IMAGE_USAGE_INPUT_ATTACHMENT_BIT).`

corechecks: Improve framebuffer usage messages

---

layers/core_checks/cc_cmd_buffer_dynamic.cpp
layers/core_checks/core_validation.h
layers/state_tracker/state_tracker.cpp
layers/state_tracker/state_tracker.h

closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/7660

layers: Add missing vkCmdSetLineStippleKHR hook

---

layers/core_checks/cc_pipeline_graphics.cpp

closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/7666
For now the chance of the pNext struct values in two different GPL is low, and rather not give false positive and come back later to catch these edge cases

layers: Do shallow pNext pointer compare

---

layers/core_checks/cc_shader_interface.cpp

There seems to be some disagreement about how Tessellation built-ins count towards interface limits
For sake of not giving false positives, decided to just adjust the VU for now

layers: Fix Tessellation component limit check

---

layers/core_checks/cc_buffer.cpp
layers/core_checks/cc_cmd_buffer_dynamic.cpp
layers/core_checks/cc_image.cpp
layers/core_checks/cc_ray_tracing.cpp
layers/drawdispatch/descriptor_validator.cpp
layers/stateless/sl_cmd_buffer_dynamic.cpp
layers/stateless/sl_pipeline.cpp

unify the way we print out `VkFormatFeatureFlags2` with a new line to help as these can become very verbose when we print all the features supported for a format

layers: Improve format feature error messages

---

layers/core_checks/cc_cmd_buffer_dynamic.cpp
tests/unit/shader_object_positive.cpp

From https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/6523
Few dynamic states are ignored if `VkRenderingInfo::colorAttachmentCount` is `0`

layers: Ignore dynamic color blend with no attachment

---

layers/drawdispatch/descriptor_validator.cpp
layers/state_tracker/shader_module.cpp
layers/state_tracker/shader_module.h
tests/unit/gpu_av_positive.cpp
tests/unit/shader_image_access.cpp
tests/unit/shader_image_access_positive.cpp

closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/7677
```glsl
layout(set = 0, binding = 0) uniform texture2D float_textures[2]; // only index 0 is accessed
layout(set = 0, binding = 0) uniform utexture2D uint_textures[2]; // only index 1 is accessed
```
before we were checking only by `binding`, now we make sure the `ValidateDescriptor` is checking to make sure the image was accessed in that index before trying to validate it

layers: Fix aliasing image bindings with different types

---

layers/sync/sync_submit.cpp
layers/sync/sync_submit.h
layers/sync/sync_validation.cpp
tests/framework/binding.h
tests/unit/sync_val_positive.cpp

Closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/7250
There are syncval endpoints that compute state in the Validate phase
and use thread local storage to propagate it to the Record phase,
which does the final update.
This change fixes one side effect of this approach in the multithreaded
environment. In some cases, the accesses that should be synchronized by
vkWaitForFences can leak through this synchronization point, and then
hazard with the following accesses.
In following scenario two threads work with the same queue.
The queue access is externally synchronized.
1. Thread A: Submits some memory accesses. Signals a fence.
2. Thread B: Submits empty command buffer. Finishes only Validate.
This imports accesses from step 1 and the batch is stored in the
thread local …

sync: Fix WaitForFences leak

---

layers/core_checks/cc_external_object.cpp
layers/state_tracker/fence_state.h
layers/state_tracker/semaphore_state.h
tests/unit/external_memory_sync_positive.cpp

Found running against CTS we didn't handle two 
```
vkGetSemaphoreFdKHR();
vkGetSemaphoreFdKHR();
```
calls next to each other

layers: Fix checking null imported handle type

---

layers/drawdispatch/descriptor_validator.cpp

Fix `std::unordered_set` in main when not using robin hood

layers: Fix std build error in main

---

layers/core_checks/cc_pipeline_graphics.cpp
tests/unit/pipeline_positive.cpp

Fix for https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/6535
`VkPipelineColorBlendStateCreateInfo::attachmentCount` can be ignored under certain conditions

layers: Ignore attachmentCount with dynamic state

---

tests/unit/wsi.cpp

Updated nvidia driver to version 551.67 and got support for VK_EXT_swapchain_maintenance1. This wsi test did not pass.

tests: Fix wsi test for the latest nvidia drivers

---

scripts/generate_source.py

before adding `-j` for https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/7701
I want to first make caching the defaulted behavior

scripts: Default caching the generated source file

---

BUILD.gn
layers/CMakeLists.txt
layers/core_checks/cc_copy_blit_resolve.cpp
layers/core_checks/cc_vuid_maps.cpp
layers/core_checks/cc_vuid_maps.h
layers/core_checks/core_validation.h
layers/error_message/error_location.h

Taking inspiration from `sync_vuid_maps.cpp` I have created a `cc_vuid_maps.cpp` that fully makes use of the `Location` scheme we have
I started with `cc_copy_blit_resolve.cpp`, mainly because it needed this the most, but the goal is to move more and more VUID fetching logic here when we want to share functions between different entry points and not want to pass a `const char* vuid` everywhere

layers: Create VUID Map file

---

layers/core_checks/cc_query.cpp
layers/core_checks/core_validation.h

This way of passing in VUs like the Draw commands was done years ago, now we have `Location`
Since there is only 2 Query calls, it seems overkill to add an entry in `cc_vuid_maps.cpp` and happy to just do a ternary (since we were and this is just making it consistent)

layers: Removed inline query VUID struct

---

layers/core_checks/cc_descriptor.cpp
layers/core_checks/cc_device.cpp
layers/core_checks/cc_shader_object.cpp
layers/core_checks/cc_synchronization.cpp
layers/vulkan/generated/chassis.cpp
layers/vulkan/generated/chassis.h
scripts/generators/layer_chassis_generator.py
scripts/known_good.json
tests/unit/command_positive.cpp

second attempt of https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/7044 to address https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/6310
- Generate checks for when a function can return `VK_ERROR_DEVICE_LOST` and sets the status
- When destroying objects, all go through `ValidateObjectNotInUse` and there we can simply not check
The test uses a special hook into MockICD to force a device lost and can confirm the cleanup is as expected

layers: Don't check for used object if Device Lost

---

layers/core_checks/cc_image.cpp
layers/core_checks/cc_vuid_maps.cpp
layers/core_checks/cc_vuid_maps.h
layers/core_checks/core_validation.h
layers/sync/sync_vuid_maps.cpp
layers/sync/sync_vuid_maps.h

Move another good candidate of VUIDs to `cc_vuid_maps.cpp`
These VUs use to be scatter around the place and now are all grouped together properly

layers: Move SubresourceRangeErrorCodes to map file

---

layers/core_checks/cc_device.cpp

closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/6310
`vkDestroyCommandPool` is a special case because it holds the command buffers which might have been used

layers: Check DEVICE_LOST for vkDestroyCommandPool

---

layers/containers/subresource_adapter.cpp
tests/unit/sync_val.cpp

We were getting sync write-after-write errors when copying non-overlapping blocks of 320x320 pixels from a buffer to an ETC2 RGB texture. 320x320 is clearly a multiple of the block size (4x4) - so this should not fail validation.
I was able to track the problem down to `ImageRangeEncoder::Encode2D`. It was computing the x-offset into the row by multiplying `offset.x` with `texel_Sizes_[aspect_index`]. That is incorrect. Imagine an 8x8 ETC2 RGB (or BC1) texture. Each 4x4 block is 8 bytes. The address of `(x = 4, y = 0)` is the address of the second block, 8. However, the old code computed it as `offset.x * texel_sizes_[aspect_index] = 4 * 0.5 = 2`.
The problem was that the rest of the code was correctly computing y-offsets and spans. For example, the span of a 4x4 copy is correctly …

Fixing Encode2D/3D address calculation for compressed textures.

---

tests/unit/sync_val.cpp
tests/unit/sync_val_positive.cpp

Follow-up to https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/7713
It's two copies instead of three that also reproduces the issue if the above fix is not applied.

tests: Simplify test and make it positive

---

docs/creating_tests.md
tests/framework/error_monitor.cpp
tests/framework/error_monitor.h
tests/framework/render.h
tests/unit/atomics.cpp

Adds a new `SetDesiredError` to replace `SetDesiredFailureMsg` for most cases
1. Outside things like Best Practices, we now know every test should be `kErrorBit` so it seems better to just make that the default
2. Adding `count` is aimmed for GPU-AV where we might need to print the error multiple times for a single shader stage
This PR just updates `atomics.cpp` (since it can make use of the `count`) but after will go through and fix everywhere
The old `SetDesiredFailureMsg` is still there so no other PRs will be broken from underneath them

tests: Add SetDesiredError

---

layers/core_checks/cc_descriptor.cpp
layers/core_checks/core_validation.h
layers/object_tracker/object_tracker_utils.cpp
layers/stateless/sl_descriptor.cpp
layers/stateless/stateless_validation.h
layers/vulkan/generated/stateless_validation_helper.cpp
scripts/generators/stateless_validation_helper_generator.py
tests/unit/descriptor_buffer.cpp
tests/unit/descriptors.cpp
tests/unit/push_descriptor.cpp

follow-up of https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/7671
For Stateless/ObjectTracking/CoreChecks we now just have `vkGetDescriptorSetLayoutSupport` and `vkCreateDescriptorSetLayout` just both call into a `ValidateDescriptorSetLayoutCreateInfo` call as both share the same VUs for `VkDescriptorSetLayoutCreateInfo`

Add proper vkGetDescriptorSetLayoutSupport support

---

BUILD.gn
layers/CMakeLists.txt
layers/core_checks/cc_synchronization.cpp
layers/state_tracker/fence_state.h
layers/state_tracker/semaphore_state.cpp
layers/state_tracker/semaphore_state.h
layers/state_tracker/submission_reference.h

Before starting with some core sync bugs, I decided it was a good time to make a change I had been thinking about for some time. I feel this makes concepts a bit more orthogonal and hopefully helps to dig faster into the code.
It is a refactor to store only submission references instead of SemOps inside the semaphore's timeline. The main gain is that a submission reference is a simpler abstraction than SemOp. As a bonus, this avoids some data duplication and the need to keep asserts to ensure that duplicated data is consistent.
SemOps are continued to be used outside the semaphore's timeline (completed/last operation, other contexts). 
We can avoid storing `payload` and `op_type` values inside timeline because:
* payload value is already known when we access semaphore timeline - it is the …

layers: Store submit reference instead of SemOp in timeline

---

tests/unit/wsi_positive.cpp

This test was failing because the surface handle wasn't initialized.

tests: Fix PositiveWsi.CreateXcbSurface on llvmpipe

---

layers/best_practices/bp_drawdispatch.cpp

`BestPractices-vkCmdDrawIndexed-sparse-index-buffer` introduced a warning if the bound index buffer doesn't make good use of the range of values in the index buffer. To do this, the validation layer captures any call to `vkMapMemory` and notes where the memory was mapped. [Here](https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/main/layers/state_tracker/state_tracker.cpp#L1451)
Later, the best practices layer uses this stored pointer to iterate over the index buffer and read the values, [here](https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/main/layers/best_practices/bp_drawdispatch.cpp#L219). However, when accessing the pointer to the buffer's memory, the layer adds on the offset that was originally passed to `vkMapMemory`. This shouldn't happen, as the pointer …

layers: Fix out-of-bounds memory access in Best Practices

---

layers/layer_chassis_dispatch_manual.cpp
layers/vulkan/generated/chassis.h
layers/vulkan/generated/layer_chassis_dispatch.cpp
scripts/generators/layer_chassis_dispatch_generator.py
scripts/generators/layer_chassis_generator.py

closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/4136
I have gone over all the various edge cases in the `layer_chassis_dispatch_generator.py` and feel confident it is in a good state now

Improve Layer Chassis Dispatch script

---

layers/core_checks/cc_cmd_buffer.cpp
tests/unit/command_positive.cpp

`VUID-vkCmdExecuteCommands-flags-06024` applies if
> vkCmdExecuteCommands is being called within a render pass instance begun with vkCmdBeginRendering
Which is not the case with nested command buffers

Fix nested cmd buffers with queries

---

layers/core_checks/cc_image_layout.cpp
layers/core_checks/cc_pipeline_graphics.cpp
layers/core_checks/cc_synchronization.cpp
layers/core_checks/core_validation.h
layers/error_message/logging.cpp
layers/error_message/logging.h
layers/gpu_validation/debug_printf.cpp
layers/gpu_validation/gpu_error_message.cpp
layers/gpu_validation/gpu_error_message.h
layers/state_tracker/cmd_buffer_state.cpp
layers/state_tracker/state_tracker.cpp
layers/sync/sync_commandbuffer.cpp
layers/sync/sync_commandbuffer.h
layers/utils/vk_layer_utils.cpp
layers/utils/vk_layer_utils.h
layers/vulkan/generated/chassis.cpp
layers/vulkan/generated/chassis.h
scripts/generators/layer_chassis_generator.py

On the quest to improve logging, first need to do some house cleaning
This change
1. `typedef struct debug_report_data` -> `class DebugReportData`
2. Move things into `DebugReportData` instead of passing around a pointer reference to it
I imagine a lot of this stems back from when there were multiple layers, but instead of functions like `BeginCmdDebugUtilsLabel` being globals that pass in a `debug_report_data*`, I just moved these calls into the new `DebugReportData` class

Move functions into DebugReportData

---

layers/gpu_validation/gpu_error_message.cpp

This is a quick fix for https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/7746
I have plans to better clean this all up, but want https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/7711 to land first
This change will for now not crash if `shader_map` fails to find the handle and move on

gpuav: Don't crash if shader_map fails to find handle

---

layers/core_checks/cc_pipeline_graphics.cpp
layers/core_checks/cc_shader_interface.cpp
layers/core_checks/core_validation.h
layers/state_tracker/pipeline_state.h
layers/state_tracker/pipeline_sub_state.cpp
layers/state_tracker/pipeline_sub_state.h
layers/stateless/sl_instance_device.cpp
layers/stateless/sl_pipeline.cpp
layers/stateless/sl_render_pass.cpp
layers/stateless/stateless_validation.h
tests/unit/dynamic_rendering.cpp
tests/unit/pipeline_advanced_blend.cpp

The core issue is we track the `subpass` state inside `StatelessValidation`
We currently are tracking state in `stateless_validation.h` and `StatelessValidation::RecordRenderPass`
My goal is to get rid of it, this PR removes half of it as the 2nd half will be a lot more messy to remove

layers: Move some state tracking out of stateless

---

layers/best_practices/best_practices_validation.h
layers/best_practices/bp_descriptor.cpp
layers/best_practices/bp_pipeline.cpp
layers/core_checks/cc_descriptor.cpp
layers/core_checks/cc_pipeline_compute.cpp
layers/core_checks/cc_pipeline_graphics.cpp
layers/core_checks/cc_pipeline_ray_tracing.cpp
layers/core_checks/cc_spirv.cpp
layers/core_checks/core_validation.h
layers/gpu_validation/debug_printf.cpp
layers/gpu_validation/debug_printf.h
layers/gpu_validation/gpu_record.cpp
layers/gpu_validation/gpu_state_tracker.cpp
layers/gpu_validation/gpu_state_tracker.h
layers/gpu_validation/gpu_validation.cpp
layers/gpu_validation/gpu_validation.h
layers/state_tracker/chassis_modification_state.h
layers/state_tracker/pipeline_state.h
layers/state_tracker/state_tracker.cpp
layers/state_tracker/state_tracker.h
layers/vulkan/generated/best_practices.cpp
layers/vulkan/generated/best_practices.h
layers/vulkan/generated/chassis.cpp
layers/vulkan/generated/chassis.h
scripts/generators/best_practices_generator.py
scripts/generators/layer_chassis_generator.py

This makes 2 simple, but really nice changes
1. Use the name of the struct instead of `void*` in the function parameters (this was `void*` before because we didn't have things separated and it would have required everyone to include everything)
2. Use `namespace chassis` for these structs instead of the strange names we had for them

Clean up chassis_modification_state.h

---

layers/core_checks/cc_drawdispatch.cpp
tests/unit/command.cpp

Add new `VUID-vkCmdDrawMultiEXT-drawCount-09628` and `VUID-vkCmdDrawMultiIndexedEXT-drawCount-09629` VU added in 1.3.281 spec
cc @mikes-lunarg these are the only 2 churn we have

layers: VU fixes for 1.3.281

---

layers/containers/subresource_adapter.cpp
tests/unit/sync_val_positive.cpp

Fixes Angle regression https://ci.chromium.org/ui/p/angle/builders/try/linux-test/19351/test-results?sortby=&groupby=&cols=
Related conversation: https://github.com/KhronosGroup/Vulkan-ValidationLayers/commit/5df44678c4f4ec06dcad3eea308b1dd70eb8cc56#commitcomment-140093219
The history here is that we made a https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/7713 PR recently, which is correct, but it exposes another existing issue. It did not cause troubles for Angle due to luck (two bugs compensated each other).
Our code assumed that rowPitch (bytes for one row of texels) is an integral number, which is true for most formats, including compressed ones, but it's not true for ASTC. For example, ASTC10x10, encodes 10x10=100 pixels in 16 bytes, so on average it's 1.6 bytes per row. …

layers: Fix arrayPitch computation for ASTC_10x10

---

layers/stateless/sl_utils.cpp
layers/stateless/stateless_validation.h

The read of count in ValidateStructTypeArray can invoke UB if the application does something like this:
```c++
uint32_t num_format_props;
CHECK_RESULT(vkGetPhysicalDeviceVideoFormatPropertiesKHR(physical_device, &video_format_info, &num_format_props, nullptr));
```
By moving the count check after the nullptr check, we avoid reading a possibly uninitialized variable.

layers: Avoid UB in ValidateStructTypeArray

---

layers/gpu_validation/spirv/module.cpp
layers/gpu_validation/spirv/module.h
layers/vulkan/generated/spirv_grammar_helper.h
scripts/generators/spirv_grammar_generator.py

This fixes small bug were I was injecting a `OpName` after a `OpModuleProcessed`

gpuav: Split debug instructions and make a switch case

---

layers/core_checks/cc_pipeline_graphics.cpp
layers/core_checks/cc_video.cpp

I found one more example of https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/7759

layers: Use VkBufferUsageFlags2 everywhere

---

layers/core_checks/cc_wsi.cpp
layers/core_checks/core_validation.h
layers/gpu_validation/gpu_image_layout.cpp
layers/gpu_validation/gpu_validation.h
layers/state_tracker/image_state.cpp
layers/state_tracker/state_tracker.cpp
layers/state_tracker/state_tracker.h
tests/framework/render.cpp
tests/unit/wsi_positive.cpp

This is follow-up to https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/7703
Found two reasons why we couldn't easily get rid of `GetSwapchainImages` from `VkRenderFramework::CreateSwapchain`:
- VUs like `VUID-VkBindImageMemorySwapchainInfoKHR-imageIndex-01644` check swapchain image count and can run before the image is acquired.
-  Swapchain image layout map initialization relied on GetSwapchainImagesKHR call.
This solution initializes swapchain image state immediately when swapchain object is created.

layers: Remove WSI validation dependency on GetSwapchainImages

---

layers/core_checks/cc_copy_blit_resolve.cpp
layers/core_checks/cc_image.cpp
layers/core_checks/cc_image_layout.cpp
layers/core_checks/core_validation.h
tests/framework/layer_validation_tests.h
tests/unit/host_image_copy.cpp
tests/unit/host_image_copy_positive.cpp

The tests for Host Image Copy were really large, so I split 2 of the large ones up. While doing that, made the tests work for lavapipe now (until we get MockICD support working)
While at it, I did some cleaning of the layer code, mainly removing unneeded `VkDevice` handles and remove `const char* ` for new Location enums

tests: Fix Host Image Copy for Lavapipe

---

layers/core_checks/cc_image.cpp
layers/gpu_validation/gpu_validation.cpp

Use the referenced struct of the safe struct everywhere
These are a few spots still left that wanted to get squashed

layers: Don't use safe struct when not needed

---

layers/gpu_validation/debug_printf.cpp
layers/gpu_validation/debug_printf.h

Pass the `Location` down to the `LogError` in DebugPrintF

gpuav: Pass Location down for DebugPrintF

---

scripts/known_good.json
tests/device_profiles/max_profile.json
tests/unit/host_image_copy.cpp

Currently we were not running `VK_EXT_host_image_copy` on MockICD due to an issue with profiles handling the strange property struct of this extension
This adds support and fixes few tests that I now see had issues but were missed from lack of testing them

tests: Add Host Image Copy support for Max Profile

---

layers/gpu_validation/debug_printf.cpp
layers/gpu_validation/debug_printf.h
layers/gpu_validation/gpu_error_message.cpp
layers/gpu_validation/gpu_error_message.h
layers/gpu_validation/gpu_setup.cpp
layers/gpu_validation/gpu_state_tracker.h
layers/gpu_validation/gpu_validation.cpp
layers/gpu_validation/gpu_validation.h
layers/state_tracker/shader_instruction.cpp
layers/state_tracker/shader_instruction.h
layers/state_tracker/shader_module.cpp
layers/state_tracker/shader_module.h

When we print the error for GPU-AV and DebugPrintF we need `spirv::Instrument` to make parsing the SPIR-V easy
Before we were creating an entire `spirv::Module` in order to get `std::vector<spirv::Instruction> instructions;` while ignore all the other state tracking that `spirv::Module` does
This splits it up to make printing errors smoother

gpuav: Don't create an entire spirv::Module for errors

---

layers/state_tracker/semaphore_state.cpp
layers/state_tracker/semaphore_state.h
tests/unit/sync_object_positive.cpp

Closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/6172
The previous refactor clarified some terminology and helped with this fix. For example, `GetLastBinarySignalSubmission` was  renamed to `GetPendingBinarySignalSubmission`.  In the current code the `pending` operation usually refers to something that is still (or was recently) in the semaphore timeline (pending execution), and the `last` operation can refer either to the `pending` operation, if it exists, otherwise it's the last completed operation.
`LastOp()` is not a proper tool to implement `AnotherQueueWaits()` because we are interesting only in the pending operations. 
One direction of further code improvements is to review LastOp() usage. It's pretty complicated. Maybe it can be split into smaller scenarios …

layers: Fix false-positive when reusing binary semaphore

---

layers/core_checks/cc_cmd_buffer.cpp
layers/state_tracker/cmd_buffer_state.cpp
layers/state_tracker/cmd_buffer_state.h
layers/state_tracker/state_tracker.cpp
layers/state_tracker/state_tracker.h
tests/unit/multiview.cpp
tests/unit/transform_feedback.cpp

`VUID-vkCmdBeginTransformFeedbackEXT-firstCounterBuffer-09630` was added in `1.3.281`
This might be what was causing some Transform Feedback tests to fail and be blacklisted in CI as the internal Gitlab issue showed that some driver crash and I never could figure out we were doing wrong in the tests

layers: Add new vkCmdBeginTransformFeedbackEXT VU

---

docs/gpu_validation.md
layers/gpu_validation/gpu_error_message.cpp
layers/state_tracker/shader_module.cpp
layers/vulkan/generated/spirv_grammar_helper.cpp
scripts/generators/spirv_grammar_generator.py

Went through and made sure the promoted alias name for SPIR-V is used throughout the code

scripts: Use promoted SPIR-V names

---

layers/layer_chassis_dispatch_manual.cpp
layers/layer_options.h
layers/state_tracker/descriptor_sets.h
layers/vulkan/generated/chassis.cpp
layers/vulkan/generated/chassis.h
scripts/generators/layer_chassis_generator.py

Trying to clean up the chassis level logic
I noticed we had a lot of stuff that is only for Layer Options and moved it over there

layers: Move things out of chassis.h to Layer Options

---

layers/gpu_validation/debug_printf.cpp
layers/gpu_validation/gpu_settings.h
layers/layer_options.cpp
layers/layer_options.h
layers/vulkan/generated/chassis.cpp
layers/vulkan/generated/chassis.h
scripts/generators/layer_chassis_generator.py

Debug PrintF was using the old way to set its settings
Now it is hooked up with vk_layer_settings like everything else

printf: Add proper vk_layer_settings support

---

layers/core_checks/cc_pipeline_graphics.cpp
layers/stateless/stateless_validation.h
layers/vulkan/generated/chassis.h
layers/vulkan/generated/valid_enum_values.cpp
layers/vulkan/generated/valid_enum_values.h
layers/vulkan/generated/valid_flag_values.cpp
scripts/generators/layer_chassis_generator.py
scripts/generators/valid_enum_values_generator.py
scripts/generators/valid_flag_values_generator.py

there are some generated checks that only `StatelessValidation` is using, but we had them in the chassis level for no good reason (I know because I added them there)

Move checks from Chassis to StatelessValidation 

---

scripts/generators/generator_utils.py

Comparison to the existing guard should be `!=` not `is not`
Found during code review of https://github.com/KhronosGroup/Vulkan-Utility-Libraries/pull/187

scripts: Fix PlatformGuardHelper.add_guard()

---

layers/core_checks/cc_buffer_address.h
layers/core_checks/cc_device_memory.cpp
layers/core_checks/cc_ray_tracing.cpp
layers/core_checks/core_validation.h
tests/unit/ray_tracing.cpp
tests/unit/ray_tracing_positive.cpp

VUID-vkCmdBuildAccelerationStructuresKHR-dstAccelerationStructure-03703
The range of memory backing the dstAccelerationStructure member of any element of pInfos that is accessed by this command must not overlap the memory backing the scratchData member of any element of pInfos (including the same element), which is accessed by this command
VUID-vkCmdBuildAccelerationStructuresKHR-scratchData-03705
The range of memory backing the scratchData member of any element of pInfos that is accessed by this command must not overlap the memory backing the srcAccelerationStructure member of any element of pInfos with a mode equal to VK_BUILD_ACCELERATION_STRUCTURE_MODE_UPDATE_KHR (including the same element), which is accessed by this command
VUID-vkCmdBuildAccelerationStructuresKHR-scratchData-03704 …

layers: Add back RT VUs 03703 03704 03705

---

layers/gpu_validation/gpu_validation.cpp

Running a replay with GFXReconstruct showed that I was not handling an early return correctly

gpu: Fix crash

---

layers/state_tracker/state_tracker.cpp
tests/unit/sync_object_positive.cpp

Non-zero payload value for imported binary semaphore caused a crash in Semaphore::Retire. We use *internal payload values* for binary semaphores as part of our implementation, but the *payload values provided through the API* (QueueSubmit2) have no meaning for binary semaphores and should be ignored. The main code path generates internal binary payload values, but there is a special case for the imported binary semaphore wait, which allowed API-provided payload to leak into our implementation details.
This also fixes CTS issue found by @ncesario-lunarg  that `dEQP-VK.synchronization2.cross_instance.suballocated.write_fill_buffer_read_copy_buffer.buffer_16384_binary_semaphore_fd` triggers assert about non-zero binary payload.

layers: Ignore non-zero binary semaphore payload

---

layers/core_checks/cc_image.cpp
tests/unit/imageless_framebuffer_positive.cpp

Part of #7795 
This PR fixes the crash, however the validation here should be moved to vkCmdExecuteCommands for imageless framebuffers

layers: Fix imageless framebuffer attachments clear crash

---

layers/vulkan/generated/chassis.cpp
scripts/generators/layer_chassis_generator.py
tests/unit/other_positive.cpp
tests/unit/others.cpp

closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/4349

layers: Report VU for bad vkGetDeviceProcAddr

---

.github/workflows/vvl.yml

for https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/6356
This created artifacts (see example here https://github.com/spencer-lunarg/Vulkan-ValidationLayers/actions/runs/8612254126)
When we merge into `main` and run CI, it will generate binary for anyone who wants to grab them

ci: Add Artifact Uploads

---

layers/chassis/chassis_handle_data.h
layers/chassis/layer_chassis_dispatch_manual.cpp
layers/error_message/error_location.h
layers/error_message/record_object.h
layers/gpu_validation/gpu_state_tracker.cpp
layers/object_tracker/object_lifetime_validation.h
layers/object_tracker/object_tracker_utils.cpp
layers/stateless/sl_cmd_buffer.cpp
layers/stateless/stateless_validation.h
layers/vulkan/generated/chassis.cpp
layers/vulkan/generated/chassis_dispatch_helper.h
layers/vulkan/generated/layer_chassis_dispatch.h
scripts/generators/layer_chassis_dispatch_generator.py
scripts/generators/layer_chassis_generator.py
tests/unit/command_positive.cpp

Currently we were tracking the command buffers for being secondary because in `VkCommandBufferBeginInfo` it says
This is the first a few spots like this, so I created a `chassis::HandleData` object we can put into the `RecordObject`/`ErrorObject` to pass down this information
This basically provides a chassis-level way of doing state tracking, but only passing down the information we care about

layers: Move Secondary CommandBuffer tracking to chassis

---

layers/core_checks/cc_wsi.cpp
layers/state_tracker/image_state.cpp
layers/state_tracker/image_state.h
layers/state_tracker/state_tracker.cpp
tests/framework/layer_validation_tests.h
tests/unit/wsi_positive.cpp

Fixes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/7786 (tested on Granite renderer).
This reworks surface capabilities caching. The result of a surface caps query depends on the surface info's pNext chain, each element can affect results. This solution caches data for two types of queries: surface info's pNext is a) null or b) a single `VkSurfacePresentModeEXT` structure. For other types of pNext chains caching is not performed and corresponding queries will skip the cache and run regular Vulkan API calls.

layers: Refactor surface caps caching

---

layers/core_checks/cc_render_pass.cpp
layers/core_checks/core_validation.h
tests/unit/render_pass.cpp

This PR adds validation for `VUID-VkSubpassBeginInfo-contents-09382`, which is for `vkCmdBeginRenderPass2`, but a similar VUID for `vkCmdBeginRenderPass` seems to be missing from the spec

Add vuid 09382, validate render pass contents

---

layers/state_tracker/image_state.h
layers/state_tracker/state_tracker.cpp

Based on this comment and the following discussion: https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/7820#discussion_r1559123395
@spencer-lunarg @Eearslya please let me know if this explanation makes sense.

layers: Add explanation why to cache surface caps

---

layers/vulkan/generated/chassis.cpp
layers/vulkan/generated/chassis_dispatch_helper.h
scripts/generators/layer_chassis_generator.py

I noticed in https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/7817 that we have a single "manual function" for the chassis logic but we only need a subset for the `chassis_dispatch_helper.h` file because it has some functions that can still make use of the `intercept_vectors`

scripts: Add InterceptId where possible

---

BUILD.gn
layers/CMakeLists.txt
layers/core_checks/cc_state_tracker.cpp
layers/core_checks/cc_state_tracker.h
layers/core_checks/cc_synchronization.cpp
layers/core_checks/core_validation.h

Due to memory usage (https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/7387) the `CommandBuffer` state object should be broken up as everyone inherent a lot of  unnecessary data

layers: Create a core::CommandBuffer

---

layers/vulkan/generated/chassis.cpp
scripts/generators/layer_chassis_generator.py
tests/unit/other_positive.cpp
tests/unit/others.cpp

was discussed today in WG call
This should be a warning since this table shows it returns null

layers: Move UNASSIGNED to Warning

---

layers/chassis/layer_chassis_dispatch_manual.cpp

For things like
```c++
vku::safe_VkDescriptorUpdateTemplateCreateInfo var_local_pCreateInfo;
vku::safe_VkDescriptorUpdateTemplateCreateInfo *local_pCreateInfo = nullptr;
```
we need to have both variables, so we generate it for everyone, but these are manual and don't need it

layer: Cleanup of manual dispatch variables

---

layers/core_checks/cc_ray_tracing.cpp
tests/framework/ray_tracing_objects.cpp
tests/framework/ray_tracing_objects.h
tests/unit/ray_tracing.cpp
tests/unit/ray_tracing_positive.cpp

VUID-vkBuildAccelerationStructuresKHR-scratchData-03704
The range of memory backing the scratchData member of any element of pInfos that is accessed by this command must not overlap the memory backing the scratchData member of any other element of pInfos, which is accessed by this command

layers: Add 03704 for host accel structs builds

---

layers/gpu_validation/gpu_record.cpp
layers/gpu_validation/gpu_subclasses.h
layers/gpu_validation/gpu_validation.cpp
layers/gpu_validation/gpu_validation.h
layers/state_tracker/cmd_buffer_state.cpp
layers/state_tracker/pipeline_state.h
tests/unit/gpu_av.cpp
tests/unit/gpu_av_descriptor_indexing.cpp
tests/unit/gpu_av_descriptor_indexing_positive.cpp

closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/7737
Before we only updated the `binding_req` (that part that maps the `OpVariable` from the pipeline to the `VkImage` in the descriptor set) at `vkCmdBindDescriptorSets` time, this caused the following to produce a false error
```
vkCmdBindPipeline(); // bad
vkCmdBindDescriptorSets();
vkCmdBindPipeline(); // good
vkCmdDraw()
```
This now updates the last `vkCmdBindDescriptorSets` if there is a `vkCmdBindPipeline` after it

gpu: Fix Descriptor Indexing assuming pipeline bound first

---

docs/gpu_validation.md
layers/VkLayer_khronos_validation.json.in
layers/gpu_validation/debug_printf.cpp
layers/gpu_validation/gpu_settings.h
layers/gpu_validation/gpu_setup.cpp
layers/gpu_validation/gpu_validation.cpp
layers/layer_options.cpp
layers/vk_layer_settings.txt

- All GPU-AV settings now start with `VK_LAYER_GPUAV_` as it caused wasted time to assume this was the case as a few settings didn't follow this
- Deprecation warning given to the few that were wrong
- It is not obvious how `vk_layer_settings` will underneath append the `VK_LAYER_`  suffix and uppercase the key name, so now all the names in `layer_options.cpp` match the actual environment variable name used to set it

layers: Unify all GPU-AV settings

---

layers/core_checks/cc_image.cpp
tests/unit/dynamic_rendering_local_read_positive.cpp

#7799 did not fix everything
From spec:
> colorAttachment is only meaningful if VK_IMAGE_ASPECT_COLOR_BIT is set in aspectMask, in which case it is an index into the currently bound color attachments
So this check needs to be skipped if the aspect does not contain `VK_IMAGE_ASPECT_COLOR_BIT`

layers: Fix clearing depth attachment with dynamic rendering local read

---

layers/core_checks/cc_image.cpp

This change reflects the spec fix applied in the latest revision of the Vulkan spec whereas usage flag requirements for video formats is relaxed in case `VK_IMAGE_CREATE_EXTENDED_USAGE_BIT` is used.

layers: Relax usage requirements for video formats

---

tests/framework/barrier_queue_family.cpp
tests/framework/binding.cpp
tests/framework/binding.h
tests/unit/buffer.cpp
tests/unit/buffer_positive.cpp
tests/unit/command_positive.cpp
tests/unit/image_positive.cpp
tests/unit/query.cpp
tests/unit/ray_tracing_nv.cpp
tests/unit/sync_object_positive.cpp
tests/unit/sync_val.cpp
tests/unit/sync_val_positive.cpp

Replaces *get family index -> get queue from family* sequence with directly requesting the queue.

tests: Add helpers to get queue directly

---

layers/core_checks/cc_cmd_buffer_dynamic.cpp
layers/drawdispatch/drawdispatch_vuids.cpp
layers/drawdispatch/drawdispatch_vuids.h
tests/unit/dynamic_state.cpp

VUID-vkCmdDraw-None-04912 has been removed from the Vulkan spec because it's redundant. Remove the check from the layer and update the tests.

layer: Stop checking removed VU

---

tests/unit/amd_best_practices.cpp

The VkAmdBestPracticesLayerTest.ImageToImageCopy was mistakently setting the image create usage to a layout define. Both usage and layout seem to be needed, so set them both to the appropriate values.

tests: Fix image usage/layout confusion

---

tests/framework/binding.cpp
tests/framework/binding.h
tests/framework/render.cpp
tests/framework/render.h
tests/unit/sync_object_positive.cpp
tests/unit/sync_val.cpp

Sometimes the tests check for the second graphics queue if 2 queues are needed.
This can decrease test coverage. For example, AMD windows drivers usually expose a single graphics queue.
This PR adds one more helper queue in addition to the default one. It will be a graphics queue if the second graphics queue is available, otherwise it's a compute if available, then transfer. Null when only 1 queue is exposed.
It can be used in situations when the test can work with the queues with different capabilities. Even if the queue with a specific capability is needed it might be easier to check`m_second_queue`'s  `VkQueueFlags` than iterating over `QueuesWithXXXCapability()` in order to skip the default queue.

tests: Add second helper queue

---

layers/core_checks/cc_pipeline_graphics.cpp
layers/core_checks/core_validation.h
layers/state_tracker/pipeline_state.cpp
layers/state_tracker/pipeline_state.h
tests/unit/dynamic_state.cpp
tests/unit/multiview.cpp
tests/unit/vertex_input.cpp

from https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/6570
- Move logic to a dedicated `ValidateVertexAttribute` function
- wrap logic with a check for `robustBufferAccess` support
cc @ziga-lunarg

layers: Add robustness check to drawn time vertex buffer

---

layers/core_checks/cc_shader_interface.cpp
layers/state_tracker/shader_module.cpp
layers/state_tracker/shader_module.h

closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/7845
its been on my todo list for a while to clean this up
before
```
vkCreateGraphicsPipelines(): pCreateInfos[0] (SPIR-V Interface) Type mismatch on Location 4 Component 0, between
VK_SHADER_STAGE_VERTEX_BIT stage:
pointer to Output ->
struct of {
array[2] of struct of {
array[2] of vec4 of float32
float32
vec3 of 	float64
}
sint32
}
VK_SHADER_STAGE_FRAGMENT_BIT stage:
pointer to Input ->
struct of {
array[2] of struct of {
array[2] of vec4 of float32
float32
vec4 of 	float32
vec2 of 	float32
}
sint32
}
```
now (note, variable names are `a`, `b`, `c`, etc) 
```
vkCreateGraphicsPipelines(): pCreateInfos[0] (SPIR-V Interface) Type mismatch on Location 4 Component 0, between
VK_SHADER_STAGE_VERTEX_BIT stage:
Variable …
```

layers: Improve Shader Interface errors

---

docs/creating_tests.md
layers/vk_layer_config.cpp
layers/vk_layer_config.h
tests/CMakeLists.txt
tests/README.md
tests/framework/config.h.in
tests/framework/test_framework.cpp

Changes:
* Add mechanism to set VK_LAYER_PATH automatically if it isn't set or if it is set but doesn't contain a path to a valid layer manifest.
* Search VK_ADD_LAYER_PATH in addition to VK_LAYER_PATH when looking for the layer manifest
* Enhance searching of the layer manifest to include directory support rather than only allowing files
* Enhance VK_ICD_FILENAMES & VK_DRIVER_FILES checking to support files in addition to the existing support for directories

test: Set VK_LAYER_PATH automatically if missing

---

scripts/known_good.json

grabs changes from
https://github.com/KhronosGroup/Vulkan-Utility-Libraries/pull/201
cc @ziga-lunarg (messed up on the git)

scripts: Update VUL

---

layers/core_checks/cc_pipeline_graphics.cpp
layers/drawdispatch/drawdispatch_vuids.cpp
layers/drawdispatch/drawdispatch_vuids.h
tests/unit/dynamic_rendering.cpp
tests/unit/dynamic_rendering_positive.cpp

Adds `VUID-vkCmdDraw-None-09642`/`VUID-vkCmdDraw-None-09643` which were added in 1.3.283 spec

layers: Add Draw VK_EXT_legacy_dithering VU

---

layers/core_checks/cc_render_pass.cpp
tests/unit/render_pass.cpp

VUID for Renderpass 1 (`VUID-vkCmdBeginRenderPass-contents-09640`) was added in 1.3.283 (https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/6595)

layers: Label RenderPass 1 VUID for nestedCommandBuffer

---

layers/stateless/sl_buffer.cpp
tests/unit/protected_memory.cpp

`VUID-VkBufferCreateInfo-flags-09641` was added in 1.3.283 spec

layers: Add Protected buffer usage flag combo

---

layers/core_checks/cc_pipeline_graphics.cpp
tests/unit/dynamic_state.cpp

Adds `VUID-VkGraphicsPipelineCreateInfo-pDynamicState-09639` from 1.3.283 spec

layers: Add dynamic state VK_EXT_conservative_rasterization

---

layers/layer_options.h

Broken due to the VALIDATION_CHECK_DISABLE_SYNCHRONIZATION_VALIDATION_QUEUE_SUBMIT changes toggled from enable to disable:
Fixed with this branch:

layers: Fix CreateInstance layer setting msg

---

layers/gpu_validation/debug_printf.cpp
layers/gpu_validation/debug_printf.h
layers/gpu_validation/gpu_error_message.cpp
layers/vulkan/generated/chassis.cpp
layers/vulkan/generated/chassis.h
scripts/generators/layer_chassis_generator.py

(plan to do with GPU-AV, but starting easy with DebugPrintF)
When we want to abort in GPU-AV/DebugPrintf it can be annoying to try and going `if (aborted) return;` everywhere. This adds a `ReleaseDeviceDispatchObject` that will remove the object from the chassis so that no function calls are ever called into after an abort

printf: Add way to disconnect from chassis on abort

---

tests/unit/shader_limits.cpp
tests/unit/shader_limits_positive.cpp
tests/unit/shader_object.cpp

The new version of glslang in https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/7872 caused issues, worked around it with just injecting SPIR-V

tests: Fix MaxSampleMaskWords

---

tests/unit/sync_object.cpp

Fixes #7885.
The previously used wait value of 5 is already signalled (at the semaphore creation time). This makes the queue submission immediately executable and may signal the semaphore[0] = 20 at any time now.
The queue will race with the subsequent signal operations. If queue signals first then the subsequent semaphore[0] = 25 becomes a valid use (no pending signal operations, change from 20 to 25) rather than a violation of the VUID-VkSemaphoreSignalInfo-value-03259.
The next signal of the semaphore[0] = 15 becomes invalid use violating the VUID-VkSemaphoreSignalInfo-value-03258 (change from 25 back to 15).
Change-Id: I2768ef5c6b3868f00965ac7d881ad1f6ac7ee515

tests: Avoid race in NegativeSyncObject.Sync2SignalSemaphoreValue

---

tests/framework/binding.cpp
tests/framework/binding.h
tests/framework/render.cpp
tests/framework/render.h
tests/unit/best_practices.cpp
tests/unit/device_queue.cpp
tests/unit/protected_memory.cpp
tests/unit/protected_memory_positive.cpp
tests/unit/query_positive.cpp
tests/unit/sync_object.cpp
tests/unit/sync_object_positive.cpp
tests/unit/sync_val.cpp

each test on the Windows NVIDIA machine takes 170ms to run at a minimum, it was discovered this is from using the max number of `queueCount` when creating a `VkDevice`
```
// Baseline number
Took 8 min 8 sec on tcubuand3
Took 5 min 35 sec on tcubumes6
Took 31 min on tcwinnvi6
Took 14 min on tcubunvi
// With this PR
Took 8 min 30 sec on tcubuand3
Took 4 min 31 sec on tcubumes6
Took 24 min on tcwinnvi6
Took 10 min on tcubunvi
```

tests: Don't use max queueCount

---

layers/state_tracker/cmd_buffer_state.cpp
tests/unit/query_positive.cpp

Closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/7874
This PR is another solution for https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/7880 PR kindly provided by @akeley98NV. This PR removes the source of a problem. The test is based on the test from the initial PR.
I made further analysis and it should be safe to remove the lock. In the comment from the original PR (https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/7880#issuecomment-2073370057) I mentioned external synchronization but that's not about it and should be ignored. It is about the requirements for pending command buffers.
For each `vkCmd*` we call `ValidateCmd` function which reports validation error if the command buffer is in the *pending* state.
`updatedQueries`  is modified by …

layers: Fix secondary command buffer query deadlock

---

layers/drawdispatch/descriptor_validator.cpp

Avoids printing dot twice as LogError adds one in string interpolation, matching `vkCmdPushDescriptorSetKHR` case, fixing the typo in current output of: vkCmdBindDescriptorSets doesn't match actual image layout at time descriptor is used..

layers: Fix typo in VUID 00344

---

scripts/known_good.json
tests/unit/nvidia_best_practices.cpp
tests/unit/pipeline_positive.cpp

closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/5931
Applying VUL change for https://github.com/KhronosGroup/Vulkan-Utility-Libraries/pull/207

layers: Fix pMultisampleState ignore logic

---

layers/state_tracker/state_tracker.cpp
layers/state_tracker/state_tracker.h

vkLatencySleepNV will trigger a semaphore signaling which is waited on by an application with vkWaitSemaphores. Currently when applications with Low Latency 2 support are run with VVL, due to the lack of semaphore tracking in vkLatencySleepNV, vkWaitSemaphores will timeout. This Pull Request adds tracking to vkLatencySleepNV which resolves the issue.

layers: Add semaphore tracking to LatencySleepNV

---

layers/gpu_validation/gpu_resources.h
layers/gpu_validation/gpu_subclasses.cpp
layers/gpu_validation/gpu_subclasses.h

After acquiring a command buffer's lock to call PostProcess on it, its resources could have been freed by another thread in the meantime, so PostProcess should account for that.
Bug showed up while replaying a capture of Doom 2
I looked at making sure we just do not end up having "empty" command buffers in `gpu_tracker::Queue::retiring_` but not sure it is worth to go down that route.
Would love @jeremyg-lunarg's eyes on that PR!

gpu: Fix concurrent access of cmb buffer resources

---

docs/creating_tests.md
tests/CMakeLists.txt
tests/framework/test_framework.cpp

Occassionally when switching between different build types in a multi-config build system would the config.h file not get copied properly. This is an inhenrent flaw in the solution used to locate build artifacts. By using a compiler definition, the correct header will always be used no matter what.

build: Fix incremental builds using wrong VK_LAYER_PATH

---

layers/gpu_validation/gpu_validation.cpp

This crashes Dota2, I added this logic in https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/7838 but clearly something is not 100% correct
There was no false positive given when doing this with Dota2, so seemed safe for now to just remove the crashing

gpuav: Fix crash in dota2

---

layers/best_practices/bp_render_pass.cpp
layers/core_checks/cc_cmd_buffer_dynamic.cpp
layers/core_checks/cc_drawdispatch.cpp
layers/drawdispatch/descriptor_validator.cpp
layers/state_tracker/cmd_buffer_state.cpp
layers/state_tracker/cmd_buffer_state.h
tests/unit/android_external_resolve.cpp
tests/unit/dynamic_state.cpp
tests/unit/dynamic_state_positive.cpp

fixes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/7327 (and the CTS tests in `dEQP-VK.pipeline.monolithic.extended_dynamic_state.misc.`)
We never had a way to know which attachments where depth vs stencil vs resolve vs color when it came to dynamic rendering
with some cleanup of the code, this logic is now all contained

Check attachment depending on type

---

layers/VkLayer_khronos_validation.json.in
layers/gpu_validation/gpu_record.cpp
layers/gpu_validation/gpu_settings.h
layers/gpu_validation/gpu_setup.cpp
layers/gpu_validation/gpu_subclasses.cpp
layers/gpu_validation/gpu_validation.cpp
layers/gpu_validation/gpu_validation.h
layers/layer_options.cpp
layers/layer_options.h

New settings as seen in VkConfig:
Also cleaned up `layer_options.h` a bit, most important thing was to remove `#include "gpu_validation/gpu_settings.h"`

gpu: Rework settings

---

tests/framework/binding.h

It's unsafe. Can hide errors when an argument is of a wrong type but conversion operator finds a way.

tests: Remove operator bool

---

layers/VkLayer_khronos_validation.json.in
layers/error_message/logging.cpp
layers/error_message/logging.h
layers/layer_options.cpp
layers/layer_options.h
layers/vk_layer_settings.txt
layers/vulkan/generated/chassis.cpp
scripts/generators/layer_chassis_generator.py
tests/unit/others.cpp

successor of https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/7943
The whole formatting of the error messages needs to be reworked, I am using this as energy to start to foundation for that future change.
This adds a simple way to print the `pApplicationName` which is helpful for something like Android which now has many processes (such as surface flinger and skia) using Vulkan to know which app is printing the error messages

layers: Option to print application name

---

layers/core_checks/cc_descriptor.cpp
tests/unit/descriptors.cpp

Fix a crash instead of reporting VUID-VkWriteDescriptorSet-dstBinding-00316

layers: Fix when updating binding never created in layout

---

layers/vulkan/generated/chassis.cpp
scripts/generators/layer_chassis_generator.py
tests/unit/others.cpp
tests/unit/query.cpp

Hit this by accident, but currently a null `pCreateInfo` in `vkCreateBuffer` crashed from where the chassis deference it
added tests for all Vulkan 1.0 creation of objects (which probably should have been done years ago)

layers: Fix crash from null pCreateInfo

---

layers/core_checks/cc_shader_interface.cpp
tests/unit/shader_interface.cpp
tests/unit/shader_interface_positive.cpp

Temp false positive patch for https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/7923 
I plan to go back in and just redo all the logic as I realize there is a lot of gaps with how we are checking Fragment output                                                                                                                                                                                                                                                                    matching. But want to at least remove false positive for the new SDK

Prevent false positive when using fragment output array

---

tests/framework/binding.h
tests/unit/debug_extensions_positive.cpp
tests/unit/ray_tracing.cpp
tests/unit/ray_tracing_positive.cpp
tests/unit/sync_object.cpp
tests/unit/sync_object_positive.cpp

UNIFORM_BUFFER looked too specific and uniform buffers still can be a bit special for hardware. The tests usually specify buffer usage explicitly. There were only 9 places that used default values.

tests: Remove vkt::Buffer default usage

---

tests/framework/binding.cpp
tests/framework/binding.h
tests/framework/queue_submit_context.cpp
tests/framework/render.cpp
tests/framework/render.h
tests/unit/dynamic_rendering.cpp

When the second queue is used, an associated command pool/buffer is often needed.

tests: Add second command pool/buffer

---

layers/gpu_validation/gpu_constants.h
layers/gpu_validation/gpu_setup.cpp
layers/gpu_validation/gpu_subclasses.cpp
layers/gpu_validation/gpu_validation.cpp

closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/7957
These use to live in spirv-tools `instrument.hpp` but we can now safely move to VVL

gpuav: Use internal stream out constants

---

scripts/generate_spirv.py

Without this, you are required to re-run clang-format on all generated spirv cpp files

scripts: Fix generate_spirv.py needing clang-format

---

tests/framework/test_framework.cpp

These were never updated when we made enabling Core Checks in tests the default

tests: Fix option descriptions

---

layers/core_checks/cc_render_pass.cpp
layers/core_checks/core_validation.h
tests/unit/subpass.cpp
tests/unit/sync_val.cpp

Takes care of 3 `UNASSIGNED-CoreValidation-DrawState-InvalidRenderpass`

layers: Cleanup old subpass UNASSIGNED VUs

---

layers/core_checks/cc_cmd_buffer_dynamic.cpp
tests/device_profiles/max_profile.json
tests/unit/vertex_input_positive.cpp

Extension is just allowing 1 shader interface VU to be allowed

layers: Add VK_EXT_legacy_vertex_attributes

---

tests/unit/object_lifetime.cpp
tests/unit/object_lifetime_positive.cpp
tests/unit/push_descriptor.cpp
tests/unit/tooling.cpp

as a reaction from https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/7975 I wanted to make sure we had good test coverage and realize we do test these object lifetime cases pretty well already

tests: Add extra object lifetime tests

---

layers/stateless/sl_pipeline.cpp
layers/stateless/sl_ray_tracing.cpp
layers/stateless/stateless_validation.h

currently most the stateless validation for compute/rtx was not checking flags if passed in via `VkPipelineCreateFlags2KHR` (added in `VK_KHR_maintenance5`)
This unifies how all the pipeline creation in stateless check for creation flags

layers: Use VkPipelineCreateFlags2KHR for stateless pipeline

---

layers/core_checks/cc_buffer.cpp
layers/core_checks/cc_copy_blit_resolve.cpp
layers/core_checks/cc_query.cpp
layers/core_checks/core_validation.h
layers/vulkan/generated/command_validation.cpp
scripts/generators/command_validation_generator.py

Instead of passing ad-hoc strings down, this separates `ValidateCmdQueueFlags` into a  `HasRequiredQueueFlags` and `DescribeRequiredQueueFlag` logic
While it seems like more code, it prevents having to pass strings around while we are still validating and saves that until we need to print the error out

layers: Refactor RequiredQueueFlags check

---

layers/sync/sync_submit.cpp
layers/sync/sync_submit.h
tests/unit/sync_val_positive.cpp

Made mistake here: https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/7985. Of course it's possible to signal and then wait on the semaphore in the same submission (was confused by my own pseudocode which was not detailed enough).
This PR reverts that change, adds regression test, and makes one more less ambitious change.

sync: Simplify SignaledSemaphores::Unsignal v2

---

tests/unit/gpu_av_ray_tracing_positive.cpp
tests/unit/ray_tracing_positive.cpp

clang-format doesn't touch anything in `R"` strings so these weren't formatted
From
to

tests: Format glsl strings

---

tests/CMakeLists.txt
tests/framework/binding.cpp
tests/framework/binding.h
tests/framework/layer_validation_tests.h
tests/framework/pipeline_helper.cpp
tests/framework/pipeline_helper.h
tests/framework/render.cpp
tests/framework/render.h
tests/framework/shader_helper.h
tests/framework/shader_object_helper.cpp
tests/framework/shader_object_helper.h
tests/unit/debug_printf.cpp
tests/unit/gpu_av_oob.cpp
tests/unit/gpu_av_shader_object_positive.cpp
tests/unit/shader_object.cpp
tests/unit/shader_object_positive.cpp

We will want to have more and more Shader Object tests for GPU-AV and to help with that, created some helpers to allow things other than `NegativeShaderObject`/`PositiveShaderObject` to use them

Cleanup for Shader Object tests

---

layers/gpu_validation/gpu_setup.cpp
layers/gpu_validation/gpu_subclasses.cpp

There is no reason I know of that these should be excluding geometry/tess stages as GPU-AV should work for all stages
cc @arno-lunarg

gpuav: Support all stages for gpuav

---

layers/core_checks/cc_device_memory.cpp
layers/state_tracker/buffer_state.cpp
layers/state_tracker/buffer_state.h
layers/state_tracker/image_state.cpp
layers/state_tracker/image_state.h
tests/unit/external_memory_sync.cpp
tests/unit/external_memory_sync_positive.cpp

from https://gitlab.khronos.org/vulkan/Vulkan-ValidationLayers/-/issues/35
These VUs say `identical` but it didn't mean the VkHandle, but the creation was the same
There is still a discussion which pNext this is suppose to account for, but for now covered the main cases

layers: Fix Image/Buffer comparing

---

layers/containers/custom_containers.h
layers/sync/sync_submit.cpp
layers/sync/sync_submit.h
layers/sync/sync_validation.cpp
layers/sync/sync_validation.h
tests/unit/sync_val_positive.cpp

This splits `SignaledSemaphores` into two parts. The part that is
repsonsible for collecting updates is put into a separate type -
`SignaledSemaphoresUpdate`. The pars that is left that's the new
`SignaledSemaphores` and is just a map.
This simplifies design and restricts possible operations that can
be done with each type since they are used in different contexts
and have different interfaces.

sync: Add SignaledSemaphoresUpdate

---

scripts/known_good.json
tests/unit/dynamic_rendering_positive.cpp

closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/8015 with https://github.com/KhronosGroup/Vulkan-Utility-Libraries/pull/210

layers: Fix pMultisampleState

---

tests/unit/other_positive.cpp
tests/unit/others.cpp

Both tests were wrong (from https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/2457)

tests: Fix DeviceIDPropertiesExtensions tests

---

layers/gpu_validation/gpu_record.cpp
layers/gpu_validation/gpu_settings.h
layers/gpu_validation/gpu_setup.cpp

Closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/8020
Take into account GPU AV settings
Tested on lightweight VK, with this change caching works as expected, removing false positives

gpu: Fix shader caching

---

layers/gpu_validation/debug_printf.cpp
layers/gpu_validation/debug_printf.h
layers/gpu_validation/gpu_error_message.cpp
layers/gpu_validation/gpu_setup.cpp
layers/gpu_validation/gpu_shader_instrumentor.cpp
layers/gpu_validation/gpu_shader_instrumentor.h
layers/gpu_validation/gpu_state_tracker.cpp
layers/gpu_validation/gpu_subclasses.cpp
layers/gpu_validation/gpu_validation.cpp
layers/vulkan/generated/chassis.cpp
layers/vulkan/generated/chassis.h
scripts/generators/layer_chassis_generator.py
tests/unit/debug_printf.cpp
tests/unit/gpu_av.cpp

- rename `ReportSetupProblem` to `InternalError` (as it does more then just during setup)
- Call `ReleaseDeviceDispatchObject` that will prevent any more `Pre/Post` chassis calls from getting called
For `aborted` we still need it, but not to "gaurd" a function, but to get out of a function, example
```
void DeepDownFunction() {
AllocationOfThing();
if (aborted) return;
}
```
We might decide in the future to do a `[[no-discard]]` bool return from these functions, but that is orthogonal to the scope of this change

gpu: Have InternalError disconnect from chassis

---

layers/best_practices/best_practices_error_enums.h
layers/best_practices/best_practices_validation.h
layers/best_practices/bp_cmd_buffer.cpp
layers/best_practices/bp_instance_device.cpp
layers/best_practices/bp_state.h
layers/best_practices/bp_synchronization.cpp
layers/containers/custom_containers.h
layers/core_checks/cc_queue.cpp
layers/core_checks/cc_state_tracker.cpp
layers/core_checks/cc_synchronization.cpp
layers/core_checks/core_validation.h
layers/state_tracker/cmd_buffer_state.cpp
layers/state_tracker/cmd_buffer_state.h
layers/state_tracker/state_tracker.cpp
layers/sync/sync_submit.cpp
tests/framework/binding.cpp
tests/framework/binding.h
tests/framework/layer_validation_tests.h
tests/unit/best_practices.cpp
tests/unit/best_practices_positive.cpp

This tracks event state within a single command buffer, in the secondary command buffers, and between queue submissions. Some parts of this can migrate later to core validation when needed for event related validation.
Closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/8004

bp: Report signaling already signaled event

---

layers/core_checks/cc_cmd_buffer_dynamic.cpp
layers/state_tracker/pipeline_state.cpp
layers/state_tracker/pipeline_state.h
tests/unit/dynamic_state_positive.cpp

closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/8028
Create a proper way to get the `VkPrimitiveTopology` at draw time

layers: Fix VkPrimitiveTopology check

---

docs/shader_validation.md
layers/core_checks/cc_device.cpp
layers/core_checks/cc_spirv.cpp
layers/core_checks/core_validation.h
layers/gpu_validation/debug_printf.cpp
layers/utils/shader_utils.cpp
layers/utils/shader_utils.h
tests/framework/shader_helper.h
tests/framework/test_framework.h
tests/unit/shader_spirv.cpp
tests/unit/shader_spirv_positive.cpp

closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/8031
Before we cached the `spirv-val` run by the version of `SPIRV-Tools`, but as shown from the tests added, the output of `spirv-val` is determined by the `spvtools::ValidatorOptions` we pass in, so we need to also account for that when handling the caching

layers: Fix Shader Cache to account for settings

---

layers/vulkan/generated/stateless_validation_helper.cpp
scripts/generators/stateless_validation_helper_generator.py
tests/unit/other_positive.cpp
tests/unit/others.cpp

`VkPhysicalDeviceIDProperties` is provided from multiple extensions. Add handling of this cornercase into layers. Fix tests that were defective to discover it.

Fix VkPhysicalDeviceIDProperties sType validation

---

layers/core_checks/cc_cmd_buffer_dynamic.cpp
layers/drawdispatch/descriptor_validator.cpp
layers/state_tracker/cmd_buffer_state.cpp
layers/state_tracker/cmd_buffer_state.h

This is mostly for Shader Object, but found nicer to read
```
cb_state.IsDynamicStateSet(CB_DYNAMIC_STATE_SCISSOR_WITH_COUNT)
```
over
```
cb_state.dynamic_state_status.cb[CB_DYNAMIC_STATE_SCISSOR_WITH_COUNT])
```
mostly with the fact that `dynamic_state_status.cb` is used differently between Pipeline and Shader Object because you can have pipelines that invalidate it and pipeline already has it's own `IsDynamic()` helper

layers: Add IsDynamicStateSet helper

---

layers/core_checks/cc_shader_object.cpp
layers/core_checks/cc_spirv.cpp
layers/core_checks/core_validation.h

Adds `ValidationCache` to Shader Object so we don't repeat running `spirv-val` on binaries across multiple runs

layers: Add Shader Val Cache for ShaderObject

---

layers/core_checks/cc_cmd_buffer_dynamic.cpp
layers/core_checks/cc_pipeline_graphics.cpp
layers/core_checks/core_validation.h
layers/state_tracker/cmd_buffer_state.cpp
layers/state_tracker/cmd_buffer_state.h
layers/state_tracker/state_tracker.cpp
tests/framework/pipeline_helper.h
tests/unit/dynamic_state.cpp
tests/unit/dynamic_state_positive.cpp

For https://github.com/KhronosGroup/Vulkan-Docs/issues/2276 (internal spec change https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/6666)
The following case was never being validated
```
vkCmdSet()
vkCmdBindPipeline() // static
vkCmdBindPipeline() // dynamic
vkCmdDraw()
```
This also adds better error messaging to let the developer know that dynamic state was invalidated

layers: Invalidate dynamic state from previous static state

---

layers/core_checks/cc_cmd_buffer_dynamic.cpp
layers/core_checks/cc_drawdispatch.cpp
layers/core_checks/cc_pipeline.cpp
layers/core_checks/cc_pipeline_graphics.cpp
layers/core_checks/cc_shader_interface.cpp
layers/core_checks/cc_spirv.cpp
layers/drawdispatch/descriptor_validator.cpp
layers/state_tracker/cmd_buffer_state.cpp
layers/state_tracker/pipeline_state.cpp
layers/state_tracker/pipeline_state.h
layers/state_tracker/state_tracker.cpp

This change does
```patch
-  bool IsDynamic(const VkDynamicState state) const { return dynamic_state.test(ConvertToCBDynamicState(state)); }
+  bool IsDynamic(const CBDynamicState state) const { return dynamic_state[state]; }
```
1. the `test()` does a bound check, but since we are using the enum, we can confirm it will be in the `dynamic_state` bitset
2. Half the things are now `CB_DYNAMIC_STATE` and half are `VK_DYNAMIC_STATE`... this is more consistent
3. This saves a `ConvertToCBDynamicState` for a function we use a LOT

layers: Use CBDynamicState

---

layers/best_practices/bp_drawdispatch.cpp
layers/core_checks/cc_cmd_buffer_dynamic.cpp
layers/core_checks/cc_drawdispatch.cpp
layers/core_checks/cc_pipeline.cpp
layers/core_checks/cc_pipeline_graphics.cpp
layers/core_checks/cc_shader_object.cpp
layers/core_checks/core_validation.h
layers/drawdispatch/drawdispatch_vuids.cpp
layers/drawdispatch/drawdispatch_vuids.h
layers/state_tracker/cmd_buffer_state.cpp
layers/state_tracker/pipeline_state.cpp
layers/state_tracker/pipeline_state.h
tests/unit/pipeline.cpp

There was a lot of churn from when we added Shader Object as well as more and more things being moved to draw time... this cleans things up
- Moves things out to functions to avoid massive mega-functions
- For things we know for sure are Pipeline, deference it and pass it around so it is clear we have broke off from the Shader Object code paths
- Consistent naming of functions (ex. `ValidateDraw*`) for draw time things (which implies graphics pipeline bind point)
- Pass around the `vvl::DrawDispatchVuid` instead of `Location` AND `vvl::DrawDispatchVuid` (since we never go more then just the function for that location)

layers: Cleanup Pipeline and ShaderObject Drawtime

---

layers/core_checks/cc_pipeline_graphics.cpp
layers/core_checks/core_validation.h

I want to add some missing VUs for https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/7688
but the `ValidateDrawPipelineDynamicRenderpass` function was kinda all over the place. Created functions to house everything

cleanup of ValidateDrawPipelineDynamicRenderpass

---

layers/gpu_validation/gpu_state_tracker.cpp
layers/gpu_validation/gpu_state_tracker.h
layers/gpu_validation/gpu_subclasses.cpp
layers/gpu_validation/gpu_subclasses.h
layers/state_tracker/fence_state.cpp
layers/state_tracker/queue_state.cpp
layers/state_tracker/queue_state.h
layers/state_tracker/state_tracker.cpp
layers/vulkan/generated/chassis.cpp
scripts/generators/layer_chassis_generator.py
tests/framework/binding.cpp
tests/framework/binding.h
tests/unit/wsi_positive.cpp

Fixes defect in this solution: https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/7694
Closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/8047

layers: Retire present operation when waiting on present fence

---

layers/best_practices/bp_drawdispatch.cpp
layers/core_checks/cc_cmd_buffer_dynamic.cpp
layers/core_checks/cc_drawdispatch.cpp
layers/core_checks/cc_pipeline.cpp
layers/core_checks/cc_pipeline_graphics.cpp
layers/core_checks/cc_shader_interface.cpp
layers/state_tracker/pipeline_state.h
layers/state_tracker/state_tracker.cpp
layers/sync/sync_commandbuffer.cpp
layers/sync/sync_renderpass.cpp
scripts/known_good.json
tests/unit/pipeline.cpp
tests/unit/pipeline_positive.cpp

closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/8051
Change from https://github.com/KhronosGroup/Vulkan-Utility-Libraries/pull/212 included
Spec change for VU in https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/6674
This change hopefully fixes all things `rasterizerDiscardEnable`/`pRasterizationState` related

layers: Fix accessing RasterizationState

---

scripts/android.py
tests/android/AndroidManifest.xml

closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/8045

tests: Update targetSdkVersion version

---

layers/core_checks/cc_drawdispatch.cpp
layers/core_checks/cc_pipeline_graphics.cpp
layers/core_checks/cc_shader_interface.cpp
layers/core_checks/cc_spirv.cpp
layers/core_checks/cc_video.cpp
layers/drawdispatch/descriptor_validator.cpp
layers/state_tracker/shader_module.cpp
layers/state_tracker/shader_module.h
layers/sync/sync_commandbuffer.cpp
tests/device_profiles/max_profile.json
tests/unit/atomics.cpp
tests/unit/descriptors.cpp
tests/unit/descriptors_positive.cpp
tests/unit/protected_memory.cpp
tests/unit/shader_interface.cpp

the `is_written_to`/`is_read_from` was a lie and never worked
This adds proper support to know if the variable is actually accessed. This is important for many upcoming SPIR-V related changes

layers: Rework shader variable access logic

---

BUILD.gn
layers/CMakeLists.txt
layers/core_checks/cc_buffer.cpp
layers/core_checks/cc_cmd_buffer_dynamic.cpp
layers/core_checks/cc_descriptor.cpp
layers/core_checks/cc_device.cpp
layers/core_checks/cc_image.cpp
layers/core_checks/cc_pipeline_compute.cpp
layers/core_checks/cc_pipeline_graphics.cpp
layers/core_checks/cc_pipeline_ray_tracing.cpp
layers/core_checks/cc_query.cpp
layers/core_checks/cc_shader_object.cpp
layers/core_checks/core_validation.h
layers/state_tracker/device_state.cpp
layers/state_tracker/device_state.h

These VUs were added in the 1.3.286 header and just check that creating certain handles is only possible if your device supports a required queue type
Moved it off to its own function as this is a very niche thing and likely not to get hit for most people (but will be helpful for the few who deal with these types of devices)

layers: Add Device Queue Type check

---

layers/gpu/spirv/type_manager.cpp

as spotted out in https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/8073#issuecomment-2143491763
The `OpTypeArray` logic is wrong

gpu: Fix OpTypeArray logic in TypeLength

---

.github/workflows/vvl.yml

Help reduce CI minute pressure by removing our longest run that has caught nothing for us

github: Remove redundant CI matrix

---

tests/framework/layer_validation_tests.cpp

Reverts KhronosGroup/Vulkan-ValidationLayers#8083
Internal CI was never ran and I broke CI :cry:

Revert "Use ALooper_pollOnce instead of ALooper_pollAll"

---

layers/core_checks/cc_cmd_buffer_dynamic.cpp
layers/core_checks/cc_drawdispatch.cpp
layers/core_checks/cc_pipeline_graphics.cpp
layers/core_checks/cc_shader_interface.cpp
layers/core_checks/core_validation.h
layers/drawdispatch/drawdispatch_vuids.cpp
layers/drawdispatch/drawdispatch_vuids.h
layers/state_tracker/cmd_buffer_state.cpp
layers/state_tracker/cmd_buffer_state.h
layers/state_tracker/pipeline_state.h
layers/state_tracker/pipeline_sub_state.cpp
layers/state_tracker/pipeline_sub_state.h
layers/state_tracker/shader_module.cpp
layers/state_tracker/shader_module.h
tests/unit/dynamic_state.cpp
tests/unit/dynamic_state_positive.cpp
tests/unit/shader_interface.cpp
tests/unit/shader_interface_positive.cpp
tests/unit/shader_limits.cpp
tests/unit/shader_limits_positive.cpp
tests/unit/shader_object.cpp

closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/5208
This adds `VUID-vkCmdDraw-maxFragmentDualSrcAttachments-09239`
Now that the dynamic state situation is better, was finally able to add this check in

Add Dual Source Blending check

---

layers/drawdispatch/descriptor_validator.cpp
layers/drawdispatch/drawdispatch_vuids.cpp
layers/drawdispatch/drawdispatch_vuids.h
tests/unit/descriptors.cpp

https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/8058 exposed that the draw time check for feedback loop is broken and giving false positives. The VUs in the spec could use some clarification, so for the time being, removing to not produce false positive while we get time to properly add this back
Tracking in https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/8095

layers: Temporarily remove Drawtime FeedbackLoop check

---

layers/sync/sync_submit.cpp
layers/sync/sync_submit.h
layers/sync/sync_validation.cpp
layers/sync/sync_validation.h

This change ensures that `QueueBatchContext::tag_range_` has a single meaning independent of the context - global range of tags.
Previously, depending on the context, the tag_range was either a local range (just a tag count, begin field was always zero) or a global range (after all initialization was done). This was confusing at times because you need to check the context of the code.
As a bonus reduced LOC and few functions are removed from the interface.

sync: Refactor batch tag_range initialization

---

.github/workflows/vvl.yml

(will create an issue pointing to this if we merge this)
Github Windows machines have been updated
```
Failing
Image: windows-2022
Version: 20240603.1.0
passing
Image: windows-2022
Version: 20240514.3.0
```
We locally tried using `17.10` to compile and still not able to reproduce this
For now removing the running of test from github CI and we are running the internally

github: Suspend running Window Tests

---

docs/synchronization_usage.md

Document that ownership transfer is not supported by syncval. Users rely on the list of supported/unsupported features (https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/8112)
Ownership transfer is planned as the third stage of timeline semahores support (after stage 1 - gpu timeline support, stage 2 - host timeline support). Ownership transfer is not related to timeline semaphores but it is often used in a multi-queue apps that use timeline semaphores, so it's good to add support to be able to fully validate correctness of timeline semaphore synchronization.

docs: Update list of syncval limitations

---

layers/core_checks/cc_device.cpp
layers/core_checks/core_validation.h
layers/gpu/core/gpuav.h
layers/gpu/core/gpuav_setup.cpp
layers/gpu/debug_printf/debug_printf.cpp
layers/gpu/debug_printf/debug_printf.h
layers/gpu/instrumentation/gpu_shader_instrumentor.cpp
layers/gpu/instrumentation/gpu_shader_instrumentor.h
layers/object_tracker/object_lifetime_validation.h
layers/object_tracker/object_tracker_utils.cpp
layers/state_tracker/state_tracker.cpp
layers/state_tracker/state_tracker.h
layers/stateless/sl_buffer.cpp
layers/stateless/sl_cmd_buffer.cpp
layers/stateless/sl_cmd_buffer_dynamic.cpp
layers/stateless/sl_descriptor.cpp
layers/stateless/sl_device_memory.cpp
layers/stateless/sl_image.cpp
layers/stateless/sl_instance_device.cpp
layers/stateless/sl_pipeline.cpp
layers/stateless/sl_ray_tracing.cpp
layers/stateless/sl_render_pass.cpp
layers/stateless/stateless_validation.h
layers/sync/sync_validation.cpp
layers/sync/sync_validation.h
layers/vulkan/generated/chassis.cpp
scripts/generators/feature_requirements.py
scripts/generators/layer_chassis_generator.py
scripts/known_good.json

closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/8110 (with help of https://github.com/KhronosGroup/Vulkan-Utility-Libraries/pull/218)
We have this nice `DeviceFeature` that we fill so we can go `enabled_features.someFeature`
This removes all the stateless checks that were scanning the `pNext` and just uses this instead... which in turn doesn't create a 200+ callstack on deletion of the `VkDevice`
----
Another issue was the use of `safe_VkDeviceCreateInfo` which was used to allow GPU-AV / DebugPrintF to add features, this has been updated

layers: Use DeviceFeature helper instead of pNext checks

---

layers/sync/sync_submit.cpp
layers/sync/sync_submit.h

We have a set of state in `QueueBatchContext` that assists during validation period and then should not be used. Trying to make it local when possible.

sync: Turn QueueBatchContext cmdbuf state into a local variable

---

layers/stateless/sl_cmd_buffer.cpp
layers/stateless/sl_pipeline.cpp
layers/stateless/sl_ray_tracing.cpp
layers/stateless/sl_wsi.cpp
layers/stateless/stateless_validation.h
layers/vulkan/generated/stateless_validation_helper.cpp
scripts/generators/stateless_validation_helper_generator.py

I noticed we were passing in both the sType enum  and string, but we can just go `string_VkStructureType` and save a LOT of strings being passed around

layers: Remove sType string in stateless

---

layers/VkLayer_khronos_validation.json.in
layers/layer_options.cpp
tests/framework/layer_validation_tests.h
tests/unit/gpu_av_positive.cpp

Closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/8027
Also add settings combinations tests. Goal is to make sure we do not crash with common settings combinations.
How it looks in the console:
```
[----------] 16 tests from GpuAvBufferContentValidationSettings/PositiveGpuAVParameterized
[ RUN      ] GpuAvBufferContentValidationSettings/PositiveGpuAVParameterized.SettingsCombinations/gpuav_indirect_draws_buffers_0_gpuav_indirect_dispatches_buffers_0_gpuav_indirect_trace_rays_buffers_0_gpuav_buffer_copies_0
[       OK ] GpuAvBufferContentValidationSettings/PositiveGpuAVParameterized.SettingsCombinations/gpuav_indirect_draws_buffers_0_gpuav_indirect_dispatches_buffers_0_gpuav_indirect_trace_rays_buffers_0_gpuav_buffer_copies_0 (270 ms)
[ RUN      ] …
```

GPU-AV: Fix settings

---

layers/core_checks/cc_image.cpp
tests/unit/command.cpp
tests/unit/command_positive.cpp

Adds two checks from the 1.3.287 spec
- VUID-vkCmdClearColorImage-image-09678
- VUID-vkCmdClearAttachments-None-09679

layers: Add Clearing 64-bit check

---

tests/unit/gpu_av_shader_object_positive.cpp

I got the implicit VU to allow for `VkValidationFeaturesEXT` in Shader Object

tests: Remove pNext warning for VkValidationFeaturesEXT

---

layers/sync/sync_commandbuffer.cpp
tests/unit/sync_val_positive.cpp

Fixes `SYNC_COMPUTE_SHADER_SHADER_STORAGE_WRITE` error in `warcraft_rumble` ANGLE trace https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/8084
That's something that had to be part of https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/8117.

sync: Apply descriptor dynamic offset during Record phase

---

layers/core_checks/cc_cmd_buffer_dynamic.cpp
layers/core_checks/core_validation.h
layers/drawdispatch/drawdispatch_vuids.cpp
layers/drawdispatch/drawdispatch_vuids.h
layers/state_tracker/pipeline_state.cpp
layers/state_tracker/pipeline_state.h
layers/vulkan/generated/dynamic_state_helper.cpp
layers/vulkan/generated/dynamic_state_helper.h
scripts/generators/dynamic_state_generator.py
tests/unit/dynamic_state.cpp
tests/unit/shader_object.cpp

This change is from https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/6345 (and there are more coming, just doing 3 to start)
The overall goal is to combine all the drawtime dynamic state checks from Shader Object and Pipeline into a single check

layers: Create combined dynamic state draw check

---

layers/core_checks/cc_cmd_buffer.cpp
tests/unit/dynamic_rendering.cpp
tests/unit/secondary_command_buffer.cpp

fix from https://github.com/KhronosGroup/Vulkan-Docs/issues/2372 that was in 1.3.287 spec
`VUID-vkCmdExecuteCommands-contents-06018` was reworked and split into
- VUID-vkCmdExecuteCommands-contents-09680
- VUID-vkCmdExecuteCommands-None-09681

layers: Fix subpass contents check

---

BUILD.gn
layers/CMakeLists.txt
layers/best_practices/best_practices_utils.cpp
layers/best_practices/bp_buffer.cpp
layers/best_practices/bp_cmd_buffer.cpp
layers/best_practices/bp_cmd_buffer_nv.cpp
layers/best_practices/bp_copy_blit_resolve.cpp
layers/best_practices/bp_descriptor.cpp
layers/best_practices/bp_device_memory.cpp
layers/best_practices/bp_drawdispatch.cpp
layers/best_practices/bp_framebuffer.cpp
layers/best_practices/bp_image.cpp
layers/best_practices/bp_instance_device.cpp
layers/best_practices/bp_pipeline.cpp
layers/best_practices/bp_ray_tracing.cpp
layers/best_practices/bp_render_pass.cpp
layers/best_practices/bp_synchronization.cpp
layers/best_practices/bp_video.cpp
layers/best_practices/bp_wsi.cpp
tests/unit/amd_best_practices.cpp
tests/unit/arm_best_practices.cpp
tests/unit/best_practices.cpp
tests/unit/nvidia_best_practices.cpp

This removes `best_practices_error_enums.h` which was left there, grew, and has no good value
1. The names in strings don't match up with the variable name
2. Some of these were not ever used
3. We should have an unique ID for each error, having many duplicates makes it hard to know where the error came from
4. I always have to do a double look-up to find which test used it

bp: Remove best_practices_error_enums.h

---

layers/object_tracker/object_tracker_utils.cpp
layers/vulkan/generated/object_tracker.cpp
scripts/generators/object_tracker_generator.py
tests/unit/parent.cpp

VUID will be added here https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/6711
This is adding some (more to come later, will take time) missing checks where we aren't checking if the `VkDevice` is the same between 2 handles used in a command (this has been discussed before in https://gitlab.khronos.org/vulkan/vulkan/-/issues/3553)

layers: Add missing parent VUs

---

layers/stateless/sl_buffer.cpp
layers/stateless/sl_cmd_buffer.cpp
layers/stateless/sl_cmd_buffer_dynamic.cpp
layers/stateless/sl_descriptor.cpp
layers/stateless/sl_image.cpp
layers/stateless/sl_instance_device.cpp
layers/stateless/sl_pipeline.cpp
layers/stateless/stateless_validation.h

We had an extra `safe_VkPhysicalDeviceFeatures2` in stateless, but now can just use `DeviceFeature enabled_features` instead

layers: Remove extra feature struct in stateless

---

layers/gpu/spirv/module.cpp
layers/gpu/spirv/module.h

was getting spirv-val errors from instrumented shaders 
> 1st operand of Capability: operand PhysicalStorageBufferAddresses(5347) requires one of these extensions: SPV_EXT_physical_storage_buffer SPV_KHR_physical_storage_buffer
OpCapability PhysicalStorageBufferAddresses
so now add `OpExtension` if we are adding the `OpCapability` for the user

gpu: Fix missing SPV_KHR_physical_storage_buffer

---

layers/core_checks/cc_descriptor.cpp
layers/stateless/sl_descriptor.cpp
layers/stateless/stateless_validation.h

The `vkCreateSampler` logic was split between CoreChecks and Stateless with no reason. Even inside Stateless it has evidence of it slowly just growing and things slapped together
This moves most logic over to Stateless (because it is) and adds more proper separation of the logic (avoiding a lot of unnecessary  nesting)

layers: Cleanup Sampler in Stateless

---

layers/stateless/sl_utils.cpp
layers/stateless/stateless_validation.h
layers/vulkan/generated/stateless_validation_helper.cpp
scripts/generators/stateless_validation_helper_generator.py

`VkAllocationCallbacks` is always called from the top level function (never nested in a struct)
we have 110 spots doing the same 5 checks.... this moves 2000+ lines of code into a single simple function

layers: Combine all VkAllocationCallbacks calls

---

layers/best_practices/best_practices_validation.h
layers/best_practices/bp_drawdispatch.cpp
layers/best_practices/bp_render_pass.cpp
layers/best_practices/bp_state.h
layers/core_checks/cc_descriptor.cpp
layers/core_checks/cc_drawdispatch.cpp
layers/core_checks/cc_pipeline_graphics.cpp
layers/core_checks/cc_spirv.cpp
layers/gpu/cmd_validation/gpuav_cmd_validation_common.cpp
layers/gpu/cmd_validation/gpuav_cmd_validation_common.h
layers/gpu/debug_printf/debug_printf.cpp
layers/gpu/instrumentation/gpuav_instrumentation.cpp
layers/state_tracker/cmd_buffer_state.cpp
layers/state_tracker/cmd_buffer_state.h
layers/state_tracker/pipeline_layout_state.cpp
layers/state_tracker/pipeline_layout_state.h
layers/state_tracker/pipeline_state.cpp
layers/state_tracker/pipeline_state.h
layers/state_tracker/state_tracker.cpp
tests/unit/gpu_av_positive.cpp

- Push constants state restoration was not working correctly
- Reworked the state tracking, also in best practices
- Added 2 tests, `RestorePushConstants` is not working on my PC, vertex shader runs correctly but no fragment are emitted when doing an indirect draw. Things work as expected when doing a normal draw. It is not related to GPU-AV, as disabling it does not solve the problem. My indirect buffer looks ok, so I will see what CI tells me.
Will see if it closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/8120

gpu: Fix user push constants restore - and state tracking in Core validation

---

layers/best_practices/best_practices_validation.h
layers/best_practices/bp_pipeline.cpp
layers/chassis/chassis_modification_state.h
layers/core_checks/cc_pipeline_compute.cpp
layers/core_checks/cc_pipeline_graphics.cpp
layers/core_checks/cc_spirv.cpp
layers/core_checks/core_validation.h
layers/gpu/debug_printf/debug_printf.cpp
layers/gpu/error_message/gpuav_error_message.cpp
layers/gpu/instrumentation/gpu_shader_instrumentor.cpp
layers/gpu/instrumentation/gpu_shader_instrumentor.h
layers/state_tracker/pipeline_state.cpp
layers/state_tracker/pipeline_state.h
layers/state_tracker/pipeline_sub_state.cpp
layers/state_tracker/pipeline_sub_state.h
layers/state_tracker/shader_module.h
layers/state_tracker/state_tracker.cpp
layers/state_tracker/state_tracker.h
layers/utils/vk_layer_utils.h
layers/vulkan/generated/chassis.cpp
layers/vulkan/generated/spirv_validation_helper.cpp
scripts/generators/layer_chassis_generator.py
scripts/generators/spirv_validation_generator.py
tests/unit/debug_printf.cpp
tests/unit/gpu_av_buffer_device_address.cpp
tests/unit/shader_compute.cpp
tests/unit/shader_spirv.cpp

closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/8103
`VK_KHR_maintenance5` and `VK_EXT_graphics_pipeline_library` added the ability to pass `VkShaderModuleCreateInfo` in the `pNext` of `VkPipelineShaderStageCreateInfo` (removing the need creating a `VkShaderModule`)
We did not have this all plumbed out. This adds full support for it now

Add StatelessData when shader is inline in pNext

---

tests/framework/render.cpp
tests/framework/render.h

`VK_LAYER_TESTS_VALIDATION_FEATURES` was not working and seems to be left from a long time ago
If a dev wanted to set the features it could just use `VK_LAYER_DISABLES`/`VK_LAYER_ENABLES` anyways

tests: Remove VK_LAYER_TESTS_VALIDATION_FEATURES

---

layers/core_checks/cc_drawdispatch.cpp
layers/core_checks/core_validation.h
layers/state_tracker/cmd_buffer_state.cpp
layers/state_tracker/descriptor_sets.cpp
layers/state_tracker/descriptor_sets.h
layers/state_tracker/pipeline_layout_state.cpp
layers/state_tracker/pipeline_layout_state.h
layers/state_tracker/pipeline_state.cpp
layers/state_tracker/pipeline_state.h
tests/unit/descriptors.cpp
tests/unit/multiview.cpp

closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/8100
Create a set of `Describe*` functions to help go over which part of the sets are not compatible
The logic for matching layout compatibility has not changed in years, so I doubt neither will the `Describe*` logic after this (but kept it next to it incase it did)

layers: Improve VU 08600

---

layers/drawdispatch/descriptor_validator.cpp
tests/unit/gpu_av_descriptor_indexing.cpp
tests/unit/gpu_av_descriptor_indexing_positive.cpp

closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/6937
Added 2 tests and found the protected memory check was wrapped in the wrong `if` so fixed that as well

gpu: Fix protected memory on descriptor indexing

---

layers/drawdispatch/descriptor_validator.cpp
layers/state_tracker/shader_module.cpp
layers/state_tracker/shader_module.h
tests/unit/gpu_av_positive.cpp

closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/7677
We didn't have `OpTypeRuntimeArray` tracked well, but as shown, for some VUs, it is just not possible without a lot of GPU-AV tracking, but for now want to just remove the false positive for the edge case and keep things working for the other 99% cases

layers: Fix checks with runtime arrays

---

layers/layer_options.cpp

Fixes possible crashes when using message filters and other string lists.

layers: Avoid using references to out-of-scope strings

---

layers/gpu/core/gpuav.cpp
layers/gpu/core/gpuav_record.cpp

The sources seem to build fine even without them (at least on Linux), so drop these OS-specific includes.

layers: Remove unused unistd.h includes

---

layers/layer_options.cpp
layers/layer_options.h

@jzulauf-lunarg @mark-lunarg so I just came across https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/1976 and there is both a `VK_VALIDATION_FEATURE_ENABLE_SYNCHRONIZATION_VALIDATION` and `VK_VALIDATION_FEATURE_ENABLE_SYNCHRONIZATION_VALIDATION_EXT` that was added. 
But the logic for `SetValidationFeatureEnable2` make no sense because `VK_VALIDATION_FEATURE_ENABLE_SYNCHRONIZATION_VALIDATION` is `0` but it will hit `VK_VALIDATION_FEATURE_ENABLE_GPU_ASSISTED_EXT` first (that is also `0`)
... basically I think I should be able to remove `SetValidationFeatureEnable2`and the original `VK_VALIDATION_FEATURE_ENABLE_SYNCHRONIZATION_VALIDATION`

layers: Remove old Sync Val enable enum

---

layers/gpu/core/gpuav_record.cpp
layers/gpu/core/gpuav_setup.cpp
layers/gpu/debug_printf/debug_printf.cpp
layers/gpu/instrumentation/gpu_shader_instrumentor.cpp
layers/gpu/instrumentation/gpu_shader_instrumentor.h
layers/vulkan/generated/chassis.cpp
scripts/generators/layer_chassis_generator.py

closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/8001
This correctly passes down the `VkDeviceCreateInfo` down to GPU so `enabled_features` works as expected

gpu: Fix enabled_features

---

layers/core_checks/cc_cmd_buffer_dynamic.cpp
layers/core_checks/cc_drawdispatch.cpp
layers/core_checks/cc_pipeline_graphics.cpp
layers/state_tracker/pipeline_state.cpp
layers/state_tracker/pipeline_state.h

We often will need the fragment shader info at drawtime, this adds a proper helper as the info might be from a pipeline and/or `VkShaderEXT`

layers: Add GetFragmentEntryPoint helper

---

layers/best_practices/bp_drawdispatch.cpp
layers/core_checks/cc_cmd_buffer_dynamic.cpp
layers/core_checks/cc_drawdispatch.cpp
layers/core_checks/cc_pipeline_compute.cpp
layers/core_checks/cc_pipeline_ray_tracing.cpp
layers/core_checks/core_validation.h

With the Shader Object path for dynamic state, this is just a cleanup for getting the `vvl::Pipeline` object around as that is our way to help know if shader object is involved or not

Misc Dynamic State Cleanup

---

tests/framework/render.cpp
tests/unit/parent.cpp
tests/unit/wsi.cpp

Without this change, running tests headlessly via SSH will fail to create a valid surface, but report success and subsequently crash in the ICD.

tests: Improve error checking/reporting in test surface creation

---

layers/core_checks/cc_descriptor.cpp
layers/core_checks/cc_spirv.cpp
layers/drawdispatch/descriptor_validator.cpp
layers/drawdispatch/descriptor_validator.h
layers/state_tracker/shader_module.cpp
layers/state_tracker/shader_module.h

closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/8190
When printing out the set/binding, we will now print out the SPIR-V debug name
error now looks like
> vkCmdDispatchIndirect():  the descriptor VkDescriptorSet 0xe88693000000000c[] [Set 0, Binding 0, Index 0, variable "SomeNameInGlsl"] is being used in dispatch but has never been updated via vkUpdateDescriptorSets() or a similar call

layers: Add Variable Debug names to errors

---

tests/framework/error_monitor.cpp
tests/framework/error_monitor.h
tests/unit/gpu_av_indirect_buffer.cpp

Proposal for https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/8140
For now only tried it in NegativeGpuAVIndirectBuffer.DrawCount

tests: Add support for regex lookup in error msg

---

layers/drawdispatch/descriptor_validator.cpp
layers/gpu/descriptor_validation/gpuav_image_layout.cpp

closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/8067
Adds basic null checking around `VkImage`/`VkBuffer` during GPU-Post Process checking

gpu: Null check image/buffers

---

BUILD.gn
layers/CMakeLists.txt
layers/sync/sync_commandbuffer.cpp
layers/sync/sync_commandbuffer.h
layers/sync/sync_stats.cpp
layers/sync/sync_stats.h
layers/sync/sync_validation.h
layers/utils/vk_layer_utils.h

Some basic scaffolding that's enough for the current task, but the plan is to evolve this further.
Stats are disabled by default (`VVL_ENABLE_SYNCVAL_STATS` in `sync_stats.h`)

sync: Add basic stats support

---

layers/gpu/core/gpuav.h
layers/gpu/core/gpuav_record.cpp
layers/gpu/instrumentation/gpu_shader_instrumentor.cpp
layers/gpu/instrumentation/gpu_shader_instrumentor.h
layers/stateless/sl_instance_device.cpp
tests/framework/layer_validation_tests.h
tests/unit/debug_printf.cpp
tests/unit/gpu_av.cpp
tests/unit/gpu_av_positive.cpp

Was trying to solve https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/7178 but first needed to improve the logic around `maxBoundDescriptorSets`
This unifies things between GPU-AV and DebugPrintF as well as adds proper testing to make sure things are working as expected

gpu: Fix maxBoundDescriptorSets logic

---

layers/sync/sync_validation.cpp
layers/sync/sync_validation.h

Adds handles of the resources that are specified directly in the API calls (not everything covered, mostly functions like copies, indirect actions, but not barriers).
The amount of memory used by the handles depends on the game. CS2 max usage: 1-2MB, doom capture: ~10 MB (found by new stats system). The previous refactoring released by a rough estimate 2x more memory than the above numbers.

sync: Store more resource handles for reporting

---

layers/core_checks/cc_wsi.cpp
layers/core_checks/core_validation.h
tests/unit/best_practices.cpp
tests/unit/wsi.cpp

closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/8204
This check was in `ValidateSwapchainPresentModesCreateInfo` which only got called if `VK_EXT_swapchain_maintenance1` was set

layers: Fix PresentMode check being hidden

---

layers/core_checks/cc_pipeline_graphics.cpp
layers/core_checks/core_validation.h
layers/state_tracker/pipeline_state.h
layers/state_tracker/render_pass_state.h
tests/unit/graphics_library.cpp

closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/8202
The main goal was to try and make it clear in the pipeline validation where/when we have a renderpass/dynamic rendering/GPL being used
The core issue was we were mixing up
- `rp_state == NULL` when using something like GPL Vertex Input and there is no state **OR** there is a bad handle to VkRenderPass
- `pipeline.GraphicsCreateInfo().renderPass == VK_NULL_HANDLE` when the passed in value is null (which can be from Dynamic Rendering OR GPL)
- `rp_state && rp_state.UsesDynamicRendering()` which is when the pipeline passes in null, but we created a `vvl::RenderPass` at `vkCmdBeginRendering` and so there is a state object
Core issue is that `vvl::RenderPass` is used for dynamic rendering where there might not be an …

Cleanup RenderPass logic for Pipeline

---

tests/framework/binding.h
tests/framework/layer_validation_tests.h
tests/unit/descriptor_buffer.cpp
tests/unit/descriptor_buffer_positive.cpp
tests/unit/gpu_av.cpp
tests/unit/gpu_av_buffer_device_address.cpp
tests/unit/gpu_av_buffer_device_address_positive.cpp
tests/unit/gpu_av_descriptor_indexing_positive.cpp
tests/unit/gpu_av_oob.cpp
tests/unit/gpu_av_positive.cpp
tests/unit/gpu_av_shader_debug_info.cpp
tests/unit/ray_tracing.cpp
tests/unit/shader_object_positive.cpp

We have many spots we need to create a `VkBuffer` with `VK_BUFFER_USAGE_SHADER_DEVICE_ADDRESS_BIT` (and the memory with `VK_MEMORY_ALLOCATE_DEVICE_ADDRESS_BIT`) in order to get the `VkDeviceAddress`
This reduces this common code to a single line to make it easier to create them

tests: Improve Device Address Buffer creation

---

BUILD.gn
layers/CMakeLists.txt
layers/VkLayer_khronos_validation.json.in
layers/layer_options.cpp
layers/layer_options.h
layers/sync/sync_commandbuffer.cpp
layers/sync/sync_settings.h
layers/sync/sync_stats.h
layers/sync/sync_validation.cpp
layers/sync/sync_validation.h
layers/vulkan/generated/chassis.cpp
layers/vulkan/generated/chassis.h
scripts/generators/layer_chassis_generator.py
tests/framework/layer_validation_tests.h
tests/unit/sync_val.cpp
tests/unit/sync_val_positive.cpp

One more PR to track resource handles for submit time validation. This adds the resource handles referenced by the descriptors. New option `sync_report_descriptor_resources` controls this feature (disabled by default).
The previous PRs added handle reporting for handles specified directly through API commands, as in `vkCmdCopyBuffer(buffer_a, buffer_b)`. Those handles have fixed and small memory footprint and they are always collected.
Shader can reference a lot of resources and it can take significant amount of memory depending on the application. That's the reason configuration option is introduced. Some numbers for the required amount of memory for descriptor resource handles from the test sessions: CS2: 70 Mb, Doom eternal: 600 Mb.
The next PR will use the information about tracked …

sync: Report descriptor resources

---

scripts/vk_validation_stats.py

In html and csv output cases the vk_validation_stats.py script will print out the VUID text as the last column. However, using text output mode the "ext" field was printed previously.

scripts: Print VUID text correctly in vk_validation_stats.py

---

layers/core_checks/cc_pipeline_graphics.cpp
layers/core_checks/core_validation.h
tests/unit/pipeline.cpp
tests/unit/pipeline_positive.cpp
tests/unit/pipeline_topology.cpp
tests/unit/pipeline_topology_positive.cpp

There were a few places were we were checking the value of the pipeline state, but it should have been ignore because the corresponding `VK_DYNAMIC_STATE_*` was used

layers: Ignore pipeline state with dynamic state

---

layers/core_checks/cc_device.cpp
layers/state_tracker/pipeline_state.h
layers/vulkan/generated/chassis.cpp
layers/vulkan/generated/layer_chassis_dispatch.cpp
scripts/generate_source.py
scripts/generators/base_generator.py
scripts/generators/layer_chassis_dispatch_generator.py
scripts/generators/layer_chassis_generator.py
tests/icd/CMakeLists.txt
tests/icd/test_icd.cpp
tests/unit/imageless_framebuffer.cpp
tests/unit/shader_storage_image.cpp
tests/unit/subpass.cpp
tests/unit/sync_val.cpp

This change contains various fixes, including fixes for the following problems:
- incorrect query entry point used by vkGetCalibratedTimestampsKHR validation
- incorrect generator script logic for the malfunctioning generator script caching
- incorrect handling of empty structextends lists
- incorrect assumptions about entry points with VkObjectType parameters
- API parameterization changes for the Test ICD
- incorrect test cases still expecting "stateless" SPIR-V validation at pipeline create call
- incorrect test case dependencies

layers: Miscellaneous fixes

---

layers/VkLayer_khronos_validation.json.in
layers/layer_options.cpp
layers/sync/sync_commandbuffer.cpp
layers/sync/sync_commandbuffer.h
layers/sync/sync_settings.h
layers/sync/sync_stats.cpp
layers/sync/sync_stats.h
layers/sync/sync_validation.cpp
layers/sync/sync_validation.h
tests/framework/layer_validation_tests.h
tests/unit/sync_val.cpp
tests/unit/sync_val_positive.cpp

I forgot to clean up handles in `CommandBufferAccessContext::Reset`.
With this fix the memory consumption by HandleRecord objects in doom capture is ~7MB (previously ~700MB).
There is an opportunity to de-duplicate groups of handles which might reduce `HandleRecord` memory usage to < 1MB range for complex workloads. That's a backup plan if we need to get rid of few more MBs.
Also improvements to syncval stats system.

sync: Fix HandleRecord increased memory usage

---

layers/sync/sync_access_context.cpp
layers/sync/sync_access_context.h
layers/sync/sync_access_state.cpp
layers/sync/sync_access_state.h
layers/sync/sync_commandbuffer.cpp
layers/sync/sync_commandbuffer.h
layers/sync/sync_common.h
layers/sync/sync_submit.cpp
layers/sync/sync_submit.h
layers/sync/sync_validation.cpp
tests/unit/sync_val.cpp

This adds the support to detect a hazardous buffer resource during queue submit validation. A similar functionality for images (and other resources) will be added later.
`ResourceUsageTagEx` is a new structure that extends tag id with resource handle information.
`vkQueueSubmit` error message adds a resource field in the end:
> [ SYNC-HAZARD-WRITE-AFTER-WRITE ] Object 0: handle = 0x2cf6ffd67d0, type = VK_OBJECT_TYPE_QUEUE; | MessageID = 0x5c0ec5d6 | vkQueueSubmit():  Hazard WRITE_AFTER_WRITE for entry 0, VkCommandBuffer 0x2cf7ea5bb60[], Submitted access info (submitted_usage: SYNC_COMPUTE_SHADER_SHADER_STORAGE_WRITE, command: vkCmdDispatch, seq_no: 1, reset_no: 1, resource: VkBuffer 0xead9370000000008[BufferB]). Access info (prior_usage: SYNC_COPY_TRANSFER_WRITE, write_barriers: 0, queue: …

sync: Detect hazardous buffer resource

---

layers/best_practices/bp_image.cpp
layers/best_practices/bp_instance_device.cpp
layers/best_practices/bp_synchronization.cpp
layers/core_checks/cc_queue.cpp
layers/core_checks/cc_synchronization.cpp
layers/core_checks/cc_wsi.cpp
layers/gpu/core/gpu_state_tracker.cpp
layers/gpu/core/gpu_state_tracker.h
layers/gpu/core/gpuav.h
layers/gpu/core/gpuav_setup.cpp
layers/gpu/instrumentation/gpu_shader_instrumentor.cpp
layers/gpu/instrumentation/gpu_shader_instrumentor.h
layers/gpu/resources/gpuav_subclasses.cpp
layers/gpu/resources/gpuav_subclasses.h
layers/state_tracker/queue_state.h
layers/state_tracker/state_tracker.cpp
layers/state_tracker/state_tracker.h
layers/sync/sync_submit.h
layers/sync/sync_validation.cpp

This allows syncval to have deterministic `QueueId` between runs that simplifies debugging. It can be frustrating when during long debug session you learn how QueueId numbers map to specific queues and on the next run the mapping changes.
`vvl::Queue` adds `queue_index` field that is the index of the queue within a queue family.

sync: Make QueueId deterministic

---

layers/core_checks/cc_render_pass.cpp
layers/core_checks/core_validation.h
layers/stateless/sl_framebuffer.cpp
layers/stateless/sl_render_pass.cpp
layers/stateless/stateless_validation.h
tests/unit/dynamic_rendering.cpp

The Renderpass/Framebuffer creations checks were getting long and a tad out-of-hand
This does 3 things
- Moves more checks to stateless where possible
- Groups logical extension logic to own function
- Pass by reference as much as possible (instead of pointers)

layers: Reorganize renderpass framebuffer checks

---

layers/best_practices/bp_render_pass.cpp
layers/core_checks/cc_android.cpp
layers/core_checks/cc_descriptor.cpp
layers/core_checks/cc_device.cpp
layers/core_checks/cc_device_memory.cpp
layers/core_checks/cc_image.cpp
layers/gpu/core/gpuav_setup.cpp
layers/state_tracker/state_tracker.cpp
layers/state_tracker/state_tracker.h
layers/stateless/sl_instance_device.cpp
layers/stateless/stateless_validation.h
layers/vulkan/generated/chassis.cpp
layers/vulkan/generated/chassis.h
scripts/generators/layer_chassis_generator.py

We make a lot of internal calls to `VK_KHR_get_physical_device_properties2` functions, but we need to make sure to use the `DispatchGetPhysicalDeviceFormatProperties2` vs `DispatchGetPhysicalDeviceFormatProperties2KHR` depending if still using Vulkan 1.0 or not
This adds a DispatchGetPhysicalDevice*2Helper` for all those calls and substitutes them everywhere

layers: Add Dispatch helpers for GPDP2 calls

---

layers/core_checks/cc_query.cpp
tests/unit/query.cpp

closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/8211
make it more clear that you can reset the query with `vkCmdResetQueryPool` or `vkResetQueryPool`

layers: Clarify Query Reset Message

---

layers/state_tracker/pipeline_state.cpp

closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/8232 (@zmike enjoy these quick GPL fixes, they won't last long :laughing: )

layers: Fix GPL with tessellation topology

---

layers/sync/sync_access_context.cpp
layers/sync/sync_commandbuffer.cpp
tests/unit/sync_val_positive.cpp

Closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/8108

sync: Ignore not accessed variables and descriptor-only access

---

layers/gpu/instrumentation/gpu_shader_instrumentor.h
layers/gpu/instrumentation/gpuav_instrumentation.cpp
layers/gpu/spirv/module.h

Currently for ALL shaders in GPU-AV (even thoughs we don't instrument) we are still running the re-building the SPIR-V and then running it through spirv-opt
This will make things faster when we are running on shaders that don't have anything to touch
it will also allow other changes in the shader instrumentation to freely do things knowing it will be ignored if it is never used

gpu: Don't run spirv-opt on non-instrumented shaders

---

scripts/generate_spirv.py

currently after you run `generate_spirv.py` it will show diffs until you re-run clang-format
we could add the "automatically run clang-format" into the script, but the only spot was the copyrights and doubt another new part will come anytime soon

scripts: Fix clang-format on generate_spirv.py

---

layers/gpu/core/gpu_state_tracker.cpp
layers/gpu/core/gpu_state_tracker.h
layers/gpu/debug_printf/debug_printf.cpp
layers/gpu/debug_printf/debug_printf.h
layers/gpu/descriptor_validation/gpuav_descriptor_set.cpp
layers/gpu/descriptor_validation/gpuav_descriptor_set.h
layers/gpu/descriptor_validation/gpuav_descriptor_validation.cpp
layers/gpu/descriptor_validation/gpuav_descriptor_validation.h
layers/gpu/resources/gpuav_subclasses.cpp
layers/gpu/resources/gpuav_subclasses.h
layers/gpu/shaders/instrumentation/buffer_device_address.comp
layers/state_tracker/cmd_buffer_state.cpp
layers/state_tracker/cmd_buffer_state.h
layers/state_tracker/state_tracker.cpp
layers/sync/sync_commandbuffer.cpp
layers/sync/sync_commandbuffer.h

For our `InternalError` we seem to have random `Location` used. When I hit this error I expected to know which original incoming function was coming in. For things like `Reset()` there are many things that can reset the command buffer and very helpful to have that information

gpu: Pipe Location through for internal errors

---

layers/VkLayer_khronos_validation.json.in
layers/gpu/core/gpu_settings.h
layers/gpu/instrumentation/gpuav_instrumentation.cpp
layers/gpu/spirv/module.cpp
layers/gpu/spirv/module.h
layers/gpu/spirv/pass.cpp
layers/gpu/spirv/pass.h
layers/layer_options.cpp

Adds a `VK_LAYER_GPUAV_DEBUG_MAX_INSTRUMENTED_COUNT` setting to help quickly limit how much we instrument shaders to easily see if limiting it fixes perf issues and understand how it scales easier
Also in future can add a "debug verbose" option to get this information as well

gpu: Add setting to limit shader instrumentation

---

layers/VkLayer_khronos_validation.json.in
layers/layer_options.cpp

The app might be setting `VK_VALIDATION_FEATURE_ENABLE_GPU_ASSISTED_EXT` and there is no `VkValidationFeatureDisableEXT` to disable it, so this adds a `VK_LAYER_GPUAV_DEBUG_DISABLE_ALL` option
this is useful for debugging if GPU-AV is the issue or not for app that is forcing it on

gpu: Add setting to override disable GPU-AV

---

docs/synchronization_usage.md
layers/VkLayer_khronos_validation.json.in
layers/layer_options.cpp
layers/layer_options.h
layers/sync/sync_settings.h
layers/sync/sync_validation.cpp
tests/unit/sync_val_positive.cpp

Remove some legacy configuration and make queue submit validation a regular layer setting of synchronization validation.
New setting is called: `syncval_submit_time_validation`.
Decided to go with `Submit time validation` term. One example it is used here: https://vulkan.org/user/pages/09.events/vulkanised-2024/vulkanised-2024-john-zulauf-lunarg.pdf. The `time` suffix is often added because it is more about the place where the validation happens and to less degree about validating vkQueueSubmit itself. The validation also happens for presentation request, so not only vkQueueSubmit(2) specific.

sync: Make queue submit validation regular layer option

---

layers/state_tracker/video_session_state.cpp
layers/state_tracker/video_session_state.h
tests/unit/video_positive.cpp

Note that the test passes even without the additional bounds check, and these safety measures were added in response to https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/8267.

layers: Add more tests and bounds checks for DPB slots

---

layers/VkLayer_khronos_validation.json.in
layers/layer_options.cpp
layers/sync/sync_commandbuffer.cpp
layers/sync/sync_settings.h

Exposes syncval validation of shader accesses as configurable option, so it's possible to disable it in case of false-positives.
The option can also be disabled by setting environment variable: `VK_VALIDATION_SYNCVAL_SHADER_ACCESS_HEURISTIC=0`

sync: Add syncval_shader_access_heuristic setting

---

tests/unit/sync_val.cpp
tests/unit/sync_val_positive.cpp

Tried to classify the problems when syncval shader access tracking does not work. Some scenarios are fixable. The rest will be in the category "too complex for heuristic". Not an attempt to provide full coverage of syncval shader access tracking. Includes a scenario reported recently by the client, and several variations of that.

tests: Add several scenarios with shader heuristic issues

---

layers/gpu/spirv/instruction.h
layers/gpu/spirv/pass.cpp
tests/unit/gpu_av_spirv_positive.cpp

Fixes issue where you have
```swift
%firstBlock = OpLabel
OpStore %a %b // don't inject anything
OpStore %c %d // inject check
```

gpu: Fix when OpStore is used in first block

---

layers/VkLayer_khronos_validation.json.in
layers/sync/sync_settings.h
tests/framework/layer_validation_tests.h
tests/unit/sync_val_positive.cpp

Improvements to SPIR-V static analysis allowed to properly identify
some accesses as writes (previously there were erroneously classified
as reads). This increased the number of cases where current validation
of shader accesses results in false-positive reports. This makes
current heuristic less suitable to be enabled by default.
Some additional improvements to the heuristic are planned. It can be
useful in some scenarios, but fundamentally it can't be a
false-positive free solution.

sync: Make shader_access_heuristic disabled by default

---

layers/VkLayer_khronos_validation.json.in
layers/layer_options.cpp
layers/sync/sync_commandbuffer.cpp
layers/sync/sync_settings.h
tests/unit/sync_val_positive.cpp

Rename setting name until it's not too late.
Use plural form for accesses: `syncval_shader_access_heuristic` -> `syncval_shader_accesses_heuristic` and *Shader accesses heuristic* in the UI.
*heuristic* part is to indicate it is not 100% reliable feature.  This suffix might go away if we come up a with robust solution.
The base setting name is *Shader accesses*, which IMO indicates well it's about accesses performed by the shader. Old version *Shader access* sounds to my ears like it's access to the shader.

sync: Update setting name

---

layers/sync/sync_access_state.cpp
layers/sync/sync_access_state.h

Minor interface cleanup. In current implementation these functions are always called together.

sync: Inline ClearPending into ApplyPendingBarriers

---

CMakeLists.txt

For LLDB on Linux, I get `error: summary string parsing error` for any string, found from many online sources the simple fix was to add ` -fstandalone-debug` to the clang build

build: Add -fstandalone-debug for Clang Debug

---

layers/vk_layer_config.cpp

Clarify that version under NDK 25 are not supported
I noticed this while attempting to build with NDK 23. The error tells you to use NDK 20 or higher, when in reality, you need NDK 25 or higher.

Correct error message when attempting to build for Android

---

layers/best_practices/bp_device_memory.cpp
tests/unit/nvidia_best_practices.cpp

Acknowledge VkMemoryPriorityAllocateInfoEXT as a memory priority when checking for VK_EXT_pageable_device_local_memory memory priorities in NVIDIA best practices. Add a unit test to verify this is working.
Fix #8276.

layers: Acknowledge allocation memory priority in NVIDIA best practices

---

layers/best_practices/bp_cmd_buffer_nv.cpp

closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/8293
clearly from vkcube we can get here with an invalid `vvl::Image`
without knowing enough of zcull scope this is the best quick fix... I added the original `ASSERT_AND_RETURN` as it "seemed" it should be always valid, but clearly my assumption was wrong and good to know now

bp: Return on invalid image in zcull scope

---

layers/gpu/debug_printf/debug_printf.cpp
layers/gpu/debug_printf/debug_printf.h
tests/unit/debug_printf.cpp

The logic for `AnalyzeAndGenerateMessage` in debug printf was a little cryptic and out-of-date. Reorganize it with the intentions to finally get a fix for https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/7143 soon

printf: Cleanup Printf string message parsing logic

---

layers/core_checks/cc_spirv.cpp
layers/core_checks/core_validation.h
layers/state_tracker/shader_module.cpp
layers/state_tracker/shader_module.h
tests/unit/debug_printf.cpp

Currently we do zero validation for debug printf, things like `debugPrintfEXT("vector of %f", myInt);` or other variations will blindly start printing garbage and there is nothing validating it
Checked and Renderdoc follows the same formatting so this should be universal (left comment)
To start these are all warnings, but some things feel like errors (so we might change them in future)

printf: Add Basic DebugPrintf string validation

---

layers/core_checks/cc_descriptor.cpp

When checking if immutableSamplers are equal, the valid possible
descriptorTypes should be either VK_DESCRIPTOR_TYPE_SAMPLER or
VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER. The current code uses
VK_DESCRIPTOR_TYPE_SAMPLED_IMAGE instead of the COMBINED one.

corechecks: Fix descriptorType check in ImmutableSamplersAreEqual

---

layers/sync/sync_commandbuffer.cpp
tests/unit/sync_val.cpp

Something to cherry pick for this SDK (and to have on the main too). Should be turned for this SDK even if we have a fix before the release. Needs more testing.
This can be related to command buffer lifetime management. Usage records can reference handles from the command buffers that were Reset (https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/8291 ).

sync: Disable resource reporting due to stale index issue

---

CMakeLists.txt
layers/gpu/debug_printf/debug_printf.cpp
tests/unit/debug_printf.cpp

Currently we were not supported `%v3lu` and `%v3lx` vectors

printf: Fix printing vectors of lu lx

---

layers/core_checks/cc_cmd_buffer.cpp
tests/unit/dynamic_rendering_local_read.cpp

MR is complete and can be reviewed, but will need an update when https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/8298 lands
adds
- VUID-vkCmdExecuteCommands-pCommandBuffers-09504
- VUID-vkCmdExecuteCommands-pCommandBuffers-09505

Add missing VUID-vkCmdExecuteCommand-pCommandBuffers checks and tests

---

layers/core_checks/cc_copy_blit_resolve.cpp
layers/core_checks/cc_image.cpp
layers/core_checks/cc_query.cpp
layers/core_checks/cc_ray_tracing.cpp
layers/core_checks/core_validation.h

(similar to https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/8307) This moves some `PreCallRecord` in Best Practices to `PostCallRecord` where it didn't need to be in `PreCall`

core: Move PreCallRecord to PostCallRecord

---

layers/best_practices/best_practices_validation.h
layers/best_practices/bp_cmd_buffer.cpp
layers/best_practices/bp_copy_blit_resolve.cpp
layers/best_practices/bp_device_memory.cpp
layers/best_practices/bp_drawdispatch.cpp
layers/best_practices/bp_pipeline.cpp
layers/best_practices/bp_render_pass.cpp

This moves some `PreCallRecord` in Best Practices to `PostCallRecord` where it didn't need to be in `PreCall`

bp: Move PreCallRecord to PostCallRecord

---

layers/vulkan/generated/object_tracker.cpp
scripts/generators/object_tracker_generator.py
tests/unit/parent.cpp

this is a follow-up to https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/8144 (based from https://gitlab.khronos.org/vulkan/vulkan/-/issues/3553)
The core issue is the spec doesn't generate proper implicit VUs for `common parent` checks
We (correctly) are ignoring and throwing warnings when we don't recognize the missing VU and with that we have been missing a LOT of checks for `common parent" checks.
Before we just threw the struct name in the `self.structs_that_forgot_about_parent_vuids` and moved on
this manually add them in a way that one day (probably not anytime soon tbh) when someone goes and fix the spec generating logic, we have a more descriptive breakdown of all the VUs missing
(tl;dr - lots of VUID churn 😢)

scripts: Add missing parent VUs

---

layers/stateless/sl_image.cpp
layers/stateless/stateless_validation.h

- first commit is just cleanup as the function was getting unnecessarily/complex
- adds changes to Image creation VU change for `VUID-VkImageCreateInfo-pNext-06722` (from https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/6774)

layers: Fix compatible image VU for 291 headers

---

layers/stateless/sl_ray_tracing.cpp

simple implicit VUID I see we forgot to add manually (`VUID-VkAccelerationStructureGeometryTrianglesDataKHR-sType-unique`)

layers: Add RTX Implicit VUID

---

layers/sync/sync_commandbuffer.cpp
layers/sync/sync_commandbuffer.h
tests/unit/sync_val.cpp

https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/8291 discovered two problems:
1) There is a potential syncval bug. Will be fixed in another PR, we have a deterministic repro case.
2) If syncval resource reporting invariants get invalidated this leads to crash/assert. The above syncval bug leads to such bad state and it will be fixed. But the same happens when we have unhandled core validation error (when core validation is disabled). The convention that syncval should handle this gracefully without crashing, although does not guarantee that reporting is correct.
This PR addresses problem 2.

🌴sync: Ensure handle index is valid

---

layers/gpu/core/gpu_state_tracker.cpp
layers/gpu/core/gpu_state_tracker.h
layers/gpu/core/gpuav.h
layers/gpu/core/gpuav_setup.cpp
layers/gpu/instrumentation/gpu_shader_instrumentor.cpp
layers/gpu/instrumentation/gpu_shader_instrumentor.h
layers/gpu/resources/gpuav_subclasses.cpp
layers/gpu/resources/gpuav_subclasses.h
layers/state_tracker/queue_state.cpp
layers/state_tracker/queue_state.h
layers/state_tracker/state_tracker.cpp
layers/state_tracker/state_tracker.h

Move most submission post processing into the PostCallRecord hooks. This avoids adding submission state in the PreCall hook and then looking for it in the PostCall hook. It also avoids adding bad state in case  the submit call fails.
The remaining work in the PreCall hook is setting up resources used by the instrumented shaders we're about to execute and that must happen  before the submit is dispatched.
This problem was hidden by sometimes calling the wrong version (core vs KHR) of vkWaitSemaphores(), which would end up calling a no-op stub set up elsewhere in VVL (and being fixed separately). So if we're using vulkan 1.2 or greater we use the core versions, if we're in 1.1 and have enabled the extensions, use the KHR versions.
Fixes #7562

gpu: Fix a race condition in submission processing

---

layers/VkLayer_khronos_validation.json.in
layers/best_practices/best_practices_utils.cpp
layers/core_checks/cc_shader_object.cpp
layers/core_checks/cc_spirv.cpp
layers/core_checks/cc_synchronization.cpp
layers/gpu/instrumentation/gpu_shader_instrumentor.cpp
layers/layer_options.cpp
layers/layer_options.h
layers/vulkan/generated/chassis.cpp
layers/vulkan/generated/chassis.h
scripts/generators/layer_chassis_generator.py

This adds a `VK_LAYER_DEBUG_DISABLE_SPIRV_VAL` setting to allow quick profiling testing with/without `spirv-val`
In order to add it, had to cleanup the settings a bit
Also improved the description of the current shader settings

layers: Cleanup Global and Shader settings

---

layers/VkLayer_khronos_validation.json.in
layers/gpu/core/gpu_settings.h
layers/gpu/instrumentation/gpuav_instrumentation.cpp
layers/gpu/spirv/module.cpp
layers/gpu/spirv/module.h
layers/gpu/spirv/pass.h
layers/layer_options.cpp
tests/spirv/instrumentation.cpp

adds a `VK_LAYER_GPUAV_DEBUG_PRINT_INSTRUMENTATION_INFO` option to help get information about the shader instrumentation passes

gpu: Add debug option to print instrumentation info

---

layers/core_checks/cc_copy_blit_resolve.cpp
layers/profiling/profiling.h
layers/state_tracker/device_memory_state.cpp
layers/state_tracker/device_memory_state.h
tests/unit/sparse_buffer_positive.cpp

Closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/8224
Stress test:
For 10,000 copies, went down from +15 minutes (stopped measured) down to 60 ms
For 4000, went down from +6 minutes to 10ms
For the stress test, the source and destination buffer are bound to only one VkDeviceMemory, I need to make another one where they are bound to multiples to see if perf is bad
~~Need to port this logic to the non sparse buffer case, will make another PR as users do not appear to be blocked on that~~ done, see `BufferCopiesValidationStressTest2 `

layers: Improve perf for sparse buffer copies validation

---

BUILD.gn
docs/debug_printf.md
layers/gpu/debug_printf/debug_printf.cpp
layers/gpu/debug_printf/debug_printf.h
layers/gpu/instrumentation/gpu_shader_instrumentor.cpp
layers/gpu/instrumentation/gpuav_instrumentation.cpp
layers/gpu/shaders/gpu_error_header.h
layers/gpu/spirv/CMakeLists.txt
layers/gpu/spirv/bindless_descriptor_pass.cpp
layers/gpu/spirv/bindless_descriptor_pass.h
layers/gpu/spirv/buffer_device_address_pass.cpp
layers/gpu/spirv/buffer_device_address_pass.h
layers/gpu/spirv/debug_printf_pass.cpp
layers/gpu/spirv/debug_printf_pass.h
layers/gpu/spirv/function_basic_block.cpp
layers/gpu/spirv/function_basic_block.h
layers/gpu/spirv/inject_function_pass.cpp
layers/gpu/spirv/inject_function_pass.h
layers/gpu/spirv/instruction.h
layers/gpu/spirv/module.cpp
layers/gpu/spirv/module.h
layers/gpu/spirv/pass.cpp
layers/gpu/spirv/pass.h
layers/gpu/spirv/ray_query_pass.cpp
layers/gpu/spirv/ray_query_pass.h
tests/spirv/instrumentation.cpp
tests/unit/debug_printf.cpp

This was brought over from the current implementations in SPIRV-Tools (`source/opt/inst_debug_printf_pass.cpp`) for 3 reasons (after lots of discussions)
1. There are bugs that need be fixed and easier to iterate without having to grab a dependency
2. To get GPU-AV and work with DebugPrintf we need a more unified way the shaders are instrumented
3. Allows future maintainer to not need to learn yet-another-code-base to make changes
There is more I want to fix/add but this is the initial "get it to work the same" change... there are limitations (as noted from disabled tests) of the old implementation and plan to fix those once this is in

printf: Move implementation inside VVL

---

layers/sync/sync_image.h
layers/sync/sync_submit.cpp
layers/sync/sync_validation.cpp
layers/sync/sync_validation.h
tests/unit/sync_val_wsi_positive.cpp

Take into account present batches.
One example when ignoring present batches caused the problem is `vkWaitForFences` did not apply tagged wait to the accesses from the present batch. As a result those accesses tunneled through the fence wait and caused hazards.
Potentially fixes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/8291

🌴sync: Fix iteration over queue batch contexts

---

layers/core_checks/cc_copy_blit_resolve.cpp
layers/core_checks/cc_shader_interface.cpp
layers/core_checks/cc_spirv.cpp
layers/error_message/logging.cpp
layers/gpu/debug_printf/debug_printf.cpp
layers/gpu/instrumentation/gpu_shader_instrumentor.cpp
layers/gpu/instrumentation/gpuav_instrumentation.cpp
layers/gpu/spirv/bindless_descriptor_pass.cpp
layers/gpu/spirv/buffer_device_address_pass.cpp
layers/gpu/spirv/debug_printf_pass.cpp
layers/gpu/spirv/ray_query_pass.cpp
layers/state_tracker/descriptor_sets.cpp
layers/state_tracker/shader_module.cpp
layers/sync/sync_stats.cpp
tests/spirv/instrumentation.cpp

small cleanup suggested by @arno-lunarg to replace `"\n"` for `'\n'` which from [checking the compilation](https://godbolt.org/#g:!((g:!((g:!((h:codeEditor,i:(filename:'1',fontScale:14,fontUsePx:'0',j:1,lang:c%2B%2B,selection:(endColumn:35,endLineNumber:8,positionColumn:35,positionLineNumber:8,selectionStartColumn:35,selectionStartLineNumber:8,startColumn:35,startLineNumber:8),source:'%23include+%3Ciostream%3E%0A%0Avoid+foo(int+x)+%7B%0A++++std::cout+%3C%3C+%22Test+%22+%3C%3C+x+%3C%3C+%22%5Cn%22%3B%0A%7D%0A%0Avoid+bar(int+x)+%7B%0A++++std::cout+%3C%3C+%22Test+%22+%3C%3C+x+%3C%3C+!'%5Cn!'%3B%0A%7D%0A%0Aint+main()+%7B%0A++++foo(3)%3B%0A++++bar(4)%3B%0A%7D'),l:'5',n:'1',o:'C%2B%2B+source+%231',t:'0')),k:52.375979112271544,l:'4',n:'0',o:'',s:0,t:'0'),(g:!((h:compiler,i:(compiler:clang1600,filt …

layers: Use char for new line in string stream

---

layers/best_practices/bp_image.cpp
layers/best_practices/bp_instance_device.cpp
layers/best_practices/bp_pipeline.cpp
layers/best_practices/bp_render_pass.cpp
layers/best_practices/bp_state.h
layers/best_practices/bp_synchronization.cpp
layers/core_checks/cc_image_layout.cpp
layers/core_checks/cc_queue.cpp
layers/error_message/logging.cpp
layers/gpu/cmd_validation/gpuav_cmd_validation_common.cpp
layers/gpu/debug_printf/debug_printf.cpp
layers/gpu/instrumentation/gpu_shader_instrumentor.cpp
layers/state_tracker/cmd_buffer_state.cpp
layers/state_tracker/device_memory_state.cpp
layers/state_tracker/image_state.cpp
layers/state_tracker/state_tracker.cpp
tests/framework/descriptor_helper.cpp
tests/framework/layer_validation_tests.cpp
tests/framework/render_pass_helper.cpp
tests/unit/best_practices.cpp
tests/unit/buffer.cpp
tests/unit/debug_printf.cpp
tests/unit/gpu_av_buffer_device_address.cpp
tests/unit/gpu_av_buffer_device_address_positive.cpp
tests/unit/mesh.cpp
tests/unit/sync_val.cpp

Basic attempt to use `emplace_back` where it should have an obvious benefits
prepared to criticism and "well technically in c++... " responses :shield:

layers: Use emplace_back where possible

---

layers/core_checks/cc_copy_blit_resolve.cpp
layers/state_tracker/device_memory_state.h
tests/unit/copy_buffer_image_positive.cpp

Took care of the sparse buffer case, this PR modifies validation for non sparse buffers.
For 1000 copies, went from **24 seconds** down to **0.5 ms**. Perf gains seem even better than what I got in the sparse case

Improve buffer copy validation perf

---

layers/best_practices/best_practices_utils.cpp
layers/best_practices/best_practices_validation.h
layers/best_practices/bp_descriptor.cpp
layers/best_practices/bp_device_memory.cpp
layers/best_practices/bp_image.cpp
layers/best_practices/bp_pipeline.cpp
layers/best_practices/bp_state.h
layers/best_practices/bp_wsi.cpp
layers/core_checks/cc_state_tracker.cpp
layers/core_checks/core_validation.h
layers/gpu/core/gpuav.h
layers/gpu/core/gpuav_setup.cpp
layers/gpu/debug_printf/debug_printf.cpp
layers/gpu/instrumentation/gpu_shader_instrumentor.cpp
layers/gpu/instrumentation/gpu_shader_instrumentor.h
layers/state_tracker/cmd_buffer_state.cpp
layers/state_tracker/cmd_buffer_state.h
layers/state_tracker/device_memory_state.cpp
layers/state_tracker/device_memory_state.h
layers/state_tracker/state_tracker.cpp
layers/state_tracker/state_tracker.h
layers/sync/sync_commandbuffer.cpp
layers/sync/sync_commandbuffer.h
layers/sync/sync_validation.cpp
layers/sync/sync_validation.h

Very nit PR, but annoying how state_tracker, BP, Sync Val, GPU-AV all have slightly different name calling conventions on their state object inheritance... this unifies them
also `VkCommandBufferAllocateInfo` should be `allocate_info` not `create_info` like it often gets mis-copy-and-pasted as

layers: Unify state object creation names

---

layers/drawdispatch/drawdispatch_vuids.cpp

Replace the initializer_list of init values to the std::map with a static array of pairs that it used to initialize the map. This avoids the stack allocation of the large initializer_list.

Fix stack overflow in GetDrawDispatchVuid

---

BUILD.gn
layers/gpu/spirv/CMakeLists.txt
layers/gpu/spirv/bindless_descriptor_pass.cpp
layers/gpu/spirv/bindless_descriptor_pass.h
layers/gpu/spirv/buffer_device_address_pass.h
layers/gpu/spirv/debug_printf_pass.cpp
layers/gpu/spirv/inject_conditional_function_pass.cpp
layers/gpu/spirv/inject_conditional_function_pass.h
layers/gpu/spirv/inject_function_pass.cpp
layers/gpu/spirv/pass.cpp
layers/gpu/spirv/pass.h
layers/gpu/spirv/ray_query_pass.h
layers/gpu/spirv/type_manager.cpp

This creates a dedicated `InjectConditionalFunctionPass` and `InjectFunctionPass` to allow future passes to better separate the logic if it wants to use 
```
if (check_logic()) {
// original code
} else {
// safe code
}
```
vs
```
check_logic();
// original_code
```

spirv: Create dedicated InjectConditionalFunctionPass class

---

layers/gpu/cmd_validation/gpuav_copy_buffer_to_image.cpp
layers/gpu/cmd_validation/gpuav_dispatch.cpp
layers/gpu/cmd_validation/gpuav_draw.cpp
layers/gpu/cmd_validation/gpuav_trace_rays.cpp
layers/gpu/core/gpuav_setup.cpp
layers/gpu/debug_printf/debug_printf.cpp
layers/gpu/descriptor_validation/gpuav_descriptor_set.cpp
layers/gpu/descriptor_validation/gpuav_descriptor_validation.cpp
layers/gpu/instrumentation/gpu_shader_instrumentor.cpp
layers/gpu/instrumentation/gpuav_instrumentation.cpp
layers/gpu/instrumentation/gpuav_instrumentation.h
layers/gpu/resources/gpuav_subclasses.cpp
tests/unit/debug_printf.cpp

The current `InternalError` messages for GPU-AV say "Aborting GPU-AV" and "GPU-AV is being disabled"... this removes the inconsistent one so that it just only is said once inside the function
Currently both DebugPrintf and GPU-AV share device creation setup and require same global requirements, but were being checked separately

gpu: Unify error message and DeviceCreation

---

layers/gpu/cmd_validation/gpuav_cmd_validation_common.cpp
layers/gpu/cmd_validation/gpuav_cmd_validation_common.h
layers/gpu/cmd_validation/gpuav_copy_buffer_to_image.cpp
layers/gpu/cmd_validation/gpuav_dispatch.cpp
layers/gpu/cmd_validation/gpuav_dispatch.h
layers/gpu/cmd_validation/gpuav_draw.cpp
layers/gpu/cmd_validation/gpuav_draw.h
layers/gpu/cmd_validation/gpuav_trace_rays.cpp
layers/gpu/cmd_validation/gpuav_trace_rays.h
layers/gpu/core/gpuav_record.cpp
layers/gpu/instrumentation/gpuav_instrumentation.cpp
layers/gpu/instrumentation/gpuav_instrumentation.h

This avoids lookup and locking churn, and makes it more obvious that the state object is in use by various instrumentation subroutines.

gpu: Avoid multiple command buffer lookups while instrumenting

---

layers/best_practices/bp_buffer.cpp
layers/best_practices/bp_cmd_buffer_nv.cpp
layers/best_practices/bp_copy_blit_resolve.cpp
layers/best_practices/bp_drawdispatch.cpp
layers/best_practices/bp_instance_device.cpp
layers/best_practices/bp_render_pass.cpp
layers/best_practices/bp_synchronization.cpp
layers/state_tracker/cmd_buffer_state.cpp
layers/state_tracker/device_state.cpp
layers/state_tracker/device_state.h
layers/state_tracker/image_state.cpp
layers/state_tracker/image_state.h
layers/state_tracker/sampler_state.h
layers/state_tracker/state_tracker.cpp
layers/stateless/sl_cmd_buffer.cpp
layers/stateless/sl_descriptor.cpp
layers/stateless/sl_image.cpp
layers/stateless/sl_render_pass.cpp
layers/stateless/sl_wsi.cpp
layers/utils/hash_util.cpp
layers/utils/hash_util.h
layers/utils/ray_tracing_utils.h
layers/utils/shader_utils.cpp
layers/utils/vk_layer_utils.h
layers/vk_layer_config.cpp

using `Zed` took some time to look through clang-tidy warnings, a LOT were not worth fixing, but here are some good low-hanging fruit

layers: Apply some clang-tidy fixes

---

layers/gpu/descriptor_validation/gpuav_descriptor_set.cpp
layers/gpu/instrumentation/gpuav_instrumentation.cpp
layers/gpu/instrumentation/gpuav_instrumentation.h
layers/state_tracker/descriptor_sets.cpp
layers/state_tracker/descriptor_sets.h
tests/unit/gpu_av_descriptor_indexing.cpp
tests/unit/gpu_av_descriptor_indexing_positive.cpp
tests/unit/gpu_av_oob.cpp
tests/unit/gpu_av_oob_positive.cpp

- We were using the "buffer size", not the "bound range", to detect buffer OOB in GPU-AV
- We didn't print the buffer handle in the GPU-AV error (yet we know it)
- Also for `VkDescriptorBufferInfo` we were not handling `VK_WHOLE_SIZE` correctly

gpu: Fix buffer OOB to use range, not size

---

layers/core_checks/cc_drawdispatch.cpp
tests/unit/command.cpp

The latter is the same as the former but with added text about vkCmdBindVertexBuffer2(), which validation already handles.
Hopefully 07825 will be removed from the spec soon.

corechecks: Replace VUID 07825 with 08798

---

BUILD.gn
layers/CMakeLists.txt
layers/gpu/core/gpu_settings.h
layers/gpu/core/gpu_shader_cache_hash.h
layers/gpu/core/gpuav_record.cpp
layers/gpu/core/gpuav_setup.cpp

This was in gpu_settings.h which is included by chassis.h. And it includes the autogenerated shader hash, which changes frequently when working on gpuav shaders and thus the whole world rebuilds every time a shader changes. It is really only needed in 2 cpp files so move it there.

gpu: Move ShaderCacheHash to a separate file

---

layers/gpu/core/gpuav.h
layers/gpu/core/gpuav_setup.cpp
layers/gpu/descriptor_validation/gpuav_descriptor_validation.cpp
layers/gpu/instrumentation/gpu_shader_instrumentor.cpp
layers/gpu/instrumentation/gpu_shader_instrumentor.h

we had this `force_buffer_device_address_` from back when `enabled_feature` was not working
this cleans up (unified the warning messages) for turning on/off settings in GPU-AV

gpu: Cleanup setting init

---

layers/best_practices/best_practices_validation.h
layers/best_practices/bp_pipeline.cpp
layers/best_practices/bp_state.h
layers/chassis/chassis_modification_state.h
layers/gpu/core/gpuav_record.cpp
layers/gpu/instrumentation/gpu_shader_instrumentor.cpp
layers/gpu/instrumentation/gpu_shader_instrumentor.h
layers/state_tracker/pipeline_state.cpp
layers/state_tracker/pipeline_state.h
layers/state_tracker/pipeline_sub_state.cpp
layers/state_tracker/shader_module.h
layers/state_tracker/state_tracker.cpp
layers/state_tracker/state_tracker.h
layers/vulkan/generated/chassis.cpp
scripts/generators/layer_chassis_generator.py
tests/unit/debug_printf.cpp

closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/7804
This move is done because the next change to improve descriptor indexing checks will requires use to know if `VK_DESCRIPTOR_BINDING_PARTIALLY_BOUND_BIT_EXT` is used or not
Luckily because of `VK_KHR_maintenance5`
we already had a path to do stuff at pipeline creation time
This change actually removed a lot of ugly tracking we did to match the `vkCreateShaderModule` at create pipeline time, having it all in a single chassis call allows us to save more data on the stack and remove it when the pipeline is created

gpu: Move Instrumentation to Pipeline creation

---

layers/state_tracker/query_state.h

Turns out adding/updating elements to this map is an hot spot for Doom Eternal. Did not improve game frame rate when actually playing the game, at least in the menu, but with a GFXR trace, the difference is drastic: Saved 19 seconds on a replay that is less than 2 minutes long

core: Use robin hood map to improve perf

---

layers/VkLayer_khronos_validation.json.in

`VK_LAYER_GPUAV_DEBUG_DISABLE_ALL` is designed for dealing with apps that have explicitly set GPU-AV on and has no reason to be seen in `VkConfig`

layers: Remove gpuav_debug_disable_all from vkconfig

---

layers/VkLayer_khronos_validation.json.in

No need for a workaround in vkconfig to hide the old and deprecated 'enables' and 'disables' settings in Vulkan Configurator, the manifest can notify Vulkan Configurator.

layers: Hide deprecated 'enables/disables' in vkconfig

---

layers/state_tracker/query_state.h

Per Artem's comment, this is indeed not needed anymore

core: Remove QueryObject <

---

layers/chassis/chassis_modification_state.h
layers/gpu/core/gpuav.h
layers/gpu/core/gpuav_record.cpp
layers/gpu/debug_printf/debug_printf.cpp
layers/gpu/debug_printf/debug_printf.h
layers/gpu/instrumentation/gpu_shader_instrumentor.cpp
layers/gpu/instrumentation/gpu_shader_instrumentor.h
layers/state_tracker/shader_object_state.cpp
layers/state_tracker/shader_object_state.h
layers/state_tracker/state_tracker.cpp
layers/vulkan/generated/chassis.cpp
scripts/generators/layer_chassis_generator.py

Combine the `PreCallRecordCreateShadersEXT` for GPU-AV and DebugPrintf as they use the same flow now
Also make it look like the Pipeline path for code consistency

gpu: Combine ShaderObject in Printf/GPU-AV

---

layers/best_practices/bp_drawdispatch.cpp
layers/core_checks/cc_cmd_buffer_dynamic.cpp
layers/core_checks/cc_drawdispatch.cpp
layers/core_checks/cc_pipeline_graphics.cpp
layers/state_tracker/cmd_buffer_state.h
layers/state_tracker/pipeline_sub_state.cpp
layers/state_tracker/pipeline_sub_state.h
layers/state_tracker/state_tracker.cpp
layers/sync/sync_commandbuffer.cpp

Rather than just storing arrays of VkVertexInputBindingDescription and VkVertexAttributeBindingDescription structures that have to be corellated to do anything useful, group all of this state by binding and location for easier lookup.
Fixes #5281

state: Improve storage of vertex input state

---

layers/core_checks/cc_cmd_buffer_dynamic.cpp
layers/state_tracker/shader_module.h
tests/unit/geometry_tessellation.cpp
tests/unit/geometry_tessellation_positive.cpp
tests/unit/mesh.cpp

closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/8319
For geometry shaders, which have an input and output topology, we were grabbing the last one listed and not the dedicated input one

layers: Fix false positive for dynamic Geometry Topology

---

layers/state_tracker/fence_state.h
layers/state_tracker/queue_state.cpp
layers/state_tracker/queue_state.h
layers/state_tracker/state_tracker.cpp
tests/unit/wsi_positive.cpp

Fixes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/8376
Based on this discussion: https://gitlab.khronos.org/vulkan/vulkan/-/issues/3962
This adds `QueueSubmission` object per swapchain (instead of per present as it was before). The reason is that present fence is defined per swapchain. This allows to use `QueueSubmission::fence` field to keep present fence and reuse existing fence tracking code path without additional changes. The first commit does `QueueSubmission` per swapchain change. The fix is the second commit, just adds the fence to `QueueSubmission`.

layers: Wait for present fences in QueueWaitIdle

---

layers/core_checks/cc_pipeline_graphics.cpp

closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/8393

layers: Fix crash for shader module identifiers and mesh shaders

---

layers/layer_options.cpp
layers/layer_options.h
layers/vulkan/generated/chassis.cpp
layers/vulkan/generated/stateless_validation_helper.cpp
scripts/generators/layer_chassis_generator.py
scripts/generators/stateless_validation_helper_generator.py
tests/unit/instanceless.cpp

The `VkLayerSettingsCreateInfoEXT`/`VkLayerSettingEXT` param validation was not possible as it needs to be done before the Create Instance setup
This will help give some error if people have null values in those structs by accident

layers: Add VK_EXT_layer_settings param validation

---

layers/core_checks/cc_cmd_buffer_dynamic.cpp
layers/vulkan/generated/object_tracker.cpp
scripts/generators/object_tracker_generator.py

2 fixes
1. ` VUID-vkCmdDraw-None-06666` now requires `VK_EXT_sample_locations` (because when using Shader Object that extension has no feature bit to turn on)
2. Fixes some VUID churn around the Object Tracker parent VUIDs not being assigned yet

layers: Spec fixes for 1.3.293

---

layers/gpu/core/gpu_settings.h
layers/gpu/core/gpu_shader_cache_hash.h
layers/gpu/core/gpuav_record.cpp
layers/gpu/core/gpuav_setup.cpp
layers/gpu/descriptor_validation/gpuav_descriptor_validation.cpp
layers/gpu/instrumentation/gpu_shader_instrumentor.cpp
layers/gpu/instrumentation/gpuav_instrumentation.cpp
layers/gpu/resources/gpuav_subclasses.cpp
layers/layer_options.cpp

Combination of https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/8021 and https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/8381 broke how caching works
also will solve most issues that caused https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/8415 to be raised

gpu: Fix GPU-AV Caching

---

layers/core_checks/cc_buffer.cpp
layers/core_checks/core_validation.h

This moves the `VK_EXT_descriptor_buffer` (and `VK_KHR_buffer_device_address` as well) so that future extensions can not worry about blending things together

layers: Separate CreateBuffer for descriptor buffers

---

layers/vulkan/generated/chassis.cpp
scripts/generators/layer_chassis_generator.py

If the extension is not known, it will print out `INVALID_EMPTY` (which is not helpful IMO)
We have the original `const char*` so this prints it out instead

layers: Print ppEnabledExtensionNames string if unknown

---

layers/state_tracker/queue_state.cpp
layers/state_tracker/queue_state.h
layers/state_tracker/state_tracker.cpp
tests/unit/wsi_positive.cpp

It's the second attempt after: https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/8400
Original present fence synchronization was implemented here: https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/7694.
It was based on PresentSync, although PresentSync was not designed for this (only for acquire-based synchronization), still it worked.
Then we accidentally ended up with two solutions to handle present fences: `QueueSubmission` and `PresentSync`. This solution removes `PresentSync` code path and uses `QueueSubmission` fence instead.
Closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/8376
Potentially fixes the issue ANGLE had with the previous approach. Two solutions worked at the same time and caused raced condition. It worth to say that race …

layers: Track present fences (better)

---

layers/state_tracker/fence_state.cpp
layers/state_tracker/fence_state.h
layers/state_tracker/state_tracker.cpp
tests/unit/wsi_positive.cpp

The previous name was nice but also a bit too general, which allowed to use it in more contexts than initially was planned, which led to problems that are fixed now, but  not forgotten.
Added comment to better explain the idea of acquire fence synchronization.

layers: Rename PresentSync -> AcquireFenceSync

---

layers/gpu/spirv/bindless_descriptor_pass.cpp
layers/gpu/spirv/bindless_descriptor_pass.h
layers/gpu/spirv/buffer_device_address_pass.h
layers/gpu/spirv/debug_printf_pass.cpp
layers/gpu/spirv/debug_printf_pass.h
layers/gpu/spirv/non_bindless_oob_buffer_pass.cpp
layers/gpu/spirv/non_bindless_oob_buffer_pass.h
layers/gpu/spirv/non_bindless_oob_texel_buffer_pass.cpp
layers/gpu/spirv/non_bindless_oob_texel_buffer_pass.h
layers/gpu/spirv/pass.cpp
layers/gpu/spirv/pass.h
layers/gpu/spirv/ray_query_pass.h
layers/gpu/spirv/type_manager.cpp

As we add more passes, and have common `Pass` member functions that might have to report an error, it is nice to have a `Name()`function to get which pass it was

gpu: Have all Passes have a name function

---

tests/framework/layer_validation_tests.cpp
tests/framework/layer_validation_tests.h
tests/framework/shader_helper.h
tests/framework/shader_object_helper.cpp
tests/framework/shader_object_helper.h
tests/framework/video_objects.h
tests/unit/command.cpp
tests/unit/dynamic_rendering_local_read.cpp
tests/unit/fragment_shading_rate.cpp
tests/unit/geometry_tessellation.cpp
tests/unit/gpu_av_shader_object_positive.cpp
tests/unit/graphics_library_positive.cpp
tests/unit/mesh.cpp
tests/unit/multiview.cpp
tests/unit/pipeline.cpp
tests/unit/render_pass.cpp
tests/unit/shader_object.cpp
tests/unit/shader_object_positive.cpp
tests/unit/subpass.cpp
tests/unit/subpass_positive.cpp
tests/unit/vertex_input.cpp

While in meeting, reducing the `#include` clustering in `./tests` so when I edit a util/framework file, I can rebuild slightly less than every test if not needed

tests: More test header cleanup

---

layers/best_practices/bp_synchronization.cpp

for https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/8469
now prints
> Validation Performance Warning: [ BestPractices-SyncObjects-HighNumberOfFences ] | MessageID = 0xa9f4ff68 | vkCreateFence():  [AMD] [NVIDIA] High number of VkFence objects created. 4 created, but recommanded max is 3. Minimize the amount of CPU-GPU synchronization that is used. Semaphores and fences have overhead. Each fence has a CPU and GPU cost with it.

bp: Improve max sync object message
