layers/core_checks/cc_queue.cpp
- `VUID-vkQueueBindSparse-queuetype` didn't tell any information about the queue that was causing the error
- `VUID-VkSparseImageMemoryBindInfo-image-02901` was just repeating the spec VU
=> layers: Improve Sparse error message

layers/best_practices/best_practices_error_enums.h, layers/best_practices/bp_render_pass.cpp, tests/unit/best_practices.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/7495
=> bp: Resolve mode none check

layers/core_checks/cc_pipeline_graphics.cpp, layers/core_checks/core_validation.h, tests/unit/mesh.cpp
prep for upcoming PR for https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/1749
Moves things to a single function
=> layers: Move MultiView shader logic together

tests/framework/ray_tracing_objects.cpp, tests/framework/ray_tracing_objects.h, tests/unit/ray_tracing_positive.cpp
Closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/7501
=> tests: Add new positive trace rays tests

layers/core_checks/cc_descriptor.cpp, layers/gpu_validation/gpu_descriptor_set.h, layers/state_tracker/descriptor_sets.cpp, layers/state_tracker/descriptor_sets.h, layers/state_tracker/shader_module.cpp, layers/state_tracker/shader_module.h, tests/unit/atomics.cpp, tests/unit/sampler.cpp
addresses https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/6944
=> layers: Detect if dynamic access

tests/unit/ray_tracing.cpp, tests/unit/ray_tracing_positive.cpp
Closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/7496
=> tests: Fix scratch buffer size mangement

layers/core_checks/cc_ray_tracing.cpp, layers/core_checks/core_validation.h, layers/stateless/sl_ray_tracing.cpp, layers/utils/ray_tracing_utils.cpp, layers/utils/ray_tracing_utils.h, tests/unit/ray_tracing.cpp
Part of https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/7362
Refacto a bunch of `vkCmdBuildAccelerationStructuresKHR` validation code to validate host and indirect builds
=> layers: CommonBuildAccelerationStructureValidation

layers/core_checks/cc_spirv.cpp, layers/state_tracker/state_tracker.cpp, layers/state_tracker/state_tracker.h, tests/framework/layer_validation_tests.h, tests/unit/shader_cooperative_matrix.cpp, tests/unit/shader_cooperative_matrix_positive.cpp
some cleanup for `VK_KHR_cooperative_matrix`
=> tests: Cleanup for VK_KHR_cooperative_matrix tests

layers/gpu_validation/gpu_record.cpp, tests/CMakeLists.txt, tests/framework/layer_validation_tests.h, tests/unit/gpu_av_ray_query_positive.cpp
Closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/7500
=> tests: Add ray query gpu av tests

layers/sync/sync_access_state.cpp, tests/unit/sync_val_positive.cpp
Addresses this comment: https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/7353#issuecomment-1957353665
This is the same fix as was done in https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/7465 (READ vs transition) but for the WRITE vs transition scenario.
=> sync: Fix one more ALL_COMMANDS leak

layers/core_checks/cc_pipeline_graphics.cpp, tests/unit/graphics_library.cpp, tests/unit/graphics_library_positive.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/7551
=> layers: Fix checking for pSampleMask

layers/core_checks/cc_device.cpp, layers/core_checks/core_validation.h, layers/gpu_validation/debug_printf.cpp, layers/gpu_validation/debug_printf.h, layers/gpu_validation/gpu_error_message.cpp, layers/gpu_validation/gpu_image_layout.cpp, layers/gpu_validation/gpu_record.cpp, layers/gpu_validation/gpu_setup.cpp, layers/gpu_validation/gpu_state_tracker.cpp, layers/gpu_validation/gpu_state_tracker.h, layers/gpu_validation/gpu_validation.cpp, layers/gpu_validation/gpu_validation.h, layers/state_tracker/state_tracker.cpp, layers/state_tracker/state_tracker.h, layers/sync/sync_validation.cpp, layers/sync/sync_validation.h
Before we printed 
> vkCreateDevice():  Setup Error. Detail: (Pipeline Layout conflict  ....
now we correctly print
> vkCreatePipelineLayout():  Setup Error. Detail: (Pipeline Layout conflict 
because we pass the `Location` around
=> gpu: Pass Location for all ReportSetupProblem

layers/core_checks/cc_spirv.cpp, layers/state_tracker/shader_module.cpp, layers/state_tracker/shader_module.h, layers/vulkan/generated/spirv_validation_helper.cpp, scripts/generators/spirv_validation_generator.py, scripts/known_good.json, tests/unit/atomics.cpp, tests/unit/atomics_positive.cpp
=> Validate VK_NV_shader_atomic_float16_vector

tests/unit/wsi.cpp
Fixes for WSI tests caught with MESA 24 RADV
=> tests: Fix WSI tests

layers/best_practices/best_practices_validation.h, layers/best_practices/bp_cmd_buffer.cpp, layers/best_practices/bp_copy_blit_resolve.cpp, layers/best_practices/bp_instance_device.cpp, layers/best_practices/bp_render_pass.cpp, layers/best_practices/bp_synchronization.cpp, layers/core_checks/cc_cmd_buffer.cpp, layers/core_checks/cc_copy_blit_resolve.cpp, layers/core_checks/cc_descriptor.cpp, layers/core_checks/cc_image.cpp, layers/core_checks/cc_query.cpp, layers/core_checks/cc_ray_tracing.cpp, layers/core_checks/cc_shader_object.cpp, layers/core_checks/cc_synchronization.cpp, layers/core_checks/core_validation.h, layers/stateless/sl_cmd_buffer.cpp, layers/stateless/sl_ray_tracing.cpp, layers/stateless/sl_render_pass.cpp, layers/stateless/stateless_validation.h, layers/sync/sync_validation.cpp
Add more more `VkCommandBuffer` to the `LogObjectList` for errors as it is really annoying to get a command buffer error and not know which one it came from
=> layers: Add missing command buffer Object Handles

layers/core_checks/cc_spirv.cpp, layers/core_checks/core_validation.h, tests/device_profiles/max_profile.json, tests/unit/shader_spirv.cpp, tests/unit/shader_spirv_positive.cpp
adds VUID-RuntimeSpirv-shaderSubgroupRotateClustered-09566
=> layers: Add VK_KHR_shader_subgroup_rotate

scripts/generate_spirv.py
@arno-lunarg pointed out this was wrong
=> scripts: Add better detection for external directory

layers/containers/range_vector.h, layers/core_checks/cc_copy_blit_resolve.cpp, layers/core_checks/cc_queue.cpp, layers/core_checks/core_validation.h, layers/state_tracker/cmd_buffer_state.cpp, layers/state_tracker/cmd_buffer_state.h, layers/stateless/sl_instance_device.cpp, layers/stateless/sl_render_pass.cpp, layers/stateless/stateless_validation.h, layers/utils/vk_layer_utils.h, layers/vulkan/generated/layer_chassis_dispatch.cpp, scripts/generators/layer_chassis_dispatch_generator.py, tests/device_profiles/max_profile.json, tests/unit/dynamic_rendering.cpp, tests/unit/dynamic_rendering_positive.cpp, tests/unit/render_pass.cpp, tests/unit/render_pass_positive.cpp
=> Add VK_ARM_render_pass_striped support

layers/vulkan/generated/gpu_inst_shader_hash.h, scripts/generate_spirv.py
=> gpu: Fix spirv gen script

layers/core_checks/cc_render_pass.cpp, tests/unit/dynamic_rendering.cpp
Spec fix in https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/6489/diffs
=> layers: Fix Multiview VU for 07908

layers/core_checks/cc_pipeline.cpp, layers/state_tracker/pipeline_state.cpp, layers/state_tracker/pipeline_state.h, layers/state_tracker/pipeline_sub_state.cpp, tests/unit/graphics_library_positive.cpp
Spec change is here https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/6515
=> layers: Ignore pStages for non shader GPL substate

layers/core_checks/cc_wsi.cpp, layers/gpu_validation/gpu_state_tracker.cpp, layers/layer_chassis_dispatch_manual.cpp, layers/object_tracker/object_tracker_utils.cpp, layers/state_tracker/image_state.h, layers/state_tracker/state_tracker.cpp, layers/stateless/sl_instance_device.cpp, layers/stateless/sl_utils.cpp, layers/thread_tracker/thread_safety_validation.cpp, layers/utils/vk_layer_utils.cpp, layers/utils/vk_layer_utils.h, layers/vk_layer_config.cpp, layers/vulkan/generated/chassis.cpp, layers/vulkan/generated/layer_chassis_dispatch.cpp, layers/vulkan/generated/object_tracker.cpp, scripts/generators/layer_chassis_dispatch_generator.py, scripts/generators/layer_chassis_generator.py, scripts/generators/object_tracker_generator.py, tests/layers/device_profile_api.cpp, tests/unit/image.cpp, tests/unit/image_positive.cpp, tests/unit/ray_tracing.cpp
trying to keep `layers/utils/vk_layer_utils.h` a little bit more lean
=> layers: Cleanup util file

tests/unit/sync_val.cpp, tests/unit/sync_val_positive.cpp
It was a problem on the application side in the issue https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/7486 and it was clarified on gitlab https://gitlab.khronos.org/vulkan/vulkan/-/issues/3811.
I found the issue's scenario quite educational and added a negative test for it.
I also decided to add a similar positive test and it looks like it found actual issue in the validation code.
@jzulauf-lunarg Could you the check positive test if that's the case?
The positive test is disabled for now. If that's a real issue it will be fixed separately. When enabled it reports:
> Validation Error: [ SYNC-HAZARD-WRITE-AFTER-READ ] Object 0: handle = 0xf56c9b0000000004, type = VK_OBJECT_TYPE_IMAGE; | MessageID = 0x376bc9df | vkCmdPipelineBarrier2():  Hazard WRITE_AFTER_READ for image …
=> tests: Add tests inspired by issue 7486

layers/core_checks/cc_pipeline_graphics.cpp, tests/unit/dynamic_rendering_positive.cpp
will merge when https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/6518 is approved (cc @zhangyiwei)
=> layers: Check for VK_FORMAT_UNDEFINED for dynamic rendering

layers/core_checks/cc_drawdispatch.cpp, layers/core_checks/cc_pipeline_graphics.cpp, layers/vulkan/generated/object_tracker.cpp, scripts/generate_source.py, scripts/generators/generator_utils.py, scripts/generators/object_tracker_generator.py, scripts/generators/stateless_validation_helper_generator.py, scripts/generators/sync_validation_generator.py, scripts/generators/valid_enum_values_generator.py, tests/unit/fragment_shading_rate.cpp, tests/unit/query.cpp
This is the PR with the promised fixes for the SPIR-V checks that do not verify that SPIR-V data is available, various script fixes, particularly around the handling of promoted extensions, and other miscellaneous fixes for issues we found downstream.
=> layers: Upstream layer, script, and test fixes from SC VVL

layers/core_checks/cc_shader_object.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/7648
=> layers: Fix maxTessellationPatchSize check

layers/vulkan/generated/layer_chassis_dispatch.cpp, scripts/generators/layer_chassis_dispatch_generator.py
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/7592
=> scripts: Fix WrapPnextChainHandles

layers/core_checks/cc_image.cpp, layers/core_checks/cc_pipeline_graphics.cpp, layers/core_checks/cc_synchronization.cpp, layers/sync/sync_vuid_maps.cpp, layers/sync/sync_vuid_maps.h, tests/unit/graphics_library.cpp, tests/unit/image.cpp, tests/unit/image_drm.cpp, tests/unit/sync_object.cpp
=> layers: Label new VUID from 280 spec

layers/best_practices/best_practices_validation.h, layers/best_practices/bp_cmd_buffer.cpp, layers/best_practices/bp_drawdispatch.cpp, layers/best_practices/bp_state.h, scripts/known_good.json, tests/unit/best_practices.cpp, tests/unit/best_practices_positive.cpp, tests/unit/ray_tracing.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/7636
=> bp: Track vertex buffer through whole command buffer

layers/core_checks/cc_descriptor.cpp, layers/core_checks/cc_pipeline_graphics.cpp, layers/core_checks/core_validation.h, tests/unit/graphics_library.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/7408
adds `VUID-VkGraphicsPipelineCreateInfo-flags-06730`
=> layers: Add GPL Layout union compatible check

layers/stateless/sl_utils.cpp
Realize we were not using `Location` here
=> layers: Remove strncmp for Location

layers/stateless/sl_utils.cpp, layers/stateless/stateless_validation.h, layers/vulkan/generated/stateless_validation_helper.cpp, scripts/generators/stateless_validation_helper_generator.py
another attempt for https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/7680
=> layers: Split up ValidatePnextStructContents

layers/core_checks/cc_copy_blit_resolve.cpp
we were looping through `pRegions` twice in `CoreChecks::ValidateCmdCopyImage`
=> layers: Combined image region loop logic

layers/state_tracker/image_state.cpp, layers/state_tracker/state_tracker.cpp, layers/state_tracker/state_tracker.h, tests/unit/wsi_positive.cpp
=> Fix validating swapchain images when they are acquired before getting them

layers/state_tracker/state_tracker.cpp, tests/unit/wsi_positive.cpp
Closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/7025
Also fixes https://github.com/KhronosGroup/Vulkan-Samples/pull/617 (@ShabbyX)
Pretty happy that `PresentSync` pass can be used here (12 strikes positively back).
=> layers: Add VkSwapchainPresentFenceInfoEXT fence sync support

layers/core_checks/cc_pipeline_graphics.cpp, tests/unit/graphics_library_positive.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/7697
=> layers: Check for valid fragment shader state

scripts/generators/safe_struct_generator.py
There is a future Extension that will have a union similar to the `VkDescriptorDataEXT` that holds a pointer depending on the `type` passed in
To both make the future PR easier and also improve the "why do we do things on this specific struct" logic in the code, I made this groupining
=> scripts: Create union of pointer group

layers/best_practices/best_practices_validation.h, layers/best_practices/bp_framebuffer.cpp, layers/best_practices/bp_pipeline.cpp, layers/core_checks/cc_device_memory.cpp, layers/core_checks/cc_image.cpp, layers/core_checks/cc_image_layout.cpp, layers/core_checks/cc_ray_tracing.cpp, layers/core_checks/cc_render_pass.cpp, layers/core_checks/cc_wsi.cpp, layers/core_checks/core_validation.h, layers/stateless/sl_cmd_buffer_dynamic.cpp, layers/stateless/sl_descriptor.cpp, layers/stateless/sl_device_memory.cpp, layers/stateless/sl_external_object.cpp, layers/stateless/sl_pipeline.cpp, layers/stateless/sl_ray_tracing.cpp, layers/stateless/sl_wsi.cpp, layers/stateless/stateless_validation.h
Found some spots using pointers that could be using a constant reference to the object. This leads to better understanding if we expect pointers to possibly be null or not in a function
=> layers: Make more use of const ref

layers/core_checks/cc_pipeline_graphics.cpp, layers/core_checks/core_validation.h, layers/state_tracker/shader_module.cpp, layers/state_tracker/shader_module.h, tests/unit/mesh.cpp, tests/unit/mesh_positive.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/7614
=> layers: Add Mesh DrawIndex undefined value

tests/unit/protected_memory.cpp
This test used old way to find the Protected Memory
Latest Mesa Intel drivers expose it in a way the old way was returning incorrect values and the test was failing
=> tests: Fix NegativeProtectedMemory.Memory

tests/unit/descriptor_buffer.cpp
This test was massive and I had an issue in it and hard to spot where it happened
This just takes it and splits it into multiple tests as it should have been
=> tests: Split up NegativeDescriptorBuffer.BindingAndOffsets

tests/unit/command.cpp, tests/unit/dynamic_state.cpp, tests/unit/external_memory_sync.cpp
address some of https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/7731
=> tests: Fix some test running on lavapipe

layers/core_checks/cc_synchronization.cpp, tests/unit/sync_object_positive.cpp
I don't know if this needs to be handled differently, but at least it fixes the crash for now.
=> Fix synchronization crash with dynamic rendering local read image barrier

layers/core_checks/cc_ray_tracing.cpp, tests/unit/ray_tracing_positive.cpp
VkBufferUsageFlags2CreateInfoKHR was ignored for vuid 09542
=> layers: Fix vuid 09542 for buffer usage 2

tests/unit/dynamic_state.cpp
Few fixes for the test suite. A test that segfaults, a test that fails on my machine but shouldn't, and a test that works but I noticed doesn't check for a required feature.
=> Test failures

layers/best_practices/bp_state.h, layers/core_checks/cc_spirv.cpp, layers/error_message/logging.h, layers/layer_options.cpp, layers/layer_options.h, layers/state_tracker/shader_module.cpp, layers/state_tracker/shader_module.h, layers/state_tracker/shader_object_state.h
some spots I noticed we were not using `vvl::unordered_map`/`vvl::unordered_set` where we could
=> layers: Use vvl custom container

layers/state_tracker/queue_state.cpp, layers/state_tracker/semaphore_state.cpp, layers/state_tracker/semaphore_state.h, layers/state_tracker/state_tracker.cpp, layers/state_tracker/submission_reference.h
Cleanup and refactor as follow-up to https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/7736
=> layers: Semaphore cleanup

layers/gpu_shaders/gpu_error_codes.h, layers/gpu_validation/gpu_error_message.cpp, layers/gpu_validation/spirv/bindless_descriptor_pass.cpp, layers/gpu_validation/spirv/buffer_device_address_pass.cpp, layers/gpu_validation/spirv/pass.cpp, layers/gpu_validation/spirv/pass.h, layers/gpu_validation/spirv/ray_query_pass.cpp, tests/unit/gpu_av_oob.cpp, tests/unit/gpu_av_oob_positive.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/7702
(going to add Debug PrintF support for this as well, but will be a separate PR since it requires a PR into SPIR-V Tools)
=> gpuav: Add Multiple EntryPoint support

tests/unit/other_positive.cpp
from https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/7717#discussion_r1543834084
=> tests: Remove comment with incorrect link

tests/unit/debug_printf.cpp
I am going to get multi-entrypoint support working for DebugPrintF, but will probably be next-next week when I get back from PTO
For now, want to get the tests in so it is ready to test with right away
=> tests: Add Multi EntryPoint tests for DebugPrintF

layers/vulkan/generated/spirv_tools_commit_id.h, scripts/known_good.json
SPIRV-Headers has not changed.
=> build: Update SPIRV-Tools and glslang to latest

layers/core_checks/cc_shader_object.cpp, layers/gpu_validation/debug_printf.cpp, layers/gpu_validation/gpu_setup.cpp, layers/gpu_validation/gpu_state_tracker.h, layers/gpu_validation/gpu_subclasses.cpp, layers/state_tracker/pipeline_state.cpp, layers/stateless/sl_ray_tracing.cpp, layers/utils/vk_layer_utils.h
moves `kShaderStageAllRayTracing` from a GPU-AV const to a layer util constant
=> layers: Add util for stage flags

tests/spirv/instrumentation.cpp, tests/spirv/validate_instrumentation.py
Helper to quickly test the time it takes to instrument any single shader
=> tests: Add timer for shader instrumentation

layers/vulkan/generated/stateless_validation_helper.cpp, scripts/generators/stateless_validation_helper_generator.py, tests/unit/other_positive.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/7803
=> layers: Check if device struct is called from instance func

README.md
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/6356
=> docs: Add how to get binaries to README

tests/unit/gpu_av_buffer_device_address.cpp, tests/unit/gpu_av_buffer_device_address_positive.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/7132
After, I am more confident that it is an old AMD Windows driver problem and the tests are good
=> tests: Re-enable GPU-AV BDA tests

layers/gpu_validation/spirv/type_manager.cpp, tests/unit/gpu_av_buffer_device_address_positive.cpp
Thank you @spencer-lunarg for the patch
=> gpu: Fix spirv struct length computation

layers/containers/subresource_adapter.cpp
Restructured code a bit to emphasize the scope of a workaround and what it does.
=> layers: Clarify mock icd workaround

layers/VkLayer_khronos_validation.json.in
sync_queue_submit was set to true by default a while ago but was unset in the Synchronization preset.
=> layers: sync_queue_submit true in the Synchronization preset

layers/core_checks/cc_drawdispatch.cpp, layers/core_checks/core_validation.h, layers/state_tracker/shader_module.cpp, layers/state_tracker/shader_module.h, tests/unit/geometry_tessellation.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/3019
=> layers: Warn if Layer is written to a single layer FB

layers/vulkan/generated/spirv_tools_commit_id.h, scripts/known_good.json
Once again, no SPIRV-Headers changes
=> build: Update glslang and SPIRV-Tools

layers/core_checks/cc_pipeline_graphics.cpp, tests/unit/mesh.cpp
=> layers: Label 09631 VUID

layers/core_checks/cc_cmd_buffer_dynamic.cpp, layers/drawdispatch/drawdispatch_vuids.cpp, layers/drawdispatch/drawdispatch_vuids.h, layers/state_tracker/cmd_buffer_state.h, layers/state_tracker/state_tracker.cpp, tests/unit/pipeline_topology.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/4413
VU was added in 1.3.282 spec
=> layers: Add draw time primitiveRestartEnable check

layers/state_tracker/image_state.cpp
The update function should always set provided data. The caching is only for getters.
Ideally is to have regression test for this, but it doesn't look like the test framework provides relatively simple way to deal with resize.  And  to be honest I can't allocate additional time to work on this, so instead a new item was added to the Test Improvements project: 
https://github.com/orgs/KhronosGroup/projects/15/views/1?pane=issue&itemId=59842280
cc @ShabbyX
=> layers: Fix UpdateCapabilitiesCache

tests/framework/binding.cpp, tests/framework/binding.h, tests/framework/queue_submit_context.cpp, tests/framework/render.cpp, tests/unit/best_practices.cpp, tests/unit/buffer.cpp, tests/unit/command.cpp, tests/unit/command_positive.cpp, tests/unit/copy_buffer_image.cpp, tests/unit/descriptor_buffer.cpp, tests/unit/host_image_copy.cpp, tests/unit/nvidia_best_practices.cpp, tests/unit/others.cpp, tests/unit/pipeline.cpp, tests/unit/push_descriptor.cpp, tests/unit/query.cpp, tests/unit/ray_tracing_nv.cpp, tests/unit/shader_object.cpp, tests/unit/shader_object_positive.cpp, tests/unit/sparse_buffer.cpp, tests/unit/sparse_buffer_positive.cpp, tests/unit/sparse_image.cpp, tests/unit/sparse_image_positive.cpp, tests/unit/sync_object.cpp, tests/unit/sync_object_positive.cpp, tests/unit/sync_val.cpp, tests/unit/sync_val_positive.cpp, tests/unit/threading_positive.cpp, tests/unit/wsi.cpp
Need to write some tests that work with different queues and it's a good opportunity to cleanup some helpers.
=> tests: Update queue family helpers

layers/core_checks/cc_shader_interface.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/7847
=> layers: Print Patch in interface error message

layers/core_checks/cc_pipeline.cpp, layers/core_checks/cc_pipeline_graphics.cpp, layers/state_tracker/pipeline_state.cpp, tests/unit/graphics_library.cpp, tests/unit/graphics_library_positive.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/7835
=> layers: Check linked GPL for stageCount not zero

layers/drawdispatch/descriptor_validator.cpp, layers/drawdispatch/drawdispatch_vuids.cpp, layers/drawdispatch/drawdispatch_vuids.h, layers/error_message/error_strings.h, tests/unit/sampler.cpp
adds `VUID-vkCmdDraw-unnormalizedCoordinates-09635`
=> layers: Add VU 09635

tests/unit/shader_limits.cpp, tests/unit/shader_object.cpp
=> tests: Fix MaxSampleMaskWords tests

layers/core_checks/cc_synchronization.cpp, layers/sync/sync_vuid_maps.cpp, tests/unit/sync_object.cpp
Closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/7861
=> layers: Add Sync1 host stage VUs

layers/gpu_validation/debug_printf.cpp, layers/gpu_validation/gpu_state_tracker.cpp
some nit cleanup I moved to a single PR
=> layers: Nit cleanup in GPU-AV

layers/vulkan/generated/object_tracker.cpp, scripts/generators/object_tracker_generator.py, tests/unit/parent.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/7895
=> scripts: VkPipelineLayoutCreateInfo common parent

layers/chassis/layer_chassis_dispatch_manual.cpp
from https://github.com/KhronosGroup/Vulkan-Utility-Libraries/pull/201
We don't need a safe struct for `safe_VkDescriptorDataEXT`, instead the `DispatchGetDescriptorEXT` was reworked to get the wrapped handle correctly
tested all of `dEQP-VK.binding_model.descriptor_buffer.*
=> layers: Rework DispatchGetDescriptorEXT

layers/state_tracker/state_tracker.cpp
Currently working on the timeline semaphore bug with non-deterministic repro case. Non-determinism is due to map iteration order. This change makes repro case fully deterministic and also good to have in general, additional sources of non-determinism make threading code more tricky to analyze.
=> layers: Notify queues in deterministic order

layers/state_tracker/queue_state.cpp, layers/state_tracker/queue_state.h, layers/state_tracker/state_tracker.cpp, tests/unit/sync_object_positive.cpp
The scenario is shown in the test.
=> layers: Fix vkDeviceWaitIdle deadlock

layers/core_checks/cc_pipeline_graphics.cpp, tests/unit/vertex_input_positive.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/7892
=> layers: Fix drawtime vertex VU 04008

layers/core_checks/cc_drawdispatch.cpp
Hit this VU and wasn't sure what was going on, improved error message a bit
=> layers: Improve Descriptor Buffer error message

layers/vulkan/generated/spirv_tools_commit_id.h, scripts/known_good.json
To grab `spirv-val` fix https://github.com/KhronosGroup/SPIRV-Tools/pull/5654
=> build: Update SPIRV-Tools

tests/unit/gpu_av_descriptor_indexing.cpp, tests/unit/gpu_av_descriptor_indexing_positive.cpp, tests/unit/ray_tracing_nv.cpp, tests/unit/shader_image_access.cpp
add test for https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/7932 when I have time later this/next week to fix it
=> tests: Add Descriptor Indexing GPU-AV tests

tests/unit/gpu_av_descriptor_indexing_positive.cpp
This creates a shader with many indexes (around 50, average of a title like Dota2)
This allows me to quickly see where the cost is for this
=> tests: Add GPU-AV Stress perf test

scripts/known_good.json, tests/unit/shader_interface_positive.cpp
as replacement for https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/7940 (cc @jeremyg-lunarg )
=> build: Update glslang to latest

layers/VkLayer_khronos_validation.json.in
Will set `Warning` and `Performance` warning when selecting the Best Practice preset in `vkconfig`
=> settings: Set warning/perf for Best Practice preset

layers/gpu_validation/gpu_settings.h, layers/layer_options.cpp
Default values were not taken into account
=> gpu: Fix settings handling

layers/core_checks/cc_buffer_address.h, layers/core_checks/cc_descriptor.cpp
Use FormatHandle to print buffers
=> layers: Update buffer address related VU error msg

layers/core_checks/cc_buffer_address.h, layers/core_checks/cc_device_memory.cpp, layers/core_checks/cc_ray_tracing.cpp, layers/stateless/sl_ray_tracing.cpp, layers/stateless/stateless_validation.h
skip was not propagated correctly
=> layers: Fix skip management in RT validation

layers/gpu_validation/gpu_descriptor_set.cpp, layers/gpu_validation/gpu_error_message.cpp, layers/gpu_validation/gpu_image_layout.cpp, layers/gpu_validation/gpu_record.cpp, layers/gpu_validation/gpu_resources.h, layers/gpu_validation/gpu_setup.cpp, layers/gpu_validation/gpu_state_tracker.cpp, layers/gpu_validation/gpu_subclasses.cpp, layers/gpu_validation/gpu_validation.cpp, layers/gpu_validation/gpu_validation.h
Also remove leftover from removed acceleration structure validation
=> gpu: Enclose in namespace gpuav

layers/stateless/sl_utils.cpp, tests/unit/others.cpp
Hit this error and wasn't sure what the actual invalid flag value was, so now printing it out
=> layers: Improve invalid VkFlag error message

layers/utils/vk_layer_utils.h
Add cctype for the usages of std::tolower and std:toupper.
=> layer: Add header for std::tolower and std::toupper

layers/core_checks/cc_drawdispatch.cpp, tests/unit/shader_object.cpp
Discussed in https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/6623
(will be in next header release)
cc @ziga-lunarg
=> layers: Check for VK_SHADER_CREATE_DISPATCH_BASE_BIT_EXT

layers/core_checks/cc_descriptor.cpp
Avoid a null pointer dereference if this function encounters an invalid VkBuffer handle. This error should be caught by the object tracker but core validation shouldn't crash.
Additionally, doing:
`    auto &state_object = *Get<>(handle);
`
Defeats the state tracker reference counting scheme and could cause a use after free error if a buggy application deletes a handle while validation is using its state object.
Fixes #7972
=> corechecks: Avoid crashing in ValidateBufferUpdate

layers/object_tracker/object_tracker_utils.cpp, tests/unit/debug_extensions_positive.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/7977
=> layers: Fix Swapchain DebugMarker false positive

layers/sync/sync_submit.cpp
Unsignal is called immediately after `vvl::TlsGuard<QueueXXXCmdState>` is constructed, and in that case nothing is added to `signaled_` yet. Assert checks that condition.
Also Unsignal is always called on the child object (not on the parent `signaled_semaphores_`). That's why prev_ != null. Assert this too.
=> sync: Simplify SignaledSemaphores::Unsignal

layers/core_checks/cc_spirv.cpp, tests/unit/shader_interface.cpp, tests/unit/shader_interface_positive.cpp
adds `VUID-RuntimeSpirv-None-09558` for `VK_KHR_dynamic_rendering_local_read`
=> layer: Add InputAttachmentIndex SPIR-V check

layers/core_checks/cc_synchronization.cpp, tests/unit/dynamic_rendering.cpp, tests/unit/dynamic_rendering_local_read.cpp, tests/unit/subpass.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/5631
Confirmed the VUs are actually done and wrote extra tests to confirm
=> tests: Add missing subpass pipeline barrier tests

tests/unit/gpu_av.cpp, tests/unit/gpu_av_positive.cpp, tests/unit/gpu_av_shader_object_positive.cpp
The `SelectInstrumentedShaders` have not been running properly and this fixes them
=> tests: Fix SelectInstrumentedShaders tests

layers/gpu_validation/gpu_validation.cpp, tests/unit/gpu_av_indirect_buffer.cpp, tests/unit/gpu_av_oob.cpp
Feature check is invalid, see https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/8001
=> gpu: Remove feature check

layers/core_checks/cc_image.cpp, layers/core_checks/core_validation.h, layers/state_tracker/state_tracker.cpp, layers/state_tracker/state_tracker.h, scripts/known_good.json, tests/device_profiles/max_profile.json, tests/unit/image.cpp, tests/unit/image_positive.cpp
Simple extension that just adds a new pNext struct for `VkImageCreateInfo`
=> layers: Add VK_MESA_image_alignment_control

layers/gpu_validation/gpu_setup.cpp
Closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/7993
=> gpu: Fix VMA linear pool flag setting handling

BUILD.gn, layers/CMakeLists.txt, layers/core_checks/cc_pipeline_graphics.cpp, layers/utils/vk_struct_compare.cpp, layers/utils/vk_struct_compare.h
There are some other structs that we will need to do "compare the structs are identical" and want to make a separate PR first to move the logic to its own file
=> layers: Add vk_struct_compare.h

layers/core_checks/cc_cmd_buffer_dynamic.cpp, layers/core_checks/cc_drawdispatch.cpp, layers/core_checks/core_validation.h, layers/state_tracker/cmd_buffer_state.cpp, layers/state_tracker/cmd_buffer_state.h, layers/state_tracker/state_tracker.cpp, layers/vulkan/generated/dynamic_state_helper.cpp, layers/vulkan/generated/dynamic_state_helper.h, scripts/generators/dynamic_state_generator.py
This provides a better error message for dynamic state related messages
=> scripts: Generate Dynamic State error messages

layers/core_checks/cc_shader_interface.cpp, tests/unit/geometry_tessellation.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/8014
=> layer: Remove Tessellation error until spec is resolved

layers/best_practices/bp_copy_blit_resolve.cpp, layers/best_practices/bp_descriptor.cpp, layers/best_practices/bp_instance_device.cpp, layers/best_practices/bp_pipeline.cpp, layers/best_practices/bp_synchronization.cpp, layers/best_practices/bp_wsi.cpp, layers/core_checks/cc_cmd_buffer.cpp, layers/core_checks/cc_descriptor.cpp, layers/core_checks/cc_device_memory.cpp, layers/core_checks/cc_image_layout.cpp, layers/core_checks/cc_queue.cpp, layers/core_checks/cc_render_pass.cpp, layers/core_checks/cc_synchronization.cpp, layers/core_checks/cc_wsi.cpp, layers/core_checks/core_validation.h, layers/state_tracker/semaphore_state.h
=> More StateTracker Null Check cleanup

layers/core_checks/cc_image.cpp, layers/drawdispatch/descriptor_validator.cpp, layers/state_tracker/image_state.cpp, layers/utils/vk_layer_utils.h, tests/unit/image.cpp, tests/unit/image_positive.cpp
We were not doing `VK_REMAINING_MIP_LEVELS`/`VK_REMAINING_ARRAY_LAYERS` correct for all VUs
=> layer: Fix VK_REMAINING_MIP_LEVELS/ARRAY_LAYERS

tests/framework/layer_validation_tests.cpp, tests/unit/arm_best_practices.cpp, tests/unit/best_practices.cpp, tests/unit/command.cpp, tests/unit/command_positive.cpp, tests/unit/debug_extensions.cpp, tests/unit/descriptor_buffer.cpp, tests/unit/descriptors.cpp, tests/unit/dynamic_state.cpp, tests/unit/fragment_shading_rate.cpp, tests/unit/geometry_tessellation.cpp, tests/unit/gpu_av.cpp, tests/unit/gpu_av_buffer_device_address.cpp, tests/unit/gpu_av_descriptor_indexing.cpp, tests/unit/gpu_av_indirect_buffer.cpp, tests/unit/gpu_av_oob.cpp, tests/unit/gpu_av_positive.cpp, tests/unit/gpu_av_ray_query.cpp, tests/unit/gpu_av_ray_tracing.cpp, tests/unit/graphics_library.cpp, tests/unit/mesh.cpp, tests/unit/others.cpp, tests/unit/push_descriptor.cpp, tests/unit/ray_tracing.cpp, tests/unit/video.cpp
Makes use of `SetDesiredError`/`SetDesiredWarning`
=> tests: Use SetDesiredFailureMsg

layers/core_checks/cc_descriptor.cpp, tests/unit/descriptors.cpp
close https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/8065
=> layers: Fix updating zero DSL with zero bindings

tests/unit/shader_spirv_positive.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/8055
Shows the missing `RayQueryPositionFetchKHR` capability was added in the 1.3.285 header release
keywords for others searching:
- `VK_KHR_ray_tracing_position_fetch`
- `SPV_KHR_ray_tracing_position_fetch`
- `GLSL_EXT_ray_tracing_position_fetch`
- `rayQueryGetIntersectionTriangleVertexPositionsEXT`
=> tests: Add RayQueryPositionFetchKHR shader

layers/core_checks/cc_descriptor.cpp, scripts/vk_validation_stats.py, tests/unit/descriptors.cpp
small fixes to make the `vk_validation_stats.py` script happy
=> layers: Fix vk_validation_stats consistency check

layers/core_checks/cc_cmd_buffer.cpp, layers/state_tracker/cmd_buffer_state.cpp, layers/state_tracker/cmd_buffer_state.h, layers/state_tracker/state_tracker.cpp, layers/state_tracker/state_tracker.h, tests/unit/secondary_command_buffer.cpp, tests/unit/secondary_command_buffer_positive.cpp, tests/unit/viewport_inheritance.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/6702
=> layers: Add remaining VK_EXT_nested_command_buffer

layers/core_checks/cc_pipeline.cpp, layers/core_checks/cc_pipeline_compute.cpp, layers/core_checks/cc_pipeline_graphics.cpp, layers/core_checks/cc_pipeline_ray_tracing.cpp, layers/core_checks/cc_spirv.cpp, layers/core_checks/core_validation.h
Some misc cleanup of the `cc_pipeline*` files
=> layers: Cleanup of Pipeline checks

tests/unit/gpu_av_positive.cpp, tests/unit/gpu_av_shader_object_positive.cpp
`PositiveGpuAVShaderObject.SelectInstrumentedShaders` was broken and not running correctly
=> test: Fix Shader Object SelectInstrumentedShaders

layers/core_checks/cc_shader_object.cpp, layers/core_checks/core_validation.h, tests/unit/mesh.cpp
Adds `VUID-vkCreateShadersEXT-pCreateInfos-09632`
=> layer: Add Mesh DrawIndex check for Shader Object

tests/framework/layer_validation_tests.cpp
The latter is deprecated and will be removed in Android 34.
=> Use ALooper_pollOnce instead of ALooper_pollAll

layers/state_tracker/state_tracker.cpp, tests/unit/gpu_av_positive.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/8091
=> layers: Make state tracker more robust to pointer

layers/core_checks/cc_render_pass.cpp, tests/unit/fragment_shading_rate.cpp
Adding a check for VUID-VkFramebufferCreateInfo-renderPass-02553 as we had some erroneous bug reports, I see it's on a list of unimplemented VUID's https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/6730
I haven't created a test yet since the relevant tests seem to be disabled (https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/main/tests/unit/fragment_shading_rate.cpp#L2377)
=> layers: Add VUID-VkFramebufferCreateInfo-renderPass-02553 check

tests/framework/layer_validation_tests.cpp
2nd attempt at https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/8083
cc @jrprice
=> tests: Use ALooper_pollOnce instead of ALooper_pollAll

layers/core_checks/cc_drawdispatch.cpp, layers/core_checks/cc_shader_interface.cpp, tests/device_profiles/max_profile.json, tests/unit/protected_memory.cpp, tests/unit/shader_interface.cpp, tests/unit/shader_interface_positive.cpp, tests/unit/shader_limits.cpp, tests/unit/shader_limits_positive.cpp
We never were checking for `maxFragmentOutputAttachments`, but we do now
=> layers: Add maxFragmentOutputAttachments

tests/unit/image.cpp, tests/unit/shader_object.cpp
some edge cases that were failing on RADV
=> tests: Fix tests on RADV

layers/sync/sync_submit.cpp, layers/sync/sync_submit.h, layers/sync/sync_validation.cpp
We had this structure of SyncValidator::ValidateQueueSubmit:
```
ValidateQueueSubmit() {
for (0..submitCount) {
batch = CreateBatch();
batch->SetupAccess();
batch->SetCommands();
batch->SetLabels();
if (has_tags)  {
batch->SetupTags();
skip |= batch->DoValidate();
} else {
batch->ReplayLabels();
}
batch->Cleanup();
}
...
}
```
Most calls went into Batch with little logic from the caller itself. Now when I need to modify this sequence I have to add even more to the Batch interface. Basically Batch interface models the algorithm rather than something more fundamental about the type.
Based on that I put that "algorithm" into the Batch type itself, will also help to modify it for timeline code (will split into more specific parts if necessary). As a bonus less LOC.
=> sync: Refactor ValidateQueueSubmit

layers/gpu/cmd_validation/gpuav_draw.cpp, layers/gpu/core/gpuav.cpp, layers/gpu/core/gpuav_setup.cpp, layers/gpu/descriptor_validation/gpuav_descriptor_set.cpp, layers/gpu/descriptor_validation/gpuav_descriptor_set.h, layers/gpu/descriptor_validation/gpuav_descriptor_validation.cpp, layers/gpu/descriptor_validation/gpuav_descriptor_validation.h, layers/gpu/instrumentation/gpuav_instrumentation.cpp, layers/gpu/resources/gpuav_subclasses.cpp, layers/gpu/resources/gpuav_subclasses.h
Also cleanup some error messages
=> gpu: Call InternalError in GetOutputState

layers/state_tracker/descriptor_sets.cpp, layers/state_tracker/descriptor_sets.h, layers/sync/sync_commandbuffer.cpp, tests/unit/sync_val_positive.cpp
Addresses https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/8084 (at least non-overlapping accesses part)
=> sync: Apply descriptor dynamic offset

layers/state_tracker/shader_module.h
per @artem-lunarg request, hopefully this sums up all the "fun" around SPIR-V variable accesses
=> layers: Add more details about VariableBase access getters

layers/best_practices/bp_drawdispatch.cpp, layers/core_checks/cc_pipeline.cpp, layers/core_checks/cc_pipeline_compute.cpp, layers/core_checks/cc_pipeline_graphics.cpp, layers/core_checks/cc_pipeline_ray_tracing.cpp, layers/core_checks/cc_spirv.cpp, layers/core_checks/core_validation.h, layers/state_tracker/pipeline_state.cpp, layers/state_tracker/pipeline_sub_state.cpp, layers/state_tracker/shader_module.cpp, layers/state_tracker/shader_module.h, layers/stateless/sl_pipeline.cpp, layers/stateless/sl_ray_tracing.cpp, layers/stateless/stateless_validation.h, layers/vulkan/generated/stateless_validation_helper.cpp, layers/vulkan/generated/stateless_validation_helper.h, scripts/generators/stateless_validation_helper_generator.py, tests/unit/debug_printf.cpp, tests/unit/graphics_library.cpp, tests/unit/pipeline.cpp, tests/unit/pipeline_positive.cpp, tests/unit/shader_compute.cpp, tests/unit/shader_interface.cpp, tests/unit/shader_spirv.cpp
test to help reproduce https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/8103
=> tests: DebugPrintf LocalSizeId

layers/sync/sync_submit.cpp, layers/sync/sync_submit.h, layers/sync/sync_validation.cpp
Having `ResolveSubmitDependencies`  as a separate step will allow to report if there are unresolved dependencies (wait-before-signal), so we can postpone processing of unresolved batches.
Some general cleanup and similar changes in present code.
=> sync: Extract ResolveSubmitDependencies step

layers/stateless/sl_pipeline.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/8156
=> layers: Update 00292 message

layers/core_checks/cc_shader_interface.cpp, layers/state_tracker/shader_module.cpp, tests/unit/atomics.cpp, tests/unit/descriptor_indexing_positive.cpp, tests/unit/descriptors.cpp, tests/unit/gpu_av_positive.cpp, tests/unit/protected_memory.cpp, tests/unit/shader_interface_positive.cpp, tests/unit/shader_limits.cpp, tests/unit/shader_spirv.cpp, tests/unit/shader_spirv_positive.cpp, tests/unit/sync_val_positive.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/7388
=> layers: Add MaxFragmentCombinedOutputResources check

layers/core_checks/cc_device.cpp, layers/core_checks/core_validation.h, tests/unit/others.cpp
simple check, we already have `is_device_lost` piped out so
=> layers: Add vkGetDeviceFaultInfoEXT check

tests/unit/descriptors.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/6621
=> tests: Make sure we don't crash with bad layout

layers/state_tracker/descriptor_sets.h
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/5074
=> layers: Add empty check for GetMaxBinding

layers/best_practices/best_practices_validation.h, layers/best_practices/bp_pipeline.cpp, layers/chassis/layer_chassis_dispatch_manual.cpp, layers/drawdispatch/descriptor_validator.cpp, layers/state_tracker/cmd_buffer_state.cpp
Found these while working on other things, seem like spots were I couldn't quickly confirm we will always have a valid pointer so added assert/null checks
=> layers: Extra null checks

layers/best_practices/best_practices_validation.h, layers/best_practices/bp_device_memory.cpp, layers/core_checks/cc_device_memory.cpp, layers/state_tracker/device_memory_state.h, layers/state_tracker/state_tracker.cpp, layers/vulkan/generated/best_practices.cpp, scripts/generators/best_practices_generator.py, tests/unit/memory.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/5527
=> layers: Handle partial bound image/buffer

scripts/gn/generate_vulkan_layers_json.py
Should be a fix for https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/8185#issuecomment-2186884474
@y-novikov if you want to try this
=> build: Fix GN build for JSON_LAYER_NAME

tests/framework/ray_tracing_objects.cpp, tests/framework/ray_tracing_objects.h, tests/unit/gpu_av_ray_query.cpp, tests/unit/gpu_av_ray_query_positive.cpp, tests/unit/gpu_av_ray_tracing_positive.cpp, tests/unit/ray_tracing.cpp, tests/unit/ray_tracing_pipeline.cpp, tests/unit/ray_tracing_pipeline_positive.cpp, tests/unit/ray_tracing_positive.cpp
Closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/7989
Also rework descriptor set management in ray tracing pipeline test framework
=> tests: Add gpuav BasicTraceRaysMultiEntryPoint

scripts/vk_validation_stats.py
Just updates where we look for VUID tags
we have since moved them out of most headers and state_tracker files
=> scripts: Update paths for vk_validation_stats.py

layers/core_checks/cc_cmd_buffer_dynamic.cpp, layers/core_checks/cc_descriptor.cpp, layers/core_checks/cc_queue.cpp, layers/core_checks/cc_ray_tracing.cpp, layers/drawdispatch/drawdispatch_vuids.cpp, layers/drawdispatch/drawdispatch_vuids.h, layers/state_tracker/pipeline_state.cpp, layers/state_tracker/pipeline_state.h, tests/unit/descriptors.cpp, tests/unit/dynamic_state.cpp, tests/unit/ray_tracing.cpp, tests/unit/ray_tracing_positive.cpp, tests/unit/shader_object.cpp
Add changes from 1.3.289 header update
=> layers: Fixes for 1.3.289 header

layers/core_checks/cc_cmd_buffer.cpp, layers/core_checks/cc_descriptor.cpp, layers/core_checks/cc_render_pass.cpp, layers/core_checks/core_validation.h, layers/state_tracker/state_tracker.cpp, layers/state_tracker/state_tracker.h, layers/stateless/sl_instance_device.cpp, layers/stateless/stateless_validation.h, layers/vulkan/generated/stateless_validation_helper.cpp, scripts/generators/stateless_validation_helper_generator.py, tests/device_profiles/max_profile.json, tests/unit/dynamic_rendering.cpp, tests/unit/others.cpp, tests/unit/render_pass.cpp, tests/unit/render_pass_positive.cpp
Most of `VK_KHR_maintenance7` for validation is just allowing things that were not previously allowed, but now drivers will support (if using the extension/feature)
=> layers: Add VK_KHR_maintenance7

layers/sync/sync_submit.cpp, layers/sync/sync_submit.h, layers/sync/sync_validation.cpp, layers/utils/convert_utils.cpp, layers/utils/convert_utils.h
and moved `SubmitInfoConverter` to `convert_utils`, not syncval specific.
=> layers: Refactor SubmitInfoConverter

layers/core_checks/cc_render_pass.cpp, tests/unit/fragment_shading_rate.cpp
New checks for:
* VUID-VkFramebufferCreateInfo-flags-03196
* VUID-VkFramebufferCreateInfo-flags-03197
=> layers: Add fragment density map imageless size checks

tests/framework/binding.h
=> tests: Fix typo in binding.h

layers/core_checks/cc_spirv.cpp, tests/unit/atomics.cpp, tests/unit/atomics_positive.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/8223
logic was wrong, tests were added, error message also greatly improved
=> layers: Fix vertexPipelineStoresAndAtomics

layers/core_checks/cc_cmd_buffer_dynamic.cpp, layers/core_checks/cc_pipeline_graphics.cpp
from https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/8235#discussion_r1664880388
=> layers: Use GetCreateInfoPNext

layers/best_practices/bp_cmd_buffer.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/8257
=> bp: Fixes false positive for vkCmdBeginQuery

tests/unit/gpu_av_shader_object_positive.cpp
Closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/8136
=> gpu: Add shader objects push constants tests

scripts/vk_validation_stats.py
Add -vendor option to allow vendor specific vuid filtering for vk_validation_stats.py script.
Sidenote: Previously only vendor specific vuids were printed and only in HTML mode. In any other cases all vuids were printed out.
=> scripts: Allow vendor filtering in vk_validation_stats.py

layers/gpu/spirv/README.md, layers/gpu/spirv/bindless_descriptor_pass.cpp, layers/gpu/spirv/bindless_descriptor_pass.h, layers/gpu/spirv/buffer_device_address_pass.cpp, layers/gpu/spirv/buffer_device_address_pass.h, layers/gpu/spirv/function_basic_block.cpp, layers/gpu/spirv/function_basic_block.h, layers/gpu/spirv/pass.cpp, layers/gpu/spirv/pass.h, layers/gpu/spirv/ray_query_pass.cpp, layers/gpu/spirv/ray_query_pass.h
2nd attempt at https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/8170
=> gpu: Add experimental non-conditional injection

tests/unit/ray_tracing_positive.cpp
Test that binding a graphics pipeline width dynamic line width state does not affect a ray tracing pipeline
=> tests: Positive test for setting unused dynamic state

tests/unit/debug_printf.cpp
The current DebugPrintF tests were full of shaders that looped which sub tests it was suppose to run
This separates tests in a way to easily unit test each part of the `printf` logic
This also adds a lot of coverage that was missing
=> tests: Cleanup and Add DebugPrintF tests

layers/core_checks/cc_device.cpp
Closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/8285
=> layers: Fix parameter name

layers/core_checks/cc_render_pass.cpp, layers/core_checks/cc_spirv.cpp, scripts/generate_spec_error_message.py, tests/unit/imageless_framebuffer.cpp, tests/unit/shader_cooperative_matrix.cpp
The following to internal spec changes required VUID fixing
- https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/6319
- https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/6766
=> Fix VUID Churn from 290 headers

docs/debug_printf.md, layers/gpu/debug_printf/debug_printf.cpp, tests/unit/debug_printf.cpp
- Update documentation
- Improve `VK_LAYER_PRINTF_BUFFER_SIZE` overflow warning
- More tests!
=> printf: More test and doc cleanup

tests/unit/descriptors_positive.cpp
The ImmutableSamplerOnlyDescriptor test should create a descriptor where the sampler is specified so it has an immutable sampler. Furthermore, do some simple drawing to correctly check if the descriptor set binding points were updated or not.
=> tests: Fix PositiveDescriptors.ImmutableSamplerOnlyDescriptor

layers/state_tracker/descriptor_sets.cpp
small perf fix found from profiling around
=> layers: Use emplace_back in DescriptorSet

layers/error_message/logging.cpp, layers/error_message/logging.h, layers/vulkan/generated/chassis.h, scripts/generators/layer_chassis_generator.py
noticed this TODO and realize could fix it
=> layers: Set Loc as const ref in LogMsg

layers/core_checks/cc_copy_blit_resolve.cpp, layers/state_tracker/device_memory_state.cpp, layers/state_tracker/device_memory_state.h, tests/unit/sparse_buffer.cpp, tests/unit/sparse_buffer_positive.cpp
Handle copies between buffers where only one is sparse
=> layers: Handle sparse/not sparse buffer copies

layers/core_checks/cc_video.cpp, tests/unit/video.cpp
I found a few issues while running the {Negative,Positive}Video tests against AMD's implementation.
CC: @aqnuep
=> Miscellaneous video fixes

tests/spirv/instrumentation.cpp, tests/spirv/profile_instrumentation.py
Allows us to get a baseline of how slow/fast our SPIR-V instrumentation is as we add more things to it
results posted internally due to nature of traces
=> Add profiling script for spirv instrumentation

layers/gpu/cmd_validation/gpuav_cmd_validation_common.cpp, layers/gpu/cmd_validation/gpuav_cmd_validation_common.h, layers/gpu/cmd_validation/gpuav_copy_buffer_to_image.cpp, layers/gpu/cmd_validation/gpuav_copy_buffer_to_image.h, layers/gpu/cmd_validation/gpuav_trace_rays.cpp, layers/gpu/core/gpuav_record.cpp, layers/gpu/core/gpuav_setup.cpp, layers/gpu/descriptor_validation/gpuav_descriptor_set.cpp, layers/gpu/descriptor_validation/gpuav_descriptor_set.h, layers/gpu/descriptor_validation/gpuav_descriptor_validation.cpp, layers/gpu/descriptor_validation/gpuav_descriptor_validation.h, layers/gpu/descriptor_validation/gpuav_image_layout.cpp, layers/gpu/instrumentation/gpu_shader_instrumentor.cpp, layers/gpu/instrumentation/gpu_shader_instrumentor.h, layers/gpu/resources/gpu_resources.cpp, layers/gpu/resources/gpu_resources.h, layers/gpu/resources/gpu_shader_resources.h, layers/gpu/resources/gpuav_subclasses.cpp
Some more cleanup separated in a separate PR
=> gpu: More cleanup around descriptor indexing

layers/gpu/debug_printf/debug_printf.cpp, layers/gpu/spirv/debug_printf_pass.cpp, layers/gpu/spirv/debug_printf_pass.h, tests/unit/debug_printf.cpp
As my original test showed, this was never working and now will print the correct values out
=> printf: Fix 8-bit 16-bit signed ints

layers/gpu/instrumentation/gpu_shader_instrumentor.cpp, layers/gpu/spirv/debug_printf_pass.cpp, layers/gpu/spirv/module.cpp, layers/gpu/spirv/module.h, tests/spirv/instrumentation.cpp
Create a setting struct that we can pass things down like required features support
=> gpu: Add feature support checks for shader instrumentation

layers/chassis/layer_chassis_dispatch_manual.cpp, layers/vulkan/generated/layer_chassis_dispatch.cpp, layers/vulkan/generated/layer_chassis_dispatch.h, scripts/generators/layer_chassis_dispatch_generator.py
=> core: Fix WrapPnextChainHandles name

layers/chassis/chassis_modification_state.h, layers/gpu/instrumentation/gpu_shader_instrumentor.cpp
cleanup from https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/8381#discussion_r1714718004
=> gpu: Remove extra copy of safe structs

layers/state_tracker/semaphore_state.cpp, tests/unit/sync_object_positive.cpp
Addresses  https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/8212 and potentially https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/8375.
=> sync: Fix vkGetSemaphoreCounterValue leaves orphaned signal

scripts/check_code_format.py
can now run `check_code_format.py` from any directory
also moved things to f-strings like rest of scripts
=> scripts: Fix check_code_format.py

docs/gpu_validation.md, layers/gpu/instrumentation/gpuav_instrumentation.cpp
All GPU-AV tests pass with Self Validation now on Mesa Intel
=> gpu: Pass all tests with self val

layers/core_checks/cc_spirv.cpp, layers/core_checks/core_validation.h, layers/stateless/sl_pipeline.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/8418
=> layers: Improve RequiredSubgroupSizeCreateInfo messages

layers/core_checks/cc_spirv.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/8419
=> layers: Fix 06038 wording

tests/unit/sync_object.cpp
Adds test for `VK_ACCESS_2_DESCRIPTOR_BUFFER_READ_BIT_EXT` (`VUID-VkMemoryBarrier2-srcAccessMask-08118`)
=> tests: Add Descriptor Buffer Access Bit

layers/core_checks/cc_descriptor.cpp
some misc cleanup around `VK_EXT_descriptor_buffer`
=> layers: Misc Descriptor Buffer message cleanup

README.md, docs/README.md, docs/limitations.md
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/8409
=> docs: Add Limitations documentations

layers/core_checks/cc_shader_interface.cpp, tests/unit/geometry_tessellation_positive.cpp, tests/unit/shader_interface.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/8443
Before, we made the assumption that the order of `VkGraphicsPipelineCreateInfo::pStages` was how to get the consumer/producer stages for checking interface matching
We now sort the graphics stages correctly
=> layers: Sort stages for ValidateInterfaceBetweenStages

layers/utils/convert_utils.cpp
Sync1->Sync2 submit converter did not check for `VkTimelineSemaphoreSubmitInfo`. Should not affect main branch where timeline values are ignored. There are tests on the timeline branch.
Basically all timeline testing is done using Sync2 API, Sync1 requires minimal testing to ensure converter works (to find bugs like this one).
=> sync: Fix SubmitInfoConverter does not store timeline values

scripts/known_good.json
Had to manually use it to alter settings in latest extensions, want to make sure CI is also running with a latest version
=> scripts: Update Profiles in known_good.json

tests/unit/sync_object.cpp
Need this test for investigation, updated it to use test helpers.
=> tests: Cleanup SignalSemaphoreValue test

layers/core_checks/cc_android.cpp, layers/core_checks/cc_buffer.cpp, layers/core_checks/cc_device_memory.cpp, layers/core_checks/cc_external_object.cpp, layers/core_checks/cc_pipeline.cpp, layers/core_checks/cc_synchronization.cpp, layers/core_checks/core_validation.h, layers/gpu/instrumentation/gpu_shader_instrumentor.cpp, layers/vulkan/generated/chassis.cpp, layers/vulkan/generated/chassis.h, scripts/generators/layer_chassis_generator.py, tests/unit/pipeline.cpp
Fix some non GPU-AV tests that were failing Self Validation
=> layers: Fix more Self Validation errors

layers/chassis/chassis_modification_state.h, layers/gpu/debug_printf/debug_printf.cpp, layers/gpu/instrumentation/gpu_shader_instrumentor.cpp, layers/state_tracker/pipeline_state.h, layers/state_tracker/shader_object_state.h
I messed up my git and forgot to apply @arno-lunarg patches before I merged the PR in https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/8482
=> gpu: Apply missing patches from 8482

layers/core_checks/cc_cmd_buffer_dynamic.cpp, layers/state_tracker/cmd_buffer_state.h, tests/unit/dynamic_state_positive.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/8444
=> layers: Fix VK_DYNAMIC_STATE_COLOR_BLEND_ENABLE_EXT false positive

layers/core_checks/cc_cmd_buffer_dynamic.cpp, tests/unit/dynamic_state_positive.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/8458
Also made sure it fixed `dEQP-VK.draw.renderpass.instanced.dynamic_state_draw_vk_primitive_topology_point_list`
=> layers: Fix vkCmdSetVertexInputEXT false positive

tests/unit/descriptor_buffer_positive.cpp
This adds some more full tests for descriptor buffers
this was half me trying to make sure i grasped the API before digging more into issues around it... half, when I want to write a test, I have a starting boilerplate to go off of
=> tests: Add some larger Descriptor Buffer tests

scripts/known_good.json, tests/unit/render_pass_positive.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/8388 by grabbing https://github.com/KhronosGroup/Vulkan-Utility-Libraries/pull/232
=> scripts: Grab latest VUL for VK_EXT_sample_locations

tests/CMakeLists.txt, tests/framework/buffer_helper.h, tests/unit/debug_printf.cpp
For https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/8503
Added a DebugPrintf test for
- DispatchIndirect
- DispatchBase
- DrawIndexed
- DrawIndexedIndirect
- DrawIndirectCount
- DrawIndexedIndirectCount
=> tests: Add Indexed and Indirect printf

layers/core_checks/cc_buffer.cpp, layers/core_checks/cc_descriptor.cpp, layers/core_checks/cc_spirv.cpp, layers/state_tracker/state_tracker.cpp, layers/state_tracker/state_tracker.h, layers/stateless/sl_buffer.cpp, layers/stateless/sl_instance_device.cpp, layers/stateless/stateless_validation.h, tests/unit/buffer.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/8423
=> layers: Fix Getting VkPhysicalDeviceVulkan13Properties

layers/containers/custom_containers.h, layers/sync/sync_stats.cpp, layers/sync/sync_stats.h, tests/framework/binding.cpp, tests/framework/binding.h, tests/framework/render.cpp, tests/framework/render.h
Some general helpers to minimize diff.
=> tests: Add new test helpers from timeline branch

layers/gpu/instrumentation/gpu_shader_instrumentor.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/8528
=> gpu: Don't emit redundant warnings

docs/generated_code.md, scripts/generate_source.py, scripts/generators/extension_helper_generator.py
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/8449
=> scripts: Improve error importing Reg

tests/unit/instance_positive.cpp
for https://github.com/KhronosGroup/Vulkan-Utility-Libraries/issues/234
=> tests: Null VkLayerSettingsCreateInfoEXT

layers/gpu/spirv/bindless_descriptor_pass.cpp, layers/gpu/spirv/buffer_device_address_pass.cpp, layers/gpu/spirv/debug_printf_pass.cpp, layers/gpu/spirv/non_bindless_oob_buffer_pass.cpp, layers/gpu/spirv/non_bindless_oob_texel_buffer_pass.cpp, layers/gpu/spirv/ray_query_pass.cpp
=> gpu: Print debug info on one line

layers/gpu/instrumentation/gpu_shader_instrumentor.cpp, layers/gpu/instrumentation/gpu_shader_instrumentor.h, tests/framework/ray_tracing_objects.cpp, tests/framework/ray_tracing_objects.h, tests/unit/gpu_av.cpp, tests/unit/gpu_av_ray_tracing.cpp
New test disabled, see https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/8545
=> gpu: Remove PostCallRecordPipelineCreationsRT

layers/sync/sync_submit.cpp, layers/sync/sync_submit.h
Forgot to add this in https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/8527
=> sync: Register QueueBatchContext in stats system

layers/gpu/core/gpuav_setup.cpp, tests/framework/error_monitor.cpp, tests/unit/gpu_av.cpp
Closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/8414
=> gpu: Auto enable uniformAndStorageBuffer8BitAccess

tests/unit/sync_object_positive.cpp
PR to blacklist linux nvidia machine: https://github.com/LunarG/VulkanTests/pull/629, potentially will need to do the same for windows nvidia machine.
Also add iteration count to have more variations of multithreaded behavior.
=> tests: Remove workaround from KhronosTimelineSemaphoreExample

tests/unit/pipeline_positive.cpp
Precursor to improvements/fixes to pipeline derivative validation (particularly for compute)
=> tests: Add positive tests for compute pipeline derivatives

layers/core_checks/cc_cmd_buffer_dynamic.cpp, layers/drawdispatch/drawdispatch_vuids.cpp, layers/drawdispatch/drawdispatch_vuids.h, layers/state_tracker/pipeline_state.cpp, layers/state_tracker/pipeline_state.h, layers/vulkan/generated/dynamic_state_helper.cpp, scripts/generators/dynamic_state_generator.py, tests/unit/shader_object.cpp
attempt 2 of https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/8593 but removed the the topology changes (https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/6876) until have time to look more into them
=> Combining more Dynamic State for upcoming header

layers/core_checks/cc_descriptor.cpp, layers/gpu/cmd_validation/gpuav_cmd_validation_common.cpp, layers/gpu/core/gpuav.h, layers/gpu/core/gpuav_record.cpp, layers/gpu/debug_printf/debug_printf.cpp, layers/gpu/instrumentation/gpu_shader_instrumentor.cpp, layers/gpu/instrumentation/gpu_shader_instrumentor.h, layers/gpu/instrumentation/gpuav_instrumentation.cpp, layers/gpu/instrumentation/gpuav_instrumentation.h, layers/state_tracker/pipeline_state.cpp, layers/state_tracker/pipeline_state.h, tests/unit/gpu_av.cpp, tests/unit/gpu_av_descriptor_indexing.cpp, tests/unit/gpu_av_descriptor_indexing_positive.cpp, tests/unit/gpu_av_positive.cpp
Closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/8377
This binding can disturb application binding in some circumstances
Add SharedPipelineLayoutSubset tests
=> gpu: Fix instrumentation desc set binding logic

layers/core_checks/cc_wsi.cpp, tests/unit/wsi.cpp
For https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/8600
=> layers: Update VK_EXT_swapchain_maintenance1 VUs

layers/gpu/core/gpuav_setup.cpp, layers/gpu/instrumentation/gpu_shader_instrumentor.cpp, tests/unit/gpu_av.cpp
attempt 2 from https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/8596 (cc @arno-lunarg )
=> gpu: Force shaderInt64 on

layers/core_checks/cc_spirv.cpp, layers/state_tracker/shader_module.cpp, layers/state_tracker/shader_module.h, layers/state_tracker/state_tracker.cpp, layers/state_tracker/state_tracker.h, tests/device_profiles/max_profile.json, tests/unit/mesh_positive.cpp, tests/unit/shader_mesh.cpp
`VK_KHR_compute_shader_derivatives` was added in 1.3.295
=> layers: Add VK_KHR_compute_shader_derivatives

layers/core_checks/cc_cmd_buffer_dynamic.cpp, layers/drawdispatch/drawdispatch_vuids.cpp, layers/drawdispatch/drawdispatch_vuids.h, tests/unit/dynamic_state.cpp, tests/unit/shader_object.cpp
Based on https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/6870
=> layers: Combine viewportCount dynamic state

layers/sync/sync_validation.cpp, tests/unit/sync_val_semaphore_positive.cpp
Fix issue similar to https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/8331 but this time for timeline signals.
=> sync: Fix iteration over queue batch contexts

layers/core_checks/cc_ray_tracing.cpp, tests/CMakeLists.txt, tests/framework/error_monitor.cpp, tests/framework/error_monitor.h, tests/framework/ray_tracing_objects.cpp, tests/framework/ray_tracing_objects.h, tests/unit/debug_printf_ray_tracing.cpp, tests/unit/gpu_av_ray_tracing_positive.cpp, tests/unit/ray_tracing.cpp, tests/unit/ray_tracing_positive.cpp
Added new ray tracing tests, that actually trace a ray into a triangle and expect to report intersections. It showed some flaws in the ray tracing framework, main one being a synchronisation issue with the function in charge of return a ready to use TLAS
=> printf: Ray tracing tests

tests/unit/sync_val_semaphore.cpp
Just one more scenario that was not tested before.
=> tests: Add one more timeline test

layers/state_tracker/cmd_buffer_state.cpp
Closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/8632
=> layers: Fix push constant recordings leaking

tests/framework/binding.cpp, tests/framework/binding.h, tests/framework/render.cpp, tests/framework/render.h, tests/unit/debug_extensions.cpp, tests/unit/debug_extensions_positive.cpp, tests/unit/gpu_av_positive.cpp, tests/unit/image_positive.cpp, tests/unit/parent.cpp, tests/unit/sync_object_positive.cpp, tests/unit/sync_val_wsi.cpp, tests/unit/sync_val_wsi_positive.cpp, tests/unit/wsi.cpp, tests/unit/wsi_positive.cpp
Some remaining parts. We also need to unify helpers for swapchain image layout transition and create info initialization but probably for another time.
=> tests: More WSI cleanup

tests/unit/sync_val_positive.cpp
The false-positive is covered by the earlier fix https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/7552
Note, that syncval does not have special support for queue ownership transfer yet. The current issue is covered by the fix to a regular pipeline barrier (no ownership transfer).
Closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/7024
=> tests: Add regression test for issue 7024

layers/gpu/debug_printf/debug_printf.cpp, layers/gpu/shaders/gpuav_error_header.h, layers/gpu/spirv/debug_printf_pass.cpp, layers/gpu/spirv/instruction.cpp, tests/unit/debug_printf_ray_tracing.cpp
Also misc cleanup I did while chasing a bug in debug printf that turned out to be an output buffer too small
=> printf: Add deferred RT pipeline test

layers/gpu/debug_printf/debug_printf.cpp, layers/gpu/instrumentation/gpuav_instrumentation.cpp, layers/gpu/instrumentation/gpuav_shader_instrumentor.cpp, layers/gpu/instrumentation/gpuav_shader_instrumentor.h
PR based on https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/8670
I will rebase after it gets merged.
Only second commit is relevant: just some renaming
=> Arno gpu av instrumentation renaming

tests/unit/sync_val_wsi.cpp
Just the test, the issue (https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/5240) is not fixed yet.
The test should be updated to expect the error when the issue is fixed. And if issue gets fixed "accidentally" then the test will start failing, so we will know.
=> tests: Add repro case for issue 5240

layers/vulkan/generated/device_features.cpp, layers/vulkan/generated/device_features.h, scripts/generators/device_features_generator.py
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/8678
=> scripts: Add deviceGeneratedCommands alias

tests/unit/sync_object.cpp
Test based on this ticket: https://gitlab.khronos.org/vulkan/vulkan/-/issues/4046
=> tests: Add binary wait before signal test

layers/core_checks/cc_cmd_buffer_dynamic.cpp, tests/unit/dynamic_state_positive.cpp
fix for change in next header update https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/6921/diffs
=> layers: Add multisampledRenderToSingleSampled check

layers/sync/sync_submit.cpp
Additional information from https://gitlab.khronos.org/vulkan/vulkan/-/issues/4048
=> sync: Update comments about missing binary signal

layers/gpu/instrumentation/gpuav_shader_instrumentor.cpp, tests/unit/debug_printf_shader_debug_info.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/8716
=> gpu: Print out multiple OpEntryPoint stages

layers/core_checks/cc_spirv.cpp, tests/unit/shader_spirv.cpp
More from https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/8709
Went through and added the `DescribeInstruction()` where it is possible to have an instruction to print out
=> layers: Use new DescribeInstruction where possible

tests/unit/shader_spirv.cpp
=> tests: Fix main PR conflict

layers/VkLayer_khronos_validation.json.in, layers/gpu/core/gpuav_settings.h, layers/gpu/instrumentation/gpuav_shader_instrumentor.cpp, layers/gpu/spirv/bindless_descriptor_pass.cpp, layers/gpu/spirv/bindless_descriptor_pass.h, layers/gpu/spirv/buffer_device_address_pass.cpp, layers/gpu/spirv/buffer_device_address_pass.h, layers/gpu/spirv/debug_printf_pass.cpp, layers/gpu/spirv/debug_printf_pass.h, layers/gpu/spirv/inject_conditional_function_pass.cpp, layers/gpu/spirv/inject_conditional_function_pass.h, layers/gpu/spirv/inject_function_pass.cpp, layers/gpu/spirv/inject_function_pass.h, layers/gpu/spirv/module.cpp, layers/gpu/spirv/module.h, layers/gpu/spirv/non_bindless_oob_buffer_pass.cpp, layers/gpu/spirv/non_bindless_oob_buffer_pass.h, layers/gpu/spirv/non_bindless_oob_texel_buffer_pass.cpp, layers/gpu/spirv/non_bindless_oob_texel_buffer_pass.h, layers/gpu/spirv/pass.h, layers/gpu/spirv/post_process_descriptor_indexing.cpp, layers/gpu/spirv/post_process_descriptor_indexing.h, layers/gpu/spirv/ray_query_pass.cpp, layers/gpu/spirv/ray_query_pass.h, layers/layer_options.cpp, tests/spirv/instrumentation.cpp
From https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/8715
=> gpu: Naming cleanup

layers/thread_tracker/thread_safety_validation.cpp
This should be merged upon a confirmation here https://gitlab.khronos.org/vulkan/vulkan/-/issues/3980
=> layers: Added present fences to thread safety checks

layers/core_checks/cc_cmd_buffer_dynamic.cpp, layers/drawdispatch/drawdispatch_vuids.cpp, layers/drawdispatch/drawdispatch_vuids.h, layers/vulkan/generated/dynamic_state_helper.cpp, scripts/generators/dynamic_state_generator.py, tests/unit/dynamic_state.cpp, tests/unit/shader_object.cpp
based on https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/6955
=> layers: Combine Sample Location Enable VUs

layers/core_checks/cc_cmd_buffer_dynamic.cpp, layers/drawdispatch/drawdispatch_vuids.cpp, layers/drawdispatch/drawdispatch_vuids.h, layers/state_tracker/pipeline_state.cpp, layers/state_tracker/pipeline_state.h, layers/vulkan/generated/dynamic_state_helper.cpp, scripts/generators/dynamic_state_generator.py, tests/device_profiles/max_profile.json, tests/unit/dynamic_state.cpp, tests/unit/dynamic_state_positive.cpp, tests/unit/shader_object.cpp, tests/unit/shader_object_positive.cpp
Based on https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/6953
=> layers: Combine Discard Rectangle Mode/Enable VUs

layers/state_tracker/state_tracker.cpp, tests/unit/wsi_positive.cpp
Fixes the root cause of issue https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/8578 and is a candidate to replace PR https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/8736
Thanks @ziga-lunarg for providing test and alternative solution, it helped to understand the problem. The test in this PR is a bit modified comparing to the original one, but the original test also passes.
The previous iterations related to presentation fences:
https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/8400
https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/8454
=> layers: Fix present fence does not retire present semaphores

layers/core_checks/cc_synchronization.cpp, layers/core_checks/cc_synchronization.h, layers/state_tracker/semaphore_state.cpp, layers/state_tracker/semaphore_state.h
Mostly preparations for the future PR to improve some semaphore error messages.
=> layers: Cleanup and minor refactor of semaphore code

layers/core_checks/cc_pipeline_graphics.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/8761
=> layers: Improve message if rasterizerDiscardEnable is true

layers/gpu/resources/gpuav_subclasses.cpp
Addresses performance regression https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/7562
Present batch does not have any GPU-AV work to post process. This is also needed for correctness. QueuePresent does not have a PostSubmit call that signals timeline semaphore - timeline wait is invalid.
=> gpu: Skip present submission

layers/core_checks/cc_cmd_buffer_dynamic.cpp, layers/stateless/sl_pipeline.cpp, tests/unit/dynamic_state.cpp, tests/unit/shader_object.cpp, tests/unit/shader_object_positive.cpp
2nd attempt at https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/8593/commits/b3bd2ba934b3725281490d37cb8ea1978f5e25a7
=> layers: Combine Dynamic Patch Control

layers/core_checks/cc_cmd_buffer_dynamic.cpp, layers/drawdispatch/drawdispatch_vuids.cpp, layers/drawdispatch/drawdispatch_vuids.h, layers/state_tracker/pipeline_state.cpp, layers/state_tracker/pipeline_state.h, tests/unit/dynamic_state.cpp, tests/unit/shader_object.cpp
Combines `vkCmdSetLineStippleKHR` from  https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/6956
cc @ziga-lunarg
=> layers: Combine Stipple Enable Dynamic State

layers/stateless/sl_device_generated_commands.cpp, tests/unit/device_generated_commands.cpp, tests/unit/device_generated_commands_positive.cpp
Adds new VU that will be in 1.3.301 header (https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/6970)
=> layers: Add maxSequenceCount zero VU

scripts/generate_spec_error_message.py
In preparation for https://github.com/KhronosGroup/Vulkan-Docs/pull/2453 I went through and removed old stuff we use to do because the `validusage.json` use to be different before we allowed `ifdef` inside VUs
=> scripts: Cleanup generate_spec_error_message.py

layers/gpu/instrumentation/gpuav_shader_instrumentor.cpp, layers/gpu/spirv/debug_printf_pass.cpp, layers/gpu/spirv/instruction.cpp, layers/gpu/spirv/module.cpp, layers/gpu/spirv/module.h, tests/spirv/instrumentation.cpp
Some upstream code for future work to allow DebugPrintf inside our GPU-AV GLSL shaders
=> printf: Add logic to help allow inside GPU-AV

scripts/generators/base_generator.py, scripts/generators/stateless_validation_helper_generator.py
Propagate aliasing to be able to reach the (eventual) core struct
=> scripts: Fix struct aliasing

layers/gpu/instrumentation/gpuav_shader_instrumentor.cpp
This removes the `CreateAggressiveDCEPass` pass post shader instrumentation in GPU-AV
1. I looked at hundreds of shaders with Mesa, and found the final output from Mesa's compiler is the same regardless of us running `CreateAggressiveDCEPass` or not
2. The time it takes getting the SPIR-V into the SPIRV-Tools internal format, run the pass, save the SPIR-V back out, is **way** more measured overhead than just having the driver's compiler do it while it is compiling
3. We don't have that much left over, found the SPIR-V was barley shrinking after running the pass, sometimes no changes were done at all
=> gpu: Remove spirv-opt pass in shader instrumentation

layers/stateless/sl_device_generated_commands.cpp, layers/stateless/sl_image.cpp, tests/unit/device_generated_commands.cpp, tests/unit/host_image_copy.cpp
adds `VUID-VkImageCreateInfo-usage-10245` and `VUID-VkGeneratedCommandsInfoEXT-maxSequenceCount-10246`
=> layers: Label VUID from 301 header

tests/unit/gpu_av_descriptor_indexing.cpp, tests/unit/gpu_av_oob.cpp, tests/unit/shader_storage_image.cpp
Fixes a few tests that were failing on Windows Arm we are trying to add into CI
=> tests: Fix tests on Windows Arm

tests/unit/best_practices.cpp, tests/unit/debug_printf.cpp, tests/unit/debug_printf_ray_tracing.cpp, tests/unit/debug_printf_shader_debug_info.cpp
Replaces `SetDesiredFailureMsg(kInformationBit`
=> tests: Use SetDesiredInfo

layers/core_checks/cc_query.cpp, layers/core_checks/cc_spirv.cpp, layers/stateless/sl_render_pass.cpp, tests/unit/buffer.cpp, tests/unit/descriptors.cpp, tests/unit/dynamic_rendering.cpp, tests/unit/ray_tracing_nv.cpp, tests/unit/shader_push_constants.cpp, tests/unit/transform_feedback.cpp
From https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/8836#discussion_r1835644862
=> layers: Fix grammar mistakes

layers/stateless/sl_cmd_buffer.cpp, layers/stateless/sl_ray_tracing.cpp, layers/stateless/sl_wsi.cpp, layers/vulkan/generated/stateless_validation_helper.cpp, layers/vulkan/generated/stateless_validation_helper.h, scripts/generators/stateless_validation_helper_generator.py
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/8837
=> Fix stateless code gen for structs

layers/core_checks/cc_buffer.cpp, layers/core_checks/cc_copy_blit_resolve.cpp, layers/core_checks/cc_descriptor.cpp, layers/core_checks/cc_device_memory.cpp, layers/core_checks/cc_pipeline.cpp, layers/core_checks/cc_ray_tracing.cpp
=> layers: Use + instead of plus

layers/VkLayer_khronos_validation.json.in, layers/gpu/core/gpuav_settings.h, layers/gpu/core/gpuav_setup.cpp, layers/gpu/instrumentation/gpuav_shader_instrumentor.cpp, layers/gpu/instrumentation/gpuav_shader_instrumentor.h, layers/vk_layer_settings.txt
tracking at https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/8850
=> gpu: Temporarily disable shader instrumentation cache

layers/core_checks/cc_descriptor.cpp, tests/unit/descriptor_buffer.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/8835
=> layers: Clarify Descriptor Buffer Binding limits

layers/chassis/layer_chassis_dispatch_manual.cpp, layers/stateless/sl_ray_tracing.cpp, layers/stateless/stateless_validation.h, layers/vulkan/generated/layer_chassis_dispatch.cpp, layers/vulkan/generated/stateless_validation_helper.cpp, scripts/generate_source.py, scripts/generators/layer_chassis_dispatch_generator.py, scripts/generators/stateless_validation_helper_generator.py, scripts/known_good.json, tests/unit/ray_tracing.cpp, tests/unit/ray_tracing_positive.cpp
=> VK_EXT_opacity_micromap fix

layers/stateless/sl_utils.cpp, layers/stateless/stateless_validation.h
These comments have been lingering around from day one of validation. They are not maintained, not complete, we aren't even confident they are accurate, and its not consistent with the rest of the code base
=> layers: Removed unmaintained doxygen comments

tests/unit/descriptor_buffer.cpp, tests/unit/descriptor_buffer_positive.cpp
@artem-lunarg to respond to your comment in https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/8849/files#r1838581557
=> tests: Remove Align from Descriptor Buffers

layers/core_checks/cc_shader_object.cpp
We have a `VUID-vkCreateShadersEXT-stage-09669` check, but there is a `VUID-vkCreateShadersEXT-stage-09670`/`VUID-vkCreateShadersEXT-stage-09671` missing
(IMO, the `VUID-vkCreateShadersEXT-stage-09669` VU could be removed from the spec, but not worth the churn right now... edit, made it here https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/7021)
=> layers: Add Queue Support for Shader Object

layers/core_checks/cc_synchronization.cpp, tests/unit/sync_object_positive.cpp
Closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/8823
=> layers: Fix ownership transfer false positive

layers/core_checks/cc_ray_tracing.cpp, layers/state_tracker/ray_tracing_state.h, layers/state_tracker/state_tracker.cpp, tests/framework/ray_tracing_objects.cpp, tests/framework/ray_tracing_objects.h, tests/unit/ray_tracing.cpp, tests/unit/ray_tracing_positive.cpp
Closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/8590
=> Fix state tracking and validation of deserialized acceleration structures 

layers/core_checks/cc_synchronization.cpp, tests/unit/sync_object.cpp
Need to check that family indices are not equal
=> layers: Fix VU 04087

layers/drawdispatch/descriptor_validator.cpp, tests/unit/gpu_av.cpp, tests/unit/gpu_av_positive.cpp, tests/unit/shader_image_access.cpp
Prevents false positives - tracking issue https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/8875
=> gpu: Prevent false positives for aliased bindings

layers/core_checks/cc_cmd_buffer.cpp, layers/gpu/debug_printf/debug_printf.cpp, layers/gpu/instrumentation/gpuav_instrumentation.cpp, layers/gpu/instrumentation/gpuav_instrumentation.h, layers/gpu/instrumentation/gpuav_shader_instrumentor.cpp, layers/gpu/instrumentation/gpuav_shader_instrumentor.h, layers/state_tracker/cmd_buffer_state.h, layers/sync/sync_commandbuffer.h, tests/framework/error_monitor.cpp, tests/framework/error_monitor.h, tests/unit/gpu_av_shader_debug_info.cpp
Still need to add it to debug printf
=> GPU-AV: Add debug label regions to instrumentation error messages

layers/gpu/spirv/post_process_descriptor_indexing.cpp
logic missing from this pass, useful for debugging/perf examining
=> gpu: Add MaxInstrumentationsCount for Post Proess Pass

layers/error_message/error_location.cpp, layers/gpu/instrumentation/gpuav_shader_instrumentor.cpp, tests/unit/gpu_av_descriptor_indexing.cpp, tests/unit/threading.cpp
=> layers: Remove extra space

docs/fine_grained_locking.md, layers/core_checks/cc_image_layout.cpp, layers/core_checks/cc_query.cpp, layers/core_checks/cc_queue.cpp, layers/core_checks/cc_ray_tracing.cpp, layers/core_checks/cc_state_tracker.cpp, layers/core_checks/cc_video.cpp, layers/state_tracker/cmd_buffer_state.cpp, layers/state_tracker/cmd_buffer_state.h
Before I go into this to fix things for GPU-AV, noticed some small QoL fixes wanted to apply first
=> layers: Cleanup of Queue and ImageLayout checks

layers/core_checks/cc_image.cpp, layers/core_checks/cc_synchronization.cpp, layers/core_checks/cc_video.cpp, layers/core_checks/core_validation.h, layers/state_tracker/video_session_state.cpp, layers/state_tracker/video_session_state.h, layers/sync/sync_validation.cpp, layers/sync/sync_vuid_maps.cpp, scripts/known_good.json, tests/device_profiles/max_profile.json, tests/framework/binding.cpp, tests/framework/feature_requirements.cpp, tests/framework/feature_requirements.h, tests/framework/render.cpp, tests/framework/render.h, tests/framework/video_objects.h, tests/icd/test_icd.cpp, tests/unit/sync_object.cpp, tests/unit/video.cpp, tests/unit/video_positive.cpp
This change adds validation support for:
- VK_KHR_video_encode_av1
- VK_KHR_video_encode_quantization_map
=> layers: Add support for AV1 encode and QP maps

layers/state_tracker/descriptor_sets.cpp, layers/state_tracker/descriptor_sets.h, tests/unit/descriptors.cpp, tests/unit/gpu_av_descriptor_indexing.cpp, tests/unit/image.cpp, tests/unit/object_lifetime.cpp, tests/unit/object_lifetime_positive.cpp
some tests for https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/8918 while i work on getting a fix
=> tests: Add Mutable Descriptor tests

layers/core_checks/cc_image_layout.cpp, layers/core_checks/cc_queue.cpp, layers/drawdispatch/drawdispatch_vuids.cpp, layers/drawdispatch/drawdispatch_vuids.h, layers/gpu/descriptor_validation/gpuav_image_layout.cpp, tests/unit/descriptors.cpp, tests/unit/gpu_av_descriptor_indexing.cpp, tests/unit/image.cpp, tests/unit/push_descriptor.cpp, tests/unit/wsi.cpp
`UNASSIGNED-CoreValidation-DrawState-InvalidImageLayout` is now `VUID-vkCmdDraw-None-09600`
=> layers: Label ImageLayout VU

layers/best_practices/bp_image.cpp, layers/best_practices/bp_instance_device.cpp, layers/best_practices/bp_render_pass.cpp, layers/best_practices/bp_synchronization.cpp, layers/best_practices/bp_wsi.cpp, tests/unit/arm_best_practices.cpp
Some spots I saw missing a better Location in the error message
=> bp: Misc cleanup

tests/framework/binding.cpp, tests/framework/binding.h, tests/framework/render.cpp, tests/framework/render.h, tests/unit/arm_best_practices.cpp, tests/unit/best_practices.cpp, tests/unit/best_practices_positive.cpp, tests/unit/debug_extensions.cpp, tests/unit/debug_extensions_positive.cpp, tests/unit/parent.cpp, tests/unit/wsi.cpp, tests/unit/wsi_positive.cpp
This fixes several leaks of surface related memory.
=> tests: Add basic vkt wrappers for Instance and Surface

layers/sync/sync_access_state.cpp, layers/sync/sync_access_state.h, layers/sync/sync_reporting.cpp
Updated some places where `SyncStageAccessFlags` (`std::bitset`) always contains a single bit (similar to Vulkan `FlagBits`). Use index instead. Saves around 20 bytes. The main goal here is not optimization but to simplify things. Having a bitset type, it's often not clear whether it can contain a collection of bits or only a single access.
Some central types got smaller:
HazardState: 64 bytes -> 40 bytes
ReadState   : 72 bytes - > 56 bytes
ResourceAccessState: 536 bytes -> 488 bytes
Potentially can bring small performance improvement. The following was observed: doom capture 4 fps -> 4.4 fps, cs2: 7.9 -> 8.1), but this is not very reliable, I have some issues with local machine, need to recheck later.
=> sync: Replace bitmask with index where possible

layers/core_checks/cc_image.cpp, layers/core_checks/cc_video.cpp, layers/error_message/unimplementable_validation.h, layers/stateless/sl_pipeline.cpp, tests/unit/pipeline.cpp, tests/unit/video.cpp
VUID churn, we are now clean with all VUIDs
=> layers: Cleanup post 1.4 VUID names

layers/gpu/core/gpuav_record.cpp, layers/gpu/resources/gpuav_state_trackers.cpp, layers/gpu/resources/gpuav_state_trackers.h
=> gpuav: Rename UpdateCommandCount

tests/framework/layer_validation_tests.h, tests/unit/host_image_copy.cpp, tests/unit/host_image_copy_positive.cpp
There were some large mega tests that make it hard to look into each VU
=> tests: Breakup and fix host image tests

layers/core_checks/cc_device_generated_commands.cpp, layers/core_checks/cc_drawdispatch.cpp, layers/core_checks/cc_pipeline_ray_tracing.cpp, layers/core_checks/cc_shader_interface.cpp, layers/core_checks/cc_spirv.cpp, layers/gpu/spirv/debug_printf_pass.cpp, layers/state_tracker/cmd_buffer_state.cpp, layers/state_tracker/state_tracker.cpp
found some sections of the code where using the c++ 17 `Structured binding declaration` improves not having to make variables of `auto x = something.first` right away
=> layers: Make use of c++17 pair accessor

layers/core_checks/cc_pipeline_graphics.cpp
small addition to https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/8987 I just noticed now
=> layers: Small legacy dithering fix

layers/state_tracker/semaphore_state.cpp, layers/state_tracker/state_tracker.cpp, tests/unit/sync_object_positive.cpp
Working on https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/8989 I found an incorrect assumption about when a specific code branch can be active. This PR provides a fix and adds a regression test to catch the issue (would trigger an assert in the original code).
Also found a hint why issues with `PositiveSyncObject.KhronosTimelineSemaphoreExampl`  on CI can be our problem and how to debug it. Will work on this next.
=> layers: Fix empty timeline assumption in Semaphore::EnqueueWait

tests/unit/gpu_av_descriptor_indexing.cpp, tests/unit/gpu_av_descriptor_indexing_positive.cpp
More for https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/8922 but this time for descriptor indexing
=> tests: More Sampled Images tests for GPU-AV

tests/unit/render_pass.cpp
makes `AttachmentDescriptionFinalLayout` 3 smaller tests for better maintainability
=> tests: Split up AttachmentDescriptionFinalLayout

scripts/gn/export_targets.py, scripts/gn/gn.py
Chromium/ANGLE run this and we want to avoid breaking them.
See #9003 for an example
=> ci: Add export_targets.py check to GN build

docs/synchronization_usage.md, layers/VkLayer_khronos_validation.json.in
Reordered list of known limitations approximately based on importance
=> docs: Update supported features and UI text

tests/unit/shader_spirv.cpp
Add test from https://github.com/KhronosGroup/SPIRV-Tools/issues/5921
=> tests: Add another spec constant test

layers/core_checks/cc_image.cpp, tests/unit/wsi_positive.cpp
=> Fix queue family indices compare for swapchain images

layers/core_checks/cc_query.cpp, layers/state_tracker/state_tracker.cpp, layers/state_tracker/state_tracker.h, tests/unit/query_positive.cpp
=> Fix enumerating performance queries

layers/best_practices/best_practices_validation.h, layers/best_practices/bp_drawdispatch.cpp, tests/unit/best_practices.cpp
=> bp: Validate push constants in compute

layers/VkLayer_khronos_validation.json.in, layers/layer_options.cpp, layers/sync/sync_error_messages.cpp, layers/sync/sync_error_messages.h, layers/sync/sync_reporting.cpp, layers/sync/sync_reporting.h, layers/sync/sync_settings.h, tests/unit/layer_settings_positive.cpp
* Sort extra properties
* Add option to pretty print extra properties.
=> sync: Extra properties update

layers/core_checks/cc_synchronization.cpp, layers/sync/sync_vuid_maps.cpp, layers/sync/sync_vuid_maps.h, tests/unit/sync_object.cpp
This should be merged when the spec change is approved https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/7075
UPDATE: approved
=> layers: Remove VUIDs already covered by 10387/10388

tests/unit/sparse_image.cpp
=> tests: Fix and enable QueueBindSparseMemoryType4 test

layers/core_checks/cc_wsi.cpp, tests/unit/wsi.cpp
=> layers: Validate surface counters

layers/core_checks/cc_spirv.cpp, layers/core_checks/core_validation.h, tests/unit/shader_object.cpp, tests/unit/shader_push_constants.cpp
=> Update push constants validation

layers/core_checks/cc_wsi.cpp, layers/stateless/sl_wsi.cpp, tests/unit/wsi.cpp
=> Validate presentModeFifoLatestReady feature

layers/stateless/sl_wsi.cpp, tests/unit/wsi.cpp
=> Validate missing imageCompressionControl feature

tests/unit/descriptors.cpp
=> tests: Test updating descriptors with acceleration structures

tests/unit/ray_tracing.cpp
Part of #9116
I have tests for the first 5 checkboxes in #9116, but not:
VUID-VkAccelerationStructureGeometryKHR-triangles-parameter
VUID-VkAccelerationStructureGeometryKHR-instances-parameter
VUID-VkAccelerationStructureGeometryKHR-aabbs-parameter
The validation layers check for these VUIDs by looking if the related members are nullptr, but these are not pointers, they are members of a structure, so I don't see how they can be hit
=> tests: Test VkAccelerationStructureGeometryKHR

tests/unit/command.cpp
=> tests: Add tests for VkCommandBufferInheritanceInfo

tests/framework/render.cpp
A funny issue showed up while investigating issue #9109 When ran on his own,
NegativeDeviceFeatureProperty.PhysicalDeviceFeatures2 would fail (expected error not emitted), but would succeed when running the whole NegativeDeviceFeatureProperty test suite. I traced back the issue to the driver info printing logic: for this info to be printed, the VK_KHR_get_physical_device_properties2 ext is needed. It was automatically added when trying to print the driver info, but only if said info had not already been printed. This explains the issue I was seeing.
I decided to just stop adding this extension under the hood. Caveat is if running a 1.0 test that does not add this extension, driver info will now not be printed. I personnally don't like when extensions or features are activated under the …
=> tests: Reworked a bit driver info printing logic

tests/CMakeLists.txt, tests/unit/device_feature_property_positive.cpp
Closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/9109
=> tests: Test enable VK_KHR_VERTEX_ATTRIBUTE_DIVISOR

layers/best_practices/bp_drawdispatch.cpp
Check if the memory allocation size is large enough for all indices
=> bp: Fix index buffer scan when robustness is enabled

layers/best_practices/bp_cmd_buffer_nv.cpp, layers/best_practices/bp_drawdispatch.cpp, layers/best_practices/bp_render_pass.cpp, layers/state_tracker/pipeline_state.cpp, layers/state_tracker/pipeline_state.h
followup of https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/9140
Make use of the `LastBound` harness to get the value from dynamic state or pipeline state
=> bp: Use LastBound for dynamic state values

tests/unit/buffer.cpp
=> tests: Add missing vertex and index buffer tests

layers/stateless/sl_instance_device.cpp, layers/stateless/sl_pipeline.cpp, layers/stateless/sl_ray_tracing.cpp, layers/stateless/stateless_validation.h, layers/vulkan/generated/feature_requirements_helper.cpp, tests/unit/robustness.cpp, tests/unit/robustness_positive.cpp
=> Add robustness supported VUIDs

tests/unit/sync_object.cpp
Part of #9150
Adding tests for:
VUID-VkBufferMemoryBarrier-None-09097
VUID-VkImageMemoryBarrier2-None-09119
VUID-VkBufferMemoryBarrier-None-09098
VUID-VkImageMemoryBarrier2-None-09120
VUID-VkBufferMemoryBarrier-srcQueueFamilyIndex-09099
VUID-VkImageMemoryBarrier2-srcQueueFamilyIndex-09121
VUID-VkBufferMemoryBarrier-dstQueueFamilyIndex-09100
VUID-VkImageMemoryBarrier2-dstQueueFamilyIndex-09122
=> tests: Add invalid queue family tests

tests/unit/sync_object.cpp
Part of #9150
Adds test for VUID-VkBufferMemoryBarrier-buffer-01931
=> tests: Test buffer in barrier is bound to memory

BUILD.md, docs/generated_code.md, tests/README.md
Some small cleanup to documentation from recent contributor
=> docs: Small cleanup from feedback

tests/unit/sync_object.cpp
Adds tests for:
VUID-VkMemoryBarrier2-dstAccessMask-03918
VUID-VkMemoryBarrier2-dstAccessMask-03919
VUID-VkMemoryBarrier2-dstAccessMask-03920
VUID-VkMemoryBarrier2-dstAccessMask-04747
VUID-VkMemoryBarrier2-dstAccessMask-03926
=> tests: Add missing barrier access mask tests

layers/state_tracker/state_tracker.cpp
@y-novikov @SoltiGG
sorry, will get this in ASAP
=> layers: Fix VK_EXT_robustness2 check

tests/unit/parent.cpp, tests/unit/pipeline_positive.cpp
few tests to help with https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/9176
=> tests: Add GetPipelinePropertiesEXT tests

docs/fine_grained_locking.md, layers/best_practices/bp_device_memory.cpp, layers/best_practices/bp_drawdispatch.cpp, layers/core_checks/cc_buffer_address.h, layers/core_checks/cc_descriptor.cpp, layers/core_checks/cc_device_memory.cpp, layers/core_checks/cc_ray_tracing.cpp, layers/core_checks/cc_video.cpp, layers/core_checks/core_validation.h, layers/state_tracker/device_memory_state.cpp, layers/state_tracker/device_memory_state.h, layers/state_tracker/image_state.h, layers/state_tracker/state_tracker.cpp, layers/sync/sync_validation.cpp
RENAME `MEM_STATE` TO SOMETHING QUIETER
=> layers: Rename shouty MEM_STATE

layers/core_checks/cc_image.cpp, layers/core_checks/cc_render_pass.cpp, tests/unit/fragment_shading_rate.cpp, tests/unit/render_pass.cpp
=> Update Framebuffer test

tests/framework/binding.h, tests/framework/render.cpp, tests/unit/arm_best_practices.cpp, tests/unit/best_practices.cpp, tests/unit/best_practices_positive.cpp, tests/unit/debug_extensions.cpp, tests/unit/debug_extensions_positive.cpp, tests/unit/parent.cpp, tests/unit/wsi.cpp, tests/unit/wsi_positive.cpp
Running X11, these WSI tests were not working
=> Fix WSI tests on MockICD X11

tests/unit/shader_interface_positive.cpp
clearing out old local todo notes
=> tests: Use DefaultColorBlendAttachmentState

tests/unit/ray_tracing.cpp
=> tests: Add AS copy tests

tests/unit/descriptor_buffer_positive.cpp
for https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/9228
=> tests: Add VkBufferUsageFlags2CreateInfo test

CONTRIBUTING.md, layers/CMakeLists.txt, layers/drawdispatch/drawdispatch_vuids.cpp, layers/gpuav/shaders/gpuav_error_header.h, layers/gpuav/shaders/instrumentation/buffer_device_address.comp, layers/gpuav/shaders/validation_cmd/draw_indexed.comp, layers/gpuav/shaders/validation_cmd/draw_indexed_indirect_vertex_buffer.comp, layers/gpuav/shaders/validation_cmd/first_instance.comp, layers/vulkan/generated/object_tracker.cpp, layers/vulkan/generated/object_tracker.h, scripts/generators/object_tracker_generator.py, tests/framework/ray_tracing_objects.h, tests/unit/best_practices.cpp, tests/unit/dynamic_state.cpp, tests/unit/dynamic_state_positive.cpp, tests/unit/gpu_av_descriptor_indexing_positive.cpp, tests/unit/pipeline_positive.cpp, tests/unit/ray_tracing_nv.cpp, tests/unit/ray_tracing_positive.cpp, tests/unit/shader_interface.cpp, tests/unit/shader_interface_positive.cpp, tests/unit/shader_limits.cpp, tests/unit/shader_limits_positive.cpp, tests/unit/shader_object.cpp, tests/unit/shader_object_positive.cpp, tests/unit/shader_spirv.cpp, tests/unit/shader_spirv_positive.cpp, tests/unit/sync_val.cpp
seems clang-format doesn't reach everywhere
=> layers: Replace rouge tab with spaces

layers/core_checks/cc_copy_blit_resolve.cpp, layers/core_checks/cc_device.cpp, layers/core_checks/cc_image_layout.cpp, layers/core_checks/cc_render_pass.cpp, layers/core_checks/cc_spirv.cpp, layers/core_checks/cc_synchronization.cpp, layers/core_checks/core_validation.h, layers/gpuav/descriptor_validation/gpuav_image_layout.cpp, layers/stateless/sl_pipeline.cpp, layers/sync/sync_utils.h, tests/device_profiles/max_profile.json, tests/unit/copy_buffer_image.cpp, tests/unit/copy_buffer_image_positive.cpp, tests/unit/image.cpp, tests/unit/image_positive.cpp, tests/unit/others.cpp, tests/unit/pipeline.cpp, tests/unit/shader_spirv.cpp, tests/unit/subpass.cpp, tests/unit/sync_object.cpp, tests/unit/sync_object_positive.cpp
Add checks for VK_KHR_maintenance8
=> layers: Add VK_KHR_maintenance8

scripts/known_good.json, tests/device_profiles/max_core.json, tests/device_profiles/max_profile.json, tests/unit/shader_storage_image.cpp
Update Profiles to run 1.4 tests
=> tests: Upgrade profiles to run 1.4

tests/unit/ycbcr_positive.cpp
Waiting on spec to decide if this is a driver bug or lack of VU, but wanted to have the test checked in (https://gitlab.khronos.org/vulkan/vulkan/-/issues/4151)
=> tests: Add YCbCr test waiting on spec issue

tests/unit/shader_object.cpp
=> tests: Test mesh draw without vertex shader bound

layers/core_checks/cc_image_layout.cpp, layers/core_checks/cc_render_pass.cpp, layers/core_checks/cc_synchronization.cpp, layers/core_checks/core_validation.h, layers/gpuav/descriptor_validation/gpuav_image_layout.cpp, layers/sync/sync_utils.h, tests/unit/sync_object.cpp, tests/unit/sync_object_positive.cpp
Addresses https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/9268
=> layers: Cleanup usage of ownership transfer flag

layers/core_checks/cc_copy_blit_resolve.cpp, layers/core_checks/core_validation.h, tests/unit/copy_buffer_image.cpp
=> layers: Validate image copy queue flag support

layers/core_checks/cc_shader_object.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/9263
=> layesrs Improve Shader Object stage bound message

layers/core_checks/cc_image.cpp
More format usage improvements, this time around `VK_IMAGE_CREATE_BLOCK_TEXEL_VIEW_COMPATIBLE_BIT`
=> layers: Improve BLOCK_TEXEL_VIEW_COMPATIBLE checks

.github/workflows/vvl.yml, BUILD.md, CMakeLists.txt, layers/core_checks/cc_spirv.cpp, layers/utils/shader_utils.cpp, layers/vulkan/generated/feature_requirements_helper.cpp, layers/vulkan/generated/spirv_grammar_helper.cpp, layers/vulkan/generated/spirv_grammar_helper.h, layers/vulkan/generated/spirv_tools_commit_id.h, layers/vulkan/generated/spirv_validation_helper.cpp, scripts/generators/spirv_tool_commit_id_generator.py, scripts/known_good.json, tests/unit/mesh.cpp, tests/unit/shader_spirv.cpp, tests/unit/shader_spirv_positive.cpp
Pulls in https://github.com/KhronosGroup/SPIRV-Tools/pull/5951 to properly do `VUID-RuntimeSpirv-Offset-10213` there
=> layers: Update SPIRV-Tools with VK_KHR_maintenance8

tests/unit/descriptors.cpp, tests/unit/descriptors_positive.cpp
https://gitlab.khronos.org/vulkan/vulkan/-/issues/4125 was resolved, these are positive tests and moved accordingly
=> tests: Add test for copying destroyed descriptors

layers/core_checks/cc_copy_blit_resolve.cpp
Was 
```
vkCmdCopyImage(): pRegions[0] srcImage format VK_FORMAT_R8_UNORM with aspectMask VK_IMAGE_ASPECT_COLOR_BIT is not compatible with dstImage format VK_FORMAT_G8_B8R8_2PLANE_420_UNORM aspectMask VK_IMAGE_ASPECT_PLANE_1_BIT.
vkCmdCopyImage(): pRegions[0] srcImage format VK_FORMAT_G8_B8R8_2PLANE_420_UNORM with aspectMask VK_IMAGE_ASPECT_PLANE_1_BIT is not compatible with dstImage format VK_FORMAT_R8_UNORM aspectMask VK_IMAGE_ASPECT_COLOR_BIT.
```
now is
```
vkCmdCopyImage(): pRegions[0] srcImage format VK_FORMAT_R8_UNORM has texel block size of 1 which is different than the dstImage format VK_FORMAT_R8G8_UNORM (which is the compatible format for plane 1 of VK_FORMAT_G8_B8R8_2PLANE_420_UNORM) which has texel block size of 2.
vkCmdCopyImage(): pRegions[0] srcImage format …
```
=> layers: Improve Multi-planar format compare error message

tests/unit/copy_buffer_image_positive.cpp
Revises @ziga-lunarg tests from https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/8573 and adds them (updated) and created https://gitlab.khronos.org/vulkan/vulkan/-/issues/4159 to track what is exactly going on here
=> tests: Add 1D Compressed Image tests

layers/core_checks/cc_cmd_buffer_dynamic.cpp, tests/unit/dynamic_state.cpp, tests/unit/dynamic_state_positive.cpp
This change was added in https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/7105 and now part of the 1.4.306 headers
Lets you now go
```c++
VkGraphicsPipelineCreateInfo::pDynamicState = [VK_DYNAMIC_STATE_TESSELLATION_DOMAIN_ORIGIN_EXT];
VkGraphicsPipelineCreateInfo::pStages = [vertex, fragment];
// Never set vkCmdSetTessellationDomainOriginEXT
vkCmdDraw()
```
=> layers: Relax tess/geom pipeline dynamic state

layers/core_checks/cc_shader_object.cpp, layers/drawdispatch/drawdispatch_vuids.cpp, tests/unit/shader_object.cpp
With some VUID churn, cleanup the way we check this code
=> layers: Fix Mesh Shader Object

tests/unit/shader_object.cpp, tests/unit/shader_object_positive.cpp
=> tests: Fix errors in shader object tests

layers/chassis/dispatch_object_manual.cpp
Might close #9277, would be great if author of the issue can confirm
=> layers: Fix determining device api version

layers/best_practices/bp_drawdispatch.cpp, tests/unit/best_practices_positive.cpp
=> bp: Fix check if vertex buffers are used

layers/core_checks/cc_cmd_buffer_dynamic.cpp
for internal issue still needed to be understood
=> layers: Fix crash in shader objects

tests/unit/device_queue.cpp
Part of #9338
This change adds tests for:
VUID-VkDeviceCreateInfo-sType-unique
VUID-VkDeviceCreateInfo-flags-zerobitmask
VUID-VkDeviceCreateInfo-pQueueCreateInfos-parameter
VUID-VkDeviceCreateInfo-queueCreateInfoCount-arraylength
There are also commented out tests for:
VUID-VkDeviceCreateInfo-ppEnabledLayerNames-parameter
Crashes, might required change in Vulkan Utility Libraries
VUID-VkDeviceCreateInfo-ppEnabledExtensionNames-parameter
Crashes, not sure what is happening
The following seem impossible to test:
VUID-VkDeviceCreateInfo-pEnabledFeatures-parameter
VUID-VkInstanceCreateInfo-pApplicationInfo-parameter
VUID-VkInstanceCreateInfo-ppEnabledLayerNames-parameter
VUID-VkInstanceCreateInfo-ppEnabledExtensionNames-parameter
=> tests: Add tests for invalid device creation

tests/unit/copy_buffer_image.cpp
=> tests: Add missing buffer and image copy tests

layers/chassis/chassis_manual.cpp, tests/unit/device_queue.cpp
for https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/9338
=> layers: Fix crash with invalid device creation

layers/core_checks/cc_copy_blit_resolve.cpp
applies spec fix being added in the next header update
https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/7141
=> layers: Maintenance 8 layerCount fix

layers/stateless/sl_wsi.cpp, tests/unit/wsi.cpp
https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/7138/diffs was approved
=> layers: Add back 06750

layers/error_message/logging.cpp, tests/unit/others.cpp
To help use new antora site in SDK
=> layers: Update new ANNOTATED_SPEC_LINK format

tests/unit/copy_buffer_image.cpp, tests/unit/protected_memory.cpp
Part of #9147 
I don't have tests for:
`VUID-vkCmdResolveImage-srcImage-04447`, because I don't see how you can get it without getting either 
`VUID-VkImageCreateInfo-imageType-00961` or `VUID-vkCmdResolveImage-dstSubresource-01712` before
and 
`VUID-vkCmdResolveImage-srcImage-00271` without getting `VUID-VkImageCreateInfo-samples-02257` before
=> tests: Add missing copy blit resolve tests

layers/external/inplace_function.h
No behavior change. Replaces a variadic template with a constexpr function and a for loop, which is simpler. The logic was added in 0d99e5aad4299d8e4b3bcf4bf1e1bea4a32a9044.
=> layers: Rewrite inplace_function default alignment

docs/generated_code.md
=> docs: Clean up section about how to generate code

layers/core_checks/cc_spirv.cpp, layers/core_checks/core_validation.h, tests/unit/shader_push_constants.cpp, tests/unit/shader_push_constants_positive.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/9364
=> layers: Fix checking pointers 8/16 bit elements

tests/CMakeLists.txt, tests/unit/atomics.cpp, tests/unit/shader_debug_info.cpp
Added dedicated Shader Debug Info test file for future changes
=> tests: Dedicated Shader Debug Info file

layers/sync/sync_access_state.cpp, layers/sync/sync_access_state.h, layers/sync/sync_error_messages.cpp
Cleanup buffer message formatting code to prepare it for re-use in other places.
=> sync: Cleanup formatting code

layers/core_checks/cc_android.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/9393
The AHB to VK stuff needed a cleanup, this cleans up some of those random maps and added better error messages
=> layers: Fix and improve AHB to VK Mapping

layers/core_checks/cc_drawdispatch.cpp, tests/unit/ray_tracing.cpp, tests/unit/ray_tracing_positive.cpp
Part of https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/9368
=> layers: Validate invalid ray gen SBT address

layers/core_checks/cc_descriptor.cpp, layers/object_tracker/object_tracker_utils.cpp, layers/state_tracker/descriptor_sets.cpp, layers/state_tracker/descriptor_sets.h, tests/unit/descriptors.cpp, tests/unit/descriptors_positive.cpp, tests/unit/parent.cpp
Should fix https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/9392
=> layers: Fix Sampler Object Tracking

layers/chassis/chassis_modification_state.h, layers/state_tracker/state_tracker.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/9402
=> layers: Only create a ShaderModule object once

layers/core_checks/cc_pipeline_graphics.cpp, layers/drawdispatch/drawdispatch_vuids.cpp, layers/drawdispatch/drawdispatch_vuids.h, tests/unit/dynamic_rendering.cpp, tests/unit/dynamic_rendering_positive.cpp
=> layers: Validate render pass begin info flags

tests/unit/ray_tracing.cpp
=> tests: Test invalid AS copies

layers/state_tracker/state_tracker.cpp
=> state: Set android_external_format_resolve shortcut variable

tests/framework/ray_tracing_objects.cpp, tests/framework/ray_tracing_objects.h, tests/unit/ray_tracing_pipeline.cpp
=> tests: Test vkGetRayTracingShaderGroupHandlesKHR

tests/framework/ray_tracing_objects.cpp, tests/framework/ray_tracing_objects.h, tests/unit/descriptor_buffer.cpp, tests/unit/descriptors.cpp, tests/unit/descriptors_positive.cpp, tests/unit/ray_tracing.cpp, tests/unit/ray_tracing_positive.cpp
Rename AccelerationStructureKHR::Build to Create, because that's what it does. Build is done after, so name was confusing
=> tests: Ray tracing framework renaming

tests/unit/shader_object_positive.cpp
=> tests: Fix shader object mutliple attachment test

tests/framework/binding.cpp, tests/framework/binding.h, tests/unit/best_practices_positive.cpp, tests/unit/debug_printf.cpp, tests/unit/gpu_av_shader_object_positive.cpp, tests/unit/shader_interface.cpp, tests/unit/shader_object.cpp, tests/unit/shader_object_positive.cpp
=> tests: Update shader object tests

layers/sync/sync_op.cpp
Fix formatting https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/9433
=> layers: Fix event stage formatting

layers/core_checks/cc_spirv.cpp, tests/unit/pipeline.cpp
Instead of just going 
> "main" was not found, sorry
you will get either
> vkCreateGraphicsPipelines(): pCreateInfos[0].pStages[1].pName "foo" entry point not found for stage VK_SHADER_STAGE_FRAGMENT_BIT. (The only entry point found was "main" for VK_SHADER_STAGE_FRAGMENT_BIT).
or if multiple entrypoints (more common with RTX) you will see
> vkCreateComputePipelines(): pCreateInfos[0].stage.pName "main" entry point not found for stage VK_SHADER_STAGE_COMPUTE_BIT. The following entry points found in the module:
"foo"	(VK_SHADER_STAGE_COMPUTE_BIT)
"not_main"	(VK_SHADER_STAGE_COMPUTE_BIT)
"still_no_main"	(VK_SHADER_STAGE_COMPUTE_BIT)
"not_this"	(VK_SHADER_STAGE_VERTEX_BIT)
=> layers: Better entry point error message

tests/unit/command.cpp, tests/unit/dynamic_rendering.cpp, tests/unit/image_layout.cpp, tests/unit/render_pass_positive.cpp, tests/unit/subpass.cpp, tests/unit/subpass_positive.cpp, tests/unit/sync_object.cpp
=> tests: Fix sync issues in core tests

tests/unit/pipeline.cpp
@charles-lunarg tried to gaslight me on the bus last week that this wasn't covered. It probably wasn't but can confirm it is with the latest SDK
=> tests: Add Shader Inline bad entry point test

tests/unit/sync_val.cpp, tests/unit/sync_val_positive.cpp
Split 1 huge test into 11 screen size tests.
=> tests: Split large draw/dispatch test

layers/drawdispatch/descriptor_validator.cpp, layers/drawdispatch/descriptor_validator.h
Some small improvements for error message pulling out into another PR
=> layers: Slight improvement of error messages for Descriptors

tests/unit/video_decode.cpp
When the video session is created with no DPB slots it is not required to specify a reconstructed picture and in this case the decode output's image layout
is always expected to be DECODE_DST, indifferent of whether the profile supports DISTINCT or COINCIDE
mode. This is in contrast to when CONCIDE mode is
used and a (coinciding) reconstructed picture is
specified where the image layout is expected to be DECODE_DPB.
=> tests: Verify decode output image layout corner-cases

tests/unit/gpu_av_descriptor_indexing_positive.cpp
(inspired by https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/9317) New stress tests and some numbers
This is O(n^2) level bad and why we will need a fix for those that are unfortunate and don't get `DontInline` (the worst part is there is no way to query the driver if it "actually" supports it)
(Time it took to run the test, which checked, it is reflecting **Pipeline Compiling times**)
No instrumentation - **0.2 seconds**
50 instrumentation of PostProcess - **0.2 seconds**
50 instrumentation of GeneralBuffer - **0.6 seconds**
50 instrumentation of DescriptorIndexing - **1.2 seconds**
50 instrumentation of PostProcess/GeneralBuffer/DescriptorIndexing - **2.0 seconds**
100 instrumentation of PostProcess - **0.3 seconds**
100 instrumentation of GeneralBuffer - **1.8 seconds** …
=> tests: Add new stress test

tests/framework/ray_tracing_objects.cpp, tests/framework/ray_tracing_objects.h, tests/unit/ray_tracing.cpp
=> tests: Test vkCmdTraceRaysKHR

tests/unit/sync_object.cpp
=> tests: Test invalid pNext in pipeline barrier 2

tests/framework/binding.h, tests/unit/atomics.cpp, tests/unit/buffer.cpp, tests/unit/descriptors.cpp, tests/unit/descriptors_positive.cpp, tests/unit/gpu_av_descriptor_class_general_buffer.cpp, tests/unit/gpu_av_descriptor_class_general_buffer_positive.cpp, tests/unit/gpu_av_descriptor_class_texel_buffer.cpp, tests/unit/gpu_av_descriptor_class_texel_buffer_positive.cpp, tests/unit/gpu_av_descriptor_indexing_positive.cpp, tests/unit/gpu_av_descriptor_post_process.cpp, tests/unit/shader_storage_texel.cpp, tests/unit/shader_storage_texel_positive.cpp, tests/unit/sync_val.cpp, tests/unit/sync_val_positive.cpp
100 lines of better buffer view creation
=> tests: Use BufferView init helper

layers/chassis/chassis_manual.cpp
@jeremyg-lunarg @mikes-lunarg @charles-lunarg thoughts on this
I found that 3 of these 4 the desktop loader just takes care of for you (not 100% sure about Android loader)
Tried to provide a better message for those that might hit this somehow
=> layers: Cleanup extension name check

tests/unit/atomics.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/9485
=> tests: Buffer views atomics with mismatched formats

layers/error_message/logging.cpp, layers/error_message/logging.h, layers/gpuav/debug_printf/debug_printf.cpp, layers/gpuav/spirv/module.cpp, layers/layer_options.cpp
small fix to address @artem-lunarg @arno-lunarg nit in https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/9512
=> layers: Small followup from 9512

layers/core_checks/cc_device.cpp, layers/core_checks/cc_device_memory.cpp, layers/core_checks/cc_image.cpp, layers/core_checks/cc_render_pass.cpp, layers/core_checks/cc_wsi.cpp, layers/error_message/error_strings.h, tests/unit/image_drm_positive.cpp
hopefully closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/8627
=> layers: Fix pNext chaining for DRM

layers/sync/sync_error_messages.cpp, layers/sync/sync_error_messages.h, layers/sync/sync_renderpass.cpp
So far simplified form (but with enough information) until this will be convered by the tests.
=> sync: Update render pass attachment messages

layers/vulkan/generated/spirv_tools_commit_id.h, scripts/known_good.json, tests/unit/debug_printf_ray_tracing.cpp, tests/unit/gpu_av_descriptor_class_general_buffer.cpp, tests/unit/gpu_av_descriptor_class_general_buffer_positive.cpp, tests/unit/gpu_av_descriptor_post_process.cpp, tests/unit/gpu_av_descriptor_post_process_positive.cpp, tests/unit/shader_interface.cpp, tests/unit/shader_interface_positive.cpp, tests/unit/shader_push_constants_positive.cpp
replacement for https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/9549 (cc @mikes-lunarg )
=> build: Update shader toolchain

layers/core_checks/cc_pipeline_graphics.cpp, tests/unit/multiview_positive.cpp
From https://gitlab.khronos.org/vulkan/vulkan/-/issues/4194
Not sure if spec bug or a GLSL bug, for now, reduce false positive for this edge case
=> layers: Ignore error with Mesh Multiview using GLSL

layers/core_checks/cc_render_pass.cpp, layers/core_checks/core_validation.h, layers/state_tracker/cmd_buffer_state.cpp, layers/state_tracker/cmd_buffer_state.h, tests/unit/fragment_shading_rate.cpp, tests/unit/fragment_shading_rate_positive.cpp
In preparation for https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/7194
Want to make this logic more friendly for Dynamic Rendering
=> layers: Make FDM Offset more Dynamic Rendering friendly

layers/sync/sync_error_messages.cpp, layers/sync/sync_error_messages.h, layers/sync/sync_reporting.cpp, layers/sync/sync_validation.cpp
Minor adjustments here and there
=> sync: Misc formatting cleanup

layers/sync/sync_validation.cpp, tests/framework/ray_tracing_objects.cpp, tests/framework/ray_tracing_objects.h, tests/unit/sync_val_ray_tracing.cpp, tests/unit/sync_val_ray_tracing_positive.cpp
Add validation of the following acceleration structure input buffers:
* transform data (VkTransformMatrixKHR)
* AABB data (VkAabbPositionsKHR)
* instance data (VkAccelerationStructureInstanceKHR)
=> sync: Validate remaining acceleration structure input buffers

layers/gpuav/spirv/buffer_device_address_pass.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/9531
Going to add spec text and `spirv-val` support for https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/7210
=> gpuav: Guard against invalid Aligned operands

layers/sync/sync_validation.cpp
Ensure that invalid/ignored input buffers do not result in the early exit when there are more buffers to validate. Previously some code paths allowed too early exits.
=> sync: Fix too early exit in ray tracing validation

CMakeLists.txt
Now this works on Ninja Multi-Config generator on linux.
=> cmake: Use generator expression

layers/core_checks/cc_copy_blit_resolve.cpp, layers/core_checks/cc_image.cpp, layers/utils/vk_layer_utils.cpp, layers/utils/vk_layer_utils.h, scripts/known_good.json, tests/unit/copy_buffer_image.cpp, tests/unit/copy_buffer_image_positive.cpp
with https://github.com/KhronosGroup/Vulkan-Utility-Libraries/pull/277
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/9588
=> layers: Fix Depth Stencil VK_KHR_maintenance8

docs/debug_printf.md, layers/gpuav/debug_printf/debug_printf.cpp, tests/unit/others.cpp
Improve the DebugPrintf to be more "what I care about first" for most people
=> printf: Cleanup documentation and logging format

layers/vulkan/generated/spirv_validation_helper.cpp, scripts/generators/spirv_validation_generator.py, tests/unit/shader_spirv.cpp, tests/unit/shader_spirv_positive.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/9601
=> layers: Add VK_EXT_shader_viewport_index_layer case

layers/core_checks/cc_drawdispatch.cpp, tests/unit/vertex_input_positive.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/9600
=> layers: Fix VK_EXT_vertex_attribute_divisor case

layers/core_checks/cc_cmd_buffer_dynamic.cpp, layers/core_checks/cc_shader_interface.cpp, layers/drawdispatch/drawdispatch_vuids.cpp, layers/drawdispatch/drawdispatch_vuids.h, layers/state_tracker/cmd_buffer_state.h, layers/state_tracker/pipeline_state.cpp, layers/state_tracker/pipeline_state.h, layers/state_tracker/state_tracker.cpp, tests/unit/dynamic_state.cpp, tests/unit/shader_object.cpp
=> Add vuid 10608

.github/workflows/vvl.yml, BUILD.md, CMakeLists.txt, layers/core_checks/cc_descriptor.cpp, layers/core_checks/cc_drawdispatch.cpp, layers/core_checks/cc_pipeline_graphics.cpp, layers/state_tracker/cmd_buffer_state.h, layers/state_tracker/pipeline_state.cpp, layers/stateless/sl_descriptor.cpp, scripts/CMakeLists.txt, scripts/tests.py, scripts/update_deps.py, tests/framework/video_objects.h, tests/unit/command.cpp
Fix various undefined behaviors found in layer / test  code when running against a mock driver.
Add UBSAN job to CI
closes #9384
=> Add UBSAN to CI

tests/unit/video_encode.cpp
Hi, 
This is not only a PR but rather a question.
This test doesn't pass but I think it should pass. That's why I suspect it's about VVL's bug.   
But unfortunately I didn't manage to fix how.   
What do you think? Is it a real bug of VVL or there's something I'm missing.
=> tests: Adds a negative testcase with RateControl disabled

layers/core_checks/cc_image.cpp, tests/unit/wsi_positive.cpp
=> Fix checking queue family indices for swapchain images

layers/sync/sync_validation.cpp
Something to cherry pick for SDK, based on comments from Dan, Fabian, and I also started to think that original idea was not a good engineering.
=> sync: Do not skip strided data in ray tracing validation

layers/containers/custom_containers.h, layers/gpuav/core/gpuav_setup.cpp, layers/gpuav/debug_printf/debug_printf.cpp, layers/gpuav/descriptor_validation/gpuav_descriptor_set.cpp, layers/gpuav/descriptor_validation/gpuav_descriptor_validation.cpp, layers/gpuav/instrumentation/gpuav_instrumentation.cpp, layers/gpuav/resources/gpuav_state_trackers.cpp, layers/gpuav/resources/gpuav_state_trackers.h, layers/gpuav/resources/gpuav_vulkan_objects.cpp, layers/gpuav/resources/gpuav_vulkan_objects.h, layers/gpuav/validation_cmd/gpuav_copy_buffer_to_image.cpp, layers/gpuav/validation_cmd/gpuav_draw.cpp, layers/profiling/profiling.h, layers/state_tracker/queue_state.cpp
Some small optimizations I made while investigating GPU-AV performance. For the lightest instrumentation, done for "out of bounds vertex attributes fetching", went from 20 -> 30 fps on Doom Eternal. 
When enabling other types of instrumentation, unfortunately bottlenecks totally shift to other spots specific to instrumentation types.
=> gpuav: Misc optimisations

.github/workflows/vvl.yml
linux-ubsan makes linux-debug redundant
=> ci: Remove linux-debug

layers/vulkan/generated/stateless_validation_helper.cpp, scripts/generators/stateless_validation_helper_generator.py
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/9640
=> scripts: Ignore VK_EXT_debug_util function check

tests/unit/gpu_av_descriptor_post_process.cpp
3 extra tests for @arno-lunarg to test with
=> gpuav: Add more Post Processing tests

layers/core_checks/cc_pipeline_graphics.cpp, tests/unit/dynamic_rendering.cpp
=> layers: Remove viewMask check for secondary cmd buffers

layers/drawdispatch/descriptor_validator.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/9666
=> layers: Fix image typo

tests/unit/wsi.cpp
=> tests: Test using swapchain after destroy

layers/core_checks/cc_descriptor.cpp, layers/core_checks/cc_drawdispatch.cpp, layers/core_checks/core_validation.h, layers/drawdispatch/descriptor_validator.cpp, layers/drawdispatch/descriptor_validator.h, layers/gpuav/descriptor_validation/gpuav_descriptor_validation.cpp, layers/gpuav/resources/gpuav_shader_resources.h
Give the command buffer and pipeline/shaderObject where draw time errors are coming from
=> layers: Pass down Handles down to descriptor validator

tests/unit/ray_tracing_positive.cpp
=> tests: Test AS build range info with primitiveCount 0

layers/core_checks/cc_copy_blit_resolve.cpp, tests/unit/copy_buffer_image.cpp
=> Fix bounds checks with uint32 overflow

layers/core_checks/cc_spirv.cpp, tests/framework/ray_tracing_objects.cpp, tests/framework/ray_tracing_objects.h, tests/unit/ray_tracing_pipeline.cpp
Closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/9672
=> vvl: Handle null desc set layout

layers/state_tracker/ray_tracing_state.h
Closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/9669
safe_VkAccelerationStructureCreateInfoKHR has issues that I could not reproduce. But turns out we don't really need it now, so just get rid of it
=> vvl: Circumvent safe accel struct issues

layers/core_checks/cc_descriptor.cpp, layers/state_tracker/descriptor_sets.cpp, layers/state_tracker/descriptor_sets.h
=> vvl: Cleanup desc set layout size caching

layers/core_checks/cc_cmd_buffer_dynamic.cpp, tests/unit/dynamic_state.cpp
From https://gitlab.khronos.org/vulkan/vulkan/-/issues/4116 - Added some context to the VU and improved error message
this will make combining this VU with ShaderObject harder and likely will just need to be an exception case
=> layers: Clarify vkCmdSetColorWriteEnableEXT VU

layers/core_checks/cc_copy_blit_resolve.cpp, tests/unit/copy_buffer_image.cpp, tests/unit/copy_buffer_image_positive.cpp
=> Fix image copy queue support check

layers/state_tracker/fence_state.cpp
Closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/9621
=> layers: Remove assert from fence tracker

layers/gpuav/core/gpuav_features.cpp, layers/vulkan/generated/spirv_validation_helper.cpp, scripts/generators/spirv_validation_generator.py, tests/unit/shader_object.cpp, tests/unit/shader_spirv.cpp, tests/unit/shader_spirv_positive.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/9716
=> printf: No error if non semantic info ext not seen

layers/CMakeLists.txt
should close https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/9703 and https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/9170
@jsyjbaba and @alusch @webez can you help verify this fixes the problem (my issue is I can't reproduce it currently and seems it is a "simple" fix)
=> build: Use 16k pages in Android

tests/unit/gpu_av_buffer_device_address_positive.cpp
For future work in https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/9725 want to add stress test for `PositiveGpuAVBufferDeviceAddress`
=> tests: Add BDA Stress test

layers/core_checks/cc_render_pass.cpp, layers/vulkan/generated/object_tracker.cpp, scripts/generators/object_tracker_generator.py, tests/unit/fragment_shading_rate.cpp
Just fixes for VUID for the 1.4.311 header
=> layers: VUID Churn 311

tests/framework/binding.cpp, tests/framework/binding.h, tests/unit/command.cpp, tests/unit/external_memory_sync.cpp, tests/unit/image.cpp, tests/unit/image_layout_positive.cpp, tests/unit/image_positive.cpp, tests/unit/memory.cpp, tests/unit/memory_positive.cpp, tests/unit/render_pass_positive.cpp, tests/unit/sampler.cpp, tests/unit/sparse_image.cpp, tests/unit/sync_object.cpp, tests/unit/ycbcr.cpp, tests/unit/ycbcr_positive.cpp
Also remove `InitialImageMemoryBarrier` which is not used that often and can be replaced with `ImageMemoryBarrier`.
=> tests: Replace DefaultCreateInfo with ImageCreateInfo2D

layers/core_checks/cc_shader_object.cpp, layers/stateless/sl_shader_object.cpp, tests/unit/shader_object.cpp
Some improvement to the Shader Object error message, mainly printing out `VkShaderEXT` handles
=> layers: Improve Shader Object error messages

layers/core_checks/cc_spirv.cpp, layers/core_checks/core_validation.h, layers/state_tracker/shader_module.cpp, layers/state_tracker/shader_module.h, tests/CMakeLists.txt, tests/unit/shader_mesh.cpp, tests/unit/shader_mesh_positive.cpp, tests/unit/shader_object.cpp
=> Validate mesh shader memory size

layers/core_checks/cc_copy_blit_resolve.cpp, tests/unit/copy_buffer_image.cpp
=> Add missing image to image copy checks

tests/unit/fragment_shading_rate.cpp, tests/unit/fragment_shading_rate_positive.cpp
=> tests: Move fragment density map offset tests to EXT

tests/unit/memory_positive.cpp
Fixes failure in Windows Arm CI run
=> tests: Fix BindMemoryStatusBuffer

.github/workflows/vvl.yml, layers/CMakeLists.txt, layers/containers/custom_containers.h, layers/core_checks/core_validation.h, layers/external/parallel_hashmap/btree.h, layers/external/parallel_hashmap/meminfo.h, layers/external/parallel_hashmap/phmap.h, layers/external/parallel_hashmap/phmap_base.h, layers/external/parallel_hashmap/phmap_bits.h, layers/external/parallel_hashmap/phmap_config.h, layers/external/parallel_hashmap/phmap_dump.h, layers/external/parallel_hashmap/phmap_fwd_decl.h, layers/external/parallel_hashmap/phmap_utils.h, layers/gpuav/spirv/CMakeLists.txt, layers/vulkan/generated/vk_dispatch_table_helper.cpp, layers/vulkan/generated/vk_dispatch_table_helper.h, scripts/CMakeLists.txt, scripts/generators/dispatch_table_helper_generator.py, scripts/gn/export_targets.py, scripts/known_good.json, tests/CMakeLists.txt, tests/layers/CMakeLists.txt
Finish up https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/9740
=> layers: Use Parallel Hashmap

layers/best_practices/best_practices_validation.h, layers/chassis/validation_object.h, layers/state_tracker/state_tracker.h, layers/vulkan/generated/chassis.cpp, scripts/generators/layer_chassis_generator.py, tests/framework/layer_validation_tests.h, tests/unit/android_hardware_buffer_positive.cpp, tests/unit/vertex_input_positive.cpp
Post removing Robin Hood, looked and tried to find things to remove as includes
=> layers: Remove unused includes

scripts/generate_spirv.py
This makes the Window build go from like 5 seconds to under a second
tested on Linux, it makes it from half a second to basically instant
Seems glslang startup cost is really bad on Windows
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/9827
=> scripts: Multi-thread generate_spirv.py

layers/gpuav/validation_cmd/gpuav_draw.cpp, tests/unit/gpu_av_index_buffer_positive.cpp
Closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/9833
Copy paste error from a recent PR that touched that code
Thank you for the test Ziga!
=> gpuav: Fix draw buffer offset update

layers/vulkan/generated/instrumentation_post_process_descriptor_index_comp.cpp, scripts/generate_spirv.py
Fix to the known issue on main and also reporting of glslang errors when threading
=> scripts: Fix generate_spirv to report errors

layers/core_checks/cc_shader_interface.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/9821
=> layers: Fix Tessellation interface bug

layers/core_checks/cc_spirv.cpp, scripts/vk_validation_stats.py, tests/unit/shader_interface.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/9631
=> layers: Get VUID from spirv-val

layers/core_checks/cc_shader_object.cpp, layers/core_checks/core_validation.h, tests/framework/binding.cpp, tests/framework/binding.h, tests/framework/shader_object_helper.cpp, tests/framework/shader_object_helper.h, tests/unit/best_practices_positive.cpp, tests/unit/gpu_av_buffer_device_address_positive.cpp, tests/unit/gpu_av_descriptor_indexing_positive.cpp, tests/unit/shader_object.cpp, tests/unit/shader_object_positive.cpp
=> Validate shader object nextStage

layers/core_checks/cc_spirv.cpp, tests/device_profiles/max_profile.json, tests/unit/shader_cooperative_matrix_positive.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/9843
Just waiting to confirm with Jeff this is desired and a spec oversight (which 99% sure it is)
=> layers: Fix CoopMat for subgroup size

layers/core_checks/cc_descriptor.cpp, tests/unit/descriptors_positive.cpp
=> Fix descriptor allocation warning when binding has descriptorCount 0

tests/framework/sync_helper.h
The tests would fail to build on android
=> tests: Add missing unordered map include

layers/core_checks/cc_pipeline.cpp
New VUs for https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/7251
this is a case we don't actually know is possible to hit in the wild and we added these VUs as per-cautious
=> layers: VUID for Pipeline Robustness and Descriptor Index

scripts/generators/best_practices_generator.py, scripts/generators/dispatch_object_generator.py, scripts/generators/dispatch_table_helper_generator.py, scripts/generators/dispatch_vector_generator.py, scripts/generators/layer_chassis_generator.py, scripts/generators/object_tracker_generator.py, scripts/generators/spirv_tool_commit_id_generator.py, scripts/generators/stateless_validation_helper_generator.py, scripts/generators/sync_validation_generator.py, scripts/generators/thread_safety_generator.py
So misc cleanup from my Ruff linter, also inline the large strings to make the python code more easy to follow indentation
=> scripts: Warning and misc cleanup

layers/sync/sync_validation.cpp, layers/sync/sync_validation.h, tests/unit/sync_val.cpp, tests/unit/sync_val_positive.cpp
Closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/9851
=> sync: Validate vkCmdDispatchBase entrypoint

layers/core_checks/cc_drawdispatch.cpp, layers/core_checks/cc_image.cpp, layers/core_checks/cc_shader_object.cpp, layers/core_checks/core_validation.h, layers/drawdispatch/drawdispatch_vuids.cpp, layers/drawdispatch/drawdispatch_vuids.h, layers/error_message/unimplementable_validation.h, layers/state_tracker/pipeline_state.cpp, tests/unit/shader_object.cpp
From changes in https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/7125
=> layers: Update shader object VUID for 1.4.312

layers/vulkan/generated/stateless_validation_helper.cpp, scripts/generators/stateless_validation_helper_generator.py
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/9887
=> scripts: Ignore NV RTX Union of pointers

layers/best_practices/bp_instance_device.cpp, layers/state_tracker/state_tracker.cpp, layers/state_tracker/state_tracker.h, tests/unit/best_practices_positive.cpp
=> Fix checking if vkGetPhysicalDeviceFeatures has been called

layers/sync/sync_error_messages.cpp, tests/unit/sync_val_reporting.cpp
Closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/9874
This also fixes the issue that in some error messages there was the following, which is incorrect because acquire command does not submit to the queue:
> which was previously read by vkAcquireNextImageKHR (submitted on VkQueue )
=> sync: Fix reported command buffer and queue mismatch

layers/core_checks/cc_synchronization.cpp
Based on @spencer-lunarg feedback.
When I wrote that part I couldn't find a way to make it shorter, it turns out the solution is very simple.
=> layers: Update message formatting

BUILD.gn, layers/CMakeLists.txt, layers/chassis/validation_object.h, layers/core_checks/cc_state_tracker.cpp, layers/core_checks/core_validation.h, layers/gpuav/core/gpuav.h, layers/gpuav/core/gpuav_setup.cpp, layers/state_tracker/state_tracker.cpp, layers/state_tracker/state_tracker.h, layers/sync/sync_validation.cpp, layers/sync/sync_validation.h, layers/utils/keyboard.cpp, layers/utils/keyboard.h
Add a `-D DEBUG_CAPTURE_KEYBOARD=ON` and if you press `F1` it will at vkQueueSubmit detect if the key was pressed and allow us to add information what is going on
=> layers: Add Debug Capture option

layers/gpuav/instrumentation/gpuav_instrumentation.cpp
Add assert (and something to return and not crash) if trying to report a Descriptor Class that is wrong (currently source of unknown bug)
=> gpuav: Check if known descriptor class is not found

layers/gpuav/validation_cmd/gpuav_draw.cpp
The same command buffer can be used concurrently, so validation buffers accesses need to be properly synchronized
=> gpuav: Fix sync issue

layers/state_tracker/render_pass_state.cpp, layers/state_tracker/render_pass_state.h
Minor clenaup while looking into renderpass image layout code.
=> layers: RenderPass cleanup

layers/best_practices/bp_device_memory.cpp, layers/best_practices/bp_instance_device.cpp, layers/best_practices/bp_pipeline.cpp, layers/chassis/dispatch_object_manual.cpp, layers/core_checks/cc_device_memory.cpp, layers/core_checks/cc_external_object.cpp, layers/core_checks/cc_image.cpp, layers/core_checks/cc_pipeline.cpp, layers/core_checks/cc_query.cpp, layers/core_checks/cc_queue.cpp, layers/core_checks/cc_spirv.cpp, layers/gpuav/descriptor_validation/gpuav_image_layout.cpp, layers/gpuav/instrumentation/gpuav_shader_instrumentor.cpp, layers/gpuav/instrumentation/gpuav_shader_instrumentor.h, layers/object_tracker/object_tracker_utils.cpp, layers/state_tracker/cmd_buffer_state.cpp, layers/state_tracker/shader_object_state.cpp, layers/state_tracker/state_tracker.cpp, layers/stateless/sl_render_pass.cpp, layers/sync/sync_validation.cpp, layers/thread_tracker/thread_safety_validation.cpp, layers/vulkan/generated/dispatch_object.cpp, layers/vulkan/generated/object_tracker.cpp, scripts/generators/dispatch_object_generator.py, scripts/generators/object_tracker_generator.py, tests/unit/shader_object_positive.cpp
Some fixes around `PostCallRecord` not checking the VkResult correctly (or consistently )
=> layers: Fix missing VkResult state tracking

layers/core_checks/cc_drawdispatch.cpp, layers/core_checks/cc_shader_object.cpp, tests/unit/shader_object.cpp
Waiting on confirmation from https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/7296
=> layers: Add VU if no compute shader object is bound

layers/core_checks/cc_spirv.cpp, layers/error_message/unimplementable_validation.h, layers/stateless/sl_shader_object.cpp, tests/unit/shader_object.cpp, tests/unit/shader_spirv.cpp
these error messages are hit normally when you load in the SPIR-V incorrectly via your filesystem logic
Tried to improve the error messages and group the code better
=> layers: Improve invalid spirv error messages

layers/state_tracker/image_state.h
@jeremyg-lunarg this just a typo?
=> layers: Fix ImageViewSubState helpers

layers/gpuav/core/gpuav.h, layers/gpuav/core/gpuav_setup.cpp, layers/gpuav/instrumentation/gpuav_instrumentation.cpp, layers/gpuav/instrumentation/gpuav_shader_instrumentor.cpp, layers/gpuav/resources/gpuav_state_trackers.cpp, layers/gpuav/resources/gpuav_state_trackers.h, layers/state_tracker/last_bound_state.cpp, layers/state_tracker/last_bound_state.h, layers/state_tracker/shader_object_state.h, layers/state_tracker/state_tracker.h
finally moving out state tracking to be GPU-AV only
=> gpuav: Make a ShaderObjectSubState

tests/unit/gpu_av_indirect_buffer_positive.cpp
@arno-lunarg good job, your `RestorablePipelineState` logic seems good
=> tests: Add extra restore pipeline test

layers/core_checks/cc_cmd_buffer_dynamic.cpp, layers/core_checks/cc_drawdispatch.cpp, layers/core_checks/cc_image.cpp, layers/core_checks/cc_shader_object.cpp, layers/drawdispatch/drawdispatch_vuids.cpp, layers/drawdispatch/drawdispatch_vuids.h, layers/sync/sync_utils.cpp, layers/sync/sync_vuid_maps.cpp, tests/unit/debug_printf.cpp, tests/unit/gpu_av_buffer_device_address_positive.cpp, tests/unit/gpu_av_descriptor_indexing_positive.cpp, tests/unit/host_image_copy.cpp, tests/unit/others.cpp, tests/unit/pipeline_topology.cpp, tests/unit/ray_tracing.cpp, tests/unit/shader_object.cpp, tests/unit/shader_object_positive.cpp, tests/unit/sync_object.cpp, tests/unit/sync_object_positive.cpp
Lots of UNASSIGNED VUs getting a VUID
-  VUID-vkCmdDraw-primitiveTopology-10747
-  VUID-vkCmdDraw-primitiveTopology-10748
-  VUID-vkCmdDispatch-None-10743
- VUID-VkHostImageLayoutTransitionInfo-image-10749
- VUID-VkHostImageLayoutTransitionInfo-image-10750
-  ~~VUID-vkCmdDraw-nextStage-10744~~
-  VUID-vkCmdDraw-nextStage-10745
- VUID-vkCmdPipelineBarrier-srcStageMask-10754
-  VUID-VkMemoryBarrier2-srcStageMask-10751
-  VUID-VkMemoryBarrier2-srcStageMask-10752
-  VUID-VkMemoryBarrier2-srcStageMask-10753
=> layers: VUID churn 1.4.313

layers/core_checks/cc_descriptor.cpp, tests/unit/gpu_av_descriptor_class_general_buffer.cpp
=> tests: More GPL test GPUAV

layers/core_checks/cc_device_memory.cpp, tests/unit/android_hardware_buffer.cpp, tests/unit/memory.cpp
=> layers: More VUID Churn 1.4.313

layers/object_tracker/object_lifetime_validation.h, layers/object_tracker/object_tracker_utils.cpp, tests/unit/push_descriptor_positive.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/9792
forgot to cover edge case around Push Descriptors
=> layers: Fix Push Descriptor Immutable Sampler

layers/gpuav/resources/gpuav_state_trackers.cpp, layers/gpuav/resources/gpuav_state_trackers.h, layers/state_tracker/cmd_buffer_state.cpp, layers/state_tracker/cmd_buffer_state.h, layers/state_tracker/state_tracker.cpp
Saw this while working in this area, pulled out the flamethrower
=> gpuav: Return on failure, remove dead code

layers/core_checks/cc_device_memory.cpp, tests/unit/memory.cpp
VU churn for https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/6883
- Removed VUID-VkBufferDeviceAddressInfo-buffer-02600
- Updated VUID-vkGetBufferDeviceAddress-bufferDeviceAddress-03324
- Updated VUID-vkGetBufferOpaqueCaptureAddress-None-03326
- Added VUID-vkGetBufferOpaqueCaptureAddress-pInfo-10725
- Updated VUID-vkGetDeviceMemoryOpaqueCaptureAddress-None-03334
- Added  VUID-vkGetDeviceMemoryOpaqueCaptureAddress-pInfo-10727
- Updated VUID-VkBufferCreateInfo-flags-03338
=> layers: Fix BDA VU churn 1.4.313

layers/CMakeLists.txt, layers/chassis/validation_object.h, layers/state_tracker/state_tracker.cpp, layers/utils/keyboard.cpp, layers/utils/keyboard.h
Adds XCB support along side XLib support for `DEBUG_CAPTURE_KEYBOARD` debugging
=> debug: Add xcb support for keyboard detection

layers/chassis/dispatch_object.h, layers/chassis/dispatch_object_manual.cpp, layers/core_checks/cc_cmd_buffer_dynamic.cpp, layers/core_checks/cc_image.cpp, layers/core_checks/cc_render_pass.cpp, layers/core_checks/cc_state_tracker.h, layers/core_checks/cc_synchronization.cpp, layers/core_checks/core_validation.h, layers/state_tracker/cmd_buffer_state.cpp, layers/state_tracker/cmd_buffer_state.h, layers/state_tracker/render_pass_state.h, layers/state_tracker/state_tracker.cpp, layers/state_tracker/state_tracker.h, scripts/known_good.json, tests/device_profiles/max_profile.json, tests/unit/fragment_shading_rate.cpp, tests/unit/fragment_shading_rate_positive.cpp
https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/9962 with fixes
=> Add validation for vkCmdEndRendering2EXT

layers/core_checks/cc_descriptor.cpp, layers/core_checks/cc_pipeline_graphics.cpp, layers/core_checks/core_validation.h, tests/unit/graphics_library.cpp, tests/unit/graphics_library_positive.cpp
does not close https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/9870 (still need to add the drawtime check) but will fix the false positive Dan was seeing
=> layers: Fix over validating INDEPENDENT_SET linking

layers/gpuav/core/gpuav.h, layers/gpuav/core/gpuav_record.cpp, layers/gpuav/core/gpuav_setup.cpp, layers/gpuav/instrumentation/gpuav_instrumentation.cpp, layers/gpuav/resources/gpuav_vulkan_objects.h, layers/gpuav/spirv/vertex_attribute_fetch_oob.h
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/9975
=> gpuav: Move VertexAttributeFetchOff to shared resource

layers/core_checks/cc_copy_blit_resolve.cpp, layers/core_checks/cc_image.cpp, layers/core_checks/cc_image_layout.cpp, layers/gpuav/descriptor_validation/gpuav_image_layout.cpp, layers/state_tracker/cmd_buffer_state.cpp, layers/state_tracker/cmd_buffer_state.h, layers/state_tracker/image_layout_map.cpp, layers/state_tracker/image_layout_map.h
Mostly to simplify structure a bit before proceeding with other cleanup. And the cleanups is a preparation/learning to add some missing submit time image layout validations.
=> layers: Minor cleanup of image layout code

layers/core_checks/cc_drawdispatch.cpp, layers/state_tracker/pipeline_layout_state.cpp, layers/state_tracker/pipeline_state.cpp, tests/unit/graphics_library.cpp, tests/unit/graphics_library_positive.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/9870
=> layers: Fix GPL

layers/core_checks/cc_render_pass.cpp, layers/core_checks/core_validation.h, layers/gpuav/core/gpuav.h, layers/gpuav/core/gpuav_record.cpp, layers/gpuav/descriptor_validation/gpuav_image_layout.cpp, layers/state_tracker/state_tracker.cpp, layers/state_tracker/state_tracker.h, layers/sync/sync_validation.cpp, layers/sync/sync_validation.h
Move begin rendering/renderpass to Post call
=> layers: Move Pre to Post for begin render pass

tests/unit/image_layout_positive.cpp
Shows this scenario and can serve as regression test for future changes
It's not obvious how to write a test that tries to read bad data (probably possible, need to dig more into the code), but if fixes are needed going to address in the next PRs.
=> tests: Demo potential issue with layout tracking

layers/gpuav/descriptor_validation/gpuav_descriptor_validation.cpp, layers/gpuav/descriptor_validation/gpuav_descriptor_validation.h, layers/gpuav/instrumentation/gpuav_instrumentation.cpp, layers/gpuav/instrumentation/gpuav_instrumentation.h, layers/gpuav/resources/gpuav_shader_resources.h, layers/gpuav/resources/gpuav_state_trackers.cpp, layers/gpuav/resources/gpuav_state_trackers.h
Switch from American to British English (or simplified to traditional)
(Wanted to get this out of the PR I am working on)
=> gpuav: Fix English

layers/gpuav/instrumentation/gpuav_instrumentation.cpp, layers/gpuav/resources/gpuav_vulkan_objects.h, layers/gpuav/validation_cmd/gpuav_copy_buffer_to_image.cpp, layers/gpuav/validation_cmd/gpuav_dispatch.cpp, layers/gpuav/validation_cmd/gpuav_draw.cpp, layers/gpuav/validation_cmd/gpuav_trace_rays.cpp
=> gpuav: Update SharedResourcesCache interface

layers/core_checks/cc_synchronization.cpp, tests/unit/wsi.cpp
* Fix grammar when only single image was acquired
* Print swapchain fence wait part only if extension is enabled
* Provide different messages for shutdown scenario (after QueueWaitIdle) and during regular app loop (acquired new image). This part needs more improvements but for now it's better than before (if QueueWaitIdle was called then not mention newly acquired images even if there are some, since the app might not want to present anymore and needs just properly cleanup resources).
=> layers: Improve swapchain semaphore in-use messages

layers/best_practices/best_practices_validation.h, layers/best_practices/bp_pipeline.cpp, tests/unit/amd_best_practices.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/10019
=> bp: Handle VK_KHR_maintenance5

layers/gpuav/spirv/buffer_device_address_pass.cpp, tests/unit/gpu_av_buffer_device_address_positive.cpp
We didn't have any test in unsafe mode and mix the `min` and `max` to know the offset in the BDA being accessed, this lead to false positives when there was a struct load
=> gpuav: Fix bda range being backwards

layers/state_tracker/queue_state.cpp, layers/state_tracker/queue_state.h, layers/state_tracker/state_tracker.cpp, tests/unit/wsi_positive.cpp
This fixes memory leak from VkExtDynamicRendering's example here https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/9022#issuecomment-2834756471. I tried to come up with minimally intrusive fix. Some other options are possible but they look pretty complicated (fine-grained tracking of semaphroes across multiple frames) and this is usually terrible thing for maintenance, so trying to avoid at all possible cost (we already have such code paths for specific scenarios and it's not fun).
p.s. The original issue https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/9022 is likely something different (still makes sense to test against the latest VVL, there were sync fixes after 1.4.303).
=> layers: Help vvl retire submissions on present-only queue

layers/gpuav/core/gpuav.h, layers/gpuav/core/gpuav_setup.cpp, layers/gpuav/debug_printf/debug_printf.cpp, layers/gpuav/debug_printf/debug_printf.h, layers/gpuav/descriptor_validation/gpuav_descriptor_set.cpp, layers/gpuav/descriptor_validation/gpuav_descriptor_set.h, layers/gpuav/descriptor_validation/gpuav_descriptor_validation.cpp, layers/gpuav/descriptor_validation/gpuav_descriptor_validation.h, layers/gpuav/instrumentation/gpuav_instrumentation.cpp, layers/gpuav/resources/gpuav_state_trackers.cpp, layers/gpuav/resources/gpuav_vulkan_objects.cpp, layers/gpuav/resources/gpuav_vulkan_objects.h, layers/gpuav/spirv/vertex_attribute_fetch_oob.h, layers/gpuav/validation_cmd/gpuav_copy_buffer_to_image.cpp, layers/gpuav/validation_cmd/gpuav_draw.cpp
Cumbersome to pass around, no added value
=> gpuav: Remove location from VMA errors

layers/core_checks/cc_device_memory.cpp
just hit this right now and found the wording a bit awkward
=> layers: BindBufferMemory error message improvement

layers/VkLayer_khronos_validation.json.in
(reason explained inline)
before
after
=> settings: Order of GPU-AV settings

layers/core_checks/cc_synchronization.cpp
=> layers: Update swapchain semaphore error message

layers/gpuav/instrumentation/gpuav_shader_instrumentor.cpp, tests/unit/debug_printf.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/7178
Was still trying to instrument Shader Object after we warned the user "we will not try because you hit the limit"
=> gpuav: Fix ShaderObject hitting descriptor set limit

layers/core_checks/cc_descriptor.cpp, layers/core_checks/cc_drawdispatch.cpp, layers/core_checks/core_validation.h, layers/state_tracker/cmd_buffer_state.cpp, layers/state_tracker/last_bound_state.cpp, tests/unit/descriptors.cpp, tests/unit/pipeline.cpp, tests/unit/shader_object.cpp
Tried to improve this VU in various ways
part of (maybe closes) https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/9068
=> layers: Improve 08600 error messages

tests/unit/descriptors.cpp
https://gitlab.khronos.org/vulkan/vulkan/-/issues/4279
=> tests: Fix mutable descriptors test

tests/unit/shader_object_positive.cpp
Discussed in https://gitlab.khronos.org/vulkan/vulkan/-/issues/4258, we decided this is legal to do, so adding a test to catch it
=> tests: Add LastStage ShaderObject edge case

layers/best_practices/bp_instance_device.cpp, layers/best_practices/bp_wsi.cpp, layers/core_checks/cc_wsi.cpp, layers/state_tracker/device_state.cpp, layers/state_tracker/device_state.h
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/10084
=> layers: Fix missing checks for CallState

layers/chassis/dispatch_object_manual.cpp, layers/error_message/unimplementable_validation.h, layers/gpuav/core/gpuav_features.cpp, layers/stateless/sl_instance_device.cpp, tests/device_profiles/max_profile.json, tests/unit/device_feature_property.cpp, tests/unit/robustness.cpp, tests/unit/robustness_positive.cpp
=> layers: Add VK_KHR_robustness2

layers/state_tracker/shader_module.cpp, layers/state_tracker/shader_module.h, layers/stateless/sl_spirv.cpp, layers/stateless/sl_spirv.h, tests/device_profiles/max_profile.json, tests/unit/shader_spirv.cpp, tests/unit/shader_spirv_positive.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/9905
=> layers: Add shaderRelaxedExtendedInstruction check

layers/vulkan/generated/test_icd_helper.h, scripts/generators/test_icd_generator.py, tests/CMakeLists.txt, tests/device_profiles/max_profile.json, tests/icd/test_icd.cpp, tests/unit/shader_cooperative_vector.cpp, tests/unit/shader_cooperative_vector_positive.cpp
1. Move file to have `shader_` prefix
2. Get it running with TestICD so we can confirm regressions locally
=> layers: Add Cooperative Vector TestICD support

layers/state_tracker/semaphore_state.cpp, tests/unit/sync_object.cpp, tests/unit/sync_object_positive.cpp
When retire external payload ensure that earlier signals are retired.
Addresses timeline semaphore tracking issues from https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/10055.
=> layers: Fix external timeline semaphore tracking

layers/best_practices/bp_instance_device.cpp, layers/state_tracker/state_tracker.cpp, layers/state_tracker/state_tracker.h
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/10096
=> bp: Add vkGetPhysicalDeviceFeatures2 Uncall check

layers/core_checks/cc_device_memory.cpp, layers/core_checks/cc_image.cpp, layers/core_checks/cc_pipeline_graphics.cpp, layers/core_checks/cc_render_pass.cpp, layers/core_checks/cc_synchronization.cpp, layers/core_checks/core_validation.h, layers/state_tracker/device_memory_state.cpp, layers/state_tracker/device_memory_state.h, layers/stateless/sl_image.cpp, layers/stateless/sl_render_pass.cpp, layers/sync/sync_vuid_maps.cpp, layers/sync/sync_vuid_maps.h, tests/device_profiles/max_profile.json, tests/unit/external_memory_sync.cpp, tests/unit/image.cpp, tests/unit/memory_positive.cpp, tests/unit/protected_memory.cpp, tests/unit/render_pass.cpp, tests/unit/sync_object.cpp, tests/unit/sync_object_positive.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/10088
=> add VK_EXT_zero_initialize_device_memory

layers/core_checks/cc_video.cpp, layers/state_tracker/video_session_state.cpp, layers/state_tracker/video_session_state.h
Improve Vulkan Video related error messages with detailed information about video profiles.
=> layers: Add detailed information about video profiles in error msgs

layers/core_checks/cc_video.cpp, layers/state_tracker/video_session_state.cpp
Print the supported video profiles in a newline separated list
=> layers: Print supported video profiles in separate lines

layers/best_practices/best_practices_validation.h, layers/best_practices/bp_cmd_buffer.cpp, layers/best_practices/bp_constants.h, layers/best_practices/bp_copy_blit_resolve.cpp, layers/best_practices/bp_device_memory.cpp, layers/best_practices/bp_drawdispatch.cpp, layers/best_practices/bp_image.cpp, layers/best_practices/bp_instance_device.cpp, layers/best_practices/bp_pipeline.cpp, layers/best_practices/bp_state.h, layers/best_practices/bp_synchronization.cpp, layers/best_practices/bp_wsi.cpp, tests/unit/arm_best_practices.cpp, tests/unit/best_practices.cpp, tests/unit/nvidia_best_practices.cpp
We should not have checks that don't have a "here is what do instead response"
=> bp: Remove warning with no justification

layers/core_checks/cc_image_layout.cpp, layers/gpuav/descriptor_validation/gpuav_image_layout.cpp, layers/state_tracker/cmd_buffer_state.cpp, layers/state_tracker/image_layout_map.cpp, layers/state_tracker/image_layout_map.h
Now `CommandBufferImageLayoutMap` is a lean class that extends `BothRangeMap` with an image id field.
=> layers: Refactor CommandBufferImageLayoutMap

layers/containers/subresource_adapter.h, layers/core_checks/cc_image_layout.cpp, layers/core_checks/cc_queue.cpp, layers/core_checks/cc_state_tracker.cpp, layers/core_checks/cc_synchronization.cpp, layers/core_checks/core_validation.h, layers/gpuav/descriptor_validation/gpuav_image_layout.cpp, layers/state_tracker/cmd_buffer_state.cpp, layers/state_tracker/cmd_buffer_state.h, layers/state_tracker/image_layout_map.cpp, layers/state_tracker/image_layout_map.h
Finishing with layout map refactorings.
The main entities in `image_layout_map.h/cpp` are more or less documented and cleaned up.
=> layers: Misc layout map refactorings

layers/core_checks/cc_device_memory.cpp, layers/core_checks/cc_pipeline.cpp, layers/core_checks/cc_spirv.cpp
I updated Self VVL internally for CI (http://erusea.lunarg.localdomain:8080/view/Administration/job/vvl-self-validation/7/)
found these few spots that needed fixing
=> layers: Fixes from Self VVL

layers/stateless/sl_instance_device.cpp, layers/stateless/sl_utils.cpp, scripts/known_good.json
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/10134
cc @charles-lunarg
=> layers: Improve sType error messages

layers/core_checks/cc_cmd_buffer_dynamic.cpp, tests/unit/dynamic_state.cpp, tests/unit/dynamic_state_positive.cpp, tests/unit/shader_object.cpp
based on https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/7289
(update - might not take this, waiting for spec to be approved)
=> layers: Fix depthWriteEnable dpending on depthWriteEnable

layers/sync/sync_validation.cpp, layers/sync/sync_validation.h, tests/unit/sync_val_ray_tracing.cpp, tests/unit/sync_val_ray_tracing_positive.cpp
Many repeated parts in the tests, will add helpers in the next PR.
=> sync: Validate vkCmdTraceRaysIndirectKHR

layers/core_checks/cc_descriptor.cpp, layers/core_checks/core_validation.h, layers/state_tracker/descriptor_sets.cpp, layers/state_tracker/descriptor_sets.h, tests/unit/descriptor_indexing.cpp, tests/unit/descriptors.cpp, tests/unit/descriptors_positive.cpp
The error message before were lack luster (and found some edge case bugs too!) 
This adds better message and even added a VulkanGuide article to go along with it https://github.com/KhronosGroup/Vulkan-Guide/pull/317
=> layers: Improve Consecutive Binding Updates errors

layers/core_checks/cc_image.cpp, layers/stateless/sl_image.cpp, tests/unit/image.cpp
Fixes up some error message and adds a proper test for `02251`
=> layers: Improve image error messages

tests/unit/sync_val.cpp, tests/unit/sync_val_positive.cpp
The original test in addition to layout transition also tested implicit ordering of StoreOp/LoadOp, and mixed positive and negative checks. Introduce test for each scenario.
=> tests: Split syncval LayoutTransition test

layers/VkLayer_khronos_validation.json.in
New default "non-advance" look
=> gpuav: Move settings to advance

layers/VkLayer_khronos_validation.json.in, layers/layer_options.cpp
=> gpuav: Deprecate gpuav_max_buffer_device_addresses

layers/state_tracker/wsi_state.cpp, tests/unit/wsi_positive.cpp
Fixes that semaphore stores outdated state when shared present mode is used.
After the previous PR (https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/10225) this outdated state does not cause issues, but it's better to fix this. The previous PR should also address the second scenario from https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/10201.
=> layers: Improve semaphore swapchain info cleanup

layers/vulkan/generated/spirv_grammar_helper.cpp, layers/vulkan/generated/spirv_grammar_helper.h, layers/vulkan/generated/spirv_tools_commit_id.h, layers/vulkan/generated/spirv_validation_helper.cpp, scripts/known_good.json, tests/unit/shader_spirv.cpp
To help pull in https://github.com/KhronosGroup/SPIRV-Tools/pull/6176
=> scripts: Update SPIR-V deps

layers/chassis/chassis_manual.cpp, layers/gpuav/core/gpuav.h, layers/gpuav/core/gpuav_record.cpp, layers/gpuav/core/gpuav_setup.cpp, layers/gpuav/descriptor_validation/gpuav_descriptor_set.cpp, layers/gpuav/descriptor_validation/gpuav_descriptor_set.h, layers/gpuav/instrumentation/descriptor_checks.cpp, layers/gpuav/instrumentation/descriptor_checks.h, layers/gpuav/resources/gpuav_state_trackers.cpp, layers/gpuav/resources/gpuav_vulkan_objects.cpp, layers/gpuav/resources/gpuav_vulkan_objects.h, layers/gpuav/validation_cmd/gpuav_copy_buffer_to_image.cpp, layers/gpuav/validation_cmd/gpuav_dispatch.cpp, layers/gpuav/validation_cmd/gpuav_draw.cpp, layers/gpuav/validation_cmd/gpuav_trace_rays.cpp, layers/gpuav/validation_cmd/gpuav_validation_cmd_common.cpp, layers/gpuav/validation_cmd/gpuav_validation_cmd_common.h, layers/profiling/profiling.cpp, layers/state_tracker/state_tracker.cpp, layers/state_tracker/state_tracker.h, tests/unit/gpu_av.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/10218 (and likely https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/10230)
=> gpuav: Fix deadlock when resources are leaked

layers/chassis/dispatch_object.h, layers/chassis/dispatch_object_manual.cpp, layers/core_checks/cc_image.cpp, layers/core_checks/cc_pipeline_graphics.cpp, layers/core_checks/cc_render_pass.cpp, layers/core_checks/core_validation.h, layers/drawdispatch/drawdispatch_vuids.cpp, layers/drawdispatch/drawdispatch_vuids.h, layers/stateless/sl_render_pass.cpp, scripts/known_good.json, tests/device_profiles/max_profile.json, tests/framework/render_pass_helper.cpp, tests/framework/render_pass_helper.h, tests/unit/fragment_shading_rate.cpp, tests/unit/fragment_shading_rate_positive.cpp
Adds the following VUs
- VUID-vkCmdDraw-layers-10831
- VUID-VkRenderingInfo-flags-10826
- VUID-VkRenderingInfo-fragmentDensityMapLayered-10827
- VUID-VkRenderPassCreateInfo-fragmentDensityMapLayered-10828
- VUID-VkRenderPassCreateInfo2-fragmentDensityMapLayered-10829
- VUID-VkFramebufferCreateInfo-renderPass-10830
- VUID-VkPipelineFragmentDensityMapLayeredCreateInfoVALVE-maxFragmentDensityMapLayers-10825
=> layers: Add VK_VALVE_fragment_density_map_layered

scripts/known_good.json
to match with https://github.com/KhronosGroup/SPIRV-Tools/pull/6172/files#r2146983233
=> deps: Update mimalloc to 3.0.3

layers/core_checks/cc_descriptor.cpp, layers/state_tracker/state_tracker.cpp
some nit things noticed and wanted to fix while looking at Copies in `vkUpdateDescriptorSets`
=> layers: Misc cleanup for Copy Update

layers/sync/sync_commandbuffer.cpp, layers/sync/sync_common.cpp, layers/sync/sync_common.h, layers/sync/sync_op.h
Make sync_common a bit leaner so maybe later we can replace it with less generic includes.
=> sync: Cleanup sync_common

layers/sync/sync_access_context.cpp, layers/sync/sync_access_context.h, layers/sync/sync_access_state.cpp, layers/sync/sync_access_state.h, layers/sync/sync_common.cpp, layers/sync/sync_common.h, layers/sync/sync_op.cpp, layers/sync/sync_reporting.cpp, layers/sync/sync_submit.cpp, layers/sync/sync_validation.h
Remove `SyncStageAccess` struct.
Cleanup `SyncBarrier` struct.
=> sync: Cleanup sync_common more

layers/core_checks/cc_pipeline_graphics.cpp, tests/unit/dynamic_rendering.cpp, tests/unit/pipeline.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/10273
=> layers: Add missing VK_FORMAT_E5B9G9R9_UFLOAT_PACK32 check

layers/sync/sync_op.cpp
=> layers: Remove replaced VUID 03838

tests/unit/wsi_positive.cpp
"Fix" test to do what it should be doing, but still getting VVL error, need to look more, tracking in https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/10285
=> tests: Disable DifferentPerPresentModeImageCount

layers/core_checks/cc_drawdispatch.cpp, tests/unit/descriptor_buffer.cpp, tests/unit/descriptor_buffer_positive.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/10290
=> layers: Fix false positive for DescriptorBuffers

BUILD.gn, layers/CMakeLists.txt, layers/state_tracker/cmd_buffer_state.cpp, layers/state_tracker/query_state.cpp, layers/state_tracker/query_state.h, layers/state_tracker/state_tracker.cpp
Some cleanup to make all the Query State stuff consistent
=> layers: Cleanup of Query State

tests/unit/image_layout.cpp
Due to image layout fixes some checks can be more conservative. For example, no need to make QueueSubmit if validation can be done during record time.
On the other hand some checks that were done during submit time are moved now to Wait() we call after submit (less conservative). That's preparation for ongoing layout transition validation done at command buffer retire time.
=> tests: Cleanup blit image layout test

layers/core_checks/cc_image.cpp, tests/unit/sync_object.cpp, tests/unit/sync_object_positive.cpp
From https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/7483
cc @artem-lunarg @ziga-lunarg
=> layers: Another maintenance9 cleanup

layers/state_tracker/image_state.cpp, layers/state_tracker/image_state.h, layers/state_tracker/state_tracker.cpp, tests/unit/image_layout_positive.cpp
Closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/10330
=> layers: Fix view subresource normalization with maintenance9

layers/core_checks/cc_ray_tracing.cpp, layers/core_checks/cc_state_tracker.cpp, layers/core_checks/cc_state_tracker.h, layers/core_checks/core_validation.h, layers/state_tracker/cmd_buffer_state.cpp, layers/state_tracker/cmd_buffer_state.h, layers/state_tracker/state_tracker.cpp
Forgot this last one from https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/10333
=> layers: Move vkCmdWriteAccelerationStructuresPropertiesKHR

layers/core_checks/cc_descriptor.cpp, layers/core_checks/cc_drawdispatch.cpp, layers/core_checks/core_validation.h, tests/unit/descriptors.cpp, tests/unit/descriptors_positive.cpp, tests/unit/graphics_library.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/10312
=> layers: Fix binding Null descriptors with GPL

layers/core_checks/cc_cmd_buffer_dynamic.cpp, layers/state_tracker/cmd_buffer_state.cpp, layers/state_tracker/cmd_buffer_state.h, layers/state_tracker/last_bound_state.cpp, layers/state_tracker/last_bound_state.h, layers/state_tracker/pipeline_state.h, layers/state_tracker/pipeline_sub_state.cpp, layers/state_tracker/pipeline_sub_state.h, layers/state_tracker/render_pass_state.cpp, layers/vulkan/generated/dynamic_state_helper.cpp, scripts/generators/dynamic_state_generator.py, tests/unit/shader_object.cpp
from https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/7491
=> layers: Combine Dynamic BlendConstant VU

layers/state_tracker/cmd_buffer_state.cpp, layers/state_tracker/cmd_buffer_state.h, layers/sync/sync_commandbuffer.cpp, layers/sync/sync_commandbuffer.h, layers/sync/sync_stats.cpp, layers/sync/sync_stats.h
Some cleanup of memory stats reporting
=> sync: Refine memory stats

layers/best_practices/bp_state.cpp, layers/best_practices/bp_state.h, layers/core_checks/cc_state_tracker.cpp, layers/core_checks/cc_state_tracker.h, layers/gpuav/resources/gpuav_state_trackers.cpp, layers/gpuav/resources/gpuav_state_trackers.h, layers/state_tracker/cmd_buffer_state.cpp, layers/state_tracker/cmd_buffer_state.h, layers/state_tracker/state_tracker.cpp, layers/sync/sync_commandbuffer.cpp, layers/sync/sync_commandbuffer.h, layers/sync/sync_validation.cpp, layers/sync/sync_validation.h
Broken down by commit, the rest will take more consideration to move over
=> Sync: Even more things to command buffer sub state

layers/core_checks/cc_pipeline_ray_tracing.cpp, layers/core_checks/cc_spirv.cpp, tests/unit/ray_tracing_pipeline.cpp
Closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/10358
=> layers: Fix handling of unused shaders in RT val

layers/core_checks/cc_descriptor.cpp, layers/state_tracker/descriptor_sets.cpp, layers/state_tracker/pipeline_state.cpp, tests/unit/descriptors.cpp, tests/unit/graphics_library.cpp
from https://github.com/ValveSoftware/Fossilize/issues/275
=> layers: Fix GPL Immutable Sampler bug

tests/unit/atomics.cpp, tests/unit/dynamic_state.cpp
3 tests that were failing on newest Intel Mesa due to us not querying support
=> tests: Fix broken tests on newest Mesa

layers/gpuav/validation_cmd/gpuav_draw.cpp, tests/unit/debug_printf.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/10371
=> printf: Fix MeshIndirectCount support

scripts/known_good.json, scripts/tests.py, tests/README.md, tests/icd/test_icd.cpp
pulls in https://github.com/KhronosGroup/Vulkan-Profiles/pull/789 from Ziga
=> test: Update to new Profiles

layers/core_checks/cc_descriptor.cpp, layers/stateless/sl_descriptor.cpp, tests/unit/descriptor_buffer.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/10383
=> layers: Add missing DescriptorBuffer Sampler

tests/unit/ray_tracing_positive.cpp
Closes https://github.com/issues/assigned?issue=KhronosGroup%7CVulkan-ValidationLayers%7C10388
No need to test update build in this test, it is extensively done in other tests
=> tests: Update SerializeAccelerationStructure

layers/core_checks/cc_descriptor.cpp, layers/state_tracker/descriptor_sets.cpp, layers/state_tracker/descriptor_sets.h, layers/state_tracker/state_tracker.cpp, layers/state_tracker/state_tracker.h, layers/stateless/sl_descriptor.cpp, layers/stateless/stateless_validation.h, layers/vulkan/generated/stateless_validation_helper.cpp, scripts/generators/stateless_validation_helper_generator.py, tests/framework/binding.cpp, tests/framework/binding.h, tests/framework/layer_validation_tests.h, tests/unit/debug_printf.cpp, tests/unit/descriptor_buffer.cpp, tests/unit/descriptor_buffer_positive.cpp, tests/unit/gpu_av_descriptor_buffer_positive.cpp
1. Improves/compact writing descriptor buffer tests
2. Adds a texel buffer test
=> tests: Cleanup of DescriptorBuffers

layers/core_checks/cc_cmd_buffer.cpp, layers/core_checks/cc_render_pass.cpp, layers/stateless/sl_instance_device.cpp, tests/unit/device_feature_property.cpp, tests/unit/dynamic_rendering.cpp, tests/unit/dynamic_state.cpp, tests/unit/robustness_positive.cpp
Adds VUID for
- VUID-vkCmdBindVertexBuffers2-None-08971
- VUID-VkDeviceCreateInfo-ppEnabledExtensionNames-10858
- VUID-VkRenderingInfo-viewMask-10859
- VUID-VkRenderingInfo-viewMask-10860
- VUID-VkRenderingInfo-viewMask-10861
=> layers: VUID Churn 1.4.322

layers/state_tracker/state_tracker.cpp, tests/unit/dynamic_rendering_local_read_positive.cpp
Closes #10408
Very similar to #9865
=> Fix tracking local read location info

layers/core_checks/cc_cmd_buffer_dynamic.cpp, layers/core_checks/cc_pipeline_graphics.cpp, layers/core_checks/cc_shader_interface.cpp, layers/core_checks/cc_shader_object.cpp, layers/core_checks/cc_spirv.cpp, layers/core_checks/core_validation.h, layers/drawdispatch/drawdispatch_vuids.cpp, layers/drawdispatch/drawdispatch_vuids.h, layers/state_tracker/last_bound_state.cpp, layers/state_tracker/last_bound_state.h, layers/state_tracker/pipeline_state.cpp, layers/state_tracker/shader_module.cpp, layers/state_tracker/shader_module.h, layers/state_tracker/shader_object_state.cpp, layers/state_tracker/shader_object_state.h, layers/stateless/sl_spirv.cpp, layers/utils/vk_api_utils.h, tests/unit/dynamic_state.cpp, tests/unit/mesh.cpp, tests/unit/multiview.cpp, tests/unit/pipeline.cpp, tests/unit/portability_subset.cpp, tests/unit/shader_object.cpp
This is a large cleanup of all thing Topology
Basically we never were doing it correctly and now the spec has a nice section (https://registry.khronos.org/vulkan/specs/latest/html/vkspec.html#drawing-rasterization-input-topology)
=> layers: Cleanup Topology

layers/core_checks/cc_cmd_buffer_dynamic.cpp, layers/core_checks/cc_drawdispatch.cpp, layers/drawdispatch/drawdispatch_vuids.cpp, layers/drawdispatch/drawdispatch_vuids.h, layers/state_tracker/cmd_buffer_state.h, tests/unit/shader_object.cpp
Based on https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/7530 and https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/7527 approved today and will be in the next header
=> layers: Combine more dynamic state for color attachment

layers/core_checks/cc_drawdispatch.cpp
=> layers: Improve wording of 07750

layers/core_checks/cc_pipeline_graphics.cpp, layers/core_checks/cc_shader_object.cpp, layers/core_checks/cc_spirv.cpp, layers/core_checks/core_validation.h, layers/state_tracker/shader_module.cpp, layers/state_tracker/shader_module.h, tests/framework/layer_validation_tests.h, tests/unit/mesh.cpp, tests/unit/mesh_positive.cpp, tests/unit/shader_mesh.cpp
Adds `VUID-RuntimeSpirv-MeshEXT-10883`, had to do some cleanup around `TaskPayloadWorkgroupEXT` while here
=> layers: Add Runtime TaskPayloadWorkgroupEXT

layers/core_checks/cc_copy_blit_resolve.cpp, layers/core_checks/cc_descriptor.cpp, layers/core_checks/cc_device_memory.cpp, layers/core_checks/cc_image.cpp, layers/core_checks/cc_queue.cpp, layers/core_checks/cc_tensor.cpp, layers/core_checks/core_validation.h, layers/state_tracker/cmd_buffer_state.cpp, layers/state_tracker/cmd_buffer_state.h, layers/state_tracker/state_tracker.cpp, layers/stateless/sl_tensor.cpp, layers/stateless/stateless_validation.h, tests/framework/layer_validation_tests.h, tests/unit/tensor.cpp, tests/unit/tensor_positive.cpp
Some nit picks to make things more consistent as it is everywhere else
=> layers: Nit pick fixes

layers/state_tracker/cmd_buffer_state.cpp, tests/unit/pipeline_positive.cpp
Attachment type tracking must be reset between subpasses
=> Reset attachment types between subpasses

layers/VkLayer_khronos_validation.json.in, layers/layer_options.cpp
Feel it is time to finally remove this, been long enough
=> layers: Remove deprecated GPU-AV DebugPrintf setting

layers/core_checks/cc_wsi.cpp, tests/device_profiles/max_profile.json, tests/icd/test_icd.cpp, tests/unit/wsi.cpp
Add some missing vendor extensions so they are ready to test in Github CI when people get around to adding them
=> tests: Add missing max_profile extensions

tests/unit/copy_buffer_image.cpp, tests/unit/copy_buffer_image_positive.cpp
For https://github.com/KhronosGroup/Vulkan-Docs/issues/1005
=> tests: Confirm final Compressed image issue

layers/core_checks/cc_cmd_buffer.cpp, layers/core_checks/cc_device_generated_commands.cpp, layers/core_checks/cc_queue.cpp, layers/state_tracker/cmd_buffer_state.cpp, layers/state_tracker/cmd_buffer_state.h, layers/vulkan/generated/command_validation.cpp, scripts/generators/command_validation_generator.py, tests/unit/command.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/9929 and https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/9239
=> layers: Improve and fix CommandBuffer Recording messages

layers/core_checks/cc_image.cpp, layers/state_tracker/image_state.h, tests/unit/image_positive.cpp
Found a test that reproduces the issue mentioned in todo
=> layers: Fix image view subresource normalization todo

layers/state_tracker/image_state.cpp, tests/unit/image_layout_positive.cpp
Closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/10453
Going to do one more refactor PR that adds helper to have layout transition criteria check in a single place.
=> layers: Fix maintenance9 layout transition criteria

layers/sync/sync_access_state.cpp, layers/sync/sync_access_state.h, layers/sync/sync_commandbuffer.cpp, layers/sync/sync_commandbuffer.h, layers/sync/sync_stats.cpp, layers/sync/sync_stats.h, layers/sync/sync_submit.h, layers/sync/sync_validation.cpp, layers/sync/sync_validation.h
Add stats for main access tracking structures.
Minor refactor: update ForAllQueueBatchContexts helper.
=> sync: Add access context stats

layers/sync/sync_stats.cpp, layers/sync/sync_stats.h
Make output more structured and less cluttered
=> sync: Update stats formatting

layers/sync/sync_access_context.cpp, layers/sync/sync_access_context.h, layers/sync/sync_op.cpp, tests/unit/sync_val_positive.cpp
Closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/10488
=> sync: Fix maintenance9 layout transition

layers/vulkan/generated/spirv_tools_commit_id.h, scripts/known_good.json
Update requested here: https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/10499#discussion_r2260003676
=> layers: Update spirv-tools

tests/unit/device_queue.cpp
- the test was not setting and checking protected memory correctly
- the test was always skipped
=> tests: Fix NegativeDeviceQueue.QueuesSameQueueFamily

tests/unit/sync_val.cpp, tests/unit/sync_val_positive.cpp
SyncVal does extra steps (pending barrier state) to ensure that barriers within a single barrier command are applied independently. So far we did not have any test fails if that functionality is broken: everything passes when you apply barrier immediately without using pending state. This PR adds `NegativeSyncVal.CmdPipelineBarrier2IndependentBarriers` test that will fail in case of regression.
=> tests: Show barrier command defines independent barriers

layers/error_message/logging.cpp, layers/vulkan/generated/feature_requirements_helper.cpp, scripts/generate_spec_error_message.py, tests/unit/others.cpp
So far only tested with CS2, where this change was able to restore an interactive frame rate. Issue with current implementation is looking up a vuid far into the list, search becomes expensive.
=> layers: Improve VUID lookup perf

layers/drawdispatch/descriptor_validator.cpp, layers/state_tracker/descriptor_sets.h, tests/unit/descriptor_indexing.cpp, tests/unit/descriptor_indexing_positive.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/10490
=> layers: Fix variable count static array

layers/containers/container_utils.h
fix build issue with newer Clang
=> layers: Update container_utils.h

layers/vulkan/generated/spirv_tools_commit_id.h, scripts/known_good.json, tests/unit/atomics.cpp, tests/unit/atomics_positive.cpp, tests/unit/gpu_av_buffer_device_address.cpp, tests/unit/gpu_av_buffer_device_address_positive.cpp, tests/unit/gpu_av_descriptor_class_general_buffer.cpp, tests/unit/gpu_av_descriptor_class_general_buffer_positive.cpp, tests/unit/gpu_av_descriptor_class_texel_buffer_positive.cpp, tests/unit/gpu_av_descriptor_indexing.cpp, tests/unit/gpu_av_descriptor_indexing_positive.cpp, tests/unit/shader_debug_info.cpp, tests/unit/shader_object.cpp, tests/unit/shader_spirv.cpp
=> scripts: Update SPIRV-Tools

tests/unit/ray_tracing_pipeline.cpp
this test description was messing with `vk_validation_stats.py`
=> tests: Fix test description

layers/sync/sync_op.cpp
Each helper was called only in a single place and inlining helps to see the full picture better. This is an intermediate step in the task to rework how the pending barrier state is stored.
=> sync: Inline ApplyBarriers helpers

tests/unit/gpu_av_descriptor_post_process.cpp, tests/unit/gpu_av_descriptor_post_process_positive.cpp
This runs with update to Mesa driver, realize it was wrong VUID
=> tests: Fix MixingProtectedResources VUID reported

tests/unit/video.cpp
DISTINCT implementations cannot have DECODE_SRC + DECODE_DPB simultaneously.
=> tests: Fix NegativeVideo.CreateImageProfileIndependent for DISTINCT

tests/unit/sync_val_ray_tracing.cpp, tests/unit/sync_val_ray_tracing_positive.cpp
Add tests inspired by https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/10577
=> tests: Test two AS builds with barrier in between

layers/drawdispatch/descriptor_validator.cpp, layers/error_message/spirv_logging.cpp, layers/error_message/spirv_logging.h, layers/gpuav/instrumentation/gpuav_shader_instrumentor.cpp
Because @arno-lunarg yelled at me in https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/10563#discussion_r2293905923
=> gpuav: Combine FindShaderSource

tests/CMakeLists.txt
@artem-lunarg you were not going crazy, this was happening, but it didn't do anything bad, but lets remove it lol
=> build: Remove trying to chmod shared libs

layers/core_checks/cc_cmd_buffer.cpp, layers/core_checks/core_validation.h, layers/stateless/sl_cmd_buffer.cpp
Need to deal with `VkCommandBufferInheritanceInfo` for upcoming extension and wanted this cleaned up now
=> layers: Cleanup of VkCommandBufferInheritanceInfo

layers/core_checks/cc_cmd_buffer_dynamic.cpp, layers/core_checks/cc_pipeline_graphics.cpp, tests/unit/dynamic_state.cpp, tests/unit/pipeline.cpp, tests/unit/pipeline_positive.cpp
From: https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/7614
=> Validate min and max depth bounds

layers/state_tracker/descriptor_sets.cpp, layers/state_tracker/descriptor_sets.h, tests/unit/descriptors_positive.cpp
Follow up to https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/10604
DescriptorSetLayoutDef cannot provide information about immutable
samplres (immutable samplers are not shared between set layouts in
general).
~~In general no good reason not to use `DescriptorSetLayout::desc_set_layout_ci`
(which stores all info including immutable samplers) and instead to hop to `layout_id_`
to get incomplete information (due to immutable samplers). The main purpose of
`DescriptorSetLayoutDef` is to determine if set layouts are equivalent.~~
NOTE: the above strikethrough reasoning is wrong, the order (original) of bindings in DescriptorSetLayout::desc_set_layout_ci
is different from the bindings order in DescreiptorSetLayoutDef. The latter sorts the bindings.
Closes …
=> layers: Do not use set layout Def to get binding info

layers/core_checks/cc_synchronization.cpp
Add article linked thanks to the suggestion from https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/10624
Minor cleanup of the error message.
=> layers: Add link to swapchain reuse article

layers/core_checks/cc_render_pass.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/10622
new message
```
vkCmdBeginTransformFeedbackEXT(): cannot be called on this primary command buffer because vkCmdBeginRenderPass was called with VK_SUBPASS_CONTENTS_SECONDARY_COMMAND_BUFFERS.
Only vkCmdExecuteCommands is allowed in the first subpass until vkCmdNextSubpass or vkCmdEndRenderPass is called.
```
=> layers: Improve Subpass Contents error message

layers/core_checks/cc_drawdispatch.cpp, layers/core_checks/cc_shader_interface.cpp, layers/core_checks/core_validation.h, layers/state_tracker/cmd_buffer_state.cpp, layers/state_tracker/cmd_buffer_state.h, layers/state_tracker/state_tracker.cpp, tests/framework/render.cpp, tests/framework/render.h, tests/unit/shader_interface.cpp, tests/unit/shader_interface_positive.cpp
=> Layers: Fix fragment output compatibility check with output remapping

layers/layer_options_validation.h, scripts/generate_settings.py, tests/unit/layer_settings.cpp
=> layers: Fix typo of 'recognized'

layers/core_checks/cc_spirv.cpp, layers/vulkan/generated/spirv_grammar_helper.cpp, layers/vulkan/generated/spirv_grammar_helper.h, layers/vulkan/generated/spirv_tools_commit_id.h, layers/vulkan/generated/spirv_validation_helper.cpp, scripts/known_good.json, tests/unit/shader_interface.cpp
pulls in https://github.com/KhronosGroup/SPIRV-Tools/pull/6283
=> layers: Update SPIR-V Tools

layers/core_checks/cc_cmd_buffer.cpp, layers/stateless/sl_cmd_buffer.cpp, tests/unit/transform_feedback.cpp
=> Update transform feedback to use effective size

tests/framework/binding.cpp, tests/framework/ray_tracing_helper_nv.cpp, tests/unit/amd_best_practices.cpp, tests/unit/arm_best_practices.cpp, tests/unit/best_practices.cpp, tests/unit/best_practices_positive.cpp, tests/unit/dynamic_rendering.cpp, tests/unit/external_memory_sync_positive.cpp, tests/unit/fragment_shading_rate.cpp, tests/unit/pipeline_positive.cpp, tests/unit/ray_tracing.cpp, tests/unit/ray_tracing_nv.cpp, tests/unit/ray_tracing_positive.cpp, tests/unit/render_pass_positive.cpp, tests/unit/secondary_command_buffer.cpp
Saw one and had 5 minutes on the plane to clean up a bit
=> tests: Use InitStructHelper

tests/icd/test_icd.cpp
Found this is not obvious (which I agree)
=> tests: Add helpful text for updating format features

layers/state_tracker/cmd_buffer_state.cpp, tests/unit/dynamic_state.cpp
closing https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/10699
=> layers: Improve multiview dynamic state

layers/core_checks/cc_cmd_buffer_dynamic.cpp, layers/core_checks/cc_tensor.cpp, layers/drawdispatch/drawdispatch_vuids.cpp, layers/drawdispatch/drawdispatch_vuids.h, tests/unit/tensor.cpp
=> layers: VUID Churn 327

layers/sync/sync_access_state.cpp, tests/unit/sync_val_wsi_positive.cpp
Closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/10693
=> sync: Fix Resolve of layout transition ordering

layers/core_checks/cc_drawdispatch.cpp, layers/core_checks/cc_shader_interface.cpp, layers/core_checks/cc_shader_object.cpp, layers/core_checks/cc_spirv.cpp, layers/core_checks/core_validation.h, layers/state_tracker/shader_module.cpp, layers/state_tracker/shader_module.h, tests/unit/geometry_tessellation.cpp, tests/unit/shader_object.cpp
From https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/7694
=> layers: Fix Tessellation with Shader Object

BUILD.gn, layers/CMakeLists.txt, layers/core_checks/cc_android.cpp, layers/core_checks/cc_data_graph.cpp, layers/core_checks/cc_device.cpp, layers/core_checks/cc_device_memory.cpp, layers/core_checks/cc_drawdispatch.cpp, layers/core_checks/cc_spirv.cpp, layers/core_checks/cc_synchronization.cpp, layers/core_checks/cc_tensor.cpp, layers/core_checks/cc_vuid_maps.cpp, layers/core_checks/core_validation.h, layers/vulkan/generated/test_icd_helper.h, scripts/generators/test_icd_generator.py, tests/CMakeLists.txt, tests/device_profiles/max_profile.json, tests/framework/binding.cpp, tests/framework/binding.h, tests/framework/data_graph_objects.cpp, tests/framework/data_graph_objects.h, tests/framework/layer_validation_tests.h, tests/framework/render.cpp, tests/icd/test_icd.cpp, tests/unit/android_hardware_buffer.cpp, tests/unit/data_graph.cpp, tests/unit/data_graph_positive.cpp, tests/unit/external_memory_sync.cpp, tests/unit/parent.cpp, tests/unit/tensor.cpp
=> layers: New VK_ARM_data_graph extension - Part 2: layers and tests

layers/core_checks/cc_image_layout.cpp, layers/core_checks/core_validation.h, layers/drawdispatch/descriptor_validator.cpp, layers/state_tracker/state_tracker.h
Prints `DescribeDescriptor` error message to make Mike's life easier
=> layers: Improve layout descriptor error messages

layers/sync/sync_access_state.cpp, layers/sync/sync_stats.cpp, layers/sync/sync_stats.h
=> sync: Add max first accesses stats

tests/device_profiles/max_profile.json, tests/icd/test_icd.cpp, tests/unit/arm_best_practices.cpp, tests/unit/atomics.cpp, tests/unit/debug_printf.cpp, tests/unit/dynamic_state.cpp, tests/unit/shader_cooperative_matrix.cpp
did while traveling back from F2F
=> Misc test cleanup for TestICD

layers/chassis/dispatch_object.h, layers/chassis/dispatch_object_manual.cpp, layers/core_checks/cc_copy_blit_resolve.cpp, layers/core_checks/core_validation.h, scripts/known_good.json, tests/device_profiles/max_profile.json, tests/unit/copy_buffer_image.cpp, tests/unit/copy_buffer_image_positive.cpp
From `VK_KHR_copy_memory_indirect` added in 1.4.328
=> layers: Add VK_KHR_copy_memory_indirect

layers/gpuav/instrumentation/gpuav_instrumentation.cpp, layers/gpuav/shaders/gpuav_shaders_constants.h, layers/state_tracker/cmd_buffer_state.cpp, layers/state_tracker/cmd_buffer_state.h, layers/state_tracker/state_tracker.cpp
Some basic stuff want to get in before dropping a bomb of a PR for Descriptor Buffer support in GPU-AV
=> layers: Pre-work for Descriptor Buffer

layers/core_checks/cc_descriptor.cpp
new message
```
vkCreatePipelineLayout(): pCreateInfo->pSetLayouts[1] was created with VK_DESCRIPTOR_SET_LAYOUT_CREATE_HOST_ONLY_POOL_BIT_EXT but pSetLayouts[0] was not.
```
as it was annoying to not know which 2 `pSetLayouts` (and didn't even have a handle)
=> layers: Improve 08008 message

tests/unit/gpu_av_buffer_device_address_positive.cpp, tests/unit/gpu_av_descriptor_class_general_buffer_positive.cpp, tests/unit/gpu_av_descriptor_class_texel_buffer_positive.cpp, tests/unit/gpu_av_index_buffer_positive.cpp, tests/unit/gpu_av_ray_tracing_positive.cpp
=> tests: Add gpu-av descriptor buffer tests

layers/gpuav/instrumentation/gpuav_shader_instrumentor.cpp, layers/gpuav/instrumentation/gpuav_shader_instrumentor.h, layers/state_tracker/pipeline_state.h, tests/unit/gpu_av_buffer_device_address.cpp, tests/unit/gpu_av_descriptor_class_general_buffer.cpp, tests/unit/gpu_av_positive.cpp
Finished what I started before my PTO
For cs2, going into a map, I hit the "already seen library just re-use the instrumented one" case ~2000 times
=> gpuav: Instrument GPL only once

tests/unit/descriptor_buffer_positive.cpp
Part of #10763
These tests include mesh shaders, GPL and vkCmdBindDescriptorBufferEmbeddedSamplersEXT()
=> tests: Add more descriptor buffer tests

layers/core_checks/cc_buffer.cpp, tests/unit/descriptor_buffer_positive.cpp, tests/unit/ray_tracing_pipeline_positive.cpp
=> Add more descriptor buffer tests

layers/core_checks/cc_descriptor.cpp, layers/state_tracker/descriptor_sets.cpp, layers/state_tracker/descriptor_sets.h, tests/unit/descriptors.cpp, tests/unit/descriptors_positive.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/10785
improves errors while here as well
=> layers: Fix mutable using binding and not index

tests/framework/ray_tracing_objects.cpp, tests/unit/descriptors_positive.cpp, tests/unit/subgroups.cpp
some fixes to get my new machine to run all the tests
=> tests: Fixes to run tests on new machine

layers/core_checks/cc_image.cpp, tests/unit/imageless_framebuffer_positive.cpp
caught in mesa that the test was wrong, we were missing a Validation case
=> layers: Add missing color clear check
