KhronosGroup/Vulkan-ValidationLayers

tests/unit/imageless_framebuffer.cpp, tests/unit/imageless_framebuffer_positive.cpp
@spencer-lunarg We had some overlap in updating VUID-VkFramebufferCreateInfo-flags-04587. The layer implementation change was identical, but Samsung's version had slightly more testing, so this PR covers the test part
=> tests: Improve tests for VUID-VkFramebufferCreateInfo-flags-04587

layers/core_checks/cc_buffer_address.h, layers/core_checks/cc_descriptor.cpp, layers/stateless/sl_descriptor.cpp, tests/framework/binding.h, tests/unit/descriptor_buffer.cpp, tests/unit/descriptor_buffer_positive.cpp, tests/unit/ray_tracing_nv.cpp
- Improves some error messages
- Uses newer coding conventions
- Splits up large tests
- Use framework more for tests
=> Descriptor Buffer cleanup

layers/core_checks/cc_cmd_buffer_dynamic.cpp, layers/core_checks/cc_device.cpp, layers/core_checks/cc_ray_tracing.cpp, layers/core_checks/cc_synchronization.cpp, layers/core_checks/core_validation.h
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/8432
for lots of things `ValidateExtendedDynamicState` was just a way to call `ValidateCmd`
the other cases, it made the error message of the features being bad
=> layers: Inline ValidateExtendedDynamicState

layers/gpu/core/gpu_settings.h, layers/gpu/core/gpuav_record.cpp, layers/gpu/core/gpuav_setup.cpp, layers/gpu/instrumentation/gpu_shader_instrumentor.cpp, tests/CMakeLists.txt, tests/unit/gpu_av_descriptor_buffer_positive.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/8492
We will have to redo the entire Shader Instrumentation Flow to handle Descriptor Buffers
For now make use of `shader_instrumentation_enabled` to prevent any shader instrumentation hooks to take place when turned off
=> gpu: Fix Descriptor Buffer GPU-AV crash

layers/core_checks/cc_descriptor.cpp
@spencer-lunarg I'd like your opinion on this one. Currently the test for `VUID-vkCmdSetDescriptorBufferOffsetsEXT-firstSet-09006` correctly detects that the VUID is violated, but then continues on trying to do further validation and ends up calling `vkGetDescriptorSetLayoutSizeEXT` which is invalid because the layout was created without `VK_DESCRIPTOR_SET_LAYOUT_CREATE_DESCRIPTOR_BUFFER_BIT_EXT`
Ultimately this results in the following misleading error message in the current tests:
````
[ RUN      ] NegativeDescriptorBuffer.CmdSetDescriptorBufferOffsets
/home/SERILOCAL/r.potter/dev/Vulkan-ValidationLayers/tests/framework/error_monitor.cpp:252: Failure
Failed
Validation Error: [ VUID-vkCmdSetDescriptorBufferOffsetsEXT-pOffsets-08063 ] Object 0: handle = 0x5590ad0504c0, type = …
```
=> layers: Early exit on VUID 09006 violation

layers/gpu/instrumentation/gpu_shader_instrumentor.cpp
When `timelineSemaphore` is already enabled, there's no need to generate this warning:
```
Forcing VkPhysicalDeviceVulkan12Features::timelineSemaphore to VK_TRUE
```
=> gpu: Don't emit redundant warnings

layers/gpu/debug_printf/debug_printf.cpp, layers/layer_options.cpp, tests/unit/debug_printf.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/8411
if the user wrote over the buffer, we truncate it, but forgot to clamp the clearing to `VK_LAYER_PRINTF_BUFFER_SIZE`
added test triggered same error in the issue
=> printf: Fix clearing over output buffer size

layers/utils/vk_layer_utils.h
The `continue;` was affecting the `while (0)` loop, not the intended parent loop
=> layers: Fix assert_and_continue

layers/gpu/spirv/pass.cpp
Fixed a crash in `Pass::ConvertTo32()`.
Reproduce: https://github.com/corporateshark/lightweightvk/blob/master/samples/004_YUV.cpp
=> gpu: Fix crash in `Pass::ConvertTo32()`

layers/stateless/sl_buffer.cpp, layers/stateless/sl_cmd_buffer.cpp, layers/stateless/sl_image.cpp, layers/stateless/sl_pipeline.cpp, layers/stateless/sl_ray_tracing.cpp, layers/stateless/sl_utils.cpp, layers/stateless/stateless_validation.h, layers/vulkan/generated/stateless_validation_helper.cpp, scripts/generators/stateless_validation_helper_generator.py, tests/unit/other_positive.cpp, tests/unit/others.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/8367
This passes through the `PhysicalDevice` handle when we validate enums/flags
=> Fix maintenance5 PhysicalDevice checks

layers/vulkan/generated/spirv_grammar_helper.cpp, layers/vulkan/generated/spirv_tools_commit_id.h, layers/vulkan/generated/spirv_validation_helper.cpp, scripts/known_good.json
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/8513
This grabs this change https://github.com/KhronosGroup/SPIRV-Tools/pull/5789 that fixes the comparison of `OpTypeImage` to not compare the `Depth` which was giving false positive
=> layers: Update SPIRV-Tools

layers/gpu/spirv/pass.cpp
applies same fix from https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/8510 here
=> gpu: Add guard to CastToUint32

layers/layer_options.cpp
Was setting the wrong env variable and going crazy, changed internal variable to match name
=> gpu: Fix variable to match setting name

layers/core_checks/cc_shader_object.cpp, layers/core_checks/cc_spirv.cpp, layers/core_checks/core_validation.h, tests/unit/atomics.cpp, tests/unit/geometry_tessellation.cpp, tests/unit/shader_interface.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/8382
I went through all the `VUID-RuntimeSpirv-*` VUs and made sure there was a path from Shader Object, there were 2 functions missing and added them (with tests)
=> Add all RuntimeSpirv checks to Shader Object

layers/containers/custom_containers.h, layers/state_tracker/queue_state.cpp, layers/state_tracker/semaphore_state.cpp, layers/state_tracker/semaphore_state.h, layers/state_tracker/state_tracker.cpp, layers/state_tracker/state_tracker.h, tests/unit/sync_object.cpp, tests/unit/sync_object_positive.cpp, tests/unit/sync_val_wsi_positive.cpp
Broadly this fixes the following categories of issues:
* semaphore signal on one queue could initiate forward progress on a different queue and mark resources there as not in-use in the scenarios where the second queue is not synchronized with a host in any way.
* various combinations of timeline semaphore host signal/wait led to deadlock (timeout and internal vvl error).
* issues with timeline synchronization when signal and wait values are not equal (larger signals also resolve the waits).
The main observation that notifying timeline's timepoint should notify only resolving signals but not the waits (which can trigger forward progress on other queues even without host wait). The waits are naturally processed when forward progress on particular queue goes over submissions one by one. …
=> layers: Update semaphore state tracking

layers/core_checks/cc_cmd_buffer_dynamic.cpp, layers/state_tracker/state_tracker.cpp, tests/unit/vertex_input.cpp, tests/unit/vertex_input_positive.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/8523
When we called `vkCmdSetVertexInputEXT` twice in the same command buffer, we were not actually updating the values since `emplace()` does not override the value in the `unordered_map`
=> layers: Fix multiple calls to CmdSetVertexInputEXT

layers/gpu/core/gpuav_setup.cpp
Same as https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/8529 but for Buffer Device Address
=> gpu: Don't warn if bda is already enabled

layers/stateless/stateless_validation.h, layers/vulkan/generated/valid_enum_values.cpp, layers/vulkan/generated/valid_flag_values.cpp, scripts/generators/valid_enum_values_generator.py, scripts/generators/valid_flag_values_generator.py, tests/unit/others.cpp
similar to https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/8534 but for the enums
old message
> [ VUID-VkImageCreateInfo-format-parameter ] | vkCreateImage(): pCreateInfo->format (1000340001) requires the extensions VK_EXT_4444_formats.
now
> [ VUID-VkImageCreateInfo-format-parameter ] | vkCreateImage(): pCreateInfo->format (VK_FORMAT_A4B4G4R4_UNORM_PACK16) requires the extensions VK_EXT_4444_formats.
=> Improve enum extension error message

layers/core_checks/cc_ray_tracing.cpp, layers/core_checks/core_validation.h, tests/framework/ray_tracing_objects.cpp, tests/framework/ray_tracing_objects.h, tests/unit/ray_tracing.cpp, tests/unit/ray_tracing_positive.cpp
Considered build ranges when looking for scratch buffer memory overlaps were incorrect: the build ranges of the first operand were always used to compute scratch size of the second operand, instead of the correct build ranges.
Removed disabled test `PositiveRayTracing::BuildAccelerationStructuresDeferredOperation`, deferred operation are already covered
=> layers: Fix accel struct validation

layers/core_checks/cc_ray_tracing.cpp, tests/unit/ray_tracing.cpp
Closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/8452
Validation of compactable accel structs would require us to make a query, so skip validation in this case.
=> layers: Update 03675

layers/chassis/layer_chassis_dispatch_manual.cpp, layers/vulkan/generated/layer_chassis_dispatch.cpp, scripts/generators/layer_chassis_dispatch_generator.py, tests/unit/pipeline_binary_positive.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/8540
Background:
- `VK_KHR_pipeline_binary` is already an exception to a lot of rules for code gen because we mix the way to do input/output from pNext (fun discussion here https://gitlab.khronos.org/vulkan/vulkan/-/issues/3880)
- 1.3.294 the `VK_KHR_pipeline_binary` extension came out and we added support (https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/8450) and it was all working
- 1.3.295 there was an XML change (https://github.com/KhronosGroup/Vulkan-Docs/commit/8e435deb15124bbf9a7e3340e6cc7975999ed5c5) that caused some strange code gen (https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/8485/files#r1741222743) and it was now breaking thigns
This change basically reverts the original working …
=> scripts: Fix vkGetPipelineKeyKHR

layers/gpu/debug_printf/debug_printf.cpp, layers/gpu/instrumentation/gpu_shader_instrumentor.cpp, layers/gpu/instrumentation/gpu_shader_instrumentor.h, layers/gpu/instrumentation/gpuav_instrumentation.cpp
now the error message will display
> Shader Module (4fac1c0000000032) (internal ID 1)
which is **SUPER** nice when you have large app and do a `VK_LAYER_GPUAV_DEBUG_DUMP_INSTRUMENTED_SHADERS` and need to line up which shader matches the error
=> gpu: Print internal shader ID in error message

layers/core_checks/cc_pipeline.cpp, tests/unit/pipeline_binary_positive.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/8544
=> layers: Fix vkGetPipelineKeyKHR with null createinfo

layers/gpu/core/gpu_state_tracker.cpp, layers/gpu/core/gpu_state_tracker.h, layers/gpu/instrumentation/gpu_shader_instrumentor.cpp, layers/gpu/instrumentation/gpu_shader_instrumentor.h, layers/state_tracker/queue_state.cpp, layers/state_tracker/queue_state.h, layers/state_tracker/semaphore_state.cpp, layers/state_tracker/semaphore_state.h, layers/state_tracker/state_tracker.cpp, layers/state_tracker/state_tracker.h, tests/unit/sync_object_positive.cpp
Closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/8461
Discussed with ~@jeremy-lunarg~ @jeremyg-lunarg  reverted commit.  PreRecord guarantees that any dependent PostRecord will see registered signals/waits in semaphore state object. There is a code that relies on this (when retiring non-external semaphore wait, there should be a signal).
=> layers: Remove workaround for handling missing signals

layers/error_message/logging.cpp, layers/error_message/logging.h, layers/vk_layer_config.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/8430
now will print the full error message in logcat
```
I VALIDATION: VUID-vkCmdDraw-None-06479(ERROR / SPEC): msgNum: 1268585879 - Validation Error: [ VUID-vkCmdDraw-None-06479 ] Object 0: handle = 0xd5b26f0000000010, type = VK_OBJECT_TYPE_DESCRIPTOR_SET; Object 1: handle = 0xd897d90000000016, type = VK_OBJECT_TYPE_IMAGE_VIEW; | MessageID = 0x4b9d1597 | vkCmdDraw():  the descriptor VkDescriptorSet 0xd5b26f0000000010[] [Set 0, Binding 1, Index 0, variable "tex"] has VkImageView 0xd897d90000000016[] with format of VK_FORMAT_R4G4_UNORM_PACK8 which doesn't support VK_FORMAT_FEATURE_2_SAMPLED_IMAGE_DEPTH_COMPARISON_BIT.
I VALIDATION: (supported features: VK_FORMAT_FEATURE_2_SAMPLED_IMAGE_BIT|VK_FORMAT_FEATURE_2_BLIT_SRC_BIT …
```
=> layers: Split long android error messages

layers/gpu/instrumentation/gpu_shader_instrumentor.cpp, layers/gpu/instrumentation/gpu_shader_instrumentor.h, layers/state_tracker/pipeline_state.h, tests/unit/debug_printf.cpp, tests/unit/gpu_av_oob.cpp, tests/unit/gpu_av_oob_positive.cpp, tests/unit/gpu_av_positive.cpp
For https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/8459
Currently a little rough, if this works well, will want to cleanup the somewhat duplicate code path (already wanted to do it with shader object path)
=> gpu: Defer GPL instrumenation until linking

layers/VkLayer_khronos_validation.json.in, layers/error_message/logging.cpp, layers/error_message/logging.h, layers/gpu/core/gpu_settings.h, layers/gpu/core/gpuav_setup.cpp, layers/gpu/debug_printf/debug_printf.cpp, layers/gpu/debug_printf/debug_printf.h, layers/layer_options.cpp, layers/layer_options.h, layers/vulkan/generated/chassis.cpp, layers/vulkan/generated/chassis.h, scripts/generators/layer_chassis_generator.py
Does 2 main things
1. Move the settings together (from https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/8561)
2. Add **much** nicer error messages on what is going on with very common mistakes one would get trying to use debugprintf
=> printf: Improve the debugprintf settings

layers/gpu/instrumentation/gpu_shader_instrumentor.cpp, layers/layer_options.cpp, layers/state_tracker/shader_module.h
Update to https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/8564
found that warnings NEED to go through the callback or else they can easily be lost in the void....forever!!
=> layers: Sending setting warning through debug callback

layers/core_checks/cc_descriptor.cpp
before the error was
> VkPipelineLayout 0xd175b40000000013[]) only contains 1 setLayouts corresponding to sets 0-0, but you're attempting to bind set to index 1.
now it says
> VkPipelineLayout 0xd175b40000000013[]) only contains 1 setLayout, corresponding to index 0, but you're attempting to bind set to index 1.
or 
> VkPipelineLayout 0xd175b40000000013[]) only contains 4 setLayout, corresponding from index 0 to 3, but you're attempting to bind set to index 6.
=> layers: Improve compatible dsl message

layers/core_checks/cc_descriptor.cpp, layers/core_checks/cc_drawdispatch.cpp, layers/state_tracker/cmd_buffer_state.cpp, layers/state_tracker/cmd_buffer_state.h, layers/state_tracker/pipeline_state.h, layers/state_tracker/state_tracker.cpp, tests/unit/descriptors.cpp
While debugging GPU-AV with self val, noticed some of these Pipeline Layout Compatibility messages are still a bit cryptic ... the main issue is trying to clearly state which "layout" is from `vkCmdBindPipeline` vs `vkCmdBindDescriptorSet` calls
=> layers: Improve Error Message descriptor set layout

scripts/generators/object_tracker_generator.py
These were displaying as warning for `object_tracker.cpp` on code gen
=> scripts: Suppress VK_KHR_pipeline_binary warnings

tests/unit/sync_val_positive.cpp
When this test was introduced running time could vary 10x depending on the device. Reduce the number of threads to reduce threading contention (but still keep high enough) with a hope to make running time a bit less unpredictable.
=> tests: Simplify threading configuration

layers/gpu/core/gpuav_setup.cpp, layers/gpu/instrumentation/gpu_shader_instrumentor.cpp, tests/unit/gpu_av.cpp
from https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/8414
Adds same things for `rayQuery` and `shaderInt64`
=> gpuav: Force more features if possible

layers/gpu/core/gpuav_setup.cpp, layers/gpu/instrumentation/gpu_shader_instrumentor.cpp, tests/unit/gpu_av.cpp
This reverts commit c1f8ad1fb56dac845979536a4b082a1fa0b8bc51.
Self Validation Error: [ VUID-vkCreateDevice-ppEnabledExtensionNames-01387 ] 
Object 0: handle = 0x1ab3517f0e0, type = VK_OBJECT_TYPE_INSTANCE; | 
MessageID = 0x12537a2c | 
vkCreateDevice(): pCreateInfo->ppEnabledExtensionNames[1] Missing extension required by the device extension VK_KHR_ray_query: VK_KHR_acceleration_structure.
The Vulkan spec states: All required device extensions for each extension in the VkDeviceCreateInfo::ppEnabledExtensionNames list must also be present in that list (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-vkCreateDevice-ppEnabledExtensionNames-01387)
Not a priority now, so I am just reverting
=> gpu: Revert forcing of ray query

layers/core_checks/cc_cmd_buffer_dynamic.cpp, layers/core_checks/core_validation.h, layers/drawdispatch/drawdispatch_vuids.cpp, layers/drawdispatch/drawdispatch_vuids.h, layers/state_tracker/cmd_buffer_state.h, layers/state_tracker/pipeline_state.cpp, layers/state_tracker/pipeline_state.h, layers/state_tracker/state_tracker.cpp, layers/state_tracker/state_tracker.h, layers/stateless/sl_cmd_buffer_dynamic.cpp, layers/stateless/sl_pipeline.cpp, layers/stateless/stateless_validation.h, layers/vulkan/generated/dynamic_state_helper.cpp, layers/vulkan/generated/stateless_validation_helper.cpp, scripts/generators/dynamic_state_generator.py, scripts/generators/stateless_validation_helper_generator.py, tests/device_profiles/max_profile.json, tests/unit/dynamic_state.cpp, tests/unit/dynamic_state_positive.cpp, tests/unit/pipeline.cpp, tests/unit/pipeline_positive.cpp
=> layers: Add VK_EXT_depth_clamp_control

layers/sync/sync_submit.cpp, layers/sync/sync_submit.h, layers/sync/sync_validation.cpp, tests/unit/sync_val_semaphore_positive.cpp
Addresses signals cleanup for vkQueueWaitIdle/vkDeviceWaitIdle. Main timelines PR implemented this only for vkWaitSemaphores.
=> sync: Cleanup timeline signals after queue/device wait

.github/workflows/vvl.yml
Based on  https://github.com/KhronosGroup/Vulkan-ValidationLayers/actions/runs/11071704738/usage 
as stated in comment, the goal is to save 15+ minutes of CI time per run reducing non-useful testing
=> ci: Remove redundant Thread Sanitize testing

layers/sync/sync_validation.cpp, layers/sync/sync_validation.h, tests/unit/sync_val_semaphore_positive.cpp
In contrast to binary semaphores, timeline can be signaled arbitrary amount of times without waits. Ensure resource usage does not grow unboundeadly in this case.
Also unify code that cleanups signals, so it's shared with QueueWaitIdle/DeviceWaitIdle.
=> sync: Cleanup signals that are never/rarely waited on

layers/gpu/core/gpuav_record.cpp
funnel the KHR to the core version so we don't have to maintain duplicate code paths
=> gpuav: Use PostCallRecordCmdDispatchBase alias

layers/state_tracker/pipeline_layout_state.cpp
I hit a situation with Self Validation where the set in the middle was null and it was trying to print out the error via `DescribeDifference` and crashed
=> layers: Warn if one descriptor set is null

tests/framework/binding.cpp, tests/framework/binding.h
On a device which has queue families that only have queueFlags `VK_QUEUE_VIDEO_DECODE_BIT_KHR` or `VK_QUEUE_VIDEO_ENCODE_BIT_KHR` and none of the others some tests would assert, for example `NegativeWsi.SwapchainNotSupported`
=> tests: Add video queues to test framework

layers/vulkan/generated/gpu_av_shader_hash.h, scripts/generate_spirv.py
We were hashing the input GLSL which allowed a change like https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/8620 to completely change how the shaders work (write to binding `1` not `0`) and the hash was not being updated
=> gpuav: Hash shaders from output, not input

layers/gpu/instrumentation/gpuav_instrumentation.cpp, tests/unit/gpu_av_oob_positive.cpp
I missed this in https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/8565 and luckily there was a DebugPrintf test that caught this when I was merging things
The issue is based on having this
```
vkt::PipelineLayout pipeline_layout_vs(device, {&vertex_set.layout_, nullptr              }, {}, VK_PIPELINE_LAYOUT_CREATE_INDEPENDENT_SETS_BIT_EXT);
vkt::PipelineLayout pipeline_layout_fs(device, {nullptr,             &fragment_set.layout_}, {}, VK_PIPELINE_LAYOUT_CREATE_INDEPENDENT_SETS_BIT_EXT);
vkt::PipelineLayout pipeline_layout   (device, {&vertex_set.layout_, &fragment_set.layout_}, {},
```
and before we were grabbing the `pipeline_layout_vs` which ended up having a null set inside causing self validation error (and crashing on drivers as well in CI)
=> gpuav: Handle VK_PIPELINE_LAYOUT_CREATE_INDEPENDENT_SETS_BIT_EXT

layers/sync/sync_validation.cpp, layers/sync/sync_validation.h
This fixes false-positives in Vulkan-Samples timeline_semaphore demo and in similar multi-threaded scenarios.
Two main changes: 
* Validate phase for QueueSubmit is protected by mutex
* Validate phase does both Validation and Updates state directly instead of using pending variables.
QueueSubmit calls in syncval (Present will be update later if necessary) computed state during Validate phase. It was stored in mutable variables and then is applied in the Record phase. Having this pending variables introduce additional complexity and with timeline semaphores synchronization becomes even more difficult. 
This change applies state directly at the end of the Validate phase instead of forwarding it through pending variables. The role of the pending variables was mostly to follow conventions of …
=> sync: Apply pending state during Validate phase

layers/core_checks/core_validation.h, layers/state_tracker/pipeline_sub_state.cpp, layers/state_tracker/pipeline_sub_state.h, scripts/generate_source.py
- Use combined headers for `chassis.cpp`
- Re-add virtual qualifier lost during renaming
- Propagate code duplication of module query to all call sites
- This last item is something which should likely be refactored, as it's currently subject to copy-paste mistakes. Obtaining the module of a ShaderStage should be factored out into "one source of truth".
- We ran into this issue because a newly added test uncovered places previously uncovered. In some copies of the module obtaining query, the pipeline cache was interrogated for the module, but not in all copies, and the newly added test stumbled across such a codepath.
=> Fix issues uncovered by SC downstream

layers/VkLayer_khronos_validation.json.in
There is the [emergency commit](https://gitlab.khronos.org/vulkan/Vulkan-SDK-Packaging/-/issues/1587) we cherry-picked into the SDK
But this main PR goal is to reduce the vertical size of that JSON file as it is **VERY** error prone to work with. Even on a 15-inch laptop screen I am not able to view the entire Preset on the screen and its dangerous to edit like that
The change basically takes all the "key/value" fields and just reduce it from 4 lines to 1 so we can read them all together
```patch
- { 
-     "key": "validate_core", 
-     "value": true 
- },
- { 
-     "key": "check_image_layout", 
-     "value": true 
- },
+ { "key": "validate_core", "value": true },
+ { "key": "check_image_layout", "value": true },
```
=> settings: Shrink config json vertical size

tests/framework/binding.cpp, tests/framework/binding.h, tests/unit/image_positive.cpp, tests/unit/sync_val_wsi.cpp, tests/unit/sync_val_wsi_positive.cpp, tests/unit/wsi_positive.cpp
=> tests: Add Queue::Present helper

layers/core_checks/cc_descriptor.cpp, layers/state_tracker/descriptor_sets.cpp, layers/state_tracker/pipeline_state.cpp, layers/state_tracker/pipeline_state.h
there were some VUs in https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/8605 that needed this fix
=> layers: Fix Layout Set Compatible check

tests/framework/binding.cpp, tests/framework/binding.h, tests/framework/render.cpp, tests/framework/render.h, tests/unit/amd_best_practices.cpp, tests/unit/arm_best_practices.cpp, tests/unit/best_practices.cpp, tests/unit/best_practices_positive.cpp, tests/unit/wsi.cpp, tests/unit/wsi_positive.cpp
=> tests: Add Swapchain wrapper

layers/gpu/cmd_validation/gpuav_cmd_validation_common.cpp, layers/gpu/cmd_validation/gpuav_cmd_validation_common.h, layers/gpu/cmd_validation/gpuav_copy_buffer_to_image.cpp, layers/gpu/cmd_validation/gpuav_draw.cpp, layers/gpu/cmd_validation/gpuav_trace_rays.cpp, layers/gpu/core/gpuav.h, layers/gpu/core/gpuav_record.cpp, layers/gpu/core/gpuav_setup.cpp, layers/gpu/debug_printf/debug_printf.cpp, layers/gpu/debug_printf/debug_printf.h, layers/gpu/descriptor_validation/gpuav_descriptor_set.cpp, layers/gpu/descriptor_validation/gpuav_descriptor_set.h, layers/gpu/descriptor_validation/gpuav_descriptor_validation.cpp, layers/gpu/descriptor_validation/gpuav_image_layout.cpp, layers/gpu/instrumentation/gpuav_instrumentation.cpp, layers/gpu/instrumentation/gpuav_instrumentation.h, layers/gpu/instrumentation/gpuav_shader_instrumentor.cpp, layers/gpu/instrumentation/gpuav_shader_instrumentor.h, layers/gpu/resources/gpuav_resources.cpp, layers/gpu/resources/gpuav_resources.h, layers/gpu/resources/gpuav_shader_resources.h, layers/gpu/resources/gpuav_subclasses.cpp, layers/gpu/resources/gpuav_subclasses.h
(Broken up into nice commits)
The goal of this was to have `DeviceMemoryBlock` wrap VMA so we can now just go
```c++
debug_printf_output_buffer.CreateBuffer(loc, &buffer_info, &alloc_info);
uint32_t *data;
debug_printf_output_buffer.MapMemory(loc, reinterpret_cast<void **>(&data));
memset(data, 0, gpuav.gpuav_settings.debug_printf_buffer_size);
debug_printf_output_buffer.UnmapMemory();
```
without the many (error-prone copy-and-pasted) "is VMA returning VK_SUCCESS" checks
While at it, I had to move a lot of stuff out of `GpuShaderInstrumentor` to the main GPU-AV class object (because now there is no trying to duplicate work for DebugPrintf) ... we can on the future of `GpuShaderInstrumentor` later, but this now leaves it where it is only dealing with "shader instrumentation" and not …
=> gpuav: Create VMA wrappers for DeviceMemoryBlock

tests/framework/binding.cpp, tests/framework/binding.h, tests/unit/sync_object.cpp, tests/unit/sync_object_positive.cpp, tests/unit/sync_val.cpp, tests/unit/sync_val_positive.cpp, tests/unit/sync_val_semaphore.cpp, tests/unit/sync_val_semaphore_positive.cpp, tests/unit/sync_val_wsi.cpp, tests/unit/sync_val_wsi_positive.cpp, tests/unit/wsi.cpp, tests/unit/wsi_positive.cpp
This unifies submit helpers so functions that work with timeline semaphores do not need distinctive names.
Also makes it more visible if semaphore describes wait or signal.
=> tests: Update submit helpers

scripts/generate_source.py
Update json.in files as strings instead of round-tripping through the python json module. The old way implicitly formats the file and adds a lot of vertical whitespace that makes these hard to edit by hand.
=> scripts: Don't reformat json on gen

layers/gpu/cmd_validation/gpuav_copy_buffer_to_image.cpp, layers/gpu/core/gpuav_setup.cpp, layers/gpu/debug_printf/debug_printf.cpp, layers/gpu/descriptor_validation/gpuav_descriptor_set.cpp, layers/gpu/descriptor_validation/gpuav_descriptor_validation.cpp, layers/gpu/instrumentation/gpuav_instrumentation.cpp, layers/gpu/resources/gpuav_resources.cpp, layers/gpu/resources/gpuav_resources.h, layers/gpu/resources/gpuav_subclasses.cpp, layers/gpu/resources/gpuav_subclasses.h
- no public member in DeviceMemoryBlock
=> either everything public or nothing
- MapMemory simply returns a void* pointer
=> Just as the test framework. This pointer is immediately cast to appropriate type. Thought about using a template method to specify the type, but a simple manual cast is probably better here
=> gpu: Cleanup in DeviceMemoryBlock

tests/framework/ray_tracing_objects.cpp, tests/framework/ray_tracing_objects.h, tests/unit/debug_printf_ray_tracing.cpp, tests/unit/gpu_av_ray_query_positive.cpp, tests/unit/gpu_av_ray_tracing_positive.cpp
part of https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/8562
Main new test: `NegativeDebugPrintfRayTracing, OneMultiEntryPointsShader2`
"Complex" ray tracing tests, involving 2 cubes, 2 ray generation shaders, 2 miss shaders, and 2 closest hit shaders. Rays are traced in various ways to invoke precise shaders.
I wrote the shader code in slang, to have one shader with multiple entry points.
=> printf: Ray tracing tests

layers/sync/sync_commandbuffer.cpp, layers/sync/sync_commandbuffer.h, layers/sync/sync_common.cpp, layers/sync/sync_common.h, layers/sync/sync_validation.cpp, tests/unit/sync_val_positive.cpp
Validation of ranges that depend on the values of indirect buffer requires shader instrumentation support or injection of additional commands that read the content of indirect buffers just before the draw (similar to descriptors). Disable corresponding functionality that tried to do its best (validated entire range) since it causes false-positives.
Closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/8664, https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/8502.
~~Also potentially addresses https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/3605.~~
Pretty sure if closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/3605 too because that test uses indirect action command, will additionally notify authors.
=> sync: Disable validation of ranges defined by indirect buffer

tests/framework/render.cpp, tests/framework/render.h, tests/framework/shader_helper.cpp, tests/framework/shader_helper.h, tests/framework/test_framework.cpp, tests/framework/test_framework.h, tests/unit/debug_printf.cpp, tests/unit/gpu_av_buffer_device_address.cpp, tests/unit/pipeline.cpp, tests/unit/shader_object.cpp, tests/unit/shader_spirv.cpp
We use to have 2 different workflows to parse the GLSL into SPIR-V for tests (Android used shaderc)
We (over a year ago) unified all of that, in the process we left behind a lot of old shader code
We have had all these ways to configure glsl with `.conf` files and other flows that I have never once used (and I have added most of the shader validation tests)
The PR removes unused workflows so we can add new ones we care about (like adding `-g` or `-gVS` to have glslang print out debug info and test if it is providing that information in GPU-AV tests)
=> test: Cleanup shader helper

layers/gpu/spirv/bindless_descriptor_pass.h, layers/gpu/spirv/buffer_device_address_pass.h, layers/gpu/spirv/debug_printf_pass.h, layers/gpu/spirv/inject_conditional_function_pass.h, layers/gpu/spirv/inject_function_pass.h, layers/gpu/spirv/non_bindless_oob_buffer_pass.h, layers/gpu/spirv/non_bindless_oob_texel_buffer_pass.h, layers/gpu/spirv/pass.h, layers/gpu/spirv/ray_query_pass.h
They are never used through their base class,
so might as well remove the added complexity
=> gpuav: Devirtualize Run and PrintDebugInfo

layers/sync/sync_access_context.cpp, layers/sync/sync_access_state.cpp, layers/sync/sync_common.cpp, layers/sync/sync_common.h, layers/sync/sync_op.h, layers/sync/sync_validation.cpp, layers/sync/sync_validation.h, layers/sync/sync_vuid_maps.cpp
Checking some `clangd` logs and noticed these sync files had some unused headers
=> sync: Cleanup of headers

layers/gpu/instrumentation/gpuav_shader_instrumentor.cpp, layers/gpu/spirv/debug_printf_pass.cpp, tests/unit/debug_printf_shader_debug_info.cpp, tests/unit/gpu_av_shader_debug_info.cpp
Adds support for [Non-Semantic Shader Debug Info](https://htmlpreview.github.io/?https://github.com/KhronosGroup/SPIRV-Registry/blob/main/nonsemantic/NonSemantic.Shader.DebugInfo.100.html) so that GPU-AV (and verbose DebugPrintf) can provide the exact source line that caused the error
`NonSemantic.Shader.DebugInfo` is a successor of the original `OpLine`/`OpSource`
This adds a lot of tests to help confirm coverage as well
=> gpu: Add ShaderDebugInfo in error message

BUILD.gn, layers/CMakeLists.txt, layers/error_message/spirv_logging.cpp, layers/error_message/spirv_logging.h, layers/gpu/debug_printf/debug_printf.cpp, layers/gpu/instrumentation/gpuav_instrumentation.cpp, layers/gpu/instrumentation/gpuav_shader_instrumentor.cpp, layers/gpu/instrumentation/gpuav_shader_instrumentor.h, layers/gpu/spirv/instruction.cpp, layers/gpu/spirv/instruction.h, layers/state_tracker/shader_instruction.cpp, layers/state_tracker/shader_instruction.h
I recently added ShaderDebugInfo in error message for GPU-AV https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/8691
There are **many** normal core validation error messages that also should have source code printed in the error message
I have a follow-up PR to do it for some VUs, but want to get this in first which is just splitting the GPU-AV logging code for SPIR-V into a dedicated `spirv_logging` helper file
=> Add a common spirv_logging.cpp helper

layers/gpu/debug_printf/debug_printf.cpp, tests/unit/debug_printf.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/8656
Adds 64-int support using `%ld` 
We had ability to support it, just were not parsing it correctly (or attempted at all)
=> printf: Add Signed Int64 support

layers/core_checks/cc_spirv.cpp, layers/error_message/spirv_logging.cpp, layers/error_message/spirv_logging.h, layers/gpu/instrumentation/gpuav_shader_instrumentor.cpp, layers/state_tracker/shader_module.cpp, layers/state_tracker/shader_module.h, tests/unit/atomics.cpp, tests/unit/gpu_av_shader_debug_info.cpp
Follow up of https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/8691
If users have debug information in their shader, will print source information (just added for Atomic VUs, will add rest after)
Before
```
Validation Error: [ VUID-RuntimeSpirv-None-06284 ] | MessageID = 0x6b26b332 | vkCreateShaderModule():  SPIR-V is using float atomics operations
%22 = OpAtomicLoad %8 %21 %14 %19
with StorageBuffer storage class, but none of the required features were enabled.
```
now :rocket: 
```
Validation Error: [ VUID-RuntimeSpirv-None-06284 ] | MessageID = 0x6b26b332 | vkCreateShaderModule():  SPIR-V is using float atomics operations with StorageBuffer storage class, but none of the required features were enabled.
%57 = OpAtomicLoad %31 %56 %47 %49
From shader debug information: in file …
```
=> layers: Add Shader Debug Info into core validation

.github/workflows/vvl.yml
> The macOS 12 runner image will be removed by December 3rd, 2024.
=> ci: Update MacOS to latest OS

layers/state_tracker/state_tracker.cpp
Inspired by https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/8689 which was confusing and time consuming.
The idea is that in-use tracking is not a GPU side system. Evaluate resource in-use status based on CPU side API usage pattern. Make GPU/driver errors a separate axis of error handling.
The problem with mixing these two types of errors handling is that it leads to confusion in practice. For example, if the application is correctly structured to handle resource lifetimes or image layouts transition, but it did poor job with handling VkResult, and the error message reports that resource is still in use (but we just called vkDeviceWaitIdle!) or layout is incorrect when all transitions are properly specified. This misleading messages can focus attention on the wrong area …
=> layers: Break dependency of in-use tracking on GPU state

docs/limitations.md, layers/object_tracker/object_tracker_utils.cpp, layers/state_tracker/state_tracker.cpp, layers/vulkan/generated/chassis.cpp, layers/vulkan/generated/chassis.h, scripts/generators/layer_chassis_generator.py, tests/unit/shader_spirv.cpp
Helps addresses https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/8618
Note - still requires `VK_LAYER_DISABLES=VK_VALIDATION_FEATURE_DISABLE_UNIQUE_HANDLES_EXT` as need to still find a way to not have the handle wrapping blowup on us
=> layers: Add atexit to safely tear down layers

BUILD.gn, layers/CMakeLists.txt, layers/core_checks/cc_state_tracker.cpp, layers/core_checks/cc_state_tracker.h, layers/core_checks/cc_submit.cpp, layers/core_checks/cc_submit.h, layers/core_checks/core_validation.h, layers/state_tracker/state_tracker.cpp, tests/unit/sync_object.cpp, tests/unit/sync_object_positive.cpp
This introduces new type of submit validation (will see how it flies) and it is done and reported by the Queue threads. This should be taken into account by the tests. During QueueSubmit call no error might be reported when validation is performed by the Queue thread. `VerifyFound` should be put after device/queue `Wait` which guarantees that Queue thread finished its job.
=> layers: Validate monotonic increase of timeline values

layers/best_practices/bp_pipeline.cpp, layers/core_checks/cc_android.cpp, layers/core_checks/cc_device_generated_commands.cpp, layers/core_checks/cc_external_object.cpp, layers/core_checks/cc_pipeline_graphics.cpp, layers/core_checks/cc_ray_tracing.cpp, layers/core_checks/cc_render_pass.cpp, layers/state_tracker/device_memory_state.cpp, layers/stateless/sl_descriptor.cpp, layers/stateless/sl_instance_device.cpp, layers/stateless/sl_wsi.cpp, tests/unit/copy_buffer_image.cpp, tests/unit/image_positive.cpp, tests/unit/protected_memory.cpp, tests/unit/ray_tracing_pipeline_nv.cpp, tests/unit/video.cpp
as @arno-lunarg pointed out in https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/8720#discussion_r1808412232
the spec goes `the pNext **element**` or `the pNext **chain**`
when through and found all `the pNext` missing that wording
=> layers: Fix the pNext wording

layers/gpu/error_message/gpuav_vuids.cpp, layers/gpu/error_message/gpuav_vuids.h, layers/gpu/instrumentation/gpuav_instrumentation.cpp, tests/unit/gpu_av_descriptor_indexing.cpp, tests/unit/gpu_av_oob.cpp
This was added back in 1.3.292 from https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/6793
Adds the `VUID-vkCmdDraw-None-10068` draw time VU for having a descriptor index out of bounds
=> gpu: Add new VUID label of Index OOB

layers/core_checks/cc_synchronization.cpp, layers/state_tracker/queue_state.cpp, layers/state_tracker/queue_state.h, layers/state_tracker/semaphore_state.cpp, layers/state_tracker/semaphore_state.h, tests/framework/binding.cpp, tests/framework/binding.h, tests/unit/sync_object.cpp, tests/unit/wsi.cpp
~This partially~ addresses https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/8707
What's left for other PRs:
* Provide different messages depending on which condition triggered VUs like `VUID-vkQueueSubmit-pWaitSemaphores-03238`: either missing binary signal or binary signal exists but depends on timeline wait.
* ~Try to analyze entire synchronization chain, not only direct parent.~ - actually this works, added one more test to show this `NegativeSyncObject.BinarySyncDependsOnTimelineWait3`.
=> layers: Validate binary sync depenency on timeline wait

layers/gpu/cmd_validation/gpuav_draw.cpp, layers/gpu/error_message/gpuav_vuids.cpp, layers/gpu/error_message/gpuav_vuids.h, tests/unit/gpu_av_indirect_buffer.cpp
These VUID will be removed in the next header update (https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/6969)
Was discussed in https://gitlab.khronos.org/vulkan/vulkan/-/issues/3991 that these VUs were not possible to hit if your `maxDrawCount` is within range of the buffer.
We decided to keep this check, but demote it to a warning for now
=> gpu: Demote DrawCount capped by maxDrawCount to warning

layers/stateless/sl_image.cpp, layers/stateless/stateless_validation.h, tests/unit/gpu_av.cpp, tests/unit/image.cpp, tests/unit/image_positive.cpp, tests/unit/instance_positive.cpp, tests/unit/sampler.cpp, tests/unit/ycbcr.cpp, tests/unit/ycbcr_positive.cpp
The main goal was to add the [spec change](https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/6774) from 1.3.291 that added `VUID-VkImageCreateInfo-pNext-10062`
In process I cleaned up some YCbCr and Stateless CreateImage code
=>  layers: Add MultiPlanar FormatList

scripts/generate_spec_error_message.py
=> scripts: Fix UTF8 with ASCII values

tests/framework/layer_validation_tests.h, tests/unit/copy_buffer_image.cpp, tests/unit/image.cpp, tests/unit/memory.cpp, tests/unit/sampler.cpp, tests/unit/sync_val.cpp, tests/unit/ycbcr.cpp, tests/unit/ycbcr_positive.cpp
- Removes `AddOptionalExtensions(VK_KHR_SAMPLER_YCBCR_CONVERSION_EXTENSION_NAME);` in favor for a Multi-Plane version of tests
- Remove `InitBasicYcbcr` to use new enable feature/extensions (this extension loooooog ago was the worst because it had so many requirements and didn't have codegen yet)
- remove `_KHR` suffix where not needed
=> tests: Cleanup MultiPlane and YCbCr tests

tests/unit/sync_object.cpp, tests/unit/sync_object_positive.cpp
This test failed for me on CI so I removed it. The comment in the test suggests it failed before too, so less troubles for everyone.
That's correct but not a real reason. It's incorrect to do this according: `VUID-vkSetEvent-event-09543`
Seemingly we don't have VUID-vkSetEvent-event-09543 implemented fully.
more spec notes:
> If a command buffer is waiting for an event to be signaled from the host, the application must signal the event before submitting the command buffer, as described in the [queue forward progress](https://registry.khronos.org/vulkan/specs/1.3-extensions/html/vkspec.html#commandbuffers-submission-progress) section.
> Since the original users of this functionality were highly limited and platform-specific, this functionality is now considered defunct and should not be …
=> tests: Remove incorrect event test

layers/core_checks/cc_device_generated_commands.cpp
`VUID-VkGeneratedCommandsInfoEXT-indirectCommandsLayout-10241` was added in the 1.3.300 spec
=> layers: Add VUID label from 300 headers

layers/core_checks/cc_external_object.cpp, layers/core_checks/cc_synchronization.cpp, layers/state_tracker/queue_state.cpp, layers/state_tracker/queue_state.h, layers/state_tracker/semaphore_state.cpp, layers/state_tracker/semaphore_state.h, tests/unit/external_memory_sync.cpp
Follow-up to https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/8739
VUs like `VUID-vkQueueSubmit2-semaphore-03873` validate binary wait by checking two conditions:
* there is a signal
* signal does not depend on not submitted signal
Existing message covers the first condition. This PR provides a separate message for the second condition.
Also provided additional test for external semaphore `VUID-VkSemaphoreGetFdInfoKHR-handleType-03254`, other VUs are tested by https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/8739
> Validation Error: [ VUID-VkSemaphoreGetFdInfoKHR-handleType-03254 ] Object 0: handle = 0xf56c9b0000000004, type = VK_OBJECT_TYPE_SEMAPHORE; Object 1: handle = 0xe7f79a0000000005, type = VK_OBJECT_TYPE_SEMAPHORE; | MessageID = 0x6b4a4728 | …
=> layers: Add error message for binary signal dependency

tests/device_profiles/max_profile.json, tests/unit/arm_best_practices.cpp, tests/unit/atomics.cpp, tests/unit/buffer.cpp, tests/unit/buffer_positive.cpp, tests/unit/command.cpp, tests/unit/copy_buffer_image.cpp, tests/unit/copy_buffer_image_positive.cpp, tests/unit/dynamic_state.cpp, tests/unit/geometry_tessellation.cpp, tests/unit/gpu_av.cpp, tests/unit/graphics_library.cpp, tests/unit/image.cpp, tests/unit/image_drm.cpp, tests/unit/other_positive.cpp, tests/unit/pipeline.cpp, tests/unit/pipeline_topology_positive.cpp, tests/unit/push_descriptor.cpp, tests/unit/ray_tracing_pipeline_positive.cpp, tests/unit/sampler.cpp, tests/unit/sampler_positive.cpp, tests/unit/shader_object.cpp, tests/unit/shader_spirv_positive.cpp, tests/unit/shader_storage_image.cpp, tests/unit/sparse_image.cpp, tests/unit/subgroups.cpp, tests/unit/subpass.cpp, tests/unit/sync_object.cpp, tests/unit/wsi.cpp, tests/unit/ycbcr.cpp
We have some `GetPhysicalDeviceFeatures` after we merged in https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/8687
=> tests: Remove unused GetPhysicalDeviceFeatures

layers/core_checks/cc_copy_blit_resolve.cpp, layers/core_checks/cc_pipeline.cpp, layers/core_checks/core_validation.h, layers/stateless/sl_pipeline.cpp, layers/stateless/stateless_validation.h, layers/vulkan/generated/stateless_validation_helper.cpp, scripts/generators/stateless_validation_helper_generator.py
Pulling out the cleanup code from https://gitlab.khronos.org/vulkan/Vulkan-ValidationLayers/-/merge_requests/107 to have in now and make that PR cleaner in the future
=> layers: Cleanup prior to extension release

layers/core_checks/cc_device_generated_commands.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/8773
I mixed up `supportedIndirectCommandsShaderStagesPipelineBinding` with `supportedIndirectCommandsShaderStagesShaderBinding` here
=> layers: Fix DGC supportedIndirectCommandsShaderStagesPipelineBinding

layers/core_checks/cc_cmd_buffer_dynamic.cpp, tests/unit/shader_object.cpp
Changes in upcoming 1.3.301 header https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/6976
Uses feature bits instead of extensions to check for drawtime dynamic state VUs
=> layers: Replace Line extension with feature bit check

layers/core_checks/cc_copy_blit_resolve.cpp, layers/stateless/sl_image.cpp, tests/unit/host_image_copy.cpp
for future 1.3.301 header - https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/6982
Move the `hostImageCopy` to image creation time
cc @ziga-lunarg (since you caught this)
=> layers: Move hostImageCopy feature check to image

layers/core_checks/cc_cmd_buffer_dynamic.cpp, tests/unit/shader_object.cpp, tests/unit/shader_object_positive.cpp
For future header fix in https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/6981
prevents you to draw with shader object with tessellation without setting `VK_PRIMITIVE_TOPOLOGY_PATCH_LIST`
cc @ziga-lunarg who caught this
=> layers: Add ShaderObject Tess Topology draw VU

layers/state_tracker/state_tracker.cpp, layers/vulkan/generated/chassis.cpp, scripts/generators/layer_chassis_generator.py, tests/framework/binding.cpp, tests/framework/binding.h, tests/framework/render.cpp, tests/framework/render.h, tests/unit/amd_best_practices.cpp, tests/unit/sync_object_positive.cpp, tests/unit/wsi.cpp, tests/unit/wsi_positive.cpp
Closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/8753
The issue was caused by presenting multiple swapchains with a single `QueuePresent` command. If one presentation failed, state tracking was disabled for all swapchains, even those without presentation errors. This led to false positives for "good" swapchains that had no presentation issues. This problem occurred when the optional `VkPresentInfoKHR::pResults` was not specified.
=> layers: Ensure QueuePresent has access to per-swapchain results

layers/core_checks/cc_wsi.cpp, layers/core_checks/core_validation.h, layers/state_tracker/image_state.cpp, tests/unit/wsi_positive.cpp
Closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/8772
Also move all image extent checks to `ValidateSwapchainImageExtent`.
=> layers: Fix wsi image extent caching

layers/core_checks/cc_render_pass.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/8788
=> layers: Check VK_ATTACHMENT_UNUSED 09353

layers/core_checks/cc_video.cpp, tests/unit/video.cpp, tests/unit/video_positive.cpp
In Vulkan 1.3.299, VkVideoEncodeRateControlInfoKHR VU 08358 was updated to allow initialVirtualBufferSizeInMs to equal virtualBufferSizeInMs.
Also add a positive test case for this.
=> layers: Revise VU 08358 to include equality

layers/core_checks/cc_wsi.cpp, layers/state_tracker/image_state.cpp, layers/state_tracker/image_state.h
Replaces yesterday's fix (https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/8789) with a different one (so the same tests).
Why better:
- Simpler then yesterday's fix (no need to sync between two groups)
- Potentially fixes most blacklisted Android WSI tests. Big if true. (according to my experiments  https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/8792 there's a chance, but need to test with current changes).
- Potentially solves a problem raised by Ralph or at least handles additional cases (failures of our Android WSI is likely one of the manifestation of the problem): https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/8321
=> layers: Better surface caps caching

tests/framework/layer_validation_tests.h, tests/unit/wsi.cpp, tests/unit/wsi_positive.cpp
Crash on the system where the first physical device is AMD GPU and the second one NVIDIA GPU.
=> tests: Fix crash on some multi gpu configurations

layers/layer_options.cpp
Small change to add nullptr check for pApplicationName to avoid crashes at string assignment for display_application_name setting.
=> layers: Check null pApplicationName

layers/sync/sync_commandbuffer.cpp, layers/sync/sync_commandbuffer.h, layers/sync/sync_common.h, layers/sync/sync_op.cpp, layers/sync/sync_submit.cpp, tests/unit/sync_val.cpp
Outputs this:
> Validation Error: [ SYNC-HAZARD-WRITE-AFTER-WRITE ] Object 0: handle = 0x1582da52030, type = VK_OBJECT_TYPE_COMMAND_BUFFER; Object 1: handle = 0xf443490000000006, type = VK_OBJECT_TYPE_BUFFER; | MessageID = 0x5c0ec5d6 | vkCmdCopyBuffer():  Hazard WRITE_AFTER_WRITE for dstBuffer VkBuffer 0xf443490000000006[], region 0. Access info (usage: SYNC_COPY_TRANSFER_WRITE, prior_usage: SYNC_COPY_TRANSFER_WRITE, write_barriers: **SYNC_ALL_COMMANDS_SHADER_READ**, command: vkCmdCopyBuffer, seq_no: 1, reset_no: 1, resource: VkBuffer 0xf443490000000006[]).
Instead of this:
> Validation Error: [ SYNC-HAZARD-WRITE-AFTER-WRITE ] Object 0: handle = 0x15232b73f60, type = VK_OBJECT_TYPE_COMMAND_BUFFER; Object 1: handle = 0xf443490000000006, type = VK_OBJECT_TYPE_BUFFER; | MessageID = …
=> sync: Add compact output for ALL reads

layers/gpu/instrumentation/gpuav_shader_instrumentor.cpp, layers/gpu/instrumentation/gpuav_shader_instrumentor.h, tests/unit/debug_printf.cpp, tests/unit/gpu_av_oob.cpp, tests/unit/gpu_av_positive.cpp
See inline comments, we can't use `VK_DESCRIPTOR_TYPE_STORAGE_BUFFER_DYNAMIC` with `vkCreateIndirectExecutionSetEXT` but it "seems to work" for people (because we are not actually touching those descriptors in the `vkCmdExecuteGeneratedCommandsEXT` currently - https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/8605)
so for now, report an error, but let run incase it might still work
=> gpu: Give error if using IES with GPU-AV

layers/state_tracker/cmd_buffer_state.cpp, layers/sync/sync_submit.cpp, layers/sync/sync_submit.h, tests/unit/sync_val_reporting.cpp
Don't need this after timelines support was added.
Removes temporary solution https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/7504
=> sync: Remove debug labels todo

tests/unit/gpu_av.cpp, tests/unit/gpu_av_shader_debug_info.cpp
Went through disabled GPU-AV tests and found some that are working now! (due to recent cleanup/fixes in the code)
=> tests: Re-Enable tests that are working now

layers/core_checks/cc_descriptor.cpp, layers/drawdispatch/descriptor_validator.cpp, layers/drawdispatch/descriptor_validator.h, layers/gpu/descriptor_validation/gpuav_descriptor_set.cpp, layers/gpu/descriptor_validation/gpuav_descriptor_validation.cpp, layers/gpu/resources/gpuav_shader_resources.h, layers/state_tracker/descriptor_sets.cpp, layers/state_tracker/descriptor_sets.h
Two small commits to improve the usage of `DescriptorClass`
Main thing is removing the `default` in the switch cases so it is easier to see which descriptors are covered or not in various spots
=> gpu: Cleanup DescriptorClass usage

layers/drawdispatch/descriptor_validator.cpp, layers/drawdispatch/descriptor_validator.h, layers/gpu/descriptor_validation/gpuav_descriptor_set.cpp, layers/gpu/descriptor_validation/gpuav_descriptor_set.h, layers/state_tracker/descriptor_sets.cpp, layers/state_tracker/descriptor_sets.h
Broken into commits, main goal was 
Remove the `#include <state_tracker.h>` from the `descriptor_validator.h` header
=> Remove including state tracker in header 

layers/vulkan/generated/layer_chassis_dispatch.cpp, scripts/generators/layer_chassis_dispatch_generator.py
Most of these can be replaced directly with small_vector<>. But, deferred operations still require use of raw pointers so that clean up can be ... deferred.
=> scripts: Remove most raw new/deletes from handle wrapping

layers/core_checks/cc_descriptor.cpp, layers/core_checks/core_validation.h, layers/state_tracker/descriptor_sets.h, layers/utils/vk_struct_compare.cpp, layers/utils/vk_struct_compare.h, tests/unit/descriptors.cpp, tests/unit/descriptors_positive.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/8497
Add exception to check the `VkSamplerCreateInfo` of 2 `pImmutableSamplers` to see if they are the same for Descriptor Set Layout Compatibility
=> layers: Fix VerifySetLayoutCompatibility for Samplers

tests/unit/graphics_library_positive.cpp
Running these tests with the cache off will fail because the `VkPipeline` is null and invalid
It is hard to properly test things that reply on the driver's pipeline cache, so for these tests, on the first run it will skip and second time will run as expected
=> tests: Add pipeline cache result checks to tests

layers/core_checks/cc_descriptor.cpp, tests/unit/debug_printf.cpp, tests/unit/gpu_av_positive.cpp
Inline Uniform Buffers don't have anyway to be OOB (pending https://gitlab.khronos.org/vulkan/vulkan/-/issues/4083) so the only thing we "could" do is check if the value you are reading from was not updated, and give a warning the data was uninitialized... but for now, added tests to make sure we don't generate false positive for Inline Uniform Buffers
=> tests: Add inline uniform buffer for GPU-AV

layers/gpu/instrumentation/gpuav_shader_instrumentor.cpp, layers/gpu/instrumentation/gpuav_shader_instrumentor.h
- Remove VK_PIPELINE_CREATE_FAIL_ON_PIPELINE_COMPILE_REQUIRED_BIT from instrumented pipeline libray
GPU-AV needs to succeed in creating them no matter driver cache state
- Renaming for clarification
=> gpuav: Fix handling of PIPELINE_COMPILE_REQUIRED

layers/sync/sync_access_context.cpp, layers/sync/sync_access_context.h, layers/sync/sync_commandbuffer.cpp, layers/sync/sync_submit.cpp, layers/sync/sync_validation.cpp, tests/unit/sync_val_reporting.cpp
Similar to https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/8222 but for images.
Closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/8139
> [ SYNC-HAZARD-WRITE-AFTER-READ ] Object 0: handle = 0x213dbe93750, type = VK_OBJECT_TYPE_QUEUE; | MessageID = 0x376bc9df | vkQueueSubmit():  Hazard WRITE_AFTER_READ for entry 0, VkCommandBuffer 0x213e8443680[], Submitted access info (submitted_usage: SYNC_COPY_TRANSFER_WRITE, command: vkCmdCopyBufferToImage, seq_no: 1, reset_no: 1, resource: VkImage 0xf443490000000006[ImageB]). Access info (prior_usage: SYNC_COPY_TRANSFER_READ, read_barriers: VkPipelineStageFlags2(0), queue: VkQueue 0x213dbe93750[], submit: 2, batch: 0, batch_tag: 5, command: vkCmdCopyImage, command_buffer: VkCommandBuffer 0x213e8435de0[], seq_no: 1, …
=> sync: Report image resources during submit time validation

layers/VkLayer_khronos_validation.json.in, layers/layer_options.cpp, layers/sync/sync_reporting.cpp, layers/sync/sync_settings.h, layers/sync/sync_submit.cpp, tests/unit/sync_val_positive.cpp
Closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/7491
Debug/internal information is not reported by default now.
There might be more tweaks before the next SDK what should be put into this category.
=> sync: Add setting to report debug information

layers/sync/sync_commandbuffer.cpp, layers/sync/sync_commandbuffer.h, layers/sync/sync_common.h, layers/sync/sync_renderpass.cpp, layers/sync/sync_renderpass.h, layers/sync/sync_reporting.cpp, layers/sync/sync_reporting.h, layers/sync/sync_submit.cpp
* Use formatting functions instead of operators. It was hard to search the code with operators.
* Move more code to `sync_reporting`
* Remove `SyncValidationInfo` type. Did not bring much value, currently use `CommandExecutionContext` instead (which might also be modified to show responsibilities better).
* Use `CommandBufferAccessContext` directly instead of base `CommandExecutionContext ` when type is statically known.
* Use reference instead of pointer for `CommandExecutionContext::sync_state_`.
=> sync: Mics cleanup of reporting code

layers/sync/sync_commandbuffer.h, layers/sync/sync_op.cpp, layers/sync/sync_op.h, layers/sync/sync_submit.h, layers/sync/sync_validation.cpp
Only primary command buffers can begin/end render pass.
This simplifies design by removing dynamic dispatch and shows explicitly that operations are applicable only to `QueueBatchContext`.
=> sync: Devirtualize renderpass replay

layers/stateless/sl_pipeline.cpp, layers/stateless/stateless_validation.h, layers/vulkan/generated/stateless_validation_helper.cpp, scripts/generators/stateless_validation_helper_generator.py, tests/unit/shader_spirv.cpp
seems `VUID-vkCreateShaderModule-pCreateInfo-06904` was missing
It is, yet-another, except around pNext checking so need to do it explicitly
=> layers: Add pNext check for vkCreateShaderModule

layers/core_checks/cc_spirv.cpp, layers/core_checks/cc_vuid_maps.cpp, layers/core_checks/cc_vuid_maps.h, tests/unit/pipeline_layout.cpp
From https://gitlab.khronos.org/vulkan/vulkan/-/issues/4083
Add check to prevent having an array of descriptor when using `VK_DESCRIPTOR_TYPE_INLINE_UNIFORM_BLOCK`
=> layers: Add Array check for Inline Uniform Blocks

layers/drawdispatch/descriptor_validator.cpp, layers/gpu/descriptor_validation/gpuav_descriptor_set.cpp, layers/gpu/shaders/gpuav_shaders_constants.h, layers/gpu/shaders/instrumentation/post_process_descriptor_index.comp, tests/unit/descriptors.cpp, tests/unit/gpu_av.cpp, tests/unit/gpu_av_descriptor_indexing.cpp, tests/unit/gpu_av_positive.cpp, tests/unit/shader_image_access.cpp, tests/unit/ycbcr.cpp
We had some disabled tests for GPU-AV because it was getting through `DescriptorValidator::ValidateDescriptor()` correctly.
The core issue is we ignore things when we don't know the index into an array on the CPU, but that can be ignored post process in GPU-AV because we are passing in the index
Added various tests to help with coverage
=> gpu: Fix Sampler array checks

layers/core_checks/cc_wsi.cpp
Minor fix to a couple format strings in WSI validation. Extraneous `%s` in the stringstream output would result in messages like:
```
pCreateInfo->preTransform is not supported, support values are:
VK_SURFACE_TRANSFORM_IDENTITY_BIT_KHR%s
. The Vulkan spec states: ...
```
=> layers: Fix message formatting in WSI validation

tests/framework/barrier_queue_family.cpp, tests/framework/binding.cpp, tests/framework/binding.h, tests/unit/sync_object.cpp
There is validation but not the tests for:
VUID-VkBufferMemoryBarrier-None-09049
VUID-VkImageMemoryBarrier-None-09052
=> tests: Add ownership transfer tests for 09049 and 09052

layers/core_checks/cc_synchronization.cpp, layers/core_checks/core_validation.h, layers/sync/sync_vuid_maps.cpp, layers/sync/sync_vuid_maps.h, tests/unit/sync_object.cpp
This removes `ValidatorState` ownership transfer helper. It was mostly additional abstraction layer that copied local variables and the result was stored as another local variable.
Also replaced `VUID-vkQueueSubmit-pSubmits-04626` with unassigned VUID when resource is EXCLUSIVE. 04626 is only about checking CONCURRENT resource properties. It also checks resource itself but not a barrier properties which is needed in unassigned VUID.
Unassigned VUID is about this requirement from `7.7.4. Queue Family Ownership Transfer`:
> The srcQueueFamilyIndex parameter of the barrier must be the source queue family index, and the dstQueueFamilyIndex parameter to the destination queue family index.
Opened gitlab issue: https://gitlab.khronos.org/vulkan/vulkan/-/issues/4092. Will open a MR too.
=> layers: Fix and cleanup ownership transfer code

layers/core_checks/cc_synchronization.cpp, layers/core_checks/core_validation.h, tests/unit/sync_object.cpp
Tobias's **second** comment here https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/5799#note_403058 is very useful. Indeed we can move validation to command buffer recording.
Also here's proposal to define unassigned queue family VUs: https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/7029
=> layers: Move queue family validation from submit to record

layers/core_checks/cc_synchronization.cpp, layers/state_tracker/fence_state.cpp, layers/state_tracker/fence_state.h, layers/state_tracker/semaphore_state.cpp, layers/state_tracker/semaphore_state.h, tests/unit/object_lifetime.cpp
Closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/8745
before: fence can't be called on VkFence that is in use by VkFence 🥹
> Validation Error: [ VUID-vkDestroyFence-fence-01120 ] | MessageID = 0x5d296248 | vkDestroyFence(): fence can't be called on VkFence 0xf56c9b0000000004[] that is currently in use by VkFence 0xf56c9b0000000004[].
The Vulkan spec states: All queue submission commands that refer to fence must have completed execution (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-vkDestroyFence-fence-01120)
after fix:
> Validation Error: [ VUID-vkDestroyFence-fence-01120 ] | MessageID = 0x5d296248 | vkDestroyFence():  can't be called on VkFence 0xf56c9b0000000004[] that is currently in use by VkQueue 0x25822fafa70[].
The Vulkan …
=> layers: Fix in-use message for fence and semaphore

tests/unit/debug_printf.cpp
This test would fail if the implementation does not support VK_EXT_multi_draw
=> tests: Fix enabling extensions in multi draw test

layers/chassis/layer_chassis_dispatch_manual.cpp, layers/core_checks/cc_wsi.cpp, layers/gpu/core/gpuav_setup.cpp, layers/gpu/instrumentation/gpuav_shader_instrumentor.cpp, layers/state_tracker/state_tracker.cpp, layers/thread_tracker/thread_safety_validation.h, layers/vulkan/generated/chassis.cpp, layers/vulkan/generated/chassis.h, layers/vulkan/generated/chassis_dispatch_helper.h, layers/vulkan/generated/layer_chassis_dispatch.cpp, layers/vulkan/generated/layer_chassis_dispatch.h, scripts/generators/layer_chassis_dispatch_generator.py, scripts/generators/layer_chassis_generator.py
Previously, there were top level ValidationObjects stored in layer_data_map. These didn't do validation but contained more ValidationObjects in the object_dispatch vector (and a few others).
This caused much confusion, since some members were only used at the top level and others only at the lower level.  When uses got mixed up, this could only be detected at runtime since the members were always available even though they might not be set up correctly.
Start to split this up by moving top level functionality to a new DispatchObject class. This does handle wrapping and coordination of validation by the child ValidationObjects. There are still many members related to settings, extension status, logging  and dispatch tables that are duplicated at both levels. Fixing this is a big change …
=> scripts: Start to refactor ValidationObject

layers/VkLayer_khronos_validation.json.in
While browsing/modifying this JSON file I spotted a glaring typo in the main layer description, and ended up fixing a few more in the settings descriptions down below.
=> settings: Fix minor typos in VkLayer_khronos_validation.json.in

layers/containers/subresource_adapter.h, layers/state_tracker/image_layout_map.cpp, layers/state_tracker/image_layout_map.h
There is no `SPARSE_CONTAINER_UNIT_TEST` or `vk_snippets.h` and I think this is just been left over from years of code churn
=> layers: Remove unused ifdef

layers/state_tracker/fence_state.cpp, layers/state_tracker/fence_state.h, layers/state_tracker/image_state.cpp, layers/state_tracker/image_state.h, layers/state_tracker/state_tracker.cpp, tests/unit/wsi_positive.cpp
`AcquireNextImage` does not necessarily use the same fence with a specific
swapchain image. The previous implementation made this (incorrect) assumption,
and this allowed to use Fence object as the owner of `AcquireFenceSync`.
A better solution is that Present call stores `AcquireFenceSync` in a
swapchain image. When swapchain image is re-acquired, it assigns
`AcquireFenceSync` to a Fence object, if any.
This also removes the need to handle a special case that swapchain can
be re-created, and in that case we had to invalidate `AcquireFenceSync`
stored inside Fence. Now Fence object is automatically associated
with correct swapchain.
Closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/8880
=> layers: Change ownership of AcquireFenceSync object

layers/containers/qfo_transfer.h, layers/core_checks/cc_synchronization.cpp, tests/unit/sync_object.cpp
This specifies proper VUIDs. I did not check if there are any issues with how corresponding validation is implemented (regarding CTS hitting this).
Initiated by https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/8902
=> layers: Replace unassigned VUIDs for ownership transfer

layers/stateless/sl_pipeline.cpp, layers/stateless/sl_shader_object.cpp, layers/stateless/stateless_validation.h, tests/framework/binding.h, tests/unit/shader_push_constants.cpp
Part of https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/8737
We were not validating `VkPushConstantRange` for Shader Objects before
=> layers: Add PushConstantRange check for ShaderObjects

layers/utils/hash_util.h
replacement for https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/8914
needed for LLVM 20
=> layers: Add string_view header

layers/best_practices/bp_drawdispatch.cpp, layers/core_checks/cc_drawdispatch.cpp, layers/gpu/cmd_validation/gpuav_cmd_validation_common.cpp, layers/gpu/descriptor_validation/gpuav_descriptor_validation.cpp, layers/gpu/instrumentation/gpuav_instrumentation.cpp, layers/state_tracker/cmd_buffer_state.cpp, layers/state_tracker/cmd_buffer_state.h, layers/state_tracker/pipeline_state.cpp, layers/state_tracker/pipeline_state.h, layers/sync/sync_commandbuffer.cpp
`LastBound::PER_SET` is not helpful name, changed to `DescriptorSetSlot`
also instead of going `last_bound.ds_slots[index].bound_descriptor_set` it is just `last_bound.ds_slots[index].ds_state` to try and reduce the `bound` being littered everything it doesn't need to be (since you are already actively grabbing `LastBound`)
=> layers: Rename LastBound::PER_SET

layers/core_checks/cc_cmd_buffer_dynamic.cpp, layers/core_checks/cc_device.cpp, layers/core_checks/cc_shader_interface.cpp, layers/core_checks/cc_shader_object.cpp, layers/core_checks/cc_spirv.cpp, layers/drawdispatch/drawdispatch_vuids.cpp, layers/drawdispatch/drawdispatch_vuids.h, layers/stateless/sl_instance_device.cpp, layers/stateless/sl_ray_tracing.cpp, scripts/generate_spec_error_message.py, tests/device_profiles/max_profile.json, tests/unit/device_feature_property.cpp, tests/unit/ray_tracing_positive.cpp, tests/unit/shader_object.cpp, tests/unit/vertex_input_positive.cpp
Fixes for
- VUID-vkCmdDraw-primitiveTopology-10286
- VUID-VkDeviceCreateInfo-robustBufferAccess-10247
- VUID-vkCreateShadersEXT-device-09669
also [VK_EXT_vertex_attribute_robustness](https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/6992)
- VUID-vkCmdDraw-Input-07939
- VUID-VkGraphicsPipelineCreateInfo-Input-07904
=> layers: 1.3.302 VU Churn

layers/core_checks/cc_descriptor.cpp, layers/core_checks/cc_drawdispatch.cpp, layers/core_checks/core_validation.h
Both Pipeline and ShaderObjects have copy and pasted code that is important so moved to a central `NeedDrawStateValidated` call for now
=> layers: Make common NeedDrawStateValidated function

layers/drawdispatch/descriptor_validator.cpp, layers/state_tracker/descriptor_sets.cpp, layers/state_tracker/descriptor_sets.h, tests/unit/gpu_av.cpp, tests/unit/gpu_av_positive.cpp, tests/unit/sampler.cpp
attempt 2 of https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/8879
(Added many test, which found more bugs :cry: but are tracking in https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/8922)
=> gpu: Reduce post processing already done on CPU

.github/workflows/vvl.yml, scripts/tests.py
The introduction of https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/8911 showed that we are running about an hour longer for the Thread Sanitizer tests because there is something causing each Video tests to slowly increase the time the test takes to run.
This is intended to be a quick fix until we have time to investigate more. This should reduce the test time from 2.5 hours back to under 1.5 hours
edit - the 2.5+ hour run now only takes 30 minutes!
=> ci: Skip Video tests for ThreadSanitizer

tests/framework/render.cpp, tests/framework/render.h, tests/unit/sync_object.cpp
Added missing sparse bindings tests as a follow-up to https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/8764.
With regard to https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/8900, one theory (suggested by @HansKristian-Work) is that it happens due to missing timeline support for sparse operations, but so far it looks like we  handle them properly. Likely the issue is in the general algorithm (or in another part of sparse functionality!).
=> tests: Test binary-timeline dependency with sparse ops

BUILD.gn, layers/CMakeLists.txt, layers/sync/sync_access_state.cpp, layers/sync/sync_access_state.h, layers/sync/sync_commandbuffer.cpp, layers/sync/sync_commandbuffer.h, layers/sync/sync_error_messages.cpp, layers/sync/sync_error_messages.h, layers/sync/sync_op.cpp, layers/sync/sync_renderpass.cpp, layers/sync/sync_renderpass.h, layers/sync/sync_submit.cpp, layers/sync/sync_validation.cpp, layers/sync/sync_validation.h
That's all syncval error messages that have different structure. More work is needed to classify this further.
The idea that this should simplify further work when it's in a single place (already this helped to detect some inconsistencies and opportunities to organize this better).
Additional progress on this might allow to filter error messages (as ANGLE does) in more reliable way. Currently ANGLE specifies multiple parts of the error message to identify specific use case. A potential improvement is to filter in a more structured way and to specify more stable values than just arbitrary text snippets.
Initial motivation behind the change is to minimize breaking changes for the clients that filter error messages based on current structure. Having this in a centralized place it should be …
=> sync: Categorize error messages

layers/gpu/cmd_validation/gpuav_copy_buffer_to_image.cpp, layers/gpu/cmd_validation/gpuav_dispatch.cpp, layers/gpu/cmd_validation/gpuav_draw.cpp, layers/gpu/cmd_validation/gpuav_trace_rays.cpp, layers/gpu/debug_printf/debug_printf.cpp, layers/gpu/instrumentation/gpuav_instrumentation.cpp, layers/gpu/instrumentation/gpuav_instrumentation.h, layers/gpu/instrumentation/gpuav_shader_instrumentor.cpp, layers/gpu/instrumentation/gpuav_shader_instrumentor.h, layers/gpu/resources/gpuav_state_trackers.cpp, layers/gpu/resources/gpuav_state_trackers.h, layers/state_tracker/cmd_buffer_state.cpp, layers/state_tracker/cmd_buffer_state.h, layers/state_tracker/queue_state.cpp, layers/state_tracker/queue_state.h, layers/state_tracker/state_tracker.cpp, tests/unit/debug_printf_shader_debug_info.cpp, tests/unit/gpu_av_shader_debug_info.cpp, tests/unit/sync_val_reporting.cpp
Took some of what Artem did for syncval
Add debug label regions for debug printf
Still need to add support for secondary command buffers, not so easy
EDIT: Updated PR to add support for debug label regions starting in one (primary) command buffer and ending in another following one. To do that I drew inspiration from sync val, but had to come up with my own (little) system, for GPU-AV has different constraints. I described the problem in a comment above this new `vvl::CommandBuffer` method: https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/19390298820aceb3881e9865f05eabdd27cecf41/layers/state_tracker/cmd_buffer_state.h#L710
EDIT 2: Reworked again to account for Artem's comments. Removed debug label region tracking from the `CommandBuffer` class, now it is tracked on a "per …
=> gpuav: Update debug label regions management

layers/state_tracker/queue_state.cpp, layers/state_tracker/semaphore_state.cpp, tests/unit/sync_object_positive.cpp
Closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/8900
=> layers: Fix detection of dependent timeline signal during binary wait

layers/core_checks/cc_copy_blit_resolve.cpp, layers/core_checks/core_validation.h
some clean up in the copy image/buffer code. Mainly reducing the number of loops through `pRegions` we had
=> layers: Reduce pRegions loops

layers/sync/sync_submit.cpp, layers/sync/sync_submit.h, layers/sync/sync_validation.cpp, layers/sync/sync_validation.h, tests/framework/binding.cpp, tests/framework/binding.h, tests/unit/sync_val_wsi_positive.cpp
Closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/8934
Syncval cleanups old access entries during host side synchronization
operations. For example, when frame synchronization uses `vkWaitForFences`
to wait for the QueueSubmit's fence, this guarantees that device memory
accesses are completed and it is safe to remove corresponding tracking
state.
There are synchronization mechanisms that are not associated directly
with a queue (acquire fence sync) and do not guarantee completion
of memory accesses (provide only execution dependency). In this case
we need to cleanup access entries when resource is destroyed, because
there is no guarantee they will be removed later.
=> sync: Remove access entries of destroyed resources

tests/unit/best_practices.cpp, tests/unit/command.cpp, tests/unit/command_positive.cpp, tests/unit/copy_buffer_image.cpp, tests/unit/descriptors.cpp, tests/unit/external_memory_sync.cpp, tests/unit/fragment_shading_rate.cpp, tests/unit/gpu_av_positive.cpp, tests/unit/host_image_copy.cpp, tests/unit/host_image_copy_positive.cpp, tests/unit/image.cpp, tests/unit/image_positive.cpp, tests/unit/imageless_framebuffer_positive.cpp, tests/unit/memory.cpp, tests/unit/memory_positive.cpp, tests/unit/multiview.cpp, tests/unit/object_lifetime.cpp, tests/unit/render_pass.cpp, tests/unit/render_pass_positive.cpp, tests/unit/sparse_image.cpp, tests/unit/sync_object_positive.cpp, tests/unit/sync_val.cpp, tests/unit/sync_val_positive.cpp, tests/unit/sync_val_wsi_positive.cpp, tests/unit/ycbcr.cpp, tests/unit/ycbcr_positive.cpp
Started as a way to clean up some tests in `copy_buffer_image.cpp` but figured I would just squash things from being copied and pasted in the future
=> tests: Cleanup copy image buffer tests

layers/core_checks/cc_copy_blit_resolve.cpp, layers/state_tracker/state_tracker.h
Some error messages were incorrect and this also unifies how we use `vkuFormatTexelBlockExtent`
=> layers: Fix TexelBlockExtent error messages

layers/core_checks/cc_image_layout.cpp, layers/gpu/descriptor_validation/gpuav_image_layout.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/8940 (well fixes the false positives for now)
=> layers: Don't validate external image layouts

layers/core_checks/cc_copy_blit_resolve.cpp, tests/unit/copy_buffer_image.cpp, tests/unit/copy_buffer_image_positive.cpp
1. Error messages didn't print which miplevel which was not helpful when missing and you suddenly have a smaller width/height then expected
2. Added some tests from related open issues
=> layers: Fix error message and new tests for copies

layers/gpu/descriptor_validation/gpuav_descriptor_set.cpp, layers/gpu/descriptor_validation/gpuav_descriptor_set.h, layers/state_tracker/descriptor_sets.cpp, layers/state_tracker/descriptor_sets.h
https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/8937 introduced a huge perf regression, the way around it is to just check the total Descriptor Count and if high, defer work to the GPU
=> gpu: Fix GPU-AV Perf Regression

layers/sync/sync_access_context.cpp, layers/sync/sync_access_context.h, layers/sync/sync_access_state.cpp, layers/sync/sync_access_state.h, layers/sync/sync_commandbuffer.cpp, layers/sync/sync_op.cpp, layers/sync/sync_renderpass.cpp
* Rename `ResourceAccessWriteState` to have symmetrical names: `WriteState` and `ReadState`
* Use named calls (instead of constructor) to construct `HazardResult` objects for better searchability: `HazardVsPriorWrite`, `HazardVsPriorRead`
=> sync: Access state cleanup

layers/gpu/spirv/buffer_device_address_pass.cpp, layers/gpu/spirv/buffer_device_address_pass.h, layers/gpu/spirv/instruction.cpp, layers/gpu/spirv/instruction.h, tests/unit/gpu_av_buffer_device_address.cpp, tests/unit/gpu_av_buffer_device_address_positive.cpp
Found out with Slang you can have a BDA reference not tied to a struct (https://godbolt.org/z/1eKesYaPW)
Currently we were not validating it, this adds logic to detect it as well as tests
=> gpu: Support Slang global BDA style pointers

tests/unit/memory.cpp, tests/unit/ycbcr.cpp
Vulkan SC downstreaming uncovered few missing extension enablements in tests.
=> tests: Missing extension enablements in tests

layers/core_checks/cc_copy_blit_resolve.cpp, layers/core_checks/cc_vuid_maps.cpp, layers/core_checks/cc_vuid_maps.h, layers/core_checks/core_validation.h, layers/state_tracker/state_tracker.h
This does a lot of things around the Copy Buffer/Image code
1. Reduce places we loop the `pRegion`
2. Keep src and dst together (prevents cache trashing going between)
3. Make more use of VUID maps to not need to pass `const char*` everywhere possible
=> layers: Misc cleanup of Copy Buffer Image code

docs/fine_grained_locking.md, layers/core_checks/cc_cmd_buffer.cpp, layers/core_checks/cc_image_layout.cpp, layers/core_checks/cc_synchronization.cpp, layers/gpu/descriptor_validation/gpuav_image_layout.cpp, layers/state_tracker/cmd_buffer_state.cpp, layers/state_tracker/cmd_buffer_state.h, layers/state_tracker/image_layout_map.cpp, layers/state_tracker/image_layout_map.h, layers/state_tracker/image_state.cpp, layers/state_tracker/state_object.h, layers/state_tracker/state_tracker.h, tests/unit/image_layout.cpp
1. `ImageSubresourceLayoutMap` is not a map, it contains the `LayoutMap` and it is confusing, renamed to reflect that
2. Moved the `uint32_t` (`IdType`) inside `ImageSubresourceLayoutInfo` so that the other `image_layout_map` is simpler to use
=> Collapse the image layout map value

layers/core_checks/cc_pipeline_graphics.cpp, layers/state_tracker/pipeline_sub_state.h, tests/unit/graphics_library_positive.cpp
The VK_PIPELINE_CREATE_2_ENABLE_LEGACY_DITHERING_BIT_EXT flag is part of the fragment output state, but is not tracked by the fragment output state of the validation layer. This can cause incorrect validation layer errors when the flag is included when creating a pipeline library, while not including it in the final pipeline. This PR fixes this by adding the flag to the fragment output state, and adds a test to the positive graphics pipeline library test class.
Addresses issue: #8988
=> tests: Add test for GPL and legacy dithering

.github/workflows/vvl.yml, scripts/tests.py
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/8931
This limits TSAN to threading, sync val, sync object, and WSI tests for now (which is 348 tests currently)
cc @artem-lunarg @aqnuep
=> ci: Reduce TSAN to tests that need it

layers/VkLayer_khronos_validation.json.in, layers/layer_options.cpp, layers/sync/sync_commandbuffer.h, layers/sync/sync_error_messages.cpp, layers/sync/sync_error_messages.h, layers/sync/sync_reporting.cpp, layers/sync/sync_reporting.h, layers/sync/sync_settings.h, layers/sync/sync_submit.h, tests/unit/sync_val_positive.cpp
This section is optional and is disabled by default. If enabled it is appended to the main error messages. The purpose of the key-values section is to allow filtering of the error messages based on selected properties. It can also contain debug/optional information.
This aims to solve a problem when the applications extract parts of the main error message for filtering purposes (false positives or the errors not fixed by the application yet). Even minor changes to the main error message can break these filters. This makes it harder to modify and improve error messages. The key-values section is more structured and more stable which makes it more suitable for filtering purposes.
The key-values section is not used to improve the main error message. The latter should contain all the …
=> sync: Introduce key-value properties section

layers/thread_tracker/thread_safety_validation.cpp, tests/unit/threading_positive.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/8975
simply seems we did mark `UNUSED_WHILE_PENDING` the same way we did for `UPDATE_AFTER_BIND`
=> layers: Add UNUSED_WHILE_PENDING to threading exception

layers/core_checks/cc_copy_blit_resolve.cpp, layers/core_checks/cc_image.cpp, layers/core_checks/cc_image_layout.cpp, layers/core_checks/cc_vuid_maps.cpp, layers/core_checks/cc_vuid_maps.h, layers/core_checks/core_validation.h, layers/error_message/error_strings.h, tests/unit/host_image_copy.cpp
Improves the `ValidateHostCopyCurrentLayout` code flow to match other functions
=> layers: Cleanup ValidateHostCopyCurrentLayout

layers/gpu/cmd_validation/gpuav_draw.cpp, layers/state_tracker/buffer_state.h, layers/state_tracker/state_tracker.cpp, layers/state_tracker/vertex_index_buffer_state.h, layers/sync/sync_common.cpp, layers/sync/sync_common.h, layers/utils/vk_layer_utils.h
It always has been `ComputeValidSize` under the hood, so remove needless abstractions
=> layers: Cleanup Buffer::ComputeSize

BUILD.gn
Log to failure output:
https://logs.chromium.org/logs/angle/buildbucket/cr-buildbucket/8728843360838685857/+/u/presubmit/stdout
=> Fix GN build

layers/VkLayer_khronos_validation.json.in, layers/layer_options.cpp, layers/vk_layer_settings.txt, tests/framework/layer_validation_tests.h, tests/unit/copy_buffer_image.cpp, tests/unit/descriptor_buffer.cpp, tests/unit/dynamic_state.cpp, tests/unit/fragment_shading_rate.cpp, tests/unit/gpu_av_descriptor_indexing.cpp, tests/unit/layer_settings.cpp, tests/unit/nvidia_best_practices.cpp, tests/unit/pipeline.cpp, tests/unit/ray_tracing_nv.cpp, tests/unit/sampler.cpp, tests/unit/shader_spirv.cpp, tests/unit/sync_object.cpp, tests/unit/sync_val.cpp, tests/unit/threading_positive.cpp, tests/unit/video.cpp, tests/unit/viewport_inheritance.cpp
reverts https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/8784/commits/ff8e3acfcac128f9faabb74d8b62206ff0195939
Now logic is 
- default is limit to 10
- This is new, as pointed out that we have tests failing because of this
- `enable_message_limit = false`  there is no limit
- `duplicate_message_limit = 0` (which is possible outside of vkconfig) there is no limit
@ziga-lunarg @artem-lunarg you 2 wanted this back (and agree) but please verify this is what you wanted
(the vkconfig GUI looks the exact same it was before)
=> settings: Revert enable_message_limit

layers/state_tracker/semaphore_state.cpp, tests/unit/sync_object_positive.cpp
This is follow-up to https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/9000 and reproduces another assert https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/8989#issuecomment-2535685344
Wait timepoint should not be registered when signal is already retired.
In this case wait should be resolved againt `completed_` state.
There is assert in `Semaphore::CanBinaryBeSignaled` that checks that
binary timepoint has at least signal op. The new tests will trigger this
assert in case of a regression.
There might be other places to adjust, will continue to inspect code.
Addresses assert part of https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/9009
=> layers: Do not create wait timepoint after signal retired

layers/core_checks/cc_spirv.cpp, tests/unit/shader_spirv.cpp
Crashes driver, found in https://gitlab.khronos.org/vulkan/vulkan/-/issues/4111 
We were missing an exception if you have a runtime array but still supply zero
=> layers: Check if runtime descriptor array have zero

layers/external/inplace_function.h, layers/gpu/resources/gpuav_vulkan_objects.h, layers/utils/vk_layer_utils.h
This is to fix build error when we set use_libcxx_modules=true in chromium build.
=> build: Add missing header includes

tests/framework/descriptor_helper.cpp, tests/framework/descriptor_helper.h, tests/unit/best_practices.cpp, tests/unit/descriptor_indexing.cpp, tests/unit/descriptor_indexing_positive.cpp, tests/unit/descriptors.cpp, tests/unit/gpu_av_descriptor_class_general_buffer.cpp, tests/unit/gpu_av_descriptor_class_general_buffer_positive.cpp, tests/unit/gpu_av_descriptor_indexing.cpp, tests/unit/gpu_av_descriptor_indexing_positive.cpp, tests/unit/gpu_av_descriptor_post_process.cpp, tests/unit/gpu_av_descriptor_post_process_positive.cpp, tests/unit/gpu_av_image_layout.cpp, tests/unit/gpu_av_image_layout_positive.cpp, tests/unit/gpu_av_positive.cpp, tests/unit/gpu_av_ray_tracing.cpp, tests/unit/graphics_library.cpp, tests/unit/image_layout_positive.cpp, tests/unit/pipeline.cpp, tests/unit/pipeline_positive.cpp, tests/unit/ray_tracing_nv.cpp, tests/unit/ray_tracing_pipeline.cpp, tests/unit/render_pass_positive.cpp, tests/unit/shader_image_access_positive.cpp, tests/unit/shader_spirv_positive.cpp, tests/unit/sync_val.cpp, tests/unit/sync_val_positive.cpp, tests/unit/threading_positive.cpp
After creating about 50 GPU-AV tests using `OneOffDescriptorSet` this adds a `OneOffDescriptorIndexingSet` that lets me put the `VkDescriptorBindingFlags` inside with the `VkDescriptorSetLayoutBinding` (It is easy to both have to re-aligned them or forget the UpdateAfterBind pool/DSL flags as well
so instead of going
```c++
// needs to make sure this line up in the order of bindings listed, not the "binding number"
VkDescriptorBindingFlagsEXT ds_binding_flags[2] = {VK_DESCRIPTOR_BINDING_PARTIALLY_BOUND_BIT, 0};
//...
{2, VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER, 2, VK_SHADER_STAGE_ALL, nullptr},
{4, VK_DESCRIPTOR_TYPE_STORAGE_BUFFER, 1, VK_SHADER_STAGE_ALL, nullptr},
```
it just goes
```
{2, VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER, 2, VK_SHADER_STAGE_ALL, nullptr, …
```
=> tests: Create a OneOffDescriptorIndexingSet

layers/gpu/cmd_validation/gpuav_draw.cpp, layers/gpu/cmd_validation/gpuav_draw.h, layers/gpu/core/gpuav_record.cpp, scripts/vk_validation_stats.py, tests/framework/error_monitor.cpp, tests/framework/error_monitor.h, tests/unit/gpu_av_indirect_buffer.cpp
https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/8953 reverted the changes from https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/8743
The VUIDs removed don't exists in the spec anymore
=> layers: Revert CountBuffer back to warning

tests/framework/layer_validation_tests.h
Fixes video test errror:
> D:\vvl\tests\framework\video_objects.h(483,29): error C2061: syntax error: identifier '_ARM64_BARRIER_SY' [D:\vvl\build\Debug\tests\vk_layer_validation_tests.vcxproj]
(compiling source file '../../../tests/unit/video.cpp')
We already have similar define for the layer code in sync_utils.h.
=> tests: Fix compilation on Windows ARM64

scripts/update_deps.py
Current default configuration tries to build x64 on ARM64 which fails. It's possible to specify --arch, but it's nicer if by default it's a workable configuration.
This is how it fails:
> D:\vvl-temp\external\Debug\64\SPIRV-Tools\build\install\lib\SPIRV-Tools-opt.lib : warning LNK4272: library machine type
'x64' conflicts with target machine type 'ARM64' [D:\vvl-temp\build\Debug\layers\vvl.vcxproj]
D:\vvl-temp\external\Debug\64\SPIRV-Tools\build\install\lib\SPIRV-Tools.lib : warning LNK4272: library machine type 'x6
4' conflicts with target machine type 'ARM64' [D:\vvl-temp\build\Debug\layers\vvl.vcxproj]
D:\vvl-temp\external\Debug\64\Vulkan-Utility-Libraries\build\install\lib\VulkanLayerSettings.lib : warning LNK4272: lib
rary machine type 'x64' conflicts with target machine type 'ARM64' …
=> scripts: Set default arch to arm64 on ARM64 machines

tests/framework/external_memory_sync.cpp, tests/framework/external_memory_sync.h, tests/unit/sync_object_positive.cpp
Current Windows Adreno driver supports only binary semaphore export. The test incorrectly queried support for timeline semaphores and because of that failed. The fix takes into account VkSemaphoreTypeCreateInfo.
=> tests: Fix test failure on Windows Arm

tests/unit/sync_val.cpp
The problem was, that after DestroyedUnusedDescriptors, all other tests started to fail. Investigation shown that Adreno driver does not like when uniform buffer is removed even it is not dynamically used.
The solution is simple. DestroyedUnusedDescriptors triggers record time validation of descriptors (ValidateDispatchDrawDescriptorSet). If we remove QueueSubmit we still run the same validation but also make the test stable on Adreno driver.
NOTE: One of *many* potential reasons (just to demo at least one possibility) why deleting uniform buffer that is not dynamically used can be problematic, is that native gpu isa compiler can generate load insructions early in the shader to deal with latency. There can be a heuristic that says it's better to send memory load requests early in the …
=> tests: Fix massive syncval tests failure on Windows Arm

layers/gpu/cmd_validation/gpuav_draw.cpp, tests/unit/gpu_av_indirect_buffer_positive.cpp
Closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/9014
=> gpuav: Fix / 0 in draw mesh indirect validation

layers/state_tracker/state_tracker.cpp, tests/unit/vertex_input.cpp, tests/unit/vertex_input_positive.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/9027
`vkCmdSetVertexInputEXT` has a special clause in it so when setting it, we need to reset the previous bindings
=> layers: Clear dynamic vertex input not set

layers/gpu/cmd_validation/gpuav_draw.cpp, tests/unit/gpu_av_index_buffer_positive.cpp, tests/unit/gpu_av_indirect_buffer_positive.cpp
Follow-up to https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/9019
Same "prevent / 0" fix
=> gpuav: Handle case where indirect cmd stride is 0

tests/unit/ycbcr_positive.cpp
This test would fail on one of my devices.
The test `PositiveYcbcr.ImageQuerySizeLod` has the same check.
=> tests: Skip test if descriptor set alloc fails

tests/unit/descriptor_buffer.cpp
`VUID-VkBufferCreateInfo-usage-08101`:
> If usage includes VK_BUFFER_USAGE_PUSH_DESCRIPTORS_DESCRIPTOR_BUFFER_BIT_EXT, the descriptorBufferPushDescriptors feature must be enabled
=> tests: Enable missing descriptor buffer feature

layers/gpu/spirv/buffer_device_address_pass.cpp, layers/gpu/spirv/descriptor_class_general_buffer_pass.cpp, layers/gpu/spirv/descriptor_class_texel_buffer_pass.cpp, layers/gpu/spirv/descriptor_indexing_oob_pass.cpp, layers/gpu/spirv/link.h, layers/gpu/spirv/post_process_descriptor_indexing.cpp, layers/gpu/spirv/ray_query_pass.cpp
I added the `LinkFunctions` before I just added the `OpName` and so far I have found/thought of no good reason to keep these here, so removing until we actually find a real reason to use them
=> gpu: Remove unused LinkFunction

layers/layer_options.cpp, tests/CMakeLists.txt, tests/unit/layer_settings.cpp, tests/unit/layer_settings_positive.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/9028
We ultimately need a more streamline, auto-generated way of doing this type of checks (else adding a setting only gets more complicated again)
For now, at least warn the user if they have the wrong `VkLayerSettingTypeEXT` or duplicated a setting
=> layers: Warn if VkLayerSettingEXT has wrong type or duplicated

layers/gpu/spirv/buffer_device_address_pass.cpp, tests/unit/gpu_av_buffer_device_address.cpp, tests/unit/gpu_av_buffer_device_address_positive.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/9029
Luckily the `OpAtomicLoad` and `OpLoad` are the same code flow, except it doesn't have an alignment
=> gpu: Add atomics for BDA checks

layers/vulkan/generated/spirv_tools_commit_id.h, scripts/known_good.json
This aligns it with the version in the upcoming SDK release.
=> build: Roll SPIRV-Tools back to v2024.4.rc2

layers/gpu/spirv/descriptor_class_general_buffer_pass.cpp, layers/gpu/spirv/descriptor_class_general_buffer_pass.h, layers/gpu/spirv/module.cpp, layers/gpu/spirv/pass.cpp, layers/gpu/spirv/pass.h, layers/gpu/spirv/type_manager.cpp, layers/gpu/spirv/type_manager.h, layers/state_tracker/shader_module.cpp, tests/framework/layer_validation_tests.h, tests/unit/gpu_av_descriptor_class_general_buffer.cpp, tests/unit/gpu_av_descriptor_class_general_buffer_positive.cpp, tests/unit/pipeline_topology_positive.cpp
This fixes case when you go
```
%36 = OpAccessChain %23 %35 0
%37 = OpAccessChain %20 %36 1
```
instead of `%36 = OpAccessChain %23 %35 0 1` 
While here, added lots of test to fix checking when copying between Array/Structs
=> gpu: Fix Chaining of Accesses for General Buffer

layers/sync/sync_commandbuffer.h, layers/sync/sync_error_messages.cpp, layers/sync/sync_error_messages.h, layers/sync/sync_renderpass.cpp, layers/sync/sync_reporting.cpp, layers/sync/sync_reporting.h
Adds properties to filter common types of syncval error messages. Tested on ANGLE's error supression list. Later, after more testing, will provide to ANGLE an example/patch how to update suppression list to use new properties. This will make the project less affected by the changes to error messages.
=> sync: Add more properties to filter syncval errors

layers/VkLayer_khronos_validation.json.in, layers/vk_layer_settings.txt
We never updated these settings after turning them off in https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/8586 (which have since been fixed)
=> settings: Update GPU-AV settings

layers/core_checks/cc_device_memory.cpp, layers/core_checks/core_validation.h, tests/unit/memory.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/9033
=> layers: Check maxMemoryAllocationSize

tests/framework/video_objects.h, tests/unit/video.cpp, tests/unit/video_positive.cpp
To make it consistent with other syncval tests.
`NegativeSyncVal*` should pattern match all negative tests.
Existing syncval test suites:
NegativeSyncVal
NegativeSyncValWsi
NegativeSyncValTimelineSemaphore
cc @aqnuep
=> sync: Rename video test suite

layers/VkLayer_khronos_validation.json.in, layers/gpu/core/gpuav_settings.h, layers/gpu/descriptor_validation/gpuav_image_layout.cpp, layers/layer_options.cpp, layers/vk_layer_settings.txt, tests/framework/layer_validation_tests.h, tests/unit/gpu_av_image_layout.cpp, tests/unit/gpu_av_image_layout_positive.cpp, tests/unit/layer_settings_positive.cpp
https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/8688
and 
https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/8869
are showing that we still have some false positives around Image Layouts with GPU-AV
For short term, created a setting (which we probably should have had anyway) and made the default off
=> gpu: Default Image Layout to off

layers/gpu/spirv/descriptor_class_general_buffer_pass.cpp, layers/gpu/spirv/descriptor_indexing_oob_pass.cpp, layers/gpu/spirv/pass.cpp, layers/gpu/spirv/post_process_descriptor_indexing.cpp, layers/gpu/spirv/type_manager.h, tests/unit/gpu_av_descriptor_class_general_buffer.cpp, tests/unit/gpu_av_descriptor_class_general_buffer_positive.cpp, tests/unit/gpu_av_descriptor_indexing.cpp, tests/unit/gpu_av_descriptor_post_process.cpp, tests/unit/gpu_av_descriptor_post_process_positive.cpp
Adds more Slang shaders that use chains of `OpAccessChains` and finally fixed the various TODO to add support for it
=> gpu: Add support for multiple access chains

layers/sync/sync_vuid_maps.cpp, tests/unit/sync_object.cpp
Follow-up to https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/8878 after https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/7029
=> layers: Replace ownership transfer UNASSIGNED with VUIDs

layers/chassis/dispatch_object.h, layers/chassis/dispatch_object_manual.cpp, layers/chassis/validation_object.h, layers/error_message/logging.h, layers/vulkan/generated/dispatch_object.cpp, scripts/generators/dispatch_object_generator.py
Add DispatchObject methods for common handle wrapping operations that were being done inline in many places.
Add Logger class to define LogError(), etc. so that the can only be defined once.
=> chassis: Clean up handle wrapping and Log method definitions

layers/state_tracker/state_tracker.cpp, layers/state_tracker/state_tracker.h
We had logic in the vkDestroyDevice() code path that cleans up the state maps in a specific order to handle interdependencies between state object types. This also needs to be called in the destructor, in case an application exits without destroying vulkan objects. In that case, everything gets destroyed via an atexit() callback and it still needs to use the correct ordering.
=> state: Tear down state maps correctly in destructor

layers/state_tracker/state_tracker.cpp, layers/state_tracker/state_tracker.h
Closes #8874 
I have a test that reproduced this, but I can't submit it, because it is not reliable. 
```
TEST_F(PositiveExternalMemorySync, Test) {
TEST_DESCRIPTION("");
{
SetTargetApiVersion(VK_API_VERSION_1_1);
AddRequiredExtensions(VK_KHR_EXTERNAL_MEMORY_WIN32_EXTENSION_NAME);
RETURN_IF_SKIP(Init());
const auto handle_type = VK_EXTERNAL_MEMORY_HANDLE_TYPE_OPAQUE_WIN32_BIT;
VkExternalMemoryBufferCreateInfo external_buffer_info = vku::InitStructHelper();
external_buffer_info.handleTypes = handle_type;
auto buffer_info = vkt::Buffer::CreateInfo(4096u, VK_BUFFER_USAGE_TRANSFER_SRC_BIT | VK_BUFFER_USAGE_TRANSFER_DST_BIT);
buffer_info.pNext = &external_buffer_info;
vkt::Buffer buffer_export(*m_device, buffer_info, vkt::no_mem);
auto alloc_info = …
```
=> layers: Remove win32 handle on memory free

layers/core_checks/cc_descriptor.cpp, layers/object_tracker/object_tracker_utils.cpp, layers/state_tracker/descriptor_sets.cpp, layers/stateless/sl_descriptor.cpp, tests/framework/binding.cpp, tests/framework/binding.h, tests/unit/descriptors.cpp, tests/unit/push_descriptor.cpp
Closes #8251
The issue here is that while `vkCmdUpdateDescriptorSets` can be validated in stateless, `vkUpdateDescriptorSetWithTemplate` cannot and can only be in core checks.
=> Validate update descriptor set with template

layers/core_checks/cc_descriptor.cpp, layers/state_tracker/descriptor_sets.cpp, layers/stateless/sl_descriptor.cpp, tests/unit/descriptors.cpp, tests/unit/push_descriptor.cpp, tests/unit/push_descriptor_positive.cpp
Some small cleanup of https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/9069 (cc @ziga-lunarg )
1. Renaming `auto *dest`
2. Grouping somethings in `ValidateWriteUpdate`
3. Using the new `vkt::DescriptorUpdateTemplate` everywhere possible
=> layers: More Update Descriptor cleanup

layers/error_message/error_strings.h, layers/gpu/instrumentation/gpuav_instrumentation.cpp, layers/state_tracker/pipeline_layout_state.cpp, tests/unit/gpu_av_buffer_device_address_positive.cpp, tests/unit/gpu_av_descriptor_indexing_positive.cpp
Added tests that showed issues with the selection of the pipeline layout used to bind the instrumentation descriptor set. Now, when trying to get pipeline layout from last bound pipeline, if it has been destroyed it is temporarily re-created and used to bind instrumentation descriptor set.
Trying to get a pipeline layout from another source (for the new test, pipeline layout specified in last vkCmdPushConstants call) lead to the dreaded vkCmdDraw-None-08600
=> gpuav: Fix selection of instrumentation desc set pipeline layout

layers/error_message/logging.cpp, tests/unit/others.cpp
Followup of https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/9016 to fix `ANNOTATED_SPEC_LINK`
=> layers: Fix annotated spec link

layers/chassis/chassis_manual.cpp
Closes #9090
The device extensions should be loaded from `VkPhysicalDeviceProperties::apiVersion` and not the instance api version. 
Currently the instance api version is used and if it is higher than device api version extensions will be enabled for the device which it does not have. In the linked issue the problem was that instance api version was 1.3 and device only 1.1, so`VkPhysicalDeviceVulkan11Properties` and `VkPhysicalDeviceVulkan12Properties` were used in `state_tracker.cpp:766`, and these structs were passed into `vkGetPhysicalDeviceProperties2()` and were not filled in. Even though the driver supported VK_KHR_multiview those same properties in `VkPhysicalDeviceVulkan11Properties` were 0.
=> layers: Fix enabling extensions from api version

layers/gpu/cmd_validation/gpuav_draw.cpp
For `VUID-vkCmdDrawIndexed-None-02721` the spec says:
> If the robustBufferAccess feature is not enabled, **and** that pipeline was created without enabling VK_PIPELINE_ROBUSTNESS_BUFFER_BEHAVIOR_ROBUST_BUFFER_ACCESS for vertexInputs
=> gpuav: Fix VUID 02721 features check

layers/core_checks/cc_descriptor.cpp, layers/core_checks/core_validation.h, layers/object_tracker/object_tracker_utils.cpp, layers/state_tracker/descriptor_sets.cpp, layers/state_tracker/descriptor_sets.h, tests/unit/buffer.cpp, tests/unit/descriptors.cpp, tests/unit/descriptors_positive.cpp, tests/unit/parent.cpp
`VUID-vkUpdateDescriptorSets-pDescriptorWrites-06238` was missing and it lead down a rabbit hole of cleaning up the Write/Copy descriptor error messages and grouping things together to make it easier when dealing with the many `VkDescriptorType`
=> layers: Improve Descriptors error messages

tests/framework/barrier_queue_family.cpp, tests/framework/binding.cpp, tests/framework/binding.h, tests/framework/buffer_helper.h, tests/framework/queue_submit_context.cpp, tests/framework/ray_tracing_objects.cpp, tests/framework/ray_tracing_objects.h, tests/framework/render.h, tests/framework/video_objects.h, tests/unit/copy_buffer_image.cpp, tests/unit/debug_printf_ray_tracing.cpp, tests/unit/fragment_shading_rate.cpp, tests/unit/gpu_av_buffer_device_address_positive.cpp, tests/unit/gpu_av_index_buffer.cpp, tests/unit/gpu_av_index_buffer_positive.cpp, tests/unit/gpu_av_indirect_buffer.cpp, tests/unit/gpu_av_indirect_buffer_positive.cpp, tests/unit/ray_tracing_positive.cpp, tests/unit/robustness.cpp, tests/unit/shader_object.cpp, tests/unit/shader_object_positive.cpp, tests/unit/sync_val_positive.cpp, tests/unit/vertex_input.cpp, tests/unit/vertex_input_positive.cpp, tests/unit/video.cpp, tests/unit/video_positive.cpp, tests/unit/wsi.cpp
Starting off the new year with removing the various Deprecated renaming of lowercase function helper names
=> tests: Remove deprecated helpers

layers/core_checks/cc_ray_tracing.cpp, layers/object_tracker/object_tracker_utils.cpp, layers/state_tracker/state_tracker.cpp, layers/stateless/sl_buffer.cpp, layers/stateless/sl_descriptor.cpp, layers/stateless/sl_pipeline.cpp, layers/stateless/sl_ray_tracing.cpp, scripts/check_code_format.py, tests/unit/buffer.cpp, tests/unit/device_generated_commands.cpp, tests/unit/ray_tracing.cpp, tests/unit/render_pass.cpp, tests/unit/shader_spirv.cpp
Some spots have this `if (pCreateInfo)` check that my tests show are not needed actually because that is handled in the auto-generated stateless checks
=> layers: Remove unneeded pCreateInfo checks

layers/core_checks/cc_device_generated_commands.cpp, layers/error_message/error_strings.h
small followup of https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/9072 to improve `string_VkPushConstantRange` when used with Device Generated Commands
=> layers: Small cleanup to string_VkPushConstantRange

layers/error_message/unimplementable_validation.h, layers/stateless/sl_ray_tracing.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/9116
@ziga-lunarg pointed out in https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/9121 (and I confirmed) there is no way to hit these implicit VUs, so just moving them out of the code as we have no way to test them
=> layers: Remove unimplementable union of struct sType

layers/core_checks/cc_wsi.cpp, layers/vulkan/generated/test_icd_helper.h, scripts/generators/test_icd_generator.py, tests/icd/test_icd.cpp, tests/unit/wsi_positive.cpp
`vkGetPhysicalDeviceSurfaceCapabilities2EXT` was not properly supported and some WSI tests were failing locally on my TestICD
=> tests: Add GetPhysicalDeviceSurfaceCapabilities2EXT to testICd

layers/gpu/spirv/debug_printf_pass.cpp, tests/unit/debug_printf.cpp
=> printf: Fix error messages with newlines

tests/unit/copy_buffer_image.cpp, tests/unit/memory.cpp, tests/unit/query.cpp, tests/unit/secondary_command_buffer.cpp, tests/unit/transform_feedback.cpp
Part of #9119
For 
VUID-vkCmdEndQuery-query-00812
VUID-vkCmdEndQuery-queryPool-03228
VUID-vkCmdExecuteCommands-None-02286
I don't see a way to hit these VUIDs without hitting something else first.
And VUID-vkCmdExecuteCommands-pCommandBuffers-00091 runs into an unassigned that seems to check the same thing.
```
TEST_F(NegativeSecondaryCommandBuffer, MissingSimultaniousUseBit) {
RETURN_IF_SKIP(Init());
vkt::CommandBuffer primary(*m_device, m_command_pool);
vkt::CommandBuffer secondary(*m_device, m_command_pool, VK_COMMAND_BUFFER_LEVEL_SECONDARY);
secondary.Begin();
secondary.End();
primary.Begin(VK_COMMAND_BUFFER_USAGE_SIMULTANEOUS_USE_BIT);
vk::CmdExecuteCommands(primary.handle(), 1u, &secondary.handle());
primary.End();
m_command_buffer.Begin(VK_COMMAND_BUFFER_USAGE_SIMULTANEOUS_USE_BIT); …
```
=> tests: Add missing tests

layers/best_practices/bp_render_pass.cpp
`VkRenderingAttachmentInfo::imageView` can be `VK_NULL_HANDLE`
=> bp: Fix assert when image view can be null

layers/best_practices/bp_drawdispatch.cpp
If the maintenance6 feature is enabled, buffer can be VK_NULL_HANDLE. If buffer is VK_NULL_HANDLE and the nullDescriptor feature is enabled, every index fetched results in a value of zero.
=> bp: Fix assert when buffer can be null

layers/sync/sync_vuid_maps.cpp, tests/unit/secondary_command_buffer.cpp
@ziga-lunarg showed in https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/9130 that `VUID-vkCmdExecuteCommands-pCommandBuffers-00091` is not needed (going to remove from spec) but it showed we were missing a test (and not had a bug) for `VUID-vkQueueSubmit-pCommandBuffers-00073`
=> tests: Add Test for 00073

layers/core_checks/cc_copy_blit_resolve.cpp, tests/unit/copy_buffer_image.cpp
@spencer-lunarg There was no test for `VUID-vkCmdCopyBuffer-dstBuffer-00121` and it would have found this
=> Fix crash when dst buffer has no memory

layers/sync/sync_reporting.cpp
NOTE about testing methodology of changes that affect error messages.
Dump all negative errors before and after the fix and diff compare these files.
The gtest filter is of this form:  `NegativeSyncVal*.* --gtest_print_time=0 --print-vu >d:\sync_{before/after}.txt`
`--gtest_print_time` removes varying time field from the error message.
To remove varying dispatchable handles from the output the attached patch can be used:
[remove-dispatchable-handles.patch](https://github.com/user-attachments/files/18318045/remove-dispatchable-handles.patch)
Will add this to sync docs too.
Replaces https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/9137
=> sync: Fix extra comma in vkAcquireNextImageKHR error

layers/chassis/dispatch_object_manual.cpp, layers/vulkan/generated/dispatch_functions.h, layers/vulkan/generated/dispatch_object.cpp, layers/vulkan/generated/dispatch_object_device_methods.h, layers/vulkan/generated/dispatch_object_instance_methods.h, layers/vulkan/generated/feature_requirements_helper.cpp, layers/vulkan/generated/feature_requirements_helper.h, scripts/generators/dispatch_object_generator.py, scripts/generators/feature_requirements.py, tests/unit/buffer_positive.cpp
When handle wrapping was enabled, `VkBindMemoryStatus` was not handled correctly
=> layers: Fix getting bind memory status result

layers/sync/sync_renderpass.cpp, tests/unit/sync_val_positive.cpp
Syncval would assert if dynamic rendering contains a depth attachment without depth aspect or stencil attachment without stencil aspect
=> sync: Fix creating dynamic rendering attachments in sync val

layers/core_checks/cc_descriptor.cpp, layers/core_checks/core_validation.h, layers/state_tracker/descriptor_sets.cpp, layers/state_tracker/descriptor_sets.h, layers/state_tracker/pipeline_layout_state.h, layers/state_tracker/state_tracker.cpp, tests/unit/descriptors.cpp, tests/unit/push_descriptor.cpp
This mainly cleans up the `VkWriteDescriptorSet` checks to provide a better error message when using `VK_KHR_push_descriptor` (now promoted to 1.4)
the tl;dr is for the normal flow, you look at `VkWriteDescriptorSet::dstSet` to get the VkDescriptorSetLayout... but with Push Descriptors, you use the `VkPipelineLayout` at the `vkCmdPushDescriptorSet` call
Many error messages were really confusing because it would talk about the `VkDescriptorSet`, but there isn't one with Push Descriptors
=> layers: Improve Push Descriptor error messages

scripts/generators/base_generator.py, scripts/generators/vulkan_object.py
The `number` here is not being used anywhere
=> scripts: Remove Version::number from VulkanObject

layers/best_practices/bp_device_memory.cpp, layers/core_checks/cc_device_memory.cpp, layers/gpu/descriptor_validation/gpuav_image_layout.cpp, layers/state_tracker/device_memory_state.h, layers/state_tracker/image_state.h, layers/state_tracker/state_tracker.cpp, layers/state_tracker/state_tracker.h, layers/sync/sync_validation.cpp, tests/unit/buffer_positive.cpp, tests/unit/memory.cpp, tests/unit/memory_positive.cpp
`VkBindMemoryStatus` was added in `VK_KHR_maintenance6` (which is now part of 1.4)
I allows cases where people batch many things in `vkBindImageMemory2` but provides a way to know which buffer/images actually bound memory or not
This was not well plumbed out throughout the VVL
=> Fixes for VkBindMemoryStatus

layers/best_practices/bp_render_pass.cpp, layers/core_checks/cc_cmd_buffer.cpp, layers/core_checks/cc_image_layout.cpp, layers/core_checks/cc_render_pass.cpp, layers/core_checks/core_validation.h, layers/stateless/sl_render_pass.cpp, layers/stateless/stateless_validation.h
The logic for `vkCmdBeginRendering` was all over the place between Stateless, CoreCheck, and Best Practice
Tried to unify things (naming, how things are broken up, etc) and group things as there is a lot going on and hard to follow it at first read
=> layers: Cleanup vkCmdBeginRendering

layers/gpu/spirv/function_basic_block.h
Trying to build with C++23 fails due to the Instruction type being incomplete (probably std::unique_ptr<> requirements became stricter). This patch fixes the error by #including the type instead of forward declaring.
There are a few other C++23 build errors related to the use of std::aligned_storage, but fixing those is beyond the scope of this patch.
=> Fix C++23 build error in function_base_block.h

layers/core_checks/cc_cmd_buffer_dynamic.cpp, tests/unit/dynamic_state_positive.cpp
If discard rectangles enable is false, then discard rectangles don't have to be set
=> layers: Fix checking discard rectangle dynamic state

tests/unit/shader_object.cpp
Part of #9153 
VUIDS:
VUID-vkCmdBindShadersEXT-pShaders-08474
VUID-vkCmdBindShadersEXT-pShaders-08475
VUID-vkCmdBindShadersEXT-pShaders-08490
VUID-vkCmdBindShadersEXT-pShaders-08491
Cannot be hit without hitting something else. If the require feature is not enabled, then those shaders cannot be created. The only option would be to bind a shader created for a different stage, but there is a VUID for that too.
=> tests: Add missing shader object tests

layers/VkLayer_khronos_validation.json.in, layers/gpu/core/gpuav_record.cpp, tests/unit/gpu_av_index_buffer.cpp
Second half of the fix for https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/9141
It can be too slow, stalling the GPU. I am moving validation to instrumentation
=> gpuav: Disable vertex buffer fetching validation

tests/framework/binding.h, tests/unit/sync_object.cpp, tests/unit/sync_val.cpp
- Move 2 tests to Sync Object
- Use `vkt::Event` the same everywhere
=> Small misc Sync Test fixes

layers/gpu/descriptor_validation/gpuav_image_layout.cpp, layers/sync/sync_validation.cpp
Found some GPU-AV and Sync Val functions that were not just passing through for alias and duplicating things
=> layers: Use alias passthrough for recording functions

layers/core_checks/cc_synchronization.cpp, tests/unit/sync_object.cpp, tests/unit/sync_object_positive.cpp
created internal spec fix https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/7089
but we were missing the "new" `VUID-vkCmdWaitEvents2-dependencyFlags-03844`
=> layers: Fix vkCmdWaitEvents2 VU

layers/sync/sync_utils.cpp, layers/vulkan/generated/sync_validation_types.cpp, layers/vulkan/generated/sync_validation_types.h, scripts/generators/sync_validation_generator.py
We were missing `VK_PIPELINE_STAGE_2_ACCELERATION_STRUCTURE_COPY_BIT_KHR` in manual code.
=> sync: Generate expansion for ALL_TRANSFER stage

layers/core_checks/cc_pipeline.cpp, layers/state_tracker/state_tracker.cpp, layers/state_tracker/state_tracker.h, layers/stateless/sl_instance_device.cpp, layers/stateless/sl_pipeline.cpp, layers/stateless/sl_ray_tracing.cpp, layers/stateless/stateless_validation.h
followup to https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/9088 (after spending more time looking into it)
I think this stuff is better suited in CoreChecks state tracking than stateless, we already had a `ValidatePipelineRobustnessCreateInfo` doing the same logic and rather keep the "check if the extension is supported" logic together
=> layers: Move VK_EXT_robustness2 check to corechecks

layers/vulkan/generated/feature_requirements_helper.cpp, layers/vulkan/generated/stateless_validation_helper.cpp, layers/vulkan/generated/stateless_validation_helper.h, scripts/generators/stateless_validation_helper_generator.py, tests/unit/other_positive.cpp, tests/unit/others.cpp
quick fix for SDK - tracking in https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/9185
=> scripts: Temp remove VkPhysicalDeviceLayeredApiPropertiesKHR

layers/chassis/dispatch_object_manual.cpp, tests/unit/instanceless.cpp
It is possible for a the tls cache to contain a destroyed object in multithreaded applications.
Fixes #9181
=> chassis: Remove tls caching of device/instance state

tests/unit/command_positive.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/5356
@ziga-lunarg wrote CTS tests and it is a driver bug, so we will blacklist any GPU failing and continue onward keeping this test
=> tests: Renable ClearRectWith2DArray

layers/core_checks/cc_pipeline_graphics.cpp
Noticed we were doing an assert not on the image state but on the `VkSampleCountFlagBits`
=> layers: Fix assert check on sample count image state

layers/sync/sync_vuid_maps.cpp, tests/unit/sync_object.cpp
Adds tests for:
VUID-vkCmdPipelineBarrier-dstStageMask-04091
VUID-vkCmdPipelineBarrier-dstStageMask-04092
VUID-vkCmdPipelineBarrier-dstStageMask-04093
VUID-vkCmdPipelineBarrier-dstStageMask-04094
VUID-vkCmdPipelineBarrier-dstStageMask-03937
VUID-vkCmdPipelineBarrier-dstStageMask-07318
VUID-VkBufferMemoryBarrier2-dstStageMask-04957
VUID-VkBufferMemoryBarrier2-dstStageMask-04995
=> tests: Add missing barrier tests

layers/core_checks/cc_synchronization.cpp, tests/unit/sync_object.cpp
Closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/9191
=> layers: Use correct VUID for signaling signaled semaphore

layers/core_checks/cc_synchronization.cpp, layers/state_tracker/cmd_buffer_state.cpp, layers/state_tracker/cmd_buffer_state.h, tests/unit/sync_object.cpp
=> layers: Fix checking if event is in use

tests/unit/render_pass_positive.cpp
replace `ASSERT_NO_FATAL_FAILURE` with `RETURN_IF_SKIP` (old test must have slipped in on rebase)
=> tests: Use RETURN_IF_SKIP

tests/unit/debug_printf.cpp
Some local tests I found, were used to make sure DebugPrintf worked with the `OpArrayLength` correctly and figured it is worth adding
=> tests: Add SSBO Length DebugPrintf tests

layers/external/vma/vk_mem_alloc.h, layers/external/vma/vma.h, scripts/check_code_format.py
The main difference is it was in `3.1.0-development` version and now it is `3.1.0`
Adds very basic things like 1.4 header support
=> vma: Update VMA to 1.4 version

layers/stateless/sl_instance_device.cpp, tests/framework/layer_validation_tests.cpp, tests/unit/best_practices.cpp, tests/unit/portability_subset.cpp
From https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/8760#issuecomment-2442023146 and matches spec change in https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/6979 
This makes sure if you are using an extension like `VK_EXT_layer_settings` you need the `VkInstanceCreateInfo::ppEnabledExtensionNames` like any other extension
cc @charles-lunarg to make sure I am not overlooking anything obvious
=> layers: Add Extension Checks for Layer Extensions

layers/core_checks/cc_shader_interface.cpp, layers/core_checks/cc_spirv.cpp, layers/core_checks/core_validation.h, layers/state_tracker/shader_module.cpp, layers/state_tracker/shader_module.h, tests/unit/shader_interface.cpp, tests/unit/shader_interface_positive.cpp
(long details in https://gitlab.khronos.org/spirv/SPIR-V/-/issues/779)
but the tl;dr is we have no real CTS coverage or spec language around using a pointer for a shader interface and how it works for things like the amount of `Location` slots used
For the time being, we should at least warn the users as this is ticking timebomb for someone to get trapped in. Also having these tests help regression around the shader interface code that has to dance around this
=> layers: Add warning for using Pointer in shader interface

tests/unit/host_image_copy.cpp, tests/unit/host_image_copy_positive.cpp
`separateDepthStencilLayouts` was set for all Host Image Copy test, but shouldn't be needed and prevented `TransitionImageLayoutDepthStencil` tests from working (on latest Mesa driver that supports depth copies)
=> tests: Remove separateDepthStencilLayouts from init

layers/core_checks/cc_cmd_buffer_dynamic.cpp, tests/unit/dynamic_state.cpp, tests/unit/shader_object.cpp, tests/unit/shader_object_positive.cpp
For change in https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/7099
New VU error looks like
> [ VUID-vkCmdDraw-None-07751 ] vkCmdDraw(): vkCmdSetDiscardRectangleEXT was not set for discard rectangle index 1 for this command buffer. Need to set once for each in discardRectangleCount (2). (There was a call to vkCmdBindPipeline that didn't have VK_DYNAMIC_STATE_DISCARD_RECTANGLE_EXT and invalidated the prior vkCmdSetDiscardRectangleEXT call).
=> layers: Combine vkCmdSetDiscardRectangleEXT check

tests/unit/wsi.cpp
Apparently swapchain_images.size() can sometimes be > 1
=> tests: Fix ASAN error in SwapchainMaintenance1ExtensionRelease

layers/VkLayer_khronos_validation.json.in, layers/error_message/logging.cpp, layers/error_message/logging.h, layers/layer_options.cpp
Something I found useful when working with error message code. Helps to finds changes/regressions by removing dispatchable handles for comparison purposes. 
The usual scenario I run entire test suite of negative tests with `--print-vu` + `--gtest_print_time=0` and output result to a file. Then do the code changes, generate another file and compare them. For syncval negative tests if there are no changes then two files are binary equal (should be the same for other tests).
This also works with captures, but the message callback in addition to the main message can add additional fields that vary. This happens for example in doom capture, but added information is always on separate lines which adds a constant diff and it is still easy to detect changes. For CS2 there is no such difference …
=> layers: Add debug option to help compare error messages

layers/core_checks/cc_device_memory.cpp, layers/core_checks/core_validation.h, tests/unit/memory.cpp
This was discussed a LOT in the working group last two weeks (https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/7073)
Basically this **should** be a VU, but can't because of technically it is "defined" what the app will return, but this is impossible for CTS to catch and there is no hardware vendor had a reason why an app should ever try to go above this limit, so we are adding it as a pro-active error
=> layers: Move maxMemoryAllocationSize check

layers/core_checks/cc_pipeline_graphics.cpp, layers/sync/sync_reporting.cpp, layers/sync/sync_utils.cpp, layers/sync/sync_utils.h, layers/utils/vk_layer_utils.h, tests/unit/sync_val.cpp, tests/unit/sync_val_reporting.cpp
Use native Vulkan stage/access constants instead of synval internal representation in the error messages.
Using native constants is more familiar to the users but also provides opportunity to use meta stages to have simpler messages.
Log of doom capture error messages is reduced from 105Kb -> 69Kb.
`write_barriers` extra property before:
> write_barriers = SYNC_COMPUTE_SHADER_SHADER_BINDING_TABLE_READ|SYNC_COMPUTE_SHADER_SHADER_SAMPLED_READ|SYNC_COMPUTE_SHADER_SHADER_STORAGE_READ|SYNC_COMPUTE_SHADER_SHADER_STORAGE_WRITE|SYNC_COMPUTE_SHADER_UNIFORM_READ|SYNC_ACCELERATION_STRUCTURE_COPY_ACCELERATION_STRUCTURE_READ|SYNC_ACCELERATION_STRUCTURE_COPY_ACCELERATION_STRUCTURE_WRITE|SYNC_ACCELERATION_STRUCTURE_COPY_TRANSFER_READ|SYNC_ACCELERATION_STRUCTURE_COPY_TRANSFER_WRITE|SYNC_COPY_TRANSFER_READ …
=> sync: Implement new formatting of syncval accesses

layers/drawdispatch/descriptor_validator.cpp, tests/unit/gpu_av_descriptor_post_process.cpp, tests/unit/gpu_av_descriptor_post_process_positive.cpp, tests/unit/shader_image_access.cpp, tests/unit/shader_image_access_positive.cpp
I reworked things in https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/8864 that I wasn't sure if we still needed `is_descriptor_potentially_aliased`
Added tests and see it was too restrictive and we could remove it
=> gpuav: Remove legacy Alias check

tests/unit/gpu_av_buffer_device_address.cpp, tests/unit/gpu_av_buffer_device_address_positive.cpp, tests/unit/gpu_av_spirv_positive.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/7462
enabled these, they seem to work now, likely implicitly from the re-working of all the SPIR-V in the last year
=> tests: Enabled disabled BDA tests

layers/sync/sync_validation.cpp, layers/sync/sync_validation.h, tests/CMakeLists.txt, tests/framework/layer_validation_tests.h, tests/framework/ray_tracing_objects.cpp, tests/framework/ray_tracing_objects.h, tests/unit/sync_val_positive.cpp, tests/unit/sync_val_ray_tracing.cpp, tests/unit/sync_val_ray_tracing_positive.cpp
Adds the first syncval ray tracing related validation. The goal is to validate ray tracing memory accesses for the next SDK.
=> sync: Make the first step to validate ray tracing API

tests/framework/layer_validation_tests.cpp, tests/framework/layer_validation_tests.h, tests/framework/pipeline_helper.cpp, tests/unit/debug_printf.cpp, tests/unit/dynamic_rendering.cpp, tests/unit/dynamic_state.cpp, tests/unit/gpu_av_descriptor_class_general_buffer.cpp, tests/unit/gpu_av_descriptor_class_general_buffer_positive.cpp, tests/unit/graphics_library.cpp, tests/unit/graphics_library_positive.cpp, tests/unit/pipeline_positive.cpp, tests/unit/protected_memory.cpp, tests/unit/shader_spirv_positive.cpp
std::size is available since C++ 17.
Also use size32() helper for uint32_t values.
In existing code 64 to 32 uint casts work without warning due to warning suppression. Maybe in the future we'll be able re-enable it.
=> tests: Remove size helper in favor of std::size

layers/core_checks/cc_descriptor.cpp, tests/unit/descriptor_buffer.cpp, tests/unit/descriptor_buffer_positive.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/9228
=> layers: Fix missing usage2 in VkDescriptorBufferBindingInfoEXT

layers/gpuav/instrumentation/gpuav_instrumentation.cpp, layers/gpuav/instrumentation/gpuav_shader_instrumentor.h, layers/state_tracker/pipeline_state.cpp, layers/state_tracker/pipeline_state.h
Found using `VK_LAYER_PRINTF_ONLY_PRESET` slows down things way too much by default. With this change, find that when an app uses no printf in their shader (because assuming only 1 of there many pipelines will even have it) you regain near "normal" FPS again
note - `VK_LAYER_PRINTF_ONLY_PRESET` turns off everything but DebugPrintf just like vkconfig does
=> printf: Don't do work when there is no printf instruction

layers/sync/sync_validation.h, layers/vulkan/generated/dispatch_object.cpp, scripts/generators/dispatch_object_generator.py
This is the start of splitting class ValidationObject into separate Device and Instance classes. Syncval has nothing happening at Instance level so it gets to go first. Once all the leaf classes are split, ValidationStateTracker and ValidationObject can be split. This seems backwards but allows it to happen incrementally rather than in 1 giant PR
=> syncval: Split Device and Instance ValidationObjects

layers/gpuav/instrumentation/gpuav_instrumentation.cpp, tests/unit/gpu_av.cpp
https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/9266 plus fix for `UseAllDescriptorSlotsPipelineLayout`
=> gpuav: Fix UseAllDescriptorSlotsPipelineLayout

CMakeLists.txt, layers/CMakeLists.txt, layers/chassis/chassis_manual.cpp, layers/profiling/profiling.cpp, layers/profiling/profiling.h, layers/profiling/profiling.md, layers/state_tracker/state_tracker.cpp, layers/state_tracker/state_tracker.h, layers/vulkan/generated/chassis.cpp, layers/vulkan/generated/validation_object.cpp, layers/vulkan/generated/validation_object_methods.h, scripts/generators/layer_chassis_generator.py
Add initial support for Tracy GPU profiling
=> Allows to get GPU timings for GPU commands. For now, only draws, dispatches and trace rays commands are profiled.
Some implementation details:
GPU profiling relies on timestamp queries. Timestamps have to be added to command buffers, their status is then queried from the host, and available queried are reset after inspection, with a call to `vkCmdResetQueryPool`.
A worker thread is in charge of scanning query results, doing it on the main threads showed serious performance issues.
From testing against GFXR traces threading seems to work, still need to test on live games. A review on this threading part would be especially appreciated!
And if you can time the time to pull this PR and test it locally, that would be awesome, since no new CI …
=> vvl: Add Tracy GPU profiling

layers/core_checks/cc_pipeline_graphics.cpp
removes `vkuFormatElementIsTexel` to go along with https://github.com/KhronosGroup/Vulkan-Utility-Libraries/pull/260
=> layers: Remove vkuFormatElementIsTexel

layers/core_checks/cc_buffer.cpp, layers/core_checks/cc_copy_blit_resolve.cpp, layers/core_checks/cc_descriptor.cpp, layers/core_checks/cc_image.cpp, layers/core_checks/cc_pipeline_graphics.cpp, layers/core_checks/cc_shader_interface.cpp, layers/gpuav/descriptor_validation/gpuav_descriptor_set.cpp, layers/gpuav/validation_cmd/gpuav_draw.cpp, layers/stateless/sl_image.cpp, layers/utils/vk_layer_utils.cpp, layers/utils/vk_layer_utils.h, scripts/known_good.json, tests/unit/buffer.cpp, tests/unit/descriptor_buffer.cpp
Uses 
- https://github.com/KhronosGroup/Vulkan-Utility-Libraries/pull/261
- https://github.com/KhronosGroup/Vulkan-Utility-Libraries/pull/262
- https://github.com/KhronosGroup/Vulkan-Utility-Libraries/pull/263
Main aim to get rid of things like `vkuFormatElementSize` (as `element` is not a proper spec term) and stick to `texel` and `texel blocks`
Also where these are used (ex - vertex input, texel buffer, etc) have different inherent spec restrictions that the current code was assuming, but hard to track down
=> layers: Update how we do format size checks

layers/gpuav/core/gpuav_setup.cpp, layers/gpuav/debug_printf/debug_printf.cpp, layers/gpuav/descriptor_validation/gpuav_descriptor_set.cpp, layers/gpuav/resources/gpuav_state_trackers.cpp
Showed significant gains for the Tiny Mesh Large sample: Modifying so that it emits OOB errors, render passes are ~300 ms long without this change, and ~20 ms with it (baseline without GPU-AV instrumentation: ~2.5 ms)
=> gpuav: Switch to device local allocations

layers/containers/custom_containers.h, layers/core_checks/cc_pipeline_graphics.cpp, layers/core_checks/cc_ray_tracing.cpp, layers/core_checks/cc_render_pass.cpp, layers/gpuav/descriptor_validation/gpuav_image_layout.cpp, layers/gpuav/instrumentation/gpuav_shader_instrumentor.cpp, layers/gpuav/validation_cmd/gpuav_copy_buffer_to_image.cpp, layers/layer_options.cpp, layers/state_tracker/pipeline_layout_state.cpp, layers/state_tracker/pipeline_sub_state.cpp, layers/state_tracker/ray_tracing_state.h, layers/state_tracker/state_tracker.cpp, layers/stateless/sl_descriptor.cpp, layers/stateless/sl_ray_tracing.cpp, layers/sync/sync_validation.cpp, layers/utils/ray_tracing_utils.cpp, tests/framework/ray_tracing_objects.cpp, tests/unit/gpu_av_buffer_device_address.cpp, tests/unit/gpu_av_buffer_device_address_positive.cpp, tests/unit/gpu_av_positive.cpp, tests/unit/sparse_buffer_positive.cpp, tests/vvl_utils/small_vector.cpp
This matches behavior of `std::views::enumerate` - enumerated object is returned as a reference instead of a pointer.
Would minimize changes if we start using C++ 23 in the future.
=> layers: Update vvl::enumerate to return reference

layers/state_tracker/pipeline_state.h, layers/state_tracker/shader_module.cpp, layers/state_tracker/shader_stage_state.cpp, layers/state_tracker/shader_stage_state.h, tests/unit/descriptors.cpp, tests/unit/gpu_av_descriptor_class_general_buffer_positive.cpp
all from https://gitlab.khronos.org/vulkan/vulkan/-/issues/4145
Basically if you go
```glsl
layout(set = 0, binding = 0) buffer SSBO {
uint x[];
};
void main() {
x.length();
}
```
here `x` is **not** accessed, but the descriptor is still referenced and counts as statically used. The lack of marking this as statically used was preventing tracking and didn't appear until late
=> layers: Mark OpArrayLength as static usage

layers/core_checks/cc_copy_blit_resolve.cpp, layers/core_checks/cc_image.cpp, layers/stateless/sl_image.cpp, layers/utils/vk_layer_utils.cpp, layers/utils/vk_layer_utils.h, tests/unit/copy_buffer_image.cpp, tests/unit/copy_buffer_image_positive.cpp, tests/unit/image_positive.cpp
More cleanup around using `texel` and `texel block` correctly and consistently everywhere
=> layers: More cleaup of format size compatibility

layers/core_checks/cc_copy_blit_resolve.cpp, layers/core_checks/cc_image_layout.cpp, tests/unit/ycbcr.cpp
Was
```
vkCopyMemoryToImageEXT(): vkCopyMemoryToImageEXT(): pCopyMemoryToImageInfo->pRegions[0].imageSubresource.aspectMask VK_IMAGE_ASPECT_DEPTH_BIT invalid for image format VK_FORMAT_R8G8B8A8_UNORM.
vkCmdCopyImage(): pRegions[0].dstSubresource.aspectMask (VK_IMAGE_ASPECT_PLANE_0_BIT) cannot specify aspects not present in destination image (VK_FORMAT_D32_SFLOAT).
```
Is now 
```
vkCopyMemoryToImageEXT(): pCopyMemoryToImageInfo->pRegions[0].imageSubresource.aspectMask (VK_IMAGE_ASPECT_DEPTH_BIT) is invalid for image format VK_FORMAT_R8G8B8A8_UNORM. (Valid VkImageAspectFlags are VK_IMAGE_ASPECT_COLOR_BIT).
vkCmdCopyImage(): pRegions[0].dstSubresource.aspectMask (VK_IMAGE_ASPECT_PLANE_0_BIT) is invalid for destination image format VK_FORMAT_D32_SFLOAT. (Valid VkImageAspectFlags are …
```
=> layers: Give better Valid AspectMask errors

layers/sync/sync_op.cpp, layers/sync/sync_op.h
This code was historically a bit hard to follow because of generic naming in factory classes (e.g. `MakeApplyFunctor`). Also editor navigation did not work because of templated types.
=> sync: Replace SyncOp factories with regular functions

layers/sync/sync_op.cpp, layers/sync/sync_op.h, layers/sync/sync_validation.cpp
`SyncOpBarriers` does not bring much value.
It holds a list of barriers for derived classes but multiple barriers are used only by Events (sync2) but not by PipelineBarrier.
Now specific classes use the most suitable representation.
=> sync: Remove SyncOpBarriers helper class

layers/gpuav/instrumentation/gpuav_shader_instrumentor.cpp, layers/state_tracker/pipeline_state.h, layers/state_tracker/shader_object_state.h
Deleting an element from instrumented_shaders_map_ was too slow
=> gpuav: Improve shader map management

layers/sync/sync_access_state.cpp, layers/sync/sync_access_state.h, layers/sync/sync_op.h, layers/sync/sync_submit.cpp
* Remove `SyncExecScope ::expanded_state` which is not used
* Break dependency between `BatchBarrierOp` and `PipelineBarrierOp` (inheritance). It easier not to inherit, than inherit and then deal with inherited members that are not applicated to the derived type.
=> sync: Minor cleanup

layers/vulkan/generated/dispatch_object.cpp, layers/vulkan/generated/object_tracker.cpp, layers/vulkan/generated/object_tracker_device_methods.h, layers/vulkan/generated/stateless_validation_helper.cpp, scripts/generators/base_generator.py, scripts/generators/object_tracker_generator.py, tests/framework/binding.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/9322
Basically the Struct Alias broke down because 
- `vkGetPipelinePropertiesEXT` has a `VkPipelineInfoEXT` param
- `vkGetPipelineExecutablePropertiesKHR` has a `VkPipelineInfoKHR` param
=> scripts: Fix struct alias codegen from command param

layers/core_checks/cc_descriptor.cpp, layers/stateless/sl_ray_tracing.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/9314
Fixes both Descriptor Indexing and Ray Tracing Invocation limits to use `uint64_t` to prevent overflow
I went through the rest of the limits, the rest already use 64-bit for checking or are not feasible to ever hit 64-bit without blowing up other things first
=> layers: Fix DescriptorIndexing limit overflows

layers/sync/sync_access_state.cpp, layers/sync/sync_access_state.h, layers/sync/sync_op.cpp, layers/sync/sync_op.h, tests/unit/sync_val_reporting.cpp
Reports image handle for `vkCmdPipelineBarrier` layout transition error.
Closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/9278
Render pass layout transitions still need to be investigated but don't want to touch that subsystem for now. Will revisit when start working on error messages there.
=> sync: Report image handle in layout transition error

.github/workflows/vvl.yml
Found that a debug build running the tests has never caught anything that a release build running the tests didn't
There are a few places we have `#if debug` types wrappers around, so at least building for debug is important, but can save time running it
(also we run Debug builds in internal CI, so things are still being tested)
=> ci: Only have Debug build and not re-run tests

layers/core_checks/cc_descriptor.cpp
Fixed the error message for VkDescriptorBufferInfo-range-00342.  Swapped the (incorrect) '+' for a '-'.
Relevant doc:
https://registry.khronos.org/vulkan/specs/latest/man/html/VkDescriptorBufferInfo.html#VUID-VkDescriptorBufferInfo-range-00342
=> Fix message for VkDescriptorBufferInfo-range-00342

tests/unit/sync_val.cpp, tests/unit/sync_val_positive.cpp
Split up big test into several parts.
Remove  CmdFillBuffer/CmdUpdateBuffer sections since we have separate tests for these functions.
=> tests: Cleanup syncval buffer copy test

layers/core_checks/cc_pipeline_graphics.cpp, layers/core_checks/core_validation.h, layers/state_tracker/pipeline_sub_state.cpp, layers/state_tracker/state_tracker.cpp, layers/state_tracker/vertex_index_buffer_state.h, tests/unit/best_practices_positive.cpp, tests/unit/multiview.cpp, tests/unit/vertex_input.cpp, tests/unit/vertex_input_positive.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/9305
We had the VUs a bit mixed up
-  `VUID-vkCmdDraw-None-04007` - Makes sure you call `vkCmdBindVertexBuffers` on the binding
-  `VUID-vkCmdDraw-None-04008` - If you bound VK_NULL_HANDLE, need `nullDescriptor`
- ` VUID-vkCmdDraw-None-02721` - The values are OOB inside (also done on GPU-AV)
=> layers: Fix vertex input when unused

layers/core_checks/cc_device_memory.cpp, layers/core_checks/cc_external_object.cpp, layers/core_checks/core_validation.h, layers/stateless/sl_external_object.cpp, layers/vulkan/generated/feature_requirements_helper.cpp, tests/CMakeLists.txt, tests/unit/external_memory_metal.cpp
Cannot be merged until the extension is released since we require the actual headers with the extension in them to merge. Just looking for a LGTM to push this through the release pipeline
=> VK_EXT_external_memory_metal validation and tests

layers/best_practices/best_practices_validation.h, layers/best_practices/bp_copy_blit_resolve.cpp, layers/best_practices/bp_drawdispatch.cpp, layers/best_practices/bp_render_pass.cpp, layers/core_checks/cc_cmd_buffer.cpp, layers/core_checks/cc_cmd_buffer_dynamic.cpp, layers/core_checks/cc_device.cpp, layers/core_checks/cc_device_generated_commands.cpp, layers/core_checks/cc_drawdispatch.cpp, layers/core_checks/cc_image.cpp, layers/core_checks/cc_image_layout.cpp, layers/core_checks/cc_pipeline.cpp, layers/core_checks/cc_pipeline_graphics.cpp, layers/core_checks/cc_query.cpp, layers/core_checks/cc_render_pass.cpp, layers/core_checks/cc_shader_object.cpp, layers/core_checks/cc_synchronization.cpp, layers/core_checks/core_validation.h, layers/gpuav/core/gpuav_record.cpp, layers/gpuav/descriptor_validation/gpuav_image_layout.cpp, layers/gpuav/validation_cmd/gpuav_validation_cmd_common.cpp, layers/state_tracker/cmd_buffer_state.cpp, layers/state_tracker/cmd_buffer_state.h, layers/state_tracker/pipeline_state.h, layers/state_tracker/render_pass_state.h, layers/state_tracker/state_tracker.cpp, layers/sync/sync_commandbuffer.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/9334
so `vvl::RenderPass`
- For normal vulkan1.0 we create this at `vkCreateRenderPass` time
- For Dynamic Rendering, we create the object on the spot
- There are 2 places that consume render passes (command buffer and pipeline)
- Both need to either consume a `VkRenderPass` handle or create a `vvl::RenderPass` on the spot
- The command buffer state had some issue tracking what is a
- RenderPass state value (something you would find in  vkCreateRenderPass)
- RenderPass begin value (something at vkCmdBeginRenderPass/vkCmdBeginRendering)
- I try to pass around references/null check things early like we do for the other "normal" state objects
=> layers: Full cleanup how we do vvl::RenderPass

layers/containers/subresource_adapter.h, layers/external/inplace_function.h
These are deprecated in c++23.
Note: in the one instance where the default Align value was used for std::aligned_storage<Len, Alignment> (i.e.
std::aligned_storage<Len>), this patch now adopts an implementation similar to libc++ to avoid behavior changes.
=> build: Remove usage of deprecated std::aligned_storage/union

layers/error_message/unimplementable_validation.h
part of https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/9338
=> layers: Add Instance Implicit to unimplementable

layers/sync/sync_commandbuffer.h, layers/sync/sync_error_messages.cpp, layers/sync/sync_error_messages.h, layers/sync/sync_reporting.cpp, layers/sync/sync_reporting.h, layers/sync/sync_submit.h, layers/sync/sync_validation.cpp, tests/unit/sync_val.cpp, tests/unit/sync_val_reporting.cpp
This demonstrates new style of synval error messages. Only one specific use case is updated. The following work will involve converting other messages and reworking reporting helpers.
OLD:
> vkCmdCopyBuffer(): Hazard WRITE_AFTER_WRITE for dstBuffer VkBuffer 0xf443490000000006[], region 0. Access info (usage: SYNC_COPY_TRANSFER_WRITE, prior_usage: SYNC_COPY_TRANSFER_WRITE, write_barriers: VK_ACCESS_2_TRANSFER_WRITE_BIT accesses on VK_PIPELINE_STAGE_2_CLEAR_BIT stage, command: vkCmdCopyBuffer, resource: VkBuffer 0xf443490000000006[]).
NEW:
> vkCmdCopyBuffer(): WRITE_AFTER_WRITE hazard detected. vkCmdCopyBuffer writes to VkBuffer 0xf443490000000006[], which was written earlier by another vkCmdCopyBuffer command. The existed synchronization protects VK_ACCESS_2_TRANSFER_WRITE_BIT accesses at …
=> sync: Add example of new style of syncval reporting

BUILD.gn, layers/CMakeLists.txt, layers/error_message/logging.cpp, layers/sync/sync_commandbuffer.cpp, layers/sync/sync_error_messages.cpp, layers/sync/sync_validation.cpp, layers/utils/text_utils.cpp, layers/utils/text_utils.h, layers/utils/vk_layer_utils.h
Add helper to share implementation between logging.cpp and syncval. The helper also addresses some issues in the implementation from logging.cpp.
=> layers: Move syncval format helper to shared utils

layers/gpuav/debug_printf/debug_printf.cpp, layers/gpuav/instrumentation/gpuav_shader_instrumentor.cpp, layers/gpuav/instrumentation/gpuav_shader_instrumentor.h, layers/gpuav/spirv/debug_printf_pass.cpp, layers/gpuav/spirv/debug_printf_pass.h, layers/gpuav/spirv/descriptor_class_general_buffer_pass.cpp, layers/gpuav/spirv/descriptor_class_texel_buffer_pass.cpp, layers/gpuav/spirv/function_basic_block.cpp, layers/gpuav/spirv/function_basic_block.h, layers/gpuav/spirv/inject_conditional_function_pass.cpp, layers/gpuav/spirv/inject_function_pass.cpp, layers/gpuav/spirv/interface.h, layers/gpuav/spirv/module.cpp, layers/gpuav/spirv/post_process_descriptor_indexing.cpp, layers/gpuav/spirv/post_process_descriptor_indexing_pass.cpp, layers/gpuav/spirv/vertex_attribute_fetch_oob.cpp, layers/utils/shader_utils.cpp, layers/utils/shader_utils.h
Currently for linked in functions we just cheated and put everything in `pre_block_inst_`
This creates a proper `BasicBlock` to store the linked function instructions. This will allow being able to run the DebugPrintf on instrumented code
=> gpuav: Add fix to allow instrumeting linked functions

layers/error_message/unimplementable_validation.h
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/9254
=> vvl: Unimplementable RT replay related VUs

layers/state_tracker/descriptor_sets.cpp, layers/state_tracker/descriptor_sets.h
We had 2 `operator==(const DescriptorSetLayoutDef &lhs, const DescriptorSetLayoutDef &rhs)` and removes the one from the header
=> layers: Remove duplicate DescriptorSetLayoutDef compare

tests/unit/dynamic_state.cpp, tests/unit/shader_cooperative_matrix.cpp
`NegativeShaderCooperativeMatrix.MatchSizeWithProperties` and `NegativeDynamicState.RebindSamePipeline` were failing on ToT RADV for me and here are some quick fixes
=> tests: Fix tests failing on RADV ToT

layers/core_checks/cc_copy_blit_resolve.cpp, tests/unit/copy_buffer_image.cpp
Closes #9354 
I don't see a way to get one without the other
=> Validate 2d image blit with invalid z offsets

layers/gpuav/descriptor_validation/gpuav_descriptor_set.cpp, layers/gpuav/descriptor_validation/gpuav_descriptor_set.h, layers/gpuav/descriptor_validation/gpuav_descriptor_validation.cpp, tests/unit/gpu_av_descriptor_post_process_positive.cpp
Hit a crash in a trace using GPU-AV, root issue was the Descriptor Set was created with `VkDescriptorSetLayoutCreateInfo::bindingCount = 0` 
In this case, we save resources and don't create a Post Processing buffer (there are no descriptors in it!)
but then we were mixing up this case with a case where the somehow we did lose track of the descriptor
=> gpuav: Fix Post Processing failing on zero bindingCount

layers/gpuav/shaders/gpuav_error_codes.h
Future extension has GPU-AV support, want to make rebasing easier for the error group, so reserving
=> gpuav: Reserve Error Group

layers/sync/sync_commandbuffer.cpp, layers/sync/sync_commandbuffer.h, layers/sync/sync_error_messages.cpp, layers/sync/sync_reporting.cpp, layers/sync/sync_reporting.h, layers/sync/sync_submit.h
Used `NegativeSyncVal.BufferCopy` test as work scope to convert its errors to new style. Code is of r&d style (ugly), the focus it to finalize message structure first. Need to go over more use cases to have better idea which formatting helpers will be needed.
`WRITE_AFTER_READ` hazard for buffer copy without barrier:
OLD:
> vkCmdCopyBuffer(): Hazard WRITE_AFTER_READ for dstBuffer VkBuffer 0xf56c9b0000000004[], region 0. Access info (usage: SYNC_COPY_TRANSFER_WRITE, prior_usage: SYNC_COPY_TRANSFER_READ, read_barriers: VkPipelineStageFlags2(0), command: vkCmdCopyBuffer, resource: VkBuffer 0xf56c9b0000000004[]).
NEW: 
> vkCmdCopyBuffer(): WRITE_AFTER_READ hazard detected. vkCmdCopyBuffer writes to VkBuffer 0xf56c9b0000000004[], which was previously read by another vkCmdCopyBuffer command. No …
=> sync: Convert NegativeSyncVal.BufferCopy errors to new style

tests/unit/descriptors_positive.cpp
RADV doesn't support `VK_DESCRIPTOR_TYPE_ACCELERATION_STRUCTURE_KHR` for `VK_DESCRIPTOR_TYPE_MUTABLE_EXT` and needs to be checked
=> tests: Check if AS are supported for mutable

layers/sync/sync_commandbuffer.cpp, layers/sync/sync_error_messages.cpp, layers/sync/sync_error_messages.h, layers/sync/sync_op.cpp, layers/sync/sync_renderpass.cpp, layers/sync/sync_reporting.cpp, layers/sync/sync_reporting.h, layers/sync/sync_submit.cpp, layers/sync/sync_validation.cpp
Add these properties (used by most commands):
`hazard_type`, `command`, `prior_command`
Remove: `resource_parameter`. Can be derived from `hazard_type`
=> sync: Add new report properties

layers/CMakeLists.txt
The cmake minimum is now 3.22.1
=> cmake: Remove outdated check

.github/workflows/sdk_android_build.yml
Currently the wrong NDK version is being printed during releases.
=> ci: Remove hardcoded NDK version number

layers/state_tracker/cmd_buffer_state.cpp
VkPipelineBindPoint doesn't index nicely into an array.
i.e. VK_PIPELINE_BIND_POINT_RAY_TRACING_KHR = 1000165000
Note I found this issue by trying to compile the VVL codebase with `-fsanitize=undefined` as an experiment:
https://clang.llvm.org/docs/UndefinedBehaviorSanitizer.html
<details>
<summary>Compiler Error</summary>
```
[153/427] Building CXX object layers/CMakeFiles/vvl.dir/state_tracker/cmd_buffer_state.cpp.o
FAILED: layers/CMakeFiles/vvl.dir/state_tracker/cmd_buffer_state.cpp.o 
ccache /usr/bin/c++ -DVK_ENABLE_BETA_EXTENSIONS -DVK_USE_PLATFORM_WAYLAND_KHR -DVK_USE_PLATFORM_XCB_KHR -DVK_USE_PLATFORM_XLIB_KHR -DVK_USE_PLATFORM_XLIB_XRANDR_EXT -Dvvl_EXPORTS -I/home/runner/work/Vulkan-ValidationLayers/Vulkan-ValidationLayers/layers/. …
```
=> layers: Fix -Werror=array-bounds error

layers/sync/sync_error_messages.cpp, layers/sync/sync_error_messages.h, layers/sync/sync_reporting.h, layers/sync/sync_validation.cpp
> vkCmdCopyBuffer(): WRITE_AFTER_WRITE hazard detected. vkCmdCopyBuffer writes to VkBuffer 0xf443490000000006[], which was previously written by another vkCmdCopyBuffer command. The current synchronization protects VK_ACCESS_2_TRANSFER_WRITE_BIT accesses at VK_PIPELINE_STAGE_2_CLEAR_BIT but not at VK_PIPELINE_STAGE_2_COPY_BIT. **Hazardous copy region: 0 (offset = 0, size = 256).**
=> sync: Add copy region info to buffer messages

layers/state_tracker/device_memory_state.cpp
A lot of CTS tests assert here when they use sparse resources. They seem to pass fine if the assert is just removed
=> sync: Replace unsupported sparse assert with todo comment

layers/error_message/spirv_logging.cpp, layers/error_message/spirv_logging.h, layers/gpuav/debug_printf/debug_printf.cpp, layers/gpuav/instrumentation/gpuav_instrumentation.cpp, layers/gpuav/instrumentation/gpuav_shader_instrumentor.cpp, layers/gpuav/instrumentation/gpuav_shader_instrumentor.h, layers/gpuav/spirv/instruction.h, layers/state_tracker/shader_instruction.cpp, layers/state_tracker/shader_instruction.h, layers/state_tracker/shader_module.cpp, layers/state_tracker/shader_module.h
@arno-lunarg found https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/9381 was not good enough and we need to not use `spirv::Instruction` at all and resort to doing old-fashion `vector<uint32_t>` parsing
Added some helpers and I think it is tolerable (as parsing SPIR-V can be)
=> gpuav: Do GPU-AV Post Processing with uint32_t only

layers/core_checks/cc_device_memory.cpp, tests/unit/android_hardware_buffer.cpp, tests/unit/external_memory_sync.cpp, tests/unit/memory.cpp, tests/unit/wsi.cpp
=> Validate required dedicated allocations

layers/core_checks/cc_spirv.cpp, layers/error_message/spirv_logging.cpp, layers/gpuav/instrumentation/gpuav_shader_instrumentor.cpp, layers/state_tracker/shader_module.cpp, tests/unit/atomics.cpp, tests/unit/debug_printf_shader_debug_info.cpp, tests/unit/gpu_av_shader_debug_info.cpp, tests/unit/shader_debug_info.cpp, tests/unit/shader_object.cpp
main thing is just like I would get a gcc/clang error `layers/core_checks/cc_spirv.cpp:400:30` I would expect the same from the Shader Debug Info as well
also add more tests
=> spirv: Change file name to match gcc/clang

layers/error_message/error_location.h, layers/sync/sync_error_messages.cpp, layers/sync/sync_error_messages.h, layers/sync/sync_reporting.cpp, layers/sync/sync_reporting.h, layers/sync/sync_validation.cpp
* Extracted formatting code that potentially can be used in many error messages.
* Update some of the video error messages to use this shared helper (video tests use the most general `ErrorMessages::Error` message type and it was the simplest place to start).
OLD:
> vkCmdEncodeVideoKHR(): pEncodeInfo->pSetupReferenceSlot->pPictureResource Hazard WRITE_AFTER_READ for reconstructed picture. Access info (usage: SYNC_VIDEO_ENCODE_VIDEO_ENCODE_WRITE, prior_usage: SYNC_VIDEO_ENCODE_VIDEO_ENCODE_READ, read_barriers: VkPipelineStageFlags2(0), command: vkCmdEncodeVideoKHR).
NEW:
> vkCmdEncodeVideoKHR(): WRITE_AFTER_READ hazard detected. vkCmdEncodeVideoKHR writes to reconstructed picture pEncodeInfo->pSetupReferenceSlot->pPictureResource {VkImageView 0xd5b26f0000000010[], codedOffset (x = 0, y = …
=> sync: Error messages update

layers/sync/sync_error_messages.cpp, layers/sync/sync_error_messages.h, layers/sync/sync_validation.cpp
Initial categorization of message types was done based on pattern matching message code. Now, going over errors one by one, some things can be unified further.
=> sync: Replace VideoReferencePictureError with general Error

layers/sync/sync_error_messages.cpp, layers/sync/sync_validation.cpp, tests/framework/ray_tracing_objects.cpp, tests/unit/sync_val_ray_tracing.cpp, tests/unit/sync_val_ray_tracing_positive.cpp
> vkCmdBuildAccelerationStructuresKHR(): WRITE_AFTER_READ hazard detected. vkCmdBuildAccelerationStructuresKHR writes to VkBuffer 0xcfef35000000000a[], which backs VkAccelerationStructureKHR 0xe88693000000000c[] and was previously read by vkCmdCopyBuffer. No sufficient synchronization is present to ensure that a write (VK_ACCESS_2_ACCELERATION_STRUCTURE_WRITE_BIT_KHR) at VK_PIPELINE_STAGE_2_ACCELERATION_STRUCTURE_BUILD_BIT_KHR does not conflict with a prior read (VK_ACCESS_2_TRANSFER_READ_BIT) at VK_PIPELINE_STAGE_2_COPY_BIT. An execution dependency is sufficient to prevent this hazard. Buffer access region: (offset = 0, size = 2304).
=> sync: Validate destination acceleration structure build

docs/syncval_usage.md
Someone asked at Vulkanized how to turn on Sync Val, realized doc was a bit non-helpful explaining
=> docs: Improve how to turn on Sync Val

layers/sync/sync_error_messages.cpp, layers/sync/sync_error_messages.h, layers/sync/sync_validation.cpp, tests/unit/sync_val_ray_tracing.cpp, tests/unit/sync_val_ray_tracing_positive.cpp
Some improvements to sync messages plus validation of *source* acceleration structure in the acceleration structure update operation. Complains like this:
> vkCmdBuildAccelerationStructuresKHR(): READ_AFTER_WRITE hazard detected. vkCmdBuildAccelerationStructuresKHR reads VkBuffer 0xcfef35000000000a[] (srcAccelerationStructure), which was previously written by another vkCmdBuildAccelerationStructuresKHR command. The buffer backs VkAccelerationStructureKHR 0xe88693000000000c[]. No sufficient synchronization is present to ensure that a read (VK_ACCESS_2_ACCELERATION_STRUCTURE_READ_BIT_KHR) at VK_PIPELINE_STAGE_2_ACCELERATION_STRUCTURE_BUILD_BIT_KHR does not conflict with a prior write (VK_ACCESS_2_ACCELERATION_STRUCTURE_WRITE_BIT_KHR) at the same stage. Buffer access region: (offset = 0, …
=> sync: Validate source acceleration structure

layers/sync/sync_reporting.cpp
The separator is used when the barrier protects accesses on multiple stages.
The ":" separator is used in the extra properties format (no spaces), but for regular message it should be a user-friendly separator (comma).
Regular message (fixed by this PR):
`ACCESS_SHADER_READ|ACCESS_SHADER_WRITE` accesses at `STAGE_VERTEX_SHADER`, `ACCESS_TRANFER_WRITE` accesses at `STAGE_COPY`
Property:
`STAGE_VERTEX_SHADER(ACCESS_SHADER_READ|ACCESS_SHADER_WRITE):STAGE_COPY(ACCESS_TRANFER_WRITE)`
Closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/9432
=> sync: Fix separator in access string

layers/sync/sync_validation.cpp
We caught this issue in a UBsan build of the Vulkan-ValidationLayer on Fuchsia where `PostCallRecordQueuePresentKHR()` tried to update a null QueueSyncState pointer, causing a nullptr dereference error. This change fixes the issue by skipping the update if `queue_state` is invalid.
=> sync: vkQueuePresentKHR: Skip updating queue state if queue is invalid.

BUILD.gn
vk_function_pointers.{cpp,h} is not supported on Fuchsia yet. Since this is only used in tests and we don't yet build Validation Layers tests on Fuchsia, it's okay to skip these files when building the validation layer library.
Test: Vulkan-ValidationLayers v1.4.304.1 with this change builds on Fuchsia tip-of-tree.
Bug: https://fxbug.dev/378964821
=> gn: Remove unsupported files for Fuchsia

layers/state_tracker/state_tracker.cpp, layers/state_tracker/state_tracker.h
This adds support for vkImportSemaphoreZirconHandleFUCHSIA() and vkGetSemaphoreZirconHandleFUCHSIA() to state_tracker. The logic is similar to fd and win32 handles.
Bug: https://fxbug.dev/379153784
Test: Fuchsia image-pipe-swapchain-test [1] passed with Vulkan- ValidationLayers vulkan-sdk-1.4.304.1 patched with this change.
[1] https://cs.opensource.google/fuchsia/fuchsia/+/main:src/lib/vulkan/tests/test_swapchain.cc
=> state: Support VkSemaphores imported with Zircon handles

layers/error_message/unimplementable_validation.h
Some `RuntimeSpirv` VUs that are not going to be added
=> layers: Add more deprecated VUIDs

BUILD.gn, layers/CMakeLists.txt, layers/core_checks/cc_spirv.cpp, layers/core_checks/core_validation.h, layers/vulkan/generated/spirv_validation_helper.cpp, layers/vulkan/generated/spirv_validation_helper.h, scripts/generate_source.py, scripts/generators/spirv_validation_generator.py
Need for future to fix https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/9129
Someone **not** in CoreChecks is going to need this
=> scripts: Move CompatibleSpirvImageFormat out of core checks

layers/sync/sync_commandbuffer.cpp, layers/sync/sync_error_messages.cpp, layers/sync/sync_error_messages.h, layers/sync/sync_reporting.h, tests/unit/sync_val.cpp
OLD:
> Hazard READ_AFTER_WRITE for VkImageView 0xcb3ee80000000007[], in VkCommandBuffer [], and VkPipeline 0xd175b40000000013[], VkDescriptorSet 0x967dd1000000000e[], type: VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER, imageLayout: VK_IMAGE_LAYOUT_GENERAL, binding #0, index 0. Access info (usage: SYNC_COMPUTE_SHADER_SHADER_SAMPLED_READ, prior_usage: SYNC_COPY_TRANSFER_WRITE, write_barriers: 0, command: vkCmdCopyImage, resource: VkImage 0xf56c9b0000000004[]).
NEW:
> READ_AFTER_WRITE hazard detected. Shader stage VK_SHADER_STAGE_COMPUTE_BIT reads VkImageView 0xcb3ee80000000007[], which was previously written by vkCmdCopyImage.
The image is referenced by a VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER descriptor in VkDescriptorSet 0x967dd1000000000e[], binding 0, image layout …
=> sync: Update buffer/image descriptor error messages

layers/core_checks/cc_descriptor.cpp
It says in the `VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER` description how YCbCr are required to be used with it. If the user hits this error message they have got down pretty far and need a brief "you can't try working around this" warning
=> layers: Small improvement to YCbCr error message

layers/sync/sync_commandbuffer.cpp, layers/sync/sync_error_messages.cpp, layers/sync/sync_error_messages.h
No need for special handling of these cases, existing `BufferError` function outputs the same information that was in the scope of the removed `DrawVertexBufferError` and `DrawIndexBufferError` functions.
=> sync: Update vertex/index buffer messages

layers/core_checks/cc_ray_tracing.cpp
No warnings without reason in Core Val
These are from an older, deprecated extension, so likely no desire to move to Best Practice
=> layers: Remove old NV Warnings

layers/containers/qfo_transfer.h, layers/core_checks/cc_synchronization.cpp, layers/core_checks/core_validation.h, tests/unit/sync_object.cpp, tests/unit/sync_object_positive.cpp
We have had these warnings in forever and they should just be part of best practice, but at this point, they are so baked into the QFOScoreboard logic, that rather just remove
If someone finds these warnings **so** important, we can change course, but this just smells like "we didn't touch because we think there might be a use case"
but no warnings allowed in Core Validation without a valid comment above explaining the rational
=> layers: Remove Queue Transfer Ownership warnings

layers/gpuav/debug_printf/debug_printf.cpp, layers/state_tracker/shader_instruction.cpp
2 small fixes pulled out of https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/9471
Basically tried to use DebugPrintf to debug GPU-AV and found 2 spots that could crash
=> printf: Fix using printf debugging GPUAV

layers/sync/sync_commandbuffer.cpp, layers/sync/sync_commandbuffer.h, layers/sync/sync_error_messages.cpp, layers/sync/sync_error_messages.h, layers/sync/sync_renderpass.cpp, layers/sync/sync_renderpass.h
Some improvements of how clear attachment code is structured before updating corresponding error messages.
=> sync: Refactor clear attachment code

layers/gpuav/spirv/debug_printf_pass.cpp, layers/gpuav/spirv/descriptor_class_general_buffer_pass.cpp, layers/gpuav/spirv/descriptor_class_texel_buffer_pass.cpp, layers/gpuav/spirv/inject_conditional_function_pass.cpp, layers/gpuav/spirv/inject_function_pass.cpp, layers/gpuav/spirv/module.cpp, layers/gpuav/spirv/module.h, layers/gpuav/spirv/pass.cpp, layers/gpuav/spirv/post_process_descriptor_indexing_pass.cpp
Noticed while doing https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/9471
We have this `Settings` struct, but were still duplicating everything inside another private field member of `Module`
=> gpuav: Make Module Setting fields not be repeated

layers/error_message/error_strings.h, layers/sync/sync_commandbuffer.cpp, layers/sync/sync_commandbuffer.h, layers/sync/sync_error_messages.cpp, layers/sync/sync_error_messages.h, layers/sync/sync_validation.cpp
> WRITE_AFTER_WRITE hazard detected. vkCmdClearAttachments clears VK_IMAGE_ASPECT_COLOR_BIT aspect of color attachment 0 (VkImageView 0xcad092000000000d[]) in subpass 0, which was previously written by vkCmdCopyImage.
No sufficient synchronization is present to ensure that a write (VK_ACCESS_2_COLOR_ATTACHMENT_WRITE_BIT) at VK_PIPELINE_STAGE_2_COLOR_ATTACHMENT_OUTPUT_BIT does not conflict with a prior write (VK_ACCESS_2_TRANSFER_WRITE_BIT) at VK_PIPELINE_STAGE_2_COPY_BIT.
Clear region: {
region_index = 0,
rect = {offset = {0, 0}, extent = {128, 64}},
baseArrayLayer = 0,
layerCount = 1
}
=> sync: Update clear attachment messages

layers/best_practices/best_practices_validation.h, layers/best_practices/bp_descriptor.cpp, layers/best_practices/bp_device_memory.cpp, layers/best_practices/bp_instance_device.cpp, layers/best_practices/bp_pipeline.cpp, layers/best_practices/bp_state.h, layers/best_practices/bp_wsi.cpp, layers/core_checks/cc_wsi.cpp, layers/state_tracker/descriptor_sets.cpp, layers/state_tracker/descriptor_sets.h, layers/state_tracker/device_memory_state.h, layers/state_tracker/device_state.h, layers/state_tracker/pipeline_state.cpp, layers/state_tracker/pipeline_state.h, layers/state_tracker/state_tracker.cpp, layers/state_tracker/state_tracker.h, layers/vulkan/generated/best_practices.cpp, scripts/generators/best_practices_generator.py
These are fairly simple and not likely to cause performance problems. Just get rid of them so that it is easier to change how state tracking works.
Image and CommandBuffer are a completely different story...
=> bp: Remove simple derived state objects

layers/error_message/unimplementable_validation.h, layers/stateless/sl_instance_device.cpp, tests/unit/instanceless.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/9479
I am the one who brought these 3 VUs on the world, I feel the need to amend my mistake before more and more developers waste time on this
=> layers: Remove VK_EXT_validation_features VU

layers/best_practices/bp_image.cpp, layers/best_practices/bp_instance_device.cpp, layers/best_practices/bp_synchronization.cpp, layers/core_checks/cc_copy_blit_resolve.cpp, layers/core_checks/cc_queue.cpp, layers/core_checks/cc_video.cpp, layers/state_tracker/cmd_buffer_state.cpp, layers/state_tracker/cmd_buffer_state.h, layers/state_tracker/video_session_state.h
Many of the callbacks don't use it. Those that do should just capture the device in their lambda. Eventually the way these callbacks get run will change and so that they'll be run by the state tracker on behalf of each validation object so the device arg will be wrong.
=> layers: Remove Device arg from various submit-time callbacks

layers/drawdispatch/descriptor_validator.cpp, tests/unit/descriptors.cpp, tests/unit/shader_storage_texel.cpp
follow up to https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/9487
Removes the early `return` in `ValidateDescriptor`
I assume they were there because the first check does need to return early (if the descriptor is not valid) but otherwise there was no good reason
=> layers: Use normal skip in ValidateDescriptor

layers/VkLayer_khronos_validation.json.in, layers/layer_options.cpp
So this has been a long time coming ...
Originally there were only errors, then many warnings snuck their way into Core Checks, eventually we decided create Best Practices to hold them, then we slowly moved all the warning from Core Checks to there. In the process we found that some things are actually "warnings" people care about and then become `LogUndefinedValue` in the code (https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/6707).
So as of today, if you are just using the normal/standard Core Validation the non-errors we have are
- Warning if you try setting a device extension at instance time (and vice versa)
- `vkGetDeviceProcAddr` trying to grab an instance level function
- Failing vkAllocateDescriptorSets because they are using a type not supported (details …
=> settings: Make warnings on by default

layers/VkLayer_khronos_validation.json.in, layers/error_message/logging.cpp, layers/error_message/logging.h, layers/layer_options.cpp, layers/vk_layer_settings.txt, layers/vulkan/generated/vk_object_types.cpp, layers/vulkan/generated/vk_object_types.h, scripts/generators/object_types_generator.py, tests/unit/debug_extensions.cpp, tests/unit/layer_settings.cpp, tests/unit/memory.cpp
Before
```
Validation Error: [ VUID-vkBindBufferMemory-buffer-07459 ] Object 0: handle = 0xe7f79a0000000005, name = memory_name, type = VK_OBJECT_TYPE_DEVICE_MEMORY; Object 1: handle = 0xfa21a40000000003, type = VK_OBJECT_TYPE_BUFFER; Object 2: handle = 0xf56c9b0000000004, type = VK_OBJECT_TYPE_DEVICE_MEMORY; | MessageID = 0x5001937c | vkBindBufferMemory(): attempting to bind VkDeviceMemory 0xe7f79a0000000005[memory_name] to VkBuffer 0xfa21a40000000003 which has already been bound to VkDeviceMemory 0xf56c9b0000000004.
```
now
```
Validation Error: [ VUID-vkBindBufferMemory-buffer-07459 ] Objects: VkDeviceMemory 0xe7f79a0000000005[memory_name]; VkBuffer 0xfa21a40000000003; VkDeviceMemory 0xf56c9b0000000004 | MessageID = 0x5001937c
vkBindBufferMemory(): attempting to bind VkDeviceMemory …
```
=> layers: Enhanced error message format

layers/core_checks/cc_render_pass.cpp, layers/core_checks/core_validation.h, tests/device_profiles/max_profile.json, tests/unit/fragment_shading_rate.cpp, tests/unit/fragment_shading_rate_positive.cpp
This takes @ziga-lunarg tests (https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/9506) and improves the error messages for them
=> layers: Improve Fragment Density Map Offset messages

layers/gpuav/debug_printf/debug_printf.cpp, layers/gpuav/spirv/debug_printf_pass.cpp, layers/gpuav/spirv/module.cpp, layers/gpuav/spirv/module.h, layers/layer_options.cpp
Now that `LogMessage` is consuming a `const std::string&` we had a few spots where we going from `std::string` to `const char` back to `std::string`
=> layers: Use LogMessage with std::string where possible

layers/core_checks/cc_cmd_buffer.cpp, layers/core_checks/cc_device_generated_commands.cpp, layers/core_checks/cc_image.cpp, layers/core_checks/cc_pipeline_graphics.cpp, layers/core_checks/cc_query.cpp, layers/core_checks/cc_render_pass.cpp, layers/stateless/sl_render_pass.cpp, tests/unit/fragment_shading_rate.cpp, tests/unit/fragment_shading_rate_positive.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/9505
While here, went through and made sure we print a hex value for all `viewMask` as that is what is useful
=> layers: Fixup MultiView errors

layers/gpuav/core/gpuav.h, layers/gpuav/core/gpuav_record.cpp, layers/gpuav/core/gpuav_setup.cpp, layers/gpuav/debug_printf/debug_printf.cpp, layers/gpuav/resources/gpuav_state_trackers.cpp
Closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/9499
Went down the "Do not use VMA pools" route.
Still need to investigate our VMA usage further. 
Ideally our buffers should always use device local memory, otherwise perf can get stupid.
Buffers need to be cached rather than created/destroyed at will, it can happen a lot during a frame, so much so that in games like Doom Eternal it can become the bottleneck
=> gpuav: Remove VMA pool

layers/core_checks/cc_ray_tracing.cpp, layers/core_checks/core_validation.h, layers/gpuav/core/gpuav.h, layers/gpuav/core/gpuav_setup.cpp, layers/gpuav/resources/gpuav_state_trackers.cpp, layers/gpuav/resources/gpuav_state_trackers.h, layers/state_tracker/ray_tracing_state.h, layers/state_tracker/state_tracker.cpp, layers/state_tracker/state_tracker.h, tests/framework/ray_tracing_objects.cpp, tests/icd/test_icd.cpp, tests/unit/ray_tracing.cpp, tests/unit/ray_tracing_positive.cpp
Closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/9428
Turns out what I observed in https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/9492 WRT buffers not sharing the same base address when bound to the same memory is in practice only true for for sparse buffers, and the reworked validation in this PR does not attempt to validate sparse buffers anymore, since it is something you can only safely do a `vkQueueSubmit` time when all memory bindings can be resolved for sparse buffers/images. The code to handle the specific sparse case has never been there, we used to validate sparse buffers with the "normal" path, a mistake.
=> vvl: Rework accel structs mem aliasing validation, re-vengeance 

layers/gpuav/spirv/debug_printf_pass.cpp, tests/unit/debug_printf.cpp, tests/unit/gpu_av_positive.cpp
1. Add some basic Mesh/Task tests for Printf/GPU-AV
2. Fix how we report error for `printf` when user messes up our `%v3f` style syntax
=> printf: Extra testing and error message fix

layers/gpuav/core/gpuav_setup.cpp
Forgot to do that in https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/9516
=> gpuav: Do not try to get address of unbound buffer

docs/README.md, docs/error_messages.md, layers/VkLayer_khronos_validation.json.in, layers/error_message/logging.cpp, layers/error_message/logging.h, layers/layer_options.cpp, layers/vk_layer_settings.txt, tests/unit/layer_settings_positive.cpp
First attempt to add JSON output and an optional setting
As people try using it, we might still tweak things, but this is the initial start
```json
{
"Severity" : "Error",
"VUID" : "VUID-vkBindBufferMemory-buffer-07459",
"Objects" : [
{"type" : "VkDeviceMemory", "handle" : "0xe7f79a0000000005", "name" : "memory_name"},
{"type" : "VkBuffer", "handle" : "0xfa21a40000000003", "name" : ""},
{"type" : "VkDeviceMemory", "handle" : "0xf56c9b0000000004", "name" : ""}
],
"MessageID" : "0x5001937c",
"Function" : "vkBindBufferMemory",
"Location" : "",
"MainMessage" : "attempting to bind VkDeviceMemory 0xe7f79a0000000005[memory_name] to VkBuffer 0xfa21a40000000003 which has already been bound to VkDeviceMemory 0xf56c9b0000000004.",
"DebugRegion" : "",
"SpecText" : "buffer must not have been bound to …
```
=> layers: Add initial JSON error message option

layers/state_tracker/state_tracker.cpp, tests/unit/graphics_library_positive.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/9527
We ignored when `VkPipelineRenderingCreateInfo::pColorAttachmentFormats` is garbage in like 3 out of 4 cases, we missed one, this just brings the big hammer and nulls the pointer for the user if they are supplying it with garbage (we tried to not do this before and it worked well for the non-pNext structs, but this one is harder because its in the pNext)
=> layers: Handle yet-another ignored pointer

layers/sync/sync_error_messages.cpp, layers/sync/sync_error_messages.h, layers/sync/sync_renderpass.cpp, tests/unit/sync_val.cpp
> vkCmdBeginRenderPass(): WRITE_AFTER_WRITE hazard detected. vkCmdBeginRenderPass potentially modifies attachment 0 in subpass 0 (VkImageView 0xcfef35000000000a), which was previously written by vkCmdCopyImage.
No sufficient synchronization is present to ensure that a write (VK_ACCESS_2_COLOR_ATTACHMENT_WRITE_BIT) at VK_PIPELINE_STAGE_2_COLOR_ATTACHMENT_OUTPUT_BIT does not conflict with a prior write (VK_ACCESS_2_TRANSFER_WRITE_BIT) at VK_PIPELINE_STAGE_2_COPY_BIT.
Vulkan insight: according to the specification VK_ATTACHMENT_LOAD_OP_DONT_CARE is a write access (VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT for color attachment).
=> sync: Update renderpass load/resolve/store messages

layers/sync/sync_error_messages.cpp, layers/sync/sync_error_messages.h, layers/sync/sync_renderpass.cpp
> vkCmdBeginRenderPass(): WRITE_AFTER_WRITE hazard detected: attachment loadOp access is not synchronized with the attachment layout transition. vkCmdBeginRenderPass clears the color aspect of attachment 0 in subpass 0 (VkImageView 0x967dd1000000000e, loadOp VK_ATTACHMENT_LOAD_OP_CLEAR), which was previously written during an image layout transition initiated by the same command.
The current synchronization allows VK_ACCESS_2_INPUT_ATTACHMENT_READ_BIT|VK_ACCESS_2_SHADER_READ_BIT accesses at VK_PIPELINE_STAGE_2_FRAGMENT_SHADER_BIT, but to prevent this hazard, it must allow VK_ACCESS_2_COLOR_ATTACHMENT_WRITE_BIT accesses at VK_PIPELINE_STAGE_2_COLOR_ATTACHMENT_OUTPUT_BIT.
=> sync: Update attachment loadOp vs layout transition message

layers/drawdispatch/descriptor_validator.cpp, layers/vulkan/generated/spirv_validation_helper.cpp, layers/vulkan/generated/spirv_validation_helper.h, scripts/generators/spirv_validation_generator.py, tests/unit/shader_storage_image.cpp, tests/unit/shader_storage_image_positive.cpp, tests/unit/shader_storage_texel.cpp
Fixes issue with warning, the user might use `Rgba8` in their shader which maps to `VK_FORMAT_R8G8B8A8_UNORM` but the user can still use `VK_FORMAT_B8G8R8A8_UNORM` (basically was doing exact format check instead of using `vkuFormatCompatibilityClass`
=> layers: Fix warning for Storage Image

layers/sync/sync_error_messages.cpp, layers/sync/sync_error_messages.h, layers/sync/sync_renderpass.cpp, tests/unit/sync_val.cpp
> vkCmdBeginRenderPass(): WRITE_AFTER_READ hazard detected. vkCmdBeginRenderPass performs image layout transition in subpass 0 on attachment 0 (VkImageView 0xcfef35000000000a, VkImage 0xf56c9b0000000004, oldLayout VK_IMAGE_LAYOUT_UNDEFINED, newLayout VK_IMAGE_LAYOUT_DEPTH_STENCIL_ATTACHMENT_OPTIMAL), which was previously read by vkCmdCopyImage.
No sufficient synchronization is present to ensure that a layout transition does not conflict with a prior read (VK_ACCESS_2_TRANSFER_READ_BIT) at VK_PIPELINE_STAGE_2_COPY_BIT. An execution dependency is sufficient to prevent this hazard.
=> sync: Update renderpass layout transition messages

layers/sync/sync_error_messages.cpp, layers/sync/sync_error_messages.h, layers/sync/sync_op.cpp, tests/unit/sync_val.cpp
Temporary contains commits from https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/9543
OLD:
> vkCmdPipelineBarrier(): Hazard WRITE_AFTER_WRITE for image barrier 0 VkImage 0xf443490000000006. Access info (usage: SYNC_IMAGE_LAYOUT_TRANSITION, prior_usage: SYNC_COPY_TRANSFER_WRITE, write_barriers: 0, command: vkCmdCopyBufferToImage, resource: VkImage 0xf443490000000006).
NEW:
> vkCmdPipelineBarrier(): WRITE_AFTER_WRITE hazard detected. vkCmdPipelineBarrier performs image layout transition on the VkImage 0xf443490000000006, which was previously written by vkCmdCopyBufferToImage.
No sufficient synchronization is present to ensure that a layout transition does not conflict with a prior write (VK_ACCESS_2_TRANSFER_WRITE_BIT) at VK_PIPELINE_STAGE_2_COPY_BIT.
Image barrier: {
barrier …
=> sync: Update barrier messages

layers/sync/sync_commandbuffer.h, layers/sync/sync_error_messages.cpp, layers/sync/sync_error_messages.h, layers/sync/sync_op.cpp, layers/sync/sync_reporting.cpp, layers/sync/sync_submit.h
Both pipeline barrier and event code detect image barrier hazard. Made corresponding code shared. Refactored implementation to be able to use reporting code also during submit time (event code runs both during recording and queue submit time).
=> sync: Reuse image barrier message for event validation

layers/vk_layer_settings.txt
Change 
> Use GPU-AV to detect which descriptors **where** accessed.
to 
> Use GPU-AV to detect which descriptors **were** accessed.
=> docs: Fix a typo on vk_layer_settings for gpuav_image_layout

layers/best_practices/bp_device_memory.cpp, layers/core_checks/cc_descriptor.cpp, layers/state_tracker/descriptor_sets.cpp, layers/state_tracker/descriptor_sets.h, tests/unit/best_practices.cpp, tests/unit/descriptors.cpp, tests/unit/descriptors_positive.cpp
This will warn people without `VK_KHR_maintenance1` that they are possibly over-allocating their descriptor sets
This is a bit more conservative than the Best Practice version (because that is more of expected usage), but is a good first step to help people doing something nonsensical
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/9500
=> layers: Add Descriptor Allocate Warning

layers/core_checks/cc_cmd_buffer.cpp, layers/core_checks/cc_render_pass.cpp, layers/core_checks/core_validation.h, layers/state_tracker/cmd_buffer_state.cpp, layers/state_tracker/cmd_buffer_state.h, tests/unit/secondary_command_buffer_positive.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/9541
Basically the whole `PreCallValidateCmdExecuteCommands` was like a 1000 lines long and we made the mistake because things were so nested in things (that were not even related) that we missed a case and gave the false positive (added test and is good now)
I tried to break the function up more and separate things, there is a lot left to peel away (especially around dynamic rendering local read) but for the short term, it is a step in the right direction of cleaning it up
=> layers: Fix and cleanup vkCmdExecuteCommands

layers/sync/sync_validation.cpp
Found vertex data size computation bug in `vkCmdBuildAccelerationStructuresKHR` validation. Was debugging implementation under new Indiana Jones game which helped to see the issue.
=> sync: Fix ray tracing vertex range computation

layers/chassis/dispatch_object_manual.cpp, layers/core_checks/cc_pipeline_graphics.cpp, layers/state_tracker/state_tracker.cpp
Attempt 2 at https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/9533 and reverts https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/9567 (as it didn't fix the issue in CTS)
The new approach is just null, then recover, the pointer before we build a safe struct
=> layers: Finally fix ignoring VkPipelineRenderingCreateInfo

BUILD.gn, layers/CMakeLists.txt, layers/core_checks/cc_copy_blit_resolve.cpp, layers/core_checks/cc_image.cpp, layers/core_checks/cc_pipeline_graphics.cpp, layers/core_checks/cc_render_pass.cpp, layers/core_checks/cc_spirv.cpp, layers/gpuav/spirv/buffer_device_address_pass.cpp, layers/stateless/sl_image.cpp, layers/utils/math_utils.h, layers/utils/vk_layer_utils.h, tests/unit/external_memory_metal.cpp, tests/unit/external_memory_sync_positive.cpp, tests/unit/gpu_av_descriptor_buffer_positive.cpp, tests/unit/ray_tracing.cpp, tests/unit/sparse_image.cpp, tests/unit/video.cpp
Creates a dedicated `utils/math_utils.h` file to help reduce the "everything that doesn't fit" bin of `vk_layer_utils.h`
There were a few files that really just needed these non-Vulkan helpers
=> utils: Move math utils to dedicated file

layers/core_checks/cc_synchronization.cpp
OLD
> kQueueSubmit(): pSubmits[0].pCommandBuffers[0] in submitted command buffer VkBufferMemoryBarrier acquiring ownership of (VkBuffer 0xf56c9b0000000004), from srcQueueFamilyIndex 1 to dstQueueFamilyIndex 0 has no matching release barrier queued for execution.
NEW
> vkQueueSubmit(): pSubmits[0].pCommandBuffers[0] contains a VkBufferMemoryBarrier that acquires ownership of VkBuffer 0xf56c9b0000000004 for destination queue family 0, but no matching release operation was queued for execution from source queue family 1.
=> layers: Improve ownership transfer error message

tests/framework/layer_validation_tests.cpp, tests/framework/layer_validation_tests.h, tests/unit/buffer.cpp, tests/unit/buffer_positive.cpp, tests/unit/descriptor_buffer.cpp, tests/unit/device_queue.cpp, tests/unit/dynamic_state.cpp, tests/unit/external_memory_sync.cpp, tests/unit/fragment_shading_rate.cpp, tests/unit/image.cpp, tests/unit/image_drm.cpp, tests/unit/image_positive.cpp, tests/unit/memory.cpp, tests/unit/others.cpp, tests/unit/portability_subset.cpp, tests/unit/protected_memory.cpp, tests/unit/sampler.cpp, tests/unit/sparse_buffer.cpp, tests/unit/sparse_image.cpp, tests/unit/wsi.cpp, tests/unit/ycbcr.cpp
Things like `CreateSamplerTest` and `CreateBufferTest` were a little more clunky then needed to
1. Moved to inside `VkLayerTest` (so don't need to pass it in as a first argument)
2. Remove default string being null (Positive tests can just use `vkt::`)
3. Pass by reference
=> tests: Improve Simple Test creation helpers

layers/vulkan/generated/stateless_validation_helper.cpp, scripts/generators/stateless_validation_helper_generator.py, tests/unit/device_feature_property.cpp, tests/unit/others.cpp, tests/unit/pipeline.cpp, tests/unit/portability_subset.cpp
@jeremyg-lunarg @aqnuep here is a quick demonstration of removing the "your pNext struct is missing an extension" validation
Now looking at the tests, something like `VkLayerTest.MissingExtensionStruct` scares me to apply this PR because it would hide an obvious bug if the user tried to use `VkBufferUsageFlags2CreateInfo` and didn't understand why it wasn't working
=> layers: Remove pNext Struct Extension check

docs/error_messages.md, layers/VkLayer_khronos_validation.json.in, layers/error_message/logging.cpp, layers/error_message/logging.h, layers/layer_options.cpp, layers/object_tracker/object_tracker_utils.cpp, layers/vk_layer_settings.txt, tests/framework/error_monitor.cpp, tests/framework/error_monitor.h, tests/framework/layer_validation_tests.cpp, tests/unit/debug_extensions.cpp, tests/unit/layer_settings.cpp, tests/unit/layer_settings_positive.cpp
tl;dr - This **finally** makes messages look nice by default
```
Validation Error: [ VUID-vkCmdCopyImage-srcImage-01548 ] | MessageID = 0x1c1c4e09
vkCmdCopyImage(): srcImage format (VK_FORMAT_R8G8B8A8_UNORM) is not size-compatible with dstImage format (VK_FORMAT_D32_SFLOAT). VK_FORMAT_R8G8B8A8_UNORM is a color and VK_FORMAT_D32_SFLOAT is depth/stencil (this is only allowed with a certain set of formats during image copy with VK_KHR_maintenance8).
The Vulkan spec states: If the VkFormat of each of srcImage and dstImage is not a multi-planar format, the VkFormat of each of srcImage and dstImage must be size-compatible (https://docs.vulkan.org/spec/latest/chapters/copies.html#VUID-vkCmdCopyImage-srcImage-01548)
Objects: 3
[0] VkCommandBuffer 0x607a385f8e50[myCommandBuffer]
[1] VkImage …
```
=> layers: Refresh of messages for callbacks

layers/chassis/dispatch_object.h, layers/chassis/dispatch_object_manual.cpp, layers/core_checks/core_validation.h, layers/state_tracker/state_tracker.cpp, layers/state_tracker/state_tracker.h, layers/stateless/sl_spirv.h
Here's the promised follow-up refactoring extracting the stateless device data into its own atomically initialized class.
Unfortunately, I had to keep `extensions` and `enabled_features` mutable, because there's some patching done in the chassis of `CreateDevice`.
=> layers: Extract stateless device data initialization

layers/stateless/sl_utils.cpp, layers/stateless/stateless_validation.h, tests/unit/others.cpp
Follow up of https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/9578 
After looking, honestly just the VK_KHR_maintenance5 structs I feel are worth giving a warning about. Things like `VkAccessFlags2` you need to use the Sync2 structs. `VK_KHR_format_feature_flags2` is a special case as you don't enable it, we check if it is supported or not
Basically here is a valid spot to give a warning IMO, everything else I think is better that we got rid of
cc @jeremyg-lunarg @aqnuep
=> layers: Warn if using VK_KHR_maintenance5 flags2

layers/sync/sync_common.cpp, layers/sync/sync_utils.cpp, tests/unit/sync_object_positive.cpp, tests/unit/sync_val_ray_tracing_positive.cpp
Fixes major gap in syncval ray tracing testing, where simple scenario did not work at all
=> sync: Fix getting SyncAccessFlags from VkAccessFlags2

layers/core_checks/cc_descriptor.cpp, layers/state_tracker/state_tracker.cpp, tests/unit/descriptors.cpp, tests/unit/descriptors_positive.cpp
This was giving a false positive for the `WARNING-VkDescriptorSetAllocateInfo-descriptorCount` warning due to not accounting correctly for `VK_DESCRIPTOR_BINDING_VARIABLE_DESCRIPTOR_COUNT_BIT`
=> layers: Account for Variable Descriptor Count

layers/containers/custom_containers.h
This pull request includes an update to the `small_vector` class in the `layers/containers/custom_containers.h` file to improve the initialization process and ensure proper memory allocation. Fixes an issue where ninja would fail to compile the x64 windows release triplet.
Changes to `small_vector` class:
* Added a check to ensure the `reserve` method is called only if the size is greater than zero, preventing unnecessary memory allocation.
* Fixed the initialization loop to correctly construct elements in the allocated memory using the `placement new` operator.
=> layers: Improve small_vector initialization for better memory handling

layers/drawdispatch/descriptor_validator.cpp, layers/state_tracker/cmd_buffer_state.cpp, layers/state_tracker/descriptor_sets.cpp, layers/state_tracker/descriptor_sets.h, layers/state_tracker/pipeline_state.h
@arno-lunarg showed we were spending a lot of time in `UpdateDrawState` in GPU-AV even when Image Layout validation is off
1. Check if setting is off and skip work
2. Rename function to be clear this is only updating Image Layout state
=> gpuav: Skip State Tracking Image Layout when off

docs/debug_printf.md, layers/core_checks/cc_shader_interface.cpp, layers/drawdispatch/descriptor_validator.cpp, tests/unit/shader_interface.cpp, tests/unit/shader_storage_image.cpp
new message
```
Validation Warning: [ Undefined-Value-ShaderInputNotProduced-DynamicRendering ] | MessageID = 0x733b5ff8
vkCmdDrawIndexed(): Inside the fragment shader, the output Locaiton 1 was never written to. This means the bound VkRenderingInfo::pColorAttachments[1].imageView (VkImageView 0x3a6cbb0000000025) will have undefined values written to it. The pipeline was created with pColorBlendState->pAttachments[1].colorWriteMask set to 0xf so setting it to zero is one way to prevent undefined values overriding your color attachment (this will require independentBlend, which is basically supported everywhere, to have some attachment have different colorWriteMask).
Spec information at https://docs.vulkan.org/spec/latest/chapters/interfaces.html#interfaces-fragmentoutput
Objects: 2
[0] …
```
=> layers: Better ShaderInputNotProduced error message

layers/core_checks/cc_shader_interface.cpp
Quick hotfix to not give false positives for https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/8887
Will need to get a real solution in afterwards
=> layers: Skip warning if using VK_KHR_dynamic_rendering_local_read

layers/sync/sync_commandbuffer.cpp, layers/sync/sync_commandbuffer.h, layers/sync/sync_common.h, layers/sync/sync_error_messages.cpp, layers/sync/sync_reporting.cpp, layers/sync/sync_reporting.h, layers/sync/sync_submit.cpp, layers/sync/sync_submit.h, layers/sync/sync_validation.cpp, layers/vulkan/generated/sync_validation_types.cpp, layers/vulkan/generated/sync_validation_types.h, scripts/generators/sync_validation_generator.py
Starting removing old error reporting functionality and cleanup new functionality. There will be more follow up PRs.
=> sync: Remove old formating code

docs/gpu_av_shader_instrumentation.md, layers/VkLayer_khronos_validation.json.in, layers/gpuav/core/gpuav_settings.h, layers/gpuav/instrumentation/gpuav_shader_instrumentor.cpp, layers/gpuav/spirv/descriptor_class_general_buffer_pass.cpp, layers/gpuav/spirv/descriptor_class_general_buffer_pass.h, layers/gpuav/spirv/descriptor_indexing_oob_pass.cpp, layers/gpuav/spirv/descriptor_indexing_oob_pass.h, layers/gpuav/spirv/inject_conditional_function_pass.cpp, layers/gpuav/spirv/inject_conditional_function_pass.h, layers/gpuav/spirv/module.h, layers/gpuav/spirv/pass.cpp, layers/gpuav/spirv/pass.h, layers/layer_options.cpp, layers/vk_layer_settings.txt, tests/unit/gpu_av_descriptor_indexing_positive.cpp
By not preventing crashing, we can take things that took 20 seconds to compile down to a 2 to 3ms overhead. Many more things I can take advantage of `unsafe mode` but wanted to add it as a nice single first change
Some numbers
- [**BASE LINE**] PositiveGpuAVDescriptorIndexing.Stress
- 150 ms
- [**BASE LINE**] PositiveGpuAVDescriptorIndexing.Stress2 
- 30 ms
- [**SAFE** MODE] PositiveGpuAVDescriptorIndexing.Stress
- 2150 ms
- DescriptorIndexingOOBPass instrumentation count: 47 (Bindless version)
- [**SAFE** MODE] PositiveGpuAVDescriptorIndexing.Stress2
- 19417 ms (!!!)
- DescriptorIndexingOOBPass instrumentation count: 201 (Bindless version)
- [**UNSAFE** MODE] PositiveGpuAVDescriptorIndexing.Stress
- 1400 ms
- DescriptorIndexingOOBPass instrumentation count: 31 (Bindless version)
- …
=> gpuav: Introduce unsafe mode

.github/workflows/vvl.yml
tests.py --build will also build everything needed for testing.
Vulkan-Loader, Mock ICD, and the profile layers.
Don't use tests.py to build, unless you also run the tests.
Otherwise it just wastes time
=> ci: Reduce unneccessary builds

layers/core_checks/cc_descriptor.cpp, layers/gpuav/descriptor_validation/gpuav_descriptor_validation.cpp, layers/state_tracker/descriptor_sets.cpp, layers/state_tracker/descriptor_sets.h, layers/state_tracker/shader_module.cpp, tests/unit/gpu_av_descriptor_post_process.cpp, tests/unit/gpu_av_descriptor_post_process_positive.cpp, tests/unit/shader_image_access.cpp
Taking the good out of https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/9604
=> layers: Cleanup for deferring to GPU-AV

docs/debug_printf.md, layers/gpuav/debug_printf/debug_printf.cpp, layers/gpuav/spirv/debug_printf_pass.cpp, tests/unit/debug_printf.cpp
sick of not being able to go `%p` to print a pointer... well now we can
=> printf: Add support for printing pointers

layers/core_checks/cc_device_memory.cpp
Small improvement to  VUID-vkBindBufferMemory-bufferDeviceAddress-03339 to hint user to don't for the Memory flag is a pNext
=> layers: Improve VU message for BDa

layers/sync/sync_commandbuffer.h, layers/sync/sync_common.h, layers/sync/sync_error_messages.cpp, layers/sync/sync_error_messages.h, layers/sync/sync_reporting.cpp, layers/sync/sync_reporting.h, layers/sync/sync_submit.h, layers/sync/sync_validation.cpp
Update naming and interfaces cleanup.
Move code to proper locations:
sync_reporting - logic and helpers to generate error messages
sync_error_messages - use that logic to construct specific messages
=> sync: More cleanup of reporting code

layers/gpuav/core/gpuav_features.cpp
Simple typo, setting was not working, not sure how I got this messed up (as it was working when I first was testing it)
=> layers: Fix typo enabling wrong feature

tests/unit/gpu_av_buffer_device_address_positive.cpp
Found from https://gitlab.freedesktop.org/mesa/mesa/-/issues/12819 that this was an uncaught issue and this is why the test was failing on CI
tracking new issue at https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/9664
=> tests: Fix broken test on RADV

layers/sync/sync_commandbuffer.cpp, layers/sync/sync_commandbuffer.h, layers/sync/sync_error_messages.cpp, layers/sync/sync_reporting.cpp, layers/sync/sync_reporting.h, layers/sync/sync_submit.h
This cleanups the code that reports the properties derived from `ResourceUsageRecord`.
=> sync: Cleanup ResourceUsageRecord and corresponding properties

layers/state_tracker/descriptor_sets.h
Thought I hit a bug here (couldn't reproduce) but wanted to leave a comment as I was at first confused why we had a `small_vector` that was a 1 million items big, but learned it was the app that had literally a `descriptorCount` value of `1,000,000` and this is perfectly resized and should stay (and wanted to explain this)
=> layers: Add comment why we use small_vector

layers/gpuav/spirv/module.cpp
This fixes it where you couldn't do `printf` in our internal GLSL instrumented shaders on function parameters
=> gpuav: Fix not tracking OpFunctionParameter

layers/core_checks/cc_spirv.cpp, layers/gpuav/spirv/post_process_descriptor_indexing_pass.cpp, layers/gpuav/spirv/post_process_descriptor_indexing_pass.h, layers/state_tracker/shader_module.cpp, layers/utils/hash_util.cpp, layers/utils/hash_util.h, layers/utils/shader_utils.cpp
While looking at traces, found one where we could reduce almost half the post processing instrumentation just doing a simple hash lookup on the 4 variables we were going to pass into the function (as it means they are all going to mark the same things)
**Before**
Vert Shader - PostProcessDescriptorIndexingPass instrumentation count: **127**
Geom Shader - PostProcessDescriptorIndexingPass instrumentation count: **8**
Frag Shader - PostProcessDescriptorIndexingPass instrumentation count: **57**
**After**
Vert Shader - PostProcessDescriptorIndexingPass instrumentation count: **78**
Geom Shader - PostProcessDescriptorIndexingPass instrumentation count: **2**
Frag Shader - PostProcessDescriptorIndexingPass instrumentation count: **30**
=> gpuav: Hash Post Processing once per block

layers/gpuav/instrumentation/gpuav_shader_instrumentor.cpp
I couldn't get a shader saved that reproduced this, but sometimes my gfxrecon trace would crash in the instrumentation because the LUT was empty
=> gpuav: Fix crash when Binding LUT is null

tests/unit/gpu_av_cooperative_vector_positive.cpp
This is related to #9599 but the CI driver isn't new enough to support this test.
=> tests: Add missing feature to GPU-AV CooperativeVector

layers/drawdispatch/descriptor_validator.cpp, layers/drawdispatch/descriptor_validator.h
This thing is like 90% log messages so not having to dereference something is nice. Also the header was formatted very poorly and clang-format decided to redo it all.
=> layers: Use Logger in class DescriptorValidator

layers/state_tracker/fence_state.cpp, layers/state_tracker/fence_state.h, layers/state_tracker/image_state.cpp, layers/state_tracker/image_state.h, layers/state_tracker/queue_state.cpp, layers/state_tracker/queue_state.h, layers/state_tracker/semaphore_state.cpp, layers/state_tracker/semaphore_state.h, layers/state_tracker/state_tracker.cpp, tests/unit/wsi_positive.cpp
Closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/9587
This adds one more use case of synchronization and simplifies implementation a bit. The new use case helped to realize it's possible to use simpler implementation that unifies both previous and new sync scenario  (assuming no regression, which is hard to guarantee for such code). Some code simplifications:
* Remove `AcquireFenceSync` type. Now it can be replaced with a single instance of `SubmissionReference`
* Remove `Semaphore::GetPendingBinaryWaitSubmission`
=> layers: Fix present semaphore in use error after acquire fence wait

layers/core_checks/cc_pipeline_graphics.cpp, tests/unit/multiview.cpp, tests/unit/multiview_positive.cpp
Discussed in https://gitlab.khronos.org/vulkan/vulkan/-/issues/4194
This shows how you can use Mesh Shading with Multiview in GLSL and not trigger the Layer VU
=> layers: Multiview with Mesh Shader in GLSL

layers/gpuav/core/gpuav_setup.cpp, layers/gpuav/debug_printf/debug_printf.cpp, layers/gpuav/descriptor_validation/gpuav_descriptor_set.cpp, layers/gpuav/descriptor_validation/gpuav_descriptor_validation.cpp, layers/gpuav/instrumentation/gpuav_instrumentation.cpp, layers/gpuav/resources/gpuav_state_trackers.cpp, layers/gpuav/resources/gpuav_vulkan_objects.cpp, layers/gpuav/resources/gpuav_vulkan_objects.h, layers/gpuav/validation_cmd/gpuav_copy_buffer_to_image.cpp
Remove the `Loc` from `GetMappedPtr` as it is not actually needed
=> gpuav: Remove Loc from Mapped Ptr

layers/gpuav/descriptor_validation/gpuav_descriptor_set.cpp, layers/gpuav/descriptor_validation/gpuav_descriptor_set.h, layers/gpuav/descriptor_validation/gpuav_descriptor_validation.cpp, layers/gpuav/resources/gpuav_shader_resources.h, layers/state_tracker/shader_module.cpp, layers/state_tracker/shader_module.h
The goal is to remove the `BindingVariableMap` when doing Post Processing because
1. It is the wrong level of detail to save for the given pipeline
2. It doesn't work at all with Shader Object (main reason we can't support it currently)
3. It reduces a lot of random checks because we now can directly get the `const spirv::ResourceInterfaceVariable &` right away
=> gpuav: Use EntryPoint to map shader to post process

layers/gpuav/debug_printf/debug_printf.cpp, layers/gpuav/descriptor_validation/gpuav_descriptor_set.cpp, layers/gpuav/descriptor_validation/gpuav_descriptor_validation.cpp, layers/gpuav/resources/gpuav_state_trackers.cpp, layers/gpuav/resources/gpuav_state_trackers.h, layers/gpuav/resources/gpuav_vulkan_objects.cpp, layers/gpuav/resources/gpuav_vulkan_objects.h
All our `memset` in GPU-AV are just to clear the size of the buffer and we have to try and keep track of the size when it can be just done in `vko::Buffer`
=> gpuav: Add a Clear to vbo::Buffer

layers/chassis/chassis_manual.cpp, layers/chassis/chassis_modification_state.h, layers/gpuav/instrumentation/gpuav_shader_instrumentor.cpp
Found Doom on RADV doesn't like our changes to the RTX shader (and blows up), so added logic to check if pipelines fail and to try and re-run them so things are a bit more robust
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/9699
=> gpuav: Retry Pipeline if failed with modification

layers/state_tracker/state_tracker.cpp, layers/state_tracker/state_tracker.h
The whole point of these abstractions is to enable subclasses to provide customized creation to customized subclasses of the state objects themselves, so it would be bad design to remove this ability. For example, this is not only used by layer subclasses such as the best practices layers, but also by the Vulkan SC validation layers to ammend SC-specific data to the state objects through subclassing.
Having overrideable factory methods for the state objects is paramount to enable extensibility.
=> layers: Readd removed state creation abstractions

layers/gpuav/instrumentation/gpuav_shader_instrumentor.cpp, tests/unit/gpu_av_index_buffer_positive.cpp
VUs from the 02721 family should not be checked when robustness is on
=> gpuav: No OOB vertex validation when robustness on

layers/state_tracker/shader_module.cpp, layers/state_tracker/shader_module.h
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/8501
=> layers: Remove Robinhood for spirv parsing

layers/gpuav/instrumentation/gpuav_shader_instrumentor.cpp, tests/unit/gpu_av_descriptor_class_texel_buffer.cpp, tests/unit/gpu_av_descriptor_class_texel_buffer_positive.cpp, tests/unit/gpu_av_descriptor_indexing.cpp
We can skip texel buffer checks if robustness is on
=> gpuav: Skip TexelBuffer OOB if robustness

layers/gpuav/core/gpuav_features.cpp, layers/gpuav/instrumentation/gpuav_shader_instrumentor.h, layers/gpuav/spirv/descriptor_class_general_buffer_pass.cpp, layers/gpuav/validation_cmd/gpuav_draw.cpp
For those using `VK_LAYER_GPUAV_FORCE_ON_ROBUSTNESS` this will now also turn on `robustBufferAccess2` and `robustImageAccess2` as well
=> gpuav: Force on Robustness 2 as well

layers/state_tracker/shader_module.cpp, tests/unit/shader_push_constants.cpp
There are not many places that care about the struct size in SPIR-V, but Push Constants do. The struct
```
layout(push_constant) uniform Uniforms {
BDA ptr0;
BDA ptr1;
};
```
is 16 bytes (2 pointers), but was being counted as 9 due to this bug
=> layers: Fix BDA being viewed as 1 byte

tests/framework/barrier_queue_family.cpp, tests/framework/binding.cpp, tests/framework/binding.h, tests/unit/amd_best_practices.cpp, tests/unit/arm_best_practices.cpp, tests/unit/command.cpp, tests/unit/command_positive.cpp, tests/unit/copy_buffer_image.cpp, tests/unit/copy_buffer_image_positive.cpp, tests/unit/descriptors.cpp, tests/unit/gpu_av_image_layout.cpp, tests/unit/host_image_copy.cpp, tests/unit/host_image_copy_positive.cpp, tests/unit/image.cpp, tests/unit/image_layout.cpp, tests/unit/image_layout_positive.cpp, tests/unit/image_positive.cpp, tests/unit/memory_positive.cpp, tests/unit/parent.cpp, tests/unit/portability_subset.cpp, tests/unit/render_pass_positive.cpp, tests/unit/sampler.cpp, tests/unit/secondary_command_buffer.cpp, tests/unit/secondary_command_buffer_positive.cpp, tests/unit/subpass.cpp, tests/unit/sync_object_positive.cpp, tests/unit/sync_val.cpp, tests/unit/ycbcr.cpp, tests/unit/ycbcr_positive.cpp
This stops using `Image::image_layout_` state and instead the test directly specifies current layout when necessary. Usually the test knows exactly what is the current layout. The layout member is not removed yet and does some assert checks to help with this cleanup, but it is not used by any logic anymore.
Some reasons why not to track layout inside image object:
* It was very common that intead of using, for example, VK_LAYOUT_GENERAL constant directly, the test at first initiated real layout transition (`SetLayout`) only because this also sets `image_layout_` and then it was read using `Layout()` getter (`Layout()` getter is gone too), so very advanced way to get a constant value.
* Another potential issue is related to Vulkan design conventions. In Vulkan VkImage does not track …
=> layers: Remove layout state from vkt::Image

layers/gpuav/validation_cmd/gpuav_copy_buffer_to_image.cpp, layers/gpuav/validation_cmd/gpuav_dispatch.cpp, layers/gpuav/validation_cmd/gpuav_draw.cpp
While trying to add debug printf support for validation cmd shaders (which is another issue) I noticed some random nit to clean up and packaged them here
=> gpuav: Nit cleanup for validation cmd

tests/framework/binding.cpp, tests/framework/binding.h
`Image::image_layout_` was kept temporary to check asserts on CI but now is not needed anymore.
=> tests: Remove unused Image::image_layout_ member

layers/chassis/chassis_manual.cpp, layers/chassis/chassis_modification_state.h, layers/chassis/validation_object.h, layers/core_checks/cc_pipeline_ray_tracing.cpp, layers/core_checks/core_validation.h, layers/gpuav/instrumentation/gpuav_shader_instrumentor.cpp, layers/gpuav/instrumentation/gpuav_shader_instrumentor.h, layers/state_tracker/state_tracker.cpp, layers/state_tracker/state_tracker.h, layers/vulkan/generated/best_practices.cpp, layers/vulkan/generated/best_practices_device_methods.h, scripts/generators/best_practices_generator.py
The NV RTX path is fully unsupported and untested in GPU-AV, so removing for ease of maintaining the RTX version by itself
=> gpuav: Remove NV RTX for KHR RTX

layers/gpuav/instrumentation/gpuav_shader_instrumentor.cpp, layers/gpuav/spirv/descriptor_class_general_buffer_pass.cpp, layers/gpuav/spirv/descriptor_class_general_buffer_pass.h, layers/gpuav/spirv/descriptor_class_texel_buffer_pass.cpp, layers/gpuav/spirv/descriptor_class_texel_buffer_pass.h, layers/gpuav/spirv/descriptor_indexing_oob_pass.cpp, layers/gpuav/spirv/descriptor_indexing_oob_pass.h, layers/gpuav/spirv/pass.cpp, layers/gpuav/spirv/pass.h, layers/gpuav/spirv/post_process_descriptor_indexing_pass.cpp, layers/gpuav/spirv/post_process_descriptor_indexing_pass.h
Talking with @arno-lunarg about how to streamline the Passes, I wanted to move this check inside the pass as it might change between shaders, but also not tied to the SPIR-V itself and falls into this strange grey area
This just adds an option so each pass (which actually knows what it does) is in charge of deciding to early return, not the "chassis" calling it
=> gpuav: Add an EarlySkip option in the pass

.github/workflows/vvl.yml, layers/CMakeLists.txt, layers/containers/custom_containers.h
taking idea from https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/7558
This change the cmake flag from `USE_ROBIN_HOOD_HASHING` to `USE_CUSTOM_HASH_MAP` for when we try and use something other than robin hood
Note that this will still allow `-D DUSE_ROBIN_HOOD_HASHING=OFF` to turn it off to not break any tooling that was doing that while we get them to swap
=> build: Use Custom hash build name

layers/core_checks/cc_copy_blit_resolve.cpp, layers/core_checks/cc_descriptor.cpp, layers/core_checks/cc_synchronization.cpp, layers/error_message/error_strings.h, layers/state_tracker/image_state.cpp, layers/state_tracker/image_state.h, layers/sync/sync_commandbuffer.cpp, layers/sync/sync_image.cpp, layers/sync/sync_op.cpp, tests/unit/command_positive.cpp, tests/unit/copy_buffer_image.cpp, tests/unit/image.cpp
@ziga-lunarg discovered in https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/9747 we messed up the Array Layers using `VK_REMAINING_ARRAY_LAYERS` (which you could only use in Blit/Resolve since maintenance5)
We have this "Normalize" logic for `VkImageSubresourceRange` but not for `VkImageSubresourceLayers` and this 
1. Move the Normalize functions to be Image/ImageView state function
2. Fix Resolve check like the other PR
3. Print better error message for the blit case
=> Move logic into Image/ImageView state and fix VK_REMAINING_ARRAY_LAYERS 

tests/icd/test_icd.cpp
The Test ICD incorrectly uses `free` to free memory allocated with `_aligned_alloc` on Windows.
I don't know how this didn't cause any issue for you, but for us it resulted in hanging CI on Github Actions and in our own CI.
=> tests: Fix TestICD freeing for aligned_alloc

layers/gpuav/core/gpuav.h, layers/gpuav/core/gpuav_record.cpp, layers/gpuav/descriptor_validation/gpuav_descriptor_validation.cpp, layers/gpuav/descriptor_validation/gpuav_descriptor_validation.h, layers/gpuav/instrumentation/gpuav_instrumentation.h
in `gpuav_record.cpp` creates a single `PreCallActionCommand`/`PostCallActionCommand` spot so next time I need to update something I don't have to copy-and-probably-mis-paste in one of the 23 variation of draw calls we have
=> gpuav: Create common Pre/Post Action spot

layers/gpuav/spirv/buffer_device_address_pass.cpp, layers/gpuav/spirv/buffer_device_address_pass.h, layers/gpuav/spirv/descriptor_class_general_buffer_pass.cpp, layers/gpuav/spirv/descriptor_class_general_buffer_pass.h, layers/gpuav/spirv/descriptor_class_texel_buffer_pass.cpp, layers/gpuav/spirv/descriptor_class_texel_buffer_pass.h, layers/gpuav/spirv/descriptor_indexing_oob_pass.cpp, layers/gpuav/spirv/descriptor_indexing_oob_pass.h, layers/gpuav/spirv/link.h, layers/gpuav/spirv/post_process_descriptor_indexing_pass.cpp, layers/gpuav/spirv/post_process_descriptor_indexing_pass.h, layers/gpuav/spirv/ray_query_pass.cpp, layers/gpuav/spirv/ray_query_pass.h, layers/gpuav/spirv/vertex_attribute_fetch_oob.cpp, layers/gpuav/spirv/vertex_attribute_fetch_oob.h
Realized there is zero reason to have a `link_function_id` member variable when we literally are saving the information in the `static LinkInfo` already
=> gpuav: Remove unnecessary link id member variable

layers/state_tracker/shader_module.cpp, layers/state_tracker/shader_module.h, layers/stateless/sl_spirv.cpp
@ziga-lunarg here is a follow up to https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/9736/files#r2006576276
going `const Instruction* type = GetVariablePointerType(*insn);` is a bit cleaner and prevents mis-copy-and-pasting this if we need to update it in one spot
=> layers: Create a Variable Pointer helper

layers/gpuav/core/gpuav.h, layers/gpuav/core/gpuav_record.cpp, layers/gpuav/descriptor_validation/gpuav_image_layout.cpp, layers/gpuav/descriptor_validation/gpuav_image_layout.h, layers/gpuav/instrumentation/gpuav_instrumentation.cpp, layers/gpuav/resources/gpuav_state_trackers.cpp
small follow up from https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/9651
basically path through Image Layout stuff currently is shared, can update these when sub state is actually needed
=> gpauv: Remove substate where not needed

tests/framework/layer_validation_tests.h, tests/unit/gpu_av_descriptor_class_general_buffer.cpp, tests/unit/gpu_av_descriptor_class_general_buffer_positive.cpp, tests/unit/gpu_av_descriptor_indexing_positive.cpp
Stress test to prove issue with https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/9722
Basically we need `VK_LAYER_GPUAV_UNSAFE_MODE` to hoist the check out of the loop and do it just once (if it can be clearly determined the loop variable won't effect the check of course)
=> tests: Add Stress test for GPU loops

layers/core_checks/cc_buffer.cpp, layers/core_checks/core_validation.h, layers/stateless/sl_buffer.cpp, layers/stateless/stateless_validation.h, tests/unit/buffer.cpp
Some misc moving of checks from CoreChecks to Stateless around Buffers to keep the `cc_buffer` logic down for future change
=> layers: More buffer to stateless

layers/containers/subresource_adapter.h, layers/state_tracker/image_layout_map.cpp, layers/state_tracker/image_layout_map.h
Remove kTrisolar state. `BothRangeMap` has a single constructor that creates either a small or a big map, no other option is possible.  More streamlined assignment/copy implementation - in some places no need to do conditions for small or big use case if member-wise assignment gives the same result and potentially is more performant (no conditions).
=> layers: Cleanup BothRangeMap

layers/core_checks/cc_image_layout.cpp, layers/core_checks/cc_synchronization.cpp, layers/core_checks/core_validation.h
Initial motivation here is to deal with confusing function name `UpdateCommandBufferImageLayoutMap` which does **not** update command buffer layout map. But this ended up in additional cleanup of image barrier validation.
p.s. these PRs are a side effect of me going of image barrier/layout code to fix some synchronization issues.
=> layers: Cleanup image barrier validation

layers/chassis/dispatch_object_manual.cpp, tests/unit/vertex_input_positive.cpp
The issue is if both EXT and KHR extensions are enabled, I believe we should load the properties from KHR in that case, because it contains `supportsNonZeroFirstInstance`, which the EXT does not.
=> Fix getting vertex attrib divisor properties

layers/gpuav/spirv/pass.cpp, layers/gpuav/spirv/type_manager.cpp, layers/gpuav/spirv/type_manager.h, tests/unit/gpu_av_buffer_device_address_positive.cpp
This fixes running GPU-AV on a trace where we were crashing because we didn't account that while the `GlobalInvocationId` builtin (`gl_GlobalInvocationID`) is normally a `uvec3` it can be a `ivec3`
and we were not casting this causing RADV to blow up :boom:
=> gpuav: Fix bug not casting compute builtin

layers/core_checks/cc_image.cpp, layers/core_checks/core_validation.h, layers/stateless/sl_image.cpp, tests/unit/image.cpp
I had in my backlog to split up ` CoreChecks::PreCallValidateCreateImage` as it size makes it easy to misplace things and was a cause of a bug awhile ago
1. Split thing like Video, Swapchain, External memory into own functions
2. Move more things to stateless that are very much stateless
=> layers: Split up image validation mega function

layers/core_checks/cc_image_layout.cpp, layers/core_checks/cc_synchronization.cpp, layers/core_checks/core_validation.h, layers/state_tracker/image_state.h, tests/unit/dynamic_rendering_local_read.cpp, tests/unit/dynamic_rendering_local_read_positive.cpp
Closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/9585
Moved some code, the fix is the best visible in its separate commit.
=> layers: Fix image barrier layout validation

layers/containers/small_vector.h
To fix module build in Chromium, this adds includes for `std::is_default_constructible_v` and `std::move`.
=> layers: Fix missing includes for small_vector.h

.github/workflows/vvl.yml, layers/gpuav/spirv/buffer_device_address_pass.cpp, layers/gpuav/spirv/buffer_device_address_pass.h, layers/gpuav/spirv/descriptor_class_general_buffer_pass.cpp, layers/gpuav/spirv/descriptor_class_general_buffer_pass.h, layers/gpuav/spirv/descriptor_class_texel_buffer_pass.cpp, layers/gpuav/spirv/descriptor_class_texel_buffer_pass.h, layers/gpuav/spirv/descriptor_indexing_oob_pass.cpp, layers/gpuav/spirv/descriptor_indexing_oob_pass.h, layers/gpuav/spirv/link.h, layers/gpuav/spirv/module.cpp, layers/gpuav/spirv/module.h, layers/gpuav/spirv/post_process_descriptor_indexing_pass.cpp, layers/gpuav/spirv/post_process_descriptor_indexing_pass.h, layers/gpuav/spirv/ray_query_pass.cpp, layers/gpuav/spirv/ray_query_pass.h, layers/gpuav/spirv/vertex_attribute_fetch_oob.cpp, layers/gpuav/spirv/vertex_attribute_fetch_oob.h
replacement for https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/9808
Separates out what is generated (and can be `const static`) vs the data that is per-pass
=> gpuav: Separated generated link info from dynamic

scripts/inspect_gpuav_spirv.py
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/9800 
@arno-lunarg I just go `python3 scripts/inspect_gpuav_spirv.py --dir path/to/dump` and I get this (very fast, like instant fast for hundreds of shaders)
... we can tweak to our liking as we find needed
(Just want to say I have now built a SPIR-V parser in too many programming languages at this point)
=> scripts: Tool to inspect instrumented spirv

layers/core_checks/cc_image_layout.cpp, layers/core_checks/cc_synchronization.cpp, layers/core_checks/core_validation.h, layers/sync/sync_vuid_maps.cpp, layers/sync/sync_vuid_maps.h
Previously VUIDs for barriers inside dynamic render pass were mostly about Shader Tile Images, but now it is also about Local Read barriers. The common denominator these vuids are about barriers inside Dynamic Render Pass.
=> layers: Rename ShaderTileImage VUIDs to DynamicRenderingBarrier

layers/gpuav/spirv/buffer_device_address_pass.cpp, tests/unit/gpu_av_buffer_device_address_positive.cpp
Found crash in trace, we assumed potential OpLoad always would point inside a function, but forgot about workgroup
=> gpuav: Fix checking for variables out of function

layers/core_checks/cc_synchronization.cpp, layers/core_checks/core_validation.h, layers/sync/sync_utils.cpp, layers/sync/sync_vuid_maps.cpp, tests/unit/sync_object.cpp
Closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/9815. 
This fixes crash and reports the missing feature.
@spencer-lunarg  I did not check if there should be a warning during device initialization as suggested here:(https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/9815#issuecomment-2762127025). The crash is not related to the suggested check during device creation (just sloppy code).
=> layers: Fix crash when using not enabled feature

layers/gpuav/instrumentation/gpuav_shader_instrumentor.cpp
This PR removes non-semantic info from instrumented SPIR-V ouput if `VK_KHR_portability_subset` is enabled.  This is to prevent problems with shader compilers / cross-compilers (e.g. SPIR-V to MSL) and alternative graphics APIs (e.g. Metal) that don't understand SPIR-V non-semantic info.
Thanks to @spencer-lunarg for the solution.  I have simply created a PR with his suggested change and tested with Sascha Willems' _debugprintf_ sample and the Vulkan-Samples _shader_debugprintf_ example on macOS Ventura.  Both samples are now working fine.
Fixes #9819.
=> layers: Remove non-semantic info from SPIR-V if portability enabled

layers/core_checks/cc_spirv.cpp, layers/gpuav/spirv/vertex_attribute_fetch_oob.cpp, layers/state_tracker/shader_instruction.cpp, layers/state_tracker/shader_module.cpp, layers/state_tracker/shader_module.h, layers/stateless/sl_spirv.cpp
Small cleanup to use things like `ResultId()` and `TypeId()` helper where possible for future extension to apply easier
=> layers: Small cleanup of SPIR-V helpers

layers/gpuav/spirv/descriptor_class_general_buffer_pass.cpp, layers/gpuav/spirv/descriptor_class_texel_buffer_pass.cpp, layers/gpuav/spirv/descriptor_indexing_oob_pass.cpp, layers/gpuav/spirv/post_process_descriptor_indexing_pass.cpp, layers/state_tracker/shader_instruction.cpp, layers/state_tracker/shader_instruction.h, tests/unit/gpu_av_descriptor_indexing.cpp
We didn't handle `OpInBoundsAccessChain`, which are just `OpAccessChain` but known to be bounded statically (bounded as in they don't point outside the struct, not the memory that GPU-AV is checking)
=> gpuav: Handle OpInBoundsAccessChain

tests/unit/shader_cooperative_matrix.cpp
These tests were hitting:
```
Validation Error: [ VUID-VkShaderModuleCreateInfo-pCode-08737 ] | MessageID = 0xa5625282
vkCreateShaderModule(): pCreateInfo->pCode (spirv-val produced an error):
SPV_KHR_vulkan_memory_model extension requires SPIR-V version 1.3 or later.
OpExtension "SPV_KHR_vulkan_memory_model"
```
=> tests: Fix coop matrix tests

layers/core_checks/cc_synchronization.cpp, layers/state_tracker/fence_state.cpp, layers/state_tracker/fence_state.h, layers/state_tracker/image_state.cpp, layers/state_tracker/image_state.h, layers/state_tracker/semaphore_state.cpp, layers/state_tracker/semaphore_state.h, layers/state_tracker/state_tracker.cpp, tests/unit/sync_val_wsi_positive.cpp, tests/unit/wsi.cpp, tests/unit/wsi_positive.cpp
Addresses https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/9802
The main idea is to set a boolean flag as part of the semaphore state between QueuePresent and the next AcquireNextImage that returns the same image. If any QueueSubmit uses this semaphore as a signal and the semaphore's flag is set then it means  it can still be used by the presentation.
=> layers: Track semaphore is in use by swapchain

layers/state_tracker/state_tracker.h
This appeared to be causing problems with some MSVC 32 bit builds.
=> state_tracker: Use ! instead of not in HasSubState template

layers/vulkan/generated/chassis.cpp, scripts/generators/layer_chassis_generator.py
Don't rely on the intercept vector to set it, as some things don't intercept all calls that could return VK_ERROR_DEVICE_LOST.
=> scripts: Set all copies of vvl::base::Device::is_device_lost

layers/gpuav/spirv/descriptor_class_general_buffer_pass.cpp, layers/gpuav/spirv/descriptor_class_general_buffer_pass.h, layers/gpuav/spirv/pass.cpp, layers/gpuav/spirv/pass.h
1. Moves `FindLastByteOffset` to `FindOffsetInStruct` in `Pass` so BDA can use it in my next PR
2. Redid things so we don't need to awkwardly pass in `bool pre_pass` which was clumsy
=> gpuav: Move pre pass out of RequiresInstrumentation

layers/core_checks/cc_wsi.cpp, tests/unit/wsi_positive.cpp
CoreChecks::PreCallValidateGetDeviceGroupSurfacePresentModesKHR wants to call a validation method in the core::Instance class but it was using instance_state, which is the state tracker instead of in instance_proxy which is the core::Instance object. Bleah.
Fixes #9854
=> corechecks: Fix bad instance cast

layers/core_checks/cc_synchronization.cpp, layers/state_tracker/fence_state.cpp, layers/state_tracker/image_state.cpp, layers/state_tracker/image_state.h, layers/state_tracker/semaphore_state.cpp, layers/state_tracker/semaphore_state.h, layers/state_tracker/state_tracker.cpp
Follow up of https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/9840.
This tracks the history of the last few acquired swapchain images and uses this information to provide more informative error message to more clearly demonstrate the problem. The history of the acquired images can also be useful for debuggign swapchain issues.
Use case of swapchain with many images:
```
vkQueueSubmit(): pSubmits[0].pSignalSemaphores[0] (VkSemaphore 0x2afc0000002afc) is being signaled by VkQueue 0x14575689330, but it may still be in use by VkSwapchainKHR 0x1940000000194.
Here are the last 6 acquired image indices (brackets mark the last use of VkSemaphore 0x2afc0000002afc in a presentation operation): 0, 1, 2, [3], 4, 0.
Swapchain image 3 was presented but not re-acquired, so VkSemaphore …
```
=> layers: Update semaphore in use by swapchain error message

layers/chassis/chassis_manual.cpp, layers/sync/sync_validation.cpp, layers/sync/sync_validation.h
Make sure the state tracker runs last in vkDestroyDevice() and vkDestroyInstance().
Make sure syncval cleans up its custom state tracking in vkDestroyDevice().
=> chassis: Fix Device and Instance destroy order

layers/gpuav/core/gpuav_record.cpp, layers/gpuav/instrumentation/gpuav_instrumentation.cpp, layers/gpuav/resources/gpuav_state_trackers.cpp, layers/gpuav/resources/gpuav_state_trackers.h, layers/gpuav/shaders/gpuav_shaders_constants.h, layers/gpuav/validation_cmd/gpuav_copy_buffer_to_image.cpp, layers/gpuav/validation_cmd/gpuav_dispatch.cpp, layers/gpuav/validation_cmd/gpuav_draw.cpp, layers/gpuav/validation_cmd/gpuav_trace_rays.cpp, tests/unit/gpu_av_descriptor_class_general_buffer.cpp
Closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/9852
Actually nothing was done when reaching this limit, so I added the logic to skip validation when it is reached. It was more cumbersome to do than what I would like it to be...
The warning:
Validation Warning: [ GPU-AV::Max action per command buffer reached ] | MessageID = 0x275e89d
vkCmdDraw(): Reached maximum validation commands count for command buffer ( 8192 ). No more draw/dispatch/trace rays commands will be validated inside this command buffer.
Objects: 1
[0] VkCommandBuffer 0x1eaf1c58960
=> gpuav: Warn on reaching max actions cmd validation

layers/core_checks/cc_synchronization.cpp, layers/core_checks/core_validation.h, layers/sync/sync_vuid_maps.cpp, layers/sync/sync_vuid_maps.h, tests/unit/dynamic_rendering_local_read.cpp, tests/unit/image_layout.cpp, tests/unit/sync_object.cpp
During render pass instance (either dynamic rendering or render pass object) there can't be layout transitions (VU 01181). We did validation for render pass objects (but not in all required cases) and did not have validation for dynamic rendering. Some additional cleanup.
=> layers: Fix validation no layout transition during rendering

layers/gpuav/spirv/descriptor_indexing_oob_pass.cpp, layers/gpuav/spirv/descriptor_indexing_oob_pass.h, layers/gpuav/spirv/pass.cpp, layers/gpuav/spirv/pass.h, layers/gpuav/spirv/post_process_descriptor_indexing_pass.cpp, layers/gpuav/spirv/post_process_descriptor_indexing_pass.h, layers/gpuav/spirv/type_manager.cpp, layers/gpuav/spirv/type_manager.h, tests/unit/gpu_av_descriptor_indexing_positive.cpp
See https://godbolt.org/z/cfqnbq77f
The `data[b]` is statically known to be the same (Push Constant are readonly uniform) but the SPIR-V (from GLSL/HLSL/Slang) will produce multiple `OpLoad` that are all aliased and `spirv-opt` doesn't reduce these because it want to preserve the "lifetime" of a variable
Found this was the reason causing large shaders to still take a second or more to compile, with this, it is finally under!
Found in `StressDescriptroIndexPushConstantAccess` this gets it down to a single instrumentation
=> gpuav: Reduce duplicate indexing into descriptor array

layers/gpuav/spirv/buffer_device_address_pass.cpp, layers/gpuav/spirv/buffer_device_address_pass.h, tests/unit/gpu_av_buffer_device_address_positive.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/9725
We found shaders that would look "like"
```glsl
layout(buffer_reference) buffer BDA {
uint x[4096];
};
void main() {
BDA ptr;
ptr.x[4] = ptr.x[8] + ptr.x[12]
}
```
and our check would look like
```glsl
inst_bda(ptr + 6, 4);
inst_bda(ptr + 8, 4);
inst_bda(ptr + 12, 4);
ptr.x[6] = ptr.x[8] + ptr.x[12]
```
and would easily get 500+ instrumentation in a single shader, but just getting the being/end range statically it will now look like
```glsl
inst_bda(ptr + 6, 28); // covers range from x[4] to x[12]
ptr.x[6] = ptr.x[8] + ptr.x[12]
```
I got `PositiveGpuAVBufferDeviceAddress.Stress` down from 2 minutes to 0.3 seconds with this
I have a fossilize of the 5 worst pipeline in a large trace, it went from single-threaded …
=> gpuav: Reduce BDA when statically can detect range

layers/VkLayer_khronos_validation.json.in, layers/error_message/spirv_logging.cpp, layers/gpuav/core/gpuav_settings.h, layers/gpuav/instrumentation/gpuav_shader_instrumentor.cpp, layers/gpuav/instrumentation/gpuav_shader_instrumentor.h, layers/layer_options.cpp, tests/framework/error_monitor.h, tests/framework/layer_validation_tests.h, tests/framework/ray_tracing_objects.cpp, tests/framework/ray_tracing_objects.h, tests/unit/gpu_av.cpp, tests/unit/gpu_av_descriptor_class_general_buffer.cpp, tests/unit/gpu_av_ray_query.cpp, tests/unit/gpu_av_ray_query_positive.cpp
Closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/9771
Add the possibility to selectively instrument shaders with a debug name matching any regex from a list.
Still need to add support for shader objects, as the flow will be different
Edit: Also no support for GPL when shader modules have been destroyed before linking - we will miss instrumentation in this case
=> gpuav: Upgrade selective shader instrumentation

layers/state_tracker/shader_object_state.cpp
We do this in `vvl::ShaderModule` and just seemed to have forgot in shader object
without this, common code that just has the SPIR-V, is currently not printing out the `VkShadersEXT` handle
=> layers: Add handle to shader object spirv state

tests/unit/vertex_input_positive.cpp
Was hitting 
> Validation Error: [ VUID-vkCmdDraw-pNext-09461 ] | MessageID = 0xfefbb617
vkCmdDraw(): VkPipelineVertexInputDivisorStateCreateInfo::pVertexBindingDivisors[0].divisor is 2 and firstInstance is 1, but supportsNonZeroFirstInstance is VK_FALSE.
=> tests: Fix test on lavapipe

layers/core_checks/cc_cmd_buffer_dynamic.cpp, tests/unit/pipeline_topology.cpp, tests/unit/pipeline_topology_positive.cpp, tests/unit/shader_object.cpp, tests/unit/shader_object_positive.cpp
Add 3 drawtime VUs from https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/7281
(1 was a shader object that I made for both pipeline and shader object)
=> layers: Add runtime topology VU checks

layers/VkLayer_khronos_validation.json.in, layers/error_message/logging.cpp, layers/error_message/logging.h, layers/layer_options.cpp
After we cleaned up messages this option can't remove all dispatchable handles anymore and it's not cheap to rework this.
There's an alternative to run a filtering script over the message output, which produces identical result.
=> settings: Remove stable messages option

layers/core_checks/cc_synchronization.cpp, layers/core_checks/core_validation.h, tests/unit/dynamic_rendering_local_read.cpp
Follow up of https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/9878
Adds similar layout mismatch check we already have for render pass object for dynamic rendering.
=> layers: Check layout mismatch for dynamic rendering barrier

layers/core_checks/cc_spirv.cpp, layers/core_checks/core_validation.h, layers/drawdispatch/descriptor_validator.cpp, layers/drawdispatch/drawdispatch_vuids.cpp, layers/drawdispatch/drawdispatch_vuids.h, layers/state_tracker/descriptor_sets.cpp, layers/state_tracker/descriptor_sets.h, layers/state_tracker/pipeline_layout_state.cpp, layers/state_tracker/pipeline_layout_state.h, layers/state_tracker/shader_module.cpp, layers/state_tracker/shader_module.h, tests/framework/layer_validation_tests.cpp, tests/framework/layer_validation_tests.h, tests/unit/descriptors_positive.cpp, tests/unit/image_layout_positive.cpp, tests/unit/pipeline.cpp, tests/unit/sampler.cpp, tests/unit/sync_val.cpp, tests/unit/ycbcr.cpp, tests/unit/ycbcr_positive.cpp
The 2 drawtime VUs for YCbCr got moved to compile time, I moved them here
While here, I tried to add the new "you can't dynamically descriptor index into a YCbCr array" but hit many hard issues and going to defer it to https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/9893 (but at least I have plenty of good tests in here!)
=> layers: Move YCbCr check from drawtime to pipeline

layers/core_checks/cc_cmd_buffer_dynamic.cpp, layers/core_checks/cc_drawdispatch.cpp, layers/core_checks/core_validation.h, layers/gpuav/instrumentation/gpuav_instrumentation.cpp, layers/state_tracker/pipeline_state.cpp, layers/state_tracker/pipeline_state.h
Hit a small bug working on Dynamic State recently, so to help with that
1. Break up `ValidateDrawDynamicState` into a "vertex", "fragment" function
2. Instead of constantly going `!pipeline_state || pipeline_state->IsDynamic(state)`, now can just go `ast_bound_state.IsDynamic(state)`
=> Organize dynamic state functions

layers/gpuav/core/gpuav.h, layers/gpuav/core/gpuav_setup.cpp, layers/gpuav/descriptor_validation/gpuav_descriptor_set.cpp, layers/gpuav/descriptor_validation/gpuav_descriptor_set.h, layers/gpuav/resources/gpuav_state_trackers.cpp, layers/gpuav/resources/gpuav_state_trackers.h, layers/state_tracker/buffer_state.cpp, layers/state_tracker/buffer_state.h, layers/state_tracker/descriptor_sets.cpp, layers/state_tracker/descriptor_sets.h, layers/state_tracker/image_state.cpp, layers/state_tracker/image_state.h, layers/state_tracker/ray_tracing_state.h, layers/state_tracker/sampler_state.h, layers/state_tracker/state_tracker.h
Commit 313d1d4 caused a performance regression for very large bindless descriptor arrays. Redo the old implementation on top of sub states.
=> state_tracker: Fix bindless descriptor performance regression

layers/state_tracker/image_state.h, layers/vulkan/generated/spirv_validation_helper.cpp, scripts/generators/spirv_validation_generator.py, tests/unit/memory.cpp
In a few places, "requirements" is spelled "requirments".
=> Fix typo in "requirements"

layers/state_tracker/fence_state.cpp, layers/state_tracker/queue_state.h, layers/state_tracker/state_tracker.cpp, tests/unit/wsi_positive.cpp
* Fix waiting on present fence did not have effect
* More strict handling of QueueWaitIdle/DeviceWaitIdle. They don't have effect on present semaphores when swapchain maintenance 1 is enabled.
=> Present semaphore fixes

.github/workflows/sdk_android_build.yml, .github/workflows/vvl.yml
Ninja is now available by default on all the runner images.
The version of CMake provided by the runner images is always pretty new and gets updated frequently.
The main benefit of lukka/get-cmake was
1.) Test older version of cmake
2.) Get ninja and cache it.
Reason 2 is now outdated for most of these checks.
Removing it saves CI time & cache on runs that don't need it.
=> Utilize pre-installed Ninja

layers/core_checks/cc_spirv.cpp, layers/core_checks/core_validation.h
Try to clear code paths that are Pipeline/ShaderObject vs just Pipeline
`ValidateShaderTileImage` is a pipeline only check, so make the `vvl::Pipeline` a const ref
=> layers: Move ValidateShaderTileImage

layers/state_tracker/state_tracker.cpp, layers/state_tracker/state_tracker.h, tests/unit/gpu_av_positive.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/9916
will have another PR fixing other spots like this around state tracking
=> layers: Check created samplers for VK_SUCCESS

layers/gpuav/debug_printf/debug_printf.cpp, layers/gpuav/instrumentation/gpuav_shader_instrumentor.cpp, layers/gpuav/instrumentation/gpuav_shader_instrumentor.h, tests/unit/gpu_av_shader_debug_info.cpp
We were not saving the original SPIR-V and it was causing using Shader Debug Info to produce the wrong line from the source code (when using Shader Object)
=> gpuav: ShaderObject missing keeping old spirv

layers/chassis/chassis.h, layers/chassis/chassis_manual.cpp, layers/chassis/chassis_modification_state.h, layers/chassis/validation_object.h, layers/gpuav/instrumentation/gpuav_shader_instrumentor.cpp, layers/gpuav/instrumentation/gpuav_shader_instrumentor.h, layers/state_tracker/shader_object_state.h, layers/vulkan/generated/chassis.cpp, layers/vulkan/generated/dispatch_vector.cpp, layers/vulkan/generated/dispatch_vector.h, scripts/generators/dispatch_vector_generator.py, scripts/generators/layer_chassis_generator.py, tests/unit/gpu_av_indirect_buffer.cpp, tests/unit/gpu_av_shader_object_positive.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/9853
the `vkGetShaderBinaryDataEXT` is a problem for GPU-AV as we have already instrumented the shader
This change overrides `vkGetShaderBinaryDataEXT`  to return the original, non-instrumented shader. From here things work "as they should" as we ignore BINARY shaders coming in
=> gpuav: Handle Binary Shader Objects

layers/VkLayer_khronos_validation.json.in
This allows listing te short version of the Android system properties of a setting in the generated layer setting doc.
=> layer: Add 'prefix' in layer manifest, used by doc generation

layers/core_checks/cc_pipeline_graphics.cpp, layers/gpuav/instrumentation/gpuav_instrumentation.cpp, layers/state_tracker/pipeline_layout_state.cpp, layers/state_tracker/pipeline_layout_state.h, layers/state_tracker/pipeline_sub_state.cpp, layers/state_tracker/pipeline_sub_state.h, layers/state_tracker/shader_object_state.cpp, tests/unit/graphics_library.cpp, tests/unit/pipeline.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/9870
if you went
```
vkPipelineLayout pipeline_layout_vs(VK_PIPELINE_LAYOUT_CREATE_INDEPENDENT_SETS_BIT_EXT);
vkPipelineLayout pipeline_layout_fs(VK_PIPELINE_LAYOUT_CREATE_INDEPENDENT_SETS_BIT_EXT);
vkPipelineLayout pipeline_layout_link(0);
```
it would not produce a error, now it does
=> layers: Add Linking INDEPENDENT_SETS check

layers/best_practices/bp_instance_device.cpp, layers/best_practices/bp_wsi.cpp, layers/core_checks/cc_wsi.cpp, layers/state_tracker/device_state.cpp, layers/state_tracker/device_state.h, layers/state_tracker/state_tracker.cpp, tests/unit/threading_positive.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/9931
we didn't have `unordered_map<Func, CALL_STATE> call_state;` wrapped away in a thread safe environment
=> layers: Fix threading bug with PhyscialDevice

layers/gpuav/resources/gpuav_state_trackers.cpp, layers/state_tracker/queue_state.cpp, layers/state_tracker/queue_state.h, layers/state_tracker/state_tracker.cpp, tests/unit/gpu_av_descriptor_post_process.cpp, tests/unit/gpu_av_positive.cpp
attempts to close https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/9706
We currently were trying to signal the fence in `PreCallSubmit` and moved it to `PostCallSubmit` when using external fences
=> gpuav: Handle external fences

layers/core_checks/cc_cmd_buffer.cpp, layers/core_checks/cc_render_pass.cpp, layers/core_checks/core_validation.h, layers/state_tracker/cmd_buffer_state.cpp
I want to go
`const auto& cb_sub_state = core::SubState(cb_state);`
but we have `sub_cb_state` being randomly used to mean "secondary command buffer state" and want to clean that name space up
=> layers: Rename secondary command buffer state

layers/best_practices/bp_cmd_buffer.cpp, layers/core_checks/cc_cmd_buffer.cpp, layers/core_checks/cc_device_generated_commands.cpp, layers/core_checks/cc_queue.cpp, layers/core_checks/cc_render_pass.cpp, layers/core_checks/core_validation.h, layers/state_tracker/cmd_buffer_state.cpp, layers/state_tracker/cmd_buffer_state.h
We were storing a non-safe `VkCommandBufferInheritanceInfo` for no reason, this cleans that up
=> layers: Cleanup VkCommandBufferInheritanceInfo

layers/core_checks/cc_cmd_buffer.cpp, layers/core_checks/cc_state_tracker.cpp, layers/core_checks/cc_state_tracker.h, layers/core_checks/cc_synchronization.cpp, layers/core_checks/core_validation.h, layers/state_tracker/cmd_buffer_state.cpp, layers/state_tracker/cmd_buffer_state.h
- Gets some misc cleanup to get `vvl::CommandBuffer` stuff to some `core::CommandBufferSubState` going
- small starting win of getting `sizeof(vvl::CommandBuffer)` from `3880` to `3648`
=> layers: First step to moving cb state to core only

layers/best_practices/bp_copy_blit_resolve.cpp, layers/core_checks/cc_cmd_buffer.cpp, layers/core_checks/cc_cmd_buffer_dynamic.cpp, layers/core_checks/cc_descriptor.cpp, layers/core_checks/cc_drawdispatch.cpp, layers/core_checks/cc_image.cpp, layers/core_checks/cc_image_layout.cpp, layers/core_checks/cc_pipeline.cpp, layers/core_checks/cc_pipeline_graphics.cpp, layers/core_checks/cc_query.cpp, layers/core_checks/cc_queue.cpp, layers/core_checks/cc_render_pass.cpp, layers/core_checks/cc_synchronization.cpp, layers/core_checks/cc_video.cpp, layers/gpuav/descriptor_validation/gpuav_image_layout.cpp, layers/gpuav/resources/gpuav_state_trackers.cpp, layers/state_tracker/cmd_buffer_state.cpp, layers/state_tracker/cmd_buffer_state.h, layers/state_tracker/queue_state.cpp, layers/state_tracker/state_tracker.cpp
1. Use consistent naming style
2. Create a `Viewport`/`Scissor` struct to group viewport/scissor inheritances stuff
=> layers: Rename cleanup of vvl::CommandBuffer

layers/layer_options.cpp
If you turned on `printf_enable` it was accidentally turning on all of GPU-AV as well
(this wasn't happening in vkconfig, because vkconfig explicitly turns off GPU-AV when using printf)
=> printf: Turn off GPU-AV when using new printf layer setting

layers/gpuav/instrumentation/gpuav_instrumentation.cpp, layers/gpuav/instrumentation/gpuav_instrumentation.h, layers/gpuav/resources/gpuav_state_trackers.cpp, layers/gpuav/resources/gpuav_state_trackers.h, layers/gpuav/validation_cmd/gpuav_copy_buffer_to_image.cpp, layers/gpuav/validation_cmd/gpuav_dispatch.cpp, layers/gpuav/validation_cmd/gpuav_draw.cpp, layers/gpuav/validation_cmd/gpuav_trace_rays.cpp, layers/state_tracker/cmd_buffer_state.cpp
`LogInstrumentationError` has changed a lot, and this 
- Reduces what we pass in the lambda
- Makes better use of `InstrumentationErrorBlob`
=> gpuav: Simplify LogInstrumentationError

BUILD.gn, layers/CMakeLists.txt, layers/core_checks/cc_shader_object.cpp, layers/drawdispatch/descriptor_validator.cpp, layers/gpuav/core/gpuav.h, layers/gpuav/core/gpuav_record.cpp, layers/gpuav/core/gpuav_setup.cpp, layers/gpuav/instrumentation/gpuav_instrumentation.cpp, layers/utils/action_command_utils.h
While we instrument every Vertex shader for `VK_LAYER_GPUAV_VERTEX_ATTRIBUTE_FETCH_OOB`, it is only for indexed buffers (because for things like `VUID-vkCmdDraw-None-02721` we can validate on the CPU)
This just skips calling `GetVertexAttributeFetchLimits` when not required 
edit - I added another commit that just creates a single VkBuffer to point all the non-indexed draws at
=> gpuav: Skip VertexAttributeFetchOOB on normal draws

layers/containers/range_map.h, layers/containers/subresource_adapter.h, layers/core_checks/cc_image_layout.cpp, layers/state_tracker/image_layout_map.h, layers/state_tracker/image_state.cpp, layers/state_tracker/image_state.h
The reasons vvl hashmap did not compile with `ImageLayoutRangeMap`:
*  `ImageLayoutRangeMap` contained non-moveable/copyable `std::shared_mutex` and our hashmap sometimes wants to move/copy.
* The underlying `BothRangeMap` was copyable but in a buggy way - no compiler issues, but ASAN caught use-after-free because underlying byte storage did not handle copies/moves.
The `std::shared_mutex` fix is based on the observation that only those `ImageLayoutRangeMap`s get locked that are owned by the `vvl::Image`, so by moving a mutex inside the image the layout range maps become moveable. This also works for the case of aliased images that share a single layout range map. They all indirecty refer to a single mutex object (hold by one of the aliased images).
The `BothRangeMap` backing storage is …
=> layer: Use vvl hashmap for SubmissionImageLayoutMap

layers/gpuav/instrumentation/gpuav_instrumentation.cpp, layers/gpuav/resources/gpuav_state_trackers.cpp, layers/gpuav/resources/gpuav_vulkan_objects.cpp, layers/gpuav/resources/gpuav_vulkan_objects.h, layers/gpuav/validation_cmd/gpuav_copy_buffer_to_image.cpp, layers/gpuav/validation_cmd/gpuav_draw.cpp, tests/unit/gpu_av_positive.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/9786
For small allocations, sub-allocate in buffers
Stole the test from https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/9974 🥷
=> gpuav: Rework buffer caching

layers/core_checks/cc_drawdispatch.cpp, layers/gpuav/instrumentation/gpuav_instrumentation.cpp, layers/gpuav/validation_cmd/gpuav_validation_cmd_common.cpp, layers/state_tracker/cmd_buffer_state.cpp, layers/state_tracker/cmd_buffer_state.h, layers/state_tracker/last_bound_state.cpp, layers/state_tracker/last_bound_state.h, layers/state_tracker/state_tracker.cpp
going to need for future https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/9870 fix
everywhere we were setting `desc_set_pipeline_layout` already had to do a `Get<vvl::PipelineLayout>` prior so seemed wasteful to not just keep as a shared pointer
=> layers: Make desc_set_pipeline_layout shared pointer

docs/fine_grained_locking.md, layers/best_practices/best_practices_validation.h, layers/best_practices/bp_synchronization.cpp, layers/core_checks/cc_query.cpp, layers/core_checks/cc_synchronization.cpp, layers/core_checks/core_validation.h, layers/gpuav/core/gpuav.h, layers/gpuav/descriptor_validation/gpuav_image_layout.cpp, layers/state_tracker/state_tracker.cpp, layers/state_tracker/state_tracker.h, layers/sync/sync_validation.cpp, layers/sync/sync_validation.h
Talking to @artem-lunarg we agreed that by "**default**" we should assume all `vkCmd*` calls (that have no VkResult) should be recorded in `PostCallRecord`
PreCallRecord is reserved really for the "actually need to be in front"... thing like how GPU-AV will inject certain calls prior
This PR is a "first wave" of the easy to move over calls
=> layers: First wave of moving vkCmd calls to being PostCallRecord

layers/core_checks/cc_synchronization.cpp, layers/core_checks/core_validation.h, layers/state_tracker/state_tracker.cpp, layers/state_tracker/state_tracker.h
We had a `PreCallRecordCmdWaitEvents` and `PostCallRecordCmdWaitEvents` for no reason
same with CmdBindPipeline
so combined logic
=> layers: Combine Pre and Post records in core

layers/gpuav/core/gpuav.h, layers/gpuav/core/gpuav_record.cpp, layers/gpuav/descriptor_validation/gpuav_image_layout.cpp
all thing in `gpuav_image_layout.cpp` are `PostCallRecord` to match https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/9985
but things like `valcmd` we do actually need `PreCallRecord` and should be split up
(was strange to have `valcmd` in the `gpuav_image_layout` file)
=> gpuav: Split up CmdCopyBufferToImage Pre and Post

layers/best_practices/best_practices_validation.h, layers/best_practices/bp_cmd_buffer.cpp, layers/best_practices/bp_copy_blit_resolve.cpp, layers/best_practices/bp_drawdispatch.cpp, layers/best_practices/bp_pipeline.cpp, layers/best_practices/bp_render_pass.cpp, layers/best_practices/bp_state_tracker.cpp, layers/best_practices/bp_synchronization.cpp, layers/chassis/layer_object_id.h, layers/core_checks/cc_copy_blit_resolve.cpp, layers/core_checks/cc_device_memory.cpp, layers/core_checks/cc_image.cpp, layers/core_checks/cc_pipeline.cpp, layers/core_checks/cc_query.cpp, layers/core_checks/cc_queue.cpp, layers/core_checks/cc_ray_tracing.cpp, layers/core_checks/cc_render_pass.cpp, layers/core_checks/cc_synchronization.cpp, layers/gpuav/core/gpuav.h, layers/gpuav/core/gpuav_record.cpp, layers/gpuav/descriptor_validation/gpuav_image_layout.cpp, layers/gpuav/instrumentation/gpuav_shader_instrumentor.cpp, layers/sync/sync_validation.cpp, layers/vulkan/generated/best_practices.cpp, scripts/generators/best_practices_generator.py
The new order of how things run in the chassis is
- Pre Call LayerObjectTypeStateTracker
- Pre Call CoreCheck
- Pre Call Bp/SyncVal/GPU-AV
- Dispatch
- Post Call LayerObjectTypeStateTracker
- Post Call CoreCheck
- Post Call Bp/SyncVal/GPU-AV
This means `BaseClass::PreCallRecord` is just going to redo work (worst case be a bug)
Just simply removed them all
=> layers: Remove BaseClass::PreCallRecord

layers/containers/range.h, layers/containers/subresource_adapter.h, layers/core_checks/cc_image_layout.cpp, layers/gpuav/descriptor_validation/gpuav_image_layout.cpp, layers/state_tracker/image_layout_map.cpp, layers/state_tracker/image_layout_map.h
In `InitialLayoutState` only aspect mask member was used. Then remove `InitialLayoutState` altogether and store aspect mask directly inside `LayoutEntry`. For now, it's std::optional to have the same semantics as previous implementation (could be a null pointer), but initial testing shows it should be possible to just use regular field (need to update logic accordingly).
Also removes any possibility to access dangling pointers mentioned here: https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/9992
=> layers: Cleanup ImageLayoutRegistry::LayoutEntry

layers/best_practices/bp_cmd_buffer.cpp, layers/best_practices/bp_device_memory.cpp, layers/best_practices/bp_instance_device.cpp, layers/best_practices/bp_pipeline.cpp, layers/best_practices/bp_render_pass.cpp, layers/core_checks/cc_image.cpp, layers/core_checks/cc_render_pass.cpp, layers/core_checks/cc_spirv.cpp, layers/core_checks/cc_wsi.cpp, layers/gpuav/core/gpuav.h, layers/gpuav/core/gpuav_record.cpp, layers/gpuav/descriptor_validation/gpuav_image_layout.cpp, layers/gpuav/instrumentation/gpuav_shader_instrumentor.cpp, layers/sync/sync_validation.cpp
Same as https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/9998 but for `PreCallRecord`
We have things already that will make sure the Destroy/Free are getting ran LAST in the chassis, so don't need to manually do it here
=> layers: Remove BaseClass:PreCallRecord

tests/unit/pipeline.cpp
The issue was for example if `ds` is `0`, then the check `ds & combination.depthStencilSamples` will be `0 & 0`, which will return false, but this should count as combination found.
=> tests: Fix testing 02722

layers/best_practices/bp_pipeline.cpp, layers/core_checks/cc_pipeline_compute.cpp, layers/core_checks/cc_pipeline_graphics.cpp, layers/core_checks/cc_pipeline_ray_tracing.cpp, layers/state_tracker/state_tracker.cpp
We called `BaseClass::PreCallValidateCreate*Pipelines` but had no reason to anymore
=> layers: Remove PreCallValidate Pipeline BaseClass calls

layers/best_practices/bp_descriptor.cpp, layers/chassis/chassis_manual.cpp, layers/core_checks/cc_descriptor.cpp, layers/state_tracker/descriptor_sets.cpp, layers/state_tracker/descriptor_sets.h, layers/state_tracker/state_tracker.cpp, layers/state_tracker/state_tracker.h
Noticed we still have `BaseClass::PreCallValidate` for `vkAllocateDescriptorSets` but don't need it anymore
The order is
- Pre Call Validate | State Tracker | Populates `vvl::AllocateDescriptorSetsData`
- Pre Call Validate | Core Checks  | uses `vvl::AllocateDescriptorSetsData`
- Pre Call Record ... nothing
- Dispatch
- Post Call Record | State Tracker | uses `vvl::AllocateDescriptorSetsData` to create `vvl::DescriptorSet`
=> layers: Combine vvl::AllocateDescriptorSetsData

layers/gpuav/spirv/module.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/10003
=> gpuav: Don't DontInline

layers/sync/sync_validation.cpp
These `BaseClass::PreCallValidate` don't makes sense and just seem like copy-and-paste error from long ago when chassis functions were added
=> sync: Remove unused BaseClass calls

layers/stateless/sl_render_pass.cpp, tests/unit/subpass_positive.cpp
Update related to confirmation that TOP/BOTTOM are valid in subpass 
dependencies: https://gitlab.khronos.org/vulkan/vulkan/-/issues/4257#note_530233
So far it worked correctly even without this change because generated
code lists top/bottom meta stages for graphics pipe and
`syncAllCommandStagesByQueueFlags()` returns them. That probably will
change in the future and generated code will report only atomic stages. 
So changed code with that assusmption and added regression tests.
Also top/bottom are deprecated so their usage will be minimized in the
internal details and only added explicitly when it's necessary, similar
to how it's done in this PR.
=> layers: Add top/bottom  to the list of graphics meta stages

layers/core_checks/cc_synchronization.cpp, tests/unit/sync_object.cpp
Fixes small logic bug from new updated spec in https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/7118
- Without `maintenance8` you must have `VkDependencyFlags` of zero
- With `maintenance8` you are **only** allowed to have `VK_DEPENDENCY_QUEUE_FAMILY_OWNERSHIP_TRANSFER_USE_ALL_STAGES_BIT_KHR`
=> layers: Fix maintenance8 flags check

layers/chassis/chassis_manual.cpp, layers/state_tracker/state_tracker.cpp, tests/unit/best_practices.cpp, tests/unit/gpu_av.cpp, tests/unit/sync_val.cpp
Issue showed with destruction order in GPU-AV. We had:
gpuav::Device has a VMA allocator
gpuav::CommandBufferSubState uses this allocator
work work work ...
gpuav::Device gets destroyed
all gpuav::CommandBufferSubState get destroyed:
when state_tracker gets destroyed, all child objects are too, including CB and corresponding sub states
BOOM at "gpuav::Device gets destroyed" step,
when destroying allocator the gpuav::CommandBufferSubState still have allocated buffers
Correct Fix:
gpuav::Device has a VMA allocator
gpuav::CommandBufferSubState uses this allocator
work work work ...
all gpuav::CommandBufferSubState get destroyed
gpuav::Device gets destroyed
Properly only destroying sub states (and not base states) is complex, changes introduced here will make so that all objects linked to a …
=> layers: Workaround state destruction order

layers/best_practices/bp_descriptor.cpp, layers/core_checks/cc_descriptor.cpp, layers/state_tracker/state_tracker.cpp, layers/state_tracker/state_tracker.h, tests/unit/descriptors.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/10009
The new error message will include 
```
Where VK_DESCRIPTOR_TYPE_SAMPLER is found in the pool:
pPoolSizes[1].descriptorCount = 2
Where the allocation are being requested:
pSetLayouts[0]::pBindings[1].descriptorCount = 2
pSetLayouts[2]::pBindings[1].descriptorCount = 2
pSetLayouts[3]::pBindings[1].descriptorCount = 2
```
or 
```
Where VK_DESCRIPTOR_TYPE_STORAGE_BUFFER is found in the pool:
pPoolSizes[0].descriptorCount = 8
Where the allocation are being requested:
pSetLayouts[0]::pBindings[0].descriptorCount = 10 (adjusted for VK_DESCRIPTOR_BINDING_VARIABLE_DESCRIPTOR_COUNT_BIT)
```
type message to better show where these 2 totals (what the pool has and whats being asked) are coming from
=> layers: Print better error message for allocation warning

layers/best_practices/bp_render_pass.cpp, layers/core_checks/cc_render_pass.cpp, layers/core_checks/core_validation.h, layers/state_tracker/state_tracker.cpp, layers/state_tracker/state_tracker.h
We do need to do `EndRenderPass`/`EndRendering` in `PreCallRecord` because in the chassis it will run `LayerObjectTypeStateTracker` first and will clear the rendering
=> layers: Mark EndRendering Pre/Post

layers/state_tracker/state_tracker.cpp, layers/state_tracker/state_tracker.h
We had the `BindPipeine()` call in the PreCall but for no reason
=> layers: Combine PostCallRecordCmdBindShadersEXT

layers/gpuav/spirv/function_basic_block.h, layers/gpuav/spirv/module.cpp, layers/gpuav/spirv/post_process_descriptor_indexing_pass.cpp, layers/gpuav/spirv/post_process_descriptor_indexing_pass.h, tests/unit/gpu_av_descriptor_post_process_positive.cpp
While the Post Processing instrumentation is cheap, it is not free. From looking at a lot of shader dumps, I noticed we tend to go
```c
inst_post_process(1, 2, 3);
if (something) 
inst_post_process(1, 2, 3);
else
inst_post_process(1, 2, 3);
inst_post_process(1, 2, 3);
```
a lot, so this changes tracks a simple version of Post-Domination in order to detect as much as we can
Using a Godot sample I had running through fossilize with cache off, single threaded, we get quite a good speed up
```
// before
45 graphics pipelines took 23.143 s (accumulated time)
176 compute pipelines took 26.847 s (accumulated time)
// after
45 graphics pipelines took 17.693 s (accumulated time)
176 compute pipelines took 14.548 s (accumulated time)
```
also from the dump we got
```
Function: …
```
=> gpuav: Reduce post-dominated instructions for PostProcessing

layers/stateless/sl_ray_tracing.cpp, tests/unit/ray_tracing_pipeline.cpp
Add a check that warns when both `VK_PIPELINE_CREATE_2_RAY_TRACING_OPACITY_MICROMAP_BIT_EXT` and `VK_PIPELINE_CREATE_2_DISALLOW_OPACITY_MICROMAP_BIT_ARM` are used together in flags provided while creating ray tracing pipelines. Both are associated with the `VK_ARM_pipeline_opacity_micromap` extension.
=> layers: Validate flags for VK_ARM_pipeline_opacity_micromap

layers/error_message/logging.cpp, layers/gpuav/core/gpuav_features.cpp
```
Validation Warning: [ WARNING-GPU-Assisted-Validation ] | MessageID = 0x24b5c69f
vkCreateDevice(): Internal Warning: Adding a VkPhysicalDeviceTimelineSemaphoreFeatures to pNext with timelineSemaphore set to VK_TRUE
Objects: 1
[0] VkInstance 0x2a756b30
Validation Warning: [ WARNING-GPU-Assisted-Validation ] | MessageID = 0x24b5c69f
vkCreateDevice(): Internal Warning: Adding a VkPhysicalDeviceVulkanMemoryModelFeatures to pNext with vulkanMemoryModel and vulkanMemoryModelDeviceScope set to VK_TRUE
Objects: 1
[0] VkInstance 0x2a756b30
Validation Warning: [ WARNING-GPU-Assisted-Validation ] | MessageID = 0x24b5c69f
vkCreateDevice(): Internal Warning: Adding a VkPhysicalDeviceBufferDeviceAddressFeatures to pNext with bufferDeviceAddress set to VK_TRUE
Objects: 1
[0] VkInstance 0x2a756b30 …
```
=> gpuva: Remove Object Type spam on warnings

layers/core_checks/cc_pipeline.cpp, layers/core_checks/cc_pipeline_compute.cpp, layers/core_checks/cc_pipeline_graphics.cpp, layers/core_checks/cc_pipeline_ray_tracing.cpp, layers/core_checks/core_validation.h, layers/state_tracker/pipeline_state.cpp, layers/state_tracker/pipeline_state.h, layers/stateless/sl_pipeline.cpp, layers/stateless/sl_ray_tracing.cpp, layers/stateless/stateless_validation.h, tests/unit/pipeline.cpp, tests/unit/ray_tracing_pipeline.cpp
the `VkPipelineCreateFlags2CreateInfo` can be in the pNext of a pipeline creation, but the error messages currently will reference the ignored flags field instead (which caught me off gaurd)
We do this is stateless, and just never did it in core checks
while here, had to rearrange the RTX check a bit
=> Print better VkPipelineCreateFlags2CreateInfo messages

layers/gpuav/instrumentation/gpuav_shader_instrumentor.cpp, layers/gpuav/spirv/descriptor_class_general_buffer_pass.cpp, layers/gpuav/spirv/descriptor_class_texel_buffer_pass.cpp, layers/gpuav/spirv/module.cpp, layers/gpuav/spirv/module.h
Looking at Godot shaders, they have these massive SSBO structs used to bring everything in (ubershader) and found that turning on `VK_LAYER_GPUAV_FORCE_ON_ROBUSTNESS` makes everything fast again
```
// normal
109 graphics pipelines took 5.861 seconds
170 compute pipelines took 6.151 seconds
// with GPU-AV
109 graphics pipelines took 38.744 seconds
170 compute pipelines took 16.230 seconds
// with GPU-AV and VK_LAYER_GPUAV_FORCE_ON_ROBUSTNESS
109 graphics pipelines took 18.208 seconds
170 compute pipelines took 8.837 seconds
```
This is just the compile time, but the runtime was also much faster!
=> gpuav: Warn users to use robustness feature

layers/gpuav/instrumentation/gpuav_shader_instrumentor.cpp, tests/unit/gpu_av_shader_debug_info.cpp
Currently we printed the internal ID as a hex which was misleading
```
// before
Pipeline (aa00000000aa)
Shader Module (a300000000a3) (internal ID 11)
// now
Pipeline (0xaa00000000aa)
Shader Module (0xa300000000a3) (internal ID 17)
```
=> gpuav: Make internal shader ID print as decimal

layers/gpuav/spirv/log_error_pass.cpp, tests/unit/debug_printf.cpp, tests/unit/gpu_av_descriptor_class_general_buffer.cpp, tests/unit/gpu_av_descriptor_class_general_buffer_positive.cpp
While trying to look at https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/10036 I wrote these tests
discovered there is no `OpReturn` in Task shaders, only `OpEmitMeshTasksEXT`, so this showed we had no tests checking the new `inst_log_error` with Task shaders yet
Added a Debug Printf test as well for `vkCmdDrawMeshTasksIndirectEXT`
=> layers: Fix Task early return and add tests

layers/core_checks/cc_descriptor.cpp, layers/core_checks/cc_drawdispatch.cpp, layers/core_checks/cc_ray_tracing.cpp, layers/core_checks/cc_shader_object.cpp, layers/core_checks/core_validation.h, layers/drawdispatch/descriptor_validator.cpp, layers/state_tracker/cmd_buffer_state.cpp
Add `cb_state.GetObjectList` in more places that were missing it so we make sure to print the pipeline/shaderObject for a draw/dispatch VU
=> layers: Print out pipeline in draw spirv VUs

layers/gpuav/core/gpuav_record.cpp, tests/unit/gpu_av_descriptor_class_general_buffer.cpp, tests/unit/gpu_av_indirect_buffer.cpp, tests/unit/gpu_av_indirect_buffer_positive.cpp, tests/unit/ray_tracing.cpp
Caught in the Granite `multi-draw-indirect` test
Self validation was mad because we never handled `VkBufferUsageFlags2CreateInfo` correctly
=> gpuav: Handle VkBufferUsageFlags2CreateInfo

docs/gpu_av_development.md, docs/gpu_av_selective_shader.md, docs/gpu_validation.md
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/9714
Makes the GPU-AV landing page more of "I'm a developer, tell me what I care about"
as we constantly blend up the internals of GPU-AV we can update the other documentations
=> docs: Update GPU-AV Docs

layers/VkLayer_khronos_validation.json.in, layers/layer_options.cpp, layers/sync/sync_error_messages.cpp, layers/sync/sync_reporting.cpp, layers/sync/sync_reporting.h, layers/sync/sync_settings.h, tests/unit/layer_settings_positive.cpp
Prepare "pretty print extra properties" option for removal in future SDKs. The ability to change formatting a bit contradicts with the main feature of extra properties that they are easy to parse and stable, if you change formatting it's easy to break parsing code. Quickly considered this when introduced a feature but unfortunatley decided to add a "nice" feature.
@spencer-lunarg please check if that's the changes that we discussed.
=> layers: Remove extra properties pretty print

layers/chassis/dispatch_object_manual.cpp, layers/core_checks/cc_descriptor.cpp, layers/state_tracker/special_supported.h
From https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/7298 (will be in 1.3.314 spec)
We can ignore these limit VUs if the feature is not supported on the device
=> layers: Add check for UAB features

tests/unit/debug_printf.cpp
Might be a VU missing here
https://gitlab.khronos.org/vulkan/vulkan/-/issues/4274
=> tests: Fix debug printf dgc test

layers/core_checks/cc_copy_blit_resolve.cpp, layers/state_tracker/device_memory_state.h, tests/unit/copy_buffer_image.cpp
Probably one of our worst messages
```
vkCmdCopyImageToBuffer(): pRegions[0] Detected overlap between source and dest regions in memory.
```
now actually tells you how it found that and where the regions overlapping are
```
vkCmdCopyImageToBuffer(): pRegions[0] Detected overlap between src and dst regions in memory while trying to copy 0x64 bytes.
Overlapped memory is (VkDeviceMemory 0x60000000006) on range [48, 64).
bufferOffset (48) creates region of [48, 112)
imageOffset (x = 1, y = 1, z = 0) creates region of [0, 64).
```
The `imageOffset (x = 1, y = 1, z = 0) creates region of [0, 64).` feels wrong, because it currently takes the offset.z as everything being zero when dealing with OPTIMAL layout, looking into fixing that, but it doesn't effect this change itself
=> layers: Improve 00184 00173 error message

layers/core_checks/cc_image_layout.cpp, layers/core_checks/cc_synchronization.cpp, layers/core_checks/core_validation.h
Inline `RecordTransitionImageLayouts` into `RecordBarriers`. With this change `RecordBarriers` does everything, so no need to think about layout transitions. New version also removes one initialization of `ImageBarrier` object comparing to the  previous version.
For GPU-AV it makes sense to use aggregate `TransitionImageLayouts` because there is no additional barrier code similar to `RecordBarriers`.
=> layers: Remove TransitionImageLayouts from corechecks

layers/core_checks/cc_image_layout.cpp, layers/core_checks/cc_state_tracker.cpp, layers/core_checks/cc_state_tracker.h, layers/core_checks/cc_synchronization.cpp, layers/core_checks/core_validation.h, tests/unit/dynamic_rendering_local_read.cpp
This does submit time validation of VUIDs like `VUID-vkCmdPipelineBarrier2-image-09555` when it's not possible to do this at record time (command buffer did not specify layout earlier).
=> layers: Add submit validation of dynamic rendering barriers

layers/core_checks/cc_device_generated_commands.cpp, tests/unit/device_generated_commands.cpp, tests/unit/device_generated_commands_positive.cpp
adds VUID-vkCmdExecuteGeneratedCommandsEXT-indirectCommandsLayout-10769 from 1.4.315 spec
=> layers: Add DGC in renderpass check

layers/best_practices/bp_pipeline.cpp, layers/core_checks/cc_spirv.cpp, layers/core_checks/core_validation.h, layers/state_tracker/shader_module.cpp, layers/state_tracker/shader_module.h, tests/unit/shader_cooperative_matrix.cpp, tests/unit/shader_cooperative_matrix_positive.cpp
From https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/7308
adds `VUID-RuntimeSpirv-OpTypeCooperativeMatrixKHR-10770` and `VUID-RuntimeSpirv-OpTypeCooperativeMatrixKHR-10771`
originally thought I would need `LocalSize` so made the change, but just kept it and made a separate commit
=> layers: Add CooperativeMatrix version check

layers/core_checks/cc_image_layout.cpp, layers/core_checks/core_validation.h, layers/state_tracker/image_layout_map.cpp, layers/state_tracker/image_layout_map.h
That's a minor cleanup that makes `VerifyImageLayoutRange` more explicit (no factory template parameters), but also cleans up a bit `ImageLayoutRegistry`.
The goal for the next PRs is to represent layout information in a more unified way, with a central range map type, instead of using 3 range map types depending on the context (command buffer, submit, global).
=> layers: Cleanup image layout code

tests/icd/test_icd.cpp
Fixes `NegativeWsi.SwapchainUseAfterDestroy` on Wayland
=> icd: Fix GetSwapchainImagesKHR

tests/unit/gpu_av_shader_debug_info.cpp
If running Self Val with latest changes, noticed we missed these `shaderRelaxedExtendedInstruction` features
=> tests: Add missing shaderRelaxedExtendedInstruction

layers/containers/range_map.h, layers/state_tracker/cmd_buffer_state.cpp, layers/state_tracker/cmd_buffer_state.h, layers/state_tracker/image_layout_map.cpp, layers/state_tracker/image_layout_map.h
* Remove layout map compatibility check
* Do not return update status from splice
* Misc cleanup of layout map interface
There are few commits and comments explain reasoning behind some changes, but in general that's still small changes that make things a bit simpler.
=> layers: Misc image layout map cleanup

layers/core_checks/cc_cmd_buffer.cpp, layers/core_checks/cc_image_layout.cpp, layers/core_checks/cc_queue.cpp, layers/core_checks/cc_state_tracker.cpp, layers/core_checks/cc_synchronization.cpp, layers/core_checks/core_validation.h, layers/gpuav/descriptor_validation/gpuav_image_layout.cpp, layers/state_tracker/cmd_buffer_state.cpp, layers/state_tracker/cmd_buffer_state.h, layers/state_tracker/image_layout_map.cpp, layers/state_tracker/image_layout_map.h, layers/state_tracker/image_state.cpp, layers/state_tracker/image_state.h, layers/state_tracker/render_pass_state.cpp
The first part of changes is that I started moving types in `image_layout_map.h` to represent directly maps rather than additional abstractions over maps (still in progress). We have two image layout map types:
* `CommandBufferImageLayoutMap` - tracks layouts of image subresources during command buffer recording, and in addition to the current layout also tracks the first layout used by the command buffer
* `ImageLayoutMap` - directly stores layouts of image subresources
The second part is related to `Registry` naming (yes, I remember we discussed this... I realized too late). `Registry` was used to represent per-image layout information, but this name is better suited to represent global storage, that collects information for all images (so that's the registry). So `Registry` is a …
=> layers: Rename many image layout names

layers/core_checks/cc_wsi.cpp, layers/core_checks/core_validation.h, tests/unit/wsi.cpp, tests/unit/wsi_positive.cpp
To help silent error in https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/10112 until we get a fix
=> layers: Supress WSI native object check

tests/framework/video_objects.h, tests/unit/dynamic_state.cpp
Fixes build errors when building the unittests with gcc 11.0 on Ubuntu 22.04
=> tests: Add missing cmath includes

layers/core_checks/cc_image_layout.cpp, layers/core_checks/cc_state_tracker.cpp, layers/gpuav/descriptor_validation/gpuav_image_layout.cpp, layers/state_tracker/image_layout_map.cpp, layers/state_tracker/image_layout_map.h, layers/state_tracker/image_state.cpp, layers/state_tracker/image_state.h
The lock functionality is moved to `vvl::Image`. This allows to use `BothRangeMap` type directly as layout map. Also not all layout maps need a lock (only for global layout tracking), so without lock inside the map the code is cleaner for such use cases.
In case of aliased images the lock is shared via `shared_ptr` (in the same way as layout map is shared). In the previous implementation the lock existed in each image, and in case of aliasing some locks were unused (there was a chance to use a wrong lock).
=> layers: Make ImageLayoutMap a regular map

layers/core_checks/cc_cmd_buffer.cpp, layers/core_checks/cc_copy_blit_resolve.cpp, layers/core_checks/cc_image.cpp, layers/core_checks/cc_image_layout.cpp, layers/gpuav/descriptor_validation/gpuav_image_layout.cpp, layers/state_tracker/cmd_buffer_state.cpp, layers/state_tracker/cmd_buffer_state.h, layers/state_tracker/descriptor_sets.cpp, layers/state_tracker/image_layout_map.cpp, layers/state_tracker/image_layout_map.h, layers/state_tracker/image_state.h
This is to avoid confusion, as we already use the term "initial layout" to refer both to `VkImageCreateInfo::initialLayout` and also `initialLayout` specified in various render pass structures.
The *"first layout"* is the first detected layout of the image subresource in the command buffer.
The new term has a matching *"first access"* syncval naming, which means that we track the first memory access in the command buffer to use later for submit-time or `CmdExecuteCommands` validation.
=> layers: Rename initial layout to first layout

layers/containers/subresource_adapter.cpp, layers/core_checks/cc_copy_blit_resolve.cpp, layers/core_checks/cc_image.cpp, layers/core_checks/cc_vuid_maps.cpp, layers/core_checks/cc_vuid_maps.h, layers/core_checks/core_validation.h, layers/state_tracker/image_state.cpp, layers/utils/vk_layer_utils.cpp, scripts/known_good.json, tests/device_profiles/max_profile.json, tests/unit/copy_buffer_image.cpp, tests/unit/copy_buffer_image_positive.cpp, tests/unit/host_image_copy.cpp, tests/unit/image.cpp, tests/unit/sync_val.cpp, tests/unit/ycbcr.cpp
This is a complete rework of the `cc_copy_blit_resolve.cpp` file
We had many open issues and the core issue was the lack of fully grasping how image copies work with the many permutations of formats and functions calls
I have a few things I need to do after this PR (which will include getting agreement from the working group on spec issues)
This for the short term is a functionally correct cleanup.
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/1946
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/9209
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/6898
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/9537
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/9276
closes …
=> layers: Refactor copy image

layers/state_tracker/cmd_buffer_state.cpp
Fixes VU going
> There was a call to vkCmdBindPipeline that didn't have VK_DYNAMIC_STATE_RASTERIZATION_SAMPLES_EXT and invalidated the prior vkCmdSetRasterizationSamplesEXT call
when no pipeline is used (and the OS doesn't implicitly zero init the `histroy` field)
=> layers: Properly clear command buffer dynamic state

scripts/known_good.json, scripts/tests.py, tests/icd/CMakeLists.txt
Seems just never took time to check, but the MockAHB test do run on TestICD, so we can safely remove `Vulkan-Tools` now in `known_goods.json`
=> tests: Use TestICD for MockAHB

layers/core_checks/cc_spirv.cpp
Found people easily get tripped up that Slang will let you name the function `fragmentMain` but will output `"main"` in the SPIR-V as that has basically become the "default"
This adds an extra level of information in the error message if users are messing this up
=> layers: Better entrypoint error message

BUILD.gn, layers/CMakeLists.txt, layers/gpuav/core/gpuav.h, layers/gpuav/core/gpuav_record.cpp, layers/gpuav/descriptor_validation/gpuav_descriptor_set.cpp, layers/gpuav/descriptor_validation/gpuav_descriptor_set.h, layers/gpuav/descriptor_validation/gpuav_descriptor_validation.cpp, layers/gpuav/descriptor_validation/gpuav_descriptor_validation.h, layers/gpuav/instrumentation/gpuav_instrumentation.cpp, layers/gpuav/instrumentation/gpuav_instrumentation.h, layers/gpuav/instrumentation/post_process_descriptor_indexing.cpp, layers/gpuav/instrumentation/post_process_descriptor_indexing.h, layers/gpuav/resources/gpuav_shader_resources.h, layers/gpuav/resources/gpuav_state_trackers.cpp, layers/gpuav/resources/gpuav_state_trackers.h, layers/gpuav/resources/gpuav_vulkan_objects.cpp, layers/gpuav/resources/gpuav_vulkan_objects.h, layers/gpuav/spirv/post_process_descriptor_indexing_pass.cpp, layers/gpuav/spirv/post_process_descriptor_indexing_pass.h, layers/vulkan/generated/chassis.cpp, layers/vulkan/generated/feature_requirements_helper.cpp, scripts/generate_spirv.py, scripts/generators/layer_chassis_generator.py
VkBuffer used in GPU-AV's "post processing" step to validate correct usage of descriptors were only tied to a descriptor set:
It meant that we could run into synchronization issues where we would read the content of a buffer on the CPU while potentially it was still in use on the GPU.
To avoid needless waits, proposed solution is to move to "per command buffer submission" post processing buffers:
When a command buffer is submitted, post processing buffers are allocated _for this submission_, ensuring that when CPU reads them, at command buffer completion time, no concurrent access can happen.
Doing the necessary changes showed that we have a tendency to clobber functions that should be generic, or internally maintained state objects such as command buffer state, descriptor set state, with …
=> gpuav: Per cb submission buffers for post process

layers/state_tracker/shader_module.cpp, tests/unit/gpu_av_descriptor_class_general_buffer_positive.cpp, tests/unit/shader_limits.cpp
As discussed in https://gitlab.khronos.org/vulkan/vulkan/-/issues/4121
When it comes to an arrayStride, if you have
```
Type x[4] // arrayStride 16
```
You calculate this as `(16 * (length - 1)) + sizeof(Type)`
The 2 spots we care about "size" is
1. Total size of limits, like `maxComputeSharedMemorySize`
2. GPU-AV OOB checks
so wrote tests for each
=> layers: Fix ArrayStride

layers/VkLayer_khronos_validation.json.in
This will allow the validation layer to trigger Vulkan Configurator messages when specific settings conditions are met and perform actions to help the application developer to use the validation layer correct.
The JSON message is described in the layer manifest JSON schema: [vkconfig_core/layers/layers_schema.json](https://github.com/LunarG/VulkanTools/pull/2371/files#diff-c42aa61052ad5dc7e1ac24c49fc20aa1d8b19768273d91dccc625ac882c977ec)
=> layer: Add layer-defined messages

layers/VkLayer_khronos_validation.json.in
This PR better document layer settings in layer manifest, for Vulkan Configurator UI and generated layer usages in July SDK
This is enabled by https://github.com/LunarG/VulkanTools/pull/2384
With https://github.com/LunarG/VulkanTools/pull/2398, we will be able to use "DEBUG" instead of "ADVANCED" which will be clearer but will require a new version of Vulkan Configurator.
The manifest changes are validated using this version of the manifest schema: https://github.com/LunarG/VulkanTools/pull/2405
=> layers: Clarify `status` and `view` settings to make using validation layer easier

layers/gpuav/core/gpuav.h, layers/gpuav/core/gpuav_record.cpp, layers/gpuav/core/gpuav_setup.cpp, layers/gpuav/descriptor_validation/gpuav_descriptor_set.cpp, layers/gpuav/descriptor_validation/gpuav_descriptor_set.h, layers/gpuav/instrumentation/descriptor_checks.cpp, layers/gpuav/instrumentation/descriptor_checks.h, layers/gpuav/instrumentation/post_process_descriptor_indexing.cpp, layers/gpuav/resources/gpuav_state_trackers.h, layers/layer_options.cpp
`desc_heap_` is no more explicitly in `Validator`, and now is indirectly managed by `gpuav.shared_resources_manager`
=> gpuav: More more stuff to descriptor_checks

layers/core_checks/cc_drawdispatch.cpp, layers/drawdispatch/drawdispatch_vuids.cpp, layers/drawdispatch/drawdispatch_vuids.h, tests/unit/command.cpp
`VK_QCOM_tile_shading` added ability to dispatch in a renderpass, this VU was generated before, but now is explicit
=> layers: Check dispatch in renderPass

layers/layer_options.cpp, tests/unit/layer_settings_positive.cpp
as discussed with @arno-lunarg (and others) these 2 settings are not desired and after the July SDK we will remove them
=> gpuav: Mark old advanced settings for deprecation

layers/core_checks/cc_copy_blit_resolve.cpp, tests/unit/copy_buffer_image.cpp, tests/unit/copy_buffer_image_positive.cpp
missed `DescribeSubresourceLayers` for one group of checks and added tests @ziga-lunarg gave me to reproduce
=> layers: Improve error message for copies

scripts/generators/object_tracker_generator.py
Some `object_tracker.cpp` warnings from new ARM extension not having generated VUID
=> scripts: Supress more VUID churn 317 headers

layers/state_tracker/descriptor_sets.cpp, layers/state_tracker/descriptor_sets.h, tests/unit/gpu_av_descriptor_indexing_positive.cpp
found in https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/9651 we missed adding back `NotifyUpdate()` and since then, if you re-updated your descriptor set we never were updating the buffer in GPU-AV
=> gpuav: Add missing NotifyUpdate

layers/core_checks/cc_buffer.cpp, layers/core_checks/cc_cmd_buffer.cpp, layers/core_checks/cc_copy_blit_resolve.cpp, layers/core_checks/cc_descriptor.cpp, layers/core_checks/cc_device.cpp, layers/core_checks/cc_device_memory.cpp, layers/core_checks/cc_drawdispatch.cpp, layers/core_checks/cc_query.cpp, layers/core_checks/cc_ray_tracing.cpp, layers/core_checks/cc_video.cpp, layers/core_checks/core_validation.h, layers/gpuav/core/gpuav_record.cpp, layers/state_tracker/buffer_state.cpp, layers/state_tracker/buffer_state.h, layers/state_tracker/state_tracker.cpp, layers/stateless/sl_buffer.cpp, tests/unit/atomics.cpp, tests/unit/buffer.cpp, tests/unit/buffer_positive.cpp, tests/unit/descriptor_buffer.cpp, tests/unit/descriptors.cpp, tests/unit/descriptors_positive.cpp, tests/unit/ray_tracing.cpp, tests/unit/shader_object.cpp, tests/unit/vertex_input.cpp, tests/unit/vertex_input_positive.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/10238
There were 2 sets of VUs that referenced 
which we had wrong
=> Correctly use Buffer View usage 2 flag

layers/core_checks/cc_descriptor.cpp, layers/core_checks/core_validation.h, layers/state_tracker/descriptor_sets.h, layers/state_tracker/state_tracker.cpp, layers/state_tracker/state_tracker.h, tests/unit/descriptors.cpp, tests/unit/descriptors_positive.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/10232
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/7472
1. Fixes  AccelerationStructure when used in template updates
2. Adds proper check for object tracking for template updates (could probably be polished up when have energy to cleanup descriptor code for the n'th time)
=> layers: Add DescriptorTemplate object tracking support

layers/state_tracker/state_tracker.cpp, layers/state_tracker/state_tracker.h, tests/unit/gpu_av.cpp, tests/unit/object_lifetime.cpp
noticed that `DestroyObjectMaps()` was missing clearing some state tracking
the only things that would happen is between creating/destroying devices we would could have ever growing state tracking for the things missing
=> layers: Add missing state to DestroyObjectMaps

layers/vulkan/generated/stateless_validation_helper.cpp, scripts/generators/stateless_validation_helper_generator.py
Noticed we were generating code that was unused/not-needed
I hope the  compilers were smart enough to optimize it out, but incase they weren't, this will guarantee there is not work wasted on no-ops
=> scripts: Remove unused generated stateless code

layers/core_checks/cc_image.cpp, layers/core_checks/cc_synchronization.cpp, layers/core_checks/core_validation.h, tests/unit/image.cpp, tests/unit/image_positive.cpp
Addresses https://gitlab.khronos.org/vulkan/vulkan/-/issues/4308
> Validation Warning: [ WARNING-VkImageSubresourceRange-layerCount-compatibility ] | MessageID = 0x9b0d5645
vkCmdPipelineBarrier(): pImageMemoryBarriers[0].subresourceRange.layerCount is 1 for a 3D image (VkImage 0x40000000004) created with VK_IMAGE_CREATE_2D_ARRAY_COMPATIBLE_BIT. The maintenance9 feature is not currently enabled, so layerCount refers to all depth slices. When maintenance9 is enabled, it instead refers to a single depth slice. To remain forward-compatible, layerCount should be set to VK_REMAINING_ARRAY_LAYERS.
=> layers: Add warning for 3d image with 2d array compat

layers/core_checks/cc_drawdispatch.cpp, layers/core_checks/core_validation.h, layers/gpuav/instrumentation/gpuav_instrumentation.cpp, layers/state_tracker/cmd_buffer_state.cpp, layers/state_tracker/last_bound_state.cpp, layers/state_tracker/last_bound_state.h
The core goal was to try and squeeze a few cycles out of `vkCmdDrawIndexed` which I found in my traces get called millions of times
I noticed in the `PreCallValidateCmdDrawIndexed` we were calling a few things multiple times as it went through all the functions
This change mainly
1. sets up `LastBound last_bound_state` right away as it is used all the way through the functions (and you can get `cb_state` out of it easily)
2. Use `vvl::DrawDispatchVuid& vuid` from the start instead of grabbing it multiple times in multiple functions
3. group logic together, I caught we were doing `Get<vvl::Buffer>()` twice for the Indexed Buffer, now its all together so was easy to spot and reduce it to a single state tracking lookup
----
Ran multiple times with and without this change back-to-back and …
=> Reduce redundant look ups at drawtime

layers/core_checks/cc_cmd_buffer.cpp, tests/unit/secondary_command_buffer.cpp, tests/unit/secondary_command_buffer_positive.cpp
This fixes false positive part of https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/7896.
Need also another PR to fix that error message can print normalized layout instead of original one.
The regression test reproduces the same message as in the issue:
> Validation Error: [ UNASSIGNED-vkCmdExecuteCommands-commandBuffer-00001 ] | MessageID = 0xfa96ea8e
vkCmdExecuteCommands(): pCommandBuffers[0] was executed using VkImage 0x40000000004 (subresource: aspectMask VK_IMAGE_ASPECT_COLOR_BIT, array layer 0, mip level 0) which expects layout VK_IMAGE_LAYOUT_READ_ONLY_OPTIMAL--instead, image current layout is VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL.
=> layers: Fix image layout comparison for secondary cmdbuf

tests/unit/gpu_av_descriptor_post_process.cpp, tests/unit/gpu_av_descriptor_post_process_positive.cpp
@artem-lunarg helped narrow down why we had to blacklist these tests, taking a closer look, I am testing that two separate draws/dispatch work and the tests assume the order they are recorded in, so was a matter of missing the barrier
=> tests: Add missing barriers from tests

layers/core_checks/cc_cmd_buffer.cpp, layers/core_checks/cc_image_layout.cpp, layers/state_tracker/cmd_buffer_state.cpp, layers/state_tracker/cmd_buffer_state.h, layers/state_tracker/image_layout_map.cpp, layers/state_tracker/image_layout_map.h, layers/utils/image_layout_utils.cpp, layers/utils/image_layout_utils.h, tests/unit/secondary_command_buffer.cpp
Previously we could print normalized image used internally by vvl.
It is likely that related requires additional massaging.
Some behavior related to aspect masks is not super well defined.
Closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/7896
=> layers: Print original image layout in the error messages

tests/framework/binding.cpp, tests/framework/binding.h, tests/framework/layer_validation_tests.h, tests/framework/render.cpp, tests/framework/render.h, tests/framework/test_framework.cpp, tests/framework/test_framework.h, tests/icd/test_icd.cpp, tests/unit/wsi_positive.cpp
This was an attempt to fix CI on github from not running our WSI checks, I realize now it is a different problem, but still want this change in as we actually didn't have a Wayland helper for `InitSurface` which we will want in the future
=> tests: Add proper Wayland support 

layers/state_tracker/state_tracker.cpp
This makes computations for CmdBindVertexBuffer2 consistent with v1.
Here is the original code that was replaced (with two sections X and Y to refer to):
```
// X
vertex_buffer_binding.effective_size = pSizes ? pSizes[i] : VK_WHOLE_SIZE;
// Y
if (vertex_buffer_binding.effective_size == VK_WHOLE_SIZE) {
vertex_buffer_binding.effective_size = Buffer::GetRegionSize(buffer_state, pOffsets[i], VK_WHOLE_SIZE);
}
```
and it was replaced by Z:
```
// Z
vertex_buffer_binding.effective_size = Buffer::GetRegionSize(buffer_state, pOffsets[i], pSizes ? pSizes[i] : VK_WHOLE_SIZE);
```
In the old code `vertex_buffer_binding.effective_size` in the line X could be evaluated either to a) VK_WHOLE_SIZE or b) to something else. Lets check both cases:
a) X evaluates to VK_WHOLE_SIZE . It's easy to see that Z …
=> layers: Update vertex data efficient size computation

layers/gpuav/core/gpuav_record.cpp
we added this in https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/6527 (and even added tests) but seems we mixed up `kDebugInputBindlessMaxDescriptors` (which is 4 million) for `kDebugInputBindlessMaxDescSets` (which is 32)
=> gpuav: Fix maxUpdateAfterBindDescriptorsInAllPools

layers/core_checks/cc_android.cpp, layers/core_checks/cc_descriptor.cpp, layers/core_checks/cc_image.cpp, layers/core_checks/core_validation.h, layers/stateless/sl_descriptor.cpp, layers/stateless/sl_image.cpp, layers/stateless/stateless_validation.h
Future extension will need to validate `VkImageViewCreateInfo` and `VkSamplerCreateInfo` without the normal entry points, so created dedicated `ValidateCreateInfo` function so the future extension can just call into them as well
=> layers: Create dedicated struct for validating resource

scripts/known_good.json
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/10124 with https://github.com/KhronosGroup/Vulkan-Utility-Libraries/pull/299
=> scripts: Update VUL for env var fix

tests/unit/wsi_positive.cpp
TL;DR We mixed two type of queries generic and per-present mode. The implementation assumes that the last query is the one that was used to decide on swapchain parameters.
Closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/10285
`minImageCount validation` takes into account per-present mode limits if we used surface caps queries that specify per-present mode parameters. It is part of surface caching (implemented here https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/8794/files, `IsLastCapabilityQueryUsedPresentMode` check).
If application mixes both generic queries and per-present queries then validation does not have a way to decide based on which query we made decision how to initialize swapchain parameters (one of the gaps of Vulkan swapchain api design): …
=> tests: Fix surface caching related issue

layers/core_checks/cc_video.cpp
Not sure how nobody else got this, but for me the build was failing with:
```
/home/nnn/Projects/Vulkan-ValidationLayers/layers/core_checks/cc_video.cpp: In instantiation of ‘bool core::ValidateVideoProfileInfo(const StateObject&, const VkVideoProfileInfoKHR*, const ErrorObject&, const Location&) [with StateObject = core::Instance; VkVideoProfileInfoKHR = VkVideoProfileInfoKHR]’:
/home/nnn/Projects/Vulkan-ValidationLayers/layers/core_checks/cc_video.cpp:1004:111:   required from here
/home/nnn/Projects/Vulkan-ValidationLayers/layers/core_checks/cc_video.cpp:856:17: error: variable ‘codec_feature_not_enabled_msg’ set but not used [-Werror=unused-but-set-variable]
856 |     const char *codec_feature_not_enabled_msg = "is %s but the %s device feature is not enabled.";
| …
```
=> layers: Fix unused variable build error

tests/framework/layer_validation_tests.h, tests/framework/render.cpp, tests/framework/render.h, tests/unit/sync_val_wsi_positive.cpp, tests/unit/wsi.cpp, tests/unit/wsi_positive.cpp
Remove `TransitionToPresent` helper and use `SetPresentImageLayout` in most places. There are some places where manual recording of present transition is still needed but those few lines of code are arguably easier to read comparing to using `TransitionToPresent`.
=> tests: Simplify transition to present layout in wsi tests

layers/core_checks/cc_cmd_buffer_dynamic.cpp, layers/core_checks/cc_drawdispatch.cpp, layers/core_checks/cc_pipeline_graphics.cpp, layers/core_checks/core_validation.h, layers/drawdispatch/drawdispatch_vuids.cpp, layers/drawdispatch/drawdispatch_vuids.h, layers/state_tracker/cmd_buffer_state.cpp, layers/state_tracker/cmd_buffer_state.h, layers/state_tracker/last_bound_state.cpp, layers/state_tracker/last_bound_state.h, tests/unit/command.cpp, tests/unit/dynamic_rendering.cpp, tests/unit/dynamic_state.cpp, tests/unit/shader_object.cpp
From https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/7466
This combines (and fixes some subtle bugs) for pipeline and shader object checking of `VK_FORMAT_FEATURE_COLOR_ATTACHMENT_BLEND_BIT`
=> layers: Combine Pipeline and SO blend format feature

layers/vulkan/generated/command_validation.cpp, scripts/generators/command_validation_generator.py
The new ARM DataGraph queue type was missing in the 1.4.319 VulkanObject and was added in 1.4.320 headers
=> scripts: Fix new DataGraph queue type

layers/best_practices/best_practices_validation.h, layers/best_practices/bp_state.cpp, layers/best_practices/bp_state.h, layers/best_practices/bp_synchronization.cpp, layers/core_checks/cc_image_layout.cpp, layers/core_checks/cc_state_tracker.cpp, layers/core_checks/cc_state_tracker.h, layers/core_checks/cc_synchronization.cpp, layers/core_checks/core_validation.h, layers/state_tracker/cmd_buffer_state.cpp, layers/state_tracker/cmd_buffer_state.h, layers/state_tracker/state_tracker.cpp
Move the final `CallRecordCmd` calls out of CoreChecks and now route everything through Command Buffers substate!
=> layers: Move sync to cb substate

scripts/CMakeLists.txt
This allows to build mimalloc dependency with stats system enabled (disabled by default for release builds).
I need this for memory statistics tracking script. Can be useful in general for vvl since mimalloc provides a bunch of memory releated counters (e.g. how many times malloc was called, current, peak and total values for memory counters).
=> scripts: Add VVL_ENABLE_MI_STAT option

layers/sync/sync_commandbuffer.cpp, layers/sync/sync_commandbuffer.h, layers/sync/sync_validation.cpp, layers/sync/sync_validation.h
@artem-lunarg wanted to see what it would be like to try and move some of sync state over to use command buffer substate for recording, happy to try and do more (or leave to you)... but figured we start with some easy ones
=> sync: Move Clears to use CB SubState

layers/best_practices/bp_state.cpp, layers/best_practices/bp_state.h, layers/core_checks/cc_state_tracker.cpp, layers/core_checks/cc_state_tracker.h, layers/state_tracker/cmd_buffer_state.cpp, layers/state_tracker/cmd_buffer_state.h, layers/state_tracker/state_tracker.cpp, layers/sync/sync_commandbuffer.cpp, layers/sync/sync_commandbuffer.h, layers/sync/sync_validation.cpp, layers/sync/sync_validation.h
broken up to 3 commits, just moving the "boring" logic from `sync_validation.cpp` to `sync_commandbuffer.cpp`
=> sync: Move more things to CommandBufferSubState

layers/sync/sync_commandbuffer.cpp, layers/sync/sync_reporting.cpp, tests/unit/sync_val_wsi.cpp
This fixes questionable recommendation to add stage NONE to solve sync problem:
> The current synchronization defines the destination stage mask as VK_PIPELINE_STAGE_2_COLOR_ATTACHMENT_OUTPUT_BIT|VK_PIPELINE_STAGE_2_BOTTOM_OF_PIPE_BIT, but to prevent this hazard, it must include VK_PIPELINE_STAGE_2_NONE.
New version:
> The current synchronization defines the destination stage mask as VK_PIPELINE_STAGE_2_COLOR_ATTACHMENT_OUTPUT_BIT, but layout transition does not synchronize with these stages.
Vulkan insight: If the layout transition is done via an image barrier, consider including VK_PIPELINE_STAGE_2_COLOR_ATTACHMENT_OUTPUT_BIT in srcStageMask. If the transition occurs as part of the render pass begin operation, consider specifying an external subpass dependency (VK_SUBPASS_EXTERNAL) with …
=> sync: Improve layout transition hazard reporting

layers/state_tracker/image_state.cpp, layers/state_tracker/image_state.h, tests/unit/dynamic_rendering.cpp, tests/unit/dynamic_rendering_positive.cpp
Mike pointed out a Zink test we were throwing a false positive
The use of `normalized_subresource_range` is tricky, because it involves calling `NormalizeSubresourceRange` and the "idea" is you do it in `vvl::Image` state with a provided `VkImageSubresourceRange`... the main goal is to really just resolve `VK_REMAINING_ARRAY_LAYERS`
the issue is `maintenance9` is only applied to Image Layout, not to things like `vkCmdBeginRendering`, but we were applying the image layout
=> layers: Fix normalized_subresource_range

layers/core_checks/cc_descriptor.cpp, layers/state_tracker/descriptor_sets.h, tests/unit/descriptor_indexing.cpp, tests/unit/descriptor_indexing_positive.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/10370
1. Provides better hints around using Variable Descriptor Count
2. Adds a hint as discussed in the WG call
3. Moves the logic into the single for-loop
=> layers: Improve Variable Descriptor Count

layers/core_checks/cc_buffer_address.h, layers/core_checks/cc_descriptor.cpp, tests/framework/descriptor_helper.cpp, tests/framework/descriptor_helper.h, tests/unit/descriptor_buffer_positive.cpp
1. Adds more examples for Descriptor Buffer
2. Adds easier way to set `VkDescriptorGetInfoEXT`
3. Fixes some VU error messages found along the way
=> tests: More Descriptor Buffer examples

layers/stateless/sl_buffer.cpp, layers/stateless/sl_image.cpp
noticed from @stefano-bucciarelli-arm in https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/10392#discussion_r2200574187
These comments date some of the **ORIGINAL** validation added 8 years ago... these are just noisy, we the code is basic to understand what it is doing (it is stateless!) and the VUID are there for a reason
=> layers: Remove old redundant comments

tests/unit/sync_val_positive.cpp
Add test that behaves similarly to the scenario from https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/10376.
The sparse resources are not related to the issue and it looks like we do not hit some separate slow path. That's the current performance of general path. Syncval works well when resources are accessed as large ranges of bytes but when access if fine-graned (close to separate bytes) this creates a lot of access ranges and current data structures are not fast enough in this case.
General optimization of syncval will make this faster, but even 3-4x faster syncval (which will bring syncval perf to core checks level in some cases) means that current scenario will be only 3-4x faster. A lot of small memory accesses probably will remain a not good performance case, but will …
=> tests: Add synval performance tests

layers/core_checks/cc_render_pass.cpp, tests/unit/dynamic_rendering.cpp, tests/unit/dynamic_rendering_positive.cpp
pointed out that `VUID-VkRenderingAttachmentInfo-imageView-10780` was giving false positive
while here, reorganized and added better `LogObjectList` to the error message
=> layers: Fix UnifiedImageLayouts flag bug

layers/core_checks/cc_buffer_address.h, layers/core_checks/cc_cmd_buffer.cpp, layers/core_checks/cc_descriptor.cpp, layers/core_checks/cc_device_generated_commands.cpp, layers/core_checks/cc_device_memory.cpp, layers/core_checks/cc_drawdispatch.cpp, layers/core_checks/cc_ray_tracing.cpp, layers/core_checks/core_validation.h, layers/drawdispatch/drawdispatch_vuids.cpp, layers/error_message/unimplementable_validation.h, layers/state_tracker/state_tracker.h, layers/stateless/sl_device_generated_commands.cpp, tests/unit/descriptor_buffer.cpp, tests/unit/device_generated_commands.cpp, tests/unit/ray_tracing.cpp, tests/unit/shader_cooperative_vector.cpp
based on https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/7517
Makes it so any time a `VkDeviceAddress` is passed in we have a single path to check if its a valid VkDeviceAddress... some checks will want additional checks (if the VkBuffer under have certain buffer usages, etc) which can still be done as normal
=> layers: Simplify VkDeviceAddress checks

docs/khronos_validation_layer.md, layers/chassis/dispatch_object_manual.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/10398
So I originally wanted to find a better way to have VVL running, but on `atexit()` we call `vvl::dispatch::FreeAllData()` and now everything is destroyed and there is nothing left.
The 2 times this has been reported are on Linux environments, so hoping adding a `printf` and more documentation helps, but at some level, without completely redoing all the lifetime for chassis (which is a very non-trivial task) and the fact we have no way to even test `atexit` in CI currently, I feel this is best I can do with the limited time I have to look into this issue
=> layers: Provide some help if atexit is used

docs/debug_printf.md, docs/gpu_validation.md, layers/VkLayer_khronos_validation.json.in, layers/layer_options.cpp, layers/vk_layer_settings.txt, tests/unit/gpu_av_positive.cpp
I want to start generating more things from the JSON when it comes to settings, things like
- Validating the type (replace `ValidateLayerSettingsProvided`)
- Adding a way to dump all the setting values
- Generate the vk_layer_settings.txt file
so that adding a new setting is easier... but first, want to get rid of some very old settings I feel are fair game to remove now
=> layers: Remove old deprecated settings

layers/core_checks/cc_copy_blit_resolve.cpp, tests/unit/copy_buffer_image.cpp, tests/unit/copy_buffer_image_positive.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/10425
=> layers: Fix Compressed 2D-to-1D check

scripts/CMakeLists.txt, scripts/known_good.json, scripts/update_deps.py, tests/CMakeLists.txt, tests/framework/layer_validation_tests.h, tests/framework/ray_tracing_objects.cpp, tests/framework/ray_tracing_objects.h, tests/framework/shader_helper.cpp, tests/framework/shader_helper.h, tests/unit/debug_printf_ray_tracing.cpp, tests/unit/gpu_av_buffer_device_address.cpp, tests/unit/gpu_av_buffer_device_address_positive.cpp, tests/unit/gpu_av_descriptor_class_general_buffer.cpp, tests/unit/gpu_av_descriptor_class_general_buffer_positive.cpp, tests/unit/gpu_av_descriptor_indexing.cpp, tests/unit/gpu_av_descriptor_post_process.cpp, tests/unit/gpu_av_descriptor_post_process_positive.cpp
Caveats: Building from source is quite slow (~10 minutes, more than all other dependencies combined), so I opted to download the pre-built binaries instead.
32 bits binaries are not provided, so tests relying on slang shaders will be skipped on such platforms.
EDIT: Too much messing with the build system for now, I gave up on having slang for Mac and Android. For Android I think I am close, I had green github actions but was getting "slang.so not found" errors in our CI.
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/9454
=> tests: Add Slang

layers/core_checks/cc_cmd_buffer_dynamic.cpp, layers/core_checks/cc_drawdispatch.cpp, layers/core_checks/cc_pipeline_graphics.cpp, layers/core_checks/cc_render_pass.cpp, layers/core_checks/core_validation.h, layers/state_tracker/cmd_buffer_state.cpp, layers/state_tracker/cmd_buffer_state.h, layers/state_tracker/last_bound_state.cpp, layers/state_tracker/last_bound_state.h, layers/state_tracker/pipeline_state.h, layers/state_tracker/pipeline_sub_state.h, tests/unit/pipeline.cpp
related to https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/7549
basically `07484` and `02689` are the same, just one is for when `sampleLocationsEnable` is dynamic, but when it was not dynamic, it was not being validated if using dynamic rendering!
=> layers: Combined Dynamic Rendering and RenderPass

layers/state_tracker/last_bound_state.cpp
All access to pipeline_state->ColorBlendState()->pAttachments[i] needs to check that i is within range.
=> Fix crash when index is out of bounds for color attachments

layers/core_checks/cc_wsi.cpp
vkCreateSwapchainKHR validation uses a incorrect variable for 10160 error message. API call:
```
vkCreateSwapchainKHR(device, pCreateInfo, pAllocator, pSwapchain) returns VkResult VK_SUCCESS (0):
device:                         VkDevice = 0x55a30f9aefd0
pCreateInfo:                    const VkSwapchainCreateInfoKHR* = 0x7ffff2bd6c20:
sType:                          VkStructureType = VK_STRUCTURE_TYPE_SWAPCHAIN_CREATE_INFO_KHR (1000001000)
pNext:                          const void* = VkSwapchainPresentModesCreateInfoEXT
flags:                          VkSwapchainCreateFlagsKHR = 0
surface:                        VkSurfaceKHR = 0x55a30f646880
minImageCount:                  uint32_t = 4
imageFormat:                    VkFormat = VK_FORMAT_B8G8R8A8_UNORM (44)
imageColorSpace: …
```
=> layers: Incorrect present mode used in 10160 error message

layers/state_tracker/cmd_buffer_state.cpp, layers/state_tracker/cmd_buffer_state.h, tests/unit/dynamic_state_positive.cpp
Can't have `VK_IMAGE_CREATE_SAMPLE_LOCATIONS_COMPATIBLE_DEPTH_BIT_EXT` with a stencil only format
=> Only check 02689 if format has depth

layers/core_checks/cc_pipeline_graphics.cpp, layers/state_tracker/last_bound_state.cpp, tests/unit/dynamic_rendering_positive.cpp
Follow up of https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/10441 with @ziga-lunarg  test 
I raised https://gitlab.khronos.org/vulkan/vulkan/-/issues/4379 as I am still not sure it is actually allowed to do what we are doing here, but good to have the OOB check regardless
=> layers: Extra dynamicRenderingUnusedAttachments check

layers/core_checks/cc_drawdispatch.cpp, layers/core_checks/core_validation.h, layers/drawdispatch/drawdispatch_vuids.cpp, tests/unit/gpu_av_ray_tracing.cpp, tests/unit/ray_tracing.cpp
Follow up of https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/10400
both `vkCmdTraceRaysIndirectKHR` and `vkCmdTraceRaysIndirect2KHR` were not properly validating the `indirectDeviceAddress`
=> layers: Add missing RTX IndirectDeviceAddress check

layers/core_checks/cc_image.cpp, layers/state_tracker/image_state.cpp, layers/state_tracker/image_state.h, tests/unit/dynamic_rendering.cpp, tests/unit/dynamic_rendering_positive.cpp
This fixes that after normalization we had uint32_max for image view layer count. Also this found issue in one test.
The idea is to preserve the original meaning of layerCount when resource is created. For vvl::Image layerCount is always in array layer units since VkImage can only specify layers when created and depth slices are specified via additional contexts. 
Similarly vvl::ImageView preserves the original meaning of layerCount. If it's in depth slices units then VUIDs works with depth slices units for such views (e.g. VUID-VkImageViewCreateInfo-subresourceRange-02725), so REMAINING_LAYERS constant should be resolved against depth slices, and non-REMAINING_LAYERS remain unchanged (still in depth slices units).
=> layers: Fix ImageView layerCount normalization

layers/core_checks/cc_ray_tracing.cpp, tests/unit/ray_tracing.cpp, tests/unit/ray_tracing_positive.cpp
somehow https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/10465 failed to do the clang-format check
=> layers: Fix clang-format failing on us

BUILD.gn, layers/CMakeLists.txt, layers/best_practices/best_practices_validation.h, layers/best_practices/bp_cmd_buffer_nv.cpp, layers/best_practices/bp_instance_device.cpp, layers/best_practices/bp_state.cpp, layers/best_practices/bp_synchronization.cpp, layers/best_practices/bp_utils.cpp, layers/best_practices/bp_utils.h, layers/containers/subresource_adapter.cpp, layers/state_tracker/image_state.cpp, layers/state_tracker/image_state.h, layers/utils/image_utils.cpp, layers/utils/image_utils.h
This PR is a cleanup and refactor, no new fixes
* Address one cleanup TODO item
* Add `GetEffectiveLevelCount`/`GetEffectiveLayerCount` helpers to expand REMAINING constants
* This touches BP which duplicated subresource range function in three files, so move similar functionality to bp utils
=> layers: Cleanup subresource range functionality

layers/core_checks/cc_wsi.cpp
If `vkGetPhysicalDeviceSurfaceSupportKHR` fails for example with `VK_ERROR_OUT_OF_HOST_MEMORY` then `formats` here will be empty and validation layers will start reporting `VUID-VkSwapchainCreateInfoKHR-imageFormat-01273` for valid formats
=> Fix 01273 false positives

layers/containers/small_vector.h, layers/sync/sync_op.cpp, layers/sync/sync_op.h, layers/sync/sync_validation.cpp, tests/unit/sync_val.cpp, tests/unit/sync_val_positive.cpp, tests/unit/sync_val_video.cpp
While studying syncval barrier code found missing sync2 functionality. Documented some non-trivial parts.
=> sync: Fix execution dependencies for sync2 barriers

layers/sync/sync_op.cpp, layers/sync/sync_op.h, tests/unit/sync_val_positive.cpp
Closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/10520
That's a similar fix we did in other places. The adjusted barrier subresrouce range is then consumed by `ImageRangeGenerator` to generate subresource memory ranges, and that code I did not inspect yet - it has some handling of 3d texture slices and after this PR fixed expansion of REMAINING_LAYERS everything works, but `ImageRangeGenerator` is something to analize more closely later with regard to maintenance9.
=> sync: Fix REMAINING_LAYERS expansion for synval barriers

layers/core_checks/cc_wsi.cpp
Before the message implied that the used create flags were incompatible with VkPresentId2KHR.
=> layers: Improve 10820 message

scripts/generate_spec_error_message.py
`232-1` is a terrible thing to print when it should be `2^32-1`
=> scripts: Keep powerof symbol in message

BUILD.gn, layers/CMakeLists.txt, layers/chassis/chassis_manual.cpp, layers/chassis/dispatch_object.h, layers/vulkan/generated/feature_not_present.cpp, scripts/generate_source.py, scripts/generators/feature_not_present.py
Closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/10472
tested and got
```
Validation Warning: [ WARNING-vkCreateDevice-FeatureNotPresent ] | MessageID = 0x1879e7b2
vkCreateDevice(): returned VK_ERROR_FEATURE_NOT_PRESENT because the following features were not supported on this physical device:
VkPhysicalDeviceFeatures::shaderStorageImageMultisample is not supported
VkPhysicalDeviceFeatures::shaderFloat64 is not supported
VkPhysicalDeviceLineRasterizationFeatures::smoothLines is not supported
VkPhysicalDeviceLineRasterizationFeatures::stippledRectangularLines is not supported
VkPhysicalDeviceLineRasterizationFeatures::stippledSmoothLines is not supported
```
=> layers: Report info on VK_ERROR_FEATURE_NOT_PRESENT

layers/containers/range.h, layers/containers/range_map.h, layers/containers/subresource_adapter.h
The client code used only `keep_both` option. `keep_lower` was used only internally in one place, `keep_upper` was unused. By expanding `split_impl` with specific parameters it gets much simpler and it is straighforward to understand.
This also generates fewer instructions including minus one conditional jump (at least on MSVC) but that's a small bonus and not the goal of this change.
=> sync: Remove range_map SplitOp parameterization

scripts/generators/deprecation_generator.py
`vkEnumerateDeviceLayerProperties` was deprecated during Vulkan 1.0 and will be in the XML next release for deprecation, so preparing the code gen logic now
=> scripts: Handle Vulkan1.0 deprecation

layers/core_checks/cc_descriptor.cpp, layers/state_tracker/descriptor_sets.cpp, layers/utils/vk_struct_compare.cpp, tests/unit/descriptors.cpp, tests/unit/descriptors_positive.cpp
Don't merge until we agree on https://gitlab.khronos.org/vulkan/vulkan/-/issues/4415
From https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/10098
`pImmutableSamplers` pointers can be different as long as the `VkSampler` under them are the same handle
=> layers: Check pImmutableSamplers handles

layers/containers/range_map.h, layers/sync/sync_access_context.cpp, layers/sync/sync_access_context.h, layers/sync/sync_common.h, layers/sync/sync_op.cpp
Splits functors into more independent types as preparation for pending barriers rework.
=> sync: Misc refactor of barrier functors

tests/CMakeLists.txt
not sure why we are running `chmod +x` on a shared library and also why we have 2 redundant log messages every build
=> build: Remove chmod of slang

layers/VkLayer_khronos_validation.json.in, layers/core_checks/cc_shader_object.cpp, layers/core_checks/cc_spirv.cpp, layers/core_checks/core_validation.h, layers/layer_options.cpp, layers/layer_options.h, layers/state_tracker/pipeline_library_state.cpp, layers/state_tracker/pipeline_state.cpp, layers/state_tracker/shader_module.cpp, layers/state_tracker/shader_module.h, layers/state_tracker/state_tracker.cpp, layers/stateless/sl_spirv.cpp, layers/stateless/sl_spirv.h, tests/unit/debug_printf.cpp, tests/unit/debug_printf_ray_tracing.cpp, tests/unit/pipeline_positive.cpp, tests/unit/shader_object_positive.cpp
https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/10566 but with fixes to handle GPU-AV/DebugPrintf and also passing shader via GPL or inlined with Maintenance5
=> layers: Skip all SPIR-V processing when shader validation is disabled

layers/core_checks/cc_shader_object.cpp, layers/core_checks/cc_spirv.cpp, layers/core_checks/core_validation.h
I realized ShaderObject falls inbetween `vkCreateShaderModule` and `vkCreateGraphicsPipeline`
- Like `vkCreateShaderModule` we need to parse/store the SPIR-V
- Like `vkCreateGraphicsPipeline` we have descriptor set layout information to validate
This moves the "Validate" to the `PreCallRecord` time (we do this with `vkCreateShaderModule` as well) so we only spend the cost of parsing the SPIR-V once!!
=> layers: Only parse SPIR-V once for ShaderObject

layers/gpuav/spirv/descriptor_indexing_oob_pass.cpp, layers/gpuav/spirv/module.cpp, layers/gpuav/spirv/type_manager.cpp, layers/gpuav/spirv/type_manager.h
hit an `OpUndef` in a fossilize trace, need to handle it, still not sure if the spir-v was legal or not (so didn't add a test)
=> gpuav: Handle OpUndef on a OpSampledImage

layers/state_tracker/descriptor_sets.cpp, layers/state_tracker/descriptor_sets.h
Friday bonus explanation because initially it was confusing:
In the header file the vvl namespace scopes the entire header file, and all definitions there are automatically put into vvl namespace. In the implementation file the convention is to prefix each definition with a namespace. If we just move functions to cpp file this creates symbols without vvl:: in its name.  Then all users that use definitions from *.h file use the name with vvl:: prefix but the object (function) with that name does not exist and the linker gives up looking for it.
=> layers: Move implementation to cpp

layers/core_checks/cc_buffer_address.h, layers/error_message/unimplementable_validation.h, layers/stateless/sl_ray_tracing.cpp, layers/vulkan/generated/stateless_validation_helper.cpp, scripts/generators/stateless_validation_helper_generator.py, tests/unit/device_generated_commands.cpp, tests/unit/ray_tracing.cpp, tests/unit/ray_tracing_pipeline.cpp, tests/unit/ray_tracing_positive.cpp
(Will wait until https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/7601 is merged otherwise this change will have 3 spots with false positives due to a vk.xml bug)
This will now validate the newly added `"... must be a valid VkDeviceAddress value"` implicit VUs added to the spec
=> layers: Stateless check null VkDeviceAddress

layers/core_checks/cc_device.cpp, layers/core_checks/cc_spirv.cpp, layers/core_checks/core_validation.h, layers/utils/shader_utils.cpp, layers/utils/shader_utils.h
The interaction between VVL and spirv-val can be a mystery for many. We pass in various arguments into `spirv-val` that can be reproduced with command line options, but are not obvious. This change adds at the bottom of `spirv-val` errors the command that can be rerun to reproduce without VVL involved (also helps when the vulkan version doesn't match up with the spirv version)
=> layers: Provide spirv-val command to reproduce

layers/core_checks/cc_copy_blit_resolve.cpp, layers/core_checks/core_validation.h, layers/error_message/error_strings.h
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/10620
Fixed and new error message is MUCH nicer
> Validation Error: [ VUID-vkCmdCopyBufferToImage2-imageOffset-07738 ] | MessageID = 0x8a22c271
>
> vkCmdCopyBufferToImage2(): pCopyBufferToImageInfo->pRegions[0].imageExtent (width = 320, height = 148, depth = 1) is invalid with this command buffer's queue family minImageTransferGranularity (width = 16, height = 16, depth = 8) for copying to/from VkImage 0x40000000004 (VK_FORMAT_BC1_RGBA_SRGB_BLOCK) because both:
>
> 1) The image is in texel blocks of size (4x4x1) so the texel block extent of (width = 80, height = 37, depth = 1) is not an even integer multiple of minImageTransferGranularity.
>
> 2) The extent plus the offset (x = 0, y = 16, z = 0) is (320x164x1) which is …
=> layers: Fix minImageTransferGranularity for compressed images

scripts/known_good.json
We updated mimcalloc from `2.*` to `3.*` in https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/10251 to match SPIR-V tools, so picking `3.0.3` over the latest `3.1.5` was due to that
but since released in the latest SDK, we have found the `3.0.3` version had issues where when you debug with GDB you will get leaked virtual allocation (https://vulkan.lunarg.com/issue/view/6891df0a75be2560b8b4cb89 https://vulkan.lunarg.com/issue/view/68606660758e2e78d0e00387)
This updates to 3.1.5 which we found doesn't have these issues
update - seems SPIR-V Tools just grabs the [latest version anyway](https://github.com/KhronosGroup/SPIRV-Tools/commit/c2977ef0a6e2c36bcb0755d9ac17ee8f760199a4) so this is even more justified to do
=> scripts: Update to latest mimalloc

tests/unit/descriptor_buffer.cpp
ANV only has a `maxSamplerDescriptorBufferBindings` of `1` and these 2 tests were failing
=> tests: Check for maxSamplerDescriptorBufferBindings

layers/core_checks/cc_cmd_buffer_dynamic.cpp, layers/error_message/error_strings.h, layers/state_tracker/cmd_buffer_state.cpp
From discussions in [KhronosGroup/Vulkan-Docs#2565](https://github.com/KhronosGroup/Vulkan-Docs/issues/2565) - spec change https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/7640
Note: CTS fails the new validations without https://github.com/KhronosGroup/VK-GL-CTS/pull/541 in case that affects how you want to order merges
=> layers: Fix dynamic render local read draw VUs

layers/state_tracker/cmd_buffer_state.h, tests/unit/dynamic_rendering_positive.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/10661
`IsDepthOrStencil()` is used in 2 spots, both don't actually want the Resolve variation (and why we have a `IsResolve()`)
=> layers: Fix dynamic raster sample for ds resolve

layers/gpuav/instrumentation/gpuav_shader_instrumentor.cpp, layers/state_tracker/shader_module.h
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/10675 - if two shader modules were referenced by two PSOs at the same time and being instrumented it could cause a crash with fine-grained locking enabled. Fix by carrying a mutex in the shader module and locking it when modifying.
Just @danginsburg fix (https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/10684) but with added comment and fixed commit message to make CI happy
=> gpuav: Lock instrumentation to single thread

CMakeLists.txt, scripts/generate_source.py
This PR does two things: Codegen the 'current generated version' into CMake's `project()` field, and use that version to specify the 'minimum VulkanHeader's version required' in `find_package`. This turns the cryptic compile errors from compiling with too-old Vulkan-Headers into a clear build failure with a specific error message.
Example error message
```
CMake Error at CMakeLists.txt:55 (find_package):
Could not find a configuration file for package "VulkanHeaders" that is
compatible with requested version "1.4.326".
The following configuration files were considered but not accepted:
/home/cdgiessen/lunarg/Vulkan-Loader/external/Debug/64/Vulkan-Headers/build/install/share/cmake/VulkanHeaders/VulkanHeadersConfig.cmake, version: 1.4.325
```
=> Version check vulkan headers

layers/sync/sync_access_context.cpp, layers/sync/sync_access_context.h, layers/sync/sync_access_state.cpp, layers/sync/sync_access_state.h, layers/sync/sync_op.cpp, layers/sync/sync_op.h
This unifies handling of barrier scopes - `UntaggedScopeOps`, `QueueScopeOps` and `EventScopeOps` are gone.
`ApplyBarrier()` was untemplated and is a regular function now. Templated type is replaced with `BarrierScope` parameter.
Improved naming of various `InScop`e methods, since the previous versions were not consistent in what they describe.
=> sync: Introduce BarrierScope

layers/core_checks/cc_pipeline_graphics.cpp, tests/unit/graphics_library_positive.cpp
From https://gitlab.khronos.org/vulkan/vulkan/-/issues/4433, GPL messages can be awful to parse (thanks to the spec attempt to word smith it all)
The error message is here to help users for GPL with Mesh Shading
New error message 
```
vkCreateGraphicsPipelines(): pCreateInfos[0] pVertexInputState and pInputAssemblyState are both NULL so this is an invalid Vertex Input State.
pVertexInputState can be ignored with VK_DYNAMIC_STATE_VERTEX_INPUT_EXT
pInputAssemblyState can be ignored with VK_DYNAMIC_STATE_PRIMITIVE_RESTART_ENABLE, VK_DYNAMIC_STATE_PRIMITIVE_TOPOLOGY, and dynamicPrimitiveTopologyUnrestricted set to VK_TRUE
If there is a mesh stage, these are also ignored, but the Vertex Input library can just be skipped if creating a mesh pipeline.
```
=> layers: Improve Mesh GPL error message

layers/sync/sync_access_context.h, layers/sync/sync_op.cpp, layers/sync/sync_renderpass.cpp
This uses `PendingBarriers` object to collect pending barriers for events.
This is a follow up to https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/10639 which did the same for pipeline barriers. The remaining part is to update render pass and layout transition code.
=> sync: Use PendingBarriers for events

layers/sync/sync_access_context.cpp, layers/sync/sync_access_context.h, layers/sync/sync_renderpass.cpp
Also use `SubpassBarrierTrackback` name directly instead of `TrackBack` alias which sounds a bit cryptic
=> sync: Untemplate and cleanup SubpassBarrierTrackback

layers/core_checks/cc_shader_interface.cpp
Was noticed that the RenderPass version checks, but we didn't for dynamic rendering
=> layers: Add IsRasterizationDisabled check to FS Output

layers/core_checks/cc_render_pass.cpp
Otherwise this code:
```cpp
m_command_buffer.Begin();
vk::CmdBeginRenderingKHR(m_command_buffer, &rendering_info);
//vk::CmdEndRenderingKHR(m_command_buffer);
m_command_buffer.End();
```
Will get you this error:
Validation Error: [ VUID-vkEndCommandBuffer-commandBuffer-00060 ] | MessageID = 0x4d08326d
vkEndCommandBuffer(): It is invalid to issue this call inside an active VkRenderPass 0x0.
The Vulkan spec states: If commandBuffer is a primary command buffer, there must not be an active render pass instance (https://docs.vulkan.org/spec/latest/chapters/cmdbuffers.html#VUID-vkEndCommandBuffer-commandBuffer-00060)
Objects: 1
[0] VkCommandBuffer 0x26db64925e0
which is not the best
=> layers: Improve err msg for dynamic rendering

layers/sync/sync_access_state.h
Reduces default capacity of `ResourceAccessState::ReadStates` small_vector from 3 to 2.
In most cases apps use 1 read access per access object.
Sometimes 2 read accesses are allocated (happens in doom capture in around 5-10% of cases). 
More than 2 is posible but in practice less common (I did not see in the captures/games that I test).
Also tested with capacity 1. Memory wise it's obviously better than 2 (most apps need 1 element). But even for the apps that need 2 read accesses and need to allocate (doom capture), this still adds 2-3% speed up due ot reduced memory traffic. Still decided to go with 2 for now and test it for some time.
`ResourceAccessState` size reduction: 432 bytes -> 384 bytres.
Small performance increase ~2%. Yesterdays removal of pending barrier state also gave …
=> sync: Reduce ReadStates initial capacity from 3 to 2

layers/chassis/dispatch_object_manual.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/10659 using @pborsutzki suggested fix
=> layers: Fix WriteLockGuards on atexit

layers/gpuav/core/gpuav_settings.h, layers/gpuav/core/gpuav_setup.cpp, layers/layer_options.cpp
allows those who have `VK_EXT_descriptor_buffer` turned on always (like CTS) but want to still use DebugPrintf
=> gpuav: Allow a bypass for Descriptor Buffer in short term

tests/unit/copy_buffer_image.cpp, tests/unit/copy_buffer_image_positive.cpp
Use a format that requires `VK_FORMAT_FEATURE_2_COPY_IMAGE_INDIRECT_DST_BIT_KHR`
=> tests: Use required supported formats

layers/core_checks/cc_pipeline_graphics.cpp, tests/unit/secondary_command_buffer.cpp
hot fix to until we figure out if  https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/10761 is an ANGLE bug or Spec ambiguity (rather side on no false positive side)
=> layers: Temp relax of VU 10582

layers/core_checks/cc_pipeline_graphics.cpp, layers/core_checks/core_validation.h, tests/unit/dynamic_state.cpp, tests/unit/vertex_input.cpp, tests/unit/vertex_input_positive.cpp
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/10771
(follow up is to fix this to support shader object)
=> layers: Fix false positive for vertex input with no Location

tests/unit/descriptor_buffer_positive.cpp, tests/unit/shader_object_positive.cpp
@ziga-lunarg so `VK_PIPELINE_BIND_POINT_GRAPHICS`  vs `VK_PIPELINE_BIND_POINT_COMPUTE` is one of the **many** things we are missing validation on (found with asserts in the mesa driver)
=> tests: Fix DescriptorBuffer tests

layers/core_checks/cc_queue.cpp, layers/state_tracker/cmd_buffer_state.cpp, layers/state_tracker/cmd_buffer_state.h, tests/framework/binding.h, tests/unit/dynamic_rendering.cpp
This fixes error reporting in the scenario from the test
That's preparation for https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/10787
=> layers: Update tracking of render pass suspend state

tests/unit/descriptors_positive.cpp
this test was hitting
```
Validation Warning: [ WARNING-VkDescriptorSetAllocateInfo-descriptorCount ] | MessageID = 0x1ed8505a
vkAllocateDescriptorSets(): Trying to allocate 2 of VK_DESCRIPTOR_TYPE_ACCELERATION_STRUCTURE_KHR descriptors from VkDescriptorPool 0x30000000003, but this pool only has a total of 1 descriptors for this type so you will likely get VK_ERROR_OUT_OF_POOL_MEMORY_KHR. While this might succeed on some implementations, it will fail on others.
Where VK_DESCRIPTOR_TYPE_ACCELERATION_STRUCTURE_KHR is found in the pool:
pPoolSizes[0].descriptorCount = 1
Where the allocation are being requested:
pSetLayouts[0]::pBindings[1].descriptorCount = 1
pSetLayouts[1]::pBindings[1].descriptorCount = 1
```
and failing on me (took looking at driver code to catch)
=> tests: Fix CopyAccelerationStructureMutableDescriptors

layers/gpuav/instrumentation/gpuav_shader_instrumentor.cpp, tests/unit/gpu_av_buffer_device_address.cpp, tests/unit/gpu_av_positive.cpp
Closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/10774
A library can itself be composed of other libraries, make sure this case is handled
=> gpuav: For GPL, fix handling of sub libraries
